Add provider constraint
mullvad/mullvadvpn-app pull request #2018
Opened 2020-08-24 10:01 UTC by dlon

These changes introduce a constraint to restrict the relay selector to choosing servers matching a given hosting provider. These CLI commands were added:

`mullvad relay set provider <provider>`
`mullvad bridge set provider <provider>`

`mullvad relay list` and `mullvad bridge list` were also updated to include the hosting provider of each server.

2020-08-24 11:24 UTC, faern reviewed
I won't review the code in detail. Just checked the changelog and how it's presented towards users.

> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2018#-:-MFVCYjt-VsxVxrDGMrO:b-9vwzj3)* status: 1 of 11 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-cli/src/location.rs, line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2018#-MFVA_2C2xa2zNl09CCT:-MFVA_2C2xa2zNl09CCU:b-95f7du) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8080b3499a1dbdc30860f7f944d0391006daa757/mullvad-cli/src/location.rs#L78)):*
> ```Rust
> pub fn format_provider(provider: &str) -> String {
>     if !provider.is_empty() {
>         format!("provider {}", provider)
> ```

Does this read out in a nice way? "provider M247", "provider iRegister"?. With this wording I think it would need a colon: "provider: M247". But I think it might read out even better if written as what the `list` command does: "hosted by M247". And the else clause maybe "hosted by anyone"?


<!-- Sent from Reviewable.io -->

2020-08-24 13:44 UTC, pinkisemils requested changes
> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2018)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[mullvad-cli/src/cmds/bridge.rs, line 208 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2018#-MFVhDawBEpLvZjXepiQ:-MFVhDax-nkDBkim4zhQ:b-b161v9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8080b3499a1dbdc30860f7f944d0391006daa757/mullvad-cli/src/cmds/bridge.rs#L208)):*
> ```Rust
>     async fn handle_set_bridge_provider(matches: &clap::ArgMatches<'_>) -> Result<()> {
>         let new_provider =
>             value_t!(matches.value_of("provider"), String).unwrap_or_else(|e| e.exit());
> ```

You could use the `value_t_or_exit!` [macro]([https://docs.rs/clap/2.33.3/clap/macro.value_t_or_exit.html) here, could you not?


<!-- Sent from Reviewable.io -->

2020-08-24 13:49 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2018)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[mullvad-cli/src/cmds/bridge.rs, line 208 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2018#-MFVhDawBEpLvZjXepiQ:-MFVieoO534MlbJ-MJh4:b5j7y6v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8080b3499a1dbdc30860f7f944d0391006daa757/mullvad-cli/src/cmds/bridge.rs#L208)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

You could use the `value_t_or_exit!` [macro]([https://docs.rs/clap/2.33.3/clap/macro.value_t_or_exit.html) here, could you not?
</blockquote></details>

Apparently, trying to link nicely in markdown is not allowed here - https://docs.rs/clap/2.33.3/clap/macro.value_t_or_exit.html


<!-- Sent from Reviewable.io -->

2020-08-24 14:19 UTC, pinkisemils reviewed
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2018)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2020-08-24 14:31 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2018)* status: all files reviewed, 2 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[mullvad-cli/src/location.rs, line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2018#-MFVA_2C2xa2zNl09CCT:-MFVretN90Utt4MZLZEo:b4oms5i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8080b3499a1dbdc30860f7f944d0391006daa757/mullvad-cli/src/location.rs#L78)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Does this read out in a nice way? "provider M247", "provider iRegister"?. With this wording I think it would need a colon: "provider: M247". But I think it might read out even better if written as what the `list` command does: "hosted by M247". And the else clause maybe "hosted by anyone"?
</blockquote></details>

`mullvad relay get` currently outputs something like this:
```
Current constraints: WireGuard over any port in city got, se using any provider
...
Current constraints: WireGuard over any port in city got, se using provider 31173
```
`relay list` does show "hosted by...":
```
	Secaucus, NJ (uyk) @ 40.78954°N, -74.05650°W
		us-uyk-001 (23.226.131.130) - OpenVPN, hosted by Quadranet
		us-uyk-002 (23.226.131.154) - OpenVPN, hosted by Quadranet
```


<!-- Sent from Reviewable.io -->

2020-08-24 15:42 UTC, pinkisemils approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2018)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2020-08-25 10:50 UTC, pinkisemils approved these changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2018)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2020-08-25 12:26 UTC, faern approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2018)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[mullvad-cli/src/location.rs, line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2018#-MFVA_2C2xa2zNl09CCT:-MF__HmD51_ejDb9wtQC:b-5g592c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8080b3499a1dbdc30860f7f944d0391006daa757/mullvad-cli/src/location.rs#L78)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`mullvad relay get` currently outputs something like this:
```
Current constraints: WireGuard over any port in city got, se using any provider
...
Current constraints: WireGuard over any port in city got, se using provider 31173
```
`relay list` does show "hosted by...":
```
	Secaucus, NJ (uyk) @ 40.78954°N, -74.05650°W
		us-uyk-001 (23.226.131.130) - OpenVPN, hosted by Quadranet
		us-uyk-002 (23.226.131.154) - OpenVPN, hosted by Quadranet
```
</blockquote></details>

It's fine :+1:


<!-- Sent from Reviewable.io -->

2020-08-25 12:55 UTC, pinkisemils approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2018)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-25 13:55 UTC, merged