Linux use wg kernel module
mullvad/mullvadvpn-app pull request #2038
Opened 2020-08-26 16:08 UTC by pinkisemils

Add support to the daemon to use the WireGuard kernel implementation on Linux.

This is achieved by just using a netlink socket to query the system for the WireGuard neltink message type (it's a different value on different distributions), and then send various messages to create and configure a WireGuard interface. Some of the messages that are being sent and received don't have support in the libraries we're using, so I've implemented that in `talpid-core`. The Netlink library also has a nasty habit of tying a netlink connection to a message type - whilst this could be worked around, for simplicity's sake the new code spawns 3 netlink connections  every time it connects successfully.

2020-08-27 11:03 UTC, dlon requested changes
> Reviewed 4 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038)* status: 4 of 13 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs, line 210 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFjVN8K1Gt5vX0LTryA:-MFjVN8K1Gt5vX0LTryB:b-xellrc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38f4748fb3d1207a57c0cd92a86c6181797dc87e/talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs#L210)):*
> ```Rust
>         let message_type = Self::get_wireguard_message_type().await?;
>         let (conn, wg_handle, _messages) =
>             netlink_proto::new_connection(Protocol::Generic).expect("handle error correctly");
> ```

Should `expect` be used here?
___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs, line 225 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFjVEHa2JlxLif1QEgZ:-MFjVEHa2JlxLif1QEg_:b-jw5rjm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38f4748fb3d1207a57c0cd92a86c6181797dc87e/talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs#L225)):*
> ```Rust
>     async fn get_wireguard_message_type() -> Result<u16, Error> {
>         let (conn, mut handle, _messages) =
>             netlink_proto::new_connection(Protocol::Generic).unwrap();
> ```

Should `unwrap` be used here?


<!-- Sent from Reviewable.io -->

2020-08-27 14:14 UTC, dlon requested changes
> Reviewed 5 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038)* status: 9 of 13 files reviewed, 6 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/mod.rs, line 141 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFk7DsK9A8ACz_Zw0eo:-MFk7DsL8RHGX1_0_J-n:b-gfnqka) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38f4748fb3d1207a57c0cd92a86c6181797dc87e/talpid-core/src/tunnel/wireguard/mod.rs#L141)):*
> ```Rust
>         route_manager: &mut routing::RouteManager,
>     ) -> Result<Box<dyn Tunnel>> {
>         match wireguard_kernel::KernelTunnel::new(route_manager.runtime_handle(), config) {
> ```

You should be able to move this `#[cfg(target_os = "linux")]` condition to above this `match` expression, and get rid of the duplicate `WgGoTunnel::start_tunnel` call above.
___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs, line 258 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFk9j9c0Os4Ye0Im8Lp:-MFk9j9c0Os4Ye0Im8Lq:b-myertt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38f4748fb3d1207a57c0cd92a86c6181797dc87e/talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs#L258)):*
According to `man rtnetlink.7`:
> ifi_change is reserved for future use and should be always set to 0xFFFFFFFF.
___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs, line 279 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFk7uvNBGmtUCQAULRm:-MFk7uvNBGmtUCQAULRn:b-rjs58d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38f4748fb3d1207a57c0cd92a86c6181797dc87e/talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs#L279)):*
> ```Rust
>         while let Some(response_message) = response.next().await {
>             if let NetlinkPayload::Error(err) = response_message.payload {
>                 // if the device exists, verify that it's a wireguard device
> ```

Have you verified that `EEXIST` is only returned if the existing interface is a WG device? It looks like it might return this for any type of link. Since `NLM_F_REPLACE` is used, won't it simply replace any existing link anyway?
___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs, line 360 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFkDjhZ9SOJ3XLbHAmd:-MFkDjhZ9SOJ3XLbHAme:bmjv92z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38f4748fb3d1207a57c0cd92a86c6181797dc87e/talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs#L360)):*
> ```Rust
>                 NetlinkPayload::InnerMessage(inner) => Ok(inner),
>                 NetlinkPayload::Error(err) => {
>                     if err.code == -19 {
> ```

This should probably be replaced with a named `ENODEV` constant.


<!-- Sent from Reviewable.io -->

2020-08-27 15:41 UTC, dlon reviewed
> Reviewed 2 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038)* status: 11 of 13 files reviewed, 7 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs, line 279 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFk7uvNBGmtUCQAULRm:-MFkH1JI92JOMTAja12M:bffhktp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38f4748fb3d1207a57c0cd92a86c6181797dc87e/talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs#L279)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Have you verified that `EEXIST` is only returned if the existing interface is a WG device? It looks like it might return this for any type of link. Since `NLM_F_REPLACE` is used, won't it simply replace any existing link anyway?
</blockquote></details>

You might have to add the `NLM_F_EXCL` flag for this error to be returned, if what I'm reading is up-to-date.
___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs, line 322 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFkJMFr-LKWKzq2ZgPQ:-MFkJMFr-LKWKzq2ZgPR:bron40n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38f4748fb3d1207a57c0cd92a86c6181797dc87e/talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs#L322)):*
> ```Rust
> 
>         let mut request = NetlinkMessage::from(RtnlMessage::DelLink(link_message));
>         request.header.flags = NLM_F_REQUEST | NLM_F_ACK | NLM_F_EXCL | NLM_F_CREATE;
> ```

`NLM_F_CREATE` doesn't seem to make sense here.
___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/wg_message.rs, line 841 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFkTQs62qRQVfEjDrox:-MFkTQs62qRQVfEjDroy:bh65hpp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38f4748fb3d1207a57c0cd92a86c6181797dc87e/talpid-core/src/tunnel/wireguard/wireguard_kernel/wg_message.rs#L841)):*
> ```Rust
> 
>         DeviceMessage {
>             command: WG_CMD_GET_DEVICE,
> ```

Shouldn't this be `WG_CMD_SET_DEVICE`? I see that you re-assign this in the test below, but I'm not sure why it's initialized to `WG_CMD_GET_DEVICE`.


<!-- Sent from Reviewable.io -->

2020-08-28 09:17 UTC, dlon reviewed
> Reviewed 1 of 13 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[CHANGELOG.md, line 51 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFoGwvrEXC2NRjg2Gtr:-MFoGwvrEXC2NRjg2Gts:b-9sx1jh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dce1e44279f3ba1040b0e837dd165121be05b6b1/CHANGELOG.md#L51)):*
> ```Markdown
> 
> #### Linux
> - Add support for WireGuard's kernel module if it's loaded.
> ```

Minor: This should probably be under "Added".


<!-- Sent from Reviewable.io -->

2020-08-28 09:29 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs, line 158 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFoNItD25v3w1VX3JKX:-MFoNItD25v3w1VX3JKY:b-tw3943) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dce1e44279f3ba1040b0e837dd165121be05b6b1/talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs#L158)):*
> ```Rust
> 
>     fn stop(self: Box<Self>) -> std::result::Result<(), TunnelError> {
>         let mut netlink_connections = self.netlink_connections.clone();
> ```

Would this work and avoid the cloning?

```rust
let KernelTunnel {
    netlink_connections,
    interface_index,
    tokio_handle,
    ..
} = self;
```


<!-- Sent from Reviewable.io -->

2020-08-28 09:46 UTC, dlon approved these changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2020-08-31 18:03 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038)* status: 8 of 18 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[CHANGELOG.md, line 51 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFoGwvrEXC2NRjg2Gtr:-MG4NGZT6Ji1-7FgQcO5:b-drw486) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dce1e44279f3ba1040b0e837dd165121be05b6b1/CHANGELOG.md#L51)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Minor: This should probably be under "Added".
</blockquote></details>

All other entries start with simple present tense.
___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs, line 210 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFjVN8K1Gt5vX0LTryA:-MFlW9L34nvMH4nbLLi4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38f4748fb3d1207a57c0cd92a86c6181797dc87e/talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs#L210)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should `expect` be used here?
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs, line 225 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFjVEHa2JlxLif1QEgZ:-MFlW9riAGXl0EjFhW3Q:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38f4748fb3d1207a57c0cd92a86c6181797dc87e/talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs#L225)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should `unwrap` be used here?
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs, line 258 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFk9j9c0Os4Ye0Im8Lp:-MFkK1421Ncf0rQ_nw3-:bdxegvy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38f4748fb3d1207a57c0cd92a86c6181797dc87e/talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs#L258)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

According to `man rtnetlink.7`:
> ifi_change is reserved for future use and should be always set to 0xFFFFFFFF.
</blockquote></details>

You are correct. I was only looking at the `rtnetlink` crate - https://github.com/little-dude/netlink/blob/master/rtnetlink/src/link/set.rs#L54 But this isn't required, at least in my testing.
___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs, line 279 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFk7uvNBGmtUCQAULRm:-MFkNLgn29CxvCouXAeX:b-5ewg7n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38f4748fb3d1207a57c0cd92a86c6181797dc87e/talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs#L279)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You might have to add the `NLM_F_EXCL` flag for this error to be returned, if what I'm reading is up-to-date.
</blockquote></details>

In case a different type of device exists with the same name, the it isn't replaced. But it also doesn't fail. The tunnel creation then fails when the WireGuard config fails to be set. My original intention was to be tolerant of cases where the device already existed because the daemon crashed from a previous run. In that sense, this will fail still if a non-wireguard link exists with the same name, but if there exists an appropriately named WireGuard device, the error will still be returned.

As for this error being returned at all without `NLM_F_EXCL`, I was under the same impression. But adding a `else { panic!("documentation lies"); }` proved me wrong :disappointed: 
___
*[talpid-core/src/tunnel/wireguard/wireguard_kernel/wg_message.rs, line 841 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFkTQs62qRQVfEjDrox:-MFlYKbt3ke6F5NOROVK:b-p0p18y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38f4748fb3d1207a57c0cd92a86c6181797dc87e/talpid-core/src/tunnel/wireguard/wireguard_kernel/wg_message.rs#L841)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Shouldn't this be `WG_CMD_SET_DEVICE`? I see that you re-assign this in the test below, but I'm not sure why it's initialized to `WG_CMD_GET_DEVICE`.
</blockquote></details>

It should be.


<!-- Sent from Reviewable.io -->

2020-08-31 18:46 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038)* status: 8 of 18 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[CHANGELOG.md, line 51 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFoGwvrEXC2NRjg2Gtr:-MG4pddc4j6I-YsNb-oB:b-eae5f6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dce1e44279f3ba1040b0e837dd165121be05b6b1/CHANGELOG.md#L51)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

All other entries start with simple present tense.
</blockquote></details>

Most importantly, it should be added under `[Unreleased]` and not `[2020.6-beta2]`.

I think what David means is that it should be added unde `### Added` and not `### Fixed`


<!-- Sent from Reviewable.io -->

2020-08-31 19:19 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038)* status: 8 of 18 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[CHANGELOG.md, line 51 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MFoGwvrEXC2NRjg2Gtr:-MG4xJxq4JjoRHOBUMMQ:b-5hcf8m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dce1e44279f3ba1040b0e837dd165121be05b6b1/CHANGELOG.md#L51)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Most importantly, it should be added under `[Unreleased]` and not `[2020.6-beta2]`.

I think what David means is that it should be added unde `### Added` and not `### Fixed`
</blockquote></details>

Ah, that is fair. That should be fixed now.


<!-- Sent from Reviewable.io -->

2020-09-01 08:01 UTC, dlon approved these changes
> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2020-09-01 08:33 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[CHANGELOG.md, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MG7mnV_4ga5zM3YqAir:-MG7mnV_4ga5zM3YqAis:b-xvzrhf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af02acf0cf059ac4eb109ba960538db77f3bfa6d/CHANGELOG.md#L60)):*
> ```Markdown
> - Fix crash that could happen when leaving the Select Location screen.
> - Don't show out-of-time notification for newly created accounts.
> ```

Nitpicky. But please don't edit the changelog for older releases. There should be two blank lines between releases and this now becomes just one. Plus my command for figuring out if we changed the changelog in only the right places will trigger on this.


<!-- Sent from Reviewable.io -->

2020-09-01 10:17 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[CHANGELOG.md, line 60 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MG7mnV_4ga5zM3YqAir:-MG89uF925pdR9dzcyLK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af02acf0cf059ac4eb109ba960538db77f3bfa6d/CHANGELOG.md#L60)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nitpicky. But please don't edit the changelog for older releases. There should be two blank lines between releases and this now becomes just one. Plus my command for figuring out if we changed the changelog in only the right places will trigger on this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-01 21:20 UTC, dlon requested changes
> Reviewed 15 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/mine, line 1 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MGAXGHL9TKW8yRyDZ7G:-MGAXGHL9TKW8yRyDZ7H:b-ehj1y3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22d597b77711a9398204606015fc1f66f3b20981/talpid-core/mine#L1)):*
> ```
> x01 x01 x00 x00 x24 x00 x03 x00 x38 x47 xf4 xad x65 xdf x55 x16 xab xaf x0f x27 x35 xb4 xc1 xc6 x49 x37 x35 x3b xbc x1a x34 x4a xad xb3 x16 xd5 xa1 x47 xfc x7d x06 x00 x06 x00 x6c xca x00 x00 xdc x00 x08 x80 x6c x00 x00 x80 x24 x00 x01 x00 x20 xe0 x44 x05 x17 x88 x67 xe5 xce x3b x22 xe7 xd7 x8b xd6 xec x50 x51 xbb x07 x9a xc5 xfb x24 xab x9c x30 x49 x91 x2f x86 x36 x08 x00 x03 x00 x00 x00 x00 x00 x08 x00 x0a x00 x01 x00 x00 x00 x14 x00 x04 x00 x02 x00 x26 x45 xc0 xa8 x28 x01 x00 x00 x00 x00 x00 x00 x00 x00 x20 x00 x09 x80 x1c x00 x00 x80 x05 x00 x03 x00 x20 x00 x00 x00 x06 x00 x01 x00 x02 x00 x00 x00 x08 x00 x02 x00 xc0 xa8 x27 x01 x6c x00 x00 x80 x24 x00 x01 x00 xf4 x1c xce x0c x4f x24 x58 xb7 xc2 x9d x36 x26 x36 xb7 x7f x20 x8e x18 xfb x9e xd9 x38 x0c x92 xd0 x15 x84 x9d xa2 x44 x02 x2c x08 x00 x03 x00 x00 x00 x00 x00 x08 x00 x0a x00 x01 x00 x00 x00 x14 x00 x04 x00 x02 x00 x26 x45 xc0 xa8 x28 x02 x00 x00 x00 x00 x00 x00 x00 x00 x20 x00 x09 x80 x1c x00 x00 x80 x05 x00 x03 x00 x20 x00 x00 x00 x06 x00 x01 x00 x02 x00 x00 x00 x08 x00 x02 x00 xc0 xa8 x27 x02 x0c x00 x02 x00 x77 x67 x2d x74 x65 x73 x74 x00 x08 x00 x05 x00 x01 x00 x00 x00
> ```

Was this included by accident?
___
*[talpid-core/src/dns/linux/network_manager.rs, line 218 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MGAOe5E18p3buLF91Lp:-MGAOe5FABcdJO9wND7e:b-uqt99w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22d597b77711a9398204606015fc1f66f3b20981/talpid-core/src/dns/linux/network_manager.rs#L218)):*
> ```Rust
>             ipv6_settings.insert("routes", Variant(Box::new(device_routes6)));
>             ipv6_settings.insert("route-data", Variant(Box::new(device_route6_data)));
>             ipv6_settings.insert("addresses", Variant(Box::new(device_addresses6)));
> ```

I'm not sure if you might want to do the same with `AddressData` here, but it probably does not matter.
___
*[talpid-core/src/firewall/mod.rs, line 100 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MGAUWKQ5DU4dbnuhCw3:-MGAUWKR1T2o-_uZSVf0:b-zvl7r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22d597b77711a9398204606015fc1f66f3b20981/talpid-core/src/firewall/mod.rs#L100)):*
> ```Rust
>         #[cfg(windows)]
>         relay_client: PathBuf,
>         /// Use firewall mark or endpoint
> ```

Is this a typo -- "for"? Or am I not understanding it? Either way it could be clarified a bit.
___
*[talpid-core/src/tunnel_state_machine/connecting_state.rs, line 315 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MGATfWKBYUbtrywGCm7:-MGATfWKBYUbtrywGCm8:bema0r7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bb8173aefb3c75d7d21354ea3aec6142c68357dc/talpid-core/src/tunnel_state_machine/connecting_state.rs#L315)):*
> ```Rust
> }
> 
> fn get_openvpn_proxy_settings(
> ```

Nice that this is gone!


<!-- Sent from Reviewable.io -->

2020-09-02 09:53 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[talpid-core/mine, line 1 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MGAXGHL9TKW8yRyDZ7G:-MGDBAOB0yo9L0iFLC8q:bb77ucv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22d597b77711a9398204606015fc1f66f3b20981/talpid-core/mine#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Was this included by accident?
</blockquote></details>

Yep.
___
*[talpid-core/src/dns/linux/network_manager.rs, line 218 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MGAOe5E18p3buLF91Lp:-MGDDym8C1Exd1waW93c:bflx8dz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22d597b77711a9398204606015fc1f66f3b20981/talpid-core/src/dns/linux/network_manager.rs#L218)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I'm not sure if you might want to do the same with `AddressData` here, but it probably does not matter.
</blockquote></details>

Seems like it doesn't matter.
___
*[talpid-core/src/firewall/mod.rs, line 100 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-MGAUWKQ5DU4dbnuhCw3:-MGDCIiEEaPLovMdyKhQ:bhfqqbp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22d597b77711a9398204606015fc1f66f3b20981/talpid-core/src/firewall/mod.rs#L100)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is this a typo -- "for"? Or am I not understanding it? Either way it could be clarified a bit.
</blockquote></details>

I've clarified this a bit.


<!-- Sent from Reviewable.io -->

2020-09-02 11:21 UTC, dlon approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2038#-:-MGDY7WtE2oSOAdF4a7t:b-uwkowd)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-02 11:23 UTC, merged