Purge WFP filters upon a full uninstall when always-require-vpn is enabled
mullvad/mullvadvpn-app pull request #2039
Opened 2020-08-26 16:18 UTC by dlon

When always-require-vpn is enabled, the WFP filters should be cleared upon a full uninstall. Currently they're not.

2020-08-26 18:32 UTC, mvd-ows requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2039)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[dist-assets/windows/installer.nsh, line 774 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2039#-MFg039x7S_jZesrkSRz:-MFg039y4Uoi3HGfqVc-:bje7pie) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f3dac4da4f633804543d25cb9b8d361e81e70936/dist-assets/windows/installer.nsh#L774)):*
> ```NSIS
> 	${EndIf}
> 
> 	nsExec::ExecToStack '"$SYSDIR\net.exe" stop mullvadvpn'
> ```

`net` is a legacy multi-purpose utility. What prompted this change?

Maybe `net` waits for the command to complete, and this is what allowed you to remove the embarrassing delays further down?

In that case you need to also update the next `ExecToStack` statement.


<!-- Sent from Reviewable.io -->

2020-08-26 18:32 UTC, mvd-ows reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2039)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2020-08-27 08:45 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2039)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[dist-assets/windows/installer.nsh, line 774 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2039#-MFg039x7S_jZesrkSRz:-MFj51NO6ISjwZ6scgBb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f3dac4da4f633804543d25cb9b8d361e81e70936/dist-assets/windows/installer.nsh#L774)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

`net` is a legacy multi-purpose utility. What prompted this change?

Maybe `net` waits for the command to complete, and this is what allowed you to remove the embarrassing delays further down?

In that case you need to also update the next `ExecToStack` statement.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-27 19:33 UTC, mvd-ows approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2039)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-28 11:31 UTC, merged