Remove unused MISSING_ARGUMENT constant and document remaining constants
mullvad/mullvadvpn-app pull request #2047
Opened 2020-08-31 11:03 UTC by faern

I could not find any usage for the `MISSING_ARGUMENT` constant. So I removed it. I moved the other constants to the top of the file, where constants are usually defined, and gave them documentation.

2020-08-31 19:33 UTC, pinkisemils requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Seem to be leftovers from the GRPC transition. Or, somewhat more likely, 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2047#-:-MG5-H9f1HJYc389AuiN:b-6jou8j)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[mullvad-rpc/src/lib.rs, line 127 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2047#-MG5-QaW5vQrQJO2opzW:-MG5-QaX7hhs4pbBFxJM:bazm066) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af02acf0cf059ac4eb109ba960538db77f3bfa6d/mullvad-rpc/src/lib.rs#L127)):*
> ```Rust
>     expires: DateTime<Utc>,
> }
> pub const VOUCHER_USED: &str = "VOUCHER_USED";
> ```

This variable is not used, but the same value is matched in `mullvad-jni` in `src/lib.rs` on line 96. The same is true for `INVALID_VOUCHER`.


<!-- Sent from Reviewable.io -->

2020-08-31 19:36 UTC, pinkisemils reviewed
To finish the above comment - these seem to be leftovers from the GRPC transition, the RPC codes were used in `management_interface.rs` to translate them to JSONRPC error codes. And these codes are still used in `mullvad-jni`. So it doesn't really look good to me :/.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2047#-:-MG506TKBrsgDFS2Fb1s:bfn4xv1)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2020-09-01 08:05 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2047)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-rpc/src/lib.rs, line 127 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2047#-MG5-QaW5vQrQJO2opzW:-MG7dXMP3uYKRvDQr3f6:b-fstzev) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/af02acf0cf059ac4eb109ba960538db77f3bfa6d/mullvad-rpc/src/lib.rs#L127)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This variable is not used, but the same value is matched in `mullvad-jni` in `src/lib.rs` on line 96. The same is true for `INVALID_VOUCHER`.
</blockquote></details>

Both these `INVALID_VOUCHER` and `VOUCHER_USED` constants are matched in `management_interface.rs`. But it's a bit inconsistent since `mullvad-jni` just defines them as strings instead of using the existing constants. It might be a bit overkill to define constants where the value is identical to the constant name. The only benefit of defining a shared constant that I see is that there is a logical place to attach documentation, and documentation is always important.


<!-- Sent from Reviewable.io -->

2020-09-01 11:47 UTC, pinkisemils approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2047)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-01 11:58 UTC, merged