Add actions to Linux tray context menu
mullvad/mullvadvpn-app pull request #2086
Opened 2020-09-08 09:25 UTC by raksooo

This PR adds actions to the context menu displayed when clicking on the tray icon in some desktop environments. Since we have to have a context menu we want to make the most of it. To keep the old behavior in desktop environments that support listening on tray icon click, a list of DEs supporting it is used to decide the behavior.

In addition to adding actions to the context menu, this PR changes the behavior when clicking the tray icon (or "Open Mullvad VPN" in the context menu) to always showing and focusing the app. This was changed since the toggle behavior was a bit confusing when the app was open but hidden behind some other window. Now it will always be placed on top of other windows. Hiding the app will still be possible by pressing the "x" window icon.

![image](https://user-images.githubusercontent.com/3668602/92455657-42823380-f1c2-11ea-93d4-dd5ebdff5f56.png)
![image](https://user-images.githubusercontent.com/3668602/92455683-4910ab00-f1c2-11ea-8f11-77332638c94f.png)

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2020-09-08 09:45 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2086)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 397 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2086#-MGh5bvC1TablYl_3rxx:-MGh5bvC1TablYl_3rxy:b-vceeam) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e8c606e76c1122c46e666945b9935c3c139533e/gui/src/main/index.ts#L397)):*
> ```XML
>         break;
>       case 'linux': {
>         if (displayEnvironmentsSupportingTrayClick.includes(this.getXdgCurrentDesktop())) {
> ```

Since the app is "windowed" on Linux, maybe we should always use the same context menu?


<!-- Sent from Reviewable.io -->

2020-09-08 10:00 UTC, pronebird reviewed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2086)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2020-09-08 11:25 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2086)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/main/index.ts, line 397 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2086#-MGh5bvC1TablYl_3rxx:-MGhSTBY7na9MBbFOre-:b-h372ym) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e8c606e76c1122c46e666945b9935c3c139533e/gui/src/main/index.ts#L397)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Since the app is "windowed" on Linux, maybe we should always use the same context menu?
</blockquote></details>

I agree :thumbsup: Fixed.


<!-- Sent from Reviewable.io -->

2020-09-09 07:12 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2086#-:-MGlhEO8E0KmuQP2hK_L:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-09 09:14 UTC, merged