Add support for custom DNS server on Android
mullvad/mullvadvpn-app pull request #2096
Opened 2020-09-09 22:51 UTC by jvff

By default the app uses the DNS servers provided by the relay server. However, some users prefer to use custom DNS servers. This PR implements that and adds an initial entry in the Advanced Settings screen to configure the custom DNS server address. If left unspecified, the app falls back to using the DNS servers provided by the relay.

The current implementation is very simplified, supporting a single custom DNS server address. It is persisted as a shared preference, and how it is used to configure the tunnel is similar to how split-tunneling is implemented. When the setting is changed, the tun device is marked as stale and a reconnection is requested. When creating the tun device, `TalpidVpnService` will pass the DNS servers provided by the relay server to a `prepareDnsServers` method. This method is overloaded by the `MullvadVpnService` in order to replace them with the custom DNS server address if it is set.

As part of the UI changes, since the current UI to configure the custom DNS server address is very similar to the UI to configure the WireGuard MTU value, the `MtuCell` was split in two. The functionality that is common to both the custom DNS UI and the MTU UI was placed in a new `InputCell` widget class. The `MtuClass` then becomes a specialization of the `InputCell` class, and a new `CustomDnsCell` class was created that follows the same approach.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2020-12-03 01:30 UTC, pinkisemils reviewed
> Reviewed 19 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2096)* status: 19 of 29 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-03 10:26 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2096)* status: 19 of 29 files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[talpid-core/src/tunnel/mod.rs, line 152 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2096#-MNc7kseBSuU6owqiEZE:-MNc7ksfBc1-wVS-IyJn:b-fc6u2w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/09bfe50e5cbb9f4ad56c391c2d9f34a9bd96e3d3/talpid-core/src/tunnel/mod.rs#L152)):*
> ```Rust
>         resource_dir: &Path,
>         on_event: L,
>         #[cfg(target_os = "android")] custom_dns_servers: Option<&Vec<IpAddr>>,
> ```

Could this option be stuffed into the android specific `TunProvider`? 


<!-- Sent from Reviewable.io -->

2020-12-03 10:35 UTC, pinkisemils requested changes
> Reviewed 1 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2096)* status: 20 of 29 files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[talpid-core/src/tunnel/mod.rs, line 152 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2096#-MNc7kseBSuU6owqiEZE:-MNc9l7W6RQfw_0cyxf8:b-5vd3td) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/09bfe50e5cbb9f4ad56c391c2d9f34a9bd96e3d3/talpid-core/src/tunnel/mod.rs#L152)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Could this option be stuffed into the android specific `TunProvider`? 
</blockquote></details>

Or maybe as an android specific field in `TunnelOptions`? This really shouldn't be a standalone parameter here or in most other places where this argument would be used.


<!-- Sent from Reviewable.io -->

2020-12-03 11:33 UTC, pinkisemils reviewed
> Reviewed 1 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2096)* status: 21 of 29 files reviewed, 1 unresolved discussion (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2020-12-03 22:49 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2096)* status: 16 of 27 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/mod.rs, line 152 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2096#-MNc7kseBSuU6owqiEZE:-MNemovSDNlG0uVFMk3O:bi03g84) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/09bfe50e5cbb9f4ad56c391c2d9f34a9bd96e3d3/talpid-core/src/tunnel/mod.rs#L152)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Or maybe as an android specific field in `TunnelOptions`? This really shouldn't be a standalone parameter here or in most other places where this argument would be used.
</blockquote></details>

Done. Great suggestion! I didn't think of this approach, but it's now a lot more similar to how allow LAN is implemented on Android :D 


<!-- Sent from Reviewable.io -->

2020-12-04 12:35 UTC, pinkisemils approved these changes
> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2096)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-04 13:46 UTC, merged