Improve routing for mullvad-exclude on Linux
mullvad/mullvadvpn-app pull request #2106
Opened 2020-09-11 13:10 UTC by dlon

These changes cause the `mullvad_exclusions` table to mirror `main`, except that route changes for tunnel devices are ignored (including the addition of their zero/default routes). Currently, LAN traffic will generally operate as you'd expect, assuming that the other host is on the same network. But monitoring the traffic reveals that the destination MAC address belongs to the gateway rather than the host. This is because the second table only tracks the default route belonging to the physical interface. Including all routes fixes this.

2020-09-21 14:22 UTC, pinkisemils requested changes
> Reviewed 4 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/routing/linux.rs, line 881 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106#-MHkylm70CBfdbIjsUCt:-MHkylm9Cky_d8aAwChh:bmf5150) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82219a0d885bd348265a5fa70d7d6c5714cadd05/talpid-core/src/routing/linux.rs#L881)):*
> ```Rust
> 
>         if let Some(metric) = route.metric {
>             route_message.nlas.push(RouteNla::Priority(metric));
> ```

If the metric is omitted, is the route not deleted?
___
*[talpid-core/src/routing/linux.rs, line 945 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106#-MHkz0L082TS3VxCILG1:-MHkz0L082TS3VxCILG2:b-flpwuq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82219a0d885bd348265a5fa70d7d6c5714cadd05/talpid-core/src/routing/linux.rs#L945)):*
> ```Rust
>         };
> 
>         // TODO: Request support for route priority in RouteAddIpv{4,6}Request
> ```

Must the metric be dynamic?
___
*[talpid-core/src/routing/unix.rs, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106#-MHkzedW4v5xbgzCBc1K:-MHkzedW4v5xbgzCBc1L:b-y62stp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82219a0d885bd348265a5fa70d7d6c5714cadd05/talpid-core/src/routing/unix.rs#L70)):*
> ```Rust
>     /// Adds link to ignore in the exclusions table.
>     #[cfg(target_os = "linux")]
>     SetTunnelLink(String),
> ```

At what point is this command issued when connecting via OpenVPN? I sense there might be a race condition between the daemon being aware of the tunnel name and the route manager trying to apply OpenVPN's routes. A mitigation might be to just try and set the name of the interface to a known one.
___
*[talpid-core/src/tunnel/openvpn.rs, line 154 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106#-MHl08Wm3glPuMxxNL7L:-MHl08Wm3glPuMxxNL7M:bbtlak2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82219a0d885bd348265a5fa70d7d6c5714cadd05/talpid-core/src/tunnel/openvpn.rs#L154)):*
> ```Rust
>         resource_dir: &Path,
>         #[cfg(target_os = "linux")] route_manager: &mut routing::RouteManager,
>         #[cfg(not(target_os = "linux"))] _route_manager: &mut routing::RouteManager,
> ```

Could this parameter be omitted on other platforms?


<!-- Sent from Reviewable.io -->

2020-09-21 14:48 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/routing/linux.rs, line 881 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106#-MHkylm70CBfdbIjsUCt:-MHl56UH-jku_DxGAUfz:b-adurrf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82219a0d885bd348265a5fa70d7d6c5714cadd05/talpid-core/src/routing/linux.rs#L881)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

If the metric is omitted, is the route not deleted?
</blockquote></details>

It is. See the other response.
___
*[talpid-core/src/routing/linux.rs, line 945 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106#-MHkz0L082TS3VxCILG1:-MHl5VD57GDw2bq95mg_:bqrd0y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82219a0d885bd348265a5fa70d7d6c5714cadd05/talpid-core/src/routing/linux.rs#L945)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Must the metric be dynamic?
</blockquote></details>

Sometimes an otherwise identical route with a different metric is added (by the kernel, I assume), followed by a removal of the old route.

When the metric isn't accounted for, this causes it to replace the first route (rather than add a new one) and then delete it. So for me the default route would sometimes be deleted completely, and this caused leaks into the tunnel.

It's worth worrying about the possibility that this may apply to attributes other than the metric/priority.
___
*[talpid-core/src/routing/unix.rs, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106#-MHkzedW4v5xbgzCBc1K:-MHl7BNr1YNE1LN7jQ6c:b-n7wx4w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82219a0d885bd348265a5fa70d7d6c5714cadd05/talpid-core/src/routing/unix.rs#L70)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

At what point is this command issued when connecting via OpenVPN? I sense there might be a race condition between the daemon being aware of the tunnel name and the route manager trying to apply OpenVPN's routes. A mitigation might be to just try and set the name of the interface to a known one.
</blockquote></details>

It happens in response to the `OPENVPN_PLUGIN_UP` event. A race is possible probably, given that nothing is preventing OpenVPN from doing its thing. How likely it is, I don't know. It is probably worth worrying about, because it may cause leaks *into* the tunnel.


<!-- Sent from Reviewable.io -->

2020-09-21 15:12 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/routing/unix.rs, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106#-MHkzedW4v5xbgzCBc1K:-MHlCo7B4Ab0eqiAyRRa:b-8kir41) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82219a0d885bd348265a5fa70d7d6c5714cadd05/talpid-core/src/routing/unix.rs#L70)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It happens in response to the `OPENVPN_PLUGIN_UP` event. A race is possible probably, given that nothing is preventing OpenVPN from doing its thing. How likely it is, I don't know. It is probably worth worrying about, because it may cause leaks *into* the tunnel.
</blockquote></details>

Hrm, could we maybe block the OpenVPN plugin to wait for a response to our RPC then? And then have the application of the ignore-able interface name to block until it's set?


<!-- Sent from Reviewable.io -->

2020-09-21 15:14 UTC, pinkisemils reviewed
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2020-09-21 15:20 UTC, pinkisemils reviewed
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2020-09-22 08:52 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/routing/unix.rs, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106#-MHkzedW4v5xbgzCBc1K:-MHoyJK87zZZ2a9r9Mm9:b-bzuc6z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82219a0d885bd348265a5fa70d7d6c5714cadd05/talpid-core/src/routing/unix.rs#L70)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Hrm, could we maybe block the OpenVPN plugin to wait for a response to our RPC then? And then have the application of the ignore-able interface name to block until it's set?
</blockquote></details>

Tested this. It already waits for the `Up` event handler to return.
___
*[talpid-core/src/tunnel/openvpn.rs, line 154 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106#-MHl08Wm3glPuMxxNL7L:-MHp-Xmv5OOW21MFfpAG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82219a0d885bd348265a5fa70d7d6c5714cadd05/talpid-core/src/tunnel/openvpn.rs#L154)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Could this parameter be omitted on other platforms?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-22 09:13 UTC, pinkisemils approved these changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[talpid-core/src/routing/unix.rs, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106#-MHkzedW4v5xbgzCBc1K:-MHp4LEw-a5Q_y6RxXw7:b-x60znl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82219a0d885bd348265a5fa70d7d6c5714cadd05/talpid-core/src/routing/unix.rs#L70)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Tested this. It already waits for the `Up` event handler to return.
</blockquote></details>

But the `Up` handler doesn't wait for the route manager to finish setting the exclusion event, or at least that's my assumption.


<!-- Sent from Reviewable.io -->

2020-09-22 09:46 UTC, pinkisemils approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106#-:-MHpCG0cD8Y4TJ_cvtxz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-22 11:13 UTC, pinkisemils approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-22 11:14 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel/openvpn.rs, line 185 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106#-MHpWEGd7fItqm-zbEI3:-MHpWEGd7fItqm-zbEI4:b-jj1n8p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0e63cf03876dc4ec1e80fffd16aaefc4507cfe68/talpid-core/src/tunnel/openvpn.rs#L185)):*
> ```Rust
>                     .unbounded_send(routing::RouteManagerCommand::SetTunnelLink(interface, tx))
>                     .unwrap();
>                 futures::executor::block_on(rx).unwrap();
> ```

Is this function not actually executed from a tokio runtime in the end?


<!-- Sent from Reviewable.io -->

2020-09-22 13:43 UTC, pinkisemils approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[talpid-core/src/tunnel/openvpn.rs, line 185 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106#-MHpWEGd7fItqm-zbEI3:-MHq2GuWAyJ5gn9bMzga:b6wqjgt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0e63cf03876dc4ec1e80fffd16aaefc4507cfe68/talpid-core/src/tunnel/openvpn.rs#L185)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Is this function not actually executed from a tokio runtime in the end?
</blockquote></details>

This is as good a move as any. I guess an alternative solution would've been to change the signature of `on_openvpn_event` to return a closure and have the handler await there. 


<!-- Sent from Reviewable.io -->

2020-09-23 10:36 UTC, pinkisemils approved these changes
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-23 10:49 UTC, merged