Improve accessibility for inputs and modals
mullvad/mullvadvpn-app pull request #2117
Opened 2020-09-15 13:46 UTC by raksooo

This PR:
* Makes input labels use the `<label>` tag
* Adds attributes to labels, inputs and descriptions (`id`, `for`, `aria-labelledby`, `aria-describedby`)
* Adds `aria-disabled` attribute to `Switch` to communicate whether or not it is disabled
* Makes it possible to close modal by pressing escape
* Prevents screenreaders from navigating to content behind modal
* (Random improvement): Replaces the use of `document.getElementById` in `ModalAlert` with a ref since there's now a context.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2020-09-16 08:45 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/Switch.tsx, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117#-MHL1luo1e9rT6cuNi5m:-MHL1luo1e9rT6cuNi5n:b73iyg8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/228f9059145731fe595a3ff837a926458e53afa4/gui/src/renderer/components/Switch.tsx#L7)):*
> ```XML
> interface IProps {
>   id?: string;
>   'aria-labelledby'?: string;
> ```

If you're duplicating the aria props, then maybe we could inherit `IProps` from something that already defines all of then? I don't remember the correct type to inherit from though.


<!-- Sent from Reviewable.io -->

2020-09-16 08:57 UTC, pronebird requested changes
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @raksooo)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117#-MHL756J86hs1vuDXtRf:-MHL756K-oJsuoXEecPT:b-kll4ez) (no related file):*
Duplicating the conversation from Slack, I think we should try building some sort of abstraction to wire elements together as opposed to spreading props.

For example:

```tsx
<AriaGroup>
  <Cell.Container>
    <AriaLabel>
      <Cell.InputLabel>
        {messages.pgettext('advanced-settings-view', 'Enable IPv6')}
      </Cell.InputLabel>
    </AriaLabel>
    <AriaInput>
      <Cell.Switch
        isOn={this.props.enableIpv6}
        onChange={this.props.setEnableIpv6}
        {...enableIpv6Aria.input}
      />
    </AriaInput>
  </Cell.Container>
  <Cell.Footer>
    <AriaDescription>
      <Cell.FooterText>
        {messages.pgettext(
          'advanced-settings-view',
          'Enable IPv6 communication through the tunnel.',
        )}
      </Cell.FooterText>
    </AriaDescription>
  </Cell.Footer>
</AriaGroup>
```

Each of the `Aria*` family elements can share data via React contexts, for example:

```
var globalId = 0
const AriaContext = React.createContext();

function AriaGroup(props) {
   return <AriaContext value={ (globalId++) }>{props.children}</AriaContext>
}

function AriaLabel(props) {
   const context = useContext(AriaContext)
   const { children, ...rest } = props
   return React.clone(React.Children.only(children), { ...props, id: context.value.toString() + "-input", htmlFor={ context.value.toString() })
}

// etc..
```

---


<!-- Sent from Reviewable.io -->

2020-09-16 09:05 UTC, pronebird reviewed
> Reviewed 7 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2020-09-16 09:05 UTC, pronebird reviewed
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2020-09-17 06:53 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/src/renderer/components/Switch.tsx, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117#-MHL1luo1e9rT6cuNi5m:-MHPpNiY33OKlFvCCRzu:b-95o4el) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/228f9059145731fe595a3ff837a926458e53afa4/gui/src/renderer/components/Switch.tsx#L7)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

If you're duplicating the aria props, then maybe we could inherit `IProps` from something that already defines all of then? I don't remember the correct type to inherit from though.
</blockquote></details>

I tried extending `React.HTMLAttributes<HTMLDivElement>` but that results in conflicting types for `onChange` since the one for `HTMLDivElement` takes an event as it's argument. This could of course be resolved by renaming `onChange`, how about renaming it to `onSwitch`?


<!-- Sent from Reviewable.io -->

2020-09-17 14:14 UTC, pronebird requested changes
> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/components/Switch.tsx, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117#-MHL1luo1e9rT6cuNi5m:-MHROHrY8uTzskZZUvYS:b-vbenaj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/228f9059145731fe595a3ff837a926458e53afa4/gui/src/renderer/components/Switch.tsx#L7)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I tried extending `React.HTMLAttributes<HTMLDivElement>` but that results in conflicting types for `onChange` since the one for `HTMLDivElement` takes an event as it's argument. This could of course be resolved by renaming `onChange`, how about renaming it to `onSwitch`?
</blockquote></details>

I see. Sadly ARIA attributes alone are private:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1559

How about we make a separate type for ourselves and then inherit it where needed instead of listing ARIA props for each component?


<!-- Sent from Reviewable.io -->

2020-09-17 14:15 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/Switch.tsx, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117#-MHL1luo1e9rT6cuNi5m:-MHRPl-t0cZdgK8AaNrR:b-jz9o5j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/228f9059145731fe595a3ff837a926458e53afa4/gui/src/renderer/components/Switch.tsx#L7)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I see. Sadly ARIA attributes alone are private:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1559

How about we make a separate type for ourselves and then inherit it where needed instead of listing ARIA props for each component?
</blockquote></details>

Follow up on this: Since we don't spread the `props` I think it would be unfair to promise that we will do anything with them if they were passed.


<!-- Sent from Reviewable.io -->

2020-09-17 14:20 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[gui/src/renderer/components/Switch.tsx, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117#-MHL1luo1e9rT6cuNi5m:-MHRQ_NsDhyZBB8mYVH8:b-k93zse) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/228f9059145731fe595a3ff837a926458e53afa4/gui/src/renderer/components/Switch.tsx#L7)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Follow up on this: Since we don't spread the `props` I think it would be unfair to promise that we will do anything with them if they were passed.
</blockquote></details>

Actually. Unless we use it more than once, leave it as is. At least the interface is clean. 


<!-- Sent from Reviewable.io -->

2020-09-17 14:20 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117#-:-MHRR-rh76Bl4MhFs4U9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-17 15:06 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[gui/src/renderer/components/Switch.tsx, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117#-MHL1luo1e9rT6cuNi5m:-MHRaA0KEGoUl2lbHWGp:bnqdd14) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/228f9059145731fe595a3ff837a926458e53afa4/gui/src/renderer/components/Switch.tsx#L7)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Actually. Unless we use it more than once, leave it as is. At least the interface is clean. 
</blockquote></details>

If we do introduce an interface or use an existing one for this we should also spread the props. But I agree, let's wait until there's two component needing this.


<!-- Sent from Reviewable.io -->

2020-09-17 15:17 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-17 15:24 UTC, merged