Use netlink instead of iproute2/rt_tables to set up mullvad_exclusions
mullvad/mullvadvpn-app pull request #2127
Opened 2020-09-18 11:59 UTC by dlon

The daemon currently parses `rt_tables` to find a free slot for `mullvad_exclusions`. Aside from not being pretty, this can cause issues when `/etc/iproute2/rt_tables` does not exist or when `iproute2` is not installed. These changes instead look for an empty table using netlink and use that ID.

The route manager now also understands table IDs greater than 255.

https://github.com/mullvad/mullvadvpn-app/pull/2126 removes the use of `ip` subprocesses. With these two PRs, `iproute2` should no longer be required.

2020-09-21 16:04 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2127)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/routing/linux.rs, line 178 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2127#-MHk3OEzCKarqUl7W713:-MHk3OF-90f7xyxn1fdT:b-hwwiig) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1de3fe2e6e67abd328be036bfe071f2db3d3fb9/talpid-core/src/routing/linux.rs#L178)):*
> ```Rust
>         const RT_TABLE_COMPAT_U32: u32 = RT_TABLE_COMPAT as u32;
>         for id in 1..u32::MAX {
>             if id == RT_TABLE_COMPAT_U32 {
> ```

I think it'd be simpler to just use `id == RT_TABLE_COMPAT as u32`.


<!-- Sent from Reviewable.io -->

2020-09-21 16:08 UTC, pinkisemils reviewed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2127)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2020-09-22 07:56 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2127)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/routing/linux.rs, line 178 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2127#-MHk3OEzCKarqUl7W713:-MHoo6Gl2i3yzgzx7jZi:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1de3fe2e6e67abd328be036bfe071f2db3d3fb9/talpid-core/src/routing/linux.rs#L178)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think it'd be simpler to just use `id == RT_TABLE_COMPAT as u32`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-22 09:13 UTC, pinkisemils approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2127)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-22 10:12 UTC, pinkisemils approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2127)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-22 11:34 UTC, merged