Improve accessibility
mullvad/mullvadvpn-app pull request #2134
Opened 2020-09-21 13:32 UTC by raksooo

This PR:
* Adds an `aria-label` to the select location button to better communicate it's function
* Adds the `alert` role to the text in `Launch` and `ErrorBoundary` to notify the user that something went wrong
* Makes `BlockingButton` use a context instead of cloning children to make it compatible with the `AriaGroup` components
* Adds `aria-label` to the `extLink` icon and add them as descriptions to their corresponding button to communicate that they'll open something externally
* Change which elements are used as headings. The navigation title is now always used as heading since it works well for all settings views to have one. If we were to use the "real" headings instead, we would have to specify it in each view containing one.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2020-09-23 13:39 UTC, pronebird reviewed
> Reviewed 2 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: 2 of 15 files reviewed, all discussions resolved

___
*[gui/src/renderer/components/TunnelControl.tsx, line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134#-MHvAjaB5Aol7NHvDzHI:-MHvAjaB5Aol7NHvDzHJ:b-xi3eok) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9aecfb532675409181b335f1bac9b1626b0d276/gui/src/renderer/components/TunnelControl.tsx#L89)):*
> ```XML
>       <SwitchLocationButton
>         onClick={this.props.onSelectLocation}
>         aria-label={sprintf(
> ```

FYI on iOS I'd specify a label and description separately & VO would pronounce both with a pause. Not sure it matters on the web.


<!-- Sent from Reviewable.io -->

2020-09-23 13:42 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: 2 of 15 files reviewed, all discussions resolved

___
*[gui/src/renderer/components/TunnelControl.tsx, line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134#-MHvAjaB5Aol7NHvDzHI:-MHvBhdi2vJzEevgrp1k:bx8j8km) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9aecfb532675409181b335f1bac9b1626b0d276/gui/src/renderer/components/TunnelControl.tsx#L89)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI on iOS I'd specify a label and description separately & VO would pronounce both with a pause. Not sure it matters on the web.
</blockquote></details>

If I set a label on for example a div it reads both the label and the content but if I do it on a button it reads the label instead of the content.


<!-- Sent from Reviewable.io -->

2020-09-23 13:44 UTC, pronebird reviewed
> Reviewed 5 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: 7 of 15 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-23 13:47 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/ExpiredAccountErrorView.tsx, line 181 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134#-MHvC_HS0gkmHgTu96qF:-MHvC_HS0gkmHgTu96qG:b-tnp91j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9aecfb532675409181b335f1bac9b1626b0d276/gui/src/renderer/components/ExpiredAccountErrorView.tsx#L181)):*
> ```XML
>                   height={16}
>                   width={16}
>                   aria-label={messages.pgettext('accessibility', 'Opens externally')}
> ```

Does it make the icon navigable by VO? It would be better if the entire cell acted as a single element so that the VO wouldn't be going deep inside.


<!-- Sent from Reviewable.io -->

2020-09-23 13:58 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/renderer/components/ExpiredAccountErrorView.tsx, line 181 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134#-MHvC_HS0gkmHgTu96qF:-MHvE5kgBTryaRj7NYJR:b-4yosp8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9aecfb532675409181b335f1bac9b1626b0d276/gui/src/renderer/components/ExpiredAccountErrorView.tsx#L181)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Does it make the icon navigable by VO? It would be better if the entire cell acted as a single element so that the VO wouldn't be going deep inside.
</blockquote></details>

It's handled differently by different screenreaders. Since this is a description for the whole button VO reads the whole cell like "Buy credit Opens externally" and you cant focus the individual parts. But Narrator on windows which doesn't seem to support this as well lets you focus the label and the icon individually, but the onclick should fire if you click any of them.


<!-- Sent from Reviewable.io -->

2020-09-23 14:06 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/renderer/components/ExpiredAccountErrorView.tsx, line 181 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134#-MHvC_HS0gkmHgTu96qF:-MHvGW4zENUw8PI3ABrm:b-mmegh2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9aecfb532675409181b335f1bac9b1626b0d276/gui/src/renderer/components/ExpiredAccountErrorView.tsx#L181)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

It's handled differently by different screenreaders. Since this is a description for the whole button VO reads the whole cell like "Buy credit Opens externally" and you cant focus the individual parts. But Narrator on windows which doesn't seem to support this as well lets you focus the label and the icon individually, but the onclick should fire if you click any of them.
</blockquote></details>

We can't really control how screenreaders present our structure since different screenreaders handle a lot of situations differently. I think the best approach is to make sure our code is semantically correct and then trust screenreaders unless something proves to bad enough for us to find a workaround. I haven't really read anything specifically about this scenario but if there's a better way we should of course change it :)


<!-- Sent from Reviewable.io -->

2020-09-24 09:14 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/ExpiredAccountErrorView.tsx, line 181 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134#-MHvC_HS0gkmHgTu96qF:-MHzL4SR4Rmi57KjgY-p:b3rb60q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9aecfb532675409181b335f1bac9b1626b0d276/gui/src/renderer/components/ExpiredAccountErrorView.tsx#L181)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

We can't really control how screenreaders present our structure since different screenreaders handle a lot of situations differently. I think the best approach is to make sure our code is semantically correct and then trust screenreaders unless something proves to bad enough for us to find a workaround. I haven't really read anything specifically about this scenario but if there's a better way we should of course change it :)
</blockquote></details>

Maybe by using the `role="button"` on the button element would remedy this?


<!-- Sent from Reviewable.io -->

2020-09-24 09:29 UTC, pronebird requested changes
> Reviewed 5 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: 12 of 15 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/components/Settings.tsx, line 182 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134#-MHzOryG8aVSFAAgkBD0:-MHzOryHDbrQ8-XHfzh9:b-cv7cf4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9aecfb532675409181b335f1bac9b1626b0d276/gui/src/renderer/components/Settings.tsx#L182)):*
> ```XML
>       <AriaDescriptionGroup>
>         <AriaDescribed>
>           <Cell.CellButton disabled={this.props.isOffline} onClick={this.openDownloadLink}>
> ```

I imagine this to look like this:

```
<Cell.CellButton role="button" aria-labeledby="label-id subtext-id">
   <Cell.Label>{messages.pgettext('settings-view', 'App version')}</Cell.Label>
   <Cell.SubText>{this.props.appVersion}</Cell.SubText>
</Cell>
```

& I suppose the screen reader should not attempt at going down the tree if it hits the button element.


<!-- Sent from Reviewable.io -->

2020-09-24 09:30 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: 12 of 15 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/components/Settings.tsx, line 182 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134#-MHzOryG8aVSFAAgkBD0:-MHzRgpi2MWPWfKJ2RU3:b-usfqf6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9aecfb532675409181b335f1bac9b1626b0d276/gui/src/renderer/components/Settings.tsx#L182)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I imagine this to look like this:

```
<Cell.CellButton role="button" aria-labeledby="label-id subtext-id">
   <Cell.Label>{messages.pgettext('settings-view', 'App version')}</Cell.Label>
   <Cell.SubText>{this.props.appVersion}</Cell.SubText>
</Cell>
```

& I suppose the screen reader should not attempt at going down the tree if it hits the button element.
</blockquote></details>

ps: mady icon should be referenced in `aria-labelby` too. Can you test it and see if it works?


<!-- Sent from Reviewable.io -->

2020-09-24 09:31 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: 12 of 15 files reviewed, 2 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/src/renderer/components/ExpiredAccountErrorView.tsx, line 181 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134#-MHvC_HS0gkmHgTu96qF:-MHzRZi6-na__2AAqo38:bojjjd8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9aecfb532675409181b335f1bac9b1626b0d276/gui/src/renderer/components/ExpiredAccountErrorView.tsx#L181)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe by using the `role="button"` on the button element would remedy this?
</blockquote></details>

It already uses the `<button>` HTML element and therefore automatically gets the button role


<!-- Sent from Reviewable.io -->

2020-09-24 09:53 UTC, pronebird reviewed
> Reviewed 3 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2020-09-24 09:58 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/renderer/components/Settings.tsx, line 182 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134#-MHzOryG8aVSFAAgkBD0:-MHzSoKw-HhHEFxdF6GX:b-urer9l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9aecfb532675409181b335f1bac9b1626b0d276/gui/src/renderer/components/Settings.tsx#L182)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

ps: mady icon should be referenced in `aria-labelby` too. Can you test it and see if it works?
</blockquote></details>

The button will have the `aria-describedby` attribute for the icon. I don't think we need to add `aria-labelledby` since it uses the content as label. Now when trying buttons out with Narrator again it communicated the buttons as "Button, Opens externally, App version" which seems like what we want. I don't know what I did different this time though.


<!-- Sent from Reviewable.io -->

2020-09-24 10:32 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/Settings.tsx, line 182 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134#-MHzOryG8aVSFAAgkBD0:-MHzeVbf37uUHIh2dBvG:bxefwmo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9aecfb532675409181b335f1bac9b1626b0d276/gui/src/renderer/components/Settings.tsx#L182)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

The button will have the `aria-describedby` attribute for the icon. I don't think we need to add `aria-labelledby` since it uses the content as label. Now when trying buttons out with Narrator again it communicated the buttons as "Button, Opens externally, App version" which seems like what we want. I don't know what I did different this time though.
</blockquote></details>

The order seems to be off though, probably should say "Button, App version first, Click to open the download page in web browser"? 

Do we need to use a `tab- index` or something like this to specify the order?


<!-- Sent from Reviewable.io -->

2020-09-24 11:41 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-24 11:41 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134#-:-MHzulYsB9TutOlRzB7L:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-24 12:40 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[gui/src/renderer/components/Settings.tsx, line 182 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134#-MHzOryG8aVSFAAgkBD0:-MI-5sKKAUct14jVYN2m:b-bp6y5p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9aecfb532675409181b335f1bac9b1626b0d276/gui/src/renderer/components/Settings.tsx#L182)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

The order seems to be off though, probably should say "Button, App version first, Click to open the download page in web browser"? 

Do we need to use a `tab- index` or something like this to specify the order?
</blockquote></details>

I agree that it would be better if the order was reversed but I'm not sure we should try to fix that. Other screen readers read it in the correct order and in some it might even be possible to change whether or not descriptions should be read before or after. I believe that we should focus on making it semantically correct and unless it's presented wrong in all screen readers we're fine.

None of them have a `tabindex` value. Screenreaders navigates in text as well as input elements. Its possible to go through the buttons word by word or character by character as well.

I don't think we should have it say things like "Click to ..." since most screen readers already say that for buttons and that it is possible to change the verbosity settings for the screen reader.


<!-- Sent from Reviewable.io -->

2020-09-24 12:58 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2134)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-24 13:12 UTC, merged