Start key rotation after initial key is created.
mullvad/mullvadvpn-app pull request #2149
Opened 2020-09-25 10:45 UTC by pinkisemils

When a new account is set, and a key is generated, the daemon previously didn't start the key rotation timer. The effect is that if a new user never reboots, the key would not be rotated indefinitely. I've changed the daemon so that whenever a new key event is received and the current account has no key, the key rotation would be started. The reason for not starting the key rotation whenever a new key is created is because the key rotation will almost always be started already.

The last commit here is a small refactoring to simplify the code for key rotation/generation. This is purely optional and I can drop it, since we're so close to a release.

2020-09-25 14:22 UTC, dlon requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2149)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[mullvad-daemon/src/wireguard.rs, line 157 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2149#-MI4KzVQ53BnZmhLVyRm:-MI4KzVR1yn3MenYCZ7s:bfmnlu9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e3894cb3e8eee20fd615665ddc454c7eaf68a81/mullvad-daemon/src/wireguard.rs#L157)):*
> ```Rust
> 
>     /// Generate a new private key asynchronously. The new keys will be sent to the daemon channel.
>     pub async fn generate_key_async(&mut self, account: AccountToken, timeout: Option<Duration>) {
> ```

I see. `generate_key_async` does not wait until the key has been received and the settings/account updated. The daemon called `set_rotation` immediately after `generate_key_async`, so the account was likely to have no associated key?
___
*[mullvad-daemon/src/wireguard.rs, line 220 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2149#-MI4TslC6Z2f1yuyXsnz:-MI4LBVCEs9znl2j96bD:b-ic65aq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e3894cb3e8eee20fd615665ddc454c7eaf68a81/mullvad-daemon/src/wireguard.rs#L220)):*
> ```Rust
>                 Ok(wireguard_data) => {
>                     let public_key = wireguard_data.get_public_key();
>                     let _ = daemon_tx.send(InternalDaemonEvent::WgKeyEvent((
> ```

Should it be verified that the settings are actually updated, and not start the rotation task otherwise? `Daemon::handle_wireguard_key_event` can fail if the active account has changed or if the account history cannot be saved, both of which seem possible.
___
*[mullvad-daemon/src/wireguard.rs, line 427 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2149#-MI4TDNT7F5WQwCCL_H4:-MI4TDNT7F5WQwCCL_H5:b-orwgy5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e3894cb3e8eee20fd615665ddc454c7eaf68a81/mullvad-daemon/src/wireguard.rs#L427)):*
> ```Rust
> 
>     fn stop_automatic_rotation(&mut self) {
>         if let Some(abort_handle) = self.abort_scheduler_tx.take() {
> ```

Won't this fail to cancel the key rotation task started by `generate_key_async`?


<!-- Sent from Reviewable.io -->

2020-09-25 16:01 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2149)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/wireguard.rs, line 157 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2149#-MI4KzVQ53BnZmhLVyRm:-MI4dggg9RS9YNiPgrnM:bb77ucv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e3894cb3e8eee20fd615665ddc454c7eaf68a81/mullvad-daemon/src/wireguard.rs#L157)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I see. `generate_key_async` does not wait until the key has been received and the settings/account updated. The daemon called `set_rotation` immediately after `generate_key_async`, so the account was likely to have no associated key?
</blockquote></details>

Yep.
___
*[mullvad-daemon/src/wireguard.rs, line 220 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2149#-MI4TslC6Z2f1yuyXsnz:-MI4dr1s32uSnEs7de-s:bxtd8bs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e3894cb3e8eee20fd615665ddc454c7eaf68a81/mullvad-daemon/src/wireguard.rs#L220)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should it be verified that the settings are actually updated, and not start the rotation task otherwise? `Daemon::handle_wireguard_key_event` can fail if the active account has changed or if the account history cannot be saved, both of which seem possible.
</blockquote></details>

In the case that the account has been changed, this future will be cancelled anyway.
___
*[mullvad-daemon/src/wireguard.rs, line 427 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2149#-MI4TDNT7F5WQwCCL_H4:-MI4dm8fCSt8OeokEPcD:b-vg120d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e3894cb3e8eee20fd615665ddc454c7eaf68a81/mullvad-daemon/src/wireguard.rs#L427)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Won't this fail to cancel the key rotation task started by `generate_key_async`?
</blockquote></details>

Oh, it will. I was under the false impression that `self.current_job` would hold both key generation and key rotation futures. I guess I'll just drop the last commit as it introduces more trouble than it seems to be worth.


<!-- Sent from Reviewable.io -->

2020-09-28 09:59 UTC, dlon requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2149)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[mullvad-daemon/src/lib.rs, line 625 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2149#-MIJ31yt233reMxmh_HP:-MIJ31yt233reMxmh_HQ:bxnwsvo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2948623d95f1793b4eb544fa5b9c20a9d2490340/mullvad-daemon/src/lib.rs#L625)):*
> ```Rust
> 
>         daemon.ensure_wireguard_keys_for_current_account().await;
>         daemon.ensure_key_rotation().await;
> ```

This should probably still only be called in the case where no key will be generated
___
*[mullvad-daemon/src/wireguard.rs, line 220 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2149#-MI4TslC6Z2f1yuyXsnz:-MIJ57V48hD6YgQqgtcm:b942g1l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e3894cb3e8eee20fd615665ddc454c7eaf68a81/mullvad-daemon/src/wireguard.rs#L220)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

In the case that the account has been changed, this future will be cancelled anyway.
</blockquote></details>

I still think that it's somewhat difficult to follow all of the logic related to key rotation.

`generate_key_async` is a somewhat confusing name now, since it isn't *obvious* that it uses `tokio::spawn` and returns before its' done when `await`ed. Renaming it to `spawn_key_generate_task` or something might help.

I wonder if it could be less tightly coupled to `Daemon`. E.g., I haven't thought about it much, but maybe sending `InternalDaemonEvent`s directly is bad.

That's for some other time, though.


<!-- Sent from Reviewable.io -->

2020-09-28 10:23 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2149)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2020-09-28 10:40 UTC, dlon approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2149)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2020-09-28 10:41 UTC, merged