Add persistent firewall filters on Windows
mullvad/mullvadvpn-app pull request #2168
Opened 2020-10-06 15:13 UTC by dlon

These changes cause the WinFw module to add persistent WFP filters when deinitialized in some cases:

* `WinFw_Deinitialize` is called with the "continue blocking" cleanup policy, and the daemon exits in a blocking state. This happens if "Always require VPN" is enabled.
* `WinFw_Deinitialize` is called with the "block" cleanup policy. This effectively occurs if auto-connect is enabled.

Two sets of filters are required: Boot-time filters are used for blocking traffic before the BFE service has started. Persistent filters are used to block traffic after the BFE service has started, but before mullvad-daemon has started.

This prevents traffic leaks during boot when either "Always require VPN" or auto-connect is enabled.

2020-10-07 09:33 UTC, mvd-ows requested changes
> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[dist-assets/windows/installer.nsh, line 719 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168#-MJ0vzJ34CXVLwLkFu7y:-MJ0vzJ34CXVLwLkFu7z:b-b8y2jf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81ec0d8d8299542e1f4432424ee12a47db41d3af/dist-assets/windows/installer.nsh#L719)):*
> ```NSIS
> 	${If} $BlockFilterResult == 0
> 	${OrIf} $PersistentBlockFilterResult == 0
> 		MessageBox MB_ICONEXCLAMATION|MB_YESNO "Do you wish to unblock your internet access? Doing so will leave you with an unsecure connection." IDNO customInstall_abortInstallation_skip_firewall_revert
> ```

Maybe use a capital `I` on `Internet`? Different sources have different opinions on this. Not sure what we usually do.
___
*[windows/winfw/src/winfw/mullvadguids.cpp, line 103 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168#-MJ1CDQd3x5rHGZIITdB:-MJ1CDQd3x5rHGZIITdC:bkdfdw8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81ec0d8d8299542e1f4432424ee12a47db41d3af/windows/winfw/src/winfw/mullvadguids.cpp#L103)):*
> ```cpp
> 	std::multimap<WfpObjectType, GUID> registry;
> 
> 	if (IdentityQualifier::OnlyCurrent != (qualifier & IdentityQualifier::IncludeDeprecated))
> ```

This is quite difficult to read. It depends both on the and-overload as well as the exact definition of `OnlyCurrent`.

Is it possible to use a `flag GetFlag(composite, flag)` or `bool CheckFlag(composite, flag), but using a function name more suited to the context?
___
*[windows/winfw/src/winfw/mullvadobjects.cpp, line 69 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168#-MJ1DrK_2DQOdWbM-Bv1:-MJ1DrK_2DQOdWbM-Bv2:b-w5a25w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81ec0d8d8299542e1f4432424ee12a47db41d3af/windows/winfw/src/winfw/mullvadobjects.cpp#L69)):*
> ```cpp
> 	(*builder)
> 		.name(L"Mullvad VPN filters that survive across BFE stop/start")
> 		.description(L"Filters that restrict traffic before the has daemon started")
> ```

Grammar.


<!-- Sent from Reviewable.io -->

2020-10-07 13:29 UTC, mvd-ows reviewed
> Reviewed 4 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2020-10-07 13:44 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168)* status: 13 of 17 files reviewed, 3 unresolved discussions (waiting on @mvd-ows)

___
*[dist-assets/windows/installer.nsh, line 719 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168#-MJ0vzJ34CXVLwLkFu7y:-MJ2IIveDTxkUk4jktvh:b-t7ivg5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81ec0d8d8299542e1f4432424ee12a47db41d3af/dist-assets/windows/installer.nsh#L719)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Maybe use a capital `I` on `Internet`? Different sources have different opinions on this. Not sure what we usually do.
</blockquote></details>

I checked this with Kat, so it should be good.
___
*[windows/winfw/src/winfw/mullvadguids.cpp, line 103 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168#-MJ1CDQd3x5rHGZIITdB:-MJ2I6gVBaQrVls3u6gO:bbdob0p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81ec0d8d8299542e1f4432424ee12a47db41d3af/windows/winfw/src/winfw/mullvadguids.cpp#L103)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This is quite difficult to read. It depends both on the and-overload as well as the exact definition of `OnlyCurrent`.

Is it possible to use a `flag GetFlag(composite, flag)` or `bool CheckFlag(composite, flag), but using a function name more suited to the context?
</blockquote></details>

I've simplified it.
___
*[windows/winfw/src/winfw/mullvadobjects.cpp, line 69 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168#-MJ1DrK_2DQOdWbM-Bv1:-MJ2ICkM9p57N4pSkJM3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81ec0d8d8299542e1f4432424ee12a47db41d3af/windows/winfw/src/winfw/mullvadobjects.cpp#L69)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Grammar.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-07 13:59 UTC, mvd-ows approved these changes
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-07 14:02 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 644 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168#-MJ2KClqDFPdmsf3OBe1:-MJ2KClqDFPdmsf3OBe2:bl7lwt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/635fb3855265ff00fb1f4ef2698b58fc56f0514e/mullvad-daemon/src/lib.rs#L644)):*
> ```Rust
> 
>         #[cfg(windows)]
>         if self.settings.auto_connect {
> ```

Can we get a comment here? Explaining that on daemon shut down we block the firewall if `auto-connect` is enabled, in order to make it properly block all traffic during boot until the daemon can take over again.
___
*[talpid-core/src/firewall/windows.rs, line 322 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168#-MJ2LvVGC1bQ_8S7cTTD:-MJ2LvVGC1bQ_8S7cTTE:bjmg523) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/635fb3855265ff00fb1f4ef2698b58fc56f0514e/talpid-core/src/firewall/windows.rs#L322)):*
> ```Rust
> 
>     #[allow(dead_code)]
>     #[repr(u32)]
> ```

Is this representation currently wrong on master or does this PR also change the C++ version? I only see the `WINFW_CLEANUP_POLICY` enum, but it does not specify type as far as I can see :thinking: 


<!-- Sent from Reviewable.io -->

2020-10-07 14:28 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168)* status: 15 of 17 files reviewed, 2 unresolved discussions (waiting on @faern and @mvd-ows)

___
*[mullvad-daemon/src/lib.rs, line 644 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168#-MJ2KClqDFPdmsf3OBe1:-MJ2RfRJ8Xd_lz0FeJQt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/635fb3855265ff00fb1f4ef2698b58fc56f0514e/mullvad-daemon/src/lib.rs#L644)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we get a comment here? Explaining that on daemon shut down we block the firewall if `auto-connect` is enabled, in order to make it properly block all traffic during boot until the daemon can take over again.
</blockquote></details>

Done.
___
*[talpid-core/src/firewall/windows.rs, line 322 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168#-MJ2LvVGC1bQ_8S7cTTD:-MJ2RjOf9o5-eoSey-ty:byfiw39) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/635fb3855265ff00fb1f4ef2698b58fc56f0514e/talpid-core/src/firewall/windows.rs#L322)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is this representation currently wrong on master or does this PR also change the C++ version? I only see the `WINFW_CLEANUP_POLICY` enum, but it does not specify type as far as I can see :thinking: 
</blockquote></details>

It is wrong on master. The underlying type here will be [`int`](https://en.cppreference.com/w/cpp/types/underlying_type), since none is specified, i.e. 32 bits in this case. I've changed it to `uint32_t` for clarity now (and because `int` is not fixed).


<!-- Sent from Reviewable.io -->

2020-10-08 08:27 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168)* status: 15 of 17 files reviewed, 2 unresolved discussions (waiting on @dlon, @faern, and @mvd-ows)

___
*[talpid-core/src/firewall/windows.rs, line 322 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168#-MJ2LvVGC1bQ_8S7cTTD:-MJ6JGGc0wK8aSUguOiZ:b-grk8if) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/635fb3855265ff00fb1f4ef2698b58fc56f0514e/talpid-core/src/firewall/windows.rs#L322)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It is wrong on master. The underlying type here will be [`int`](https://en.cppreference.com/w/cpp/types/underlying_type), since none is specified, i.e. 32 bits in this case. I've changed it to `uint32_t` for clarity now (and because `int` is not fixed).
</blockquote></details>

:O So the ABI for the function wall was wrong then. How did this not cause issues? If it's guaranteed to not cause call issues on current `master` this is fine to just change without much fanfare. But otherwise I would like this to be a `### Fixed` changelog entry maybe?
Do we have any idea if this could have caused issues?


<!-- Sent from Reviewable.io -->

2020-10-08 10:20 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168)* status: 15 of 17 files reviewed, 2 unresolved discussions (waiting on @faern and @mvd-ows)

___
*[talpid-core/src/firewall/windows.rs, line 322 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168#-MJ2LvVGC1bQ_8S7cTTD:-MJ6hLOn1IcVJYpvYVLE:bvf8m8i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/635fb3855265ff00fb1f4ef2698b58fc56f0514e/talpid-core/src/firewall/windows.rs#L322)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

:O So the ABI for the function wall was wrong then. How did this not cause issues? If it's guaranteed to not cause call issues on current `master` this is fine to just change without much fanfare. But otherwise I would like this to be a `### Fixed` changelog entry maybe?
Do we have any idea if this could have caused issues?
</blockquote></details>

I investigated this. The short answer is that it was not a problem in practice.

Here is a small C program containing a function with a signature equivalent to that of `WinFw_Deinitialize`:

```
extern "C"
__declspec(dllexport)
__declspec(noinline)
void __stdcall testfunc(int a)
{
	std::cout << a << std::endl;
}

typedef void(*wrongfuncsig)(unsigned char);
```

A normal call to the function `testfunc` in C produces the following code:

```
	testfunc(1);
mov         ecx,1
call        testfunc (07FF6B2D31000h) 
```

And using a function pointer (with the incorrect signature):

```
	wrongfuncsig func = (wrongfuncsig)testfunc;
	func(1);
mov         cl,1  
call        testfunc (07FF6B2D31000h)  
```

As you can tell, only the lowest fourth of the `ecx` register is set when using the wrong signature. I could show this on the Rust side:

```
#![feature(asm)]

extern "system" {
    #[link_name = "testfunc"]
    pub fn testfunc(a: u8);
}

fn main() {
    unsafe {
        asm!("mov ecx, 0xffffffff");
        testfunc(1);
    }
}
```

This outputs `-255` (i.e., `ffffff01`).

However, calling `testfunc` with the argument 0 works as expected. The assembly code reveals why:

```
	movl	$4294967295, %ecx
	xorl	%ecx, %ecx
	popq	%rax
	jmp	testfunc
```

When `testfunc(0)` is called, the entire `ecx` register is zeroed.

Conclusion:

`WinFw_Deinitialize(WINFW_CLEANUP_POLICY_RESET_FIREWALL)` on master is not likely to produce the right value for `cleanupPolicy`.

However, the code only ever passed the argument `WINFW_CLEANUP_POLICY_CONTINUE_BLOCKING`, whose value is 0, to the function. This zeroes the entire registry that represents the argument.

So in practice, this bug was never an issue.


<!-- Sent from Reviewable.io -->

2020-10-08 11:51 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168)* status: 15 of 17 files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[talpid-core/src/firewall/windows.rs, line 322 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168#-MJ2LvVGC1bQ_8S7cTTD:-MJ71zmZBywDqJwrCFN_:ba39s9m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/635fb3855265ff00fb1f4ef2698b58fc56f0514e/talpid-core/src/firewall/windows.rs#L322)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I investigated this. The short answer is that it was not a problem in practice.

Here is a small C program containing a function with a signature equivalent to that of `WinFw_Deinitialize`:

```
extern "C"
__declspec(dllexport)
__declspec(noinline)
void __stdcall testfunc(int a)
{
	std::cout << a << std::endl;
}

typedef void(*wrongfuncsig)(unsigned char);
```

A normal call to the function `testfunc` in C produces the following code:

```
	testfunc(1);
mov         ecx,1
call        testfunc (07FF6B2D31000h) 
```

And using a function pointer (with the incorrect signature):

```
	wrongfuncsig func = (wrongfuncsig)testfunc;
	func(1);
mov         cl,1  
call        testfunc (07FF6B2D31000h)  
```

As you can tell, only the lowest fourth of the `ecx` register is set when using the wrong signature. I could show this on the Rust side:

```
#![feature(asm)]

extern "system" {
    #[link_name = "testfunc"]
    pub fn testfunc(a: u8);
}

fn main() {
    unsafe {
        asm!("mov ecx, 0xffffffff");
        testfunc(1);
    }
}
```

This outputs `-255` (i.e., `ffffff01`).

However, calling `testfunc` with the argument 0 works as expected. The assembly code reveals why:

```
	movl	$4294967295, %ecx
	xorl	%ecx, %ecx
	popq	%rax
	jmp	testfunc
```

When `testfunc(0)` is called, the entire `ecx` register is zeroed.

Conclusion:

`WinFw_Deinitialize(WINFW_CLEANUP_POLICY_RESET_FIREWALL)` on master is not likely to produce the right value for `cleanupPolicy`.

However, the code only ever passed the argument `WINFW_CLEANUP_POLICY_CONTINUE_BLOCKING`, whose value is 0, to the function. This zeroes the entire registry that represented the argument.

So in practice, this bug was never an issue.
</blockquote></details>

Great research and explanation! So all current releases are safe in practice then. Good. Great it's fixed however!

Any way we could/should adopt our FFI or Rust/C++ guidelines to prevent such issues in the future? We should probably always explicitly state the integer representation type on enums on both sides as a first step.


<!-- Sent from Reviewable.io -->

2020-10-08 11:52 UTC, faern reviewed
> Reviewed 1 of 12 files at r2, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168)* status: 16 of 17 files reviewed, all discussions resolved (waiting on @mvd-ows)



<!-- Sent from Reviewable.io -->

2020-10-08 12:13 UTC, mvd-ows approved these changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-08 12:57 UTC, dlon commented
> 
> 
> > _[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168)_ status: 15 of 17 files reviewed, all discussions resolved (waiting on @mvd-ows)
> 
> _[talpid-core/src/firewall/windows.rs, line 322 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168#-MJ2LvVGC1bQ_8S7cTTD:-MJ71zmZBywDqJwrCFN_:ba39s9m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/635fb3855265ff00fb1f4ef2698b58fc56f0514e/talpid-core/src/firewall/windows.rs#L322)):_
> Previously, dlon (David Lönnhager) wrote…
> 
> Great research and explanation! So all current releases are safe in practice then. Good. Great it's fixed however!
> 
> Any way we could/should adopt our FFI or Rust/C++ guidelines to prevent such issues in the future? We should probably always explicitly state the integer representation type on enums on both sides as a first step.

Reviewable broke for me. Anyway, that seems like a good idea.

2020-10-09 09:41 UTC, dlon reviewed
> Reviewed 10 of 25 files at r1, 1 of 12 files at r2, 4 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-09 09:51 UTC, faern approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-09 10:09 UTC, merged