Avoid unnecessary rebuilds in build.sh
mullvad/mullvadvpn-app pull request #2174
Opened 2020-10-08 14:34 UTC by dlon

Currently, `build.sh` builds all dependencies three times: Once when `cargo build` is run, once before the CLI is used to generate shell completions, and once before running the relay list updater.

2020-10-09 13:53 UTC, faern requested changes
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2174)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[update-relays.sh, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2174#-MJCbYqT9npsRS4AywSB:-MJCbYqT9npsRS4AywSC:b-5srzu0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6fb0dee8512d2429a2dec8f3db7c7046707002ef/update-relays.sh#L11)):*
> ```Shell
> else
>     CARGO_TOOLCHAIN=""
>     CARGO_ARGS=""
> ```

Do we actually need to support it running under unspecified toolchain and not in release compile mode? Is there any case where it would not work to just force `+stable --release`? I mean for the sake of simplifying the script and all callsites to it?
___
*[mullvad-cli/src/main.rs, line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2174#-MJCcQDH9bORXbH1dtCA:-MJCcQDH9bORXbH1dtCB:b-d7jrkk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6d010e40eae0fbba4fed8381a7c887aceee79ce/mullvad-cli/src/main.rs#L53)):*
> ```Rust
>     let app = build_cli(&commands);
> 
>     #[cfg(feature = "shell-completions")]
> ```

If we decide to go with always including it, but hiding it. Then you can remove the feature from `Cargo.toml` altogether?
___
*[talpid-core/Cargo.toml, line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2174#-MJCbsms4NMLt-gz9YQd:-MJCbsms4NMLt-gz9YQe:bx82jsv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6d010e40eae0fbba4fed8381a7c887aceee79ce/talpid-core/Cargo.toml#L60)):*
> ```TOML
> netlink-sys = "0.4"
> byteorder = "1"
> futures = { package = "futures", version = "0.3" }
> ```

Why do we need `futures = "0.3"` at all under Linux specifically when it's already under the global `[dependencies]` being pulled in on all platforms?


<!-- Sent from Reviewable.io -->

2020-10-09 14:14 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2174)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[update-relays.sh, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2174#-MJCbYqT9npsRS4AywSB:-MJCgluV6SWCnPRkck0H:be5p58c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6fb0dee8512d2429a2dec8f3db7c7046707002ef/update-relays.sh#L11)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Do we actually need to support it running under unspecified toolchain and not in release compile mode? Is there any case where it would not work to just force `+stable --release`? I mean for the sake of simplifying the script and all callsites to it?
</blockquote></details>

Done. I was thinking about the case of building the app without using `build.sh`, where you might not want to build everything using that config.
___
*[mullvad-cli/src/main.rs, line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2174#-MJCcQDH9bORXbH1dtCA:-MJChZRiCUPDC21NUoI6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6d010e40eae0fbba4fed8381a7c887aceee79ce/mullvad-cli/src/main.rs#L53)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

If we decide to go with always including it, but hiding it. Then you can remove the feature from `Cargo.toml` altogether?
</blockquote></details>

Done.
___
*[talpid-core/Cargo.toml, line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2174#-MJCbsms4NMLt-gz9YQd:-MJChaDm-RartoICPD2f:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6d010e40eae0fbba4fed8381a7c887aceee79ce/talpid-core/Cargo.toml#L60)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why do we need `futures = "0.3"` at all under Linux specifically when it's already under the global `[dependencies]` being pulled in on all platforms?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-09 14:49 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2174#-:-MJCpb556_y_FNDThBB4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[update-relays.sh, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2174#-MJCbYqT9npsRS4AywSB:-MJCp0kK00W-u_Ypsyrj:b-gm5yl5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6fb0dee8512d2429a2dec8f3db7c7046707002ef/update-relays.sh#L11)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. I was thinking about the case of building the app without using `build.sh`, where you might not want to build everything using that config.
</blockquote></details>

Our build scripts are already pretty complex and fragile. We quite often forget to update stuff when things change. So I would opt for fewer ways of building and supporting them better rather than supporting everything.

If people really need the relay list but does not want the things this script forces them to use, they can just build+run that binary manually.


<!-- Sent from Reviewable.io -->

2020-10-09 18:48 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2174)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[update-relays.sh, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2174#-MJCbYqT9npsRS4AywSB:-MJDgEA9Cqge4rMDAVMx:b-dxcbts) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6fb0dee8512d2429a2dec8f3db7c7046707002ef/update-relays.sh#L11)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Our build scripts are already pretty complex and fragile. We quite often forget to update stuff when things change. So I would opt for fewer ways of building and supporting them better rather than supporting everything.

If people really need the relay list but does not want the things this script forces them to use, they can just build+run that binary manually.
</blockquote></details>

Makes sense.


<!-- Sent from Reviewable.io -->

2020-10-12 08:55 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2174#-:-MJR0MSU3mJLnb3BsU-Z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-12 09:32 UTC, merged