Clear account history after unlocking firewall during uninstallation.
mullvad/mullvadvpn-app pull request #2175
Opened 2020-10-08 16:10 UTC by pinkisemils

These changes ensure that WireGuard keys are removed regardless of user's configuration. This is achieved by not relying on the daemon but rather `mullvad-setup` to clear the account history and removing the keys via communicating with the API. This is fairly straightforward on Linux and MacOS, but deducing the config directory's path on Windows was a bit more involved - there is now a feature (`deduce-system-service`) that enables `mullvad-paths` to properly deduce the daemon's config directory even when it's not ran from the context of a system service user. This feature is only used by `mullvad-setup`.

2020-10-09 07:55 UTC, dlon requested changes
👍

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-:-MJBLU4sAI9elamqKpin:b44tpx)* status: all files reviewed, 11 unresolved discussions (waiting on @pinkisemils)

___
*[Cargo.lock, line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ88l4UEWYG5OEQa4k7:-MJ88l4UEWYG5OEQa4k8:b-sb8ly3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/Cargo.lock#L0)):*
Most changes here seem unnecessary and should probably be avoided
___
*[dist-assets/windows/installer.nsh, line 600 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ83oIi6a-NCVOfxvbx:-MJ83oIi6a-NCVOfxvby:bqevps2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/dist-assets/windows/installer.nsh#L600)):*
> ```NSIS
> 	Push $1
> 
> 	SetOutPath "$TEMP"
> ```

Not blocking: These files could be extracted unconditionally in `customRemoveFiles`, since this is also done when upgrading and in `ClearFirewallRules` (the latter of which extracts them a second time).
___
*[mullvad-paths/src/settings.rs, line 111 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ8AZwo6zvMKQkYavO1:-MJ8AZwo6zvMKQkYavO2:b-st3dlf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L111)):*
> ```Rust
>             };
>             if status == FALSE {
>                 unsafe { CloseHandle(lsass_handle) };
> ```

I think you can close this handle just once after calling `OpenProcessToken`. I don't *think* it needs to remain open for the token to be valid.
___
*[mullvad-paths/src/settings.rs, line 151 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ8F0RHD63xknBdBza8:-MJ8F0RHD63xknBdBza9:b-t2wfqc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L151)):*
> ```Rust
>         {
>             let thread_token_error = std::io::Error::last_os_error();
>             if let Some(1008) = thread_token_error.raw_os_error() {
> ```

Using `ERROR_NO_TOKEN` from `winapi::shared::winerror` would be clearer.
___
*[mullvad-paths/src/settings.rs, line 177 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ8L9Px2Vf-RFPRoV5K:-MJ8L9Px2Vf-RFPRoV5L:b-p1iwb8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L177)):*
> ```Rust
>     fn adjust_token_privilege(
>         token_handle: HANDLE,
>         privilege: &WideCString,
> ```

This could be an `&OsStr` (by using [`OsStrExt::encode_wide()`](https://doc.rust-lang.org/std/os/windows/ffi/trait.OsStrExt.html) and adding a `0u16` terminator).
___
*[mullvad-paths/src/settings.rs, line 204 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ8GK6zELlLpcXs2zvw:-MJ8GK6zELlLpcXs2zvx:b10q230) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L204)):*
> ```Rust
>                 ptr::null_mut(),
>             )
>         };
> ```

I think `token_handle` should be closed after this.
___
*[mullvad-paths/src/settings.rs, line 229 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ8B69N5P7ewdwLvJmm:-MJ8B69N5P7ewdwLvJmn:b3q1m4d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L229)):*
> ```Rust
>                 ));
>             }
>             WideCStr::from_ptr_str(folder_path)
> ```

I wonder if it would be worth it to use [`OsStringExt::from_wide`](https://doc.rust-lang.org/std/os/windows/ffi/trait.OsStringExt.html) here, and not depend on `widestring`.

Probably not, since you'd have to manually find the `0u16` terminator (or use `wcslen` from libc). I don't know if there is a better way:
```
unsafe fn wcslen(a: *const u16) -> usize {
    let mut len = 0;
    while *a.offset(len) != 0u16 {
        len += 1;
    }
    len
}
```
___
*[mullvad-paths/src/settings.rs, line 230 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ8Li270X06VBKQcLFO:-MJ8Li270X06VBKQcLFP:b-opw91) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L230)):*
> ```Rust
>             }
>             WideCStr::from_ptr_str(folder_path)
>         };
> ```

There is a memory leak here. `CoTaskMemFree` should be used to free the original string.
___
*[mullvad-paths/src/settings.rs, line 247 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ8J57WAsghmr-eQ2Jq:-MJ8J57WAsghmr-eQ2Jr:bso0t76) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L247)):*
> ```Rust
>         pid_buffer.resize(num_procs as usize, 0);
>         let bytes_available = num_procs * (mem::size_of::<DWORD>() as u32);
>         if unsafe { K32EnumProcesses(pid_buffer.as_mut_ptr(), bytes_available, &mut num_procs) }
> ```

The last argument receives the number of bytes used by the array, not the number of processes. I think `pid_buffer` should be resized afterwards too.
___
*[mullvad-paths/src/settings.rs, line 258 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ839KkB0e_WZekt-6u:-MJ839KkB0e_WZekt-6v:b-eg8oim) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L258)):*
> ```Rust
>                 log::error!("Failed to open process {}", process);
>                 continue;
>             };
> ```

Unnecessary semicolon
___
*[mullvad-paths/src/settings.rs, line 262 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ82iLgAk-yTFQpX93R:-MJ82iLgAk-yTFQpX93S:bpuxhwj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L262)):*
> ```Rust
> 
>             let mut process_name = vec![0u16; 512];
>             let mut process_name_size = (process_name.len() * mem::size_of::<DWORD>()) as u32;
> ```

This argument should be specified in characters, not bytes.
___
*[mullvad-paths/src/settings.rs, line 284 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ8Hgs3BkDChBBbvdgh:-MJ8Hgs3BkDChBBbvdgi:b-4v0moe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L284)):*
> ```Rust
>             let canonical_process_path = process_path.canonicalize().unwrap_or(process_path);
> 
>             unsafe { CloseHandle(process_handle) };
> ```

This looks like a double free.
___
*[mullvad-setup/src/main.rs, line 122 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ88P1J4MMHGItRUThI:-MJ88P1J4MMHGItRUThJ:b85egi3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-setup/src/main.rs#L122)):*
> ```Rust
>         .await
>         .map_err(Error::ClearAccountHistoryError)?;
>     println!("Successfully cleared account history and all associated keys");
> ```

This essentially repeats what `AccountHistory::clear_history` prints. But no user will see this, so it doesn't matter.


<!-- Sent from Reviewable.io -->

2020-10-09 11:15 UTC, dlon approved these changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175)* status: all files reviewed, 4 unresolved discussions (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2020-10-09 11:34 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[Cargo.lock, line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ88l4UEWYG5OEQa4k7:-MJC7B354Jt0pUjaR9H6:b-s3yv0j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/Cargo.lock#L)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Most changes here seem unnecessary and should probably be avoided
</blockquote></details>

I've not clue what triggers these changes.
___
*[mullvad-paths/src/settings.rs, line 177 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ8L9Px2Vf-RFPRoV5K:-MJBxvZg-kwEwESdCbAM:b-l1yozo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L177)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This could be an `&OsStr` (by using [`OsStrExt::encode_wide()`](https://doc.rust-lang.org/std/os/windows/ffi/trait.OsStrExt.html) and adding a `0u16` terminator).
</blockquote></details>

Not a big fan of not being able to tell whether an `OsString` should have a trailing `\0` or not, so I'll leave it as is.
___
*[mullvad-paths/src/settings.rs, line 204 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ8GK6zELlLpcXs2zvw:-MJBk7IX-9e7RDmE4jMQ:b131rz3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L204)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think `token_handle` should be closed after this.
</blockquote></details>

Closed it in the caller.
___
*[mullvad-paths/src/settings.rs, line 230 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ8Li270X06VBKQcLFO:-MJBwx1pAznFGRVFuYQa:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L230)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

There is a memory leak here. `CoTaskMemFree` should be used to free the original string.
</blockquote></details>

Done.
___
*[mullvad-paths/src/settings.rs, line 247 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ8J57WAsghmr-eQ2Jq:-MJBnJ1EDj__hqfT3MFM:b-hjmjyh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L247)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The last argument receives the number of bytes used by the array, not the number of processes. I think `pid_buffer` should be resized afterwards too.
</blockquote></details>

You are correct! 
___
*[mullvad-paths/src/settings.rs, line 262 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ82iLgAk-yTFQpX93R:-MJBnt1348Nq8st6NNAT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L262)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This argument should be specified in characters, not bytes.
</blockquote></details>

Done.
___
*[mullvad-paths/src/settings.rs, line 284 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-MJ8Hgs3BkDChBBbvdgh:-MJBny7qCaTdrYYwQlnW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/21311aca4fe26b390067473f697215d159904478/mullvad-paths/src/settings.rs#L284)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This looks like a double free.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-09 12:09 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)



<!-- Sent from Reviewable.io -->

2020-10-09 16:09 UTC, pinkisemils reviewed
Turns out that specifying a feature of a dependency for one crate in a workspace will turn that feature on for all crates in the workspace. This is wrong, the daemon shouldn't be stealing tokens to get it's config path, so I just moved all of the path deducing code to `mullvad-setup`. 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-:-MJD6H9n3tPBNwlV0eP7:b-9ap1wf)* status: 5 of 12 files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)



<!-- Sent from Reviewable.io -->

2020-10-09 18:11 UTC, dlon approved these changes
> Reviewed 8 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)



<!-- Sent from Reviewable.io -->

2020-10-09 18:34 UTC, dlon approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-12 11:45 UTC, dlon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175#-:-MJRcBBB3khflVrHn3LM:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-12 12:34 UTC, merged