Upgrade to TypeScript 4
mullvad/mullvadvpn-app pull request #2183
Opened 2020-10-15 15:30 UTC by raksooo

This PR upgrades the dependency on TypeScript to `4.0.3` and also updates `@typesscript-eslint/*` to correctly lint the new version. Some code adjustments were required to make the code conform to some new linting rules.

TypeScript changes: https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2020-10-15 15:34 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183)* status: 0 of 8 files reviewed, 1 unresolved discussion

___
*[gui/src/main/daemon-rpc.ts, line 953 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183#-MJgtH4l1t54uS6HMjDK:-MJgtH4l1t54uS6HMjDL:b-87hb79) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fe3e53756d2d5212b4f8592bae9ac33972f5126/gui/src/main/daemon-rpc.ts#L953)):*
> ```XML
>       address: remoteSettings?.address!,
>       auth: {
>         ...remoteSettings?.auth!,
> ```

This is really ugly and caused some linting issue.
___
*[gui/src/renderer/components/Connect.tsx, line 191 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183#-MJgtCYI6Qeeb0Osfmyj:-MJgtCYI6Qeeb0Osfmyk:b-bxz6ws) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fe3e53756d2d5212b4f8592bae9ac33972f5126/gui/src/renderer/components/Connect.tsx#L191)):*
> ```XML
>           case 'nothing':
>             return HeaderBarStyle.error;
>           default:
> ```

There are no more cases.
___
*[gui/types/gettext-parser/index.d.ts, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183#-MJgsqDU0KGyB4-c954j:-MJgsqDVBZwactOJigPp:b-y3pxqr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cf81624ad4e9ea818dcda31a365a85c888d072d/gui/types/gettext-parser/index.d.ts#L4)):*
> ```XML
>   export namespace po {
>     // eslint-disable-next-line @typescript-eslint/ban-types
>     export function parse(input: string | Buffer, defaultCharset?: string): object;
> ```

The type `object` is discouraged but in this case we have no choice since `node-gettext` takes an `object` as argument. The rule makes sense though so I opted for just disabling it here and keeping it active everywhere else.


<!-- Sent from Reviewable.io -->

2020-10-16 08:15 UTC, pronebird reviewed
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/daemon-rpc.ts, line 953 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183#-MJgtH4l1t54uS6HMjDK:-MJkRqRLBCN4dMclaa3X:b-v0gui7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fe3e53756d2d5212b4f8592bae9ac33972f5126/gui/src/main/daemon-rpc.ts#L953)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

This is really ugly and caused some linting issue.
</blockquote></details>

Speaking of mutability, maybe we could keep the spread or use `Object.assign` to produce a copy of `auth` or, hell, maybe even duplicate all fields manually?


<!-- Sent from Reviewable.io -->

2020-10-16 08:34 UTC, pronebird reviewed
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2020-10-16 08:49 UTC, pronebird reviewed
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/types/gettext-parser/index.d.ts, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183#-MJgsqDU0KGyB4-c954j:-MJkTS_d5waE8BBseoFi:b39asjl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cf81624ad4e9ea818dcda31a365a85c888d072d/gui/types/gettext-parser/index.d.ts#L4)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

The type `object` is discouraged but in this case we have no choice since `node-gettext` takes an `object` as argument. The rule makes sense though so I opted for just disabling it here and keeping it active everywhere else.
</blockquote></details>

Can you switch us to `@types/gettext-parser`? It's pretty complete. 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gettext-parser/index.d.ts


<!-- Sent from Reviewable.io -->

2020-10-16 08:49 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2020-10-16 08:55 UTC, pronebird requested changes
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[gui/src/shared/gettext.ts, line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183#-MJkbhD42qN6FzSUt_Rp:-MJkbhD42qN6FzSUt_Rq:bo02no) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cf81624ad4e9ea818dcda31a365a85c888d072d/gui/src/shared/gettext.ts#L54)):*
> ```XML
> 
>   // eslint-disable-next-line @typescript-eslint/ban-types
>   let translations: object;
> ```

Maybe we can use `GetTextTranslations` type from `@types/gettext-parser` instead of `object`.


<!-- Sent from Reviewable.io -->

2020-10-16 08:56 UTC, pronebird reviewed
> Reviewed 4 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2020-10-16 09:01 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/src/shared/gettext.ts, line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183#-MJkbhD42qN6FzSUt_Rp:-MJkcf8Z5HT2c52Wg2QQ:b-cu4iz3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cf81624ad4e9ea818dcda31a365a85c888d072d/gui/src/shared/gettext.ts#L54)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe we can use `GetTextTranslations` type from `@types/gettext-parser` instead of `object`.
</blockquote></details>

I went with `ReturnType<typeof po.parse>` since the actual type doesn't really matter to us or tell us anything.
___
*[gui/types/gettext-parser/index.d.ts, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183#-MJgsqDU0KGyB4-c954j:-MJkcXej3MW6L8XrwsMA:b-z2c6xv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cf81624ad4e9ea818dcda31a365a85c888d072d/gui/types/gettext-parser/index.d.ts#L4)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Can you switch us to `@types/gettext-parser`? It's pretty complete. 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gettext-parser/index.d.ts
</blockquote></details>

I didn't know it existed, thanks for letting me know! Done.


<!-- Sent from Reviewable.io -->

2020-10-16 09:07 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @pronebird)

___
*[gui/src/main/daemon-rpc.ts, line 953 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183#-MJgtH4l1t54uS6HMjDK:-MJkeVwuAoztQO3aZ-Sk:bmg28hl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fe3e53756d2d5212b4f8592bae9ac33972f5126/gui/src/main/daemon-rpc.ts#L953)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Speaking of mutability, maybe we could keep the spread or use `Object.assign` to produce a copy of `auth` or, hell, maybe even duplicate all fields manually?
</blockquote></details>

How about this?


<!-- Sent from Reviewable.io -->

2020-10-16 09:09 UTC, pronebird reviewed
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183)* status: 5 of 8 files reviewed, all discussions resolved (waiting on @pronebird)

___
*[gui/src/main/daemon-rpc.ts, line 953 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183#-MJgtH4l1t54uS6HMjDK:-MJkeoFz6DM2vq-QGjwS:b-vs1pr4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fe3e53756d2d5212b4f8592bae9ac33972f5126/gui/src/main/daemon-rpc.ts#L953)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

How about this?
</blockquote></details>

Looks good.


<!-- Sent from Reviewable.io -->

2020-10-16 09:09 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183#-:-MJkeysP6ZKMuIDsqOlU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-16 09:25 UTC, merged