Fix non-working button in NotificationBanner
mullvad/mullvadvpn-app pull request #2184
Opened 2020-10-15 15:43 UTC by raksooo

The buttons in the in-app notifications doesn't work since they don't pick up the `onClick` from the `BlockingContext`. This PR fixes that by adding an button without styling that can be used in such situations.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2020-10-15 15:44 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: 0 of 4 files reviewed, 1 unresolved discussion

___
*[gui/src/renderer/components/AppButton.tsx, line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184#-MJgvcum1T0cQ8_p_405:-MJgvcunClD_Hzy6Z1Sv:bx44hoi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fb43565fba7b3b087490f5126a9c1a166a7bdf8e/gui/src/renderer/components/AppButton.tsx#L101)):*
> ```XML
>       {...props}
>       disabled={props.disabled || blockingContext.disabled}
>       onClick={blockingContext.onClick ?? props.onClick}>
> ```

Maybe it would be more reasonable to call both callbacks?


<!-- Sent from Reviewable.io -->

2020-10-16 08:58 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[CHANGELOG.md, line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184#-MJkcKOCEUPsBbvJdloe:-MJkcKOCEUPsBbvJdlof:b-nvia8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fb43565fba7b3b087490f5126a9c1a166a7bdf8e/CHANGELOG.md#L40)):*
> ```Markdown
> 
> ### Fixed
> - Fix non-working buttons in in-app notification banner.
> ```

Maybe fix "broken buttons" instead of non-working? I mean the meaning is the same but it sounds odd to say it that way.


<!-- Sent from Reviewable.io -->

2020-10-16 08:59 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/components/AppButton.tsx, line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184#-MJgvcum1T0cQ8_p_405:-MJkceZaAwdO9JLzrRGp:b7i0xpv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fb43565fba7b3b087490f5126a9c1a166a7bdf8e/gui/src/renderer/components/AppButton.tsx#L101)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Maybe it would be more reasonable to call both callbacks?
</blockquote></details>

Does `BlockingContext` need to handle clicks?


<!-- Sent from Reviewable.io -->

2020-10-16 09:11 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/src/renderer/components/AppButton.tsx, line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184#-MJgvcum1T0cQ8_p_405:-MJkeuIA5YuTsKPojtzo:bez2dnx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fb43565fba7b3b087490f5126a9c1a166a7bdf8e/gui/src/renderer/components/AppButton.tsx#L101)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Does `BlockingContext` need to handle clicks?
</blockquote></details>

The `BlockingButton` component needs to handle clicks since it blocks the button until the callback is done.
```
  const onClick = useCallback(async () => {
    setIsBlocked(true);
    try {
      await props.onClick();
    } catch (error) {
      log.error(`onClick() failed - ${error}`);
    }

    if (isMounted()) {
      setIsBlocked(false);
    }
  }, [props.onClick]);

```


<!-- Sent from Reviewable.io -->

2020-10-16 09:12 UTC, pronebird reviewed
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/AppButton.tsx, line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184#-MJgvcum1T0cQ8_p_405:-MJkdB_LAs8fUc_pwWpN:b-esi5mr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fb43565fba7b3b087490f5126a9c1a166a7bdf8e/gui/src/renderer/components/AppButton.tsx#L101)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

The `BlockingButton` component needs to handle clicks since it blocks the button until the callback is done.
```
  const onClick = useCallback(async () => {
    setIsBlocked(true);
    try {
      await props.onClick();
    } catch (error) {
      log.error(`onClick() failed - ${error}`);
    }

    if (isMounted()) {
      setIsBlocked(false);
    }
  }, [props.onClick]);

```
</blockquote></details>

Ok it actually needs to. Your answer is above, i.e the blockingContext calls the `onClick` so we don't need to call both callbacks.


<!-- Sent from Reviewable.io -->

2020-10-16 09:13 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/AppButton.tsx, line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184#-MJgvcum1T0cQ8_p_405:-MJkfh4m3fBpW6wlXQvY:b-z2mqwp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fb43565fba7b3b087490f5126a9c1a166a7bdf8e/gui/src/renderer/components/AppButton.tsx#L101)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Ok it actually needs to. Your answer is above, i.e the blockingContext calls the `onClick` so we don't need to call both callbacks.
</blockquote></details>

Alright. Looked at the entire code now. Seems like we have two `onClick`..


<!-- Sent from Reviewable.io -->

2020-10-16 09:22 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/AppButton.tsx, line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184#-MJgvcum1T0cQ8_p_405:-MJkfmEz324x8iN0yJBj:b-5odlag) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fb43565fba7b3b087490f5126a9c1a166a7bdf8e/gui/src/renderer/components/AppButton.tsx#L101)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Alright. Looked at the entire code now. Seems like we have two `onClick`..
</blockquote></details>

Well... I don't see any purpose in having two onClick handlers. It's not the most beautiful design I guess to enchance buttons in such way. 

It's also possible to rewrite that in such a way that the button's `onClick` is the actionable one, i.e:

```
const onClick = useCallback(async (theButtonOnClick) => {
    setIsBlocked(true);
    const maybePromise = theButtonOnClick();
    if ( myIsPromise(maybePromise) ) {
      try {
        // or rewrite with then+catch+finally
        await maybePromise;
      } catch (error) {
        log.error(`onClick() failed - ${error}`);
      }
   }

   if (isMounted()) {
     setIsBlocked(false);
   }
  }, [props.onClick]);
```


<!-- Sent from Reviewable.io -->

2020-10-16 09:26 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/AppButton.tsx, line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184#-MJgvcum1T0cQ8_p_405:-MJki9FW5R5Zyn_agkBJ:b-alm1j7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fb43565fba7b3b087490f5126a9c1a166a7bdf8e/gui/src/renderer/components/AppButton.tsx#L101)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Well... I don't see any purpose in having two onClick handlers. It's not the most beautiful design I guess to enchance buttons in such way. 

It's also possible to rewrite that in such a way that the button's `onClick` is the actionable one, i.e:

```
const onClick = useCallback(async (theButtonOnClick) => {
    setIsBlocked(true);
    const maybePromise = theButtonOnClick();
    if ( myIsPromise(maybePromise) ) {
      try {
        // or rewrite with then+catch+finally
        await maybePromise;
      } catch (error) {
        log.error(`onClick() failed - ${error}`);
      }
   }

   if (isMounted()) {
     setIsBlocked(false);
   }
  }, [props.onClick]);
```
</blockquote></details>

Also in the above design I'd rename `BlockingButton` to `UserInteractionRestriction` or something like that, which would allow to group elements that need to be mutually exclusive when certain action is performed. Can be more universal than just specific buttons, i.e fading elements, like buttons in response to restriction or in simple terms, when the part of interface is disabled or blocked for user interaction.


<!-- Sent from Reviewable.io -->

2020-10-16 09:28 UTC, pronebird requested changes
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/components/AppButtonStyles.tsx, line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184#-MJkjBMrEmRPHRBizc79:-MJkjBMrEmRPHRBizc7A:bghn5i5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fe3e53756d2d5212b4f8592bae9ac33972f5126/gui/src/renderer/components/AppButtonStyles.tsx#L16)):*
> ```XML
> });
> 
> export const StyledButton = styled.button({
> ```

This change is somewhat superficial. You could leave the `StyledButton` in here & use it from AppButton as is.


<!-- Sent from Reviewable.io -->

2020-10-16 09:30 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/AppButtonStyles.tsx, line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184#-MJkjBMrEmRPHRBizc79:-MJkjO7I7M_lTLugr_Wl:bz6dtdv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5fe3e53756d2d5212b4f8592bae9ac33972f5126/gui/src/renderer/components/AppButtonStyles.tsx#L16)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This change is somewhat superficial. You could leave the `StyledButton` in here & use it from AppButton as is.
</blockquote></details>

Oh maybe not, given the subclassing.


<!-- Sent from Reviewable.io -->

2020-10-16 09:31 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/AppButton.tsx, line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184#-MJgvcum1T0cQ8_p_405:-MJkjrw-1PAHe6z3E8SX:b5zxfer) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fb43565fba7b3b087490f5126a9c1a166a7bdf8e/gui/src/renderer/components/AppButton.tsx#L101)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Also in the above design I'd rename `BlockingButton` to `UserInteractionRestriction` or something like that, which would allow to group elements that need to be mutually exclusive when certain action is performed. Can be more universal than just specific buttons, i.e fading elements, like buttons in response to restriction or in simple terms, when the part of interface is disabled or blocked for user interaction.
</blockquote></details>

I meant fading elements like icons, not buttons. Either way. Seems like we may not need to go that far.


<!-- Sent from Reviewable.io -->

2020-10-16 09:32 UTC, pronebird reviewed
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2020-10-16 09:56 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-16 11:03 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[CHANGELOG.md, line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184#-MJkcKOCEUPsBbvJdloe:-MJl3kbO8zy4WtQoBliu:bo9xsot) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fb43565fba7b3b087490f5126a9c1a166a7bdf8e/CHANGELOG.md#L40)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe fix "broken buttons" instead of non-working? I mean the meaning is the same but it sounds odd to say it that way.
</blockquote></details>

I removed the changelog entry since this issue has never been released and will be backported to the current beta.
___
*[gui/src/renderer/components/AppButton.tsx, line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184#-MJgvcum1T0cQ8_p_405:-MJl3yAyDJs0ZbAflMWv:b-gnxt6z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fb43565fba7b3b087490f5126a9c1a166a7bdf8e/gui/src/renderer/components/AppButton.tsx#L101)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I meant fading elements like icons, not buttons. Either way. Seems like we may not need to go that far.
</blockquote></details>

I agree that this could be improved but since this will be backported to the beta I think we should keep the changes to a minimum.


<!-- Sent from Reviewable.io -->

2020-10-16 12:01 UTC, pronebird approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-16 12:01 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-16 12:01 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-16 12:52 UTC, merged