Fix login screen error message
mullvad/mullvadvpn-app pull request #2213
Opened 2020-10-26 15:30 UTC by pronebird

… error (i.e too many WireGuard keys)

Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [X] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

- This PR fixes a regression where "Internal error" was displayed instead of server error (i.e too many WireGuard keys).
- Add missing CHANGELOG entry for a communication protocol transition from JSON-RPC -> REST (as per @faern's request)

2020-10-26 15:35 UTC, faern requested changes
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2213)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/MullvadRest.swift, line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2213#-MK_Xexx4MKcfrqNRr0B:-MK_Xexx4MKcfrqNRr0C:b4sf51b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6bdd824f45d6623ac463f98b2667fdf21baec1c4/ios/MullvadVPN/MullvadRest.swift#L54)):*
> ```Swift
>         switch code {
>         case Code.keyLimitReached.rawValue:
>             return NSLocalizedString("Too many public WireGuard keys", comment: "")
> ```

Change to "Too many WireGuard keys in use" as per slack discussion?


<!-- Sent from Reviewable.io -->

2020-10-26 15:44 UTC, faern reviewed
I'll leave the code change review up to @jvff. I approved changelog and string changes :)

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2213#-:-MK__88nAhJfZfevrVCV:b-4oxdpg)* status: 2 of 3 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-26 17:04 UTC, jvff approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2213#-:-MK_rVoECJtt5VI2zkWB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/LoginViewController.swift, line 342 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2213#-MK_quOA3olA8Yj5h7Ny:-MK_quOB1XnjZlNIISjz:b-q8txz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df93dc43797b804e561c3b6b30011f9062fe006f/ios/MullvadVPN/LoginViewController.swift#L342)):*
> ```Swift
>                             message.append("\n\(recoverySuggestion)")
>                         }
>                         
> ```

I think XCode left some trailing whitespace again


<!-- Sent from Reviewable.io -->

2020-10-27 08:45 UTC, faern approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2213)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2020-10-27 08:57 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2213)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @jvff)

___
*[ios/MullvadVPN/LoginViewController.swift, line 342 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2213#-MK_quOA3olA8Yj5h7Ny:-MKdGlQQ271BaHvO39PH:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df93dc43797b804e561c3b6b30011f9062fe006f/ios/MullvadVPN/LoginViewController.swift#L342)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think XCode left some trailing whitespace again
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2020-10-27 10:18 UTC, faern reviewed
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2213)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2020-10-27 10:21 UTC, jvff approved these changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2213)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-27 12:48 UTC, jvff approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2213)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-27 12:52 UTC, merged