Allow more device states with NM DNS
mullvad/mullvadvpn-app pull request #2217
Opened 2020-10-27 15:19 UTC by pinkisemils

Seems like on a lot of Ubuntu 20.04 machines (and sister-distros), NM takes some time to get to the final `NM_DEVICE_STATE_ACTIVATED` state, even though any device state after [`NM_DEVICE_STATE_IP_CHECK`](https://developer.gnome.org/NetworkManager/stable/nm-dbus-types.html#NMDeviceState) should mean that the device is ready for our DNS config. Since sometimes NM can also be slow to detect that a device is ready, I made a drastic choice to bump the timeout to 15 seconds and also now more states are considered to be OK.

2020-10-27 15:40 UTC, dlon requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217)* status: all files reviewed, 3 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/src/dns/linux/network_manager.rs, line 72 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217#-MKehNf1CNX_28O4SQWI:-MKehNf1CNX_28O4SQWJ:b-sqx5ux) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86d2464967b8338e9b3493da1ce0fb73f735dbdd/talpid-core/src/dns/linux/network_manager.rs#L72)):*
> ```Rust
> 
> const NM_DEVICE_STATE_IP_CHECK: u32 = 80;
> const NM_DEVICE_STATE_SECONDARY: u32 = 90;
> ```

The original constant is called `NM_DEVICE_STATE_SECONDARIES`.
___
*[talpid-core/src/dns/linux/network_manager.rs, line 360 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217#-MKeflCf2sI7RUbt5DXA:-MKeflCf2sI7RUbt5DXB:b-p27ow8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86d2464967b8338e9b3493da1ce0fb73f735dbdd/talpid-core/src/dns/linux/network_manager.rs#L360)):*
> ```Rust
>                 .map_err(Error::Dbus)?;
> 
>             if device_is_ready(device_state) {
> ```

`!` is missing.
___
*[talpid-core/src/dns/linux/network_manager.rs, line 366 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217#-MKegiCq2On3l8YrJcHa:-MKegiCq2On3l8YrJcHb:biolg4g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86d2464967b8338e9b3493da1ce0fb73f735dbdd/talpid-core/src/dns/linux/network_manager.rs#L366)):*
> ```Rust
>                 // for TIMEOUT after the last message was received - if the device is thrashing
>                 // between states, we should probably give up rather than block indefinitely.
>                 while Instant::now() < deadline || !device_is_ready(device_state) {
> ```

I think you meant to use `&&` here.
___
*[talpid-core/src/dns/linux/network_manager.rs, line 375 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217#-MKeheSx7xT6ckeqxZSG:-MKeheSx7xT6ckeqxZSH:b37ljp3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86d2464967b8338e9b3493da1ce0fb73f735dbdd/talpid-core/src/dns/linux/network_manager.rs#L375)):*
> ```Rust
>                     );
>                     self.dbus_connection
>                         .add_match(match_rule)
> ```

I think this should be added outside of the loop. Or at least removed before the loop exits.


<!-- Sent from Reviewable.io -->

2020-10-27 15:50 UTC, faern approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217)* status: all files reviewed, 4 unresolved discussions (waiting on @pinkisemils)

___
*[CHANGELOG.md, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217#-MKej4Sn1kUvWfDraXK2:-MKej4Sn1kUvWfDraXK3:b-41lym0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86d2464967b8338e9b3493da1ce0fb73f735dbdd/CHANGELOG.md#L70)):*
What does "allow" mean more specifically? Imagine reading this as someone who has know idea what the code is doing, but is wondering how upgrading to this app might change the behaviour for them as a user.

> Be more accepting in what tunnel device states are treated as valid for applying a DNS config in NetworkManager. Solves problem of failing to set DNS, mostly on slow devices.

something something? Or is that an invalid interpretation of the change?


<!-- Sent from Reviewable.io -->

2020-10-27 16:34 UTC, dlon reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2020-10-27 16:42 UTC, dlon approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/src/dns/linux/network_manager.rs, line 375 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217#-MKeheSx7xT6ckeqxZSG:-MKeurXy6jkE_CQ7DijW:bra9e0h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86d2464967b8338e9b3493da1ce0fb73f735dbdd/talpid-core/src/dns/linux/network_manager.rs#L375)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think this should be added outside of the loop. Or at least removed before the loop exits.
</blockquote></details>

`add_match` can be called multiple times without `remove_match` in between. Are the additional calls ignored when the rule is the same?


<!-- Sent from Reviewable.io -->

2020-10-27 16:45 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[CHANGELOG.md, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217#-MKej4Sn1kUvWfDraXK2:-MKewbB_CaK_2jz7x3W_:b-5p02x4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86d2464967b8338e9b3493da1ce0fb73f735dbdd/CHANGELOG.md#L70)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

What does "allow" mean more specifically? Imagine reading this as someone who has know idea what the code is doing, but is wondering how upgrading to this app might change the behaviour for them as a user.

> Be more accepting in what tunnel device states are treated as valid for applying a DNS config in NetworkManager. Solves problem of failing to set DNS, mostly on slow devices.

something something? Or is that an invalid interpretation of the change?
</blockquote></details>

Well, the end result is that the DNS config is applied sooner, so I'll just state that - the method how that's achieved isn't really relevant to the end user.
___
*[talpid-core/src/dns/linux/network_manager.rs, line 360 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217#-MKeflCf2sI7RUbt5DXA:-MKepGf854zDyikvKqBC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86d2464967b8338e9b3493da1ce0fb73f735dbdd/talpid-core/src/dns/linux/network_manager.rs#L360)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`!` is missing.
</blockquote></details>

Done.
___
*[talpid-core/src/dns/linux/network_manager.rs, line 366 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217#-MKegiCq2On3l8YrJcHa:-MKepG4v8MWTteyaSnJh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86d2464967b8338e9b3493da1ce0fb73f735dbdd/talpid-core/src/dns/linux/network_manager.rs#L366)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think you meant to use `&&` here.
</blockquote></details>

Done.
___
*[talpid-core/src/dns/linux/network_manager.rs, line 375 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217#-MKeheSx7xT6ckeqxZSG:-MKepFtsC2AVcNNQHowL:b-ojy0zj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86d2464967b8338e9b3493da1ce0fb73f735dbdd/talpid-core/src/dns/linux/network_manager.rs#L375)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`add_match` can be called multiple times without `remove_match` in between. Are the additional calls ignored when the rule is the same?
</blockquote></details>

The `add_match` was erroneously moved into the loop - technically it should be a no-op, but it there's no benefit to calling it multiple times.


<!-- Sent from Reviewable.io -->

2020-10-27 16:52 UTC, dlon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217#-:-MKeyUkfDraPthcEtx76:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2020-10-28 12:01 UTC, faern approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-28 12:10 UTC, merged