Generalize the route manager channel
mullvad/mullvadvpn-app pull request #2231
Opened 2020-10-30 16:07 UTC by dlon

On Linux, a channel can already be used to communicate with the route manager across different threads. This has been generalized to all OSes and abstracted behind a type `RouteManagerHandle`. It is a prerequisite for manually setting up routes in the OpenVPN tunnel monitor, which is part of a refactoring to rely less on route monitoring.

### Other changes
* No longer spawn a separate new runtime on Linux for the route manager.
* Don't rely on executors from `futures` while handling events from OpenVPN.

2020-11-04 11:33 UTC, pinkisemils requested changes
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2231)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/routing/unix.rs, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2231#-MLHzfKjAmXd66ryX0lF:-MLHz_SV5-oREeldaFsu:b-du12k2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c652a6bd98a9d4c4777f24754ab86cb087bcf22/talpid-core/src/routing/unix.rs#L66)):*
> ```Rust
>         self.runtime
>             .block_on(response_rx)
>             .unwrap()
> ```

Is this discarding an error of a tokio runtime? I.e. it will only ever panic if the runtime has been dropped?
___
*[talpid-core/src/routing/windows.rs, line 166 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2231#-MLI0dBi1UlUGcyIG4UJ:-MLI0dBi1UlUGcyIG4UK:b-5l5c1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c652a6bd98a9d4c4777f24754ab86cb087bcf22/talpid-core/src/routing/windows.rs#L166)):*
> ```Rust
>             if tx.unbounded_send(RouteManagerCommand::Shutdown).is_err() {
>                 log::error!("RouteManager channel already down!");
>                 return;
> ```

If the manager is already down, does that also imply that `winnet::deactivate_routing_manager()` shouldn't be called?


<!-- Sent from Reviewable.io -->

2020-11-04 16:51 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2231)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/routing/unix.rs, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2231#-MLHzfKjAmXd66ryX0lF:-MLJ9Gb6CaUY5p9QMbL-:bx41vis) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c652a6bd98a9d4c4777f24754ab86cb087bcf22/talpid-core/src/routing/unix.rs#L66)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Is this discarding an error of a tokio runtime? I.e. it will only ever panic if the runtime has been dropped?
</blockquote></details>

It discards the error that would occur if the response sender were dropped before returning anything.


<!-- Sent from Reviewable.io -->

2020-11-04 18:00 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2231)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/routing/unix.rs, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2231#-MLHzfKjAmXd66ryX0lF:-MLJNj__EEV3PtAeSZJH:b-syhoq1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c652a6bd98a9d4c4777f24754ab86cb087bcf22/talpid-core/src/routing/unix.rs#L66)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It discards the error that would occur if the response sender were dropped before returning anything.
</blockquote></details>

Techincally that could happen if the handle was ever moved outside of the tokio runtime in which it's running, or if that runtime panicked and cleaned up it's threads. Might seem a bit far fetched, but I'd prefer panic safety here.


<!-- Sent from Reviewable.io -->

2020-11-05 16:00 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2231)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/routing/unix.rs, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2231#-MLHzfKjAmXd66ryX0lF:-MLO6hIr5PafrYDc5fus:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c652a6bd98a9d4c4777f24754ab86cb087bcf22/talpid-core/src/routing/unix.rs#L66)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Techincally that could happen if the handle was ever moved outside of the tokio runtime in which it's running, or if that runtime panicked and cleaned up it's threads. Might seem a bit far fetched, but I'd prefer panic safety here.
</blockquote></details>

Done.
___
*[talpid-core/src/routing/windows.rs, line 166 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2231#-MLI0dBi1UlUGcyIG4UJ:-MLO7gbN-oLqfVC6Whyf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c652a6bd98a9d4c4777f24754ab86cb087bcf22/talpid-core/src/routing/windows.rs#L166)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

If the manager is already down, does that also imply that `winnet::deactivate_routing_manager()` shouldn't be called?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-05 16:18 UTC, pinkisemils requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2231)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/routing/windows.rs, line 166 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2231#-MLI0dBi1UlUGcyIG4UJ:-MLOB7NlDA5gyr71IZuj:b-9nmkpa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c652a6bd98a9d4c4777f24754ab86cb087bcf22/talpid-core/src/routing/windows.rs#L166)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Whilst this is an improvement, is it still not possible to have the route manager crash, in which case the channel will be down, but this handle will not end up calling `winnet::deactivate_routing_manager()`. But clearly there is an issue with `winnet::deactivate_routing_manager()` being called multiple times, which also shouldn't be done. This maybe isn't a big deal if we make sure the manager never crashes.
However, since it's an `unbounded_send`, which is non-blocking, this function could still be called from multiple threads and `winnet::deactivate_routing_manager()` would still be called twice because the channel will only go down once the manager is down.


<!-- Sent from Reviewable.io -->

2020-11-05 16:56 UTC, pinkisemils approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2231#-:-MLOKbiG9s0vZuzDQVXn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-06 13:06 UTC, merged