Linux - parse loopback routes semi-correctly to count them and log less.
mullvad/mullvadvpn-app pull request #2245
Opened 2020-11-05 15:41 UTC by pinkisemils

Currently on every start of the daemon the route manager logs an entry for each loopback route it sees. To deal with this somewhat nicer, I've changed the route parsing code to just parse a loopback device as a route with a gateway via `127.0.0.1`, which can then be counted and filtered later.

2020-11-05 21:32 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[CHANGELOG.md, line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245#-MLPJXQA2wTWeGjneY6O:-MLPJXQB4ZUkTGX4kNk8:b6d5n7c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1bae087897ebcb0b7943562332626a6e66257e57/CHANGELOG.md#L84)):*
> ```Markdown
> - Fix routing rules sometimes being duplicated.
> - When NetworkManager is managing /etc/resolv.conf but ultimately using systemd-resolved, use
>   systemd-resolved directly to manage DNS.
> ```

What happened to the end of this previous changelog entry?


<!-- Sent from Reviewable.io -->

2020-11-06 09:58 UTC, dlon requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/src/routing/linux.rs, line 859 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245#-MLRzDYM5I48-jQ0LSRX:-MLRzDYM5I48-jQ0LSRY:b-fmev6v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b5950b9839ccc19e8a70babaef5adae2a4132a3e/talpid-core/src/routing/linux.rs#L859)):*
> ```Rust
> 
>         // when a gateway is specified but prefix is none, then this is a default route
>         if prefix.is_none() && gateway.is_some() {
> ```

Can't you specify a default route using only a device? E.g., `ip add default dev wg-mullvad`.


<!-- Sent from Reviewable.io -->

2020-11-09 13:00 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dlon and @faern)

___
*[CHANGELOG.md, line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245#-MLPJXQA2wTWeGjneY6O:-MLh2Py17XspLoMk-s1l:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1bae087897ebcb0b7943562332626a6e66257e57/CHANGELOG.md#L84)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

What happened to the end of this previous changelog entry?
</blockquote></details>

Done.
___
*[talpid-core/src/routing/linux.rs, line 859 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245#-MLRzDYM5I48-jQ0LSRX:-MLh1Kdq-BcqUSpMdwX6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b5950b9839ccc19e8a70babaef5adae2a4132a3e/talpid-core/src/routing/linux.rs#L859)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Can't you specify a default route using a device instead? E.g., `ip add default dev wg-mullvad`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-09 13:42 UTC, dlon approved these changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245)* status: all files reviewed, 3 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[talpid-core/src/routing/linux.rs, line 910 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245#-MLhEABZ-0eEwcFJHbQh:-MLhEABZ-0eEwcFJHbQi:b-ud4xsk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b8cfe8cd6a9220efabb068af12f7a39d20cc5bc4/talpid-core/src/routing/linux.rs#L910)):*
> ```Rust
>             table_id,
>         }));
>         log::debug!("ROUTE - {:?}", result);
> ```

Won't this create a lot of unnecessary log entries?
___
*[talpid-core/src/routing/linux.rs, line 1103 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245#-MLhE4SU-8t3nHTjwalQ:-MLhE4SU-8t3nHTjwalR:bo745pk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b8cfe8cd6a9220efabb068af12f7a39d20cc5bc4/talpid-core/src/routing/linux.rs#L1103)):*
> ```Rust
>         while let Some(message) = response.next().await {
>             if let NetlinkPayload::Error(err) = message.payload {
>                 log::error!("ERROR - WITH CODE {}", err.code);
> ```

Is it helpful to log this?


<!-- Sent from Reviewable.io -->

2020-11-09 14:49 UTC, faern reviewed
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[CHANGELOG.md, line 86 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245#-MLhQySuEgaiY73L4hhY:-MLhQySv170v2-E4iv_F:b-m3dx1v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ad60b5eca4320fac6e6b4895ee2a906637408ed/CHANGELOG.md#L86)):*
> ```Markdown
>   systemd-resolved directly to manage DNS.
> - Only use WireGuard kernel implementation if DNS isn't managed via NetworkManager.
> - Parse routes correctly and log less verbose routes.
> ```

Nit. But I guess you mean something like "log route changes less verbosely"? Is it the routes or the logging that's verbose? And what about them is logged (that's where my "changes" came from)?


<!-- Sent from Reviewable.io -->

2020-11-09 15:59 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[CHANGELOG.md, line 86 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245#-MLhQySuEgaiY73L4hhY:-MLhev8481U3lG5cYGo4:b-7widpg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ad60b5eca4320fac6e6b4895ee2a906637408ed/CHANGELOG.md#L86)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nit. But I guess you mean something like "log route changes less verbosely"? Is it the routes or the logging that's verbose? And what about them is logged (that's where my "changes" came from)?
</blockquote></details>

You are absolutely correct, that changelog entry was absolutely bogus.


<!-- Sent from Reviewable.io -->

2020-11-11 10:08 UTC, faern reviewed
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2020-11-11 10:14 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-11 10:14 UTC, dlon approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-11 10:16 UTC, merged