Use the route manager to set up routes when using OpenVPN
mullvad/mullvadvpn-app pull request #2254
Opened 2020-11-09 14:32 UTC by dlon

Previously, OpenVPN would create routes for us. Instead, we now simply take the routes it gives us and pass them to the route manager. This allows more flexibility in setting up routing. The step after this is to use rule-based routing in order to reduce the amount of monitoring and parsing required on Linux.

Also, the virtual interface is now also able to switch from one physical interface to another better one (e.g. when switching off of Wi-Fi), as is already the case for WireGuard. This should prevent disconnects when the original interface goes down, although I haven't tested this.

Related PRs: #2231 #2115

2020-11-09 15:46 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254)* status: 0 of 4 files reviewed, 1 unresolved discussion

___
*[talpid-core/src/tunnel/openvpn.rs, line 400 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLhf3sUCxDQvlyAtn8w:-MLhf3sUCxDQvlyAtn8x:buzz3ue) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35cd937b78a88eaef5fb1ef73a9b11c97da0df07/talpid-core/src/tunnel/openvpn.rs#L400)):*
> ```Rust
>     let tun_node6 = if tun_gateway_ip6.is_some() {
>         routing::NetNode::from(routing::Node::new(
>             "fe80::8"
> ```

This gateway is strange. I found a description here: https://github.com/OpenVPN/openvpn/blob/23e11e591347080efa3b933beca7f620dd059d5c/src/openvpn/route.c#L2020. I should add a comment here.


<!-- Sent from Reviewable.io -->

2020-11-10 00:16 UTC, pinkisemils requested changes
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/dns/linux/network_manager.rs, line 204 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLhx7Im-QQJfpl9Pypu:-MLhx7Im-QQJfpl9Pypv:b1r2xt2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc31d79f14fcd81c233e9af4be814fa4b36e22/talpid-core/src/dns/linux/network_manager.rs#L204)):*
> ```Rust
> 
>             ipv6_settings.insert("route-metric", Variant(Box::new(0u32)));
>             ipv6_settings.remove("routes");
> ```

Have you tested this to still work with WireGuard? And more specifically, WireGuard with NetworkManager?
___
*[talpid-core/src/tunnel/openvpn.rs, line 400 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLhf3sUCxDQvlyAtn8w:-MLhxxpGBojb6psSH2Lr:bi7b1ji) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35cd937b78a88eaef5fb1ef73a9b11c97da0df07/talpid-core/src/tunnel/openvpn.rs#L400)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This gateway is strange. I found a description here: https://github.com/OpenVPN/openvpn/blob/23e11e591347080efa3b933beca7f620dd059d5c/src/openvpn/route.c#L2020. I should add a comment here.
</blockquote></details>

This definitely should be documented in our code too.
___
*[talpid-core/src/tunnel/openvpn.rs, line 214 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLjVOuSBiWnl2pxA-mx:-MLjVOuTAj58pen14fuu:b637xxe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc31d79f14fcd81c233e9af4be814fa4b36e22/talpid-core/src/tunnel/openvpn.rs#L214)):*
> ```Rust
>                 }
>                 tokio::task::block_in_place(|| {
>                     let routes = extract_routes(&env).unwrap();
> ```

This `unwrap()` should be dealt with properly. The same goes for the panic 4 lines lower.
___
*[talpid-core/src/tunnel/openvpn.rs, line 308 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLjPRngBJpIXgyxRuWt:-MLjPRngBJpIXgyxRuWu:b7la133) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc31d79f14fcd81c233e9af4be814fa4b36e22/talpid-core/src/tunnel/openvpn.rs#L308)):*
> ```Rust
> 
>     for (key, value) in env.iter() {
>         if let Some(captures) = ENV_ROUTE_ENTRY.captures(key) {
> ```

Since there's a lot of unwrapping here, it'd be nice to assert that there are at least 4 items captured with that regex. Don't have to error if there isn't, just log it and `continue`. 
___
*[talpid-core/src/tunnel/openvpn.rs, line 312 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLjNPPV5FNxo_KAWobR:-MLjNPPW8iFCCgWXfCDU:b-sk0pma) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc31d79f14fcd81c233e9af4be814fa4b36e22/talpid-core/src/tunnel/openvpn.rs#L312)):*
> ```Rust
>             let property = captures.get(2).unwrap().as_str();
> 
>             let is_ipv6 = captures.get(1).map(|_| true).unwrap_or(false);
> ```

`is_ok()` or `is_some()` would be simpler here.
___
*[talpid-core/src/tunnel/openvpn.rs, line 326 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLjQL_I2_Ycj2f7Dovd:-MLjQL_J7BAzHZm4PFQr:b-vehmgu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc31d79f14fcd81c233e9af4be814fa4b36e22/talpid-core/src/tunnel/openvpn.rs#L326)):*
> ```Rust
>      -> std::result::Result<Vec<OpenVpnRoute>, RouteParseError> {
>         let mut routes = routes.into_iter().collect::<Vec<_>>();
>         routes.sort_by(|(idx0, _), (idx1, _)| idx0.partial_cmp(idx1).unwrap());
> ```

Using a plain `idx0.cmp(idx1)` would get around the issue of having an option to unwrap.
___
*[talpid-core/src/tunnel/openvpn.rs, line 340 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLjRLFLCFrsEHX3yhHG:-MLjRLFLCFrsEHX3yhHH:b9ok1x1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc31d79f14fcd81c233e9af4be814fa4b36e22/talpid-core/src/tunnel/openvpn.rs#L340)):*
> ```Rust
>                     .map_err(RouteParseError::ParseNetworkAddress)?;
> 
>                 let prefix = if let Some(mask) = route.get("netmask") {
> ```

Could be simplified a bit down by not computing the prefix from the netmask.
`let nemask = route.get("netmask").map(|mask| mask.parse().map_err(RouteParseError::ParseMaskAddress)).unwrap_or(Ok(Ipv4Addr::UNSPECIFIED))?;` and you can then use [`IpNetwork::with_netmask`](https://docs.rs/ipnetwork/0.17.0/ipnetwork/enum.IpNetwork.html).
___
*[talpid-core/src/tunnel/openvpn.rs, line 421 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLjS_Qi2yTfhXUNxlzh:-MLjS_Qi2yTfhXUNxlzi:b-jhnjrq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc31d79f14fcd81c233e9af4be814fa4b36e22/talpid-core/src/tunnel/openvpn.rs#L421)):*
> ```Rust
>             _ if route.gateway == default_node_ip => routing::NetNode::DefaultNode,
>             _ if route.gateway == tun_gateway_ip => tun_node.clone(),
>             _ if Some(route.gateway) == tun_gateway_ip6 => tun_node6.clone(),
> ```

I'm not entirely sure if this is stylistically the best choice here, just using `gateway` instead of `_` and using the variable in the `if` expression would seem a bit nicer. 
But an `if { } else if { } else if {}` would be clearer IMO. 


<!-- Sent from Reviewable.io -->

2020-11-11 11:51 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/dns/linux/network_manager.rs, line 204 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLhx7Im-QQJfpl9Pypu:-MLlvDu3ArfpY3mWUsvH:b-7lno4u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc31d79f14fcd81c233e9af4be814fa4b36e22/talpid-core/src/dns/linux/network_manager.rs#L204)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Have you tested this to still work with WireGuard? And more specifically, WireGuard with NetworkManager?
</blockquote></details>

Yes. It works. We may want to rely on routes if `route-data` is empty. But I suspect that `RouteData` has been around for long enough, since we already fail if it does not exist.
___
*[talpid-core/src/tunnel/openvpn.rs, line 400 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLhf3sUCxDQvlyAtn8w:-MLr74dN-tY4bA0P0IdW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35cd937b78a88eaef5fb1ef73a9b11c97da0df07/talpid-core/src/tunnel/openvpn.rs#L400)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This definitely should be documented in our code too.
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel/openvpn.rs, line 308 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLjPRngBJpIXgyxRuWt:-MLr7-ma5bwNkhClTRT2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc31d79f14fcd81c233e9af4be814fa4b36e22/talpid-core/src/tunnel/openvpn.rs#L308)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Since there's a lot of unwrapping here, it'd be nice to assert that there are at least 4 items captured with that regex. Don't have to error if there isn't, just log it and `continue`. 
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel/openvpn.rs, line 312 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLjNPPV5FNxo_KAWobR:-MLr70vhEpTB9E5uCjH3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc31d79f14fcd81c233e9af4be814fa4b36e22/talpid-core/src/tunnel/openvpn.rs#L312)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

`is_ok()` or `is_some()` would be simpler here.
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel/openvpn.rs, line 326 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLjQL_I2_Ycj2f7Dovd:-MLr71lLBaBJAP8PRcon:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc31d79f14fcd81c233e9af4be814fa4b36e22/talpid-core/src/tunnel/openvpn.rs#L326)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Using a plain `idx0.cmp(idx1)` would get around the issue of having an option to unwrap.
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel/openvpn.rs, line 340 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLjRLFLCFrsEHX3yhHG:-MLr78w71XWD8kwXA9pT:b-3eeofm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc31d79f14fcd81c233e9af4be814fa4b36e22/talpid-core/src/tunnel/openvpn.rs#L340)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Could be simplified a bit down by not computing the prefix from the netmask.
`let nemask = route.get("netmask").map(|mask| mask.parse().map_err(RouteParseError::ParseMaskAddress)).unwrap_or(Ok(Ipv4Addr::UNSPECIFIED))?;` and you can then use [`IpNetwork::with_netmask`](https://docs.rs/ipnetwork/0.17.0/ipnetwork/enum.IpNetwork.html).
</blockquote></details>

Done. `Ipv4Addr::UNSPECIFIED` is `0.0.0.0`, and `Ipv4Addr::BROADCAST` is not what this is, so I did it slightly differently.
___
*[talpid-core/src/tunnel/openvpn.rs, line 421 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLjS_Qi2yTfhXUNxlzh:-MLr7_oH3gFGFPfEo4K6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26fc31d79f14fcd81c233e9af4be814fa4b36e22/talpid-core/src/tunnel/openvpn.rs#L421)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I'm not entirely sure if this is stylistically the best choice here, just using `gateway` instead of `_` and using the variable in the `if` expression would seem a bit nicer. 
But an `if { } else if { } else if {}` would be clearer IMO. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-11 14:28 UTC, pinkisemils approved these changes
> Reviewed 1 of 4 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-12 10:05 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/process/openvpn.rs, line 234 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLvudKs6FTgaN88mF3o:-MLvudKt3oPa-vdGI6hz:b-sxlrh8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/53575162cb12d9be65d2c10a42ae2aa573de64f1/talpid-core/src/process/openvpn.rs#L234)):*
> ```Rust
>         }
> 
>         args.push(OsString::from("--route-noexec"));
> ```

Any reason to not include this under `BASE_ARGUMENTS`?


<!-- Sent from Reviewable.io -->

2020-11-12 12:43 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[talpid-core/src/process/openvpn.rs, line 234 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254#-MLvudKs6FTgaN88mF3o:-MLwTp_82ojtrwEMpfPn:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/53575162cb12d9be65d2c10a42ae2aa573de64f1/talpid-core/src/process/openvpn.rs#L234)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Any reason to not include this under `BASE_ARGUMENTS`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-13 11:59 UTC, pinkisemils approved these changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2020-11-16 09:34 UTC, faern reviewed
> Reviewed 1 of 3 files at r4, 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2020-11-16 12:22 UTC, merged