Upgrade to Electron 11
mullvad/mullvadvpn-app pull request #2302
Opened 2020-11-25 10:21 UTC by raksooo

This PR upgrades Electron from 8.5.2 to 11.0.2 and also contains the following changes to adjust to braking changing/issues:
* Update to compatible NSEventMonitor
* Enable use of `remote` module in the renderer process
* Remove no longer needed assignment of `app.allowRendererProcessReuse`
* Replaced deprecated method `openItem` with correct one
* Prevent Electron from downloading spellcheck dictionaries (https://github.com/electron/electron/issues/22995)
* Serve renderer content with a web server in development to make devtools work (https://github.com/electron/electron/issues/23662, https://github.com/electron/electron/issues/24011)

Changelogs for Electron:
9.0.0: https://www.electronjs.org/blog/electron-9-0
10.0.0: https://www.electronjs.org/blog/electron-10-0
11.0.0: https://www.electronjs.org/blog/electron-11-0

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2020-11-25 10:59 UTC, pronebird requested changes
> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/tasks/dev-server.js, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302#-MMz26gyE348mIv0hQFE:-MMz26gyE348mIv0hQFF:b-ho73rv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e656fe2f19333ad19704374c260c4a37981ce3df/gui/tasks/dev-server.js#L5)):*
> ```JavaScript
> 
> function startWebServer(done) {
>   serverFactory.create({ path: './build', port: 8080 }).start();
> ```

Based on [source code](https://github.com/betsol/spa-server/blob/master/lib/server.js#L65), `start` accepts a callback. 

Probably we want to fully start the web server before proceeding, so I'd do:

```
injectWorkingDirectory();
serverFactory.create({ path: './build', port: 8080 }).start(done);
```


<!-- Sent from Reviewable.io -->

2020-11-25 11:37 UTC, pronebird requested changes
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/tasks/dev-server.js, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302#-MMz98y83BAdBnpVSbmV:-MMz98y83BAdBnpVSbmW:bpn7oj6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e656fe2f19333ad19704374c260c4a37981ce3df/gui/tasks/dev-server.js#L10)):*
> ```JavaScript
> }
> 
> function injectWorkingDirectory() {
> ```

Since you only inject working directory once, it looks like any changes to `index.ts` will overwrite the injected script. I'd personally configure `spa-server` to prepend the `chdir` script to the `index.js`, i.e:

```
function (req, res, next) {
      if (req.path === '/src/renderer/index.js') {
        res.body = 'try{process.chdir("build/src/renderer")}catch(e){}\n' + res.body
      }
      next();
}
```


<!-- Sent from Reviewable.io -->

2020-11-25 13:49 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[gui/tasks/dev-server.js, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302#-MMz26gyE348mIv0hQFE:-MMzeOcO4ydeALtqGQ6J:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e656fe2f19333ad19704374c260c4a37981ce3df/gui/tasks/dev-server.js#L5)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Based on [source code](https://github.com/betsol/spa-server/blob/master/lib/server.js#L65), `start` accepts a callback. 

Probably we want to fully start the web server before proceeding, so I'd do:

```
injectWorkingDirectory();
serverFactory.create({ path: './build', port: 8080 }).start(done);
```
</blockquote></details>

Done.
___
*[gui/tasks/dev-server.js, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302#-MMz98y83BAdBnpVSbmV:-MMzeUh4C_zWqsLjI7MW:bhau02o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e656fe2f19333ad19704374c260c4a37981ce3df/gui/tasks/dev-server.js#L10)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Since you only inject working directory once, it looks like any changes to `index.ts` will overwrite the injected script. I'd personally configure `spa-server` to prepend the `chdir` script to the `index.js`, i.e:

```
function (req, res, next) {
      if (req.path === '/src/renderer/index.js') {
        res.body = 'try{process.chdir("build/src/renderer")}catch(e){}\n' + res.body
      }
      next();
}
```
</blockquote></details>

Good idea! I finally got it working, done.


<!-- Sent from Reviewable.io -->

2020-11-25 13:54 UTC, pronebird requested changes
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/tasks/dev-server.js, line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302#-MMzfg_NB3e4SSof45bz:-MMzfg_NB3e4SSof45c-:b7g5dwm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a139d63cb8805ca4bda0beb01716e01be8e2bd7/gui/tasks/dev-server.js#L18)):*
> ```JavaScript
>     response.write = (data) => {
>       // Add code that changes to the correct working directory after `"use strict";`
>       const lines = data.toString().split('\n');
> ```

Wow that's a lot of work. Why not simply concatenate strings?


<!-- Sent from Reviewable.io -->

2020-11-25 13:56 UTC, pronebird reviewed
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/tasks/dev-server.js, line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302#-MMzgEAq0gaVyoX8LQd1:-MMzgEAq0gaVyoX8LQd2:b891msz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a139d63cb8805ca4bda0beb01716e01be8e2bd7/gui/tasks/dev-server.js#L8)):*
> ```JavaScript
>       path: './build',
>       port: 8080,
>       middleware: [correctWorkingDirectory],
> ```

FYI don't you have to add it first before the serverFactory's default router?


<!-- Sent from Reviewable.io -->

2020-11-25 14:05 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/tasks/dev-server.js, line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302#-MMzgEAq0gaVyoX8LQd1:-MMzhUFw42YykAoczZQB:bj5n6la) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a139d63cb8805ca4bda0beb01716e01be8e2bd7/gui/tasks/dev-server.js#L8)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI don't you have to add it first before the serverFactory's default router?
</blockquote></details>

If nothing is specified the middleware will be the first thing to run.
___
*[gui/tasks/dev-server.js, line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302#-MMzfg_NB3e4SSof45bz:-MMzhlu19u867YJNnSQT:b-eax5x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a139d63cb8805ca4bda0beb01716e01be8e2bd7/gui/tasks/dev-server.js#L18)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Wow that's a lot of work. Why not simply concatenate strings?
</blockquote></details>

The first line of `index.js` is `'use strict';` which needs to be first to enable strict mode. This adds the directory changing code to the second line so that strict mode is still entered.


<!-- Sent from Reviewable.io -->

2020-11-25 15:36 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/tasks/dev-server.js, line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302#-MMzfg_NB3e4SSof45bz:-MN-06Z8D31e21nLsPMM:b-py63wn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a139d63cb8805ca4bda0beb01716e01be8e2bd7/gui/tasks/dev-server.js#L18)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

The first line of `index.js` is `'use strict';` which needs to be first to enable strict mode. This adds the directory changing code to the second line so that strict mode is still entered.
</blockquote></details>

Sure, why not just use `indexOf` to find the first newline instead of breaking the entire file on newlines?

```js
let s = data.toString();

// Add code that changes to the correct working directory after `"use strict";` which is located on the first line of the source file.
const index = s.indexOf("\n");

if (index !== -1) {
    const insertionIndex = index + 1;
    s = s.slice(0, insertionIndex) + "<INSERTION>\n" + s.slice(insertionIndex);
}

write(s);
```


<!-- Sent from Reviewable.io -->

2020-11-25 16:06 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/tasks/dev-server.js, line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302#-MMzfg_NB3e4SSof45bz:-MN-3Il327nPU0j6VjZM:b-7xq5ad) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a139d63cb8805ca4bda0beb01716e01be8e2bd7/gui/tasks/dev-server.js#L18)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Sure, why not just use `indexOf` to find the first newline instead of breaking the entire file on newlines?

```js
let s = data.toString();

// Add code that changes to the correct working directory after `"use strict";` which is located on the first line of the source file.
const index = s.indexOf("\n");

if (index !== -1) {
    const insertionIndex = index + 1;
    s = s.slice(0, insertionIndex) + "<INSERTION>\n" + s.slice(insertionIndex);
}

write(s);
```
</blockquote></details>

Sure, that works as well.


<!-- Sent from Reviewable.io -->

2020-11-26 08:29 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2302#-:-MN2epiIDpkNOVPydRIP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-26 09:04 UTC, merged