Wait for Wintun adapter's unicast addresses to be usable
mullvad/mullvadvpn-app pull request #2330
Opened 2020-12-04 12:39 UTC by dlon

OpenVPN doesn't wait for the network interfaces to be fully usable before considering the tunnel to be up. As a result, there may be no connectivity for up to 3 seconds after the daemon enters the connected state. This can be verified by pinging any address immediately after connecting.

The docs for [CreateUnicastIpAddressEntry](https://docs.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-createunicastipaddressentry) state:
> The unicast IP address passed in the Address member of the MIB_UNICASTIPADDRESS_ROW pointed to by the Row parameter is not usable immediately. The IP address is usable after the duplicate address detection process has completed successfully. It can take several seconds for the duplicate address detection process to complete since IP packets need to be sent and potential responses must be awaited. For IPv6, the duplicate address detection process typically takes about a second. For IPv4, the duplicate address detection process typically takes about three seconds.

This PR fixes the issue by polling the addresses using `GetUnicastIpAddressEntry` until `DadState == IpDadStatePreferred` (as suggested in the link above).

DAD could also be skipped on (only) Windows 10, assuming that this is safe, but OpenVPN doesn't do this.

2020-12-04 14:35 UTC, pinkisemils requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2330)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 1028 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2330#-MNiAHp92UNjPYYNPYRa:-MNiAHp92UNjPYYNPYRb:br2x3b2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38eaba9d80373a74dd6048345f6c3892c34a83a5/talpid-core/src/tunnel/openvpn/mod.rs#L1028)):*
> ```Rust
>             IpDadStateDuplicate => DadStateError::Duplicate,
>             IpDadStateDeprecated => DadStateError::Deprecated,
>             other @ _ => DadStateError::Unknown(other),
> ```

This can just be `other => DadStateError::Unknown(other)`.


<!-- Sent from Reviewable.io -->

2020-12-04 16:02 UTC, mvd-ows approved these changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2330)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 958 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2330#-MNiMKwgEyeZjqQ4OLV8:-MNiMKwh-cd36GCjRugh:bxta4pz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38eaba9d80373a74dd6048345f6c3892c34a83a5/talpid-core/src/tunnel/openvpn/mod.rs#L958)):*
> ```Rust
> 
>         for i in 0..(*unicast_table).NumEntries {
>             let table = first_table.offset(i as isize);
> ```

What's the reason `Table[i]` can't be used here?
___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 984 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2330#-MNiSjJ-DvZjRurb-V3C:-MNiSjJ-DvZjRurb-V3D:bpmvlcq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38eaba9d80373a74dd6048345f6c3892c34a83a5/talpid-core/src/tunnel/openvpn/mod.rs#L984)):*
> ```Rust
>                 break;
>             }
>             if row.DadState != IpDadStatePreferred {
> ```

If the state is ever `IpDadStateInvalid` before it reaches `IpDadStateTentative`, this will fail.

It would be safer to wait for `IpDadStatePreferred` on all interfaces, but then you wouldn't be able to abort early.

Not sure if this is a legitimate concern.


<!-- Sent from Reviewable.io -->

2020-12-07 10:33 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2330)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 958 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2330#-MNiMKwgEyeZjqQ4OLV8:-MNwhj4oD6EK0jXyA92i:b-m0nt55) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38eaba9d80373a74dd6048345f6c3892c34a83a5/talpid-core/src/tunnel/openvpn/mod.rs#L958)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

What's the reason `Table[i]` can't be used here?
</blockquote></details>

The type of `Table` is `[MIB_UNICASTIPADDRESS_ROW; 1]`, so its length is wrong. But it should be possible to access it as a slice by casting it to a pointer and using [std::slice::from_raw_parts](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html). You can't use `[]` on raw pointers in Rust.
___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 1028 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2330#-MNiAHp92UNjPYYNPYRa:-MNwjCwBEYDYeA6vinSL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38eaba9d80373a74dd6048345f6c3892c34a83a5/talpid-core/src/tunnel/openvpn/mod.rs#L1028)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This can just be `other => DadStateError::Unknown(other)`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-07 10:39 UTC, mvd-ows approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2330)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @pinkisemils)



<!-- Sent from Reviewable.io -->

2020-12-07 10:59 UTC, mvd-ows approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2330)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @pinkisemils)



<!-- Sent from Reviewable.io -->

2020-12-07 10:59 UTC, mvd-ows approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2330)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @pinkisemils)



<!-- Sent from Reviewable.io -->

2020-12-07 11:25 UTC, pinkisemils approved these changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2330)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2020-12-07 11:43 UTC, merged