Warn if configured to use a public custom DNS server
mullvad/mullvadvpn-app pull request #2343
Opened 2020-12-10 14:16 UTC by jvff

Our servers intercept and redirect DNS requests to prevent DNS leaks. This means that configuring a custom DNS server address that needs to be routed through the tunnel doesn't work as expected. Until this is fixed server side, the app will show a dialog warning the user about the issue.

This PR implements that dialog. It uses the `MainActivity` class to synchronize the status between the fragments, which is not ideal, but this code should be removed when things are updated in the servers.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header. **Part of an unreleased feature, so this just reuses the same changelog entry.**
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2020-12-10 17:38 UTC, pinkisemils requested changes
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2343)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2343#-MOCisYe-fcc2Hg6qUCJ:-MOCisYe-fcc2Hg6qUCK:b15qkbo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d2c4322a9316c9819ed2931774c2e9ec47cd07bc/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L82)):*
> ```Kotlin
> 
>     var backButtonHandler: (() -> Boolean)? = null
>     var confirmPublicDnsServer: CompletableDeferred<Boolean>? = null
> ```

Does this field need to exist on the parent activity if it's only ever set here? 


<!-- Sent from Reviewable.io -->

2020-12-10 17:42 UTC, pinkisemils reviewed
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2343)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2020-12-10 18:39 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2343)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2343#-MOCisYe-fcc2Hg6qUCJ:-MOCvE9tEzCnfZVFJ6WQ:bfvw79c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d2c4322a9316c9819ed2931774c2e9ec47cd07bc/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L82)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Does this field need to exist on the parent activity if it's only ever set here? 
</blockquote></details>

The problem is communication between fragments :/ The dialog needs a way to send the result to the Advanced screen, and Android recommends using the owner activity for that. This is ugly indeed, but I'm strongly hoping this is temporary. If we still have this line in a few months I think we should definitely try to improve this, but we'd have to handle Android destroying/recreating the fragment, which might make it more complex :/


<!-- Sent from Reviewable.io -->

2020-12-11 00:26 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2343)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2343#-MOCisYe-fcc2Hg6qUCJ:-MOEB8DS7nWABUn89S0C:b4bvj8q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d2c4322a9316c9819ed2931774c2e9ec47cd07bc/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L82)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

The problem is communication between fragments :/ The dialog needs a way to send the result to the Advanced screen, and Android recommends using the owner activity for that. This is ugly indeed, but I'm strongly hoping this is temporary. If we still have this line in a few months I think we should definitely try to improve this, but we'd have to handle Android destroying/recreating the fragment, which might make it more complex :/
</blockquote></details>

Given that we often get to back to code that's written recently to fix bugs rather than design, I think we'd do good to at least get the design good for new code - it's highly unlikely we'll have plenty of spare time to redo this code.


<!-- Sent from Reviewable.io -->

2020-12-11 18:16 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2343)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2343#-MOCisYe-fcc2Hg6qUCJ:-MOI-YfT9DIlr5_-S1GK:b-ow4mm3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d2c4322a9316c9819ed2931774c2e9ec47cd07bc/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L82)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Given that we often get to back to code that's written recently to fix bugs rather than design, I think we'd do good to at least get the design good for new code - it's highly unlikely we'll have plenty of spare time to redo this code.
</blockquote></details>

Done.

Yeah, that makes sense. We don't know how long this code will stay there, and it's going to be unpleasant to work around it while it does.

I refactored to have the `AdvancedFragment` set the property in the fragment directly. The problem of this is that the property's value will be lost when the dialog fragment is destroy (for example when the configuration changes due to language change or starting split screen mode). The new code handles that by simply dismissing the dialog and returning to the previous screen, which will still be in the editing state. That means that the user can just try to add the DNS server again and the dialog will appear again.


<!-- Sent from Reviewable.io -->

2020-12-12 00:11 UTC, pinkisemils approved these changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2343)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2343#-MOCisYe-fcc2Hg6qUCJ:-MOJHVoH-KAOkCQZ94OL:bz494pl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d2c4322a9316c9819ed2931774c2e9ec47cd07bc/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L82)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done.

Yeah, that makes sense. We don't know how long this code will stay there, and it's going to be unpleasant to work around it while it does.

I refactored to have the `AdvancedFragment` set the property in the fragment directly. The problem of this is that the property's value will be lost when the dialog fragment is destroy (for example when the configuration changes due to language change or starting split screen mode). The new code handles that by simply dismissing the dialog and returning to the previous screen, which will still be in the editing state. That means that the user can just try to add the DNS server again and the dialog will appear again.
</blockquote></details>

Great, this is a much nicer solution!


<!-- Sent from Reviewable.io -->

2020-12-14 14:43 UTC, merged