Added iOS info
mullvad/mullvadvpn-app pull request #2350
Opened 2020-12-12 12:03 UTC by sm0rux

Not sure, but I think the iOS app handles "WireGuard" and "Optional local network access" as the Android app does.

Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2020-12-15 14:48 UTC, faern requested changes
Thanks for this PR. The readme is indeed a bit outdated in this area.

2020-12-15 14:48 UTC, faern commented on README.md
> +| Optional local network access |    ✓    |   ✓   |   ✓   |    ✓    |  ✓  |
LAN access is not really "optional" in our iOS app at the moment. LAN is always allowed currently. There are some new possibilities with iOS 14+ that might allow locking it down, but we don't implement that yet.

Could you update this checkbox to have an asterisk and below the table put something like

```
* The local network is always accessible on iOS with the current implementation
```

Watch out for markdown formatting so it does not become a bullet list.

2020-12-15 17:16 UTC, sm0rux commented
Så, nu tror jag att jag fixade till det rätt snyggt.

2020-12-16 11:25 UTC, merged

2020-12-16 11:28 UTC, faern commented
Thanks for the contribution :)

2020-12-16 18:42 UTC, sm0rux commented
My pleasure :)