Handle DNS server addresses that Android consider invalid
mullvad/mullvadvpn-app pull request #2354
Opened 2020-12-14 17:06 UTC by jvff

When specifying the DNS server addresses to use for the tunnel device, Android may throw an exception saying that the DNS server address is invalid. This has currently only been seen when using a localhost address (`127.0.0.1`), and the code for custom DNS already prevents using localhost addresses to avoid having issues. However, not only is it hard to be sure what the exact list of invalid DNS server addresses is, it is impossible to know if that list will change in future versions of Android. 

To prevent crashes from using an unexpected invalid custom DNS server address, this PR changes the tunnel creation code to handle that failure gracefully. If the invalid DNS server address exception is thrown, `TalpidVpnService` will still continue creating the tunnel, but it will return an error state back to the tunnel state machine. This allows it to enter the blocking state gracefully, and have the error reported to the UI.

As part of the PR, the tunnel device creation was refactored to return a custom result type instead of either the tunnel file descriptor directly or a negative integer error code.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2020-12-15 12:04 UTC, pinkisemils requested changes
> Reviewed 4 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2354)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/talpid/CreateTunResult.kt, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2354#-MOaE-8_9dw7VZyX3BwU:-MOaE-8_9dw7VZyX3BwV:b-sx17yh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfc1d25ca2184abdd1dbfdeb1c7f2c8e9801ece7/android/src/main/kotlin/net/mullvad/talpid/CreateTunResult.kt#L14)):*
> ```Kotlin
>     }
> 
>     class InvalidDnsServer(val address: InetAddress, val tunFd: Int) : CreateTunResult() {
> ```

This might as well be a list of addresses, not a single one.
___
*[android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt, line 140 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2354#-MOaGKGEB5iqsGaoaE-G:-MOaGKGEB5iqsGaoaE-H:bitfto) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfc1d25ca2184abdd1dbfdeb1c7f2c8e9801ece7/android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt#L140)):*
> ```Kotlin
>         val tunFd = vpnInterface?.detachFd()
> 
>         if (tunFd != null) {
> ```

This should be inverted so that there's an early return if `tunFd` is null.
___
*[android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt, line 144 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2354#-MOaH1482EBmesbNKgLt:-MOaH1482EBmesbNKgLu:b-w7w47j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfc1d25ca2184abdd1dbfdeb1c7f2c8e9801ece7/android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt#L144)):*
> ```Kotlin
> 
>             if (invalidDnsServerAddress != null) {
>                 return CreateTunResult.InvalidDnsServer(invalidDnsServerAddress!!, tunFd)
> ```

Since the rust side ignores the FD, isn't this a leak?


<!-- Sent from Reviewable.io -->

2020-12-15 12:34 UTC, pinkisemils reviewed
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2354)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2020-12-15 21:13 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2354)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/talpid/CreateTunResult.kt, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2354#-MOaE-8_9dw7VZyX3BwU:-MObmWuj9_J8jEIjFQRz:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfc1d25ca2184abdd1dbfdeb1c7f2c8e9801ece7/android/src/main/kotlin/net/mullvad/talpid/CreateTunResult.kt#L14)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This might as well be a list of addresses, not a single one.
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt, line 140 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2354#-MOaGKGEB5iqsGaoaE-G:-MObP0wsEn6SPKbUyrSq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfc1d25ca2184abdd1dbfdeb1c7f2c8e9801ece7/android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt#L140)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This should be inverted so that there's an early return if `tunFd` is null.
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt, line 144 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2354#-MOaH1482EBmesbNKgLt:-MOaZ6g8B0ngfqJ-pgQI:b-qvkoi3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfc1d25ca2184abdd1dbfdeb1c7f2c8e9801ece7/android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt#L144)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Since the rust side ignores the FD, isn't this a leak?
</blockquote></details>

It's not used by the Rust side, but it is closed on the Java side by the `activeTunStatus` property's observable.


<!-- Sent from Reviewable.io -->

2020-12-16 11:38 UTC, pinkisemils approved these changes
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2354)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-16 13:04 UTC, merged