Rework offline detection on Linux
mullvad/mullvadvpn-app pull request #2377
Opened 2021-01-07 10:52 UTC by pinkisemils

To improve offline detection on Linux and desktop in general, I've done two things:
- Add an environment variable to allow disabling the offline check entirely, leaving it in an open state. This could later be reworked to being a proper option.
- Change offline detection on Linux to query the routing table for a path to a public IPv4 address to infer connectivity.

2021-01-07 12:34 UTC, dlon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377#-:-MQRnasp8W1Ef0OFfv3J:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/offline/linux.rs, line 118 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377#-MQRn43X8KkAkRdNoeJq:-MQRn43X8KkAkRdNoeJr:b-hj4zod) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2c8b3d39e0d787a1b45f2f80e58e6eef6971643/talpid-core/src/offline/linux.rs#L118)):*
> ```Rust
> 
> 
> async fn public_ip_not_reachable(handle: &Handle) -> Result<bool> {
> ```

I think this should be `public_ip_reachable` (i.e., not negated).


<!-- Sent from Reviewable.io -->

2021-01-07 13:17 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/offline/linux.rs, line 118 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377#-MQRn43X8KkAkRdNoeJq:-MQRwMN27NtuE94n3qRk:b-35rx6p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2c8b3d39e0d787a1b45f2f80e58e6eef6971643/talpid-core/src/offline/linux.rs#L118)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think this should be `public_ip_reachable` (i.e., not negated).
</blockquote></details>

`public_ip_unreachable()` would be better still IMO, since every time this function is called, it's return value is assigned to `is_offline` in one way or another.  Or do you think that `!pubilc_ip_reachable()` is better?


<!-- Sent from Reviewable.io -->

2021-01-07 13:56 UTC, dlon approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/offline/linux.rs, line 118 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377#-MQRn43X8KkAkRdNoeJq:-MQS7NMP0gHDsc5cNvuO:b-xd3vm6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2c8b3d39e0d787a1b45f2f80e58e6eef6971643/talpid-core/src/offline/linux.rs#L118)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

`public_ip_unreachable()` would be better still IMO, since every time this function is called, it's return value is assigned to `is_offline` in one way or another.  Or do you think that `!pubilc_ip_reachable()` is better?
</blockquote></details>

You're right.


<!-- Sent from Reviewable.io -->

2021-01-07 15:26 UTC, faern approved these changes
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2021-01-07 15:31 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/src/offline/linux.rs, line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377#-MQST-e35cmspndT7vdh:-MQST-e4-YdmTApkMM65:b3qmdea) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2c8b3d39e0d787a1b45f2f80e58e6eef6971643/talpid-core/src/offline/linux.rs#L52)):*
> ```Rust
> }
> 
> const PUBLIC_INTERNET_ADDRESS: Ipv4Addr = Ipv4Addr::new(193, 138, 218, 78);
> ```

Can we please leave a comment on such a magical constant? One that explains that any public IP should do, but we stick to one owned my Mullvad.


<!-- Sent from Reviewable.io -->

2021-01-07 15:34 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/offline/linux.rs, line 118 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377#-MQRn43X8KkAkRdNoeJq:-MQSTo6-836FOxNAcVUt:bd1l0xy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2c8b3d39e0d787a1b45f2f80e58e6eef6971643/talpid-core/src/offline/linux.rs#L118)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You're right.
</blockquote></details>

I vote for anything that does not have a negation in the name. Evaluating "is not reachable: true" in my head always leads to smoke coming out of my ears. "Is unreachable: true" or "is reachable: false" is way easier to process.


<!-- Sent from Reviewable.io -->

2021-01-07 15:39 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/offline/mod.rs, line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377#-MQSUs-46RFUN5efU6qC:-MQSUs-46RFUN5efU6qD:b-hbnzm7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2c8b3d39e0d787a1b45f2f80e58e6eef6971643/talpid-core/src/offline/mod.rs#L42)):*
> ```Rust
>     #[cfg(target_os = "android")] android_context: AndroidContext,
> ) -> Result<MonitorHandle, Error> {
>     let monitor = match std::env::var(TALPID_DISABLE_OFFLINE_MONITOR)
> ```

Maybe can be made simpler and more consistent if implemented with a `lazy_static` like the other env variable checks? Then the constant can contain the actual value and not just the name of the env var to check

https://github.com/mullvad/mullvadvpn-app/blob/6b9120724681885968b5161c7e782776ee0fda0d/talpid-core/src/tunnel/wireguard/mod.rs#L65-L67

Also easier to verify that the logic is the same as the others


<!-- Sent from Reviewable.io -->

2021-01-07 16:19 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[talpid-core/src/offline/linux.rs, line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377#-MQST-e35cmspndT7vdh:-MQScR_i7z6NLGlDN1Zl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b2c8b3d39e0d787a1b45f2f80e58e6eef6971643/talpid-core/src/offline/linux.rs#L52)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we please leave a comment on such a magical constant? One that explains that any public IP should do, but we stick to one owned my Mullvad.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-08 08:37 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/offline/mod.rs, line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377#-MQW87eq1dZRnQymfshE:-MQW87er4x4EDRvpuFEM:bpki8ww) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b673a75c54416144de0186880fb070f757300bdf/talpid-core/src/offline/mod.rs#L25)):*
> ```Rust
> lazy_static::lazy_static! {
>     /// Disables offline monitor
>     static ref FORCE_DISABLE_OFFLINE_MONITOR: bool = std::env::var("TALPID_FORCE_USERSPACE_WIREGUARD")
> ```

`USERSPACE_WIREGUARD`?


<!-- Sent from Reviewable.io -->

2021-01-08 12:26 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[talpid-core/src/offline/mod.rs, line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377#-MQW87eq1dZRnQymfshE:-MQWG1vQ4b4IJr912HWw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b673a75c54416144de0186880fb070f757300bdf/talpid-core/src/offline/mod.rs#L25)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`USERSPACE_WIREGUARD`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-08 12:28 UTC, dlon approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2021-01-08 15:11 UTC, faern reviewed
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-11 11:49 UTC, dlon approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-11 12:33 UTC, merged