Fall back on LLMNR/NetBIOS name resolution
mullvad/mullvadvpn-app pull request #2378
Opened 2021-01-07 11:45 UTC by dlon

Support for custom DNS was included in the last beta release, and it involved some changes to how DNS is managed. This was because the interface metric was tied to DNS resolver preference in Windows 10, and this worked poorly with local resolvers.

This change caused problems for single-label names (e.g., NetBIOS names). If DNS resolution failed, it would not fall back on using LLMNR. Hence other hosts on a LAN were no longer being identified.

For whatever reason, the [least strict](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-gpnrpt/b5760f13-0a23-4e37-9253-ad12af60e8a6) setting must be used, i.e. "Always fall back to LLMNR and NetBIOS for any kind of name resolution error.". Otherwise, names do not resolve.

2021-01-07 13:31 UTC, mvd-ows requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2378)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[CHANGELOG.md, line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2378#-MQRyqUa7XbOsMmuulZz:-MQRyqUa7XbOsMmuul_-:b60srg9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa48f44ab58cc829c9070f2e77072d681505ab65/CHANGELOG.md#L41)):*
> ```Markdown
> 
> #### Windows
> - Resolve single-label names correctly.
> ```

`names` doesn't capture the context. Needs to be more specific.
___
*[talpid-core/src/dns/windows/mod.rs, line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2378#-MQRzVQC5ZaGokMXjDaa:-MQRzVQC5ZaGokMXjDab:b-doan9z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa48f44ab58cc829c9070f2e77072d681505ab65/talpid-core/src/dns/windows/mod.rs#L29)):*
> ```Rust
> lazy_static! {
>     /// Use a global
>     static ref ENABLE_DNS_CACHE_POLICY: bool = env::var("TALPID_DNS_CACHE_POLICY")
> ```

Is there a guideline for whether the environment variable should include `ENABLE` in its name?
___
*[talpid-core/src/dns/windows/mod.rs, line 137 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2378#-MQS1WNS-d_vDsaljqN8:-MQS1WNS-d_vDsaljqN9:bn40cfg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa48f44ab58cc829c9070f2e77072d681505ab65/talpid-core/src/dns/windows/mod.rs#L137)):*
> ```Rust
>     fn drop(&mut self) {
>         if *ENABLE_DNS_CACHE_POLICY && is_minimum_windows10() {
>             if let Err(error) = reset_dns_cache_policy() {
> ```

This resets with no consideration for what the original settings were? But not worth fixing at this point.


<!-- Sent from Reviewable.io -->

2021-01-07 15:54 UTC, faern approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2378)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[talpid-core/src/dns/windows/mod.rs, line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2378#-MQRzVQC5ZaGokMXjDaa:-MQSYMvEDVRcQbUUoJTa:b-v0xpmw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa48f44ab58cc829c9070f2e77072d681505ab65/talpid-core/src/dns/windows/mod.rs#L29)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Is there a guideline for whether the environment variable should include `ENABLE` in its name?
</blockquote></details>

We use environment variables so sparsely so it's not really justified to have a guideline maybe. But we should always try to be consistent of course.

I think the comment can be much more explanatory as well...  A global what?

Please also add any new environment variable to the README.


<!-- Sent from Reviewable.io -->

2021-01-08 11:31 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2378)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dlon, @faern, and @mvd-ows)

___
*[CHANGELOG.md, line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2378#-MQRyqUa7XbOsMmuulZz:-MQWke1p2_WJhuvppwdJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa48f44ab58cc829c9070f2e77072d681505ab65/CHANGELOG.md#L41)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

`names` doesn't capture the context. Needs to be more specific.
</blockquote></details>

Done.
___
*[talpid-core/src/dns/windows/mod.rs, line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2378#-MQRzVQC5ZaGokMXjDaa:-MQWkixL9voA4C4WYLwQ:beccrha) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa48f44ab58cc829c9070f2e77072d681505ab65/talpid-core/src/dns/windows/mod.rs#L29)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We use environment variables so sparsely so it's not really justified to have a guideline maybe. But we should always try to be consistent of course.

I think the comment can be much more explanatory as well...  A global what?

Please also add any new environment variable to the README.
</blockquote></details>

It should be clearer now.


<!-- Sent from Reviewable.io -->

2021-01-08 12:05 UTC, mvd-ows approved these changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2378)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-01-08 13:52 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2378)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[talpid-core/src/dns/windows/mod.rs, line 137 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2378#-MQS1WNS-d_vDsaljqN8:-MQXEgkh0JKHld6lr5Hc:b-axn4nw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa48f44ab58cc829c9070f2e77072d681505ab65/talpid-core/src/dns/windows/mod.rs#L137)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This resets with no consideration for what the original settings were? But not worth fixing at this point.
</blockquote></details>

Yeah. Ideally it should be stored in a file and recovered in case the daemon doesn't exit gracefully as well.


<!-- Sent from Reviewable.io -->

2021-01-08 13:53 UTC, merged