Update build instructions for Windows
mullvad/mullvadvpn-app pull request #2379
Opened 2021-01-07 12:50 UTC by dlon

The instructions for running the app on Windows (without using a service) are not up-to-date. One must launch a command prompt as the SYSTEM user, since the settings and cache cannot be not accessed otherwise.

2021-01-07 13:13 UTC, mvd-ows requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[README.md, line 345 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379#-MQRyLK42CdBv-h9zGyP:-MQRyLK42CdBv-h9zGyQ:b-ylfmb1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57061e6f41adaa70f2d6dfe2640f7499e4cdd20f/README.md#L345)):*
> ```Markdown
> 
> 1. On Windows, also copy `wintun.dll` to the resource directory:
>    ```
> ```

This code box should have a `bash` tag.
___
*[README.md, line 358 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379#-MQRySM19ZJKbOVN2qT-:-MQRySM19ZJKbOVN2qT0:bsrypve) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57061e6f41adaa70f2d6dfe2640f7499e4cdd20f/README.md#L358)):*
> ```Markdown
> 1. Run the daemon with verbose logging with:
>     ```
>     sudo MULLVAD_RESOURCE_DIR="./dist-assets" ./target/debug/mullvad-daemon -vv
> ```

This will no longer work on Windows, because the previous step changed the context away from bash.


<!-- Sent from Reviewable.io -->

2021-01-08 11:06 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mvd-ows)

___
*[README.md, line 345 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379#-MQRyLK42CdBv-h9zGyP:-MQWe5SZ4PLnjdePhleA:b-fty1ak) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57061e6f41adaa70f2d6dfe2640f7499e4cdd20f/README.md#L345)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This code box should have a `bash` tag.
</blockquote></details>

Done.

Incidentally, wireguard-go will look for `wintun.dll` in the directory where `mullvad-daemon.exe` is. The OpenVPN tunnel uses the resource directory. Normally, they are the same. But ideally it should always use the resource directory.
___
*[README.md, line 358 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379#-MQRySM19ZJKbOVN2qT-:-MQWf40g6vHeN0Rt4ut5:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57061e6f41adaa70f2d6dfe2640f7499e4cdd20f/README.md#L358)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This will no longer work on Windows, because the previous step changed the context away from bash.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-08 12:02 UTC, mvd-ows requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[README.md, line 358 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379#-MQRySM19ZJKbOVN2qT-:-MQWrlrwB9ZMgmsWBXP_:bpsnlq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57061e6f41adaa70f2d6dfe2640f7499e4cdd20f/README.md#L358)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't work. You can't set environment variables like that on Windows.


<!-- Sent from Reviewable.io -->

2021-01-08 12:19 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379)* status: all files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[README.md, line 358 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379#-MQRySM19ZJKbOVN2qT-:-MQWXG6L8Z5Dn8qF5wN6:b-6hoeik) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57061e6f41adaa70f2d6dfe2640f7499e4cdd20f/README.md#L358)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Doesn't work. You can't set environment variables like that on Windows.
</blockquote></details>

You're supposed to open bash in the previous step before doing this. I suppose it might be more readable to replace the previous step with this, though?

```
psexec64 -i -s cmd.exe
set MULLVAD_RESOURCE_DIR=".\dist-assets"
target\debug\mullvad-daemon -vv
```


<!-- Sent from Reviewable.io -->

2021-01-08 12:45 UTC, mvd-ows requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[README.md, line 358 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379#-MQRySM19ZJKbOVN2qT-:-MQX0Nsk60hi2WF16Og4:bjcu1w2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57061e6f41adaa70f2d6dfe2640f7499e4cdd20f/README.md#L358)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You're supposed to open bash in the previous step before doing this. I suppose it might be more readable to replace the previous step with this, though?

```
psexec64 -i -s cmd.exe
set MULLVAD_RESOURCE_DIR=".\dist-assets"
target\debug\mullvad-daemon -vv
```
</blockquote></details>

Right, initially you're in bash, but then `psexec` takes you to a `cmd` context.

So either update the commands to what you suggested, or start another instance of git-bash rather than starting cmd.

(BTW `./dist-assets` is probably wrong because the new console doesn't inherit the working dir?)


<!-- Sent from Reviewable.io -->

2021-01-11 13:23 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[README.md, line 358 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379#-MQRySM19ZJKbOVN2qT-:-MQlbQDN0kjtKqz1mlFH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57061e6f41adaa70f2d6dfe2640f7499e4cdd20f/README.md#L358)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Right, initially you're in bash, but then `psexec` takes you to a `cmd` context.

So either update the commands to what you suggested, or start another instance of git-bash rather than starting cmd.

(BTW `./dist-assets` is probably wrong because the new console doesn't inherit the working dir?)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-11 13:40 UTC, mvd-ows requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[README.md, line 353 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379#-MQlel2U0dq8yeoUDXb_:-MQlel2V63AAGmCQN5v-:bigmri1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2021509c0916c39fa175fa8fe7eebeb5c378972d/README.md#L353)):*
> ```
> bash.exe
> ```

Did you try this? On my machine this attempts to activate WLS1|2.

There is `git-bash.exe` on most developer machines. But it's not in the PATH.


<!-- Sent from Reviewable.io -->

2021-01-11 14:06 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379)* status: all files reviewed, 1 unresolved discussion (waiting on @mvd-ows)

___
*[README.md, line 353 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379#-MQlel2U0dq8yeoUDXb_:-MQljsi50cs0PKSrDcyH:b-2kdtzk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2021509c0916c39fa175fa8fe7eebeb5c378972d/README.md#L353)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

> ```
> bash.exe
> ```

Did you try this? On my machine this attempts to activate WLS1|2.

There is `git-bash.exe` on most developer machines. But it's not in the PATH.
</blockquote></details>

Yes. It's possible that I manually added `C:\Program Files\Git\bin` to PATH, but I think it is also an option in the Git installer.


<!-- Sent from Reviewable.io -->

2021-01-11 14:09 UTC, mvd-ows approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[README.md, line 353 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379#-MQlel2U0dq8yeoUDXb_:-MQlluxG-LBoYYfstLeq:bg96r0j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2021509c0916c39fa175fa8fe7eebeb5c378972d/README.md#L353)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Yes. It's possible that I manually added `C:\Program Files\Git\bin` to PATH, but I think it is also an option in the Git installer.
</blockquote></details>

Hmm.. I've been using `C:\Program Files\Git\git-bash.exe`


<!-- Sent from Reviewable.io -->

2021-01-12 14:48 UTC, merged