Migrate cache files
mullvad/mullvadvpn-app pull request #2384
Opened 2021-01-11 15:11 UTC by dlon

The cache directory is currently found in `C:\Windows\System32\config\systemprofile\AppData\Local\Mullvad VPN`. This is a problem for the problem report tool, which needs to be able to read API addresses, even if it is not run as the SYSTEM user (or even admin). For this reason, that file is currently stored in a separate cache directory to which anyone has read access (but not write access). This PR consolidates the two cache directories into `C:\ProgramData\Mullvad VPN\cache`.

The above description is for Windows, but an analogous change had to be made for macOS.

2021-01-11 21:02 UTC, mvd-ows requested changes
> Reviewed 7 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384)* status: 7 of 16 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[windows/nsis-plugins/src/cleanup/cleaningops.h, line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384#-MQn9m1962UBbQc7IUPb:-MQn9m1A0pRA_nFCBYYD:b-6xh0ll) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/163fc28c09d9287b354eac82540d206929ee0120/windows/nsis-plugins/src/cleanup/cleaningops.h#L6)):*
> ```objc
> {
> 
> void MigrateCacheFilesServiceUser();
> ```

Consistency: Existing functions do not include `Files` in their names.
___
*[windows/nsis-plugins/src/cleanup/cleaningops.cpp, line 133 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384#-MQnAy9L23XWfz43DoEb:-MQnAy9L23XWfz43DoEc:b-cxd0x7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/163fc28c09d9287b354eac82540d206929ee0120/windows/nsis-plugins/src/cleanup/cleaningops.cpp#L133)):*
> ```cpp
> 	const auto newCacheDir = std::filesystem::path(programData).append(L"Mullvad VPN").append(L"cache");
> 
> 	const auto status = CreateDirectoryW(std::wstring(L"\\\\?\\").append(newCacheDir).c_str(), nullptr);
> ```

There's also `common::fs::Mkdir` which implements `mkdir -p` and obscures that hideous prefix.
___
*[windows/nsis-plugins/src/cleanup/cleaningops.cpp, line 358 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384#-MQnF5oD5kVv_GeqBYl5:-MQnF5oD5kVv_GeqBYl6:begv3j6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/163fc28c09d9287b354eac82540d206929ee0120/windows/nsis-plugins/src/cleanup/cleaningops.cpp#L358)):*
> ```cpp
> }
> 
> void RemoveRelayCacheServiceUser()
> ```

Comparing this and the next function with `RemoveCacheServiceUser`, I would have thought that these functions would be referring to the same directory?


<!-- Sent from Reviewable.io -->

2021-01-11 21:02 UTC, mvd-ows reviewed
Thanks, finally!

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384#-:-MQnFSQl2Q0MBQPz2yQV:b-v8i40w)* status: 7 of 16 files reviewed, 3 unresolved discussions (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-01-12 14:10 UTC, faern reviewed
> Reviewed 4 of 16 files at r1, 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384)* status: 6 of 16 files reviewed, 4 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[dist-assets/pkg-scripts/preinstall, line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384#-MQqvP45Aw0u_GVHGjrD:-MQqvP4620hXWESfIGmZ:b-usr3vi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/163fc28c09d9287b354eac82540d206929ee0120/dist-assets/pkg-scripts/preinstall#L62)):*
> ```
> # Migrate cache files from <=2020.8-beta2 paths
> OLD_CACHE_DIRS=(
>     "$HOME/Library/Caches/mullvad-daemon"
> ```

We have stopped supporting `<=2018.1` a **long** time ago. I think we can stop considering these versions in the scripts. If we never remove old migration code it will grow more complex than it needs to be.


<!-- Sent from Reviewable.io -->

2021-01-12 14:15 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384)* status: 6 of 16 files reviewed, 4 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[dist-assets/pkg-scripts/preinstall, line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384#-MQqvP45Aw0u_GVHGjrD:-MQqwX-A9tKmprOyZLF9:b-kcqfij) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/163fc28c09d9287b354eac82540d206929ee0120/dist-assets/pkg-scripts/preinstall#L62)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We have stopped supporting `<=2018.1` a **long** time ago. I think we can stop considering these versions in the scripts. If we never remove old migration code it will grow more complex than it needs to be.
</blockquote></details>

Also, this change removes all all mentions of which versions they migrate from. This is not optimal, as in the future we don't know which path will belong to which version. Making it way harder to know when to remove future paths.

Please remove the `<=2018.1` path completely now and for the remaining `OLD_CACHE_...` paths keep the comment for each specifying what version they are for.


<!-- Sent from Reviewable.io -->

2021-01-12 14:22 UTC, faern reviewed
> Reviewed 5 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384)* status: 11 of 16 files reviewed, 4 unresolved discussions (waiting on @dlon and @mvd-ows)



<!-- Sent from Reviewable.io -->

2021-01-12 14:22 UTC, faern reviewed
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384)* status: 11 of 16 files reviewed, 4 unresolved discussions (waiting on @dlon and @mvd-ows)



<!-- Sent from Reviewable.io -->

2021-01-12 14:29 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384)* status: 11 of 16 files reviewed, 2 unresolved discussions (waiting on @faern and @mvd-ows)

___
*[dist-assets/pkg-scripts/preinstall, line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384#-MQqvP45Aw0u_GVHGjrD:-MQqzPCX1qLuADclM4Fw:b-6wyzq0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/163fc28c09d9287b354eac82540d206929ee0120/dist-assets/pkg-scripts/preinstall#L62)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Also, this change removes all all mentions of which versions they migrate from. This is not optimal, as in the future we don't know which path will belong to which version. Making it way harder to know when to remove future paths.

Please remove the `<=2018.1` path completely now and for the remaining `OLD_CACHE_...` paths keep the comment for each specifying what version they are for.
</blockquote></details>

Alright. Shouldn't the path for `<=2018.2-betaX` be removed as well?
___
*[windows/nsis-plugins/src/cleanup/cleaningops.cpp, line 133 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384#-MQnAy9L23XWfz43DoEb:-MQqzx0N8cO0V1yoDo9I:b-k6guu2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/163fc28c09d9287b354eac82540d206929ee0120/windows/nsis-plugins/src/cleanup/cleaningops.cpp#L133)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

There's also `common::fs::Mkdir` which implements `mkdir -p` and obscures that hideous prefix.
</blockquote></details>

Nice one.
___
*[windows/nsis-plugins/src/cleanup/cleaningops.cpp, line 358 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384#-MQnF5oD5kVv_GeqBYl5:-MQr-3_Q1H7sb534HZYu:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/163fc28c09d9287b354eac82540d206929ee0120/windows/nsis-plugins/src/cleanup/cleaningops.cpp#L358)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Comparing this and the next function with `RemoveCacheServiceUser`, I would have thought that these functions would be referring to the same directory?
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-01-12 14:54 UTC, mvd-ows approved these changes
> Reviewed 5 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2021-01-12 14:54 UTC, mvd-ows approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2021-01-12 15:06 UTC, faern approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[dist-assets/pkg-scripts/preinstall, line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384#-MQqvP45Aw0u_GVHGjrD:-MQr7TwnA4M-Z46Hun9K:bh2l5ep) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/163fc28c09d9287b354eac82540d206929ee0120/dist-assets/pkg-scripts/preinstall#L62)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Alright. Shouldn't the path for `<=2018.2-betaX` be removed as well?
</blockquote></details>

Ah, yes please. That's also **very** outdated. Should be fine to remove that as well.


<!-- Sent from Reviewable.io -->

2021-01-12 15:12 UTC, faern reviewed
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384)* status: 15 of 16 files reviewed, all discussions resolved (waiting on @faern)



<!-- Sent from Reviewable.io -->

2021-01-12 15:13 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384)* status: 15 of 16 files reviewed, all discussions resolved (waiting on @faern)

___
*[dist-assets/pkg-scripts/preinstall, line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384#-MQqvP45Aw0u_GVHGjrD:-MQr8wb5Aaj74zqsdsMb:baqndfi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/163fc28c09d9287b354eac82540d206929ee0120/dist-assets/pkg-scripts/preinstall#L62)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Ah, yes please. That's also **very** outdated. Should be fine to remove that as well.
</blockquote></details>

I did the same for settings and logs.


<!-- Sent from Reviewable.io -->

2021-01-12 15:13 UTC, faern approved these changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-12 15:39 UTC, merged