[DO NOT MERGE] Run service on a separate process on Android
mullvad/mullvadvpn-app pull request #2396
Opened 2021-01-19 15:38 UTC by jvff

This is a draft PR to discuss the overall design and architecture of the approach of splitting the Android app in two processes. The final code will be pushed as separate PRs.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-01-20 06:21 UTC, axti commented on android/src/main/kotlin/net/mullvad/mullvadvpn/model/KeygenEvent.kt
> +    class TooManyKeys() : KeygenFailure(), Parcelable
Could it be just an object?

2021-01-20 06:24 UTC, axti commented on android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt
>          fun get0() = countryCode
Can you explain why do we have get0 get1 get2?

2021-01-20 06:35 UTC, axti commented on android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelayList.kt
> +data class RelayList(val countries: ArrayList<RelayListCountry>) : Parcelable
Check typealis, looks like suitable: 
https://kotlinlang.org/docs/reference/type-aliases.html

2021-01-20 06:38 UTC, axti commented on android/src/main/kotlin/net/mullvad/mullvadvpn/model/Settings.kt
>  data class Settings(
Maybe name is not clear. Is it user settings or vpn settings or global settings?

2021-01-20 07:22 UTC, axti commented on android/src/main/kotlin/net/mullvad/mullvadvpn/model/VoucherSubmissionResult.kt
> +    class Ok(val submission: VoucherSubmission) : VoucherSubmissionResult(), Parcelable
data class maybe?

2021-01-20 07:24 UTC, axti commented on android/src/main/kotlin/net/mullvad/mullvadvpn/model/VoucherSubmissionResult.kt
> +    class OtherError : VoucherSubmissionResult(), Parcelable
should we have any throwable or string inside error (e.g. error message)?

2021-01-20 10:59 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396)* status: 0 of 92 files reviewed, 6 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/KeygenEvent.kt, line 34 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MRQI3wx70eUk-bxCy7S-r1-34:-MRUECz9Aynm3m_JYQYP:b-4178k4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/242cc9ac6575dfcac3b206018d5ee742b195d2e9/android/src/main/kotlin/net/mullvad/mullvadvpn/model/KeygenEvent.kt#L34)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Could it be just an object?
</blockquote></details>

Yes, that would be much better. However, that also requires a change in the `jnix` Rust crate. I'll see if I can get that done soon.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MRQI3wx70eUk-bxCy7T-r1-22:-MRUENEKAu9wPcOYH3ss:byhqtl5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/242cc9ac6575dfcac3b206018d5ee742b195d2e9/android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt#L22)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Can you explain why do we have get0 get1 get2?
</blockquote></details>

Sure, this is because the Rust side has a macro to generate the code for converting from a Java type. The code generated doesn't know the name of the properties if the Rust type is a tuple, so it uses indices to represent the elements in order.

An example:

```
struct MyType {
    my_field: i32, // Would need the MyType class to have a getMyField getter
}
```

```
struct MyTuple(i32); // This needs a MyTuple.get0 getter, because the Rust type has no name for the field
``` 
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelayList.kt, line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MRQI3wx70eUk-bxCy7X-r1-8:-MRUHCz7EJUNT_h4zIVW:b9cds2d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/242cc9ac6575dfcac3b206018d5ee742b195d2e9/android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelayList.kt#L8)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Check typealis, looks like suitable: 
https://kotlinlang.org/docs/reference/type-aliases.html
</blockquote></details>

I'm not sure I understood. What type alias do you think should be created?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/Settings.kt, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MRQI3wx70eUk-bxCy7b-r1-7:-MRUJFGQ-5EFG-zLsjPx:b-yt1iaq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/242cc9ac6575dfcac3b206018d5ee742b195d2e9/android/src/main/kotlin/net/mullvad/mullvadvpn/model/Settings.kt#L7)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Maybe name is not clear. Is it user settings or vpn settings or global settings?
</blockquote></details>

Yeah, unfortunately this follows the name from the daemon in Rust. This class maps to the `Settings` Rust type defined there. It's kind of the global settings, at least all the ones that are handled by the daemon. Most of them are handled there, except a few exceptions (split tunneling is an example).
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/VoucherSubmissionResult.kt, line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MRQI3wx70eUk-bxCy7f-r1-21:-MRUNQE-17cEAmm5-L6M:blex7d2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/242cc9ac6575dfcac3b206018d5ee742b195d2e9/android/src/main/kotlin/net/mullvad/mullvadvpn/model/VoucherSubmissionResult.kt#L21)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

should we have any throwable or string inside error (e.g. error message)?
</blockquote></details>

I'm not sure. If this error occurs, it will already be logged by the Rust side (https://github.com/mullvad/mullvadvpn-app/blob/master/mullvad-jni/src/lib.rs#L906), and the Java side doesn't have to do anything (because it's very likely that the error is already being handled by the `DaemonInstance` class by restarting the daemon).


<!-- Sent from Reviewable.io -->

2021-01-21 21:42 UTC, pinkisemils reviewed
> Reviewed 22 of 92 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396)* status: 22 of 93 files reviewed, 7 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/LoginStatus.kt, line 14 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MR_a7q-5lx3LdlfWqI0:-MR_a7q-5lx3LdlfWqI1:b-c64quz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/993f382f5f8ea5143bc19cea3aea10ff39fe6dc9/android/src/main/kotlin/net/mullvad/mullvadvpn/model/LoginStatus.kt#L14)):*
> ```Kotlin
> ) : Parcelable {
>     val isExpired: Boolean
>         get() = expiry != null && expiry.isAfterNow()
> ```

Do we only allow a login after the user has reached the API on Android?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt, line 148 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MR_uQnv7jcoPOstoJan:-MR_uQnv7jcoPOstoJao:b4tcdug) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/993f382f5f8ea5143bc19cea3aea10ff39fe6dc9/android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt#L148)):*
> ```Kotlin
>     private fun spawnActor() = GlobalScope.actor<Command>(Dispatchers.Default, Channel.UNLIMITED) {
>         try {
>             val command = channel.receive()
> ```

Should this be a loop ? Or is there only ever going to be a single command issues? In that case, does it make sense to have this be an actor? The code could then be simplified by just making all the `do***` methods synchronized.


<!-- Sent from Reviewable.io -->

2021-01-22 12:32 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396)* status: 22 of 93 files reviewed, 7 unresolved discussions (waiting on @axti, @jvff, and @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/LoginStatus.kt, line 14 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MR_a7q-5lx3LdlfWqI0:-MRe3zMz4DWJpMfb-ZkO:bs3su2c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/993f382f5f8ea5143bc19cea3aea10ff39fe6dc9/android/src/main/kotlin/net/mullvad/mullvadvpn/model/LoginStatus.kt#L14)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Do we only allow a login after the user has reached the API on Android?
</blockquote></details>

No, the service side `AccountCache` now handles the login logic, and it will allow a login if the RPC communication fails.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt, line 148 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MR_uQnv7jcoPOstoJan:-MRe4DzVCD0Co0Kn7E-U:b-ax0ybv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/993f382f5f8ea5143bc19cea3aea10ff39fe6dc9/android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt#L148)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Should this be a loop ? Or is there only ever going to be a single command issues? In that case, does it make sense to have this be an actor? The code could then be simplified by just making all the `do***` methods synchronized.
</blockquote></details>

Oops, good catch. I'll fix this :+1:


<!-- Sent from Reviewable.io -->

2021-04-23 09:28 UTC, axti requested changes
> Reviewed 14 of 92 files at r3, 1 of 7 files at r4, 5 of 40 files at r5, 65 of 65 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396)* status: all files reviewed, 6 unresolved discussions (waiting on @jvff and @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, line 34 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MYxxbpE-OR8Pr7hKrFg:-MYxxbpE-OR8Pr7hKrFh:b-dj1t1n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/be4e0f9080632b8df59bedb1316b6788f7bebc5e/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L34)):*
> ```
> private var service: Messenger? = null
> ```
Sorry, I didn't find where do you assign any value to this property?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/RedeemVoucherDialogFragment.kt, line 130 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MYy-FvsB0V02qAGL80M:-MYy-FvsB0V02qAGL80N:b-gkf8zo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cfdc91678a64057df3cb684eda336b66885b4ce/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/RedeemVoucherDialogFragment.kt#L130)):*
> ```
>         redeemButton?.apply {
>             setEnabled(voucherInputIsValid && voucherRedeemer != null)
>         }
> ```
Can we simplify it to:
`redeemButton?.setEnabled(voucherInputIsValid && voucherRedeemer != null)`
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/NotificationWithUrlWithToken.kt, line 11 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MYy04Ew4n9UxiAa8w6U:-MYy04Ew4n9UxiAa8w6V:bsp9uyz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cfdc91678a64057df3cb684eda336b66885b4ce/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/NotificationWithUrlWithToken.kt#L11)):*
> ```
> urlId: Int
> ```
Could be good to add `@StringRes` annotation.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/util/Intermittent.kt, line 28 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MYy2OgRBfGvhmjCf8wR:-MYy2OgRBfGvhmjCf8wS:bbfxd3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cfdc91678a64057df3cb684eda336b66885b4ce/android/src/main/kotlin/net/mullvad/mullvadvpn/util/Intermittent.kt#L28)):*
> ```
> class Intermittent
> ```
Do you have any tests for this class or do you plan to add them?


<!-- Sent from Reviewable.io -->

2021-04-23 10:04 UTC, pinkisemils approved these changes
> Reviewed 14 of 92 files at r3, 1 of 7 files at r4, 4 of 40 files at r5, 9 of 65 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396)* status: all files reviewed, 5 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/VoucherSubmissionResult.kt, line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MRQI3wx70eUk-bxCy7f-r1-9:-MYy6UoP7tC_HSTOukuy:bua0h62) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/242cc9ac6575dfcac3b206018d5ee742b195d2e9/android/src/main/kotlin/net/mullvad/mullvadvpn/model/VoucherSubmissionResult.kt#L9)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

data class maybe?
</blockquote></details>

Wouldn't hurt.


<!-- Sent from Reviewable.io -->

2021-04-23 13:20 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396)* status: 94 of 97 files reviewed, 5 unresolved discussions (waiting on @axti and @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/VoucherSubmissionResult.kt, line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MRQI3wx70eUk-bxCy7f-r1-9:-MYylk_R0zTabD1NW79E:b-uv0ytr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/242cc9ac6575dfcac3b206018d5ee742b195d2e9/android/src/main/kotlin/net/mullvad/mullvadvpn/model/VoucherSubmissionResult.kt#L9)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Wouldn't hurt.
</blockquote></details>

Done, as part of a separate PR (#2697).
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, line 34 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MYxxbpE-OR8Pr7hKrFg:-MYymSyl2QIebtRl3L4p:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/be4e0f9080632b8df59bedb1316b6788f7bebc5e/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L34)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> private var service: Messenger? = null
> ```
Sorry, I didn't find where do you assign any value to this property?
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/RedeemVoucherDialogFragment.kt, line 130 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MYy-FvsB0V02qAGL80M:-MYyqvuuEaLoElyYNsYb:b-ec4tfj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cfdc91678a64057df3cb684eda336b66885b4ce/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/RedeemVoucherDialogFragment.kt#L130)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>         redeemButton?.apply {
>             setEnabled(voucherInputIsValid && voucherRedeemer != null)
>         }
> ```
Can we simplify it to:
`redeemButton?.setEnabled(voucherInputIsValid && voucherRedeemer != null)`
</blockquote></details>

Done, as part of other PR (#2697).
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/NotificationWithUrlWithToken.kt, line 11 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MYy04Ew4n9UxiAa8w6U:-MYyqRby0JXBnuQTtQHb:b-yspetz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cfdc91678a64057df3cb684eda336b66885b4ce/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/NotificationWithUrlWithToken.kt#L11)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> urlId: Int
> ```
Could be good to add `@StringRes` annotation.
</blockquote></details>

Done, on a separate PR (#2698).
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/util/Intermittent.kt, line 28 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396#-MYy2OgRBfGvhmjCf8wR:-MYyqXiN4ewVDHmIB_Tq:bydiidh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cfdc91678a64057df3cb684eda336b66885b4ce/android/src/main/kotlin/net/mullvad/mullvadvpn/util/Intermittent.kt#L28)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> class Intermittent
> ```
Do you have any tests for this class or do you plan to add them?
</blockquote></details>

I can do that later in a separate PR.


<!-- Sent from Reviewable.io -->

2021-04-23 13:25 UTC, axti approved these changes
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-23 13:25 UTC, axti approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-23 14:10 UTC, pinkisemils approved these changes
> Reviewed 1 of 92 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-23 14:10 UTC, pinkisemils approved these changes
> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-23 14:18 UTC, pinkisemils approved these changes
> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-23 14:18 UTC, pinkisemils approved these changes
> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-23 14:19 UTC, pinkisemils approved these changes
> Reviewed 1 of 92 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-23 14:26 UTC, merged