Add IP version constraint for WireGuard
mullvad/mullvadvpn-app pull request #2422
Opened 2021-01-29 11:27 UTC by dlon

This adds a relay constraint for connecting to relays over IPv6. It can be enabled in the CLI:

```
mullvad relay set tunnel wireguard --ip 6
```

If the constraint is set to either `4` or `Any`, then the relay selector will always prefer the IPv4 address.

2021-01-29 14:51 UTC, pinkisemils reviewed
> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422)* status: 8 of 9 files reviewed, all discussions resolved

___
*[mullvad-daemon/src/relays.rs, line 652 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422#-MSDb_HU91nIeAbbxfI6:-MSDb_HU91nIeAbbxfI7:bt6dahe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9dba11614a88e82c11e1142a8751fbec7efc4613/mullvad-daemon/src/relays.rs#L652)):*
> ```Rust
>                             relay.ipv4_addr_in.into()
>                         }
>                         Constraint::Only(IpVersion::V6) => relay
> ```

Shouldn't relays without IPv6 entry addresses be filtered out at this point in time?
I think this would greatly benefit from having a unit test to see this does what it needs to do and then have a panic here IMO. But that might necessitate clients update their filters so that IPv6 and IPv4 relays are filtered properly. Or maybe this here is the expected behavior - maybe @faern can have a better idea as to what is supposed to happen here.
___
*[mullvad-daemon/src/relays.rs, line 665 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422#-MSDadhMCkL6DdbaYC5K:-MSDadhMCkL6DdbaYC5L:b-xotqbe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9dba11614a88e82c11e1142a8751fbec7efc4613/mullvad-daemon/src/relays.rs#L665)):*
> ```Rust
>         };
> 
>         match constraints.tunnel_protocol {
> ```

I think to simplify this code, it'd be better to just have this match statement only be compiled on _not_ android, and have the android codepath just be a single expression (since it's always going to be WireGuard on Android).


<!-- Sent from Reviewable.io -->

2021-01-29 15:02 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422)* status: 8 of 9 files reviewed, all discussions resolved

___
*[mullvad-daemon/src/relays.rs, line 652 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422#-MSDb_HU91nIeAbbxfI6:-MSDd7sI8k0LMTSOaWEY:bcz00s1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9dba11614a88e82c11e1142a8751fbec7efc4613/mullvad-daemon/src/relays.rs#L652)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Shouldn't relays without IPv6 entry addresses be filtered out at this point in time?
I think this would greatly benefit from having a unit test to see this does what it needs to do and then have a panic here IMO. But that might necessitate clients update their filters so that IPv6 and IPv4 relays are filtered properly. Or maybe this here is the expected behavior - maybe @faern can have a better idea as to what is supposed to happen here.
</blockquote></details>

Probably, yes.

Looking at `mullvad_rpc::relay_list`, it looks as if it isn't really optional. Also, the API does currently return IPv6 addresses for all relays. Am I mistaken?


<!-- Sent from Reviewable.io -->

2021-02-01 16:22 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-cli/src/cmds/relay.rs, line 163 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422#-MSTO0nN8tosTD7XrXzG:-MSTO0nP5tNZLwvI_nqV:b-w0cav8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9dba11614a88e82c11e1142a8751fbec7efc4613/mullvad-cli/src/cmds/relay.rs#L163)):*
> ```Rust
>                                     .required(false)
>                                     .default_value("any")
>                                     .possible_values(&["any", "4", "6"]),
> ```

An argument named `--ip` not taking an IP address is very much going against my instincts. Can we name the flag "ip version" instead of "ip protocol"? We have enough "protocol"s in this daemon already. It's transport protocols and tunnel protocols etc. `--ipv` might not be perfect, but it's at least not using a long name where everyone will assume it takes an IP address as argument.

We need to overhaul the UX of the CLI in general. But the more careful we are when adding new features now the less work will have to be done and fewer breaking changes when that overhaul comes.


<!-- Sent from Reviewable.io -->

2021-02-02 10:27 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[mullvad-cli/src/cmds/relay.rs, line 163 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422#-MSTO0nN8tosTD7XrXzG:-MSXH5qO3swSec8s1PNI:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9dba11614a88e82c11e1142a8751fbec7efc4613/mullvad-cli/src/cmds/relay.rs#L163)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

An argument named `--ip` not taking an IP address is very much going against my instincts. Can we name the flag "ip version" instead of "ip protocol"? We have enough "protocol"s in this daemon already. It's transport protocols and tunnel protocols etc. `--ipv` might not be perfect, but it's at least not using a long name where everyone will assume it takes an IP address as argument.

We need to overhaul the UX of the CLI in general. But the more careful we are when adding new features now the less work will have to be done and fewer breaking changes when that overhaul comes.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/relays.rs, line 665 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422#-MSDadhMCkL6DdbaYC5K:-MSXH9i283TG56RyowM-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9dba11614a88e82c11e1142a8751fbec7efc4613/mullvad-daemon/src/relays.rs#L665)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think to simplify this code, it'd be better to just have this match statement only be compiled on _not_ android, and have the android codepath just be a single expression (since it's always going to be WireGuard on Android).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-02 22:32 UTC, pinkisemils reviewed
> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[mullvad-types/src/relay_constraints.rs, line 415 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422#-MSZrhvX-TKGKAaaVede:-MSZrhvX-TKGKAaaVedf:bwfimhr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78cd8b1d0b2120195338b0bd94b187ea5e6a2891/mullvad-types/src/relay_constraints.rs#L415)):*
> ```Rust
> 
> impl Match<WireguardEndpointData> for WireguardConstraints {
>     fn matches(&self, endpoint: &WireguardEndpointData) -> bool {
> ```

Shouldn't this function be updated too? Or does this implementation not matter because an IPv4 address be turned in an IPv6 one?


<!-- Sent from Reviewable.io -->

2021-02-03 11:23 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-types/src/relay_constraints.rs, line 415 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422#-MSZrhvX-TKGKAaaVede:-MSbcCiX2VsI3cZDADMx:b-z62sff) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78cd8b1d0b2120195338b0bd94b187ea5e6a2891/mullvad-types/src/relay_constraints.rs#L415)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Shouldn't this function be updated too? Or does this implementation not matter because an IPv4 address be turned in an IPv6 one?
</blockquote></details>

All WireGuard endpoints are currently assigned in-v6 addresses, which means that any constraint would match here.


<!-- Sent from Reviewable.io -->

2021-02-04 15:02 UTC, pinkisemils approved these changes
> Reviewed 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-09 12:22 UTC, pinkisemils reviewed
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2021-03-01 14:01 UTC, merged