Implement Intermittent daemon
mullvad/mullvadvpn-app pull request #2439
Opened 2021-02-05 18:46 UTC by jvff

There are certain parts of the app that can only work if a daemon instance is available. Most of the time there will be an instance available, but there are situations where it's not available:

- When the service (and/or the daemon) is still starting
- When the daemon has crashed and is restarting
- When the service was requested to stop but then requested to start shortly afterwards, so it must perform a "soft restart"

Previously, the code that depended on the daemon instance availability would operate through callbacks, so that they can correctly handle the events of an instance becoming available or unavailable. This added complexity to the code, which is exacerbated by the refactor to split the app in two processes.

This PR attempts to collect that complexity into a single helper class, called `Intermittent`. It is responsible for waiting for something (it has a generic type parameter) to become available, and suspends any coroutines needed that something until it becomes available. It still provides an `EventNotifier` endpoint for registering callbacks for the use cases that still need it.

The PR also performs a small change in `EventNotifier` to make it notify listeners in the order that they were registered, so that the creator of an `EventNotifier` can register specific callbacks to be executed before any other listener is notified.

The new `Intermittent` class is then used by the `DaemonInstance` class. The `DaemonInstance` class exposes an `Intermittent<MullvadDaemon>` and updates it internally whenever the instance becomes available or unavailable. The classes that still use `MullvadDaemon` directly will be changed by future PRs that incrementally remove the `ServiceInstance` callback channel.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header. **Internal refactor, no user visible changes.**
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-02-09 00:25 UTC, pinkisemils requested changes
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2439)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/util/Intermittent.kt, line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2439#-MT39xMWDU7PLHUrKbOo:-MT396e63Dgk5NpkZJ64:bh0de0g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e19d347cc21fc8ad7133292e6131e7e02719254b/android/src/main/kotlin/net/mullvad/mullvadvpn/util/Intermittent.kt#L32)):*
> ```Kotlin
> class Intermittent<T> {
>     private val notifier = EventNotifier<T?>(null)
>     private val semaphore = Semaphore(1, 1)
> ```

Could the semaphore be replaced with a conditional variable? You could awake coroutines that are awaiting a value when it's being updated. A sempahore with a permit of 1 is a mutex anyway. I don't see a way that the semaphore might be bumped to more than 1 lease at a time - in which case I think using a regular mutex might be good enough?


<!-- Sent from Reviewable.io -->

2021-02-09 01:07 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2439)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/util/Intermittent.kt, line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2439#-MT39xMWDU7PLHUrKbOo:-MT3JBwU9XhASFrPn7ik:b-dn8czm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e19d347cc21fc8ad7133292e6131e7e02719254b/android/src/main/kotlin/net/mullvad/mullvadvpn/util/Intermittent.kt#L32)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Could the semaphore be replaced with a conditional variable? You could awake coroutines that are awaiting a value when it's being updated. A sempahore with a permit of 1 is a mutex anyway. I don't see a way that the semaphore might be bumped to more than 1 lease at a time - in which case I think using a regular mutex might be good enough?
</blockquote></details>

I couldn't find a conditional variable implementation for coroutines. There's only Mutexes and Semaphores in the Kotlin standard coroutines library =/

While you're right that a mutex can be implemented by wrapping a semaphore with a single permit, the inverse is not true. A semaphore with a permit of one can have the permit released by any thread without prior notice, unblocking a single thread, while a mutex can only be unlocked/released by the first thread to lock it.


<!-- Sent from Reviewable.io -->

2021-02-09 10:37 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2439)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/util/Intermittent.kt, line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2439#-MT39xMWDU7PLHUrKbOo:-MT5LX8JC7xYmwQ5M043:b-e4o6ta) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e19d347cc21fc8ad7133292e6131e7e02719254b/android/src/main/kotlin/net/mullvad/mullvadvpn/util/Intermittent.kt#L32)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I couldn't find a conditional variable implementation for coroutines. There's only Mutexes and Semaphores in the Kotlin standard coroutines library =/

While you're right that a mutex can be implemented by wrapping a semaphore with a single permit, the inverse is not true. A semaphore with a permit of one can have the permit released by any thread without prior notice, unblocking a single thread, while a mutex can only be unlocked/released by the first thread to lock it.
</blockquote></details>

There is an Android specific [implementation](https://developer.android.com/reference/kotlin/android/os/ConditionVariable).


<!-- Sent from Reviewable.io -->

2021-02-09 10:50 UTC, pinkisemils approved these changes
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2439)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/util/Intermittent.kt, line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2439#-MT39xMWDU7PLHUrKbOo:-MT5OrlD9t1FPn03iYj5:byrxjii) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e19d347cc21fc8ad7133292e6131e7e02719254b/android/src/main/kotlin/net/mullvad/mullvadvpn/util/Intermittent.kt#L32)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

There is an Android specific [implementation](https://developer.android.com/reference/kotlin/android/os/ConditionVariable).
</blockquote></details>

Ah, but that is not coroutine friendly :/ I guess then the semaphore will be the best one can do here.


<!-- Sent from Reviewable.io -->

2021-02-11 14:31 UTC, axti commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 





<!-- Sent from Reviewable.io -->

2021-02-11 14:31 UTC, axti commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2021-02-11 16:06 UTC, pinkisemils approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2439)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-11 17:23 UTC, merged