Update suggested upgrade version when enabling/disabling beta program
mullvad/mullvadvpn-app pull request #2447
Opened 2021-02-09 14:52 UTC by raksooo

This PR updates the value of `suggested_upgrade` and emits it to clients when `set_show_beta_releases` is called. This fixes the issue where the GUI doesn't show/hide the notification telling the user to upgrade after the beta program toggle has been changed.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-02-09 14:54 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2447)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[mullvad-daemon/src/lib.rs, line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2447#-MT6GvQoEWrhklk2jA-4:-MT6GuSxEaW3YWt0AP9T:b-se2278) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/32e858bae5aef36bf799ba4506124a1f24ecc7d0/mullvad-daemon/src/lib.rs#L2)):*
> ```XML
> #![deny(rust_2018_idioms)]
> #![recursion_limit = "512"]
> ```

I don't know why this change is needed but as soon as I added code inside the `futures::select` macro I got compilation errors for exceeding the maximum recursion depth or something.


<!-- Sent from Reviewable.io -->

2021-02-09 21:44 UTC, pinkisemils requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2447)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[mullvad-daemon/src/lib.rs, line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2447#-MT6GvQoEWrhklk2jA-4:-MT6xe90Ert54LrmIpKd:b-qnn6yo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/32e858bae5aef36bf799ba4506124a1f24ecc7d0/mullvad-daemon/src/lib.rs#L2)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I don't know why this change is needed but as soon as I added code inside the `futures::select` macro I got compilation errors for exceeding the maximum recursion depth or something.
</blockquote></details>

This is fine and expected. The select macro is recursive, and the recursion is artificially bound because most of the time runaway recursion is a bug.
___
*[mullvad-daemon/src/version_check.rs, line 256 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2447#-MT70ywU0J9mF2hPFmkj:-MT70ywVCfGT42-28mkg:b-icbnzy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/32e858bae5aef36bf799ba4506124a1f24ecc7d0/mullvad-daemon/src/version_check.rs#L256)):*
> ```XML
>     }
> 
>     async fn update_version_info(&mut self, new_version_info: AppVersionInfo) -> () {
> ```

If a function returns nothing, you don't need to add `-> ()`.


<!-- Sent from Reviewable.io -->

2021-02-10 08:37 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2447)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-daemon/src/version_check.rs, line 256 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2447#-MT70ywU0J9mF2hPFmkj:-MTA4hhf0_8MtCnq_HTg:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/32e858bae5aef36bf799ba4506124a1f24ecc7d0/mullvad-daemon/src/version_check.rs#L256)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

If a function returns nothing, you don't need to add `-> ()`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-10 12:47 UTC, pinkisemils approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2447)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-10 15:05 UTC, pinkisemils approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2447)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-10 15:27 UTC, merged