Use non-quick rules for blocking all traffic on macOS.
mullvad/mullvadvpn-app pull request #2460
Opened 2021-02-11 16:27 UTC by pinkisemils

To allow users to add their own custom firewall rules, we shouldn't have all of our rules be eagerly evaluated, more specifically, our all encompassing blocking rules shouldn't be eagerly evaluated. These changes make it so.

I've tested these changes for leaks when changing between all states and I have also added a permissive rule to `/etc/pf.conf` to allow UDP traffic to 8.8.8.8 on port 53 (both ways), and this _hole_ does work in all the blocking states too, so I am asuming my changes achieve the wanted results in #2171.

2021-02-11 17:27 UTC, faern requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[CHANGELOG.md, line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460#-MTH6xBK-nLR7OdEfEzA:-MTH6xBK-nLR7OdEfEzB:bem8tpf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5eddde96bdf1b035205351d06b8fa8ad63bc27fe/CHANGELOG.md#L60)):*
> ```Markdown
> #### macOS
> - Change blocking firewall rules to not be _quick_ to allow for user specified rules in `pf` to
>   circumvent our rules.
> ```

This changelog entry is not in the right spot. You probably have to do some rebasing.
___
*[talpid-core/src/firewall/macos.rs, line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460#-MTH739JCaqY8DGGXui8:-MTH739JCaqY8DGGXui9:b-1imaiv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/435f4115cf1049854df6fe9a96eae4822630b379/talpid-core/src/firewall/macos.rs#L84)):*
> ```XML
>         let drop_all_rule = self
>             .create_rule_builder(FilterRuleAction::Drop(DropAction::Drop))
>             .quick(true)
> ```

I cannot figure out super easily if this is going to keep the security tight. But I trust you have tried it. We can always merge it to master. But we should give it another look before any release. I'd like to run it and look at the actual rules produced.


<!-- Sent from Reviewable.io -->

2021-02-11 18:53 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[CHANGELOG.md, line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460#-MTH6xBK-nLR7OdEfEzA:-MTHR4YxAcxDJS4_ShZA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5eddde96bdf1b035205351d06b8fa8ad63bc27fe/CHANGELOG.md#L60)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This changelog entry is not in the right spot. You probably have to do some rebasing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-12 00:42 UTC, dlon reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460)* status: all files reviewed, 2 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 131 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460#-MTIdx74BoEZxGUTdWp9:-MTIdx756Mu88CWFkbMD:bvy1ugq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/804584178520b00e9386b9980013180742d5364a/talpid-core/src/firewall/macos.rs#L131)):*
> ```XML
>                 rules.append(&mut self.get_block_dns_rules()?);
> 
>                 rules.push(self.get_allow_tunnel_rule(tunnel.interface.as_str())?);
> ```

Does this rule override later, more restrictive rules (not in this ruleset) by letting "everything" pass through the tunnel?


<!-- Sent from Reviewable.io -->

2021-02-12 10:29 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @faern)

___
*[talpid-core/src/firewall/macos.rs, line 131 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460#-MTIdx74BoEZxGUTdWp9:-MTKcvLTBWktz66cZgj3:bb77ufg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/804584178520b00e9386b9980013180742d5364a/talpid-core/src/firewall/macos.rs#L131)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Does this rule override later, more restrictive rules (not in this ruleset) by letting "everything" pass through the tunnel?
</blockquote></details>

Yes.


<!-- Sent from Reviewable.io -->

2021-02-12 10:33 UTC, faern approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-02-12 12:27 UTC, dlon approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 131 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460#-MTIdx74BoEZxGUTdWp9:-MTLBuN5BgbhHQ2aFd34:bapdxxm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/804584178520b00e9386b9980013180742d5364a/talpid-core/src/firewall/macos.rs#L131)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Is that intentional? I'm assuming that the point here is to allow users to also block things that we currently allow (and vice versa).


<!-- Sent from Reviewable.io -->

2021-02-12 12:36 UTC, faern approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 131 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460#-MTIdx74BoEZxGUTdWp9:-MTLE-8f1tAIRL9h4sM9:bb40u3w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/804584178520b00e9386b9980013180742d5364a/talpid-core/src/firewall/macos.rs#L131)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is that intentional? I'm assuming that the point here is to allow users to also block things that we currently allow (and vice versa).
</blockquote></details>

If we can easily get both that would be cool. But again. A single person has asked for this during the entire lifetime of the app. And security is paramount here. So we can't possibly change the rules in any way that jeopardizes security to accommodate the feature. If we can only easily get part of the feature we should likely stop there. I don't know currently what we can get really.


<!-- Sent from Reviewable.io -->

2021-02-12 12:45 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2460#-MTH739JCaqY8DGGXui8:-MTLEvJ4Dwclp8CsTL69:b-8ngkjr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/435f4115cf1049854df6fe9a96eae4822630b379/talpid-core/src/firewall/macos.rs#L84)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I cannot figure out super easily if this is going to keep the security tight. But I trust you have tried it. We can always merge it to master. But we should give it another look before any release. I'd like to run it and look at the actual rules produced.
</blockquote></details>

I have a similar concern, sounds like "drop all" would definitely interfere.


<!-- Sent from Reviewable.io -->

2021-02-12 13:57 UTC, pinkisemils commented
Dropping this as our rules can be circumvented via anchors already.

2021-02-12 13:57 UTC, closed without merging