Only update the relay list if it has changed
mullvad/mullvadvpn-app pull request #2462
Opened 2021-02-11 17:47 UTC by dlon

The relay list endpoint (https://api.mullvad.net/v1/relays) will soonish include ETags in its responses. Setting the `If-None-Match` header to this value allows the server to respond with 304 instead of sending back the entire unmodified list (saving ~1 MB per hour).

2021-02-11 19:14 UTC, pinkisemils requested changes
> Reviewed 6 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2462)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-rpc/src/lib.rs, line 366 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2462#-MTHUM6A0wOKs2Q4XZO-:-MTHUM6A0wOKs2Q4XZO0:b-nmrtaj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c9b7e4ba740126ceb6419292f8730c009fd2d99/mullvad-rpc/src/lib.rs#L366)):*
> ```XML
>         let request = self.handle.factory.request(&path, Method::GET);
> 
>         let platform_version = platform_version.to_string();
> ```

Are these changes required at all?
___
*[mullvad-rpc/src/relay_list.rs, line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2462#-MTHS2PNAwk4s_8SvQ_t:-MTHS2PNAwk4s_8SvQ_u:b-jrr53o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c9b7e4ba740126ceb6419292f8730c009fd2d99/mullvad-rpc/src/relay_list.rs#L54)):*
> ```XML
> 
>             let etag = response.headers().get(header::ETAG).and_then(|tag| {
>                 let tag = tag.to_str();
> ```

Purely a nitpick, but I think shadowing `tag` when it's only ever invoked once seems a bit silly to me.
___
*[mullvad-rpc/src/relay_list.rs, line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2462#-MTHVXYM49oC4uCKrEKY:-MTHVXYM49oC4uCKrEKZ:by1dr48) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c9b7e4ba740126ceb6419292f8730c009fd2d99/mullvad-rpc/src/relay_list.rs#L58)):*
> ```XML
>                     Ok(tag) => Some(tag.to_string()),
>                     Err(_) => {
>                         log::error!("Ignoring invalid tag from server");
> ```

It'd be nice to log the invalid etag value.
___
*[mullvad-types/src/relay_list.rs, line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2462#-MTHVavo6xoBzeDcso3r:-MTHVavo6xoBzeDcso3s:bymr0q3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c9b7e4ba740126ceb6419292f8730c009fd2d99/mullvad-types/src/relay_list.rs#L24)):*
> ```XML
> #[cfg_attr(target_os = "android", jnix(package = "net.mullvad.mullvadvpn.model"))]
> pub struct RelayList {
>     pub etag: Option<String>,
> ```

Is the etag supposed to be valid UTF-8? Could it not be just a bunch of bytes?


<!-- Sent from Reviewable.io -->

2021-02-12 10:03 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2462)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-rpc/src/lib.rs, line 366 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2462#-MTHUM6A0wOKs2Q4XZO-:-MTKXkqw7XcaP-NTEaof:b-p2q8gl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c9b7e4ba740126ceb6419292f8730c009fd2d99/mullvad-rpc/src/lib.rs#L366)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Are these changes required at all?
</blockquote></details>

Nope. Reverted. `platform_version` being a `String` just looked a bit wrong to me.
___
*[mullvad-rpc/src/relay_list.rs, line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2462#-MTHS2PNAwk4s_8SvQ_t:-MTKdOJU0UqMpsP0kikl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c9b7e4ba740126ceb6419292f8730c009fd2d99/mullvad-rpc/src/relay_list.rs#L54)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Purely a nitpick, but I think shadowing `tag` when it's only ever invoked once seems a bit silly to me.
</blockquote></details>

Done.
___
*[mullvad-rpc/src/relay_list.rs, line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2462#-MTHVXYM49oC4uCKrEKY:-MTKdPMiEaeh__07UPCh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c9b7e4ba740126ceb6419292f8730c009fd2d99/mullvad-rpc/src/relay_list.rs#L58)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It'd be nice to log the invalid etag value.
</blockquote></details>

Done.
___
*[mullvad-types/src/relay_list.rs, line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2462#-MTHVavo6xoBzeDcso3r:-MTKe9fQ8bZ0CjueWFpz:b-mk1ng) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c9b7e4ba740126ceb6419292f8730c009fd2d99/mullvad-types/src/relay_list.rs#L24)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Is the etag supposed to be valid UTF-8? Could it not be just a bunch of bytes?
</blockquote></details>

It is an ASCII string surrounded by quotes, possibly prefixed with `w/`.


<!-- Sent from Reviewable.io -->

2021-02-12 11:34 UTC, pinkisemils reviewed
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2462)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @pinkisemils)

___
*[mullvad-rpc/src/lib.rs, line 366 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2462#-MTHUM6A0wOKs2Q4XZO-:-MTKof1P-Ag8auzc1JLc:b-rwy52) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c9b7e4ba740126ceb6419292f8730c009fd2d99/mullvad-rpc/src/lib.rs#L366)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nope. Reverted. `platform_version` being a `String` just looked a bit wrong to me.
</blockquote></details>

Ideally, it'd be a `&'static str` but until it can be, I think this should remain as is.


<!-- Sent from Reviewable.io -->

2021-02-12 13:58 UTC, pinkisemils approved these changes
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2462)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-15 18:19 UTC, merged