Android refactor splittunneling screen
mullvad/mullvadvpn-app pull request #2475
Opened 2021-02-15 18:00 UTC by axti

In this PR we redesign split tunnelling screen to group applications included/excluded from tunnel. 
Also, was made refactoring for usage android architecture components, it will help to keep control on background tasks, to prevent memory leak in ui and slicing into layers. Added DI based on Koin, next iteration will have more DI integrations and help to write tests easy and inject mocked instances.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-02-15 20:32 UTC, jvff requested changes
> Reviewed 7 of 67 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 7 of 67 files reviewed, 4 unresolved discussions (waiting on @axti)

___
*[android/build.gradle, line 126 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTbL0Nd8ALWUIV_EKKQ:-MTbL0Nd8ALWUIV_EKKR:brz5k3p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/022b2a014cb51e5df5cfed21b0b60c848fcc2dd3/android/build.gradle#L126)):*
> ```Gradle
>     implementation "org.koin:koin-androidx-scope:$koin_version"
>     implementation "org.koin:koin-androidx-viewmodel:$koin_version"
>     implementation "org.koin:koin-androidx-fragment:$koin_version"
> ```

Can the dependencies above be ordered in alphabetical order, so it makes them easier to find?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt, line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTbMtWi6vtpe_TwPOj9:-MTbMtWi6vtpe_TwPOjA:b2ifkl2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/022b2a014cb51e5df5cfed21b0b60c848fcc2dd3/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt#L24)):*
> ```Kotlin
>             list.addAll(packageManager.getInstalledApplications(PackageManager.GET_META_DATA))
>         }
>         Log.d("test", "fetchtime=$fetchTime")
> ```

I think these test log messages should be removed, right?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt, line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTbMxX30uV3tUs8redw:-MTbMxX30uV3tUs8redx:b-o3vk2f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/022b2a014cb51e5df5cfed21b0b60c848fcc2dd3/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt#L40)):*
> ```Kotlin
>         Log.d("test", "mapTime=$mapTime")
>         return result
> //            .sortedBy { info -> info.title }
> ```

Should we sort it here and uncomment this line, or just remove the commented line?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTbMDJJ3h1kyFzzmlxk:-MTbMDJK9NsJnnofCiLs:b-9fa5am) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/022b2a014cb51e5df5cfed21b0b60c848fcc2dd3/android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt#L22)):*
> ```Kotlin
>     single<String> (named("packagename")) { get<Context>().packageName }
> 
>     viewModel { SplitTunnelingViewModel(get(), get()) }
> ```

Nit: Is it better without the empty lines? Don't need to do it, just asking if it's better to keep them or remove them.


<!-- Sent from Reviewable.io -->

2021-02-16 08:58 UTC, axti reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 4 of 68 files reviewed, 4 unresolved discussions (waiting on @jvff)

___
*[android/build.gradle, line 126 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTbL0Nd8ALWUIV_EKKQ:-MTe2swY-UlOj3oDTLe6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/022b2a014cb51e5df5cfed21b0b60c848fcc2dd3/android/build.gradle#L126)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Can the dependencies above be ordered in alphabetical order, so it makes them easier to find?
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt, line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTbMtWi6vtpe_TwPOj9:-MTe2QmNBo3VSI4w0iH-:biasu7w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/022b2a014cb51e5df5cfed21b0b60c848fcc2dd3/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt#L24)):*
> ```
> Log.d("test"
> ```
Thanks. I forgot to delete this.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt, line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTbMxX30uV3tUs8redw:-MTe2UtdE2Wds2wqSvMv:bylrd5k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/022b2a014cb51e5df5cfed21b0b60c848fcc2dd3/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt#L40)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Should we sort it here and uncomment this line, or just remove the commented line?
</blockquote></details>

Sure. Now we sort it after grouping.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTbMDJJ3h1kyFzzmlxk:-MTe2YMU3o8zA4VvQ41G:byqi4eb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/022b2a014cb51e5df5cfed21b0b60c848fcc2dd3/android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt#L22)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Is it better without the empty lines? Don't need to do it, just asking if it's better to keep them or remove them.
</blockquote></details>

We can group them by usage or some other logical groups. I remove some lines and keep line before viewModel group, just to have some divider, maybe later on we can move to different modules.


<!-- Sent from Reviewable.io -->

2021-02-16 10:36 UTC, axti reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 4 of 68 files reviewed, 3 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt, line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTbMtWi6vtpe_TwPOj9:-MTePKS8-1qe5Op3eFqZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/022b2a014cb51e5df5cfed21b0b60c848fcc2dd3/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt#L24)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> Log.d("test"
> ```
Thanks. I forgot to delete this.
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt, line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTbMxX30uV3tUs8redw:-MTePLP47mt_D981xRNP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/022b2a014cb51e5df5cfed21b0b60c848fcc2dd3/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt#L40)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Sure. Now we sort it after grouping.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-16 12:36 UTC, jvff requested changes
> Reviewed 9 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 13 of 68 files reviewed, 1 unresolved discussion (waiting on @axti)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTbMDJJ3h1kyFzzmlxk:-MTeotlg8-T5F-qhYNll:bodb18m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/022b2a014cb51e5df5cfed21b0b60c848fcc2dd3/android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt#L22)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

We can group them by usage or some other logical groups. I remove some lines and keep line before viewModel group, just to have some divider, maybe later on we can move to different modules.
</blockquote></details>

Sounds good. We can probably play with this as more things are added and the groups become more apparent.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, line 209 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTepWz18BcdEhVSnvlC:-MTepWz23nWqo1xTDULv:bofxp1h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L209)):*
> ```Kotlin
>     @Suppress("DEPRECATION")
>     fun requestVpnPermission(intent: Intent) {
>         startActivityForResult(intent, 1)
> ```

Does the request code need to change? Or is there some convention to not use `0`?


<!-- Sent from Reviewable.io -->

2021-02-16 12:52 UTC, jvff requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 13 of 68 files reviewed, 4 unresolved discussions (waiting on @axti)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTesZZ71yBMUzao1YmS:-MTesZZ71yBMUzao1YmT:b-4mtolz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L9)):*
> ```Kotlin
> 
> class ListItemData private constructor(builder: Builder) {
> ```

Nit: Could we standardize at not having an empty line after the class declaration?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 52 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTeslQpE3t_eTCpqkgm:-MTeslQpE3t_eTCpqkgn:b-9jiw21) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L52)):*
> ```Kotlin
>     }
> 
>     override fun equals(other: Any?): Boolean {
> ```

Seems weird to have to implement `equals` and `hashCode`. Couldn't `ListItemData` be a `data class` and have `Builder.build` pass the correct parameters to the constructor?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 80 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTepwFg6hRZKI_1Q0DO:-MTepwFg6hRZKI_1Q0DP:bry7l5p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L80)):*
> ```Kotlin
>     }
> 
>     class Builder {
> ```

Could this builder just use the setters from the properties instead of having custom setters?


<!-- Sent from Reviewable.io -->

2021-02-16 12:56 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, line 209 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTepWz18BcdEhVSnvlC:-MTeuECDClEWnoz4MV55:b9r02vh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L209)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Does the request code need to change? Or is there some convention to not use `0`?
</blockquote></details>

This is something was complained before about 0. But in any case this api is deprecated, so I mark it for now, we have to change implementation with new api with callback.


<!-- Sent from Reviewable.io -->

2021-02-16 12:57 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 80 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTepwFg6hRZKI_1Q0DO:-MTeuapA3eD1vM9gBw3p:b-871fhr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L80)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Could this builder just use the setters from the properties instead of having custom setters?
</blockquote></details>

Setter from properties will not return Builder instance to use as builder pattern.


<!-- Sent from Reviewable.io -->

2021-02-16 12:59 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 52 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTeslQpE3t_eTCpqkgm:-MTeupsH3NEvqQ0yFTU5:b-wh5ex0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L52)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Seems weird to have to implement `equals` and `hashCode`. Couldn't `ListItemData` be a `data class` and have `Builder.build` pass the correct parameters to the constructor?
</blockquote></details>

We want to have custom equals method, to be able to skip some properties.


<!-- Sent from Reviewable.io -->

2021-02-16 12:59 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTesZZ71yBMUzao1YmS:-MTev3c822rlewgFqDIm:bb77uci) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L9)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Could we standardize at not having an empty line after the class declaration?
</blockquote></details>

Yep!


<!-- Sent from Reviewable.io -->

2021-02-16 13:00 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 52 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTeslQpE3t_eTCpqkgm:-MTev8S48_rKdLVR6rXE:bc6e1n6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L52)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

We want to have custom equals method, to be able to skip some properties.
</blockquote></details>

To have a lot of fields in constructor is not a good idea, that is one of builder pattern purpose. 


<!-- Sent from Reviewable.io -->

2021-02-16 16:40 UTC, jvff requested changes
> Reviewed 1 of 67 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 13 of 69 files reviewed, 3 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppInfo.kt, line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTetUGaDzuWXRL31Xmf:-MTetUGaDzuWXRL31Xmg:bma0ssz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppInfo.kt#L10)):*
> ```Kotlin
> }
> 
> data class AppInfo2(val packageName: String, val iconRes: Int, val name: String)
> ```

Could these two classes be merged into one?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 52 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTeslQpE3t_eTCpqkgm:-MTfgU3m43y-2tdbxckP:b-71xvf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L52)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

To have a lot of fields in constructor is not a good idea, that is one of builder pattern purpose. 
</blockquote></details>

I'm not sure I agree there. I agree it's bad for the user to have to call a constructor with many parameters, but if the constructor is only used internally I don't think it's bad :thinking: 

Implementing `equals` and `hashCode` to me seem a lot more complex than making it a `data class` and having an internal `var isSelected = false private set` which is only set by the constructor. What do you think?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 80 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTepwFg6hRZKI_1Q0DO:-MTffM8sDjm-HZX8GsSY:b-5ocmlo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L80)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Setter from properties will not return Builder instance to use as builder pattern.
</blockquote></details>

That's true, but you can do:

```
ListItemData.Builder().run {
    identifier = "ID"
    // ...
    build()
}
```

I also wonder if it would make sense to add that as a factory method:

```
companion object {
    fun build(setUp: Builder.() -> Unit): ListItemData = Builder().also(setUp).build()
}
```

so that building is

```
ListItemData.build {
    identifier = "ID"
    // ..
}
```

but maybe that's too complicated?


<!-- Sent from Reviewable.io -->

2021-02-16 16:41 UTC, jvff commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 52 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTeslQpE3t_eTCpqkgm:-MTfhx0bBA8ziNygHroF:b-acc2au) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L52)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I'm not sure I agree there. I agree it's bad for the user to have to call a constructor with many parameters, but if the constructor is only used internally I don't think it's bad :thinking: 

Implementing `equals` and `hashCode` to me seem a lot more complex than making it a `data class` and having an internal `var isSelected = false private set` which is only set by the constructor. What do you think?
</blockquote></details>

Wait, does `data class` require a `public` constructor? Let me check


<!-- Sent from Reviewable.io -->

2021-02-16 16:46 UTC, jvff commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 52 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTeslQpE3t_eTCpqkgm:-MTfj-hw4vCKd0sHAlRx:broikgd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L52)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Wait, does `data class` require a `public` constructor? Let me check
</blockquote></details>

No, `data class MyData private constructor(val value: Int)` works normally :+1: 


<!-- Sent from Reviewable.io -->

2021-02-16 17:04 UTC, jvff commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/BaseFragment.kt, line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTfmKTjD_pIwKsTIEY3:-MTfmKTjD_pIwKsTIEY4:b-tcuad5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/BaseFragment.kt#L12)):*
> ```Kotlin
>     constructor() : super()
>     constructor (@LayoutRes contentLayoutId: Int) : super(contentLayoutId)
>     override fun onCreateAnimation(transit: Int, enter: Boolean, nextAnim: Int): Animation? {
> ```

Could you add a new line to separate the constructors from the `onCreateAnimation` method?


<!-- Sent from Reviewable.io -->

2021-02-16 17:30 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppInfo.kt, line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTetUGaDzuWXRL31Xmf:-MTft6ei4i0Bel29uUdA:b-6ofkfn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppInfo.kt#L10)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Could these two classes be merged into one?
</blockquote></details>

Sure. I was keeping in for compatibility. 


<!-- Sent from Reviewable.io -->

2021-02-16 17:32 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 52 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTeslQpE3t_eTCpqkgm:-MTftGGG-BqH9Tybnod9:b6w84px) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L52)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

No, `data class MyData private constructor(val value: Int)` works normally :+1: 
</blockquote></details>

Let me test it, because it could produce some unexpected behaviour on the DiffUtil since we don't control _equals()_


<!-- Sent from Reviewable.io -->

2021-02-16 17:35 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 80 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTepwFg6hRZKI_1Q0DO:-MTfti_Z8BJcPV-hnKnm:b9epcdx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L80)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

That's true, but you can do:

```
ListItemData.Builder().run {
    identifier = "ID"
    // ...
    build()
}
```

I also wonder if it would make sense to add that as a factory method:

```
companion object {
    fun build(setUp: Builder.() -> Unit): ListItemData = Builder().also(setUp).build()
}
```

so that building is

```
ListItemData.build {
    identifier = "ID"
    // ..
}
```

but maybe that's too complicated?
</blockquote></details>

Will it be accessible from java? Let me check generated code.


<!-- Sent from Reviewable.io -->

2021-02-16 17:42 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/BaseFragment.kt, line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTfmKTjD_pIwKsTIEY3:-MTfuJ2mEPefSZpT7Hht:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/BaseFragment.kt#L12)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Could you add a new line to separate the constructors from the `onCreateAnimation` method?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-16 17:42 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppInfo.kt, line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTetUGaDzuWXRL31Xmf:-MTfw0L51eylfYb5zDBw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppInfo.kt#L10)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Sure. I was keeping in for compatibility. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-16 17:47 UTC, jvff requested changes
> Reviewed 9 of 67 files at r1, 8 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 27 of 71 files reviewed, 3 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt, line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTfmwWZCSVGB9izOs0l:-MTfmwWZCSVGB9izOs0m:b-lxghvw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt#L58)):*
> ```Kotlin
>             addItemDecoration(
>                 ListItemDividerDecoration(parentActivity).apply {
>                     topOffset = resources.getDimensionPixelSize(R.dimen.list_item_divider)
> ```

Why not keep `topOffset` private and use `topOffsetId` here?


<!-- Sent from Reviewable.io -->

2021-02-17 08:04 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt, line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTfmwWZCSVGB9izOs0l:-MTizqVg5Kq6zWfQchwQ:bhi025r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt#L58)):*
> ```
> ListItemDividerDecoration
> ```
In this particular place I tried to investigate why do we need to keep reference to **context** in ListItemDividerDecoration and was about to change it. I think it is redundant to have it and if you check implementation you can find that *getDimensionPixelSize* is not safe and could throw NotFoundException.


<!-- Sent from Reviewable.io -->

2021-02-17 13:30 UTC, axti reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 25 of 71 files reviewed, 3 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 80 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTepwFg6hRZKI_1Q0DO:-MTkAs-A6vAVQq81IA4l:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L80)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Will it be accessible from java? Let me check generated code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-17 17:50 UTC, jvff requested changes
> Reviewed 1 of 67 files at r1, 2 of 10 files at r3, 2 of 2 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 30 of 71 files reviewed, 7 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 98 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTjrmWv9tq5u82Viu6V:-MTjrmWv9tq5u82Viu6W:b-7eiq7y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/84d06df5ba2cccdcae55eb389e982fd454bc53cf/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L98)):*
> ```Kotlin
> 
>     companion object {
>         fun build(setUp: Builder.() -> Unit): ListItemData = Builder().also(setUp).build()
> ```

Nit: Could you place the constants first?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 28 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTl4SjQ9UwLlR5DY7JY:-MTl4SjQ9UwLlR5DY7JZ:b-mt5hvg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/84d06df5ba2cccdcae55eb389e982fd454bc53cf/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L28)):*
> ```Kotlin
> ) : ViewModel() {
>     private val _data = MutableSharedFlow<List<ListItemData>>(replay = 1)
>     val data = _data.asSharedFlow() // read-only public view
> ```

Could these two properties be called `private val listItemDataSink` and `val listItemData`?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 30 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTl4Fg64dBSUBJPyYWd:-MTl4Fg64dBSUBJPyYWe:b-wo9ezl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/84d06df5ba2cccdcae55eb389e982fd454bc53cf/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L30)):*
> ```Kotlin
>     val data = _data.asSharedFlow() // read-only public view
> 
>     private val _intentFlow = MutableSharedFlow<ViewIntent>()
> ```

I'd rather if we didn't use underscores in the names. In Rust we only use underscores to mark variables that aren't used, and on Kotlin we use the `_` to mark parameters as unused. Having `_variable` will add another convention that makes things more confusing :/
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 136 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTl5BEE1wxn57P8y7lJ:-MTl5BEE1wxn57P8y7lK:bjoghsq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/84d06df5ba2cccdcae55eb389e982fd454bc53cf/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L136)):*
> ```Kotlin
>     }
> 
>     private fun createApplicationItem(
> ```

I'm still trying to understand the code, but wouldn't it be better to replace all of these factory methods with types? Having something like:

```
sealed class ListItemData {
    abstract val identifier: String
    // ...

    data class ApplicationItemData(id: String, name: String, icon: Int, checked: Boolean) {
        override val identifier = id
        // ...
    }

    data class DividerItemData(id: Int) {
        override val identifier = "space_$id"
        // ...
    }

    // ...
}
```
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 182 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTl45-YB22RmicuEvEr:-MTl45-YB22RmicuEvEs:b-m8uz7q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/84d06df5ba2cccdcae55eb389e982fd454bc53cf/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L182)):*
> ```Kotlin
>     }
> 
>     // Represents different states for the LatestNews screen
> ```

What is `LatestNews`?


<!-- Sent from Reviewable.io -->

2021-02-17 19:50 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 30 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTl4Fg64dBSUBJPyYWd:-MTlXhsL30l3yc8eJUzk:b2nhll9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/84d06df5ba2cccdcae55eb389e982fd454bc53cf/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L30)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I'd rather if we didn't use underscores in the names. In Rust we only use underscores to mark variables that aren't used, and on Kotlin we use the `_` to mark parameters as unused. Having `_variable` will add another convention that makes things more confusing :/
</blockquote></details>

Ok.


<!-- Sent from Reviewable.io -->

2021-02-17 19:53 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 28 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTl4SjQ9UwLlR5DY7JY:-MTlYQ890-x8cY7aVoqB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/84d06df5ba2cccdcae55eb389e982fd454bc53cf/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L28)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Could these two properties be called `private val listItemDataSink` and `val listItemData`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-17 19:53 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 182 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTl45-YB22RmicuEvEr:-MTlYRypB7f_fBx27xG1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/84d06df5ba2cccdcae55eb389e982fd454bc53cf/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L182)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

What is `LatestNews`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-19 14:20 UTC, jvff requested changes
> Reviewed 1 of 67 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 29 of 71 files reviewed, 7 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/util/ViewKtx.kt, line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTl6aEW77SWcYMH_s0v:-MTl6aEW77SWcYMH_s0w:b8irkdt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/84d06df5ba2cccdcae55eb389e982fd454bc53cf/android/src/main/kotlin/net/mullvad/mullvadvpn/util/ViewKtx.kt#L13)):*
> ```Kotlin
>         this.requestLayout()
>     } else {
>         Log.w("ViewKtx", "setMargins is not supported")
> ```

I usually use the `mullvad` Log tag for all log messages so that it's easier to find in the log. Could we do that here as well?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 33 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTu_YYn1vpCOek7o_tP:-MTu_YYn1vpCOek7o_tQ:b5sv9n3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a4db885a2903820a957d2a9312bc94ee53fdf6a/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L33)):*
> ```Kotlin
> 
>     private lateinit var excludedApps: MutableMap<String, AppInfo>
>     private lateinit var allAps: MutableMap<String, AppInfo>
> ```

Typo here: `allApps`.

But also, the name isn't very clear. Shouldn't it be something like `notExcludedApps`?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 70 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTud2Zf5qWDQHTpGxeo:-MTud2Zg6SlC44a_Y1NY:b-nl5mvg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a4db885a2903820a957d2a9312bc94ee53fdf6a/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L70)):*
> ```Kotlin
> 
>     private fun removeFromExcluded(packageName: String) {
>         excludedApps.apply {
> ```

This could be simplified to be something like:

```
excludedApps.remove(packageName)?.let { appInfo ->
    allApps.add(packageName, appInfo)
    splitTunneling.includeApp(packageName)
}
``
```

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 73 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTudjcg5aT00Ju3ag_e:-MTudjcg5aT00Ju3ag_f:b-sof1rc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a4db885a2903820a957d2a9312bc94ee53fdf6a/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L73)):*
> ```Kotlin
>             get(packageName)?.let { appInfo ->
>                 allAps[packageName] = appInfo
>                 viewModelScope.launch {
> ```

Is there a need to launch a new coroutine here?fetch


<!-- Sent from Reviewable.io -->

2021-02-19 19:39 UTC, jvff requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 29 of 71 files reviewed, 11 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 63 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTupLN9ER-5VFBE1tij:-MTupLNA1_SeGlVhT4QS:bisqywk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a4db885a2903820a957d2a9312bc94ee53fdf6a/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L63)):*
> ```Kotlin
>         }
>         fetchData()
>         viewModelScope.launch(Dispatchers.Default) {
> ```

This seems a bit confusing. I don't think there's a need for spawning four coroutines. Also, isn't there a risk that `processIntent` could be called before the lists are ready?

 I'd suggest to run everything in a single coroutine, and also split things into separate methods to make it easier to understand.

```
init {
    viewModelScope.launch(Dispatchers.Default) {
        configureEmptyState()
        fetchInitialState()
        handleIntents()
    }
}

private fun configureEmptyState() {
    if (!splitTunneling.enabled) {
        // TODO: I guess this should eventually be removed, since there's no toggle anymore?
        splitTunneling.enabled = true
    }

    listItemsSink.emit(defaultListItems + createDivider(0) + createProgressItem())
}

private fun fetchInitialState() {
    appsProvider.getAppsList()...
}
```
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 95 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTvfnii4XfbArKu3fhk:-MTvfnii4XfbArKu3fhl:b-tl0xfe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a4db885a2903820a957d2a9312bc94ee53fdf6a/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L95)):*
> ```Kotlin
>     private fun fetchData() {
>         viewModelScope.launch(Dispatchers.Default) {
>             appsProvider.getAppsList().map { it.packageName to it }.toMap().let { applications ->
> ```

Maybe it's simpler to use `partition` here?

```
val excludedPackages = splitTunneling.excludedAppList

val (excludedAppsList, notExcludedAppsList) = appsProvider.getAppsList().partition { app ->
    excludedPackages.contains(app.packageName)
}

excludedApps = excludedAppsList.map { it.packageName to it }.toMutableMap()
notExcludedApps = notExcludedAppsList.map { it.packageName to it }.toMutableMap()
```
    
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 106 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTvfQeN75-0XrBp0nfN:-MTvfQeOAb7gChbmSFCO:b-1fdryc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a4db885a2903820a957d2a9312bc94ee53fdf6a/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L106)):*
> ```Kotlin
>                     .toMutableMap()
>             }
>             delay(100)
> ```

Is this delay needed?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 111 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTvgy7s95D61niypAvN:-MTvgy7t-4NJmDk-Tk4l:b-15szzy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a4db885a2903820a957d2a9312bc94ee53fdf6a/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L111)):*
> ```Kotlin
>     }
> 
>     private suspend fun publishList() {
> ```

It seems inefficient to recreate and sort the list every time something changes. Especially considering there are devices with many apps installed. It's especially worse considering that it seems to me that what we're doing is getting an intention, moving an item to a new position in the list (possibly adding headers) and then rebuilding the list to send to a differ that will just recalculate the change that we did.

To me it seems that this should just be an adapter, without all the view model complexity.


<!-- Sent from Reviewable.io -->

2021-02-22 09:29 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/util/ViewKtx.kt, line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTl6aEW77SWcYMH_s0v:-MU8360s67O8Cg08clr4:b-pfn78m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/84d06df5ba2cccdcae55eb389e982fd454bc53cf/android/src/main/kotlin/net/mullvad/mullvadvpn/util/ViewKtx.kt#L13)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I usually use the `mullvad` Log tag for all log messages so that it's easier to find in the log. Could we do that here as well?
</blockquote></details>

If you want ti find messages in the log you can filter by process id and/or package name. Tag in logs suppose to link to some class to help find the right place. If we have same tag everywhere what is a point to have it?


<!-- Sent from Reviewable.io -->

2021-02-22 09:37 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 63 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTupLN9ER-5VFBE1tij:-MU84q1A4-P6ry7I5rMu:b-sw723k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a4db885a2903820a957d2a9312bc94ee53fdf6a/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L63)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This seems a bit confusing. I don't think there's a need for spawning four coroutines. Also, isn't there a risk that `processIntent` could be called before the lists are ready?

 I'd suggest to run everything in a single coroutine, and also split things into separate methods to make it easier to understand.

```
init {
    viewModelScope.launch(Dispatchers.Default) {
        configureEmptyState()
        fetchInitialState()
        handleIntents()
    }
}

private fun configureEmptyState() {
    if (!splitTunneling.enabled) {
        // TODO: I guess this should eventually be removed, since there's no toggle anymore?
        splitTunneling.enabled = true
    }

    listItemsSink.emit(defaultListItems + createDivider(0) + createProgressItem())
}

private fun fetchInitialState() {
    appsProvider.getAppsList()...
}
```
</blockquote></details>

 if (!splitTunneling.enabled) {
        // TODO: I guess this should eventually be removed, since there's no toggle anymore?
        splitTunneling.enabled = true
    }
I agree with you, this is should be removed next time, it could be that user turned off on previous version and we should turn on on daemon. 


<!-- Sent from Reviewable.io -->

2021-02-23 00:22 UTC, jvff requested changes
> Reviewed 28 of 67 files at r1, 1 of 11 files at r2, 1 of 3 files at r6, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 59 of 71 files reviewed, 27 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAbLkjEOYZjojzApJk:-MUAbLkk3sGxoPhzPyxG:bfiyzar) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt#L13)):*
> ```Kotlin
>     override fun animateRemove(holder: RecyclerView.ViewHolder): Boolean {
>         if (holder.itemViewType == ListItemData.PROGRESS) {
>             removeDuration = 200
> ```

Is this to speed up removal of the progress view?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemDividerDecoration.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAaR18-xKzetNtU2qr:-MUAaR18-xKzetNtU2qs:b-j61nh1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemDividerDecoration.kt#L13)):*
> ```Kotlin
> class ListItemDividerDecoration(context: Context) : ItemDecoration() {
>     private var bottomOffset = 0
>     var topOffset = 0
> ```

This should stay private, otherwise an instance could be in an inconsistent state, where the `topOffset` is X, but the `topOffsetId` would have set it to Y.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemDividerDecoration.kt, line 16 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAa_nl2ON54D0YzLzO:-MUAa_nmBNR6foa-6yNi:bdu0fjk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemDividerDecoration.kt#L16)):*
> ```Kotlin
> 
>     var bottomOffsetId by observable<Int?>(null) { _, _, id ->
>         bottomOffset = if (id != null) {
> ```

Since this is being changed, could you change it to:

```
var bottomOffsetId by observable<Int?>(null) { _, _, newId ->
    bottomOffset = newId?.let { id -> context.resources.getDimensionPixelSize(id) } ?: 0
}
```
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemDividerDecoration.kt, line 24 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAb4Ef6vHHSfMNUYcu:-MUAb4Ef6vHHSfMNUYcv:b8h5l6c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemDividerDecoration.kt#L24)):*
> ```Kotlin
> 
>     var topOffsetId by observable<Int?>(null) { _, _, id ->
>         topOffset = if (id != null) {
> ```

Same as above:

```
var topOffsetId by observable<Int?>(null) { _, _, newId ->
    topOffset = newId?.let { id -> context.resources.getDimensionPixelSize(id) } ?: 0
}
```
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 28 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9vqsuAIkJz7ta53Ls:-MU9vqsuAIkJz7ta53Lt:bkqmsd2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L28)):*
> ```Kotlin
> 
>     @get:LayoutRes
>     protected abstract val layoutRes: Int
> ```

Would it make sense to make `layoutRes` and `heightRes` constructor parameters, since they're only used inside `init`?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 31 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9tDMwBOL8iMf4bZzu:-MU9tDMwBOL8iMf4bZzv:b-wsozrv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L31)):*
> ```Kotlin
> 
>     @get:DimenRes
>     protected abstract val heightRes: Int
> ```

Could this be made `Int?`, or is there a special reason to use `0` to mark it to use `WRAP_CONTENT`? It could also be `null` by default so that sub-classes don't have to specify a value if it doesn't need one different from the default.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 34 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9s8K69YoNiVb-E1MQ:-MU9s8K69YoNiVb-E1MR:b-yocvnz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L34)):*
> ```Kotlin
> 
>     init {
>         init()
> ```

Could the `init()` method's body be joined into the `init` block itself?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 40 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9so-Z9p14YJvZ5Q80:-MU9so-_5wzeUTYEqvf5:b-uluk7w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L40)):*
> ```Kotlin
>     private fun init() {
>         val view = inflater.inflate(layoutRes, this, true)
>         val height = if (heightRes > 0)
> ```

Could we add `{}` to the `if` and `else` bodies to avoid any possible mistakes in the future?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 47 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9sWi9DV3vWXi2vlYF:-MU9sWi9DV3vWXi2vlYG:bcykvmw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L47)):*
> ```Kotlin
>     }
> 
>     @CallSuper
> ```

Question: what does the `@CallSuper` annotation do? Does it require sub-classes to call the `super`'s method?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 49 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9wUV_15ZflNPDS4u7:-MU9wUV_15ZflNPDS4u8:b-6bm3kd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L49)):*
> ```Kotlin
>     @CallSuper
>     open fun update(data: ListItemData) {
>         itemData = data
> ```

Would it make sense to have a `protected abstract onUpdate()` method and have `update` be:

```
open fun update(data: ListItemData) {
    itemData = data
    onUpdate()
}
```
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAG9DF4aMJ6rWgAFqV:-MUAG9DF4aMJ6rWgAFqW:b-4c2fvo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt#L13)):*
> ```Kotlin
> sealed class WidgetViewController<T : WidgetState>(val parent: ViewGroup) {
>     @get:LayoutRes
>     protected abstract val layoutRes: Int
> ```

Nit: Would it make sense to make this a constructor parameter?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt, line 21 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAGVDe6A3jXXJyJzI3:-MUAGVDe6A3jXXJyJzI4:bglc3qz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt#L21)):*
> ```Kotlin
> 
>     abstract fun updateState(state: T)
>     abstract fun bind()
> ```

It seems `bind` is only once during initialization.  Could it be replaced by just using `in [...]

2021-02-24 07:58 UTC, axti reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 43 of 74 files reviewed, 26 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAbLkjEOYZjojzApJk:-MUI1d7k6B_fbZSLEcJT:b-6zhgyt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt#L13)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Is this to speed up removal of the progress view?
</blockquote></details>

I'm thinking to remove it, but just keep it since this timing was before, in previous design. By default it is 120ms. Should we use default?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt, line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTfmwWZCSVGB9izOs0l:-MUI1b3V87GGwll9vFiT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt#L58)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> ListItemDividerDecoration
> ```
In this particular place I tried to investigate why do we need to keep reference to **context** in ListItemDividerDecoration and was about to change it. I think it is redundant to have it and if you check implementation you can find that *getDimensionPixelSize* is not safe and could throw NotFoundException.
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemDividerDecoration.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAaR18-xKzetNtU2qr:-MUI1_HN1F0ORvd-0vBU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemDividerDecoration.kt#L13)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This should stay private, otherwise an instance could be in an inconsistent state, where the `topOffset` is X, but the `topOffsetId` would have set it to Y.
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemDividerDecoration.kt, line 16 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAa_nl2ON54D0YzLzO:-MUI1ZRJDvwl3mYlKLwY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemDividerDecoration.kt#L16)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Since this is being changed, could you change it to:

```
var bottomOffsetId by observable<Int?>(null) { _, _, newId ->
    bottomOffset = newId?.let { id -> context.resources.getDimensionPixelSize(id) } ?: 0
}
```
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemDividerDecoration.kt, line 24 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAb4Ef6vHHSfMNUYcu:-MUI1Zjr8ithb7A1deAb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemDividerDecoration.kt#L24)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Same as above:

```
var topOffsetId by observable<Int?>(null) { _, _, newId ->
    topOffset = newId?.let { id -> context.resources.getDimensionPixelSize(id) } ?: 0
}
```
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 28 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9vqsuAIkJz7ta53Ls:-MUI1WDH4IVioCQ6AwqS:bb710yj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L28)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Would it make sense to make `layoutRes` and `heightRes` constructor parameters, since they're only used inside `init`?
</blockquote></details>

Nope
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 31 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9tDMwBOL8iMf4bZzu:-MUI1VPe4xBJ7_sTNZjE:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L31)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Could this be made `Int?`, or is there a special reason to use `0` to mark it to use `WRAP_CONTENT`? It could also be `null` by default so that sub-classes don't have to specify a value if it doesn't need one different from the default.
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 40 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9so-Z9p14YJvZ5Q80:-MUI1T2j2YMnRw3Alfnx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L40)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Could we add `{}` to the `if` and `else` bodies to avoid any possible mistakes in the future?
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 47 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9sWi9DV3vWXi2vlYF:-MUI1R2oD6BTj1e08EGF:b2nhswv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L47)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Question: what does the `@CallSuper` annotation do? Does it require sub-classes to call the `super`'s method?
</blockquote></details>

Yep
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAG9DF4aMJ6rWgAFqV:-MUI09kc1yHqVscUo4HA:bb710yj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt#L13)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Would it make sense to make this a constructor parameter?
</blockquote></details>

Nope
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt, line 21 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAGVDe6A3jXXJyJzI3:-MUI06yi5R3tbt5dLrvG:bxrxq1q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt#L21)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

It seems `bind` is only once during initialization.  Could it be replaced by just using `init` in the child classes (or even better, having something `private val switch: SwitchCompat = parent.findViewById(R.id.widgetSwitch)`?)
</blockquote></details>

Good point.
Done.
___
*[android/src/main/kot [...]

2021-02-24 12:55 UTC, jvff requested changes
> Reviewed 1 of 67 files at r1, 12 of 21 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 56 of 74 files reviewed, 17 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 28 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9vqsuAIkJz7ta53Ls:-MUIuvhsDXzGV91_5Jj7:b-pszly8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L28)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Nope
</blockquote></details>

Please explain why.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 48 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUIqrqD2ywkJft3aMGJ:-MUIqrqF4KFbzdSH3wVi:b-j7go32) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e594dbeb2603d33195f79dbcddd97d9978c6aae/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L48)):*
> ```Kotlin
>             fetchData()
>         }
>         viewModelScope.launch(Dispatchers.Default) {
> ```

This coroutine doesn't have to be spawned I think. The `intentFlow.shareIn...` statement can be in the coroutine above it, right?
___
*[android/src/main/res/color/switch_thumb_border.xml, line 6 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUIsa4lDlJpGJR8LYJA:-MUIsa4lDlJpGJR8LYJB:b-r5qw7n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e594dbeb2603d33195f79dbcddd97d9978c6aae/android/src/main/res/color/switch_thumb_border.xml#L6)):*
> ```XML
>     <item android:color="@color/transparent"
>           android:state_checked="true" />
>     <item android:color="@color/transparent"/>
> ```

I think this file should be removed. It's not actually a selector (there's only one color), and it's just transparent. There's only one usage and it can use `@color/transparent` directly.
___
*[android/src/main/res/values/colors.xml, line 26 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUATHOOBeE0QaVk88Ib:-MUJ5sE38bN-VjqROEqn:bgwwdfj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/res/values/colors.xml#L26)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

This is transparent color but short version. #00000000 equals #0000
</blockquote></details>

How is it different from `@android:color/transparent`?
___
*[android/src/main/res/values/dimens.xml, line 3 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUARZ8JDcMYpwUzgZi6:-MUJ5xha9F5SaP9zR2Yq:bx9a5lc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/res/values/dimens.xml#L3)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No. I meant the other way round.


<!-- Sent from Reviewable.io -->

2021-02-24 13:27 UTC, jvff requested changes
> Reviewed 3 of 21 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 59 of 74 files reviewed, 17 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt, line 39 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUJAf7H7gg4u0NyzRi9:-MUJAf7H7gg4u0NyzRiA:b-gazoej) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e594dbeb2603d33195f79dbcddd97d9978c6aae/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt#L39)):*
> ```Kotlin
>                     ListItemData.APPLICATION -> ApplicationListItemView(parent.context)
>                     else ->
>                         throw IllegalArgumentException("View type /'$viewType/' is not supported")
> ```

Why are there slashes here?
___
*[android/src/main/res/values/integers.xml, line 3 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUATvey4loXn6bFDWiO:-MUJ9ET8BFN6zAsWQGJj:b6oekqe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/res/values/integers.xml#L3)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Fixed, using default timings.
</blockquote></details>

Why not use the same value as in the desktop?


<!-- Sent from Reviewable.io -->

2021-02-25 11:24 UTC, axti reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 55 of 76 files reviewed, 17 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 48 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUIqrqD2ywkJft3aMGJ:-MUNqoGIDgk20wSEl79_:br3ufx4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e594dbeb2603d33195f79dbcddd97d9978c6aae/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L48)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This coroutine doesn't have to be spawned I think. The `intentFlow.shareIn...` statement can be in the coroutine above it, right?
</blockquote></details>

It is needed, since we want to do in parallel, since fetchData is blocking.
___
*[android/src/main/res/values/dimens.xml, line 3 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUARZ8JDcMYpwUzgZi6:-MUNq2caDofuxnG-Phsw:bfyzqyo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/res/values/dimens.xml#L3)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

No. I meant the other way round.
</blockquote></details>

It is not make any sense, but default name of file for dimensions is dimens, somehow historically.
___
*[android/src/main/res/values/integers.xml, line 3 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUATvey4loXn6bFDWiO:-MUNpn5fBJk-k3qg0DOx:bdk00v2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/res/values/integers.xml#L3)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Why not use the same value as in the desktop?
</blockquote></details>

After speaking with Andrej and Oskar we were agreed that it is good to have default system timings.


<!-- Sent from Reviewable.io -->

2021-02-25 11:36 UTC, jvff requested changes
> Reviewed 1 of 21 files at r8, 4 of 8 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 60 of 76 files reviewed, 14 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAbLkjEOYZjojzApJk:-MUJMh81181PNmBL_DbY:bo2j64t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt#L13)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

I'm thinking to remove it, but just keep it since this timing was before, in previous design. By default it is 120ms. Should we use default?
</blockquote></details>

I think it's a nice touch to animate the removal. I don't think desktop has something similar, so in this case we can use 
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAG9DF4aMJ6rWgAFqV:-MUJMSEZ5YZNEvuvYCb8:b-pszly8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt#L13)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Nope
</blockquote></details>

Please explain why.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/util/ViewKtx.kt, line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTl6aEW77SWcYMH_s0v:-MUNx5udEu0s6gSpYwNE:b-geqb6o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/84d06df5ba2cccdcae55eb389e982fd454bc53cf/android/src/main/kotlin/net/mullvad/mullvadvpn/util/ViewKtx.kt#L13)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

If you want ti find messages in the log you can filter by process id and/or package name. Tag in logs suppose to link to some class to help find the right place. If we have same tag everywhere what is a point to have it?
</blockquote></details>

We can discuss changing it later. It doesn't make sense to make a single message have a different tag right now, while all the other situations use `mullvad` as the tag.
___
*[android/src/main/res/values/dimens.xml, line 3 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUARZ8JDcMYpwUzgZi6:-MUNy25oA2CleMDDn72v:b7ml387) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/res/values/dimens.xml#L3)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

It is not make any sense, but default name of file for dimensions is dimens, somehow historically.
</blockquote></details>

The name doesn't matter when building the APK. You only needed to add a line to the file that already existed. Not create a new file nor rename the file that already existed. If this is truly an issue, we can rename it in a separate file. The PR is already too large as is.
___
*[android/src/main/res/values/strings.xml, line 179 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAT8no3p3dN1-_1T1y:-MUJMYbU-D7r8y951sLL:b-2wnxpc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/res/values/strings.xml#L179)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

I don't have translations for now. Probably translations will be added in separate PR.
</blockquote></details>

Not a problem. Mark them as translatable.


<!-- Sent from Reviewable.io -->

2021-02-25 11:47 UTC, jvff requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 60 of 76 files reviewed, 14 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 48 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUIqrqD2ywkJft3aMGJ:-MUO-CrZ2IXxJaXZvsLN:b6v84vk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e594dbeb2603d33195f79dbcddd97d9978c6aae/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L48)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

It is needed, since we want to do in parallel, since fetchData is blocking.
</blockquote></details>

That's my point, it doesn't have to be in parallel, because it only makes sense to listen for intents after the view is set up and the data made available.


<!-- Sent from Reviewable.io -->

2021-02-25 11:49 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAG9DF4aMJ6rWgAFqV:-MUO02jpB--8kaLNL02c:b-j94mls) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt#L13)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Please explain why.
</blockquote></details>

Each widget has some specific controllers and containers that is relay on, if. you pass layout that doesn't contain specific item it will cause a crash.


<!-- Sent from Reviewable.io -->

2021-02-25 11:51 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 48 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUIqrqD2ywkJft3aMGJ:-MUO0ZBDBne-IPNZsHdB:bo63blt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e594dbeb2603d33195f79dbcddd97d9978c6aae/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L48)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

That's my point, it doesn't have to be in parallel, because it only makes sense to listen for intents after the view is set up and the data made available.
</blockquote></details>

Please look it again, I added new intent when animation is done, and removed hardcoded delay. Since we observe this intent we can't listen it when loading is finished.


<!-- Sent from Reviewable.io -->

2021-02-25 12:23 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 55 of 73 files reviewed, 13 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAG9DF4aMJ6rWgAFqV:-MUO6Oka-Yels6DD7hV0:bcxxdh9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt#L13)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Each widget has some specific controllers and containers that is relay on, if. you pass layout that doesn't contain specific item it will cause a crash.
</blockquote></details>

I don't understand. It's a sealed class that requires `layoutRes` during initialization, right? So why can't it be:

```
sealed class WidgetViewController<T : WidgetState>(parent: ViewGroup, layoutRes: Int) {
    init {
        LayoutInflater.from(parent.context).inflate(layoutRes, parent)
    }

    class StandardController(parent: ViewGroup) :
        WidgetViewController<WidgetState.ImageState>(parent, R.layout.list_item_widget_image) {
        // ...
    }

    class SwitchController(parent:ViewGroup) :
        WidgetViewController<WidgetState.ImageState>(parent, R.layout.list_item_widget_switch) {
        // ...
    }
}
```
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt, line 48 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUIqrqD2ywkJft3aMGJ:-MUO7x9e4u3zEGhhPAli:b-9cmciv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e594dbeb2603d33195f79dbcddd97d9978c6aae/android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt#L48)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Please look it again, I added new intent when animation is done, and removed hardcoded delay. Since we observe this intent we can't listen it when loading is finished.
</blockquote></details>

Ah! Now I got it, thanks!


<!-- Sent from Reviewable.io -->

2021-02-25 12:29 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt, line 39 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUJAf7H7gg4u0NyzRi9:-MUO9cjs2lra-x-dFGCW:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e594dbeb2603d33195f79dbcddd97d9978c6aae/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt#L39)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Why are there slashes here?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-02-25 12:31 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAG9DF4aMJ6rWgAFqV:-MUO9uV2EKSij08o-fpK:buho37j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt#L13)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I don't understand. It's a sealed class that requires `layoutRes` during initialization, right? So why can't it be:

```
sealed class WidgetViewController<T : WidgetState>(parent: ViewGroup, layoutRes: Int) {
    init {
        LayoutInflater.from(parent.context).inflate(layoutRes, parent)
    }

    class StandardController(parent: ViewGroup) :
        WidgetViewController<WidgetState.ImageState>(parent, R.layout.list_item_widget_image) {
        // ...
    }

    class SwitchController(parent:ViewGroup) :
        WidgetViewController<WidgetState.ImageState>(parent, R.layout.list_item_widget_switch) {
        // ...
    }
}
```
</blockquote></details>

Ok, I got it. But why we should do this? What it will change?


<!-- Sent from Reviewable.io -->

2021-02-25 12:31 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/util/ViewKtx.kt, line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTl6aEW77SWcYMH_s0v:-MUOA6lO8QdL5LAWYAPV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/84d06df5ba2cccdcae55eb389e982fd454bc53cf/android/src/main/kotlin/net/mullvad/mullvadvpn/util/ViewKtx.kt#L13)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

We can discuss changing it later. It doesn't make sense to make a single message have a different tag right now, while all the other situations use `mullvad` as the tag.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-25 12:31 UTC, axti commented
___
*[android/src/main/res/color/switch_thumb_border.xml, line 6 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUIsa4lDlJpGJR8LYJA:-MUOA8kjE1EMdV-Y0FNC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e594dbeb2603d33195f79dbcddd97d9978c6aae/android/src/main/res/color/switch_thumb_border.xml#L6)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think this file should be removed. It's not actually a selector (there's only one color), and it's just transparent. There's only one usage and it can use `@color/transparent` directly.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-25 12:33 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAbLkjEOYZjojzApJk:-MUOAMFGCn-bIxElzFNu:b-d8vau5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt#L13)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think it's a nice touch to animate the removal. I don't think desktop has something similar, so in this case we can use 
</blockquote></details>

We still have animation, but the default removal animation is a bit faster. So, maybe make things a bit simpler?


<!-- Sent from Reviewable.io -->

2021-02-25 12:43 UTC, jvff requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 55 of 73 files reviewed, 12 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAbLkjEOYZjojzApJk:-MUOCZzrDSSWi9YcXTkr:bkiat1l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt#L13)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

We still have animation, but the default removal animation is a bit faster. So, maybe make things a bit simpler?
</blockquote></details>

Ah, so you mean we can just remove this whole class and it will still animate, but a bit faster?


<!-- Sent from Reviewable.io -->

2021-02-25 12:49 UTC, jvff requested changes
> Reviewed 6 of 9 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 58 of 73 files reviewed, 8 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAG9DF4aMJ6rWgAFqV:-MUOCvL7-Po3Pzq-aIyD:b-e3ckig) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/WidgetViewController.kt#L13)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Ok, I got it. But why we should do this? What it will change?
</blockquote></details>

On a low level, I think the classes become simpler and a getter method doesn't need to be generated for them, which I believe will make them a bit smaller.

On a high level, IMHO it makes more sense to list an initialization requirement as a constructor parameter, instead of as a property.
___
*[android/src/main/res/values/strings.xml, line 177 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUODisZ1D6Bo5_JBYkg:-MUODisZ1D6Bo5_JBYkh:b4fg6kj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/53d13565977de3cf7ec01c91c380a3842da2fc72/android/src/main/res/values/strings.xml#L177)):*
> ```XML
>     <string name="add_anyway">Add anyway</string>
>     <string name="exclude_applications"
>             translatable="false">Excluded applications</string>
> ```

Need to mark this as translatable too.

The main reason is that the translated strings are generated from the desktop translation file, and the strings that are marked as `translatable="false"` are ignored, which means that they won't get translations automatically.


<!-- Sent from Reviewable.io -->

2021-02-25 12:52 UTC, axti commented
___
*[android/src/main/res/values/strings.xml, line 177 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUODisZ1D6Bo5_JBYkg:-MUOEkEJ-kja3uyEuAJP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/53d13565977de3cf7ec01c91c380a3842da2fc72/android/src/main/res/values/strings.xml#L177)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Need to mark this as translatable too.

The main reason is that the translated strings are generated from the desktop translation file, and the strings that are marked as `translatable="false"` are ignored, which means that they won't get translations automatically.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-25 12:52 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAbLkjEOYZjojzApJk:-MUOEomL-wWVOK8XFEPI:bmdjbef) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt#L13)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Ah, so you mean we can just remove this whole class and it will still animate, but a bit faster?
</blockquote></details>

Yes. Progress bar will hide in 120ms instead of 200ms.


<!-- Sent from Reviewable.io -->

2021-02-25 12:54 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 34 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9s8K69YoNiVb-E1MQ:-MUOFHOIEHuGYhkmFMj8:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L34)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Could the `init()` method's body be joined into the `init` block itself?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-25 12:55 UTC, jvff requested changes
> Reviewed 1 of 1 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 58 of 73 files reviewed, 6 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAbLkjEOYZjojzApJk:-MUOFSjoBgqPVp5dYnH3:bumho64) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt#L13)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Yes. Progress bar will hide in 120ms instead of 200ms.
</blockquote></details>

Sounds good! I think it makes sense to remove this then :+1:


<!-- Sent from Reviewable.io -->

2021-02-25 13:32 UTC, axti commented
___
*[android/src/main/res/values/colors.xml, line 26 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUATHOOBeE0QaVk88Ib:-MUONfpb2ifH938clN65:b-rl9ijd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/res/values/colors.xml#L26)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

How is it different from `@android:color/transparent`?
</blockquote></details>

no difference. But we use our color palette.


<!-- Sent from Reviewable.io -->

2021-02-25 13:33 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 49 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9wUV_15ZflNPDS4u7:-MUOO9Uk-q3Zbltpzyc1:b3zbgyq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L49)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Would it make sense to have a `protected abstract onUpdate()` method and have `update` be:

```
open fun update(data: ListItemData) {
    itemData = data
    onUpdate()
}
```
</blockquote></details>

No, because then you have to implement onUpdate on each subclass even if it is not needed.


<!-- Sent from Reviewable.io -->

2021-02-25 13:39 UTC, jvff requested changes
> Reviewed 1 of 21 files at r8, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 59 of 73 files reviewed, 6 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 49 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9wUV_15ZflNPDS4u7:-MUOPG23DfXBjwrzdV5q:b-q29nzq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L49)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

No, because then you have to implement onUpdate on each subclass even if it is not needed.
</blockquote></details>

Yes, that's true, but you can provide a default implementation: `protected open fun onUpdate() {}`


<!-- Sent from Reviewable.io -->

2021-02-25 13:41 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt, line 13 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUAbLkjEOYZjojzApJk:-MUOQ9SS9tj6vjPzWvT6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ProgressListItemAnimator.kt#L13)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Sounds good! I think it makes sense to remove this then :+1:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-25 13:43 UTC, jvff requested changes
> Reviewed 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 59 of 72 files reviewed, 5 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/res/values/colors.xml, line 26 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUATHOOBeE0QaVk88Ib:-MUOQ7aQ5cGW6pW541tw:bohnj1x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/res/values/colors.xml#L26)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

no difference. But we use our color palette.
</blockquote></details>

That doesn't make sense to me. Why create a new color that's exactly the same as the Android color?


<!-- Sent from Reviewable.io -->

2021-02-25 13:44 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 49 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9wUV_15ZflNPDS4u7:-MUOQP5y2781nYFU09MM:b5ihoen) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L49)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Yes, that's true, but you can provide a default implementation: `protected open fun onUpdate() {}`
</blockquote></details>

And what's a difference then? What would be a benefit to have one more function? Or you don't like annotations?


<!-- Sent from Reviewable.io -->

2021-02-25 13:47 UTC, jvff requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 59 of 72 files reviewed, 5 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 49 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9wUV_15ZflNPDS4u7:-MUOQtCrEaoGj0V05gzt:b-q7bixl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L49)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

And what's a difference then? What would be a benefit to have one more function? Or you don't like annotations?
</blockquote></details>

My problem is less with the annotation than having to call the super method in every sub-class, when this can be avoided by a design tweak. An override is meant to (at least IMHO) change the behavior of something, and in this case it's more of an extension, that only makes sense when listening to the event. That's why I think it's better to have a separate "callback method", it makes the purpose clearer.


<!-- Sent from Reviewable.io -->

2021-02-25 14:06 UTC, axti reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 53 of 71 files reviewed, 5 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 49 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9wUV_15ZflNPDS4u7:-MUOVjLi-swJiSXBGL9e:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L49)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

My problem is less with the annotation than having to call the super method in every sub-class, when this can be avoided by a design tweak. An override is meant to (at least IMHO) change the behavior of something, and in this case it's more of an extension, that only makes sense when listening to the event. That's why I think it's better to have a separate "callback method", it makes the purpose clearer.
</blockquote></details>

Done.
___
*[android/src/main/res/values/colors.xml, line 26 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUATHOOBeE0QaVk88Ib:-MUOViiQ5tDXD6i9wxP3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/res/values/colors.xml#L26)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

That doesn't make sense to me. Why create a new color that's exactly the same as the Android color?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-25 14:08 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 28 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9vqsuAIkJz7ta53Ls:-MUOW1p52T93M02VMCJc:b-n7essi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L28)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Please explain why.
</blockquote></details>

Maybe put them into attributes?


<!-- Sent from Reviewable.io -->

2021-02-25 14:16 UTC, jvff reviewed
> Reviewed 1 of 8 files at r9, 5 of 6 files at r15.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 59 of 71 files reviewed, 3 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 28 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9vqsuAIkJz7ta53Ls:-MUOX8L6-ZUnvBTfARAN:b-yjjcdh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L28)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Maybe put them into attributes?
</blockquote></details>

You mean XML layout attributes? Hmm, I'm not sure. It could lead to an issue where someone uses `PlainListItemView` but sets the attribute to `@layout/list_item_action`.


<!-- Sent from Reviewable.io -->

2021-02-26 10:39 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt, line 52 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MTeslQpE3t_eTCpqkgm:-MUSv-jB5xflp2rSco2x:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2828e71b3a389a14ee8cf4bdc98725ba2893ac47/android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt#L52)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Let me test it, because it could produce some unexpected behaviour on the DiffUtil since we don't control _equals()_
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-16 07:06 UTC, axti reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 24 of 79 files reviewed, 3 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt, line 28 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MU9vqsuAIkJz7ta53Ls:-MYKy9xG7MmAergB1X1f:b880dnd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ListItemView.kt#L28)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

You mean XML layout attributes? Hmm, I'm not sure. It could lead to an issue where someone uses `PlainListItemView` but sets the attribute to `@layout/list_item_action`.
</blockquote></details>

We agreed to keep it as it is.
___
*[android/src/main/res/values/dimens.xml, line 3 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUARZ8JDcMYpwUzgZi6:-MYKxzmh-UNlK0zoCZHZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4752701332509131016ec27fe621f548e84362e1/android/src/main/res/values/dimens.xml#L3)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

The name doesn't matter when building the APK. You only needed to add a line to the file that already existed. Not create a new file nor rename the file that already existed. If this is truly an issue, we can rename it in a separate file. The PR is already too large as is.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-16 14:37 UTC, jvff requested changes
> Reviewed 2 of 21 files at r8, 2 of 9 files at r10, 1 of 6 files at r15, 3 of 48 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 30 of 79 files reviewed, 5 unresolved discussions (waiting on @axti and @jvff)

___
*[android/.idea/kotlinc.xml, line 1 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQ6LPa47BLthBmr9xi:-MYQ6LPa47BLthBmr9xj:b9ldfcx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/.idea/kotlinc.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

Maybe this file shouldn't be included in the repo?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ApplicationListItemView.kt, line 30 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUOej0v9fGmlpDAANs4:-MUOej0w2YZvE1iiyPcN:b-yjct6g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/15f5649b918686689ef8f4cbb4dccbb92f22b7c9/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ApplicationListItemView.kt#L30)):*
> ```Kotlin
>     defStyleRes: Int = 0
> ) : ActionListItemView(context, attrs, defStyleAttr, defStyleRes), KoinScopeComponent {
>     override val scope: Scope = getKoin().getScope(APPS_SCOPE)
> ```

I usually order the fields/properties with `private` first, then `protected`, then `public', and separate the groups with an empty line. Inside each group, I also make `val`s go before `var`s, and separate the `val`s from `var`s with an empty line. I understand that the `scope` might be a good exception to the rule, but could we add an empty line to make it more separate and emphasized?


<!-- Sent from Reviewable.io -->

2021-04-16 14:42 UTC, jvff reviewed
> Reviewed 37 of 48 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 67 of 79 files reviewed, 2 unresolved discussions (waiting on @axti and @jvff)



<!-- Sent from Reviewable.io -->

2021-04-16 14:52 UTC, axti reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 65 of 79 files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[android/.idea/kotlinc.xml, line 1 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQ6LPa47BLthBmr9xi:-MYQ9pHD34SNjUVuoWYX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/.idea/kotlinc.xml#L1)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Maybe this file shouldn't be included in the repo?
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ApplicationListItemView.kt, line 30 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MUOej0v9fGmlpDAANs4:-MYQ9qe50lHCcFKVFFJC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/15f5649b918686689ef8f4cbb4dccbb92f22b7c9/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/listitemview/ApplicationListItemView.kt#L30)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I usually order the fields/properties with `private` first, then `protected`, then `public', and separate the groups with an empty line. Inside each group, I also make `val`s go before `var`s, and separate the `val`s from `var`s with an empty line. I understand that the `scope` might be a good exception to the rule, but could we add an empty line to make it more separate and emphasized?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-16 15:10 UTC, jvff requested changes
> Reviewed 2 of 48 files at r16, 1 of 1 files at r17, 1 of 3 files at r18.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 69 of 79 files reviewed, 7 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 40 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQAa6SEWGR4iinz_DS:-MYQAa6TBNt9TDbnya3L:bzhpm0m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L40)):*
> ```Kotlin
> 
>     private val scope: Scope = getKoin().getOrCreateScope(APPS_SCOPE, named(APPS_SCOPE)).apply {
>         getKoin().getScopeOrNull(SERVICE_CONNECTION_SCOPE)?.let { this.linkTo(it) }
> ```

Is `this` in this case the scope?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 44 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQAfsi1SKDiriTPEq3:-MYQAfsi1SKDiriTPEq4:b-tjxlkw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L44)):*
> ```Kotlin
>     private val viewModel by scope.viewModel<SplitTunnelingViewModel>(
>         owner = {
>             ViewModelOwner.from(this, this)
> ```

What is `this` in this case? Is it the delegate, some anonymous object created by the `{}` lambda, or the fragment?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 48 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQB2vQ4_5sq5tz4uGB:-MYQB2vQ4_5sq5tz4uGC:b5cqnal) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L48)):*
> ```Kotlin
>     )
>     private val toggleExcludeChannel = Channel<ListItemData>(Channel.BUFFERED)
>     private val listItemListener = object : ListItemListener {
> ```

Couldn't this property be replaced by an lambda? It could even be initialized when creating the `listItemsAdapter`:

```
class SplitTunnelingFragment : BaseFragment(R.layout.collapsed_title_layout) {
    private val toggleExcludeChannel = Channel<ListItemData>(Channel.BUFFERED)

    private val listItemsAdapter = ListItemsAdapter().apply {
        listItemListener = { item -> toggleExcludeChannel.offer(item) }
        setHasStableIds(true)
    }

    // ...
```
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 56 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQBy0UEPWZW_mS5bGR:-MYQBy0UEPWZW_mS5bGS:bw46jqj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L56)):*
> ```Kotlin
>     override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
>         super.onViewCreated(view, savedInstanceState)
>         (view.findViewById(R.id.collapsing_toolbar) as CollapsingToolbarLayout).apply {
> ```

Can't this be `view.findViewById<CollapsingToolbarLayout>(R.id.collapsing_toolbar).apply {`?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 92 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQCfEp6S5K5DtsHMrH:-MYQCfEp6S5K5DtsHMrI:b-pcmdoz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L92)):*
> ```Kotlin
>     override fun onStop() {
>         super.onStop()
>         view?.findViewById<RecyclerView>(R.id.recyclerView)?.adapter = null
> ```

Maybe store the `RecyclerView` in a property, to avoid having to search for it twice?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 114 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQCy316n6OAFASoF5F:-MYQCy316n6OAFASoF5G:b-3bjfzb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L114)):*
> ```Kotlin
>     private fun hasNavigationBar(): Boolean {
>         // Emulator
>         if (Build.FINGERPRINT.contains("generic")) {
> ```

Is this a good check? I mean, can't custom ROMs also have this in the fingerprint?


<!-- Sent from Reviewable.io -->

2021-04-16 15:15 UTC, jvff requested changes
> Reviewed 1 of 48 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 70 of 79 files reviewed, 8 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/res/values/styles.xml, line 11 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQEgeb3mz8OMhW_y0e:-MYQEgeb3mz8OMhW_y0f:bnlo3dv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b050ccbe800330c799d4af6e8947b6ed32fdf1d4/android/src/main/res/values/styles.xml#L11)):*
> ```XML
>         <item name="actionListItemViewStyle">@style/ListItem.Action</item>
>         <item name="applicationListItemViewStyle">@style/ListItem.Action.Application</item>
>         <item name="android:spotShadowAlpha">0</item>
> ```

I couldn't see where this is used. Is it used to disable something Android does by default?


<!-- Sent from Reviewable.io -->

2021-04-16 15:24 UTC, jvff requested changes
> Reviewed 4 of 67 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 74 of 79 files reviewed, 9 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/res/layout/list_item_widget_edit_text.xml, line 1 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQGv7NB_ZHhBrRGPLZ:-MYQGv7NB_ZHhBrRGPL_:br45tdv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/15f5649b918686689ef8f4cbb4dccbb92f22b7c9/android/src/main/res/layout/list_item_widget_edit_text.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> ```

This doesn't seem to be used anywhere, or did I miss something?


<!-- Sent from Reviewable.io -->

2021-04-16 15:33 UTC, axti reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 72 of 79 files reviewed, 9 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 40 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQAa6SEWGR4iinz_DS:-MYQHkL2BR5P8aAI14bT:b5an12c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L40)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Is `this` in this case the scope?
</blockquote></details>

`this` inside `apply` is an object for which we apply parameters, so it is a scope in this case.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 44 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQAfsi1SKDiriTPEq3:-MYQHWVJ-aStqYp4yzPA:b-brhon1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L44)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

What is `this` in this case? Is it the delegate, some anonymous object created by the `{}` lambda, or the fragment?
</blockquote></details>

`this` is a Fragment itself.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 48 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQB2vQ4_5sq5tz4uGB:-MYQI0F48wnNdoj_18P4:bavslb9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L48)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Couldn't this property be replaced by an lambda? It could even be initialized when creating the `listItemsAdapter`:

```
class SplitTunnelingFragment : BaseFragment(R.layout.collapsed_title_layout) {
    private val toggleExcludeChannel = Channel<ListItemData>(Channel.BUFFERED)

    private val listItemsAdapter = ListItemsAdapter().apply {
        listItemListener = { item -> toggleExcludeChannel.offer(item) }
        setHasStableIds(true)
    }

    // ...
```
</blockquote></details>

![Screenshot 2021-04-16 at 17.24.58.png](https://files.reviewableusercontent.io/images/reviewable/5171553/MYlAPhcnDKn6PT_lJnv-gmsU/Screenshot%202021-04-16%20at%2017.24.58.png)
No, it is not possible to use as a lambda.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 56 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQBy0UEPWZW_mS5bGR:-MYQIV1xCodX7AsaFg1X:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L56)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Can't this be `view.findViewById<CollapsingToolbarLayout>(R.id.collapsing_toolbar).apply {`?
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 114 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQCy316n6OAFASoF5F:-MYQFy1j2az1E5RXZIhO:b-jsf2pm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L114)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Is this a good check? I mean, can't custom ROMs also have this in the fingerprint?
</blockquote></details>

It should not. Usually emulators have it.
___
*[android/src/main/res/layout/list_item_widget_edit_text.xml, line 1 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQGv7NB_ZHhBrRGPLZ:-MYQJ3NM22HKzaE3Qu49:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/15f5649b918686689ef8f4cbb4dccbb92f22b7c9/android/src/main/res/layout/list_item_widget_edit_text.xml#L1)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This doesn't seem to be used anywhere, or did I miss something?
</blockquote></details>

Done.
___
*[android/src/main/res/values/styles.xml, line 11 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQEgeb3mz8OMhW_y0e:-MYQFm_g3Dh-VnUoA-oN:b-eychto) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b050ccbe800330c799d4af6e8947b6ed32fdf1d4/android/src/main/res/values/styles.xml#L11)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I couldn't see where this is used. Is it used to disable something Android does by default?
</blockquote></details>

Yes, this is configuring Android defaults.


<!-- Sent from Reviewable.io -->

2021-04-16 15:34 UTC, jvff requested changes
> Reviewed 1 of 67 files at r1, 2 of 3 files at r18.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 75 of 79 files reviewed, 11 unresolved discussions (waiting on @axti and @jvff)

___
*[android/.idea/.gitignore, line 11 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQH9uC-oHxaTfsLv5y:-MYQH9uC-oHxaTfsLv5z:b-mfo93a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b050ccbe800330c799d4af6e8947b6ed32fdf1d4/android/.idea/.gitignore#L11)):*
> ```ignore
> modules/android.iml
> modules.xml
> kotlinc.xml
> ```

Wouldn't it make sense to add `.idea` instead of the individual files?
___
*[android/src/main/res/layout/collapsed_title_layout.xml, line 12 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQItia3jwTXkX9eGR6:-MYQItia3jwTXkX9eGR7:b58fq5y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/res/layout/collapsed_title_layout.xml#L12)):*
> ```XML
>     <com.google.android.material.appbar.AppBarLayout android:id="@+id/appbar"
>                                                      android:layout_width="match_parent"
>                                                      android:layout_height="104dp"
> ```

Could this value become a dimension? Or do you think it won't be used anywhere else?
___
*[android/src/main/res/layout/collapsed_title_layout.xml, line 64 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQImc06W7Ea4LaR018:-MYQImc06W7Ea4LaR019:b-5u97mk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/res/layout/collapsed_title_layout.xml#L64)):*
> ```XML
>                                                tools:itemCount="15"
>                                                app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
>                                                app:layout_behavior="@string/appbar_scrolling_view_behavior" />
> ```

This string doesn't seem to be defined?


<!-- Sent from Reviewable.io -->

2021-04-16 15:38 UTC, axti commented
___
*[android/src/main/res/layout/collapsed_title_layout.xml, line 64 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQImc06W7Ea4LaR018:-MYQKNzP1Qi18kByOvhk:b-t6k80t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/res/layout/collapsed_title_layout.xml#L64)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This string doesn't seem to be defined?
</blockquote></details>

This string from Android.


<!-- Sent from Reviewable.io -->

2021-04-16 15:44 UTC, jvff requested changes
> Reviewed 1 of 2 files at r19, 1 of 4 files at r20.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 74 of 79 files reviewed, 6 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 40 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQAa6SEWGR4iinz_DS:-MYQJTQU9OmVen4sTSTV:bhdyaot) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L40)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

`this` inside `apply` is an object for which we apply parameters, so it is a scope in this case.
</blockquote></details>

Ah, so this links the `APPS_SCOPE` to the `SERVICE_CONNECTION_SCOPE`? Now I understand, thanks!

Would it make sense to replace these lines with:

```
private val scope = getKoin().getOrCreateScope(APPS_SCOPE, named(APPS_SCOPE)).also { appsScope ->
    getKoin().getScopeOrNull(SERVICE_CONNECTION_SCOPE)?.let { serviceConnectionScope ->
        appsScope.linkTo(serviceConnectionScope)
    }
}
```
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 44 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQAfsi1SKDiriTPEq3:-MYQKYzx9nkDoiXeqP_P:botlh9b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L44)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

`this` is a Fragment itself.
</blockquote></details>

Ah, got it :ok_hand: 
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 48 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQB2vQ4_5sq5tz4uGB:-MYQLTTd3wZUdUevywSN:bot177v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L48)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

![Screenshot 2021-04-16 at 17.24.58.png](https://files.reviewableusercontent.io/images/reviewable/5171553/MYlAPhcnDKn6PT_lJnv-gmsU/Screenshot%202021-04-16%20at%2017.24.58.png)
No, it is not possible to use as a lambda.
</blockquote></details>

Okay :( 


<!-- Sent from Reviewable.io -->

2021-04-16 15:45 UTC, jvff reviewed
> Reviewed 1 of 2 files at r19, 1 of 4 files at r20.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 76 of 79 files reviewed, 3 unresolved discussions (waiting on @axti and @jvff)



<!-- Sent from Reviewable.io -->

2021-04-16 15:46 UTC, jvff reviewed
> Reviewed 1 of 4 files at r20.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 77 of 79 files reviewed, 2 unresolved discussions (waiting on @axti)



<!-- Sent from Reviewable.io -->

2021-04-16 15:52 UTC, axti reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 76 of 79 files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[android/.idea/.gitignore, line 11 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQH9uC-oHxaTfsLv5y:-MYQL_hAEwlb4q6vkDJi:bk2x48b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b050ccbe800330c799d4af6e8947b6ed32fdf1d4/android/.idea/.gitignore#L11)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Wouldn't it make sense to add `.idea` instead of the individual files?
</blockquote></details>

Not really, because I think it is good to share already configured code styles. It will save time and provide same code styles for other developers.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 40 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQAa6SEWGR4iinz_DS:-MYQNYwc3NHdEg1yh2D7:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L40)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Ah, so this links the `APPS_SCOPE` to the `SERVICE_CONNECTION_SCOPE`? Now I understand, thanks!

Would it make sense to replace these lines with:

```
private val scope = getKoin().getOrCreateScope(APPS_SCOPE, named(APPS_SCOPE)).also { appsScope ->
    getKoin().getScopeOrNull(SERVICE_CONNECTION_SCOPE)?.let { serviceConnectionScope ->
        appsScope.linkTo(serviceConnectionScope)
    }
}
```
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt, line 92 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQCfEp6S5K5DtsHMrH:-MYQNaO_79oeESXE3eIh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragment.kt#L92)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Maybe store the `RecyclerView` in a property, to avoid having to search for it twice?
</blockquote></details>

Done.
___
*[android/src/main/res/layout/collapsed_title_layout.xml, line 12 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQItia3jwTXkX9eGR6:-MYQNcNe1MTK8n8IY_rg:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd33dd3b2b20c060048269f7075d55a8cb855cdd/android/src/main/res/layout/collapsed_title_layout.xml#L12)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Could this value become a dimension? Or do you think it won't be used anywhere else?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-16 15:55 UTC, jvff requested changes
> Reviewed 2 of 48 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 78 of 79 files reviewed, 5 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/androidTest/kotlin/net/mullvad/mullvadvpn/RecyclerViewMatcher.kt, line 13 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQMAYJ-HYMQyUGw5Op:-MYQMAYJ-HYMQyUGw5Oq:brvigga) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8cdf1d3ac94bf48951ff55c2ac34709c80c6496/android/src/androidTest/kotlin/net/mullvad/mullvadvpn/RecyclerViewMatcher.kt#L13)):*
> ```Kotlin
> class RecyclerViewMatcher(private val recyclerViewId: Int) {
>     fun atPosition(position: Int): Matcher<View> {
>         return atPositionOnView(position, -1)
> ```

Could this use `null` instead of `-1`, so that the `targetViewId` below becomes `Int?`?
___
*[android/src/androidTest/kotlin/net/mullvad/mullvadvpn/RecyclerViewMatcher.kt, line 41 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQMqER7Xepo_VroV-B:-MYQMqER7Xepo_VroV-C:b-804gft) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8cdf1d3ac94bf48951ff55c2ac34709c80c6496/android/src/androidTest/kotlin/net/mullvad/mullvadvpn/RecyclerViewMatcher.kt#L41)):*
> ```Kotlin
>                     } else {
>                         return false
>                     }
> ```

Could these lines be:

```
val recyclerView =
    view.rootView.findViewById<View>(recyclerViewId) as RecyclerView?

if (recyclerView == null || recyclerView.id != recyclerViewId) {
    return false
}

childView = recyclerView.findViewHolderForAdapterPosition(position)?.itemView
```
___
*[android/src/androidTest/kotlin/net/mullvad/mullvadvpn/RecyclerViewMatcher.kt, line 48 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQN8o10iSsoEsttdeH:-MYQN8o10iSsoEsttdeI:bsg5pxl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8cdf1d3ac94bf48951ff55c2ac34709c80c6496/android/src/androidTest/kotlin/net/mullvad/mullvadvpn/RecyclerViewMatcher.kt#L48)):*
> ```Kotlin
>                     val targetView = childView?.findViewById<View>(targetViewId)
>                     view == targetView
>                 }
> ```

With a `null` `targetViewId` this could become:

```
val targetView = targetViewId?.let { id ->
    childView?.findViewById<View>(id)
} ?: childView

return view == targetView
```


<!-- Sent from Reviewable.io -->

2021-04-16 15:56 UTC, jvff reviewed
> Reviewed 1 of 1 files at r21.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: all files reviewed, 3 unresolved discussions (waiting on @axti)



<!-- Sent from Reviewable.io -->

2021-04-19 09:01 UTC, axti reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475)* status: 78 of 79 files reviewed, 3 unresolved discussions (waiting on @jvff)

___
*[android/src/androidTest/kotlin/net/mullvad/mullvadvpn/RecyclerViewMatcher.kt, line 13 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQMAYJ-HYMQyUGw5Op:-MYdLy2b9CzSeMfsbotW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8cdf1d3ac94bf48951ff55c2ac34709c80c6496/android/src/androidTest/kotlin/net/mullvad/mullvadvpn/RecyclerViewMatcher.kt#L13)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Could this use `null` instead of `-1`, so that the `targetViewId` below becomes `Int?`?
</blockquote></details>

Done.
___
*[android/src/androidTest/kotlin/net/mullvad/mullvadvpn/RecyclerViewMatcher.kt, line 41 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQMqER7Xepo_VroV-B:-MYdMFFl5tppPDmVIibb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8cdf1d3ac94bf48951ff55c2ac34709c80c6496/android/src/androidTest/kotlin/net/mullvad/mullvadvpn/RecyclerViewMatcher.kt#L41)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Could these lines be:

```
val recyclerView =
    view.rootView.findViewById<View>(recyclerViewId) as RecyclerView?

if (recyclerView == null || recyclerView.id != recyclerViewId) {
    return false
}

childView = recyclerView.findViewHolderForAdapterPosition(position)?.itemView
```
</blockquote></details>

Done.
___
*[android/src/androidTest/kotlin/net/mullvad/mullvadvpn/RecyclerViewMatcher.kt, line 48 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-MYQN8o10iSsoEsttdeH:-MYdMFlYAvSnF2iIf9S2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8cdf1d3ac94bf48951ff55c2ac34709c80c6496/android/src/androidTest/kotlin/net/mullvad/mullvadvpn/RecyclerViewMatcher.kt#L48)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

With a `null` `targetViewId` this could become:

```
val targetView = targetViewId?.let { id ->
    childView?.findViewById<View>(id)
} ?: childView

return view == targetView
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-19 12:06 UTC, jvff approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r22.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2475#-:-MYe0Xu69eXRp5uj5C7N:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-19 13:05 UTC, merged