Do not fail if Wintun adapter is assigned a different alias
mullvad/mullvadvpn-app pull request #2476
Opened 2021-02-15 18:14 UTC by dlon

Currently, if a non-Wintun device has an alias that conflicts with ours, starting the tunnel fails with `ERROR_ALREADY_EXISTS`. These changes make sure that whatever alias is assigned to the adapter is used instead.

2021-02-15 20:21 UTC, mvd-ows approved these changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476)* status: all files reviewed, 5 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/tunnel/wireguard/wireguard_go.rs, line 154 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476#-MTbH5qW1VxPqJmeJ0Xl:-MTbH5qW1VxPqJmeJ0Xm:bbuy8wn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a0e8065125054ec1220eb44c81334b7219439c1/talpid-core/src/tunnel/wireguard/wireguard_go.rs#L154)):*
> ```Rust
>         }
> 
>         if alias_ptr.is_null() {
> ```

If this is required data, shouldn't `wgTurnOn` fail if it cannot provide the data?
___
*[wireguard/libwg/libwg_windows.go, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476#-MTb7ZTQBWshHwgv4D6p:-MTb7ZTQBWshHwgv4D6q:b-z4zxy4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a0e8065125054ec1220eb44c81334b7219439c1/wireguard/libwg/libwg_windows.go#L4)):*
> ```Go
>  *
>  * Copyright (C) 2017-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
>  * Copyright (C) 2020 Mullvad VPN AB. All Rights Reserved.
> ```

Might as well update the copyright year.
___
*[wireguard/libwg/libwg_windows.go, line 71 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476#-MTbE1TO8szClpk5Aq68:-MTbE1TO8szClpk5Aq69:brqc5dg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a0e8065125054ec1220eb44c81334b7219439c1/wireguard/libwg/libwg_windows.go#L71)):*
> ```Go
> func wgTurnOn(cIfaceName *C.char, mtu int, waitOnIpv6 bool, cSettings *C.char, cIfaceNameOut **C.char, logSink LogSink, logContext LogContext) int32 {
> 	logger := logging.NewLogger(logSink, logContext)
> 	*cIfaceNameOut = nil
> ```

Maybe verify the pointer first to avoid NULL pointer deref.
___
*[wireguard/libwg/libwg_windows.go, line 111 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476#-MTb8WOmDC0bd8mH1-AJ:-MTb8WOmDC0bd8mH1-AK:b-q8a8hi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a0e8065125054ec1220eb44c81334b7219439c1/wireguard/libwg/libwg_windows.go#L111)):*
> ```Go
> 	actualInterfaceName, err := nativeTun.Name()
> 	if err != nil {
> 		logger.Debug.Println("Failed to determine name of wintun adapter")
> ```

This doesn't seem right. You assume the correct alias was assigned if you can't verify.

I would prefer if this continued to be a failure case.

And if a successful return value from this function would *always* assign `cIfaceNameOut`.
___
*[wireguard/libwg/libwg_windows.go, line 118 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476#-MTb8wi992Ue6nM_ljn7:-MTb8wiA7l0v5lRii8OR:b-ijfs9s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a0e8065125054ec1220eb44c81334b7219439c1/wireguard/libwg/libwg_windows.go#L118)):*
> ```Go
> 			logger.Debug.Println("Failed to create adapter with specific name")
> 		}
> 		if cIfaceNameOut != nil {
> ```

This is a mandatory argument, you already made a default assignment in the prologue.


<!-- Sent from Reviewable.io -->

2021-02-15 22:18 UTC, pinkisemils approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476)* status: all files reviewed, 5 unresolved discussions (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-02-16 09:58 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476)* status: 3 of 11 files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[wireguard/libwg/libwg_windows.go, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476#-MTb7ZTQBWshHwgv4D6p:-MTeGgCs0xhjmsptvs_f:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a0e8065125054ec1220eb44c81334b7219439c1/wireguard/libwg/libwg_windows.go#L4)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Might as well update the copyright year.
</blockquote></details>

Done.
___
*[wireguard/libwg/libwg_windows.go, line 71 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476#-MTbE1TO8szClpk5Aq68:-MTeGh3s5Ns06I6wd8Bu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a0e8065125054ec1220eb44c81334b7219439c1/wireguard/libwg/libwg_windows.go#L71)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Maybe verify the pointer first to avoid NULL pointer deref.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-16 11:34 UTC, pinkisemils requested changes
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 440 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476#-MTbnHD711xl8rO_0uWd:-MTbnHD711xl8rO_0uWe:bccyn2s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a0e8065125054ec1220eb44c81334b7219439c1/talpid-core/src/tunnel/openvpn/mod.rs#L440)):*
> ```XML
>             params,
>             user_pass_file.as_ref(),
>             match proxy_auth_file {
> ```

Maybe this could be a single line with `proxy_auth_file.map(AsRef::as_ref)` or similar.
___
*[talpid-core/src/tunnel/openvpn/windows.rs, line 175 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476#-MTbo3Fe02Pst5muUkrC:-MTbo3FfAtStRPD9ExJt:bhz0j2q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a0e8065125054ec1220eb44c81334b7219439c1/talpid-core/src/tunnel/openvpn/windows.rs#L175)):*
> ```XML
>         }
> 
>         Ok(WintunDll {
> ```

I wonder if we should have a test for these unwraps. On the other hand, it's probably impossible to get a bug here pass through actual testing.
___
*[talpid-core/src/tunnel/openvpn/windows.rs, line 202 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476#-MTboFBy7_w6eRKzBPdP:-MTboFBy7_w6eRKzBPdQ:bssuz6l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a0e8065125054ec1220eb44c81334b7219439c1/talpid-core/src/tunnel/openvpn/windows.rs#L202)):*
> ```XML
>             },
>             func_get_adapter_name: unsafe {
>                 std::mem::transmute(Self::get_proc_address(
> ```

I believe the `mem::transmute` call can be replaced by casting the void pointer via `&* addr as *const _ as *const _`. 


<!-- Sent from Reviewable.io -->

2021-02-16 18:29 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @mvd-ows and @pinkisemils)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 440 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476#-MTbnHD711xl8rO_0uWd:-MTg4IKg52C0gD7Sghat:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a0e8065125054ec1220eb44c81334b7219439c1/talpid-core/src/tunnel/openvpn/mod.rs#L440)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Maybe this could be a single line with `proxy_auth_file.map(AsRef::as_ref)` or similar.
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel/openvpn/windows.rs, line 175 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476#-MTbo3Fe02Pst5muUkrC:-MTfxxjT7pXSjkzFCEOP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a0e8065125054ec1220eb44c81334b7219439c1/talpid-core/src/tunnel/openvpn/windows.rs#L175)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I wonder if we should have a test for these unwraps. On the other hand, it's probably impossible to get a bug here pass through actual testing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-17 08:17 UTC, mvd-ows reviewed
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @mvd-ows and @pinkisemils)

___
*[wireguard/libwg/libwg_windows.go, line 71 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476#-MTbE1TO8szClpk5Aq68:-MTj2qf1DSdZlV1eMvgz:bhzl6sw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a0e8065125054ec1220eb44c81334b7219439c1/wireguard/libwg/libwg_windows.go#L71)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If this is indeed a mandatory argument, which it seems to be, shouldn't the logic be be more similar to the logic below?


<!-- Sent from Reviewable.io -->

2021-02-17 09:23 UTC, pinkisemils approved these changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-17 11:49 UTC, pinkisemils approved these changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-17 11:51 UTC, mvd-ows approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-17 12:01 UTC, merged