Split `SettingsListener` in server side and UI side classes
mullvad/mullvadvpn-app pull request #2496
Opened 2021-02-21 02:26 UTC by jvff

This PR continues the work to run the service in a separate process by splitting the `SettingsListener` class in two, one for the UI side process and one for the service side process. They communicate through the IPC channel that was configured in a [previous PR](#2463). For now, only sending events from the service side to the UI side is implemented, using a new `Event.SettingsUpdate` message. Changing individual settings by sending requests from the UI to the service will be implemented in one or more future PRs.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header. **Internal refactor, no user visible changes.**
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-02-21 02:31 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496)* status: 0 of 25 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU1PgcV59Xm_hK2_E7r:-MU1PgcWDQxMT0PxwGKQ:begdkzo) (no related file):*
Some refactoring of how the `EventListener` for the settings is also included. It is very likely that this will be changed in the future so that it uses [Kotlin Flows] (likely an Android [`StateFlow`]). I'm not sure if it's best to do that now, or to get the split process PRs merged first and then to change this.

[Kotlin Flows]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/
[`StateFlow`]: https://developer.android.com/kotlin/flow/stateflow-and-sharedflow

---


<!-- Sent from Reviewable.io -->

2021-02-22 07:04 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7YK543kdB9sQEukDn:-MU7YK543kdB9sQEukDo:bk7mbw3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt#L17)):*
> ```
> class SettingsUpdate(val settings: Settings?) : Event(), Parcelable
> ```
Should it be data class maybe? What do you think?


<!-- Sent from Reviewable.io -->

2021-02-22 07:06 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7YK543kdB9sQEukDn:-MU7YpZU1-QsbmIXn4Hc:b-a4j6hj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt#L17)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> class SettingsUpdate(val settings: Settings?) : Event(), Parcelable
> ```
Should it be data class maybe? What do you think?
</blockquote></details>

Can settings be nullable?


<!-- Sent from Reviewable.io -->

2021-02-22 07:10 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt, line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7ZeG1CVI7cXuMZ7bx:-MU7ZeG1CVI7cXuMZ7by:b-1djfp1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt#L8)):*
> ```
> var countryCode: String
> ```
Should it be **val**?


<!-- Sent from Reviewable.io -->

2021-02-22 07:10 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt, line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7ZrCf-oAIxYkrHQLj:-MU7ZrCf-oAIxYkrHQLk:by3cxj2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt#L16)):*
> ```
> var countryCode: String, var cityCode: String, var hostname: String
> ```
Should it be **val**?


<!-- Sent from Reviewable.io -->

2021-02-22 07:10 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt, line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7ZnZqCDgqEtQYksNu:-MU7ZnZqCDgqEtQYksNv:bpsnq7b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt#L12)):*
> ```
> var countryCode: String, var cityCode: String
> ```
Should it be **val**?


<!-- Sent from Reviewable.io -->

2021-02-22 07:12 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelaySettings.kt, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7_Hqm9hHsm4YUBrJU:-MU7_Hqm9hHsm4YUBrJV:b-ylsz47) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelaySettings.kt#L11)):*
> ```
> var relayConstraints: RelayConstraints
> ```
Should it be **val**?


<!-- Sent from Reviewable.io -->

2021-02-22 07:14 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/Settings.kt, line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7_iDz5Z1nW4ERzYrT:-MU7_iE--_krxsFXFTXT:b98mj8k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/model/Settings.kt#L12)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     var accountToken: String?,
>     var relaySettings: RelaySettings,
>     var allowLan: Boolean,
>     var autoConnect: Boolean,
>     var tunnelOptions: TunnelOptions,
>     var showBetaReleases: Boolean
> ```
</details>

Should it be **val**?


<!-- Sent from Reviewable.io -->

2021-02-22 07:20 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/CustomDns.kt, line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7augm-H2Qr-sWfxkP:-MU7augm-H2Qr-sWfxkQ:b-eqh6k0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/service/CustomDns.kt#L27)):*
> ```
> dnsServers = ArrayList(dnsOptions.addresses)
> ```
What is a reason to create a new list?


<!-- Sent from Reviewable.io -->

2021-02-22 07:35 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7eIX-2G0NIxcWI__n:-MU7eIX-2G0NIxcWI__o:b-x7vos4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L10)):*
> ```
> private val daemon = endpoint.intermittentDaemon
> ```
Can we avoid to interact it directly? What the reason to have ServiceEndpoint in constructor if we using IntermittenDaemon directly?


<!-- Sent from Reviewable.io -->

2021-02-22 07:37 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7eskJEHAXkePgYjs0:-MU7eskJEHAXkePgYjs1:bg9g80b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L22)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>             maybeNewDaemon?.let { newDaemon ->
>                 newDaemon.onSettingsChange.subscribe(this@SettingsListener) { maybeSettings ->
>                     synchronized(this@SettingsListener) {
>                         maybeSettings?.let { newSettings -> handleNewSettings(newSettings) }
>                     }
>                 }
> ```
</details>

Try to make it simpler and improve readebility.


<!-- Sent from Reviewable.io -->

2021-02-22 08:39 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 77 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7szJGCNWgxrdSE8j7:-MU7szJGCNWgxrdSE8j8:behrxkz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L77)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
>         synchronized(this) {
>             if (settings?.accountToken != newSettings.accountToken) {
>                 accountNumberNotifier.notify(newSettings.accountToken)
>             }
>             if (settings?.tunnelOptions?.dnsOptions != newSettings.tunnelOptions.dnsOptions) {
>                 dnsOptionsNotifier.notify(newSettings.tunnelOptions.dnsOptions)
>             }
>             if (settings?.relaySettings != newSettings.relaySettings) {
>                 relaySettingsNotifier.notify(newSettings.relaySettings)
>             }
>             settings = newSettings
>         }
> ```
</details>

Why do we need synchronised here?


<!-- Sent from Reviewable.io -->

2021-02-22 08:41 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/PreferencesFragment.kt, line 63 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7tWjl6h0YChNR1US5:-MU7tWjl6h0YChNR1US6:b1af6kl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/PreferencesFragment.kt#L63)):*
> ```
> updateUi
> ```
Please make a constant


<!-- Sent from Reviewable.io -->

2021-02-22 08:46 UTC, axti reviewed
> Reviewed 24 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496)* status: 24 of 25 files reviewed, 12 unresolved discussions (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-02-22 18:08 UTC, pinkisemils approved these changes
> Reviewed 12 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496)* status: all files reviewed, 12 unresolved discussions (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-02-24 18:12 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496)* status: 19 of 25 files reviewed, 12 unresolved discussions (waiting on @axti and @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7YK543kdB9sQEukDn:-MUK3lqp7iYwhmKrzNh5:btfrqym) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt#L17)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Can settings be nullable?
</blockquote></details>

Done, regarding `data class.

As for nullable settings, unfortunately, the daemon can return `null` in certain scenarios :( I think there might be a way to avoid this, but I need to try out a few things. I think it's best to leave this for a separate PR since it can end up touching other parts of the code.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt, line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7ZeG1CVI7cXuMZ7bx:-MUJbiasAYBLZ3QBmWk9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt#L8)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> var countryCode: String
> ```
Should it be **val**?
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt, line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7ZnZqCDgqEtQYksNu:-MUJbkFBCDWvWIm2OmYc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt#L12)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> var countryCode: String, var cityCode: String
> ```
Should it be **val**?
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt, line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7ZrCf-oAIxYkrHQLj:-MUJbksi3OTlYx_dLFHI:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt#L16)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> var countryCode: String, var cityCode: String, var hostname: String
> ```
Should it be **val**?
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelaySettings.kt, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7_Hqm9hHsm4YUBrJU:-MUJf2kW852QwkF-nule:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelaySettings.kt#L11)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> var relayConstraints: RelayConstraints
> ```
Should it be **val**?
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/Settings.kt, line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7_iDz5Z1nW4ERzYrT:-MUJf3MvCOGWEdzLMKZ3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/model/Settings.kt#L12)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>     var accountToken: String?,
>     var relaySettings: RelaySettings,
>     var allowLan: Boolean,
>     var autoConnect: Boolean,
>     var tunnelOptions: TunnelOptions,
>     var showBetaReleases: Boolean
> ```
Should it be **val**?
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/CustomDns.kt, line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7augm-H2Qr-sWfxkP:-MUJhJSd05G6DEHX5IAX:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/service/CustomDns.kt#L27)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> dnsServers = ArrayList(dnsOptions.addresses)
> ```
What is a reason to create a new list?
</blockquote></details>

Fixed.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7eIX-2G0NIxcWI__n:-MUJf7SI8uYdhY4v8om8:b1wvr38) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L10)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> private val daemon = endpoint.intermittentDaemon
> ```
Can we avoid to interact it directly? What the reason to have ServiceEndpoint in constructor if we using IntermittenDaemon directly?
</blockquote></details>

This is implemented using something similar to the dependency injection pattern. The `endpoint` is the injector from where the `SettingsListener` class (and other classes in the `.service.endpoint` package) can obtain their dependencies.

Another reason is to ensure consistency, so that all classes in the `.service.endpoint` package have similar constructor parameters.

I wonder if we could use `koin` here, but that's probably something we should discuss and experiment in a separate PR.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7eskJEHAXkePgYjs0:-MUK1Jrb0NHAIjCBstmq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L22)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>             maybeNewDaemon?.let { newDaemon ->
>                 newDaemon.onSettingsChange.subscribe(this@SettingsListener) { maybeSettings ->
>                     synchronized(this@SettingsListener) {
>                         maybeSettings?.let { newSettings -> handleNewSettings(newSettings) }
>                     }
>                 }
> ```
Try to make it simpler and improve readebility.
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 77 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7szJGCNWgxrdSE8j7:-MUK0AAB17e3lpOSfKTP:bkgy3l3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L77)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>         synchronized(this) {
>             if (settings?.accountToken != newSettings.accountToken) {
>                 accountNumberNotifier.notify(newSettings.accountToken)
>             }
>             if (settings?.tunnelOptions?.dnsOptions != newSettings.tunnelOptions.dnsOptions) {
>                 dnsOptionsNotifier.notify(newSettings.tunnelOptions.dnsOptions)
>             }
>             if (settings?.relaySettings != newSettings.relaySettings) {
>                 relaySettingsNotifier.notify(newSettings.relaySettings)
>             }
>             settings = newSettings
>         }
> ```
Why do we need synchronised here?
</blockquote></details>

This is needed because we don't want to have a race condition wri [...]

2021-03-04 07:33 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7eskJEHAXkePgYjs0:-MUw8v1xC3-6VBK_Zhuu:bb6wk0y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L22)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Good


<!-- Sent from Reviewable.io -->

2021-03-04 07:38 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 71 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MUw928bA_dO5gsIVT94:-MUw928bA_dO5gsIVT95:b-d0eeun) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35e2ce470348ec80fae49c2a9d358f3aedd7c1ff/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L71)):*
<details><summary><i alt="summary">Quoted 16 lines of code…</i></summary>

> ```
>     private fun registerListener(daemon: MullvadDaemon) {
>         daemon.onSettingsChange.subscribe(this) { maybeSettings ->
>             synchronized(this) {
>                 maybeSettings?.let { newSettings -> handleNewSettings(newSettings) }
>             }
>         }
>     }
>     private fun fetchInitialSettings(daemon: MullvadDaemon) {
>         synchronized(this) {
>             daemon.getSettings()?.let { newSettings ->
>                 handleNewSettings(newSettings)
>             }
>         }
>     }
>     private fun handleNewSettings(newSettings: Settings) {
>         synchronized(this) {
> ```
</details>

Could we make it like this:
```
    private fun registerListener(daemon: MullvadDaemon) {
        daemon.onSettingsChange.subscribe(this, ::handleNewSettings)
    }
    private fun fetchInitialSettings(daemon: MullvadDaemon) {
        handleNewSettings(daemon.getSettings())
    }
    private fun handleNewSettings(newSettings: Settings?) {
         if(newSettings == null) {
             return
         }
     .....
    }
```
What do you think?


<!-- Sent from Reviewable.io -->

2021-03-04 07:43 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 77 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7szJGCNWgxrdSE8j7:-MUwAHXp5utw8DvCaNeT:b-7jx0q6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L77)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

This is needed because we don't want to have a race condition writing to `settings`. First we register the listener, and the listener's callback is executed in a separate thread (except for the first event), and that can happen at the same time as we're loading the initial settings. So we synchronize to make sure either one or the other gets written.

More specifically, the race condition is if we call `getSettings`, get a value `A`, and before we update `settings` to have `A` the listener callback is executed in a separate thread with a value `B`, which sets `settings` first. So the order becomes `B` -> `A` instead of `A` -> `B`.
</blockquote></details>

To prevent this maybe we can fetch initial setting onSubscribe? But this is another question.
My question was written because you already have `synchronized` block inside callback and `fetchInitialSettings`, feels unnecessary. Also, do we need to lock `SettingsListener` object? Will it be enough to lock just `settings` object?


<!-- Sent from Reviewable.io -->

2021-03-04 07:56 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SettingsListener.kt, line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MUwE-hP1PO_0QwrrWA1:-MUwE-hP1PO_0QwrrWA2:b90wu96) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35e2ce470348ec80fae49c2a9d358f3aedd7c1ff/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SettingsListener.kt#L21)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         eventDispatcher.registerHandler(Event.SettingsUpdate::class) { event ->
>             event.settings?.let { newSettings ->
>                 handleNewSettings(newSettings)
>             }
>         }
> ```
</details>

Will it be nicer to have something like this:
`eventDispatcher.registerHandler(Event.SettingsUpdate::class, ::handleNewSettingsEvent)`
`private fun handleNewSettingsEvent(settingsUpdate: Event.SettingsUpdate) =
        handleNewSettings(settingsUpdate.settings)`


<!-- Sent from Reviewable.io -->

2021-03-04 07:57 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SettingsListener.kt, line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MUwEE2O-lhSNV2yEtV3:-MUwEE2O-lhSNV2yEtV4:b1pbq8n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35e2ce470348ec80fae49c2a9d358f3aedd7c1ff/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SettingsListener.kt#L33)):*
> ```
> private fun handleNewSettings(newSettings: Settings) {
> ```
And we can add simple change:

```
   private fun handleNewSettings(newSettings: Settings?) {
        if (newSettings == null)
            return
       ....
   }
```


<!-- Sent from Reviewable.io -->

2021-03-04 11:29 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496)* status: 15 of 25 files reviewed, 15 unresolved discussions (waiting on @axti and @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 77 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MU7szJGCNWgxrdSE8j7:-MUwm6QE0mqsaqnzWZVB:bnx6zm5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81af5ccb4ea911d6dd796fa16191f8a2c581a925/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L77)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

To prevent this maybe we can fetch initial setting onSubscribe? But this is another question.
My question was written because you already have `synchronized` block inside callback and `fetchInitialSettings`, feels unnecessary. Also, do we need to lock `SettingsListener` object? Will it be enough to lock just `settings` object?

</blockquote></details>

Yeah, the initial fetch can be reworked (maybe the logic can be moved into `MullvadDaemon`?), but we can look at that in a separate PR.

We could look it using one of the fields, but I think it's simpler to just use the lock on `this` because what needs to be synchronized is also all the notifiers in the class.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt, line 71 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MUw928bA_dO5gsIVT94:-MUwvhN60LQ7EwJTY0Y0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35e2ce470348ec80fae49c2a9d358f3aedd7c1ff/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt#L71)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>     private fun registerListener(daemon: MullvadDaemon) {
>         daemon.onSettingsChange.subscribe(this) { maybeSettings ->
>             synchronized(this) {
>                 maybeSettings?.let { newSettings -> handleNewSettings(newSettings) }
>             }
>         }
>     }
>     private fun fetchInitialSettings(daemon: MullvadDaemon) {
>         synchronized(this) {
>             daemon.getSettings()?.let { newSettings ->
>                 handleNewSettings(newSettings)
>             }
>         }
>     }
>     private fun handleNewSettings(newSettings: Settings) {
>         synchronized(this) {
> ```
Could we make it like this:
```
    private fun registerListener(daemon: MullvadDaemon) {
        daemon.onSettingsChange.subscribe(this, ::handleNewSettings)
    }
    private fun fetchInitialSettings(daemon: MullvadDaemon) {
        handleNewSettings(daemon.getSettings())
    }
    private fun handleNewSettings(newSettings: Settings?) {
         if(newSettings == null) {
             return
         }
     .....
    }
```
What do you think?
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SettingsListener.kt, line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MUwE-hP1PO_0QwrrWA1:-MUwviEq0oDDgiJB1ECR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35e2ce470348ec80fae49c2a9d358f3aedd7c1ff/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SettingsListener.kt#L21)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>         eventDispatcher.registerHandler(Event.SettingsUpdate::class) { event ->
>             event.settings?.let { newSettings ->
>                 handleNewSettings(newSettings)
>             }
>         }
> ```
Will it be nicer to have something like this:
`eventDispatcher.registerHandler(Event.SettingsUpdate::class, ::handleNewSettingsEvent)`
`private fun handleNewSettingsEvent(settingsUpdate: Event.SettingsUpdate) =
        handleNewSettings(settingsUpdate.settings)`
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SettingsListener.kt, line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MUwEE2O-lhSNV2yEtV3:-MUwvU-SCWo_pXI_x4_7:b2o6i5g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35e2ce470348ec80fae49c2a9d358f3aedd7c1ff/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SettingsListener.kt#L33)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> private fun handleNewSettings(newSettings: Settings) {
> ```
And we can add simple change:

```
   private fun handleNewSettings(newSettings: Settings?) {
        if (newSettings == null)
            return
       ....
   }
```
</blockquote></details>

I added the `null` check to the `handleNewEvent` method, because we can then keep the indentation level here as is, which makes it easier to read.


<!-- Sent from Reviewable.io -->

2021-03-04 11:52 UTC, axti approved these changes
> Reviewed 5 of 6 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2021-03-04 12:30 UTC, axti approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-:-MUxCqXV4oeUNo0QHPXs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2021-03-04 12:47 UTC, pinkisemils approved these changes
> Reviewed 3 of 25 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2021-03-23 09:44 UTC, axti requested changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt, line 119 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MWTSWmg7ewIo45yLLLb:-MWTSWmg7ewIo45yLLLc:bwd8ras) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/08105220d91ecf66f51b51c951370d708604cac0/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt#L119)):*
> ```
> isAllowLanEnabled = maybeSettings?.allowLan ?: false
> ```
Should it be inside `configureHeader`?


<!-- Sent from Reviewable.io -->

2021-03-23 11:22 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496)* status: all files reviewed, 2 unresolved discussions (waiting on @axti)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt, line 119 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-MWTSWmg7ewIo45yLLLb:-MWTnjf08tuU9YP0tDSE:b8refp5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/08105220d91ecf66f51b51c951370d708604cac0/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt#L119)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> isAllowLanEnabled = maybeSettings?.allowLan ?: false
> ```
Should it be inside `configureHeader`?
</blockquote></details>

Unfortunately, the settings listener calls `updateUi` on every settings change. and`updateUi` requires `wireguardMtuInput` to be initialized. It's only initialized in `configureHeader` :/

I thought it was easier to just add the `isAllowLanEnabled` to the existing listener than to create a new listener. But I think this will likely change in the future, so I think we can improve it in a separate PR.


<!-- Sent from Reviewable.io -->

2021-03-23 12:33 UTC, axti approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496#-:-MWU3kmr3VyGlTkSThRH:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-23 13:41 UTC, merged