Watch DNS config changes in systemd-resolved
mullvad/mullvadvpn-app pull request #2501
Opened 2021-02-22 20:13 UTC by pinkisemils

Certain NM versions will overwrite systemd-resovled config when they're
reapplying existing config, this can be invoked 
`nmcli general reload dns-full`  or by receiving a new DHCP lease. NM will 
just wipe the config for interfaces it doesn't have the config for in
systemd-resolved, and since our daemon prefers systemd-resolved over NM, 
our config would be wiped. To fix this, I've changed the systemd-resolved DNS
code to listen to changes to the global DNS config and reapply the tunnel interface 
DNS config if it's changed in any way.

To better seperate the conecrns, the systemd-resolved DBus specific code
was moved to the `talpid-dbus` crate, and the DNS code that manages the
state and applies changes remains in `talpid-core`.

One other solution that was considered was to just prefer NM over
systemd-resolved, and we already kind of could do that, but the coming
NM versions (1.28 and up) seem to not be able to manage DNS via it's own
`/etc/resolv.conf`.

2021-02-23 15:04 UTC, dlon requested changes
> Reviewed 8 of 8 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2501)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/dns/linux/systemd_resolved.rs, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2501#-MUEEhEGBV_Fj5GY3bZl:-MUEEhEGBV_Fj5GY3bZm:btwyabu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0955621b7fd206895a2f0d26cc3ec3d643d4103/talpid-core/src/dns/linux/systemd_resolved.rs#L70)):*
> ```XML
>                                 .collect();
>                             current_servers.sort();
>                             if current_servers != *dns_state_ref.set_servers {
> ```

Is the latter list guaranteed to be sorted?
___
*[talpid-dbus/src/network_manager.rs, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2501#-MUDqhth3XzbVZB1RkH6:-MUDqhth3XzbVZB1RkH7:b-807afv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0955621b7fd206895a2f0d26cc3ec3d643d4103/talpid-dbus/src/network_manager.rs#L70)):*
> ```XML
>     MatchDBusTypeError(#[error(source)] dbus::arg::TypeMismatchError),
> 
>     #[error(display = "NM is configured to manage DNS via systemd-resolved but systemd-resolved is not manaing /etc/resolv.conf: {}", _0)]
> ```

Typo.
___
*[talpid-dbus/src/systemd_resolved.rs, line 308 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2501#-MUEM6X2AvUVCHgzcghE:-MUEM6X32Mr-anDQyczY:bczvl24) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c08b928874f61809678514a792c3ee111ee52c4/talpid-dbus/src/systemd_resolved.rs#L308)):*
> ```XML
>             .add_match(
>                 match_rule,
>                 move |mut prop_changed: PropertiesPropertiesChanged, _connection, _message| {
> ```

Instead of removing the match explicitly, it should be possible to return `should_continue()` here. But it doesn't matter.
___
*[talpid-dbus/src/systemd_resolved.rs, line 317 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2501#-MUEOkR70FOgaPCmUibx:-MUEOkR70FOgaPCmUiby:bqxzuch) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c08b928874f61809678514a792c3ee111ee52c4/talpid-dbus/src/systemd_resolved.rs#L317)):*
> ```XML
>                     {
>                         match DnsServer::server_list_from_refarg(dns_change) {
>                             Some(new_server_list) => callback(new_server_list),
> ```

Why do we care about the result from `callback`? If it returns false, this match rule is removed, but the loop continues, which seems kind of weird.


<!-- Sent from Reviewable.io -->

2021-03-01 11:40 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2501)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/dns/linux/systemd_resolved.rs, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2501#-MUEEhEGBV_Fj5GY3bZl:-MUhVh4k727C4qVWxjdf:b1r7g7e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0955621b7fd206895a2f0d26cc3ec3d643d4103/talpid-core/src/dns/linux/systemd_resolved.rs#L70)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is the latter list guaranteed to be sorted?
</blockquote></details>

Good catch, it is now.
___
*[talpid-dbus/src/systemd_resolved.rs, line 317 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2501#-MUEOkR70FOgaPCmUibx:-MUExeYvCJrXDrwmIJaO:b2dryn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8c08b928874f61809678514a792c3ee111ee52c4/talpid-dbus/src/systemd_resolved.rs#L317)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Why do we care about the result from `callback`? If it returns false, this match rule is removed, but the loop continues, which seems kind of weird.
</blockquote></details>

Yeah, the return value here is completely useless. I think just relying on `should_continue` and always removing the match manually is good enough.

Although  I am wondering if as part of the DBus connection, there should just be a thread that pumps the messages, so we could actually just rely on the match being removed by it's return value and not have this stupid dance.


<!-- Sent from Reviewable.io -->

2021-03-02 08:49 UTC, dlon approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2501)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/dns/linux/systemd_resolved.rs, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2501#-MUEEhEGBV_Fj5GY3bZl:-MUi4NBF3Nsi3m4SV_IU:b-sbz8mi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0955621b7fd206895a2f0d26cc3ec3d643d4103/talpid-core/src/dns/linux/systemd_resolved.rs#L70)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Good catch, it is now.
</blockquote></details>

I don't see any changes


<!-- Sent from Reviewable.io -->

2021-03-02 10:29 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2501)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/dns/linux/systemd_resolved.rs, line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2501#-MUEEhEGBV_Fj5GY3bZl:-MUmTxEs8wg7Fln2HFeG:b-vmy83q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0955621b7fd206895a2f0d26cc3ec3d643d4103/talpid-core/src/dns/linux/systemd_resolved.rs#L70)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I don't see any changes
</blockquote></details>

Gah, I hadn't pushed all the changes. `DnsState.set_servers` is now sorted in `SystemdResolved::set_dns`. 


<!-- Sent from Reviewable.io -->

2021-03-02 10:35 UTC, dlon approved these changes
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2501)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-02 11:46 UTC, merged