Add rules to allow relay traffic through reverse path filtering on Linux.
mullvad/mullvadvpn-app pull request #2535
Opened 2021-03-04 16:18 UTC by pinkisemils

When the daemon runs on a system that attempts to do strict reverse path filtering, incoming relay traffic would be filtered out, leaving the user without a working connection, because the daemon would never receive the tunnel traffic, leaving it in a reconnection loop. This is because on Linux, we use policy based routing, and an incoming TCP or UDP packet does not have the necessary context at the filtering stage to determine if a response to said packet would be routed through the same interface. To fix this, I've added a new chain to our main table that will apply the correct firewall mark to the relay traffic so that it would still work.

2021-03-04 16:21 UTC, pinkisemils commented
This is one probable fix for #2457.

2021-03-05 09:23 UTC, dlon requested changes
Split tunneling also doesn't work with strict rpf, but we'll leave that for a later time.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-:-MV0erqd4oeYiivQ1A8U:b-3dqjst)* status: all files reviewed, 3 unresolved discussions (waiting on @pinkisemils)

___
*[CHANGELOG.md, line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-MV0g7ySEcyv5mqTgO_p:-MV0g7ySEcyv5mqTgO_q:b-443az3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4e6a29cc8f4a91bc72c8ca6e1ce4c3ef28534b/CHANGELOG.md#L65)):*
> ```Markdown
> #### Linux
> - Fix DNS issues where NM would overwrite Mullvad tunnel's DNS config in systemd-resolved.
> - Fix inability to connect when user has set reverse-path filtering.
> ```

It works fine with the loose setting (2), which is the default. So I'd add "strict" here.
___
*[talpid-core/src/firewall/linux.rs, line 226 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-MV0gYycBjjFgs4H_JBF:-MV0gYycBjjFgs4H_JBG:b-eky2xi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4e6a29cc8f4a91bc72c8ca6e1ce4c3ef28534b/talpid-core/src/firewall/linux.rs#L226)):*
> ```XML
>     pub fn new(tables: &'a FirewallTables) -> Self {
>         let mut batch = Batch::new();
>         let mut allow_tunnel_chain = Chain::new(&*ALLOW_TUNNEL_TRAFFIC_CHAIN_NAME, &tables.main);
> ```

We have the separate `ip` and `ip6` tables to work around some issue with older kernels (I forget the details). I wonder if we could move everything to `inet mullvad` at this point.
___
*[talpid-core/src/firewall/linux.rs, line 603 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-MV0e9OLDmFaaNSk0WXP:-MV0e9OLDmFaaNSk0WXQ:b-pm7err) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4e6a29cc8f4a91bc72c8ca6e1ce4c3ef28534b/talpid-core/src/firewall/linux.rs#L603)):*
> ```XML
> 
>     fn add_allow_tunnel_endpoint_rules(&mut self, endpoint: &Endpoint, use_fwmark: bool) {
>         let mut in_pre_chain = Rule::new(&self.allow_tunnel_chain);
> ```

The rule could be conditional on `use_fwmark == true`.
___
*[talpid-core/src/firewall/linux.rs, line 605 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-MV0fR8A0pF7pG8n8DVe:-MV0fR8A0pF7pG8n8DVf:b-5c72sv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4e6a29cc8f4a91bc72c8ca6e1ce4c3ef28534b/talpid-core/src/firewall/linux.rs#L605)):*
> ```XML
>         let mut in_pre_chain = Rule::new(&self.allow_tunnel_chain);
>         check_endpoint(&mut in_pre_chain, End::Src, endpoint);
>         in_pre_chain.add_expr(&nft_expr!(immediate data crate::linux::TUNNEL_FW_MARK));
> ```

The rpf kind of ignores the fwmark if `/proc/sys/net/ipv4/conf/all/src_valid_mark` is not set to 1, so we should probably do that.
___
*[talpid-core/src/firewall/linux.rs, line 608 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-MV0eZhFCRidKXxgd6wZ:-MV0eZhFCRidKXxgd6w_:buo4san) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4e6a29cc8f4a91bc72c8ca6e1ce4c3ef28534b/talpid-core/src/firewall/linux.rs#L608)):*
> ```XML
>         in_pre_chain.add_expr(&nft_expr!(meta mark set));
> 
>         self.batch.add(&in_pre_chain, nftnl::MsgType::Add);
> ```

`in_pre_chain` is not a great name, as this is a rule.


<!-- Sent from Reviewable.io -->

2021-03-05 09:41 UTC, faern approved these changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/firewall/linux.rs, line 226 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-MV0gYycBjjFgs4H_JBF:-MV0gnqI7fAUuGDO8sM-:ba5dps6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4e6a29cc8f4a91bc72c8ca6e1ce4c3ef28534b/talpid-core/src/firewall/linux.rs#L226)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We have the separate `ip` and `ip6` tables to work around some issue with older kernels (I forget the details). I wonder if we could move everything to `inet mullvad` at this point.
</blockquote></details>

Let's find out which kernel version is needed for better `inet` support. If we can drop the separate v4/v6 tables that would be great.
___
*[talpid-core/src/firewall/linux.rs, line 605 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-MV0fR8A0pF7pG8n8DVe:-MV0kRD93wShts8seYM-:b-2k8ag1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4e6a29cc8f4a91bc72c8ca6e1ce4c3ef28534b/talpid-core/src/firewall/linux.rs#L605)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The rpf kind of ignores the fwmark if `/proc/sys/net/ipv4/conf/all/src_valid_mark` is not set to 1, so we should probably do that.
</blockquote></details>

We should be very careful about changing anything under `/proc`. We'll need to discuss that.
___
*[talpid-core/src/firewall/linux.rs, line 608 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-MV0eZhFCRidKXxgd6wZ:-MV0kcLV5ZgMIf8JmGte:bsucf02) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4e6a29cc8f4a91bc72c8ca6e1ce4c3ef28534b/talpid-core/src/firewall/linux.rs#L608)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`in_pre_chain` is not a great name, as this is a rule.
</blockquote></details>

I agree. If following the other naming in this method it would be `prerouting_rule`.


<!-- Sent from Reviewable.io -->

2021-03-05 11:27 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @faern)

___
*[CHANGELOG.md, line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-MV0g7ySEcyv5mqTgO_p:-MV16JH42ZFgZK2fjmzW:b-4k3d1u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4e6a29cc8f4a91bc72c8ca6e1ce4c3ef28534b/CHANGELOG.md#L65)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It works fine with the loose setting (2), which is the default. So I'd add "strict" here.
</blockquote></details>

There's many ways to do RFP, and some firewalls do it.
___
*[talpid-core/src/firewall/linux.rs, line 226 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-MV0gYycBjjFgs4H_JBF:-MV16fOP3t0SAOLM_dBJ:b5yytdv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4e6a29cc8f4a91bc72c8ca6e1ce4c3ef28534b/talpid-core/src/firewall/linux.rs#L226)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Let's find out which kernel version is needed for better `inet` support. If we can drop the separate v4/v6 tables that would be great.
</blockquote></details>

A plain old `nft add table inet test` works just fine on kernel 4.9 on Debian 9. But this would be out of scope for this PR.
___
*[talpid-core/src/firewall/linux.rs, line 603 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-MV0e9OLDmFaaNSk0WXP:-MV17By20iUPvAk44U8O:b3c8s9e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4e6a29cc8f4a91bc72c8ca6e1ce4c3ef28534b/talpid-core/src/firewall/linux.rs#L603)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The rule could be conditional on `use_fwmark == true`.
</blockquote></details>

I think it's still required to get OpenVPN to work. The routing rules stay the same for both, right?


<!-- Sent from Reviewable.io -->

2021-03-05 11:28 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @faern)

___
*[CHANGELOG.md, line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-MV0g7ySEcyv5mqTgO_p:-MV18HUA2sOh7uwPmo6m:b-pnyivm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4e6a29cc8f4a91bc72c8ca6e1ce4c3ef28534b/CHANGELOG.md#L65)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

There's many ways to do RFP, and some firewalls do it.
</blockquote></details>

I've changed it to elaborate for now. 


<!-- Sent from Reviewable.io -->

2021-03-05 11:38 UTC, dlon approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[CHANGELOG.md, line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-MV0g7ySEcyv5mqTgO_p:-MV19ZWg3-PvrxCwXORg:b-7vo826) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4e6a29cc8f4a91bc72c8ca6e1ce4c3ef28534b/CHANGELOG.md#L65)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I've changed it to elaborate for now. 
</blockquote></details>

Ah, I see.
___
*[talpid-core/src/firewall/linux.rs, line 603 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-MV0e9OLDmFaaNSk0WXP:-MV19trTBlE2yLm7eRC_:b-6aycl2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4e6a29cc8f4a91bc72c8ca6e1ce4c3ef28534b/talpid-core/src/firewall/linux.rs#L603)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think it's still required to get OpenVPN to work. The routing rules stay the same for both, right?
</blockquote></details>

Well, `use_fwmark` could/should be set to true when using Shadowsocks or OpenVPN as well.


<!-- Sent from Reviewable.io -->

2021-03-05 13:21 UTC, faern approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/firewall/linux.rs, line 226 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2535#-MV0gYycBjjFgs4H_JBF:-MV1H8iSB8BQ0v19XKTy:b-gcm2yb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d4e6a29cc8f4a91bc72c8ca6e1ce4c3ef28534b/talpid-core/src/firewall/linux.rs#L226)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

A plain old `nft add table inet test` works just fine on kernel 4.9 on Debian 9. But this would be out of scope for this PR.
</blockquote></details>

Adding the tables have been allowed for many versions. It's what kind of rules/expressions you are allowed to put into the chains in them that has increased I think. but if this new rule works in the `inet` scope it's fine.

I agree that changing **other** chains is out of scope for this PR.


<!-- Sent from Reviewable.io -->

2021-03-05 14:24 UTC, merged