Support WireGuard over TCP for custom relays
mullvad/mullvadvpn-app pull request #2537
Opened 2021-03-05 11:51 UTC by dlon

This adds support for reaching WireGuard relays over TCP via [udp-over-tcp](https://github.com/mullvad/udp-over-tcp). Currently, this can only be configured for custom relays (that are running `Tcp2Udp`).

Usage:
```
mullvad relay set custom wireguard <IP> <PORT> tcp <PEER PUBLIC KEY> <GATEWAY> --addr <TUNNEL IP>
```

2021-03-05 13:22 UTC, faern requested changes
I don't think we should merge this while at this PoC stage. First of all it does not really work against any of our servers yet. Secondly it brings in a lot of extra Rust dependencies that no one will have any use for yet

We should evaluate if this can sit in a feature branch until later, or if we should migrate `udp-over-tcp` to tokio 0.2 and keep it like that until we can upgrade the entire app.

> Reviewed 6 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-:-MV1JFv88GzQI9Nk4Kpe:bevc4oc)* status: 6 of 14 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[mullvad-cli/src/cmds/relay.rs, line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MV1Lpzs4gkUP9VqYT-T:-MV1Lpzs4gkUP9VqYT-U:buxdmvf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/173e05c2ad6ca945d831dcaa0f847bbabcef8c2e/mullvad-cli/src/cmds/relay.rs#L62)):*
> ```XML
>                                         .default_value("udp")
>                                         .possible_values(&["udp", "tcp"])
>                                         .required(false),
> ```

Doesn't `default_value` imply `required(false)`?
___
*[mullvad-cli/src/cmds/relay.rs, line 358 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MV1MUghBxgLLy-Gf7tL:-MV1MUghBxgLLy-Gf7tM:b-fxa74p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/173e05c2ad6ca945d831dcaa0f847bbabcef8c2e/mullvad-cli/src/cmds/relay.rs#L358)):*
> ```XML
>             "tcp" => TransportProtocol::Tcp,
>             _ => clap::Error::with_description(
>                 "unknown transport protocol",
> ```

Nit. I know this is just copied. But "invalid transport protocol" is probably better than *unknown*. Because we know all possible values, so any other string is not unknown to us, it's wrong.
___
*[mullvad-daemon/src/management_interface.rs, line 1533 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MV1NSQj3tv8cIf9jmw8:-MV1NSQj3tv8cIf9jmw9:bvd1e6y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/173e05c2ad6ca945d831dcaa0f847bbabcef8c2e/mullvad-daemon/src/management_interface.rs#L1533)):*
> ```XML
>     match types::TransportProtocol::from_i32(protocol) {
>         Some(types::TransportProtocol::Udp) => Ok(TransportProtocol::Udp),
>         Some(types::TransportProtocol::Tcp) => Ok(TransportProtocol::Tcp),
> ```

Maybe not in this PR. But it would be more idiomatic, and maybe slightly easier to read if we had:
```rust
impl From<types::TransportProtocol> for TransportProtocol> {}
impl From<TransportProtocol> for types::TransportProtocol> {}
```


<!-- Sent from Reviewable.io -->

2021-03-05 13:22 UTC, faern reviewed
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537)* status: 7 of 14 files reviewed, 3 unresolved discussions (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-03-05 15:54 UTC, faern requested changes
> Reviewed 3 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537)* status: 10 of 14 files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/relays.rs, line 683 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MV1ZjvK-8CtjYMvkKSq:-MV1ZjvK-8CtjYMvkKSr:bu6x3o5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/173e05c2ad6ca945d831dcaa0f847bbabcef8c2e/mullvad-daemon/src/relays.rs#L683)):*
> ```XML
>             allowed_ips: all_of_the_internet(),
>             // TODO: Add Udp2Tcp support
>             protocol: TransportProtocol::Udp,
> ```

Not really a todo *yet*, as that part is not in scope. I think we can remove the comment for now. It will be obvious that this needs changing when we extend the TCP support to our normal relay selector I think?


<!-- Sent from Reviewable.io -->

2021-03-11 09:53 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537)* status: 10 of 14 files reviewed, 5 unresolved discussions (waiting on @dlon)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MVVgmfp56GsZjSDIgnc:-MVVgmfqCAk3EBNUGwS-:b-5i2zmi) (no related file):*
Old settings must be migrated or read correctly.

---


<!-- Sent from Reviewable.io -->

2021-03-31 11:15 UTC, faern requested changes
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537)* status: 9 of 14 files reviewed, 6 unresolved discussions (waiting on @dlon and @faern)

___
*[talpid-core/src/tunnel_state_machine/connected_state.rs, line 117 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MX6zS2iCRGti5aAwFlb:-MX6zS2iCRGti5aAwFlc:b-f8ni6z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/46b1ba2cba87f5327eb4a72ab07ac765f8e60f89/talpid-core/src/tunnel_state_machine/connected_state.rs#L117)):*
> ```XML
>             ),
>             #[cfg(target_os = "linux")]
>             use_fwmark: self.tunnel_parameters.supports_fwmark(),
> ```

Does this change now maybe with the merging of #2627? If so. Maybe rebase this PR and adapt what's needed.


<!-- Sent from Reviewable.io -->

2021-03-31 13:07 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537)* status: 3 of 13 files reviewed, 5 unresolved discussions (waiting on @dlon and @faern)

___
*[mullvad-cli/src/cmds/relay.rs, line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MV1Lpzs4gkUP9VqYT-T:-MX7MGoV-wuvkej6lEwQ:b-mhv9ll) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/173e05c2ad6ca945d831dcaa0f847bbabcef8c2e/mullvad-cli/src/cmds/relay.rs#L62)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Doesn't `default_value` imply `required(false)`?
</blockquote></details>

True. Actually, all of these arguments except except `v6_gateway` are really *required*. I'm not sure why `required(false)` was used. So now I've changed the above to `required(true)` (if it's omitted or `false`, clap panics).
___
*[mullvad-cli/src/cmds/relay.rs, line 358 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MV1MUghBxgLLy-Gf7tL:-MX7NnkvB6YEcm2J7NAQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/173e05c2ad6ca945d831dcaa0f847bbabcef8c2e/mullvad-cli/src/cmds/relay.rs#L358)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nit. I know this is just copied. But "invalid transport protocol" is probably better than *unknown*. Because we know all possible values, so any other string is not unknown to us, it's wrong.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/relays.rs, line 683 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MV1ZjvK-8CtjYMvkKSq:-MX78ctz3Adgd2WC6w0a:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/173e05c2ad6ca945d831dcaa0f847bbabcef8c2e/mullvad-daemon/src/relays.rs#L683)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Not really a todo *yet*, as that part is not in scope. I think we can remove the comment for now. It will be obvious that this needs changing when we extend the TCP support to our normal relay selector I think?
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel_state_machine/connected_state.rs, line 117 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MX6zS2iCRGti5aAwFlb:-MX78eEm1rjfaph0Y4WD:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/46b1ba2cba87f5327eb4a72ab07ac765f8e60f89/talpid-core/src/tunnel_state_machine/connected_state.rs#L117)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Does this change now maybe with the merging of #2627? If so. Maybe rebase this PR and adapt what's needed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-31 15:03 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537)* status: 3 of 13 files reviewed, 7 unresolved discussions (waiting on @dlon and @faern)

___
*[mullvad-cli/src/cmds/relay.rs, line 59 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MX7bViz5nhhbPueEQWs:-MX7bVj-E_soVm239neA:b72v4km) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1f5c05870deb1dd583fcaa5632a07f1b52dad2/mullvad-cli/src/cmds/relay.rs#L59)):*
> ```XML
>                                         .default_value("udp")
>                                         .possible_values(&["udp", "tcp"])
>                                         .required(true),
> ```

If it has a default it does not make sense to be required. Maybe this should not be a positional argument but rather have a long option? `.long("protocol")`?
___
*[mullvad-cli/src/cmds/relay.rs, line 62 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MX7bIz95I3p3BcRKZLU:-MX7bIzA7SioNKAS2diT:b-baylej) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1f5c05870deb1dd583fcaa5632a07f1b52dad2/mullvad-cli/src/cmds/relay.rs#L62)):*
> ```XML
>                                 )
>                                 .arg(
>                                     clap::Arg::with_name("peer-key")
> ```

Can we name this arg `peer-pubkey` to make it clear it's a pubkey please?
___
*[mullvad-cli/src/cmds/relay.rs, line 71 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MX7brccCLCee-YDZl7a:-MX7brccCLCee-YDZl7b:b-ciehsm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1f5c05870deb1dd583fcaa5632a07f1b52dad2/mullvad-cli/src/cmds/relay.rs#L71)):*
> ```XML
>                                         .help("Local address of wireguard tunnel")
>                                         .long("addr")
>                                         .required(true)
> ```

Feels like we could be more consistent here. Why does this have a long option and is not a positional argument if it's required? Can we work out some standard for when something is a positional argument and when it has a long/short option?


<!-- Sent from Reviewable.io -->

2021-03-31 15:14 UTC, faern reviewed
> Reviewed 8 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537)* status: 10 of 13 files reviewed, 4 unresolved discussions (waiting on @dlon and @faern)



<!-- Sent from Reviewable.io -->

2021-04-06 10:38 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[mullvad-cli/src/cmds/relay.rs, line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MV1Lpzs4gkUP9VqYT-T:-MXakiHM0faSBmBF3K0P:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/173e05c2ad6ca945d831dcaa0f847bbabcef8c2e/mullvad-cli/src/cmds/relay.rs#L62)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

True. Actually, all of these arguments except except `v6_gateway` are really *required*. I'm not sure why `required(false)` was used. So now I've changed the above to `required(true)` (if it's omitted or `false`, clap panics).
</blockquote></details>

Done.
___
*[mullvad-cli/src/cmds/relay.rs, line 59 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MX7bViz5nhhbPueEQWs:-MXakgt1EBiXdRj5MFTa:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1f5c05870deb1dd583fcaa5632a07f1b52dad2/mullvad-cli/src/cmds/relay.rs#L59)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

If it has a default it does not make sense to be required. Maybe this should not be a positional argument but rather have a long option? `.long("protocol")`?
</blockquote></details>

Done.
___
*[mullvad-cli/src/cmds/relay.rs, line 62 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MX7bIz95I3p3BcRKZLU:-MXak8A_EQHdJDdQT9s9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1f5c05870deb1dd583fcaa5632a07f1b52dad2/mullvad-cli/src/cmds/relay.rs#L62)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we name this arg `peer-pubkey` to make it clear it's a pubkey please?
</blockquote></details>

Done.
___
*[mullvad-cli/src/cmds/relay.rs, line 71 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MX7brccCLCee-YDZl7a:-MXakBeN0vYBpE-29R_Z:bb82w1n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1f5c05870deb1dd583fcaa5632a07f1b52dad2/mullvad-cli/src/cmds/relay.rs#L71)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Feels like we could be more consistent here. Why does this have a long option and is not a positional argument if it's required? Can we work out some standard for when something is a positional argument and when it has a long/short option?
</blockquote></details>

Now positional arguments are used for required arguments. Long/short is used for optional arguments and options with default values.


<!-- Sent from Reviewable.io -->

2021-04-07 08:21 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @dlon and @faern)

___
*[mullvad-cli/src/cmds/relay.rs, line 71 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MX7brccCLCee-YDZl7a:-MXfFTBwB01fj-8zu2Rh:b-1jitep) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1f5c05870deb1dd583fcaa5632a07f1b52dad2/mullvad-cli/src/cmds/relay.rs#L71)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Now positional arguments are used for required arguments. Long/short is used for optional arguments and options with default values.
</blockquote></details>

:+1: Awesome!
___
*[mullvad-cli/src/cmds/relay.rs, line 72 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MXfG4Az44QVyZ7-kbk-:-MXfG4Az44QVyZ7-kbk0:b6kmvtk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8560347efd4ad89fe701be7b8761303dc27aaf07/mullvad-cli/src/cmds/relay.rs#L72)):*
> ```XML
>                                 .arg(
>                                     clap::Arg::with_name("protocol")
>                                         .help("Transport protocol")
> ```

I think it would be great if the CLI was more informative. It would not hurt to add that if TCP is selected the WireGuard traffic is sent via a custom UDP over TCP proxy.
___
*[mullvad-cli/src/cmds/relay.rs, line 112 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MXfPxXj5OlqMepadDTv:-MXfPxXkB3_akGpP80Zn:b-ooqpke) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8560347efd4ad89fe701be7b8761303dc27aaf07/mullvad-cli/src/cmds/relay.rs#L112)):*
> ```XML
>                                         .default_value("udp")
>                                         .possible_values(&["udp", "tcp"])
>                                         .required(true),
> ```

Is required really required for an argument with a default value? We don't require the user to specify this.
___
*[mullvad-cli/src/cmds/relay.rs, line 271 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MXfPTb1-6BYIqICTsOc:-MXfPTb1-6BYIqICTsOd:b-gmwihp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8560347efd4ad89fe701be7b8761303dc27aaf07/mullvad-cli/src/cmds/relay.rs#L271)):*
> ```XML
>         let addresses = values_t!(matches.values_of("addr"), IpAddr).unwrap_or_else(|e| e.exit());
>         let peer_key_str =
>             value_t!(matches.value_of("peer-key"), String).unwrap_or_else(|e| e.exit());
> ```

This does not match the new name. I'm not able to run this when testing your branch.


<!-- Sent from Reviewable.io -->

2021-04-07 09:48 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[mullvad-cli/src/cmds/relay.rs, line 72 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MXfG4Az44QVyZ7-kbk-:-MXfir8rAZIMzF7ONzn8:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8560347efd4ad89fe701be7b8761303dc27aaf07/mullvad-cli/src/cmds/relay.rs#L72)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I think it would be great if the CLI was more informative. It would not hurt to add that if TCP is selected the WireGuard traffic is sent via a custom UDP over TCP proxy.
</blockquote></details>

Done.
___
*[mullvad-cli/src/cmds/relay.rs, line 112 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MXfPxXj5OlqMepadDTv:-MXfivJZ7dKCf8etvgwW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8560347efd4ad89fe701be7b8761303dc27aaf07/mullvad-cli/src/cmds/relay.rs#L112)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is required really required for an argument with a default value? We don't require the user to specify this.
</blockquote></details>

Done.
___
*[mullvad-cli/src/cmds/relay.rs, line 271 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MXfPTb1-6BYIqICTsOc:-MXfiwqgBvjio_w8oT0p:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8560347efd4ad89fe701be7b8761303dc27aaf07/mullvad-cli/src/cmds/relay.rs#L271)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This does not match the new name. I'm not able to run this when testing your branch.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-07 11:49 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537)* status: 9 of 13 files reviewed, 2 unresolved discussions (waiting on @dlon and @faern)

___
*[mullvad-cli/src/cmds/relay.rs, line 112 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MXfPxXj5OlqMepadDTv:-MXg9I1H2AfEpdSBUmio:b-3wb8wj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8560347efd4ad89fe701be7b8761303dc27aaf07/mullvad-cli/src/cmds/relay.rs#L112)):*
From the `clap` docs on `default_value`:

> NOTE: This implicitly sets `Arg::takes_value(true)`

So no need to explicitly set that.


<!-- Sent from Reviewable.io -->

2021-04-07 12:39 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537)* status: 9 of 13 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[mullvad-cli/src/cmds/relay.rs, line 112 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537#-MXfPxXj5OlqMepadDTv:-MXgKx4tDyAFWD-JbKY1:b-vlluuq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8560347efd4ad89fe701be7b8761303dc27aaf07/mullvad-cli/src/cmds/relay.rs#L112)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

From the `clap` docs on `default_value`:

> NOTE: This implicitly sets `Arg::takes_value(true)`

So no need to explicitly set that.
</blockquote></details>

Nice. Fixed.


<!-- Sent from Reviewable.io -->

2021-04-08 13:52 UTC, faern approved these changes
> Reviewed 2 of 5 files at r2, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-13 09:53 UTC, faern approved these changes
> Reviewed 1 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-13 11:25 UTC, merged