Improve Relay items sorting
mullvad/mullvadvpn-app pull request #2555
Opened 2021-03-09 12:56 UTC by axti

Previously sorting of Relays was based on string, so in this case it was not respected to numbers inside string. For example "se10" will be placed before "se5". In the new comparator we extract numbers and compare by string AND numbers.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-03-10 14:55 UTC, axti commented
___
*[android/src/test/kotlin/net/mullvad/mullvadvpn/relaylist/RelayNameComparatorTest.kt, line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-MVRMO7m6f_m6wbmJA7C:-MVRcAup70puVxeU109j:b-7ct2wz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786c81e09c9f16f20d07f187a8cdfb9145bf5b6/android/src/test/kotlin/net/mullvad/mullvadvpn/relaylist/RelayNameComparatorTest.kt#L19)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: I'm just curious, do you have any rule for when to use `camelCase` and when to use `snake_case`? I usually use `camelCase` for everything in Java, but maybe test names is a good exception?
</blockquote></details>

I'm not sure about naming in the tests, we should have a discussion. It should be easy to read and understand test case. 
I thing we can use, that in kotlin we can name it like this:
`test describe test case with as normal sentence` - and this will work and compile. 


<!-- Sent from Reviewable.io -->

2021-03-10 14:56 UTC, axti commented
___
*[android/src/test/kotlin/net/mullvad/mullvadvpn/relaylist/RelayNameComparatorTest.kt, line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-MVRL24p9Hio8NjO4n09:-MVRcvl45MpFCh3f4pZT:b-xg3tcf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786c81e09c9f16f20d07f187a8cdfb9145bf5b6/android/src/test/kotlin/net/mullvad/mullvadvpn/relaylist/RelayNameComparatorTest.kt#L24)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: Not sure if this is a silly suggestion, but would it help to have a `private fun assertOrder(first: String, second: String)` that always creates the relays and does `assertTrue(RelayNameComparator.compare(firstRelay, secondRelay) < 0)` and `assertTrue(RelayNameComparator.compare(secondRelay, firstRelay) > 0)`?
</blockquote></details>

I will look on it.


<!-- Sent from Reviewable.io -->

2021-03-10 17:28 UTC, jvff requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555)* status: all files reviewed, 5 unresolved discussions (waiting on @axti and @jvff)

___
*[android/build.gradle, line 125 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-MVMlwQJ2GAk6BkmAG3p:-MVSADQr8v5LrWruOFp-:b-v69q3n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786c81e09c9f16f20d07f187a8cdfb9145bf5b6/android/build.gradle#L125)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

This is made to have same version of dependencies. Next time we plat to have test for UI, but it will use another import for **mockk**, so to have same version and easy bump library version I put it into constant
</blockquote></details>

I think we should not create these constants until we need them. So if we only use them once, no need for constant. When/If we need to use the same version more than once, we create the constant.

What do you think?


<!-- Sent from Reviewable.io -->

2021-03-15 07:31 UTC, axti commented
___
*[android/build.gradle, line 125 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-MVMlwQJ2GAk6BkmAG3p:-MVomoZx5B9D28l1gDjf:bjtemz3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786c81e09c9f16f20d07f187a8cdfb9145bf5b6/android/build.gradle#L125)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think we should not create these constants until we need them. So if we only use them once, no need for constant. When/If we need to use the same version more than once, we create the constant.

What do you think?
</blockquote></details>

I think we can keep it, it is not hurt us.


<!-- Sent from Reviewable.io -->

2021-03-15 08:19 UTC, axti commented
___
*[android/src/test/kotlin/net/mullvad/mullvadvpn/relaylist/RelayNameComparatorTest.kt, line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-MVRLheM-DwA4ZQf1il-:-MVoxt3e8VvDMulJ46ww:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786c81e09c9f16f20d07f187a8cdfb9145bf5b6/android/src/test/kotlin/net/mullvad/mullvadvpn/relaylist/RelayNameComparatorTest.kt#L79)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Nit: The naming here is a bit confusing, because of the alphabetical order. Could they be changed to `relayAr8` and `relaySe5`?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-03-18 18:18 UTC, jvff requested changes
> Reviewed 5 of 5 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555)* status: all files reviewed, 2 unresolved discussions (waiting on @axti)

___
*[.github/workflows/android-app.yml, line 78 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-MW5Y5Qe3WRYhA8rgwql:-MW5Y5Qf67vT8EjnCXjL:b-7nzwc4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a35d205cf7542dda36054478bda672fdaddbfff/.github/workflows/android-app.yml#L78)):*
> ```YAML
>                 cd android
>                 ./gradlew --console plain assembleDebug
>                 ./gradlew testDebugUnitTest
> ```

FYI: We might want to do this in a separate job later to improve speed, but for now this is fine, since we might need some extra work to get it running as a separate job :+1:
___
*[.github/workflows/android-ktlint.yml, line 24 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-MW5Xuk2DsRWRT9QxTk1:-MW5Xuk2DsRWRT9QxTk2:byfu280) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a35d205cf7542dda36054478bda672fdaddbfff/.github/workflows/android-ktlint.yml#L24)):*
> ```YAML
>             # Check formatting
>             - run: |
>                 cd android/src/main
> ```

I think we should also lint the test code, or are there any annoying issues that it reports for the tests?
___
*[android/build.gradle, line 89 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-MW5YUJU-2Fed9rd7IjC:-MW5YUJU-2Fed9rd7IjD:byytfie) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a35d205cf7542dda36054478bda672fdaddbfff/android/build.gradle#L89)):*
> ```Gradle
>         unitTests.all {
>             testLogging {
>                 outputs.upToDateWhen { false }
> ```

I'm not sure I understand what this does. Does it force the build to always run the tests?


<!-- Sent from Reviewable.io -->

2021-03-19 07:35 UTC, axti commented
___
*[android/build.gradle, line 89 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-MW5YUJU-2Fed9rd7IjC:-MW8OzUL9nPHsPUwICGW:byno4jb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a35d205cf7542dda36054478bda672fdaddbfff/android/build.gradle#L89)):*
> ```
> outputs.upToDateWhen 
> ```
Yes, it means when we run test task, don't use previous output. So gradle can avoid running tests if it found cache result.


<!-- Sent from Reviewable.io -->

2021-03-19 07:39 UTC, axti commented
___
*[.github/workflows/android-app.yml, line 78 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-MW5Y5Qe3WRYhA8rgwql:-MW8Pj0GAs8jycZZSoAg:b-rhqj5r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a35d205cf7542dda36054478bda672fdaddbfff/.github/workflows/android-app.yml#L78)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

FYI: We might want to do this in a separate job later to improve speed, but for now this is fine, since we might need some extra work to get it running as a separate job :+1:
</blockquote></details>

I was not sure where to place it, so I append current task, since tests run only for a couple of seconds. I think we should do it in a separate job later on as you said.


<!-- Sent from Reviewable.io -->

2021-03-19 07:40 UTC, axti commented
___
*[.github/workflows/android-ktlint.yml, line 24 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-MW5Xuk2DsRWRT9QxTk1:-MW8QBn73jonFbcKUkeB:b-9wh93l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a35d205cf7542dda36054478bda672fdaddbfff/.github/workflows/android-ktlint.yml#L24)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I think we should also lint the test code, or are there any annoying issues that it reports for the tests?
</blockquote></details>

There is no need to run linter for tests, since it is not a production code and it just should test the logic.


<!-- Sent from Reviewable.io -->

2021-03-19 12:00 UTC, jvff requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555)* status: all files reviewed, 2 unresolved discussions (waiting on @axti)

___
*[.github/workflows/android-ktlint.yml, line 24 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-MW5Xuk2DsRWRT9QxTk1:-MW9LIUR9NrBzQhj-YCy:bzdhtf4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a35d205cf7542dda36054478bda672fdaddbfff/.github/workflows/android-ktlint.yml#L24)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

There is no need to run linter for tests, since it is not a production code and it just should test the logic.
</blockquote></details>

That's true, but we're going to add separate source sets later when payments is introduced, so I'd rather not have `main` there or we might forget to add other source sets there.

The simplest solution is to just lint the tests, there should be no big issues I think, and might help with maintainability in the future (even though I agree it's less important for tests).
___
*[android/build.gradle, line 89 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-MW5YUJU-2Fed9rd7IjC:-MW9LnIF1JdtI03m6uQJ:b-o6lib3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a35d205cf7542dda36054478bda672fdaddbfff/android/build.gradle#L89)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> outputs.upToDateWhen 
> ```
Yes, it means when we run test task, don't use previous output. So gradle can avoid running tests if it found cache result.
</blockquote></details>

But, shouldn't we allow Gradle to decide when to run tests or not? I mean, it should already be pretty smart about this, right?


<!-- Sent from Reviewable.io -->

2021-03-19 13:48 UTC, axti reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[.github/workflows/android-ktlint.yml, line 24 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-MW5Xuk2DsRWRT9QxTk1:-MW9jTpN8Gm0DU7y3KIR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a35d205cf7542dda36054478bda672fdaddbfff/.github/workflows/android-ktlint.yml#L24)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

That's true, but we're going to add separate source sets later when payments is introduced, so I'd rather not have `main` there or we might forget to add other source sets there.

The simplest solution is to just lint the tests, there should be no big issues I think, and might help with maintainability in the future (even though I agree it's less important for tests).
</blockquote></details>

Done.
___
*[android/build.gradle, line 89 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-MW5YUJU-2Fed9rd7IjC:-MW9jVbY0Nssp0I_i5jA:b-6y15iq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3a35d205cf7542dda36054478bda672fdaddbfff/android/build.gradle#L89)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

But, shouldn't we allow Gradle to decide when to run tests or not? I mean, it should already be pretty smart about this, right?
</blockquote></details>

As we discussed it is used locally.


<!-- Sent from Reviewable.io -->

2021-03-19 18:57 UTC, jvff approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555#-:-MWAqGLc0QwaEz8oxiXF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-19 19:29 UTC, merged