Create GitHub Actions workflows for the Rust code
mullvad/mullvadvpn-app pull request #2559
Opened 2021-03-10 11:58 UTC by jvff

We're planning on slowly migrating our CI from Travis to GitHub Actions. This PR adds workflows that are equivalent to the Rust jobs we have on Travis, with the small difference that the Rust formatting check is done in a separate workflow so that it runs separately in parallel.

The Travis job was not removed yet, because we will have some time with both CI jobs running for a while so that we can check for any inconsistencies.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header. **Internal tooling change, no changelog entry needed.**
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-03-10 16:15 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559)* status: all files reviewed, 5 unresolved discussions (waiting on @jvff)

___
*[.github/workflows/daemon.yml, line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVRu2tc7nPnLcUoTfmF:-MVRu2tc7nPnLcUoTfmG:b-wifbae) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e64ce4636230fc06e71115a1365faf93eb6b62b/.github/workflows/daemon.yml#L55)):*
> ```YAML
>             - uses: actions/setup-go@v2.1.3
>               with:
>                   go-version: 1.16
> ```

A lot of the setup/getting compilers are the same on the different platforms. Is there no way to share/not duplicate that?
___
*[.github/workflows/daemon.yml, line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVRuMb-6xxfdtrQKUzW:-MVRuMb-6xxfdtrQKUzX:bq8j9xj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e64ce4636230fc06e71115a1365faf93eb6b62b/.github/workflows/daemon.yml#L62)):*
> ```YAML
>               run: |
>                 ./wireguard/build-wireguard-go.sh
>                 sudo apt-get install libdbus-1-dev
> ```

Maybe have a separate step where dependencies are installed? Feels not 100% related to running the actual build/tests IMHO.
___
*[.github/workflows/rustfmt.yml, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVRunbV6pQGl-cWMqtV:-MVRunbV6pQGl-cWMqtW:b9d9d28) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e64ce4636230fc06e71115a1365faf93eb6b62b/.github/workflows/rustfmt.yml#L22)):*
> ```YAML
>             - talpid-openvpn-plugin/**/*.rs
>             - talpid-platform-metadata/**/*.rs
>             - talpid-types/**/*.rs
> ```

Instead of listing all the crates. Can't this be simplified to `**/*.rs`?


<!-- Sent from Reviewable.io -->

2021-03-10 16:16 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559)* status: all files reviewed, 6 unresolved discussions (waiting on @jvff)

___
*[.github/workflows/rustfmt.yml, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVRv8xuAkIuxP0N7O_X:-MVRv8xuAkIuxP0N7O_Y:b-wopt14) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e64ce4636230fc06e71115a1365faf93eb6b62b/.github/workflows/rustfmt.yml#L5)):*
> ```YAML
>     # Check whenever a file that affects Android is changed by a push
>     push:
>         paths:
> ```

This job should trigger also if the root `rustfmt.toml` changes I think. Because it can affect formatting.


<!-- Sent from Reviewable.io -->

2021-03-10 20:23 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @dlon and @faern)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVSik3R7klZymYsf2Z2:-MVSik3S-ISExlhzmBiq:brbj764) (no related file):*
Windows jobs still take most of the time. Is there any way to parallelize it? I mean, could there be a separate job to build the windows modules?

---
___
*[.github/workflows/daemon.yml, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVS060O54P9alE8o5p2:-MVSbEb21Inzy2Zs59SU:b-rtjs9d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e64ce4636230fc06e71115a1365faf93eb6b62b/.github/workflows/daemon.yml#L7)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could this be simplified using something like this?

```
- '**'
- '!mullvad-jni/**'
- '!dist-assets/**'
- '!ios/**'
- '!docs/**'
- '!audits/**'
```

It seems easy to forget to add a new directory here. It's probably better to accidentally include too much.
</blockquote></details>

Done. I added a lot more paths that I think don't affect the build, but please let me know if there's anything there that shouldn't be :D
___
*[.github/workflows/daemon.yml, line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVRnX9f4HLx2isxKCzT:-MVSbMMB1pQE783B5pZ4:b-vve210) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e64ce4636230fc06e71115a1365faf93eb6b62b/.github/workflows/daemon.yml#L23)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I forgot about `windows/**`.
</blockquote></details>

Done. Solved by using `paths-ignore`.
___
*[.github/workflows/daemon.yml, line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVRu2tc7nPnLcUoTfmF:-MVScWie-ObYQEedto85:bkbso82) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e64ce4636230fc06e71115a1365faf93eb6b62b/.github/workflows/daemon.yml#L55)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

A lot of the setup/getting compilers are the same on the different platforms. Is there no way to share/not duplicate that?
</blockquote></details>

I tried to improve that, but GitHub Actions doesn't support anchors yet :(
___
*[.github/workflows/daemon.yml, line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVRuMb-6xxfdtrQKUzW:-MVSZ_LB0dz0yFFzAyFg:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e64ce4636230fc06e71115a1365faf93eb6b62b/.github/workflows/daemon.yml#L62)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Maybe have a separate step where dependencies are installed? Feels not 100% related to running the actual build/tests IMHO.
</blockquote></details>

Done.
___
*[.github/workflows/daemon.yml, line 103 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVRrVq4DYJpjzPgz2Wl:-MVSVoB41OeNk2tvRd81:b-f9wv8m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e64ce4636230fc06e71115a1365faf93eb6b62b/.github/workflows/daemon.yml#L103)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do we need these? I think everything you need to build the app can be found in `dist-assets/binaries/x86_64-*`.
</blockquote></details>

Done. Yep, that's a lot simpler :D 
___
*[.github/workflows/daemon.yml, line 119 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVRmY4M7kgnNSTLD-iJ:-MVSWQLo36iqFssBWqqR:b-d8oeet) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e64ce4636230fc06e71115a1365faf93eb6b62b/.github/workflows/daemon.yml#L119)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We might want to specify 16 as the (minimum) `vs-version` here.
</blockquote></details>

Done. Let me know if it needs to be a more specific `16.x` version.
___
*[.github/workflows/rustfmt.yml, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVRv8xuAkIuxP0N7O_X:-MVSeS0QAMp0jPBarA25:blp4x9v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e64ce4636230fc06e71115a1365faf93eb6b62b/.github/workflows/rustfmt.yml#L5)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This job should trigger also if the root `rustfmt.toml` changes I think. Because it can affect formatting.
</blockquote></details>

Done. Nice catch, thanks!
___
*[.github/workflows/rustfmt.yml, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVRunbV6pQGl-cWMqtV:-MVSeSWA9g1TAeR9Zptv:b-271pc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e64ce4636230fc06e71115a1365faf93eb6b62b/.github/workflows/rustfmt.yml#L22)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Instead of listing all the crates. Can't this be simplified to `**/*.rs`?
</blockquote></details>

Done. Much better :D


<!-- Sent from Reviewable.io -->

2021-03-11 08:08 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @dlon and @jvff)

___
*[.github/workflows/daemon.yml, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVS060O54P9alE8o5p2:-MVVIaNxBB8YCt5gHb0w:b-74dane) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e64ce4636230fc06e71115a1365faf93eb6b62b/.github/workflows/daemon.yml#L7)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done. I added a lot more paths that I think don't affect the build, but please let me know if there's anything there that shouldn't be :D
</blockquote></details>

Wow. Pretty long list. Let's try! It does not have to be perfect from day one. Better to let it build a bit too often compared to miss a few builds. So an inverted list like this makes sense I guess :+1:
___
*[.github/workflows/daemon.yml, line 6 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVVI3Es7FNVd-8INBp0:-MVVI3Es7FNVd-8INBp1:b-sxs8oe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac3d582e8bf5f8a85afeb264d7df7c596e18451b/.github/workflows/daemon.yml#L6)):*
> ```YAML
>     push:
>         paths-ignore:
>             - .github/*.md
> ```

You already have a `**/*.md* entry, so this one should not be needed?
___
*[.github/workflows/daemon.yml, line 62 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVVJwVZ8dqS5y0pxuqW:-MVVJwVZ8dqS5y0pxuqX:b-v75p7e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac3d582e8bf5f8a85afeb264d7df7c596e18451b/.github/workflows/daemon.yml#L62)):*
> ```YAML
>             - run: sudo apt-get install libdbus-1-dev
> 
>             # Build and test crates
> ```

Can tests be given names? Can this comment be made as a real name to this step?

This step is currently our main step that builds everything. But in the CI UI it shows up as `Run ./wireguard/build-wireguard-go.sh` as that's the first command. Not very intuitive.


<!-- Sent from Reviewable.io -->

2021-03-11 09:34 UTC, dlon approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559)* status: all files reviewed, 3 unresolved discussions (waiting on @jvff)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVSik3R7klZymYsf2Z2:-MVVc-wk85ruFHtN9UDq:bdv5pus) (no related file):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Windows jobs still take most of the time. Is there any way to parallelize it? I mean, could there be a separate job to build the windows modules?
</blockquote></details>

I suppose all `Win*_*` functions could be replaced with noop functions for CI builds. Then `build_windows_modules.sh` could be run in a separate job.

---


<!-- Sent from Reviewable.io -->

2021-03-11 09:37 UTC, dlon approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559)* status: all files reviewed, 3 unresolved discussions (waiting on @jvff)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVSik3R7klZymYsf2Z2:-MVVdKMi3PxXSiLIl5tQ:bt0r4nv) (no related file):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I suppose all `Win*_*` functions could be replaced with noop functions for CI builds. Then `build_windows_modules.sh` could be run in a separate job.
</blockquote></details>

There are probably tests that would fail.

---


<!-- Sent from Reviewable.io -->

2021-03-11 10:01 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559)* status: all files reviewed, 3 unresolved discussions (waiting on @jvff)

___
*[.github/workflows/daemon.yml, line 6 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVVI3Es7FNVd-8INBp0:-MVVibIE0vKROnPsrFJv:b-tlrjyt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac3d582e8bf5f8a85afeb264d7df7c596e18451b/.github/workflows/daemon.yml#L6)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

You already have a `**/*.md* entry, so this one should not be needed?
</blockquote></details>

How about moving wildcard paths like `**/*.md` to the top of the list. Currently it's in the middle and it's not very easy to see "oh, all markdown is ignored". Makes sense to have "normal" paths sorted alphabetically, but I think the wildcards can come first.


<!-- Sent from Reviewable.io -->

2021-03-11 18:29 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dlon, @faern, and @jvff)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVSik3R7klZymYsf2Z2:-MVXVuRL-wOkZLtFWF1N:bq0iyuy) (no related file):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

There are probably tests that would fail.
</blockquote></details>

Ah, in that case it's probably best to leave it as is. We can think of engineering a solution to reduce times later if needed :+1:

---
___
*[.github/workflows/daemon.yml, line 6 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVVI3Es7FNVd-8INBp0:-MVXWYi0DKqKoiIEDlDN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac3d582e8bf5f8a85afeb264d7df7c596e18451b/.github/workflows/daemon.yml#L6)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

How about moving wildcard paths like `**/*.md` to the top of the list. Currently it's in the middle and it's not very easy to see "oh, all markdown is ignored". Makes sense to have "normal" paths sorted alphabetically, but I think the wildcards can come first.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-12 08:01 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-:-MV_S2IzCA_HHigfObxb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-12 10:12 UTC, dlon approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-12 10:14 UTC, dlon requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[.github/workflows/daemon.yml, line 11 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MV_vKGEA0K_V7cwgyb0:-MV_vKGF2ELvpyul_efu:brtdji9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d3e6ad391d249bf1a1aa7331a4bfca3f1a19401e/.github/workflows/daemon.yml#L11)):*
> ```YAML
>             - android/**
>             - audits/**
>             - ci/**
> ```

This is not correct anymore due to `ci/check-daemon.sh`.


<!-- Sent from Reviewable.io -->

2021-03-12 12:11 UTC, faern approved these changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-03-12 12:11 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-:-MVaLKjJ3tCKxxcZ-o6-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-03-12 12:12 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[.github/workflows/daemon.yml, line 62 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MVVJwVZ8dqS5y0pxuqW:-MVaD6no0WHkmxsmCcBY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac3d582e8bf5f8a85afeb264d7df7c596e18451b/.github/workflows/daemon.yml#L62)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can tests be given names? Can this comment be made as a real name to this step?

This step is currently our main step that builds everything. But in the CI UI it shows up as `Run ./wireguard/build-wireguard-go.sh` as that's the first command. Not very intuitive.
</blockquote></details>

Done.
___
*[.github/workflows/daemon.yml, line 11 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559#-MV_vKGEA0K_V7cwgyb0:-MVaD0loDAu5Es-BXA1k:bdf04cz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d3e6ad391d249bf1a1aa7331a4bfca3f1a19401e/.github/workflows/daemon.yml#L11)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is not correct anymore due to `ci/check-daemon.sh`.
</blockquote></details>

Done. Good catch, thanks!


<!-- Sent from Reviewable.io -->

2021-03-12 12:57 UTC, dlon approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-12 13:29 UTC, merged