Disable unused functionality in renderer
mullvad/mullvadvpn-app pull request #2565
Opened 2021-03-12 09:50 UTC by raksooo

This PR further locks down the renderer process. The changes are:
* automatically deny any permission requests
* block navigation
* block `file://` access to files outside build directory
* limit ipc calls to `openUrl` to only allow mullvad.net URLs
* replaced `openPath` ipc method with `viewLog` which only needs the ID instead of the full path to open.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-03-12 13:12 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 1168 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565#-MVaZ1qPD9S-d3-Lo9zR:-MVaZ1qPD9S-d3-Lo9zS:bfd5fgf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce72d4dcc004c6a5b675b2eefcea417efdf35bb4/gui/src/main/index.ts#L1168)):*
> ```XML
>     });
> 
>     IpcMainEventChannel.problemReport.handleSendReport(({ email, message, savedReport }) => {
> ```

As I understand you pass the report UUID in place of `savedReport` which used to be a file path, so perhaps rename the variable to reflect that, i.e `reportID`?


<!-- Sent from Reviewable.io -->

2021-03-12 13:28 UTC, pronebird requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 1196 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565#-MVabjBR3b-foj7bd0EQ:-MVabjBR3b-foj7bd0ER:b-blld1i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce72d4dcc004c6a5b675b2eefcea417efdf35bb4/gui/src/main/index.ts#L1196)):*
> ```XML
>     IpcMainEventChannel.app.handleQuit(() => app.quit());
>     IpcMainEventChannel.app.handleOpenUrl(async (url) => {
>       if (url.startsWith('https://mullvad.net/')) {
> ```

Maybe we could move that to `config.json`?


<!-- Sent from Reviewable.io -->

2021-03-12 14:50 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[gui/src/main/index.ts, line 1168 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565#-MVaZ1qPD9S-d3-Lo9zR:-MVau5Y_DbsbeV8tRrvL:bbv011x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce72d4dcc004c6a5b675b2eefcea417efdf35bb4/gui/src/main/index.ts#L1168)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

As I understand you pass the report UUID in place of `savedReport` which used to be a file path, so perhaps rename the variable to reflect that, i.e `reportID`?
</blockquote></details>

The previous name didn't imply that it was a path but I agree that it's a good idea to rename it. Done.
___
*[gui/src/main/index.ts, line 1196 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565#-MVabjBR3b-foj7bd0EQ:-MVauMuA89yNtvVz3E7K:b-vh1rfa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce72d4dcc004c6a5b675b2eefcea417efdf35bb4/gui/src/main/index.ts#L1196)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe we could move that to `config.json`?
</blockquote></details>

I went with another approach, what do you think?
___
*[gui/src/main/index.ts, line 1425 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565#-MVauTCm0LnKi86bhf0x:-MVauTCm0LnKi86bhf0y:bjx0vwi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce72d4dcc004c6a5b675b2eefcea417efdf35bb4/gui/src/main/index.ts#L1425)):*
> ```XML
>   private blockRequests() {
>     const buildDir = 'file:' + path.normalize(path.join(__dirname, '..', '..'));
> ```

I realized that in some cases the URL starts with `file:` and in some cases `file://` and it might also be url-encoded so I had to handle that as well.


<!-- Sent from Reviewable.io -->

2021-03-15 12:20 UTC, pronebird requested changes
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 1168 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565#-MVaZ1qPD9S-d3-Lo9zR:-MVpmMzY0hCheX56Wr8F:b4736jv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce72d4dcc004c6a5b675b2eefcea417efdf35bb4/gui/src/main/index.ts#L1168)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

The previous name didn't imply that it was a path but I agree that it's a good idea to rename it. Done.
</blockquote></details>

I agree, but it doesn't mean that we have to stick to old habits. :-) Thanks for fixing the variable name.
___
*[gui/src/main/index.ts, line 1196 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565#-MVabjBR3b-foj7bd0EQ:-MVpmCZ95phmxQ7Q0V8m:b-vs1prh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce72d4dcc004c6a5b675b2eefcea417efdf35bb4/gui/src/main/index.ts#L1196)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I went with another approach, what do you think?
</blockquote></details>

Looks good!
___
*[gui/src/main/index.ts, line 1425 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565#-MVauTCm0LnKi86bhf0x:-MVpmvoKBce1wiDd3oyM:btqge94) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce72d4dcc004c6a5b675b2eefcea417efdf35bb4/gui/src/main/index.ts#L1425)):*
You could probably run it through `URL` to get it parsed for you.

```
> new URL("file:///Users/pronebird/file.log")
URL {
  href: 'file:///Users/pronebird/file.log',
  origin: 'null',
  protocol: 'file:',
  username: '',
  password: '',
  host: '',
  hostname: '',
  port: '',
  pathname: '/Users/pronebird/file.log',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
> new URL("file:///Users/pronebird/file.log")
```
___
*[gui/src/main/index.ts, line 1427 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565#-MVpn5fBDLX96CZz0VX6:-MVpn5fCBiEVoenuQ3Ly:b52p0z0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce72d4dcc004c6a5b675b2eefcea417efdf35bb4/gui/src/main/index.ts#L1427)):*
> ```XML
> 
>     session.defaultSession.webRequest.onBeforeRequest(
>       { urls: ['*://*/*', 'file://*/*'] },
> ```

`*://*/*` should catch `file://*` as well ain't it? Also note that probably `*://*` should work as well. I don't quite understand the reason for capturing the trailing slash with whatever comes after it.

Also if you'd like to capture all requests, then you don't need a filter ([see docs](https://www.electronjs.org/docs/api/web-request#webrequestonbeforerequestfilter-listener))

```
webRequest.onBeforeRequest([filter, ]listener)

```


<!-- Sent from Reviewable.io -->

2021-03-15 21:08 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/main/index.ts, line 1425 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565#-MVauTCm0LnKi86bhf0x:-MVrgVX53VCks5H4-pBk:bbcvooa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce72d4dcc004c6a5b675b2eefcea417efdf35bb4/gui/src/main/index.ts#L1425)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You could probably run it through `URL` to get it parsed for you.

```
> new URL("file:///Users/pronebird/file.log")
URL {
  href: 'file:///Users/pronebird/file.log',
  origin: 'null',
  protocol: 'file:',
  username: '',
  password: '',
  host: '',
  hostname: '',
  port: '',
  pathname: '/Users/pronebird/file.log',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
> new URL("file:///Users/pronebird/file.log")
```
</blockquote></details>

Good idea! I still have to handle URLs starting with `file:///C:/` resulting in a `pathname` starting with `/C:/` though.
___
*[gui/src/main/index.ts, line 1427 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565#-MVpn5fBDLX96CZz0VX6:-MVrgt7U6dz7NI72XDuP:b-ycu1cl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce72d4dcc004c6a5b675b2eefcea417efdf35bb4/gui/src/main/index.ts#L1427)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`*://*/*` should catch `file://*` as well ain't it? Also note that probably `*://*` should work as well. I don't quite understand the reason for capturing the trailing slash with whatever comes after it.

Also if you'd like to capture all requests, then you don't need a filter ([see docs](https://www.electronjs.org/docs/api/web-request#webrequestonbeforerequestfilter-listener))

```
webRequest.onBeforeRequest([filter, ]listener)

```
</blockquote></details>

I remember from last time I worked with this that `*://*` didn't work, I have no idea why. It seems like `*://*/*` only works matches `https` and `http`, it didn't match `file:`, `ws:`, `devtools:`, `chrome-extension:` and possibly others. Good idea with removing the filter, now it matches everything.


<!-- Sent from Reviewable.io -->

2021-03-15 21:09 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/main/index.ts, line 1427 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565#-MVpn5fBDLX96CZz0VX6:-MVri8bTAxNUZyW_4-hm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce72d4dcc004c6a5b675b2eefcea417efdf35bb4/gui/src/main/index.ts#L1427)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I remember from last time I worked with this that `*://*` didn't work, I have no idea why. It seems like `*://*/*` only works matches `https` and `http`, it didn't match `file:`, `ws:`, `devtools:`, `chrome-extension:` and possibly others. Good idea with removing the filter, now it matches everything.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-16 10:37 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565#-:-MVubF4TC4bbTUHMf3Ah:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[gui/src/main/index.ts, line 1427 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565#-MVpn5fBDLX96CZz0VX6:-MVub02J3kUcxQALVqUA:b5dx0er) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce72d4dcc004c6a5b675b2eefcea417efdf35bb4/gui/src/main/index.ts#L1427)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think filter didn't properly work in older Electron but probably should have been fixed by now. Please double check if that works :)


<!-- Sent from Reviewable.io -->

2021-03-16 10:38 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-24 15:46 UTC, merged