Manually strip native Android libraries
mullvad/mullvadvpn-app pull request #2568
Opened 2021-03-13 16:15 UTC by jvff

A previous tool update (#2453) increased the size of the final APK (funny side note: the release notes for the new tool version says that in the new version ["App size significantly reduced for apps using code shrinking"](https://developer.android.com/studio/releases/gradle-plugin#4.1-app-size-reduction) ).

The root cause seems to be that the tool internally changed how it finds the NDK path and fails to find the `strip` tool, so it simply emits a warning and includes the unstripped library. A known workaround is to add a `ndk.dir` property to the `local.properties` file in order to force the old way to find the tool. However, that file should not be versioned since it's environment specific. Therefore, it's not a good solution and would require instead adding documentation for all build environments to have its own custom `local.properties` file.

Since a previous update also led to not-stripping the libraries for a different reason (#1908), this PR fixes the issue by manually stripping the libraries after they have been built. Therefore there is no longer a dependency on the Android Gradle Plugin working as expected.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header. **Fixes a minor issue not present in any publicly released version.**
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-03-15 15:28 UTC, faern requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2568)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[build-apk.sh, line 126 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2568#-MVqUUjg7YOPmK_qj1wE:-MVqUUjh7KM0bo0ZjP9D:brt2gif) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e1c2537d60a91ddf9fa057721830c8d19a8c1a5/build-apk.sh#L126)):*
> ```Shell
> 
>     cp "$SCRIPT_DIR/target/$TARGET/$BUILD_TYPE/libmullvad_jni.so" "$DESTINATION_PATH"
>     $STRIP_TOOL --strip-debug --strip-unneeded "$DESTINATION_PATH"
> ```

The normal linux strip tool allows `-o <out>` to give the output path directly. That would remove the need of a separate `cp` step. Can we do that? Or does these strip tools not have that flag maybe?


<!-- Sent from Reviewable.io -->

2021-03-17 15:44 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2568)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[build-apk.sh, line 126 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2568#-MVqUUjg7YOPmK_qj1wE:-MW-qghT2qZSKlVU372r:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e1c2537d60a91ddf9fa057721830c8d19a8c1a5/build-apk.sh#L126)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The normal linux strip tool allows `-o <out>` to give the output path directly. That would remove the need of a separate `cp` step. Can we do that? Or does these strip tools not have that flag maybe?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-17 17:39 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2568#-:-MW0GFDyDj2KP2hEuE0A:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-18 08:39 UTC, faern approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2568)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-22 12:16 UTC, faern approved these changes
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2568)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-22 13:56 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2568#-:-MWPDLB26i98L-DctWal:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-22 15:15 UTC, merged