Fix not setting account when not connected to daemon
mullvad/mullvadvpn-app pull request #2572
Opened 2021-03-15 09:56 UTC by raksooo

This PR fixes and issue with the account not being set in the renderer if not connected to the daemon. This was introduced in https://github.com/mullvad/mullvadvpn-app/pull/2566.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-03-15 12:03 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2572)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/app.tsx, line 212 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2572#-MVpkbKm1r2IFfsouo9t:-MVpkbKm1r2IFfsouo9u:b2p7ghm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc216a51aadcb0a94b84f35f07f66d088bc8e1/gui/src/renderer/app.tsx#L212)):*
> ```XML
>     this.setWireguardPublicKey(initialState.wireguardPublicKey);
> 
>     if (initialState.isConnected) {
> ```

As noted in the conversation on Slack, I think you could take a stab at reworking the `constructor` a bit by moving navigation right here.

Something like that:

```
this.connectedToDaemon = initialState.isConnected;

if (initialState.isConnected) { // daemon is connected
  if (initialState.settings.accountToken) { // logged in!
    reduxAccount.updateAccountToken(initialState.settings.accountToken);
    reduxAccount.loggedIn();
    this.history.resetWith('/connect');
  } else { // not logged in yet!
    this.history.resetWith('/login');
  }
} else { // daemon is not connected.
  this.history.resetWith('/');
}
```


<!-- Sent from Reviewable.io -->

2021-03-15 12:03 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2572)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2021-03-15 20:22 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2572)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/renderer/app.tsx, line 212 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2572#-MVpkbKm1r2IFfsouo9t:-MVrY9JVCpUrHCCrkc6A:bfykkx2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc216a51aadcb0a94b84f35f07f66d088bc8e1/gui/src/renderer/app.tsx#L212)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

As noted in the conversation on Slack, I think you could take a stab at reworking the `constructor` a bit by moving navigation right here.

Something like that:

```
this.connectedToDaemon = initialState.isConnected;

if (initialState.isConnected) { // daemon is connected
  if (initialState.settings.accountToken) { // logged in!
    reduxAccount.updateAccountToken(initialState.settings.accountToken);
    reduxAccount.loggedIn();
    this.history.resetWith('/connect');
  } else { // not logged in yet!
    this.history.resetWith('/login');
  }
} else { // daemon is not connected.
  this.history.resetWith('/');
}
```
</blockquote></details>

We would still have to call both `handleAccountTokenChange` and `onDaemonConnected` right? I just pushed another alternative. Let me know what you think!


<!-- Sent from Reviewable.io -->

2021-03-16 10:41 UTC, pronebird requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2572)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @pronebird and @raksooo)

___
*[gui/src/renderer/app.tsx, line 212 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2572#-MVpkbKm1r2IFfsouo9t:-MVubgNS-kZ-iLNkOXIF:bse8mbl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc216a51aadcb0a94b84f35f07f66d088bc8e1/gui/src/renderer/app.tsx#L212)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

We would still have to call both `handleAccountTokenChange` and `onDaemonConnected` right? I just pushed another alternative. Let me know what you think!
</blockquote></details>

Not from `constructor` as constructor can make assumptions and set the correct initial view + state.


<!-- Sent from Reviewable.io -->

2021-03-16 10:44 UTC, pronebird requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2572)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/app.tsx, line 212 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2572#-MVpkbKm1r2IFfsouo9t:-MVuceHIBJEBgXIFuOkp:b-mab9at) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc216a51aadcb0a94b84f35f07f66d088bc8e1/gui/src/renderer/app.tsx#L212)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Not from `constructor` as constructor can make assumptions and set the correct initial view + state.
</blockquote></details>

Although with the proposed changes I guess that will do.


<!-- Sent from Reviewable.io -->

2021-03-16 10:44 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2572)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-16 10:44 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2572#-:-MVucis81zEd8Mk3kaUA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-16 10:45 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2572)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[gui/src/renderer/app.tsx, line 212 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2572#-MVpkbKm1r2IFfsouo9t:-MVucaek2VydsW6vIvi1:bn9i2dz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc216a51aadcb0a94b84f35f07f66d088bc8e1/gui/src/renderer/app.tsx#L212)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Although with the proposed changes I guess that will do.
</blockquote></details>

It would still require to call both of these
```
        reduxAccount.updateAccountToken(newAccount);
        reduxAccount.loggedIn();
```
and
```
        await this.autoConnect();
```

So there will be quite a bit of code duplication.

Great, I'll merge it then :+1:


<!-- Sent from Reviewable.io -->

2021-03-16 10:56 UTC, merged