Save initial target state
mullvad/mullvadvpn-app pull request #2608
Opened 2021-03-23 14:46 UTC by dlon

Previously, the target state cache was deleted after being restored by the daemon. This means that the daemon would not enter the correct state after a crash (or restart during an upgrade) in this situation. This was fixed by caching the initial target state.

2021-03-23 19:58 UTC, faern requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2608)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[CHANGELOG.md, line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2608#-MWU_izu6WkRqMCg95ew:-MWU_izu6WkRqMCg95ex:b-oe9uhp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb7f3ca8c26ac7120c8ba4d6aa1e59a2509eee5f/CHANGELOG.md#L65)):*
> ```Markdown
> - Fix incorrectly displayed "inconsistent version" text in settings if disconnected from daemon on
>   startup.
> - Cache initial target state.
> ```

This is not really helpful for a reader not familiar with the code. We also need to explain what it fixes, not just very short what code was changed.

Move it to `### Security` and explain that we fixed a small traffic leak window during upgrades please.


<!-- Sent from Reviewable.io -->

2021-03-24 09:00 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2608)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[CHANGELOG.md, line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2608#-MWU_izu6WkRqMCg95ew:-MWYSVgRAlugzpX8Ok7F:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb7f3ca8c26ac7120c8ba4d6aa1e59a2509eee5f/CHANGELOG.md#L65)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This is not really helpful for a reader not familiar with the code. We also need to explain what it fixes, not just very short what code was changed.

Move it to `### Security` and explain that we fixed a small traffic leak window during upgrades please.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-24 09:19 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2608)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[CHANGELOG.md, line 81 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2608#-MWYWmUa5rCAyNOqb9hi:-MWYWmUbC9QaQgIne2IU:b-mk6i03) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa6b6652763c8f287aa4430002e5c1d0311f3d4f/CHANGELOG.md#L81)):*
> ```Markdown
> 
> ### Security
> - Fix small traffic leak window during upgrades.
> ```

It does not affect all platforms. So it should live under a `#### Windows` subsection


<!-- Sent from Reviewable.io -->

2021-03-24 09:43 UTC, faern requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2608)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[CHANGELOG.md, line 81 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2608#-MWYWmUa5rCAyNOqb9hi:-MWYbI-B7ucRWgCjTfnf:bbb4rr9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa6b6652763c8f287aa4430002e5c1d0311f3d4f/CHANGELOG.md#L81)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It does not affect all platforms. So it should live under a `#### Windows` subsection
</blockquote></details>

After discussions on Slack I was informed that this might not be Windows specific. Should be confirmed before this is merged. So we know the scope of the issue.


<!-- Sent from Reviewable.io -->

2021-03-24 10:45 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2608)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[CHANGELOG.md, line 81 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2608#-MWYWmUa5rCAyNOqb9hi:-MWYnHAA3mivX8tuxbK0:b-ahhv5c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa6b6652763c8f287aa4430002e5c1d0311f3d4f/CHANGELOG.md#L81)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

After discussions on Slack I was informed that this might not be Windows specific. Should be confirmed before this is merged. So we know the scope of the issue.
</blockquote></details>

Confirmed. Holds true on Linux as well, running the following twice:
```
/opt/Mullvad\ VPN/resources/mullvad-setup prepare-restart && systemctl restart mullvad-daemon
```
I've updated the changelog. It's not really a leak window, but an issue of not starting in the right state.


<!-- Sent from Reviewable.io -->

2021-03-24 11:01 UTC, faern approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2608)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[CHANGELOG.md, line 81 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2608#-MWYWmUa5rCAyNOqb9hi:-MWYtMLc9BW2L41CCNuc:b-uqr9vp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa6b6652763c8f287aa4430002e5c1d0311f3d4f/CHANGELOG.md#L81)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Confirmed. Holds true on Linux as well, running the following twice:
```
/opt/Mullvad\ VPN/resources/mullvad-setup prepare-restart && systemctl restart mullvad-daemon
```
I've updated the changelog. It's not really a leak window, but an issue of not starting in the right state.
</blockquote></details>

Great! This is much more explanatory. And with your new discovery: more correct also :)


<!-- Sent from Reviewable.io -->

2021-03-25 13:38 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2608#-:-MWdauB7CnbTTD_lreS1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-25 15:37 UTC, merged