Split `LocationInfoCache` into UI-side and service-side classes
mullvad/mullvadvpn-app pull request #2610
Opened 2021-03-23 18:49 UTC by jvff

This PR continues the work on splitting the code base so that the background service can run in a separate process. This PR focuses on the `LocationInfoCache` which is responsible for obtaining the Geo IP location. Now there are two classes, where the service-side `LocationInfoCache` is where the behavior is kept, and the UI side which will register and listen for `NewLocation` events from the IPC channel.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header. **Internal refactor, no user visible changes.**
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-03-24 10:45 UTC, axti requested changes
> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2610)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2610#-MWYGaA63RMxPFvSp6Bp:-MWYGaA63RMxPFvSp6Bq:b6om2v5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e1d7ea5dfa0931e73c259445ded719ca4898b5b/android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt#L10)):*
> ```
>     val daemon: MullvadDaemon,
>     val intermittentDaemon: Intermittent<MullvadDaemon>,
> ```
we already have a `daemon` here, why do we need `Intermittent`?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2610#-MWYMvIp3IW_ircFap6l:-MWYMvIp3IW_ircFap6m:b-8ahl5i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e1d7ea5dfa0931e73c259445ded719ca4898b5b/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt#L66)):*
> ```
>     var stateEvents by autoSubscribable<TunnelState>(this, TunnelState.Disconnected) { newState ->
>         state = newState
>     }
> ```
What is a difference with `var state` from above?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt, line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2610#-MWYMOdK5yUy9SLC5l_n:-MWYMOdK5yUy9SLC5l_o:bqfyf9g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e1d7ea5dfa0931e73c259445ded719ca4898b5b/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt#L82)):*
<details><summary><i alt="summary">Quoted 21 lines of code…</i></summary>

> ```
>         endpoint.settingsListener.relaySettingsNotifier.subscribe(this) { relaySettings ->
>             selectedRelayLocation = (relaySettings as? RelaySettings.Normal)?.let { settings ->
>                 when (val constraint = settings.relayConstraints.location) {
>                     is Constraint.Any -> null
>                     is Constraint.Only -> when (val location = constraint.value) {
>                         is LocationConstraint.Country -> {
>                             GeoIpLocation(null, null, location.countryCode, null, null)
>                         }
>                         is LocationConstraint.City -> {
>                             GeoIpLocation(null, null, location.countryCode, location.cityCode, null)
>                         }
>                         is LocationConstraint.Hostname -> GeoIpLocation(
>                             null,
>                             null,
>                             location.countryCode,
>                             location.cityCode,
>                             location.hostname
>                         )
>                     }
>                 }
>             }
> ```
</details>

Please improve readability `when inside when inside lambda inside lambda` it difficult to read and track context.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt, line 126 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2610#-MWYnHwiCDJ6skV8ACHI:-MWYnHwiCDJ6skV8ACHJ:b1bj9cr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e1d7ea5dfa0931e73c259445ded719ca4898b5b/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt#L126)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>         while (true) {
>             var fetchType = channel.receive()
>             var newLocation = daemon.await().getCurrentLocation()
>             while (newLocation == null || !channel.isEmpty) {
>                 fetchType = delayOrReceive(delays, channel, fetchType)
>                 newLocation = daemon.await().getCurrentLocation()
>             }
>             handleNewLocation(newLocation, fetchType)
>             delays.reset()
>         }
> ```
</details>

This could be simplified with:
```
for (fetchType in channel) {
} 
```
What are your thoughts?


<!-- Sent from Reviewable.io -->

2021-03-24 18:41 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2610)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @axti)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2610#-MWYGaA63RMxPFvSp6Bp:-MW_T0Z16ExR0d-nvviy:bnphw93) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e1d7ea5dfa0931e73c259445ded719ca4898b5b/android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt#L10)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>     val daemon: MullvadDaemon,
>     val intermittentDaemon: Intermittent<MullvadDaemon>,
> ```
we already have a `daemon` here, why do we need `Intermittent`?
</blockquote></details>

This is not great, but it's temporary. This `ServiceInstance` class will be removed once the split is complete. Right now it's kind of in a limbo where it's being used by new code temporarily and old code while the split is not yet complete :/
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2610#-MWYMvIp3IW_ircFap6l:-MW_F18K-ZIkoA75dl-z:bhft85c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e1d7ea5dfa0931e73c259445ded719ca4898b5b/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt#L66)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>     var stateEvents by autoSubscribable<TunnelState>(this, TunnelState.Disconnected) { newState ->
>         state = newState
>     }
> ```
What is a difference with `var state` from above?
</blockquote></details>

Right, this is a bit confusing: `state` contains the actual state value, while `stateEvents` is a reference to the source of state change events. The `autoSubscribable` delegate will automatically subscribe to any event source that the property is set to, and call the listener block provided. The block will just set `state` whenever there's a state change event.

This is temporary, because in the future there will only be one event source, so the class can just register once and not worry about it anymore. Right now, the `ConnectionProxy` isn't correctly split between processes, so the `stateEvents` is used so that the source can be configured externally.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt, line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2610#-MWYMOdK5yUy9SLC5l_n:-MW_G9-e4OTnGJPRfn40:bz9s5ut) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e1d7ea5dfa0931e73c259445ded719ca4898b5b/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt#L82)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>         endpoint.settingsListener.relaySettingsNotifier.subscribe(this) { relaySettings ->
>             selectedRelayLocation = (relaySettings as? RelaySettings.Normal)?.let { settings ->
>                 when (val constraint = settings.relayConstraints.location) {
>                     is Constraint.Any -> null
>                     is Constraint.Only -> when (val location = constraint.value) {
>                         is LocationConstraint.Country -> {
>                             GeoIpLocation(null, null, location.countryCode, null, null)
>                         }
>                         is LocationConstraint.City -> {
>                             GeoIpLocation(null, null, location.countryCode, location.cityCode, null)
>                         }
>                         is LocationConstraint.Hostname -> GeoIpLocation(
>                             null,
>                             null,
>                             location.countryCode,
>                             location.cityCode,
>                             location.hostname
>                         )
>                     }
>                 }
>             }
> ```
Please improve readability `when inside when inside lambda inside lambda` it difficult to read and track context.
</blockquote></details>

Done. Yeah, this was too dense :/ 
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt, line 126 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2610#-MWYnHwiCDJ6skV8ACHI:-MW_SHn7DE7_JOcF-hgp:b-4cc8qr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e1d7ea5dfa0931e73c259445ded719ca4898b5b/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt#L126)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>         while (true) {
>             var fetchType = channel.receive()
>             var newLocation = daemon.await().getCurrentLocation()
>             while (newLocation == null || !channel.isEmpty) {
>                 fetchType = delayOrReceive(delays, channel, fetchType)
>                 newLocation = daemon.await().getCurrentLocation()
>             }
>             handleNewLocation(newLocation, fetchType)
>             delays.reset()
>         }
> ```
This could be simplified with:
```
for (fetchType in channel) {
} 
```
What are your thoughts?
</blockquote></details>

That would've been awesome, but `fetchType` needs to be `var` because it might be received again in the middle of the loop.

Do you have any ideas on how to restructure this?


<!-- Sent from Reviewable.io -->

2021-03-26 06:58 UTC, axti approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 11 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2610#-:-MWhJzXlCFYoLIYftoHD:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt, line 126 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2610#-MWYnHwiCDJ6skV8ACHI:-MWhJJEL16eCRBaWHVOs:b-83sjo4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e1d7ea5dfa0931e73c259445ded719ca4898b5b/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt#L126)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

That would've been awesome, but `fetchType` needs to be `var` because it might be received again in the middle of the loop.

Do you have any ideas on how to restructure this?
</blockquote></details>

Nice.


<!-- Sent from Reviewable.io -->

2021-03-26 06:59 UTC, axti approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2610)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-26 12:13 UTC, merged