Split `KeyStatusListener` in a UI-side class and a service-side class
mullvad/mullvadvpn-app pull request #2621
Opened 2021-03-26 12:43 UTC by jvff

This PR continues the work on splitting the app so that the service runs in a separate process. This PR focuses on the `KeyStatusListener` class. This class is responsible for sending verify key and (re)generate key commands while also listening for the status of the WireGuard key, i.e., if it's available or not, or if there was any error with the key generation.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header. **Internal refactor, no user visible changes.**
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-03-26 13:45 UTC, pinkisemils requested changes
> Reviewed 11 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2621)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/KeyStatusListener.kt, line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2621#-MWijzfF1UtqDQmMNmmS:-MWijzfF1UtqDQmMNmmT:bf6dupr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0bd8e7fef108129bab155376d672b02f80d9b551/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/KeyStatusListener.kt#L61)):*
> ```Kotlin
> 
>     private fun verifyKey() = GlobalScope.launch(Dispatchers.Default) {
>         val verified = daemon.await().verifyWireguardKey()
> ```

Should this call the IPC even if the key is not present?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt, line 326 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2621#-MWilDWU02lSNVKHOvze:-MWilDWU02lSNVKHOvzf:b92yy3q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0bd8e7fef108129bab155376d672b02f80d9b551/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt#L326)):*
> ```Kotlin
>         keyStatus = null
> 
>         actionCompletion = CompletableDeferred()
> ```

Shouldn't this be synchronized too? I do wonder at what point `actionCompletion?.await()` would top waiting if it was overwritten. 


<!-- Sent from Reviewable.io -->

2021-03-26 13:48 UTC, axti reviewed
> Reviewed 8 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2621)* status: all files reviewed, 3 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/KeyStatusListener.kt, line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2621#-MWikv3x9b62xNPhRZKV:-MWikv3x9b62xNPhRZKW:b-63wjh8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0bd8e7fef108129bab155376d672b02f80d9b551/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/KeyStatusListener.kt#L42)):*
> ```
>     fun onDestroy() {
>         daemon.unregisterListener(this)
>     }
> ```
Do we need to unregister handler from `endpoint.dispatcher`?


<!-- Sent from Reviewable.io -->

2021-03-26 15:51 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2621)* status: 8 of 16 files reviewed, 3 unresolved discussions (waiting on @axti and @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/KeyStatusListener.kt, line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2621#-MWikv3x9b62xNPhRZKV:-MWiuR8h-1OjVNMrn4j-:bofpi5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0bd8e7fef108129bab155376d672b02f80d9b551/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/KeyStatusListener.kt#L42)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>     fun onDestroy() {
>         daemon.unregisterListener(this)
>     }
> ```
Do we need to unregister handler from `endpoint.dispatcher`?
</blockquote></details>

We don't need to because `onDestroy` is called by `endpoint` itself, and `ServiceEndpoint.onDestroy` unregisters all of the dispatcher's listeners.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/KeyStatusListener.kt, line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2621#-MWijzfF1UtqDQmMNmmS:-MWiubvu0oaA6Fvi6b58:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0bd8e7fef108129bab155376d672b02f80d9b551/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/KeyStatusListener.kt#L61)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Should this call the IPC even if the key is not present?
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt, line 326 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2621#-MWilDWU02lSNVKHOvze:-MWiwXrG0kIyJHNUb6Ov:bbuqhpe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0bd8e7fef108129bab155376d672b02f80d9b551/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt#L326)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Shouldn't this be synchronized too? I do wonder at what point `actionCompletion?.await()` would top waiting if it was overwritten. 
</blockquote></details>

It doesn't need to be because the button actions run as coroutines in the UI thread.


<!-- Sent from Reviewable.io -->

2021-03-27 10:53 UTC, pinkisemils approved these changes
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2621)* status: all files reviewed, 1 unresolved discussion (waiting on @axti)



<!-- Sent from Reviewable.io -->

2021-03-29 14:04 UTC, axti commented
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt, line 341 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2621#-MWyIAXT8FO-EWcKqTAN:-MWyIAXT8FO-EWcKqTAO:b8izn5a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc806d8672b918aa49a3e872c474a1c115ec5346/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt#L341)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         jobTracker.newUiJob("resetReconnectionExpected") {
>             delay(20_000)
>             if (reconnectionExpected) {
>                 reconnectionExpected = false
>             }
>         }
> ```
</details>

Why do we need to delay this job?


<!-- Sent from Reviewable.io -->

2021-03-29 14:11 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2621)* status: all files reviewed, 2 unresolved discussions (waiting on @axti)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt, line 341 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2621#-MWyIAXT8FO-EWcKqTAN:-MWyInns-w7X7rL6FiuZ:b-vao7ii) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc806d8672b918aa49a3e872c474a1c115ec5346/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt#L341)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>         jobTracker.newUiJob("resetReconnectionExpected") {
>             delay(20_000)
>             if (reconnectionExpected) {
>                 reconnectionExpected = false
>             }
>         }
> ```
Why do we need to delay this job?
</blockquote></details>

Oh this is actually a timeout. What happens when we change the key is that if the tunnel was connected, it will reconnect. During the reconnection, it will show a UI message saying that it's waiting for the reconnection. However, if the tunnel gets locked up or takes too long to reconnect, then this task will timeout (after the 20 seconds) and reset the UI state so that it's back to normal.

The normal path is that this job is created and cancelled once the tunnel reconnects (i.e., when a new expected tunnel state is received).


<!-- Sent from Reviewable.io -->

2021-03-29 14:18 UTC, axti approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2621)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-29 14:47 UTC, merged