Add CI job for checking translations
mullvad/mullvadvpn-app pull request #2624
Opened 2021-03-27 16:08 UTC by jvff

The process to handle adding translations to the app (desktop and Android) became more complex due to the requirement of keeping gettext files and Android resources synchronized. This PR aims to help with that problem by creating a new CI workflow that will fail in some situations where the translations aren't properly synchronized. More specifically, the workflow will fail in the following scenarios:

- adding a new message to the desktop GUI but not including that message in the template file (`messages.pot`)
- adding a new Android string resource that and either:
  - not adding the translations extracted from the desktop GUI locales for that message
  - not adding the message to the template file
- changing a message in the desktop GUI and not updating the template file or not updating the respective Android translations
- changing a string resource in the Android app and not updating its translations or its entry in the template file
- removing a message in the desktop GUI but not updating the template file or not updating the respective Android translations
- removing a string resource in the Android app and not removing its respective translations or its respective entry in the template file

If this job fails, the fix is to update the translations by running first `npm run update-translations` in the `gui` directory and then running the Android translation converter tool with `cargo run` in the `android/translations-converter` directory.

As part of the PR, the translations converter tool was updated to become more deterministic. The entries appended to the template file are now sorted so that they are always added in the same order. Also, the template file and the Android resources were updated.

A small bug in the tool was also fixed, where the single quote `'` was being incorrectly escaped in strings appended to the template file. The fix was to manually escape only the double quotes `"` instead of relying on `fmt::Debug` to do the escaping for us.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header. **Internal tooling changes, no chaneglog entry necessary.**
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-03-28 14:10 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2624)* status: 0 of 23 files reviewed, all discussions resolved

___
*[.github/workflows/daemon.yml, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2624#-MWpCEb6AdTIy6WgMP03:-MWpCEb72HV-OuLS693Q:b-ro7lx1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a4d0a1febd93c772f40a63ea3cf2256ab67bf94/.github/workflows/daemon.yml#L11)):*
> ```YAML
>             - .github/workflows/ios.yml
>             - .github/workflows/rustfmt.yml
>             - .github/workflows/translations.yml
> ```

FYI: The `daemon` workflow was being triggered to much, so I added some more paths for it to ignore.


<!-- Sent from Reviewable.io -->

2021-03-28 19:49 UTC, raksooo requested changes
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2624)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[.github/workflows/translations.yml, line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2624#-MWuNQdk2-Lbyhknpeoi:-MWuNQdk2-Lbyhknpeoj:b-ppuwnq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a4d0a1febd93c772f40a63ea3cf2256ab67bf94/.github/workflows/translations.yml#L9)):*
> ```YAML
>             - android/translations-converter/**
>             - android/src/**/plurals.xml
>             - android/src/**/strings.xml
> ```

Are strings on Android manually added to `plurals.xml` or `strings.xml`? Or are these generated?
___
*[.github/workflows/translations.yml, line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2624#-MWuIYhs9ei9LYUaxupg:-MWuIYhs9ei9LYUaxuph:bqtm3ff) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a4d0a1febd93c772f40a63ea3cf2256ab67bf94/.github/workflows/translations.yml#L50)):*
> ```YAML
>               run: |
>                 git diff
>                 ! git status -s | grep .
> ```

Does `grep .` make any difference here? Shouldn't just `! git status -s` work?


<!-- Sent from Reviewable.io -->

2021-03-29 12:03 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2624)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[.github/workflows/translations.yml, line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2624#-MWuNQdk2-Lbyhknpeoi:-MWxq0LN4alFpM9CGLl3:b-3txcrk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a4d0a1febd93c772f40a63ea3cf2256ab67bf94/.github/workflows/translations.yml#L9)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Are strings on Android manually added to `plurals.xml` or `strings.xml`? Or are these generated?
</blockquote></details>

Strings are manually added to `android/src/*/res/values/{strings,plurals}.xml`, but the translations that are in `android-src/*/res/values-<LOCALE>/{strings,plurals}.xml` are automatically generated by the tool.

I added both to the trigger since I want to run if a string is manually added and/or if the translations change.
___
*[.github/workflows/translations.yml, line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2624#-MWuIYhs9ei9LYUaxupg:-MWxqh9eCG3sWASQv8pV:b274ypa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a4d0a1febd93c772f40a63ea3cf2256ab67bf94/.github/workflows/translations.yml#L50)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Does `grep .` make any difference here? Shouldn't just `! git status -s` work?
</blockquote></details>

Unfortunately, `git status -s` doesn't return an error in the cases we need (AFAICT, it never returns an error unless the repo meta-data is corrupt I think). So I use `grep .` to get the error status.

What the command really does is `git status -s | ! grep .` but that's invalid syntax :laughing: 


<!-- Sent from Reviewable.io -->

2021-03-29 13:15 UTC, raksooo approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2624#-:-MWy6sbA516712tP8uHg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[.github/workflows/translations.yml, line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2624#-MWuIYhs9ei9LYUaxupg:-MWy6pPm-g_fXiHe2ptK:b-cc7ba7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a4d0a1febd93c772f40a63ea3cf2256ab67bf94/.github/workflows/translations.yml#L50)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Unfortunately, `git status -s` doesn't return an error in the cases we need (AFAICT, it never returns an error unless the repo meta-data is corrupt I think). So I use `grep .` to get the error status.

What the command really does is `git status -s | ! grep .` but that's invalid syntax :laughing: 
</blockquote></details>

Okay :+1:


<!-- Sent from Reviewable.io -->

2021-03-29 13:19 UTC, merged