Split `AccountCache` into UI-side and service-side classes
mullvad/mullvadvpn-app pull request #2628
Opened 2021-03-29 17:49 UTC by jvff

This PR continues the work to split the Android app into two processes, so that the service can run in a separate process. This PR focuses on the `AccountCache` class. The class is responsible for handling the account token, the account history and fetching the account expiration.

After this PR, the service side `AccountCache` will also handle the login procedure logic. It can now receive `Login`, `Logout` and `CreateAccount` requests and will respond by sending a `LoginStatus` event that contains a tuple `(accountToken, optionalExpiry, isNewFlag)` and also has a helper property `isExpired` calculated from the `optionalExpiry`.

For the account history, it's possible to send a `RemoveAccountFromHistory` request in order to remove an account token from the history list. Every change to the account history sends an `AccountHistory` event.

The account expiry can be requested to be fetched either by a `FetchAccountExpiry` request or by a `InvalidateAccountExpiry` request. The difference is that the latter has a extra parameter that represents the account expiry that should be invalidated. What that means is that the fetch will retry while the fetch result is the same invalid expiry. This is used after a voucher code is redeemed, for example.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header. **Internal refactor, no user visible changes yet.**
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-03-30 09:43 UTC, axti requested changes
> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628)* status: all files reviewed, 8 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1QUmuDz24PPjL2JMe:-MX1QUmuDz24PPjL2JMf:b-lcv1fs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt#L17)):*
> ```
> ArrayList
> ```
Does it need to be `ArrayList`? Maybe it is enough just `List`?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt, line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1RB9W2eX3s-ODx7rJ:-MX1RB9W2eX3s-ODx7rK:bfoovm7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt#L2)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.ipc
> ```

How do you sort and/or group requests inside? Which strategy you use?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1Qi1uEGDeSdqgpnRT:-MX1Qi1uEGDeSdqgpnRU:b-acx6c9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt#L10)):*
> ```
> messageId = 2
> ```
How do we control messageIds unique?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt, line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1Qyj86jacMzrkwyQR:-MX1Qyj86jacMzrkwyQS:bnv7fis) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt#L20)):*
> ```
> val expiry: DateTime
> ```
Can it be a `string` that we will parse later on?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/LoginStatus.kt, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1RhL20BDRII16Htlq:-MX1RhL20BDRII16Htlr:b-ihx3wz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/model/LoginStatus.kt#L11)):*
> ```
> val isNew: Boolean
> ```
What does it mean new login status?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt, line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1SctKA4gtgS-X51hV:-MX1SctKA4gtgS-X51hW:bi5i2dk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt#L32)):*
> ```
> class CreateAccount() : Command()
> ```
Could it be an `object CreateAccount: Command()`?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt, line 34 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1SUVf8lJhiQI3Yfnx:-MX1SUVf8lJhiQI3Yfny:b-7lxrhp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt#L34)):*
> ```
> class Logout() : Command()
> ```
Could this be an `object Logout: Command()` ?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt, line 192 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1VNpGE3PsblK0-n9Z:-MX1VNpGE3PsblK0-n9_:b-udtzph) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L192)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>         val fragment = if (status == null) {
>             return
>         } else if (status.isNew) {
>             WelcomeFragment()
>         } else if (status.isExpired) {
>             OutOfTimeFragment()
>         } else {
>             ConnectFragment()
>         }
> ```
</details>

Can we replace it with `when`?


<!-- Sent from Reviewable.io -->

2021-03-30 15:28 UTC, pinkisemils approved these changes
> Reviewed 16 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628)* status: all files reviewed, 8 unresolved discussions (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-03-30 16:34 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628)* status: 14 of 22 files reviewed, 8 unresolved discussions (waiting on @axti and @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt, line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1QUmuDz24PPjL2JMe:-MX2Y2cL1rFC0XDi143w:bjiit9d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt#L17)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> ArrayList
> ```
Does it need to be `ArrayList`? Maybe it is enough just `List`?
</blockquote></details>

Done. Yeah, it didn't need to be an `ArrayList` :D
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt, line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1RB9W2eX3s-ODx7rJ:-MX2Y4dlAB2vz45ON-86:bc64dpn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt#L2)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

How do you sort and/or group requests inside? Which strategy you use?
</blockquote></details>

I just sorted them alphabetically :sweat_smile: 
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1Qi1uEGDeSdqgpnRT:-MX2Y9u14I1BlbddlUqL:bkoh7xx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt#L10)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> messageId = 2
> ```
How do we control messageIds unique?
</blockquote></details>

Good point. I tried to refactor it a bit. There are now redundant `EventMessage` and `RequestMessage` classes, but from what I understood they can be safely removed when Kotlin language version 1.5 is out :tada:
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt, line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1Qyj86jacMzrkwyQR:-MX2b2o67VASKaPBMqXu:bmgf0rf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt#L20)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> val expiry: DateTime
> ```
Can it be a `string` that we will parse later on?
</blockquote></details>

I don't think that's a good idea, the data to be sent was already a `DateTime` object, and adding a step to make it a string to then parse again seems to be more complicated :/
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/LoginStatus.kt, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1RhL20BDRII16Htlq:-MX1xipVBXIj_EXVTdl-:b-rlvifx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/model/LoginStatus.kt#L11)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> val isNew: Boolean
> ```
What does it mean new login status?
</blockquote></details>

It means that the account was created when logging in. The name isn't very clear. Maybe it should be `isAccountNew`?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt, line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1SctKA4gtgS-X51hV:-MX2qDch7nG3yr9ZaBH1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt#L32)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> class CreateAccount() : Command()
> ```
Could it be an `object CreateAccount: Command()`?
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt, line 34 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1SUVf8lJhiQI3Yfnx:-MX2qE9nADWgTS1UoOQf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt#L34)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> class Logout() : Command()
> ```
Could this be an `object Logout: Command()` ?
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt, line 192 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1VNpGE3PsblK0-n9Z:-MX2yP_SC0xUkv49Tjw-:bjws3ei) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt#L192)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>         val fragment = if (status == null) {
>             return
>         } else if (status.isNew) {
>             WelcomeFragment()
>         } else if (status.isExpired) {
>             OutOfTimeFragment()
>         } else {
>             ConnectFragment()
>         }
> ```
Can we replace it with `when`?
</blockquote></details>

Done. Much better, thanks!


<!-- Sent from Reviewable.io -->

2021-03-31 07:41 UTC, axti approved these changes
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/LoginStatus.kt, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1RhL20BDRII16Htlq:-MX6D2nACAvi-TI26Mhe:b5upqf7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/model/LoginStatus.kt#L11)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

It means that the account was created when logging in. The name isn't very clear. Maybe it should be `isAccountNew`?
</blockquote></details>

Could be, but why it is important to get info is it new account or not?


<!-- Sent from Reviewable.io -->

2021-03-31 08:22 UTC, axti approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-03-31 08:22 UTC, axti approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-:-MX6N5Yz1rZ_uQLoJPqm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-03-31 10:50 UTC, pinkisemils approved these changes
> Reviewed 1 of 19 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/model/LoginStatus.kt, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628#-MX1RhL20BDRII16Htlq:-MX6tdnY8-DOdHtzjLy9:b8y0z3e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9135e082390f2589aec34ad69f4ede61a667561f/android/src/main/kotlin/net/mullvad/mullvadvpn/model/LoginStatus.kt#L11)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Could be, but why it is important to get info is it new account or not?
</blockquote></details>

To show a different screen to the user - if the account was generated in the app, the user should first top up their account so that they can actually use the app.


<!-- Sent from Reviewable.io -->

2021-03-31 13:24 UTC, axti approved these changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2628)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-31 15:33 UTC, merged