Split `SplitTunneling` into UI-side class and service-side class
mullvad/mullvadvpn-app pull request #2634
Opened 2021-03-31 20:48 UTC by jvff

This PR continues the work to split the Android app to run in two separate processes, by focusing on the `SplitTunneling` class. Now there are two `SplitTunneling` classes, one on the UI side and one on the service side.

The two classes communicate through the IPC channel. The UI can send requests to exclude an app from the tunnel, include an app in the tunnel, persist the split tunneling configuration to disk, and to enable or disable split tunneling. The service side class only sends split tunneling events which contain the list of excluded apps, or `null` if split tunneling is disabled.

The PR also contains a fix to an issue that becomes apparent with the changes included in this PR. There was previously the possibility of a race condition that ended up starting the daemon again while quitting. The fix was to not restart the daemon if the service was already in the `Stopped` state.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header. **Internal refactor, no changelog entry necessary.**
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634)

2021-04-01 07:56 UTC, axti requested changes
> Reviewed 11 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634)* status: 11 of 14 files reviewed, 7 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt, line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-MXBH7dFAkSYPuJilL6z:-MXBH7dFAkSYPuJilL7-:bdenrh9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da7227b29d94704f9ee1e6b69c8cad332b025f30/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt#L16)):*
> ```
> val packageName: String?
> ```
Why this could be nullable?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-MXBHBzRC9-rVaHSsrlU:-MXBHBzRC9-rVaHSsrlV:b-od84lq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da7227b29d94704f9ee1e6b69c8cad332b025f30/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt#L22)):*
> ```
> val packageName: String?
> ```
Same question as above.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt, line 114 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-MXBQY9o9__sn3b7AWLE:-MXBQY9o9__sn3b7AWLF:b-c8hy8c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da7227b29d94704f9ee1e6b69c8cad332b025f30/android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt#L114)):*
> ```Kotlin
> 
>         notificationManager =
>             ForegroundNotificationManager(this, serviceNotifier, keyguardManager).apply {
> ```

Maybe it will be better to have fix in separate PR?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SplitTunneling.kt, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-MXBIPqMBaNYZogUPNXW:-MXBIPqMBaNYZogUPNXX:b-yqpk7p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da7227b29d94704f9ee1e6b69c8cad332b025f30/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SplitTunneling.kt#L15)):*
> ```
> class SplitTunneling(context: Context, endpoint: ServiceEndpoint) {
> ```
My suggestion will be to not use `Context` but use kind of storage interface that will provide persistent values. So, it will be easy to maintain and migrate if needed without any changes in the original class. 
Please divide responsibilities and don't combine them in one class.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/CustomDns.kt, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-MXBJXrCB7hTrl_jm6mD:-MXBJXrCB7hTrl_jm6mE:b-waa5ua) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da7227b29d94704f9ee1e6b69c8cad332b025f30/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/CustomDns.kt#L7)):*
> ```Kotlin
> import net.mullvad.talpid.util.EventNotifier
> 
> class CustomDns(val connection: Messenger, val settingsListener: SettingsListener) {
> ```

I think this is not related to this PR and guess it is here by mistake?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SplitTunneling.kt, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-MXBKmpBCUvYqECfE_sV:-MXBKmpBCUvYqECfE_sW:b902jnf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da7227b29d94704f9ee1e6b69c8cad332b025f30/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SplitTunneling.kt#L22)):*
> ```
> HashSet(event.excludedApps)
> ```
you can do it in kotlin style like this: `event.excludedApps.toSet()`
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SplitTunneling.kt, line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-MXBP6fz35zOonoYLhfp:-MXBP6fz35zOonoYLhfq:b-7mfxlo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da7227b29d94704f9ee1e6b69c8cad332b025f30/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SplitTunneling.kt#L29)):*
> ```
> fun isAppExcluded(appPackageName: String) = excludedApps.contains(appPackageName)
> ```
Please specify return type explicitly.
How we can clean this list if app is removed?


<!-- Sent from Reviewable.io -->

2021-04-01 09:01 UTC, pinkisemils reviewed
> Reviewed 11 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634)* status: 13 of 14 files reviewed, 7 unresolved discussions (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-04-01 10:30 UTC, pinkisemils approved these changes
> Reviewed 2 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634)* status: all files reviewed, 7 unresolved discussions (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-04-01 22:51 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634)* status: 8 of 14 files reviewed, 7 unresolved discussions (waiting on @axti and @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt, line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-MXBH7dFAkSYPuJilL6z:-MXEAXhR4O-lC5gJgpsW:be7w4a8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da7227b29d94704f9ee1e6b69c8cad332b025f30/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt#L16)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> val packageName: String?
> ```
Why this could be nullable?
</blockquote></details>

Done. Yeah, it makes no sense for these two parameters to be `null`.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-MXBHBzRC9-rVaHSsrlU:-MXEAb9D8X0isMO9htGC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da7227b29d94704f9ee1e6b69c8cad332b025f30/android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt#L22)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> val packageName: String?
> ```
Same question as above.
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt, line 114 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-MXBQY9o9__sn3b7AWLE:-MXE_FRJ7Yutimn5OPE6:b-s34kva) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da7227b29d94704f9ee1e6b69c8cad332b025f30/android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt#L114)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Maybe it will be better to have fix in separate PR?
</blockquote></details>

Done. https://reviewable.io/reviews/mullvad/mullvadvpn-app/2638
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SplitTunneling.kt, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-MXBIPqMBaNYZogUPNXW:-MXEUXc99Zv7LYTd-e0h:b-k35yr2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da7227b29d94704f9ee1e6b69c8cad332b025f30/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SplitTunneling.kt#L15)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> class SplitTunneling(context: Context, endpoint: ServiceEndpoint) {
> ```
My suggestion will be to not use `Context` but use kind of storage interface that will provide persistent values. So, it will be easy to maintain and migrate if needed without any changes in the original class. 
Please divide responsibilities and don't combine them in one class.
</blockquote></details>

Done. I didn't know exactly where to put it, so I created a new `persistence` package.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/CustomDns.kt, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-MXBJXrCB7hTrl_jm6mD:-MXEDRgz2vuq7ga6Jdnw:b-c7h5gm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da7227b29d94704f9ee1e6b69c8cad332b025f30/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/CustomDns.kt#L7)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

I think this is not related to this PR and guess it is here by mistake?
</blockquote></details>

Done. Yep, shouldn't be in this PR :sweat_smile: 
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SplitTunneling.kt, line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-MXBKmpBCUvYqECfE_sV:-MXEHcRk6_CIhuEjHSDs:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da7227b29d94704f9ee1e6b69c8cad332b025f30/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SplitTunneling.kt#L22)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> HashSet(event.excludedApps)
> ```
you can do it in kotlin style like this: `event.excludedApps.toSet()`
</blockquote></details>

Done.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SplitTunneling.kt, line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-MXBP6fz35zOonoYLhfp:-MXEHnRZ6_7W3IoUZiFn:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da7227b29d94704f9ee1e6b69c8cad332b025f30/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SplitTunneling.kt#L29)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> fun isAppExcluded(appPackageName: String) = excludedApps.contains(appPackageName)
> ```
Please specify return type explicitly.
How we can clean this list if app is removed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-06 07:48 UTC, axti approved these changes
Looks good for me. But you have to fix test, because a small change in ViewModel class, that is why build failed.

> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-:-MXa8PHY4DdQwpd3Thbf:b-w9fpw8)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-07 12:47 UTC, jvff reviewed
> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634)* status: 13 of 21 files reviewed, all discussions resolved (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-04-07 18:08 UTC, axti approved these changes
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634)* status: 19 of 21 files reviewed, all discussions resolved (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-04-07 18:08 UTC, axti approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634)* status: 19 of 21 files reviewed, all discussions resolved (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-04-07 20:20 UTC, jvff reviewed
> Reviewed 2 of 14 files at r1, 5 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634)* status: 19 of 21 files reviewed, all discussions resolved (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-04-07 20:20 UTC, jvff reviewed
> Reviewed 1 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634)* status: 19 of 21 files reviewed, all discussions resolved (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-04-07 20:20 UTC, jvff reviewed
> Reviewed 5 of 14 files at r1, 6 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634)* status: 19 of 21 files reviewed, all discussions resolved (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-04-07 20:21 UTC, jvff reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634#-:-MXhziDu5mPWrUbS-tFi:bnfp4nl)* status: 19 of 21 files reviewed, all discussions resolved (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-04-08 06:25 UTC, axti approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634)* status: 19 of 21 files reviewed, all discussions resolved (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-04-08 11:32 UTC, axti approved these changes
> Reviewed 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2634)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-08 11:36 UTC, merged