Secure filtering of forwarded packets on Linux
mullvad/mullvadvpn-app pull request #2658
Opened 2021-04-12 17:10 UTC by dlon

Previously, the app only filtered packets at the output and input hooks in netfilter, ignoring the forward hook. This meant that forwarded traffic was unfiltered. So a machine/router running Mullvad was able to pass on traffic without any restrictions. For example, if "Always require VPN" was enabled, it would still forward packets from other hosts.

Perhaps more importantly, this also had consequences for virtual networks/bridges, such as when Mullvad was running on a host with virtual machines. For example, guests were able to reach the internet even though the daemon was in a blocking state. In the connected state, it was also able to resolve hostnames using any resolver. Moreover, the local network (except the host machine) could be reached from a guest, even if local network sharing was disabled.

The new chain lets through traffic under essentially the same [conditions](https://github.com/mullvad/mullvadvpn-app/blob/master/docs/security.md) as the output and input chains, e.g. allowing LAN (if enabled), NDP, DHCP, DNS requests for the selected servers, tunnel traffic, etc., when connected.

2021-04-13 13:30 UTC, pinkisemils reviewed
Shouldn't ` docs/security.md` also be updated? Do these rules allow for traffic to flow to the host if _allow lan_ is enabled in a blocked state? Have you tested this with Canonical's multipass, docker and libvirt/kvm/qemu?

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2658#-:-MYA8PpE9mEK5gHrPaF5:b-sn6st9)* status: 1 of 2 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-13 13:31 UTC, pinkisemils approved these changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2658)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-13 14:06 UTC, faern requested changes
Yes. `security.md` indeed needs some bump saying forwarded traffic is handled the same as outgoing traffic. Because I guess it is? Any deviations from that?

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2658#-:-MYAXtes2IMSFVy5m27i:bbzb809)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[CHANGELOG.md, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2658#-MYAY5ci3CRyqq1pBi_-:-MYAY5cjEfWKXSkhiinA:bjv3st5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e15d89e4825a95a6d2d00afff9acb60e8c23fc2f/CHANGELOG.md#L66)):*
> ```Markdown
> #### Linux
> - Drop packets being forwarded unless they go inside the tunnel or are explicitly approved by
>   the firewall rules.
> ```

"explicitly approved by the firewall rules" is not saying very much. The rules here should be that forwarded traffic is subject to the same filtering/security as outgoing traffic, right? So probably more informative to say that.


<!-- Sent from Reviewable.io -->

2021-04-14 10:23 UTC, dlon reviewed
Done. 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2658#-:-MYEpr5TEABOk3yA0x7c:bs7wumx)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[CHANGELOG.md, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2658#-MYAY5ci3CRyqq1pBi_-:-MYEtBUE-Da-8qMaDt-Z:b6x1uns) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e15d89e4825a95a6d2d00afff9acb60e8c23fc2f/CHANGELOG.md#L66)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

"explicitly approved by the firewall rules" is not saying very much. The rules here should be that forwarded traffic is subject to the same filtering/security as outgoing traffic, right? So probably more informative to say that.
</blockquote></details>

Done. It must actually permit most of what the input chain does as well. Eg the forward chain must allow inbound DNS traffic, or the original sender won't see the response.


<!-- Sent from Reviewable.io -->

2021-04-14 14:46 UTC, pinkisemils approved these changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2658)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2021-04-15 09:34 UTC, faern requested changes
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2658)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[CHANGELOG.md, line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2658#-MYAY5ci3CRyqq1pBi_-:-MYJs7Ob9xrN-TCoDUlf:b-6rqwic) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e15d89e4825a95a6d2d00afff9acb60e8c23fc2f/CHANGELOG.md#L66)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. It must actually permit most of what the input chain does as well. Eg the forward chain must allow inbound DNS traffic, or the original sender won't see the response.
</blockquote></details>

Ok! Yeah this entry is better IMO :+1:
___
*[docs/security.md, line 96 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2658#-MYJsHv_E9CwmrSogsWc:-MYJsHv_E9CwmrSogsWd:b-knfbzy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7aadb4d9540d17c0a50652d1a30a1584ca006a16/docs/security.md#L96)):*
> ```Markdown
> 
> On Linux, any situation that permits incoming or outgoing traffic also allows that traffic to be
> forwarded.
> ```

I think we should also say that all other forward traffic is being rejected. To not be vague about what happens to the traffic *not* mentioned in the existing sentence.


<!-- Sent from Reviewable.io -->

2021-04-15 11:38 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2658)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[docs/security.md, line 96 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2658#-MYJsHv_E9CwmrSogsWc:-MYKJis4586Yl15N-VX_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7aadb4d9540d17c0a50652d1a30a1584ca006a16/docs/security.md#L96)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I think we should also say that all other forward traffic is being rejected. To not be vague about what happens to the traffic *not* mentioned in the existing sentence.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-15 13:25 UTC, faern approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2658)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-15 13:28 UTC, pinkisemils approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2658)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-16 15:44 UTC, merged