Get installed apps windows
mullvad/mullvadvpn-app pull request #2665
Opened 2021-04-14 10:30 UTC by raksooo

This PR is the first in a series of PRs implementing different parts of the split tunneling UI on Windows. The changes include:
* Parse PE format to retrieve list of imported DLLs of an exe-file
* Read installed applications from the start menu and filter those based on imported DLLs
* Add support for arrays in `guiSettings`
* Add support to `guiSettings` for persisting list of manually added applications.

Information about the PE format can be found here:
https://docs.microsoft.com/en-us/windows/win32/debug/pe-format

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-04-14 20:58 UTC, mvd-ows requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665)* status: 1 of 5 files reviewed, 13 unresolved discussions (waiting on @raksooo)

___
*[gui/src/main/windows-pe-parser.ts, line 112 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYGqzf5057ny_TgiGfv:-MYGqzf5057ny_TgiGfw:bt7tzv5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-pe-parser.ts#L112)):*
> ```XML
>   rva: number,
>   numberOfSections: number,
>   firstSectionAddress: number,
> ```

`Address`is ambiguous in this context. Consider renaming to `firstSectionHeaderOffset` instead.
___
*[gui/src/main/windows-pe-parser.ts, line 121 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYGsKE-6w4WAPVhIMA2:-MYGsKE-6w4WAPVhIMA3:b-vomrq7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-pe-parser.ts#L121)):*
> ```XML
>       IMAGE_SECTION_HEADER,
>     );
>     const sectionVirtualAddress = sectionHeader.get('VirtualAddress').value<number>();
> ```

The field name in the specification is wrong, and kept for legacy reasons. Consider renaming the variable to clarify that it refers to an RVA.
___
*[gui/src/main/windows-pe-parser.ts, line 122 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYGuFxD9AYiML6UvA6Y:-MYGuFxD9AYiML6UvA6Z:btg4v2z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-pe-parser.ts#L122)):*
> ```XML
>     );
>     const sectionVirtualAddress = sectionHeader.get('VirtualAddress').value<number>();
>     const sectionSize = sectionHeader.get('SizeOfRawData').value<number>();
> ```

There's a special case where the physical section size is 0 bytes long. This is used for e.g. uninitialized variables, so they don't waste space on disk, but the section is inflated when the image is mapped.

You should reject these section headers because an RVA that falls inside the section can't be mapped to disk.
___
*[gui/src/main/windows-pe-parser.ts, line 124 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYGwISo3OqdQKdghSzy:-MYGwISo3OqdQKdghSzz:bie04p1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-pe-parser.ts#L124)):*
> ```XML
>     const sectionSize = sectionHeader.get('SizeOfRawData').value<number>();
> 
>     if (rva >= sectionVirtualAddress && rva <= sectionVirtualAddress + sectionSize) {
> ```

There's an off-by-one issue in the second comparison. Consider that a section of length one will have exactly one valid address.
___
*[gui/src/main/windows-pe-parser.ts, line 130 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYGx3qk2kUC07k6Bwfw:-MYGx3qk2kUC07k6Bwfx:b43vn2j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-pe-parser.ts#L130)):*
> ```XML
>   }
> 
>   throw new Error('Failed to calculate RVA');
> ```

`Failed to map RVA to offset`, or something more specific along those lines.
___
*[gui/src/main/windows-split-tunneling.ts, line 224 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYGyegH9UNOz-MJgufe:-MYGyegH9UNOz-MJguff:b-5wyji1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-split-tunneling.ts#L224)):*
> ```XML
>   const imports = await getExeImports(fileHandle, path);
>   await fileHandle.close();
>   return imports.map((name) => name.toLowerCase()).includes(dllName.toLowerCase());
> ```

Is the `includes` method a substring search? If so, this is maybe not what we want.
___
*[gui/src/main/windows-split-tunneling.ts, line 232 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYH0WG45sVeBULV2Dea:-MYH0WG45sVeBULV2Deb:b-h0z8o9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-split-tunneling.ts#L232)):*
> ```XML
>     const optionalHeader = ntHeader.get<StructValue<ImageOptionalHeaderUnion>>('OptionalHeader');
> 
>     const importSectionRva = optionalHeader
> ```

There's no such concept as an "import section". It could be taken to mean the section the import table resides in, which is not at all what is being meant here.

A more accurate name would be `importTableRva`.
___
*[gui/src/main/windows-split-tunneling.ts, line 247 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYH1M-W2_6SwsgfzS-i:-MYH1M-W2_6SwsgfzS-j:b-53auu9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-split-tunneling.ts#L247)):*
> ```XML
>       .value<number>();
> 
>     const importSectionOffset = await rvaToOffset(
> ```

As above, with regards to naming.
___
*[gui/src/main/windows-split-tunneling.ts, line 251 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYH8krR32hS_6Z1bIZc:-MYH8krR32hS_6Z1bIZd:brf4t06) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-split-tunneling.ts#L251)):*
> ```XML
>       importSectionRva,
>       numberOfSections,
>       ntHeader.endOffset,
> ```

The size of this type is not strictly constant. IIRC, you need to compute it using `.FileHeader.SizeOfOptionalHeader` and `.OptionalHeader.NumberOfRvaAndSizes`.

Possibly using `.FileHeader.SizeOfOptionalHeader` will be enough, but that has to be verified.
___
*[gui/src/main/windows-split-tunneling.ts, line 290 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYH2Vh2-ftg8GjxHHOT:-MYH2Vh2-ftg8GjxHHOU:br957qy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-split-tunneling.ts#L290)):*
> ```XML
>   const eMagic = dosHeader.get<PrimitiveValue>('e_magic').value<number>();
>   if (eMagic !== 0x5a4d) {
>     throw new Error('Incorrect PE format');
> ```

Consider "not a PE file" vs "invalid PE file". At this point, no PE specific headers have been evaluated.
___
*[gui/src/main/windows-split-tunneling.ts, line 297 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYH3v0nDOGx76KgKg9k:-MYH3v0nDOGx76KgKg9l:beavrcp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-split-tunneling.ts#L297)):*
> ```XML
>   // Check if this is a 32- or 64-bit exe-file and return the correct datatype.
>   const ntHeader32 = await Value.fromFile(fileHandle, ntHeaderOffset, IMAGE_NT_HEADERS);
>   const magic = ntHeader32
> ```

Before reading `OptionalHeader.Magic`, you need to verify `Signature`.
___
*[gui/src/main/windows-split-tunneling.ts, line 311 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYH5BM45Oe0cewLrUJC:-MYH5BM5A3uFGICA6pje:bff8wlb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-split-tunneling.ts#L311)):*
> ```XML
> async function getImportModuleNames(
>   fileHandle: fs.promises.FileHandle,
>   importSectionOffset: number,
> ```

`importTableOffset`
___
*[gui/src/main/windows-split-tunneling.ts, line 312 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYH5Et79aLVXgZCZ8nt:-MYH5Et79aLVXgZCZ8nu:bn7l0y7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-split-tunneling.ts#L312)):*
> ```XML
>   fileHandle: fs.promises.FileHandle,
>   importSectionOffset: number,
>   firstSectionAddress: number,
> ```

`firstSectionHeaderOffset`?


<!-- Sent from Reviewable.io -->

2021-04-14 20:58 UTC, mvd-ows reviewed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665)* status: 2 of 5 files reviewed, 13 unresolved discussions (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2021-04-14 21:02 UTC, mvd-ows reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665)* status: 2 of 5 files reviewed, 13 unresolved discussions (waiting on @raksooo)

___
*[gui/src/main/windows-split-tunneling.ts, line 232 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYH0WG45sVeBULV2Dea:-MYHAtfJDUXSMCVQMLRW:biupc3l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-split-tunneling.ts#L232)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

There's no such concept as an "import section". It could be taken to mean the section the import table resides in, which is not at all what is being meant here.

A more accurate name would be `importTableRva`.
</blockquote></details>

Yes, contemporary Microsoft linkers produce a section called `.idata`, but that's an implementation detail of those linkers.


<!-- Sent from Reviewable.io -->

2021-04-15 07:27 UTC, pronebird approved these changes
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665)* status: all files reviewed, 13 unresolved discussions (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2021-04-15 07:27 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665)* status: all files reviewed, 13 unresolved discussions (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2021-04-15 09:28 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @mvd-ows)

___
*[gui/src/main/windows-pe-parser.ts, line 122 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYGuFxD9AYiML6UvA6Y:-MYJiihPB0mdQtMQSb5E:b4velfy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-pe-parser.ts#L122)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

There's a special case where the physical section size is 0 bytes long. This is used for e.g. uninitialized variables, so they don't waste space on disk, but the section is inflated when the image is mapped.

You should reject these section headers because an RVA that falls inside the section can't be mapped to disk.
</blockquote></details>

Won't the condition below do this automatically?
___
*[gui/src/main/windows-pe-parser.ts, line 124 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYGwISo3OqdQKdghSzy:-MYJihw8DfxV9MeL7kQm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-pe-parser.ts#L124)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

There's an off-by-one issue in the second comparison. Consider that a section of length one will have exactly one valid address.
</blockquote></details>

Done.
___
*[gui/src/main/windows-pe-parser.ts, line 130 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYGx3qk2kUC07k6Bwfw:-MYJAybK1vPsae8Bf9zc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-pe-parser.ts#L130)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

`Failed to map RVA to offset`, or something more specific along those lines.
</blockquote></details>

Done.
___
*[gui/src/main/windows-split-tunneling.ts, line 224 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYGyegH9UNOz-MJgufe:-MYJB1oqBl4TLMPn2UoA:bqf8o2a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-split-tunneling.ts#L224)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Is the `includes` method a substring search? If so, this is maybe not what we want.
</blockquote></details>

No, `includes` is called on the result of `map` and searches the array for equal strings.
___
*[gui/src/main/windows-split-tunneling.ts, line 251 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYH8krR32hS_6Z1bIZc:-MYJqurT-hJTa2RL6jGW:b-biprqi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-split-tunneling.ts#L251)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

The size of this type is not strictly constant. IIRC, you need to compute it using `.FileHeader.SizeOfOptionalHeader` and `.OptionalHeader.NumberOfRvaAndSizes`.

Possibly using `.FileHeader.SizeOfOptionalHeader` will be enough, but that has to be verified.
</blockquote></details>

I've switched to using `FileHeader.SizeOfOptionalHeader` and it works fine. I haven't verified that it's correct though. Will do this now.
___
*[gui/src/main/windows-split-tunneling.ts, line 297 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYH3v0nDOGx76KgKg9k:-MYJq7jcACBL2x54GvYn:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-split-tunneling.ts#L297)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Before reading `OptionalHeader.Magic`, you need to verify `Signature`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-15 10:17 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @mvd-ows)

___
*[gui/src/main/windows-split-tunneling.ts, line 251 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYH8krR32hS_6Z1bIZc:-MYK10tX2lERIfr9CO2G:b-im9xe0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-split-tunneling.ts#L251)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I've switched to using `FileHeader.SizeOfOptionalHeader` and it works fine. I haven't verified that it's correct though. Will do this now.
</blockquote></details>

For all my installed applications `FileHeader.SizeOfOptionalHeader` matched `OptionalHeader.NumberOfRvaAndSizes * 8 + <rest of optional header>`.


<!-- Sent from Reviewable.io -->

2021-04-15 10:22 UTC, mvd-ows approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/main/windows-pe-parser.ts, line 122 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYGuFxD9AYiML6UvA6Y:-MYJxdXL1L3LCwhvSJK9:bx9u0a0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-pe-parser.ts#L122)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Won't the condition below do this automatically?
</blockquote></details>

Well, it won't reject the section. But the section will be skipped. This is fine.
___
*[gui/src/main/windows-pe-parser.ts, line 115 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYJu_lODSyWIjP6Ot-O:-MYJu_lP3rYGy_90jyJn:b-o2buez) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e7f8dbc4b582775bf6002084fcf89c2ac7b278c1/gui/src/main/windows-pe-parser.ts#L115)):*
> ```XML
> ): Promise<number> {
>   for (let i = 0; i < numberOfSections; i++) {
>     const sectionHeaderAddress = firstSectionHeaderOffset + i * Value.sizeOf(IMAGE_SECTION_HEADER);
> ```

`sectionHeaderAddress` -->`sectionHeaderOffset`?
___
*[gui/src/main/windows-split-tunneling.ts, line 224 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYGyegH9UNOz-MJgufe:-MYJxx0pEduJ5ArPx6yj:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-split-tunneling.ts#L224)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

No, `includes` is called on the result of `map` and searches the array for equal strings.
</blockquote></details>

:+1: 
___
*[gui/src/main/windows-split-tunneling.ts, line 300 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYK0Kwb7yH_QJtCVuNg:-MYK0Kwb7yH_QJtCVuNh:bt4ri1u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e7f8dbc4b582775bf6002084fcf89c2ac7b278c1/gui/src/main/windows-split-tunneling.ts#L300)):*
> ```XML
>   // Check whether or not the file follows the PE format.
>   const dosHeader = await Value.fromFile(fileHandle, 0, DOS_HEADER);
>   const signature = await getPeSignature(fileHandle);
> ```

This seems a little backwards. You're reading the `e_lfanew` field before you've validated the MZ header signature.

What you had before was better. Just, add a check of the `Signature` field right after you've created the `ntHeader32` instance.


<!-- Sent from Reviewable.io -->

2021-04-15 10:41 UTC, mvd-ows approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/main/windows-split-tunneling.ts, line 251 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYH8krR32hS_6Z1bIZc:-MYK28II5Q6z32dflI6g:bpu1ih4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/291f20e9ba4f85a2cee27f8d71993bb50a13d4f8/gui/src/main/windows-split-tunneling.ts#L251)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

For all my installed applications `FileHeader.SizeOfOptionalHeader` matched `OptionalHeader.NumberOfRvaAndSizes * 8 + <rest of optional header>`.
</blockquote></details>

I made a quick test to refresh my memory on this:

- Add 0x10 to `SizeOfOptionalHeader`.
- Shift all section table headers by 0x10 bytes.
- Observe that file is able to load and execute successfully.

`NumberOfRvaAndSizes` is merely an aid when accessing data directory entries.


<!-- Sent from Reviewable.io -->

2021-04-15 10:58 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[gui/src/main/windows-split-tunneling.ts, line 300 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665#-MYK0Kwb7yH_QJtCVuNg:-MYKAKSQCHJkTguQhgqD:b-cwfcrz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e7f8dbc4b582775bf6002084fcf89c2ac7b278c1/gui/src/main/windows-split-tunneling.ts#L300)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This seems a little backwards. You're reading the `e_lfanew` field before you've validated the MZ header signature.

What you had before was better. Just, add a check of the `Signature` field right after you've created the `ntHeader32` instance.
</blockquote></details>

Sorry confused `e_magic` with `OptionalHeader.Magic` and didn't think it through.


<!-- Sent from Reviewable.io -->

2021-04-15 13:09 UTC, mvd-ows approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-15 13:49 UTC, merged