Split `AppVersionInfoCache` in a UI-side class and a service-side class
mullvad/mullvadvpn-app pull request #2668
Opened 2021-04-14 14:56 UTC by jvff

This PR continues the work to make `MullvadVpnService` run in a separate process. This PR focuses on the app version information. The `AppVersionInfoCache` is now split in two classes, one for the UI side and one for the service side. The relationship between them is that the service side will keep track of the version information and then send updates to the UI side class so that the UI can use that information.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header. **Internal refactor, no user visible changes.**
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-04-14 15:37 UTC, axti requested changes
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2668)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AppVersionInfoCache.kt, line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2668#-MYG0BZV3pSONP3kz1_D:-MYG0BZV3pSONP3kz1_E:b2rmlah) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef3ff36c69c5d9b1e598281990f138cb28353b2a/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AppVersionInfoCache.kt#L29)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         context.getSharedPreferences(LEGACY_SHARED_PREFERENCES, Context.MODE_PRIVATE)
>             .edit()
>             .clear()
>             .commit()
> ```
</details>

Hello. Same as before we have a storage for split tunnelling, it will be good to have storage instance instead of context.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AppVersionInfoCache.kt, line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2668#-MYG0h2h2EQylEfmQx9Q:-MYG0h2h2EQylEfmQx9R:b454k5g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef3ff36c69c5d9b1e598281990f138cb28353b2a/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AppVersionInfoCache.kt#L52)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         settingsListener.settingsNotifier.subscribe(this) { maybeSettings ->
>             maybeSettings?.let { settings ->
>                 showBetaReleases = settings.showBetaReleases
>             }
>         }
> ```
</details>

From where it come? I have not seen in out UI any `beta releases`.


<!-- Sent from Reviewable.io -->

2021-04-14 18:33 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2668)* status: all files reviewed, 2 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AppVersionInfoCache.kt, line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2668#-MYG0h2h2EQylEfmQx9Q:-MYGdvt9A6lhdU7HPvGY:b-63tp13) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef3ff36c69c5d9b1e598281990f138cb28353b2a/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AppVersionInfoCache.kt#L52)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>         settingsListener.settingsNotifier.subscribe(this) { maybeSettings ->
>             maybeSettings?.let { settings ->
>                 showBetaReleases = settings.showBetaReleases
>             }
>         }
> ```
From where it come? I have not seen in out UI any `beta releases`.
</blockquote></details>

It's a settings option that's available on the desktop. We don't have any UI to change this yet because we only have beta versions for now :/


<!-- Sent from Reviewable.io -->

2021-04-15 07:19 UTC, axti requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2668)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AppVersionInfoCache.kt, line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2668#-MYG0h2h2EQylEfmQx9Q:-MYJOX5a8SXx7MvnIMPc:bhdgvrm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef3ff36c69c5d9b1e598281990f138cb28353b2a/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AppVersionInfoCache.kt#L52)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

It's a settings option that's available on the desktop. We don't have any UI to change this yet because we only have beta versions for now :/
</blockquote></details>

Yes. So, do we really need it on Android?


<!-- Sent from Reviewable.io -->

2021-04-15 13:06 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2668)* status: all files reviewed, 2 unresolved discussions (waiting on @axti and @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AppVersionInfoCache.kt, line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2668#-MYG0h2h2EQylEfmQx9Q:-MYKchqr96hW7hK8WaPL:bvfijr8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef3ff36c69c5d9b1e598281990f138cb28353b2a/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AppVersionInfoCache.kt#L52)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Yes. So, do we really need it on Android?
</blockquote></details>

I see no reason to remove it. It was already there before this PR, so it's kind of out of the scope of this PR. And it's already working and we'll need it later.


<!-- Sent from Reviewable.io -->

2021-04-15 13:27 UTC, pinkisemils approved these changes
> Reviewed 3 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2668)* status: all files reviewed, 2 unresolved discussions (waiting on @axti and @jvff)



<!-- Sent from Reviewable.io -->

2021-04-15 15:24 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2668)* status: 6 of 12 files reviewed, 1 unresolved discussion (waiting on @axti and @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt, line 29 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2668#-MYL7Rr78cUTKqhBi6nf:-MYL7Rr78cUTKqhBi6ng:bf0rm6p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86cbccff8db77c4aad5667d8ed5c6da98e7a3a85/android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt#L29)):*
> ```Kotlin
>     }
> 
>     scope(named(SERVICE_CONNECTION_SCOPE)) {
> ```

FYI: I think this was due to the rebase, but let me know if I got anything wrong :+1:
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AppVersionInfoCache.kt, line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2668#-MYG0BZV3pSONP3kz1_D:-MYL5eGh4BSYZ6Fu7u7o:b-n6ki2v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef3ff36c69c5d9b1e598281990f138cb28353b2a/android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AppVersionInfoCache.kt#L29)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
>         context.getSharedPreferences(LEGACY_SHARED_PREFERENCES, Context.MODE_PRIVATE)
>             .edit()
>             .clear()
>             .commit()
> ```
Hello. Same as before we have a storage for split tunnelling, it will be good to have storage instance instead of context.
</blockquote></details>

Done. I removed the code since it's been a long time since this migration code was implemented, and the old versions aren't even supported anymore.


<!-- Sent from Reviewable.io -->

2021-04-16 06:36 UTC, axti approved these changes
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2668)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-16 12:45 UTC, merged