Split `AuthTokenCache` into service side and UI side classes
mullvad/mullvadvpn-app pull request #2677
Opened 2021-04-16 18:56 UTC by jvff

This PR continues the work to make `MullvadVpnService` run in a separate process. The focus of this PR is on the `AuthTokenCache` which will now be split into a service-side class and a UI-side class. The UI side class can be used to obtain WWW authentication tokens to access the website. It does this by sending a request to the service side class and waiting for an event with the token. The service side class has a queue to handle one request at a time.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header. **Internal refactor, no user visible changes.**
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-04-19 06:54 UTC, axti approved these changes
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/NotificationWithUrlWithToken.kt, line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677#-MYcqmAB42jyoFF2iJV5:-MYcqmAB42jyoFF2iJV6:bz8n9vf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/420502f2b48a5e18da30b5b950b37ab028d3e9f7/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/NotificationWithUrlWithToken.kt#L16)):*
> ```Kotlin
> 
>     protected val openUrl: suspend () -> Unit = {
>         context.startActivity(Intent(Intent.ACTION_VIEW, buildUrl()))
> ```

Nit: How do you handle cancellations?
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677#-MYctj30Dc55o1LGz7wW:-MYctj30Dc55o1LGz7wX:b-rf0auh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/420502f2b48a5e18da30b5b950b37ab028d3e9f7/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt#L11)):*
> ```
> LinkedList<CompletableDeferred<String>>()
> ```
You can use `BlockingQueue` or `LinkedBlockingDeque` they are thread-safe if you need it.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt, line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677#-MYct-ob0EHbJi3ZKCS8:-MYct-ob0EHbJi3ZKCS9:b-j7km9n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/420502f2b48a5e18da30b5b950b37ab028d3e9f7/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt#L16)):*
> ```
> !fetchQueue.isEmpty()
> ```
Nit: Could be changed to `fetchQueue.isNotEmpty()`


<!-- Sent from Reviewable.io -->

2021-04-19 06:54 UTC, axti approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677)* status: all files reviewed, 1 unresolved discussion (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-04-19 09:33 UTC, pinkisemils requested changes
> Reviewed 15 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677)* status: all files reviewed, 2 unresolved discussions (waiting on @jvff)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677#-MYctj30Dc55o1LGz7wW:-MYdTAsP49RSUjANSOUz:b-rtb30b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/420502f2b48a5e18da30b5b950b37ab028d3e9f7/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt#L11)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> LinkedList<CompletableDeferred<String>>()
> ```
You can use `BlockingQueue` or `LinkedBlockingDeque` they are thread-safe if you need it.
</blockquote></details>

I think the class should still be using locks, but having a granular lock on the queue would be redundant given that the cache has to be threadsafe itself, IMO.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt, line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677#-MYdT6vD-6m93e-WF7rQ:-MYdT6vD-6m93e-WF7rR:bppi5el) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/420502f2b48a5e18da30b5b950b37ab028d3e9f7/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt#L36)):*
> ```Kotlin
> 
>     fun onDestroy() {
>         for (pendingFetch in fetchQueue) {
> ```

Shouldn't this function be synchronized too?


<!-- Sent from Reviewable.io -->

2021-04-19 12:56 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @axti and @pinkisemils)

___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/NotificationWithUrlWithToken.kt, line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677#-MYcqmAB42jyoFF2iJV5:-MYe389aBVnHd7xjiHN0:b-69hgc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/420502f2b48a5e18da30b5b950b37ab028d3e9f7/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/NotificationWithUrlWithToken.kt#L16)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

Nit: How do you handle cancellations?
</blockquote></details>

The coroutine can be cancelled by the super class, which uses a `JobTracker` to handle all coroutine jobs.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt, line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677#-MYctj30Dc55o1LGz7wW:-MYe6xHD7F6v3Vf1NYCW:b-p5s7qc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/420502f2b48a5e18da30b5b950b37ab028d3e9f7/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt#L11)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think the class should still be using locks, but having a granular lock on the queue would be redundant given that the cache has to be threadsafe itself, IMO.
</blockquote></details>

I left it as is for now. Using a `BlockingQueue` could block to while handling the message, which I think is not optimal.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt, line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677#-MYct-ob0EHbJi3ZKCS8:-MYe6gW2712TZT7_BbV0:b-j4gu3i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/420502f2b48a5e18da30b5b950b37ab028d3e9f7/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt#L16)):*
<details><summary><i>Previously, axti (Alex Granin) wrote…</i></summary><blockquote>

> ```
> !fetchQueue.isEmpty()
> ```
Nit: Could be changed to `fetchQueue.isNotEmpty()`
</blockquote></details>

Done, but I decided to remove it and use the `Queue` interface methods. The check was redundant anyway, because if the queue is empty the call to get an item would return `null`.
___
*[android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt, line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677#-MYdT6vD-6m93e-WF7rQ:-MYe6PEHDutingJPz9qn:b-dtkds3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/420502f2b48a5e18da30b5b950b37ab028d3e9f7/android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt#L36)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Shouldn't this function be synchronized too?
</blockquote></details>

Done, thanks!


<!-- Sent from Reviewable.io -->

2021-04-19 13:53 UTC, pinkisemils approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-19 15:22 UTC, axti approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-19 15:22 UTC, axti approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-20 13:19 UTC, axti approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-20 13:19 UTC, axti approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-20 14:25 UTC, merged