Use `TVActivity` class when asking for VPN permission on TVs
mullvad/mullvadvpn-app pull request #2681
Opened 2021-04-19 20:59 UTC by jvff

When the app runs on TVs, a different activity class (`TVActivity`) is used to make sure the UI is displayed correctly. A recent refactor (#2644) included a hard-coded reference to the non-TV class (`MainActivity`), which ended up breaking requesting the Android VPN permission when running on TVs.

This PR fixes that by detecting if the app is running on a TV device or not and selecting the appropriate class.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-04-20 07:44 UTC, axti commented
Issue is not only here. In the PR #2644 (Split `ConnectionProxy` into a UI-side and a service-side class) we removed request for VPN permission, so no it is not possible to connect without this permission.        
![Screenshot 2021-04-20 at 09.43.02.png](https://files.reviewableusercontent.io/images/reviewable/5171553/UmGZukWbyPz1jhH5LK9cxm01/Screenshot%202021-04-20%20at%2009.43.02.png)





<!-- Sent from Reviewable.io -->

2021-04-20 07:44 UTC, axti requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2681)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-21 20:29 UTC, jvff reviewed
Ah, I had missed that this was broken :( I fixed it in a separate PR #2692 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2681#-:-MYq6qJg0T8WzEt7Wdc4:b-pxjmvr)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-22 05:44 UTC, axti approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2681)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-23 13:06 UTC, merged