Add length condition when parsing GUI settings array
mullvad/mullvadvpn-app pull request #2747
Opened 2021-05-18 08:22 UTC by raksooo

This PR corrects the condition that checks the types of array content in the GUI settings. Previously this didn't work for empty arrays.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-05-18 08:54 UTC, pronebird approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2747)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-18 08:55 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2747)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/gui-settings.ts, line 140 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2747#-M_yfqCp8vwf1yMMluyJ:-M_yfqCp8vwf1yMMluyK:b-jtzl2p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a06902e4b83a0ef2a1449a69af8ba6ee0d4fd025/gui/src/main/gui-settings.ts#L140)):*
> ```XML
>               innerTypes[0] !== expectedInnerType)
>           ) {
>             throw new Error(`Expected ${key} to to contain ${expectedInnerType}s`);
> ```

Double `to`


<!-- Sent from Reviewable.io -->

2021-05-18 09:16 UTC, raksooo reviewed
I moved the `key in settings` check to wrap all the checks since no checks are supposed to be performed if the value is `undefined`.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2747#-:-M_ykZYP6FPlcRR7Ntrq:b60ouyd)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/main/gui-settings.ts, line 140 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2747#-M_yfqCp8vwf1yMMluyJ:-M_ykXu22Yipmx8H4qDl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a06902e4b83a0ef2a1449a69af8ba6ee0d4fd025/gui/src/main/gui-settings.ts#L140)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Double `to`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-20 09:41 UTC, pronebird approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2747)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-20 10:25 UTC, merged