Assign local DNS servers to correct interfaces with systemd-resolved
mullvad/mullvadvpn-app pull request #2761
Opened 2021-05-24 07:14 UTC by dlon

Previously, only the tunnel interface had its DNS config updated when using systemd-resolved. This no longer works. Since there's no way to set a global config using D-Bus, resolvectl, etc., this PR monitors the routing table to determine the correct interfaces.

2021-05-24 08:11 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761)* status: 0 of 10 files reviewed, 1 unresolved discussion

___
*[talpid-core/src/dns/linux/systemd_resolved.rs, line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-MaSPSn_AqTI0LX7kv2t:-MaSPSna09cV0qKF8gLm:bg5oxxm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d5106b237b7b9bd6870c83426f24cffebe35dcd/talpid-core/src/dns/linux/systemd_resolved.rs#L78)):*
> ```XML
>                 }
>             };
>             let dns_state = match self.dbus_interface.set_dns(
> ```

Maybe this should be done on a different thread. It might block for a while.


<!-- Sent from Reviewable.io -->

2021-05-26 10:15 UTC, pinkisemils requested changes
> Reviewed 4 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/dns/linux/mod.rs, line 141 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-Mac9pQO8zKAzBv1NXE9:-Mac9pQO8zKAzBv1NXEA:bmd0elo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d5106b237b7b9bd6870c83426f24cffebe35dcd/talpid-core/src/dns/linux/mod.rs#L141)):*
> ```XML
>             }
>             SystemdResolved(ref mut systemd_resolved) => {
>                 handle.block_on(systemd_resolved.set_dns(interface, &servers))?
> ```

I have to wonder, this would be executed from a thread that runs the tunnel state machine, right? Would this not deadlock if the TSM was ran on a runtime that has a single executor thread?
___
*[talpid-core/src/dns/linux/routing.rs, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-Mac9WOx65S66CXvQuVS:-Mac9WOx65S66CXvQuVT:b6hjuqw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d5106b237b7b9bd6870c83426f24cffebe35dcd/talpid-core/src/dns/linux/routing.rs#L1)):*
> ```XML
> use futures::{
> ```

Would it be too finnicky to have this code be moved into the route monitor and just have it send events to the DNS implementation?


<!-- Sent from Reviewable.io -->

2021-05-26 10:46 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/dns/linux/systemd_resolved.rs, line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-MaSPSn_AqTI0LX7kv2t:-MacH3oM2Pyqvgpkk7SV:b35dczy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d5106b237b7b9bd6870c83426f24cffebe35dcd/talpid-core/src/dns/linux/systemd_resolved.rs#L78)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Maybe this should be done on a different thread. It might block for a while.
</blockquote></details>

Not only that, but it can block the executor. The runtime is not re-entrant AFAIK.


<!-- Sent from Reviewable.io -->

2021-05-26 10:47 UTC, pinkisemils reviewed
> Reviewed 4 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-05-27 07:50 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761)* status: 6 of 12 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/src/dns/linux/mod.rs, line 141 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-Mac9pQO8zKAzBv1NXE9:-Mad1Qpx8EF58b9059zY:b-44v0mc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d5106b237b7b9bd6870c83426f24cffebe35dcd/talpid-core/src/dns/linux/mod.rs#L141)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I have to wonder, this would be executed from a thread that runs the tunnel state machine, right? Would this not deadlock if the TSM was ran on a runtime that has a single executor thread?
</blockquote></details>

I think it would panic if it ran on a tokio thread, but that is not the case here.
___
*[talpid-core/src/dns/linux/routing.rs, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-Mac9WOx65S66CXvQuVS:-Magj-Ic6jb2_G6UYa4C:b-8q7jna) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d5106b237b7b9bd6870c83426f24cffebe35dcd/talpid-core/src/dns/linux/routing.rs#L1)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Would it be too finnicky to have this code be moved into the route monitor and just have it send events to the DNS implementation?
</blockquote></details>

It would be nice. I'm not sure how to abstract everything in a decent way. But I think we should do this later.


<!-- Sent from Reviewable.io -->

2021-05-27 11:21 UTC, pinkisemils requested changes
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/dns/linux/routing.rs, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-Mac9WOx65S66CXvQuVS:-MahLRVb27DmcSZg4fg5:b-74u3h9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d5106b237b7b9bd6870c83426f24cffebe35dcd/talpid-core/src/dns/linux/routing.rs#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It would be nice. I'm not sure how to abstract everything in a decent way. But I think we should do this later.
</blockquote></details>

Well, the architecture I had in mind was having an actor that listens for changes to the routing table and for registrations - when a route change happens, registered handles would receive an event. The DNS monitor would register on setup and deregister on shutdown. It does imply a dependency from one to another though.
___
*[talpid-dbus/src/systemd_resolved.rs, line 262 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-MahMQGQCseKozlBdYFi:-MahMQGQCseKozlBdYFj:buggxhz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0d65881beef7b8ffecb2ddf2b823bd5b24c6cbba/talpid-dbus/src/systemd_resolved.rs#L262)):*
> ```XML
>     }
> 
>     pub fn set_dns(&self, interface_index: u32, servers: &[IpAddr]) -> Result<DnsState> {
> ```

I'd prefer to just change the call sites to have to convert the slice to a vector and just have `pub fn set_dns` without `fn set_dns_inner` here.


<!-- Sent from Reviewable.io -->

2021-05-27 12:40 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/src/dns/linux/routing.rs, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-Mac9WOx65S66CXvQuVS:-MahoqvsCQ_MZLmFkL9i:b-16b2wy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d5106b237b7b9bd6870c83426f24cffebe35dcd/talpid-core/src/dns/linux/routing.rs#L1)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Well, the architecture I had in mind was having an actor that listens for changes to the routing table and for registrations - when a route change happens, registered handles would receive an event. The DNS monitor would register on setup and deregister on shutdown. It does imply a dependency from one to another though.
</blockquote></details>

Yes, that makes sense.
___
*[talpid-dbus/src/systemd_resolved.rs, line 262 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-MahMQGQCseKozlBdYFi:-MahojJjAq0NxSCFE-2F:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0d65881beef7b8ffecb2ddf2b823bd5b24c6cbba/talpid-dbus/src/systemd_resolved.rs#L262)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I'd prefer to just change the call sites to have to convert the slice to a vector and just have `pub fn set_dns` without `fn set_dns_inner` here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-28 10:38 UTC, pinkisemils requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/dns/linux/systemd_resolved.rs, line 84 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-MamPLVC0KRdqhYHlo_y:-MamPLVC0KRdqhYHlo_z:bb9abhu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b951f0d318269e0e9094c6f8debc8df34eeda3e/talpid-core/src/dns/linux/systemd_resolved.rs#L84)):*
> ```XML
>                 break;
>             }
>             self.initial_states.lock().unwrap().push(initial_state);
> ```

Could this lock be acquired outside of the loop? Or would that make it vulnerable to deadlocks?
___
*[talpid-core/src/dns/linux/systemd_resolved.rs, line 127 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-MamY75z1zEMGnGIPTR6:-MamY75z1zEMGnGIPTR7:byhj1aa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b951f0d318269e0e9094c6f8debc8df34eeda3e/talpid-core/src/dns/linux/systemd_resolved.rs#L127)):*
> ```XML
>                 let mut new_initial_states = { initial_states.lock().unwrap().clone() };
>                 new_initial_states.sort_by(|a, b| a.interface_index.cmp(&b.interface_index));
>                 new_config.sort_by(|a, b| a.interface.cmp(&b.interface));
> ```

Would it not make a bit more sense to store the contents of `new_config` and `new_initial_states` in a `BTreeMap`? 
___
*[talpid-core/src/dns/linux/systemd_resolved.rs, line 190 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-MamYIlfAKmOfaqjsAeb:-MamXE_R4tagFfcbVYWp:b-qhqjcs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b951f0d318269e0e9094c6f8debc8df34eeda3e/talpid-core/src/dns/linux/systemd_resolved.rs#L190)):*
> ```XML
> 
>                 let tunnel_domains =
>                     if new_config.len() == 1 && new_config[0].interface == tunnel_index {
> ```

What's going on here makes sense, but it took me a while to come to that conclusion. Yet, I do no t know how to make this clearer :/ 


<!-- Sent from Reviewable.io -->

2021-06-08 08:10 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/dns/linux/systemd_resolved.rs, line 84 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-MamPLVC0KRdqhYHlo_y:-MbeejVQEfQgN_YVD5ji:bifs8dt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b951f0d318269e0e9094c6f8debc8df34eeda3e/talpid-core/src/dns/linux/systemd_resolved.rs#L84)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Could this lock be acquired outside of the loop? Or would that make it vulnerable to deadlocks?
</blockquote></details>

No, that should be fine. Done.
___
*[talpid-core/src/dns/linux/systemd_resolved.rs, line 127 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-MamY75z1zEMGnGIPTR6:-Mbeev9p06pSuwLeVjWV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b951f0d318269e0e9094c6f8debc8df34eeda3e/talpid-core/src/dns/linux/systemd_resolved.rs#L127)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Would it not make a bit more sense to store the contents of `new_config` and `new_initial_states` in a `BTreeMap`? 
</blockquote></details>

Done.
___
*[talpid-core/src/dns/linux/systemd_resolved.rs, line 190 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761#-MamYIlfAKmOfaqjsAeb:-MbeeqaNE1hEjTxinFc2:beccrha) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b951f0d318269e0e9094c6f8debc8df34eeda3e/talpid-core/src/dns/linux/systemd_resolved.rs#L190)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

What's going on here makes sense, but it took me a while to come to that conclusion. Yet, I do no t know how to make this clearer :/ 
</blockquote></details>

It should be clearer now.


<!-- Sent from Reviewable.io -->

2021-06-08 16:20 UTC, pinkisemils approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-09 14:04 UTC, merged