Give Windows more time to init IP interfaces
mullvad/mullvadvpn-app pull request #2778
Opened 2021-05-31 14:47 UTC by dlon

Previously, the daemon had a five-second timeout for waiting on the `MibAddInstance` event (i.e., for IP interfaces to attach to the tunnel device) after setting up a new Wintun device. Early after a reboot, this can take considerably more time to occur on some machines (30 seconds or more), causing some machines to get stuck in the error state, especially with auto-connect enabled.

The previous code blocked the tunnel state machine, so it had to time out quickly. To extend/remove the timeout, the tunnel monitors were updated to do this asynchronously/on a separate thread. The blocking code was also removed from `libwg` and now uses the same code as the openvpn tunnel monitor.

2021-06-01 09:32 UTC, pinkisemils requested changes
> Reviewed 5 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778)* status: 5 of 13 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel/windows.rs, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb5pPXu1IJoKReAmbq_:-Mb5pPXv7RjQa4ezta0o:b-7uwbc6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/windows.rs#L15)):*
> ```XML
> /// Context for [`notify_ip_interface_change`]. When it is dropped,
> /// the callback is unregistered.
> pub struct IpNotifierHandle<'a> {
> ```

Could this not be refactored to be a `Handle` and a `InnerHandle`, like `Handle { inner: Mutex<InnerHandle> }`? Or is it the case that the raw handle should be cancelled before acquiring the mutex as to not get into a deadlock?
___
*[talpid-core/src/tunnel/windows.rs, line 98 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb5qYTEDyEeBMDkEA4f:-Mb5qYTEDyEeBMDkEA4g:b-d56sww) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/windows.rs#L98)):*
> ```XML
>     match get_ip_interface_entry(family, luid) {
>         Ok(_) => Ok(true),
>         Err(error) => match error.raw_os_error() {
> ```

You could lose the nested match statement by having two error cases
`Err(error) if error.raw_os_error() == Some(ERROR_NOT_FOUND) => Ok(false)` and
`Err(error) => Err(error)`.


<!-- Sent from Reviewable.io -->

2021-06-01 09:57 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778)* status: 5 of 13 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/windows.rs, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb5pPXu1IJoKReAmbq_:-Mb5xALm7BU3WnHRQtZ-:b-vqp6sq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/windows.rs#L15)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Could this not be refactored to be a `Handle` and a `InnerHandle`, like `Handle { inner: Mutex<InnerHandle> }`? Or is it the case that the raw handle should be cancelled before acquiring the mutex as to not get into a deadlock?
</blockquote></details>

It prevents use after free. Consider this outcome in `IpNotifierHandle::drop()`:
```
let inner = mutex.lock();
// an event occurs, and inner_callback waits to acquire the mutex
cancel(inner.raw_handle);
// mutex is released, IpNotifierHandle is destroyed
// inner_callback is still using the inner context/mutex which has been destroyed
```


<!-- Sent from Reviewable.io -->

2021-06-01 10:13 UTC, pinkisemils requested changes
> Reviewed 7 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/tunnel/windows.rs, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb5pPXu1IJoKReAmbq_:-Mb62ujQCc_hFesj7t7S:b-iovvxc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/windows.rs#L15)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It prevents use after free. Consider this outcome in `IpNotifierHandle::drop()`:
```
let inner = mutex.lock();
// an event occurs, and inner_callback waits to acquire the mutex
cancel(inner.raw_handle);
// mutex is released
// inner_callback is still using the inner context/mutex which has been destroyed
```
</blockquote></details>

Ah, so it'd have to be a`Mutex<Option<InnerHandle>>` then, no ?
___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 762 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb5z41pCf0Q39XpgE_I:-Mb5z41q9lnBZ1Wh-fof:bkhttwy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/openvpn/mod.rs#L762)):*
> ```XML
>             Some(task) => task,
>             None => {
>                 log::error!("BUG: spawn_task == None");
> ```

I wonder if it'd make sense to panic here. Most probably not because `wait_tunnel()` can be called multiple times. Then again, `wait_tunnel()` could take `self` instead of `&mut self` it seems. In which case, I'd advocate for panicking here. This would definitely be caught in a test.
___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 948 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb60zJ2BaL5jkSBZ78x:-Mb60zJ2BaL5jkSBZ78y:bhtuzzn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/openvpn/mod.rs#L948)):*
> ```XML
>                 child.kill()
>             } else {
>                 self.abort_spawn.abort();
> ```

Isn't there a small chance of still spawning a child here? Regardless, I think there's no harm and it's simpler to always abort the spawn first, and then kill the child if it exists.
___
*[talpid-core/src/tunnel/wireguard/mod.rs, line 229 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb62D363WRYnOaKoTA9:-Mb62D363WRYnOaKoTAA:b3ov5cm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/wireguard/mod.rs#L229)):*
> ```XML
>                     futures::select! {
>                         result = setup_future.fuse() => {
>                             match result {
> ```

This match statement could be a dirty `.map_err(|err| iface_close_sender.send(...` hack. Less lines and a bit more readable, I think.


<!-- Sent from Reviewable.io -->

2021-06-01 11:38 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/windows.rs, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb5pPXu1IJoKReAmbq_:-Mb66zL0ES6c-4T-1S80:b-odjt40) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/windows.rs#L15)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Ah, so it'd have to be a`Mutex<Option<InnerHandle>>` then, no ?
</blockquote></details>

Still doesn't work, I think. The pointer to `IpNotifierHandle` is invalid after it is dropped, and the mutex has been dropped at that point.
___
*[talpid-core/src/tunnel/windows.rs, line 98 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb5qYTEDyEeBMDkEA4f:-Mb6Lhj40W5CHago8ZFv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/windows.rs#L98)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

You could lose the nested match statement by having two error cases
`Err(error) if error.raw_os_error() == Some(ERROR_NOT_FOUND) => Ok(false)` and
`Err(error) => Err(error)`.
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 762 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb5z41pCf0Q39XpgE_I:-Mb6Ls9T3zC7TmEmJBGP:b-qri8p7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/openvpn/mod.rs#L762)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I wonder if it'd make sense to panic here. Most probably not because `wait_tunnel()` can be called multiple times. Then again, `wait_tunnel()` could take `self` instead of `&mut self` it seems. In which case, I'd advocate for panicking here. This would definitely be caught in a test.
</blockquote></details>

Done. Usually when I hesitate, I go for not panicking. But it really should be impossible here.
___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 948 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb60zJ2BaL5jkSBZ78x:-Mb6M4fDEI8NOF0CmaeD:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/openvpn/mod.rs#L948)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Isn't there a small chance of still spawning a child here? Regardless, I think there's no harm and it's simpler to always abort the spawn first, and then kill the child if it exists.
</blockquote></details>

Done.
___
*[talpid-core/src/tunnel/wireguard/mod.rs, line 229 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb62D363WRYnOaKoTA9:-Mb6M93P9oH1pNBWuRm5:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/wireguard/mod.rs#L229)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This match statement could be a dirty `.map_err(|err| iface_close_sender.send(...` hack. Less lines and a bit more readable, I think.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-01 14:52 UTC, pinkisemils requested changes
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/tunnel/windows.rs, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb5pPXu1IJoKReAmbq_:-Mb72YYU-CJ157B5HSbf:b-v270un) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/windows.rs#L15)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Still doesn't work, I think. The pointer to `IpNotifierHandle` is invalid after it is dropped, and the mutex has been dropped at that point.
</blockquote></details>

It'd have to be an `Arc<Mutex<Option<<<InnerHandle>>>`, and  the callback should try and convert the pointer to a weak reference, which then you'd ultimately try and upgrade to a strong one.
___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 762 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb5z41pCf0Q39XpgE_I:-Mb6kSxvBMWzDS-hjgHF:b-pjgexn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/openvpn/mod.rs#L762)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. Usually when I hesitate, I go for not panicking. But it really should be impossible here.
</blockquote></details>

I agree, but we have tests that should exercise this function anyway, right? We might benefit from some coverage tools.


<!-- Sent from Reviewable.io -->

2021-06-01 16:09 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/windows.rs, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb5pPXu1IJoKReAmbq_:-Mb7Cj0G5cM_rlfcnzyV:bo5dq3r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/windows.rs#L15)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It'd have to be an `Arc<Mutex<Option<<<InnerHandle>>>`, and  the callback should try and convert the pointer to a weak reference, which then you'd ultimately try and upgrade to a strong one.
</blockquote></details>

Wouldn't the `Arc` itself be destroyed along with `IpNotifierHandle`? I might need a more complete explanation.

I've made some changes. The mutex wraps the callback function, which is the only thing that is being accessed in the callback anyway.


<!-- Sent from Reviewable.io -->

2021-06-01 17:10 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/tunnel/windows.rs, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb5pPXu1IJoKReAmbq_:-Mb7XV4W9UdgBk1jja8M:bl39e0r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/windows.rs#L15)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Wouldn't the `Arc` itself be destroyed along with `IpNotifierHandle`? I might need a more complete explanation.

I've made some changes. The mutex wraps the callback function, which is the only thing that is being accessed in the callback anyway.
</blockquote></details>

It would be, but it'd be safe to check if it's still alive from the callback. Isn't the issue here that `inner_callback` be called when it's context has already been dropped? If not, then the current solution is good enough. The issue with using a `Mutex` without an `Arc` is that you have to be really certain about the lifetimes of of the stuff that's being protected by the mutex. In case of a mutex being accessed by multiple threads, you'd still want an Arc, right? If you don't need an arc, do you need a mutex?


<!-- Sent from Reviewable.io -->

2021-06-02 09:40 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/windows.rs, line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2778#-Mb5pPXu1IJoKReAmbq_:-MbB4SrJ-rBfYppMrpNm:b-2ogq0q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a5907fca68046a6f883141b62254a1449766a76/talpid-core/src/tunnel/windows.rs#L15)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It would be, but it'd be safe to check if it's still alive from the callback. Isn't the issue here that `inner_callback` be called when it's context has already been dropped? If not, then the current solution is good enough. The issue with using a `Mutex` without an `Arc` is that you have to be really certain about the lifetimes of of the stuff that's being protected by the mutex. In case of a mutex being accessed by multiple threads, you'd still want an Arc, right? If you don't need an arc, do you need a mutex?
</blockquote></details>

I've found that `CancelMibChangeNotify2` doesn't return until all calls to `inner_callback` are complete. So the code as it is works correctly.


<!-- Sent from Reviewable.io -->

2021-06-02 10:04 UTC, merged