Add workaround for closing context menus on macOS 11
mullvad/mullvadvpn-app pull request #2781
Opened 2021-06-03 08:02 UTC by raksooo

This PR adds a workaround for [this Electron issue](https://github.com/electron/electron/issues/28776) which causes other menubar context menus to remain open after opening our app.

This solution doesn't allow VoiceOver to focus the window properly but VoiceOver didn't work when the other context menus were ontop of our window either. VoiceOver still works as expected if the window is opened by launching the app when already running from the dock, spotlight or other methods.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-06-03 08:08 UTC, pronebird requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2781)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 1773 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2781#-MbFuZSM2SbwBvQMRroj:-MbFuZSNBY_5Vs2KjJA9:b351d2l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9b47c1a5674bd257f0ee64106c5fae8503a4360c/gui/src/main/index.ts#L1773)):*
> ```XML
>           // https://github.com/electron/electron/issues/28776
>           const contextMenu = Menu.buildFromTemplate([]);
>           contextMenu.on('menu-will-show', () => this.windowController?.toggle());
> ```

Don't know if toggle() makes sense since this branch performs only when the window is invisible. Don't we have `show()` call defined there?


<!-- Sent from Reviewable.io -->

2021-06-03 08:14 UTC, pronebird reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2781)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2021-06-03 08:41 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2781)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/main/index.ts, line 1773 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2781#-MbFuZSM2SbwBvQMRroj:-MbG15Oq-fytxw0VxEhl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9b47c1a5674bd257f0ee64106c5fae8503a4360c/gui/src/main/index.ts#L1773)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Don't know if toggle() makes sense since this branch performs only when the window is invisible. Don't we have `show()` call defined there?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-04 06:35 UTC, pronebird approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2781)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-04 07:41 UTC, merged