Handle uninstaller errors correctly
mullvad/mullvadvpn-app pull request #2814
Opened 2021-06-24 09:10 UTC by dlon

#2813 gives the option to decide what to do if the uninstaller returns an error or refuses to run. The default behavior is to ignore any errors, so we checked for the presence of "uninstall.log" to infer that it failed. Aside from getting rid of that hack, the installer can now always refuse to continue if some old files could not be deleted.

2021-06-24 12:52 UTC, mvd-ows requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2814)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[dist-assets/windows/installer.nsh, line 762 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2814#-Mcy1oTiDF98aedsqM8u:-Mcy1oTiDF98aedsqM8v:b-46euy4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec08a9e9434f909d7e34b71cbf7527ddce5861/dist-assets/windows/installer.nsh#L762)):*
> ```NSIS
> ###############################################################################
> 
> !macro customUnInstallCheck
> ```

Lots of magic here. On entry someone is supposed to have:

- Set/cleared the error flag depending on overall state
- Updated $R0

Can we be sure this is always true?

Perhaps add a function description/comment explaining in which situations this function is activated.
___
*[dist-assets/windows/installer.nsh, line 772 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2814#-McxzU1E0Qy_gZjMF2lU:-McxzU1E0Qy_gZjMF2lV:bacwn2d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14b1c184b8d5007870de465bde9cf2d9311e6144/dist-assets/windows/installer.nsh#L772)):*
> ```NSIS
> 	${If} $BlockFilterResult == 0
> 	${OrIf} $PersistentBlockFilterResult == 0
> 		MessageBox MB_ICONEXCLAMATION|MB_YESNO "Do you wish to unblock your internet access? Doing so will leave you with an unsecure connection." IDNO customInstall_abort_installation_skip_firewall_revert
> ```

This message/warning is no longer needed?
___
*[dist-assets/windows/installer.nsh, line 790 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2814#-Mcy31ME7DEg-bnqXmNu:-Mcy31ME7DEg-bnqXmNv:bp2u9wj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec08a9e9434f909d7e34b71cbf7527ddce5861/dist-assets/windows/installer.nsh#L790)):*
> ```
> see
> ```

`review`?


<!-- Sent from Reviewable.io -->

2021-06-28 08:20 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2814)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @mvd-ows)

___
*[dist-assets/windows/installer.nsh, line 762 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2814#-Mcy1oTiDF98aedsqM8u:-MdGfvLL-LYZQ3srPwPZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec08a9e9434f909d7e34b71cbf7527ddce5861/dist-assets/windows/installer.nsh#L762)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Lots of magic here. On entry someone is supposed to have:

- Set/cleared the error flag depending on overall state
- Updated $R0

Can we be sure this is always true?

Perhaps add a function description/comment explaining in which situations this function is activated.
</blockquote></details>

Done.
___
*[dist-assets/windows/installer.nsh, line 772 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2814#-McxzU1E0Qy_gZjMF2lU:-MdGg-bfCTkaLKFKS_Lh:besmk6r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14b1c184b8d5007870de465bde9cf2d9311e6144/dist-assets/windows/installer.nsh#L772)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

This message/warning is no longer needed?
</blockquote></details>

I think it's easy to shoot yourself in the foot. If you choose not to unblock, it's pretty hard to get rid of the persistent filters without reinstalling.


<!-- Sent from Reviewable.io -->

2021-06-28 08:27 UTC, mvd-ows reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2814)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dlon and @mvd-ows)

___
*[dist-assets/windows/installer.nsh, line 772 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2814#-McxzU1E0Qy_gZjMF2lU:-MdGhi-n2Js6rAoqDPT-:b-1vuzj0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14b1c184b8d5007870de465bde9cf2d9311e6144/dist-assets/windows/installer.nsh#L772)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think it's easy to shoot yourself in the foot. If you choose not to unblock, it's pretty hard to get rid of the persistent filters without reinstalling.
</blockquote></details>

Agree. But maybe there should be a messagebox informing about the removal of filters, with only an OK button?

Previously there was a guarantee that traffic is never leaked, even on failure, unless you approved the removal of filters.

Now there is no such guarantee, and it's not clearly communicated.


<!-- Sent from Reviewable.io -->

2021-06-28 08:27 UTC, mvd-ows approved these changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2814)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-06-28 11:24 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2814)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[dist-assets/windows/installer.nsh, line 772 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2814#-McxzU1E0Qy_gZjMF2lU:-MdHMAeT-JHndmJ5mWZP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14b1c184b8d5007870de465bde9cf2d9311e6144/dist-assets/windows/installer.nsh#L772)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Agree. But maybe there should be a messagebox informing about the removal of filters, with only an OK button?

Previously there was a guarantee that traffic is never leaked, even on failure, unless you approved the removal of filters.

Now there is no such guarantee, and it's not clearly communicated.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-28 12:48 UTC, mvd-ows approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2814)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-28 13:54 UTC, merged