Fix WireGuard entry relay selection
mullvad/mullvadvpn-app pull request #2841
Opened 2021-07-06 15:31 UTC by dlon

Previously, the WireGuard "entry peer" was always obtained after the exit (i.e., "normal") relay was decided. This could be an issue if a specific entry relay constraint were set, e.g. a hostname, that was a subset of the exit location constraint. The same peer could be selected for both exit and entry.

To fix this, the entry relay is now selected before the exit relay if the entry location constraint is more specific than the exit location constraint, and vice versa if the exit location constraint is more specific than the entry relay constraint. For example, if the entry location constraint is a city and the entry location constraint is a country, the exit peer is decided first.

Some unit tests were also added to test the changes in this PR.

2021-07-08 09:42 UTC, pinkisemils reviewed
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841)* status: 3 of 4 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-08 14:37 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/relays.rs, line 234 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841#-Me5XkV27Fmt3_pWws6G:-Me5XkV31vVk10FrS44b:b-itlf6p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65521f3af48ea261cb70ffdd0e3029f4e4154bc9/mullvad-daemon/src/relays.rs#L234)):*
> ```XML
>     ) -> Result<(Relay, MullvadEndpoint), Error> {
>         let mut exit_relay_constraints = relay_constraints.clone();
>         let wg_entry_is_subset = if let Some(entry_location) =
> ```

I think the location constraint deserves set operation implementations on the type itself. 
___
*[mullvad-daemon/src/relays.rs, line 652 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841#-Me5SofIDtfGDZnAEJ_g:-Me5SofIDtfGDZnAEJ_h:b-ypabye) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65521f3af48ea261cb70ffdd0e3029f4e4154bc9/mullvad-daemon/src/relays.rs#L652)):*
> ```XML
>         }
> 
>         let include_wg = if let Some(wg_peer) = skip_wg_peer {
> ```

I'm not sure what `skip_wg_peer` means? Is it a peer that has to be skipped ? 
___
*[mullvad-daemon/src/relays.rs, line 821 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841#-Me5SZBu2vf7gu2OlXKV:-Me5SZBu2vf7gu2OlXKW:b-lhn7mv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86bb6d0efb5d93cfd3054b1dc7d5cddcd1575d04/mullvad-daemon/src/relays.rs#L821)):*
> ```XML
>                     port_index -= ports_in_range;
>                 }
>                 panic!("Port selection algorithm is broken")
> ```

Do we have reports of the panic occurring in real world usage? If not, I think this is the easiest way to make sure that this breaks during testing. OTOH, since we have tests now, maybe it's ok to not panic.


<!-- Sent from Reviewable.io -->

2021-07-09 08:14 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/relays.rs, line 652 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841#-Me5SofIDtfGDZnAEJ_g:-Me9HsBp5qxZ0i_9J1f8:bxdhu13) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65521f3af48ea261cb70ffdd0e3029f4e4154bc9/mullvad-daemon/src/relays.rs#L652)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I'm not sure what `skip_wg_peer` means? Is it a peer that has to be skipped ? 
</blockquote></details>

This should be clearer. It means that the relay's "WireGuard tunnels" should be skipped, since we're already using the server as the entry or exit relay.
___
*[mullvad-daemon/src/relays.rs, line 821 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841#-Me5SZBu2vf7gu2OlXKV:-Me9I_9d0OHauIr242tC:bt7ii52) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86bb6d0efb5d93cfd3054b1dc7d5cddcd1575d04/mullvad-daemon/src/relays.rs#L821)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Do we have reports of the panic occurring in real world usage? If not, I think this is the easiest way to make sure that this breaks during testing. OTOH, since we have tests now, maybe it's ok to not panic.
</blockquote></details>

Isn't there a risk that it breaks and that this is only discovered in real-world usage, though? Adding more tests is probably the best thing to do.


<!-- Sent from Reviewable.io -->

2021-07-09 09:04 UTC, pinkisemils reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-daemon/src/relays.rs, line 821 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841#-Me5SZBu2vf7gu2OlXKV:-Me9UsEBAPQ4oQ2kyawZ:bs12q2m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86bb6d0efb5d93cfd3054b1dc7d5cddcd1575d04/mullvad-daemon/src/relays.rs#L821)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Isn't there a risk that it breaks and that this is only discovered in real-world usage, though? Adding more tests is probably the best thing to do.
</blockquote></details>

Previously, it was thought that a bug here would be triggered by manual testing 100% of the time. In any case, I'm fine with the panic being removed, as the tests are good. In a somewhat related note, we should probably look into test coverage tooling to make sure that the tests we have actually exercise the code we want to test.


<!-- Sent from Reviewable.io -->

2021-07-09 09:07 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-daemon/src/relays.rs, line 234 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841#-Me5XkV27Fmt3_pWws6G:-Me9VIdX5QaHP59oEMkY:b719dls) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65521f3af48ea261cb70ffdd0e3029f4e4154bc9/mullvad-daemon/src/relays.rs#L234)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think the location constraint deserves set operation implementations on the type itself. 
</blockquote></details>

Done. Maybe it deserves to be implemented as a trait on `Constraint` as well.


<!-- Sent from Reviewable.io -->

2021-07-09 10:20 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-daemon/src/relays.rs, line 234 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841#-Me5XkV27Fmt3_pWws6G:-Me9lz7B5aDyqBtGHSiR:brp8jl3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65521f3af48ea261cb70ffdd0e3029f4e4154bc9/mullvad-daemon/src/relays.rs#L234)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. Maybe it deserves to be implemented as a trait on `Constraint` as well.
</blockquote></details>

If it wouldn't be too much work, I think that'd be the better thing to do. 


<!-- Sent from Reviewable.io -->

2021-07-09 10:20 UTC, pinkisemils reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2021-07-09 10:20 UTC, pinkisemils approved these changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-09 10:37 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[mullvad-daemon/src/relays.rs, line 821 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841#-Me5SZBu2vf7gu2OlXKV:-Me9psHc2uYpz26qn0wd:bceuwbh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/86bb6d0efb5d93cfd3054b1dc7d5cddcd1575d04/mullvad-daemon/src/relays.rs#L821)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Previously, it was thought that a bug here would be triggered by manual testing 100% of the time. In any case, I'm fine with the panic being removed, as the tests are good. In a somewhat related note, we should probably look into test coverage tooling to make sure that the tests we have actually exercise the code we want to test.
</blockquote></details>

For sure.


<!-- Sent from Reviewable.io -->

2021-07-09 10:40 UTC, pinkisemils approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-09 10:41 UTC, pinkisemils approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2841#-:-Me9qn5q1eOyOLHkv7np:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-09 10:56 UTC, merged