Add WireGuard transport protocol constraint
mullvad/mullvadvpn-app pull request #2856
Opened 2021-07-15 13:11 UTC by dlon

This previously existed for custom relays. The PR adds the option for normal relays. Because the relay list does not currently include ports/TCP endpoints, all WireGuard relays are assumed to run `tcp2udp` on a set of hardcoded ports.

Usage:
> mullvad relay set tunnel wireguard any --protocol tcp

2021-07-16 08:07 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[mullvad-daemon/src/relays.rs, line 897 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MeiLgkNDiKhfop2Woms:-MeiLgkO1ggIxwNUP9lX:b-slkxap) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e53f8358d7e9cabf9ffde447ab0248de5b659ef/mullvad-daemon/src/relays.rs#L897)):*
> ```XML
>     ) -> Option<u16> {
>         // TODO: The relay list does not currently provide TCP ports.
>         let port_ranges = match constraints.protocol {
> ```

Maybe `WireguardEndpointData` should be modified right away instead.


<!-- Sent from Reviewable.io -->

2021-07-19 14:46 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[mullvad-types/src/relay_constraints.rs, line 522 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MezCq_D4NbYoAevNrlf:-MezCq_D4NbYoAevNrlg:bmxefz3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e53f8358d7e9cabf9ffde447ab0248de5b659ef/mullvad-types/src/relay_constraints.rs#L522)):*
> ```XML
>                     .port_ranges
>                     .iter()
>                     .any(|range| (port >= range.0 && port <= range.1)),
> ```

So for a constraint with a specified port but transport protocol set to `Any` it will match if the port is in the allowed UDP ranges? :thinking: That's only correct under the assumption that transport protocol `Any` will deterministically select UDP for the actual connection at a later stage. Do we want to make those assumptions in `mullvad-types` really?

On top of that, it's unfortunate that the allowed TCP ports has to be defined in `mullvad-types`. It feels like our design forces more code than desired to land in the `-types` crates.


<!-- Sent from Reviewable.io -->

2021-08-09 11:20 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[mullvad-types/src/relay_constraints.rs, line 522 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MezCq_D4NbYoAevNrlf:-Mge_oHp6b_Mn4p98E4S:b-t6uvh4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e53f8358d7e9cabf9ffde447ab0248de5b659ef/mullvad-types/src/relay_constraints.rs#L522)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

So for a constraint with a specified port but transport protocol set to `Any` it will match if the port is in the allowed UDP ranges? :thinking: That's only correct under the assumption that transport protocol `Any` will deterministically select UDP for the actual connection at a later stage. Do we want to make those assumptions in `mullvad-types` really?

On top of that, it's unfortunate that the allowed TCP ports has to be defined in `mullvad-types`. It feels like our design forces more code than desired to land in the `-types` crates.
</blockquote></details>

Yes. The protocol and ports probably belong in `WireguardEndpointData`? I think the assumption was that this would eventually be included in the relay list instead of hardcoded, so it didn't matter much.


<!-- Sent from Reviewable.io -->

2021-08-09 13:14 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[mullvad-types/src/relay_constraints.rs, line 482 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-Mgf1pFl74cYEHbFsusA:-Mgf1pFl74cYEHbFsusB:bdacwzu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e53f8358d7e9cabf9ffde447ab0248de5b659ef/mullvad-types/src/relay_constraints.rs#L482)):*
> ```XML
> pub struct WireguardConstraints {
>     pub port: Constraint<u16>,
>     pub protocol: Constraint<TransportProtocol>,
> ```

Can we consider going with a port+protocol representation that does not allow invalid combinations such as `protocol: Any, port: Only(443)`? As discussed on Slack.

Maybe we can consider

```
pub struct WireGuardConstraints {
    pub port: Constraint<TransportPort>,
}

pub struct TransportPort {
    pub protocol: TransportProtocol,
    pub port: Constraint<u16>,
}
```

And maybe later do the same for OpenVPN. But changing will require settings migration code. So if we can avoid this "mistake" on WireGuard from the start it will need less migration code in the long run.
___
*[mullvad-types/src/relay_constraints.rs, line 522 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MezCq_D4NbYoAevNrlf:-Mgf1fvcDohv0dbOxdg8:b-nj47ni) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e53f8358d7e9cabf9ffde447ab0248de5b659ef/mullvad-types/src/relay_constraints.rs#L522)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Yes. The protocol and ports probably belong in `WireguardEndpointData`? I think the assumption was that this would eventually be included in the relay list instead of hardcoded, so it didn't matter much.
</blockquote></details>

We should not rely on the ports being added to the relay list in the near future. So it's better to make a design that's nice and clean with hardcoded ports, because we might be keeping it for a while.


<!-- Sent from Reviewable.io -->

2021-08-13 08:26 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[mullvad-types/src/relay_constraints.rs, line 482 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-Mgf1pFl74cYEHbFsusA:-MgyYd2v4iW7H20-3VRo:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e53f8358d7e9cabf9ffde447ab0248de5b659ef/mullvad-types/src/relay_constraints.rs#L482)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we consider going with a port+protocol representation that does not allow invalid combinations such as `protocol: Any, port: Only(443)`? As discussed on Slack.

Maybe we can consider

```
pub struct WireGuardConstraints {
    pub port: Constraint<TransportPort>,
}

pub struct TransportPort {
    pub protocol: TransportProtocol,
    pub port: Constraint<u16>,
}
```

And maybe later do the same for OpenVPN. But changing will require settings migration code. So if we can avoid this "mistake" on WireGuard from the start it will need less migration code in the long run.
</blockquote></details>

Done.
___
*[mullvad-types/src/relay_constraints.rs, line 522 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MezCq_D4NbYoAevNrlf:-MgyYle48nvOOUvPRzdA:b-3g5qlm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e53f8358d7e9cabf9ffde447ab0248de5b659ef/mullvad-types/src/relay_constraints.rs#L522)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We should not rely on the ports being added to the relay list in the near future. So it's better to make a design that's nice and clean with hardcoded ports, because we might be keeping it for a while.
</blockquote></details>

I'm not sure it's "clean", but the TCP ports are only defined in the relay selector now.


<!-- Sent from Reviewable.io -->

2021-08-17 13:31 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[mullvad-types/src/relay_constraints.rs, line 522 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MezCq_D4NbYoAevNrlf:-MhJI5zJAtvd9PkOcP3Z:bkgrqik) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e53f8358d7e9cabf9ffde447ab0248de5b659ef/mullvad-types/src/relay_constraints.rs#L522)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I'm not sure it's "clean", but the TCP ports are only defined in the relay selector now.
</blockquote></details>

It doesn't look like this matching code takes `port.protocol` into consideration at all?


<!-- Sent from Reviewable.io -->

2021-08-17 13:53 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/relays.rs, line 917 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MhJMwlL9Y3cxSKDuROv:-MhJMwlL9Y3cxSKDuROw:bisgjzl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36968b4111798ce1ce824eb5f718389c19d2d003/mullvad-daemon/src/relays.rs#L917)):*
> ```XML
>         constraints: &WireguardConstraints,
>     ) -> Option<u16> {
>         // TODO: The relay list does not currently provide TCP ports.
> ```

It's not clear that the relay list ever will provide TCP ports actually. Or it's not on the roadmap currently. So I'm not sure this is a `TODO` item because it's not something we know we will change.
___
*[mullvad-daemon/src/relays.rs, line 922 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MhJN2qI4xbwHnswlkYh:-MhJN2qI4xbwHnswlkYi:b-ze01kc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36968b4111798ce1ce824eb5f718389c19d2d003/mullvad-daemon/src/relays.rs#L922)):*
> ```XML
>                 &WIREGUARD_TCP_PORTS[..]
>             }
>             _ => &data.port_ranges,
> ```

So for `Constraints::Any` this will return the UDP ports? That seems wrong since `Any` means automatic, meaning some fallback algorithm can toggle between UDP and TCP... But yeah, for now `Any` does indeed mean `UDP` so maybe we can cut some corners. But this will be changed rather soon, so it's important we don't mess stuff up too much and instead prepare for a version where TCP will be used by the fallback algorithm.


<!-- Sent from Reviewable.io -->

2021-08-18 08:11 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[mullvad-daemon/src/relays.rs, line 922 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MhJN2qI4xbwHnswlkYh:-MhNIpz622b50b9CJQIN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36968b4111798ce1ce824eb5f718389c19d2d003/mullvad-daemon/src/relays.rs#L922)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

So for `Constraints::Any` this will return the UDP ports? That seems wrong since `Any` means automatic, meaning some fallback algorithm can toggle between UDP and TCP... But yeah, for now `Any` does indeed mean `UDP` so maybe we can cut some corners. But this will be changed rather soon, so it's important we don't mess stuff up too much and instead prepare for a version where TCP will be used by the fallback algorithm.
</blockquote></details>

Done.
___
*[mullvad-types/src/relay_constraints.rs, line 522 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MezCq_D4NbYoAevNrlf:-MhJUTzC75_iRMDL_mqn:b-5vpz91) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e53f8358d7e9cabf9ffde447ab0248de5b659ef/mullvad-types/src/relay_constraints.rs#L522)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It doesn't look like this matching code takes `port.protocol` into consideration at all?
</blockquote></details>

It didn't, but I've improved the design now.


<!-- Sent from Reviewable.io -->

2021-08-18 10:23 UTC, pinkisemils requested changes
> Reviewed 5 of 12 files at r2, 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856)* status: 8 of 14 files reviewed, 3 unresolved discussions (waiting on @dlon and @faern)

___
*[mullvad-cli/src/cmds/relay.rs, line 762 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MhNlG5R9i_RD1ZuQZTr:-MhNlG5R9i_RD1ZuQZTs:b-wywmnr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/463a744d04770669b29daa380937cbde63ce7b03/mullvad-cli/src/cmds/relay.rs#L762)):*
> ```XML
>             let mut out = format!(
>                 "{} over {} over {}",
>                 Self::format_port(constraints.port.as_ref().map(|port| port.port).unwrap_or(0)),
> ```

Shouldn't the `unwrap_or(0)` zero be converted into a `any`?

In fact, it seems like you often need to access the port number from the constraint, which could be made into a method that returns an optional u16. 


<!-- Sent from Reviewable.io -->

2021-08-18 10:28 UTC, pinkisemils reviewed
> Reviewed 3 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856)* status: 11 of 14 files reviewed, 4 unresolved discussions (waiting on @dlon and @faern)

___
*[mullvad-types/src/relay_list.rs, line 146 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MhNn6J22VqJqTNfgBZy:-MhNn6J22VqJqTNfgBZz:bflbns6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/463a744d04770669b29daa380937cbde63ce7b03/mullvad-types/src/relay_list.rs#L146)):*
> ```XML
>     pub public_key: wireguard::PublicKey,
>     #[serde(default = "default_wg_transport")]
>     #[serde(skip)]
> ```

I'm not sure if there's a better way, but having a type that the fetched relay list deserializes to have these trap-door properties that have a default value seems a bit hacky. On the other hand, having two different types with the only difference between them being a single property is also insane.


<!-- Sent from Reviewable.io -->

2021-08-18 11:32 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856)* status: 11 of 14 files reviewed, 4 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[mullvad-cli/src/cmds/relay.rs, line 762 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MhNlG5R9i_RD1ZuQZTr:-MhNwMVeBFJknnXrF3Ur:b-anv2a6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/463a744d04770669b29daa380937cbde63ce7b03/mullvad-cli/src/cmds/relay.rs#L762)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Shouldn't the `unwrap_or(0)` zero be converted into a `any`?

In fact, it seems like you often need to access the port number from the constraint, which could be made into a method that returns an optional u16. 
</blockquote></details>

The `constraints.port` field is a `TransportPort` (the gRPC type). If it is not set, then the port is `any`. But if `constraints.port.port` is set to 0, then the port is also `any` (but the transport protocol is set). So `format_port` needs to check if it's 0 anyway.

Maybe the cleanest way to improve this would be to convert the gRPC type to back to the `mullvad-types`/`talpid-types` equivalent and then use its `Display` impl to format this? If it can be done without reworking all of the CLI.
___
*[mullvad-types/src/relay_list.rs, line 146 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MhNn6J22VqJqTNfgBZy:-MhNzDeGCGeMFPL2Qt7r:b-v4dl8e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/463a744d04770669b29daa380937cbde63ce7b03/mullvad-types/src/relay_list.rs#L146)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I'm not sure if there's a better way, but having a type that the fetched relay list deserializes to have these trap-door properties that have a default value seems a bit hacky. On the other hand, having two different types with the only difference between them being a single property is also insane.
</blockquote></details>

We could just also leave this field there in the file, even though the file itself will not contain the "TCP endpoints". I don't know if it should -- probably not? If it should, then the extra endpoints must be appended to the relay list at some point. I considered this but it seemed wrong to do it in `mullvad-rpc`. But it cannot simply be done in `mullvad_daemon::relays` before writing to the file, since the `mullvad_rpc::relay_list` bin must do it as well.


<!-- Sent from Reviewable.io -->

2021-08-18 13:53 UTC, pinkisemils requested changes
> Reviewed 1 of 12 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856)* status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @dlon and @faern)

___
*[mullvad-cli/src/cmds/relay.rs, line 762 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MhNlG5R9i_RD1ZuQZTr:-MhOWchz4DXzUqV4Z2RB:b52ku1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/463a744d04770669b29daa380937cbde63ce7b03/mullvad-cli/src/cmds/relay.rs#L762)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The `constraints.port` field is a `TransportPort` (the gRPC type). If it is not set, then the port is `any`. But if `constraints.port.port` is set to 0, then the port is also `any` (but the transport protocol is set). So `format_port` needs to check if it's 0 anyway.

Maybe the cleanest way to improve this would be to convert the gRPC type to back to the `mullvad-types`/`talpid-types` equivalent and then use its `Display` impl to format this? If it can be done without reworking all of the CLI.
</blockquote></details>

I think that'd be the best thing to do, yes.
___
*[mullvad-types/src/relay_list.rs, line 146 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MhNn6J22VqJqTNfgBZy:-MhOWsIVDbjtH4G38tx_:b2ksftb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/463a744d04770669b29daa380937cbde63ce7b03/mullvad-types/src/relay_list.rs#L146)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We could just also leave this field there in the file, even though the file itself will not contain the "TCP endpoints". I don't know if it should -- probably not? If it should, then the extra endpoints must be appended to the relay list at some point. I considered this but it seemed wrong to do it in `mullvad-rpc`. But it cannot simply be done in `mullvad_daemon::relays` before writing to the file, since the `mullvad_rpc::relay_list` bin must do it as well.
</blockquote></details>

I guess this truly is the best solution to a weird problem.


<!-- Sent from Reviewable.io -->

2021-08-19 08:24 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856)* status: 11 of 14 files reviewed, 4 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[mullvad-cli/src/cmds/relay.rs, line 762 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856#-MhNlG5R9i_RD1ZuQZTr:-MhSUfsvAISEdlAz8WcN:bbrp1qr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/463a744d04770669b29daa380937cbde63ce7b03/mullvad-cli/src/cmds/relay.rs#L762)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think that'd be the best thing to do, yes.
</blockquote></details>

Done. This should really be done for all types, but that work can be continued in a separate PR.


<!-- Sent from Reviewable.io -->

2021-08-19 09:33 UTC, pinkisemils approved these changes
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @faern)



<!-- Sent from Reviewable.io -->

2021-08-19 10:43 UTC, merged