Pause/defer automatic API requests while offline or the account is invalid
mullvad/mullvadvpn-app pull request #2937
Opened 2021-09-01 10:48 UTC by dlon

New behavior:
* When the daemon starts, the account validity is checked. If the account is non-existent, expired, or invalid, automatic requests to the API are delayed until `GetAccountData` is called with a valid account (or a valid voucher is submitted). These requests include: WireGuard key rotation, initial WireGuard key push, relay list updates, version checks, API IP cache rotations, etc.
* While offline, automatic requests are delayed until the machine is back online.
* Stop rotating the API IP when offline and a request fails.

2021-09-01 11:42 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 0 of 14 files reviewed, 2 unresolved discussions

___
*[mullvad-daemon/src/lib.rs, line 1508 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-MiVz3Lb9T-JcKVOKXYo:-MiVz3Lb9T-JcKVOKXYp:bi41tkv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/mullvad-daemon/src/lib.rs#L1508)):*
> ```XML
>     ) {
>         match result {
>             Ok(_expiry) if *_expiry >= chrono::Utc::now() => api_availability.resume(),
> ```

Maybe it wasn't ideal to implement this logic here? Would it be better to hide it in `mullvad-rpc`? Similarly, "waiting" could be implemented on `MullvadRestHandle`, so that one could do stuff like this:

```
let mut handle = rpc_runtime.mullvad_rest_handle();
handle.block_while_offline(true);
let proxy = AccountsProxy::new(handle);
proxy.get_expiry().await;
```

The RPC proxy objects would call something like `availability.set_account_valid(true)` to update the status.
___
*[mullvad-rpc/src/availability.rs, line 102 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-MiW-aSsCG0EIF56Xasn:-MiW-aSsCG0EIF56Xaso:b-43dxzq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/mullvad-rpc/src/availability.rs#L102)):*
> ```XML
>     }
> 
>     pub fn wait_online(&self) -> impl Future<Output = Result<(), Error>> {
> ```

This seems somewhat shaky. Might be mostly on Windows because the offline monitor doesn't wait for routes. Should it also wait for while to see if the state flips off again or is that too hacky?


<!-- Sent from Reviewable.io -->

2021-09-01 12:15 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 0 of 14 files reviewed, 3 unresolved discussions

___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 255 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-MiWGzpx803xWUkDaSE5:-MiWGzpx803xWUkDaSE6:b-hzolv8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/talpid-core/src/tunnel_state_machine/mod.rs#L255)):*
> ```XML
>         let (offline_tx, mut offline_rx) = mpsc::unbounded();
>         let initial_offline_state_tx = offline_state_tx.clone();
>         tokio::spawn(async move {
> ```

The idea that we might want another channel between the daemon and TSM is relevant here. Instead of having a special channel just for the offline monitor.


<!-- Sent from Reviewable.io -->

2021-09-01 13:03 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 0 of 14 files reviewed, 3 unresolved discussions

___
*[mullvad-rpc/src/availability.rs, line 102 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-MiW-aSsCG0EIF56Xasn:-MiWRsAA0YT3FgYqEXTs:bwcvxto) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/mullvad-rpc/src/availability.rs#L102)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This seems somewhat shaky. Might be mostly on Windows because the offline monitor doesn't wait for routes. Should it wait for while to see if the state flips off again or is that too hacky?
</blockquote></details>

This appears to work fine, actually.


<!-- Sent from Reviewable.io -->

2021-09-02 10:31 UTC, pinkisemils reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 1508 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-MiVz3Lb9T-JcKVOKXYo:-Mia15a201Uu111_k9uw:bvacnkd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/mullvad-daemon/src/lib.rs#L1508)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Maybe it wasn't ideal to implement this logic here? Would it be better to hide it in `mullvad-rpc`? Similarly, "waiting" could be implemented on `MullvadRestHandle`, so that one could do stuff like this:

```
let mut handle = rpc_runtime.mullvad_rest_handle();
handle.block_while_offline(true);
let proxy = AccountsProxy::new(handle);
proxy.get_expiry().await;
```

The RPC proxy objects would call something like `availability.set_account_valid(true)` to update the status.
</blockquote></details>

Should the scheduling be moved to `mullvad-rpc`? No, I think maybe there should be a module/struct for managing the account data. But I do feel like making the handle block seems to be a good idea - however, we have to be careful not to block the daemon whenever someone executes an RPC that would eventually hit the API - blocking the daemon's main loop is a no go. 


<!-- Sent from Reviewable.io -->

2021-09-02 10:32 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 0 of 14 files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 2432 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-Mia36A53ojJ227sTakO:-Mia36A53ojJ227sTakP:b-nvq01e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/mullvad-daemon/src/lib.rs#L2432)):*
> ```XML
>         mut offline_state_rx: mpsc::UnboundedReceiver<bool>,
>     ) {
>         let initial_state = offline_state_rx
> ```

Does the TSM publish the offline state as soon as it is spawned? If not, this is a dangerous place to block.


<!-- Sent from Reviewable.io -->

2021-09-02 10:35 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 0 of 14 files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 1508 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-MiVz3Lb9T-JcKVOKXYo:-Mia3e1e81wlBWSWz5Rz:bujeygp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/mullvad-daemon/src/lib.rs#L1508)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Should the scheduling be moved to `mullvad-rpc`? No, I think maybe there should be a module/struct for managing the account data. But I do feel like making the handle block seems to be a good idea - however, we have to be careful not to block the daemon whenever someone executes an RPC that would eventually hit the API - blocking the daemon's main loop is a no go. 
</blockquote></details>

Maybe the rest handle should just have 
___
*[mullvad-daemon/src/relays.rs, line 1132 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-Mia3pf8-y9_Yj13zM2r:-Mia3pf936w0m08zRxKC:b-4h8gt8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/mullvad-daemon/src/relays.rs#L1132)):*
> ```XML
>     ) -> impl Future<Output = Result<Option<RelayList>, mullvad_rpc::Error>> + 'static {
>         let download_futures = move || {
>             let available = api_handle.wait_available();
> ```

I think explicitly waiting for the API to be available is the correct thing to do here.


<!-- Sent from Reviewable.io -->

2021-09-02 10:35 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 0 of 14 files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/lib.rs, line 1508 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-MiVz3Lb9T-JcKVOKXYo:-Mia40s94L0AFaa_vU2m:bocv4rh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/mullvad-daemon/src/lib.rs#L1508)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Maybe the rest handle should just have 
</blockquote></details>

Disregard my last comment.


<!-- Sent from Reviewable.io -->

2021-09-02 15:36 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 0 of 14 files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/lib.rs, line 2432 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-Mia36A53ojJ227sTakO:-Mib5IBJ9sITd7vi-avx:b-q7v3tb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/mullvad-daemon/src/lib.rs#L2432)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Does the TSM publish the offline state as soon as it is spawned? If not, this is a dangerous place to block.
</blockquote></details>

Yes, it publishes the initial state to this channel prior to returning from `tunnel_state_machine::spawn`. (If that function succeeded, then the state was posted.)
___
*[mullvad-daemon/src/relays.rs, line 1132 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-Mia3pf8-y9_Yj13zM2r:-Mib6FQg8EKHHaKlrogJ:bx5r17a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/mullvad-daemon/src/relays.rs#L1132)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think explicitly waiting for the API to be available is the correct thing to do here.
</blockquote></details>

Could you elaborate? Is that not what it's doing right now?


<!-- Sent from Reviewable.io -->

2021-09-06 11:58 UTC, pinkisemils reviewed
> Reviewed 4 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 4 of 14 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[mullvad-daemon/src/relays.rs, line 1132 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-Mia3pf8-y9_Yj13zM2r:-Mif8fGa49bHJHxGcL_-:b4843qy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/mullvad-daemon/src/relays.rs#L1132)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could you elaborate? Is that not what it's doing right now?
</blockquote></details>

I'm not saying this is something you should fix, I'm referring to the other discussion about moving the waiting logic right into the API handle so that the waiting would be done automatically - and I prefer the way it's implemented now.
___
*[mullvad-rpc/src/availability.rs, line 102 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-MiW-aSsCG0EIF56Xasn:-MiuXRmgAbNQvJx7W0mF:b6le6se) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/mullvad-rpc/src/availability.rs#L102)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This appears to work fine, actually.
</blockquote></details>

I think this is fine as is.


<!-- Sent from Reviewable.io -->

2021-09-06 12:26 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 4 of 14 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 255 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-MiWGzpx803xWUkDaSE5:-Miv3_ml5BP9KarIozCy:bkrecso) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/talpid-core/src/tunnel_state_machine/mod.rs#L255)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The idea that we might want another channel between the daemon and TSM is relevant here. Instead of having a special channel just for the offline monitor.
</blockquote></details>

Yep, this channel could be generalized.


<!-- Sent from Reviewable.io -->

2021-09-07 14:05 UTC, pinkisemils reviewed
> Reviewed 2 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 6 of 14 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[mullvad-rpc/src/lib.rs, line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-MizeHPQ75zlQAe7YmER:-MizeHPQ75zlQAe7YmES:bxtr2ff) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/mullvad-rpc/src/lib.rs#L85)):*
> ```XML
>                 Arc::new(Box::new(|_| Ok(()))),
>             )?,
>             api_availability: availability::ApiAvailability::new(availability::State::default()),
> ```

This has some slight Steve Ballmer undertones. Maybe we could just import the items declared in the `availability`  module.


<!-- Sent from Reviewable.io -->

2021-09-07 17:48 UTC, pinkisemils reviewed
> Reviewed 6 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-09-07 17:48 UTC, pinkisemils reviewed
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-09-08 11:02 UTC, pinkisemils approved these changes
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-09-08 18:14 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[mullvad-rpc/src/lib.rs, line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-MizeHPQ75zlQAe7YmER:-Mj5aof0DLUxTycExoCC:b2n4n9y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f84973977e880427c3aab3321cd490a88d328171/mullvad-rpc/src/lib.rs#L85)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This has some slight Steve Ballmer undertones. Maybe we could just import the items declared in the `availability`  module.
</blockquote></details>

Lol. Done.


<!-- Sent from Reviewable.io -->

2021-09-10 10:04 UTC, pinkisemils requested changes
> Reviewed 1 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/lib.rs, line 1494 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-MjE6pNREU7wKb8Fs9-h:-MjE6pNS9zMmL1NzaSkQ:b-3n170f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60bef5f6c0c7398a3354c31db77cf339a794460f/mullvad-daemon/src/lib.rs#L1494)):*
> ```XML
>         const RETRY_INTERVAL_FACTOR: u32 = 5;
>         const RETRY_INTERVAL_MAX: Duration = Duration::from_secs(24 * 60 * 60);
> ```

This logic feels like it could be put in it's own module, not unlike the `relay_list`.


<!-- Sent from Reviewable.io -->

2021-09-10 23:05 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: 13 of 15 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[mullvad-daemon/src/lib.rs, line 1494 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937#-MjE6pNREU7wKb8Fs9-h:-MjGwi493EYS27y-v0CH:b-xp165k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60bef5f6c0c7398a3354c31db77cf339a794460f/mullvad-daemon/src/lib.rs#L1494)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This logic feels like it could be put in it's own module, not unlike the `relay_list`.
</blockquote></details>

Done. It doesn't seem perfect but I think it's better.


<!-- Sent from Reviewable.io -->

2021-09-14 13:26 UTC, pinkisemils approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-15 11:40 UTC, merged