Improve connection info
mullvad/mullvadvpn-app pull request #2940
Opened 2021-09-02 11:57 UTC by raksooo

This PR contains fixes for a bunch of issues relating to the connection info in the main view:
* Showing "SECURE CONNECTION" while disconnecting
* Showing the location of the previously connected server while disconnecting
* Showing information about the previous connection before receiving new information while connecting and reconnecting
* Having a delay when entering the disconnecting state (disconnect and reconnect). This is due to the time it takes before the frontend receives the daemon event with the new tunnel status.

To fix these issues I've made the following changes:
* Remove the status label while disconnecting
* Move all location handling code to the renderer since that's where it's used
* Use the location from when last disconnected while disconnecting
* Use location constraints when starting a new connection/reconnection
* Update the renderer state immediately when pressing disconnect/reconnect
* Ignore tunnel state updates that doesn't correspond to the latest action. E.g. Pressing `Connect` followed by `Cancel` before the `connecting` event has arrived ignores the `connecting` event since we've already requested a disconnect.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2940)

2021-09-02 12:38 UTC, pronebird requested changes
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2940)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/app.tsx, line 933 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2940#-MiaU7DN2s-2NOrL-hVy:-MiaU7DN2s-2NOrL-hVz:bn8pko9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76a3a9b2575d6f041d7dadc1cba712fd96ccf9e7/gui/src/renderer/app.tsx#L933)):*
> ```
>  const location = await this.fetchLocation();
> ```
___
*[gui/src/renderer/components/Connect.tsx, line 217 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2940#-MiaVsy_-gF9GnVr5GCh:-MiaVsy_-gF9GnVr5GCi:b-h35cog) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76a3a9b2575d6f041d7dadc1cba712fd96ccf9e7/gui/src/renderer/components/Connect.tsx#L217)):*
> ```XML
> 
>     return status.state === 'connecting' ||
>       (status.state === 'disconnecting' && status.details === 'reconnect')
> ```

Does reconnect happen too fast or what's the reason behind removing the spinner in that state?


<!-- Sent from Reviewable.io -->

2021-09-02 12:42 UTC, pronebird reviewed
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2940)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2021-09-02 13:21 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2940)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/renderer/components/Connect.tsx, line 217 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2940#-MiaVsy_-gF9GnVr5GCh:-MiaeXnICHnl0eaidcD9:b-lepl3v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/76a3a9b2575d6f041d7dadc1cba712fd96ccf9e7/gui/src/renderer/components/Connect.tsx#L217)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Does reconnect happen too fast or what's the reason behind removing the spinner in that state?
</blockquote></details>

It wasn't showing while disconnecting, it was showing while reconnecting. The first thing that happens when reconnecting is that the app enters the disconnecting state with `reconnect` in the `property`. Now I've changed it so that it shows in the disconnected state both during reconnect and regular disconnect.


<!-- Sent from Reviewable.io -->

2021-09-06 10:13 UTC, pronebird reviewed
> Reviewed 1 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2940)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2021-09-06 11:20 UTC, pronebird approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2940)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-06 12:45 UTC, merged