Refactor AppStoreReceipt
mullvad/mullvadvpn-app pull request #2957
Opened 2021-09-14 11:38 UTC by pronebird

Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

1. Make sure that `ReceiptRefreshOperation` run on serial `OperationQueue`. Since that call triggers system "Sign in with AppStore" prompt, it's better if we avoid possibility of running two of such operations side by side.
2. Handle `CocoaError.fileReadNoSuchFile` when reading AppStore receipt from disk. I am pretty sure that in the past `fileNoSuchFile` was thrown instead. Map both to `AppStoreReceipt.Error.doesNotExist`.
3. Move `ReceiptRefreshOperation` to separate source file.

2021-09-14 14:09 UTC, raksooo requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2957)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/AppStoreReceipt.swift, line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2957#-MjZbmT-08Jhb4ZVLBaH:-MjZbmT-08Jhb4ZVLBaI:bfyfgx2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14827d8e80b7d9271addfe5d6586c4eb6380a48d/ios/MullvadVPN/AppStoreReceipt.swift#L46)):*
> ```Swift
>     /// This call may trigger a sign in with AppStore prompt to appear.
>     static func fetch(forceRefresh: Bool = false, receiptProperties: [String: Any]? = nil) -> Result<Data, Error>.Promise {
>         guard forceRefresh else {
> ```

Shouldn't this be
```
guard !forceRefresh else {
```
So that we only skip reading from disk when `forceRefresh` is true?


<!-- Sent from Reviewable.io -->

2021-09-15 08:31 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2957)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[ios/MullvadVPN/AppStoreReceipt.swift, line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2957#-MjZbmT-08Jhb4ZVLBaH:-Mjc_8ONEMKyXpcv8PdX:ba341ky) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14827d8e80b7d9271addfe5d6586c4eb6380a48d/ios/MullvadVPN/AppStoreReceipt.swift#L46)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Shouldn't this be
```
guard !forceRefresh else {
```
So that we only skip reading from disk when `forceRefresh` is true?
</blockquote></details>

You're right! Good spot! Maybe I should avoid using `guard` here and just do old fashion `if`?


<!-- Sent from Reviewable.io -->

2021-09-15 08:34 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2957)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[ios/MullvadVPN/AppStoreReceipt.swift, line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2957#-MjZbmT-08Jhb4ZVLBaH:-Mjc_uI-22D2PvuTEpRO:b-x05hbj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14827d8e80b7d9271addfe5d6586c4eb6380a48d/ios/MullvadVPN/AppStoreReceipt.swift#L46)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You're right! Good spot! Maybe I should avoid using `guard` here and just do old fashion `if`?
</blockquote></details>

Reverted to the old code that used `if` branch. Less confusing since we don't have to inverse the condition


<!-- Sent from Reviewable.io -->

2021-09-15 09:00 UTC, raksooo approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2957#-:-MjcfnOS5DzjuKhYStXV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ios/MullvadVPN/AppStoreReceipt.swift, line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2957#-MjZbmT-08Jhb4ZVLBaH:-Mjcfh0I3ARcvvl6C3kJ:boddrvw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14827d8e80b7d9271addfe5d6586c4eb6380a48d/ios/MullvadVPN/AppStoreReceipt.swift#L46)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Reverted to the old code that used `if` branch. Less confusing since we don't have to inverse the condition
</blockquote></details>

Looks good :+1:


<!-- Sent from Reviewable.io -->

2021-09-15 09:05 UTC, merged