Fix intermittent tunnel device errors
mullvad/mullvadvpn-app pull request #2970
Opened 2021-09-17 12:28 UTC by dlon

Changes:
* Try to create Wintun devices multiple times if an error occurs. This is to work around poorly understood races/delays that can occur when resuming from hibernation or reboot.
* Small amount of refactoring.

2021-09-17 12:33 UTC, dlon reviewed
CI is complaining about unstable features. It must not be using the latest stable Rust.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970#-:-Mjnj1js6B6Ic_xdcftE:b-xj3iz)* status: 0 of 4 files reviewed, 2 unresolved discussions

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 407 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970#-MjnjI4h5wuz623y2nTS:-MjnjI4h5wuz623y2nTT:bprha7g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd15a3c834fb1421abcf3f449433c0a6a785e933/talpid-core/src/tunnel/openvpn/mod.rs#L407)):*
> ```XML
>                     attempt
>                 );
>                 std::thread::sleep(std::time::Duration::from_secs(1));
> ```

I don't love this. It makes the daemon unresponsive for up to five seconds. This probably needs to happen in a separate thread.
___
*[wireguard/libwg/libwg_windows.go, line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970#-Mjnjt5CCiJksymLXAVR:-Mjnjt5CCiJksymLXAVS:b-8kjrmn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd15a3c834fb1421abcf3f449433c0a6a785e933/wireguard/libwg/libwg_windows.go#L85)):*
> ```Go
> 		if wintunErr != nil {
> 			if attempt == MAX_WINTUN_CREATION_ATTEMPTS {
> 				time.Sleep(1 * time.Second)
> ```

Same thing here. This blocks the TSM. But might not be worth it to spend any significant amount of time on the `wireguard-go` impl, so this might have to do.


<!-- Sent from Reviewable.io -->

2021-09-17 13:12 UTC, mvd-ows requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 407 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970#-MjnjI4h5wuz623y2nTS:-Mjno8JX4Jqc1SNbqQ4O:b-bwiopz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd15a3c834fb1421abcf3f449433c0a6a785e933/talpid-core/src/tunnel/openvpn/mod.rs#L407)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I don't love this. It makes the daemon unresponsive for up to five seconds. This probably needs to happen in a separate thread.
</blockquote></details>

The max time spent sleeping is 3 seconds? Given the current synchronous context, is there a reasonable change that will make the daemon more responsive?
___
*[wireguard/libwg/libwg_windows.go, line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970#-MjnsbrN42gQzlMciiYY:-MjnsbrN42gQzlMciiYZ:blvxtl4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd15a3c834fb1421abcf3f449433c0a6a785e933/wireguard/libwg/libwg_windows.go#L84)):*
> ```Go
> 		wintun, wintunErr = tun.CreateTUNWithRequestedGUID(ifaceName, &networkId, mtu)
> 		if wintunErr != nil {
> 			if attempt == MAX_WINTUN_CREATION_ATTEMPTS {
> ```

Invert this comparison.


<!-- Sent from Reviewable.io -->

2021-09-17 13:31 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 407 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970#-MjnjI4h5wuz623y2nTS:-Mjnsw3e8F5e5kaomh70:bezjws) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd15a3c834fb1421abcf3f449433c0a6a785e933/talpid-core/src/tunnel/openvpn/mod.rs#L407)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

The max time spent sleeping is 3 seconds? Given the current synchronous context, is there a reasonable change that will make the daemon more responsive?
</blockquote></details>

Two solutions come to mind:
1. We could return a specific error and have the tunnel state machine reconnect/retry on this error (indefinitely?). Might be the simplest way to go, though it reruns the relay selection, etc.
2. Spawn a blocking tokio thread and run the device creation code there. That task can then be aborted. This is also relatively simple.


<!-- Sent from Reviewable.io -->

2021-09-17 13:35 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @mvd-ows)

___
*[wireguard/libwg/libwg_windows.go, line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970#-MjnsbrN42gQzlMciiYY:-MjnxzJ7EA1B4C2RGpKw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd15a3c834fb1421abcf3f449433c0a6a785e933/wireguard/libwg/libwg_windows.go#L84)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Invert this comparison.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-17 13:38 UTC, mvd-ows requested changes
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[wireguard/libwg/libwg_windows.go, line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970#-MjnsbrN42gQzlMciiYY:-MjnyUgU1jTXF6eKuYNY:b-vg19l8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd15a3c834fb1421abcf3f449433c0a6a785e933/wireguard/libwg/libwg_windows.go#L84)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, I meant the test should be for inequality. If you have not yet reached max tries you sleep and go again.


<!-- Sent from Reviewable.io -->

2021-09-17 13:44 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @mvd-ows)

___
*[wireguard/libwg/libwg_windows.go, line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970#-MjnsbrN42gQzlMciiYY:-MjnzVPA9n0zdT48V3WX:b-4ossuy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd15a3c834fb1421abcf3f449433c0a6a785e933/wireguard/libwg/libwg_windows.go#L84)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

No, I meant the test should be for inequality. If you have not yet reached max tries you sleep and go again.
</blockquote></details>

Wow. Fixed.


<!-- Sent from Reviewable.io -->

2021-09-17 13:59 UTC, mvd-ows approved these changes
> Reviewed 1 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970)* status: all files reviewed, 1 unresolved discussion

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 407 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970#-MjnjI4h5wuz623y2nTS:-Mjo2P94D7ZE6lbGeq4_:b-tl50cd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd15a3c834fb1421abcf3f449433c0a6a785e933/talpid-core/src/tunnel/openvpn/mod.rs#L407)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Two solutions come to mind:
1. We could return a specific error and have the tunnel state machine reconnect/retry on this error (indefinitely?). Might be the simplest way to go, though it reruns the relay selection, etc.
2. Spawn a blocking tokio thread and run the device creation code there. That task can then be aborted. This is also relatively simple.
</blockquote></details>

I don't have a strong opinion on this. I suggest you consult with faern before merging.


<!-- Sent from Reviewable.io -->

2021-09-20 11:31 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @mvd-ows)

___
*[talpid-core/src/tunnel/openvpn/mod.rs, line 407 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970#-MjnjI4h5wuz623y2nTS:-Mk1yMkr9Yunz0YukPmO:b-ltzzv0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd15a3c834fb1421abcf3f449433c0a6a785e933/talpid-core/src/tunnel/openvpn/mod.rs#L407)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

I don't have a strong opinion on this. I suggest you consult with faern before merging.
</blockquote></details>

Done. It no longer blocks.


<!-- Sent from Reviewable.io -->

2021-09-20 12:27 UTC, mvd-ows approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel_state_machine/connecting_state.rs, line 416 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970#-Mk29bAvCagix7HLC3IA:-Mk29bAvCagix7HLC3IB:b8ol74s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/91ca18e9b558491061e0efbfbcdd4b2df3d756eb/talpid-core/src/tunnel_state_machine/connecting_state.rs#L416)):*
> ```XML
> 
> #[cfg_attr(not(target_os = "windows"), allow(unused_variables))]
> fn should_retry(error: &tunnel::Error, retry_attempt: u32) -> bool {
> ```

IMO there's no reason for this function to know about the retry count.

If retry count > threshold you don't even need to call this function.


<!-- Sent from Reviewable.io -->

2021-09-21 10:59 UTC, merged