Make sure time since key was generated is positive
mullvad/mullvadvpn-app pull request #3009
Opened 2021-10-04 11:55 UTC by raksooo

This PR fixes a bug where the app said that a WireGuard key was generated "less than a day left". This was solved by making sure that the key generated date can't be in the future.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-10-04 12:38 UTC, pronebird requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3009)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/WireguardKeys.tsx, line 283 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3009#-MlAEQFK-2hLYYl4T6Hj:-MlAEQFK-2hLYYl4T6Hk:br15p8k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fe8d0180fcc469035b76608312346125760b2ef5/gui/src/renderer/components/WireguardKeys.tsx#L283)):*
> ```XML
>       case 'being-verified': {
>         const createdDate =
>           new Date(keyState.key.created) > new Date() ? Date.now() : keyState.key.created;
> ```

Maybe use `Math.max` to compare the timestamps and pick the one that's not in thee past?

```
let createdDate: number = Math.max(+Date.now(), keyState.key.created)
```


<!-- Sent from Reviewable.io -->

2021-10-04 12:38 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3009#-:-MlAJ0sL1-1J24ti_rvY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2021-10-04 14:52 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3009)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/renderer/components/WireguardKeys.tsx, line 283 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3009#-MlAEQFK-2hLYYl4T6Hj:-MlAmdxf90QJLt268F-O:b2yzpp4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fe8d0180fcc469035b76608312346125760b2ef5/gui/src/renderer/components/WireguardKeys.tsx#L283)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe use `Math.max` to compare the timestamps and pick the one that's not in thee past?

```
let createdDate: number = Math.max(+Date.now(), keyState.key.created)
```
</blockquote></details>

Done. But with `Math.min`.


<!-- Sent from Reviewable.io -->

2021-10-05 07:30 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3009)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @pronebird)

___
*[gui/src/renderer/components/WireguardKeys.tsx, line 283 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3009#-MlAEQFK-2hLYYl4T6Hj:-MlEL4fCCONgzAKE0Mpm:b-bbrr63) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fe8d0180fcc469035b76608312346125760b2ef5/gui/src/renderer/components/WireguardKeys.tsx#L283)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Done. But with `Math.min`.
</blockquote></details>

Right. Oh I thought `keyState.key.created` was a timestamp. :+1: 


<!-- Sent from Reviewable.io -->

2021-10-05 07:30 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3009)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-10-05 11:01 UTC, merged