Add script that detects bidirectional Unicode text
mullvad/mullvadvpn-app pull request #3097
Opened 2021-11-08 11:14 UTC by dlon

Certain Unicode characters can be used to produce code that looks innocuous when rendered in editors, but that contains malicious code. Specifically, they may change the order in which characters appear. Details here: https://www.trojansource.codes/trojan-source.pdf.

This PR includes a script that scans all text and source code for these code points. Rust 1.56.1 already includes lints that [reject](https://blog.rust-lang.org/2021/11/01/cve-2021-42574.html) them, but other compilers may not. The PR also adds a GitHub actions workflow that runs this script.

2021-11-08 12:33 UTC, faern requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[check-codepoints.sh, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097#-MnzWGrh421tPAEuXGBT:-MnzWGrh421tPAEuXGBU:bxcnbt6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/891f9bf9f794a509891a0b73de2054fbd34d3bbe/check-codepoints.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Can we please put this into `ci/` to not take up space in the repository root?
___
*[check-codepoints.sh, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097#-MnzWkRk3qOto9YIxWwg:-MnzWkRk3qOto9YIxWwh:bghyw0q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/891f9bf9f794a509891a0b73de2054fbd34d3bbe/check-codepoints.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Just "check codepoints" is very generic. Check them for what? Would a better script name maybe be `check-trojan-source.sh`?
___
*[check-codepoints.sh, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097#-MnzXALAEnrZcfX2hI9V:-MnzXALAEnrZcfX2hI9W:bjouww0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/891f9bf9f794a509891a0b73de2054fbd34d3bbe/check-codepoints.sh#L4)):*
> ```Shell
> 
> # Script for detecting suspicious code points in source code and text.
> # It assumes UTF-8 encoding.
> ```

It would be great if the script itself refers to the CVE/exploit info website. The PR description is great, but that's not going to be around to inform readers once this is merged. Having the CVE number here somewhere would be great as it increases the discoverability of this when grepping.


<!-- Sent from Reviewable.io -->

2021-11-08 12:54 UTC, faern requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097)* status: all files reviewed, 5 unresolved discussions (waiting on @dlon)

___
*[check-codepoints.sh, line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097#-MnzZ1Is423eXhTjnwyE:-MnzZ1Is423eXhTjnwyF:b-2m0d9l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/891f9bf9f794a509891a0b73de2054fbd34d3bbe/check-codepoints.sh#L10)):*
> ```Shell
> export LC_ALL=en_US.UTF-8
> 
> CODEPOINT_REGEX=$( printf "\u202a\|\u202b\|\u202c\|\u202d\|\u202e\|\u2066\|\u2067\|\u2068\|\u2069" )
> ```

The reason for referring to the CVE/some authoritative document on this is so that this otherwise magical constant has some context to live under :)
___
*[check-codepoints.sh, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097#-MnzZjN05_s22vkjf_JB:-MnzZjN05_s22vkjf_JC:byckjvz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/891f9bf9f794a509891a0b73de2054fbd34d3bbe/check-codepoints.sh#L14)):*
> ```Shell
> cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
> 
> #FILES=( $( find -type f -regex '.*\.\(rs\|cpp\|c\|cc\|h\|kt\|swift\|toml\)' ) )
> ```

Is this left over from testing, or what's the purpose of this comment?
___
*[check-codepoints.sh, line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097#-Mnz__sX2b6eT25PYe4L:-Mnz__sX2b6eT25PYe4M:bjqynct) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/891f9bf9f794a509891a0b73de2054fbd34d3bbe/check-codepoints.sh#L33)):*
> ```Shell
> if echo "$SAFE_STR" | grep -q "${CODEPOINT_REGEX}"; then
>     echo "Incorrectly detected code point in test string"
>     exit 1
> ```

Tests are good! But if the code under test is just duplicated instead of reused we don't have any guarantees that the real check code will remain working.I suggest refactoring the actual checking for bad code points into a bash function that we can then call with the known good/bad strings and then start working on the real files?

Or something else. The way the code sits now I feel there is a substantial risk of the real code breaking without these tests actually catching it. If that's the case we can make do without the tests.


<!-- Sent from Reviewable.io -->

2021-11-08 14:21 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @faern)

___
*[check-codepoints.sh, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097#-MnzWGrh421tPAEuXGBT:-Mnzu7qR3PfFN23SqhMh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/891f9bf9f794a509891a0b73de2054fbd34d3bbe/check-codepoints.sh#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we please put this into `ci/` to not take up space in the repository root?
</blockquote></details>

Done.
___
*[check-codepoints.sh, line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097#-MnzXALAEnrZcfX2hI9V:-MnzuHNy1k7iXUWgSaXR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/891f9bf9f794a509891a0b73de2054fbd34d3bbe/check-codepoints.sh#L4)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It would be great if the script itself refers to the CVE/exploit info website. The PR description is great, but that's not going to be around to inform readers once this is merged. Having the CVE number here somewhere would be great as it increases the discoverability of this when grepping.
</blockquote></details>

Done.
___
*[check-codepoints.sh, line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097#-MnzZjN05_s22vkjf_JB:-MnzuRS6AQBHQep8KA7r:b-ofb81s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/891f9bf9f794a509891a0b73de2054fbd34d3bbe/check-codepoints.sh#L14)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is this left over from testing, or what's the purpose of this comment?
</blockquote></details>

I've removed it. I wasn't sure if scanning *everything* was excessive. But it is pretty quick, so I think it's a good idea.
___
*[check-codepoints.sh, line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097#-Mnz__sX2b6eT25PYe4L:-MnzuggjEh6qKAJmirsk:bkv1o8n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/891f9bf9f794a509891a0b73de2054fbd34d3bbe/check-codepoints.sh#L33)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Tests are good! But if the code under test is just duplicated instead of reused we don't have any guarantees that the real check code will remain working.I suggest refactoring the actual checking for bad code points into a bash function that we can then call with the known good/bad strings and then start working on the real files?

Or something else. The way the code sits now I feel there is a substantial risk of the real code breaking without these tests actually catching it. If that's the case we can make do without the tests.
</blockquote></details>

Done. Would it make more sense to always use standard input?


<!-- Sent from Reviewable.io -->

2021-11-08 14:40 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @faern)

___
*[check-codepoints.sh, line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097#-Mnz__sX2b6eT25PYe4L:-MnzzTf98hn-hKB0CR9d:beyoy2r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/891f9bf9f794a509891a0b73de2054fbd34d3bbe/check-codepoints.sh#L33)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. Would it make more sense to always use standard input?
</blockquote></details>

It does this now.


<!-- Sent from Reviewable.io -->

2021-11-09 12:48 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097#-:-Mo3j_vL08uGuKjiMSSS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-09 14:16 UTC, merged