Store locations in english and translate for rendering
mullvad/mullvadvpn-app pull request #3103
Opened 2021-11-10 12:37 UTC by raksooo

Prevent trying to translate translation of city and country name while connecting. This is accomplished by not storing translated locations in the Redux state and instead translating while rendering.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2021-11-15 13:35 UTC, pronebird requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3103)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/LocationList.tsx, line 287 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3103#-MoYnKzEEebFPJVNUgfM:-MoYnKzF0QTXsHrCaj3j:b-u11bsc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f8d0625e6ef73bf0ec9759fc42bfe8a2257fd91/gui/src/renderer/components/LocationList.tsx#L287)):*
> ```XML
>             <LocationRow
>               key={getLocationKey(countryLocation)}
>               name={relayLocations.gettext(relayCountry.name)}
> ```

The app may not know new locations introduced via relay list, hence it's better to fallback to original English name than show empty string. This was achieved previously by using the `||` operator, i.e:

```
relayLocations.gettext(city) || city;
```


<!-- Sent from Reviewable.io -->

2021-11-15 13:35 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3103)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/renderer/components/LocationList.tsx, line 303 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3103#-MoYnt3R9HREDzjP4olH:-MoYnt3R9HREDzjP4olI:brhumzt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f8d0625e6ef73bf0ec9759fc42bfe8a2257fd91/gui/src/renderer/components/LocationList.tsx#L303)):*
> ```XML
>                   <LocationRow
>                     key={getLocationKey(cityLocation)}
>                     name={relayLocations.gettext(relayCity.name)}
> ```

Same here.


<!-- Sent from Reviewable.io -->

2021-11-15 13:36 UTC, pronebird reviewed
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3103)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2021-11-15 15:09 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3103)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird and @raksooo)

___
*[gui/src/renderer/components/LocationList.tsx, line 287 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3103#-MoYnKzEEebFPJVNUgfM:-MoZ8AoFADJKxgXH0bA8:b-caw7v4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f8d0625e6ef73bf0ec9759fc42bfe8a2257fd91/gui/src/renderer/components/LocationList.tsx#L287)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

The app may not know new locations introduced via relay list, hence it's better to fallback to original English name than show empty string. This was achieved previously by using the `||` operator, i.e:

```
relayLocations.gettext(city) || city;
```
</blockquote></details>

`.gettext` already does that for us. If it can't find any translation it will return the original string.


<!-- Sent from Reviewable.io -->

2021-11-16 10:43 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3103)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/components/LocationList.tsx, line 287 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3103#-MoYnKzEEebFPJVNUgfM:-MocKvnF01txOoHydIxD:b-ssb8je) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f8d0625e6ef73bf0ec9759fc42bfe8a2257fd91/gui/src/renderer/components/LocationList.tsx#L287)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

`.gettext` already does that for us. If it can't find any translation it will return the original string.
</blockquote></details>

Oh does it? I thought it used to return `undefined`.


<!-- Sent from Reviewable.io -->

2021-11-16 10:43 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3103)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-16 11:16 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3103#-:-MocSgb87YR2nQQbi9d6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-16 11:22 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3103)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[gui/src/renderer/components/LocationList.tsx, line 287 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3103#-MoYnKzEEebFPJVNUgfM:-MocTtn38wuWSJA7qUMe:b-mq6xju) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f8d0625e6ef73bf0ec9759fc42bfe8a2257fd91/gui/src/renderer/components/LocationList.tsx#L287)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Oh does it? I thought it used to return `undefined`.
</blockquote></details>

Yep, here's the documentation:
```
Returns: String - Translation or the original string if no translation was found
```


<!-- Sent from Reviewable.io -->

2021-11-16 11:38 UTC, merged