Add DNS resovler for macOS
mullvad/mullvadvpn-app pull request #3138
Opened 2021-11-22 18:09 UTC by pinkisemils

Adds a custom resolver for macOS to optionally allow specific hosts to be reached when otherwise all traffic would be dropped. Currently, the only allowed host is `captive.apple.com`.

2021-11-23 09:36 UTC, dlon reviewed
> Reviewed 9 of 34 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 9 of 34 files reviewed, 5 unresolved discussions (waiting on @pinkisemils)

___
*[CHANGELOG.md, line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpB0gHw1HAQLF9OKet3:-MpB0gHx-aJAC2RnZ9M0:bmvbhff) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/CHANGELOG.md#L29)):*
> ```Markdown
> #### macOS
> - Add custom resolver to allow macOS connectivity check reach `captive.apple.com` when the firewall would otherwise block
>   such traffic.
> ```

This should mention the problem that it fixes from users' point of view, IMO.
___
*[mullvad-cli/src/cmds/dns.rs, line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpB3zQR83fHlQlEqGG0:-MpB3zQR83fHlQlEqGG1:b-g313ne) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/mullvad-cli/src/cmds/dns.rs#L46)):*
> ```XML
>         #[cfg(target_os = "macos")]
>         let set_subcommand = set_subcommand.subcommand(
>             clap::SubCommand::with_name("custom-resolver")
> ```

To me, "custom resolver" is too generic for what this does currently. It probably gives the impression that the resolver is active all the time. (This applies elsewhere too.)
___
*[mullvad-daemon/src/exclusion_gid.rs, line 7 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpB5RPh4E4mkRskL7J_:-MpB5RPh4E4mkRskL7Ja:bkzj4v4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/mullvad-daemon/src/exclusion_gid.rs#L7)):*
> ```XML
> /// Returns the GID of `mullvad-exclusion` group if it exists.
> pub fn get_exclusion_gid() -> Option<u32> {
>     let exclusion_group_name = unsafe { CStr::from_ptr(EXCLUSION_GROUP.as_ptr() as *const i8) };
> ```

Could you use `CStr::from_bytes_with_nul_unchecked(EXCLUSION_GROUP)` here?
___
*[mullvad-daemon/src/lib.rs, line 244 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpB7uc-Bf2IJhDMgcQJ:-MpB7uc-Bf2IJhDMgcQK:b-1ar0k2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/mullvad-daemon/src/lib.rs#L244)):*
> ```XML
>     #[cfg(target_os = "macos")]
>     SetCustomResolver(
>         ResponseTx<(), Either<settings::Error, talpid_core::resolver::Error>>,
> ```

Instead of using `Either`, this could return `Error`, and a new variant could be added. This is fine, though.
___
*[mullvad-daemon/src/lib.rs, line 2232 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpB75C57jRKBZKtiBwZ:-MpB75C64mh7pW8vxWeX:bgjov7t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/mullvad-daemon/src/lib.rs#L2232)):*
> ```XML
>         enable_custom_resolver: bool,
>     ) {
>         // TODO: add custom error type instead of retunring a bool
> ```

Comment is no longer true?


<!-- Sent from Reviewable.io -->

2021-11-23 12:15 UTC, dlon reviewed
> Reviewed 8 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 17 of 34 files reviewed, 6 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/src/macos.rs, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpBCsC8762lIUP0y5v3:-MpBBLDI8mRiE-_j-FEF:bmjfle3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/talpid-core/src/macos.rs#L5)):*
> ```XML
> /// Returns the GID of `mullvad-exclusion` group if it exists.
> pub fn get_group_id(group_name: &CStr) -> Option<u32> {
>     let group = unsafe { libc::getgrnam(group_name.as_ptr() as *const _) };
> ```

Probably does not matter: The buffer behind this is shared across the thread. I can think of some unlikely scenarios in which this might cause problems.
___
*[talpid-core/src/dns/server/mod.rs, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpBIy_80NKtzGJtGiqQ:-MpBIy_80NKtzGJtGiqR:btccnez) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/talpid-core/src/dns/server/mod.rs#L1)):*
> ```XML
> use 
> ```

Included by mistake?


<!-- Sent from Reviewable.io -->

2021-11-23 15:49 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 12 of 34 files reviewed, 7 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[CHANGELOG.md, line 28 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpCTtu9CB9kKVArY9vh:-MpCTtuABjq3sXu8EVi8:bwqar6y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ab4e6c2a39fe82e15234de3ecf53921b40dcc521/CHANGELOG.md#L28)):*
> ```Markdown
> ### Added
> #### macOS
> - Add custom resolver to allow macOS connectivity check reach `captive.apple.com` when the firewall would otherwise block
> ```

* Custom **DNS** resolver
* check **to** reach
?


<!-- Sent from Reviewable.io -->

2021-11-23 16:38 UTC, dlon approved these changes
> Reviewed 7 of 34 files at r1, 15 of 15 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 9 unresolved discussions (waiting on @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpCQr7I6-uxfoeFo3M5:-MpCQr7J3W7OtrCladd8:b-5ad8n9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a81cd52ba3a6f56d6dc5fc6fe300dee554992c32/talpid-core/src/firewall/macos.rs#L168)):*
> ```XML
>                     rules.append(&mut self.get_block_dns_rules()?);
>                     rules.append(&mut self.get_allow_lan_rules()?);
>                     rules.append(&mut self.get_allow_ips_rules(&allowed_ips)?);
> ```

Is this actually supposed to depend on `allow_lan`? I'm assuming it's meant to unconditionally allow incoming packets except for port 53.
___
*[talpid-core/src/resolver/conn_provider.rs, line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpCTzr41RfsyHE79Rec:-MpCTzr56-dhMFbXdrTw:bgqvbvl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a81cd52ba3a6f56d6dc5fc6fe300dee554992c32/talpid-core/src/resolver/conn_provider.rs#L1)):*
> ```XML
> use std::{future::Future, pin::Pin, time::Duration, net::SocketAddr};
> ```

Also not used?
___
*[talpid-core/src/resolver/mod.rs, line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpBoJItCUcTV7wHVlYx:-MpBoJItCUcTV7wHVlYy:b-gh2wbv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/talpid-core/src/resolver/mod.rs#L82)):*
> ```XML
>     port: u16,
> ) {
>     let mut builder = tokio::runtime::Builder::new_multi_thread();
> ```

Can't we just pass in a `tokio::runtime::Handle` for the existing runtime? Or is there a reason for the separate runtime?
___
*[talpid-core/src/resolver/mod.rs, line 88 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpBjeqp9i2-K591JUZn:-MpBjeqp9i2-K591JUZo:b4vy28w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/talpid-core/src/resolver/mod.rs#L88)):*
> ```XML
>     builder.on_thread_start(move || {
>         #[cfg(target_os = "macos")]
>         if let Some(gid) = exclusion_gid.clone() {
> ```

Unnecessary clone.
___
*[talpid-core/src/resolver/mod.rs, line 314 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpC2Faj0p2HgD3Pq9Ua:-MpC2Faj0p2HgD3Pq9Ub:b-o23yu8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/talpid-core/src/resolver/mod.rs#L314)):*
> ```XML
>     async fn stop_server(&mut self) {
>         if let Some((old_server, done_rx)) = self.dns_server.take() {
>             old_server.abort();
> ```

Nice. I didn't even know that `JoinHandle` had an `abort` method.
___
*[talpid-core/src/tunnel_state_machine/disconnected_state.rs, line 103 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpCV9WP15_JdnScNz9B:-MpCV9WP15_JdnScNz9C:b-r657aq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a81cd52ba3a6f56d6dc5fc6fe300dee554992c32/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L103)):*
> ```XML
>     fn set_dns(shared_values: &mut SharedTunnelStateValues) {
>         if let Some(ref dns_servers) = shared_values.dns_servers {
>             if let Err(err) = shared_values.dns_monitor.set("lo0", &dns_servers) {
> ```

This should only be done on macOS, right?
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 460 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpBvRNu4qzbZdFOEpsb:-MpBvRNu4qzbZdFOEpsc:b-wapvxs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/talpid-core/src/tunnel_state_machine/mod.rs#L460)):*
> ```XML
>     pub fn deactivate_custom_resolver(
>         &mut self,
>         enable_resolver: bool,
> ```

This is slightly confusing, I think. `deactivate_custom_resolver(true)` enables the resolver but deactivates it, and `deactivate_custom_resolver(false)` shuts it down. But not too important.
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 211 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpCZLre-mDzsXXNi3uw:-MpCZLre-mDzsXXNi3ux:b-owtrns) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a81cd52ba3a6f56d6dc5fc6fe300dee554992c32/talpid-core/src/tunnel_state_machine/mod.rs#L211)):*
> ```XML
>     /// Sets IP addresses which should be allowed to pass through the firewall.
>     #[cfg(target_os = "macos")]
>     AddAllowedIps(BTreeSet<IpAddr>, oneshot::Sender<()>),
> ```

Not important right now, but I wonder if this could be merged with `AllowEndpoint`.


<!-- Sent from Reviewable.io -->

2021-11-23 17:29 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 33 of 34 files reviewed, 9 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-cli/src/cmds/dns.rs, line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpB3zQR83fHlQlEqGG0:-MpCAY2o0UwELVskNeg3:b85psx1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/mullvad-cli/src/cmds/dns.rs#L46)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

To me, "custom resolver" is too generic for what this does currently. It probably gives the impression that the resolver is active all the time. (This applies elsewhere too.)
</blockquote></details>

This is a valid concern, but this is the terminology we've been using for the development of the project. I'm in favor of changing it, but we should probably discuss this elsewhere.
___
*[mullvad-daemon/src/lib.rs, line 244 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpB7uc-Bf2IJhDMgcQJ:-MpCB6xC842Ab_7B8Xk1:b23y0fi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/mullvad-daemon/src/lib.rs#L244)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Instead of using `Either`, this could return `Error`, and a new variant could be added. This is fine, though.
</blockquote></details>

This would necessitate a new error enum with exactly two variants, as such I decided not to do that.
___
*[talpid-core/src/macos.rs, line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpBCsC8762lIUP0y5v3:-MpCBboH1k7rLDPNnmmR:b7e3cg4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/talpid-core/src/macos.rs#L5)):*
https://developers.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/getgrent.3.html
> All of these routines are thread-safe.
Using the same buffer should be fine.
___
*[talpid-core/src/dns/server/mod.rs, line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpBIy_80NKtzGJtGiqQ:-MpCBoRu9VJSQ6nnC5TW:bb77ucv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/talpid-core/src/dns/server/mod.rs#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Included by mistake?
</blockquote></details>

Yep.


<!-- Sent from Reviewable.io -->

2021-11-23 17:30 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 33 of 34 files reviewed, 9 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpCQr7I6-uxfoeFo3M5:-MpCqDX67eEgOnY3wKV1:b1f7lhf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a81cd52ba3a6f56d6dc5fc6fe300dee554992c32/talpid-core/src/firewall/macos.rs#L168)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is this actually supposed to depend on `allow_lan`? I'm assuming it's meant to unconditionally allow incoming packets except for port 53.
</blockquote></details>

Good catch, this should be enabled regardless of LAN settings.


<!-- Sent from Reviewable.io -->

2021-11-24 08:49 UTC, dlon reviewed
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 7 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpCQr7I6-uxfoeFo3M5:-MpE-UMj1wsUvse60by4:b896gum) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a81cd52ba3a6f56d6dc5fc6fe300dee554992c32/talpid-core/src/firewall/macos.rs#L168)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Good catch, this should be enabled regardless of LAN settings.
</blockquote></details>

Should we still add `get_block_dns_rules()` before the allowed IPs rules, or is it okay to leak not to block port 53?
___
*[talpid-core/src/firewall/macos.rs, line 160 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpE5-Us9VKQg82FXKWA:-MpE5-Us9VKQg82FXKWB:b-nmacm2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df5a2792256f723dd7b587ba8d37b6122ceb21f9/talpid-core/src/firewall/macos.rs#L160)):*
> ```XML
>                 rules.push(self.get_allowed_endpoint_rule(allowed_endpoint)?);
> 
>                 rules.extend(self.get_exclusion_rules(&allowed_ips)?);
> ```

Isn't `get_allow_ips_rules` sufficient here?
___
*[talpid-core/src/firewall/macos.rs, line 199 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpE2pyi8tKfwb28VF7p:-MpE2pyi8tKfwb28VF7q:blsrnwd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df5a2792256f723dd7b587ba8d37b6122ceb21f9/talpid-core/src/firewall/macos.rs#L199)):*
> ```XML
>                             .group(exclusion_gid)
>                             .build(),
>                         self.create_rule_builder(FilterRuleAction::Pass)
> ```

Is it possible to set `.keep_state(Keep)` on the UDP out rule instead of having this extra rule?
___
*[talpid-core/src/tunnel_state_machine/disconnected_state.rs, line 110 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpDzLsVA3Z2uKN-jqV_:-MpDzLsW2OqPd8yGoc5i:b2d114a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df5a2792256f723dd7b587ba8d37b6122ceb21f9/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L110)):*
> ```XML
>     }
> 
>     fn reset_dns(shared_values: &mut SharedTunnelStateValues) {
> ```

This should probably also be called on macOS only as well.


<!-- Sent from Reviewable.io -->

2021-11-24 11:56 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 6 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpCQr7I6-uxfoeFo3M5:-MpCuns8CqX5X5hT2ZSG:b-bet9wp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a81cd52ba3a6f56d6dc5fc6fe300dee554992c32/talpid-core/src/firewall/macos.rs#L168)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Good catch, this should be enabled regardless of LAN settings.
</blockquote></details>

This exposed an issue with UDP rules for allowed resolvers, which now has been addressed :thumbsup: .
___
*[talpid-core/src/firewall/macos.rs, line 199 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpE2pyi8tKfwb28VF7p:-MpGnIjv7nvonyRq2g6r:bgmi3nz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df5a2792256f723dd7b587ba8d37b6122ceb21f9/talpid-core/src/firewall/macos.rs#L199)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is it possible to set `.keep_state(Keep)` on the UDP out rule instead of having this extra rule?
</blockquote></details>

There is no state in UDP.
___
*[talpid-core/src/resolver/mod.rs, line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpBoJItCUcTV7wHVlYx:-MpCvOLFCL0tOIjHYjl7:b-rqfega) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/talpid-core/src/resolver/mod.rs#L82)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Can't we just pass in a `tokio::runtime::Handle` for the existing runtime? Or is there a reason for the separate runtime?
</blockquote></details>

It needs to be a separate runtime unfortunately, as the worker threads should have a specific group ID that allows the firewall to allow the resolver traffic to _leak_. This basically is a poor man's split tunneling implementation.
___
*[talpid-core/src/tunnel_state_machine/disconnected_state.rs, line 103 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpCV9WP15_JdnScNz9B:-MpCvpN_-fghswAimDD9:b-jli521) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a81cd52ba3a6f56d6dc5fc6fe300dee554992c32/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L103)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This should only be done on macOS, right?
</blockquote></details>

Correct! However, the counterpart, `reset_dns()` could well be called on all platforms without any issues, IMO, since it will be a no-op there.  Not quite sure if those calls should be conditionally compiled only for macOS too. 
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 460 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpBvRNu4qzbZdFOEpsb:-MpCw-SkAQdY-etLmtqb:b-ja0wsk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/talpid-core/src/tunnel_state_machine/mod.rs#L460)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is slightly confusing, I think. `deactivate_custom_resolver(true)` enables the resolver but deactivates it, and `deactivate_custom_resolver(false)` shuts it down. But not too important.
</blockquote></details>

It is an awkward tristate of unbound to port 53, bound to port 53 and not resolving and bound to port 53 *and* resolving. 
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 211 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpCZLre-mDzsXXNi3uw:-MpCvs9V8LlXNe32sgpY:b428l4u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a81cd52ba3a6f56d6dc5fc6fe300dee554992c32/talpid-core/src/tunnel_state_machine/mod.rs#L211)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Not important right now, but I wonder if this could be merged with `AllowEndpoint`.
</blockquote></details>

It should be different sets of addresses IMO, as one set should be cleared during tunnel state transitions. 


<!-- Sent from Reviewable.io -->

2021-11-24 12:43 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 199 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpE2pyi8tKfwb28VF7p:-MpGunek5pJ-99voQ6Bv:b-u7fkc1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df5a2792256f723dd7b587ba8d37b6122ceb21f9/talpid-core/src/firewall/macos.rs#L199)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

There is no state in UDP.
</blockquote></details>

Of course, but doesn't pf have some notion of it anyway? https://www.openbsd.org/faq/pf/filter.html#udpstate
___
*[talpid-core/src/resolver/mod.rs, line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpBoJItCUcTV7wHVlYx:-MpGvJnn15IO0YEZgAmf:b2gm18x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/talpid-core/src/resolver/mod.rs#L82)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It needs to be a separate runtime unfortunately, as the worker threads should have a specific group ID that allows the firewall to allow the resolver traffic to _leak_. This basically is a poor man's split tunneling implementation.
</blockquote></details>

That makes sense. Does `setgid` actually only set the gid for the current thread? On Linux, at least, it seems to do so for all threads in the process.
___
*[talpid-core/src/tunnel_state_machine/disconnected_state.rs, line 103 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpCV9WP15_JdnScNz9B:-MpGxOs0D11kPbXFssaN:bfjz2o9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a81cd52ba3a6f56d6dc5fc6fe300dee554992c32/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L103)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Correct! However, the counterpart, `reset_dns()` could well be called on all platforms without any issues, IMO, since it will be a no-op there.  Not quite sure if those calls should be conditionally compiled only for macOS too. 
</blockquote></details>

That should be fine, yeah.


<!-- Sent from Reviewable.io -->

2021-11-24 17:03 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 199 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpE2pyi8tKfwb28VF7p:-MpHPCql2hR09yckB8iZ:b-bqdyzg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df5a2792256f723dd7b587ba8d37b6122ceb21f9/talpid-core/src/firewall/macos.rs#L199)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Of course, but doesn't pf have some notion of it anyway? https://www.openbsd.org/faq/pf/filter.html#udpstate
</blockquote></details>

You're correct.
___
*[talpid-core/src/resolver/mod.rs, line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpBoJItCUcTV7wHVlYx:-MpHtjkI0sTgLa9BiQzy:b-ugfveb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/talpid-core/src/resolver/mod.rs#L82)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

That makes sense. Does `setgid` actually only set the gid for the current thread? On Linux, at least, it seems to do so for all threads in the process.
</blockquote></details>

It does not, I'll simplify the code.


<!-- Sent from Reviewable.io -->

2021-11-25 15:17 UTC, faern commented
@pinkisemils Should probably update `security.md` with these changes as well before merging. Since this is an opt in "leak" we better document it.

2021-11-29 14:33 UTC, dlon requested changes
> Reviewed 9 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 33 of 35 files reviewed, 7 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-daemon/src/exclusion_gid.rs, line 7 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpg3xy633wnI95QI7GT:-Mpg3xy633wnI95QI7GU:b-krei6r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3fa382d1b88be6628c7125bbfca9c3963b8edf4/mullvad-daemon/src/exclusion_gid.rs#L7)):*
> ```XML
> /// Returns the GID of `mullvad-exclusion` group if it exists.
> pub fn get_exclusion_gid() -> io::Result<u32> {
>     let exclusion_group_name = unsafe { CStr::from_bytes_with_nul_unchecked(EXCLUSION_GROUP) };
> ```

Maybe paranoia, but I realize now that `CStr::from_bytes_with_nul(EXCLUSION_GROUP).unwrap()` might be better. That way, the unit test will fail if `EXCLUSION_GROUP` isn't null-terminated or contains interior null bytes.
___
*[talpid-core/src/macos.rs, line 21 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpg2eqA14JDGnJZi9J0:-Mpg2eqBAQImfhWDlMQc:br9c2eo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3fa382d1b88be6628c7125bbfca9c3963b8edf4/talpid-core/src/macos.rs#L21)):*
> ```XML
>         Ok(())
>     } else {
>         Err(io::Error::from_raw_os_error(result))
> ```

I think `result` will always be `-1`. Use `last_os_error` instead.
___
*[talpid-core/src/macos.rs, line 33 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpg3bdQDSHgmrceue2n:-Mpg3bdQDSHgmrceue2o:bxy5el0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3fa382d1b88be6628c7125bbfca9c3963b8edf4/talpid-core/src/macos.rs#L33)):*
> ```XML
>     };
>     // SAFETY: `&mut limits` is a valid pointer parameter for the getrlimit syscall
>     let status = unsafe { libc::getrlimit(libc::RLIMIT_NOFILE, &mut limits as *mut _) };
> ```

Nit: `as *mut _` isn't necessary, is it? (Because type coercion.)
___
*[talpid-core/src/macos.rs, line 50 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpg3HD614-P24s2pQJ_:-Mpg3HD614-P24s2pQJa:b-7riol) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3fa382d1b88be6628c7125bbfca9c3963b8edf4/talpid-core/src/macos.rs#L50)):*
> ```XML
>     limits.rlim_cur = INCREASED_FILEHANDLE_LIMIT;
>     // SAFETY: `&limits` is a valid pointer parameter for the getrlimit syscall
>     let status = unsafe { libc::setrlimit(libc::RLIMIT_NOFILE, &limits as *const _) };
> ```

Nit: `as *const _` isn't necessary, is it? (Because type coercion.)


<!-- Sent from Reviewable.io -->

2021-11-29 20:21 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 20 of 35 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/macos.rs, line 21 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpg2eqA14JDGnJZi9J0:-MpgcXqn4t3bYgfdehPS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3fa382d1b88be6628c7125bbfca9c3963b8edf4/talpid-core/src/macos.rs#L21)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think `result` will always be `-1`. Use `last_os_error` instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-30 14:16 UTC, dlon requested changes
> Reviewed 1 of 11 files at r6, 17 of 18 files at r7, 4 of 5 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 37 of 39 files reviewed, 9 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[docs/security.md, line 219 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpkYYuSCm_mmyLyCo87:-MpkYYuSCm_mmyLyCo88:b-cpmiec) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e705e70be0a2512676dd845f305e933f9c29a04c/docs/security.md#L219)):*
> ```Markdown
> So rather than failing open, meaning if the tunnel fails your traffic leaves in other ways,
> we fail closed, meaning if the packets don't leave encrypted in the way the app intends,
> then they can't leave at all. However, to help the app get a working connection, an exclusion rule
> ```

Incomplete?
___
*[gui/locales/messages.pot, line 1288 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpl7wXA6ZhFXrLPD-fm:-Mpl7wXA6ZhFXrLPD-fn:b-wxxzov) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f42798e6bff9a4acefca3982307458b5ab474f70/gui/locales/messages.pot#L1288)):*
> ```pot
> msgid "WireGuard settings"
> msgstr ""
> ```

Were all of these strings supposed to disappear?
___
*[talpid-core/src/firewall/macos.rs, line 179 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpkbfCk1TdTZBmuANUY:-MpkbfCk1TdTZBmuANUZ:b-n3kqxf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edb734604586ebcd4fbfd225577a70b3b3500d76/talpid-core/src/firewall/macos.rs#L179)):*
> ```XML
>     fn get_allow_excluded_dns_rules(&self) -> Result<[pfctl::FilterRule; 4]> {
>         Ok([
>             self.create_rule_builder(FilterRuleAction::Pass)
> ```

Nice! This is very optional but I suppose it could be made even simpler by reusing a builder:
```
        let builder = self.create_rule_builder(FilterRuleAction::Pass)
            .direction(pfctl::Direction::Out)
            .quick(true)
            .keep_state(pfctl::StatePolicy::Keep)
            .to(pfctl::Port::from(53))
            .group(self.exclusion_gid);

        Ok([
            builder
                .proto(pfctl::Proto::Udp)
                .build()?,
            builder
                .proto(pfctl::Proto::Tcp)
                .tcp_flags(Self::get_tcp_flags())
                .build()?,
            // self.create_rule_builder ...
        ])
```
___
*[talpid-core/src/firewall/macos.rs, line 196 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpkoGRS0bRWjebrRum8:-MpkoGRS0bRWjebrRum9:bxf8a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edb734604586ebcd4fbfd225577a70b3b3500d76/talpid-core/src/firewall/macos.rs#L196)):*
> ```XML
>                 .group(self.exclusion_gid)
>                 .build()?,
>             self.create_rule_builder(FilterRuleAction::Pass)
> ```

Aren't the rules for localhost required? It looks like the `get_block_dns_rules` ruleset is added if (and only if) `allow_lan` is enabled, in which case those packets will be dropped.

Isn't that also a bug in the existing set of rules, as DNS is leaking to `127/8` if `allow_lan` is `false`? I suppose it isn't a big deal since a local resolver wouldn't be able to make any DNS requests in turn, but it's a bit unexpected.
___
*[talpid-core/src/tunnel_state_machine/disconnected_state.rs, line 223 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpk_0U-0Y9W4kx54_vN:-Mpk_0U-0Y9W4kx54_vO:bbe2oxh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e705e70be0a2512676dd845f305e933f9c29a04c/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L223)):*
> ```XML
>                     Self::register_split_tunnel_addresses(shared_values, true);
>                     #[cfg(target_os = "macos")]
>                     if !block_when_disconnected {
> ```

Isn't this supposed to not be negated?
___
*[talpid-core/src/tunnel_state_machine/disconnected_state.rs, line 231 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpka59c2P9kUpOUWb7T:-Mpka59c2P9kUpOUWb7U:b-leuh90) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e705e70be0a2512676dd845f305e933f9c29a04c/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L231)):*
> ```XML
>                             return NewState(ErrorState::enter(shared_values, block_reason));
>                         }
>                         return SameState(self.into());
> ```

Does `set_firewall_policy` need to be called unconditionally? To apply or remove the blocking policy. Also, it's not being called at all on other OSes now.
___
*[talpid-core/src/tunnel_state_machine/disconnected_state.rs, line 38 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpl9gZn56vBc3V8cplz:-Mpl9gZn56vBc3V8cpm-:b-tdst0m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c654a45f321aa4764c7f29c712f68d562b46c119/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L38)):*
> ```XML
>                 #[cfg(target_os = "macos")]
>                 allow_custom_resolver: shared_values.enable_custom_resolver
>                     && shared_values.block_when_disconnected,
> ```

The second condition is redundant.


<!-- Sent from Reviewable.io -->

2021-11-30 14:59 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 35 of 39 files reviewed, 8 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[docs/security.md, line 219 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpkYYuSCm_mmyLyCo87:-MplLkz33XjICb09-zMp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e705e70be0a2512676dd845f305e933f9c29a04c/docs/security.md#L219)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Incomplete?
</blockquote></details>

Done.
___
*[gui/locales/messages.pot, line 1288 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpl7wXA6ZhFXrLPD-fm:-MplHx5AClsDJYJHcC5D:b-9009k4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f42798e6bff9a4acefca3982307458b5ab474f70/gui/locales/messages.pot#L1288)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Were all of these strings supposed to disappear?
</blockquote></details>

Nope. I do not know what went on here. 
___
*[talpid-core/src/firewall/macos.rs, line 196 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpkoGRS0bRWjebrRum8:-MplIHWhB0pXLp5hrtQM:bnqx12s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edb734604586ebcd4fbfd225577a70b3b3500d76/talpid-core/src/firewall/macos.rs#L196)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Aren't the rules for localhost required? It looks like the `get_block_dns_rules` ruleset is added if (and only if) `allow_lan` is enabled, in which case those packets will be dropped.

Isn't that also a bug in the existing set of rules, as DNS is leaking to `127/8` if `allow_lan` is `false`? I suppose it isn't a big deal since a local resolver wouldn't be able to make any DNS requests in turn, but it's a bit unexpected.
</blockquote></details>

The localhost rules have been removed.
___
*[talpid-core/src/tunnel_state_machine/disconnected_state.rs, line 223 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpk_0U-0Y9W4kx54_vN:-MplJMSF9WL2Vws_9Fxe:b-vxp8r1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e705e70be0a2512676dd845f305e933f9c29a04c/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L223)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Isn't this supposed to not be negated?
</blockquote></details>

Good catch., it isn't. 
___
*[talpid-core/src/tunnel_state_machine/disconnected_state.rs, line 231 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpka59c2P9kUpOUWb7T:-MplJPGo9mHEuHO2kXIo:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e705e70be0a2512676dd845f305e933f9c29a04c/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L231)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Does `set_firewall_policy` need to be called unconditionally? To apply or remove the blocking policy. Also, it's not being called at all on other OSes now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-30 15:19 UTC, dlon reviewed
> Reviewed 1 of 18 files at r7, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 38 of 39 files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 196 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpkoGRS0bRWjebrRum8:-MplPCYl2xNkK54qrJJ5:b-pwen4j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edb734604586ebcd4fbfd225577a70b3b3500d76/talpid-core/src/firewall/macos.rs#L196)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The localhost rules have been removed.
</blockquote></details>

Never mind all of the above. I didn't realize that the loopback rules were added first.


<!-- Sent from Reviewable.io -->

2021-11-30 16:14 UTC, dlon approved these changes
> Reviewed 1 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)



<!-- Sent from Reviewable.io -->

2021-12-01 09:48 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 36 of 39 files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[gui/locales/messages.pot, line 1288 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpl7wXA6ZhFXrLPD-fm:-MppNtNb5GsyDNK836Lc:byqxvo1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f42798e6bff9a4acefca3982307458b5ab474f70/gui/locales/messages.pot#L1288)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

@raksooo, I can't find any of the message IDs in `gui/src`, neither on master, should these IDs have been removed earlier? Or should they not be removed at all?
</blockquote></details>

All of these are added by the `translations-converter` tool in `android/`. To get this file up-to-date you first need to run `npm run update-translations` in the `gui` directory which updates the desktop translations and clears the Adnroid ones, and then run `translations-converter` to re-add the Android ones.


<!-- Sent from Reviewable.io -->

2021-12-01 09:51 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 35 of 39 files reviewed, 4 unresolved discussions (waiting on @dlon, @pinkisemils, and @raksooo)

___
*[gui/locales/messages.pot, line 1288 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpl7wXA6ZhFXrLPD-fm:-MppOyT7-UW31KoBEe9T:b-l2ec13) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f42798e6bff9a4acefca3982307458b5ab474f70/gui/locales/messages.pot#L1288)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

All of these are added by the `translations-converter` tool in `android/`. To get this file up-to-date you first need to run `npm run update-translations` in the `gui` directory which updates the desktop translations and clears the Adnroid ones, and then run `translations-converter` to re-add the Android ones.
</blockquote></details>

Cool, now everything's back to normal :) 


<!-- Sent from Reviewable.io -->

2021-12-01 10:01 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 35 of 39 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[gui/locales/messages.pot, line 1288 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpl7wXA6ZhFXrLPD-fm:-MppQJdUEMyx3W9hB_OZ:bhzvliq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f42798e6bff9a4acefca3982307458b5ab474f70/gui/locales/messages.pot#L1288)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Cool, now everything's back to normal :) 
</blockquote></details>

Great :+1:


<!-- Sent from Reviewable.io -->

2021-12-01 11:37 UTC, dlon approved these changes
> Reviewed 3 of 3 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 191 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpplcaw488Zdoxjf3hu:-Mppl6VGDBPiqmmgMyOd:bb1yqm3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4438b835186fbd7ca28334d6ba9017bb7966aa1e/talpid-core/src/firewall/macos.rs#L191)):*
> ```XML
>                 .tcp_flags(Self::get_tcp_flags())
>                 .build()?,
>             builder.proto(pfctl::Proto::Udp).build()?,
> ```

Does it matter if tcp_flags is set here (since `builder.asdf()` takes `&mut self` rather than return a new builder)? Probably not, but otherwise, maybe just reverse the order.
___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 321 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mppm3m-6iSYaqoFWUG8:-Mppm3m-6iSYaqoFWUG9:bihbw5l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4438b835186fbd7ca28334d6ba9017bb7966aa1e/talpid-core/src/tunnel_state_machine/mod.rs#L321)):*
> ```XML
>         };
> 
>         tokio::task::spawn_blocking(move || {
> ```

Why do this?


<!-- Sent from Reviewable.io -->

2021-12-01 11:46 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 321 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mppm3m-6iSYaqoFWUG8:-MppnmC-47tQPuxXkoG_:b-65m62o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4438b835186fbd7ca28334d6ba9017bb7966aa1e/talpid-core/src/tunnel_state_machine/mod.rs#L321)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Why do this?
</blockquote></details>

Because `DisconnectedState::enter()` calls `runtime.block_on()`. Otherwise, this results in a panic, since this code is executed from an async context.


<!-- Sent from Reviewable.io -->

2021-12-01 12:10 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[talpid-core/src/tunnel_state_machine/mod.rs, line 321 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mppm3m-6iSYaqoFWUG8:-Mppt-Ga5f7UYdiXsj7D:b-4hvi0z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4438b835186fbd7ca28334d6ba9017bb7966aa1e/talpid-core/src/tunnel_state_machine/mod.rs#L321)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Because `DisconnectedState::enter()` calls `runtime.block_on()`. Otherwise, this results in a panic, since this code is executed from an async context.
</blockquote></details>

Got it!


<!-- Sent from Reviewable.io -->

2021-12-01 13:44 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-12-01 18:01 UTC, dlon approved these changes
> Reviewed 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-12-02 09:47 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 6 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[docs/security.md, line 253 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpuSZVx9-k27bvuGjI3:-MpuSZVx9-k27bvuGjI4:b7xeiye) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9a38b54d6af148b43d45679fc4d35085c46473e/docs/security.md#L253)):*
> ```Markdown
> In the other states DNS is simply blocked.
> 
> ## macOS custom resolver
> ```

Should it be a subheading of `DNS`? In other words `###`? Or do you think this should stand by itself since the problem it tries to fix is not by itself DNS-related.

Nitpick: Can we please have empty lines after headers like in the rest of the file?
___
*[docs/security.md, line 255 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpuTI252OlyNJQn39HP:-MpuTI252OlyNJQn39HQ:b92ymbn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9a38b54d6af148b43d45679fc4d35085c46473e/docs/security.md#L255)):*
I think we can explain the problem in a better way "publishing default routes" does not give an intuitive feeling about what problems one might have. Can we start the chapter something like

> macOS performs a connectivity check when it connects to a new network. This typically happens when it wakes up after sleep. macOS will refuse to treat the new network as functional (won't publish default routes) until the connectivity check either returns a correct response, or a timeout expires. If the Mullvad VPN app is engaged, the strict firewall rules preventing leaks will block this connectivity check. The result is that the device will not have any working network, or VPN tunnel until the timeout expires.
___
*[docs/security.md, line 257 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpuSwLCB1T57gIU2IFj:-MpuSwLCB1T57gIU2IFk:bclze4e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9a38b54d6af148b43d45679fc4d35085c46473e/docs/security.md#L257)):*
> ```Markdown
> dependency for publishing default routes, when the app is in the error state or disconnected with
> _always require VPN_ enabled, DNS traffic coming from a mullvad specific group will optionally be
> allowed to bypass the firewall. To allow macOS to perform it's connectivity check, two different
> ```

s/it's/its/
___
*[docs/security.md, line 257 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpuXRwhE9arC1PzNJMy:-MpuXRwiDELID8Q3OaKA:bdq7otm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9a38b54d6af148b43d45679fc4d35085c46473e/docs/security.md#L257)):*
> ```Markdown
> dependency for publishing default routes, when the app is in the error state or disconnected with
> _always require VPN_ enabled, DNS traffic coming from a mullvad specific group will optionally be
> allowed to bypass the firewall. To allow macOS to perform it's connectivity check, two different
> ```

Can we have a new paragraph around here somewhere. Paragraph one explains the problem and paragraph two explains how it's solved?


<!-- Sent from Reviewable.io -->

2021-12-02 09:50 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 7 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[CHANGELOG.md, line 28 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpuY3MiEZ4RqHumuOHv:-MpuY3MiEZ4RqHumuOHw:b329yez) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9a38b54d6af148b43d45679fc4d35085c46473e/CHANGELOG.md#L28)):*
> ```Markdown
> ### Added
> #### macOS
> - Add custom resolver to allow macOS connectivity check reach `captive.apple.com` when the firewall would otherwise block
> ```

Can we please say "DNS resolver" instead of just resolver? :pray: 


<!-- Sent from Reviewable.io -->

2021-12-02 11:04 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 33 of 39 files reviewed, 6 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[docs/security.md, line 253 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpuSZVx9-k27bvuGjI3:-Mpujog5-7jBS_jWycAq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9a38b54d6af148b43d45679fc4d35085c46473e/docs/security.md#L253)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Should it be a subheading of `DNS`? In other words `###`? Or do you think this should stand by itself since the problem it tries to fix is not by itself DNS-related.

Nitpick: Can we please have empty lines after headers like in the rest of the file?
</blockquote></details>

Done.
___
*[docs/security.md, line 257 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpuXRwhE9arC1PzNJMy:-MpujZXb8tklrns8pho0:byiwnxl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9a38b54d6af148b43d45679fc4d35085c46473e/docs/security.md#L257)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we have a new paragraph around here somewhere. Paragraph one explains the problem and paragraph two explains how it's solved?
</blockquote></details>

I've made it into 3, and I've made the problem slightly more vague. I don't think this is the place where the problem should be explained in detail.
___
*[docs/security.md, line 257 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpuSwLCB1T57gIU2IFj:-MpujZeX29rzpu2bZYey:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9a38b54d6af148b43d45679fc4d35085c46473e/docs/security.md#L257)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

s/it's/its/
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-02 11:18 UTC, dlon approved these changes
> Reviewed 6 of 6 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 7 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 166 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpuqbzb-nYnXYK0YVZU:-Mpuqbzb-nYnXYK0YVZV:b-y9wze6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dbb51494e99516de8b8e882b6d9830357f38ea24/talpid-core/src/firewall/macos.rs#L166)):*
> ```XML
>                 if allow_lan {
>                     // Important to block DNS before allow LAN (so DNS does not leak to the LAN)
>                     rules.append(&mut self.get_block_dns_rules()?);
> ```

Can we add these rules unconditionally before `if allow_lan ...`? Feel free to ignore as it probably doesn't matter, but it seems weird to block port 53 for the allowed IPs only if LAN sharing is enabled.


<!-- Sent from Reviewable.io -->

2021-12-02 11:28 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 38 of 39 files reviewed, 7 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 166 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpuqbzb-nYnXYK0YVZU:-Mputbp_-FIvqrND4hx5:benj5ts) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dbb51494e99516de8b8e882b6d9830357f38ea24/talpid-core/src/firewall/macos.rs#L166)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Can we add these rules unconditionally before `if allow_lan ...`? Feel free to ignore as it probably doesn't matter, but it seems weird to block port 53 for the allowed IPs only if LAN sharing is enabled.
</blockquote></details>

I don't think they should be unconditional, as these IPs should only be allowed through when the custom resolver is enabled.


<!-- Sent from Reviewable.io -->

2021-12-02 12:40 UTC, faern requested changes
> Reviewed 1 of 6 files at r17.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 38 of 39 files reviewed, 4 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[docs/security.md, line 260 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpv8xOwEDOU47b0y0b0:-Mpv8xOwEDOU47b0y0b1:b5s5u3w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1ddacc8d7c9164c5382f86ce8d5128e6e7d716b/docs/security.md#L260)):*
> ```Markdown
> 
> To work around the issue, when the app is in the error state or disconnected with _always require
> VPN_ enabled, DNS traffic coming from a mullvad specific group will optionally be allowed to bypass
> ```

Instead of just saying "optionally be allowed" this entire chapter needs to be more specific around what setting it is that toggles this behavior. So the setting needs a good name that we decide on unless we already have it, and this documentation needs to say that it talks about that setting.


<!-- Sent from Reviewable.io -->

2021-12-02 12:46 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 38 of 39 files reviewed, 5 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-types/src/settings/mod.rs, line 84 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpvASllEaoMmzpoY6AO:-MpvASllEaoMmzpoY6AP:bfy08e8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1ddacc8d7c9164c5382f86ce8d5128e6e7d716b/mullvad-types/src/settings/mod.rs#L84)):*
> ```XML
>     #[cfg(target_os = "macos")]
>     /// Enable custom resolver
>     pub enable_custom_resolver: bool,
> ```

I'm not sure this extremely generic name is optimal? I thought we would call this `allow_apple_connectivity_check` or something more specific.


<!-- Sent from Reviewable.io -->

2021-12-02 12:49 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 38 of 39 files reviewed, 5 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[mullvad-cli/src/cmds/dns.rs, line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpB3zQR83fHlQlEqGG0:-MpvB8gx2dZHhYgDWY3S:b-usym6t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60e9c253fb620bc7e5d605f392736da2e75ca5e5/mullvad-cli/src/cmds/dns.rs#L46)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This is a valid concern, but this is the terminology we've been using for the development of the project. I'm in favor of changing it, but we should probably discuss this elsewhere.
</blockquote></details>

I don't think this should be under `mullvad dns` at all. DNS is just *how* we solved the problem. It's not the name of the problem itself.. I'd prefer `mullvad apple-allow-connectivity-check on`


<!-- Sent from Reviewable.io -->

2021-12-02 13:45 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 5 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-core/src/firewall/macos.rs, line 166 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-Mpuqbzb-nYnXYK0YVZU:-MpvO9veDdQ8nVIT3rAc:b-2yqwhu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dbb51494e99516de8b8e882b6d9830357f38ea24/talpid-core/src/firewall/macos.rs#L166)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I don't think they should be unconditional, as these IPs should only be allowed through when the custom resolver is enabled.
</blockquote></details>

This is good. :+1: 


<!-- Sent from Reviewable.io -->

2021-12-06 15:03 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 7 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[CHANGELOG.md, line 28 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqFG2gB8xR6wWRF8fCR:-MqFG2gB8xR6wWRF8fCS:b2slv7t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1ddacc8d7c9164c5382f86ce8d5128e6e7d716b/CHANGELOG.md#L28)):*
> ```Markdown
> ### Added
> #### macOS
> - Add custom DNS resolver to allow macOS connectivity check reach `captive.apple.com` when the
> ```

Please mention the name of the new feature here now when we have one. So it's actually possible to match this feature to what it does/is/looks like in the app.
___
*[docs/security.md, line 253 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqFGOBW-BHdP1NyhKZ4:-MqFGOBW-BHdP1NyhKZ5:b-75442h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1ddacc8d7c9164c5382f86ce8d5128e6e7d716b/docs/security.md#L253)):*
> ```Markdown
> In the other states DNS is simply blocked.
> 
> ### macOS custom DNS resolver
> ```

Please mention name of new feature in the title of this chapter.


<!-- Sent from Reviewable.io -->

2021-12-07 17:53 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 12 of 42 files reviewed, 6 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[CHANGELOG.md, line 28 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqFG2gB8xR6wWRF8fCR:-MqL06I7Btq3VQCm4IbJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1ddacc8d7c9164c5382f86ce8d5128e6e7d716b/CHANGELOG.md#L28)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Please mention the name of the new feature here now when we have one. So it's actually possible to match this feature to what it does/is/looks like in the app.
</blockquote></details>

Done.
___
*[docs/security.md, line 253 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqFGOBW-BHdP1NyhKZ4:-MqL076N5nz73T5laoAf:b-fqr8j7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1ddacc8d7c9164c5382f86ce8d5128e6e7d716b/docs/security.md#L253)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Please mention name of new feature in the title of this chapter.
</blockquote></details>

I've referenced the whole feature's documentation file instead of elaborating on it's mechanics here.
___
*[mullvad-types/src/settings/mod.rs, line 84 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MpvASllEaoMmzpoY6AO:-MqL0csVAmYAcMGfQPpV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1ddacc8d7c9164c5382f86ce8d5128e6e7d716b/mullvad-types/src/settings/mod.rs#L84)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'm not sure this extremely generic name is optimal? I thought we would call this `allow_apple_connectivity_check` or something more specific.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-08 09:30 UTC, faern requested changes
> Reviewed 2 of 30 files at r20.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 14 of 42 files reviewed, 6 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[docs/allow-macos-network-check.md, line 7 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqOC4BR1PxsNjzLudwl:-MqOC4BS0mqBJH9xcpsD:b2ni54z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/docs/allow-macos-network-check.md#L7)):*
> ```Markdown
> and since macOS's network reachability seemingly does too, the daemon won't be able to connect to a
> relay and thus stay in the blocked state for a prolonged time. The default route is only published
> when macOS finishes or times out it's captive portal check. The captive portal check involves
> ```

its
___
*[docs/allow-macos-network-check.md, line 12 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqOCLyNErRMeVIfc6ml:-MqOCLyODYjkW-00NQoY:b2ni54z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/docs/allow-macos-network-check.md#L12)):*
> ```Markdown
> always incurred, which forces the app into the offline error state for a prolonged time.
> 
> To not have to wait for macOS to time out it's captive portal check, the app should allow the
> ```

its
___
*[docs/allow-macos-network-check.md, line 20 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqOFT6nEDU3Jw1MSXgM:-MqOFT6o27WoeAH_cCXl:b-fmmcfu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/docs/allow-macos-network-check.md#L20)):*
> ```Markdown
> # Leaking macOS network-check traffic
> To allow macOS's network-check to function, _some_ DNS queries need to leaked during a blocked
> state. This can be done via using a resolver that is selectively reacts to some DNS queries and is
> ```

remove is: "that selectively reacts"?
___
*[docs/allow-macos-network-check.md, line 20 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqOFXIx9RghBKyrtGM0:-MqOFXIx9RghBKyrtGM1:b-5vffnq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/docs/allow-macos-network-check.md#L20)):*
> ```Markdown
> # Leaking macOS network-check traffic
> To allow macOS's network-check to function, _some_ DNS queries need to leaked during a blocked
> state. This can be done via using a resolver that is selectively reacts to some DNS queries and is
> ```

You use the term "filtering resolver" fairly consistently later in the documentation. But that term is not really introduced to the reader. This might a good place to do so? "This can be done via a filtering resolver running on the local host that selectively ..."?
___
*[docs/allow-macos-network-check.md, line 31 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqOEUnV9ApSzoWOe6IY:-MqOEUnV9ApSzoWOe6IZ:b-ebc1ih) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/docs/allow-macos-network-check.md#L31)):*
> ```Markdown
> To enable the custom resolver, certain conditions in the rest of the daemon need to be met:
> - The firewall must allow traffic coming from our resolver (identified via GID) to the configured
>   upstream resolvers.  The firewall must have a list of IPs for which traffic will be
> ```

Double spaces
___
*[docs/allow-macos-network-check.md, line 36 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqOEW2ODZ5Ir7bBZ-ck:-MqOEW2P5S97hZIYHe1B:b-42m9p5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/docs/allow-macos-network-check.md#L36)):*
> ```Markdown
> - The daemon must configure the system to use the filtering resolver.
> - The resolver must only reply to queries when it's in an active state and it must only reply to
>   allowed queries. For now, only queries for `captive.apple.com` are allowed.
> ```

I'd say that more important than not *replying to* queries when inactive/wrong domains, from a security/privacy standpoint it's more important that it does not *send queries to the network* in the states when it's not supposed to. That's the leak. If it were to reply with bogus replies to any lookup at any time, that's a flaw, but not a security flaw :)
___
*[docs/allow-macos-network-check.md, line 48 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqOG5zODoXcs8HPeKf_:-MqOG5zODoXcs8HPeKfa:b-s5hhpz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/docs/allow-macos-network-check.md#L48)):*
This documentation is very extensive, which is good. But it's also repetitive. That we need a list of IPs and when they are being cleared has already been explained above. If we can say the same thing with less words that would make it easier to consume.

> ... allowed to pass. The list will be populated by the resolved A and AAAA records, and reset when the
  tunnel state machine moves away from the error state.

> - The list of IP addresses that are allowed to pass through our firewall are cleared.

The same goes for a few other things in this document.
___
*[docs/allow-macos-network-check.md, line 60 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqOGvJ90_xYYmEMSnCl:-MqOGvJ90_xYYmEMSnCm:b-kw1ys9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/docs/allow-macos-network-check.md#L60)):*
> ```Markdown
>   1. Configure the host to use our local resolver
>   If any of the above steps fail, the app should report the failure to the frontend that toggled the
>   setting.
> ```

Minor detail. But I think the error should be reported to all frontends, not just the one that toggled the setting?


<!-- Sent from Reviewable.io -->

2021-12-08 09:32 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 14 of 42 files reviewed, 7 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[talpid-types/src/tunnel.rs, line 111 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqONjcN94171Qv8BvYi:-MqONjcN94171Qv8BvYj:b-o72h9a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/talpid-types/src/tunnel.rs#L111)):*
> ```XML
>     /// Failed to start filtering resolver
>     #[cfg(target_os = "macos")]
>     FiilteringResolverError,
> ```

s/Fii/fi/


<!-- Sent from Reviewable.io -->

2021-12-08 14:04 UTC, dlon requested changes
> Reviewed 28 of 30 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 10 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[docs/allow-macos-network-check.md, line 74 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqP7hmA6wiZTmmXY_uu:-MqP7hmB5Hovb-5oZrGr:bkj8flv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/docs/allow-macos-network-check.md#L74)):*
> ```Markdown
> ### When the network-check leak is enabled
> #### Behavior when the daemon enters a blocking state
> When entering a blocking state, the system's current DNS config should be replaced w
> ```

Not complete.
___
*[docs/security.md, line 242 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqPL4aYC96SHvh_sqd2:-MqPL4aYC96SHvh_sqd3:b-w8o721) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/docs/security.md#L242)):*
> a

an
___
*[talpid-core/src/tunnel_state_machine/disconnected_state.rs, line 127 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqPHle491mlzVvrmnGI:-MqPHle491mlzVvrmnGJ:b-bb8sbb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L127)):*
> ```XML
> 
>         #[cfg(target_os = "macos")]
>         if shared_values.enable_filtering_resolver {
> ```

Should it not be conditional on `block_when_disconnected` also? If not, why is `start_filtering_resolver` called when `block_when_disconnected` is turned on?
___
*[talpid-core/src/tunnel_state_machine/disconnected_state.rs, line 202 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqPI2wSEIKKt_POhwtm:-MqPI2wSEIKKt_POhwtn:ba44qro) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L202)):*
> ```XML
>                     Self::register_split_tunnel_addresses(shared_values, true);
>                     #[cfg(target_os = "macos")]
>                     if block_when_disconnected {
> ```

Should it be conditional on `enable_filtering_resolver` also? See the above comment.
___
*[talpid-core/src/tunnel_state_machine/disconnected_state.rs, line 252 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqPLoU647ue2x02K0h4:-MqPLoU647ue2x02K0h5:b-xst3ok) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L252)):*
> ```XML
>                     shared_values.enable_filtering_resolver = enable;
>                     self.set_firewall_policy(shared_values, false);
>                     if shared_values.block_when_disconnected && enable {
> ```

See the comments above.


<!-- Sent from Reviewable.io -->

2021-12-09 09:05 UTC, faern requested changes
> Reviewed 1 of 13 files at r21, 1 of 2 files at r22.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 31 of 42 files reviewed, 6 unresolved discussions (waiting on @dlon, @faern, and @pinkisemils)

___
*[CHANGELOG.md, line 29 at r22](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqTPW850y6RtOtHmgi8:-MqTPW8622JA7BhpzyyO:bicasng) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d71e8ac1908d4d8e707e1c49f7e85840b0a70b52/CHANGELOG.md#L29)):*
> ```Markdown
> #### macOS
> - Add a feature to leak macOS network check traffic in blocked states to resolve issues with the app
>   blocking internet connectivity after sleep or when connecting to new wireless networks.
> ```

Can we cram in an "opt-in" or "disabled by default" here somewhere? I don't want users to be alarmed that we have started "leaking" by default.
___
*[docs/allow-macos-network-check.md, line 61 at r22](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqTQlq0DuCz5UJLX6Bg:-MqTQlq0DuCz5UJLX6Bh:b-oa2azh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d71e8ac1908d4d8e707e1c49f7e85840b0a70b52/docs/allow-macos-network-check.md#L61)):*
> ```Markdown
>   1. Configure the host to use our local resolver
> - In all other states, the filtering resolver should bind to port 53.
> If any of the above steps fail, the app should report the failure to the frontend that toggled the
> ```

Should be indented if it's part of the above bullet list item.


<!-- Sent from Reviewable.io -->

2021-12-09 11:51 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: 29 of 42 files reviewed, 5 unresolved discussions (waiting on @dlon and @faern)

___
*[CHANGELOG.md, line 29 at r22](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqTPW850y6RtOtHmgi8:-MqTjZ17BqYMYMDpMWOm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d71e8ac1908d4d8e707e1c49f7e85840b0a70b52/CHANGELOG.md#L29)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we cram in an "opt-in" or "disabled by default" here somewhere? I don't want users to be alarmed that we have started "leaking" by default.
</blockquote></details>

Done.
___
*[docs/allow-macos-network-check.md, line 48 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqOG5zODoXcs8HPeKf_:-MqU13Nw5WUA0Gtg52Mb:b-cu1c48) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/docs/allow-macos-network-check.md#L48)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This documentation is very extensive, which is good. But it's also repetitive. That we need a list of IPs and when they are being cleared has already been explained above. If we can say the same thing with less words that would make it easier to consume.

> ... allowed to pass. The list will be populated by the resolved A and AAAA records, and reset when the
  tunnel state machine moves away from the error state.

> - The list of IP addresses that are allowed to pass through our firewall are cleared.

The same goes for a few other things in this document.
</blockquote></details>

I've made some changes to remove redundant statements, do you still feel there's too much repetition going on?
___
*[talpid-types/src/tunnel.rs, line 111 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqONjcN94171Qv8BvYi:-MqTizlL1RVUFnsnfWug:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/talpid-types/src/tunnel.rs#L111)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

s/Fii/fi/
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-09 12:23 UTC, dlon approved these changes
> Reviewed 10 of 13 files at r21, 1 of 2 files at r22, 3 of 3 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon and @faern)



<!-- Sent from Reviewable.io -->

2021-12-09 12:34 UTC, faern reviewed
> Reviewed 1 of 3 files at r23.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[docs/allow-macos-network-check.md, line 48 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138#-MqOG5zODoXcs8HPeKf_:-MqUAkT-BtPcc9Ax8LYG:b-mynuma) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f8db0c38bc1737ed675abe8d082e92956bde63d/docs/allow-macos-network-check.md#L48)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I've made some changes to remove redundant statements, do you still feel there's too much repetition going on?
</blockquote></details>

I'm not going to read the entire doc again. But I think this might be a bit better.


<!-- Sent from Reviewable.io -->

2021-12-09 16:18 UTC, dlon approved these changes
> Reviewed 4 of 4 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-12-10 08:50 UTC, faern approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3138)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-12-10 10:00 UTC, merged