Add WG entry hop "state" setting
mullvad/mullvadvpn-app pull request #3177
Opened 2021-12-07 10:37 UTC by dlon

Previously, the entry location was an `Option`. This meant that it could not be turned off without losing the location, and the gRPC message worked differently than it did for relays, etc. This PR adds a separate "state" and makes the entry location non-optional.

The CLI currently behaves exactly as before. The state setting is not exposed at all.

2021-12-07 12:11 UTC, pinkisemils reviewed
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3177)* status: 5 of 7 files reviewed, all discussions resolved

___
*[mullvad-types/src/relay_constraints.rs, line 513 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3177#-MqJl6HW-qKXbZmIX4xg:-MqJl6HW-qKXbZmIX4xh:bpvp8nz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58efa4b271fe1ae6673f68d0c90f057f2bcbaebd/mullvad-types/src/relay_constraints.rs#L513)):*
> ```XML
>     }
> 
>     pub fn off(&self) -> bool {
> ```

Not sure how necessary this function is if `on()` exists.
___
*[mullvad-types/src/relay_constraints.rs, line 541 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3177#-MqJl0l42jwtikQBelIJ:-MqJl0l42jwtikQBelIK:bp6xxx2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58efa4b271fe1ae6673f68d0c90f057f2bcbaebd/mullvad-types/src/relay_constraints.rs#L541)):*
> ```XML
>             Constraint::Only(protocol) => write!(f, "{}", protocol)?,
>         }
>         if self.multihop_state == MultihopState::On {
> ```

I would use `self.multihop_state.on()` here.


<!-- Sent from Reviewable.io -->

2021-12-07 12:48 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3177)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-12-07 12:55 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3177)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[mullvad-types/src/relay_constraints.rs, line 541 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3177#-MqJl0l42jwtikQBelIJ:-MqJxRlY804rGNhJi8n8:b-ho5wpv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58efa4b271fe1ae6673f68d0c90f057f2bcbaebd/mullvad-types/src/relay_constraints.rs#L541)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can I suggest we rename that method to `is_on`, please. Right now it sounds like an action, and not a check. That would also be consistent with the standard libray. See `is_some`, `is_none`, `is_ok`, `Ordering::is_gt` etc.
</blockquote></details>

Agreed. Done.


<!-- Sent from Reviewable.io -->

2021-12-07 13:14 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3177)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[mullvad-types/src/relay_constraints.rs, line 497 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3177#-MqJy_At8lxQ1BlU8E11:-MqK0W4V-5FR2mI4TNdh:b-o17mjb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b0baabcadeee554c3e0d35afba4c986116bfc952/mullvad-types/src/relay_constraints.rs#L497)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is there enough gain in having this type over just `pub use_multihop: bool`? Having and maintaining a type is also not zero cost.
</blockquote></details>

I suppose we'll never need an `auto` setting for this? If so, a boolean is indeed simpler.


<!-- Sent from Reviewable.io -->

2021-12-07 13:21 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3177)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[mullvad-types/src/relay_constraints.rs, line 497 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3177#-MqJy_At8lxQ1BlU8E11:-MqK2KVS-ZQskRkReLtm:bz957m7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b0baabcadeee554c3e0d35afba4c986116bfc952/mullvad-types/src/relay_constraints.rs#L497)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I suppose we'll never need an `auto` setting for this? If so, a boolean is indeed simpler.
</blockquote></details>

I think there's no need since there's no obfuscation anyway. It doesn't make sense to automatically use it.


<!-- Sent from Reviewable.io -->

2021-12-08 15:46 UTC, pinkisemils approved these changes
> Reviewed 1 of 7 files at r1, 1 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3177)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2021-12-09 12:42 UTC, merged