Use exponential backoff for WireGuard connectivity check timeout
mullvad/mullvadvpn-app pull request #3195
Opened 2021-12-14 12:21 UTC by dlon

Previously, the timeout for establishing a WireGuard tunnel was always 15 seconds. This is very high except for very slow connections. It is bad for two reasons: 1) If a relay is down, it takes far too much time to try another relay. 2) On the device concept branch, the device validity check occurs after a couple of failed connect attempts. This means that it takes over 30 seconds to discover that the device/WireGuard key is invalid.

This PR sets the initial timeout to 4 seconds, and multiplies it by two for each reconnect attempt, up to a maximum of 15 seconds. So if a relay is down (and the relay list does not say so), it will normally take 4 seconds to try a working one. It will also "only" take about 12 seconds to discover that the device has been revoked.

2021-12-14 12:27 UTC, pinkisemils reviewed
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3195)* status: 4 of 5 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-16 10:21 UTC, pinkisemils requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3195)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel/wireguard/connectivity_check.rs, line 134 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3195#-Mr1jsctDCN0xb65M3sw:-Mr1jsctDCN0xb65M3sx:bs5b22z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edc922904e9bce007400d410f915dab96378fcd1/talpid-core/src/tunnel/wireguard/connectivity_check.rs#L134)):*
> ```XML
>                 .checked_mul(
>                     timeout_multiplier
>                         .checked_pow(retry_attempt)
> ```

Could use [saturating_pow](https://doc.rust-lang.org/std/primitive.u32.html#method.saturating_pow) here.


<!-- Sent from Reviewable.io -->

2021-12-16 12:20 UTC, pinkisemils reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3195)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2021-12-16 12:48 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3195)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/connectivity_check.rs, line 134 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3195#-Mr1jsctDCN0xb65M3sw:-Mr2H6SBDsiEXz1Mx_WH:b-83sjoh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edc922904e9bce007400d410f915dab96378fcd1/talpid-core/src/tunnel/wireguard/connectivity_check.rs#L134)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Could use [saturating_pow](https://doc.rust-lang.org/std/primitive.u32.html#method.saturating_pow) here.
</blockquote></details>

Nice!


<!-- Sent from Reviewable.io -->

2021-12-20 16:01 UTC, pinkisemils approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3195)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-03 15:17 UTC, merged