Add API address cache
mullvad/mullvadvpn-app pull request #3196
Opened 2021-12-14 12:57 UTC by pronebird

Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

This PR adds support for API address cache that is used to perform REST requests to Mullvad API. The address cache is updated periodically using background task and timer based solution.

Detailed changeset:

1. Rename `update-relays.sh` to `prebuild.sh`. Update script to download API address list to `Assets/api-ip-address.json`, which is later on bundled with the app.
2. SSL pinning: return `.rejectProtectionSpace` if found that SSL certificate chain is invalid. This makes the network layer return the proper error back to caller, i.e: `The certificate for this server is invalid. You might be connecting to a server that is pretending to be "<ENDPOINT_IP>" which could put your confidential information at risk.`. When returning `.cancelAuthentication`, the network layer simply cancels the request which makes it impossible to tell what really happened.
3. Add `AddressCache.Store` that's responsible for persisting API address cache on disk, loading cache shipped with the app and provides means for picking and shuffling API endpoints.
4. Add `AddressCache.Tracker` that's responsible for updating API address cache periodically.
5. Add `REST.NetworkOperation` that performs network requests using given retry strategy and address cache.
6. Add `REST.RequestAdapter` that provides a simple interface to work with REST API using either closure block or Promises.

2021-12-14 13:02 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3196)* status: 0 of 29 files reviewed, all discussions resolved

___
*[ios/MullvadVPN/REST/SSLPinningURLSessionDelegate.swift, line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3196#-Mqt1AQ637IwA0iDO8ig:-Mqt1AQ637IwA0iDO8ih:bvx20h8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ea8bf7a080b1201df8d612af4572f177130dd81c/ios/MullvadVPN/REST/SSLPinningURLSessionDelegate.swift#L43)):*
> ```Swift
> 
>         // Set SSL policy
>         let sslPolicy = SecPolicyCreateSSL(true, sslHostname as CFString)
> ```

FYI we have to set the expected hostname (`api.mullvad.net`) before verifying the SSL certificate, since we now talk to Mullvad API via IP vs. hostname.


<!-- Sent from Reviewable.io -->

2021-12-15 18:53 UTC, raksooo requested changes
> Reviewed 25 of 29 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r6, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3196)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[ios/MullvadVPN/REST/SSLPinningURLSessionDelegate.swift, line 31 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3196#-MqxVaUi9LZd9A1xYON9:-MqxVaUi9LZd9A1xYONA:b-sf0uvj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6cb94c49531ca7a3fad5519993ce1b87ee6be93f/ios/MullvadVPN/REST/SSLPinningURLSessionDelegate.swift#L31)):*
> ```Swift
>                 evaluation = (.useCredential, URLCredential(trust: serverTrust))
>             } else {
>                 evaluation = (.cancelAuthenticationChallenge, nil)
> ```

Why has this been removed? Is it not needed anymore?


<!-- Sent from Reviewable.io -->

2021-12-15 19:20 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3196)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[ios/MullvadVPN/REST/SSLPinningURLSessionDelegate.swift, line 31 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3196#-MqxVaUi9LZd9A1xYON9:-MqzTH3CCjexqbxaOzGT:b-6gmebo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6cb94c49531ca7a3fad5519993ce1b87ee6be93f/ios/MullvadVPN/REST/SSLPinningURLSessionDelegate.swift#L31)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Why has this been removed? Is it not needed anymore?
</blockquote></details>

As described in PR's description, the SSL certificate resolution in case of failure was changed from `.cancelAuthenticationChallenge ` to `.rejectProtectionSpace`. 

Previously three code paths, were also combined into two code paths since we do not handle any other challenges but server trust. 

Based on documentation and some practical observation, if server supports more than one authentication method, `.rejectProtectionSpace` will move onto next authentication method by calling this very function with new challenge, while `.cancelAuthenticationChallenge ` would prevent any further authentication attempts. 

However, the `URLError.cancelled` error returned as a result of passing `.cancelAuthenticationChallenge` resolution is a very generic cancellation error, and it's really impossible to tell what went wrong based on that error alone. Same error is emitted if I cancel request programmatically elsewhere. 

At the same time `. rejectProtectionSpace` resolution properly returns `URLError.serverCertificateUntrusted` error which is indicative of what went wrong.

Our servers have only one authentication method (SSL certificate), so there is no overhead for us. Previously we used to have client certificate authentication served by mistake, in that case `URLSession` also called the same function with `NSURLAuthenticationMethodClientCertificate` authentication method. However that's no longer the case as far as I know.

I hope that clears out things.


<!-- Sent from Reviewable.io -->

2021-12-16 09:48 UTC, raksooo approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3196#-:-Mr1dC_bBg8VB89X8p5R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[ios/MullvadVPN/REST/SSLPinningURLSessionDelegate.swift, line 31 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3196#-MqxVaUi9LZd9A1xYON9:-Mr1cjK-91E6_KfOlYfl:b-91yy87) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6cb94c49531ca7a3fad5519993ce1b87ee6be93f/ios/MullvadVPN/REST/SSLPinningURLSessionDelegate.swift#L31)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

As described in PR's description, the SSL certificate resolution in case of failure was changed from `.cancelAuthenticationChallenge ` to `.rejectProtectionSpace`. 

Previously three code paths, were also combined into two code paths since we do not handle any other challenges but server trust. 

Based on documentation and some practical observation, if server supports more than one authentication method, `.rejectProtectionSpace` will move onto next authentication method by calling this very function with new challenge, while `.cancelAuthenticationChallenge ` would prevent any further authentication attempts. 

However, the `URLError.cancelled` error returned as a result of passing `.cancelAuthenticationChallenge` resolution is a very generic cancellation error, and it's really impossible to tell what went wrong based on that error alone. Same error is emitted if I cancel request programmatically elsewhere. 

At the same time `. rejectProtectionSpace` resolution properly returns `URLError.serverCertificateUntrusted` error which is indicative of what went wrong.

Our servers have only one authentication method (SSL certificate), so there is no overhead for us. Previously we used to have client certificate authentication served by mistake, in that case `URLSession` also called the same function with `NSURLAuthenticationMethodClientCertificate` authentication method. However that's no longer the case as far as I know.

I hope that clears out things.
</blockquote></details>

Thanks for the explanation :+1:


<!-- Sent from Reviewable.io -->

2021-12-16 14:01 UTC, merged