Disable background throttling while resetting navigation while in background
mullvad/mullvadvpn-app pull request #3223
Opened 2021-12-28 12:11 UTC by raksooo

This PR disabled background throttling of the renderer process during the `navigation.notifyReset` call is made. This is to allow the UI to update and perform the navigation while the window isn't visible. Without this the previous view will be visible for a split second when opening the window after resetting.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2022-01-03 16:55 UTC, raksooo reviewed
There's still a slight flicker on Windows sometimes but it's a lot better.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3223#-:-MsVrUTZ2zJ2sHuhB-1P:bvsm6wp)* status: 0 of 3 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-24 09:22 UTC, pronebird requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3223)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 1143 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3223#-MuANAZp6ZYMgU6XNYUY:-MuANAZp6ZYMgU6XNYUZ:b-da34v5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f1a130f3135a1dcd3213c3573a5b3aba71ffae07/gui/src/main/index.ts#L1143)):*
> ```XML
> 
>         this.backgroundThrottleScheduler.schedule(() => {
>           this.windowController?.webContents?.setBackgroundThrottling(true);
> ```

Maybe make sure that `webContents.isDestroyed()` returns `false` before calling `setBackgroundThrottling()` to guard against situations when this timer fires before the app quit but after the window is already destroyed.


<!-- Sent from Reviewable.io -->

2022-01-24 09:41 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3223)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/main/index.ts, line 1143 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3223#-MuANAZp6ZYMgU6XNYUY:-MuASVs8EaafgLFPFWMX:bc79kus) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f1a130f3135a1dcd3213c3573a5b3aba71ffae07/gui/src/main/index.ts#L1143)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe make sure that `webContents.isDestroyed()` returns `false` before calling `setBackgroundThrottling()` to guard against situations when this timer fires before the app quit but after the window is already destroyed.
</blockquote></details>

```
  get webContents(): WebContents | undefined {
    return this.webContentsValue.isDestroyed() ? undefined : this.webContentsValue;
  }
```

We already do this in `windowController`.


<!-- Sent from Reviewable.io -->

2022-01-24 10:17 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3223)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-24 10:17 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3223#-:-MuA_oji7gEy-cxbyWA_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-24 15:54 UTC, merged