Upgrade rustls crates
mullvad/mullvadvpn-app pull request #3280
Opened 2022-01-20 09:36 UTC by dlon

This upgrades `tokio-rustls` and `hyper-rustls` to version 0.23, and `rustls` to 0.20. These are mostly API changes.

2022-01-20 12:11 UTC, pinkisemils approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3280)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-20 12:12 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3280)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel/wireguard/connectivity_check.rs, line 804 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3280#-MtrOd6A0dZIXNfT8Ais:-MtrOd6B7G4sLVkoMvWU:b-9h76bc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1756c03313369fff2fd87fb1c6e6230677f040e7/talpid-core/src/tunnel/wireguard/connectivity_check.rs#L804)):*
> ```XML
>             }
>         });
>         let err = DELAY_ON_INITIAL_SETUP + Duration::from_millis(200);
> ```

How is this related to these changes?


<!-- Sent from Reviewable.io -->

2022-01-20 12:12 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3280)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[mullvad-rpc/src/https_client_with_sni.rs, line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3280#-MtrOn6c6v2S1YYL1s_K:-MtrOn6c6v2S1YYL1s_L:b-gn4re) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1756c03313369fff2fd87fb1c6e6230677f040e7/mullvad-rpc/src/https_client_with_sni.rs#L82)):*
> ```XML
>         let mut cert_store = rustls::RootCertStore::empty();
> 
>         let certs = rustls_pemfile::certs(&mut BufReader::new(LE_ROOT_CERT))
> ```

I was hoping they would give a better API for reading certs, but oh well :shrug: 


<!-- Sent from Reviewable.io -->

2022-01-20 12:28 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3280)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/connectivity_check.rs, line 804 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3280#-MtrOd6A0dZIXNfT8Ais:-MtrS2-t30Je2AYlsKwa:bkncpyy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1756c03313369fff2fd87fb1c6e6230677f040e7/talpid-core/src/tunnel/wireguard/connectivity_check.rs#L804)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

How is this related to these changes?
</blockquote></details>

It is unrelated as far as I know, but the test failed twice. I guess it is somewhat unreliable.


<!-- Sent from Reviewable.io -->

2022-01-20 13:26 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3280)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel/wireguard/connectivity_check.rs, line 804 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3280#-MtrOd6A0dZIXNfT8Ais:-MtrejT51Rfcw8rzc8dV:b-qm876n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1756c03313369fff2fd87fb1c6e6230677f040e7/talpid-core/src/tunnel/wireguard/connectivity_check.rs#L804)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It is unrelated as far as I know, but the test failed twice. I guess it is somewhat unreliable.
</blockquote></details>

I've reverted this.


<!-- Sent from Reviewable.io -->

2022-01-20 16:20 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3280#-:-MtsHOqRDGi4KPLXDdHg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2022-01-21 12:42 UTC, pinkisemils approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3280#-:-Mtwe6I-EWrXQF9-7e64:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-21 15:49 UTC, merged