Refactor relay selector
mullvad/mullvadvpn-app pull request #3289
Opened 2022-01-24 12:46 UTC by pinkisemils

This is a refactoring of the relay selector with a single purpose - to make the code clearer. The main issue with the previous state of the relay selector was that all relay selector functions always took all of the parameters, regardless of necessity, which made it hard to understand what bit of the parameters affected which bit of the selection process. To remedy this, yet another layer of abstraction has been added (`TunnelMatcher` trait and `RelayMatcher` struct) which are constructed only from the necessary bits of the `RelayConstraints` for each tunnel type. In the process, some new tests have been added, and the relay list updater has been moved into it's own module. Care has been taken to have the preferred constraints remain the same.

2022-01-24 14:25 UTC, dlon reviewed
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[mullvad-types/src/endpoint.rs, line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuBORQF7oH5Y03-pWfv:-MuBORQF7oH5Y03-pWfw:b-6n621z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79704c2d6b72fe6f9930b97175f93d407cb82c32/mullvad-types/src/endpoint.rs#L41)):*
> ```XML
>     pub fn get_peer_config(&self) -> Option<&wireguard::PeerConfig> {
>         match self {
>             Self::Wireguard(wireguard_endpoint) => Some(&wireguard_endpoint.peer),
> ```

Nit: Could we use `Self::` in the other method as well (or at least be consistent)?
___
*[mullvad-daemon/src/relays/mod.rs, line 350 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuBOyc84P-tvXa1Sr-O:-MuBOyc84P-tvXa1Sr-P:b-ph1pyu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1edaedd1be1517d758ed669a352a245c196dc6ce/mullvad-daemon/src/relays/mod.rs#L350)):*
> ```XML
>             exit_endpoint
>                 .get_peer_config()
>                 .expect("Failed to get peer config from WireGuard endpoint"),
> ```

Would it be useful to have a macro for extracting values out of enum instances? E.g.,

```rust
macro_rules! unwrap_enum {
    ($value: expr, $variant: path) => {{
        if let $variant(inner) = $value {
            inner
        } else {
            panic!("unexpected enum variant");
        }
    }};
}
```

Then you could just do this:

```rust
        Self::set_entry_peers(
            &unwrap_enum!(&exit_endpoint, MullvadEndpoint::Wireguard).peer,
            &mut entry_endpoint,
        );
```


<!-- Sent from Reviewable.io -->

2022-01-24 16:24 UTC, dlon reviewed
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[mullvad-daemon/src/relays/matcher.rs, line 259 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuBsrT43JrJm55pm3Xf:-MuBsrT43JrJm55pm3Xg:b-uepaso) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1edaedd1be1517d758ed669a352a245c196dc6ce/mullvad-daemon/src/relays/matcher.rs#L259)):*
> ```XML
>         {
>             Constraint::Any => true,
>             Constraint::Only(port) => endpoint
> ```

I guess this is correct without checking `protocol` because the ports don't overlap?
___
*[mullvad-daemon/src/relays/mod.rs, line 541 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuBm8KE7-bZcsW0merb:-MuBm8KE7-bZcsW0merc:bva5xmb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1edaedd1be1517d758ed669a352a245c196dc6ce/mullvad-daemon/src/relays/mod.rs#L541)):*
> ```XML
>                 // connect, then afterwards 2 of each 4 successive attempts will try to connect
>                 // on port 53.
>                 if retry_attempt % 4 > 1 && relay_constraints.wireguard_constraints.port.is_any() {
> ```

`preferred_wireguard_port` could be reused here.


<!-- Sent from Reviewable.io -->

2022-01-25 08:33 UTC, mvd-ows reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[mullvad-daemon/src/relays/matcher.rs, line 69 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuBcAGO3B7--yTHRY5P:-MuFKBWo5YboubHFbSXw:b-ewzujs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1edaedd1be1517d758ed669a352a245c196dc6ce/mullvad-daemon/src/relays/matcher.rs#L69)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I still find this a bit confusing. Maybe the documentation could mention that it returns the same relay, if it matches, but with all endpoints that don't match the constraints removed. The name seems a bit too vague as well, but I don't have a better suggestion.
</blockquote></details>

The name is currently focused on the filtering that is being done. But the context where this is used is always `filter_map()` on a collection of `Relay`.

Trying to fit everything in the name would yield an overly long and complicated name.

How about trying to focus on the mapping instead? Something like `map_matching_endpoints()`?


<!-- Sent from Reviewable.io -->

2022-01-25 08:38 UTC, mvd-ows reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[mullvad-daemon/src/relays/matcher.rs, line 69 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuBcAGO3B7--yTHRY5P:-MuFNVWi1Fga-A8eiZML:brnrvjd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1edaedd1be1517d758ed669a352a245c196dc6ce/mullvad-daemon/src/relays/matcher.rs#L69)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

The name is currently focused on the filtering that is being done. But the context where this is used is always `filter_map()` on a collection of `Relay`.

Trying to fit everything in the name would yield an overly long and complicated name.

How about trying to focus on the mapping instead? Something like `map_matching_endpoints()`?
</blockquote></details>

Actually, `filter_matching_endpoints()` was suggested and may be better. And a clarifying comment?


<!-- Sent from Reviewable.io -->

2022-01-25 08:56 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[mullvad-daemon/src/relays/matcher.rs, line 69 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuBcAGO3B7--yTHRY5P:-MuFReVSEMns4NtAx2-C:b-wzc5z0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1edaedd1be1517d758ed669a352a245c196dc6ce/mullvad-daemon/src/relays/matcher.rs#L69)):*
<details><summary><i>Previously, mvd-ows wrote…</i></summary><blockquote>

Actually, `filter_matching_endpoints()` was suggested and may be better. And a clarifying comment?
</blockquote></details>

Yep, that seems good.


<!-- Sent from Reviewable.io -->

2022-01-25 13:37 UTC, mvd-ows reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @dlon and @mvd-ows)

___
*[mullvad-daemon/src/relays/matcher.rs, line 108 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuBaZ9N4uL9A8E6Jqvb:-MuGRgb0BzcYsPUtrHHb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1edaedd1be1517d758ed669a352a245c196dc6ce/mullvad-daemon/src/relays/matcher.rs#L108)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Maybe defining and using `pub type OpenVpnMatcher = OpenVpnConstraints;` would be slightly cleaner?
</blockquote></details>

Done.
___
*[mullvad-daemon/src/relays/matcher.rs, line 160 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuBdCkg78Yq1lpOnC7H:-MuGRj--3DhL4FO7JBzM:b-25g0o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1edaedd1be1517d758ed669a352a245c196dc6ce/mullvad-daemon/src/relays/matcher.rs#L160)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think this deserves a comment or a better name. What it does is cause a relay not to match if it has the same hostname as that of `peer`, right? To me, `not_hostname`, `not_relay`, or something like that would make more sense.
</blockquote></details>

Added a comment. Is this sufficient?
___
*[mullvad-daemon/src/relays/matcher.rs, line 259 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuBsrT43JrJm55pm3Xf:-MuFkrKFDcEsRDncHLzK:bwpsdgd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1edaedd1be1517d758ed669a352a245c196dc6ce/mullvad-daemon/src/relays/matcher.rs#L259)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I guess this is correct without checking `protocol` because the ports don't overlap?
</blockquote></details>

That's fine, the protocol field will be removed shortly.
___
*[mullvad-types/src/endpoint.rs, line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuBORQF7oH5Y03-pWfv:-MuGRXET8PGPUTrKWuKC:b-229vrj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79704c2d6b72fe6f9930b97175f93d407cb82c32/mullvad-types/src/endpoint.rs#L41)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: Could we use `Self::` in the other method as well (or at least be consistent)?
</blockquote></details>

This function has been removed.
___
*[mullvad-daemon/src/relays/mod.rs, line 350 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuBOyc84P-tvXa1Sr-O:-MuGRxNyBVg0-f-vOpMb:bixqeri) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1edaedd1be1517d758ed669a352a245c196dc6ce/mullvad-daemon/src/relays/mod.rs#L350)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Would it be useful to have a macro for extracting values out of enum instances? E.g.,

```rust
macro_rules! unwrap_enum {
    ($value: expr, $variant: path) => {{
        if let $variant(inner) = $value {
            inner
        } else {
            panic!("unexpected enum variant");
        }
    }};
}
```

Then you could just do this:

```rust
        Self::set_entry_peers(
            &unwrap_enum!(&exit_endpoint, MullvadEndpoint::Wireguard).peer,
            &mut entry_endpoint,
        );
```
</blockquote></details>

Great suggestion. Done.
___
*[mullvad-daemon/src/relays/mod.rs, line 541 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuBm8KE7-bZcsW0merb:-MuGS-xe7GYjpqandPcm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1edaedd1be1517d758ed669a352a245c196dc6ce/mullvad-daemon/src/relays/mod.rs#L541)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`preferred_wireguard_port` could be reused here.
</blockquote></details>

Done.
___
*[mullvad-daemon/src/relays/mod.rs, line 582 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuBhTXbAuLTMvnIVEF5:-MuGS147BzUF_cJdmRFh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1edaedd1be1517d758ed669a352a245c196dc6ce/mullvad-daemon/src/relays/mod.rs#L582)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

See the other comment about `unwrap_enum!`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-25 14:35 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dlon and @mvd-ows)

___
*[talpid-core/src/unwrap_enum.rs, line 8 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuGeEol5OhNJA-duBKl:-MuGeEol5OhNJA-duBKm:b-td00t5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35e63a26d86ed3530b558f34412e0fa19b15d43c/talpid-core/src/unwrap_enum.rs#L8)):*
> ```XML
>             inner
>         } else {
>             panic!("Unexpected enum variant! Expected {}", stringify!($variant));
> ```

This should also include the name/type/contents of the value that was received, not just what was expected.


<!-- Sent from Reviewable.io -->

2022-01-25 16:53 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @dlon, @mvd-ows, and @pinkisemils)

___
*[mullvad-daemon/src/relays/mod.rs, line 349 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuH8RsO3Wi47tnKKfAm:-MuH8RsO3Wi47tnKKfAn:b-7zoqyy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35e63a26d86ed3530b558f34412e0fa19b15d43c/mullvad-daemon/src/relays/mod.rs#L349)):*
> ```XML
> 
>         Self::set_entry_peers(
>             &unwrap_enum!(&exit_endpoint, MullvadEndpoint::Wireguard).peer,
> ```

As far as I can see this macro is only ever used on `MullvadEndpoint::Wireguard`. Can't it instead be an associated method on `MullvadEndpoint`? `MullvadEndpoint::unwrap_wireguard`? I think that would be less magical, easier to read and not require any "utilities".


<!-- Sent from Reviewable.io -->

2022-01-26 11:37 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @dlon, @faern, and @mvd-ows)

___
*[mullvad-daemon/src/relays/mod.rs, line 349 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289#-MuH8RsO3Wi47tnKKfAm:-MuLA8yi0EmdHu_iEIsG:b-ojce65) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35e63a26d86ed3530b558f34412e0fa19b15d43c/mullvad-daemon/src/relays/mod.rs#L349)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

As far as I can see this macro is only ever used on `MullvadEndpoint::Wireguard`. Can't it instead be an associated method on `MullvadEndpoint`? `MullvadEndpoint::unwrap_wireguard`? I think that would be less magical, easier to read and not require any "utilities".
</blockquote></details>

Then we need `unwrap_wireguard(self)` and `unwrap_ref_wrieguard(&self)`. I prefer the macro version instead.


<!-- Sent from Reviewable.io -->

2022-01-28 18:39 UTC, dlon approved these changes
> Reviewed 3 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @dlon, @faern, and @mvd-ows)



<!-- Sent from Reviewable.io -->

2022-01-31 10:50 UTC, faern reviewed
> Reviewed 1 of 5 files at r5, 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dlon, @faern, and @mvd-ows)



<!-- Sent from Reviewable.io -->

2022-01-31 11:45 UTC, dlon approved these changes
> Reviewed 1 of 5 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3289)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dlon, @faern, and @mvd-ows)



<!-- Sent from Reviewable.io -->

2022-01-31 12:02 UTC, merged