Remove user config files on purge
mullvad/mullvadvpn-app pull request #3302
Opened 2022-01-28 13:20 UTC by raksooo

This PR makes `after-remove.sh`, which is run when uninstalling on Linux, remove user configuration directories and files created by the app.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2022-01-28 13:37 UTC, faern requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[CHANGELOG.md, line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302#-MuVs2Hu5psIVJWRGFWF:-MuVs2Hu5psIVJWRGFWG:bwiz1ze) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e711d3e3f3fce652970e5595a264fbb7ce753367/CHANGELOG.md#L85)):*
> ```Markdown
> 
> #### Linux
> - Remove user configuration files when uninstalling/purging.
> ```

Can we make this slightly more explanatory? I know that "user configuration" can be computed to mean GUI settings, but it's not immediately clear from just reading this. Can we make this text specify that it's talking about the frontend app's settings? And preferably that it's removing them from users home directories also.


<!-- Sent from Reviewable.io -->

2022-01-28 15:02 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[CHANGELOG.md, line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302#-MuVs2Hu5psIVJWRGFWF:-MuWBrFX1RsN0rG8TaRB:btx28rq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e711d3e3f3fce652970e5595a264fbb7ce753367/CHANGELOG.md#L85)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we make this slightly more explanatory? I know that "user configuration" can be computed to mean GUI settings, but it's not immediately clear from just reading this. Can we make this text specify that it's talking about the frontend app's settings? And preferably that it's removing them from users home directories also.
</blockquote></details>

How about something like this?


<!-- Sent from Reviewable.io -->

2022-01-28 19:13 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[dist-assets/linux/after-remove.sh, line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302#-MuX2W76BoBUGne4Jflr:-MuX2W76BoBUGne4Jfls:b86rmcy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d997635f9c69ad9dd8d085c1db2a2fb6ab7aad58/dist-assets/linux/after-remove.sh#L17)):*
> ```Shell
>   # Remove app settings and auto-launcher for all users. This doesn't respect XDG_CONFIG_HOME due
>   # to the complexity required.
>   if [[ -f "/etc/passwd" ]] && command -v cut > /dev/null; then
> ```

Couldn't you omit the if statement entirely?

```
home_dirs=$(cut -d: -f6 /etc/passwd 2>/dev/null)
```

I guess it's somewhat risky to assume that stdout will receive no output.


<!-- Sent from Reviewable.io -->

2022-01-31 11:58 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[dist-assets/linux/after-remove.sh, line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302#-MuX2W76BoBUGne4Jflr:-MujzxnI-OFNh_Nh9W7N:ba45j38) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d997635f9c69ad9dd8d085c1db2a2fb6ab7aad58/dist-assets/linux/after-remove.sh#L17)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Couldn't you omit the if statement entirely?

```
home_dirs=$(cut -d: -f6 /etc/passwd 2>/dev/null)
```

I guess it's somewhat risky to assume that stdout will receive no output.
</blockquote></details>

Wouldn't that make the whole script fail due to `set -eu`?


<!-- Sent from Reviewable.io -->

2022-01-31 13:15 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[dist-assets/linux/after-remove.sh, line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302#-MuX2W76BoBUGne4Jflr:-MukGMAxCyKCZoa6TJA3:bp241n1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d997635f9c69ad9dd8d085c1db2a2fb6ab7aad58/dist-assets/linux/after-remove.sh#L17)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Wouldn't that make the whole script fail due to `set -eu`?
</blockquote></details>

That's true. It should work with `|| true` appended, though:

```bash
home_dirs=$(cut -d: -f6 /etc/passwd 2>/dev/null || true)
```


<!-- Sent from Reviewable.io -->

2022-01-31 13:19 UTC, dlon approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[dist-assets/linux/after-remove.sh, line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302#-MuX2W76BoBUGne4Jflr:-MukHKSjEFUo-NSIXvTK:bq8i3oi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d997635f9c69ad9dd8d085c1db2a2fb6ab7aad58/dist-assets/linux/after-remove.sh#L17)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

That's true. It should work with `|| true` appended, though:

```bash
home_dirs=$(cut -d: -f6 /etc/passwd 2>/dev/null || true)
```
</blockquote></details>

Or if you don't use the temporary variable at all:

```bash
for home_dir in $(cut -d: -f6 /etc/passwd 2>/dev/null); do
    # ...
done
```


<!-- Sent from Reviewable.io -->

2022-01-31 13:56 UTC, faern reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-31 13:56 UTC, faern approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-31 13:59 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[dist-assets/linux/after-remove.sh, line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302#-MuX2W76BoBUGne4Jflr:-MukQTJa6GZKCCUVGeLG:bmg3qak) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6470ced7e3cb13f070130c06fe1f7145715f3123/dist-assets/linux/after-remove.sh#L17)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Or if you don't use the temporary variable at all:

```bash
for home_dir in $(cut -d: -f6 /etc/passwd 2>/dev/null); do
    # ...
done
```
</blockquote></details>

I think I prefer the current solution due to readability. But thanks for the suggestion, I didn't think about this!


<!-- Sent from Reviewable.io -->

2022-01-31 14:00 UTC, merged