Don't update the firewall policy twice when setting a new allowed endpoint
mullvad/mullvadvpn-app pull request #3458
Opened 2022-03-25 15:20 UTC by dlon

This PR fixes two bugs:
* `TunnelCommand::AllowEndpoint` updated the firewall policy twice in the connecting state, for no good reason.
* The `allowed_endpoint` field was updated regardless of whether setting the firewall policy succeeded. It now keeps using the old endpoint in case it fails.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3458)

2022-03-25 16:41 UTC, pinkisemils requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3458)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[talpid-core/src/tunnel_state_machine/connecting_state.rs, line 341 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3458#-Mz0x3Z88t9mx8Hz1uFr:-Mz0x3Z88t9mx8Hz1uFs:bdhugze) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b42fad6d22472e7a8f0f3b4576a87964d69ce76f/talpid-core/src/tunnel_state_machine/connecting_state.rs#L341)):*
> ```XML
>                         );
>                     }
>                     shared_values.allowed_endpoint = endpoint;
> ```

This assignment has to take place berfore the call to `Self::set_firewall_policy`. 


<!-- Sent from Reviewable.io -->

2022-03-28 08:37 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3458)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[talpid-core/src/tunnel_state_machine/connecting_state.rs, line 341 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3458#-Mz0x3Z88t9mx8Hz1uFr:-Mz16Yyt34ZZLybZSSZ0:bwah8o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b42fad6d22472e7a8f0f3b4576a87964d69ce76f/talpid-core/src/tunnel_state_machine/connecting_state.rs#L341)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This assignment has to take place berfore the call to `Self::set_firewall_policy`. 
</blockquote></details>

Very true. I think `TunnelCommand::AllowEndpoint` should not return a result at all. The assumption now is that one should continue to use the previous endpoint if it fails, but that makes no sense.


<!-- Sent from Reviewable.io -->

2022-03-28 12:17 UTC, pinkisemils approved these changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3458)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-03-28 12:33 UTC, pinkisemils approved these changes
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3458)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-03-28 14:39 UTC, merged