Add split tunneling remove button
mullvad/mullvadvpn-app pull request #3468
Opened 2022-03-30 08:47 UTC by raksooo

This PR adds a button to remove manually added applications in the split tunneling view on Windows. I also did a small fix for accessing the ref in the `List` clean up code.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2022-03-30 11:33 UTC, pronebird approved these changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-03-30 11:34 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/shared/ipc-schema.ts, line 208 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468#-MzPaVwrEuS5L-Yg5Fzf:-MzPaVwrEuS5L-Yg5Fzg:b-5mhrul) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d0dc28ccfa550311717abb94068cac833b477ff/gui/src/shared/ipc-schema.ts#L208)):*
> ```XML
>     getApplications: invoke<boolean, { fromCache: boolean; applications: IWindowsApplication[] }>(),
>     addApplication: invoke<IWindowsApplication | string, void>(),
>     removeApplication: invoke<IWindowsApplication, void>(),
> ```

`removeApplication` and `deleteApplication` are synonymous from the first sight.


<!-- Sent from Reviewable.io -->

2022-03-30 11:36 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 1400 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468#-MzPb5QpCbXph4HMsxal:-MzPb5QpCbXph4HMsxam:b3dnrmu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d0dc28ccfa550311717abb94068cac833b477ff/gui/src/main/index.ts#L1400)):*
> ```XML
>       } else {
>         throw Error(
>           'windowsSplitTunneling.handleRemoveApplication function called without being imported',
> ```

Should perhaps fix the error message


<!-- Sent from Reviewable.io -->

2022-03-30 11:42 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468)* status: all files reviewed, 3 unresolved discussions (waiting on @raksooo)

___
*[gui/src/main/index.ts, line 1397 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468#-MzPb_sM27OJhspFnn9g:-MzPb_sM27OJhspFnn9h:by6z57e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d0dc28ccfa550311717abb94068cac833b477ff/gui/src/main/index.ts#L1397)):*
> ```XML
>       if (windowsSplitTunneling) {
>         this.guiSettings.deleteBrowsedForSplitTunnelingApplications(application.absolutepath);
>         return windowsSplitTunneling.removeApplicationFromCache(application);
> ```

Are we supposed to tell the daemon to disable split tunnelling for the app when it's removed from the list of apps added manually?


<!-- Sent from Reviewable.io -->

2022-03-30 14:11 UTC, MrChocolatine commented on gui/src/main/index.ts
> +      }
The `else` does not seem necessary.

```suggestion
      throw Error(
        'windowsSplitTunneling.handleRemoveApplication function called without being imported',
      );
```

2022-03-31 08:37 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @MrChocolatine and @pronebird)

___
*[gui/src/main/index.ts, line 1397 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468#-MzPb_sM27OJhspFnn9g:-MzU01109yQcJSOC9duT:b-tjec63) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d0dc28ccfa550311717abb94068cac833b477ff/gui/src/main/index.ts#L1397)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Are we supposed to tell the daemon to disable split tunnelling for the app when it's removed from the list of apps added manually?
</blockquote></details>

The remove button is only visible when it's not split so it can't be removed while split. And the app still shows all split apps even if it's not a "known" app (this can happen if apps are added with the CLI).
___
*[gui/src/main/index.ts, line 1400 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468#-MzPb5QpCbXph4HMsxal:-MzU4Rrt4UKCE1nXnl34:b-7r3boa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d0dc28ccfa550311717abb94068cac833b477ff/gui/src/main/index.ts#L1400)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Should perhaps fix the error message
</blockquote></details>

I removed the check entirely. It will throw an error anyway.
___
*[gui/src/main/index.ts, line 1402 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468#-MzP-UHb7qKlR-7oo183-r1-1402:-MzU4cS-AvAPNf1nNdc2:b352n4d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d0dc28ccfa550311717abb94068cac833b477ff/gui/src/main/index.ts#L1402)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

The `else` does not seem necessary.

```suggestion
      throw Error(
        'windowsSplitTunneling.handleRemoveApplication function called without being imported',
      );
```
</blockquote></details>

Yes, I've removed it. It will of course throw an error automatically if `windowsSplitTunneling` is `undefined`.
___
*[gui/src/shared/ipc-schema.ts, line 208 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468#-MzPaVwrEuS5L-Yg5Fzf:-MzU4tUc3gktOrOiiKwc:blnn23d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d0dc28ccfa550311717abb94068cac833b477ff/gui/src/shared/ipc-schema.ts#L208)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`removeApplication` and `deleteApplication` are synonymous from the first sight.
</blockquote></details>

I've renamed `delete` to `forget`.


<!-- Sent from Reviewable.io -->

2022-03-31 10:48 UTC, pronebird requested changes
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @MrChocolatine, @pronebird, and @raksooo)

___
*[gui/src/shared/ipc-schema.ts, line 208 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468#-MzPaVwrEuS5L-Yg5Fzf:-MzUYbZb2hEqCvG33_T8:b-kzaj6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d0dc28ccfa550311717abb94068cac833b477ff/gui/src/shared/ipc-schema.ts#L208)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I've renamed `delete` to `forget`.
</blockquote></details>

FYI I am not gonna insist but I'd probably stick to remove + custom application or user application or manually added application. But I am not gonna insist. It's just that terminology is not very clear to me here, but perhaps because I am not resolving as much around split tunnel.


<!-- Sent from Reviewable.io -->

2022-03-31 10:48 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @MrChocolatine, @pronebird, and @raksooo)

___
*[gui/src/shared/ipc-schema.ts, line 208 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468#-MzPaVwrEuS5L-Yg5Fzf:-MzU_tIg941zd2Nya5FJ:bfo4ygd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d0dc28ccfa550311717abb94068cac833b477ff/gui/src/shared/ipc-schema.ts#L208)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI I am not gonna insist but I'd probably stick to remove + custom application or user application or manually added application. But I am not gonna insist. It's just that terminology is not very clear to me here, but perhaps because I am not resolving as much around split tunnel.
</blockquote></details>

resolving = revolving


<!-- Sent from Reviewable.io -->

2022-03-31 10:48 UTC, pronebird reviewed
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468)* status: all files reviewed, 2 unresolved discussions (waiting on @MrChocolatine and @raksooo)



<!-- Sent from Reviewable.io -->

2022-03-31 11:44 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468)* status: 7 of 11 files reviewed, 2 unresolved discussions (waiting on @MrChocolatine and @pronebird)

___
*[gui/src/shared/ipc-schema.ts, line 208 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468#-MzPaVwrEuS5L-Yg5Fzf:-MzUmXW-Bae4DsirDFdg:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d0dc28ccfa550311717abb94068cac833b477ff/gui/src/shared/ipc-schema.ts#L208)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

resolving = revolving
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-31 14:03 UTC, merged