Remember history and scroll positions when replacing window
mullvad/mullvadvpn-app pull request #3507
Opened 2022-04-14 14:50 UTC by raksooo

This PR adds storage of the navigation history and scroll positions in the main process for reuse when the browser window is replaced or refreshed. This is useful when toggling unpinned window and when refreshing during development.

Git checklist:

* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

2022-04-18 09:09 UTC, pronebird approved these changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3507)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-18 09:11 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3507)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[gui/src/renderer/app.tsx, line 835 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3507#-N-vw1b707Rcr1-Xl8tK:-N-vw1b707Rcr1-Xl8tL:bjtmwfz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/83cf304cc0ad3fb17f5b3f7e333cc366d6d94441/gui/src/renderer/app.tsx#L835)):*
> ```XML
>     newDeviceEvent: IDeviceEvent,
>     oldAccount?: string,
>     preventRedirectToConnect?: boolean,
> ```

Why is this flag needed?


<!-- Sent from Reviewable.io -->

2022-04-19 08:06 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3507)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[gui/src/renderer/app.tsx, line 835 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3507#-N-vw1b707Rcr1-Xl8tK:-N0-qUUU7_-wpqBpTs5U:b-n1pfi7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/83cf304cc0ad3fb17f5b3f7e333cc366d6d94441/gui/src/renderer/app.tsx#L835)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Why is this flag needed?
</blockquote></details>

When the app receives a new account it redirect to `Connect`. This includes when it first loads so this flag is used to say that we never want to redirect to `Connect` on the first load. We'll end up there anyway since we in the end of the constructor runs `resetNavigation()`.


<!-- Sent from Reviewable.io -->

2022-04-20 08:37 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3507)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-20 08:37 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3507#-:-N056gSo7728SpmKNFZx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-20 09:04 UTC, merged