Refactor device removal out of daemon struct
mullvad/mullvadvpn-app pull request #3556
Opened 2022-05-06 14:04 UTC by dlon

Small refactoring PR in the same vein as some earlier PRs: #3554, #3550.

2022-05-06 14:22 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3556)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`mullvad-daemon/src/device/mod.rs` line 866 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3556#-N1OjwGlEMZfB6Q5g6AU:-N1OjwGlEMZfB6Q5g6AV:b-efejv0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef86e7d4918725113f0b82aaa609e8da31240f60/mullvad-daemon/src/device/mod.rs#L866)):*
> ```XML
> }
> 
> pub async fn remove_device(
> ```

This could perhaps just be a method in `DeviceService`.


<!-- Sent from Reviewable.io -->

2022-05-06 15:54 UTC, pinkisemils requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3556)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-daemon/src/device/mod.rs` line 866 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3556#-N1OjwGlEMZfB6Q5g6AU:-N1P3gbOAVHEaXrFrh9G:bykdu3u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef86e7d4918725113f0b82aaa609e8da31240f60/mullvad-daemon/src/device/mod.rs#L866)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This could perhaps just be a method in `DeviceService`.
</blockquote></details>

I agree, it would belong there.  Shouldn't this code also deal with the case where the current device is revoked? 


<!-- Sent from Reviewable.io -->

2022-05-09 08:56 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3556)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`mullvad-daemon/src/device/mod.rs` line 866 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3556#-N1OjwGlEMZfB6Q5g6AU:-N1c06V5BAJ2AMdvQ5hA:bcn88ub) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ef86e7d4918725113f0b82aaa609e8da31240f60/mullvad-daemon/src/device/mod.rs#L866)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I agree, it would belong there.  Shouldn't this code also deal with the case where the current device is revoked? 
</blockquote></details>

Perhaps, though this normally won't happen. The GUI only uses this function to remove devices when there are too many of them, prior to logging in, but never when logged in. It can be done from the CLI, though.


<!-- Sent from Reviewable.io -->

2022-05-09 09:22 UTC, pinkisemils reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3556)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2022-05-09 09:52 UTC, pinkisemils approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3556)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-09 19:45 UTC, pinkisemils approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3556)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`mullvad-daemon/src/device/service.rs` line 151 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3556#-N1eLbwN08esjxlbKyFh:-N1eLbwN08esjxlbKyFi:b-upzcbj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/689c5e0b5590944e680a3989cf9c49402114bb24/mullvad-daemon/src/device/service.rs#L151)):*
> ```XML
>     /// Same as [Self::remove_device] but returns the removed device and all remaining devices on
>     /// success.
>     pub async fn take_device(
> ```

I think this can still be named `removed_device`. 


<!-- Sent from Reviewable.io -->

2022-05-10 08:45 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3556)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @pinkisemils)

___
*[`mullvad-daemon/src/device/service.rs` line 151 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3556#-N1eLbwN08esjxlbKyFh:-N1h8Ehh3ryrRpb8GGIk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a30044f0e6d0d47d7939492b08da273fb866e271/mullvad-daemon/src/device/service.rs#L151)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think this can still be named `removed_device`. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-10 10:27 UTC, pinkisemils approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3556)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-05-10 11:29 UTC, merged