Ci verify lockfiles signed
mullvad/mullvadvpn-app pull request #3583
Opened 2022-05-13 08:51 UTC by Jontified

Add script that verifies that lockfiles are only modified in signed commits and adds a github action workflow for this on PRs for `Cargo.lock` and `package-lock.json`. This is done in order to enforce a stricter security policy.

2022-05-17 13:15 UTC, albin-mullvad reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Jontified)

___
*[`ci/verify-lockfile-signature.sh` line 5 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N2H7xSHDhvRogsxVC4x:-N2H7xSHDhvRogsxVC4y:b-mcrh2q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8187649d4cf4ac85233be6f776f0964a88115136/ci/verify-lockfile-signature.sh#L5)):*
> ```Shell
> shopt -s nullglob
> SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
> LOCKFILES="$SCRIPT_DIR/../Cargo.lock $SCRIPT_DIR/../gui/package-lock.json"
> ```

I know this is sort of a WIP, but it would perhaps be good to move this list into a separate file so that it's easy to add additional lockfiles.


<!-- Sent from Reviewable.io -->

2022-06-02 07:26 UTC, faern requested changes
> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @Jontified)

___
*[`ci/locked_down_files.txt` line 3 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N3YHlxt8UdZc9bY7UPW:-N3YHlxt8UdZc9bY7UPX:b3a3pby) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d41b8a1d9745fbb3ff81ea6ea2eb8f202ca7ed0/ci/locked_down_files.txt#L3)):*
> ```help
> Cargo.lock
> gui/package-lock.json
> ci/trusted_keys.pub
> ```

May I suggest that we keep each key in a separate file in a dedicated `keys/` directory instead? That way it becomes easier to modify when a developer joins, leaves or changes key. Currently it's a blob that has to be fully re-generated to change anything.
___
*[`.github/workflows/verify-locked-down-signatures.yml` line 7 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N3YILSi2rQBFKuT_fIn:-N3YILSi2rQBFKuT_fIo:bxyaoom) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d41b8a1d9745fbb3ff81ea6ea2eb8f202ca7ed0/.github/workflows/verify-locked-down-signatures.yml#L7)):*
> ```YAML
>             - .github/workflows/verify-locked-down-signatures.yml
>             - Cargo.lock
>             - gui/package-lock.json
> ```

This list is now not in sync with `locked_down_files.txt`. Is there any way to automate that? Best would maybe be if github actions allowed loading a list from file, but that is probably not supported(?).

If the above is not possible, can we invert it? specify the file list here and then parse it out in the script where we need it? In order to need duplicates mostly.
___
*[`.github/workflows/verify-locked-down-signatures.yml` line 15 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N3YGjpX0D0b-BSjAqSj:-N3YGjpX0D0b-BSjAqSk:b4c8vag) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d41b8a1d9745fbb3ff81ea6ea2eb8f202ca7ed0/.github/workflows/verify-locked-down-signatures.yml#L15)):*
> ```YAML
>             - uses: actions/checkout@v3
>               with:
>                 ref: ${{ github.event.pull_request.head.sha }}
> ```

Why do we need to explicitly give this sha? is this commit not the default one it checks out anyway?


<!-- Sent from Reviewable.io -->

2022-06-02 07:36 UTC, faern requested changes
Nice! This looks very good overall. Some smaller stuff to look at maybe, but otherwise splendid.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-:-N3YKyAJ3c_9W8xxhvCF:b-xz0ugq)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @Jontified)

___
*[`ci/verify-locked-down-signatures.sh` line 16 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N3YJK9U8JvmZIxoOqeV:-N3YJK9U8JvmZIxoOqeW:b-6ixb2j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d41b8a1d9745fbb3ff81ea6ea2eb8f202ca7ed0/ci/verify-locked-down-signatures.sh#L16)):*
> ```Shell
> LOCKED_DOWN_FILES=$(cat $SCRIPT_DIR/locked_down_files.txt)
> for locked_file in $LOCKED_DOWN_FILES;
> do
> ```

Very nitpicky, but according to our style guide, the `do` should be on the same line as the `for`. Just like how `if` and `then` are.


<!-- Sent from Reviewable.io -->

2022-06-03 19:38 UTC, Jontified commented
> _[`.github/workflows/verify-locked-down-signatures.yml` line 15 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N3YGjpX0D0b-BSjAqSj:-N3YGjpX0D0b-BSjAqSk:b4c8vag) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d41b8a1d9745fbb3ff81ea6ea2eb8f202ca7ed0/.github/workflows/verify-locked-down-signatures.yml#L15)):_
> 
> > ```yaml
> >             - uses: actions/checkout@v3
> >               with:
> >                 ref: ${{ github.event.pull_request.head.sha }}
> > ```
> 
> Why do we need to explicitly give this sha? is this commit not the default one it checks out anyway?

It seems that `cheackout@v3` will create a temporary merge branch, if we want to be on the latest commit we need to use that `ref`.

I have fixed all other comments. The deduplication of `locked_down_files.txt` became fairly complicated since parsing the yaml isn't straightforward. Please review the changes in the script that parse the yaml and tell me if you think there is a better way of doing it @faern.

2022-06-08 13:09 UTC, faern requested changes
> Reviewed 2 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 2 of 12 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad, @faern, and @Jontified)

___
*[`ci/verify-locked-down-signatures.sh` line 5 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N42QEki3VkDEDmunLJq:-N42QEki3VkDEDmunLJr:bete91f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/777e119128d76d1c752c98934ba9bba307f40efe/ci/verify-locked-down-signatures.sh#L5)):*
> ```Shell
> shopt -s nullglob
> SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
> # In the CI environment we would like to import trusted public keys from a file, but not in our build environment
> ```

We usually try to stick to 100 column scripts. These comment lines are pretty long. Consider breaking them up. Maybe also introduce some space between lines? Currently everything from the shebang down to `whitelisted_commit` is a single block (no empty lines). In most other bash scripts we usually separate it something like

```bash
#!/usr/bin/env bash

set -eu

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Constants

# Code
```


<!-- Sent from Reviewable.io -->

2022-06-09 11:31 UTC, Jontified commented
> > Reviewed 2 of 12 files at r5.
> > _[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)_ status: 2 of 12 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad, @faern, and @Jontified)
> 
> _[`ci/verify-locked-down-signatures.sh` line 5 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N42QEki3VkDEDmunLJq:-N42QEki3VkDEDmunLJr:bete91f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/777e119128d76d1c752c98934ba9bba307f40efe/ci/verify-locked-down-signatures.sh#L5)):_
> 
> > ```shell
> > shopt -s nullglob
> > SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
> > # In the CI environment we would like to import trusted public keys from a file, but not in our build environment
> > ```
> 
> We usually try to stick to 100 column scripts. These comment lines are pretty long. Consider breaking them up. Maybe also introduce some space between lines? Currently everything from the shebang down to `whitelisted_commit` is a single block (no empty lines). In most other bash scripts we usually separate it something like
> 
> ```shell
> #!/usr/bin/env bash
> 
> set -eu
> 
> SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
> 
> # Constants
> 
> # Code
> ```

I've looked over the code again and tried to trim down the rows as well as spaced it out a bit. Let me know what you think.

2022-06-14 08:22 UTC, faern reviewed
> Reviewed 1 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 3 of 12 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Jontified)

___
*[`.github/workflows/verify-locked-down-signatures.yml` line 25 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N4Bn0Ao3x4MNwwTXvd0:-N4Bn0Ao3x4MNwwTXvd1:be36yeb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1ed33e1c2dc6b9bd18031de107dedf1ccaa751/.github/workflows/verify-locked-down-signatures.yml#L25)):*
> ```YAML
>                     git fetch --depth="$(( commits + 1 ))" origin ${{ github.head_ref }} master
>                 fi
>                 ci/verify-locked-down-signatures.sh --import-gpg-keys --whitelist origin/master
> ```

Maybe not important. But is there any way to get the name of the branch the PR is based off of? So we can do that instead of `origin/master`? That way, if you ever create a PR based off of some other branch, it will correctly check against that base commit. Only worth it if it's easily available through some variable or something. Not worth making a complicated solution for it.


<!-- Sent from Reviewable.io -->

2022-06-14 08:56 UTC, albin-mullvad reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 3 of 12 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @faern)

___
*[`.github/workflows/verify-locked-down-signatures.yml` line 25 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N4Bn0Ao3x4MNwwTXvd0:-N4WPpGq9fccwXx7cfDR:bwaccy8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1ed33e1c2dc6b9bd18031de107dedf1ccaa751/.github/workflows/verify-locked-down-signatures.yml#L25)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Maybe not important. But is there any way to get the name of the branch the PR is based off of? So we can do that instead of `origin/master`? That way, if you ever create a PR based off of some other branch, it will correctly check against that base commit. Only worth it if it's easily available through some variable or something. Not worth making a complicated solution for it.
</blockquote></details>

Sounds like a good idea! `github.base_ref` can be used for that, however note:

"This property is only available when the event that triggers a workflow run is either `pull_request` or `pull_request_target`"

https://docs.github.com/en/actions/learn-github-actions/contexts#github-context


<!-- Sent from Reviewable.io -->

2022-06-21 11:26 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 3 of 12 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad, @faern, and @Jontified)

___
*[`ci/verify-locked-down-signatures.sh` line 26 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N4WKqMA1dUYFPuAnRlN:-N4WKqMA1dUYFPuAnRlO:b-rmlu3z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1ed33e1c2dc6b9bd18031de107dedf1ccaa751/ci/verify-locked-down-signatures.sh#L26)):*
> ```Shell
>             shift
>             ;;
>         -*)
> ```

This branch not needed, as agreed upon in the coding guidelines PR :)
___
*[`ci/verify-locked-down-signatures.sh` line 43 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N4WLBZjAkxhiKJ1F9b_:-N4WLBZjAkxhiKJ1F9ba:bao7py6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1ed33e1c2dc6b9bd18031de107dedf1ccaa751/ci/verify-locked-down-signatures.sh#L43)):*
Is `--armor` really needed? I have never used it when *importing* and I never hit any issues with armored key files. And the gpg man page seems to indicate that it's only for output:

>        --armor
>        -a     Create ASCII armored output.  The default is to create the binary OpenPGP format.


<!-- Sent from Reviewable.io -->

2022-06-22 10:37 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 3 of 12 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @faern)

___
*[`ci/verify-locked-down-signatures.sh` line 26 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N4WKqMA1dUYFPuAnRlN:-N59zDLABiQZSzsOgoSM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1ed33e1c2dc6b9bd18031de107dedf1ccaa751/ci/verify-locked-down-signatures.sh#L26)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This branch not needed, as agreed upon in the coding guidelines PR :)
</blockquote></details>

Done.
___
*[`ci/verify-locked-down-signatures.sh` line 43 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N4WLBZjAkxhiKJ1F9b_:-N59zE9F0vXEQlOGIhxm:bgf1zzs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1ed33e1c2dc6b9bd18031de107dedf1ccaa751/ci/verify-locked-down-signatures.sh#L43)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is `--armor` really needed? I have never used it when *importing* and I never hit any issues with armored key files. And the gpg man page seems to indicate that it's only for output:

>        --armor
>        -a     Create ASCII armored output.  The default is to create the binary OpenPGP format.

</blockquote></details>

Right you are, fixed.


<!-- Sent from Reviewable.io -->

2022-06-28 12:12 UTC, faern requested changes
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 4 of 12 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @Jontified)

___
*[`ci/verify-locked-down-signatures.sh` line 64 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N5eCgG4ByJWzS0wJkln:-N5eCgG4ByJWzS0wJklo:b-o5z91s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a146e6fadccc3863f7ac3fe470120ba0eb7121d/ci/verify-locked-down-signatures.sh#L64)):*
> ```Shell
> 
>     for commit in $locked_file_commit_hashes;
>     do
> ```

Style nitpick. `for ...; do` on one line
___
*[`ci/verify-locked-down-signatures.sh` line 65 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N5eCnfqA42vTtLzcbGk:-N5eCnfqA42vTtLzcbGl:b-krv0u5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a146e6fadccc3863f7ac3fe470120ba0eb7121d/ci/verify-locked-down-signatures.sh#L65)):*
> ```Shell
>     for commit in $locked_file_commit_hashes;
>     do
>         if ! $(git verify-commit $commit 2> /dev/null); then
> ```

Nitpick. I don't think you need a subshell here. Just `if ! command` should work
___
*[`ci/verify-locked-down-signatures.sh` line 66 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N5eDAbb97mifeG4mAaf:-N5eDAbb97mifeG4mAag:bqoz2xk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a146e6fadccc3863f7ac3fe470120ba0eb7121d/ci/verify-locked-down-signatures.sh#L66)):*
> ```Shell
>     do
>         if ! $(git verify-commit $commit 2> /dev/null); then
>             echo Commit $commit which changed $locked_file is not signed.
> ```

Please enclose the string to echo with `""`. Not strictly needed. But we usually do that. And it makes syntax highlighting better.


<!-- Sent from Reviewable.io -->

2022-06-28 12:23 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 4 of 12 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @Jontified)

___
*[`ci/verify-locked-down-signatures.sh` line 58 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N5eFjKd6IePVRsnC30-:-N5eFjKd6IePVRsnC300:bq4yhy9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a146e6fadccc3863f7ac3fe470120ba0eb7121d/ci/verify-locked-down-signatures.sh#L58)):*
> ```Shell
> 
> unsigned_commits_exist=0
> for locked_file in $locked_down_files; do
> ```

For the path `ci/keys` this will be a directory. The current code here won't `git rev-list` each individual key file, but rather the entire `keys` directory. I think that's fine, because git will still list every commit any file in it was changed. But maybe name the variable `locked_path` instead to not say it's a file when it strictly isn't?


<!-- Sent from Reviewable.io -->

2022-06-28 13:13 UTC, MrChocolatine reviewed
If I may, shellcheck reports several warnings on your shell script:
- https://www.shellcheck.net/wiki/SC2034
- https://www.shellcheck.net/wiki/SC2231
- https://www.shellcheck.net/wiki/SC2086
- https://www.shellcheck.net/wiki/SC2091

2022-06-28 13:13 UTC, MrChocolatine commented on ci/verify-locked-down-signatures.sh
> +SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
For more strictness you could declare this constant as read-only:

```suggestion
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
```

Also suggested in your coding guidelines for Bash:
https://github.com/mullvad/coding-guidelines/issues/17

2022-06-28 13:13 UTC, MrChocolatine commented on ci/verify-locked-down-signatures.sh
> +SEPARATOR=';'
Similarly to my other comment:

```suggestion
readonly SEPARATOR=';'
```

2022-06-28 13:13 UTC, MrChocolatine commented on ci/verify-locked-down-signatures.sh
> +locked_down_files=$(cat $SCRIPT_DIR/../.github/workflows/verify-locked-down-signatures.yml \
This variable could also become a constant:

```suggestion
readonly LOCKED_DOWN_FILES=$(cat $SCRIPT_DIR/../.github/workflows/verify-locked-down-signatures.yml \
```

2022-06-28 14:16 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 4 of 12 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad, @faern, and @MrChocolatine)

___
*[`ci/verify-locked-down-signatures.sh` line 5 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N3UQuE_gLqHoczslOCI-r8-5:-N5eWFVR382ElG9N7lhC:btxpph9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a146e6fadccc3863f7ac3fe470120ba0eb7121d/ci/verify-locked-down-signatures.sh#L5)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

For more strictness you could declare this constant as read-only:

```suggestion
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
```

Also suggested in your coding guidelines for Bash:
https://github.com/mullvad/coding-guidelines/issues/17

</blockquote></details>

Good suggestion!
```
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly SCRIPT_DIR
```
However above seems more idiomatic per:
https://www.shellcheck.net/wiki/SC2155
___
*[`ci/verify-locked-down-signatures.sh` line 50 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N3UQuE_gLqHoczslOCI-r8-50:-N5eWSua3PiwB2PgvVh5:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a146e6fadccc3863f7ac3fe470120ba0eb7121d/ci/verify-locked-down-signatures.sh#L50)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

Similarly to my other comment:

```suggestion
readonly SEPARATOR=';'
```
</blockquote></details>

Done.
___
*[`ci/verify-locked-down-signatures.sh` line 51 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N3UQuE_gLqHoczslOCI-r8-51:-N5eb0la5RH7tHC93our:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a146e6fadccc3863f7ac3fe470120ba0eb7121d/ci/verify-locked-down-signatures.sh#L51)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

This variable could also be flagged as a constant:

```suggestion
readonly LOCKED_DOWN_FILES=$(cat $SCRIPT_DIR/../.github/workflows/verify-locked-down-signatures.yml \
```
</blockquote></details>

Done.
___
*[`ci/verify-locked-down-signatures.sh` line 58 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N5eFjKd6IePVRsnC30-:-N5eankD4fyuq_ANIZ9h:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a146e6fadccc3863f7ac3fe470120ba0eb7121d/ci/verify-locked-down-signatures.sh#L58)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

For the path `ci/keys` this will be a directory. The current code here won't `git rev-list` each individual key file, but rather the entire `keys` directory. I think that's fine, because git will still list every commit any file in it was changed. But maybe name the variable `locked_path` instead to not say it's a file when it strictly isn't?
</blockquote></details>

Done.
___
*[`ci/verify-locked-down-signatures.sh` line 65 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N5eCnfqA42vTtLzcbGk:-N5ea1ArAKpYj0p_W6_M:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a146e6fadccc3863f7ac3fe470120ba0eb7121d/ci/verify-locked-down-signatures.sh#L65)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nitpick. I don't think you need a subshell here. Just `if ! command` should work
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-28 14:35 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 3 of 12 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad, @faern, and @MrChocolatine)



<!-- Sent from Reviewable.io -->

2022-07-01 09:04 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 3 of 12 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad, @faern, and @MrChocolatine)

___
*[`ci/verify-locked-down-signatures.sh` line 51 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N3UQuE_gLqHoczslOCI-r8-51:-N5t-5-I2ilNcJRcFKX6:bkr4m4d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a146e6fadccc3863f7ac3fe470120ba0eb7121d/ci/verify-locked-down-signatures.sh#L51)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This feels overkill to me. It adds an extra line of code, and it's not very likely to become a bug or issue if we don't `readonly` the variable.


<!-- Sent from Reviewable.io -->

2022-07-01 12:20 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 3 of 12 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad, @faern, and @MrChocolatine)

___
*[`ci/verify-locked-down-signatures.sh` line 5 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N3UQuE_gLqHoczslOCI-r8-5:-N5th6sR6gIa5-mBPrGo:bvc5bxk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a146e6fadccc3863f7ac3fe470120ba0eb7121d/ci/verify-locked-down-signatures.sh#L5)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Good suggestion!
```
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly SCRIPT_DIR
```
However above seems more idiomatic per:
https://www.shellcheck.net/wiki/SC2155
</blockquote></details>

Let's not get this PR blocked on bash bikeshedding. That can be had in the coding guidelines repository. We need this CI job to be merged.


<!-- Sent from Reviewable.io -->

2022-07-01 12:25 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 3 of 12 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad, @faern, and @MrChocolatine)

___
*[`ci/verify-locked-down-signatures.sh` line 5 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N3UQuE_gLqHoczslOCI-r8-5:-N5thJNG-CmlJTIw_vKy:brxp9sq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a146e6fadccc3863f7ac3fe470120ba0eb7121d/ci/verify-locked-down-signatures.sh#L5)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Let's not get this PR blocked on bash bikeshedding. That can be had in the coding guidelines repository. We need this CI job to be merged.
</blockquote></details>

Sounds good.
___
*[`ci/verify-locked-down-signatures.sh` line 51 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N3UQuE_gLqHoczslOCI-r8-51:-N5thQGoDe_2JMle3iD_:bixoe50) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a146e6fadccc3863f7ac3fe470120ba0eb7121d/ci/verify-locked-down-signatures.sh#L51)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This feels overkill to me. It adds an extra line of code, and it's not very likely to become a bug or issue if we don't `readonly` the variable.
</blockquote></details>

It might be a little bit overkill, but `locked_down_paths` is not super obviously read-only now that it's not longer SCREAMING_SNAKE_CASE. In the spirit of not bike-shedding further I suggest we just merge this as is.
Every other complaint is solved and this seems like this *might* be good.


<!-- Sent from Reviewable.io -->

2022-07-01 12:33 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 3 of 12 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad, @faern, and @MrChocolatine)



<!-- Sent from Reviewable.io -->

2022-07-01 12:40 UTC, faern reviewed
> Reviewed 8 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 11 of 12 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad, @faern, and @MrChocolatine)



<!-- Sent from Reviewable.io -->

2022-07-05 07:52 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 10 of 12 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad, @faern, and @MrChocolatine)

___
*[`ci/verify-locked-down-signatures.sh` line 51 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N3UQuE_gLqHoczslOCI-r8-51:-N6CI92d8rQREy2MgNrk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a146e6fadccc3863f7ac3fe470120ba0eb7121d/ci/verify-locked-down-signatures.sh#L51)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

On slack we agreed to not start littering with `readonly` for these uncertain cases until we have established a standard. So this should go away.
</blockquote></details>

Done.
___
*[`ci/verify-locked-down-signatures.sh` line 64 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N5eCgG4ByJWzS0wJkln:-N6CI8GU2ctZVXDyg9K4:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0a146e6fadccc3863f7ac3fe470120ba0eb7121d/ci/verify-locked-down-signatures.sh#L64)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Style nitpick. `for ...; do` on one line
</blockquote></details>

Fixed
___
*[`ci/verify-lockfile-signature.sh` line 5 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N2H7xSHDhvRogsxVC4x:-N6CJIOi0kCd4l3DkKPb:b-4b2jpp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8187649d4cf4ac85233be6f776f0964a88115136/ci/verify-lockfile-signature.sh#L5)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

That sounds like a good idea, I'll add this in. Perhaps it might also be a good idea to make the naming a bit more generic in case the script will be used for other types of security critical files in the future?
</blockquote></details>

This is done.


<!-- Sent from Reviewable.io -->

2022-07-05 07:58 UTC, faern reviewed
> Reviewed 1 of 1 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: all files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @MrChocolatine)

___
*[`.github/workflows/verify-locked-down-signatures.yml` line 25 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N4Bn0Ao3x4MNwwTXvd0:-N6CMRi2AZZw8fy9Dwhg:boyjtr1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1ed33e1c2dc6b9bd18031de107dedf1ccaa751/.github/workflows/verify-locked-down-signatures.yml#L25)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Sounds like a good idea! `github.base_ref` can be used for that, however note:

"This property is only available when the event that triggers a workflow run is either `pull_request` or `pull_request_target`"

https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
</blockquote></details>

This can be looked at later if hard to solve now.


<!-- Sent from Reviewable.io -->

2022-07-05 08:05 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 11 of 12 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad, @faern, @Jontified, and @MrChocolatine)

___
*[`ci/verify-locked-down-signatures.sh` line 16 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N6CNwrUCBOSGbyOtvs1:-N6CNwrUCBOSGbyOtvs2:b3vun1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1519ccec27243c819323cccf74f780dfd7a1da9d/ci/verify-locked-down-signatures.sh#L16)):*
> ```Shell
> # The whitelisted commit can be set in order to allow github actions to only check changes
> # since origin/master
> whitelisted_commit="5d41b8a1d9745fbb3ff81ea6ea2eb8f202ca7ed0"
> ```

I suppose this commit hash has to be changed? Or have we really been signing cleanly since then? Sounds too good to be true :) But that can be fixed after merging also. Since our CI does not force us to sign, we have no incentive to sign. So I guess we need to merge this first.


<!-- Sent from Reviewable.io -->

2022-07-05 08:11 UTC, faern reviewed
> Reviewed 1 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad, @faern, and @MrChocolatine)



<!-- Sent from Reviewable.io -->

2022-07-05 08:12 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-:-N6CPccIEqPA3NGddd9p:bnfp4nl)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad, @faern, and @MrChocolatine)



<!-- Sent from Reviewable.io -->

2022-07-05 08:44 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad, @faern, and @MrChocolatine)

___
*[`ci/verify-locked-down-signatures.sh` line 16 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N6CNwrUCBOSGbyOtvs1:-N6CWvRDC_m6xEAyGk0t:bmrewx0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1519ccec27243c819323cccf74f780dfd7a1da9d/ci/verify-locked-down-signatures.sh#L16)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I suppose this commit hash has to be changed? Or have we really been signing cleanly since then? Sounds too good to be true :) But that can be fixed after merging also. Since our CI does not force us to sign, we have no incentive to sign. So I guess we need to merge this first.
</blockquote></details>

Changed this hash to the latest master and signed all of the commits in this PR. We should not need to merge this later.


<!-- Sent from Reviewable.io -->

2022-07-05 09:08 UTC, faern approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: all files reviewed, 5 unresolved discussions (waiting on @albin-mullvad, @Jontified, and @MrChocolatine)

___
*[`ci/verify-locked-down-signatures.sh` line 72 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N6CbMm79i8KHVirK1aK:-N6CbMm79i8KHVirK1aL:beq9nal) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c63c9f2e12a7a7292200d86bd508515968b6f25c/ci/verify-locked-down-signatures.sh#L72)):*
> ```Shell
> done
> 
> exit $unsigned_commits_exist
> ```

A bit nitpicky. But I realize from the output of the CI that it's not apparent that this script even ran at all. It prints nothing on success. I feel like we should check `unsigned_commits_exist` here and print a success message before exiting the script if everything worked as expected. As a sort of canary making it easier to detect if the script did not run at all.


<!-- Sent from Reviewable.io -->

2022-07-05 09:20 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 11 of 12 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad, @faern, @Jontified, and @MrChocolatine)

___
*[`ci/verify-locked-down-signatures.sh` line 16 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N6Ce6DF7t7Fb2xig7Gd:-N6Ce6DF7t7Fb2xig7Ge:bl6ufwv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bdc55e4974fbe237af6dca06824a26005fcd1458/ci/verify-locked-down-signatures.sh#L16)):*
> ```Shell
> # The whitelisted commit can be set in order to allow github actions to only check changes
> # since origin/master
> whitelisted_commit="618130520"
> ```

I think I signed everything between the last one and here. So should not need to bump. But does not matter.


<!-- Sent from Reviewable.io -->

2022-07-05 09:21 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: 11 of 12 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad, @faern, and @MrChocolatine)

___
*[`ci/verify-locked-down-signatures.sh` line 72 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583#-N6CbMm79i8KHVirK1aK:-N6CeZMaBVwWrCXwh2ZU:b-hcihat) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c63c9f2e12a7a7292200d86bd508515968b6f25c/ci/verify-locked-down-signatures.sh#L72)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

A bit nitpicky. But I realize from the output of the CI that it's not apparent that this script even ran at all. It prints nothing on success. I feel like we should check `unsigned_commits_exist` here and print a success message before exiting the script if everything worked as expected. As a sort of canary making it easier to detect if the script did not run at all.
</blockquote></details>

Added this.


<!-- Sent from Reviewable.io -->

2022-07-05 09:22 UTC, faern reviewed
> Reviewed 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: all files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @MrChocolatine)



<!-- Sent from Reviewable.io -->

2022-07-05 09:24 UTC, faern approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3583)* status: all files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @MrChocolatine)



<!-- Sent from Reviewable.io -->

2022-07-05 09:28 UTC, merged