Add CLI command for listing excluded processes on Windows
mullvad/mullvadvpn-app pull request #3642
Opened 2022-06-07 18:24 UTC by dlon

This PR adds `mullvad split-tunnel pid list`, which prints a list of all currently excluded processes, e.g.

```
12345 I  [firefox.exe]
54321 C  [test.exe]
```

The first column contains the process identifier, the second whether the process is split due to its image being in the list of processes to exclude (C) or due because it is a child process of such a process (I), and the final column contains the name of the image.

2022-06-09 08:50 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-cli/src/cmds/split_tunnel/windows.rs` line 115 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642#-N46drQS9IhA4rM29xAM:-N46drQS9IhA4rM29xAN:bhk9lxi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63cb3bddac3097115a7cc41c901a11cfcfb4c007/mullvad-cli/src/cmds/split_tunnel/windows.rs#L115)):*
> processes to exclude (C) or due to its being a child process of such a process (I),

This information seems to be available only in the PR description? How will a user of the CLI know what `C` and `I` means? Can this CLI command maybe get a better help text, or can we expand these letters to be something self-explanatory please?


<!-- Sent from Reviewable.io -->

2022-06-09 10:53 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`mullvad-cli/src/cmds/split_tunnel/windows.rs` line 115 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642#-N46drQS9IhA4rM29xAM:-N471o1oDzfYeq87HEUl:bx80ffb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63cb3bddac3097115a7cc41c901a11cfcfb4c007/mullvad-cli/src/cmds/split_tunnel/windows.rs#L115)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

> processes to exclude (C) or due to its being a child process of such a process (I),

This information seems to be available only in the PR description? How will a user of the CLI know what `C` and `I` means? Can this CLI command maybe get a better help text, or can we expand these letters to be something self-explanatory please?
</blockquote></details>

Done. It now looks pretty much like this:

```
1234      subprocess     a.exe
4321                     b.exe
```


<!-- Sent from Reviewable.io -->

2022-06-09 12:51 UTC, pinkisemils reviewed
> Reviewed 12 of 12 files at r1, 6 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)



<!-- Sent from Reviewable.io -->

2022-06-09 14:31 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[`talpid-core/src/split_tunnel/windows/driver.rs` line 793 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642#-N47WqzT5R-N_3LG-XfZ:-N47WqzT5R-N_3LG-Xf_:be41vwf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9344715a0974497611cb59596d9d5338e66eba6/talpid-core/src/split_tunnel/windows/driver.rs#L793)):*
> ```XML
>             0u8,
>         );
>         Some(buffer)
> ```

The backing vector could be declared outside of this block and the `out_buffer` could just hold the mutable slice to the backing buffer instead. This would help with the `buffer.as_mut().map()` dance later.


<!-- Sent from Reviewable.io -->

2022-06-10 11:20 UTC, pinkisemils reviewed
> Reviewed 2 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[`talpid-core/src/split_tunnel/windows/driver.rs` line 777 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642#-N4BzV0T9TrBqOTJ2w3w:-N4BzV0T9TrBqOTJ2w3x:b-1jyy5i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9344715a0974497611cb59596d9d5338e66eba6/talpid-core/src/split_tunnel/windows/driver.rs#L777)):*
> ```XML
> /// # Safety
> ///
> /// `device` must be a valid device handle.
> ```

The unsafety could be reduced by newtyping the `RawHandle` and then `device_io_control` can be less unsafe and just take the newtype instead.


<!-- Sent from Reviewable.io -->

2022-06-14 08:57 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[`talpid-core/src/split_tunnel/windows/driver.rs` line 777 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642#-N4BzV0T9TrBqOTJ2w3w:-N4HeTa8D95u7K6UlI8r:bxsqixq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9344715a0974497611cb59596d9d5338e66eba6/talpid-core/src/split_tunnel/windows/driver.rs#L777)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The unsafety could be reduced by newtyping the `RawHandle` and then `device_io_control` can be less unsafe and just take the newtype instead.
</blockquote></details>

I've changed it to `fs::File`. Not sure how sane it is to mark it as safe despite that. But removing the `timeout` parameter guarantees that the out buffer can't be written to after a timeout, at least.


<!-- Sent from Reviewable.io -->

2022-06-14 10:36 UTC, pinkisemils reviewed
> Reviewed 2 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @faern and @pinkisemils)

___
*[`talpid-core/src/split_tunnel/windows/driver.rs` line 777 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642#-N4BzV0T9TrBqOTJ2w3w:-N4WmAoXEaJYcPoOw158:b-y7qwo6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9344715a0974497611cb59596d9d5338e66eba6/talpid-core/src/split_tunnel/windows/driver.rs#L777)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I've changed it to `fs::File`. Not sure how sane it is to mark it as safe despite that. But removing the `timeout` parameter guarantees that the out buffer can't be written to after a timeout, at least.
</blockquote></details>

I was thinking more something along the lines of having a `struct STDriver(RawHandle)` and have the functions be `fn device_io_control(device: &STDriver,...`, but I guess this works too.


<!-- Sent from Reviewable.io -->

2022-06-14 11:02 UTC, pinkisemils reviewed
> Reviewed 1 of 4 files at r3, 2 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2022-06-14 11:24 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`talpid-core/src/split_tunnel/windows/driver.rs` line 777 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642#-N4BzV0T9TrBqOTJ2w3w:-N4WnqwKCDWs0_VYhO4z:bj0ybbx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9344715a0974497611cb59596d9d5338e66eba6/talpid-core/src/split_tunnel/windows/driver.rs#L777)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I was thinking more something along the lines of having a `struct STDriver(RawHandle)` and have the functions be `fn device_io_control(device: &STDriver,...`, but I guess this works too.
</blockquote></details>

I was trying to keep it generic, but there's no real point. I'll just update this to use `&DeviceHandle`, as it's better than allowing random file handles to be passed in.


<!-- Sent from Reviewable.io -->

2022-06-14 11:25 UTC, pinkisemils approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2022-06-14 11:42 UTC, pinkisemils approved these changes
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2022-06-14 11:58 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`mullvad-cli/src/cmds/split_tunnel/windows.rs` line 115 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3642#-N46drQS9IhA4rM29xAM:-N4X42aH0e9EpDKy2vrY:btojbfd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63cb3bddac3097115a7cc41c901a11cfcfb4c007/mullvad-cli/src/cmds/split_tunnel/windows.rs#L115)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. It now looks pretty much like this:

```
1234      subprocess     [a.exe]
4321                     [b.exe]
```

I guess the brackets are superfluous as well.
</blockquote></details>

Great!


<!-- Sent from Reviewable.io -->

2022-06-14 12:03 UTC, merged