Add last used account to login view
mullvad/mullvadvpn-app pull request #3656
Opened 2022-06-13 14:52 UTC by AndreasShortcut

Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

- Add last used account to the login view
   - Pressing the last used account logs in with this account
   - Pressing the x button next to it removes the saved account
- Minor UI changes to match the design in Zeplin

2022-06-14 08:07 UTC, pronebird requested changes
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @AndreasShortcut)

___
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 359 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WEUCu0QbywyF7dYgE:-N4WEUCu0QbywyF7dYgF:beoc69b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4f40895ed117c5eeddcf19d4ca2e0b34fcc733be/ios/MullvadVPN/AccountInputGroupView.swift#L359)):*
> ```Swift
>     // MARK: - Private
> 
>     @discardableResult private func removeLastUsedAccount() -> Bool {
> ```

Please add a closure or a delegate. See `onSendButton`, it does not initiate a log in from here, instead `LoginViewController` handles that.


<!-- Sent from Reviewable.io -->

2022-06-14 08:13 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656)* status: 1 of 13 files reviewed, 2 unresolved discussions (waiting on @AndreasShortcut)

___
*[`ios/MullvadVPN/LoginViewController.swift` line 240 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WFstX3sK-5FKzZPla:-N4WFstX3sK-5FKzZPlb:b-y01fh6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4f40895ed117c5eeddcf19d4ca2e0b34fcc733be/ios/MullvadVPN/LoginViewController.swift#L240)):*
> ```Swift
>             contentView.accountInputGroup.updateLastUsedAccount()
>         } catch {
>             return
> ```

You can log that error, i.e:

```
import Logging

class LoginViewController {
   private let logger = Logger(label: "LoginViewController")
   // ...  
} 
```

Then in `catch` block:

```
logger.error(
  chainedError: AnyChainedError(error),
  message: "Failed to <#description#>."
)
```

Unless it's `KeychainError.itemNotFound` in that case, since that means that the entry is not found. No need to log that one.


<!-- Sent from Reviewable.io -->

2022-06-14 08:15 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656)* status: 1 of 13 files reviewed, 3 unresolved discussions (waiting on @AndreasShortcut)

___
*[`ios/MullvadVPN/UIColor+Palette.swift` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WGt17AGPCai3O401T:-N4WGt17AGPCai3O401U:b-f2b6na) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4f40895ed117c5eeddcf19d4ca2e0b34fcc733be/ios/MullvadVPN/UIColor%2BPalette.swift#L29)):*
> ```Swift
>             static let borderColor = secondaryColor
>             static let textColor = primaryColor
>             static let backgroundColor = UIColor.white.withAlphaComponent(0.8)
> ```

Based on design mockups in Zeplin, the opacity is 0.4


<!-- Sent from Reviewable.io -->

2022-06-14 08:18 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656)* status: 1 of 13 files reviewed, 4 unresolved discussions (waiting on @AndreasShortcut)

___
*[`ios/MullvadVPN/UIImage+TintColor.swift` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WHGBw5VDGnVNC6_-3:-N4WHGBw5VDGnVNC6_-4:buyn5ph) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5320469393d9f36f5cd061d25dd008d4b4d32a80/ios/MullvadVPN/UIImage%2BTintColor.swift#L13)):*
> ```Swift
> extension UIImage {
>     
>     static let smallClose: UIImage? = { UIImage(named: "IconCloseSml") }()
> ```

This is extension for back-porting the `tintColor` support for iOS 12. Please do inline `UIImage(named: "IconCloseSml")` in the view that uses this asset.


<!-- Sent from Reviewable.io -->

2022-06-14 08:57 UTC, pronebird requested changes
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656)* status: 2 of 13 files reviewed, 9 unresolved discussions (waiting on @AndreasShortcut and @pronebird)

___
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WJ0gCAMHZXea1lwDR:-N4WJ0gDEPZxbsOrhehQ:b-pocbhk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4f40895ed117c5eeddcf19d4ca2e0b34fcc733be/ios/MullvadVPN/AccountInputGroupView.swift#L74)):*
> ```Swift
>     }()
> 
>     private let accountView: UIView = {
> ```

last account and account views, easy to mix them up. Can we rename it to something that's clearer that this is a container for input field?
___
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WHzmB3RA_6KEY8Cs7:-N4WHzmB3RA_6KEY8Cs8:b-m62kqz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68fc78c892a6e25cdb360ce5104d40330add6993/ios/MullvadVPN/AccountInputGroupView.swift#L81)):*
> ```Swift
>         switch loginState {
>         case .default:
>             return privateTextField.isEditing
> ```

This is actually intentional. The border is a "focus". That's the reason why it's rendered as an outline of the account input group view.
___
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 300 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WQEiRE_Gu43DXEqTl:-N4WQEiRE_Gu43DXEqTm:b-en83x4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/45808e8bb65e13d97487bc33f29db1cab541920b/ios/MullvadVPN/AccountInputGroupView.swift#L300)):*
> ```Swift
>     }
> 
>     func updateLastUsedAccount() {
> ```

Instead of a two-step process where you first assign the `lastUsedAccount` and then call `updateLastUsedAccount`, perhaps this could be reworked into single function?

```
func setLastUsedAccount(_ accountNumber: String?, animated: Bool)
```
___
*[`ios/MullvadVPN/LoginViewController.swift` line 102 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WORBJC6_XicLJL4eO:-N4WORBJC6_XicLJL4eP:b-hehme5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5320469393d9f36f5cd061d25dd008d4b4d32a80/ios/MullvadVPN/LoginViewController.swift#L102)):*
> ```Swift
>     override func viewWillAppear(_ animated: Bool) {
>         super.viewWillAppear(animated)
>         updateLastUsedAccount()
> ```

I think you can do it in `viewDidLoad()` _and_ `reset()` methods instead of `viewWillAppear`. This should also prevent undesired animations.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 905 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WP28y25C1La2y3WUQ:-N4WP28y25C1La2y3WUR:b-5ndgl2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5320469393d9f36f5cd061d25dd008d4b4d32a80/ios/MullvadVPN.xcodeproj/project.pbxproj#L905)):*
> ```
> 				58B3F30E2742708B00A2DD38 /* HeaderBarButton.swift */,
> 				58F3C0A3249CB069003E76BE /* HeaderBarView.swift */,
> 				E158B35E285381BE0002F069 /* Helpers */,
> ```

We have a lot of helpers and extensions, so perhaps just add it under `MullvadVPN` and then "Sort by name" and that's it for now. We could reorganize the structure down the road but I think it's that will require some thorough planning. We have some classes that are shared between processes and we have the rest that's solely used by the main process, so perhaps that should be considered as well. It's not cute at the moment I know.


<!-- Sent from Reviewable.io -->

2022-06-14 09:00 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WHzmB3RA_6KEY8Cs7:-N4WQuYv3ZUsbEuNSYgQ:bkftol6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68fc78c892a6e25cdb360ce5104d40330add6993/ios/MullvadVPN/AccountInputGroupView.swift#L81)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This is actually intentional. The border is a "focus". That's the reason why it's rendered as an outline of the account input group view.
</blockquote></details>

I see. In Zeplin it looks like we have a border even before the text field is active. Am I not understanding this correctly?


<!-- Sent from Reviewable.io -->

2022-06-14 09:12 UTC, pronebird requested changes
> Reviewed 2 of 9 files at r1, 4 of 7 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656)* status: 12 of 13 files reviewed, 9 unresolved discussions (waiting on @AndreasShortcut)

___
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WHzmB3RA_6KEY8Cs7:-N4WTyBt6idKNgIO77OX:b52bsy9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68fc78c892a6e25cdb360ce5104d40330add6993/ios/MullvadVPN/AccountInputGroupView.swift#L81)):*
<details><summary><i>Previously, AndreasShortcut wrote…</i></summary><blockquote>

I see. In Zeplin it looks like we have a border even before the text field is active. Am I not understanding this correctly?
</blockquote></details>

Yeah I think it does not reflect all states, but if you look at desktop app, if you lose focus to the text field, then the border disappears. At least this is how it was designed originally.


<!-- Sent from Reviewable.io -->

2022-06-14 09:34 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WJ0gCAMHZXea1lwDR:-N4WZ0-k6QbKbN7x4smJ:b-q461fk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4f40895ed117c5eeddcf19d4ca2e0b34fcc733be/ios/MullvadVPN/AccountInputGroupView.swift#L74)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

last account and account views, easy to mix them up. Can we rename it to something that's clearer that this is a container for input field?
</blockquote></details>

Perhaps topContentView and bottomContentView?


<!-- Sent from Reviewable.io -->

2022-06-14 09:40 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WHzmB3RA_6KEY8Cs7:-N4WXz-g2sm9S_NMXP2b:bo9l39s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68fc78c892a6e25cdb360ce5104d40330add6993/ios/MullvadVPN/AccountInputGroupView.swift#L81)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Yeah I think it does not reflect all states, but if you look at desktop app, if you lose focus to the text field, then the border disappears. At least this is how it was designed originally.
</blockquote></details>

I see, I'll revert it


<!-- Sent from Reviewable.io -->

2022-06-14 10:01 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 300 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WQEiRE_Gu43DXEqTl:-N4WdI389DFOlRtX9--q:b6kn064) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/45808e8bb65e13d97487bc33f29db1cab541920b/ios/MullvadVPN/AccountInputGroupView.swift#L300)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Instead of a two-step process where you first assign the `lastUsedAccount` and then call `updateLastUsedAccount`, perhaps this could be reworked into single function?

```
func setLastUsedAccount(_ accountNumber: String?, animated: Bool)
```
</blockquote></details>

Very good point.


<!-- Sent from Reviewable.io -->

2022-06-14 11:08 UTC, pronebird reviewed
> Reviewed 1 of 9 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656)* status: all files reviewed, 5 unresolved discussions (waiting on @AndreasShortcut)

___
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WJ0gCAMHZXea1lwDR:-N4Wt1EqDAxQ3Vubg58N:balwdvw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4f40895ed117c5eeddcf19d4ca2e0b34fcc733be/ios/MullvadVPN/AccountInputGroupView.swift#L74)):*
<details><summary><i>Previously, AndreasShortcut wrote…</i></summary><blockquote>

Perhaps topContentView and bottomContentView?
</blockquote></details>

Sure, sounds good. Maybe then rename `contentView` to `containerView` or something like that so we don't have a `contentView` that's neither top nor bottom.


<!-- Sent from Reviewable.io -->

2022-06-14 11:09 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656)* status: all files reviewed, 6 unresolved discussions (waiting on @AndreasShortcut)



<!-- Sent from Reviewable.io -->

2022-06-14 14:20 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 300 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WQEiRE_Gu43DXEqTl:-N4X__mSD_gO1KbYVPt4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/45808e8bb65e13d97487bc33f29db1cab541920b/ios/MullvadVPN/AccountInputGroupView.swift#L300)):*
<details><summary><i>Previously, AndreasShortcut wrote…</i></summary><blockquote>

Very good point.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-14 14:24 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WJ0gCAMHZXea1lwDR:-N4X_jjC0YVGhhMHwDOD:b-uw04yi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4f40895ed117c5eeddcf19d4ca2e0b34fcc733be/ios/MullvadVPN/AccountInputGroupView.swift#L74)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Sure, sounds good. Maybe then rename `contentView` to `containerView` or something like that so we don't have a `contentView` that's neither top nor bottom.
</blockquote></details>

Hm, good point. Then I actually prefer to keep contentView as it was, since that's similar to e.g. a table view. And then maybe calling the other ones topContainerView and bottomContainerView or topRowView and bottomRowView. 


<!-- Sent from Reviewable.io -->

2022-06-14 14:27 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 359 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WEUCu0QbywyF7dYgE:-N4Xb44n4vpVoZgTL5ff:b-wem2mj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4f40895ed117c5eeddcf19d4ca2e0b34fcc733be/ios/MullvadVPN/AccountInputGroupView.swift#L359)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Please add a closure or a delegate. See `onSendButton`, it does not initiate a log in from here, instead `LoginViewController` handles that.
</blockquote></details>

Done. I went the delegate route, and also refactored onSendButton


<!-- Sent from Reviewable.io -->

2022-06-14 14:30 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/LoginViewController.swift` line 102 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WORBJC6_XicLJL4eO:-N4XbxCr5JgbI8NAUv7d:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5320469393d9f36f5cd061d25dd008d4b4d32a80/ios/MullvadVPN/LoginViewController.swift#L102)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think you can do it in `viewDidLoad()` _and_ `reset()` methods instead of `viewWillAppear`. This should also prevent undesired animations.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-06-14 14:31 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/LoginViewController.swift` line 240 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WFstX3sK-5FKzZPla:-N4XbzzA-xZcsravvw3G:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4f40895ed117c5eeddcf19d4ca2e0b34fcc733be/ios/MullvadVPN/LoginViewController.swift#L240)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You can log that error, i.e:

```
import Logging

class LoginViewController {
   private let logger = Logger(label: "LoginViewController")
   // ...  
} 
```

Then in `catch` block:

```
logger.error(
  chainedError: AnyChainedError(error),
  message: "Failed to <#description#>."
)
```

Unless it's `KeychainError.itemNotFound` in that case, since that means that the entry is not found. No need to log that one.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-06-14 14:31 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/UIColor+Palette.swift` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WGt17AGPCai3O401T:-N4Xc1X13yyR720wGGW9:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4f40895ed117c5eeddcf19d4ca2e0b34fcc733be/ios/MullvadVPN/UIColor%2BPalette.swift#L29)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Based on design mockups in Zeplin, the opacity is 0.4
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-06-14 14:36 UTC, AndreasShortcut commented
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 905 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WP28y25C1La2y3WUQ:-N4Xcrmo2g9rJJ5v3bL1:bakri4y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5320469393d9f36f5cd061d25dd008d4b4d32a80/ios/MullvadVPN.xcodeproj/project.pbxproj#L905)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

We have a lot of helpers and extensions, so perhaps just add it under `MullvadVPN` and then "Sort by name" and that's it for now. We could reorganize the structure down the road but I think it's that will require some thorough planning. We have some classes that are shared between processes and we have the rest that's solely used by the main process, so perhaps that should be considered as well. It's not cute at the moment I know.
</blockquote></details>

Done. Yes, that makes sense.


<!-- Sent from Reviewable.io -->

2022-06-14 14:36 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/UIImage+TintColor.swift` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WHGBw5VDGnVNC6_-3:-N4XdDomEppGAauOsDwl:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5320469393d9f36f5cd061d25dd008d4b4d32a80/ios/MullvadVPN/UIImage%2BTintColor.swift#L13)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This is extension for back-porting the `tintColor` support for iOS 12. Please do inline `UIImage(named: "IconCloseSml")` in the view that uses this asset.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-06-14 14:46 UTC, pronebird reviewed
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, 2 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @pronebird)

___
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4WJ0gCAMHZXea1lwDR:-N4XammW12WQC852GNo6:b-ptdl8s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4f40895ed117c5eeddcf19d4ca2e0b34fcc733be/ios/MullvadVPN/AccountInputGroupView.swift#L74)):*
<details><summary><i>Previously, AndreasShortcut wrote…</i></summary><blockquote>

Hm, good point. Then I actually prefer to keep contentView as it was, since that's similar to e.g. a table view. And then maybe calling the other ones topContainerView and bottomContainerView or topRowView and bottomRowView. 
</blockquote></details>

Looks good :+1: 
___
*[`ios/MullvadVPN/LoginViewController.swift` line 409 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4Xe6qc746qyPF_nE9n:-N4Xe6qc746qyPF_nE9o:b-dc71ch) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5adc74cdd1b35c0045a3b3ace3afa557b1f616ae/ios/MullvadVPN/LoginViewController.swift#L409)):*
> ```Swift
> }
> 
> protocol AccountInputGroupViewDelegate: AnyObject {
> ```

FYI Canonical delegate pattern in Objective-C or Swift is usually implemented in a way when the subject is passed back to object implementing delegate:

```
protocol AccountInputGroupDelegate: AnyObject {
  func accountInputGroupShouldLogin(_ view: AccountInputGroupView) -> Bool
  func accountInputGroupShouldRemoveLastUsedAccount(_ view: AccountInputGroupView) -> Bool
}
```

Although this is rather picky and perhaps unnecessary, but that's how I'd usually find delegate implemented in the system frameworks. 

Just found a decent article on that btw: https://www.swiftbysundell.com/articles/delegation-in-swift/


<!-- Sent from Reviewable.io -->

2022-06-14 15:22 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/LoginViewController.swift` line 409 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4Xe6qc746qyPF_nE9n:-N4XiSOV-y7j8ZL26iza:bkje5o4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5adc74cdd1b35c0045a3b3ace3afa557b1f616ae/ios/MullvadVPN/LoginViewController.swift#L409)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI Canonical delegate pattern in Objective-C or Swift is usually implemented in a way when the subject is passed back to object implementing delegate:

```
protocol AccountInputGroupDelegate: AnyObject {
  func accountInputGroupShouldLogin(_ view: AccountInputGroupView) -> Bool
  func accountInputGroupShouldRemoveLastUsedAccount(_ view: AccountInputGroupView) -> Bool
}
```

Although this is rather picky and perhaps unnecessary, but that's how I'd usually find delegate implemented in the system frameworks. 

Just found a decent article on that btw: https://www.swiftbysundell.com/articles/delegation-in-swift/
</blockquote></details>

Yep, that's true. I opted against passing the view, since I don't see any reason we would ever have more than one. The point about the methods being recognizable is fair though.

Anyways, I've changed it now


<!-- Sent from Reviewable.io -->

2022-06-14 16:00 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @AndreasShortcut and @pronebird)

___
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 344 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4XtZ0i1Qpl727Qp-rR:-N4XtZ0i1Qpl727Qp-rS:b-muougk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e5e3d6da882558174958050fae380e4cce6b66b/ios/MullvadVPN/AccountInputGroupView.swift#L344)):*
> ```Swift
> 
>     @objc private func didTapLastUsedAccount() {
>         guard let accountNumber = lastUsedAccountButton.titleLabel?.text else { return }
> ```

Can we please store the last used account as a property and use it as a source of truth instead of snapping it from the button label?
___
*[`ios/MullvadVPN/LoginViewController.swift` line 406 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4XufHE2EPYDuugC6Cv:-N4XufHE2EPYDuugC6Cw:br5z6v6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e5e3d6da882558174958050fae380e4cce6b66b/ios/MullvadVPN/LoginViewController.swift#L406)):*
> ```Swift
> }
> 
> protocol AccountInputGroupViewDelegate: AnyObject {
> ```

Since the declaration for the delegate protocol is for `AccountInputGroupView`, perhaps it belongs in `AccountInputGroupView.swift` and not in `LoginViewController.swift`?

`LoginViewController` extension implementing `AccountInputGroupViewDelegate` does make sense to be placed here though.


<!-- Sent from Reviewable.io -->

2022-06-14 16:01 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @AndreasShortcut and @pronebird)

___
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 359 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4Xw_ro-0ILLQsfXzki:-N4Xw_rp7tZgbWVvMjbs:b-y7mvi9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e5e3d6da882558174958050fae380e4cce6b66b/ios/MullvadVPN/AccountInputGroupView.swift#L359)):*
> ```Swift
>     // MARK: - Private
>     
>     private static func accountNumberFont() -> UIFont {
> ```

Great! :+1: 


<!-- Sent from Reviewable.io -->

2022-06-14 16:13 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @AndreasShortcut and @pronebird)

___
*[`ios/MullvadVPN/StringFormatter.swift` line 11 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4Xz8BZ1FPBavKu4nqp:-N4Xz8BZ1FPBavKu4nqq:b-px62w8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e5e3d6da882558174958050fae380e4cce6b66b/ios/MullvadVPN/StringFormatter.swift#L11)):*
> ```Swift
> import Foundation
> 
> struct StringFormatter {
> ```

FYI `enum` without cases is a decent alternative to `struct` for namespaces, since it does not have constructor.


<!-- Sent from Reviewable.io -->

2022-06-15 07:28 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 344 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4XtZ0i1Qpl727Qp-rR:-N4aFrhtD6cPZpok2DFa:b92p7ca) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e5e3d6da882558174958050fae380e4cce6b66b/ios/MullvadVPN/AccountInputGroupView.swift#L344)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Can we please store the last used account as a property and use it as a source of truth instead of snapping it from the button label?
</blockquote></details>

Yes, good point. Done!


<!-- Sent from Reviewable.io -->

2022-06-15 07:40 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/LoginViewController.swift` line 406 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4XufHE2EPYDuugC6Cv:-N4aHpiwEix5tlmfDcT7:b-x9vcb9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e5e3d6da882558174958050fae380e4cce6b66b/ios/MullvadVPN/LoginViewController.swift#L406)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Since the declaration for the delegate protocol is for `AccountInputGroupView`, perhaps it belongs in `AccountInputGroupView.swift` and not in `LoginViewController.swift`?

`LoginViewController` extension implementing `AccountInputGroupViewDelegate` does make sense to be placed here though.
</blockquote></details>

Good point! Not entirely sure what the convention is here. Could perhaps even be in its own file. I put it at the top of AccountInputGroupView now. Is that good with you?


<!-- Sent from Reviewable.io -->

2022-06-15 08:03 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @AndreasShortcut and @pronebird)

___
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 352 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4aNlna9zfvVqUy7IuL:-N4aNlnb85CAQofjXdbs:b-8va509) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/add499244edc9e144e9114c5c05168a611b5a1ec/ios/MullvadVPN/AccountInputGroupView.swift#L352)):*
> ```Swift
> 
>     @objc private func didTapLastUsedAccount() {
>         privateTextField.autoformattingText = lastUsedAccount
> ```

Same here, use `setToken(lastUsedAccount)` as it will make sure to enable the send button. However less relevant as the next thing that should happen is the state transition to logging in state, but for consistency I think it makes sense.
___
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 360 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4aN7rrAiqR7WcIkLck:-N4aN7rrAiqR7WcIkLcl:b-h3rp92) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/add499244edc9e144e9114c5c05168a611b5a1ec/ios/MullvadVPN/AccountInputGroupView.swift#L360)):*
> ```Swift
>     @objc private func didTapRemoveLastUsedAccount() {
>         if self.delegate?.accountInputGroupViewShouldRemoveLastUsedAccount(self) ?? false {
>             privateTextField.autoformattingText = ""
> ```

Perhaps use `clearToken()` as it also makes sure to disable the send button.
___
*[`ios/MullvadVPN/LoginViewController.swift` line 406 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4XufHE2EPYDuugC6Cv:-N4aNNygB6y8enChiDr7:b-k614gu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e5e3d6da882558174958050fae380e4cce6b66b/ios/MullvadVPN/LoginViewController.swift#L406)):*
<details><summary><i>Previously, AndreasShortcut wrote…</i></summary><blockquote>

Good point! Not entirely sure what the convention is here. Could perhaps even be in its own file. I put it at the top of AccountInputGroupView now. Is that good with you?
</blockquote></details>

Yes, thanks!


<!-- Sent from Reviewable.io -->

2022-06-15 10:23 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 352 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4aNlna9zfvVqUy7IuL:-N4asqjWCeqODhkkStFx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/add499244edc9e144e9114c5c05168a611b5a1ec/ios/MullvadVPN/AccountInputGroupView.swift#L352)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Same here, use `setToken(lastUsedAccount)` as it will make sure to enable the send button. However less relevant as the next thing that should happen is the state transition to logging in state, but for consistency I think it makes sense.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-15 10:23 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 360 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4aN7rrAiqR7WcIkLck:-N4assFv9-_P1X6PIz7G:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/add499244edc9e144e9114c5c05168a611b5a1ec/ios/MullvadVPN/AccountInputGroupView.swift#L360)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Perhaps use `clearToken()` as it also makes sure to disable the send button.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-15 12:54 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/AccountInputGroupView.swift` line 280 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4bLGBD5RR-wT0cQVyA:-N4bQXrG5PFOHpzV15oR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7702ee83deb8007492ce140ad24b47327f495111/ios/MullvadVPN/AccountInputGroupView.swift#L280)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

As noted on Slack, the last used account should not be displayed when logging in because it makes it possible to log in with the last used account while creating account. 

I'd add a function call to update the visibility of last used account in here, in pseudo code:

```swift
func updateLastUsedAccountVisible() {
  guard hasLastUsedAccountSet() else { 
       hideLastUsedAccount()
       return 
  }

  switch loginState {
       case .default, .failure:
           showLastUsedAccount()
       case .authenticating, .success:
           hideLastUsedAccount()
  }
}

func setLoginState(_ state: LoginState, animated: Bool) { 
  // all code from before...

  updateLastUsedAccountVisible()
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-15 12:59 UTC, AndreasShortcut commented
*[`ios/MullvadVPN/LoginViewController.swift` line 231 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-N4bKVyI2PF1TCTmnifp:-N4bRZX1D9eMmUFPhJk8:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7702ee83deb8007492ce140ad24b47327f495111/ios/MullvadVPN/LoginViewController.swift#L231)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI nitpick: superficial `return`
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2022-06-15 13:16 UTC, pronebird approved these changes
Looks ace! Let's rebase it on top of `master`, trim leftover whitespace and then merge <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656#-:-N4bV8pP7Ra5SIjoiEFS:batiesc)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-06-15 13:17 UTC, pronebird approved these changes
> Reviewed 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3656)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-06-15 13:18 UTC, merged