Windows auto set mtu
mullvad/mullvadvpn-app pull request #3703
Opened 2022-06-28 07:20 UTC by Jontified

This PR makes the Windows daemon look up the MTU of the default interface and use that as the default in the Wireguard tunnel.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [x] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3703)

2022-07-04 11:08 UTC, dlon requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3703)* status: all files reviewed, 1 unresolved discussion (waiting on @Jontified)

___
*[`talpid-core/src/routing/windows.rs` line 129 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3703#-N67mg6ZBhJysb6YOHe2:-N67mg6ZBhJysb6YOHe3:b-dfsdgw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0ae0af9e4a44c25472193acebbbdc29bd06b88fe/talpid-core/src/routing/windows.rs#L129)):*
> ```XML
>                     );
>                 }
>                 RouteManagerCommand::GetMtuForRoute(ip, tx) => {
> ```

This doesn't need to be in the route manager at all. Is it here because we want to have the same interface on Linux and Windows? That does make sense to me.
___
*[`talpid-core/src/routing/windows.rs` line 201 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3703#-N67qEa5-62YsOcYqFdR:-N67qEa5-62YsOcYqFdS:b-xm244r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0ae0af9e4a44c25472193acebbbdc29bd06b88fe/talpid-core/src/routing/windows.rs#L201)):*
> ```XML
>             };
>             let interface_row = crate::windows::get_ip_interface_entry(addr_family, &luid)
>                 .map_err(|_| Error::GetMtu)?;
> ```

I think either the io error should be logged here, or it should be the source. Currently, it is impossible to figure out why `get_mtu_for_route` fails based on the logs.


<!-- Sent from Reviewable.io -->

2022-07-08 16:51 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3703)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-core/src/routing/windows.rs` line 129 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3703#-N67mg6ZBhJysb6YOHe2:-N6TOnBg4mjWU43clpvv:b-f3ed8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0ae0af9e4a44c25472193acebbbdc29bd06b88fe/talpid-core/src/routing/windows.rs#L129)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This doesn't need to be in the route manager at all. Is it here because we want to have the same interface on Linux and Windows? That does make sense to me.
</blockquote></details>

It is because we want to have the same interface for both Linux and windows. I'm not sure if that's the right decision but I'll keep it like this unless you disagree.
___
*[`talpid-core/src/routing/windows.rs` line 201 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3703#-N67qEa5-62YsOcYqFdR:-N6TRQyZ3NIgQIOXixrC:b-dkciup) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0ae0af9e4a44c25472193acebbbdc29bd06b88fe/talpid-core/src/routing/windows.rs#L201)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think either the io error should be logged here, or it should be the source. Currently, it is impossible to figure out why `get_mtu_for_route` fails based on the logs.
</blockquote></details>

Good point.
I decided to go with the logging option since
1. We want to both log the error from `winnet` and from `crate::windows` and we would either have to log at least one or create new error variants which encapsulate them.
2. We are not planning on treating these errors differently anyway, an error here will simply result in not setting the MTU.
3. It's nice to not have the interface use foreign errors if avoidable.
4. Creating multiple error variants just to log them and not treat them differently seems unnecessary.

I also realized that we should probably log the fact that setting the MTU fails for whatever reason if an error occurs. I've added this as well.


<!-- Sent from Reviewable.io -->

2022-07-11 11:45 UTC, dlon approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3703)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`talpid-core/src/routing/windows.rs` line 200 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3703#-N6h3IwI6zn5bdx-AA_Q:-N6h3IwI6zn5bdx-AA_R:b-dxfsxt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/89d71e03c4da67b56587ed06307a6a796a9164e4/talpid-core/src/routing/windows.rs#L200)):*
> ```XML
>                 Value: route.interface_luid,
>             };
>             let interface_row = match crate::windows::get_ip_interface_entry(addr_family, &luid) {
> ```

Nit: The logging could be thrown into the closure passed to `map_err` for brevity.


<!-- Sent from Reviewable.io -->

2022-07-12 10:01 UTC, dlon approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3703)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-12 10:50 UTC, merged