Migrate a given percentage of windows users to WG
mullvad/mullvadvpn-app pull request #3748
Opened 2022-07-14 15:05 UTC by Jontified

Retrieve a percentage from the version check API response.
Use this percentage to decide if a user should use WG or OpenVpn as
their "automatic" default option.

Currently not implemented for windows or functioning and contains dbg
statements.

Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.

Git checklist:

* [x] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.
* [ ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)

2022-07-15 10:24 UTC, dlon requested changes
> Reviewed 3 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: 3 of 9 files reviewed, 5 unresolved discussions (waiting on @Jontified)

___
*[`CHANGELOG.md` line 34 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N70C-CP4g-qXRahMOTn:-N70C-CP4g-qXRahMOTo:bpuwxmc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/CHANGELOG.md#L34)):*
> ```Markdown
>   default 1500. The 1500 is still the fallback if this for some reason fails. This may stop
>   fragmentation.
> - Windows users now sometimes default to using Wireguard tunnels rather than OpenVpn tunnels.
> ```

Nit: "Windows users" is redundant since this is under the Windows heading. :P
___
*[`mullvad-daemon/src/settings.rs` line 300 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N70IZJFD5-Ocb9t5PIT:-N70IZJFD5-Ocb9t5PIU:b-ootur4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-daemon/src/settings.rs#L300)):*
> ```XML
>     }
> 
>     pub async fn set_x_wg_migration_rand_num(&mut self, x_wg_migration_rand_num: Option<XWgMigrationRandNum>) -> Result<bool, Error> {
> ```

I don't think this function should needed at all. Look at the `SettingsPersister` constructor (`SettingsPersister::load`). You could just generate the random number there, if it's not set.

It would also be nice for the field to be non-optional, but I'm not sure if that can be solved nicely. Using `#[serde(default = "random_number")]` would probably work, but you'd also have to make sure to save the settings if the field was not present in the file.
___
*[`mullvad-daemon/src/tunnel.rs` line 136 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N70NQx14sr3JUMqZhdV:-N70NQx14sr3JUMqZhdW:b-1q684a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-daemon/src/tunnel.rs#L136)):*
> ```XML
> impl InnerParametersGenerator {
>     async fn generate(&mut self, retry_attempt: u32) -> Result<TunnelParameters, Error> {
>         let x_threshold_wg_default = match load_cache(&self.cache_dir).await {
> ```

As we discussed elsewhere, it would probably be simpler to add a `default_tunnel_type` or `preferred_tunnel_type` field to the relay selector config.
___
*[`mullvad-types/src/version.rs` line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N70DMVmArhIxBNR9P-x:-N70DMVmArhIxBNR9P-y:bnsgpx1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-types/src/version.rs#L40)):*
> ```XML
>     /// Temporary field used to decide if a user should default to Wireguard or OpenVpn.
>     /// NOTE: This field will be removed completely in future versions.
>     pub x_threshold_wg_default: Option<XThresholdWgDefault>,
> ```

I think you can get around having to newtype this by just removing `Eq` from this type as well as any type that contains it.
___
*[`mullvad-types/src/settings/mod.rs` line 97 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N70CP799dD3kZ0HIXCd:-N70CP799dD3kZ0HIXCe:bnwmf3n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-types/src/settings/mod.rs#L97)):*
> ```XML
>     /// use wireguard or openvpn when the automatic feature is set. This variable will be removed
>     /// in future versions.
>     pub x_wg_migration_rand_num: Option<XWgMigrationRandNum>,
> ```

Is the newtype really needed here?
___
*[`mullvad-types/src/settings/mod.rs` line 97 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N70MeBG0l3vO8MMtQ09:-N70MeBG0l3vO8MMtQ0A:b-jkugb2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-types/src/settings/mod.rs#L97)):*
> ```XML
>     /// use wireguard or openvpn when the automatic feature is set. This variable will be removed
>     /// in future versions.
>     pub x_wg_migration_rand_num: Option<XWgMigrationRandNum>,
> ```

Nit: Could we keep `settings_version` at the bottom?


<!-- Sent from Reviewable.io -->

2022-07-18 11:48 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: 3 of 9 files reviewed, 7 unresolved discussions (waiting on @Jontified)

___
*[`CHANGELOG.md` line 34 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7Fzm3DDS0Mtd3d0LjN:-N7Fzm3DDS0Mtd3d0LjO:blqwls6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/CHANGELOG.md#L34)):*
> ```Markdown
>   default 1500. The 1500 is still the fallback if this for some reason fails. This may stop
>   fragmentation.
> - Windows users now sometimes default to using Wireguard tunnels rather than OpenVpn tunnels.
> ```

Nit: OpenV**PN** and Wire**G**uard is the correct capitalizations, respectively.
___
*[`mullvad-types/src/version.rs` line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7G1Cl33cVg9UmWWobf:-N7G1Cl33cVg9UmWWobg:b-2po803) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-types/src/version.rs#L40)):*
> ```XML
>     /// Temporary field used to decide if a user should default to Wireguard or OpenVpn.
>     /// NOTE: This field will be removed completely in future versions.
>     pub x_threshold_wg_default: Option<XThresholdWgDefault>,
> ```

`#[serrde(default = 1.0)]`


<!-- Sent from Reviewable.io -->

2022-07-18 14:31 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @dlon and @faern)

___
*[`mullvad-api/src/lib.rs` line 488 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7GXFgJ4qNhDij9-Wmi:-N7GXFgJ4qNhDij9-Wmj:b-lqh8j5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0bcba5915d4286125f7ec6f7517cea55e4df3dc1/mullvad-api/src/lib.rs#L488)):*
> ```XML
> fn default_wg_threshold() -> f32 {
>     // MAGIC NUMBER 1.0 is the default threshold of 100%
>     1.0
> ```

After some discussion with @faern we decided to make the threshold value into a `f32` rather than an `Option`. After doing this I'm a little bit unsure if this is a good idea. We end up having a bunch of `1.0`s as default everywhere, it might be more intuitive if there is just a bunch of `None`s everywhere instead and we then unwrap that to `1.0` when the value is used. Thoughts?
___
*[`mullvad-daemon/src/settings.rs` line 300 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N70IZJFD5-Ocb9t5PIT:-N7GarXn2-MM5rSO5ddY:b9t5t56) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-daemon/src/settings.rs#L300)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I don't think this function should needed at all. Look at the `SettingsPersister` constructor (`SettingsPersister::load`). You could just generate the random number there, if it's not set.

It would also be nice for the field to be non-optional, but I'm not sure if that can be solved nicely. Using `#[serde(default = "random_number")]` would probably work, but you'd also have to make sure to save the settings if the field was not present in the file.
</blockquote></details>

You make a good point. The new solution is to avoid having an option and instead defaulting to a number outside of the range (-1) and inside of `SettingsPersister::load` check if the random value is outside of the range and in that case generate a new value and save it.
___
*[`mullvad-types/src/version.rs` line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N70DMVmArhIxBNR9P-x:-N7GYERC0VgR_OjdP2u1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-types/src/version.rs#L40)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think you can get around having to newtype this by just removing `Eq` from this type as well as any type that contains it.
</blockquote></details>

Done.
___
*[`mullvad-types/src/version.rs` line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7G1Cl33cVg9UmWWobf:-N7GYFGlCF08BQp9TPVw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-types/src/version.rs#L40)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`#[serrde(default = 1.0)]`
</blockquote></details>

Done.
___
*[`mullvad-types/src/settings/mod.rs` line 97 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N70CP799dD3kZ0HIXCd:-N7GYGHsEBudIZ7uhQp7:bo8pv6h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-types/src/settings/mod.rs#L97)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is the newtype really needed here?
</blockquote></details>

Removed `Eq`
___
*[`mullvad-daemon/src/tunnel.rs` line 136 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N70NQx14sr3JUMqZhdV:-N7GZO9jCyMJg0tAihLh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-daemon/src/tunnel.rs#L136)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

As we discussed elsewhere, it would probably be simpler to add a `default_tunnel_type` or `preferred_tunnel_type` field to the relay selector config.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-18 16:33 UTC, dlon requested changes
> Reviewed 2 of 11 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: all files reviewed, 5 unresolved discussions (waiting on @faern and @Jontified)

___
*[`mullvad-api/src/lib.rs` line 488 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7GXFgJ4qNhDij9-Wmi:-N7H3eAp87WWltxpBMdY:b-mq516d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0bcba5915d4286125f7ec6f7517cea55e4df3dc1/mullvad-api/src/lib.rs#L488)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

After some discussion with @faern we decided to make the threshold value into a `f32` rather than an `Option`. After doing this I'm a little bit unsure if this is a good idea. We end up having a bunch of `1.0`s as default everywhere, it might be more intuitive if there is just a bunch of `None`s everywhere instead and we then unwrap that to `1.0` when the value is used. Thoughts?
</blockquote></details>

I don't have a strong opinion on this.
___
*[`mullvad-daemon/src/settings.rs` line 300 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N70IZJFD5-Ocb9t5PIT:-N7GxWNO2lTHiJRzELaE:b5qtem8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-daemon/src/settings.rs#L300)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

You make a good point. The new solution is to avoid having an option and instead defaulting to a number outside of the range (-1) and inside of `SettingsPersister::load` check if the random value is outside of the range and in that case generate a new value and save it.
</blockquote></details>

This is pretty good.
___
*[`mullvad-daemon/src/settings.rs` line 76 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7H0eOD542WzkDzqLse:-N7H0eOD542WzkDzqLsf:b1hwo16) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5ec9c9645250acb617b6c7770c7a70ef61e4fd5/mullvad-daemon/src/settings.rs#L76)):*
> ```XML
>             use rand::Rng;
>             let mut rng = rand::thread_rng();
>             settings.wg_migration_rand_num = rng.gen_range(0.0, 1.0);
> ```

This is never reached by `reset`. So the random number might have to be generated in `Self::default_settings` as well, unfortunately.
___
*[`mullvad-relay-selector/src/lib.rs` line 178 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7GxMAe4BmqxoHr0Aql:-N7GxMAf4oNSwPu28sMf:b-sbfy3v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5ec9c9645250acb617b6c7770c7a70ef61e4fd5/mullvad-relay-selector/src/lib.rs#L178)):*
> ```XML
>     pub bridge_settings: BridgeSettings,
>     pub obfuscation_settings: ObfuscationSettings,
>     pub default_tunnel_protocol: DefaultTunnelProtocol,
> ```

Nit: Using `TunnelType` here would probably be fine. Having this additional type doesn't add much.
___
*[`mullvad-types/src/version.rs` line 42 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7H5URH3JjGde13yMHe:-N7H5URH3JjGde13yMHf:b-10on1w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5ec9c9645250acb617b6c7770c7a70ef61e4fd5/mullvad-types/src/version.rs#L42)):*
> ```XML
>     /// NOTE: This field will be removed completely in future versions.
>     // TODO: Should be windows only
>     #[serde(default = "default_wg_threshold")]
> ```

Arguably, the default isn't needed. If the file does not contain the field, it should be discarded anyway (as it will be, if deserialization fails).
___
*[`mullvad-daemon/src/tunnel.rs` line 136 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N70NQx14sr3JUMqZhdV:-N7Gy4c232jI3TSNiWOD:b-6znjz4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-daemon/src/tunnel.rs#L136)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice! This is much better.


<!-- Sent from Reviewable.io -->

2022-07-19 07:59 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @faern)

___
*[`mullvad-daemon/src/settings.rs` line 300 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N70IZJFD5-Ocb9t5PIT:-N7KS4hC4zDm_VM3d1tP:b-p9aie1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-daemon/src/settings.rs#L300)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is pretty good.
</blockquote></details>

After a bit of thinking I'm wondering if this is a good idea. It in a sense allows bugs to silently fall through, if the random value is left uninitialized due to some oversight (such as the reset path) then we end up with having a percentage initialized as -1 rather than None.
-1 in this case is probably fine, it means you'll default to using wireguard. However the practice in general seems flawed. If we for whatever reason do not want to panic in the case of a bug (and instead log it as an error for example) then we could make sure to use `unwrap_or`.
___
*[`mullvad-daemon/src/settings.rs` line 76 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7H0eOD542WzkDzqLse:-N7KS1Op912HBzTIf8Oo:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5ec9c9645250acb617b6c7770c7a70ef61e4fd5/mullvad-daemon/src/settings.rs#L76)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is never reached by `reset`. So the random number might have to be generated in `Self::default_settings` as well, unfortunately.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2022-07-19 11:21 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @dlon and @faern)

___
*[`mullvad-daemon/src/settings.rs` line 76 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7H0eOD542WzkDzqLse:-N7LB-k6DwqoLl___Bm8:b-4nwv5j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5ec9c9645250acb617b6c7770c7a70ef61e4fd5/mullvad-daemon/src/settings.rs#L76)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

`reset` uses the `Default::default` initialization and I've now fixed so that this correctly initializes. `load` is as far as I can see the only public API which loads `Settings` from disk and as such this should be the only place we need to ensure that the value is re-initialized.
___
*[`mullvad-types/src/settings/mod.rs` line 142 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7LAa8E6P3D62frN_hA:-N7LAa8E6P3D62frN_hB:b-i6q1vc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0403d0cc8ef9a4d9090f12ea5a075bb4431c458/mullvad-types/src/settings/mod.rs#L142)):*
> ```XML
>             show_beta_releases: false,
>             // TODO: Should be windows only
>             wg_migration_rand_num: rand_percent(),
> ```

This should make sure that any init of `Settings` that does not go through the filesystem (and serde) contains a correctly initialized value.
It does require that we import `rand` in the types crate. I've imported `rand` 0.8 since that's the one we are trying to target.


<!-- Sent from Reviewable.io -->

2022-07-19 12:29 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: 3 of 11 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`mullvad-types/src/version.rs` line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7G1Cl33cVg9UmWWobf:-N7LOE3P6mb73_8VuuXC:b-w8zvqg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-types/src/version.rs#L40)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Done.
</blockquote></details>

After some discussion with @dlon. I believe the correct behavior is to have the serialization fail to indicate that the cached version is out of date and a newer version should be downloaded. The daemon can function with a None value as the app version.


<!-- Sent from Reviewable.io -->

2022-07-21 06:41 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: 1 of 11 files reviewed, 4 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`CHANGELOG.md` line 35 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7URswX0StkwgUC1x2V:-N7URswX0StkwgUC1x2W:b-209mku) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/51060200514cd37bcb83f759c3b098e6e0dcbb11/CHANGELOG.md#L35)):*
"sometimes defaults" can be interpreted like it's randomized per connection attempt. I also feel like "the daemon" is a bit too specific. Yeah, the daemon creates the connections, but conceptually, the app is the overall entity that creates tunnels from a user perspective. How about:

> The default VPN protocol is slowly being changed to WireGuard. The app fetches the ratio between the protocols from the API.

My formulation answers the question "Why is this being done?" - Because we want to change the default protocol, but in a controlled manner.


<!-- Sent from Reviewable.io -->

2022-07-21 07:02 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: 1 of 11 files reviewed, 3 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`mullvad-types/src/settings/mod.rs` line 142 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7LAa8E6P3D62frN_hA:-N7UYCNu98widy9Xd8sT:b9s4815) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0403d0cc8ef9a4d9090f12ea5a075bb4431c458/mullvad-types/src/settings/mod.rs#L142)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

This should make sure that any init of `Settings` that does not go through the filesystem (and serde) contains a correctly initialized value.
It does require that we import `rand` in the types crate. I've imported `rand` 0.8 since that's the one we are trying to target.
</blockquote></details>

Nit: Personally I think it might be simpler to just have
```rust
wg_migration_rand_num: rand::thread_rng().gen_range(0.0..1.0)
```
over a separate function.

And as we talked about in the office. It might be a nice refactor to not make `Settings` implement `Default` at all. Instead define the default values for all fields in `mullvad-daemon`. The benefits of doing so:
* No need to depend on `rand` in `mullvad-types` (also, having a `Default` implementation return different values on different invocations is not idiomatic.
* All defaults in one place. Currently they are spread out in the entire code base due to `Default` requiring us to implement `Default` for all types that are part of `Settings`, which is types spread out in many places.


<!-- Sent from Reviewable.io -->

2022-07-21 07:04 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: 1 of 11 files reviewed, 4 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`mullvad-relay-selector/src/lib.rs` line 621 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7UZTeY1CY0bErtoWx-:-N7UZTeY1CY0bErtoWx0:bqo0fs3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/51060200514cd37bcb83f759c3b098e6e0dcbb11/mullvad-relay-selector/src/lib.rs#L621)):*
> ```XML
>         bridge_state: BridgeState,
>         retry_attempt: u32,
>         default_tunnel_type: &TunnelType,
> ```

Tiny `Copy` types are usually passed by ownership rather than by reference. I'm surprised clippy does not pick this up? :thinking: 


<!-- Sent from Reviewable.io -->

2022-07-21 08:52 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: 1 of 11 files reviewed, 4 unresolved discussions (waiting on @dlon and @faern)

___
*[`CHANGELOG.md` line 35 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7URswX0StkwgUC1x2V:-N7Uq7iD2J9BnYcNrUtg:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/51060200514cd37bcb83f759c3b098e6e0dcbb11/CHANGELOG.md#L35)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

"sometimes defaults" can be interpreted like it's randomized per connection attempt. I also feel like "the daemon" is a bit too specific. Yeah, the daemon creates the connections, but conceptually, the app is the overall entity that creates tunnels from a user perspective. How about:

> The default VPN protocol is slowly being changed to WireGuard. The app fetches the ratio between the protocols from the API.

My formulation answers the question "Why is this being done?" - Because we want to change the default protocol, but in a controlled manner.
</blockquote></details>

Done.
___
*[`mullvad-relay-selector/src/lib.rs` line 621 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7UZTeY1CY0bErtoWx-:-N7UphsL4d2TpX9BVYGn:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/51060200514cd37bcb83f759c3b098e6e0dcbb11/mullvad-relay-selector/src/lib.rs#L621)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Tiny `Copy` types are usually passed by ownership rather than by reference. I'm surprised clippy does not pick this up? :thinking: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-21 08:53 UTC, dlon requested changes
> Reviewed 1 of 7 files at r4, 1 of 7 files at r5, 7 of 8 files at r6, 1 of 1 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: all files reviewed, 5 unresolved discussions (waiting on @dlon, @faern, and @Jontified)

___
*[`mullvad-relay-selector/src/lib.rs` line 964 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7Uwhme2jBUgblVyNak:-N7Uwhme2jBUgblVyNal:b-uvfcfj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/51060200514cd37bcb83f759c3b098e6e0dcbb11/mullvad-relay-selector/src/lib.rs#L964)):*
> ```XML
>                     });
> 
>                 if location_supports_openvpn {
> ```

This code no longer defaults to WireGuard when the constraints only match wg relays.


<!-- Sent from Reviewable.io -->

2022-07-21 09:28 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @dlon and @faern)

___
*[`mullvad-relay-selector/src/lib.rs` line 964 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N7Uwhme2jBUgblVyNak:-N7V498I74R_jyADOcgh:biyomqq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/51060200514cd37bcb83f759c3b098e6e0dcbb11/mullvad-relay-selector/src/lib.rs#L964)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This code no longer defaults to WireGuard when the constraints only match wg relays.
</blockquote></details>

if `location_supports_openvpn` is false then it will default to using WG for the first two retries and OpenVPN for the remainder. So even if `default_tunnel_type` is passed as `OpenVpn` if the constraints do not permit OpenVPN it should use WG.


<!-- Sent from Reviewable.io -->

2022-07-29 08:53 UTC, faern reviewed
> Reviewed 2 of 8 files at r6, 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`mullvad-daemon/src/settings.rs` line 300 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N70IZJFD5-Ocb9t5PIT:-N87vU3F5fajbl26Bueg:b253tir) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19ec51526b9ed5cdf0ef661073e8950fcc41324c/mullvad-daemon/src/settings.rs#L300)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

After a bit of thinking I'm wondering if this is a good idea. It in a sense allows bugs to silently fall through, if the random value is left uninitialized due to some oversight (such as the reset path) then we end up with having a percentage initialized as -1 rather than None.
-1 in this case is probably fine, it means you'll default to using wireguard. However the practice in general seems flawed. If we for whatever reason do not want to panic in the case of a bug (and instead log it as an error for example) then we could make sure to use `unwrap_or`.
</blockquote></details>

Exposing something that should be initialized as an option is also a design flaw. It tells the user "this should be a number, but I don't trust myself, so you have to handle my errors for me :shrug:"

As discussed AFK. This should be a float, and it should only be initialized in a single place. `Settings` should not implement `Default` and must be loaded from the persister at all times. Even resets should go through this settings management type.
___
*[`mullvad-daemon/src/settings.rs` line 76 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N87v41i-yo0sNUfVAnt:-N87v41i-yo0sNUfVAnu:b-rqk1jj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/46d4b4554c664af12856799b0ee1c04961d21f2a/mullvad-daemon/src/settings.rs#L76)):*
> ```XML
>         // percentage.
>         if settings.wg_migration_rand_num < 0.0 || settings.wg_migration_rand_num > 1.0 {
>             use rand::Rng;
> ```

Nit. But I don't see any reason not to import this at the top of the file.


<!-- Sent from Reviewable.io -->

2022-08-08 13:12 UTC, dlon reviewed
> Reviewed 1 of 1 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-09 12:01 UTC, dlon reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-10 08:20 UTC, faern reviewed
> Reviewed 3 of 8 files at r6, 2 of 3 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`mullvad-daemon/src/settings.rs` line 78 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N95pDEY-TdSPBBEoZZH:-N95pDEY-TdSPBBEoZZI:b-omp6bo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b424c52a4cbb2dfe4d7d72622c8fcd557a26b6ea/mullvad-daemon/src/settings.rs#L78)):*
> ```XML
>         if settings.wg_migration_rand_num < 0.0 || settings.wg_migration_rand_num > 1.0 {
>             let mut rng = rand::thread_rng();
>             settings.wg_migration_rand_num = rng.gen_range(0.0..1.0);
> ```

Not that it really matters. But this range is exclusive of `1.0`. But the if-check above has `>1.0` meaning up there `1.0` is a valid value. Really nitpicky and has absolutely no impact on the results, but a small inconsistency nonetheless


<!-- Sent from Reviewable.io -->

2022-08-10 08:33 UTC, faern requested changes
> Reviewed 1 of 7 files at r4, 1 of 8 files at r6, 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: all files reviewed, 1 unresolved discussion (waiting on @Jontified)

___
*[`mullvad-daemon/src/settings.rs` line 196 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N95sfFNCMMUsaoKFKjA:-N95sfFNCMMUsaoKFKjB:b-5gq13j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b424c52a4cbb2dfe4d7d72622c8fcd557a26b6ea/mullvad-daemon/src/settings.rs#L196)):*
> ```XML
>     /// Modifies `Settings::default()` somewhat, e.g. depending on whether a beta version
>     /// is being run or not.
>     fn default_settings() -> Settings {
> ```

Can we move the randomized field initialization from `Settings::default` into here? Seems more logical since we already have this method for modifying the defaults :thinking: 


<!-- Sent from Reviewable.io -->

2022-08-10 10:14 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`mullvad-daemon/src/settings.rs` line 196 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N95sfFNCMMUsaoKFKjA:-N96DqlC3BebOqjRr-Oo:b-biopa1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b424c52a4cbb2dfe4d7d72622c8fcd557a26b6ea/mullvad-daemon/src/settings.rs#L196)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we move the randomized field initialization from `Settings::default` into here? Seems more logical since we already have this method for modifying the defaults :thinking: 
</blockquote></details>

The problem that occurs is that since `Settings::default` is public it needs to return a correct version of `Settings` and as such must initialize.  We can not remove every public constructor of `Settings` as that would make us unable to create it in the `mullvad-daemon` crate unless we also move `Settings` into this crate.


<!-- Sent from Reviewable.io -->

2022-08-10 14:32 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @dlon, @faern, and @Jontified)

___
*[`docs/relay-selector.md` line 57 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N979vuAC8gzABFFK3La:-N979vuAC8gzABFFK3Lb:b-isk81q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d7d0a9216e3a4b371617e14267ba03faabba218/docs/relay-selector.md#L57)):*
> ```Markdown
> 
> - If no tunnel protocol is specified for tunnel endpoints, then the behavior is different on Windows
>   and other platforms.
> ```

What happened here? This is just a verbatim copy of the above.


<!-- Sent from Reviewable.io -->

2022-08-11 07:39 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @dlon and @faern)

___
*[`docs/relay-selector.md` line 57 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N979vuAC8gzABFFK3La:-N9Apv3h1k1FB6FDLmeQ:b-4da7n8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6d7d0a9216e3a4b371617e14267ba03faabba218/docs/relay-selector.md#L57)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

What happened here? This is just a verbatim copy of the above.
</blockquote></details>

Oops! I made a copy of the old text in order to have a reference when writing and then I forgot that it wasn't just another paragraph. Removed.


<!-- Sent from Reviewable.io -->

2022-08-11 14:45 UTC, faern reviewed
> Reviewed 2 of 2 files at r13, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-12 09:16 UTC, dlon approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`docs/relay-selector.md` line 53 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N9COhpMAv4XZXGeeVcY:-N9COhpMAv4XZXGeeVcZ:b-mke1hv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8748e641a6e11856c5864b8e800de1edc537f86b/docs/relay-selector.md#L53)):*
> ```Markdown
>   - On Windows, a migration to WireGuard is ongoing and a percentage value provided by the API tells
>     clients to randomly decide if they will use WireGuard as a default or OpenVPN as a default.
>     The clients decision will persist over time.
> ```

Nit: "client's" or "clients'".


<!-- Sent from Reviewable.io -->

2022-08-12 10:17 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-12 10:55 UTC, faern requested changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: all files reviewed, 1 unresolved discussion (waiting on @Jontified)

___
*[`mullvad-relay-selector/src/lib.rs` line 279 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N9GgExJ1slsuFrxb7kU:-N9GgExJ1slsuFrxb7kV:b1xwsl0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11c596ff8490cd1e72052095aaba17e0fb882216/mullvad-relay-selector/src/lib.rs#L279)):*
> ```XML
>         bridge_state: BridgeState,
>         retry_attempt: u32,
>         default_tunnel_type: TunnelType,
> ```

Why does a method that takes `&self` need to have this argument passed in? It's stored in `self`.


<!-- Sent from Reviewable.io -->

2022-08-15 07:26 UTC, faern approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`mullvad-relay-selector/src/lib.rs` line 279 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748#-N9GgExJ1slsuFrxb7kU:-N9VO7IxCTkJPL0ifXmg:b-5p8vwu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/11c596ff8490cd1e72052095aaba17e0fb882216/mullvad-relay-selector/src/lib.rs#L279)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why does a method that takes `&self` need to have this argument passed in? It's stored in `self`.
</blockquote></details>

Discussed on slack. Because of how the relay selector is currently designed. We lean towards removing the locks from within this type and instead let everyone who want to use it have a `Arc<Mutex<RelaySelector>>` in order to greatly simplify the relay selector itself.


<!-- Sent from Reviewable.io -->

2022-08-15 07:34 UTC, faern approved these changes
> Reviewed 1 of 1 files at r9, 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-15 08:30 UTC, merged