Update location cell
mullvad/mullvadvpn-app pull request #3828
Opened 2022-08-11 18:19 UTC by nchlscs

Small request that does 2 things:
1. Fixes an unexpected table view layout (see 1.mov below) while updating rows in case the cell is partially out of visible area. The current implementation relies on estimated heights to calculate table view geometry, reloading rows asks the data source for a new cell which causes the table view to recalculate heights. As documentation says, if reloading rows is unnecessary, it may be better to update cell directly. This PR introduces a closure block to update cells without reloading its row.

https://user-images.githubusercontent.com/50764345/184208736-3438d4f9-7dea-4018-a2d0-d51f417d5fd0.MOV

2. Adds table view scrolling to the expanded locations if they weren’t visible.

https://user-images.githubusercontent.com/50764345/184208794-d898b01d-38a5-497b-a4fa-ddebb3f4fb50.MOV

2022-08-12 13:41 UTC, pronebird commented
What version of iOS do you run? This seems to look alright on iOS 15.5.

https://user-images.githubusercontent.com/704044/184365829-a06a36f6-04bd-415e-a63c-8773c39d93c4.MP4

2022-08-12 14:05 UTC, pronebird requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3828)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @nchlscs)

___
*[`ios/MullvadVPN/LocationDataSource.swift` line 362 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3828#-N9HDP0GDRH-sDYILusU:-N9HDP0GDRH-sDYILusV:b-zfyrjt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/40ff473ccf1e046e7a8480b7530fed0ccb40ca00/ios/MullvadVPN/LocationDataSource.swift#L362)):*
> ```Swift
>                     at: lastInsertedIndexPath,
>                     at: .bottom,
>                     animated: true
> ```

We could reuse value of `animated` passed to parent function as an argument here?  Same applies to `if` branch.

```swift
private func toggleChildrenInternal(
        _ relayLocation: RelayLocation,
        show: Bool,
        showHiddenParents: Bool,
        animated: Bool, // <-- this one
        completion: (() -> Void)? = nil
    )
```
___
*[`ios/MullvadVPN/LocationDataSource.swift` line 368 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3828#-N9HBgVZB7oO56nPQso8:-N9HBgV_30dzGWhEdMw8:b-p3bkt2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/40ff473ccf1e046e7a8480b7530fed0ccb40ca00/ios/MullvadVPN/LocationDataSource.swift#L368)):*
> ```Swift
> 
>         if animated {
>             guard let changeSet = applyChanges() else { return }
> ```

Could you please add a call to `completion?()` in the else block before return. Perhaps we still want to notify the interested party that the call has finished. 
___
*[`ios/MullvadVPN/LocationDataSource.swift` line 372 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3828#-N9HMWzG7FX_j1CwG5yK:-N9HMWzG7FX_j1CwG5yL:b-dk01qm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/40ff473ccf1e046e7a8480b7530fed0ccb40ca00/ios/MullvadVPN/LocationDataSource.swift#L372)):*
> ```Swift
>                 tableView.insertRows(at: changeSet.insertIndexPaths, with: .fade)
>                 tableView.deleteRows(at: changeSet.deleteIndexPaths, with: .fade)
>                 changeSet.updateIndexPaths.forEach { indexPath in
> ```

Sadly `reconfigureRows` is only available since iOS 15. Either way. I think we could greatly benefit by updating cells directly and so I think you could break down cellProvider onto provider + configurator part. I had a little experiment based on your work, have a look:

https://github.com/mullvad/mullvadvpn-app/commit/ea802b2e8afbfe8cc80cc1d6f6adad24df2f1026


<!-- Sent from Reviewable.io -->

2022-08-12 15:07 UTC, pronebird commented
Hi, thanks for submitting this PR! I was able to reproduce this issue on my phone.

2022-08-12 16:02 UTC, pronebird reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3828)* status: all files reviewed, 3 unresolved discussions (waiting on @nchlscs)



<!-- Sent from Reviewable.io -->

2022-08-15 13:33 UTC, nchlscs commented
> I think you could break down cellProvider onto provider + configurator part. I had a little experiment based on your work, have a look: https://github.com/mullvad/mullvadvpn-app/commit/ea802b2e8afbfe8cc80cc1d6f6adad24df2f1026

Looks fine to me, I took it. I see, it also resolves all requested changes, thanks. And I guess, we can get rid of at least one force unwrapping given the cell provider returns non-optional cell now: https://github.com/mullvad/mullvadvpn-app/pull/3828/commits/375c457c75f14959f39b79394f1e51070b363f3c

2022-08-16 08:57 UTC, pronebird approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3828)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-08-16 09:00 UTC, pronebird commented
> > I think you could break down cellProvider onto provider + configurator part. I had a little experiment based on your work, have a look: [ea802b2](https://github.com/mullvad/mullvadvpn-app/commit/ea802b2e8afbfe8cc80cc1d6f6adad24df2f1026)
> 
> Looks fine to me, I took it. I see, it also resolves all requested changes, thanks. And I guess, we can get rid of at least one force unwrapping given the cell provider returns non-optional cell now: [375c457](https://github.com/mullvad/mullvadvpn-app/commit/375c457c75f14959f39b79394f1e51070b363f3c)

Makes sense. Merged via https://github.com/mullvad/mullvadvpn-app/commit/cfe03f2c74e3803ea3819ae5a1e6977bbdfc191e

2022-08-16 09:00 UTC, closed without merging