Improve android buildscripts
mullvad/mullvadvpn-app pull request #3864
Opened 2022-08-25 11:57 UTC by pinkisemils

I've changed two small things in the `build-apk.sh` script for developer (_my own_) quality of life. Firstly, the development builds won't strip debug symbols so that stack traces are actually legible. Secondly, I've changed the buildscript to use `CARGO_TARGET_DIR` to find the cargo target directory instead of assuming it will always be relative to the build script.

If you feel strongly about any of these changes, I'm open to not making them - but let's have a discussion about it then :)

2022-08-29 13:48 UTC, albin-mullvad requested changes
> Reviewed 2 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3864)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`build-apk.sh` line 124 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3864#-NAdp-AY5xuRDHrxJOGd:-NAdp-AY5xuRDHrxJOGe:b-qf9o2m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/64fe69bddf2054d12ca64558a14e185f4bb67728/build-apk.sh#L124)):*
> ```Shell
> 
>     STRIP_TOOL="${NDK_TOOLCHAIN_DIR}/${LLVM_TRIPLE}-strip"
>     STRIPPED_LIB_PATH="$SCRIPT_DIR/android/app/build/extraJni/$ABI/libmullvad_jni.so"
> ```

I suggest renaming `STRIPPED_LIB_PATH` to something like `ANDROID_LIB_PATH` or `TARGET_LIB_PATH`.

Also, a minor optional readability improvement could be to switch order of line `124` and `125`.



_Code quote:_
```Shell
STRIPPED_LIB_PATH
```


<!-- Sent from Reviewable.io -->

2022-08-31 15:13 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3864)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`build-apk.sh` line 124 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3864#-NAdp-AY5xuRDHrxJOGd:-NAoSbED4hmKqhzH_wCq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/64fe69bddf2054d12ca64558a14e185f4bb67728/build-apk.sh#L124)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest renaming `STRIPPED_LIB_PATH` to something like `ANDROID_LIB_PATH` or `TARGET_LIB_PATH`.

Also, a minor optional readability improvement could be to switch order of line `124` and `125`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-01 05:54 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3864#-:-NArbIVFAYWH2BKZS6L9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)



<!-- Sent from Reviewable.io -->

2022-09-01 05:54 UTC, albin-mullvad approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3864)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-01 12:57 UTC, merged