Port winnet to rust
mullvad/mullvadvpn-app pull request #3902
Opened 2022-09-06 07:56 UTC by Jontified

2022-09-14 12:13 UTC, dlon requested changes
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 3 of 5 files reviewed, 13 unresolved discussions (waiting on @Jontified)

___
*[`talpid-core/src/winnet_rs/mod.rs` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvq6d39B_hXh_OARvP:-NBvq6d39B_hXh_OARvQ:by8t1wr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L37)):*
> ```XML
> 
> pub struct WinNetDefaultRoute {
>     pub interface_luid: u64,
> ```

I think we should use `NET_LUID_LH` here.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvLSf3C0OLKw4DPv6F:-NBvLSf3C0OLKw4DPv6G:bf08ew9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L38)):*
> ```XML
> pub struct WinNetDefaultRoute {
>     pub interface_luid: u64,
>     pub gateway: WinNetIp,
> ```

This could be replaced with `IpAddr`. Are there any reasons not to do that?
___
*[`talpid-core/src/winnet_rs/mod.rs` line 48 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvLjiT6fjhlOfTP46s:-NBvLjiT6fjhlOfTP46t:b-tcba8s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L48)):*
> ```XML
> 
> 
> fn ip_from_native(from: &SOCKADDR_INET) -> Result<WinNetIp> {
> ```

Let's reuse `talpid_core::windows::try_socketaddr_from_inet_sockaddr`, which already implements this.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvNQN97ArKyT_4ZAvs:-NBvNQN97ArKyT_4ZAvt:b-94lvhc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L84)):*
> ```XML
> struct MibIpforwardTable2(*mut MIB_IPFORWARD_TABLE2);
> 
> impl MibIpforwardTable2 {
> ```

An alternative to this would be to simply copy all of the rows (`MIB_IPFORWARD_ROW2`) into a vector. See `talpid_core::windows::get_unicast_table` for an example.

A benefit of that approach is that it is a bit shorter and easier to use, perhaps. A downside is that it makes unnecessary copies. So I'm not sure which is preferable.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvNoeL9F31OZiolyCr:-NBvNoeL9F31OZiolyCs:b-p7mwsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L85)):*
> ```XML
> 
> impl MibIpforwardTable2 {
>     fn new(family: WinNetAddrFamily) -> Result<Self> {
> ```

I think it would make more sense to use `talpid_core::windows::AddressFamily` instead of `WinNetAddrFamily` here.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 93 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvMCWn2JTzqiaGdp-d:-NBvMCWn2JTzqiaGdp-e:b-ga2w84) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L93)):*
> ```XML
>         // SAFETY: GetIpForwardTable2 does not have clear safety specifications however what it does is
>         // heap allocate a IpForwardTable2 and then change table_ptr to point to that allocation.
>         unsafe { GetIpForwardTable2(u16::try_from(family.0).map_err(|_| Error::Conversion)?, &mut table_ptr).map_err(|_| Error::WindowsApi)? };
> ```

The result of `u16::try_from` could just be unwrapped here. All of the possible values are supposed to be valid.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 97 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvOqmL8NRz_xbuoiGw:-NBvOqmL8NRz_xbuoiGx:b-4h3wp2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L97)):*
> ```XML
>     }
> 
>     fn get_table_entry(&self, i: u32) -> &MIB_IPFORWARD_ROW2 {
> ```

I've mentioned this, but I think you could return `Option<&MIB_IPFORWARD_ROW2>` here instead.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvMmv95lI9rEsrqfNS:-NBvMmv95lI9rEsrqfNT:b6628gc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L101)):*
> ```XML
>         assert!(usize::try_from(i).unwrap() * std::mem::size_of::<MIB_IPFORWARD_ROW2>() < usize::try_from(isize::MAX).unwrap());
> 
>         // SAFETY: The slice will live as long as safe is not dropped. As such this pointer
> ```

Nit: `self`, not `safe`.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 171 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvfXn7BcietwqApcUI:-NBvfXn7BcietwqApcUJ:b-vdzpu8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L171)):*
> ```XML
>         }
>         //return lhs.active && false == rhs.active;
>         if lhs.active {
> ```

Nitpick: Would it not be more correct to prefer the active route, or else return `Equal`?

```
match (lhs.active, rhs.active) {
    (true, false) => Ordering::Less,
    (false, true) => Ordering::Greater,
    _ => Ordering::Equal,
}
```

I feel like it would be even more readable to [`filter`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.filter) on `active` first, though.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 191 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvhIwN7QasK6ASiYcO:-NBvhIwO7PSXujxyLmd_:b-lkbx30) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L191)):*
> ```XML
> 
> fn route_has_gateway(route: &MIB_IPFORWARD_ROW2) -> bool {
>     match ip_from_native(&route.NextHop) {
> ```

[`IpAddr::is_unspecified`](https://doc.rust-lang.org/std/net/enum.IpAddr.html#method.is_unspecified) could be used here if `WinNetIp` is replaced by `IpAddr`.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 205 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvlbt1DX-MXTRuB1tp:-NBvlbt1DX-MXTRuB1tq:b-rwnu2u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L205)):*
> ```XML
> 
> 
> fn is_route_on_physical_interface(route: &MIB_IPFORWARD_ROW2) -> Result<bool> {
> ```

Out of scope for this PR, probably: It would be more correct to simply filter out routes that match the known LUID of the tunnel interface.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 212 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvhbJYEIRk2TdUPOYD:-NBvhbJYEIRk2TdUPOYE:b-auwcc3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L212)):*
> ```XML
>     // and the other is a wrapped u64. Access to the _bitfield as such is safe since it does not reinterpret the 
>     // u64 as anything it is not.
>     let if_type = unsafe { route.InterfaceLuid.Info._bitfield } & 0xFFFF;
> ```

Nit: You could cast the result to a `u32`/`u16` instead of using `u64::from` below.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 232 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvjdFH8TGYEpNG-pJ5:-NBvjdFH8TGYEpNG-pJ6:b-6hcz3h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L232)):*
> ```XML
> 
>     let row_description =
>         U16CString::from_vec_truncate(row.Description)
> ```

You should be able to use [`U16CStr::from_slice_truncate`](https://docs.rs/widestring/latest/widestring/ucstr/struct.U16CStr.html#method.from_slice_truncate) here.

Is it possible to use [this](https://docs.rs/widestring/latest/widestring/ma [...]

2022-09-16 09:50 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 2 of 6 files reviewed, 17 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 108 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC4fqmU3-Aoh1mhJzSS:-NC4fqmU3-Aoh1mhJzST:bgapcf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L108)):*
> ```XML
> 
> // SAFETY: The value wrapped in ReadOnly is not allowed to be mutated until dropped.
> struct ReadOnly(Box<OuterContext>);
> ```

We must wrap the owner of the pointers we send to the windows API in something that prevents mutation.
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 123 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC4g1dz9ekIPSPaEHW_:-NC4g1e-1x3e1WK9PbIL:b-ckk04w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L123)):*
> ```XML
>     // SAFETY: Context must be dropped after all of the notifier handles have been dropped in order to guarantee none of them use its pointer.
>     // context is also wrapped in a ReadOnly struct in order to guarantee no mutation happens to it after pointers have been given to the notifier functions.
>     context: ReadOnly,
> ```

Potentially dangerous that it would be UB to drop `context` before any of the `Handle`s
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 154 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC4gFIQBIFW9jFLIuR0:-NC4gFIQBIFW9jFLIuR1:b-hfb2tu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L154)):*
> ```XML
> struct OuterContext {
>     context: Arc<Mutex<DefaultRouteMonitorContext>>,
>     burst_guard: Mutex<BurstGuard>,
> ```

We must wrap `BurstGuard` in a `Mutex` in order for it to be `Sync` and we need it to be `Sync` because we need to be able to send a pointer and cast it to a reference to the windows API.
The problem is that `BurstGuard` is not `Sync` due to it holding a `Sender` and there is no way for us to give ownership of a cloned `BurstGuard` to the windows API in a good way.
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 231 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC4h7A-5uovY8vvHoJn:-NC4h7A-5uovY8vvHoJo:b-it94t4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L231)):*
> ```XML
>     }
> 
>     let outer_context: &OuterContext = unsafe { &*(context as *const OuterContext) };
> ```

This access should be safe as long as we do not mutably modify the the original `Box<OuterContext>` nor drop that Box.


<!-- Sent from Reviewable.io -->

2022-09-16 14:50 UTC, dlon requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 2 of 6 files reviewed, 22 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 55 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC5X1cJ7XCgLDAPMyN6:-NC5X1cJ7XCgLDAPMyN7:b-c7ne3q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L55)):*
> ```XML
>     fn update_refresh_flag(&mut self, luid: &NET_LUID_LH, index: u32) {
>         match &self.best_route {
>             None => return,
> ```

`if let Some(best_route) = &self.best_route` is simpler, IMO.
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC5Ukbg30YGjJKizR5J:-NC5Ukbg30YGjJKizR5K:b-rcb0bc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L59)):*
> ```XML
>                 // SAFETY: luid is a union but both fields are finally represented by u64, as such any access is valid
>                 if unsafe { luid.Value } == best_route.interface_luid {
>                     self.refresh_current_route = true;
> ```

This is missing a `return`, no?
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 160 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC5JMmtAuJap66EkSaf:-NC5JMmtAuJap66EkSag:b-189fck) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L160)):*
> ```XML
>     fn new<F: Fn(EventType, &Option<WinNetDefaultRoute>) + Send + 'static>(family: WinNetAddrFamily, callback: F) -> Result<Self> {
>         let callback = Box::new(callback);
>         // FIXME: We reordered this from the c++ code so it calls get_best_default_route in the beginning before the
> ```

You should not do this. Suppose some event is sent before the listener has been registered.
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 164 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC5TanS95QW6kDrjmo-:-NC5TanS95QW6kDrjmo0:bq8gnc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L164)):*
> ```XML
>         let context = Arc::new(Mutex::new(DefaultRouteMonitorContext::new(callback, family)?));
> 
>         let moved_context = Arc::clone(&context);
> ```

Why not `context.clone()`?
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 194 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC5YnvwD3sqA9xiPPgr:-NC5Ynvx184597pT_FS4:b-a6gfb7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L194)):*
> ```XML
> 
>         // NotifyIpInterfaceChange
>         let context_ptr = &**outer_context as *const OuterContext;
> ```

You could reuse `context_ptr`.


<!-- Sent from Reviewable.io -->

2022-09-16 18:58 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 2 of 6 files reviewed, 25 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC6X8P4EDWvDsy6ObTF:-NC6X8P4EDWvDsy6ObTG:b-g8n5uq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L31)):*
> ```XML
> }
> 
> const BURST_DURATION: Duration = Duration::from_millis(200);
> ```

I know they're just copied from C++, but I think these names are too vague. At least there should be a couple of comments explaining the difference between `BURST_DURATION` and `BURST_INTERVAL`.
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 108 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC5mXgpCgHOibgMAHLE:-NC5mXgpCgHOibgMAHLF:biy2gta) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L108)):*
> ```XML
> 
> // SAFETY: The value wrapped in ReadOnly is not allowed to be mutated until dropped.
> struct ReadOnly(Box<OuterContext>);
> ```

This could be generalized to `ReadOnly<T: Deref>`.
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 123 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC6YxNU1NvIrPJ2C6qc:-NC6YxNU1NvIrPJ2C6qd:b-440iqq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L123)):*
> ```XML
>     // SAFETY: Context must be dropped after all of the notifier handles have been dropped in order to guarantee none of them use its pointer.
>     // context is also wrapped in a ReadOnly struct in order to guarantee no mutation happens to it after pointers have been given to the notifier functions.
>     context: ReadOnly,
> ```

How useful is `ReadOnly` really? Even if you fixed the visibility by moving `ReadOnly` to its own module, you could still drop `context` by assigning a new value to the field. After which the notify callbacks would be deref'ing garbage.

Personally, I think the box should just be left as is. Or you could turn it into a raw pointer using `Box::into_raw` and back to a box in `drop`.


<!-- Sent from Reviewable.io -->

2022-09-16 19:55 UTC, dlon requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 2 of 6 files reviewed, 27 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 274 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC6r9KJ1kP1o_Hy8nOv:-NC6r9KJ1kP1o_Hy8nOw:b3uhmkd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L274)):*
> ```XML
> 
> impl BurstGuard {
>     fn new<F: Fn() + Send + 'static>(callback: F, burst_duration: Duration, burst_interval: Duration) -> Self {
> ```

Since we only use this in this module, `BURST_DURATION` and `INTERFERENCE_INTERVAL` should be used directly, I think. I.e., don't pass them in as arguments.
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 283 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC6pW2YBS4uPeZOPbQS:-NC6pW2YBS4uPeZOPbQT:b4si67f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L283)):*
> ```XML
>                     match listener.recv_timeout(timeout) {
>                         Ok(()) => {
>                             match burst_interval.checked_sub(start.elapsed()) {
> ```

I would just simplify the `Ok(())` case to this:

```
if start.elapsed() >= INTERFERENCE_INTERVAL {
    callback();
    break;
}
```

It's consistent with the current behavior on master, I believe, and much easier to read.


<!-- Sent from Reviewable.io -->

2022-09-19 14:43 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 1 of 7 files reviewed, 19 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`talpid-core/src/winnet_rs/mod.rs` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvq6d39B_hXh_OARvP:-NC4mOdx4q04XepF0IXt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L37)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think we should use `NET_LUID_LH` here.
</blockquote></details>

Done.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 48 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvLjiT6fjhlOfTP46s:-NCKAglM9OLdAg3NgbfM:b-3z31p5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L48)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Let's reuse `talpid_core::windows::try_socketaddr_from_inet_sockaddr`, which already implements this.
</blockquote></details>

Sounds good, I've moved away from the `windows` crate over to the `windows_sys` crate because the types are not interoperable between them and all of the tooling is written for the latter.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvNQN97ArKyT_4ZAvs:-NCKBF8e5SO3gkWrJ21M:bf7s740) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L84)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

An alternative to this would be to simply copy all of the rows (`MIB_IPFORWARD_ROW2`) into a vector. See `talpid_core::windows::get_unicast_table` for an example.

A benefit of that approach is that it is a bit shorter and easier to use, perhaps. A downside is that it makes unnecessary copies. So I'm not sure which is preferable.
</blockquote></details>

You mean and avoid using `MIB_IPFORWARD_TABLE2` totally? If not to avoid using it we still need to destruct it properly. I don't really see the point of trying to avoid using it in order to avoid a wrapper. The wrapper seems like a pretty small piece of code that uses the API how it is intended and avoids cloning unnecessarily. You'd also still have to manage the destructing correctly since you need to create the table to clone it.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvNoeL9F31OZiolyCr:-NCKDeluEN3i6WMDg--D:bitloqj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L85)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think it would make more sense to use `talpid_core::windows::AddressFamily` instead of `WinNetAddrFamily` here.
</blockquote></details>

Sounds good, I removed `WinNetAddrFamily` and replaced all occurrences with `AddressFamily`
___
*[`talpid-core/src/winnet_rs/mod.rs` line 97 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvOqmL8NRz_xbuoiGw:-NCKFRsv9l11OQTI3vyW:b-jzadix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L97)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I've mentioned this, but I think you could return `Option<&MIB_IPFORWARD_ROW2>` here instead.
</blockquote></details>

Sounds fair, however I've left an `unwrap()` in the place we use this function in order to signal that a None in that case is a bug.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 171 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvfXn7BcietwqApcUI:-NCKIpjv9HxBd2OJBViD:bz1g62k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L171)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nitpick: Would it not be more correct to prefer the active route, or else return `Equal`?

```
match (lhs.active, rhs.active) {
    (true, false) => Ordering::Less,
    (false, true) => Ordering::Greater,
    _ => Ordering::Equal,
}
```

I feel like it would be even more readable to [`filter`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.filter) on `active` first, though.
</blockquote></details>

Removed the active field totally as discussed further down.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 205 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvlbt1DX-MXTRuB1tp:-NCKNQo47o984kcnu0uF:bs5gkds) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L205)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Out of scope for this PR, probably: It would be more correct to simply filter out routes that match the known LUID of the tunnel interface.
</blockquote></details>

Probably out of scope since we'd want to change as little logic as possible here. I added a comment for a future TODO.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 232 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvjdFH8TGYEpNG-pJ5:-NCKlrYgDVJQn25FZAvA:b-b22zg6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L232)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You should be able to use [`U16CStr::from_slice_truncate`](https://docs.rs/widestring/latest/widestring/ucstr/struct.U16CStr.html#method.from_slice_truncate) here.

Is it possible to use [this](https://docs.rs/widestring/latest/widestring/macro.u16cstr.html) macro to define the descriptions as well? If so, you don't need to convert the string to UTF-8 first.
</blockquote></details>

This requires that we upgrade to `widestring = 1.0`, which I think is fine. I've used the macro however the comparing the slices could not be done trivially, utilized the `windows()` iterator as we discussed.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 267 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvmVtID_xaKd8eNXhD:-NCKzyOu82YMBcPs3VQX:bz3dm8z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L267)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Why even return inactive routes at all? Maybe the field can be removed altogether.
</blockquote></details>

Removed the active field, any inactive route is not returned from the `annotated_routes()` function
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC5Ukbg30YGjJKizR5J:-NCL3V3T7H4EaqxCYoOo:bo06g33) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L59)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is missing a `return`, no?
</blockquote></details>

Yes it is, fixed.
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 164 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC5TanS95QW6kDrjmo-:-NCL7RhdBM_o3A2wmdNm:b4mo0uv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L164)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Why not `context.clone()`?
</blockquote></details>

I thought it looked clearer, but fixed.
___
*[`talpid-core/src/win [...]

2022-09-19 17:09 UTC, dlon reviewed
> Reviewed 2 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 3 of 7 files reviewed, 11 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`talpid-core/src/winnet_rs/mod.rs` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvNQN97ArKyT_4ZAvs:-NCLcbVl1q-FNvO59-Qz:bu6dyyb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L84)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

You mean and avoid using `MIB_IPFORWARD_TABLE2` totally? If not to avoid using it we still need to destruct it properly. I don't really see the point of trying to avoid using it in order to avoid a wrapper. The wrapper seems like a pretty small piece of code that uses the API how it is intended and avoids cloning unnecessarily. You'd also still have to manage the destructing correctly since you need to create the table to clone it.
</blockquote></details>

To your question: Yes. I mean just returning a vector: `fn get_forward_table() -> Vec<MIB_IPFORWARD_ROW2>`.

This would potentially simplify things a lot at the call site:

```
let annotated_routes = get_forward_table()
   .iter()
   .filter(|route| is_route_on_physical_interface(route) /* && ... */)
   .filter_map(annotate_route)
   .collect();
```

You could also achieve the same thing by implementing `Iterator` on `MibIpforwardTable2`. But I think you should go with whichever approach is simpler, not necessarily the most optimized solution.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 171 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvfXn7BcietwqApcUI:-NCLg4p-ERgRXTL80jIN:b-83sjoh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L171)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Removed the active field totally as discussed further down.
</blockquote></details>

Nice!
___
*[`talpid-core/src/winnet_rs/mod.rs` line 232 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvjdFH8TGYEpNG-pJ5:-NCLcFWpCtp5vioLbMok:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L232)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

This requires that we upgrade to `widestring = 1.0`, which I think is fine. I've used the macro however the comparing the slices could not be done trivially, utilized the `windows()` iterator as we discussed.
</blockquote></details>

:+1: 
___
*[`talpid-core/src/winnet_rs/mod.rs` line 267 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvmVtID_xaKd8eNXhD:-NCLcWjeAK9Q3WG2y9Da:b-83sjoh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L267)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Removed the active field, any inactive route is not returned from the `annotated_routes()` function
</blockquote></details>

Nice!
___
*[`talpid-core/src/winnet_rs/mod.rs` line 162 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NCLe-rwE0a4KO1jLpc2:-NCLe-rwE0a4KO1jLpc3:b7dfnc6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f6b41c7e07f9f28238d63706bfafa258935e2b/talpid-core/src/winnet_rs/mod.rs#L162)):*
> ```XML
> 	}
> 
> 	let mut annotated = annotated_routes(&candidates);
> ```

See my other suggestion about `MibIpforwardTable2`. If you either implement `Iterator` or return a vec, you should be able to simplify the above:

```
let annotated_routes = get_forward_table()
   .iter()
   .filter(|route| route.DestinationPrefix.PrefixLength == 0 && route_has_gateway(route) && is_route_on_physical_interface(route))
   .filter_map(annotate_route)
   .collect();
```
___
*[`talpid-core/src/winnet_rs/mod.rs` line 223 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NCLbghx05Vu58acwA-q:-NCLbghx05Vu58acwA-r:b-25m4r4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f6b41c7e07f9f28238d63706bfafa258935e2b/talpid-core/src/winnet_rs/mod.rs#L223)):*
> ```XML
>     for tunnel_interface_desc in TUNNEL_INTERFACE_DESCS {
>         // There is no slice equivalent of `String::contains` so we will have to make due with `windows()`
>         if row_description.as_slice().windows(tunnel_interface_desc.as_slice().len())
> ```

Nit: Do you think that this would benefit from being moved to its own function, e.g. `contains_subslice<T>(slice: &[T], subslice: &[T]) -> bool`? That should make it self-documenting.
___
*[`talpid-core/src/winnet_rs/mod.rs` line 238 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NCLgwOKAKqNS09nR5ha:-NCLgwOKAKqNS09nR5hb:bhasoqq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f6b41c7e07f9f28238d63706bfafa258935e2b/talpid-core/src/winnet_rs/mod.rs#L238)):*
> ```XML
> }
> 
> fn annotated_routes<'a>(routes: &'_ Vec<&'a MIB_IPFORWARD_ROW2>) -> Vec<AnnotatedRoute<'a>> {
> ```

See my other comments: Should this maybe "annotate" a single route instead, and return `Option<AnnotatedRoute<'a>>`?

That way, you'd be able to use it directly on an iterator: `routes.iter().filter_map(annotate_route)`
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 274 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC6r9KJ1kP1o_Hy8nOv:-NCLgGCn4GLxf6_cmkib:bofyxby) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L274)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sweet. The comments are helpful.


<!-- Sent from Reviewable.io -->

2022-09-19 17:29 UTC, dlon requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 3 of 7 files reviewed, 12 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`talpid-core/src/winnet_rs/mod.rs` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NBvNQN97ArKyT_4ZAvs:-NCLjge2Cp40FsUdDeof:b-1xutt5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6691d2b29e87112515a29c94252c762df75d3e48/talpid-core/src/winnet_rs/mod.rs#L84)):*
> by implementing Iterator on MibIpforwardTable2

Correction: Implementing an iterator for.
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 190 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NCLlDdN2mptR2CJhGgL:-NCLlDdN2mptR2CJhGgM:b-l1fqt1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f6b41c7e07f9f28238d63706bfafa258935e2b/talpid-core/src/winnet_rs/route_manager.rs#L190)):*
> ```XML
>         }
>         // SAFETY: NotifyRouteChange2 is guaranteed not to be an error here so handle_ptr is guaranteed to be non-null so dereferencing is safe
>         let notify_route_change_handle = Handle(unsafe { *handle_ptr });
> ```

This looks incorrect. You'll want to pass `&mut handle_ptr` to `NotifyRouteChange2` above. `NotifyRouteChange2` will set the address that `handle_ptr` points to. There's no need to dereference it.

The same applies to the notify functions below.


<!-- Sent from Reviewable.io -->

2022-09-19 20:36 UTC, dlon requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 3 of 7 files reviewed, 13 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`talpid-core/src/winnet_rs/mod.rs` line 251 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NCMSIJ-3UwIdo9vAqFk:-NCMSIJ-3UwIdo9vAqFl:b-79pifs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f6b41c7e07f9f28238d63706bfafa258935e2b/talpid-core/src/winnet_rs/mod.rs#L251)):*
> ```XML
>         // or iface.InterfaceIndex and use that information to populate the struct. We guarantee here that this struct and these
>         // fields are valid since they are initliazed through default.
>         let res = unsafe { GetIpInterfaceEntry(&mut iface as *mut MIB_IPINTERFACE_ROW) };
> ```

Could we use `talpid_core::windows::get_ip_interface_entry` here?


<!-- Sent from Reviewable.io -->

2022-09-20 12:45 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 3 of 7 files reviewed, 13 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`talpid-core/src/winnet.rs` line 350 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NCPuhdH1p1sb2gseVoV:-NCPuhdH1p1sb2gseVoW:b-u6ewn7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f6b41c7e07f9f28238d63706bfafa258935e2b/talpid-core/src/winnet.rs#L350)):*
> ```XML
>                     ip_bytes[1] = octets[1];
>                     ip_bytes[2] = octets[2];
>                     ip_bytes[3] = octets[3];
> ```

Nitpicky. But I'd say there are more idiomatic ways to copy these four bytes over. First of all, you can destructure the `octets` without indexing with `let [a, b, c, d] = addr.ip.octets()`. Secondly it can be one statement with `ip_bytes[0..4].copy_from_slice(&addr.ip.octets())`


<!-- Sent from Reviewable.io -->

2022-09-20 13:41 UTC, dlon reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 3 of 7 files reviewed, 13 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`talpid-core/src/winnet.rs` line 350 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NCPuhdH1p1sb2gseVoV:-NCQ33bN7eJH2bm_vb2q:b-6kz8o9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f6b41c7e07f9f28238d63706bfafa258935e2b/talpid-core/src/winnet.rs#L350)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nitpicky. But I'd say there are more idiomatic ways to copy these four bytes over. First of all, you can destructure the `octets` without indexing with `let [a, b, c, d] = addr.ip.octets()`. Secondly it can be one statement with `ip_bytes[0..4].copy_from_slice(&addr.ip.octets())`
</blockquote></details>

I think we could also get rid of this wrapper function completely. As well as `WinNetDefaultRoute`. But it doesn't necessarily have to be done in this PR.


<!-- Sent from Reviewable.io -->

2022-09-20 15:48 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 3 of 7 files reviewed, 9 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/winnet.rs` line 350 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NCPuhdH1p1sb2gseVoV:-NCQ8phS8Q1tm6_wpp4M:b-3e77c2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f6b41c7e07f9f28238d63706bfafa258935e2b/talpid-core/src/winnet.rs#L350)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think we could also get rid of this wrapper function completely. As well as `WinNetDefaultRoute`. But it doesn't necessarily have to be done in this PR.
</blockquote></details>

This is glue code that I'm using just for testing so I can avoid changing anything outside of the actual port. This will be cleaned up after I've tested everything. However good suggestion, I changed it anyway because why not?
___
*[`talpid-core/src/winnet_rs/mod.rs` line 251 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NCMSIJ-3UwIdo9vAqFk:-NCPhy2W2Cgdpk11mrKG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f6b41c7e07f9f28238d63706bfafa258935e2b/talpid-core/src/winnet_rs/mod.rs#L251)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could we use `talpid_core::windows::get_ip_interface_entry` here?
</blockquote></details>

Done.
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 108 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC5mXgpCgHOibgMAHLE:-NCPvAPq0XH62V-kKP3R:bqj86f8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L108)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This could be generalized to `ReadOnly<T: Deref>`.
</blockquote></details>

After much discussion with you I've removed `ReadOnly`
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 123 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC6YxNU1NvIrPJ2C6qc:-NCPvGEqDUpWaC3oQah9:b-7gybu1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L123)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

How useful is `ReadOnly` really? Even if you fixed the visibility by moving `ReadOnly` to its own module, you could still drop `context` by assigning a new value to the field. After which the notify callbacks would be deref'ing garbage.

Personally, I think the box should just be left as is. Or you could turn it into a raw pointer using `Box::into_raw` and back to a box in `drop`.
</blockquote></details>

After discussion with you I've decided on storing a `Box::into_raw()` pointer as well as a `Option<(Handle, Handle, Handle)>` to safely drop the handles before the context.
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 160 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NC5JMmtAuJap66EkSaf:-NCQ8K3d-Ln5Enh0MOhd:b-fz84h3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e46cbad1a139e46e90007acbd5bb65d7617bdf11/talpid-core/src/winnet_rs/route_manager.rs#L160)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You should not do this. Suppose some event is sent before the listener has been registered.
</blockquote></details>

I set the default value to `None` and moved the call to `get_best_default_route` to the bottom were all listeners have been registered.
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 190 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NCLlDdN2mptR2CJhGgL:-NCPzpC-BJtWVnZKRiMW:bpnaljv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f6b41c7e07f9f28238d63706bfafa258935e2b/talpid-core/src/winnet_rs/route_manager.rs#L190)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This looks incorrect. You'll want to pass `&mut handle_ptr` to `NotifyRouteChange2` above. `NotifyRouteChange2` will set the address that `handle_ptr` points to. There's no need to dereference it.

The same applies to the notify functions below.
</blockquote></details>

Alright, this forces us to dereference the pointer later when we want to cancel the notification. I've made this change but out of curiosity does it matter?


<!-- Sent from Reviewable.io -->

2022-09-23 14:01 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @Jontified)

___
*[`talpid-core/src/winnet.rs` line 350 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NCPuhdH1p1sb2gseVoV:-NCed2apD1iDHCD8Pali:b-55ne3j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f6b41c7e07f9f28238d63706bfafa258935e2b/talpid-core/src/winnet.rs#L350)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

This is glue code that I'm using just for testing so I can avoid changing anything outside of the actual port. This will be cleaned up after I've tested everything. However good suggestion, I changed it anyway because why not?
</blockquote></details>

If possible I think we should remove/improve as much as possible in the same PR. I usually want feature PRs to be focused and not do too much stuff. But this PR is nothing but a cleanup PR. So I'd say it's very much in scope to do as much cleanup as possible that is actually related to `winnet`.
___
*[`talpid-core/src/winnet.rs` line 1 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NCedNsI364XDTCAGz7z:-NCedNsI364XDTCAGz8-:b1rpjke) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8178e5967086cc5851fe2aac4d321a73546728cf/talpid-core/src/winnet.rs#L1)):*
> ```XML
> use self::api::*;
> ```

This comment is about the file in general, not this line. This module does no longer stringly need to be named `winnet`. Because it's no longer a wrapper around an external library. We could now, with the new Rust impls, have dedicated modules doing the different tasks that `winnet` previously did. There is no reason really to have a kitchensink-windows-networking-module.

I'm not sure what good ways of splitting it up that exists, just noting that this unlocks that potential.


<!-- Sent from Reviewable.io -->

2022-09-27 12:37 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @faern and @Jontified)

___
*[`talpid-core/src/winnet.rs` line 1 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NCedNsI364XDTCAGz7z:-NCeoK2m5QZFav7uGnAQ:b-l7p1dp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8178e5967086cc5851fe2aac4d321a73546728cf/talpid-core/src/winnet.rs#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This comment is about the file in general, not this line. This module does no longer stringly need to be named `winnet`. Because it's no longer a wrapper around an external library. We could now, with the new Rust impls, have dedicated modules doing the different tasks that `winnet` previously did. There is no reason really to have a kitchensink-windows-networking-module.

I'm not sure what good ways of splitting it up that exists, just noting that this unlocks that potential.
</blockquote></details>

It should be trivial to move some parts, like the route monitor itself, into `talpid_core::routing::windows`, and possibly some more generic things to `talpid_core::windows` (though that module is might also be becoming a kitchensink).


<!-- Sent from Reviewable.io -->

2022-10-04 08:17 UTC, dlon requested changes
> Reviewed 9 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 13 of 18 files reviewed, 4 unresolved discussions (waiting on @dlon, @faern, and @Jontified)

___
*[`talpid-core/src/winnet.rs` line 81 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDX-ZsLAZKesPseFuOw:-NDX-ZsLAZKesPseFuOx:b-7pgb6i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ac67ba7af9a552577de03e91905aadfad6a9f4b/talpid-core/src/winnet.rs#L81)):*
> ```XML
> pub struct WinNetDefaultRoute {
>     pub interface_luid: u64,
>     pub gateway: WinNetIp,
> ```

I've probably suggested this already, but I see no need for `WinNetIp` here. Just use `IpAddr` instead.
___
*[`talpid-core/src/tunnel/wireguard/wireguard_go.rs` line 211 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDX2r-H6ScivuiSqWyn:-NDX2r-H6ScivuiSqWyo:buqmqme) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ac67ba7af9a552577de03e91905aadfad6a9f4b/talpid-core/src/tunnel/wireguard/wireguard_go.rs#L211)):*
> ```XML
>         event_type: crate::winnet_rs::EventType,
>         address_family: crate::windows::AddressFamily,
>         default_route: &Option<crate::winnet_rs::InterfaceAndGateway>,
> ```

I think that the route could be part of the enum variant instead of being optional:
```rust
enum RouteEvent {
    Removed,
    Updated(InterfaceAndGateway),
    ...
}
```


<!-- Sent from Reviewable.io -->

2022-10-06 00:02 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 5 of 23 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/tunnel/wireguard/wireguard_go.rs` line 211 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDX2r-H6ScivuiSqWyn:-NDeYlaf6l5jmJP7oIsN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ac67ba7af9a552577de03e91905aadfad6a9f4b/talpid-core/src/tunnel/wireguard/wireguard_go.rs#L211)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think that the route could be part of the enum variant instead of being optional:
```rust
enum RouteEvent {
    Removed,
    Updated(InterfaceAndGateway),
    ...
}
```
</blockquote></details>

Done.
___
*[`talpid-core/src/winnet_rs/route_manager.rs` line 190 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NCLlDdN2mptR2CJhGgL:-NDeaVHCD9pxnPqdPC_8:b-teoq0f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c9f6b41c7e07f9f28238d63706bfafa258935e2b/talpid-core/src/winnet_rs/route_manager.rs#L190)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Right now, the last argument that is passed to the notify functions is still `NULL`.

What `NotifyRouteChange2` wants to do is this:

```
int NotifyRouteChange2(/*...*/ void *handle_ptr) {
    // ...
    if (handle_ptr)
        *handle_ptr = something;
}
```

This won't work when `handle_ptr` is `NULL`. So you need to pass `&mut handle` to that function.

Your `Handle` type should contain a `HANDLE`, not a pointer to a `HANDLE`.
</blockquote></details>

This should be fixed now.


<!-- Sent from Reviewable.io -->

2022-10-07 12:08 UTC, dlon requested changes
> Reviewed 18 of 18 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: all files reviewed, 26 unresolved discussions (waiting on @Jontified)

___
*[`talpid-core/src/offline/windows.rs` line 112 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDl_O5A1I8FtqDvhVJU:-NDl_O5BCT9fXwDN9Zsl:b-4qspey) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/offline/windows.rs#L112)):*
> ```XML
>     /// The caller must make sure the `system_state` reference is valid
>     /// until after `WinNet_DeactivateConnectivityMonitor` has been called.
>     async unsafe fn setup_network_connectivity_listener(
> ```

I see no reason for this to be `unsafe` anymore.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 43 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDlbqqs3XB2e9FFi00V:-NDlbqqt55wKhoN8zU8k:b-apqqc4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L43)):*
> ```XML
> }
> 
> impl std::ops::Drop for CallbackHandle {
> ```

`std::ops::` should be removed. `Drop` is in the prelude.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 161 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDlnKoC9Q7VppsSLlFH:-NDlnKoC9Q7VppsSLlFI:b-bxegzm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L161)):*
> ```XML
>                         //}
>                         _ => {
>                             // TODO: Look up why this is important to split these?
> ```

On master, it's for `WinNet_AddRoutes`to return all of these codes:

```
pub fn routing_manager_add_routes(routes: &[WinNetRoute]) -> Result<(), Error> {
    let ptr = routes.as_ptr();
    let length: u32 = routes.len() as u32;
    match unsafe { WinNet_AddRoutes(ptr, length) } {
        WinNetAddRouteStatus::Success => Ok(()),
        WinNetAddRouteStatus::GeneralError => Err(Error::GeneralAddRoutesError),
        WinNetAddRouteStatus::NoDefaultRoute => Err(Error::GetDefaultRoute),
        WinNetAddRouteStatus::NameNotFound => Err(Error::GetDeviceByName),
        WinNetAddRouteStatus::GatewayNotFound => Err(Error::GetDeviceByGateway),
    }
}
```

All of these except `GeneralAddRoutesError` are treated as "recoverable" errors by the connecting state (in `is_recoverable_routing_error`) . However, it's possible that we should just treat all errors here as recoverable.

If possible, I think we should just simplify this to

```
Self::add_into_routing_table(&route).map_err(|error| {
    Self::undo_events(...);
    error
});
```
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 262 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDm8mcN32E2kZcLNrJP:-NDm8mcN32E2kZcLNrJQ:buoua1z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L262)):*
> ```XML
>                         .expect("Failed to convert UTF-8 string to null terminated UCS string");
>                     // TODO: Make sure this is right
>                     let luid = match Self::parse_string_encoded_luid(device_name.as_ucstr())? {
> ```

This looks correct to me. I'm not sure that we even need to try parse the LUID strings, but let's keep it for now.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 262 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDmAy7rEy8_9XaAMftG:-NDmAy7s2h0R8tJXzi-3:b-22907w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L262)):*
> ```XML
>                         .expect("Failed to convert UTF-8 string to null terminated UCS string");
>                     // TODO: Make sure this is right
>                     let luid = match Self::parse_string_encoded_luid(device_name.as_ucstr())? {
> ```

Would it be possible to simplify this using `unwrap_or_else`?

```
Self::parse_string_encoded_luid(device_name.as_ucstr())?
    .unwrap_or_else(|| {
        let mut luid = NET_LUID_LH { Value: 0 };
        if NO_ERROR as i32 == unsafe { ConvertInterfaceAliasToLuid(device_name.as_ptr(), &mut luid) } {
            Ok(luid)
        } else {
            log::error!(
                "Unable to derive interface LUID from interface alias: {:?}",
                device_name
            );
            Err(Error::DeviceNameNotFound)
        }
    })?;
```
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 289 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDlpQsU-S3aLebB0x5H:-NDlpQsU-S3aLebB0x5I:b-gs6tc1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L289)):*
> ```XML
>                             None => match family {
>                                 AddressFamily::Ipv4 => {
>                                     SocketAddr::new(IpAddr::V4(Ipv4Addr::new(0, 0, 0, 0)), 0)
> ```

You could use `Ipv4Addr::UNSPECIFIED` here.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 292 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDlp_-bDk1BDd-mTfLf:-NDlp_-bDk1BDd-mTfLg:b-egidbz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L292)):*
> ```XML
>                                 }
>                                 AddressFamily::Ipv6 => SocketAddr::new(
>                                     IpAddr::V6(Ipv6Addr::new(0, 0, 0, 0, 0, 0, 0, 0)),
> ```

You could use `Ipv6Addr::UNSPECIFIED` here.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 337 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDlqFC59HKqq1twWUMI:-NDlqFC59HKqq1twWUMJ:b-mp64ep) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L337)):*
> ```XML
>                         None => {
>                             log::error!("Internal state inconsistency in route manager");
>                             // TODO: Panic here, or not?
> ```

Calling `expect` for the result does make sense if this is unreachable.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 344 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDmCHyD3jaYW6638sUK:-NDmCHyD3jaYW6638sUL:boyekb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L344)):*
> ```XML
>                         Some(record_idx) => {
>                             // TODO: make sure this is right
>                             let record = match records.get(record_idx) {
> ```

Same here: We should probably unwrap this?
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 354 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDmCP5m9UJYMWGiy-0Z:-NDmCP5m9UJYMWGiy-0_:b-8qt8xk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L354)):*
> ```XML
>                                 Some(rec) => rec,
>                             };
>                             match Self::delete_from_routing_table(&record.registered_route) {
> ```

This could be simplified to `if let Some(error) = ...`.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 369 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDmCYCo7923kM0hLmxB:-NDmCYCo7923kM0hLmxC:b-8qt8xk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/ [...]

2022-10-07 12:12 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: all files reviewed, 26 unresolved discussions (waiting on @Jontified)

___
*[`talpid-core/src/routing/windows/route_manager.rs` line 262 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDmAy7rEy8_9XaAMftG:-NDmLw1FEfiDGJXiqMsB:bhcjkyn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L262)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Would it be possible to simplify this using `unwrap_or_else`?

```
Self::parse_string_encoded_luid(device_name.as_ucstr())?
    .unwrap_or_else(|| {
        let mut luid = NET_LUID_LH { Value: 0 };
        if NO_ERROR as i32 == unsafe { ConvertInterfaceAliasToLuid(device_name.as_ptr(), &mut luid) } {
            Ok(luid)
        } else {
            log::error!(
                "Unable to derive interface LUID from interface alias: {:?}",
                device_name
            );
            Err(Error::DeviceNameNotFound)
        }
    })?;
```
</blockquote></details>

Not exactly what I said above. You'd need to turn the option into a result first.


<!-- Sent from Reviewable.io -->

2022-10-10 18:35 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: all files reviewed, 18 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/offline/windows.rs` line 112 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDl_O5A1I8FtqDvhVJU:-NE-iH9UBrpfBIPH_OKK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/offline/windows.rs#L112)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I see no reason for this to be `unsafe` anymore.
</blockquote></details>

Done.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 43 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDlbqqs3XB2e9FFi00V:-NE-isx46neJJBGRXGiS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L43)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`std::ops::` should be removed. `Drop` is in the prelude.
</blockquote></details>

Done.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 161 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDlnKoC9Q7VppsSLlFH:-NE22caDCbcYUxu-DfLX:bmrkwa8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L161)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

On master, it's for `WinNet_AddRoutes`to return all of these codes:

```
pub fn routing_manager_add_routes(routes: &[WinNetRoute]) -> Result<(), Error> {
    let ptr = routes.as_ptr();
    let length: u32 = routes.len() as u32;
    match unsafe { WinNet_AddRoutes(ptr, length) } {
        WinNetAddRouteStatus::Success => Ok(()),
        WinNetAddRouteStatus::GeneralError => Err(Error::GeneralAddRoutesError),
        WinNetAddRouteStatus::NoDefaultRoute => Err(Error::GetDefaultRoute),
        WinNetAddRouteStatus::NameNotFound => Err(Error::GetDeviceByName),
        WinNetAddRouteStatus::GatewayNotFound => Err(Error::GetDeviceByGateway),
    }
}
```

All of these except `GeneralAddRoutesError` are treated as "recoverable" errors by the connecting state (in `is_recoverable_routing_error`) . However, it's possible that we should just treat all errors here as recoverable.

If possible, I think we should just simplify this to

```
Self::add_into_routing_table(&route).map_err(|error| {
    Self::undo_events(...);
    error
});
```
</blockquote></details>

Done, I've reworked the Error type a bit to handle both the low-level windows API errors and the high-level route manager errors. There is now a wrapping error for all errors returned when trying to add a route, this wrapping is done in the RouteManager so it should be on the same abstraction layer as previously.
I've put the high-level variants and the low-level variants in the same `Error` type in order to avoid having two `Error` types which seemed needlessly complex.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 262 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDm8mcN32E2kZcLNrJP:-NE-ivMV3gINqtA2Byqe:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L262)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This looks correct to me. I'm not sure that we even need to try parse the LUID strings, but let's keep it for now.
</blockquote></details>

Done.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 262 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDmAy7rEy8_9XaAMftG:-NE25pM14qmC-h8lY1g_:bcjog73) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L262)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Not exactly what I said above. You'd need to turn the option into a result first.
</blockquote></details>

I think doing it the functional way in this case becomes more complicated and harder to read since the `None` case might sometimes return `Ok` and sometimes `Err` you need to create an intermediate `Result` type but then you can not just map it's error to the block since the block does not always return an error. Unless you disagree I'll leave this as is.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 289 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDlpQsU-S3aLebB0x5H:-NE-j6Ii7tLsLjEmgQ51:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L289)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You could use `Ipv4Addr::UNSPECIFIED` here.
</blockquote></details>

Done.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 292 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDlp_-bDk1BDd-mTfLf:-NE-j6Zl1BZ-EM2B9QTK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L292)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You could use `Ipv6Addr::UNSPECIFIED` here.
</blockquote></details>

Done.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 337 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDlqFC59HKqq1twWUMI:-NE0ZaGSB5b82RZsQ9LC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L337)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Calling `expect` for the result does make sense if this is unreachable.
</blockquote></details>

Done.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 344 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDmCHyD3jaYW6638sUK:-NE0Zh6C2kR6ojKLaKOi:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L344)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Same here: We should probably unwrap this?
</blockquote></details>

Done.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 405 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDm54Rc1L0Xh8qnxIxd:-NE26FSW0ZtP6syjt_3I:b-dfddp9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L405)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could this return a specific error with the underlying `io::Error` as the source? A generic `WindowsApi` error, especially without any source, is not very helpful.

This is probably a good idea in general, not just here.
</blockquote></details>

I've removed the `WindowsApi` error and replaced it with a variety of variants that all wrap an `io::Error`
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 586 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDlbwC56zsrqcvpF2ED:-NE-lNMD8ePQLZ7JvS6j:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L586)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`std::ops::` should be removed. `Drop` is in the prelude.
</blockquote></details>

Done.
___
*[`talpid-core/src/tunnel_state_machine/connec [...]

2022-10-13 12:31 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: all files reviewed, 14 unresolved discussions (waiting on @Jontified)

___
*[`talpid-core/src/routing/windows/route_manager.rs` line 676 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NEAMq-70a9Sgiy60SV9:-NEGJk1GD2AyGWGlI6hw:b-xmyg5a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6172c35e5f278ec9cac126d4872dba0cb8ca86f9/talpid-core/src/routing/windows/route_manager.rs#L676)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

If we're going to panic here, we should make the function infallible. And panic due to "invalid address family" or something like that.
</blockquote></details>

But I retract the earlier suggestion -- this is not technically unreachable. Just return `Err(Error::InvalidSiFamily)` here, IMO.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 659 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NEGHJju4NE4wdWVMLPR:-NEGHJju4NE4wdWVMLPS:b-kk4mhs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14e9f6a9707a62fa2ae7c692d7309cef86840980/talpid-core/src/routing/windows/route_manager.rs#L659)):*
> ```XML
> /// All pointers returned by this function are valid to dereference assuming above criteria are met.
> unsafe fn isolate_gateway_address(
>     head: *mut IP_ADAPTER_GATEWAY_ADDRESS_LH,
> ```

This could be a const pointer, or a reference even. Using references here should let us specify lifetimes nicely, but I'm not sure how complicated it would be.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 680 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NEGHTkE9_rvoJCz2_aH:-NEGHTkE9_rvoJCz2_aI:bx1ed1k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14e9f6a9707a62fa2ae7c692d7309cef86840980/talpid-core/src/routing/windows/route_manager.rs#L680)):*
> ```XML
>     }
> 
>     return matches;
> ```

`matches`


<!-- Sent from Reviewable.io -->

2022-10-16 10:49 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: 18 of 24 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/routing/windows/route_manager.rs` line 161 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NDlnKoC9Q7VppsSLlFH:-NELH9ul0vkbvprD-W5l:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de92567842b187dd121cd63cde653ac1f736338b/talpid-core/src/routing/windows/route_manager.rs#L161)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Looks good to me! We're not using any of these variants yet, are we? They simply exist. As suggested before, maybe we should remove the variants and just retry whenever `AddRoutesFailed` is returned in `connecting_state::is_recoverable_routing_error`.
</blockquote></details>

Done.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 153 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NEAIJH69O3Ftr8CLYPV:-NELFeTfAPv0jCw4o1JZ:b-3iq0f8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6172c35e5f278ec9cac126d4872dba0cb8ca86f9/talpid-core/src/routing/windows/route_manager.rs#L153)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: You could use `Result::and` here.
</blockquote></details>

`Result::and` returns a `Result<_, Error>` but we want to return an `Error`
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 659 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NEGHJju4NE4wdWVMLPR:-NELn_wQ45nQguN1Tva0:btupk3s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14e9f6a9707a62fa2ae7c692d7309cef86840980/talpid-core/src/routing/windows/route_manager.rs#L659)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This could be a const pointer, or a reference even. Using references here should let us specify lifetimes nicely, but I'm not sure how complicated it would be.
</blockquote></details>

I changed it to use references instead of `*const`. I think it made it more understandable.
___
*[`talpid-core/src/routing/windows/route_manager.rs` line 778 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NEG1bnL2yjnsrTj8IJk:-NEVMza0030m7LYZvgq9:bv8iccl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14e9f6a9707a62fa2ae7c692d7309cef86840980/talpid-core/src/routing/windows/route_manager.rs#L778)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I believe `buffer_size` specifies the buffer size in bytes. It's being interpreted as the number of elements here. In the original code, we use a byte buffer (`Vec<u8>`) and later reinterpret it. We should do that here as well.
</blockquote></details>

Done. Now uses a Vec<u8> and casts when needed.


<!-- Sent from Reviewable.io -->

2022-10-17 08:07 UTC, dlon approved these changes
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`talpid-core/src/routing/windows/route_manager.rs` line 153 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NEAIJH69O3Ftr8CLYPV:-NEZvPbADPBMyolIFnYM:bonj806) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6172c35e5f278ec9cac126d4872dba0cb8ca86f9/talpid-core/src/routing/windows/route_manager.rs#L153)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

`Result::and` returns a `Result<_, Error>` but we want to return an `Error`
</blockquote></details>


```rust
add_into_routing_table(..).or_else(|result| Self::undo_events(&event_log, &mut route_manager_routes).and(result))
```

is what I probably had in mind. Anyway, not important.


<!-- Sent from Reviewable.io -->

2022-10-17 11:04 UTC, dlon approved these changes
> Reviewed 4 of 6 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-17 11:47 UTC, faern reviewed
> Reviewed 1 of 17 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-17 11:50 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: all files reviewed, 1 unresolved discussion (waiting on @Jontified)

___
*[`talpid-core/Cargo.toml` line 90 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NE_lnWr5i_6bpaCQJjd:-NE_lnWr5i_6bpaCQJje:b-plt82f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d36f5884d4bc046a55e41621726b9b7d7f5dae68/talpid-core/Cargo.toml#L90)):*
> ```TOML
> 
> [target.'cfg(windows)'.dependencies.windows]
> version = "0.36.1"
> ```

The latest is already up to 0.42.0. Is there any reason not to upgrade? I'm not sure how much (if any) code changes would be needed.


<!-- Sent from Reviewable.io -->

2022-10-17 11:53 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: all files reviewed, 2 unresolved discussions (waiting on @Jontified)

___
*[`talpid-core/src/routing/windows/default_route_monitor.rs` line 27 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NE_mRZW6VhT72DkxDRp:-NE_mRZW6VhT72DkxDRq:bgtdgyl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d36f5884d4bc046a55e41621726b9b7d7f5dae68/talpid-core/src/routing/windows/default_route_monitor.rs#L27)):*
> ```XML
> };
> 
> const WIN_FALSE: BOOLEAN = 0;
> ```

Looks like `BOOLEAN` implements `From<bool>`, so could we use `BOOLEAN::from(false)` instead of `0` for the value?


<!-- Sent from Reviewable.io -->

2022-10-17 11:54 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: all files reviewed, 2 unresolved discussions (waiting on @Jontified)

___
*[`talpid-core/src/routing/windows/default_route_monitor.rs` line 27 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NE_mRZW6VhT72DkxDRp:-NE_mkH50icJu-G6efY2:bwv3pi1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d36f5884d4bc046a55e41621726b9b7d7f5dae68/talpid-core/src/routing/windows/default_route_monitor.rs#L27)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Looks like `BOOLEAN` implements `From<bool>`, so could we use `BOOLEAN::from(false)` instead of `0` for the value?
</blockquote></details>

Oh no, we can't. Because `From` is not `const` (yet). That sucks. Is this really not defined anywhere? :scream: 


<!-- Sent from Reviewable.io -->

2022-10-18 08:52 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`talpid-core/Cargo.toml` line 90 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902#-NE_lnWr5i_6bpaCQJjd:-NEeHrdABzX-MEeqKeAX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d36f5884d4bc046a55e41621726b9b7d7f5dae68/talpid-core/Cargo.toml#L90)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The latest is already up to 0.42.0. Is there any reason not to upgrade? I'm not sure how much (if any) code changes would be needed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-18 09:18 UTC, dlon approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3902)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2022-10-18 13:09 UTC, merged