Use awk instead of sed to replace toml versions
mullvad/mullvadvpn-app pull request #3910
Opened 2022-09-07 14:43 UTC by dlon

The [previous change](https://github.com/mullvad/mullvadvpn-app/pull/3874) to this script used a GNU extension to replace the versions. So injecting the version failed on macOS.

2022-09-08 12:06 UTC, faern reviewed
The best would be if there was a cleaner way to edit toml files from scripts. Cargo really should have subcommands to modify the package metadata. I guess we could go with something like https://crates.io/crates/tomato-toml. But it seems fairly new/unused and is not available in regular package repositories.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3910#-:-NBRzIfVCrHrSf2yKwHL:b1b3uia)* status: 0 of 1 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-14 14:29 UTC, faern requested changes
> Reviewed 5 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3910)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @dlon and @faern)

___
*[`version-metadata.sh` line 67 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3910#-NBwOGcW6KNmPw14mQma:-NBwOGcW6KNmPw14mQmb:bmlr83q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb0b145899ce9cc441b269c34afd27e0e139e1b/version-metadata.sh#L67)):*
> ```Shell
>     for toml in "${MANIFESTS[@]}"; do
>         cp "$toml" "$toml.bak"
>         cargo set-version "$semver_version" --manifest-path "$toml"
> ```

The fact that we need to back toml files up and restore them is a bit ugly. Not that this PR makes it worse in any way! So not a blocker. But maybe we should consider skipping `cargo set-version` and instead set some environment variable that we export before `cargo build` that we can then pick up in `build.rs` and produce a `PRODUCT_VERSION`. We already do all of this work! But we base it off of `CARGO_PKG_VERSION`. It would be pretty simple to base it off of something else.
___
*[`dist-assets/windows/version.h` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3910#-NBwMX9f1-F4DJlr26WC:-NBwMX9f1-F4DJlr26WD:b-i2pg0p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb0b145899ce9cc441b269c34afd27e0e139e1b/dist-assets/windows/version.h#L1)):*
> ```objc
> #define MAJOR_VERSION 2020
> ```

This should probably not be `2020`, but rather `2022`?


<!-- Sent from Reviewable.io -->

2022-09-19 13:15 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3910)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`dist-assets/windows/version.h` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3910#-NBwMX9f1-F4DJlr26WC:-NCKsuY_CkG_JazBq5gQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9cb0b145899ce9cc441b269c34afd27e0e139e1b/dist-assets/windows/version.h#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This should probably not be `2020`, but rather `2022`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-19 13:20 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3910)* status: 0 of 22 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`prepare-release.sh` line 61 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3910#-NCKttvG9lN9ydrOZOKb:-NCKttvG9lN9ydrOZOKc:bbdeqy9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27846758e3440c6287ee6f28e1a13f53f7d78053/prepare-release.sh#L61)):*
> ```Shell
> 
> echo "Updating version in metadata files..."
> . version-metadata.sh inject $PRODUCT_VERSION $VERSION_METADATA_ARGS
> ```

This will no longer increment the versions. I suppose we still do need that for this script?


<!-- Sent from Reviewable.io -->

2022-09-19 13:35 UTC, faern requested changes
> Reviewed 6 of 20 files at r4, 1 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3910)* status: 7 of 22 files reviewed, 2 unresolved discussions (waiting on @dlon and @faern)

___
*[`prepare-release.sh` line 61 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3910#-NCKttvG9lN9ydrOZOKb:-NCKunx7BEXNI4e80F20:bhry5v8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27846758e3440c6287ee6f28e1a13f53f7d78053/prepare-release.sh#L61)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This will no longer increment the versions. I suppose we still do need that for this script?
</blockquote></details>

Yeah. A large part of the point of this script is to set the version to the release version. So all the metadata is correct when building the release artifacts.
___
*[`mullvad-daemon/src/version_check.rs` line 307 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3910#-NCKxIUt4LvtT5SkGVfJ:-NCKxIUt4LvtT5SkGVfK:b33x2ux) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e04ba5fdf766747a993a2182e5f3ed6298b4b1a/mullvad-daemon/src/version_check.rs#L307)):*
> ```XML
>         show_beta: bool,
>     ) -> Option<String> {
>         if !*IS_DEV_BUILD {
> ```

Having this `if` removed is probably a leftover from debugging?


<!-- Sent from Reviewable.io -->

2022-09-20 12:50 UTC, faern approved these changes
> Reviewed 2 of 20 files at r4, 1 of 9 files at r5, 21 of 21 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3910)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-20 14:17 UTC, faern approved these changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3910)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`version-metadata.sh` line 68 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3910#-NCQFVrIBICZg8NObecc:-NCQFVrIBICZg8NObecd:bwpi5pr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6300606ffe52557cd0fd1652ba59dcd28e4a90c7/version-metadata.sh#L68)):*
> ```Shell
>         cp "$toml" "$toml.bak"
>         awk "BEGIN { matches=0; } matches==0 && /^version = \"[^\"]+\"$/ \
>              { print \"version = \\\"$semver_version\\\"\"; matches++; next; } { print }" "$toml.bak" > "$toml"
> ```

Oh dear :sweat_smile: :sweat: This is why we want to replace this with some more dedicated toml editor :see_no_evil: But that's out of scope for this PR.


<!-- Sent from Reviewable.io -->

2022-09-20 14:21 UTC, merged