MUL22-02 for Linux - maintain blocking firewall rules during system shutdown.
mullvad/mullvadvpn-app pull request #3940
Opened 2022-09-19 09:08 UTC by pinkisemils

Due to the ordering of shutdown events, the mullvad daemon will most often be shut down while network interfaces are still configured and working, which allows for a time window where arbitrary processes can send network traffic outside of the tunnel, even if the user never intended for this. 

To fix this, the daemon will not clear it's firewall rules during shutdown if the user didn't explicitly disconnect before the daemon is being stopped, unless `systemd` is reachable over D-Bus and it's reporting that the system is not shutting down.

2022-09-19 11:02 UTC, faern requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`mullvad-daemon/src/lib.rs` line 2166 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940#-NCKORV7DNAO67jfiV_q:-NCKORV7DNAO67jfiV_r:b-br1uhn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c5e81ec3b95d9e2a6965fe09db88d11661cc181c/mullvad-daemon/src/lib.rs#L2166)):*
> ```XML
>         #[cfg(windows)]
>         if self.settings.auto_connect || *self.target_state == TargetState::Secured {
>             self.send_tunnel_command(TunnelCommand::BlockWhenDisconnected(true));
> ```

As discussed AFK. Remove the Windows change for now and do that in a separate PR when we have evaluated the situation there.
___
*[`talpid-dbus/src/systemd.rs` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940#-NCKP1ij5EX0qY3tkHS6:-NCKP1ij5EX0qY3tkHS7:b-z1l1kf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c5e81ec3b95d9e2a6965fe09db88d11661cc181c/talpid-dbus/src/systemd.rs#L24)):*
> ```XML
> const RPC_TIMEOUT: Duration = Duration::from_secs(1);
> 
> pub fn host_shutting_down() -> Result<bool> {
> ```

Nit. I think an `is_` would be good in this function name. Any reason to name this differently than the function it calls?


<!-- Sent from Reviewable.io -->

2022-09-19 11:58 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`mullvad-daemon/src/lib.rs` line 2166 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940#-NCKORV7DNAO67jfiV_q:-NCKaPLf75uWhcUdLdLk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c5e81ec3b95d9e2a6965fe09db88d11661cc181c/mullvad-daemon/src/lib.rs#L2166)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

As discussed AFK. Remove the Windows change for now and do that in a separate PR when we have evaluated the situation there.
</blockquote></details>

Done.
___
*[`talpid-dbus/src/systemd.rs` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940#-NCKP1ij5EX0qY3tkHS6:-NCKbCSm9Cj2GjwghCNX:b-79pzff) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c5e81ec3b95d9e2a6965fe09db88d11661cc181c/talpid-dbus/src/systemd.rs#L24)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nit. I think an `is_` would be good in this function name. Any reason to name this differently than the function it calls?
</blockquote></details>

No good reason, I've added the prefix now.


<!-- Sent from Reviewable.io -->

2022-09-19 12:35 UTC, faern approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-19 13:00 UTC, dlon approved these changes
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`talpid-dbus/src/systemd.rs` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940#-NCKnikD6g-1dbJZx53m:-NCKnikD6g-1dbJZx53n:b-v7jws1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c136649c7f3949cb61b657821d387338f4974a9f/talpid-dbus/src/systemd.rs#L42)):*
> ```XML
>         self.as_manager_object()
>             .get(MANAGER_INTERFACE, SYSTEM_STATE)
>             .map(|state: String| state == SYSTEM_STATE_STOPPING)
> ```

Does this work when systemd is in maintenance or degraded mode? Part of me wants to invert it: `state != SYSTEM_STATE_RUNNING`.


<!-- Sent from Reviewable.io -->

2022-09-20 09:05 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`talpid-dbus/src/systemd.rs` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940#-NCKnikD6g-1dbJZx53m:-NCL9TS1DqJPtVyDCLOp:b-sfstaa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c136649c7f3949cb61b657821d387338f4974a9f/talpid-dbus/src/systemd.rs#L42)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Does this work when systemd is in maintenance or degraded mode? Part of me wants to invert it: `state != SYSTEM_STATE_STARTING && state != SYSTEM_STATE_INITIALIZING && ...`.
</blockquote></details>

I think you are correct - it's easier to check if the system is in a good state. I'll invert the logic here.
This will allow the blocking rules to remain if the system enters maintenance/emergency mode after bootup. The degraded state is fine - if the system is in a degraded state due to our daemon not running, that's fine - this code won't be executed anyway. 


<!-- Sent from Reviewable.io -->

2022-09-21 08:57 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`mullvad-daemon/src/lib.rs` line 2167 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940#-NCQq7ZsApkJz_wnYRhM:-NCUFwNA3yRcYffV2QgE:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c40a5a874fb4aaa6c4ea650ea9181110624b3fdd/mullvad-daemon/src/lib.rs#L2167)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Don't forget to remove this.
</blockquote></details>

Done.
___
*[`mullvad-daemon/src/main.rs` line 141 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940#-NCQpv97Db7YK3YK4_4r:-NCUFwpGCIUYpoJMUoi7:b-bx2cf8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c40a5a874fb4aaa6c4ea650ea9181110624b3fdd/mullvad-daemon/src/main.rs#L141)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is this not used on Windows when the daemon is run directly?
</blockquote></details>

You are correct, but I assume in that case the daemon should always be removing the firewall rules, when shutting down right?


<!-- Sent from Reviewable.io -->

2022-09-21 09:01 UTC, dlon approved these changes
> Reviewed 4 of 6 files at r1, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`mullvad-daemon/src/lib.rs` line 2163 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940#-NCUGfQDC9m6xHD-tEAs:-NCUGfQDC9m6xHD-tEAt:b1qjp48) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73139394a70c03543a2ae6d9c1e72dce74e679e7/mullvad-daemon/src/lib.rs#L2163)):*
> ```XML
>     }
> 
>     #[cfg_attr(not(target_os = "windows"), allow(unused_variables))]
> ```

Also remove this.
___
*[`mullvad-daemon/src/main.rs` line 141 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940#-NCQpv97Db7YK3YK4_4r:-NCUGjUp1nMZNnKCyLJ1:br56xs1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c40a5a874fb4aaa6c4ea650ea9181110624b3fdd/mullvad-daemon/src/main.rs#L141)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

You are correct, but I assume in that case the daemon should always be removing the firewall rules, when shutting down right?
</blockquote></details>

Yes, that looks right.


<!-- Sent from Reviewable.io -->

2022-09-21 09:03 UTC, dlon requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`CHANGELOG.md` line 81 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940#-NCUHG-17sG-pbAVQcmj:-NCUHG-17sG-pbAVQcmk:bf46ncg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73139394a70c03543a2ae6d9c1e72dce74e679e7/CHANGELOG.md#L81)):*
> ```Markdown
>   that the system service starts after a networking daemon has already configured a network
>   interface.
> - When the system process is being shut down and the target state is _secured_, maintain the
> ```

Should this be directly under "Security"?


<!-- Sent from Reviewable.io -->

2022-09-21 10:26 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`CHANGELOG.md` line 81 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940#-NCUHG-17sG-pbAVQcmj:-NCU_FzL4h3NM1VbByEL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73139394a70c03543a2ae6d9c1e72dce74e679e7/CHANGELOG.md#L81)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should this be directly under "Security"?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-21 10:53 UTC, dlon approved these changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`CHANGELOG.md` line 77 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940#-NCUetYY6FQgnO94Y2MN:-NCUetYY6FQgnO94Y2MO:b1fw8p2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e94675ee42ed09b7744d45a950ff9eb84fcbb8ca/CHANGELOG.md#L77)):*
> ```Markdown
> 
> ### Security
> - Added traffic blocking during early boot, before the daemon starts, to prevent leaks in the case
> ```

Isn't this Linux-specific?


<!-- Sent from Reviewable.io -->

2022-09-21 12:13 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`CHANGELOG.md` line 77 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940#-NCUetYY6FQgnO94Y2MN:-NCUxrIACpH7k-cbbtX5:bb77ufg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e94675ee42ed09b7744d45a950ff9eb84fcbb8ca/CHANGELOG.md#L77)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Isn't this Linux-specific?
</blockquote></details>

Yes.


<!-- Sent from Reviewable.io -->

2022-09-21 12:47 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-21 13:06 UTC, merged