Add notification permision for android 13
mullvad/mullvadvpn-app pull request #3970
Opened 2022-09-27 08:12 UTC by sabercodic

swap bug on android 13 fixed by upgrade
compile SDK and adding notification
permission request to the app

2022-09-28 08:55 UTC, albin-mullvad requested changes
According to the documentation, we shouldn't send any notification unless/until after the permission has been granted, which means that we probably need additional logic to keep track of the permission state.

>Your app must wait to send notifications until after you request the new permission and the user grants that permission to your app.

https://developer.android.com/develop/ui/views/notifications/notification-permission#new-apps

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-:-ND2HUBG-5MbEWY8KZp4:bg0201j)* status: all files reviewed, 6 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-ND2IVapDYCExMVxWsB7):*
This should be refined a bit and only include the actual changes of this commit/PR.



_Code quote:_
```
  swape bug on android 13 fixed by upgrade
  compile sdk and adding notification
  permission request to the app
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/NotificationChannel.kt` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-ND26L3t3Z1T2jf9Jgf2:-ND26L3t3Z1T2jf9Jgf3:bdmxlvq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c6cef788305f5bfcac00ee5ff7c7abc9facd0859/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/NotificationChannel.kt#L45)):*
> ```Kotlin
>         title: String,
>         deleteIntent: PendingIntent? = null,
>         ongoing: Boolean = false
> ```

I suggest changing `isOngoing`. This also applies to the other functions.



_Code quote:_
```Kotlin
ongoing
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 48 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-ND28J_Y3hmGBv0IFVM_:-ND28J_Y3hmGBv0IFVMa:bkpvzdf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c6cef788305f5bfcac00ee5ff7c7abc9facd0859/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L48)):*
> ```Kotlin
> open class MainActivity : FragmentActivity() {
>     val problemReport = MullvadProblemReport()
>     private lateinit var mPermReceiver: ActivityResultLauncher<String>
> ```

The m-prefix is usually not used in kotlin



_Code quote:_
```Kotlin
mPermReceiver
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-ND28al8AYNPpuGjr1c8:-ND28al8AYNPpuGjr1c9:b-w5ld16) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/693f63ec46a6e372f0ddd6eca65cacea23cb1892/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L60)):*
> ```Kotlin
>     override fun onCreate(savedInstanceState: Bundle?) {
>         loadKoinModules(uiModule)
> ```

Skip removing this empty line as it's not part of this PR
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-ND2ClXI3rAF2DMT9YTw:-ND2ClXI3rAF2DMT9YTx:bxuzsn4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c6cef788305f5bfcac00ee5ff7c7abc9facd0859/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L89)):*
> ```Kotlin
>         launchDeviceStateHandler()
> 
>         registerPermissionReceiver() // Notification permission check
> ```

This comment shouldn't be needed. I suggest changing the function to clarify what it does.



_Code quote:_
```Kotlin
// Notification permission check
```
___
*[`dist-assets/binaries` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-ND26gOeD0-94YFzrhk1:-ND26gOeD0-94YFzrhk2:b-k039oz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c6cef788305f5bfcac00ee5ff7c7abc9facd0859/dist-assets/binaries#L1)):*
> ```
> Subproject commit 4ccf373118861377c0a6fe10de50eeab7650ab5b
> ```

This diff shouldn't be part of this PR.



_Code quote:_
```
Subproject commit 4ccf373118861377c0a6fe10de50eeab7650ab5b
```


<!-- Sent from Reviewable.io -->

2022-09-29 14:01 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 48 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-ND28J_Y3hmGBv0IFVM_:-ND8So_t9tNyAWWfzT-P:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c6cef788305f5bfcac00ee5ff7c7abc9facd0859/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L48)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The m-prefix is usually not used in kotlin
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-29 14:01 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/NotificationChannel.kt` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-ND26L3t3Z1T2jf9Jgf2:-ND8SNTl0p18ayyPDe65:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c6cef788305f5bfcac00ee5ff7c7abc9facd0859/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/NotificationChannel.kt#L45)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest changing `isOngoing`. This also applies to the other functions.
</blockquote></details>

Done.



_Code quote:_
```Kotlin
ongoing: Boolean = false
```


<!-- Sent from Reviewable.io -->

2022-09-30 13:19 UTC, sabercodic commented
*[`dist-assets/binaries` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-ND26gOeD0-94YFzrhk1:-NDDYD6E0t0PxtGps2sL:b-wuc5rl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c6cef788305f5bfcac00ee5ff7c7abc9facd0859/dist-assets/binaries#L1)):*
> https://developer.android.com/develop/ui/views/notifications/notification-permission#new-apps


<!-- Sent from Reviewable.io -->

2022-09-30 13:21 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-ND28al8AYNPpuGjr1c8:-NDDYef5AC2Hge5kMU9Z:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/693f63ec46a6e372f0ddd6eca65cacea23cb1892/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L60)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Skip removing this empty line as it's not part of this PR
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-04 08:04 UTC, albin-mullvad requested changes
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970)* status: all files reviewed, 5 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-ND2IVapDYCExMVxWsB7):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The swipe thing is not really a bug, right? It's rather changed default behavior. I suggest something like:

`Prevent Foreground service notification from being dismissed`

It seems like this could have been two commits as one adds a permission and another changes how we post notifications.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt` line 100 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NDX-3eu1f1PB0pH4Y02:-NDX-3eu1f1PB0pH4Y03:brhwogy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ec11aafa929ae0ce6191a43ddb6f0558e4cc2a0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt#L100)):*
> ```Kotlin
>             PackageManager.PERMISSION_GRANTED
>         return hasNotificationPermission &&
>             NotificationManagerCompat.from(context).areNotificationsEnabled()
> ```

Will this call not handle the case of missing permission? Do we also need to call `checkSelfPermission()`?



_Code quote:_
```Kotlin
areNotificationsEnabled()
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt` line 100 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NDX-MHK6lnicz7EhvF2:-NDX-MHK6lnicz7EhvF3:b-p268j3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ec11aafa929ae0ce6191a43ddb6f0558e4cc2a0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt#L100)):*
> ```Kotlin
>             PackageManager.PERMISSION_GRANTED
>         return hasNotificationPermission &&
>             NotificationManagerCompat.from(context).areNotificationsEnabled()
> ```

Is there a way to inject the notification manager?



_Code quote:_
```Kotlin
NotificationManagerCompat.from(context)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt` line 58 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NDWzDvr73lZSgt_2jaE:-NDWzDvr73lZSgt_2jaF:b-glvvwb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ec11aafa929ae0ce6191a43ddb6f0558e4cc2a0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt#L58)):*
> ```Kotlin
>         }
> 
>     private val notificationOngoing: Boolean
> ```

I suggest changing to: `shouldDisplayOngoingNotification`



_Code quote:_
```Kotlin
notificationOngoing
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 275 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NDT8jFt37mhPHb1EQh0:-NDT8jFt37mhPHb1EQh1:b-z8oxdf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ec11aafa929ae0ce6191a43ddb6f0558e4cc2a0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L275)):*
> ```Kotlin
>         ) {
>             checkForNotificationPermission()
>         }
> ```

The current implementation doesn't seem work properly for me, meaning that I don't seem to get the permission dialog when trying it out in the emulator (API 33). However, after making some changes to the implementation, it seems to work as expected. See more about that below.

This callback block is for handling the result of the requested permission, right? At this point it should be enough to handle the state (true/false) provided to the callback, meaning that we shouln't need any of the logic in the `checkForNotificationPermission`. The launch of the `permissionReceiver` should not originate from inside the callback.

I suggest having a look at the [documentation](https://developer.android.com/training/permissions/requesting#allow-system-manage-request-code) and structure it in a similar way. For example, the ActivityResultLauncher can be initiated and registered like below:

```
val requestNotificationPermissionLauncher = registerForActivityResult(RequestPermission() ) { /* */ }
```

The `launch` can then be call from `onStart` or `onResume` (perhaps via a helper function) as a starting point. 



_Code quote:_
```Kotlin
        ) {
            checkForNotificationPermission()
        }
```


<!-- Sent from Reviewable.io -->

2022-10-04 10:05 UTC, sabercodic commented
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-ND2IVapDYCExMVxWsB7):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The swipe thing is not really a bug, right? It's rather changed default behavior. I suggest something like:

`Prevent Foreground service notification from being dismissed`

It seems like this could have been two commits as one adds a permission and another changes how we post notifications.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-04 10:46 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt` line 58 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NDWzDvr73lZSgt_2jaE:-NDXaeVO3zc0iEnuz-qw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ec11aafa929ae0ce6191a43ddb6f0558e4cc2a0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt#L58)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest changing to: `shouldDisplayOngoingNotification`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-07 07:24 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 275 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NDT8jFt37mhPHb1EQh0:-NDlK4umB1Qdqr-ExJKS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ec11aafa929ae0ce6191a43ddb6f0558e4cc2a0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L275)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The current implementation doesn't seem work properly for me, meaning that I don't seem to get the permission dialog when trying it out in the emulator (API 33). However, after making some changes to the implementation, it seems to work as expected. See more about that below.

This callback block is for handling the result of the requested permission, right? At this point it should be enough to handle the state (true/false) provided to the callback, meaning that we shouln't need any of the logic in the `checkForNotificationPermission`. The launch of the `permissionReceiver` should not originate from inside the callback.

I suggest having a look at the [documentation](https://developer.android.com/training/permissions/requesting#allow-system-manage-request-code) and structure it in a similar way. For example, the ActivityResultLauncher can be initiated and registered like below:

```
val requestNotificationPermissionLauncher = registerForActivityResult(RequestPermission() ) { /* */ }
```

The `launch` can then be call from `onStart` or `onResume` (perhaps via a helper function) as a starting point. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-07 07:24 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt` line 100 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NDX-3eu1f1PB0pH4Y02:-NDXOUl39EEwSDoveXgo:b-sqzuzw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ec11aafa929ae0ce6191a43ddb6f0558e4cc2a0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt#L100)):*
> permission


<!-- Sent from Reviewable.io -->

2022-10-10 07:43 UTC, albin-mullvad requested changes
> Reviewed 1 of 4 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970)* status: all files reviewed, 9 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-ND2IVapDYCExMVxWsB7):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Pehaps also start with `Also`:

`Also prevent foreground service notification from being dismissed`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/FeaturesModule.kt` line 7 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NE-e9xb-W2rE3aBfmFF:-NE-e9xc9_kmgrIDrZ9e:b-klgyzi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/FeaturesModule.kt#L7)):*
> ```Kotlin
> import org.koin.dsl.module
> 
> val featuresModule = module {
> ```

A feature module should be named according to the feature itself, for instance, a `notificationModule`. However, I believe it might be easier to start with naming it `vpnServiceModule` and  use it for mixed dependencies within the `MullvadVpnService`.



_Code quote:_
```Kotlin
featuresModule
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt` line 100 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NDX-3eu1f1PB0pH4Y02:-NE-mHI40tYUJGOTXREH:b-ghoet) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ec11aafa929ae0ce6191a43ddb6f0558e4cc2a0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt#L100)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

> permission
</blockquote></details>

Please elaborate. Is there a case where`areNotificationsEnabled` can return `true` when `hasNotificationPermission` is false? Isn't it enough to just check `areNotificationsEnabled` if that's the case?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt` line 67 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NDlf8t22D4QdNEFxPG9:-NDlf8t22D4QdNEFxPGA:b-yg4d0h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt#L67)):*
> ```Kotlin
> 
>     init {
>         loadKoinModules(featuresModule)
> ```

I suggest loading the module in `onCreate` of the `MullvadVpnService`



_Code quote:_
```Kotlin
loadKoinModules(featuresModule)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt` line 70 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NDlmIN4BeRUhFFsAU8z:-NDlmIN4BeRUhFFsAU9-:b-x84m88) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt#L70)):*
> ```Kotlin
>         getKoin().apply {
>             notificationManagerCompat = get()
>         }
> ```

We will probably want to inject it in the constructor in the future, but for now I suggest to extending `KoinComponent` and using field injection.



_Code quote:_
```Kotlin
        getKoin().apply {
            notificationManagerCompat = get()
        }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt` line 106 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NE-kt5m-JkJf2Cf5J4j:-NE-kt5m-JkJf2Cf5J4k:b-t1co2r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt#L106)):*
> ```Kotlin
> 
>     private fun isNotificationAllowed(): Boolean {
>         var hasNotificationPermission = Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU ||
> ```

`SdkUtils.isNotificationPermissionSupported().not()` (explaind in other comment) can be used here.



_Code quote:_
```Kotlin
Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt` line 106 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NE-l_Ti9SCvCxhtjXwf:-NE-l_Ti9SCvCxhtjXwg:b-q3umwg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt#L106)):*
> ```Kotlin
> 
>     private fun isNotificationAllowed(): Boolean {
>         var hasNotificationPermission = Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU ||
> ```

The name of this variable is misleading as the permission might have been denied when `Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU`.



_Code quote:_
```Kotlin
hasNotificationPermission
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 48 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NE-cFaq5pg36MlyUY4J:-NE-cFar3G2WSwPH-M5s:b-ymsufp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L48)):*
> ```Kotlin
>     val problemReport = MullvadProblemReport()
>     private var requestNotificationPermissionLauncher: ActivityResultLauncher<String> =
>         registerForActivityResult(ActivityResultContracts.RequestPermission()) {}
> ```

Add a comment explaining why this block is empty.



_Code quote:_
```Kotlin
{}
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 89 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NE-kFeY7sgKiJ79WNOU:-NE-kFeY7sgKiJ79WNOV:bzbhu9v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L89)):*
> ```Kotlin
> 
>         launchDeviceStateHandler()
> ```

I suggest skipping the empty line here
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 273 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NE-pVZt4hE6LlfTs757:-NE-pVZu6X-Wd7_4a9pO:b-m8q8yk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L273)):*
> ```Kotlin
>             requestNotificationPermissionLauncher.launch(Manifest.permission.POST_NOTIFICATIONS)
>         }
>     }
> ```

Sorry if I'm repeating this question, but is anything stopping this from launching the permission check every time the apps starts with the permission disabled?



_Code quote:_
```Kotlin
    private fun checkForNotificationPermission() {
        if (SdkUtils.checkNotificationPermissionIfRequiredAndNotGranted(this)) {






            requestNotificationPermissionLauncher.launch(Manifest.permission.POST_NOTIFICATIONS)

        }
    }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt` line 24 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NE-cc0f6tQb3kRxoEkK:-NE-cc0f6tQb3kRxoEkL:bsujksu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt#L24)):*
> ```Kotlin
>             context.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS) !=
>             PackageManager.PERMISSION_GRANTED
>     }
> ```

My suggestion was to only do the following here so that it can be re-used (e.g. in `AccountExpiryNotification`):

```
fun isNotificationPermission [...]

2022-10-10 09:54 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt` line 70 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NDlmIN4BeRUhFFsAU8z:-NE0JHKnBi3lBOC2PgZw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt#L70)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We will probably want to inject it in the constructor in the future, but for now I suggest to extending `KoinComponent` and using field injection.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-10 09:54 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt` line 67 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NDlf8t22D4QdNEFxPG9:-NE0-OFp4_EOqqNHwYqD:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt#L67)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest loading the module in `onCreate` of the `MullvadVpnService`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-10 10:51 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/FeaturesModule.kt` line 7 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NE-e9xb-W2rE3aBfmFF:-NE0-LIH0s9-XIN2V5E8:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/FeaturesModule.kt#L7)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

A feature module should be named according to the feature itself, for instance, a `notificationModule`. However, I believe it might be easier to start with naming it `vpnServiceModule` and  use it for mixed dependencies within the `MullvadVpnService`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-10 10:51 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt` line 106 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NE-kt5m-JkJf2Cf5J4j:-NE0WOR21OujE14hv5MT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt#L106)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

`SdkUtils.isNotificationPermissionSupported().not()` (explaind in other comment) can be used here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-10 10:53 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt` line 106 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NE-l_Ti9SCvCxhtjXwf:-NE0Wjy0DF7oWNM-R3Qb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt#L106)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The name of this variable is misleading as the permission might have been denied when `Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-10 10:53 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 89 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NE-kFeY7sgKiJ79WNOU:-NE03eN05fRPgTFHzEBH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L89)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest skipping the empty line here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-10 10:54 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 48 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NE-cFaq5pg36MlyUY4J:-NE03VuD65RhWCHYDXWS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L48)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Add a comment explaining why this block is empty.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-10 10:54 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 273 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NE-pVZt4hE6LlfTs757:-NE0WxmuAR19KpfKh6TA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L273)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Sorry if I'm repeating this question, but is anything stopping this from launching the permission check every time the apps starts with the permission disabled?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-10 10:54 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt` line 24 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NE-cc0f6tQb3kRxoEkK:-NE0X02D0LUQS85SO-Kw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/913c1f439f33535795a5215127c09d142c3a2d15/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt#L24)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

My suggestion was to only do the following here so that it can be re-used (e.g. in `AccountExpiryNotification`):

```
fun isNotificationPermissionSupported(): Boolean {
    return Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU
}
```

And do the remaining part at the calling location.

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-10 11:55 UTC, albin-mullvad reviewed
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt` line 27 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970#-NE0jkze1KxB9KvQvd3w:-NE0jkze1KxB9KvQvd3x:b642f19) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3e3c34ba690bc2bf58670c6c4ce9ca676bf8c5e7/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt#L27)):*
> ```Kotlin
> import org.koin.core.component.inject
> 
> @OptIn(KoinApiExtension::class)
> ```

As discussed AFK, it would be nice to double check whether this has any implications.



_Code quote:_
```Kotlin
@OptIn(KoinApiExtension::class)
```


<!-- Sent from Reviewable.io -->

2022-10-10 12:37 UTC, albin-mullvad approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-10 14:21 UTC, merged