Stop logging to a file in early boot blocking service
mullvad/mullvadvpn-app pull request #4008
Opened 2022-10-07 09:44 UTC by pinkisemils

Since some configurations mount `/var/` later in the boot process, logging will fail. To work around this, the behavior is changed so that if file logging doesn't work, it can rely solely on `stdout` logging.

2022-10-07 09:56 UTC, faern requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`CHANGELOG.md` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008#-NDls0EqADNZM-JmuJ6j:-NDls0EqADNZM-JmuJ6k:b-jvrjk0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d7d4b844898e59f1077a651cb5fd63bac3572bac/CHANGELOG.md#L44)):*
> ```Markdown
> #### Linux
> - Fix app crashing immediately when using some icon themes.
> - Don't prevent early boot service from running if logging to a file fails.
> ```

Wrong section. This beta is already released.


<!-- Sent from Reviewable.io -->

2022-10-07 10:03 UTC, faern requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`mullvad-daemon/src/main.rs` line 71 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008#-NDltTuU7Zbvz7t8GBFE:-NDltTuV26yBBBCLyilg:b-m6cb48) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d7d4b844898e59f1077a651cb5fd63bac3572bac/mullvad-daemon/src/main.rs#L71)):*
> ```XML
>         exception_logging::enable();
>         version::log_version();
>         return Ok(None);
> ```

This currently steps panics, exceptions and the version from being logged. Can we mitigate that "regression"?


<!-- Sent from Reviewable.io -->

2022-10-07 10:04 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`mullvad-daemon/src/main.rs` line 71 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008#-NDltTuU7Zbvz7t8GBFE:-NDltnRG5aLW-oekULam:b-dtpybb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d7d4b844898e59f1077a651cb5fd63bac3572bac/mullvad-daemon/src/main.rs#L71)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This currently steps panics, exceptions and the version from being logged. Can we mitigate that "regression"?
</blockquote></details>

Wait, it does not miss it. It was duplicated. I missed that part. Is there really no way to write this so the flow is easier to follow?


<!-- Sent from Reviewable.io -->

2022-10-07 10:13 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`mullvad-daemon/src/main.rs` line 71 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008#-NDltTuU7Zbvz7t8GBFE:-NDlugEB36I4Zhfm7_zW:b-76lmvb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d7d4b844898e59f1077a651cb5fd63bac3572bac/mullvad-daemon/src/main.rs#L71)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Wait, it does not miss it. It was duplicated. I missed that part. Is there really no way to write this so the flow is easier to follow?
</blockquote></details>

An attempt at making it better has been made now.


<!-- Sent from Reviewable.io -->

2022-10-07 12:24 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2022-10-07 12:49 UTC, faern approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`mullvad-daemon/src/main.rs` line 71 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008#-NDltTuU7Zbvz7t8GBFE:-NDmU-ay3Z1Sfq1wwjXc:b-3amltq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d7d4b844898e59f1077a651cb5fd63bac3572bac/mullvad-daemon/src/main.rs#L71)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

An attempt at making it better has been made now.
</blockquote></details>

This is way nicer!! Great you spent some time polishing it :ok_hand: 


<!-- Sent from Reviewable.io -->

2022-10-07 12:49 UTC, faern approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`mullvad-daemon/src/main.rs` line 78 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008#-NDmUWy90NYr-jLKhDIl:-NDmUWy90NYr-jLKhDIm:bw540lp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5daf802d529cf0724cb364b810a73affd3615179/mullvad-daemon/src/main.rs#L78)):*
> ```XML
> 
>     if let Some(ref log_dir) = log_dir {
>         log::info!("Logging to {}", log_dir.display());
> ```

This is now *not* logged if running in `initialize_firewall_and_exit` mode and initializing the logger worked.


<!-- Sent from Reviewable.io -->

2022-10-07 15:03 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`mullvad-daemon/src/main.rs` line 78 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008#-NDmUWy90NYr-jLKhDIl:-NDmxrnA6bOmJYzrf7t5:b-avsykr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5daf802d529cf0724cb364b810a73affd3615179/mullvad-daemon/src/main.rs#L78)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This is now *not* logged if running in `initialize_firewall_and_exit` mode and initializing the logger worked.
</blockquote></details>

Yes, and this isn't necessary IMO. If it can log to the filesystem, the daemon most likely will also be able to log to the filesystem. 


<!-- Sent from Reviewable.io -->

2022-10-10 07:29 UTC, faern approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-10 07:31 UTC, merged