Show changes after upgrade
mullvad/mullvadvpn-app pull request #4037
Opened 2022-10-13 10:48 UTC by sabercodic

Draft PR to check code style

2022-10-14 08:32 UTC, albin-mullvad reviewed
> Reviewed 1 of 33 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037)* status: 1 of 33 files reviewed, 14 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/build.gradle.kts` line 69 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKUGup-GDpXqhNt49I:-NEKUGup-GDpXqhNt49J:b-3nbbfu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/build.gradle.kts#L69)):*
> ```Kotlin
>     sourceSets {
>         getByName("main") {
>             assets.srcDirs(extraAssetsDirectory, changeLogAssetsDirectory)
> ```

I suggest a separate commit for the inclusion of the notes



_Code quote:_
```Kotlin
assets.srcDirs(extraAssetsDirectory, changeLogAssetsDirectory)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKbHdw1FCDgb7c_vDI:-NEKbHdw1FCDgb7c_vDJ:b-yqvbh0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt#L31)):*
> ```Kotlin
> @Composable
> fun ShowChangesDialog(
>     context: Context,
> ```

I believe we shouldn't need to pass the context here.



_Code quote:_
```Kotlin
context: Context,
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKVgUrCz2xEq6MeJH6:-NEKVgUs93IGwcCdKFOH:bntz2i3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt#L32)):*
> ```Kotlin
> fun ShowChangesDialog(
>     context: Context,
>     changesViewModel: AppChangesViewModel,
> ```

I suggest replacing the view model argument with the view state plus any actions as with `onBackPressed`.



_Code quote:_
```Kotlin
changesViewModel: AppChangesViewModel,
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKaNYzCGxfwt257glF:-NEKaNYzCGxfwt257glG:b42f2nd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt#L33)):*
> ```Kotlin
>     context: Context,
>     changesViewModel: AppChangesViewModel,
>     serviceConnectionManager: ServiceConnectionManager,
> ```

The view/dialog shouldn't know about the`ServiceConnectionManager`



_Code quote:_
```Kotlin
serviceConnectionManager: ServiceConnectionManager,
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKaTO9BI1znOn9XIO3:-NEKaTO9BI1znOn9XIO4:b-d4zwkc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt#L36)):*
> ```Kotlin
>     onBackPressed: () -> Unit
> ) {
>     var version: String? = serviceConnectionManager.appVersionInfoCache()?.version
> ```

As mentioned AFK, we can rely on the `BuildConfig.VERSION_NAME` instead.



_Code quote:_
```Kotlin
var version: String? = serviceConnectionManager.appVersionInfoCache()?.version
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt` line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKbBSoBg5y0KyM-BeJ:-NEKbBSp-E2ni_5Nl9bf:b-gtm5vp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt#L61)):*
> ```Kotlin
>             Column {
>                 Text(
>                     text = context.getString(R.string.changesHeader),
> ```

Any reason for not using `stringResource`?



_Code quote:_
```Kotlin
context.getString(R.string.changesHeader)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt` line 90 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKYutDBqTR8dJxKUwk:-NEKYutDBqTR8dJxKUwl:b-i8vu05) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt#L90)):*
> ```Kotlin
>         ttt.setSpan(BulletSpan(), 0, text.length - 1, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)
>         Text(
>             text = "• ",
> ```

I don't remember exactly how it looks like on desktop, but we can probably simplify this and instead prefix each item with the dot, e.g. "• {text}"
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKWhiY-aWaMDK_KNxW:-NEKWhiY-aWaMDK_KNxX:bctyb4s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt#L27)):*
> ```Kotlin
> fun ChangesListScreen(
>     viewModel: AppChangesViewModel,
>     serviceConnectionManager: ServiceConnectionManager,
> ```

The view/screen should not know about the `ServiceConnectionManager`. It should only interact with one more more view models.



_Code quote:_
```Kotlin
serviceConnectionManager: ServiceConnectionManager,
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKXPkX2M-sM0k-6r-V:-NEKXPkX2M-sM0k-6r-W:bfr9obz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L78)):*
> ```Kotlin
> 
> private fun providePreferences(app: Context): SharedPreferences =
>     app.getSharedPreferences(PREFS_FILE_KEY, Context.MODE_PRIVATE)
> ```

Is there any reason or benefit of doing this compared to just providing it withing the `single` scope (the place we call `providePreferences`)? Would probably also be nice to give it a scope/name.



_Code quote:_
```Kotlin
private fun providePreferences(app: Context): SharedPreferences =
    app.getSharedPreferences(PREFS_FILE_KEY, Context.MODE_PRIVATE)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEK_-yM6VioAv9GxFfd:-NEK_-yN5jRc-KvFbtqI:bz2l380) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L17)):*
> ```Kotlin
>     ShouldShow,
>     AlreadyShowed,
>     Unknown
> ```

This state should probably not exist. It should be enough with the other two.



_Code quote:_
```Kotlin
Unknown
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEK_HEB447iGSKYQKUb:-NEK_HEB447iGSKYQKUc:bf4a3kh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L37)):*
> ```Kotlin
>         preferences.edit().putBoolean(KEY_CHANGES_SHOWED, true).apply()
> 
>     fun getLastVersionChanges(): List<String> {
> ```

I suggest adding a data source as an abstraction layer between the repository and the file itself. The data source can be responsible for reading the file and the repository can handle the parsing.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 200 at r1 [...]

2022-10-14 09:08 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKbHdw1FCDgb7c_vDI:-NEKk1rK9Z8dvkHc0xTP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt#L31)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe we shouldn't need to pass the context here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-14 09:31 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKaNYzCGxfwt257glF:-NEKpSWt5y_TzffvJEkQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt#L33)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The view/dialog shouldn't know about the`ServiceConnectionManager`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-14 09:32 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKaTO9BI1znOn9XIO3:-NEKpbkY8rK5k1Ak8jeQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt#L36)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As mentioned AFK, we can rely on the `BuildConfig.VERSION_NAME` instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-14 09:35 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt` line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKbBSoBg5y0KyM-BeJ:-NEKqFV88LDXLHkDh7MI:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt#L61)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Any reason for not using `stringResource`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-14 09:45 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKWhiY-aWaMDK_KNxW:-NEKsXzI9pdMUJ-uFJsz:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt#L27)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The view/screen should not know about the `ServiceConnectionManager`. It should only interact with one more more view models.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-14 10:04 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEK_-yM6VioAv9GxFfd:-NEKwzWf6op0AqZkbCb9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L17)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This state should probably not exist. It should be enough with the other two.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-14 11:27 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 200 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEK_eos0pRYIOebH9gM:-NELDf893MTgtqlY9mS9:b-dhp13z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L200)):*
> the
we have "Initial" state and it is not good state to show dialog, app is busy with a lot of initializations back there


<!-- Sent from Reviewable.io -->

2022-10-14 11:28 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ListExt.kt` line 3 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKZn166B8nwXhFHg3e:-NELF46a-VDRh5nU7GYb:bb7s9zc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ListExt.kt#L3)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This one can be removed, right?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2022-10-17 08:38 UTC, sabercodic commented
*[`android/app/build.gradle.kts` line 69 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKUGup-GDpXqhNt49I:-NE_53KN1fUCvUuzxWUl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/build.gradle.kts#L69)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest a separate commit for the inclusion of the notes
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-17 09:46 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKVgUrCz2xEq6MeJH6:-NE_KZ5dCysnNAwY9lsx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt#L32)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest replacing the view model argument with the view state plus any actions as with `onBackPressed`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-17 11:50 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKXPkX2M-sM0k-6r-V:-NE_lXWICOGYDqwGk1S4:b16i4pl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L78)):*
> SharedPreferences
no, just different way to implement, I changed it


<!-- Sent from Reviewable.io -->

2022-10-17 12:06 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEK_HEB447iGSKYQKUb:-NE_peE17f_Y3CtnwTx4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L37)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest adding a data source as an abstraction layer between the repository and the file itself. The data source can be responsible for reading the file and the repository can handle the parsing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-17 12:07 UTC, sabercodic commented
*[`android/src/main/play/release-notes/en-US/default.txt` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEKZS9Z4iIVovnEKaC1:-NE_pvld3x9f9V1AlM16:b-k73z76) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/src/main/play/release-notes/en-US/default.txt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Would be nice to have a convenient way of improving the development workflow. I'll have a look at how we can do that.
</blockquote></details>

thanks


<!-- Sent from Reviewable.io -->

2022-10-18 07:08 UTC, albin-mullvad requested changes
> Reviewed 20 of 33 files at r1, 8 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037)* status: 28 of 34 files reviewed, 7 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/build.gradle.kts` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEdgUYO08Fo6rtYuVbP:-NEdgUYO08Fo6rtYuVbQ:bnmloj4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e00251964f6fab1ba329753e0301882ad6e1061/android/app/build.gradle.kts#L42)):*
> ```Kotlin
>             type = "boolean",
>             name = "ALWAYS_SHOW_CHANGELOG",
>             value = "$alwaysShowChangelog"
> ```

We can probably skip the string formatting here and just assign `value = alwaysShowChangelog`



_Code quote:_
```Kotlin
"$alwaysShowChangelog"
```
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangeLogScreenTest.kt` line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEdgy-0CMcNVrvar1xe:-NEdgy-0CMcNVrvar1xf:b-r8zpm1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e00251964f6fab1ba329753e0301882ad6e1061/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangeLogScreenTest.kt#L54)):*
> ```Kotlin
> 
>     companion object {
>         private const val UNBLOCK_WARNING = "Changes in this version:"
> ```

What does this constant name mean? Can it be clarified?



_Code quote:_
```Kotlin
UNBLOCK_WARNING
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt` line 73 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEdhNOr8WtjT4BZ83ek:-NEdhNOr8WtjT4BZ83el:be63hcp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e00251964f6fab1ba329753e0301882ad6e1061/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt#L73)):*
> ```Kotlin
>             Column(
>                 Modifier
>                     .padding(start = 16.dp, end = 16.dp, bottom = 16.dp)
> ```

Can some of these dimensions be set using common dimension resources? Same applies for some other dimensions in this file.



_Code quote:_
```Kotlin
16.dp, end = 16.dp, bottom = 16.dp
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt` line 104 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEdhqOf59pQE7rx7ZeE:-NEdhqOf59pQE7rx7ZeF:bge61cu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e00251964f6fab1ba329753e0301882ad6e1061/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt#L104)):*
> ```Kotlin
>         Box(
>             modifier = Modifier
>                 .absolutePadding(left = 16.dp, right = 16.dp)
> ```

Same as another comment, can some of these dimensions be set using common dimension resources?



_Code quote:_
```Kotlin
16.dp, right = 16.dp
```
___
*[`android/app/src/main/res/values/strings.xml` line 185 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEdiSqW3xpnuWaU2TjN:-NEdiSqW3xpnuWaU2TjO:b48mu9d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e00251964f6fab1ba329753e0301882ad6e1061/android/app/src/main/res/values/strings.xml#L185)):*
> ```XML
>     <string name="failed_to_remove_device">Failed to remove device</string>
>     <string name="changesHeader">Changes in this version:</string>
>     <string name="gotIt">Got it!</string>
> ```

Can the name be clarified a bit? I also believe we use snake case. E.g: `changelog_dismiss_button`
And perhaps `changelog_header` for the header text.



_Code quote:_
```XML
gotIt
```


<!-- Sent from Reviewable.io -->

2022-10-20 07:19 UTC, sabercodic commented
*[`android/app/build.gradle.kts` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEdgUYO08Fo6rtYuVbP:-NEoFgsaD3y50jiB2fC0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e00251964f6fab1ba329753e0301882ad6e1061/android/app/build.gradle.kts#L42)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We can probably skip the string formatting here and just assign `value = alwaysShowChangelog`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-20 08:28 UTC, sabercodic commented
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangeLogScreenTest.kt` line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEdgy-0CMcNVrvar1xe:-NEoVLTM1yJr6fBOYk-1:b-x869i7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e00251964f6fab1ba329753e0301882ad6e1061/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangeLogScreenTest.kt#L54)):*
> UNBLOCK_WARNING
changelog subtitle test, variable name changed


<!-- Sent from Reviewable.io -->

2022-10-20 08:32 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt` line 73 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEdhNOr8WtjT4BZ83ek:-NEoWK5nCRH0rDqqroiV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e00251964f6fab1ba329753e0301882ad6e1061/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt#L73)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can some of these dimensions be set using common dimension resources? Same applies for some other dimensions in this file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-20 08:39 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt` line 104 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEdhqOf59pQE7rx7ZeE:-NEoY4Hi2747HN0vCdQX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e00251964f6fab1ba329753e0301882ad6e1061/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt#L104)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Same as another comment, can some of these dimensions be set using common dimension resources?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-20 12:33 UTC, sabercodic commented
*[`android/app/src/main/res/values/strings.xml` line 185 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEdiSqW3xpnuWaU2TjN:-NEpNXQr1eqyI9hyR88X:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e00251964f6fab1ba329753e0301882ad6e1061/android/app/src/main/res/values/strings.xml#L185)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can the name be clarified a bit? I also believe we use snake case. E.g: `changelog_dismiss_button`
And perhaps `changelog_header` for the header text.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-21 11:14 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEpDPA_EkrwzLvu2IYS:-NEuF7IcAV7I_yMmIOTQ:bogcyhy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e763c2e24e11d5d9339c5ea97daa96896edae27a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt#L88)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this one needed? In that case we should add it as a dimensionResource
</blockquote></details>

no, removed


<!-- Sent from Reviewable.io -->

2022-10-21 11:49 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt` line 89 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEpDKIR4-9dtnwsGEr3:-NEuN5F22tB2hAIlkGDN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e763c2e24e11d5d9339c5ea97daa96896edae27a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt#L89)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this also use `dimensionResource`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-21 11:55 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt` line 108 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEpDae1CzJFzbRWqvPY:-NEuOPFl0fjWhyZ9X69C:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e763c2e24e11d5d9339c5ea97daa96896edae27a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt#L108)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this also use `dimensionResource`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-21 12:27 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 93 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEpYEjW7WkqUs0A-iez:-NEuVpNW8UOZ46OxeIqq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e763c2e24e11d5d9339c5ea97daa96896edae27a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L93)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should be possible to remove now and and instead use `ALWAYS_SHOW_CHANGELOG` within the VM or repo to override the behavior while testing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-21 12:27 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 200 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEK_eos0pRYIOebH9gM:-NEuVub54qwIsP5j008R:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L200)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Good point! I'll have another look if there are any alternative ways to handle this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-21 12:39 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ChangeLogDataProvider.kt` line 19 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEpaK3w-LoUdZ7Bt6MN:-NEuYWjNDYxVYT1Vl0v6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e763c2e24e11d5d9339c5ea97daa96896edae27a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ChangeLogDataProvider.kt#L19)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We usually avoid printing the stacktrack, so this should be changed to a regular error print, e.g. `Log.e(..., "Unable to read bundled changelog file.")`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-21 12:48 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt` line 22 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEpE8xB5Qt_OLDhvEfd:-NEu_HK60YNpgyaWStH0:b-pzgi1u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e763c2e24e11d5d9339c5ea97daa96896edae27a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt#L22)):*
> I believe we can skip including this in the PR as we will not use this atm, but perhaps keep it locally if/when we realize that we might want to visualize the changelog as a screen.
ChangeListFragment was unused part for now and i removed it, we use this one for show hide ChangelogDialog


<!-- Sent from Reviewable.io -->

2022-10-21 13:53 UTC, sabercodic commented
*[`android/app/src/main/res/values/strings.xml` line 185 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEdiSqW3xpnuWaU2TjN:-NEuoV5a94fbpGchaI-m:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e00251964f6fab1ba329753e0301882ad6e1061/android/app/src/main/res/values/strings.xml#L185)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Nice improvement :thumbsup: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-03 11:18 UTC, albin-mullvad requested changes
> Reviewed 1 of 33 files at r1, 4 of 20 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037)* status: 18 of 35 files reviewed, 9 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NFrjrz3D-31YjKl-_j_):*
There seem to be some uninteded text here? :thinking: 



_Code quote:_
```
end
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt` line 26 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NFwsHOk0eabiHn12mQ4:-NFwsHOk0eabiHn12mQ5:b8h0pzb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f69795c1af6302006dad1799ca938ecb859d0aa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt#L26)):*
> ```Kotlin
> 
>         ShowChangesDialog(
>             changesList = viewModel.getChangesList(),
> ```

I believe the changelog should be included in the state provided by the view model. This would mean that `shouldShowChanges` and `getChangesList` can be replaced with a refresh function that the activity can call once it's ready.

Here's how the state can be represented:

```
sealed class ChangelogDialogState {
    data class Show(val changes: List<String>): ChangelogDialogState()
    object Hide: ChangelogDialogState()
}
```



_Code quote:_
```Kotlin
getChangesList
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt` line 39 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NFws3oQEJxaO82hNlgg:-NFws3oQEJxaO82hNlgh:b7pvwov) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f69795c1af6302006dad1799ca938ecb859d0aa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt#L39)):*
> ```Kotlin
>             .fillMaxWidth()
>             .background(colorResource(id = R.color.colorPrimary))
>     ) {}
> ```

Does this need to be kept?



_Code quote:_
```Kotlin
    ConstraintLayout(
        modifier = Modifier
            .fillMaxHeight()
            .fillMaxWidth()
            .background(colorResource(id = R.color.colorPrimary))
    ) {}
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 26 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NFwq1nqBC5z089zO4rm:-NFwq1nrDLRSXv4sjfhb:b4s009) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f69795c1af6302006dad1799ca938ecb859d0aa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L26)):*
> ```Kotlin
> 
>     fun resetShouldShowLastChanges() {
>         preferences.edit().putBoolean(KEY_CHANGES_SHOWED, false).apply()
> ```

What's the reason for persisting with the version name as a key? It seems like there would be a growing amount of keys. Did you consider a static key with the last showed version name/code as a value? The version code might be most suitable to use as it's easy to compare.

```
putInt("last_showed_changelog_version_code", BuildConfig.VERSION_CODE)
```



_Code quote:_
```Kotlin
KEY_CHANGES_SHOWED
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ChangeLogDataProvider.kt` line 19 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEpaK3w-LoUdZ7Bt6MN:-NFrkZrVDhN1Ew-Xnkff:b-stned5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e763c2e24e11d5d9339c5ea97daa96896edae27a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ChangeLogDataProvider.kt#L19)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The text doesn't seem to be correct. Did you see my suggested text? Also, I don't believe we need to print `ex.message`.

The `LOG_TAG` used is not correct. Easiest would be to use the string `mullvad` atm. We'll eventually want to improve logging to either use `Timber` or our own minimal re-usable logging class.



_Code quote:_
```Kotlin
Error capturing screenshot
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt` line 17 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NFx4PoIEGCN4-k6Yp63:-NFx4PoIEGCN4-k6Yp64:b-q12hwf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f69795c1af6302006dad1799ca938ecb859d0aa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt#L17)):*
> ```Kotlin
> class AppChangesViewModel(
>     private val appChangesRepository: AppChangesRepository,
>     private val dispatcher: CoroutineDispatcher = Dispatchers.Default
> ```

Doesn't need to be a `val`



_Code quote:_
```Kotlin
val 
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt` line 23 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NFx8-G2Esja1lqH8Vzk:-NFx8-G2Esja1lqH8Vzl:bxeyj6b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f69795c1af6302006dad1799ca938ecb859d0aa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt#L23)):*
> ```Kotlin
>             ChangeLogState.ShouldShow
>         else ChangeLogState.AlreadyShowed
>     )
> ```

I believe the changelog should be included in the state provided by the view model. This would mean that `shouldShowChanges` and `getChangesList` can be replaced with a refresh function that the activity can call once it's ready.

Here's a pseudo-ish example: 
```
    private val shouldShowChangelog = MutableStateFlow(false)

    val changeLogState = shouldShowChangelog
        .map { shouldShow ->
            if (shouldShow) {
                ChangelogDialogState.Show(appChangesRepository.getLastVersionChanges())
            } else {
                ChangelogDialogState.Hide
            }
        }
        .stateIn(
            CoroutineScope(dispatcher),
            SharingStarted.WhileSubscribed(),
            ChangelogDialogState.Hide
        )

    fun refresh() {
        shouldShowChangelog.value = appChangesRepository.getLastShowedChangelogVersionCode().let {
            // logic to compare version codes to determine whether to show changelog or not.
        }
    }
```

Here's how the state would be represented instead of the current enum:

```
sealed class ChangelogDialogState {
    data class Show(val changes: List<String>): ChangelogDialogState()
    object Hide: ChangelogDialogState()
}
```


<!-- Sent from Reviewable.io -->

2022-11-03 12:30 UTC, sabercodic commented
*[`-- commits` line 5 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NFrjrz3D-31YjKl-_j_):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

There seem to be some uninteded text here? :thinking: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-07 12:08 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 26 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NFwq1nqBC5z089zO4rm:-NGGzNPrCvNk8BgCoztx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f69795c1af6302006dad1799ca938ecb859d0aa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L26)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

What's the reason for persisting with the version name as a key? It seems like there would be a growing amount of keys. Did you consider a static key with the last showed version name/code as a value? The version code might be most suitable to use as it's easy to compare.

```
putInt("last_showed_changelog_version_code", BuildConfig.VERSION_CODE)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-07 12:11 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ChangeLogDataProvider.kt` line 19 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEpaK3w-LoUdZ7Bt6MN:-NGH-3WX4caKhL4untrT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e763c2e24e11d5d9339c5ea97daa96896edae27a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ChangeLogDataProvider.kt#L19)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The text doesn't seem to be correct. Did you see my suggested text? Also, I don't believe we need to print `ex.message`.

The `LOG_TAG` used is not correct. Easiest would be to use the string `mullvad` atm. We'll eventually want to improve logging to either use `Timber` or our own minimal re-usable logging class.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-07 12:12 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt` line 17 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NFx4PoIEGCN4-k6Yp63:-NGH-J205VeyNqBm5OOJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f69795c1af6302006dad1799ca938ecb859d0aa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt#L17)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Doesn't need to be a `val`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-07 12:12 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt` line 26 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NFwsHOk0eabiHn12mQ4:-NGGw3D48W0v-eJU2obB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f69795c1af6302006dad1799ca938ecb859d0aa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt#L26)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe the changelog should be included in the state provided by the view model. This would mean that `shouldShowChanges` and `getChangesList` can be replaced with a refresh function that the activity can call once it's ready.

Here's how the state can be represented:

```
sealed class ChangelogDialogState {
    data class Show(val changes: List<String>): ChangelogDialogState()
    object Hide: ChangelogDialogState()
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-07 12:32 UTC, sabercodic commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2022-11-15 16:13 UTC, albin-mullvad requested changes
> Reviewed 2 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037)* status: 17 of 35 files reviewed, 24 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt` line 25 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGvUL7QDiFTiWJdtcD3:-NGvUL7QDiFTiWJdtcD4:b-slf8zl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt#L25)):*
> ```Kotlin
> 
> @Composable
> fun ShowChangesDialog(
> ```

I suggest using the same composable function name as the file name. As mentioned before, I would suggest sticking with "Changelog" everywhere to keep the naming unified. In that case the function and file would be named `ChangelogDialog`



_Code quote:_
```Kotlin
ShowChangesDialog
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt` line 12 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGvyPWM63JgG9gula3J:-NGvyPWM63JgG9gula3K:bg2jxf3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt#L12)):*
> ```Kotlin
> @Composable
> fun ChangesListScreen(
>     viewModel: AppChangesViewModel,
> ```

pass the `uiState` here rather than the vm



_Code quote:_
```Kotlin
viewModel: AppChangesViewModel
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 35 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGvVWvT6dMs1x7IhDjB:-NGvVWvT6dMs1x7IhDjC:b843mci) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L35)):*
> ```Kotlin
> val uiModule = module {
> 
>     single { androidApplication().getSharedPreferences(PREFS_FILE_KEY, Context.MODE_PRIVATE) }
> ```

This one should be named as there are might be other instances of `SharedPreferences`



_Code quote:_
```Kotlin
single { androidApplication().getSharedPreferences(PREFS_FILE_KEY, Context.MODE_PRIVATE) }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 78 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGvV96YAyHtTVSxVL_4:-NGvV96YAyHtTVSxVL_5:b58qwmg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L78)):*
> ```Kotlin
> const val SERVICE_CONNECTION_SCOPE = "SERVICE_CONNECTION_SCOPE"
> const val SELF_PACKAGE_NAME = "SELF_PACKAGE_NAME"
> const val PREFS_FILE_KEY = "net.mullvad.mullvadvpn.app_preferences"
> ```

I suggest renaming to `APP_PREFERENCES_NAME`



_Code quote:_
```Kotlin
PREFS_FILE_KEY
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 26 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NFwq1nqBC5z089zO4rm:-NGvdewwEadIQ1QDuPCn:bsnv6cb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f69795c1af6302006dad1799ca938ecb859d0aa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L26)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think the key should be a bit more clear, like the one I suggested `last_showed_changelog_version_code`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 10 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGvjH878dOuL0JT4a7u:-NGvjH878dOuL0JT4a7v:bmkib2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L10)):*
> ```Kotlin
> private const val KEY_CHANGES_SHOWED = "key_changes_showed"
> 
> interface IChangeLogDataProvider {
> ```

Nit: lowercase l



_Code quote:_
```Kotlin
L
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 17 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGw2MwI2cXa0frXyOrf:-NGw2MwI2cXa0frXyOrg:bfrhafr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L17)):*
> ```Kotlin
>     private val preferences: SharedPreferences,
>     private val dataProvider: IChangeLogDataProvider,
>     private val dispatcher: CoroutineDispatcher = Dispatchers.IO
> ```

Is this one used?



_Code quote:_
```Kotlin
private val dispatcher: CoroutineDispatcher = Dispatchers.IO
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 29 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGw0i1s0YbmNorO8ZsF:-NGw0i1tBXTVeGvHveLD:bpwzhy4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L29)):*
> ```Kotlin
> 
>     fun setShowedLastChanges() =
>         preferences.edit().putInt(KEY_CHANGES_SHOWED, BuildConfig.VERSION_CODE).apply()
> ```

I suggest changing `shouldShowLastChanges` and `setShowedLastChanges`to the following and move the version comparison logic to the view model. That would also mean we can remove `resetShouldShowLastChanges`

```
setVersionCodeOfMostRecentChangelogShowed(versionCode: Int)
getVersionCodeOfMostRecentChangelogShowed(): Int
```



_Code quote:_
```Kotlin
    fun shouldShowLastChanges(): Boolean {
        return preferences.getInt(KEY_CHANGES_SHOWED, -1) < BuildConfig.VERSION_CODE ||
            BuildConfig.ALWAYS_SHOW_CHANGELOG
    }

    fun setShowedLastChanges() =
        preferences.edit().putInt(KEY_CHANGES_SHOWED, BuildConfig.VERSION_CODE).apply()
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 197 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGw-EDQ-8y3kqBJLsN6:-NGw-EDQ-8y3kqBJLsN7:bq4wcfp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L197)):*
> ```Kotlin
>                     if (currentState is DeviceState.LoggedOut ||
>                         currentState is DeviceState.LoggedIn
>                     ) {
> ```

It would probably be good to move this to a separate subscription in order to avoid increased complexity.



_Code quote:_
```Kotlin
                    if (currentState is DeviceState.LoggedOut ||
                        currentState is DeviceState.LoggedIn
                    ) {
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 211 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGvzWK65fGiXEGjsVFJ:-NGvzWK65fGiXEGjsVFK:b-21997q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L211)):*
> ```Kotlin
>                     topBarColor = colorResource(id = android.R.color.transparent),
>                     statusBarColor = colorResource(id = android.R.color.transparent),
>                     navigationBarColor = colorResource(id = android.R.color.transparent),
> ```

This seem to include things that only should be required for regular views/fragments. For example, is the Scaffolding call required?



_Code quote:_
```Kotlin
                ScaffoldWithTopBar(
                    topBarColor = colorResource(id = android.R.color.transparent),
                    statusBarColor = colorResource(id = android.R.color.transparen [...]

2022-11-16 08:29 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt` line 25 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGvUL7QDiFTiWJdtcD3:-NGzYc-m2OBDAZB2DTX1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt#L25)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest using the same composable function name as the file name. As mentioned before, I would suggest sticking with "Changelog" everywhere to keep the naming unified. In that case the function and file would be named `ChangelogDialog`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-16 08:35 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt` line 12 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGvyPWM63JgG9gula3J:-NGz_7GMDLq0_IU2UHHx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt#L12)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

pass the `uiState` here rather than the vm
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-16 08:45 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037)* status: 17 of 35 files reviewed, 26 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 33 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGzb7uqDZBVwfMysg_S:-NGzb7uqDZBVwfMysg_T:bh3nrpe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L33)):*
> ```Kotlin
>     fun getLastVersionChanges(): List<String> {
>         return dataProvider.getChangeLog().split('\n')
>             .filter { !it.isNullOrEmpty() }
> ```

Change to `it.isNotEmpty`. Null check not needed



_Code quote:_
```Kotlin
!it.isNullOrEmpty()
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 34 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGzbD0fAwhXdCPLoxil:-NGzbD0fAwhXdCPLoxim:b55s3cm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L34)):*
> ```Kotlin
>         return dataProvider.getChangeLog().split('\n')
>             .filter { !it.isNullOrEmpty() }
>             .map { "$it" }
> ```

This doesn't seem to do anything as it's already a string



_Code quote:_
```Kotlin
.map { "$it" }
```


<!-- Sent from Reviewable.io -->

2022-11-16 09:03 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037)* status: 17 of 35 files reviewed, 29 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt` line 13 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGze7XHDr30lwYKVUFQ:-NGze7XHDr30lwYKVUFR:b-ehxuzq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt#L13)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.repository.AppChangesRepository
> 
> class AppChangesViewModel(
> ```

As the repository isn't reactive (atm) and the logic is quite simple, I believe the following simplification of the vm would be beneficial. The `repo.getVersionCodeOfMostRecentChangelogShowed` funciton call depends on one of the other suggested changes

```
    private val _changelogDialogUiState =
        MutableStateFlow<ChangelogDialogState>(ChangelogDialogState.Hide)
    val changelogDialogUiState = _changelogDialogUiState.asStateFlow()

    fun refreshChangelogDialogUiState() {
        val shouldShowChangelogDialog = repo.getVersionCodeOfMostRecentChangelogShowed() /* + comparison logic */
  
        _changelogDialogUiState.value = if (shouldShowChangelogDialog) {
            ChangelogDialogState.Show(appChangesRepository.getLastVersionChanges())
        } else {
            ChangelogDialogState.Hide
        }
    }

    fun dismissChangelogDialog() {
        appChangesRepository.setShowedLastChanges()
        _changelogDialogUiState.value = ChangelogDialogState.Hide
    }
```



_Code quote:_
```Kotlin
AppChangesViewModel
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt` line 39 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGzdf5G4HPO8Xh8M7sv:-NGzdf5G4HPO8Xh8M7sw:bpvb19o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt#L39)):*
> ```Kotlin
>     }
> 
>     fun setDialogShowed() = appChangesRepository.setShowedLastChanges().also {
> ```

I suggest renaming to `onChangelogDialogDismissed`



_Code quote:_
```Kotlin
setDialogShowed
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt` line 44 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGzdPGgEAT0GPz7LDle:-NGzdPGgEAT0GPz7LDlf:bak857o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt#L44)):*
> ```Kotlin
> }
> 
> sealed class ChangelogDialogState {
> ```

As we now use this as a way to represent the UI state, I believe it would be nice to rename it to: `ChangelogDialogUiState`. Also, I suggest moving it to a separate file.



_Code quote:_
```Kotlin
ChangelogDialogState
```


<!-- Sent from Reviewable.io -->

2022-11-16 12:48 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 78 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGvV96YAyHtTVSxVL_4:-NH-TtNFCJz0bGulIJQD:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L78)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest renaming to `APP_PREFERENCES_NAME`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-16 12:50 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 17 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGw2MwI2cXa0frXyOrf:-NH-USkXB0IJCYPRCxa-:bogcyhy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L17)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this one used?
</blockquote></details>

no, removed


<!-- Sent from Reviewable.io -->

2022-11-16 12:59 UTC, sabercodic commented
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 35 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGvVWvT6dMs1x7IhDjB:-NH-WRFn1oV_B2fuHG-T:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L35)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This one should be named as there are might be other instances of `SharedPreferences`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-16 15:51 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037)* status: 11 of 37 files reviewed, 27 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 26 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NFwq1nqBC5z089zO4rm:-NH-X1Hg5HCi88QYs1NV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f69795c1af6302006dad1799ca938ecb859d0aa/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L26)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I think the key should be a bit more clear, like the one I suggested `last_showed_changelog_version_code`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 29 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGw0i1s0YbmNorO8ZsF:-NH-YK_S-pFphOAq9lb1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L29)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest changing `shouldShowLastChanges` and `setShowedLastChanges`to the following and move the version comparison logic to the view model. That would also mean we can remove `resetShouldShowLastChanges`

```
setVersionCodeOfMostRecentChangelogShowed(versionCode: Int)
getVersionCodeOfMostRecentChangelogShowed(): Int
```
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 33 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGzb7uqDZBVwfMysg_S:-NH-Z5U9BREOLKqQdmjW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L33)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Change to `it.isNotEmpty`. Null check not needed
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 34 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGzbD0fAwhXdCPLoxil:-NH-Z5ij42SMOj10yzZg:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L34)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This doesn't seem to do anything as it's already a string
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 197 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGw-EDQ-8y3kqBJLsN6:-NH-_-lmELPskfE_amtC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L197)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

It would probably be good to move this to a separate subscription in order to avoid increased complexity.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 211 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGvzWK65fGiXEGjsVFJ:-NH-_rm55asPzB1fK45D:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L211)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This seem to include things that only should be required for regular views/fragments. For example, is the Scaffolding call required?
</blockquote></details>

Done.
___
*[`android/app/src/main/res/layout/main.xml` line 8 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGb9dpG0ygmYU_V5VXH:-NH-rcva4lqZdaleyoMm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/res/layout/main.xml#L8)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is there a constant that can be used instead? Also, can you add a code comment explaining why it's zero height?
</blockquote></details>

Done.
___
*[`android/app/src/main/res/values/strings.xml` line 173 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGvo6HSBtejv5P-bNQy:-NH07rGS1FXoQ-Zczj9W:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/res/values/strings.xml#L173)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This diff looks a bit odd :thinking: 
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ChangeLogDataProvider.kt` line 19 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEpaK3w-LoUdZ7Bt6MN:-NH-apFW4L3TDjtlIMx-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e763c2e24e11d5d9339c5ea97daa96896edae27a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ChangeLogDataProvider.kt#L19)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Also change to `Log.e` and to not use `androidx.core.content.PackageManagerCompat.LOG_TAG` as I mentioned above
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ChangeLogDataProvider.kt` line 10 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGvnm7F3NJc5YfE19gu:-NH-a2JX7PiQhDC133bD:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ChangeLogDataProvider.kt#L10)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

`CHANGELOG_FILE`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ChangeLogDataProvider.kt` line 19 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGvn89WAuHyo-itcxzX:-NH-aaMw80_1dfAWfDUl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ChangeLogDataProvider.kt#L19)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should be possible to simplify using something like: `File(CHANGES_FILE).readText()`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGw2V7Z0GrG2nOeQsis:-NH-axai69L5RAI5rFMS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2b6155a2257f748f8f5565e6f3ab4462ff7c4f9d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt#L15)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Rename to `ChangelogViewModel`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt` line 13 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGze7XHDr30lwYKVUFQ:-NH-bpTH4507R8YzCXnh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppChangesViewModel.kt#L13)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As the repository isn't reactive (atm) and the logic is quite simple, I believe the following simplification of the vm would be beneficial. Th [...]

2022-11-17 09:08 UTC, albin-mullvad requested changes
> Reviewed 12 of 20 files at r4, 14 of 14 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037)* status: all files reviewed, 4 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt` line 22 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NEpE8xB5Qt_OLDhvEfd:-NH3p7n20oZW6tPULwRR:bckohc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e763c2e24e11d5d9339c5ea97daa96896edae27a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangesListScreen.kt#L22)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

> I believe we can skip including this in the PR as we will not use this atm, but perhaps keep it locally if/when we realize that we might want to visualize the changelog as a screen.
ChangeListFragment was unused part for now and i removed it, we use this one for show hide ChangelogDialog
</blockquote></details>

This composable component is a bit of a special one since it's something in between a screen (full view) and a re-usable component. Atm it's a bit hard to distinguish the purpose of this one vs `ShowChangelog`, therefore I suggest to remove this class and moving the state colleciton and if-statement to the `MainActivity`.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt` line 13 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NH3pp952VypvJBBhvzt:-NH3pp952VypvJBBhvzu:b-v3r44w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e016b1c92c9c503f3174230117bb8715b687fbb/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AppChangesRepository.kt#L13)):*
> ```Kotlin
> ) {
>     fun getVersionCodeOfMostRecentChangelogShowed(): Int {
>         return preferences.getInt(LAST_SHOWED_CHANGELOG_VERSION_CODE, -1)
> ```

Add a constant for this value, e.g. `MISSING_VERSION_CODE`



_Code quote:_
```Kotlin
-1
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ChangeLogViewModelTest.kt` line 15 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NH3lHs50aZZnwMkwyT3:-NH3lHs50aZZnwMkwyT4:b-y6yxfx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e016b1c92c9c503f3174230117bb8715b687fbb/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ChangeLogViewModelTest.kt#L15)):*
> ```Kotlin
> import org.junit.Test
> 
> class ChangeLogViewModelTest {
> ```

Change to lowercase "l": `ChangelogViewModelTest`



_Code quote:_
```Kotlin
L
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ChangeLogViewModelTest.kt` line 40 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NH3pEmx-Sz36BptfBW1:-NH3pEmx-Sz36BptfBW2:bkbev3a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e016b1c92c9c503f3174230117bb8715b687fbb/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ChangeLogViewModelTest.kt#L40)):*
> ```Kotlin
>         viewModel.changelogDialogUiState.test {
>             viewModel.refreshChangelogDialogUiState()
>         }
> ```

It looks like this test is missing an assertion



_Code quote:_
```Kotlin
        viewModel.changelogDialogUiState.test {
            viewModel.refreshChangelogDialogUiState()
        }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt` line 25 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NGvUL7QDiFTiWJdtcD3:-NH3loUB24SEFsBuaeAG:b-thtlke) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb398fb78cafaa187ba2aee12c2c827db6fcee45/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ChangesDialog.kt#L25)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Composable functions should have component names rather rather than typical function names. Any reason for not going with the suggested name above (`ChangelogDialog`)? 


<!-- Sent from Reviewable.io -->

2022-11-17 15:07 UTC, albin-mullvad requested changes
> Reviewed 10 of 10 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037)* status: all files reviewed, 2 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 72 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NH579WeEOh7Sj5lO26g:-NH579WeEOh7Sj5lO26h:brln57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/677e0ff660e6174c399b8fcb0143388ec9f69105/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L72)):*
> ```Kotlin
>     private lateinit var deviceRepository: DeviceRepository
>     private lateinit var serviceConnectionManager: ServiceConnectionManager
>     private lateinit var changesViewModel: ChangelogViewModel
> ```

Adjust to `changelogViewModel` to match the class name



_Code quote:_
```Kotlin
changes
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt` line 194 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NH571eD7G-LlFW0eKpW:-NH571eD7G-LlFW0eKpX:brre1g8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/677e0ff660e6174c399b8fcb0143388ec9f69105/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt#L194)):*
> ```Kotlin
>                         }
>                     }
>                     currentState = newState
> ```

It looks like this one was moved by mistake :thinking: 



_Code quote:_
```Kotlin
currentState = newState
```


<!-- Sent from Reviewable.io -->

2022-11-17 20:58 UTC, albin-mullvad approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-18 07:55 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037)* status: all files reviewed, 2 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ChangelogDataProvider.kt` line 15 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NH8gK4w2OHF2YLraBHZ:-NH8gK4w2OHF2YLraBH_:bxhoxgc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/335c61fb0337ce3fce268b6cc087da68f76081e2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ChangelogDataProvider.kt#L15)):*
> ```Kotlin
>         } catch (ex: IOException) {
>             Log.e("mullvad", "Unable to read bundled changelog file.")
>             ""
> ```

Nit: Add a constant called `EMPTY_DEFAULT_STRING_WHEN_UNABLE_TO_READ_CHANGELOG` to improve readability.



_Code quote:_
```Kotlin
""
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ChangelogViewModel.kt` line 21 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-NH8hhvV84mYzms9vBM7:-NH8hhvV84mYzms9vBM8:b-cbaq3a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/335c61fb0337ce3fce268b6cc087da68f76081e2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ChangelogViewModel.kt#L21)):*
> ```Kotlin
>             .getVersionCodeOfMostRecentChangelogShowed() < buildVersionCode
>         _changelogDialogUiState.value = if (shouldShowChangelogDialog) {
>             ChangelogDialogUiState.Show(changelogRepository.getLastVersionChanges())
> ```

I think we need check/fix the behavior of when the change list is empty and also add an automated vm test for it. Atm I believe the user might see a dialog without any changes.



_Code quote:_
```Kotlin
ChangelogDialogUiState.Show(changelogRepository.getLastVersionChanges())
```


<!-- Sent from Reviewable.io -->

2022-11-18 09:39 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r10, 1 of 1 files at r11, 2 of 12 files at r12, 12 of 12 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4037#-:-NH95w2QCi-Ol-YzghR2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-18 09:43 UTC, merged