Split up talpid-core into various modules
mullvad/mullvadvpn-app pull request #4041
Opened 2022-10-13 15:24 UTC by pinkisemils

To help with generalizing the tunnel state machine and decoupling it from tunnel implementations, I've split up a `talpid-core` into a bunch of crates.  This is but a draft, but feedback is very welcome.

2022-10-14 07:37 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041)* status: 0 of 95 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`talpid-openvpn/Cargo.toml` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NEKPxdi0XwGpm-qXN_4:-NEKPxdi0XwGpm-qXN_5:bmp3ktr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8ff53a99182647dc1b1ee6ace449f5c3abaed1f/talpid-openvpn/Cargo.toml#L6)):*
> ```TOML
> edition = "2021"
> 
> # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
> ```

Please remove this comment and copy the metadata of all other crates. Author, publish, license. And add a descriptive description, so it becomes easier to understand which crate does what and how it relates to the others.


<!-- Sent from Reviewable.io -->

2022-10-14 14:02 UTC, dlon requested changes
> Reviewed 7 of 95 files at r1, 3 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041)* status: 10 of 98 files reviewed, 9 unresolved discussions (waiting on @pinkisemils)

___
*[`talpid-dbus/src/network_manager.rs` line 396 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELfnZRC0ESdR_KyefZ:-NELfnZRC0ESdR_Kyef_:bntnzy4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-dbus/src/network_manager.rs#L396)):*
> ```XML
>     }
> 
>     pub fn can_be_used_to_manage_dns(&self) -> Result<()> {
> ```

The signature feels a bit unintuitive. Should this just return a bool? Or rename it to `ensure_nm_can_manage_dns`.
___
*[`talpid-openvpn/Cargo.toml` line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELYt4x0i8hhEaF1KwV:-NELYt4x0i8hhEaF1KwW:b-jxomvm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-openvpn/Cargo.toml#L33)):*
> ```TOML
> parity-tokio-ipc = "0.9"
> triggered = "0.1.1"
> tonic = "0.5"
> ```

Could we use `0.8` here?
___
*[`talpid-openvpn/Cargo.toml` line 34 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELYh8b0JZcHV57tFwY:-NELYh8b0JZcHV57tFwZ:b-5quefc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-openvpn/Cargo.toml#L34)):*
> ```TOML
> triggered = "0.1.1"
> tonic = "0.5"
> prost = "0.8"
> ```

Could we use `0.11` here?
___
*[`talpid-openvpn/Cargo.toml` line 55 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELZ7f0BdSn2BWGb01E:-NELZ7f1-b5A75VkL49V:b-jxomvm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-openvpn/Cargo.toml#L55)):*
> ```TOML
> 
> [build-dependencies]
> tonic-build = { version = "0.5", default-features = false, features = ["transport", "prost"] }
> ```

Could we use `0.8` here?
___
*[`talpid-windows/src/driver.rs` line 5 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELeOPCA4LB5LsdgU2D:-NELeOPCA4LB5LsdgU2E:b-n4j4zs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-windows/src/driver.rs#L5)):*
> ```XML
> /// Casts a struct to a slice of possibly uninitialized bytes.
> #[cfg(target_os = "windows")]
> pub fn as_uninit_byte_slice<T: Copy + Sized>(value: &T) -> &[mem::MaybeUninit<u8>] {
> ```

Maybe `ffi` or `serialize` would be better homes for this.
___
*[`talpid-windows/src/logging.rs` line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELd5M25QCdUe8I6RmV:-NELd5M25QCdUe8I6RmW:b-eryozg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-windows/src/logging.rs#L9)):*
> ```XML
> 
> /// Logging callback implementation.
> pub extern "system" fn log_sink(level: log::Level, msg: *const c_char, context: *mut c_void) {
> ```

All of this logging stuff should be hidden in the Windows firewall module once the winnet refactoring has been merged.
___
*[`talpid-windows/src/logging.rs` line 38 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELcuXU5Vn08dZmQLRo:-NELcuXU5Vn08dZmQLRp:byrlgpk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-windows/src/logging.rs#L38)):*
> ```XML
> }
> 
> pub fn multibyte_to_wide(mb_string: &CStr, codepage: u32) -> Result<Vec<u16>, io::Error> {
> ```

This belongs in `super::string`, if it needs to be public. And we should an enum for `codepage`, but that's pretty out of scope.
___
*[`talpid-wireguard/src/lib.rs` line 861 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELhVkVAkJ4aKkD0SWB:-NELhVkVAkJ4aKkD0SWC:b2ksqpk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-wireguard/src/lib.rs#L861)):*
> ```XML
> /// Converts an interface name into the corresponding index.
> #[cfg(target_os = "linux")]
> pub fn iface_index(name: &str) -> std::result::Result<libc::c_uint, IfaceIndexLookupError> {
> ```

Since this is duplicated: `talpid-linux`? :slightly_smiling_face: 

We could also have a shared `talpid-platform` crate containing `windows` (instead of `talpid-windows`), `linux`, etc.
___
*[`talpid-wireguard/src/wireguard_go.rs` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELiErK63LJsu9AlZst:-NELiErK63LJsu9AlZsu:bu3dtml) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-wireguard/src/wireguard_go.rs#L18)):*
> ```XML
> };
> #[cfg(not(windows))]
> use talpid_tunnel::tun_provider::TunProvider;
> ```

Nit: Can be combined with the latter imports.


<!-- Sent from Reviewable.io -->

2022-10-14 14:39 UTC, dlon requested changes
> Reviewed 41 of 95 files at r1, 3 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041)* status: 54 of 98 files reviewed, 15 unresolved discussions (waiting on @pinkisemils)

___
*[`dist-assets/binaries` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELvZpb84WF95mT0BSJ:-NELvZpb84WF95mT0BSK:bxq6mhr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/dist-assets/binaries#L1)):*
> ```
> Subproject commit 4ccf373118861377c0a6fe10de50eeab7650ab5b
> ```

Wrong commit.
___
*[`mullvad-management-interface/src/types.rs` line 1413 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELpq7H1ANwRdTNff2c:-NELpq7H1ANwRdTNff2d:batgxg9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/mullvad-management-interface/src/types.rs#L1413)):*
> ```XML
>                         cipher: proxy_settings.cipher,
>                         #[cfg(target_os = "linux")]
>                         fwmark: None,
> ```

Should this not be set to `Some(mullvad_types::TUNNEL_FWMARK)`?
___
*[`talpid-core/src/firewall/linux.rs` line 111 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELosfJ-vc_f_rbpvY3:-NELosfJ-vc_f_rbpvY4:b-1ug294) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-core/src/firewall/linux.rs#L111)):*
> ```XML
> impl Firewall {
>     pub fn from_args(args: FirewallArguments) -> Result<Self> {
>         Ok(Firewall {
> ```

Nit: `Firewall::new(args.fwmark)`
___
*[`talpid-core/src/window.rs` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELu4EqC3uTIlrNg6Vu:-NELu4EqC3uTIlrNg6Vv:b-6p7b6h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/611cdecfb3d146620865b4ea9b376694f49446d1/talpid-core/src/window.rs#L1)):*
> ```XML
> //! Utilities for windows.
> ```

Can we rename the module to `windows`?
___
*[`talpid-routing/src/linux.rs` line 64 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELr9fk9o5Df6hl0_qc:-NELr9fk9o5Df6hl0_qd:b-3sc98e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-routing/src/linux.rs#L64)):*
> ```XML
>         no_fwmark_rule_v4(fwmark, table),
>         no_fwmark_rule_v6(fwmark, table),
>         SUPPRESS_RULE_V4.clone(),
> ```

I wonder if we even need these two rules. Assuming that all tunnel traffic has the mark set, probably not.
___
*[`talpid-tunnel/src/network_interface.rs` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELuyDPC3w4R8xx0GwW:-NELuyDPC3w4R8xx0GwX:b-lzhh9o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-tunnel/src/network_interface.rs#L1)):*
> ```XML
> use nix::fcntl;
> ```

I'd argue this belongs in `talpid_tunnel::tun_provider::unix`, since we only ever use it there.


<!-- Sent from Reviewable.io -->

2022-11-01 14:48 UTC, pinkisemils commented
This is now a *real* pull request - review at your own pace.

2022-11-01 15:20 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041)* status: 31 of 113 files reviewed, 8 unresolved discussions (waiting on @dlon and @faern)

___
*[`talpid-openvpn/Cargo.toml` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NEKPxdi0XwGpm-qXN_4:-NE_4eFLAAA6tsA48cri:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8ff53a99182647dc1b1ee6ace449f5c3abaed1f/talpid-openvpn/Cargo.toml#L6)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Please remove this comment and copy the metadata of all other crates. Author, publish, license. And add a descriptive description, so it becomes easier to understand which crate does what and how it relates to the others.
</blockquote></details>

Done.
___
*[`dist-assets/binaries` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELvZpb84WF95mT0BSJ:-NFnlrgLDhX0hL8CESCl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/dist-assets/binaries#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Wrong commit.
</blockquote></details>

Done.
___
*[`talpid-core/src/window.rs` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELu4EqC3uTIlrNg6Vu:-NE_9kua5QkXWZPC-nu6:bbubkbw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/611cdecfb3d146620865b4ea9b376694f49446d1/talpid-core/src/window.rs#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Can we rename the module to `windows`?
</blockquote></details>

Instead I suggest I change the description since this module deals with windows on Windows, for inferring the power state. Or, it could be named `power`. It serves a singular purpose, I think, so the meaning should be encapsulated in the name. 
___
*[`talpid-routing/src/linux.rs` line 64 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELr9fk9o5Df6hl0_qc:-NFnluRn3I-hK4gvFoTI:b-srqlee) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-routing/src/linux.rs#L64)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I wonder if we even need these two rules. Assuming that all tunnel traffic has the mark set, probably not.
</blockquote></details>

Changing routing rules is definitely something I do not want to change here.
___
*[`talpid-tunnel/src/network_interface.rs` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELuyDPC3w4R8xx0GwW:-NE_f_jb-mIqKf434ubU:b-rttraf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-tunnel/src/network_interface.rs#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I'd argue this belongs in `talpid_tunnel::tun_provider::unix`, since we only ever use it there.
</blockquote></details>

I've moved it there. I think originally there was a vain hope that someday an interface like this could be used to abstract networking stuff for all desktop platforms.
___
*[`talpid-windows/src/logging.rs` line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELd5M25QCdUe8I6RmV:-NFnloPw2rA02w7AAkt3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-windows/src/logging.rs#L9)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

All of this logging stuff should be hidden in the Windows firewall module once the winnet refactoring has been merged.
</blockquote></details>

Done.
___
*[`talpid-windows/src/logging.rs` line 38 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELcuXU5Vn08dZmQLRo:-NE_6E0y0mB3DCLH6O-R:bl891fb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-windows/src/logging.rs#L38)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This belongs in `super::string`, if it needs to be public. And we should an enum for `codepage`, but that's pretty out of scope.
</blockquote></details>

It doesn't need to be public at all.
___
*[`talpid-wireguard/src/lib.rs` line 861 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELhVkVAkJ4aKkD0SWB:-NE_6hYi8iCH6OG2h1JA:b5r8g3w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-wireguard/src/lib.rs#L861)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Since this is duplicated: `talpid-linux`? :slightly_smiling_face: 

We could also have a shared `talpid-platform` crate containing `windows` (instead of `talpid-windows`), `linux`, etc.
</blockquote></details>

To be fair, I think it belongs in the routing crate, as


<!-- Sent from Reviewable.io -->

2022-11-02 13:17 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041)* status: 30 of 113 files reviewed, 8 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[`talpid-routing/Cargo.toml` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NFsU1RtAGlXc5QyLmzv:-NFsU1RtAGlXc5QyLmzw:b3whhzh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a689ed95b8a0e2d0e3593a10f2c662acb681a23e/talpid-routing/Cargo.toml#L1)):*
> ```TOML
> [package]
> ```

I believe this crate is not listed in the workspace toml at the top.


<!-- Sent from Reviewable.io -->

2022-11-02 14:48 UTC, dlon requested changes
> Reviewed 18 of 95 files at r1, 3 of 17 files at r2, 1 of 4 files at r3, 33 of 51 files at r4, 32 of 32 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041)* status: all files reviewed, 10 unresolved discussions (waiting on @pinkisemils)

___
*[`talpid-core/src/firewall/.windows.rs.swp` line 0 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NFsbPOv3A30M6GACeSw:-NFsbPOw3BmPzuTqjaHn:b-x8iyly) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a689ed95b8a0e2d0e3593a10f2c662acb681a23e/talpid-core/src/firewall/.windows.rs.swp#L0)):*
Swap file.
___
*[`talpid-core/src/tunnel_state_machine/tunnel.rs` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NFsd89n2x6xbAWK2PoO:-NFsd89n2x6xbAWK2PoP:b-15vvo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a689ed95b8a0e2d0e3593a10f2c662acb681a23e/talpid-core/src/tunnel_state_machine/tunnel.rs#L1)):*
> ```XML
> 
> ```

Should this file be here?
___
*[`talpid-routing/src/windows/routing.rs` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NFseekc7D7XKV5zC-wB:-NFseekc7D7XKV5zC-wC:b33ef6i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a689ed95b8a0e2d0e3593a10f2c662acb681a23e/talpid-routing/src/windows/routing.rs#L1)):*
> ```XML
> 
> ```

Empty file.
___
*[`talpid-core/src/window.rs` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELu4EqC3uTIlrNg6Vu:-NFsaZ8LEXCLmEFqG1Vv:b-cgyx44) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/611cdecfb3d146620865b4ea9b376694f49446d1/talpid-core/src/window.rs#L1)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Instead I suggest I change the description since this module deals with windows on Windows, for inferring the power state. Or, it could be named `power`. It serves a singular purpose, I think, so the meaning should be encapsulated in the name. 
</blockquote></details>

`create_hidden_window` is also used to detect new volumes/disks. Not only for power state changes.
___
*[`talpid-routing/src/lib.rs` line 97 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NEzbnQJDwXaq7K5K0tc:-NEzbnQJDwXaq7K5K0td:bnlcels) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d21d8702a067611bdefd79030d654a40e6cd820f/talpid-routing/src/lib.rs#L97)):*
> ```XML
>             prefix,
>             #[cfg(target_os = "linux")]
>             table_id: u32::from(RT_TABLE_MAIN),
> ```

The default table was previously set to the Mullvad-specific table. Now it's main. Is that not incorrect?
___
*[`talpid-routing/src/unix.rs` line 174 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NEzb_FI36r2uAzuz77c:-NEzb_FJCCFfuYkNy7Pr:b-jddl2u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d21d8702a067611bdefd79030d654a40e6cd820f/talpid-routing/src/unix.rs#L174)):*
> ```XML
>     GetDestinationRoute(
>         IpAddr,
>         Option<u32>,
> ```

`type Fwmark = u32`? Or a docstring, at least.
___
*[`talpid-tunnel/src/tun_provider/unix.rs` line 117 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NFsffCEEiY34_3lw0JG:-NFsffCEEiY34_3lw0JH:b-4gaefc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a689ed95b8a0e2d0e3593a10f2c662acb681a23e/talpid-tunnel/src/tun_provider/unix.rs#L117)):*
> ```XML
> }
> 
> trait WireguardLink: AsRawFd + IntoRawFd {}
> ```

Nit: Can we delete this trait? I don't see it being used anywhere.
___
*[`talpid-tunnel/src/tun_provider/unix.rs` line 126 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NFsfpdqEf_vEl0anLeo:-NFsfpdr6TCk4qdDNARg:blnqmkw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a689ed95b8a0e2d0e3593a10f2c662acb681a23e/talpid-tunnel/src/tun_provider/unix.rs#L126)):*
> ```XML
> }
> 
> /// A tunnel devie
> ```

Nit: device


<!-- Sent from Reviewable.io -->

2022-11-03 12:28 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041)* status: 101 of 113 files reviewed, 7 unresolved discussions (waiting on @dlon and @faern)

___
*[`talpid-routing/Cargo.toml` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NFsU1RtAGlXc5QyLmzv:-NFsrioN9wtoK0-bEdnz:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a689ed95b8a0e2d0e3593a10f2c662acb681a23e/talpid-routing/Cargo.toml#L1)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I believe this crate is not listed in the workspace toml at the top.
</blockquote></details>

Done.
___
*[`talpid-core/src/firewall/.windows.rs.swp` line  at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NFsbPOv3A30M6GACeSw:-NFsrbPb4xBwO3TSVhGH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a689ed95b8a0e2d0e3593a10f2c662acb681a23e/talpid-core/src/firewall/.windows.rs.swp#L)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Swap file.
</blockquote></details>

Done.
___
*[`talpid-core/src/tunnel_state_machine/tunnel.rs` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NFsd89n2x6xbAWK2PoO:-NFsrgb33IFBq_qBLtE4:b-83og3x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a689ed95b8a0e2d0e3593a10f2c662acb681a23e/talpid-core/src/tunnel_state_machine/tunnel.rs#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should this file be here?
</blockquote></details>

Nope.
___
*[`talpid-routing/src/windows/routing.rs` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NFseekc7D7XKV5zC-wB:-NFsrnxBBoEHx2-rMR1L:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a689ed95b8a0e2d0e3593a10f2c662acb681a23e/talpid-routing/src/windows/routing.rs#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Empty file.
</blockquote></details>

Removed.
___
*[`talpid-core/src/window.rs` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELu4EqC3uTIlrNg6Vu:-NFtDqCe9tvxsIWLS4BO:bs10lpe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/611cdecfb3d146620865b4ea9b376694f49446d1/talpid-core/src/window.rs#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`create_hidden_window` is also used to detect new volumes/disks. Not only for power state changes.
</blockquote></details>

Well, if it's only going to contain logic to deal with windows on Windows, should it not be called `window` ?
___
*[`talpid-routing/src/lib.rs` line 97 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NEzbnQJDwXaq7K5K0tc:-NFtDxgxCsV4Bai0mL43:b-sujtoa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d21d8702a067611bdefd79030d654a40e6cd820f/talpid-routing/src/lib.rs#L97)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The default table was previously set to the Mullvad-specific table. Now it's main. Is that not incorrect?
</blockquote></details>

By default, `RT_TABLE_MAIN` should be set, and if a route needs to be added to the mullvad table, it should be set manually. But I have changed it further so that at this layer, the table IDs are somewhat abstracted.
___
*[`talpid-wireguard/src/lib.rs` line 861 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELhVkVAkJ4aKkD0SWB:-NFsulPkBnxzYNFYsdoH:bfkbmxh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-wireguard/src/lib.rs#L861)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

To be fair, I think it belongs in the routing crate, as
</blockquote></details>

Err, to finish the sentence from yesterday, I think if this code was to be consolidated, it should be put in `talpid-routing`. But I don't think we should do that - we can just inline it since it's only used ever used in two call sites.


<!-- Sent from Reviewable.io -->

2022-11-03 13:21 UTC, dlon requested changes
> Reviewed 7 of 7 files at r7, 1 of 3 files at r8, 1 of 2 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041)* status: all files reviewed, 3 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[`talpid-core/src/window.rs` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELu4EqC3uTIlrNg6Vu:-NFxbpXq4c4NhZV9fFGj:bmh52io) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/611cdecfb3d146620865b4ea9b376694f49446d1/talpid-core/src/window.rs#L1)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Well, if it's only going to contain logic to deal with windows on Windows, should it not be called `window` ?
</blockquote></details>

`window` contains logic only for windows on Windows, and not for windows on non-Windows, nor for things other than windows on Windows.

I still think that it's bad to have a Windows-specific `window` module in `lib.rs`, so I'd prefer `windows` here.

But I'll let you decide.
___
*[`talpid-openvpn/src/lib.rs` line 369 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NFxTuUq78cbKxrOpSLj:-NFxTuUq78cbKxrOpSLk:bynbtc7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/988f1f6541f51df6620b10a361f2e8ca8e33e830/talpid-openvpn/src/lib.rs#L369)):*
> ```XML
>     let mut routes = HashSet::new();
>     for network in &["0.0.0.0/0".parse().unwrap(), "::/0".parse().unwrap()] {
>         routes.insert(RequiredRoute::new(*network, tun_node.clone()));
> ```

Are these not added to the main table now? I don't believe they should be, or split tunneling breaks.
___
*[`talpid-routing/src/lib.rs` line 97 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NEzbnQJDwXaq7K5K0tc:-NFxanGV2_U_ShlfE4rp:bcjc0v9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d21d8702a067611bdefd79030d654a40e6cd820f/talpid-routing/src/lib.rs#L97)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

By default, `RT_TABLE_MAIN` should be set, and if a route needs to be added to the mullvad table, it should be set manually. But I have changed it further so that at this layer, the table IDs are somewhat abstracted.
</blockquote></details>

Alright. I pointed out an issue in another comment.
___
*[`talpid-wireguard/src/lib.rs` line 861 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELhVkVAkJ4aKkD0SWB:-NFxU_fwDdHZ42kjQxMu:b-r9sz8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78c49f164f2f7afc6e4b00438fa3e0dc78d73084/talpid-wireguard/src/lib.rs#L861)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Err, to finish the sentence from yesterday, I think if this code was to be consolidated, it should be put in `talpid-routing`. But I don't think we should do that - we can just inline it since it's only used ever used in two call sites.
</blockquote></details>

That's fine.


<!-- Sent from Reviewable.io -->

2022-11-03 15:55 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041)* status: 112 of 113 files reviewed, 3 unresolved discussions (waiting on @dlon and @faern)

___
*[`talpid-openvpn/src/lib.rs` line 369 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NFxTuUq78cbKxrOpSLj:-NFyBmDt1UPa1YAIiEF8:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/988f1f6541f51df6620b10a361f2e8ca8e33e830/talpid-openvpn/src/lib.rs#L369)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Are these not added to the main table now? I don't believe they should be, or split tunneling breaks.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-03 16:07 UTC, dlon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-:-NFyEetGEVRbEqpXlbDj:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @faern and @pinkisemils)



<!-- Sent from Reviewable.io -->

2022-11-03 16:07 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @faern)

___
*[`talpid-core/src/window.rs` line 1 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NELu4EqC3uTIlrNg6Vu:-NFyEclmAcyDrrKteiQw:bwgraf8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/611cdecfb3d146620865b4ea9b376694f49446d1/talpid-core/src/window.rs#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`window` contains logic only for windows on Windows, and not for windows on non-Windows, nor for things other than windows on Windows.

I still think that it's bad to have a Windows-specific `window` module in `lib.rs`, so I'd prefer `windows` here.

But I'll let you decide.
</blockquote></details>

There's precedent for this in that there's also a `resolver` module at the root of `talpid-core`, but it's only ever used on macOS to do wizardry. I think it's fine to have some modules be specific to a platform.


<!-- Sent from Reviewable.io -->

2022-11-04 12:24 UTC, dlon approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2022-11-04 13:19 UTC, Jontified requested changes
> Reviewed 1 of 51 files at r4, 2 of 32 files at r5, 1 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041)* status: all files reviewed, 2 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[`talpid-core/src/tunnel/windows.rs` line 1 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-NG1cLxBA-hXKo9OcwPg:-NG1cLxBA-hXKo9OcwPh:bhjeh37) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0ba71e2c256a9796f940963137980b32d53e5263/talpid-core/src/tunnel/windows.rs#L1)):*
> ```XML
> use crate::windows::{get_ip_interface_entry, set_ip_interface_entry, AddressFamily};
> ```

`talpid-core/src/tunnel/windows.rs` remains as an empty file.


<!-- Sent from Reviewable.io -->

2022-11-07 10:46 UTC, Jontified approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4041#-:-NGGgo4y-F9L1HC6uDGt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2022-11-07 11:42 UTC, merged