Detect always on vpn
mullvad/mullvadvpn-app pull request #4120
Opened 2022-11-03 10:38 UTC by sabercodic

In case of failed to establishing tunnel connection because of lack of VPN permission app will check for 'Always-on VPN' enabled for other apps and show relevant in app notification

2022-11-22 08:00 UTC, albin-mullvad requested changes
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NHTF768Esef6C-np1MP):*
It's generally a good practice to try to still with commit message subjects with a maximum length of 50 chars. I suggest changing to something like: `Add string resources for always-on notification`



_Code quote:_
```
Add string resources for show detecting Always-on VPN for other apps
```
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NHTG1OS3CuCIiRv9D5-):*
I suggest chaning to `Add always-on in-app notification`



_Code quote:_
```
Add inApp notification for other app's always on vpn turned on
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt` line 29 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NHTKVjQ5ZyRxRfW9561:-NHTKVjQ5ZyRxRfW9562:bnryzfo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df54bde2297ea9f25780f34ab93312ca4403dd21/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt#L29)):*
> ```Kotlin
>     }
> 
>     fun Context.getAlwaysOnVpnAppName(): String? {
> ```

This funciton does a bit too much imo. I suggest the following refactoring (pseudo code):

Change `getAlwaysOnVpnAppName` to only do the following:
```
return resolveAlwaysOnVpnPackageName()?.resolveLabel()
```

Change `isAccessToHiddenSettingAllowed` to `resolveAlwaysOnVpnPackageName` and us it to check sdk version and 
```
private fun Context.resolveAlwaysOnVpnPackageName(): String? { 
  return if sdk < 123 
    try { Settings.Secure.getString } catch { log; return null }
  else
    null
}
```

Separate ext fun to resolve label from package name. Might be good to discuss with linus:
```
private fun String.resolveLabelFromPackageName(): String { 
  // packagemanager stuff
}
```



_Code quote:_
```Kotlin
getAlwaysOnVpnAppName
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NHTKH_q9_aWxD-VXLEk:-NHTKH_q9_aWxD-VXLEl:b-y5c5kr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df54bde2297ea9f25780f34ab93312ca4403dd21/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt#L31)):*
> ```Kotlin
>     fun Context.getAlwaysOnVpnAppName(): String? {
>         var currentAlwaysOn: String? = null
>         if (Build.VERSION.SDK_INT < Build.VERSION_CODES.S_V2 || isAccessToHiddenSettingAllowed()) {
> ```

Is it worth implementing this if it doesn't support newer sdk versions? Is there another way to detect this? Perhaps just detect that it's enable for _some_ app rather than the specific app?



_Code quote:_
```Kotlin
Build.VERSION.SDK_INT < Build.VERSION_CODES.S_V2
```


<!-- Sent from Reviewable.io -->

2022-12-15 09:02 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad)

___
*[`-- commits` line 3 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NHTF768Esef6C-np1MP):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

It's generally a good practice to try to still with commit message subjects with a maximum length of 50 chars. I suggest changing to something like: `Add string resources for always-on notification`
</blockquote></details>

Done.
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NHTG1OS3CuCIiRv9D5-):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest chaning to `Add always-on in-app notification`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt` line 29 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NHTKVjQ5ZyRxRfW9561:-NHe1Qfs4Wa5Rt6-peik:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df54bde2297ea9f25780f34ab93312ca4403dd21/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt#L29)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This funciton does a bit too much imo. I suggest the following refactoring (pseudo code):

Change `getAlwaysOnVpnAppName` to only do the following:
```
return resolveAlwaysOnVpnPackageName()?.resolveLabel()
```

Change `isAccessToHiddenSettingAllowed` to `resolveAlwaysOnVpnPackageName` and us it to check sdk version and 
```
private fun Context.resolveAlwaysOnVpnPackageName(): String? { 
  return if sdk < 123 
    try { Settings.Secure.getString } catch { log; return null }
  else
    null
}
```

Separate ext fun to resolve label from package name. Might be good to discuss with linus:
```
private fun String.resolveLabelFromPackageName(): String { 
  // packagemanager stuff
}
```
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NHTKH_q9_aWxD-VXLEk:-NHe1R370mKw-XwLCQyl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df54bde2297ea9f25780f34ab93312ca4403dd21/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt#L31)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is it worth implementing this if it doesn't support newer sdk versions? Is there another way to detect this? Perhaps just detect that it's enable for _some_ app rather than the specific app?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-19 12:52 UTC, albin-mullvad requested changes
> Reviewed 1 of 4 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: all files reviewed, 9 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeMnboDvKLPCOTtGQ_:-NJeMnbp9-357uY6G8bI:b-xzhcmq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L25)):*
> ```Kotlin
>     return resolveAlwaysOnVpnPackageName()?.let { currentAlwaysOnVpn ->
>         var appName = packageManager.getInstalledPackages(0)
>             .filter { it.packageName == currentAlwaysOnVpn }
> ```

Change to `singleOrNull` to simplify this and the if-statement below.



_Code quote:_
```Kotlin
.filter
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 27 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeN8KyDzUg_t8GpyHW:-NJeN8KyDzUg_t8GpyHX:b-2ypyr1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L27)):*
> ```Kotlin
>             .filter { it.packageName == currentAlwaysOnVpn }
>         if (appName.size == 1 && appName[0].packageName != packageName) {
>             appName[0].applicationInfo.loadLabel(packageManager).toString()
> ```

Do we need a fallback for this?



_Code quote:_
```Kotlin
appName[0].applicationInfo.loadLabel(packageManager).toString()
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 33 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeNFzP31_lgflk0ZrH:-NJeNFzP31_lgflk0ZrI:b-1qn7z6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L33)):*
> ```Kotlin
>     } ?: run {
>         null
>     }
> ```

This can be removed.



_Code quote:_
```Kotlin
    } ?: run {
        null
    }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 46 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeP8fTDsZvWNq7_u4j:-NJeP8fTDsZvWNq7_u4k:b-d8ildl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L46)):*
> ```Kotlin
> }
> 
> private fun Context.resolveAlwaysOnVpnPackageName(): String? {
> ```

Will this return an empty string in case no other vpn is set to always-on? Would be good to add a function comment if that's the case.



_Code quote:_
```Kotlin
String?
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/InAppNotificationController.kt` line 53 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeLUQiBdgLiB88WrZ1:-NJeLUQiBdgLiB88WrZ2:b984a4q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/InAppNotificationController.kt#L53)):*
> ```Kotlin
>             }
>         } else {
>             if (!notification.shouldShow) activeNotifications.remove(notification)
> ```

This is redundant to the `shouldShow` check above and should therefore be removed.



_Code quote:_
```Kotlin
if (!notification.shouldShow)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt` line 52 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJePrCX3xmEJOFJdgpq:-NJePrCX3xmEJOFJdgpr:banae9q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt#L52)):*
> ```Kotlin
>                 title = context.getString(R.string.always_on_vpn_error_notification_title)
>                 message = context.getString(R.string.always_on_vpn_error_notification_content, it)
>             } ?: run {
> ```

Didn't we discuss an additional state for the notification? Basically the message presented to the user should be different for the following cases:

1. Always-on _enabled_ for another app. The one implemented here.
2. Always-on _not enabled_ for another app. This should result in a generic error message, like the `run` block below.
3. Always-on _might be enabled_ for another app. This one isn't covered, right?



_Code quote:_
```Kotlin
            context.getAlwaysOnVpnAppName()?.let {
                title = context.getString(R.string.always_on_vpn_error_notification_title)
                message = context.getString(R.string.always_on_vpn_error_notification_content, it)
            } ?: run {
```
___
*[`android/app/src/main/res/values/strings.xml` line 189 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeLwwtBQP6VGvEIchw:-NJeLwwtBQP6VGvEIchx:b-jvcbhq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/res/values/strings.xml#L189)):*
> ```XML
>     <string name="always_on_vpn_error_notification_title">Always-on VPN assigned to other
>     app</string>
>     <string name="always_on_vpn_error_notification_content">Unable to start tunnle connection.
> ```

Change to "tunnel"



_Code quote:_
```XML
tunnle
```


<!-- Sent from Reviewable.io -->

2022-12-21 09:14 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: 2 of 8 files reviewed, 9 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeMnboDvKLPCOTtGQ_:-NJea2jOEpYQQuW2btHM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L25)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Change to `singleOrNull` to simplify this and the if-statement below.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 27 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeN8KyDzUg_t8GpyHW:-NJjY78F8DIGrn8AErF4:bxv1qlj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L27)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Do we need a fallback for this?
</blockquote></details>

this part is for getting app name from PackageManager based on package name 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 33 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeNFzP31_lgflk0ZrH:-NJeaq5N7xjJVCXKkZg3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L33)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This can be removed.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 46 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeP8fTDsZvWNq7_u4j:-NJeb0Q87zGtpMYEYlfF:bu60mxz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L46)):*
> string
no, this one will return package name of the desired app
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt` line 52 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJePrCX3xmEJOFJdgpq:-NJjXzvXDmuHUUpxt4cg:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt#L52)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Didn't we discuss an additional state for the notification? Basically the message presented to the user should be different for the following cases:

1. Always-on _enabled_ for another app. The one implemented here.
2. Always-on _not enabled_ for another app. This should result in a generic error message, like the `run` block below.
3. Always-on _might be enabled_ for another app. This one isn't covered, right?
</blockquote></details>

Done.
___
*[`android/app/src/main/res/values/strings.xml` line 189 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeLwwtBQP6VGvEIchw:-NJem5heD0kfaKZYFGyG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/res/values/strings.xml#L189)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Change to "tunnel"
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/InAppNotificationController.kt` line 53 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeLUQiBdgLiB88WrZ1:-NJebXPI8cuUvfKV5NN6:b-nbwp29) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/InAppNotificationController.kt#L53)):*
> should
this one was result of corrupted rebase, fixed


<!-- Sent from Reviewable.io -->

2022-12-21 09:56 UTC, albin-mullvad requested changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: all files reviewed, 6 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt` line 65 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJo63EV12drdq--oXqF:-NJo63EV12drdq--oXqG:bglqk4l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e27e88d4076ceb27f760627bd70b6ca3f5e807ef/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt#L65)):*
> ```Kotlin
>                     }
>                 }
>             }
> ```

This is too many levels of nesting etc so please have a look at making it more flat.



_Code quote:_
```Kotlin
            is TunnelState.Error -> {
                if (state.errorState.isBlocking) {
                    R.string.blocking_all_connections
                } else {
                    context.getAlwaysOnVpnAppName()?.let {
                        R.string.always_on_vpn_error_notification_title
                    } ?: run {
                        if (state.errorState.cause == ErrorStateCause.VpnPermissionDenied) {
                            R.string.vpn_permission_error_notification_title
                        } else {
                            R.string.critical_error
                        }
                    }
                }
            }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 27 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeN8KyDzUg_t8GpyHW:-NJo41KX4wbPX8HPWfFs:b3qzgry) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L27)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

this part is for getting app name from PackageManager based on package name 
</blockquote></details>

Yes. My question was more about if we need to handle any null/empty string cases etc
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 46 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeP8fTDsZvWNq7_u4j:-NJo4Poj0dslnWF25Kvm:b-k94w5t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L46)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

> string
no, this one will return package name of the desired app
</blockquote></details>

What do you mean with "desired"? The purpose is to resolve the active always-on vpn app, not an arbitrary app, right? If no always-on vpn app is active, the call to `Settings.Secure.getString` returns either an empty string or null?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 22 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJo3X5ECdxEDW4TsIWb:-NJo3X5ECdxEDW4TsIWc:b9tnkve) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e27e88d4076ceb27f760627bd70b6ca3f5e807ef/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L22)):*
> ```Kotlin
> }
> 
> fun Context.getAlwaysOnVpnAppName(): String? {
> ```

Can be made a bit more compact into this:

```
fun Context.getAlwaysOnVpnAppName(): String? {
    return resolveAlwaysOnVpnPackageName()
        ?.let { currentAlwaysOnVpn ->
            packageManager.getInstalledPackages(0)
                .singleOrNull { it.packageName == currentAlwaysOnVpn }
        }?.applicationInfo?.loadLabel(packageManager)?.toString()
}
```



_Code quote:_
```Kotlin
getAlwaysOnVpnAppName
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 24 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJo3oEh-awXG6cK09zI:-NJo3oEiB9XRYTu6YQak:b-seal4c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e27e88d4076ceb27f760627bd70b6ca3f5e807ef/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L24)):*
> ```Kotlin
> fun Context.getAlwaysOnVpnAppName(): String? {
>     return resolveAlwaysOnVpnPackageName()?.let { currentAlwaysOnVpn ->
>         var appName = packageManager.getInstalledPackages(0)
> ```

This one seem to be deprecated.



_Code quote:_
```Kotlin
getInstalledPackages(0)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt` line 52 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJePrCX3xmEJOFJdgpq:-NJo5KLfE_9Tnr_wbqP7:brs74b8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt#L52)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

As mentioned AFK, this code is quite hard to follow. Please see if it's possible to improve readability. Pehaps this `show` function should contain a when-statement rather than nested if-statements?


<!-- Sent from Reviewable.io -->

2022-12-23 13:42 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: 4 of 9 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt` line 65 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJo63EV12drdq--oXqF:-NJyVBXWDD1S70q0QBBg:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e27e88d4076ceb27f760627bd70b6ca3f5e807ef/android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt#L65)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This is too many levels of nesting etc so please have a look at making it more flat.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 27 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeN8KyDzUg_t8GpyHW:-NJt0kxJ9HkhsMVRdier:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L27)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Yes. My question was more about if we need to handle any null/empty string cases etc
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 46 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJeP8fTDsZvWNq7_u4j:-NJt2p-t5ex52WDYCrO2:b-6fnk6z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L46)):*
> other

my purpose from desired app was current Always-on VPN,
in case of no App, result will be null. I added some comments
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 22 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJo3X5ECdxEDW4TsIWb:-NJsq7kN6jB9gw5u3JFM:b49yvtm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e27e88d4076ceb27f760627bd70b6ca3f5e807ef/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L22)):*
> fun Context.getAlwaysOnVpnAppName(): String? {
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

>     return resolveAlwaysOnVpnPackageName()
>         ?.let { currentAlwaysOnVpn ->
>             packageManager.getInstalledPackages(0)
>                 .singleOrNull { it.packageName == currentAlwaysOnVpn }
>         }?.applicationInfo?.loadLabel(packageManager)?.toString()
</details>
> }
in the original function I have one extra condition to check if Always-on VPN is not assigned to our app(for the case of facing non blocking error when mullvad set to Always-on VPN)
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 24 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJo3oEh-awXG6cK09zI:-NJsvTva8pyqMFt7r_kY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e27e88d4076ceb27f760627bd70b6ca3f5e807ef/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L24)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This one seem to be deprecated.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt` line 52 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NJePrCX3xmEJOFJdgpq:-NJyVAu37eO41953Y-tU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f5a09455aa593e157088d3629c59082069aa9e9f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt#L52)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As mentioned AFK, this code is quite hard to follow. Please see if it's possible to improve readability. Pehaps this `show` function should contain a when-statement rather than nested if-statements?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-29 12:34 UTC, albin-mullvad requested changes
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: all files reviewed, 7 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 24 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSp9t862aLgSEMySPN:-NKSp9t862aLgSEMySPO:bqfvs3g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L24)):*
> ```Kotlin
>                 cause.addresses
>                     .map { address -> address.addressString() }
>                     .joinToString()
> ```

I suggest moving this outside the constructor call as it's a bit hard to follow atm.



_Code quote:_
```Kotlin
                cause.addresses
                    .map { address -> address.addressString() }
                    .joinToString()
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 38 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSp0Xy9d6QC-LoIeom:-NKSp0Xy9d6QC-LoIeon:b-7hhxcq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L38)):*
> ```Kotlin
>                 R.string.vpn_permission_error_notification_title,
>                 R.string.vpn_permission_error_notification_message
>             )
> ```

This is a bit difficult to read. I suggest a variable (val)  and if-statement instead.



_Code quote:_
```Kotlin
            context.getAlwaysOnVpnAppName()
                ?.let {
                    ErrorNotificationMessage(
                        R.string.always_on_vpn_error_notification_title,
                        R.string.always_on_vpn_error_notification_content,
                        it
                    )
                } ?: ErrorNotificationMessage(
                R.string.vpn_permission_error_notification_title,
                R.string.vpn_permission_error_notification_message
            )
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 47 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSrbB09g66GlsboIRN:-NKSrbB09g66GlsboIRO:b-60lps) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L47)):*
> ```Kotlin
> }
> 
> data class ErrorNotificationMessage(
> ```

Move to separate file.



_Code quote:_
```Kotlin
ErrorNotificationMessage
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 65 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSoa3FBYHIJIkukmpn:-NKSoa3FBYHIJIkukmpo:b-gmwb2x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L65)):*
> ```Kotlin
> }
> 
> private fun blockingErrorMessageId(cause: ErrorStateCause): Int {
> ```

Any reason to not use this as an extension function?



_Code quote:_
```Kotlin
fun blockingErrorMessageId(cause: ErrorStateCause):
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 90 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSojC0BB1sKW-0nNgt:-NKSojC0BB1sKW-0nNgu:b-vxr1x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L90)):*
> ```Kotlin
> }
> 
> private fun notBlockingErrorMessageId(cause: ErrorStateCause?): Int {
> ```

I suggest chaning this to an extension function and to handle the null case outside the function.



_Code quote:_
```Kotlin
notBlockingErrorMessageId(cause: ErrorStateCause?)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt` line 39 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSqAUk-WrDeYJiqi54:-NKSqAUk-WrDeYJiqi55:b-48hlmb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt#L39)):*
> ```Kotlin
>     }
> 
>     fun PackageManager.getInstalledPackagesCompat(flags: Int = 0): List<PackageInfo> =
> ```

I suggest removing this part of the function name



_Code quote:_
```Kotlin
Compat
```
___
*[`android/app/src/main/res/values/strings.xml` line 195 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSnl6k9q23Pupdenjh:-NKSnl6k9q23Pupdenji:b-1doult) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/res/values/strings.xml#L195)):*
> ```XML
>     <string name="vpn_permission_error_notification_title">VPN permission error</string>
>     <string name="vpn_permission_error_notification_message">Always-on might be enabled for another
>     app</string>
> ```

As previously discussed, these need to be aligned.



_Code quote:_
```XML
    <string name="always_on_vpn_error_notification_title">Always-on VPN assigned to other
    app</string>
    <string name="always_on_vpn_error_notification_content">
<![CDATA[Unable to start tunnel connection. Please disable Always-on VPN for <b>%s</b> before
    using Mullvad VPN.]]>
    </string>
    <string name="vpn_permission_error_notification_title">VPN permission error</string>
    <string name="vpn_permission_error_notification_message">Always-on might be enabled for another
    app</string>
```


<!-- Sent from Reviewable.io -->

2022-12-30 14:15 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: all files reviewed, 7 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 24 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSp9t862aLgSEMySPN:-NKYIAOT46omvi2gQsHH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L24)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest moving this outside the constructor call as it's a bit hard to follow atm.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 38 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSp0Xy9d6QC-LoIeom:-NKYL2mr7uU88ZfmszMG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L38)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This is a bit difficult to read. I suggest a variable (val)  and if-statement instead.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 47 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSrbB09g66GlsboIRN:-NKYLT183AOnFSd_0TfZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L47)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Move to separate file.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 65 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSoa3FBYHIJIkukmpn:-NKYMMKn7BBZH325UYqz:bjwxppv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L65)):*
> blockingErrorMessageId
no, functions moved to original class
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 90 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSojC0BB1sKW-0nNgt:-NKYMdgf6sZWsB7WRWgn:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L90)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest chaning this to an extension function and to handle the null case outside the function.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt` line 39 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSqAUk-WrDeYJiqi54:-NKYNT_YEks_zebNi7W3:b-ywex05) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt#L39)):*
> Compat
"getInstalledPackages" is name of the deprecated function, function changed into getInstalledPackagesList
___
*[`android/app/src/main/res/values/strings.xml` line 195 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSnl6k9q23Pupdenjh:-NKYMy6wBLIsJ7BT_Rvq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/res/values/strings.xml#L195)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As previously discussed, these need to be aligned.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-02 08:49 UTC, albin-mullvad requested changes
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: all files reviewed, 11 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 65 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSoa3FBYHIJIkukmpn:-NKlczZKCw9PYlqTqOjt:b-o8feb1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L65)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

> blockingErrorMessageId
no, functions moved to original class
</blockquote></details>

I don't agree with that. See my comments in the base class.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 90 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSojC0BB1sKW-0nNgt:-NKle9f556vNO2VpNbAA:b-v2gzgb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L90)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not really done. See my later comment regarding base class function vs extension function.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 14 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKlZykSDNTWZBI8TnVj:-NKlZykSDNTWZBI8TnVk:bm24map) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L14)):*
> ```Kotlin
>         isBlocking -> ErrorNotificationMessage(
>             R.string.blocking_all_connections,
>             this.cause.blockingErrorMessageId()
> ```

Skip `this` unless needed



_Code quote:_
```Kotlin
this.
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 19 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKl_6pRDBTfGuhvShJf:-NKl_6pRDBTfGuhvShJg:bm24map) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L19)):*
> ```Kotlin
>             ErrorNotificationMessage(
>                 R.string.blocking_all_connections,
>                 this.cause.blockingErrorMessageId(),
> ```

Skip `this` unless needed



_Code quote:_
```Kotlin
this.
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 28 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKlbMO86mrTreCJcjkA:-NKlbMO86mrTreCJcjkB:bm24map) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L28)):*
> ```Kotlin
>         else -> ErrorNotificationMessage(
>             R.string.critical_error,
>             this.cause.notBlockingErrorMessageId()
> ```

Skip `this` unless needed



_Code quote:_
```Kotlin
this.
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 33 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKlc9pIEcdZaAkcIMAQ:-NKlc9pIEcdZaAkcIMAR:bllv3is) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L33)):*
> ```Kotlin
> }
> 
> private fun resolveErrorNotificationMessage(alwaysOnVPN: String?): ErrorNotificationMessage {
> ```

Change to `resolveAlwaysOnVpnErrorNotificationMessage` as it's specific to the always-on vpn case



_Code quote:_
```Kotlin
resolveErrorNotificationMessage
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 46 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKlaGM_6xUA1uI1UacQ:-NKlaGM_6xUA1uI1UacR:b-aslhc7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L46)):*
> ```Kotlin
>         },
>         alwaysOnVPN
>     )
> ```

This is a bit hard to read. I suggest something like this instead:

```
return if (alwaysOnVpn != null) {
  ErrorNotificationMessage(...)
} else {
  ErrorNotificationMessage(...)
}
```



_Code quote:_
```Kotlin
    return ErrorNotificationMessage(
        if (alwaysOnVPN != null) {
            R.string.always_on_vpn_error_notification_title








        } else {
            R.string.vpn_permission_error_notification_title
        },
        if (alwaysOnVPN != null) {
            R.string.always_on_vpn_error_notification_content
        } else {
            R.string.vpn_permission_error_notification_message
        },
        alwaysOnVPN
    )
```
___
*[`android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt` line 42 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKle0EyD1dzTLIZRvLG:-NKle0EyD1dzTLIZRvLH:b4l5uki) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt#L42)):*
> ```Kotlin
>     object VpnPermissionDenied : ErrorStateCause()
> 
>     fun blockingErrorMessageId(): Int {
> ```

This function doesn not belong in this class as this functionality is UI specific (mapping) and might be broken if it's used in a place where the resources aren't available. I suggest moving to an extension function.



_Code quote:_
```Kotlin
blockingErrorMessageId
```
___
*[`android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt` line 63 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKlbksd6WGL_j4e_V17:-NKlbksd6WGL_j4e_V18:b-4z4zml) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt#L63)):*
> ```Kotlin
>                 }
>             }
>             is VpnPermissionDenied -> R.string.vpn_permission_denied_error
> ```

Is this valid? Shouln't this VpnPermissionDenied be either "blocking" or "notBlocking"?



_Code quote:_
```Kotlin
is VpnPermissionDenied -> R.string.vpn_permission_denied_error
```
___
*[`android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt` line 67 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKlaaIl5tcuL_jUOi-V:-NKlaaIl5tcuL_jUOi-W:btn9zp6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt#L67)):*
> ```Kotlin
>     }
> 
>     fun notBlockingErrorMessageId(): Int {
> ```

Not introduced in this PR, but I suggest changing to `nonBlocking...` as it's more gramatically correct.



_Code quote:_
```Kotlin
not
```
___
*[`android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt` line 67 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKldA_3-Kkd-xq9OxDP:-NKldA_3-Kkd-xq9OxDQ:b4l5uki) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt#L67)):*
> ```Kotlin
>     }
> 
>     fun notBlockingErrorMessageId(): Int {
> ```

This function doesn not belong in this class as this functionality is UI specific (mapping) and might be broken if it's used in a place where the resources aren't available. I suggest moving to an extension function.



_Code quote:_
```Kotlin
fun notBlockingErrorMessageId(): Int {
```


<!-- Sent from Reviewable.io -->

2023-01-02 09:54 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: all files reviewed, 11 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 65 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSoa3FBYHIJIkukmpn:-NKlmvE4DsDkKyfrw80U:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L65)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I don't agree with that. See my comments in the base class.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 90 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKSojC0BB1sKW-0nNgt:-NKln9JG7M7CiG7ClIP_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ea406f21a5cf29985b44b3f484d6a116a4ae23a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L90)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Not really done. See my later comment regarding base class function vs extension function.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 14 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKlZykSDNTWZBI8TnVj:-NKlijUK0G4LYhOF4VoX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L14)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Skip `this` unless needed
</blockquote></details>

Done.



_Code quote:_
```Kotlin
blockingErrorMessageId
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 19 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKl_6pRDBTfGuhvShJf:-NKlik-S5VNdppYexCx1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L19)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Skip `this` unless needed
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 28 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKlbMO86mrTreCJcjkA:-NKlikbS1eHnC6CAuWBh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L28)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Skip `this` unless needed
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 33 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKlc9pIEcdZaAkcIMAQ:-NKljDHX3pLzQnemAu9R:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L33)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Change to `resolveAlwaysOnVpnErrorNotificationMessage` as it's specific to the always-on vpn case
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 46 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKlaGM_6xUA1uI1UacQ:-NKlpBmi0uur7dpa-8-O:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L46)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This is a bit hard to read. I suggest something like this instead:

```
return if (alwaysOnVpn != null) {
  ErrorNotificationMessage(...)
} else {
  ErrorNotificationMessage(...)
}
```
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt` line 42 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKle0EyD1dzTLIZRvLG:-NKlpKFb88e4UxWO9Joo:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt#L42)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This function doesn not belong in this class as this functionality is UI specific (mapping) and might be broken if it's used in a place where the resources aren't available. I suggest moving to an extension function.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt` line 63 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKlbksd6WGL_j4e_V17:-NKltWEQ84rRqYUAvXHN:bpv07th) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt#L63)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this valid? Shouln't this VpnPermissionDenied be either "blocking" or "notBlocking"?
</blockquote></details>

keep the logic same as before as we discuss on slack.
___
*[`android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt` line 67 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKlaaIl5tcuL_jUOi-V:-NKltWzI9Si51LMtYhd_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt#L67)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Not introduced in this PR, but I suggest changing to `nonBlocking...` as it's more gramatically correct.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt` line 67 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKldA_3-Kkd-xq9OxDP:-NKltkX79_11_V9xn1en:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eebd74054338ab62e8be0ea6a6d19f152fb0cc53/android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt#L67)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This function doesn not belong in this class as this functionality is UI specific (mapping) and might be broken if it's used in a place where the resources aren't available. I suggest moving to an extension function.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-02 14:12 UTC, albin-mullvad requested changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: all files reviewed, 2 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateCauseExtension.kt` line 28 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKm07TD0xmLqdNUf9yc:-NKm07TE1Mutma1aRyVu:b-nax69d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5129185fe616b53fb0291d633e65fb4fa68fdcfd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateCauseExtension.kt#L28)):*
> ```Kotlin
>             }
>         }
>         is ErrorStateCause.VpnPermissionDenied -> R.string.vpn_permission_denied_error
> ```

As mentioned in another comment, can this ever occur? If we get this error we can't block traffic, right? I suggest fixing/removing it in a separate commit (same PR).



_Code quote:_
```Kotlin
is ErrorStateCause.VpnPermissionDenied
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 34 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKmoOFc35boNENlkw6M:-NKmoOFc35boNENlkw6N:b-pzfj6i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5129185fe616b53fb0291d633e65fb4fa68fdcfd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L34)):*
> ```Kotlin
> 
> private fun resolveAlwaysOnVpnErrorNotificationMessage(
>     alwaysOnVPN: String?
> ```

Change to: `alwaysOnVpnAppName`



_Code quote:_
```Kotlin
alwaysOnVPN
```


<!-- Sent from Reviewable.io -->

2023-01-03 08:36 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateCauseExtension.kt` line 28 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKm07TD0xmLqdNUf9yc:-NKqlDAE0JwN5hi4_PTx:b7zhyok) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5129185fe616b53fb0291d633e65fb4fa68fdcfd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateCauseExtension.kt#L28)):*
> right
you are right but we get this error as response from Daemon service and I afraid to remove it from here
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 34 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKmoOFc35boNENlkw6M:-NKmtErsB4-Mn9hwUFIq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5129185fe616b53fb0291d633e65fb4fa68fdcfd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L34)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Change to: `alwaysOnVpnAppName`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-03 10:25 UTC, albin-mullvad requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: all files reviewed, 4 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 5 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKr585oDfR7OHQkLWb7):*
We usually refer to this as "update translations", so i suggest the following message:

> Also update translations.



_Code quote:_
```
execute string resources script
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateCauseExtension.kt` line 28 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKm07TD0xmLqdNUf9yc:-NKqnrY298Ct5fFFAggK:bz6qpkb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5129185fe616b53fb0291d633e65fb4fa68fdcfd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateCauseExtension.kt#L28)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

> right
you are right but we get this error as response from Daemon service and I afraid to remove it from here
</blockquote></details>

Are there any reason to not merge `blockingErrorMessageId()` with `nonBlockingErrorMessageId()` as they are both used for the message and not the title?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 15 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKr5o3XBcwDGAK6nl3R:-NKr5o3XBcwDGAK6nl3S:b-phnwsj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e0a49ead70162027499c4753ce9aa40a980dec8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L15)):*
> ```Kotlin
>             R.string.blocking_all_connections,
>             cause.blockingErrorMessageId()
>         )
> ```

Shouldn't this further down in this when-statement because otherwise the case of `InvalidDnsServers` would not show ever



_Code quote:_
```Kotlin
        isBlocking -> ErrorNotificationMessage(
            R.string.blocking_all_connections,
            cause.blockingErrorMessageId()
        )
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 45 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKr4uCA6h0ZCHGN10uO:-NKr4uCA6h0ZCHGN10uP:b-v2w1dn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e0a49ead70162027499c4753ce9aa40a980dec8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L45)):*
> ```Kotlin
>             R.string.vpn_permission_error_notification_title,
>             R.string.vpn_permission_error_notification_message,
>             alwaysOnVpnAppName
> ```

This should be moved up to the other message, right?



_Code quote:_
```Kotlin
alwaysOnVpnAppName
```


<!-- Sent from Reviewable.io -->

2023-01-03 12:19 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: all files reviewed, 4 unresolved discussions (waiting on @albin-mullvad)

___
*[`-- commits` line 5 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKr585oDfR7OHQkLWb7):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We usually refer to this as "update translations", so i suggest the following message:

> Also update translations.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateCauseExtension.kt` line 28 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKm07TD0xmLqdNUf9yc:-NKrGrcw7vOIbV0vdnFT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5129185fe616b53fb0291d633e65fb4fa68fdcfd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateCauseExtension.kt#L28)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Are there any reason to not merge `blockingErrorMessageId()` with `nonBlockingErrorMessageId()` as they are both used for the message and not the title?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 15 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKr5o3XBcwDGAK6nl3R:-NKrVnPCAC9U0thj1Za9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e0a49ead70162027499c4753ce9aa40a980dec8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L15)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Shouldn't this further down in this when-statement because otherwise the case of `InvalidDnsServers` would not show ever
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt` line 45 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKr4uCA6h0ZCHGN10uO:-NKrW0B0-l7ZGkHiA5kH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e0a49ead70162027499c4753ce9aa40a980dec8/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt#L45)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This should be moved up to the other message, right?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-03 12:31 UTC, albin-mullvad requested changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`-- commits` line 5 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKr585oDfR7OHQkLWb7):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I would say that you can skip/remove that part of the commit message and just keep the commit message subject


<!-- Sent from Reviewable.io -->

2023-01-03 12:54 UTC, albin-mullvad reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-03 12:58 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt` line 46 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKrhCZ44paGE0JTRdqa:-NKrhCZ44paGE0JTRdqb:b-9xe9kr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5621d022cf752cd114d79765f7c32a5576bb201f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt#L46)):*
> ```Kotlin
>     }
> 
>     private fun showBlocking() {
> ```

I believe this function should set the message to `null`as well to match the previous behavior.



_Code quote:_
```Kotlin
showBlocking
```


<!-- Sent from Reviewable.io -->

2023-01-03 13:00 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt` line 46 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKrhCZ44paGE0JTRdqa:-NKrhgyA9oDGmmDvCBTE:bhouxgd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5621d022cf752cd114d79765f7c32a5576bb201f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt#L46)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe this function should set the message to `null`as well to match the previous behavior.
</blockquote></details>

Perhaps also change the function name to something like the following to distinguish from the blocking error messages: `showGenericBlockingMessage`


<!-- Sent from Reviewable.io -->

2023-01-03 13:20 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt` line 46 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-NKrhCZ44paGE0JTRdqa:-NKrmbGi0S3lLxq1vlak:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5621d022cf752cd114d79765f7c32a5576bb201f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt#L46)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Perhaps also change the function name to something like the following to distinguish from the blocking error messages: `showGenericBlockingMessage`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-03 13:34 UTC, albin-mullvad approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-01-03 16:53 UTC, merged

2023-01-10 10:06 UTC, sabercodic reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120#-:-NLQ8Lmn7fOTHTIBoLFi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->