Add version to tunnel settings and device state
mullvad/mullvadvpn-app pull request #4144
Opened 2022-11-14 13:46 UTC by sajacl

- Introduced :
`Versioned` struct,
`Versions` enum,
`MigrateSettingsOperation.VersioningError` error enum.

- Adding functionality to wrap saved data in `Versioned` in Migrate settings operation:

1. Migrate legacy settings, add them with version and remove them.

2. If we don't have legacy settings, then read `TunnelSettings` version from keychain.
  2.1 If version is the same as current (expected), then no migration is needed.
  2.2 If version is lesser, finish operation with error.
  2.3 If couldn't read version from keychain, but `TunnelSettings` is contained in a keychain, wrap it into Versioned<TunnelSettings> and save it.
  
3. Read version of `DeviceState`
  2.1 If version is the same as current (expected), then no migration is needed.
  2.2 If version is lesser, finish operation with error.
  3.3 If couldn't read version from keychain, but `DeviceState` is stored in keychain, wrap it into Versioned<StoredDeviceState> and save it.

2022-11-15 06:37 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @sajacl)

___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 757 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NGu-2eo-3Valm2Sg5Qv:-NGu-2eo-3Valm2Sg5Qw:bwepv83) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d42e69da762f13226b9d5a20da9a61c3c426d976/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L757)):*
> ```Swift
>         if persist {
>             do {
>                 try SettingsManager.writeSettings(
> ```

This is sub-optimal that `TunnelManager` has to be aware of schema version. Consumer should always read and write the latest schema which is at the moment `TunnelSettingsV2`.


<!-- Sent from Reviewable.io -->

2022-11-15 07:25 UTC, pronebird requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 77 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NGu4BGcAmO-mspoOjja:-NGu4BGcAmO-mspoOjjb:b-2jozz2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d42e69da762f13226b9d5a20da9a61c3c426d976/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L77)):*
> ```Swift
>     // MARK: - Settings
> 
>     private static func readVersionedSettings() throws -> VersionedTunnelSettings {
> ```

Same here, four functions that do the same thing. That has to be improved.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NGu3jTI4qfWQIt7Ulnl:-NGu3jTI4qfWQIt7Ulnm:b-3klj9c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d42e69da762f13226b9d5a20da9a61c3c426d976/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L113)):*
> ```Swift
>     // MARK: - Device state
> 
>     private static func readVersionedDeviceState() throws -> VersionedDeviceState {
> ```

These are four functions that do the same thing. That has to be consolidated and most of it related to versioning hidden away. 


<!-- Sent from Reviewable.io -->

2022-11-15 07:35 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @sajacl)

___
*[`ios/Shared/ApplicationConfiguration.swift` line 72 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NGuBbKCB9yDHtxNPdxk:-NGuBbKCB9yDHtxNPdxl:b-slkyw6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d42e69da762f13226b9d5a20da9a61c3c426d976/ios/Shared/ApplicationConfiguration.swift#L72)):*
> ```Swift
>     static let addressCacheUpdateTaskIdentifier = "net.mullvad.MullvadVPN.AddressCacheUpdate"
> 
>     static let settingsCurrentVersion: Versions = .two
> ```

App config should not contain schema versions. This was discussed before. This information belongs in settings manager.


<!-- Sent from Reviewable.io -->

2022-11-15 07:35 UTC, pronebird reviewed
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @sajacl)



<!-- Sent from Reviewable.io -->

2022-11-15 07:36 UTC, pronebird reviewed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 4 unresolved discussions (waiting on @sajacl)



<!-- Sent from Reviewable.io -->

2022-11-15 08:51 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 5 unresolved discussions (waiting on @sajacl)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NGuF8wxCzskS8r33Enr:-NGuF8wxCzskS8r33Ens:bggob7d) (no related file):*
First of all let's start with schema versioning, we have two distinct versions:

- Version 1 - legacy settings stored differently in a keychain and later migrated using `readLegacySettings` and `deleteLegacySettings`. Most recently converted to `TunnelSettingsV2` but unversioned.
- Version 2 - new format of settings that stored tunnel settings and device state in separate Keychain entries. This can be witnessed as being stored unversioned, so during the migration we should only add version field to it.

So let's express that with a simple `enum` that we can call a `SchemaVersion`:

```swift
/// Settings and device state schema versions.
enum SchemaVersion: Int {
    /// Legacy settings format, stored as `TunnelSettingsV1`.
    case v1 = 1

    /// New settings format, stored as `TunnelSettingsV2`.
    case v2 = 2

    /// Current schema version.
    static let current = SchemaVersion.v2
}
```

Note that `SchemaVersion.current` always tells us the currently used version of settings which can later be used to determine whether settings we have are older or newer than what current version of the app supports.

For the most part, once the app is fully initialized, consumers of `SettingsManager` should not care about versioning, so the methods to read and write settings or device state should be transparent and use the latest settings struct, i.e:

```swift
func readSettings() throws -> TunnelSettingsV2
func writeSettings(_ newSettings: TunnelSettingsV2) throws

// and so on
```

The migration part is only done during application initialization and so we could move methods specific to manipulating raw settings versioned or unversioned into a separate entity, let's call it `MigrationManager`. 

The role of this little struct could be to glue together the logic behind migration, such as we do networking when converting settings from version 1 (`v1`) to version 2 (`v2`), isolate low level functions for working with settings storage and take some load off `SettingsManager`. For example:

```swift
private struct VersionHeader: Codable {
    var version: Int
}

struct Payload<T: Codable>: Codable {
    var data: T
}

struct VersionedPayload<T: Codable>: Codable {
    var version: Int
    var data: T
}

struct MigrationManager {
    private let item: Item
    private var data: Data

    fileprivate init(item: Item, data: Data) {
        self.item = item
        self.data = data
    }

    /// Returns settings version if found inside the stored data.
    func parseVersion() -> Int? {
        let header = try? JSONDecoder().decode(VersionHeader.self, from: data)

        return header?.version
    }

    /// Returns payload type holding the given type.
    func parsePayload<T: Codable>(as type: T.Type) throws -> Payload<T> {
        return try JSONDecoder().decode(Payload<T>.self, from: data)
    }

    /// Returns unversioned payload parsed as the given type.
    func parseUnversionedPayload<T: Codable>(as type: T.Type) throws -> T {
        return try JSONDecoder().decode(T.self, from: data)
    }

    /// Persist versioned payload to the keychain store.
    mutating func store<T: Codable>(versionedPayload: VersionedPayload<T>) throws {
        let data = try JSONEncoder().encode(versionedPayload)

        try SettingsManager.addOrUpdateItem(item, data: data)

        self.data = data
    }
}
```

Then we could add methods on `SettingsManager` to initialize `MigrationManager` when migration is needed, otherwise return `nil`. These methods could read the `version` field first to determine if stored data is out of date. For instance:

```swift
static func tryMigrateSettings() throws -> MigrationManager? {
    return try tryMigrate(item: .settings)
}

static func tryMigrateDeviceState() throws -> MigrationManager? {
    return try tryMigrate(item: .deviceState)
}

private static func tryMigrate(item: Item) throws -> MigrationManager? {
    do {
        let data = try readItemData(item)
        let header = try? JSONDecoder().decode(VersionHeader.self, from: data)

        if header?.version == SchemaVersion.current.rawValue {
            return nil
        } else {
            return MigrationManager(item: item, data: data)
        }
    } catch .itemNotFound as KeychainError {
        return nil
    } catch {
        throw error
    }
}
```

Also perhaps `SettingsManager.readSettings()` could read version and then throw an error if it does not match the current version before deserializing the `data`.

___


<!-- Sent from Reviewable.io -->

2022-11-15 08:58 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 6 unresolved discussions (waiting on @sajacl)

___
*[`ios/Shared/ApplicationConfiguration.swift` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NGuVWZP9w3Wk_TNaq4s:-NGuVWZP9w3Wk_TNaq4t:b-nkvn1i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d42e69da762f13226b9d5a20da9a61c3c426d976/ios/Shared/ApplicationConfiguration.swift#L73)):*
> ```Swift
> 
>     static let settingsCurrentVersion: Versions = .two
>     static let deviceStateCurrentVersion: Versions = .one
> ```

Ideally it would be great to align versions off settings and device state for simplicity.


<!-- Sent from Reviewable.io -->

2022-11-17 09:11 UTC, pronebird requested changes
> Reviewed 3 of 6 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 2 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NH3qhbfASAnqREGXEqt:-NH3qhbfASAnqREGXEqu:bhsyrds) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d51d8666684a9b04fdf0683178b1961115b688d6/ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift#L25)):*
> ```Swift
> 
>     /// Current schema version.
>     static let current = SchemaVersion.v1
> ```

Current is `v2`.


<!-- Sent from Reviewable.io -->

2022-11-17 09:22 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 2 unresolved discussions (waiting on @sajacl)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NH3qpt-587gGlF36KDf:-NH3qpt-587gGlF36KDg:bse4az1) (no related file):*
OK this implementation looks simple. Now, I think we could go ahead and explore the following opportunities:

1. Progressive/incremental migration where each migration is encapsulated within a certain class, I'd imagine we could establish a common protocol for migrations and then implement a migration class for `v1` to `v2`.

In the future, we'll keep adding them, i.e `v2` to `v3` etc.. This should help to avoid the bloat in `MigrateSettingsOperation` and make migration logic much simpler and also testable.

Obviously we have edge cases such as legacy settings are stored differently and that `TunnelSettingsV2` can be stored unversioned but I think `SettingsManager` could handle some of them and then the rest can be covered with abstraction for settings store reader/writer.

```swift
protocol MigrationProtocol {
  func migrate(with readerWriter: StoreReaderWriterProtocol, completion: (Error?) -> Void)
}
```

2. Note that desktop app stores `settings_version` only in `/etc/mullvad-vpn/settings.json` so perhaps we could avoid versioning device state, and simply version tunnel settings only and then migrate the entire store in one go.

___


<!-- Sent from Reviewable.io -->

2022-11-22 10:02 UTC, pronebird requested changes
> Reviewed 2 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 3 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 404 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHTmU1C8eeED7L5h61e:-NHTmU1DCsFUv0AfTIMT:bauisi6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7edcedfb4abb45e20d200f8e604e998912b04f2/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L404)):*
> ```Swift
> }
> 
> // MARK: - Keychain Facade
> ```

Easier to review if these classes were put in separate files.


<!-- Sent from Reviewable.io -->

2022-11-22 10:06 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 4 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 498 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHTmxlx4k6ne7xWPNCI:-NHTmxlx4k6ne7xWPNCJ:br57men) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7edcedfb4abb45e20d200f8e604e998912b04f2/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L498)):*
> ```Swift
> }
> 
> struct SettingsStorageMiddleware {
> ```

This looks like a god object. It can parse generic data, versioned data, unversioned data, it also provides individual methods to parse `TunnelSettingsV2` and `DeviceState`, it also checks if version is unsupported. 


<!-- Sent from Reviewable.io -->

2022-11-22 10:07 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 5 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/SettingsManager/MigrationManager/Migration.swift` line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHTnVMtCVwXvpb5VclL:-NHTnVMtCVwXvpb5VclM:bqy3lnv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7edcedfb4abb45e20d200f8e604e998912b04f2/ios/MullvadVPN/SettingsManager/MigrationManager/Migration.swift#L13)):*
> ```Swift
> protocol Migration {
>     func migrate(
>         with middleware: SettingsStorageMiddleware,
> ```

It really feels like the only requirement for migration should be `SettingsStore` itself. Versioning can be slapped on top as a simple serializer around version data.


<!-- Sent from Reviewable.io -->

2022-11-22 15:36 UTC, pronebird requested changes
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 2 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 1712 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHUyWGE0msYsJs9VwUl:-NHUyWGE0msYsJs9VwUm:b5uml7q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0982ada8abf41b0003b25d04f4bcb4931050af80/ios/MullvadVPN.xcodeproj/project.pbxproj#L1712)):*
> ```
> 			packageProductDependencies = (
> 				583E1E2B2848E1A1004838B3 /* WireGuardKitTypes */,
> 				06410E01292D04AD00AFC18C /* Logging */,
> ```

Since we dropped tests for now, maybe we don't need to add swift-log to MullvadVPNTests


<!-- Sent from Reviewable.io -->

2022-11-22 15:53 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 4 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/SettingsManager/SettingsParser.swift` line 39 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHV0Qkw1jBvMqpkhvVA:-NHV0Qkx8BV5Reh3SCBz:b-nn6kbq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0982ada8abf41b0003b25d04f4bcb4931050af80/ios/MullvadVPN/SettingsManager/SettingsParser.swift#L39)):*
> ```Swift
>     }
> 
>     func producePayload<T: Encodable>(_ payload: VersionedPayload<T>) throws -> Data {
> ```

Just came to my mind that since both `producePayload()` and `produceUnversionedPayload()` are identical, we could then rewrite them as:

```
func producePayload<T: Codable>(_ payload: T, version: Int) throws -> Data {
    return try encoder.encode(VersionedPayload(version: version, data: payload))
}

func produceUnversionedPayload<T: Codable>(_ payload: T) throws -> Data {
    return try encoder.encode(payload)
}
```

and this would allow us to mark `VersionedPayload,` `Payload`, and `VersionHeader` as private structs and make it fully opaque for consumer how versioning works.
___
*[`ios/MullvadVPN/SettingsManager/SettingsParser.swift` line 62 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHUzNXF5lsDn1GmpW29:-NHUzNXG2uJkjKz6nfB9:bpn8ggg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0982ada8abf41b0003b25d04f4bcb4931050af80/ios/MullvadVPN/SettingsManager/SettingsParser.swift#L62)):*
Perhaps this has to be changed to reflect the actual change, i.e:

> Returns data from versioned payload parsed as the given type.


<!-- Sent from Reviewable.io -->

2022-11-23 07:02 UTC, pronebird requested changes
> Reviewed 4 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: 12 of 13 files reviewed, 19 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 115 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYHWTf5BqF1gL29LtH:-NHYHWTf5BqF1gL29LtI:b-57xu8w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/AppDelegate.swift#L115)):*
> ```Swift
>         let setupTunnelManagerOperation =
>             AsyncBlockOperation(dispatchQueue: .main) { operation in
>                 SettingsManager.migrateStore(with: self.proxyFactory) { error in
> ```

This error is unhandled, can we do `precondition(error == nil)` for now and then we can handle showing error in the UI at some point later
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 102 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYBveY5iyLkGn5r4No:-NHYBveY5iyLkGn5r4Np:bj017z6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L102)):*
> ```Swift
>         completion: @escaping (Error?) -> Void
>     ) {
>         guard let settingsData = try? store.read(key: .settings)
> ```

This check will prevent the app from migrating from legacy settings to `v2`.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 104 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYAcHY9BUvg-hmN1zg:-NHYAcHY9BUvg-hmN1zh:bc321pz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L104)):*
> ```Swift
>         guard let settingsData = try? store.read(key: .settings)
>         else {
>             // Return new/not logged in user immediately.
> ```

This comment makes no sense. It says we return "new/not logged in user".
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 109 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYB9qyA6u5aQY_JlD0:-NHYB9qyA6u5aQY_JlD1:b-6ckhkq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L109)):*
> ```Swift
>         }
> 
>         // Check versions.
> ```

This comment seems redundant.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 124 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYCDk24EzxzVZmz0WM:-NHYCDk3EH4U4LY_13un:b-921087) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L124)):*
> ```Swift
>             from: settingsData
>         ) {
>             // Check for unversion settings.
> ```

Poorly worded.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 155 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYCkGs3r_Cx2J1lIBy:-NHYCkGs3r_Cx2J1lIBz:bmt8hin) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L155)):*
> ```Swift
>                     completion(error)
>                 } else {
>                     // migration was successful, deleting legacy settings.
> ```

Poorly worded again, besides you already have a logger below explaining what this does, so maybe no need to re-iterate the same?
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 359 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYD0pZ9U2tKmziUNYy:-NHYD0pZ9U2tKmziUNYz:b-921087) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L359)):*
> ```Swift
> }
> 
> /// An error type that contains description about version handling.
> ```

Poorly worded.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 364 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYDCPe-msb8COg-8IP:-NHYDCPe-msb8COg-8IQ:b-293nrk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L364)):*
> ```Swift
> 
>     var errorDescription: String? {
>         "Stored settings version was not the same as current version, stored version: \(storedVersion), current version: \(currentVersion)"
> ```

Missing `return` statement.
___
*[`ios/MullvadVPN/SettingsManager/SettingsParser.swift` line 24 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYEHAxCZfgav070ev0:-NHYEHAxCZfgav070ev1:b-f00naq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsParser.swift#L24)):*
> ```Swift
> }
> 
> struct SettingsParser {
> ```

Documentation for this class should be improved. `produceXXX` family of methods do not have any explanation of what each method does while the rest do. We don't have to document every single bit but since we already document the "decoding methods", it would be great to document "encoding methods" too.
___
*[`ios/MullvadVPN/SettingsManager/SettingsParser.swift` line 32 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYDwFwBjx2unK3ynYd:-NHYDwFwBjx2unK3ynYe:b-ejfxwr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsParser.swift#L32)):*
> ```Swift
> 
>     init(
>         decoder: JSONDecoder,
> ```

Could be put on a single line, these two are very short.
___
*[`ios/MullvadVPN/SettingsManager/MigrationManager/MigrationFromUnversionedToV2.swift` line 26 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYFilR1VGQI5aaQZYq:-NHYFilR1VGQI5aaQZYr:b-ec4h5u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/MigrationManager/MigrationFromUnversionedToV2.swift#L26)):*
> ```Swift
>     ) {
>         do {
>             logger.debug("Migrating from unversioned to version v2")
> ```

I suggest we move this log statement to `SettingsManager.migrateStore()`.
___
*[`ios/MullvadVPN/SettingsManager/MigrationManager/MigrationFromUnversionedToV2.swift` line 44 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYFrdj4rD-fieUt-iX:-NHYFrdj4rD-fieUt-iY:b-wux0dt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/MigrationManager/MigrationFromUnversionedToV2.swift#L44)):*
> ```Swift
>             completion(nil)
>         } catch {
>             logger.error(
> ```

Since we already log failures in `SettingsManager.migrateStore()`, perhaps we can drop `logger` in this class.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 2970 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHY9JNM5NfuoH4DCO_5:-NHY9JNM5NfuoH4DCO_6:b-3msqhz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN.xcodeproj/project.pbxproj#L2970)):*
> ```
> 				CLANG_ENABLE_MODULES = YES;
> 				CODE_SIGN_ENTITLEMENTS = MullvadVPN/MullvadVPN.entitlements;
> 				CODE_SIGN_IDENTITY = "Apple Development";
> ```

None of code signing properties should be added to the project. We use Xcode configuration files to declare that.
___
*[`ios/MullvadVPN/SettingsManager/MigrationManager/MigrationFromV1ToV2.swift` line 27 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYGfU-85XwYG6GKTTt:-NHYGfU-85XwYG6GKTTu:b3ee6ae) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/MigrationManager/MigrationFromV1ToV2.swift#L27)):*
> ```Swift
>     private let legacySe [...]

2022-11-23 07:02 UTC, pronebird reviewed
> Reviewed 1 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 19 unresolved discussions (waiting on @sajacl)



<!-- Sent from Reviewable.io -->

2022-11-23 07:09 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 21 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 115 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYIUtGBzBqaJghGyFt:-NHYIUtGBzBqaJghGyFu:b-8uxdy6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L115)):*
> ```Swift
>            settingsVersion != SchemaVersion.current.rawValue
>         {
>             completion(UnsupportedVersionSettings(
> ```

We should log that we stumbled upon an unknown version.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 1036 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYJDjDDVaBwUgEI2lU:-NHYJDjDDVaBwUgEI2lV:b-li79xn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN.xcodeproj/project.pbxproj#L1036)):*
> ```
> 			sourceTree = "<group>";
> 		};
> 		068CE57129278F5F00A068BB /* MigrationManager */ = {
> ```

Migrations are stored under "MigrationManager" folder?


<!-- Sent from Reviewable.io -->

2022-11-23 07:41 UTC, pronebird reviewed
In regards of testing migrations while we don't have unit tests (hopefully should be easier down the road):

1. v1 (legacy) can be produced with current AppStore app.
2. v2 (unversioned) can be produced with `ios/2022.3-build2`

In either case I suggest to log out within the app before rolling back to the older app.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-:-NHYPosX6kv-BGsaeJU7:b7vxkgh)* status: all files reviewed, 20 unresolved discussions (waiting on @sajacl)



<!-- Sent from Reviewable.io -->

2022-11-23 13:18 UTC, pronebird reviewed
> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 3 unresolved discussions (waiting on @sajacl)



<!-- Sent from Reviewable.io -->

2022-11-23 14:14 UTC, pronebird reviewed
> Reviewed 2 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 2 unresolved discussions (waiting on @sajacl)



<!-- Sent from Reviewable.io -->

2022-11-23 14:42 UTC, sajacl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 115 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYHWTf5BqF1gL29LtH:-NHZu8YJDl2wu8xsrYia:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/AppDelegate.swift#L115)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This error is unhandled, can we do `precondition(error == nil)` for now and then we can handle showing error in the UI at some point later
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 77 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NGu4BGcAmO-mspoOjja:-NHZuDYb-4qNlaS2q5JQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d42e69da762f13226b9d5a20da9a61c3c426d976/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L77)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Same here, four functions that do the same thing. That has to be improved.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NGu3jTI4qfWQIt7Ulnl:-NHZuHCj6YsrtMTtBDBm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d42e69da762f13226b9d5a20da9a61c3c426d976/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L113)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

These are four functions that do the same thing. That has to be consolidated and most of it related to versioning hidden away. 
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 159 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHTldrCCBl2IA808oTa:-NHZuM055iRTyF9nhTm-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7edcedfb4abb45e20d200f8e604e998912b04f2/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L159)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Before "middleware" we had a reader class capable of reading versions. The code is still in the middleware but unused and decoder is used directly to read `VersionHeader`.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 404 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHTmU1C8eeED7L5h61e:-NHZuRRl-Y9MAKrl6UZR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7edcedfb4abb45e20d200f8e604e998912b04f2/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L404)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Easier to review if these classes were put in separate files.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 498 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHTmxlx4k6ne7xWPNCI:-NHZuX1E2lTLhWlJU4CX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7edcedfb4abb45e20d200f8e604e998912b04f2/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L498)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This looks like a god object. It can parse generic data, versioned data, unversioned data, it also provides individual methods to parse `TunnelSettingsV2` and `DeviceState`, it also checks if version is unsupported. 
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 102 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYBveY5iyLkGn5r4No:-NHZuK8v2xZraP6fLxgQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L102)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This check will prevent the app from migrating from legacy settings to `v2`.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 104 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYAcHY9BUvg-hmN1zg:-NHZuHx0-rQ2txDLjPmC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L104)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This comment makes no sense. It says we return "new/not logged in user".
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 109 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYB9qyA6u5aQY_JlD0:-NHZuLOv8hKlDcKan2hW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L109)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This comment seems redundant.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 115 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYIUtGBzBqaJghGyFt:-NHZuMw67lrtP7PyN5QA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L115)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

We should log that we stumbled upon an unknown version.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 124 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYCDk24EzxzVZmz0WM:-NHZuO-JATxoizBw2DAP:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L124)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Poorly worded.
</blockquote></details>

Removed.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 155 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYCkGs3r_Cx2J1lIBy:-NHZuOiM8BbTkAbQqCkx:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L155)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Poorly worded again, besides you already have a logger below explaining what this does, so maybe no need to re-iterate the same?
</blockquote></details>

Removed.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 359 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYD0pZ9U2tKmziUNYy:-NHZuS2C4_lmvaiHdOi0:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L359)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Poorly worded.
</blockquote></details>

Removed.
___
*[`ios/MullvadVPN/SettingsManager/SettingsManager.swift` line 364 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-NHYDCPe-msb8COg-8IP:-NHZuWME5mQPT4x_Peqp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28b599074bcd7ae5b8c97ca0aca1ce719ef5b82d/ios/MullvadVPN/SettingsManager/SettingsManager.swift#L364)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Missing `return` statement.
</blockquote></details>

Done.
___
*[`ios/Mullv [...]

2022-11-23 15:04 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 1 unresolved discussion (waiting on @sajacl)



<!-- Sent from Reviewable.io -->

2022-11-23 15:34 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 1 unresolved discussion (waiting on @sajacl)



<!-- Sent from Reviewable.io -->

2022-11-23 15:35 UTC, pronebird reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: all files reviewed, 1 unresolved discussion (waiting on @sajacl)



<!-- Sent from Reviewable.io -->

2022-11-23 16:02 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144#-:-NH_DNv55EhT-kth2h05:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-23 16:18 UTC, merged

2023-03-12 11:38 UTC, danielsC93 reviewed
> Reviewed 1 of 6 files at r2, 1 of 8 files at r4, 4 of 10 files at r5, 1 of 7 files at r7, 2 of 3 files at r8, 1 of 3 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4144)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->