Handle application updates with settings migration
mullvad/mullvadvpn-app pull request #4173
Opened 2022-11-28 15:53 UTC by sajacl

1. Block all the traffic when tunnel cannot read the settings (Introduced empty tunnel in `TunnelConfiguration`).
2. Introduce proper error enum, wrap WireGuard error and settings migration error.
3. Report possible errors to GUI.

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173)

2022-11-30 10:57 UTC, pronebird requested changes
> Reviewed 1 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173)* status: all files reviewed, 4 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadTypes/PacketTunnelErrorWrapper.swift` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NI7Ad8_3WuTq5uFInGZ:-NI7Ad8a5I95ZfCOxIu5:b-12bc1f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30acc90c6096ceb4d03b68067fb5d9231e5e3061/ios/MullvadTypes/PacketTunnelErrorWrapper.swift#L15)):*
> ```Swift
>     case wireguard(error: String)
> 
>     /// Failure that indicates settings need migration.
> ```

Nit: description is slightly off. It's likely that settings need to be migrated but it could be something else too, i.e keychain is broken.
___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 189 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NI79MiF0dDRz4PYK0SQ:-NI79MiF0dDRz4PYK0SR:b-b2admq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30acc90c6096ceb4d03b68067fb5d9231e5e3061/ios/PacketTunnel/PacketTunnelProvider.swift#L189)):*
> ```Swift
>             )
> 
>             if !lastErrors.contains(.readConfiguration) {
> ```

Shouldn't `startTunnel()` be called only once and hence at that point `lastErrors` should be empty? In that regard I also told that it would be much simpler for you to keep two separate errors and them `compactMap` them instead of filtering `lastErrors` array.
___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 496 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NI79sKi3g4VPyKK9Vgf:-NI79sKjBImVL4D27P7P:bauxq7m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30acc90c6096ceb4d03b68067fb5d9231e5e3061/ios/PacketTunnel/PacketTunnelProvider.swift#L496)):*
> ```Swift
>                     )
> 
>                     if let index = self.lastErrors.firstIndex(where: { $0 == wrappedError }) {
> ```

I don't understand what this code does. It's looking for exact same error with exact same description and then replaces it with exact same copy? 

Hence why I mentioned that having two error fields and then using `compactMap` to put them into array when returning `packetTunnelStatus` would make your life much easier.
___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 715 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NI78qMx2q0UPeqoq6YI:-NI78qMyB1D8q93KzSZj:b5woeqi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30acc90c6096ceb4d03b68067fb5d9231e5e3061/ios/PacketTunnel/PacketTunnelProvider.swift#L715)):*
> ```Swift
> /// Used for creating an empty tunnel in certain situations.
> extension TunnelConfiguration {
>     fileprivate static let emptyTunnel = TunnelConfiguration(
> ```

Why do we need extension, can't we simply initialize this tunnel configuration in `startEmptyTunnel()`?


<!-- Sent from Reviewable.io -->

2022-11-30 10:59 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173)* status: all files reviewed, 5 unresolved discussions (waiting on @sajacl)

___
*[`ios/MullvadVPN/Notifications/TunnelStatusNotificationProvider.swift` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NI7B9Tg68m1Rs5SALR5:-NI7B9ThCQUmZG43naK4:b-b3krgt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30acc90c6096ceb4d03b68067fb5d9231e5e3061/ios/MullvadVPN/Notifications/TunnelStatusNotificationProvider.swift#L10)):*
> ```Swift
> 
> import Foundation
> import MullvadTypes
> ```

Nit: I think all types can be inferred so perhaps no need for `import`


<!-- Sent from Reviewable.io -->

2022-12-09 13:56 UTC, pronebird requested changes
> Reviewed 2 of 9 files at r3, 2 of 87 files at r4, 1 of 83 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173)* status: 5 of 90 files reviewed, 3 unresolved discussions (waiting on @sajacl)

___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 48 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NIr9l-W9u6eDaAnKYcy:-NIr9l-W9u6eDaAnKYcz:b-1efx6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6288b1dc476f8343174a3e00085a45003e622caa/ios/PacketTunnel/PacketTunnelProvider.swift#L48)):*
> ```Swift
> 
>     /// Last runtime error.
>     private var lastError: PacketTunnelErrorWrapper?
> ```

Naming can be improved. For instance: `tunnelProviderError` for packet tunnel errors and `wgError` for WireGuard errors.
___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 501 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NIr9xFp6IE9Yfm0AkQt:-NIr9xFp6IE9Yfm0AkQu:bd60xev) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6288b1dc476f8343174a3e00085a45003e622caa/ios/PacketTunnel/PacketTunnelProvider.swift#L501)):*
> ```Swift
>                     let wrappedError: PacketTunnelErrorWrapper = .wireguard(
>                         error: error
>                             .localizedDescription
> ```

Please fix indentation, error and localizedDescription same line. Our formatter is certainly not the brightest in that regard.


<!-- Sent from Reviewable.io -->

2022-12-09 13:57 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173)* status: 5 of 90 files reviewed, 3 unresolved discussions (waiting on @sajacl)

___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 243 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NIrAAMY45kauT5Aq6qH:-NIrAAMY45kauT5Aq6qI:bwjnha3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6288b1dc476f8343174a3e00085a45003e622caa/ios/PacketTunnel/PacketTunnelProvider.swift#L243)):*
> ```Swift
>                     self.providerLogger.error(
>                         error: error,
>                         message: "Failed to start the tunnel."
> ```

`else` branch mentions empty tunnel, maybe mention it here too so that we know where this error comes from.


<!-- Sent from Reviewable.io -->

2022-12-09 14:50 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173)* status: 6 of 90 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-12-09 14:51 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173)* status: 7 of 90 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-12-09 15:04 UTC, sajacl commented
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 715 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NI78qMx2q0UPeqoq6YI:-NIrP_1a2Uk28UdCItoZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30acc90c6096ceb4d03b68067fb5d9231e5e3061/ios/PacketTunnel/PacketTunnelProvider.swift#L715)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Why do we need extension, can't we simply initialize this tunnel configuration in `startEmptyTunnel()`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 15:04 UTC, sajacl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173)* status: 7 of 90 files reviewed, all discussions resolved

___
*[`ios/MullvadTypes/PacketTunnelErrorWrapper.swift` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NI7Ad8_3WuTq5uFInGZ:-NIrPOiL1awhq7-XKFqg:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30acc90c6096ceb4d03b68067fb5d9231e5e3061/ios/MullvadTypes/PacketTunnelErrorWrapper.swift#L15)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: description is slightly off. It's likely that settings need to be migrated but it could be something else too, i.e keychain is broken.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Notifications/TunnelStatusNotificationProvider.swift` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NI7B9Tg68m1Rs5SALR5:-NIrPPXV1PXR7ECEgiGu:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30acc90c6096ceb4d03b68067fb5d9231e5e3061/ios/MullvadVPN/Notifications/TunnelStatusNotificationProvider.swift#L10)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: I think all types can be inferred so perhaps no need for `import`
</blockquote></details>

Removed.
___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 189 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NI79MiF0dDRz4PYK0SQ:-NIrPTl4-niQTGKoHMMG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30acc90c6096ceb4d03b68067fb5d9231e5e3061/ios/PacketTunnel/PacketTunnelProvider.swift#L189)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Shouldn't `startTunnel()` be called only once and hence at that point `lastErrors` should be empty? In that regard I also told that it would be much simpler for you to keep two separate errors and them `compactMap` them instead of filtering `lastErrors` array.
</blockquote></details>

Done.
___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 496 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NI79sKi3g4VPyKK9Vgf:-NIrPYjU1izhGHL6Yfll:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/30acc90c6096ceb4d03b68067fb5d9231e5e3061/ios/PacketTunnel/PacketTunnelProvider.swift#L496)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I don't understand what this code does. It's looking for exact same error with exact same description and then replaces it with exact same copy? 

Hence why I mentioned that having two error fields and then using `compactMap` to put them into array when returning `packetTunnelStatus` would make your life much easier.
</blockquote></details>

Removed.
___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 48 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NIr9l-W9u6eDaAnKYcy:-NIrPSCH5jdS2mx9wkCw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6288b1dc476f8343174a3e00085a45003e622caa/ios/PacketTunnel/PacketTunnelProvider.swift#L48)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Naming can be improved. For instance: `tunnelProviderError` for packet tunnel errors and `wgError` for WireGuard errors.
</blockquote></details>

Done.
___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 243 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NIrAAMY45kauT5Aq6qH:-NIrPWeWARWJTimVWRxA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6288b1dc476f8343174a3e00085a45003e622caa/ios/PacketTunnel/PacketTunnelProvider.swift#L243)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`else` branch mentions empty tunnel, maybe mention it here too so that we know where this error comes from.
</blockquote></details>

Done.
___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 501 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173#-NIr9xFp6IE9Yfm0AkQt:-NIrPXiq1X7O2d1h9e6p:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6288b1dc476f8343174a3e00085a45003e622caa/ios/PacketTunnel/PacketTunnelProvider.swift#L501)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Please fix indentation, error and localizedDescription same line. Our formatter is certainly not the brightest in that regard.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 15:06 UTC, merged