Add netsh DNS manager
mullvad/mullvadvpn-app pull request #4208
Opened 2022-12-12 16:14 UTC by dlon

Given the issues found on some Windows 10 builds, I've opted to keep it simple and just do the obvious thing. This will cause some complaints: (1) timeouts (i.e., the hosts file cannot be used for adblocking), and (2) the app depends on `dnscache`.

This PR adds a new Rust wrapper around netsh instead of bringing back the old WinDns one.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4208)

2022-12-13 20:49 UTC, dlon commented on talpid-core/src/dns/windows.rs
> +    fn reset(&mut self) -> Result<(), Error> {
Calling this is actively bad when we're just doing it prior to destroying the tunnel interface. Should we add another method that defaults to calling `reset` but that is no-op for most DNS monitor implementations? I'd want to use that whenever destroying the tunnel interface is sufficient to achieve the same result.

2022-12-15 09:17 UTC, Jontified requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4208)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/dns/windows.rs` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4208#-NJK-Vgm6yqsreCTX27L:-NJK-Vgm6yqsreCTX27M:b-f0ipmq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a70475c73e78b55a590b53ff9f09f7b75c456775/talpid-core/src/dns/windows.rs#L79)):*
> ```XML
>         self.current_index = Some(interface_index);
> 
>         let mut ipv4_index = 0;
> ```

Shouldn't these be `bool` rather than integers? We only care if they are non-zero and we never decrement them.
___
*[`talpid-core/src/dns/windows.rs` line 114 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4208#-NJ6b3DACbLHwmI8RnZp-r1-114:-NJK3Zqx7eWkRJfdbR1I:bp8f9jp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a70475c73e78b55a590b53ff9f09f7b75c456775/talpid-core/src/dns/windows.rs#L114)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Calling this is actively bad when we're just doing it prior to destroying the tunnel interface. Should we add another method that defaults to calling `reset` but that is no-op for most DNS monitor implementations? I'd want to use that whenever destroying the tunnel interface is sufficient.
</blockquote></details>

This sounds like a pretty cheap solution to a somewhat real problem. So that sounds good to me.


<!-- Sent from Reviewable.io -->

2022-12-15 10:02 UTC, Jontified approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4208#-:-NJKE26Z6YLne204T80I:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2022-12-22 15:14 UTC, dlon commented
We should perhaps keep the old code and make this another module.

2023-01-10 11:00 UTC, merged