Upload all build artifacts at the same time
mullvad/mullvadvpn-app pull request #4314
Opened 2023-01-26 13:55 UTC by raksooo

This PR makes a few improvements to `buildserver-build.sh` and `buildserver-upload.sh`:
* Uploads/transfers all artifacts to the upload directory at the same time.
* Uses a single `sha256` file for all artifacts.
* Adds the version name to the `.pdb` file.
* Uploads the `.pdb` files to a subdirectory in the version directory.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314)

2023-01-31 12:16 UTC, faern requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`ci/buildserver-build.sh` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-NN6julp-vqEvNOCxlSP:-NN6julq6SIfv9u4Wa0R:b-fk3xml) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7815e1d4f89aff788290d46c31ea4bd929c19769/ci/buildserver-build.sh#L46)):*
> ```Shell
> upload() {
>   version=$1
>   target=$(rustc -vV | sed -n 's|host: ||p')
> ```

Maybe it's confusing to use the build hosts local target? Since that might not be what we build for. This needs to be unique with regards to all other build servers uploading to the same upload host. What if we have two linux machines one producing the Android builds and one producing the Linux builds? Then they will have the same local target. I think we should use the build machines hostname here to uniquely identify that build machine.

use `$HOSTNAME`?


<!-- Sent from Reviewable.io -->

2023-01-31 12:24 UTC, faern requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[`ci/buildserver-upload.sh` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-NN6lYeB7RrUFMt-jnen:-NN6lYeB7RrUFMt-jneo:b-qlmhs4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7815e1d4f89aff788290d46c31ea4bd929c19769/ci/buildserver-upload.sh#L35)):*
> ```Shell
>       fi
> 
>       rsync -av --rsh='ssh -p 1122' "$f" "build@releases.mullvad.net:$upload_path/$version/" || continue
> ```

Does this means that `pdb-2024.1.tar` will end up at `/releases/additional-files/2024.1/`? I guess it would be great if they could be uploaded to `/releases/2024.1/additional-files/` instead? So we get everything related to one build in one directory.


<!-- Sent from Reviewable.io -->

2023-01-31 21:32 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`ci/buildserver-build.sh` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-NN6julp-vqEvNOCxlSP:-NN8i-XL3B2q_yiT-kqP:b2bwim7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7815e1d4f89aff788290d46c31ea4bd929c19769/ci/buildserver-build.sh#L46)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Maybe it's confusing to use the build hosts local target? Since that might not be what we build for. This needs to be unique with regards to all other build servers uploading to the same upload host. What if we have two linux machines one producing the Android builds and one producing the Linux builds? Then they will have the same local target. I think we should use the build machines hostname here to uniquely identify that build machine.

use `$HOSTNAME`?
</blockquote></details>

Good idea! `$HOSTNAME` isn't set on my computer :thinking: Do we make sure it's set on the macOS build server? I opted for the `hostname`-command instead. Let me know if that's a bad idea.
___
*[`ci/buildserver-upload.sh` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-NN6lYeB7RrUFMt-jnen:-NN8jIHr1NwLxPod9S0a:b-bjeqyo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7815e1d4f89aff788290d46c31ea4bd929c19769/ci/buildserver-upload.sh#L35)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Does this means that `pdb-2024.1.tar` will end up at `/releases/additional-files/2024.1/`? I guess it would be great if they could be uploaded to `/releases/2024.1/additional-files/` instead? So we get everything related to one build in one directory.
</blockquote></details>

Great spot! I also noticed that `/additional-files` was appended for each iteration the condition was met. Done.


<!-- Sent from Reviewable.io -->

2023-02-01 09:41 UTC, faern requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`ci/buildserver-build.sh` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-NN6julp-vqEvNOCxlSP:-NNBKGnH6ncNq9NDxzdA:b-g8hezo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7815e1d4f89aff788290d46c31ea4bd929c19769/ci/buildserver-build.sh#L46)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Good idea! `$HOSTNAME` isn't set on my computer :thinking: Do we make sure it's set on the macOS build server? I opted for the `hostname`-command instead. Let me know if that's a bad idea.
</blockquote></details>

Ok! On all the current build servers `$HOSTNAME` and `$(hostname)` return the same thing. Yes. All build servers are named `app-build-linux`, `app-build-macos`, `app-build-windows` etc.

Now the assigning is so minimal, so a nitpick is to just go with:

```
f_checksums="$version+$(hostname).sha256"
```
___
*[`ci/buildserver-upload.sh` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-NNBKs9C9tXc_DJ_aGCM:-NNBKs9C9tXc_DJ_aGCN:b-pic90y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dac2fb785ba4f86be1433148b44e4dfa0b63b29e/ci/buildserver-upload.sh#L31)):*
> ```Shell
>     files=$(awk '{print $2}' < "$f_checksums")
>     for f in $files; do
>       file_upload_path="$upload_path/$version"
> ```

Nit: Our coding guidelines recommend `_dir` for paths to directories. https://github.com/mullvad/coding-guidelines/#files-paths-and-directories. With the current name my first impression is that it's the full path including the destination filename.


<!-- Sent from Reviewable.io -->

2023-02-06 09:51 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`ci/buildserver-build.sh` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-NN6julp-vqEvNOCxlSP:-NNa7lBB-ZhC1BwdH0Nm:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7815e1d4f89aff788290d46c31ea4bd929c19769/ci/buildserver-build.sh#L46)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Ok! On all the current build servers `$HOSTNAME` and `$(hostname)` return the same thing. Yes. All build servers are named `app-build-linux`, `app-build-macos`, `app-build-windows` etc.

Now the assigning is so minimal, so a nitpick is to just go with:

```
f_checksums="$version+$(hostname).sha256"
```
</blockquote></details>

Done
___
*[`ci/buildserver-upload.sh` line 31 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-NNBKs9C9tXc_DJ_aGCM:-NNa7nSk--eA6ULHm8FR:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dac2fb785ba4f86be1433148b44e4dfa0b63b29e/ci/buildserver-upload.sh#L31)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nit: Our coding guidelines recommend `_dir` for paths to directories. https://github.com/mullvad/coding-guidelines/#files-paths-and-directories. With the current name my first impression is that it's the full path including the destination filename.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-02-07 10:54 UTC, faern approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`ci/buildserver-build.sh` line 48 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-NNfVLsR8n-L5t9umG2a:-NNfVLsR8n-L5t9umG2b:b5jr0ts) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5919526ac94d5da2c2b38fd3118ad7f96c6c3172/ci/buildserver-build.sh#L48)):*
> ```Shell
> 
>   files=( *"$version"* )
>   f_checksums="$version+$(hostname).sha256"
> ```

Nitpick, and I realize I'm the one who originally started using `f_checksum` as a variable name. But I don't think it's a very good variable name, and now you introduce it to more places. So maybe we should swap to a better name? `checksums_filename` is clearer and follows our coding guidelines.


<!-- Sent from Reviewable.io -->

2023-02-07 12:13 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @faern)

___
*[`ci/buildserver-build.sh` line 48 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-NNfVLsR8n-L5t9umG2a:-NNfmnqH9p8x5JwkS4A0:bb9otq5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5919526ac94d5da2c2b38fd3118ad7f96c6c3172/ci/buildserver-build.sh#L48)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nitpick, and I realize I'm the one who originally started using `f_checksum` as a variable name. But I don't think it's a very good variable name, and now you introduce it to more places. So maybe we should swap to a better name? `checksums_filename` is clearer and follows our coding guidelines.
</blockquote></details>

Done. I also renamed `f` to `file`. Maybe those should be `filename` as well?


<!-- Sent from Reviewable.io -->

2023-02-07 12:17 UTC, faern approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`ci/buildserver-build.sh` line 48 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-NNfVLsR8n-L5t9umG2a:-NNfn9h4466oh1uWJXna:bvanhch) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5919526ac94d5da2c2b38fd3118ad7f96c6c3172/ci/buildserver-build.sh#L48)):*
I guess this works. file is better than f!

I realize to be fully correct this should be `checksums_path`. Because we treat it as a full path to a file (a relative one, but still a path). To quote the coding guidelines:

> foo_filename - Variables containing filenames that are not paths. Usually used to build paths with by concatenating it with a _path or _dir. Example: foo.log.


<!-- Sent from Reviewable.io -->

2023-02-07 12:35 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @faern)

___
*[`ci/buildserver-build.sh` line 48 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-NNfVLsR8n-L5t9umG2a:-NNfrnn4-7fusftuvV2G:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5919526ac94d5da2c2b38fd3118ad7f96c6c3172/ci/buildserver-build.sh#L48)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I guess this works. file is better than f!

I realize to be fully correct this should be `checksums_path`. Because we treat it as a full path to a file (a relative one, but still a path). To quote the coding guidelines:

> foo_filename - Variables containing filenames that are not paths. Usually used to build paths with by concatenating it with a _path or _dir. Example: foo.log.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-02-07 13:44 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-:-NNg6evO8Tk21QlM89Bk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-08 13:24 UTC, faern requested changes
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`ci/buildserver-build.sh` line 141 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-NNlBSpj7Bni8xFbLC8g:-NNlBSpj7Bni8xFbLC8h:b-al5blm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a62670b793277fbd0f70d764cba246ddd6150316/ci/buildserver-build.sh#L141)):*
> ```Shell
>       # Pipes all matching names and their new name to mv
>       pushd "$artifact_dir"
>       for original_file in MullvadVPN-*-dev-*{.deb,.rpm,.exe,.pkg,.apk,.aab}; do
> ```

This file is no longer building for Android. So the `apk` and `aab` parts can be removed.


<!-- Sent from Reviewable.io -->

2023-02-08 13:27 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`ci/buildserver-build.sh` line 141 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-NNlBSpj7Bni8xFbLC8g:-NNlCIOM3hCkgBK2fjzR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a62670b793277fbd0f70d764cba246ddd6150316/ci/buildserver-build.sh#L141)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This file is no longer building for Android. So the `apk` and `aab` parts can be removed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-08 13:27 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4314#-:-NNlCMp2-2b8O9BsxmuP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-08 16:12 UTC, merged