Remove automatic fallback to wireguard-go on Windows
mullvad/mullvadvpn-app pull request #4337
Opened 2023-02-06 12:21 UTC by dlon

It's unclear how often this path is taken, so it makes sense to keep the option to use wireguard-go for now.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4337)

2023-02-06 16:13 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4337)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`talpid-wireguard/src/wireguard_nt.rs` line 167 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4337#-NNbQPSV7NlxktC5WfLd:-NNbQPSV7NlxktC5WfLe:b-3sr4c7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c1f71bd6fb5bb29254daff0ec5c70918e2bcbc2e/talpid-wireguard/src/wireguard_nt.rs#L167)):*
> ```XML
> }
> 
> impl From<Error> for super::TunnelError {
> ```

This mapping isn't great, but I'm not sure how to best improve it.


<!-- Sent from Reviewable.io -->

2023-02-07 09:11 UTC, faern requested changes
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4337)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-wireguard/src/lib.rs` line 874 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4337#-NNf6y62912Os2-8SX-K:-NNf6y62912Os2-8SX-L:bv5itmw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ea035a59966a398350a2d9648812133d22f2b65/talpid-wireguard/src/lib.rs#L874)):*
> ```XML
>     /// Unknown error
>     #[error(display = "An error occurred")]
>     Other,
> ```

I can't see this being used anywhere in the PR. Why is this needed? Can it be named more specifically?


<!-- Sent from Reviewable.io -->

2023-02-07 09:28 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4337)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`talpid-wireguard/src/lib.rs` line 874 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4337#-NNf6y62912Os2-8SX-K:-NNfBxMx9z1Avrduo9XR:b-dy3h4l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3ea035a59966a398350a2d9648812133d22f2b65/talpid-wireguard/src/lib.rs#L874)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I can't see this being used anywhere in the PR. Why is this needed? Can it be named more specifically?
</blockquote></details>

Thanks for catching that! It was no longer needed.


<!-- Sent from Reviewable.io -->

2023-02-07 10:50 UTC, faern approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4337)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-07 13:30 UTC, merged