Refactor advance setting page
mullvad/mullvadvpn-app pull request #4347
Opened 2023-02-08 16:30 UTC by sabercodic

2023-02-09 08:42 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347)* status: 0 of 20 files reviewed, 6 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedSettingFragment.kt` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NNpJYFF75e5vDAWZyJe:-NNpJYFF75e5vDAWZyJf:b-d0y9rx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/687e3a82eb23a4b270dda1d7ecffe15a4f82b886/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedSettingFragment.kt#L39)):*
> ```Kotlin
> import org.koin.androidx.viewmodel.ext.android.viewModel
> 
> class AdvancedSettingFragment : BaseFragment() {
> ```

Most of this class can be cleaned up as it's no longer needed. Even if this is still a WIP it would be nice to clean up go get an overview of how the final fragment will look.



_Code quote:_
```Kotlin
 AdvancedSettingFragment
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NNpJFhSBz5N65hLNqFh:-NNpJFhSBz5N65hLNqFi:b5ee3so) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/687e3a82eb23a4b270dda1d7ecffe15a4f82b886/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L59)):*
> ```Kotlin
>     EditDns,
>     NewDns,
>     ConfirmLocalDns
> ```

We might want to use boolean properties for these, but we can keep it if it works fine



_Code quote:_
```Kotlin
    Normal,
    EditMtu,
    EditDns,
    NewDns,
    ConfirmLocalDns
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 149 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NNpIO_AB4BD3KAES-PK:-NNpIO_AB4BD3KAES-PL:b-ba16do) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/687e3a82eb23a4b270dda1d7ecffe15a4f82b886/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L149)):*
> ```Kotlin
>      * Refresh advanced settings and update the UI state accordingly
>      */
>     private fun refreshSettings() {
> ```

As we already observe settings in via `init`, I believe we it might be possible to do something like below here:

1. Set `viewModelState.isLoading=true`
2. Call `repository.refreshSettings()`



_Code quote:_
```Kotlin
refreshSettings
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 217 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NNpBtux2JZ4iC3Nj_q5:-NNpBtux2JZ4iC3Nj_q6:b-xi08c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/687e3a82eb23a4b270dda1d7ecffe15a4f82b886/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L217)):*
> ```Kotlin
>         return newValue.toIntOrNull()?.let {
>             it in 1280..1420
>         } ?: run { true }
> ```

What's the purpose of this?



_Code quote:_
```Kotlin
 ?: run { true }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 228 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NNpBaQ1DPw6J6Qk9wMq:-NNpBaQ1DPw6J6Qk9wMr:bl9fqp1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/687e3a82eb23a4b270dda1d7ecffe15a4f82b886/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L228)):*
> ```Kotlin
> 
> sealed class DnsSettingsState {
>     class Normal(var dns: String) : DnsSettingsState()
> ```

The meaning of this state is not clear.



_Code quote:_
```Kotlin
Normal
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 240 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NNpBPp4B7Uw8KhG2YT0:-NNpBPp4B7Uw8KhG2YT1:bnjw9k9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/687e3a82eb23a4b270dda1d7ecffe15a4f82b886/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L240)):*
> ```Kotlin
> }
> 
> sealed class CellUiState {
> ```

Is this class necessary?



_Code quote:_
```Kotlin
CellUiState
```


<!-- Sent from Reviewable.io -->

2023-02-13 11:19 UTC, albin-mullvad requested changes
> Reviewed 2 of 20 files at r1, 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347)* status: 3 of 20 files reviewed, 12 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 35 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NO9Jia763MOvOreg-98:-NO9Jia763MOvOreg-99:b-yr5tpv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb021593a1a6c13c46075f312db9d79aee4829bb/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L35)):*
> ```Kotlin
> @Preview
> @Composable
> fun testUi() {
> ```

Reminder: Add proper names to this and other preview functions.



_Code quote:_
```Kotlin
testUi
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt` line 29 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NO9UDqu1LDlRzrl_ZQS:-NO9UDqu1LDlRzrl_ZQT:blltxpi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb021593a1a6c13c46075f312db9d79aee4829bb/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt#L29)):*
> ```Kotlin
>     dispatcher: CoroutineDispatcher = Dispatchers.IO
> ) {
>     private val settings = MutableStateFlow<MullvadSetting>(
> ```

I believe it might make sense to split the exposed settings to `dnsSettings` and `mtuSettings`



_Code quote:_
```Kotlin
private val settings = MutableStateFlow<MullvadSetting>(
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 55 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NO9TksE1_RGcw7zjHJ4:-NO9TksE1_RGcw7zjHJ5:b3lrw6l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb021593a1a6c13c46075f312db9d79aee4829bb/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L55)):*
> ```Kotlin
>         override val editDnsIndex: Int = NO_EDIT_MODE,
>         val onConfirm: () -> Unit,
>         val onCancel: () -> Unit,
> ```

Why are these part of the `uiState`?



_Code quote:_
```Kotlin
        val onConfirm: () -> Unit,
        val onCancel: () -> Unit,
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 121 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NO9TPCT-JPFGxiyZiBp:-NO9TPCU9HBb3e9vtY7k:b8ljarg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb021593a1a6c13c46075f312db9d79aee4829bb/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L121)):*
> ```Kotlin
>         .stateIn(
>             viewModelScope,
>             SharingStarted.Eagerly,
> ```

Does this need to be eagerly?



_Code quote:_
```Kotlin
Eagerly
```
___
*[`android/buildSrc/src/main/kotlin/Dependencies.kt` line 63 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NO9K3NZ8vAcu1PvieAY:-NO9K3NZ8vAcu1PvieAZ:b-x3jlok) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb021593a1a6c13c46075f312db9d79aee4829bb/android/buildSrc/src/main/kotlin/Dependencies.kt#L63)):*
> ```Kotlin
> 
>         const val composeCollapsingToolbar =
>             "me.onebone:toolbar-compose:${Versions.Compose.composeCollapsingToolbar}"
> ```

We try to keep these in alphabetical order



_Code quote:_
```Kotlin
        const val composeCollapsingToolbar =
            "me.onebone:toolbar-compose:${Versions.Compose.composeCollapsingToolbar}"
```
___
*[`android/buildSrc/src/main/kotlin/Versions.kt` line 47 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NO9KB8o6y3_zxs34_O2:-NO9KB8o6y3_zxs34_O3:b-x3jlok) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb021593a1a6c13c46075f312db9d79aee4829bb/android/buildSrc/src/main/kotlin/Versions.kt#L47)):*
> ```Kotlin
>         const val uiController = "0.28.0"
>         const val viewModelLifecycle = "2.5.1"
>         const val composeCollapsingToolbar = "2.3.5"
> ```

We try to keep these in alphabetical order



_Code quote:_
```Kotlin
composeCollapsingToolbar
```


<!-- Sent from Reviewable.io -->

2023-02-15 13:43 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347)* status: 3 of 21 files reviewed, 18 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt` line 123 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOKIXfQ7_WIhFyAyqpU:-NOKIXfQ7_WIhFyAyqpV:bdd3tkp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/16d15c4941ea2a722cf2ba8e7a2ab85d8eb88cc2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt#L123)):*
> ```Kotlin
>     var isCustomDnsEnabled: Boolean,
>     var dnsList: List<InetAddress>
> )
> ```

As mentioned in a previous revision, this class is probably not needed as we probably want to expose the `DnsOptions` + mtu to the VM that can combine the flows.



_Code quote:_
```Kotlin
data class MullvadSetting(
    var mtu: String,
    var isCustomDnsEnabled: Boolean,
    var dnsList: List<InetAddress>
)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt` line 48 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOKHrKO3tARwzqnfAk2:-NOKHrKO3tARwzqnfAk3:bspewvy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/16d15c4941ea2a722cf2ba8e7a2ab85d8eb88cc2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt#L48)):*
> ```Kotlin
> 
> 
>     private val advancesSettingViewModel by viewModel<AdvancedSettingViewModel>()
> ```

Should probably be removed from here



_Code quote:_
```Kotlin
 private val advancesSettingViewModel by viewModel<AdvancedSettingViewModel>()
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 55 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NO9TksE1_RGcw7zjHJ4:-NOKIHbrE-4tG2UbKbKw:b3mowg8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb021593a1a6c13c46075f312db9d79aee4829bb/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L55)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why are these part of the `uiState`?
</blockquote></details>

These should probably be exposed by the VM instead.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 214 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOKFrsKCJo4UUI16kG9:-NOKFrsKCJo4UUI16kGA:b-19xh85) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/16d15c4941ea2a722cf2ba8e7a2ab85d8eb88cc2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L214)):*
> ```Kotlin
>         if (isValidMtu(newValue)) {
>             repository.wireguardMtu = newValue.toIntOrNull()
>         }
> ```

I suggest reversing the order of parsing and validating. Also see related comment about the `isValidMtu` fun.

1. Parse string to int
2. Check if in valid range
3. Update repository

Also, can't this be moved to the `onSubmitMtu` fun?



_Code quote:_
```Kotlin
        if (isValidMtu(newValue)) {
            repository.wireguardMtu = newValue.toIntOrNull()
        }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 217 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOKFTE_4Uop99Xdt-9b:-NOKFTE_4Uop99Xdt-9c:b-j35vpm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/16d15c4941ea2a722cf2ba8e7a2ab85d8eb88cc2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L217)):*
> ```Kotlin
>     }
> 
>     private fun isValidMtu(newValue: String): Boolean {
> ```

I suggest to moving the int parsing outside of this fun and making this a private ext fun: 
```
private fun Int.isValidMtu(): Boolean
```



_Code quote:_
```Kotlin
private fun isValidMtu(newValue: String): Boolean {
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 225 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOKF4NbCoCBZLg0DbgH:-NOKF4NbCoCBZLg0DbgI:b-14nik) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/16d15c4941ea2a722cf2ba8e7a2ab85d8eb88cc2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L225)):*
> ```Kotlin
>     private fun shouldShowLocalDnsWarningDialog(address: InetAddress): Boolean {
>         val isLocalAddress = address.isLinkLocalAddress() || address.isSiteLocalAddress()
>         return isLocalAddress || !repository.isLocalNetworkSharingEnabled()
> ```

Sould probably be `&&`



_Code quote:_
```Kotlin
||
```


<!-- Sent from Reviewable.io -->

2023-02-17 08:39 UTC, albin-mullvad requested changes
> Reviewed 1 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347)* status: 4 of 23 files reviewed, 25 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 3 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOKvnGxC9QGxY0h3Ve_):*
I know this is temporary (before merging this PR), but I suggest cleaning up the message subject as it looks very strange.
___
*[`-- commits` line 5 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOKw9FABG67lTaw79hF):*
I suggesting changing this message subject to: `Add collapsing toolbar dependency`



_Code quote:_
```
'Compose collapsing toolbar'
```
___
*[`-- commits` line 7 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOKw4pVBt1-CNrH40iQ):*
typo



_Code quote:_
```
copose
```
___
*[`android/app/build.gradle.kts` line 220 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOKvZW0EQs6A5C1aNcH:-NOKvZW0EQs6A5C1aNcI:b-k9tg5z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c3daa6394e013edadebdaaca04d220b0ccc58c7/android/app/build.gradle.kts#L220)):*
> ```Kotlin
> 
>     // Compose collapsing toolbar
>     implementation(Dependencies.Compose.composeCollapsingToolbar)
> ```

Move to above `Dependencies.Compose.constrainLayout` and skip comment



_Code quote:_
```Kotlin
    // Compose collapsing toolbar
    implementation(Dependencies.Compose.composeCollapsingToolbar)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 83 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOTUaB70wfdeV-zaI16:-NOTUaB70wfdeV-zaI17:bayhbhh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de2cdb0e4f66a3c62734f2cb0a6ea6d59a1747b5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L83)):*
> ```Kotlin
> 
>             // Click listener
>             onCellClicked?.let {
> ```

For use-cases like this I believe it's more readable to use if-statements.



_Code quote:_
```Kotlin
onCellClicked?.let {
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 85 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOTUt0qESyBazUpXQyr:-NOTUt0qESyBazUpXQys:b-e4rkpg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de2cdb0e4f66a3c62734f2cb0a6ea6d59a1747b5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L85)):*
> ```Kotlin
>             onCellClicked?.let {
>                 Button(
>                     onClick = it,
> ```

As discussed AFK, I believe we need to rethink this a bit since all rows should be focusable/clickable



_Code quote:_
```Kotlin
                Button(
                    onClick = it,
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 148 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOTTRKt5_BRSxGBDjnK:-NOTTRKt5_BRSxGBDjnL:bd04e2g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de2cdb0e4f66a3c62734f2cb0a6ea6d59a1747b5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L148)):*
> ```Kotlin
>                             .padding(top = 8.dp)
>                             .background(MullvadBlue)
>                     ) {
> ```

Do we need to wrap the `MtuComposeCell`? Would be nice to skip the wrapped, but if that's not possible we should probably use a simpler compose component like `Box` or similar.



_Code quote:_
```Kotlin
                    ConstraintLayout(
                        modifier = Modifier
                            .fillMaxWidth()
                            .wrapContentHeight()
                            .padding(top = 8.dp)
                            .background(MullvadBlue)
                    ) {
```


<!-- Sent from Reviewable.io -->

2023-02-27 11:02 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347)* status: 3 of 23 files reviewed, 27 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 35 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NO9Jia763MOvOreg-98:-NPHVEko8mjIY4ylEI1e:b-qei1i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb021593a1a6c13c46075f312db9d79aee4829bb/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L35)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Reminder: Add proper names to this and other preview functions.
</blockquote></details>

As the discussed AFK, we should probably stick to names prefixed with `Preview`, e.g. `PreviewBaseCell`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NavigationComposeCell.kt` line 21 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPHVmqU3j_99uxOfTNI:-NPHVmqU3j_99uxOfTNJ:b-1wkwhm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1c08e5d490f0aa3f942eb23b01205e8bae66c25/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NavigationComposeCell.kt#L21)):*
> ```Kotlin
> @Preview
> @Composable
> fun SplitTunnelingNavigationComposeCellPreview() {
> ```

I believe that the names of some of the preview functions can be simplified:
* The preview names doesn't have to match the names of the function name it previews. 
* Preview implies that it's compose, so we don't need that in the preview function name as well.
* The preview of a generic component should also be generic.

The resulting name could be something like: `PreviewNavigationCell`



_Code quote:_
```Kotlin
SplitTunnelingNavigationComposeCellPreview
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NavigationComposeCell.kt` line 23 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPHWhMr7kKFqGiYUwFX:-NPHWhMr7kKFqGiYUwFY:bitc6qz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1c08e5d490f0aa3f942eb23b01205e8bae66c25/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NavigationComposeCell.kt#L23)):*
> ```Kotlin
> fun SplitTunnelingNavigationComposeCellPreview() {
>     NavigationComposeCell(
>         title = stringResource(id = R.string.split_tunneling),
> ```

Change to some string like for example: `"Menu navigation item"`



_Code quote:_
```Kotlin
stringResource(id = R.string.split_tunneling)
```


<!-- Sent from Reviewable.io -->

2023-02-28 09:32 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347)* status: 3 of 24 files reviewed, 26 unresolved discussions (waiting on @albin-mullvad)

___
*[`-- commits` line 5 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOKw9FABG67lTaw79hF):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggesting changing this message subject to: `Add collapsing toolbar dependency`
</blockquote></details>

Done.
___
*[`android/app/build.gradle.kts` line 220 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOKvZW0EQs6A5C1aNcH:-NPID4Ay7izZItMSAGeK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c3daa6394e013edadebdaaca04d220b0ccc58c7/android/app/build.gradle.kts#L220)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Move to above `Dependencies.Compose.constrainLayout` and skip comment
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 35 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NO9Jia763MOvOreg-98:-NPIDD2B5k5dZkIeE6mU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb021593a1a6c13c46075f312db9d79aee4829bb/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L35)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As the discussed AFK, we should probably stick to names prefixed with `Preview`, e.g. `PreviewBaseCell`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 78 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NO9fr5i8fZFfBqGXdkJ:-NPIK_C5-iq5Emk1qA6F:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb021593a1a6c13c46075f312db9d79aee4829bb/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L78)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Make sure to use immutable `val` in all places where it's possible.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 83 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOTUaB70wfdeV-zaI16:-NPIWB8N-Yh5jVnwCrbo:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de2cdb0e4f66a3c62734f2cb0a6ea6d59a1747b5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L83)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

For use-cases like this I believe it's more readable to use if-statements.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 85 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOTUt0qESyBazUpXQyr:-NPIXKY51lgw4nwQ4A5j:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de2cdb0e4f66a3c62734f2cb0a6ea6d59a1747b5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L85)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As discussed AFK, I believe we need to rethink this a bit since all rows should be focusable/clickable
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NavigationComposeCell.kt` line 21 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPHVmqU3j_99uxOfTNI:-NPIXpW23hQ8JXQLtegO:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1c08e5d490f0aa3f942eb23b01205e8bae66c25/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NavigationComposeCell.kt#L21)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe that the names of some of the preview functions can be simplified:
* The preview names doesn't have to match the names of the function name it previews. 
* Preview implies that it's compose, so we don't need that in the preview function name as well.
* The preview of a generic component should also be generic.

The resulting name could be something like: `PreviewNavigationCell`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NavigationComposeCell.kt` line 23 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPHWhMr7kKFqGiYUwFX:-NPIY5sw1-RVSgC-A8UM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b1c08e5d490f0aa3f942eb23b01205e8bae66c25/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NavigationComposeCell.kt#L23)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Change to some string like for example: `"Menu navigation item"`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 121 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NO9TPCT-JPFGxiyZiBp:-NODzurcEZ6k_xPSpTEQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb021593a1a6c13c46075f312db9d79aee4829bb/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L121)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Does this need to be eagerly?
</blockquote></details>

Done.



_Code quote:_
```Kotlin
State.value.toUi
```


<!-- Sent from Reviewable.io -->

2023-02-28 10:17 UTC, albin-mullvad requested changes
> Reviewed 1 of 15 files at r4, 1 of 9 files at r5, 3 of 15 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347)* status: 8 of 24 files reviewed, 49 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 3 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMNPuvEzL-WryTvz_B):*
I suggest fixing the commit message even though it will be removed.



_Code quote:_
```
. git add --a! remove this commit later git add --a./adb shell
```
___
*[`-- commits` line 7 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMO4J04gnHhf8ynu2-):*
typo



_Code quote:_
```
copose
```
___
*[`-- commits` line 11 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMOwPR1PuUvqWFT0TA):*
typo in two words



_Code quote:_
```
settint statusgs
```
___
*[`-- commits` line 19 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMNfW24rsnrsH0jiU9):*
Squash or change to: `Use content heigh for conditional collapsing of toolbar`



_Code quote:_
```
Only collapse when body is high enough
```
___
*[`-- commits` line 21 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMNZkn7gBsPI4AXcMN):*
Fix commit message.



_Code quote:_
```
wip mtu design
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 35 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NO9Jia763MOvOreg-98:-NPMOCVT2zLK6dXVkdDF:b3ouesi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb021593a1a6c13c46075f312db9d79aee4829bb/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L35)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Typo. Also, skip `Usage` in the function name as it's implied by the `Preview` part of the function name. Also make `private`.



_Code quote:_
```Kotlin
Bae
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 28 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMOegI160Xuqg-n_lV:-NPMOegI160Xuqg-n_lW:bsyt37k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L28)):*
> ```Kotlin
> @Preview
> @Composable
> fun PreviewBaeCellUsage() {
> ```

As this preview currently renders more or less the whole advanced settings screen, is there a reason to not just preview the advanced settings screen instead?



_Code quote:_
```Kotlin
PreviewBaeCellUsage
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 51 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMP6NFD9s94NzY8JNh:-NPMP6NFD9s94NzY8JNi:b-lmn0o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L51)):*
> ```Kotlin
> @Composable
> fun BaseCell(
> ```

Skip the empty lines in the argument list.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 89 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMPIyg5qJauxNzpvVT:-NPMPIyg5qJauxNzpvVU:b-fjzxzw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L89)):*
> ```Kotlin
>                     .clickable { onCellClicked }
>             ) {
>                 // Cell title
> ```

Nit: skip this comment



_Code quote:_
```Kotlin
// Cell title
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 92 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMPes54ZVqjANOpXUb:-NPMPes54ZVqjANOpXUc:b-hlqti6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L92)):*
> ```Kotlin
>                 title()
> 
>                 Spacer(modifier = Modifier.weight(1.0f))
> ```

What's the purpose of this `weight`?



_Code quote:_
```Kotlin
1.0f
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 105 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMPQGa2oYaGHdY0aOP:-NPMPQGa2oYaGHdY0aOQ:b-yap11o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L105)):*
> ```Kotlin
> 
>         // Cell subtitle
>         subtitle?.let {
> ```

I believe it might be more readable to use a `if`-statement here.



_Code quote:_
```Kotlin
 subtitle?.let {
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 111 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMPanh7tuJNk_sd9Ii:-NPMPanh7tuJNk_sd9Ij:b-rcvxp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L111)):*
> ```Kotlin
>                     .padding(
>                         start = cellHorizontalSpacing,
>                         top = 6.dp,
> ```

Can this be defined somewhere?



_Code quote:_
```Kotlin
6.dp
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt` line 32 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMPkrj8tCTi2lhNeQK:-NPMPkrj8tCTi2lhNeQL:b-q8twf8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt#L32)):*
> ```Kotlin
> @Preview
> @Composable
> fun TopBarPreview() {
> ```

Change to `PreviewTopBar`. Also make `private`.



_Code quote:_
```Kotlin
TopBarPreview
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt` line 36 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMPrZhC7eESyY2Wv3X:-NPMPrZhC7eESyY2Wv3Y:b3qy2ws) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt#L36)):*
> ```Kotlin
>         backgroundColor = MullvadDarkBlue,
>         onBackClicked = {},
>         title = stringResource(id = R.string.settings_advanced),
> ```

As this will be used for a lot of screens/fragments, I believe the title in the preview should be more generic. For example something like: `Screen title`



_Code quote:_
```Kotlin
R.string.settings_advanced
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt` line 44 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMQ8ET4H2EOK_s2ByP:-NPMQ8ET4H2EOK_s2ByQ:b-gd3y6w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt#L44)):*
> ```Kotlin
> 
> @Composable
> fun CollapsingTopBar(
> ```

This one contains many `dp` values that are not clearly defined somewhere. Can we use constants/resources for these? Most of them should probably be global, but the `padding` and `fontSize` for the `title` should perhaps be defined privately in this file?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt` line 72 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMR8fK4csTVLHCWgf5:-NPMR8fK4csTVLHCWgf6:bo90o9t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/ne [...]

2023-02-28 10:58 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347)* status: 8 of 24 files reviewed, 53 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/DnsCell.kt` line 223 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMdVwlBUCqwybJ1Fj1:-NPMdVwlBUCqwybJ1Fj2:b-dfch6u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/DnsCell.kt#L223)):*
> ```Kotlin
>     var editValue: String = ""
> ) {
>     val dnsCellUiState = MutableStateFlow<DnsCellMode>(DnsCellMode.NewDns)
> ```

This state flow should probably not exist. The uiState should only consist of "dumb" data that represent the ui content



_Code quote:_
```Kotlin
val dnsCellUiState = MutableStateFlow<DnsCellMode>(DnsCellMode.NewDns)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/DnsCell.kt` line 238 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMeDLv0QOcO4eJnMbF:-NPMeDLv0QOcO4eJnMbG:bgcxx78) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/DnsCell.kt#L238)):*
> ```Kotlin
>             )
>         }
>     }
> ```

Same as with the `MutableStateFlow`. We shouldn't need any initiation of a `uiState` class.



_Code quote:_
```Kotlin
    init {
        dnsCellUiState.value = when {
            isEditMode -> DnsCellMode.EditDns(
                ipString = inputValue.value,
                editValue = editValue
            )
            ip == null -> DnsCellMode.NewDns
            else -> DnsCellMode.NormalDns(
                ipString = inputValue.value,
                editValue = editValue
            )
        }
    }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/DnsCell.kt` line 244 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMdu6X12o_0BQUqNKQ:-NPMdu6X12o_0BQUqNKR:b-kjaxtc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/DnsCell.kt#L244)):*
> ```Kotlin
>         var editValue: String
> 
>         data class NormalDns(override var ipString: String, override var editValue: String) :
> ```

As discussed or mentioned before, `Normal` can mean many things. I suggest changing it to something like that is more explanatory like `ViewDns`



_Code quote:_
```Kotlin
Normal
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/MtuComposeCell.kt` line 47 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMeiVkDt3yt3-xziAT:-NPMeiVkDt3yt3-xziAU:b-k947t9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/MtuComposeCell.kt#L47)):*
> ```Kotlin
>     Column {
> //        var currentMtu = value.uiState.collectAsState().value.mtuState.mtuValue?.wireguardMtu
> //        var mtuString: String = currentMtu?.let { it.toString() } ?: run{ "" }
> ```

Cleanup :slightly_smiling_face: 



_Code quote:_
```Kotlin
//        var currentMtu = value.uiState.collectAsState().value.mtuState.mtuValue?.wireguardMtu
//        var mtuString: String = currentMtu?.let { it.toString() } ?: run{ "" }
```


<!-- Sent from Reviewable.io -->

2023-03-01 13:29 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347)* status: 3 of 25 files reviewed, 43 unresolved discussions (waiting on @albin-mullvad)

___
*[`-- commits` line 3 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOKvnGxC9QGxY0h3Ve_):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I know this is temporary (before merging this PR), but I suggest cleaning up the message subject as it looks very strange.
</blockquote></details>

Done.
___
*[`-- commits` line 3 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMNPuvEzL-WryTvz_B):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest fixing the commit message even though it will be removed.
</blockquote></details>

Done.
___
*[`-- commits` line 19 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMNfW24rsnrsH0jiU9):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Squash or change to: `Use content heigh for conditional collapsing of toolbar`
</blockquote></details>

Done.
___
*[`-- commits` line 21 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMNZkn7gBsPI4AXcMN):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Fix commit message.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 28 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMOegI160Xuqg-n_lV:-NPRIfsqCHJXU9UF245U:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L28)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As this preview currently renders more or less the whole advanced settings screen, is there a reason to not just preview the advanced settings screen instead?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 51 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMP6NFD9s94NzY8JNh:-NPMxgiz5MdzNceYnB_H:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L51)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Skip the empty lines in the argument list.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 92 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMPes54ZVqjANOpXUb:-NPMyAxr66jSc7xSYr7w:bkp1g69) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L92)):*
> weight
to make Spacer fill whole area between right and left components
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 105 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMPQGa2oYaGHdY0aOP:-NPMyqdd11kFkYVGMmcc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L105)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe it might be more readable to use a `if`-statement here.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 111 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMPanh7tuJNk_sd9Ii:-NPMz9DDEXPnkbTnvaL-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L111)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this be defined somewhere?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt` line 32 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMPkrj8tCTi2lhNeQK:-NPMzE2N3xw77vVZRNJe:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt#L32)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Change to `PreviewTopBar`. Also make `private`.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt` line 36 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMPrZhC7eESyY2Wv3X:-NPMzRDE2Gy6eFoduac9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt#L36)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As this will be used for a lot of screens/fragments, I believe the title in the preview should be more generic. For example something like: `Screen title`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt` line 44 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMQ8ET4H2EOK_s2ByP:-NPN0e6A8adn5070d7Df:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt#L44)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This one contains many `dp` values that are not clearly defined somewhere. Can we use constants/resources for these? Most of them should probably be global, but the `padding` and `fontSize` for the `title` should perhaps be defined privately in this file?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt` line 72 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMR8fK4csTVLHCWgf5:-NPN1CQfAqrTyN-wNn4L:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt#L72)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Add `contentDescription`. Perhaps `R.string.back`?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CustomDnsComposeCell.kt` line 21 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMQh10E1wZaUDkhUfm:-NPN1Ht4-Mfdbo64ytok:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CustomDnsComposeCell.kt#L21)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Make function `private`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CustomDnsComposeCell.kt` line 49 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMRdIhBtnJq1lCSzA9:-NPN1RGp7RNY3uWodO76:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CustomDnsComposeCell.kt#L49)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mu [...]

2023-03-02 13:08 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347)* status: 9 of 26 files reviewed, 17 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 67 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPN2LFY0z8OF5xhW6h2:-NPWVVWs6mndUaU5_6tB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L67)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Do we need both a `Column` and `ConstraintLayout`?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt` line 92 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMPes54ZVqjANOpXUb:-NPWZLiW2xgM6ecKQcCH:btsqxjq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/BaseCell.kt#L92)):*
> layout
Constraint layout already removed. is it that bad?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Dialog.kt` line 100 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPN0UDK4yJcWlRm876E:-NPWZojCEB1_jemAVvrF:bpm35d1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Dialog.kt#L100)):*
> Also, in the documentation it 
done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/MtuComposeCell.kt` line 108 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPMTRSq-rCz6fBvGGQX:-NPWbhT03kkjJ1rkbIvc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcb0cc9d879d0369f58fb12385f33bfd79362443/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/MtuComposeCell.kt#L108)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This should be moved to some util/extension etc.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 148 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOTTRKt5_BRSxGBDjnK:-NPWjgo5DUEhjC6IPLpX:bms8s7v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/de2cdb0e4f66a3c62734f2cb0a6ea6d59a1747b5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L148)):*
> wrapContentHeight
Constraints removed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt` line 29 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NO9UDqu1LDlRzrl_ZQS:-NPXR5CU5yW4bHZ_nObu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb021593a1a6c13c46075f312db9d79aee4829bb/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt#L29)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe it might make sense to split the exposed settings to `dnsSettings` and `mtuSettings`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt` line 123 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOKIXfQ7_WIhFyAyqpU:-NPXKCsV1rfruefH_U4N:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/16d15c4941ea2a722cf2ba8e7a2ab85d8eb88cc2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt#L123)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As mentioned in a previous revision, this class is probably not needed as we probably want to expose the `DnsOptions` + mtu to the VM that can combine the flows.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt` line 27 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPSTD2k8nFK6uq1ICRU:-NPXOwwe5yC7vgg89PcW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d651287fb104483145e9113830db2fda05021dea/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt#L27)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This should either be an integer extension or a validator class/object with a validation function. Parsing the string as an integer and having a default value should be moved to the caller
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NNpJFhSBz5N65hLNqFh:-NPXP9yn0PC7oIG-oCGO:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/687e3a82eb23a4b270dda1d7ecffe15a4f82b886/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L59)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We might want to use boolean properties for these, but we can keep it if it works fine
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 149 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NNpIO_AB4BD3KAES-PK:-NPXPho7-y9yWttA4pMK:bkdg6wh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/687e3a82eb23a4b270dda1d7ecffe15a4f82b886/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L149)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As we already observe settings in via `init`, I believe we it might be possible to do something like below here:

1. Set `viewModelState.isLoading=true`
2. Call `repository.refreshSettings()`

</blockquote></details>

unnecessary parts removed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 217 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NNpBtux2JZ4iC3Nj_q5:-NPXQVoT08_9knucwPKO:b8swqt4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/687e3a82eb23a4b270dda1d7ecffe15a4f82b886/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L217)):*
> isBlank
entering non digit character is imposible
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt` line 214 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NOKFrsKCJo4UUI16kG9:-NPXR-ssB0wvLPAbADxu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/16d15c4941ea2a722cf2ba8e7a2ab85d8eb88cc2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingViewModel.kt#L214)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest reversing the order of parsing and validating. Also see related comment about the `isValidMtu` fun.

1. Parse string to int
2. Check if in valid range
3. Update repository

Also, can't this be moved to the `onSubmitMtu` fun?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-02 13:19 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347)* status: 9 of 26 files reviewed, 17 unresolved discussions (waiting on @albin-mullvad)

___
*[`-- commits` line 34 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347#-NPSRG9p3d2k1tmGBEbZ):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This commit looks a bit strange?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-17 15:25 UTC, albin-mullvad reviewed
> Reviewed 2 of 48 files at r25, 26 of 28 files at r26.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4347)* status: 46 of 92 files reviewed, 1 unresolved discussion (waiting on @sabercodic)



<!-- Sent from Reviewable.io -->

2023-03-20 15:45 UTC, merged