Pq multihop
mullvad/mullvadvpn-app pull request #4353
Opened 2023-02-10 12:18 UTC by Jontified

This PR makes it possible to use PQ while using wireguards multihop. It does this by modifying the firewall API and doing two PQ handshakes through the WG tunnel to establish the PQ PSKs.

2023-02-14 15:26 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: 0 of 19 files reviewed, 19 unresolved discussions

___
*[`talpid-core/src/firewall/macos.rs` line 373 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFMpG41Vi-caLLAReA:-NOFMpG41Vi-caLLAReB:b59ytm8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/talpid-core/src/firewall/macos.rs#L373)):*
> ```XML
>             }
>         };
>         Ok(rules)
> ```

We can return in the match instead
___
*[`talpid-core/src/firewall/windows.rs` line 172 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFNmri7EtP9ZTYdHlK:-NOFNmri7EtP9ZTYdHlL:b-tfveg2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/talpid-core/src/firewall/windows.rs#L172)):*
> ```XML
> 
>         // SAFETY: `allowed_tun_ips` and `allowed_tunnel_endpoints` must not be dropped until
>         // `WinFw_ApplyPolicyConnecting` is done with it
> ```

    until `WinFw_ApplyPolicyConnecting` has returned *



_Code quote:_
```XML
        // SAFETY: `allowed_tun_ips` and `allowed_tunnel_endpoints` must not be dropped until
        // `WinFw_ApplyPolicyConnecting` is done with it
```
___
*[`talpid-core/src/firewall/windows.rs` line 462 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFOVDc5J1rMvT3es1f:-NOFOVDc5J1rMvT3es1g:bp6roio) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/talpid-core/src/firewall/windows.rs#L462)):*
> ```XML
>         pub type_: WinFwAllowedTunnelTrafficType,
>         pub endpoints: *const WinFwEndpoint,
>         pub endpoints_length: usize,
> ```

Should this be pascalCase?
___
*[`talpid-core/src/tunnel/mod.rs` line 146 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFOcoJAn1CtPBWwfwi:-NOFOcoJAn1CtPBWwfwj:by8vr4h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/talpid-core/src/tunnel/mod.rs#L146)):*
> ```XML
>         let monitor = talpid_wireguard::WireguardMonitor::start(
>             config,
>             // TODO: We only need to use a bool here, the actual public key can be found in the
> ```

Remove this TODO
___
*[`talpid-tunnel-config-client/src/lib.rs` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFOv0W2Wk55NfZtFgP:-NOFOv0W2Wk55NfZtFgQ:b-myw90w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/talpid-tunnel-config-client/src/lib.rs#L67)):*
> ```XML
> 
>     let client = new_client(service_address).await;
>     let mut client = client?;
> ```

This can be removed
___
*[`talpid-tunnel-config-client/src/lib.rs` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFOsXz9OhT3yc-gMno:-NOFOsXz9OhT3yc-gMnp:b-myw90w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/talpid-tunnel-config-client/src/lib.rs#L79)):*
> ```XML
>         .await
>         .map_err(Error::GrpcError);
>     let response = response?;
> ```

This can be removed
___
*[`talpid-wireguard/src/lib.rs` line 239 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFP5iCC9QcO7HdQbQd:-NOFP5iDEhaw_qj46fjW:b-684e7m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/talpid-wireguard/src/lib.rs#L239)):*
> ```XML
>         args: TunnelArgs<'_, F>,
>     ) -> Result<WireguardMonitor> {
>         let on_event = args.on_event.clone();
> ```

Consider if necessary
___
*[`talpid-wireguard/src/lib.rs` line 248 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFPG7VDpSN88tNJtbP:-NOFPG7VDpSN88tNJtbQ:b-gxoo4m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/talpid-wireguard/src/lib.rs#L248)):*
> ```XML
>         let tunnel = Self::open_tunnel(
>             args.runtime.clone(),
>             &config,
> ```

Consider implications
___
*[`talpid-wireguard/src/lib.rs` line 274 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFPW58ACRXF-i-cp8A:-NOFPW58ACRXF-i-cp8B:bf08gv0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/talpid-wireguard/src/lib.rs#L274)):*
> ```XML
>             close_obfs_sender.clone(),
>         ))?;
>         let obfuscator = Arc::new(AsyncMutex::new(obfuscator));
> ```

Can be shortened
___
*[`talpid-wireguard/src/lib.rs` line 335 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFQ7DL6x4eXMJ6q52t:-NOFQ7DL6x4eXMJ6q52u:btgmhx3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/talpid-wireguard/src/lib.rs#L335)):*
> ```XML
>                     // Set up tunnel to entry do psk
>                     let mut entry_tun_config = config.clone();
>                     // Here we know there are exactly 2 peers, the last one is the exit
> ```

Should we do some verification that there are exactly 2 peers? Perhaps in the future we'll have more than 2 and weird stuff might happen here.
___
*[`talpid-wireguard/src/lib.rs` line 337 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFRLM8BIX8K830huDX:-NOFRLM8BIX8K830huDY:b-4mah9x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/talpid-wireguard/src/lib.rs#L337)):*
> ```XML
>                     // Here we know there are exactly 2 peers, the last one is the exit
>                     entry_tun_config.peers.pop();
>                     entry_tun_config
> ```

Consider implications of `Self::patch_allowed_ips`
___
*[`talpid-wireguard/src/lib.rs` line 501 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFRvk360waogs3VJLO:-NOFRvk360waogs3VJLP:bdq1n9g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/talpid-wireguard/src/lib.rs#L501)):*
> ```XML
> 
>     /// Reconfigures the tunnel to use the provided config while potentially modifying the config
>     /// and restarting the obfuscation provider. Returns the used config.
> ```

Returns the used config. -> Returns the new config used by the new tunnel*



_Code quote:_
```XML
Returns the used config.
```
___
*[`talpid-wireguard/src/lib.rs` line 610 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFS4v4-yplGV1qsrBG:-NOFS4v4-yplGV1qsrBH:b67f8wv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/talpid-wireguard/src/lib.rs#L610)):*
> ```XML
> 
>     async fn perform_psk_negotiation(
>         //obfuscation_handle: Arc<AsyncMutex<Option<ObfuscatorHandle>>>,
> ```

Cleanup
___
*[`talpid-wireguard/src/lib.rs` line 641 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFSFpbABPVk2PSBBFM:-NOFSFpbABPVk2PSBBFN:b67f8wv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/talpid-wireguard/src/lib.rs#L641)):*
> ```XML
> 
>         // Restart the obfuscation server
>         //let mut obfs_guard = obfuscation_handle.lock().await;
> ```

Cleanup
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp` line 68 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFV00e1EVj4Oqc4lIW:-NOFV00e1EVj4Oqc4lIX:br4neg9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp#L68)):*
> ```cpp
>             {
>                 GUID guid;
>                 if (i == 0) {
> ```

Is there a nicer way to do this?
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp` line 126 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFV6Jr6eQpfH63_Qn-:-NOFV6JsD9yXre5dTVVk:b67f8wv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e7 [...]

2023-02-14 15:31 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: 0 of 19 files reviewed, 20 unresolved discussions

___
*[`docs/architecture.md` line 197 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFY1aYD-AuUveWKHmV:-NOFY1aYD-AuUveWKHmW:b23xms5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/docs/architecture.md#L197)):*
> ```Markdown
> #### Post-quantum
> 
> A post-quantum (PQ) resistant tunnel is established by creating a pre-shared key (PSK)
> ```

This makes it sound like the PSK is created on the client, but the PSK is created through an exchange between the client and server. The client  only generates some key material and sends this to the server.


<!-- Sent from Reviewable.io -->

2023-02-14 16:32 UTC, dlon requested changes
> Reviewed 1 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: 1 of 19 files reviewed, 21 unresolved discussions (waiting on @Jontified)

___
*[`talpid-core/src/firewall/windows.rs` line 462 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFOVDc5J1rMvT3es1f:-NOFk09l-6ebb2U79Tzy:bezgaf3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/talpid-core/src/firewall/windows.rs#L462)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Should this be pascalCase?
</blockquote></details>

We should be consistent, at least. But personally I think we should use underscores everywhere.
___
*[`talpid-core/src/firewall/windows.rs` line 175 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFjIvYEQT9idRWMjBv:-NOFjIvYEQT9idRWMjBw:b-8cnpoq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/900d1f224798613f9fe27b6f8ccce0811e3a5a5c/talpid-core/src/firewall/windows.rs#L175)):*
> ```XML
>         let mut allowed_tun_ips = [WideCString::new(), WideCString::new()];
>         let allowed_tunnel_endpoints = match allowed_tunnel_traffic {
>             AllowedTunnelTraffic::Only(endpoint) => {
> ```

It seems redundant to have `Only` when `Many` can also take a single endpoint. Maybe we only need `Many`/`Some`? Alternatively, `One` and `Two` or something, since the Windows impl only supports at most two endpoints anyway.
___
*[`talpid-core/src/firewall/windows.rs` line 185 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFjm5L1EfcyU-Iu-ID:-NOFjm5L1EfcyU-Iu-IE:b-8cgdbi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/900d1f224798613f9fe27b6f8ccce0811e3a5a5c/talpid-core/src/firewall/windows.rs#L185)):*
> ```XML
>             AllowedTunnelTraffic::Many(endpoints) => {
>                 Some(endpoints.into_iter().enumerate().map(|(i, endpoint)| {
>                     allowed_tun_ips[i] = widestring_ip(endpoint.address.ip());
> ```

This will panic if `endpoints` contains more than two endpoints.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp` line 68 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFV00e1EVj4Oqc4lIW:-NOFkO891uNUuHENolzB:b-720q41) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp#L68)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Is there a nicer way to do this?
</blockquote></details>

I think it would probably be nicer if `PermitVpnTunnel` took one entry endpoint and one optional exit endpoint instead of a list.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.cpp` line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFW85cDvCrcrWVAw01:-NOFl1yt2tAC_RWCi20Y:b-otilcs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.cpp#L70)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Can we improve?
</blockquote></details>

See comment above.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.cpp` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFWHm2DjJCF0p-YsOA:-NOFl5EkDDuoxle_Y91E:b-35y3ba) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b12c62ccde225475acc1b51fe8cda493e78a91f/windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.cpp#L75)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Should return error rather than false?
</blockquote></details>

It would probably make sense to throw an exception here. Or make it impossible to pass in more than two endpoints in the first place.


<!-- Sent from Reviewable.io -->

2023-02-15 09:33 UTC, dlon reviewed
> Reviewed 2 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: 3 of 19 files reviewed, 23 unresolved discussions (waiting on @Jontified)

___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp` line 62 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOJPegvE5Z36clYSfzi:-NOJPegvE5Z36clYSfzj:bbm00u6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/900d1f224798613f9fe27b6f8ccce0811e3a5a5c/windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp#L62)):*
> ```cpp
> 
> 		return objectInstaller.addFilter(filterBuilder, conditionBuilder);
>     } else {
> ```

Nit: The `else` is unnecessary.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.cpp` line 64 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOJPTyE9xJC4UeyY-sz:-NOJPTyE9xJC4UeyY-t-:bbm00u6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/900d1f224798613f9fe27b6f8ccce0811e3a5a5c/windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.cpp#L64)):*
> ```cpp
> 
> 		return objectInstaller.addFilter(filterBuilder, conditionBuilder);
>     } else {
> ```

Nit: The `else` is unnecessary.


<!-- Sent from Reviewable.io -->

2023-02-16 09:43 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: 2 of 20 files reviewed, 6 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/firewall/windows.rs` line 175 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFjIvYEQT9idRWMjBv:-NOOYVom4dhbTgnYsG5c:b-rwildz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/900d1f224798613f9fe27b6f8ccce0811e3a5a5c/talpid-core/src/firewall/windows.rs#L175)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It seems redundant to have `Only` when `Many` can also take a single endpoint. Maybe we only need `Many`/`Some`? Alternatively, `One` and `Two` or something, since the Windows impl only supports at most two endpoints anyway.
</blockquote></details>

I went with `One` and `Two` because as we discussed it offloads some of the potential runtime checks to compiletime and it is unlikely we will need to whitelist more than two endpoints in the future. The naming is still not yet set in stone.
___
*[`talpid-core/src/firewall/windows.rs` line 185 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOFjm5L1EfcyU-Iu-ID:-NOJJi-Y7sJIkqwiSO9R:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/900d1f224798613f9fe27b6f8ccce0811e3a5a5c/talpid-core/src/firewall/windows.rs#L185)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This will panic if `endpoints` contains more than two endpoints.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-16 09:44 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: 2 of 20 files reviewed, 7 unresolved discussions (waiting on @dlon)

___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.cpp` line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOOb40L31tdAP9av2nk:-NOOb40L31tdAP9av2nl:b-jmdbbr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/900d1f224798613f9fe27b6f8ccce0811e3a5a5c/windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.cpp#L61)):*
> ```cpp
> 		conditionBuilder.reset(FWPM_LAYER_ALE_AUTH_CONNECT_V6);
> 
> 		conditionBuilder.add_condition(ConditionInterface::Alias(m_tunnelInterfaceAlias));
> ```

Make all spaces into tabs in all C++ files


<!-- Sent from Reviewable.io -->

2023-02-16 14:59 UTC, dlon requested changes
> Reviewed 1 of 19 files at r1, 2 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: 3 of 20 files reviewed, 4 unresolved discussions (waiting on @Jontified)

___
*[`talpid-core/src/firewall/windows.rs` line 173 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOPhcKV3jgipG5DBXBo:-NOPhcKV3jgipG5DBXBp:b9r0hn1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e07a2bc251ea6b25afdf5c15dcc7325bf0fd1ec3/talpid-core/src/firewall/windows.rs#L173)):*
> ```XML
>         // SAFETY: `allowed_tun_ips`, `entry_endpoint` and `exit_endpoint` must not be dropped until
>         // `WinFw_ApplyPolicyConnecting` has returned.
>         let mut allowed_tun_ips = [WideCString::new(), WideCString::new()];
> ```

There's no need to store these in an array anymore.
___
*[`talpid-core/src/firewall/windows.rs` line 222 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOPhnC-E-pMuamfbEDW:-NOPhnC0EJVYh03B0pE3:b-474ulr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e07a2bc251ea6b25afdf5c15dcc7325bf0fd1ec3/talpid-core/src/firewall/windows.rs#L222)):*
> ```XML
>         // `allowed_tunnel_traffic` and must remain allocated until `WinFw_ApplyPolicyConnecting`
>         // has returned.
>         drop(allowed_tun_ips);
> ```

Are we only manually dropping here to prevent accidents? Maybe we should not.
___
*[`talpid-types/src/net/mod.rs` line 297 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOPiRxx6fRqr4pZ_t4A:-NOPiRxx6fRqr4pZ_t4B:bio2rh7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e07a2bc251ea6b25afdf5c15dcc7325bf0fd1ec3/talpid-types/src/net/mod.rs#L297)):*
> ```XML
>             AllowedTunnelTraffic::All => "All".fmt(f),
>             AllowedTunnelTraffic::One(endpoint) => endpoint.fmt(f),
>             AllowedTunnelTraffic::Two(endpoint1, endpoint2) => {
> ```

Should the endpoints be separate by something, e.g. a comma?
___
*[`talpid-wireguard/src/lib.rs` line 313 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOPitJ42XLAz8oxrn1c:-NOPitJ42XLAz8oxrn1d:b2d68t7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d87248c1c052f6f6f338b60ff3ff284dd617bfd/talpid-wireguard/src/lib.rs#L313)):*
> ```XML
>                 AllowedTunnelTraffic::All
>             };
>             (on_event)(TunnelEvent::InterfaceUp(metadata.clone(), allowed_traffic)).await;
> ```

Why was this removed? Perhaps we purposely punched a hole before adding any routes here.


<!-- Sent from Reviewable.io -->

2023-02-16 17:11 UTC, dlon requested changes
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: 3 of 21 files reviewed, 9 unresolved discussions (waiting on @Jontified)

___
*[`talpid-wireguard/src/lib.rs` line 323 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOQAlnS2g3Nu1ddVr7w:-NOQAlnS2g3Nu1ddVr7x:b-k9ga03) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/talpid-wireguard/src/lib.rs#L323)):*
> ```XML
>                 .map_err(CloseMsg::SetupError)?;
> 
>             if psk_negotiation {
> ```

This should probably be moved to a function/method.
___
*[`talpid-wireguard/src/lib.rs` line 324 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOQ1XsM1Cd4j0EQCBSg:-NOQ1XsM1Cd4j0EQCBSh:b-h77bp1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/talpid-wireguard/src/lib.rs#L324)):*
> ```XML
> 
>             if psk_negotiation {
>                 let mut wg_psk_privkey = None;
> ```

You could just generate a key here. It does not need to be an option.
___
*[`talpid-wireguard/src/lib.rs` line 328 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOQBioDCs5L4ls3CJX5:-NOQBioDCs5L4ls3CJX6:bvnly8y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/talpid-wireguard/src/lib.rs#L328)):*
> ```XML
> 
>                 if config.peers.len() > 1 {
>                     assert_eq!(config.peers.len(), 2);
> ```

I'm a bit skeptical of the panicking here. I think we should return an error, even though it's supposed to be unreachable.
___
*[`talpid-wireguard/src/lib.rs` line 342 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOQ6w_m7OnDL6G600ek:-NOQ6w_m7OnDL6G600el:b4299ws) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/talpid-wireguard/src/lib.rs#L342)):*
> ```XML
>                         .allowed_ips
>                         .push(IpNetwork::new(IpAddr::V4(config.ipv4_gateway), 32).unwrap());
>                     let entry_tun_config =
> ```

This adds `10.64.0.1`. So calling `patch_allowed_ips` is unnecessary, as is `entry_tun_config.peers.pop();`.
___
*[`talpid-wireguard/src/lib.rs` line 375 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOQ90nWBufjeZo_5ehD:-NOQ90nWBufjeZo_5ehE:bu8er2t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/talpid-wireguard/src/lib.rs#L375)):*
> ```XML
>                 let wg_psk_privkey = wg_psk_privkey.unwrap_or_else(PrivateKey::new_from_random);
>                 // Set up tunnel to exit and exchange psk
>                 let exit_config = Self::patch_allowed_ips(&config, psk_negotiation);
> ```

All you need here is the original config, since it already swallows everything with `0.0.0.0/0`. Maybe it would make more sense to call `perform_psk_negotiation` for the exit first, so you'd only have to update the WireGuard config and firewall rules twice instead of three times?

I don't think we should use `patch_allowed_ips` at all here. It is intended for Android, and it makes no difference.


<!-- Sent from Reviewable.io -->

2023-02-20 18:54 UTC, dlon requested changes
> Reviewed 1 of 19 files at r1, 1 of 1 files at r2, 9 of 17 files at r3, 2 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: 16 of 21 files reviewed, 20 unresolved discussions (waiting on @Jontified)

___
*[`docs/architecture.md` line 197 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk8u6y59BK833Mzf8k:-NOk8u6y59BK833Mzf8l:b-pnjgo6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/docs/architecture.md#L197)):*
> ```Markdown
> #### Post-quantum
> 
> A post-quantum (PQ) resistant tunnel is established by creating a pre-shared key (PSK)
> ```

This should probably be changed to either `quantum-resistant tunnel` or `post-quantum tunnel`.
___
*[`docs/architecture.md` line 201 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk96smEl6OtHpVgJUI:-NOk96snCvxV9dUmN8wc:b-b5qs8m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/docs/architecture.md#L201)):*
> ```Markdown
> the PSK is saved on the relay and on the client together with a new temporary wireguard
> key which the client generates. After this a new tunnel is created which uses the new WG key
> and the PSK, this new tunnel is PQ resistant.
> ```

"PQ safe" or "quantum resistant" (in my opinion).
___
*[`docs/architecture.md` line 208 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk9KLp-dvdpfhsuX_n:-NOk9KLp-dvdpfhsuX_o:b-otilcs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/docs/architecture.md#L208)):*
> ```Markdown
> temporary key and uses it to do a PSK exchange with the entry relay. Then, a normal tunnel is
> established from the entry to the exit relay and a new PSK is exchanged along with the temporary
> key. Finally, a new PQ resistant tunnel is created using the new WG key and the two PSKs to route
> ```

See comment above.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnel.h` line 35 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk4gQKBUBfWJxAgMwL:-NOk4gQKBUBfWJxAgMwM:b95inm7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/windows/winfw/src/winfw/rules/baseline/permitvpntunnel.h#L35)):*
> ```objc
> 
> private:
> 	bool AddEndpointFilter(const std::optional<Endpoint> &endpoint, GUID ipv4Guid, GUID ipv6Guid, wfp::FilterBuilder &filterBuilder, IObjectInstaller& objectInstaller);
> ```

Could you change this to `IObjectInstaller &objectInstaller` for consistency?



_Code quote:_
```objc
IObjectInstaller& objectInstaller
```
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp` line 27 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk5QYJ5G4gOIsddpWB:-NOk5QYJ5G4gOIsddpWC:b-jo8yo0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp#L27)):*
> ```cpp
> }
> 
> bool PermitVpnTunnel::AddEndpointFilter(const std::optional<Endpoint> &endpoint, GUID ipv4Guid, GUID ipv6Guid, wfp::FilterBuilder &filterBuilder, IObjectInstaller& objectInstaller)
> ```

I think the `wfp::FilterBuilder` should be constructed in this function instead of passed in as an argument. Right now, it's possible to pass in an incorrectly initialized filter builder. If you were to construct it here, the function would be completely self-contained. It's more cohesive.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp` line 27 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk7P8mEt4Z7dB1nwUE:-NOk7P8mEt4Z7dB1nwUF:bky9gy7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp#L27)):*
> ```cpp
> }
> 
> bool PermitVpnTunnel::AddEndpointFilter(const std::optional<Endpoint> &endpoint, GUID ipv4Guid, GUID ipv6Guid, wfp::FilterBuilder &filterBuilder, IObjectInstaller& objectInstaller)
> ```

You could pass the GUIDs as `const GUID &...`.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp` line 27 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk7agMDWY9m3SQ9QK5:-NOk7agMDWY9m3SQ9QK6:b-erq1fs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp#L27)):*
> ```cpp
> }
> 
> bool PermitVpnTunnel::AddEndpointFilter(const std::optional<Endpoint> &endpoint, GUID ipv4Guid, GUID ipv6Guid, wfp::FilterBuilder &filterBuilder, IObjectInstaller& objectInstaller)
> ```

`IObjectInstaller &objectInstaller`



_Code quote:_
```cpp
IObjectInstaller& objectInstaller
```
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp` line 29 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk67g5CVIHU6YtdmfQ:-NOk67g5CVIHU6YtdmfR:b1lbcab) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp#L29)):*
> ```cpp
> bool PermitVpnTunnel::AddEndpointFilter(const std::optional<Endpoint> &endpoint, GUID ipv4Guid, GUID ipv6Guid, wfp::FilterBuilder &filterBuilder, IObjectInstaller& objectInstaller)
> {
> 	if (!endpoint.has_value() || endpoint.value().ip.type() == wfp::IpAddress::Ipv4)
> ```

Just my opinion, but I think we should store these conditions in booleans for the purpose of documentation, like we did previously. E.g.,

```
bool shouldAddV4Filter = ...;
```

What the condition is for is currently very non-obvious.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.h` line 8 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk4H1-3zpwuKl21C8D:-NOk4H1-3zpwuKl21C8E:b-lh65ro) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.h#L8)):*
> ```objc
> #include <libwfp/ipaddress.h>
> #include <string>
> #include <vector>
> ```

You should probably import `optional`, and `vector` is no longer needed.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.h` line 25 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk3bwpChQLskzKVNT2:-NOk3bwpChQLskzKVNT3:b95inm7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.h#L25)):*
> ```objc
> 
> private:
> 	bool AddEndpointFilter(const std::optional<PermitVpnTunnel::Endpoint> &endpoint, GUID ipv4Guid, GUID ipv6Guid, wfp::FilterBuilder &filterBuilder, IObjectInstaller& objectInstaller);
> ```

Could you change this to `IObjectInstaller &objectInstaller` for consistency?



_Code quote:_
```objc
IObjectInstaller&
```
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.cpp` line 28 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk6ZYF5ChbSb-b9EFr:-NOk6ZYF5ChbSb-b9EFs:b-ta0y3n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.cpp#L28)):*
> ```cpp
> }
> 
> bool PermitVpnTunnelService::AddEndpointFilter(const std::optional<PermitVpnTunnel::Endpoint> &endpoint, GUID ipv4Guid, GUID ipv6Guid, wfp::FilterBuilder &filterBuilder, IObjectInstaller& objectInstaller)
> ```

Everything I said about `PermitVpnTunnel` also applies here.


<!-- Sent from Reviewable.io -->

2023-02-21 18:49 UTC, dlon reviewed
> Reviewed 4 of 17 files at r3, 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: all files reviewed, 20 unresolved discussions (waiting on @Jontified)



<!-- Sent from Reviewable.io -->

2023-02-22 11:51 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: 15 of 21 files reviewed, 17 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/firewall/windows.rs` line 222 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOPhnC-E-pMuamfbEDW:-NOUUMUZ57bIvI44MopL:btaqnuo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e07a2bc251ea6b25afdf5c15dcc7325bf0fd1ec3/talpid-core/src/firewall/windows.rs#L222)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Are we only manually dropping here to prevent accidents? Maybe we should not.
</blockquote></details>

Dropping here seems like a good idea to me because it causes compile errors if unsafe changes are made.
___
*[`talpid-wireguard/src/lib.rs` line 313 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOPitJ42XLAz8oxrn1c:-NOiQp4E4IumAhYWlx1u:bi8j6mp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d87248c1c052f6f6f338b60ff3ff284dd617bfd/talpid-wireguard/src/lib.rs#L313)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Why was this removed? Perhaps we purposely punched a hole before adding any routes here.
</blockquote></details>

Fixed after discussion.
___
*[`talpid-wireguard/src/lib.rs` line 323 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOQAlnS2g3Nu1ddVr7w:-NOiMfDgEIu-e25NrHN_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/talpid-wireguard/src/lib.rs#L323)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This should probably be moved to a function/method.
</blockquote></details>

Done.
___
*[`talpid-wireguard/src/lib.rs` line 324 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOQ1XsM1Cd4j0EQCBSg:-NOiMg4t6z4m4jq4xdXi:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/talpid-wireguard/src/lib.rs#L324)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You could just generate a key here. It does not need to be an option.
</blockquote></details>

Done.
___
*[`talpid-wireguard/src/lib.rs` line 328 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOQBioDCs5L4ls3CJX5:-NOiSqnZ0rroZrXuBAxP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/talpid-wireguard/src/lib.rs#L328)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I'm a bit skeptical of the panicking here. I think we should return an error, even though it's supposed to be unreachable.
</blockquote></details>

Done.
___
*[`talpid-wireguard/src/lib.rs` line 342 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOQ6w_m7OnDL6G600ek:-NOiT1eu-5njF5iLdHZT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/talpid-wireguard/src/lib.rs#L342)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This adds `10.64.0.1`. So calling `patch_allowed_ips` is unnecessary, as is `entry_tun_config.peers.pop();`.
</blockquote></details>

Done.
___
*[`talpid-wireguard/src/lib.rs` line 375 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOQ90nWBufjeZo_5ehD:-NOspHFY2acVskL0rg3D:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/talpid-wireguard/src/lib.rs#L375)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

All you need here is the original config, since it already swallows everything with `0.0.0.0/0`. Maybe it would make more sense to call `perform_psk_negotiation` for the exit first, so you'd only have to update the WireGuard config and firewall rules twice instead of three times?

I don't think we should use `patch_allowed_ips` at all here. It is intended for Android, and it makes no difference.
</blockquote></details>

Done.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnel.h` line 35 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk4gQKBUBfWJxAgMwL:-NOn9MIwCCeuDSGCCHc4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/windows/winfw/src/winfw/rules/baseline/permitvpntunnel.h#L35)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could you change this to `IObjectInstaller &objectInstaller` for consistency?
</blockquote></details>

Done.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp` line 27 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk5QYJ5G4gOIsddpWB:-NOn9tVt6lpWCSJyr6ue:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp#L27)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think the `wfp::FilterBuilder` should be constructed in this function instead of passed in as an argument. Right now, it's possible to pass in an incorrectly initialized filter builder. If you were to construct it here, the function would be completely self-contained. It's more cohesive.
</blockquote></details>

Done.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp` line 27 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk7P8mEt4Z7dB1nwUE:-NOnAC637ACzGBW4ozuy:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp#L27)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You could pass the GUIDs as `const GUID &...`.
</blockquote></details>

Done.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp` line 27 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk7agMDWY9m3SQ9QK5:-NOnAEwn-bKAyPZOU8Q4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp#L27)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`IObjectInstaller &objectInstaller`
</blockquote></details>

Done.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp` line 29 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk67g5CVIHU6YtdmfQ:-NOnAqteBFo90n3gtBr-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp#L29)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Just my opinion, but I think we should store these conditions in booleans for the purpose of documentation, like we did previously. E.g.,

```
bool shouldAddV4Filter = ...;
```

What the condition is for is currently very non-obvious.
</blockquote></details>

Done.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.h` line 8 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk4H1-3zpwuKl21C8D:-NOnAzPr1rf6Sc5YB4mv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.h#L8)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You should probably import `optional`, and `vector` is no longer needed.
</blockquote></details>

Done.
___
*[`windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.h` line 25 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk3bwpChQLskzKVNT2:-NOnB23sDzeA9sN_X5ok:b-896fix) ([raw file](ht [...]

2023-02-22 13:31 UTC, dlon approved these changes
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: all files reviewed, 5 unresolved discussions (waiting on @Jontified)

___
*[`talpid-wireguard/src/lib.rs` line 323 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOQAlnS2g3Nu1ddVr7w:-NOtHFwVBDWCzyv_v-Kn:btojbfd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/talpid-wireguard/src/lib.rs#L323)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great!
___
*[`talpid-wireguard/src/lib.rs` line 458 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOtH1fr2-IqzO7-HGUX:-NOtH1fs4eBrcg-vr_qG:b-7h9uhb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8089731dcb4e5a854f1988e14ac8b9f9a39c5ae9/talpid-wireguard/src/lib.rs#L458)):*
> ```XML
>         .await?;
> 
>         log::debug!("Successfully exchanged PSK with gateway peer");
> ```

Nit: Maybe "exit peer"?


<!-- Sent from Reviewable.io -->

2023-02-22 16:03 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[`docs/architecture.md` line 197 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk8u6y59BK833Mzf8k:-NOtoVcR01fzFQ0S3GbH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/docs/architecture.md#L197)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This should probably be changed to either `quantum-resistant tunnel` or `post-quantum tunnel`.
</blockquote></details>

Done.
___
*[`docs/architecture.md` line 201 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk96smEl6OtHpVgJUI:-NOtoWq0Bq8V6PxyqKNp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/docs/architecture.md#L201)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

"PQ safe" or "quantum resistant" (in my opinion).
</blockquote></details>

Done.
___
*[`docs/architecture.md` line 208 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOk9KLp-dvdpfhsuX_n:-NOtoXad2TyAvx712A6r:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d1eac00dd638131495b9f086af9cc6138799e8c/docs/architecture.md#L208)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

See comment above.
</blockquote></details>

Done.
___
*[`talpid-wireguard/src/lib.rs` line 458 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOtH1fr2-IqzO7-HGUX:-NOtLJ136sEFS-fSnE15:bxmpjkf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8089731dcb4e5a854f1988e14ac8b9f9a39c5ae9/talpid-wireguard/src/lib.rs#L458)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: Maybe "exit peer"?
</blockquote></details>

The reason I said gateway peer is because it might be the entry and exit if there is no multihop, but if we usually call it the exit then I'll change it?


<!-- Sent from Reviewable.io -->

2023-02-23 09:54 UTC, dlon approved these changes
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: all files reviewed, 2 unresolved discussions (waiting on @Jontified)

___
*[`docs/architecture.md` line 203 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOxehQKBm67EqThwEa5:-NOxehQKBm67EqThwEa6:bl3pe86) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2839828fb3e85b0ab3df4983d52431c8cff0d617/docs/architecture.md#L203)):*
> ```Markdown
> and the PSK, this new tunnel is quantum-resistant.
> 
> The specifics of how the PSK exchange is done can be found (here)[https://github.com/mullvad/mullvadvpn-app/blob/master/talpid-tunnel-config-client/proto/tunnel_config.proto]
> ```

The link is broken. Also, I think you could use a relative path: `../talpid-tunnel-config/proto ...`.
___
*[`talpid-wireguard/src/lib.rs` line 458 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOtH1fr2-IqzO7-HGUX:-NOxg3VH9Sy7bS-vyvby:b-x0katf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8089731dcb4e5a854f1988e14ac8b9f9a39c5ae9/talpid-wireguard/src/lib.rs#L458)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

The reason I said gateway peer is because it might be the entry and exit if there is no multihop, but if we usually call it the exit then I'll change it?
</blockquote></details>

I would argue that "exit" is always correct. But if you disagree, maybe you could log different things after checking `config.peers.len()`.


<!-- Sent from Reviewable.io -->

2023-02-23 09:54 UTC, dlon requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: all files reviewed, 2 unresolved discussions (waiting on @Jontified)



<!-- Sent from Reviewable.io -->

2023-02-23 12:44 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`talpid-wireguard/src/lib.rs` line 458 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOtH1fr2-IqzO7-HGUX:-NOyIHBW6xj1bTO5MTEz:be4mlrh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8089731dcb4e5a854f1988e14ac8b9f9a39c5ae9/talpid-wireguard/src/lib.rs#L458)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I would argue that "exit" is always correct. But if you disagree, maybe you could log different things after checking `config.peers.len()`.
</blockquote></details>

Exit is fine and correct. The last hop is always the exit no matter how many hops come before it.
___
*[`talpid-wireguard/src/lib.rs` line 419 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOyICD1AOJhD8jdhLEw:-NOyICD1AOJhD8jdhLEx:b-nqlids) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2839828fb3e85b0ab3df4983d52431c8cff0d617/talpid-wireguard/src/lib.rs#L419)):*
> ```XML
>             + Sync
>             + Clone
>             + 'static,
> ```

Nit, but this might be a case where putting the bounds in a `where` clause significantly clears up the function signature :see_no_evil: 


<!-- Sent from Reviewable.io -->

2023-02-23 15:28 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @faern)

___
*[`docs/architecture.md` line 198 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOyMW-BEgheUSghhrww:-NOyr-wN8ZpPfSHQGeih:b-7hzf34) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2839828fb3e85b0ab3df4983d52431c8cff0d617/docs/architecture.md#L198)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'd like to have the text point out that the "cryptographic key exchange" is actually quantum-safe. And I think there would be value in including the well known abbreviation "KEM". The readme for `liboqs` says "quantum-safe key encapsulation mechanism (KEM)" and I think we should include that formulation here. How about phrasing this paragraph something like:

> A quantum-resistant tunnel is created by applying a pre-shared key (PSK) derived using a quantum-safe key encapsulation mechanism (KEM) to the encryption of the tunnel. This is done by establishing a regular WireGuard tunnel to the relay, derive the PSK in the tunnel and have it associated with an ephemeral WireGuard pubkey picked by the client, and then re-establish a new tunnel to the same relay but with the ephemeral WireGuard key and the PSK. Details about the protocol and the cryptographic strength are discussed in more details in the [protocol definition file]
</blockquote></details>

What do you think about the new paragraph?
___
*[`docs/architecture.md` line 203 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOxehQKBm67EqThwEa5:-NOyr2oYDn9OKcy1iL42:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2839828fb3e85b0ab3df4983d52431c8cff0d617/docs/architecture.md#L203)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The link is broken. Also, I think you could use a relative path: `../talpid-tunnel-config/proto ...`.
</blockquote></details>

Done.
___
*[`docs/architecture.md` line 209 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOyJlWv-jXbKJbqebx-:-NOysL2d4Ab5h27-DlcW:b-50mbmy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2839828fb3e85b0ab3df4983d52431c8cff0d617/docs/architecture.md#L209)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

"generates a temporary WireGuard key and establishes a normal tunnel"

This can be confused as the temporary WireGuard key being used, which it is not. It is also not clear that this is a multihop tunnel. "normal" is a bit vague as it only refers to the non-pq aspect of it.

Can this paragraph(s) be written more concise as something like:

> To create a multihop tunnel where both hops are quantum resistant the client must negotiate a a unique PSK with both the entry and the exit relay separately. It must use the same ephemeral WireGuard key on both relays since the end result (just as with regular multihop tunnels) is two peers on a single WireGuard interface, which can only have a single key for the local peer.
>
> The PSKs are established by first creating a regular multihop tunnel to the exit via the entry relay and negotiate a PSK with the exit. Then establish a regular tunnel to just the entry and negotiate a PSK with it. Lastly the client can set up a multihop tunnel using the new ephemeral WireGuard key and the two PSKs via the entry to the exit.
</blockquote></details>

Yeah, that works really well.


<!-- Sent from Reviewable.io -->

2023-02-23 15:57 UTC, dlon approved these changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: all files reviewed, 2 unresolved discussions (waiting on @faern)



<!-- Sent from Reviewable.io -->

2023-02-27 09:59 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: all files reviewed, 1 unresolved discussion (waiting on @Jontified)

___
*[`docs/architecture.md` line 198 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOyMW-BEgheUSghhrww:-NPHHNo34QXt5rQXHtVB:b-1gz5k1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2839828fb3e85b0ab3df4983d52431c8cff0d617/docs/architecture.md#L198)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

What do you think about the new paragraph?
</blockquote></details>

I'm not a fan of using "saved on the relay and the client". Because we are very adamant about not persisting it or even letting it spread into too many places in RAM. The PSK is stored in memory only and treated as ephemeral on the client. On the server it's kept until reboot/restart of wg-manager but still only in memory.

Nitpicky, but using [this] as the link text is not my favorite option. It's used too often IMHO. I way prefer when the link text actually says what it links to. Which is why my example used [protocol definition file]


<!-- Sent from Reviewable.io -->

2023-02-27 17:43 UTC, dlon approved these changes
> Reviewed 1 of 2 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: all files reviewed, 1 unresolved discussion (waiting on @Jontified)



<!-- Sent from Reviewable.io -->

2023-02-27 21:58 UTC, Jontified reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[`docs/architecture.md` line 198 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353#-NOyMW-BEgheUSghhrww:-NPJrsc3AyQOBIWn6W9h:b-modxbt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2839828fb3e85b0ab3df4983d52431c8cff0d617/docs/architecture.md#L198)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'm not a fan of using "saved on the relay and the client". Because we are very adamant about not persisting it or even letting it spread into too many places in RAM. The PSK is stored in memory only and treated as ephemeral on the client. On the server it's kept until reboot/restart of wg-manager but still only in memory.

Nitpicky, but using [this] as the link text is not my favorite option. It's used too often IMHO. I way prefer when the link text actually says what it links to. Which is why my example used [protocol definition file]
</blockquote></details>

I've updated to make it clear that it's stored only in memory on both the client and the server.
I've also updated the protocol definition file.


<!-- Sent from Reviewable.io -->

2023-02-28 09:09 UTC, dlon approved these changes
> Reviewed 1 of 3 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-28 09:21 UTC, merged