Add mold linker to container
mullvad/mullvadvpn-app pull request #4439
Opened 2023-03-13 13:50 UTC by faern

Updates the Linux (and indirectly Android) build container to have the [`mold`](https://github.com/rui314/mold.git) linker installed in it. Then adjust the container helper scripts to be able to easily use it.

The reason for not using it [like recommended for Rust](https://github.com/rui314/mold#how-to-use) is because that requires me to install `clang`, which blows up the size of the container significantly. With this `LD_PRELOAD` hack way of running it it's much easier.

I have opted out of mold for the real builds. Partially because it does not cut down on build times anyway, and partially because it feels iffy to depend on this linker without knowing more about it.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439)

2023-03-13 13:53 UTC, faern reviewed
The way the scripts are set up right now, they should be mergable before we bump the official containers. Using this new `container-run.sh` on a container without mold should work fine if you just set `USE_MOLD=false` for now.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439#-:-NQQEUGi2LwYfIarbqIj:b-o5ri91)* status: 0 of 4 files reviewed, all discussions resolved

___
*[`building/container-run.sh` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439#-NQQEK4j2kqc6ycHi2o5:-NQQEK4j2kqc6ycHi2o6:b-k6d5lh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f7e1c0e1bfbdee66c6abd81486f72a9ccbc568dd/building/container-run.sh#L11)):*
> ```Shell
> # Usage: $ container-run.sh <linux/android> [command ...]
> #
> # Not supplying any command gives you a shell in the container.
> ```

This simply was untrue. I think it broke back when we added the `bash -c` part. But I did not spend time on fixing it right now. Invoking it with an extra `bash` argument seemed not a big deal IMO


<!-- Sent from Reviewable.io -->

2023-03-13 13:57 UTC, pinkisemils approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`building/Dockerfile` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439#-NQQFb1DBDGQ5r2Nu3Ol:-NQQFb1E448hPfjTfXTH:b-jwri71) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28814effd6929993ad9178a01d940f97567ef373/building/Dockerfile#L46)):*
> ```Dockerfile
>     gcc-mingw-w64-x86-64 \
>     # For building mold further down
>     cmake libssl-dev zlib1g-dev gcc g++ file \
> ```

I think it'd be better to install these packages all in one step when building mold.


<!-- Sent from Reviewable.io -->

2023-03-13 14:08 UTC, albin-mullvad requested changes
Please elaborate briefly in the PR description why we want to use mold as it doesn't sound like it improves build times etc.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439#-:-NQQG_kz7ufQRyRVg9-6:b2x58mo)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439#-NQQHw1W2Q_Mq8S9He4p):*

Shouldn't the default for `USE_MOLD` be `false` until we bump the container image version/tag? Otherwise this would brake on the build servers as they use an image version without `mold`, or am I missing something?



_Code quote:_
```
Use mold by default in container, but opt out with USE_MOLD=false
```


<!-- Sent from Reviewable.io -->

2023-03-13 14:13 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439#-NQQHw1W2Q_Mq8S9He4p):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Shouldn't the default for `USE_MOLD` be `false` until we bump the container image version/tag? Otherwise this would brake on the build servers as they use an image version without `mold`, or am I missing something?
</blockquote></details>

Nvm, missed the bit where the build-server defaults to `false`. However, I would have preferred keeping as `false` until the new image were published


<!-- Sent from Reviewable.io -->

2023-03-13 14:25 UTC, faern reviewed
When linking in release mode we have full LTO optimizations on. That takes up the majority of the linking time and essentially forces the linking to be single threaded anyway. So in release mode we don't save any time with `mold` indeed. However, in debug builds/builds without compiler optimization where we don't use LTO, we save a lot of time by using `mold`.

Some rudimentary benchmarking on my laptop shows we cut down linking from ~12s to ~4 seconds for all the Rust binaries together:

```
$ find . -iname "main.rs" -exec touch "{}" \; && time mold -run cargo build
...
real	0m3.716s
user	0m11.712s
sys	0m4.660s

$ find . -iname "main.rs" -exec touch "{}" \; && time cargo build
...
real	0m12.139s
user	0m24.675s
sys	0m5.975s
```

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439#-:-NQQKdvi002uH0XUPif1:b4q1mmw)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439#-NQQHw1W2Q_Mq8S9He4p):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Nvm, missed the bit where the build-server defaults to `false`. However, I would have preferred keeping as `false` until the new image were published
</blockquote></details>

Ok. Good point. Fixed


<!-- Sent from Reviewable.io -->

2023-03-13 14:26 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @pinkisemils)

___
*[`building/Dockerfile` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439#-NQQFb1DBDGQ5r2Nu3Ol:-NQQM4H1-W1iJxO-Kf1M:bppvxda) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28814effd6929993ad9178a01d940f97567ef373/building/Dockerfile#L46)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I think it'd be better to install these packages all in one step when building mold.
</blockquote></details>

Then we need to duplicate the full `apt-get update -y && apt-get install -y ... && rm -rf /var/lib/apt/lists/*`. That's doable I guess. Do you still think that's better? If so, maybe we should consider if there are more things in this list that better belong to other chapters below.


<!-- Sent from Reviewable.io -->

2023-03-13 14:46 UTC, albin-mullvad requested changes
Thanks for the clarification!

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439#-:-NQQO1kA6ZJB8gRHv44s:b-uv4tn)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`building/Dockerfile` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439#-NQQFb1DBDGQ5r2Nu3Ol:-NQQPpusEMLmLSHJXMAm:bjw0hc5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/28814effd6929993ad9178a01d940f97567ef373/building/Dockerfile#L46)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Then we need to duplicate the full `apt-get update -y && apt-get install -y ... && rm -rf /var/lib/apt/lists/*`. That's doable I guess. Do you still think that's better? If so, maybe we should consider if there are more things in this list that better belong to other chapters below.
</blockquote></details>

I believe it might be a good idea to do what @pinkisemils suggested, at least for `libssl-dev`, since the layer where it's installed will still include it regardless if it's removed in a later layer.


<!-- Sent from Reviewable.io -->

2023-03-14 07:29 UTC, albin-mullvad reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`building/Dockerfile` line 68 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439#-NQU0AiF-6UuaqPwimhT:-NQU0AiF-6UuaqPwimhU:b3jlu4g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3e87cb782238aaea14cf2faab79f9c71e85bf642/building/Dockerfile#L68)):*
> ```Dockerfile
> # === mold (fast linker) ===
> # Allows linking Rust binaries significantly faster.
> # This requires some build time dependencies, they are installed further up.
> ```

Remove or update this comment.



_Code quote:_
```Dockerfile
This requires some build time dependencies, they are installed further up.
```


<!-- Sent from Reviewable.io -->

2023-03-14 09:02 UTC, albin-mullvad approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4439)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-03-14 10:01 UTC, merged