Add dns content blockers droid 10
mullvad/mullvadvpn-app pull request #4482
Opened 2023-03-24 16:23 UTC by sabercodic

2023-03-27 06:06 UTC, albin-mullvad requested changes
Looks good overall, I just have some input on some naming and formatting.

> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-:-NRWf3Be2NXOW65uv9jj:b-id5xv9)* status: all files reviewed, 19 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt` line 64 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWcpmGAywbQA5NYOns:-NRWcpmGAywbQA5NYOnt:bd3nzfl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b0cba059010057fb4649bb985090fd9bb769117a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt#L64)):*
> ```Kotlin
> 
> @Composable
> private fun RightCellView(
> ```

This name is a bit unclear. Perhaps rename to `ExpandableComposeCellBody`?



_Code quote:_
```Kotlin
RightCellView
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt` line 99 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWcjTyCqJm9hoYhucQ:-NRWcjTyCqJm9hoYhucR:b-ao865c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b0cba059010057fb4649bb985090fd9bb769117a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt#L99)):*
> ```Kotlin
> 
> @Composable
> fun ChevronView(
> ```

I suggest moving this to a separate file since we might re-use it for other things



_Code quote:_
```Kotlin
ChevronView
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 43 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRW_9OG7y2eOa4Bgzzz:-NRW_9OG7y2eOa4Bh---:b-ggzk3o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26449e3f1926eb45bf421a8dc7bc09c9c1ecd760/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L43)):*
> ```Kotlin
> fun SwitchComposeCell(
>     title: String,
>     checkboxDefaultState: Boolean,
> ```

Rename to: `isToggled`



_Code quote:_
```Kotlin
checkboxDefaultState
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 44 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRW_5dLBddaHzxD8LzF:-NRW_5dLBddaHzxD8LzG:be9q9k1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26449e3f1926eb45bf421a8dc7bc09c9c1ecd760/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L44)):*
> ```Kotlin
>     title: String,
>     checkboxDefaultState: Boolean,
>     checkboxEnableState: Boolean = true,
> ```

Rename to `isEnabled`



_Code quote:_
```Kotlin
checkboxEnableState
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 93 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWZN7125t8W-RDA1pG:-NRWZN7125t8W-RDA1pH:b-47uqss) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26449e3f1926eb45bf421a8dc7bc09c9c1ecd760/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L93)):*
> ```Kotlin
>     isToggled: Boolean,
>     modifier: Modifier,
>     switchTriggered: ((Boolean) -> Unit)? = null,
> ```

I suggest renaming to `onSwitchClicked`



_Code quote:_
```Kotlin
switchTriggered
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 125 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRW_puv2n0O8dvrzp4A:-NRW_puv2n0O8dvrzp4B:byml6dg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/26449e3f1926eb45bf421a8dc7bc09c9c1ecd760/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L125)):*
> ```Kotlin
>             isChecked = isToggled,
>             isEnabled = isEnabled,
>             onCheckedChange = switchTriggered,
> ```

Rename to `onSwitchClicked`



_Code quote:_
```Kotlin
onCheckedChange
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Switch.kt` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWYCiS1k_WgVdZnYiJ:-NRWYCiS1k_WgVdZnYiK:b-4swdzy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fe780a620570a0e1ed4dff6ba8d19c1453bf669b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Switch.kt#L32)):*
> ```Kotlin
> private fun PreviewSwitch() {
>     Column {
> ```

nit: skip this empty line
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt` line 31 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWc1SG6yAgY9tdBl6g:-NRWc1SG6yAgY9tdBl6h:b-e8ti74) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c4574acb01ab5b9d6a33340c980a66c53e11c12c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt#L31)):*
> ```Kotlin
> 
> @Composable
> fun ContentBlockersInfo(onDismiss: () -> Unit) {
> ```

I suggest renaming to `ContentBlockersInfoDialog`



_Code quote:_
```Kotlin
ContentBlockersInfo
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt` line 36 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWbxob6PHIehm_IexN:-NRWbxoc0wKPpO3LEoHO:bv17fp9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c4574acb01ab5b9d6a33340c980a66c53e11c12c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt#L36)):*
> ```Kotlin
> 
> @Composable
> fun MalwareInfo(onDismiss: () -> Unit) {
> ```

I suggest renaming to `MalwareInfoDialog`



_Code quote:_
```Kotlin
MalwareInfo
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt` line 38 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWbk1T25sfTd808fQR:-NRWbk1T25sfTd808fQS:bmvzrnl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c4574acb01ab5b9d6a33340c980a66c53e11c12c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt#L38)):*
> ```Kotlin
> fun MalwareInfo(onDismiss: () -> Unit) {
>     InfoDialog(stringResource(id = R.string.malware_info), onDismiss)
> }
> ```

Might be nice to move these to separate files to make it easier to navigate



_Code quote:_
```Kotlin
@Composable
fun ContentBlockersInfo(onDismiss: () -> Unit) {
    InfoDialog(stringResource(id = R.string.dns_content_blockers_info), onDismiss)
}

@Composable
fun MalwareInfo(onDismiss: () -> Unit) {
    InfoDialog(stringResource(id = R.string.malware_info), onDismiss)
}
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt` line 48 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWbOmj7paFndOQ95dT:-NRWbOmj7paFndOQ95dU:bdjr888) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c4574acb01ab5b9d6a33340c980a66c53e11c12c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt#L48)):*
> ```Kotlin
>                 modifier = Modifier
>                     .fillMaxWidth()
>                     .height(44.dp),
> ```

Can this be changed to a resource or constant?



_Code quote:_
```Kotlin
44.dp
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt` line 57 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWbJo2AN3qoI9wRfdb:-NRWbJo2AN3qoI9wRfdc:bdjr888) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c4574acb01ab5b9d6a33340c980a66c53e11c12c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt#L57)):*
> ```Kotlin
>             Column(
>                 horizontalAlignment = Alignment.CenterHorizontally,
>                 modifier = Modifier.padding(top = 64.dp),
> ```

Can this be changed to a resource or constant?



_Code quote:_
```Kotlin
64.dp
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt` line 113 at r4](http [...]

2023-03-29 12:01 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482)* status: 1 of 13 files reviewed, 27 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt` line 46 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRhCir3DTrFTEaQDv3c:-NRhCir3DTrFTEaQDv3d:b-tnqhvm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb01e36c0f4b49675f4c8bed82521f747200519/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt#L46)):*
> ```Kotlin
>         } else {
>             Modifier
>         }
> ```

I suggesting making this immutable and changing it into:

```
val rowModifier = Modifier.apply {
    if (isRowEnabled) clickable { onCellClicked() }
}
```



_Code quote:_
```Kotlin
        var rowModifier = if (isRowEnabled) {
            Modifier.clickable { onCellClicked.invoke() }
        } else {
            Modifier
        }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt` line 45 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRhCO4NB9F0p0g-G4Lm:-NRhCO4NB9F0p0g-G4Ln:bbcpl1m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb01e36c0f4b49675f4c8bed82521f747200519/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt#L45)):*
> ```Kotlin
>     title: String,
>     expandState: Boolean,
>     titleAlpha: Float = 1f,
> ```

I suggest changing this alpha to a boolean `isEnabled` and resolve the alpha within the function.



_Code quote:_
```Kotlin
titleAlpha: Float = 1f,
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt` line 50 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRhCFQBA7RN5dnCo8W3:-NRhCFQBA7RN5dnCo8W4:bm96hxr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb01e36c0f4b49675f4c8bed82521f747200519/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt#L50)):*
> ```Kotlin
>     onInfoClicked: (() -> Unit)? = null
> ) {
>     val alpha = if (checkboxEnableState) 1f else 0.3f
> ```

I suggest making these floats into constants. Perhaps move it into `Color.kt`?. Applies to other alpha values as well.



_Code quote:_
```Kotlin
1f else 0.3f
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt` line 45 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRhDVIxD1hLB_kPvKIP:-NRhDVIxD1hLB_kPvKIQ:b-g4077d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb01e36c0f4b49675f4c8bed82521f747200519/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt#L45)):*
> ```Kotlin
> 
> @Composable
> fun InfoDialog(info: String?, warnings: String?, onDismiss: () -> Unit) {
> ```

nit: rename to `warning`



_Code quote:_
```Kotlin
warnings
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt` line 45 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRhDbvm2eY3ud6eP7n9:-NRhDbvm2eY3ud6eP7nA:bgjstsh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb01e36c0f4b49675f4c8bed82521f747200519/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt#L45)):*
> ```Kotlin
> 
> @Composable
> fun InfoDialog(info: String?, warnings: String?, onDismiss: () -> Unit) {
> ```

Why are both `info` and `warning` needed? Isn't one enough? Or can both be provided? If it's just a matter of styling it's probably better to handle by providing either a modifier or other argument like `isWarning: Boolean`



_Code quote:_
```Kotlin
info: String?, warnings: String
```


<!-- Sent from Reviewable.io -->

2023-04-02 23:46 UTC, albin-mullvad requested changes
> Reviewed 2 of 12 files at r8, 11 of 12 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482)* status: 13 of 15 files reviewed, 15 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt` line 46 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRhCir3DTrFTEaQDv3c:-NS3DIMh0Afy6CROmSPt:bfzek7b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb01e36c0f4b49675f4c8bed82521f747200519/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt#L46)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

> val rowModifier = Modifier.apply {
>     if (isRowEnabled) clickable { onCellClicked() }
> }
done with let, it is not working with apply
</blockquote></details>

Please elaborate, in what way is it not working? Seems to work fine for me.

Also, please check the Reviewable Preview before submitting a comment to ensure correct formatting and citation.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt` line 45 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRhCO4NB9F0p0g-G4Lm:-NS3EjW8Aqlkk_LaHGJ0:bpr6wr9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb01e36c0f4b49675f4c8bed82521f747200519/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt#L45)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Rename to `isTitleEnabled`



_Code quote:_
```Kotlin
isTitleEnable
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt` line 61 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NS3EqB99BE005ZNgFYx:-NS3EqB99BE005ZNgFYy:b-w9y2ad) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/068efb1f560d22e1e216dda8958466ec8daeacc1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt#L61)):*
> ```Kotlin
> private fun getTitleAlpha(isEnable: Boolean): Float {
>     return if (isEnable) MullvadNotTransparent else MullvadTransparent20
> }
> ```

Unless this is used in multiple places this function isn't needed.



_Code quote:_
```Kotlin
private fun getTitleAlpha(isEnable: Boolean): Float {
    return if (isEnable) MullvadNotTransparent else MullvadTransparent20
}
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt` line 36 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWbxob6PHIehm_IexN:-NS3HIFzEB-OC8N4iMC-:b7gxtsz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c4574acb01ab5b9d6a33340c980a66c53e11c12c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt#L36)):*
> Might be nice to move these to separate files to make it easier to navigate

You seem to have cited the wrong thing here and my suggestion hasn't been made.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AdvancedFragment.kt` line 37 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NS3IVrfEMpdehfZYBq_:-NS3IVrfEMpdehfZYBqa:b-93w5ti) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/068efb1f560d22e1e216dda8958466ec8daeacc1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AdvancedFragment.kt#L37)):*
> ```Kotlin
>                     onToggleDnsClick = vm::onToggleDnsClick,
>                     onToggleBlockAds = vm::onToggleBlockAds,
>                     onToggleBlockTracker = vm::onToggleBlockTrackers,
> ```

nit: rename to `onToggleBlockTrackers` to match the vm function.



_Code quote:_
```Kotlin
onToggleBlockTracker
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModelState.kt` line 21 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NS3JESaASQwnNtdng9W:-NS3JESaASQwnNtdng9X:bp4hy9i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/068efb1f560d22e1e216dda8958466ec8daeacc1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModelState.kt#L21)):*
> ```Kotlin
>                 contentBlockersOptions.blockAdultContent||
>                 contentBlockersOptions.blockGambling
>             )
> ```

Since this can be derived from the `contentBlockersOptions` I suggest making this a function within the ui state class.



_Code quote:_
```Kotlin
        val isCustomDnsClickable = !(
            contentBlockersOptions.blockAds ||
                contentBlockersOptions.blockTrackers||
                contentBlockersOptions.blockMalware||
                contentBlockersOptions.blockAdultContent||
                contentBlockersOptions.blockGambling
            )
```


<!-- Sent from Reviewable.io -->

2023-04-03 11:42 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482)* status: 13 of 15 files reviewed, 14 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt` line 46 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRhCir3DTrFTEaQDv3c:-NS51p3A8J_SmDvAjTo_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb01e36c0f4b49675f4c8bed82521f747200519/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt#L46)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Please elaborate, in what way is it not working? Seems to work fine for me.

Also, please check the Reviewable Preview before submitting a comment to ensure correct formatting and citation.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt` line 45 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRhCO4NB9F0p0g-G4Lm:-NS52Mde2GJ9k_xxNINd:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb01e36c0f4b49675f4c8bed82521f747200519/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt#L45)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Rename to `isTitleEnabled`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt` line 61 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NS3EqB99BE005ZNgFYx:-NS53vBkEfI6mSESbK1r:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/068efb1f560d22e1e216dda8958466ec8daeacc1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt#L61)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Unless this is used in multiple places this function isn't needed.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt` line 31 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWc1SG6yAgY9tdBl6g:-NS55EBkBK672YLthYe_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c4574acb01ab5b9d6a33340c980a66c53e11c12c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt#L31)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest renaming to `ContentBlockersInfoDialog`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt` line 36 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWbxob6PHIehm_IexN:-NS55DAK0hvrGT45dksi:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c4574acb01ab5b9d6a33340c980a66c53e11c12c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt#L36)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

> Might be nice to move these to separate files to make it easier to navigate

You seem to have cited the wrong thing here and my suggestion hasn't been made.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt` line 38 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWbk1T25sfTd808fQR:-NS54yMVEOdYtYO00jqO:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c4574acb01ab5b9d6a33340c980a66c53e11c12c/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt#L38)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Might be nice to move these to separate files to make it easier to navigate
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt` line 45 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRhDbvm2eY3ud6eP7n9:-NS5SFOw1VZXTH8XgtT4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb01e36c0f4b49675f4c8bed82521f747200519/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt#L45)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why are both `info` and `warning` needed? Isn't one enough? Or can both be provided? If it's just a matter of styling it's probably better to handle by providing either a modifier or other argument like `isWarning: Boolean`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt` line 221 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRghReI2UdmQhZUSNDt:-NS5piFF2Ze32lVlI6Lr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb01e36c0f4b49675f4c8bed82521f747200519/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt#L221)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can be simplified using `copy`:

```
vmState.value.contentBlockersOptions.copy(blockAds = isEnabled)
```
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt` line 289 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRggW9hEvj-cZA1iP1D:-NS5qZ0NErZvSKj_CaYl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb01e36c0f4b49675f4c8bed82521f747200519/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt#L289)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Since this isn't exposed as an action to the view, it doesn't need to follow the same `on*` naming. I suggest renaming to something like `updateDefaultDnsOptionsViaRepository`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModelState.kt` line 75 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWdpNg5BuREgN3Q9eN:-NS5robz4r5kjAAXKB7E:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eab31ba346362755639fe9587d45acc3dbedd668/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModelState.kt#L75)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Rename to: `ContentBlockersInfoDialog` (`s` moved)
</blockquote></details>

Done.
___
*[`android/app/src/main/res/values/strings.xml` line 211 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWaBY02nigWK29sjwA:-NS5uxkF3tZP7T0rujc0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/91214320503af6620eeb160a98f19bdd1902c97d/android/app/src/main/res/values/strings.xml#L211)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest renaming to `dns_content_blockers_title`
</blockquote></details>

Done.
___
*[`android/app/src/main/res/values/strings.xml` line 215 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWaQ4k1TloUpbk9mj2:-NS5uy2t-6WI0Qp7d_ML:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/91214320503af6620eeb160a98f19bdd1902c97d/android/app/src/main/res/values/strings.xml#L215)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest renaming this and the other blockers to `block_*_title` to improve readability. If the usage changes we can just rename it to be less specific.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-05 10:41 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482)* status: all files reviewed, 7 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ContentBlockersInfoDialog.kt` line 11 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NSFzRRR11bnoHZU0znR:-NSFzRRR11bnoHZU0znS:b-wbr5qu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36fb19e4b7260fa49c7a64348e5c81ef66218c94/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ContentBlockersInfoDialog.kt#L11)):*
> ```Kotlin
>     InfoDialog(
>         message =
>         "${stringResource(id = R.string.dns_content_blockers_info)} \n\n\n " +
> ```

The trailing space causes the dialog text to look strange



_Code quote:_
```Kotlin
\n\n\n "
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ContentBlockersInfoDialog.kt` line 12 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NSFzcdRAIAWW_GGrPCc:-NSFzcdRAIAWW_GGrPCd:bahlntl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36fb19e4b7260fa49c7a64348e5c81ef66218c94/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ContentBlockersInfoDialog.kt#L12)):*
> ```Kotlin
>         message =
>         "${stringResource(id = R.string.dns_content_blockers_info)} \n\n\n " +
>             "${stringResource(id = R.string.dns_content_blockers_warning)}",
> ```

Fix this redundant string template. My IDE clearly complain about this, doesn't your IDE also do that?



_Code quote:_
```Kotlin
"${
```


<!-- Sent from Reviewable.io -->

2023-04-06 15:19 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482)* status: 9 of 20 files reviewed, 7 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt` line 46 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRhCir3DTrFTEaQDv3c:-NSKOwxT3hkt32eyRcOD:b-au4cf1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb01e36c0f4b49675f4c8bed82521f747200519/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt#L46)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Still looks the same
</blockquote></details>

suggested way of using "apply" sis not work, it should be like this:



_Code snippet (i):_
```Kotlin
var rowModifier: Modifier
    Modifier.apply {
        rowModifier = if (isRowEnabled) {
            this. clickable { onCellClicked() 
            }
        } else {
            this
        }
    }
```



_Code snippet (ii):_
```Kotlin
or 
```



_Code snippet (iii):_
```Kotlin
val rowModifier = Modifier.let {
            if (isRowEnabled) { it.clickable { onCellClicked() } } else it
        }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ContentBlockersInfoDialog.kt` line 11 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NSFzRRR11bnoHZU0znR:-NSKZkzg4_f_dDaZt_e8:bs7wumb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36fb19e4b7260fa49c7a64348e5c81ef66218c94/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ContentBlockersInfoDialog.kt#L11)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The trailing space causes the dialog text to look strange
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ContentBlockersInfoDialog.kt` line 12 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NSFzcdRAIAWW_GGrPCc:-NSK_-cDCo7686sDTapF:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36fb19e4b7260fa49c7a64348e5c81ef66218c94/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ContentBlockersInfoDialog.kt#L12)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Fix this redundant string template. My IDE clearly complain about this, doesn't your IDE also do that?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 175 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NRWdNgL43huik6x4IY8:-NSM01s80OQQGtBv6-9K:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b0cba059010057fb4649bb985090fd9bb769117a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L175)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Perhaps we should add a `itemWithDivider` to avoid all the duplicated `Divider()` calls?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Color.kt` line 6 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NSFZiMN18gQT7OikdZm:-NSKtTHKDqrdLr0QN2jy:b-sgpx6w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36fb19e4b7260fa49c7a64348e5c81ef66218c94/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Color.kt#L6)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this correct?
</blockquote></details>

it should be 0.33f, fixed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Color.kt` line 6 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NSF_bytA12OcvZrnN8u:-NSKtay92o7i5eC-pEWq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36fb19e4b7260fa49c7a64348e5c81ef66218c94/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Color.kt#L6)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

These should be `const` and I suggest naming them to:

`AlphaOpaque`
`Alpha20`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModelState.kt` line 21 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NS3JESaASQwnNtdng9W:-NSM5kQUCZ9u48dH5Hqk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/068efb1f560d22e1e216dda8958466ec8daeacc1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModelState.kt#L21)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Since this can be derived from the `contentBlockersOptions` I suggest making this a function within the ui state class.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-06 15:53 UTC, albin-mullvad requested changes
> Reviewed 11 of 11 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482)* status: all files reviewed, 4 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 15 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NSMEh9y2lbofxZio5IY):*
Here's a duplicate text in the commit message



_Code quote:_
```
 Add content blockers to the AdvancedSettingsScreen
```
___
*[`-- commits` line 23 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NSMEsriBgRpgF8OEdry):*
Will this be squashed?



_Code quote:_
```
Fix feedbacks
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Color.kt` line 6 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NSF_bytA12OcvZrnN8u:-NSMDXsUBPYvNPfLsA9_:b-5mw8qq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36fb19e4b7260fa49c7a64348e5c81ef66218c94/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Color.kt#L6)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still looks the same
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModelState.kt` line 21 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NS3JESaASQwnNtdng9W:-NSMDorpBEjuNt9A0sjS:b849d52) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/068efb1f560d22e1e216dda8958466ec8daeacc1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModelState.kt#L21)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What I meant with my previous comment is that we can remove the `isCustomDnsClickable` property  from the `AdvancedSettingsUiState` since this can be called from the view in the following way:

```
uiState.contentBlockersOptions.isAnyBlockerEnabled()
```


<!-- Sent from Reviewable.io -->

2023-04-11 08:42 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482)* status: 0 of 41 files reviewed, all discussions resolved (waiting on @albin-mullvad)

___
*[`-- commits` line 15 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-NSMEh9y2lbofxZio5IY):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Here's a duplicate text in the commit message
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-11 08:59 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 20 files at r12, 1 of 3 files at r13, 1 of 1 files at r14, 3 of 3 files at r15, 12 of 14 files at r16, 20 of 20 files at r17, 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482#-:-NSjXfjK5zbINtNylYx_:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-11 09:19 UTC, albin-mullvad approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4482)* status: 3 of 41 files reviewed, all discussions resolved (waiting on @sabercodic)



<!-- Sent from Reviewable.io -->

2023-04-11 09:34 UTC, merged