Delay tunnel reconnection after private key rotation
mullvad/mullvadvpn-app pull request #4497
Opened 2023-03-28 08:03 UTC by rablador

When a WireGuard key is rotated, if the user is connected, the tunnel shouldn't be reconnected immediately. Instead, it should reconnect after 120 seconds to allow for latency when relays are synched.

2023-03-28 10:18 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @rablador)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRbhTKL69ZMbSzMRLez:-NRbhTKL69ZMbSzMRLf-:b8a282) (no related file):*
As we spoke earlier, it's better to have a separate IPC endpoint to tell the tunnel that key rotation took place. In response the tunnel should simply start a 2 min timer before reconnecting.

This PR has a flaw where device state is fetched after key is already rotated. Ideally we want `makeConfiguration` to store the last device data in a variable.

If user initiates reconnection requests before 2 minutes passed since last key rotation, we should still keep the old device state around and only swap it 2 minutes after. There are ways to achieve that, the timer could fire reconnect with a flag that would tell the `makeConfiguration()` to replace old device state or we could rely on `creationDate + 2min <= Date()` before we decide if the new device data can be used.

___
___
*[`ios/CHANGELOG.md` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRbh9Q5E3dLgKKuYxTg:-NRbh9Q5E3dLgKKuYxTh:b-n9788p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ce3641eb51bd7294adfac2cbc49dd0accfdf8cf/ios/CHANGELOG.md#L47)):*
> ```Markdown
>   otherwise display days.
> - Changed key rotation interval from 4 to 7 days.
> - Delay tunnel reconnection after a WireGuard private key rotates. Accounts for latency when
> ```

I'd perhaps reword the second part of that to say that it "accounts for latency in key propagation to relays". Because "relays are synced" is a bit broad.


<!-- Sent from Reviewable.io -->

2023-03-28 10:20 UTC, pronebird requested changes
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 425 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRbikKLA_prJfrUGI_s:-NRbikKM8k5_tlueI_cE:b-m9ew8f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ce3641eb51bd7294adfac2cbc49dd0accfdf8cf/ios/PacketTunnel/PacketTunnelProvider.swift#L425)):*
> ```Swift
>     // MARK: - Private
> 
>     private func startTunnelReconnectionTimer(
> ```

Tunnel manager may not survive 2 minutes of runtime, so packet tunnel should run the timer instead. Send IPC request telling the packet tunnel that key rotation has happened and that it needs to start counting 2 min before reconnecting the tunnel.


<!-- Sent from Reviewable.io -->

2023-03-28 10:22 UTC, pronebird reviewed
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497)* status: all files reviewed, 3 unresolved discussions (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-03-28 12:45 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @pronebird)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRbhTKL69ZMbSzMRLez:-NRbzwoi4OgduAVUOfF8:bvaxcfn) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

As we spoke earlier, it's better to have a separate IPC endpoint to tell the tunnel that key rotation took place. In response the tunnel should simply start a 2 min timer before reconnecting.

This PR has a flaw where device state is fetched after key is already rotated. Ideally we want `makeConfiguration` to store the last device data in a variable.

If user initiates reconnection requests before 2 minutes passed since last key rotation, we should still keep the old device state around and only swap it 2 minutes after. There are ways to achieve that, the timer could fire reconnect with a flag that would tell the `makeConfiguration()` to replace old device state or we could rely on `creationDate + 2min <= Date()` before we decide if the new device data can be used.

</blockquote></details>

I think a flag would be best here since relying solely on creation date wouldn't let us know if the reconnection was triggered by eg. the user.

___
___
*[`ios/CHANGELOG.md` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRbh9Q5E3dLgKKuYxTg:-NRc6gnI41RGMaTA3f40:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ce3641eb51bd7294adfac2cbc49dd0accfdf8cf/ios/CHANGELOG.md#L47)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I'd perhaps reword the second part of that to say that it "accounts for latency in key propagation to relays". Because "relays are synced" is a bit broad.
</blockquote></details>

Done.
___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 425 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRbikKLA_prJfrUGI_s:-NRc6Vqz7mLA2I1RNC6w:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ce3641eb51bd7294adfac2cbc49dd0accfdf8cf/ios/PacketTunnel/PacketTunnelProvider.swift#L425)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Tunnel manager may not survive 2 minutes of runtime, so packet tunnel should run the timer instead. Send IPC request telling the packet tunnel that key rotation has happened and that it needs to start counting 2 min before reconnecting the tunnel.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-28 13:17 UTC, pronebird requested changes
> Reviewed 1 of 9 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @rablador)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRbhTKL69ZMbSzMRLez:-NRcKCMY2qltOX4D4-HL:btd51a6) (no related file):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I think a flag would be best here since relying solely on creation date wouldn't let us know if the reconnection was triggered by eg. the user.
</blockquote></details>

I agree.

___
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 553 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRcMF8t7QP-939R-tyH:-NRcMF8t7QP-939R-tyI:bnpq46k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a5a48fc53aa6ca721ee5bf52745a1ffae3d1ed2c/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L553)):*
> ```Swift
>         )
> 
>         operation.addCondition(
> ```

I'd simply chain both operations at the start and put both into group so that the entire group has exclusivity + background execution.

```swift
let notifyOperation = AsyncBlockOperation(dispatchQueue: internalQueue) {
    self.tunnel?.notifyKeyRotation(completionHandler: { result in
        // log result.error?
    })

    // We don't have to wait for this operation to finish.
    // So it will finish() automatically at the end of scope.
}
notifyOperation.addCondition(NoFailedDependenciesCondition(ignoreCancellations: false))
notifyOperation.addDependency(operation)

let groupOperation = GroupOperation(operations: [operation, notifyOperation])

groupOperation.addCondition(MutuallyExclusive(category: OperationCategory.deviceStateUpdate.category))
groupOperation.addObserver(
    BackgroundObserver(
        application: application,
        name: "Rotate private key",
        cancelUponExpiration: true
    )
)

operationQueue.addOperation(groupOperation)
```


<!-- Sent from Reviewable.io -->

2023-03-28 13:20 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497)* status: 2 of 9 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/TunnelManager/NotifyKeyRotationOperation.swift` line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRcMssY1-kqNFV1aIU5:-NRcMssY1-kqNFV1aIU6:b-ns0ik) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a5a48fc53aa6ca721ee5bf52745a1ffae3d1ed2c/ios/MullvadVPN/TunnelManager/NotifyKeyRotationOperation.swift#L13)):*
> ```Swift
> import Operations
> 
> class NotifyKeyRotationOperation: ResultOperation<Void> {
> ```

This is a bit superficial operation and it can be replaced with block operation as proposed below. (see other comment)


<!-- Sent from Reviewable.io -->

2023-03-28 14:01 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 553 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRcMF8t7QP-939R-tyH:-NRcWY7Y5PXskd1wLacn:b2j6a32) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a5a48fc53aa6ca721ee5bf52745a1ffae3d1ed2c/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L553)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Actually I guess, wait for `notifyOperation` to finish because this method is called from background task and we don't want to end up in suspended state before we call the IPC
</blockquote></details>

Scrape that..


<!-- Sent from Reviewable.io -->

2023-03-28 14:03 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/TunnelManager/NotifyKeyRotationOperation.swift` line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRcWhjsE4sNEzV5Yp_0:-NRcWhjsE4sNEzV5Yp_1:bxe6w0i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a5a48fc53aa6ca721ee5bf52745a1ffae3d1ed2c/ios/MullvadVPN/TunnelManager/NotifyKeyRotationOperation.swift#L13)):*
> ```Swift
> import Operations
> 
> class NotifyKeyRotationOperation: ResultOperation<Void> {
> ```

Simply send an IPC from `RotateKeyOperation`, something like that in `didRotateKey()`:

```swift
if let tunnel = interactor.tunnel {
    tunnel.notifyKeyRotation { _ in
        finish(result: .success(true))
    }
} else {
    finish(result: .success(true))
}
```


<!-- Sent from Reviewable.io -->

2023-03-28 21:18 UTC, rablador reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-:-NRe4V7_00jG6hNJD0yV:bnfp4nl)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @pronebird)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRbhTKL69ZMbSzMRLez:-NRe4Edb5Sc6DR3Kkr2a:b-896fix) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I agree.
</blockquote></details>

Done.

___
___
*[`ios/MullvadVPN/TunnelManager/NotifyKeyRotationOperation.swift` line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRcMssY1-kqNFV1aIU5:-NRe4OoZ1RNHdHYZgnLY:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a5a48fc53aa6ca721ee5bf52745a1ffae3d1ed2c/ios/MullvadVPN/TunnelManager/NotifyKeyRotationOperation.swift#L13)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This is a bit superficial operation and it can be replaced with block operation as proposed below. (see other comment)
</blockquote></details>

Removed.
___
*[`ios/MullvadVPN/TunnelManager/NotifyKeyRotationOperation.swift` line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRcWhjsE4sNEzV5Yp_0:-NRe4TNq1ExNnUq-cL5Z:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a5a48fc53aa6ca721ee5bf52745a1ffae3d1ed2c/ios/MullvadVPN/TunnelManager/NotifyKeyRotationOperation.swift#L13)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Simply send an IPC from `RotateKeyOperation`, something like that in `didRotateKey()`:

```swift
if let tunnel = interactor.tunnel {
    tunnel.notifyKeyRotation { _ in
        finish(result: .success(true))
    }
} else {
    finish(result: .success(true))
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-29 07:51 UTC, pronebird requested changes
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/TunnelManager/RotateKeyOperation.swift` line 89 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRgK16E0nstm6D_5Wca:-NRgK16E0nstm6D_5Wcb:bhnyd6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb9f62bca847825a84a5a81eb28194a49af2dad8/ios/MullvadVPN/TunnelManager/RotateKeyOperation.swift#L89)):*
> ```Swift
> 
>     private func didRotateKey(newPrivateKey: PrivateKey, result: Result<REST.Device, Error>) {
>         guard let tunnel = interactor.tunnel else {
> ```

Perhaps don't fail key rotation altogether if the tunnel is not there. User may delete the tunnel any time from System Settings. Instead send IPC if the tunnel is set, otherwise finish as normal.


<!-- Sent from Reviewable.io -->

2023-03-29 08:49 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/MullvadVPN/TunnelManager/RotateKeyOperation.swift` line 89 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497#-NRgK16E0nstm6D_5Wca:-NRgY_Al0iJbAY6l2Ehw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb9f62bca847825a84a5a81eb28194a49af2dad8/ios/MullvadVPN/TunnelManager/RotateKeyOperation.swift#L89)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Perhaps don't fail key rotation altogether if the tunnel is not there. User may delete the tunnel any time from System Settings. Instead send IPC if the tunnel is set, otherwise finish as normal.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-29 09:01 UTC, pronebird approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-03-29 09:22 UTC, pronebird reviewed
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-03-29 09:22 UTC, merged