Persist last key rotation date to determine next scheduled rotation
mullvad/mullvadvpn-app pull request #4517
Opened 2023-04-03 22:56 UTC by rablador

If the current private key is old enough to be rotated, the app will always try to do so immediately on wake/start. If the API is down or rotation for some reason keeps failing, this can lead to more rotation attempts than the default rotation interval allows. By persisting last rotation date we can make sure that the intended interval is respected.

2023-04-04 08:58 UTC, pronebird requested changes
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/TunnelManager/SetAccountOperation.swift` line 416 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517#-NSASzt2ClBrO4P3yqwy:-NSASzt37gDKagu00ZHl:bo59ivj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ac0753740831cdbc572bd786034c979f1f54f70/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L416)):*
> ```Swift
>                     ipv6Address: device.ipv6Address,
>                     wgKeyData: StoredWgKeyData(
>                         creationDate: keyCreationDate,
> ```

Maybe just leave it as is with Date() in here? The change seems superficial.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 153 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517#-NSAU9YW2kNJVlQF_XDH:-NSAU9YW2kNJVlQF_XDI:b-ccedr2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfbb2864773034b2281f20351d94996ee0a27a58/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L153)):*
> ```Swift
>             // Do not rotate the key if account or device is not found.
>             if let restError = completion.error as? REST.Error,
>                restError.compareErrorCode(.invalidAccount) ||
> ```

Ideally we should log out user if we see `.invalidAccount`. This can happen if you create a new account and never top it up. Then eventually it's being removed on our backend.


<!-- Sent from Reviewable.io -->

2023-04-04 09:03 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 153 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517#-NSAU9YW2kNJVlQF_XDH:-NSAVFEW4OE2AywC5RGH:b-y3po3m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfbb2864773034b2281f20351d94996ee0a27a58/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L153)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Ideally we should log out user if we see `.invalidAccount`. This can happen if you create a new account and never top it up. Then eventually it's being removed on our backend.
</blockquote></details>

So in that regard continuing key rotation for account the doesn't exist anymore will always fail so it would make sense to switch to loggedOut state.


<!-- Sent from Reviewable.io -->

2023-04-04 09:11 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 143 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517#-NSAVxY-DC8H3mSYNf6F:-NSAVxY-DC8H3mSYNf6G:b9zk3ss) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ac0753740831cdbc572bd786034c979f1f54f70/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L143)):*
> ```Swift
> 
>         let nextRotationDate: Date
>         if let lastAttemptDate = deviceData.wgKeyData.lastRotationAttemptDate {
> ```

Working with dates is always ugly. How about we make a struct describing all intervals, i.e:

```swift
struct KeyRotationConfiguration {
   let rotationInterval: TimeInterval = ...
   let retryInterval: TimeInterval = ...
}
```

Then we can pass it here in rotation operation too and perhaps use default initializer to fill in the values.

Then we can also add extension on `StoredWgKeyData` something along the lines of:

```swift
extension StoredWgKeyData {
   func getNextRotationDate(configuration: KeyRotationConfiguration) -> Date { 
       return max(Date(), lastAttemptDate?.addingTimeInterval(configuration.retryInterval) ?? creationDate.addingTimeInterval(configuration.retryInterval))
   }
}
```

This should offload tunnel manager a bit as we have a lot of code in it already.


<!-- Sent from Reviewable.io -->

2023-04-04 09:19 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 449 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517#-NSAYtIyA-BgtO9ZsrYl:-NSAYtIyA-BgtO9ZsrYm:b-v35dk0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ac0753740831cdbc572bd786034c979f1f54f70/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L449)):*
> ```Swift
>             interactor: TunnelInteractorProxy(self),
>             devicesProxy: devicesProxy,
>             rotationInterval: privateKeyRotationInterval,
> ```

As I mentioned above maybe passing a struct with all intervals would be beneficial to improve code readability.


<!-- Sent from Reviewable.io -->

2023-04-04 13:37 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517)* status: all files reviewed, 4 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/TunnelManager/SetAccountOperation.swift` line 416 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517#-NSASzt2ClBrO4P3yqwy:-NSBKl_77BnZk_Vn3Wqz:buwkswy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ac0753740831cdbc572bd786034c979f1f54f70/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L416)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe just leave it as is with Date() in here? The change seems superficial.
</blockquote></details>

Leftover from when lastRotationAttemptDate wasn't nil. Fixed now.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 143 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517#-NSAVxY-DC8H3mSYNf6F:-NSBPS9A76WMs3gP9RgU:b4dlvei) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ac0753740831cdbc572bd786034c979f1f54f70/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L143)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Working with dates is always ugly. How about we make a struct describing all intervals, i.e:

```swift
struct KeyRotationConfiguration {
   let rotationInterval: TimeInterval = ...
   let retryInterval: TimeInterval = ...
}
```

Then we can pass it here in rotation operation too and perhaps use default initializer to fill in the values.

Then we can also add extension on `StoredWgKeyData` something along the lines of:

```swift
extension StoredWgKeyData {
   func getNextRotationDate(configuration: KeyRotationConfiguration) -> Date { 
       return max(Date(), lastAttemptDate?.addingTimeInterval(configuration.retryInterval) ?? creationDate.addingTimeInterval(configuration.retryInterval))
   }
}
```

This should offload tunnel manager a bit as we have a lot of code in it already.
</blockquote></details>

Much nicer!
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 153 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517#-NSAU9YW2kNJVlQF_XDH:-NSBThoaCnLUQ67CxvCw:b9hao1t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfbb2864773034b2281f20351d94996ee0a27a58/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L153)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

So in that regard continuing key rotation for account the doesn't exist anymore will always fail so it would make sense to switch to loggedOut state.
</blockquote></details>

Not sure I follow. I agree with the logic, but I don't think it should be handled in this function.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 449 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517#-NSAYtIyA-BgtO9ZsrYl:-NSBPiho9lDtaSB8M0sa:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ac0753740831cdbc572bd786034c979f1f54f70/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L449)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

As I mentioned above maybe passing a struct with all intervals would be beneficial to improve code readability.
</blockquote></details>

Done.



_Code quote:_
```Swift
return max(nextRotationDate, Date())
```


<!-- Sent from Reviewable.io -->

2023-04-05 08:35 UTC, pronebird reviewed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-04-05 12:17 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 153 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517#-NSAU9YW2kNJVlQF_XDH:-NSGLE5O8S8ycmSZp1Jv:bkb3gl3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfbb2864773034b2281f20351d94996ee0a27a58/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L153)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Not here for sure.
</blockquote></details>

Added checks for invalid account and device not found.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 132 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517#-NSBu8JQ-WN0HxhVXAMF:-NSFE76kAna0A4ZxHIEu:b44tpx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db70cb338f8f8d81ac7f68f2561dced9b2855ffa/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L132)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This guard can be avoided by using `deviceState.deviceData` which returns `StoredDeviceData` when logged in otherwise `nil`:

```swift
return deviceState.deviceData?.wgKeyData.getNextRotationDate(for: StoredWgKeyData.KeyRotationConfiguration())
```
</blockquote></details>

👍


<!-- Sent from Reviewable.io -->

2023-04-05 12:38 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517#-:-NSGQBwmAkW99mFDsVZ2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-05 12:43 UTC, merged