WIP
mullvad/mullvadvpn-app pull request #4532
Opened 2023-04-06 13:27 UTC by rablador

2023-04-13 11:17 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: 0 of 32 files reviewed, 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NSuKDE58WfK5A4oKB_A:-NSuKDE58WfK5A4oKB_B:bwg5kbq) (no related file):*
Many images were updated when running the asset conversion script. Only IconInfo is new.

___
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 57 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NSuIbWa2HaIc9IMFUQY:-NSuIbWbCa70ly0ePv-T:b-l1hvek) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/742c652ee665876ce01071a8cd10fe45efa8526c/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L57)):*
> ```Swift
>     override func viewWillAppear(_ animated: Bool) {
>         super.viewWillAppear(animated)
>         tableView
> ```

Adding the header view in viewDidLoad generates an error about tableview being told to layout its visible cells and other contents without being in the view hierarchy. Adding it here instead seems to help.


<!-- Sent from Reviewable.io -->

2023-04-14 07:34 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: 0 of 32 files reviewed, 4 unresolved discussions

___
*[`ios/MullvadVPN/View controllers/Settings/SettingsCell.swift` line 123 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NSyfvvpD18PywS0dl9G:-NSyfvvq74oOYmAwKu5g:b-aoom5e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bcce1731cc5d4c7893b7e9d98506019f9dca02c7/ios/MullvadVPN/View%20controllers/Settings/SettingsCell.swift#L123)):*
> ```Swift
>             infoButton.leadingAnchor.constraint(
>                 equalTo: titleLabel.trailingAnchor,
>                 constant: -UIMetrics.interButtonSpacing
> ```

Perhaps a more correct way would be to let the button be native size and then adjust the touch area (`point(inside...)`), but simply moving the button to the left and "over" the title works pretty well too. Suggestions?
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsContentBlockersHeaderView.swift` line 84 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NSyg-pjDVuXTGYMIak5:-NSyg-pjDVuXTGYMIak6:b-aoom5e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bcce1731cc5d4c7893b7e9d98506019f9dca02c7/ios/MullvadVPN/View%20controllers/Settings/SettingsContentBlockersHeaderView.swift#L84)):*
> ```Swift
>             infoButton.leadingAnchor.constraint(
>                 equalTo: titleLabel.trailingAnchor,
>                 constant: -UIMetrics.interButtonSpacing
> ```

Perhaps a more correct way would be to let the button be native size and then adjust the touch area (`point(inside...)`), but simply moving the button to the left and "over" the title works pretty well too. Suggestions?


<!-- Sent from Reviewable.io -->

2023-04-17 09:47 UTC, buggmagnet requested changes
> Reviewed 26 of 32 files at r2, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: 27 of 33 files reviewed, 6 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift` line 110 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTDUe9k0jUvcRaokYMC:-NTDUe9k0jUvcRaokYMD:b-9wlq71) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa32847adffc5c77ba57829f0b4e853afac8d3b6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesCellFactory.swift#L110)):*
> ```Swift
>             cell.accessibilityHint = nil
>             cell.applySubCellStyling()
>             cell.setInfoButtonIsVisible(true)
> ```

Isn't it a bit overkill to have a method just for that when doing `infoButton.isHidden = false` is less code and achieves the same result ?
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 57 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NSuIbWa2HaIc9IMFUQY:-NTDSm4ZD1W54Wbz0t3R:b-3a1hj3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/742c652ee665876ce01071a8cd10fe45efa8526c/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L57)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Adding the header view in viewDidLoad generates an error about tableview being told to layout its visible cells and other contents without being in the view hierarchy. Adding it here instead seems to help.
</blockquote></details>

That's because we do update the cell views in the `viewDidLoad` method. 
If you set the `tableHeaderView` after the call to `dataSource?.update(from: interactor.dnsSettings)` in `viewDidLoad` the warning is not issued anymore.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsCell.swift` line 123 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTDDhgV8oSVOpbcoaGf:-NTDDhgV8oSVOpbcoaGg:bniyr17) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa32847adffc5c77ba57829f0b4e853afac8d3b6/ios/MullvadVPN/View%20controllers/Settings/SettingsCell.swift#L123)):*
> ```Swift
>             infoButton.leadingAnchor.constraint(
>                 equalTo: titleLabel.trailingAnchor,
>                 constant: -UIMetrics.interButtonSpacing
> ```

Small pet peeve of mine, but I think it's a code smell when we have negative values in layout constraints constants.
If we swap the order of the constraint like so
```
titleLabel.trailingAnchor.constraint(equalTo: infoButton.leadingAnchor, constant: UIMetrics.interButtonSpacing)
```

We should be able to get rid of that `-` sign. It's easy to miss, and it makes it harder to reason about values when you have to deal with both positive and negative values.


<!-- Sent from Reviewable.io -->

2023-04-17 12:12 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: 27 of 33 files reviewed, 6 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift` line 110 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTDUe9k0jUvcRaokYMC:-NTE3upDApJHiqzCSppQ:b-cc7mem) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa32847adffc5c77ba57829f0b4e853afac8d3b6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesCellFactory.swift#L110)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Isn't it a bit overkill to have a method just for that when doing `infoButton.isHidden = false` is less code and achieves the same result ?
</blockquote></details>

I don't disagree, but since infoButton is private I thought it unnecessary to expose if just for this one thing.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 57 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NSuIbWa2HaIc9IMFUQY:-NTE4cfSAT39Xorm6mQY:b3t1g35) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/742c652ee665876ce01071a8cd10fe45efa8526c/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L57)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

That's because we do update the cell views in the `viewDidLoad` method. 
If you set the `tableHeaderView` after the call to `dataSource?.update(from: interactor.dnsSettings)` in `viewDidLoad` the warning is not issued anymore.
</blockquote></details>

Ah, that's better.



_Code quote:_
```Swift
tableView.tableHeaderView
```
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsCell.swift` line 123 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTDDhgV8oSVOpbcoaGf:-NTE4ldGAClJqgPqeMEc:b-a1tfos) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa32847adffc5c77ba57829f0b4e853afac8d3b6/ios/MullvadVPN/View%20controllers/Settings/SettingsCell.swift#L123)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Small pet peeve of mine, but I think it's a code smell when we have negative values in layout constraints constants.
If we swap the order of the constraint like so
```
titleLabel.trailingAnchor.constraint(equalTo: infoButton.leadingAnchor, constant: UIMetrics.interButtonSpacing)
```

We should be able to get rid of that `-` sign. It's easy to miss, and it makes it harder to reason about values when you have to deal with both positive and negative values.

</blockquote></details>

I don't agree on this one. To me the direction - or context - is more important than the value. In this case the context is the `infoButton` and it's relation to others, ie we're positioning the `infoButton` in relation to the label rather than the opposite.

A better example is when we have a single view constrained to a superview, with margins. To me the subview is the thing being positioned, so the direction should be subview anchors -> superview anchors. It makes little sense constraining the superview to the subview.

I know that the Apple docs suggest switching the order to eliminate negative values, so I'm probably not in the majority here. It's fine to change it according to your suggestion, but I thought I'd give my perspective on it at least. :)


<!-- Sent from Reviewable.io -->

2023-04-18 08:03 UTC, buggmagnet reviewed
> Reviewed 2 of 32 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: 30 of 33 files reviewed, 6 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Settings/SettingsCell.swift` line 123 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTDDhgV8oSVOpbcoaGf:-NTIK9MO2K-8OqAPn0jh:b-4rxn02) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa32847adffc5c77ba57829f0b4e853afac8d3b6/ios/MullvadVPN/View%20controllers/Settings/SettingsCell.swift#L123)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I don't agree on this one. To me the direction - or context - is more important than the value. In this case the context is the `infoButton` and it's relation to others, ie we're positioning the `infoButton` in relation to the label rather than the opposite.

A better example is when we have a single view constrained to a superview, with margins. To me the subview is the thing being positioned, so the direction should be subview anchors -> superview anchors. It makes little sense constraining the superview to the subview.

I know that the Apple docs suggest switching the order to eliminate negative values, so I'm probably not in the majority here. It's fine to change it according to your suggestion, but I thought I'd give my perspective on it at least. :)
</blockquote></details>

Apple also says that "You should choose the solution that most clearly describes your intent".
And that being consistent is better than being right. 


My point of view, is that we think "left to right".
However, reading that constraint, we take a leading anchor (left), constrain it to a trailing anchor (right) but then we go in the opposite direction (negative constant). 

In both cases (negative or positive constant value), we are constraining two items in relation to each other, I think it's incorrect to say that we're placing `infoButton` in relation to `titleLabel` rather than the opposite, because this constraint directly affects `titleLabel` too.

Let's leave this for now as it is because ultimately it's not that important. But for future decisions, we should decide to a style and commit to it. Ideally, a style that everyone is happy with !


<!-- Sent from Reviewable.io -->

2023-04-18 09:51 UTC, mojganii reviewed
take a look at these comments and let me know what you think!

2023-04-18 09:51 UTC, mojganii commented on ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift
> +            return UITableView.automaticDimension
I think maybe it's better to set fixed value for header. automatic dimension caused overhead while the header is not going to be grown up dynamically

2023-04-18 09:51 UTC, mojganii commented on ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift
> +        newSnapshot.appendSections([.contentBlockers, .customDNS])
If I were you,I would conform CaseIterable protocol to have access all cases by .allCases.It makes much easier for us to keep future changes simpler

2023-04-18 09:51 UTC, mojganii commented on ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift
> +            let contentBlockers: [Item] = [
maybe it's better to group the options based on their section.

2023-04-18 11:43 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: 30 of 33 files reviewed, 9 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 274 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#gh-1169765271:-NTJ5qZg9vRXvZ8xX9gb:b-a3pf6r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbc54bf51c50ebf7d94c638eef59eff494701afc/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L274)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I think maybe it's better to set fixed value for header. automatic dimension caused overhead while the header is not going to be grown up dynamically
</blockquote></details>

I see your point, but there are two things at play here. The content blocker header is a real header, while the dns settings header is not. It's actually a regular cell. So, in order to sync the heights I made the content blocker header work the same way as the cell, ie height being determined by the size of the label. 

The optimal solution might be to turn the dns header into a real header as well, but that would require some rework of the whole data source content structure.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 367 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#gh-1169770850:-NTJ8VB97PLAAwL_hEyX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbc54bf51c50ebf7d94c638eef59eff494701afc/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L367)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

If I were you,I would conform CaseIterable protocol to have access all cases by .allCases.It makes much easier for us to keep future changes simpler
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 577 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#gh-1169777426:-NTJ98Wd5XyNSV3Gn1gD:bk3cn80) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbc54bf51c50ebf7d94c638eef59eff494701afc/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L577)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

maybe it's better to group the options based on their section.
</blockquote></details>

I'd rather not change how Item is structured (would require rework of data source), but I created a static var for content blockers on it.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsCell.swift` line 123 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTDDhgV8oSVOpbcoaGf:-NTJ7uHOATdBelsorChm:b-gqdwow) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa32847adffc5c77ba57829f0b4e853afac8d3b6/ios/MullvadVPN/View%20controllers/Settings/SettingsCell.swift#L123)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Apple also says that "You should choose the solution that most clearly describes your intent".
And that being consistent is better than being right. 


My point of view, is that we think "left to right".
However, reading that constraint, we take a leading anchor (left), constrain it to a trailing anchor (right) but then we go in the opposite direction (negative constant). 

In both cases (negative or positive constant value), we are constraining two items in relation to each other, I think it's incorrect to say that we're placing `infoButton` in relation to `titleLabel` rather than the opposite, because this constraint directly affects `titleLabel` too.

Let's leave this for now as it is because ultimately it's not that important. But for future decisions, we should decide to a style and commit to it. Ideally, a style that everyone is happy with !
</blockquote></details>

Agreed, we should decide on something that we all can stick to.


<!-- Sent from Reviewable.io -->

2023-04-19 15:11 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: 29 of 33 files reviewed, 8 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NSuKDE58WfK5A4oKB_A:-NTP1sNRDs4M0FHn8Ndn:b-qntprj) (no related file):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Many images were updated when running the asset conversion script. Only IconInfo is new.
</blockquote></details>

Are there actual changes or metadata noise? If it's metadata noise then I'd only commit new asset and discaard the rest.

___
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsCell.swift` line 123 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NSyfvvpD18PywS0dl9G:-NTP2TpY0w5PeI0c6365:bi12mcd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bcce1731cc5d4c7893b7e9d98506019f9dca02c7/ios/MullvadVPN/View%20controllers/Settings/SettingsCell.swift#L123)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Perhaps a more correct way would be to let the button be native size and then adjust the touch area (`point(inside...)`), but simply moving the button to the left and "over" the title works pretty well too. Suggestions?
</blockquote></details>

Similar to other instance we have here. As long as it does not break the UI it's fine to keep it this way for now.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsCell.swift` line 123 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTDDhgV8oSVOpbcoaGf:-NTOxr1Q4R-7tMgwY8Id:bnrw8wl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa32847adffc5c77ba57829f0b4e853afac8d3b6/ios/MullvadVPN/View%20controllers/Settings/SettingsCell.swift#L123)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Agreed, we should decide on something that we all can stick to.
</blockquote></details>

Personally, I flip first and second views to avoid negative values but I wouldn't be blocking this PR because of this. It's also possible to add some sort of helper to our builder to pin edges of two individual views, which then would flip it for us to eliminate negative values.

Same could be applied to  `pinEdges()` family of methods in autolayout builder which currently produce negative constants. It's probably easier to debug UI when all values are positive.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsContentBlockersHeaderView.swift` line 84 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NSyg-pjDVuXTGYMIak5:-NTOzyw07VuqadNhefZ2:bdeady5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bcce1731cc5d4c7893b7e9d98506019f9dca02c7/ios/MullvadVPN/View%20controllers/Settings/SettingsContentBlockersHeaderView.swift#L84)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Perhaps a more correct way would be to let the button be native size and then adjust the touch area (`point(inside...)`), but simply moving the button to the left and "over" the title works pretty well too. Suggestions?
</blockquote></details>

You could also implement `func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView?`, but that requires a bit of math and coordinate conversion. I am just not sure it's needed since you fixed that issue with constraints, but I can imagine it may become an issue with introduction of Dynamic Type. Maybe leave it as is for now?


<!-- Sent from Reviewable.io -->

2023-04-19 15:33 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: 29 of 33 files reviewed, 9 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/View controllers/Settings/SettingsContentBlockersHeaderView.swift` line 124 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTP8H0h6WrKxO3oKZiI:-NTP8H0i51Ski1tsoXdZ:bru5tym) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/49b1bf5a161c0868edbb9ffe50feb494ae41890a/ios/MullvadVPN/View%20controllers/Settings/SettingsContentBlockersHeaderView.swift#L124)):*
> ```Swift
>             ? NSLocalizedString(
>                 "SELECT_LOCATION_COLLAPSE_ACCESSIBILITY_ACTION",
>                 tableName: "SelectLocation",
> ```

Accessibility labels are copied from somewhere else but not updated to reflect that we're expanding a list of content blockers and not "locations"


<!-- Sent from Reviewable.io -->

2023-04-19 16:22 UTC, pronebird reviewed
> Reviewed 2 of 32 files at r2, 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: 32 of 33 files reviewed, 9 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)



<!-- Sent from Reviewable.io -->

2023-04-20 09:36 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: 8 of 33 files reviewed, 8 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NSuKDE58WfK5A4oKB_A:-NTP5R1D2uNck2zWKRpl:bhotci7) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Are there actual changes or metadata noise? If it's metadata noise then I'd only commit new asset and discaard the rest.
</blockquote></details>

I think is was discussed in chat that this is just noise. Will discard the rest.

___
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift` line 110 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTDUe9k0jUvcRaokYMC:-NTSWVGbBELaB_IJkfch:b44tpx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa32847adffc5c77ba57829f0b4e853afac8d3b6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesCellFactory.swift#L110)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

For future reference:

We could introduce a model and let the cell configure itself based on provided data. It's a bit more work but it eliminates the need to configure each cell within a huge switch+case. It also eliminates quite a bit of code repetition. For example:

```swift
struct ContentBlockerItemConfiguration {
  var title: String // titleLabel
  var isOn: Bool
  var accessibilityHint: String?
  // etc...
}

extension SettingsSwitchCell {
  func update(from model: ContentBlockerItemConfiguration) {
      titleLabel.text = model.title
      // etc..
  }
}
```
</blockquote></details>

👍
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsContentBlockersHeaderView.swift` line 84 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NSyg-pjDVuXTGYMIak5:-NTP4t-IDZHqZZnwLnj6:b-gtfq9f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bcce1731cc5d4c7893b7e9d98506019f9dca02c7/ios/MullvadVPN/View%20controllers/Settings/SettingsContentBlockersHeaderView.swift#L84)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You could also implement `func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView?`, but that requires a bit of math and coordinate conversion. I am just not sure it's needed since you fixed that issue with constraints, but I can imagine it may become an issue with introduction of Dynamic Type. Maybe leave it as is for now?
</blockquote></details>

Yeah, let's see if we need to change it later. Then we could create a helper for it or something.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsContentBlockersHeaderView.swift` line 124 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTP8H0h6WrKxO3oKZiI:-NTSXDnXAAJEVCoXhBrR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/49b1bf5a161c0868edbb9ffe50feb494ae41890a/ios/MullvadVPN/View%20controllers/Settings/SettingsContentBlockersHeaderView.swift#L124)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Accessibility labels are copied from somewhere else but not updated to reflect that we're expanding a list of content blockers and not "locations"
</blockquote></details>

Done.



_Code quote:_
```Swift
ELECT_LOCATION_COLLAPSE_ACCESSIBILITY_ACTIO
```


<!-- Sent from Reviewable.io -->

2023-04-20 11:50 UTC, pronebird reviewed
> Reviewed 2 of 32 files at r2, 13 of 26 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: 20 of 33 files reviewed, 6 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/CHANGELOG.md` line 35 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTTU7zC7ggu2EQryzzl:-NTTU7zC7ggu2EQryzzm:b-gj1d5m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c64f89ba382740b20c532564bad7c62e95346bce/ios/CHANGELOG.md#L35)):*
> ```Markdown
>   propagation to relays.
> ```

Nit: We do have two newlines between unreleased and released blocks. So maybe just discard changes you have made to reduce the diff


<!-- Sent from Reviewable.io -->

2023-04-20 11:50 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r5, 2 of 26 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: 22 of 33 files reviewed, 6 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)



<!-- Sent from Reviewable.io -->

2023-04-21 11:11 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 5 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-:-NTYViXd1L0lgVsivbu8:bnfp4nl)* status: 23 of 34 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2023-04-24 09:19 UTC, buggmagnet approved these changes
> Reviewed 10 of 26 files at r10, 1 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: all files reviewed, 7 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 66 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTmXbgZ5vp4WcSof2pk:-NTmXbgZ5vp4WcSof2pl:bx6kz6r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f165c053e65ab30f800ba1c9647e8b87f7b5ec3/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L66)):*
> ```Swift
>         case dnsServer(_ uniqueID: UUID)
> 
>         static var contentBlockers: [Item] {
> ```

I think that instead of doing this, we should reuse `DNSBlockingOptions`if possible
This way, whenever we modify those settings, we only need to change one place in the codebase

It would also likely simplify `PreferencesViewModel` and all the settings related code

But I think we should do this in a different pull request, not this one.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsContentBlockersHeaderView.swift` line 18 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTm1Pj27FdllTvk0k-G:-NTm1Pj27FdllTvk0k-H:b6ykoj0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f165c053e65ab30f800ba1c9647e8b87f7b5ec3/ios/MullvadVPN/View%20controllers/Settings/SettingsContentBlockersHeaderView.swift#L18)):*
> ```Swift
>         let titleLabel = UILabel()
>         titleLabel.translatesAutoresizingMaskIntoConstraints = false
>         titleLabel.font = .systemFont(ofSize: 17)
> ```

I counted 22 instances of `.systemFont(ofSize: 17)` in the project so far.
I propose that we have a constant in the `UIMetrics` class instead. 
As it is, I'm guessing `17` is usually what we want for a title label, but the search results show that sometimes, it's a text label, or a detail text label
with this font size. So the value `17` is ambiguous here, is it for titles, something else ?

We should probably engage the UX team as well to define that. 

No necessary need to change that, but let's schedule some sync in the near future so we can define that.


<!-- Sent from Reviewable.io -->

2023-04-24 09:43 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 66 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTmXbgZ5vp4WcSof2pk:-NTmauQX4wHjfw_XSh9V:by0a7g6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f165c053e65ab30f800ba1c9647e8b87f7b5ec3/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L66)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I think that instead of doing this, we should reuse `DNSBlockingOptions`if possible
This way, whenever we modify those settings, we only need to change one place in the codebase

It would also likely simplify `PreferencesViewModel` and all the settings related code

But I think we should do this in a different pull request, not this one.
</blockquote></details>

The diffable data source currently expects all rows to be of type `Item`, so either we'd have to make `DNSBlockingOptions` conform to some protocol that can be shared with the other items in the table (`useCustomDNS`, `addDNSServer`, `dnsServer`), or introduce some sort of mapping. But as you said, this should be explored in another PR.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsContentBlockersHeaderView.swift` line 18 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTm1Pj27FdllTvk0k-G:-NTm_c_Q96z-3wQ1_UkU:b-th7k5t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f165c053e65ab30f800ba1c9647e8b87f7b5ec3/ios/MullvadVPN/View%20controllers/Settings/SettingsContentBlockersHeaderView.swift#L18)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I counted 22 instances of `.systemFont(ofSize: 17)` in the project so far.
I propose that we have a constant in the `UIMetrics` class instead. 
As it is, I'm guessing `17` is usually what we want for a title label, but the search results show that sometimes, it's a text label, or a detail text label
with this font size. So the value `17` is ambiguous here, is it for titles, something else ?

We should probably engage the UX team as well to define that. 

No necessary need to change that, but let's schedule some sync in the near future so we can define that.
</blockquote></details>

This will be taken care of in another PR handling dynamic type (https://linear.app/mullvad/issue/IOS-64/use-dynamic-type).

In dynamic type, 17 is the size for the `.body` text style.


<!-- Sent from Reviewable.io -->

2023-04-24 12:46 UTC, buggmagnet approved these changes
> Reviewed 1 of 1 files at r7, 14 of 26 files at r10, 4 of 5 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: all files reviewed, 7 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2023-04-25 10:58 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: all files reviewed, 8 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/Supporting Files/Assets.xcassets/IconInfo.imageset/IconInfo.pdf` line 0 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTs33T480QZnQeq7bdH:-NTs33T480QZnQeq7bdI:b560rc2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80b8a3f36a86c9290d67e50386b78555af5107cb/ios/MullvadVPN/Supporting%20Files/Assets.xcassets/IconInfo.imageset/IconInfo.pdf#L0)):*
Re-run the export script please.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 274 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#gh-1169765271:-NTs22Z288hyq10GeEiZ:buiv43z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbc54bf51c50ebf7d94c638eef59eff494701afc/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L274)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I see your point, but there are two things at play here. The content blocker header is a real header, while the dns settings header is not. It's actually a regular cell. So, in order to sync the heights I made the content blocker header work the same way as the cell, ie height being determined by the size of the label. 

The optimal solution might be to turn the dns header into a real header as well, but that would require some rework of the whole data source content structure.
</blockquote></details>

I don't think we can have sections with zero items. So can we please turn the header into individual cell?
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 66 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTmXbgZ5vp4WcSof2pk:-NTs0-NcERnoqowFlNHw:b5gdo2p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80b8a3f36a86c9290d67e50386b78555af5107cb/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L66)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

The diffable data source currently expects all rows to be of type `Item`, so either we'd have to make `DNSBlockingOptions` conform to some protocol that can be shared with the other items in the table (`useCustomDNS`, `addDNSServer`, `dnsServer`), or introduce some sort of mapping. But as you said, this should be explored in another PR.
</blockquote></details>

`DNSBlockingOptions` is an `OptionSet` so I don't think it will make it easier. 
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsContentBlockersHeaderView.swift` line 18 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-NTm1Pj27FdllTvk0k-G:-NTs-dZREQAyIV5t_dxZ:b-uik7rz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/80b8a3f36a86c9290d67e50386b78555af5107cb/ios/MullvadVPN/View%20controllers/Settings/SettingsContentBlockersHeaderView.swift#L18)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This will be taken care of in another PR handling dynamic type (https://linear.app/mullvad/issue/IOS-64/use-dynamic-type).

In dynamic type, 17 is the size for the `.body` text style.
</blockquote></details>

As Jon said. Dynamic type will take care of this. It's imminent and we don't need to do work that will be wiped weeks to months later.


<!-- Sent from Reviewable.io -->

2023-04-25 11:04 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: all files reviewed, 8 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 274 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#gh-1169765271:-NTs4V8B1bioAwxzHyxn:b-9udkck) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bbc54bf51c50ebf7d94c638eef59eff494701afc/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L274)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I don't think we can have sections with zero items. So can we please turn the header into individual cell?
</blockquote></details>

Scratch that.


<!-- Sent from Reviewable.io -->

2023-04-25 11:18 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532#-:-NTs7cxm2i0_2T16yMIo:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @mojganii and @rablador)



<!-- Sent from Reviewable.io -->

2023-04-25 16:01 UTC, pronebird reviewed
> Reviewed 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)* status: all files reviewed, 8 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)



<!-- Sent from Reviewable.io -->

2023-04-25 16:03 UTC, merged