Fix RPM package to not include build ids
mullvad/mullvadvpn-app pull request #4547
Opened 2023-04-12 11:32 UTC by pinkisemils

This fixes #4534. I've tested this myself with the currently available Slack RPM package, and this does fix the issue. The folder `/usr/lib/.build-id` is no longer present in our package with my changes, but it's there in our current installers.

2023-04-13 08:44 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4547)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`gui/tasks/distribution.js` line 205 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4547#gh-1164237166:-NStmGRzApsBMn6wEQca:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55962cf6413228b496a0296859d2d6c36171a4e2/gui/tasks/distribution.js#L205)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

IMO would not hurt to add a comment. This line is not self explanatory. And you don't immediately figure out what it did by removing it in a year either.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-14 09:39 UTC, faern requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4547)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`CHANGELOG.md` line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4547#-NSz7TGa4S85xnFcHmOw:-NSz7TGa4S85xnFcHmOx:b2nhexc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ba43297df1efe58dea122ca5fa53aa71bb570603/CHANGELOG.md#L54)):*
> ```Markdown
> 
> #### Linux
> - Fixed RPM package containing unecessary files causing conflicts with other electron-builder based
> ```

Fix
___
*[`gui/tasks/distribution.js` line 205 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4547#-NSz7Oxp4u4TRXiO4xi2:-NSz7Oxp4u4TRXiO4xi3:bkzu9h9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ba43297df1efe58dea122ca5fa53aa71bb570603/gui/tasks/distribution.js#L205)):*
> ```JavaScript
>   rpm: {
>     fpm: [
>       // Prevents RPM from packaing build-id metadata, some of which is the
> ```

nit. Packaging


<!-- Sent from Reviewable.io -->

2023-04-17 11:17 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4547)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`CHANGELOG.md` line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4547#-NSz7TGa4S85xnFcHmOw:-NTDvgFe-YU_CGtPLsWL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ba43297df1efe58dea122ca5fa53aa71bb570603/CHANGELOG.md#L54)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Fix
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-17 13:07 UTC, faern reviewed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4547)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-17 13:07 UTC, faern approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4547)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-17 13:58 UTC, merged