Change "Time left" on iOS to days and years
mullvad/mullvadvpn-app pull request #4586
Opened 2023-04-18 15:11 UTC by mojganii

In the app we have some platforms that round 5.99 months to 5 months, this is misleading and we want to be clear on how much time a user has left.

It was decided that we will use days and years only to display the time left:

- If a user has more than 2 years (730 days) left of time it should be displayed in whole years rounded down. (Divide the number of days with 365 and round down)

- If a user has less than 2 years left (e.g. 729 days) then this should be displayed in days.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4586)

2023-04-19 09:15 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4586)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift` line 34 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4586#-NTNcBGw7rqx4n0wKew7:-NTNn1TKDdvafj6ogHDZ:b-sy70rr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa1f3f8d9c97526615ede5b271f338d671077f9c/ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift#L34)):*
> let numDays = Calendar.current.dateComponents([.day], from: start, to: end)

There is a typo above. `numDays.day` would return number of days between two of dates.


<!-- Sent from Reviewable.io -->

2023-04-19 12:00 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4586)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @pinkisemils and @pronebird)

___
*[`ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4586#-NTNYhdt6d1clhAM0nAK:-NTOMiP4Cm5V57MoNXDu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa1f3f8d9c97526615ede5b271f338d671077f9c/ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift#L30)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

We configure units in here however we override them in both conditions below. Feels unnecessary.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift` line 34 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4586#-NTNcBGw7rqx4n0wKew7:-NTOMng70nMQkikkABo6:b-2yci91) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa1f3f8d9c97526615ede5b271f338d671077f9c/ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift#L34)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

> let numDays = Calendar.current.dateComponents([.day], from: start, to: end)

There is a typo above. `numDays.day` would return number of days between two of dates.
</blockquote></details>

as we discussed it's better to get diff from two dates by built-in calander API
___
*[`ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4586#-NTNmZT46HaWCjcLMGJ-:-NTOMyw13uz9hy078TP2:b-w9js2a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c0fa05e4cf507084f79cf66e21aec913747c3d2/ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift#L46)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

When user has less than a day, formatter that is only allowed to display duration in "days" will print "0 days". This has to be accounted for. Talk to @pinkisemils 
</blockquote></details>

fixed the test part and I would talk to Matilda about "0 days" to know her opinion


<!-- Sent from Reviewable.io -->

2023-04-19 16:20 UTC, pronebird requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4586)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii and @pinkisemils)

___
*[`ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift` line 35 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4586#-NTPIKYwCPdVdYkBtg6C:-NTPIKYwCPdVdYkBtg6D:b-ji33aa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81824b8ac1a34fd4deb4f93dd19adb24a431c7dd/ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift#L35)):*
> ```Swift
>         let years = dateComponents.year ?? 0
> 
>         if years >= 2 {
> ```

can this be simplified to:

```swift

let dateComponents = calendar.dateComponents([.year, .day], from: start, to: end)

/*

 // In case we need to handle 0 days (less than a day):

 guard (dateComponents.day ?? 0) > 0 else {
     return "Less than a day"
 }

*/

formatter.allowedUnits = [ years >= 2 ? .year : .day ]

return formatter.string(from: start, to: end)
```
___
*[`ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4586#-NTNmZT46HaWCjcLMGJ-:-NTPHbus4lzCrbMp_0jW:b-dtk8pp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c0fa05e4cf507084f79cf66e21aec913747c3d2/ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift#L46)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

fixed the test part and I would talk to Matilda about "0 days" to know her opinion
</blockquote></details>

I'll keep it blocked for now until we figure out how to handle this.


<!-- Sent from Reviewable.io -->

2023-04-20 09:49 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4586)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @pinkisemils and @pronebird)

___
*[`ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift` line 35 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4586#-NTPIKYwCPdVdYkBtg6C:-NTT35DN7NRb9Xj0o2SV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81824b8ac1a34fd4deb4f93dd19adb24a431c7dd/ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift#L35)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

can this be simplified to:

```swift

let dateComponents = calendar.dateComponents([.year, .day], from: start, to: end)

/*

 // In case we need to handle 0 days (less than a day):

 guard (dateComponents.day ?? 0) > 0 else {
     return "Less than a day"
 }

*/

formatter.allowedUnits = [ years >= 2 ? .year : .day ]

return formatter.string(from: start, to: end)
```
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4586#-NTNmZT46HaWCjcLMGJ-:-NTT3B-j2KIhSl2YN86H:b-1ykllv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c0fa05e4cf507084f79cf66e21aec913747c3d2/ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift#L46)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I'll keep it blocked for now until we figure out how to handle this.
</blockquote></details>

I've talked to her.she confirmed it's ok


<!-- Sent from Reviewable.io -->

2023-04-20 12:48 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4586#-:-NTThOyUEjrAuAfTPSOv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-20 13:06 UTC, merged