Add in-app banner message for a new device
mullvad/mullvadvpn-app pull request #4608
Opened 2023-04-24 12:44 UTC by mojganii

Add an in-app banner message that the user need to close for it to disappear, when the user has closed the in-app banner message the device name and time left are shown in the header (see referenced card), Confluence and Zeplin links in Parent card

2023-04-24 14:13 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @MrChocolatine)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotification.swift` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#gh-1175260887:-NTnQJDOECpz9kC1JeMe:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4666e577029a334a63684e46003873974420e4a7/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotification.swift#L12)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

I believe you may want to add a space here.

```suggestion

final class RegisteredDeviceInAppNotification: NotificationProvider, InAppNotificationProvider {
```
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-04-25 10:41 UTC, pronebird requested changes
> Reviewed 9 of 11 files at r1, 4 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608)* status: all files reviewed, 5 unresolved discussions (waiting on @mojganii and @MrChocolatine)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 657 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTrzqZB5Go4ClG6nzqM:-NTrzqZB5Go4ClG6nzqN:b-yqk23l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/090417df6c4506ad868aac28426e47560d4d5503/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L657)):*
> ```Swift
>             expiry: deviceState.accountData?.expiry,
>             showsAccountButton: deviceState.isLoggedIn,
>             showDeviceInfo: showDeviceInfo
> ```

Is `showDeviceInfo` used somewhere?
___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotification.swift` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#gh-1175260887:-NTrxQnkCYtneXPcR6iw:bprir9o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4666e577029a334a63684e46003873974420e4a7/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotification.swift#L12)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I don't think so.it's not good idea to import the whole of UIKit.It's not presentation layer
</blockquote></details>

Fine but can you unglue class definition from import please?
___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotification.swift` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTrxntW7nc_t7JAnJQb:-NTrxntW7nc_t7JAnJQc:b-l0t5wq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/090417df6c4506ad868aac28426e47560d4d5503/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotification.swift#L88)):*
> ```Swift
>             self.invalidate()
>         })
>         tunnelManager.addObserver(tunnelObserver!)
> ```

Please avoid force unwrapping even though it's obvious that `tunnelObserver` cannot be `nil`, but it can be easily avoided by assigning the tunnelObserver to `let` variable and then assigning `self.tunnelObserver = tunnelObserver` immediately after. Another option is to use `flatMap`, i.e:

```swift
tunnelObserver.flatMap { tunnelManager.addObserver($0) }
```
___
*[`ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift` line 69 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTrz1Mv9sudLRDpXALW:-NTrz1MwAPZmuM5DiC-O:b-sow8ae) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/090417df6c4506ad868aac28426e47560d4d5503/ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift#L69)):*
> ```Swift
>         let button = UIButton()
>         button.translatesAutoresizingMaskIntoConstraints = false
>         button.layoutMargins = UIMetrics.inAppBannerNotificationLayoutMargins
> ```

Does it add anything to presentation given that you set the size of the button itself?
___
*[`ios/MullvadVPN/Notifications/UI/NotificationController.swift` line 109 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTrzG1wB8zcWJKgaCnY:-NTrzG1wB8zcWJKgaCnZ:br05rqw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/090417df6c4506ad868aac28426e47560d4d5503/ios/MullvadVPN/Notifications/UI/NotificationController.swift#L109)):*
> ```Swift
>         bannerView.style = notification.style
>         bannerView.actionHandler = notification.action
>         bannerView.accessibilityLabel = "\(notification.title)\n\(notification.body)"
> ```

Perhaps `notification.body` should be changed to `notification.body.string`? I am not sure how attributed string is turned into `String` here.


<!-- Sent from Reviewable.io -->

2023-04-25 10:42 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608)* status: all files reviewed, 5 unresolved discussions (waiting on @mojganii and @MrChocolatine)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 657 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTrzqZB5Go4ClG6nzqM:-NTs-Htv2aGbEwXPb-8G:b-mnpnnb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/090417df6c4506ad868aac28426e47560d4d5503/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L657)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Is `showDeviceInfo` used somewhere?
</blockquote></details>

Had to roll back in history to see other changes. Nevermind.


<!-- Sent from Reviewable.io -->

2023-04-25 11:04 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608)* status: 12 of 15 files reviewed, 5 unresolved discussions (waiting on @MrChocolatine and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 657 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTrzqZB5Go4ClG6nzqM:-NTs0DD-9t61-GglMoXV:b-306uyq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/090417df6c4506ad868aac28426e47560d4d5503/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L657)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Had to roll back in history to see other changes. Nevermind.
</blockquote></details>

Yes,it's flag for showing device name and time left in header view.when user logged in we show device name with some description in header view once user dismisses the banner view we show device name and time left into header view
___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotification.swift` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#gh-1175260887:-NTs0zkb7rnn3FeiBKKh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4666e577029a334a63684e46003873974420e4a7/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotification.swift#L12)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Fine but can you unglue class definition from import please?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotification.swift` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTrxntW7nc_t7JAnJQb:-NTs1Wd55andX1yjmpuT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/090417df6c4506ad868aac28426e47560d4d5503/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotification.swift#L88)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Please avoid force unwrapping even though it's obvious that `tunnelObserver` cannot be `nil`, but it can be easily avoided by assigning the tunnelObserver to `let` variable and then assigning `self.tunnelObserver = tunnelObserver` immediately after. Another option is to use `flatMap`, i.e:

```swift
tunnelObserver.flatMap { tunnelManager.addObserver($0) }
```
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift` line 69 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTrz1Mv9sudLRDpXALW:-NTs2QMIBDPJ4UUQAoCR:b-j7twr8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/090417df6c4506ad868aac28426e47560d4d5503/ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift#L69)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Does it add anything to presentation given that you set the size of the button itself?
</blockquote></details>

No,the default margin is enough. I'll be removing this line
___
*[`ios/MullvadVPN/Notifications/UI/NotificationController.swift` line 109 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTrzG1wB8zcWJKgaCnY:-NTs2tr6BLzWUHqSKAUv:b-655ayl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/090417df6c4506ad868aac28426e47560d4d5503/ios/MullvadVPN/Notifications/UI/NotificationController.swift#L109)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Perhaps `notification.body` should be changed to `notification.body.string`? I am not sure how attributed string is turned into `String` here.
</blockquote></details>

It makes sense  


<!-- Sent from Reviewable.io -->

2023-04-25 12:02 UTC, rablador requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608)* status: all files reviewed, 7 unresolved discussions (waiting on @mojganii, @MrChocolatine, and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 657 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTrzqZB5Go4ClG6nzqM:-NTsDdpJE1SM5hackI9S:bhmdyz0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/090417df6c4506ad868aac28426e47560d4d5503/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L657)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Yes,it's flag for showing device name and time left in header view.when user logged in we show device name with some description in header view once user dismisses the banner view we show device name and time left into header view
</blockquote></details>

Nit: I think we should decide on either showX or showsX.
___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotification.swift` line 23 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTsF3NBAQqbV-kiBlm2:-NTsF3NBAQqbV-kiBlm3:b-afq64l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c8461bb3c86c9b1eb88c020a52997e00025a7b3/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotification.swift#L23)):*
> ```Swift
>     private var shouldShowBanner = false
>     private var deviceState: DeviceState {
>         didSet {}
> ```

This didSet can be removed.
___
*[`ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift` line 150 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTsG-jE7QtaE79CrKsp:-NTsG-jE7QtaE79CrKsq:b-lqr1n4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c8461bb3c86c9b1eb88c020a52997e00025a7b3/ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift#L150)):*
> ```Swift
>     }
> 
>     @objc private func didPressed() {
> ```

Nit: Repeated past tense. Consider changing to didPress.


<!-- Sent from Reviewable.io -->

2023-04-25 14:27 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608)* status: all files reviewed, 6 unresolved discussions (waiting on @MrChocolatine, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 657 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTrzqZB5Go4ClG6nzqM:-NTsm18e7meE8TFPUknN:bk4hxz4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/090417df6c4506ad868aac28426e47560d4d5503/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L657)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: I think we should decide on either showX or showsX.
</blockquote></details>

I change this to showsX.but after that we can make a decision  on it
___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotification.swift` line 23 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTsF3NBAQqbV-kiBlm2:-NTsmNGPC92n1_5QdCJ2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c8461bb3c86c9b1eb88c020a52997e00025a7b3/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotification.swift#L23)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This didSet can be removed.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift` line 150 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTsG-jE7QtaE79CrKsp:-NTsmyc56zSIDDotDqdU:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c8461bb3c86c9b1eb88c020a52997e00025a7b3/ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift#L150)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Repeated past tense. Consider changing to didPress.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-04-25 14:35 UTC, rablador approved these changes
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608)* status: all files reviewed, 5 unresolved discussions (waiting on @MrChocolatine and @pronebird)



<!-- Sent from Reviewable.io -->

2023-04-25 16:05 UTC, pronebird reviewed
> Dismissed @MrChocolatine from a discussion.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-25 16:10 UTC, pronebird approved these changes
> Reviewed 1 of 3 files at r4, 2 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-25 16:10 UTC, pronebird approved these changes
> Reviewed 2 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-26 07:36 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTwUD9hEOY2cGNcmGoG:-NTwUD9hEOY2cGNcmGoH:b-4q2kal) (no related file):*
As it was raised by @mojganii. This banana will not be displayed in any other view controller as it's incorporated into tunnel controller. So we need to figure out the way to perhaps have this banner more persistent, for instance by moving it into root container. A bit trickier on iPad as we use modal to present out of time view, but maybe that's fine. Needs some experimentation.

___


<!-- Sent from Reviewable.io -->

2023-04-26 07:37 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTwUD9hEOY2cGNcmGoG:-NTwUZQQAaGWmAzwXLiw:b7mpjq) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

As it was raised by @mojganii. This banana will not be displayed in any other view controller as it's incorporated into tunnel controller. So we need to figure out the way to perhaps have this banner more persistent, for instance by moving it into root container. A bit trickier on iPad as we use modal to present out of time view, but maybe that's fine. Needs some experimentation.
</blockquote></details>

Typo: /banana/banner

___


<!-- Sent from Reviewable.io -->

2023-04-26 07:49 UTC, pronebird approved these changes
> Reviewed 1 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608#-NTwUD9hEOY2cGNcmGoG:-NTwXReC6Ovf54FU-gz5:b68ybbq) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Typo: /banana/banner
</blockquote></details>

Should be handled in a separate PR as I realize this will cause a lot of changes.

___


<!-- Sent from Reviewable.io -->

2023-04-26 07:52 UTC, merged