Improve behavior when there's no network
mullvad/mullvadvpn-app pull request #4613
Opened 2023-04-24 19:23 UTC by rablador

When an iOS device has no connectivity, iOS won't let us start a tunnel. From a UX perspective, this looks like the app is broken - it enters the connecting state and is immediately thrown back out of it. To improve the UX, a banner tells the user that there's no network and all action buttons are disabled.

2023-04-25 12:13 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/Notifications/UI/NotificationController.swift` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613#-NTsK0-Q3Z_jmdqiquef:-NTsK0-R1txGe1mD4Iok:bx0una7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fcba77dce88a3fd783ae90923884392528ae4510/ios/MullvadVPN/Notifications/UI/NotificationController.swift#L28)):*
> ```Swift
>     }}
> 
>     var didUpdateLastNotification: ((InAppNotificationDescriptor?) -> Void)?
> ```

why do we need to this block?


<!-- Sent from Reviewable.io -->

2023-04-25 13:30 UTC, pronebird reviewed
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Notifications/UI/NotificationController.swift` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613#-NTsK0-Q3Z_jmdqiquef:-NTsa2saDxmJIkF5_H32:b1pvy31) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fcba77dce88a3fd783ae90923884392528ae4510/ios/MullvadVPN/Notifications/UI/NotificationController.swift#L28)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It's used in TunnelViewController to notify the UI that buttons should be enabled or disabled.
</blockquote></details>

I think we should perhaps expose this functionality via tunnel manager, `packetTunnelStatus.isNetworkReachable` contains information received from the packet tunnel. But when packet tunnel is down, we could fill in this field via `NWPathMonitor`. Then we could generate notifications the same way we do right now. Does not have to be exactly this way but something along those lines seems reasonable..?


<!-- Sent from Reviewable.io -->

2023-04-25 13:33 UTC, pronebird reviewed
> Reviewed 2 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2023-04-28 13:24 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @mojganii and @pronebird)

___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 746 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613#-NU71E1B-vv34k6q0pLC:-NU71E1B-vv34k6q0pLD:bfnlh4p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d30e138ef9b3ab51547e944dabc996075f9a97f/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L746)):*
> ```Swift
> 
>     private func didUpdateNetworkPath(_ path: Network.NWPath) {
>         updateTunnelStatus(tunnel?.status ?? .disconnected)
> ```

Is `.disconnected` (as fallback) safe?


<!-- Sent from Reviewable.io -->

2023-04-28 13:59 UTC, pronebird requested changes
> Reviewed 11 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613)* status: 11 of 12 files reviewed, 5 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 742 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613#-NU78v6GDOzs06ETG7ga:-NU78v6GDOzs06ETG7gb:b-4fjt8s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d30e138ef9b3ab51547e944dabc996075f9a97f/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L742)):*
> ```Swift
>         #endif
>         refreshTunnelStatus()
>         startNetworkMonitor()
> ```

Maybe look into `loadConfiguration()` and see if you can start network monitor in there from completion handler after we loaded settings and fetched system VPN tunnels.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 746 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613#-NU71E1B-vv34k6q0pLC:-NU76GdZ2EDrkzxdcc0z:b-alf8j1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d30e138ef9b3ab51547e944dabc996075f9a97f/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L746)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Is `.disconnected` (as fallback) safe?
</blockquote></details>

I think so. The status will be overwritten, if somehow, tunnel re-appears down the road.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 814 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613#-NU76R8aEQBDPNXHqtX7:-NU76R8aEQBDPNXHqtX8:b-a1o6xy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d30e138ef9b3ab51547e944dabc996075f9a97f/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L814)):*
> ```Swift
> 
>     private func startNetworkMonitor() {
>         networkMonitor = NWPathMonitor()
> ```

Make sure you don't start multiple monitors, i.e:

```swift
guard networkMonitor == nil else { return }
```

or make it idempotent by calling `cancelNetworkMonitor()` first thing in here.
___
*[`ios/MullvadVPN/TunnelManager/TunnelState.swift` line 37 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613#-NU77JFF7aRauFzarQsn:-NU77JFF7aRauFzarQso:b-8i5pje) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d30e138ef9b3ab51547e944dabc996075f9a97f/ios/MullvadVPN/TunnelManager/TunnelState.swift#L37)):*
> ```Swift
> enum TunnelState: Equatable, CustomStringConvertible {
>     enum WaitingForConnectionReason {
>         case noConnection
> ```

Please document both cases.


<!-- Sent from Reviewable.io -->

2023-04-28 14:04 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613)* status: 11 of 12 files reviewed, 6 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 815 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613#-NU7AB8A3HfY3OE1Jr45:-NU7AB8A3HfY3OE1Jr46:b-23xo05) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d30e138ef9b3ab51547e944dabc996075f9a97f/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L815)):*
> ```Swift
>     private func startNetworkMonitor() {
>         networkMonitor = NWPathMonitor()
>         networkMonitor?.pathUpdateHandler = didUpdateNetworkPath
> ```

This creates a strong reference to `self`, i.e it's equivalent to:

```swift
self.networkMonitor?.pathUpdateHandler = { path in
   self.didUpdateNetworkPath(path)
}
```

Please define explicit closure and use `[weak self]` inside to avoid retain cycle.


<!-- Sent from Reviewable.io -->

2023-04-28 14:45 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613)* status: 9 of 12 files reviewed, 5 unresolved discussions (waiting on @mojganii and @pronebird)

___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 742 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613#-NU78v6GDOzs06ETG7ga:-NU7HiqtDEk_MfAcs2Wp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d30e138ef9b3ab51547e944dabc996075f9a97f/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L742)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe look into `loadConfiguration()` and see if you can start network monitor in there from completion handler after we loaded settings and fetched system VPN tunnels.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 814 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613#-NU76R8aEQBDPNXHqtX7:-NU7IF9K-n84oAwfmvYM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d30e138ef9b3ab51547e944dabc996075f9a97f/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L814)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Make sure you don't start multiple monitors, i.e:

```swift
guard networkMonitor == nil else { return }
```

or make it idempotent by calling `cancelNetworkMonitor()` first thing in here.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 815 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613#-NU7AB8A3HfY3OE1Jr45:-NU7IPyjCzGxAF28CTI3:bsn99kk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d30e138ef9b3ab51547e944dabc996075f9a97f/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L815)):*
> pathUpdateHandler
Huh, I didn't know that, but it makes sense. 👍 Will change.
___
*[`ios/MullvadVPN/TunnelManager/TunnelState.swift` line 37 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613#-NU77JFF7aRauFzarQsn:-NU7Jo379yhZmdw5lVqc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8d30e138ef9b3ab51547e944dabc996075f9a97f/ios/MullvadVPN/TunnelManager/TunnelState.swift#L37)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Please document both cases.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-28 20:28 UTC, MrChocolatine commented on ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift
> +                    has access to internet.
```suggestion
                    has access to Internet.
```

2023-05-02 07:23 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613)* status: 8 of 12 files reviewed, 6 unresolved discussions (waiting on @mojganii, @MrChocolatine, and @pronebird)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift` line 214 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613#gh-1180788979:-NUQKxYp1xHqiIN0BjnM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/94d23114be74fa8ce8d7913164279ec4280b050e/ios/MullvadVPN/Notifications/Notification%20Providers/TunnelStatusNotificationProvider.swift#L214)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

```suggestion
                    has access to Internet.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-03 08:22 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 12 files at r3, 1 of 2 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613#-:-NUVh6T18j_71AjajyrZ:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @mojganii, @MrChocolatine, and @pronebird)



<!-- Sent from Reviewable.io -->

2023-05-04 09:47 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r5, 3 of 4 files at r6.
> Dismissed @MrChocolatine from a discussion.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613#-:-NUXAoIYCQLFbVo1BU4e:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2023-05-04 11:12 UTC, pronebird reviewed
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2023-05-04 11:13 UTC, pronebird reviewed
> Dismissed @mojganii from a discussion.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2023-05-04 11:15 UTC, merged