Fix view state when disconnecting from out-of-time view
mullvad/mullvadvpn-app pull request #4620
Opened 2023-04-26 09:01 UTC by rablador

When in the out-of-time view, the app will fail to update its view state on disconnect, blocking the user from accessing the add time button.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620)

2023-04-27 15:16 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeViewController.swift` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU2GI3UBlrwAkcQ9zZl:-NU2GI3UBlrwAkcQ9zZm:b-8cu4a1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4271de7db101a457ba34df08f6e70eb73e79554f/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeViewController.swift#L17)):*
> ```Swift
> 
> /// Interval used for periodic polling account updates.
> private let accountUpdateTimerInterval: TimeInterval = 60
> ```

How about moving this into interactor and simply calling methods to start or stop polling account data from here?
___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeViewController.swift` line 123 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU2G8oqDZFc4WgoxV7R:-NU2G8oqDZFc4WgoxV7S:b8b3ojv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4271de7db101a457ba34df08f6e70eb73e79554f/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeViewController.swift#L123)):*
> ```Swift
> 
>     deinit {
>         cancelAccountUpdateTimer()
> ```

I think `DispatchSourceTimer` invalidates itself on deinit (unlike `Timer`)
___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeViewController.swift` line 186 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU2H1LX59xsYtUt4dfV:-NU2H1LX59xsYtUt4dfW:bt7nitw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4271de7db101a457ba34df08f6e70eb73e79554f/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeViewController.swift#L186)):*
> ```Swift
> 
>         contentView.disconnectButton.isEnabled = tunnelState.isSecured
>         UIView.animate(withDuration: 0.25) {
> ```

FYI I'd move that into `OutOfTimeContentView` instead and call a function to enable disconnect button with or without animation.


<!-- Sent from Reviewable.io -->

2023-04-27 22:19 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeViewController.swift` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU2GI3UBlrwAkcQ9zZl:-NU3kY-dDkVscRvkxIRn:b-j58sim) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4271de7db101a457ba34df08f6e70eb73e79554f/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeViewController.swift#L17)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

How about moving this into interactor and simply calling methods to start or stop polling account data from here?
</blockquote></details>

It crossed my mind, but I wasn't sure if interactor should be more of a mediator of function calls rather than keeping track of things itself. It does clean things up a bit though.
___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeViewController.swift` line 123 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU2G8oqDZFc4WgoxV7R:-NU3kS8_Cz0JWxAoOKka:bb77uci) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4271de7db101a457ba34df08f6e70eb73e79554f/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeViewController.swift#L123)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think `DispatchSourceTimer` invalidates itself on deinit (unlike `Timer`)
</blockquote></details>

Yep!


<!-- Sent from Reviewable.io -->

2023-04-28 09:32 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU6AuYWECXSEnXeYCPQ:-NU6AuYWECXSEnXeYCPR:b-3uuxg7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17dbf6875b613d0f6e3e4540e0fb647ffec639/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeInteractor.swift#L28)):*
> ```Swift
>     private let logger = Logger(label: "OutOfTimeInteractor")
>     private var accountUpdateTimer: DispatchSourceTimer?
>     private var isPolling = false
> ```

Nit: What are we polling here ?

The way we use this boolean is to have idempotency in `startAccountUpdateTimer` 
I think a name like `updateTimerIsRunning` would be more explicit. 
___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift` line 94 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU66BsX-puPyx2VXpzY:-NU66BsX-puPyx2VXpzZ:b-33yhao) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17dbf6875b613d0f6e3e4540e0fb647ffec639/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeInteractor.swift#L94)):*
> ```Swift
> 
>     func startAccountUpdateTimer() {
>         guard !isPolling else { return }
> ```

There are some potential race conditions here.

Say we have thread A and thread B running here this function.
L94-95: This method is not thread safe, thread A could be pre-empted at L94 before the if check, whilst thread B runs L95.
Now we have 2 dispatch source timers running.

In practice, I haven't checked how we use `OutOfTimeInteractor`, so we could be safe, but I think it's still worth being said.
___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift` line 95 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU6BpZh8kTpX5xvQtNv:-NU6BpZh8kTpX5xvQtNw:bnr5w9c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17dbf6875b613d0f6e3e4540e0fb647ffec639/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeInteractor.swift#L95)):*
> ```Swift
>     func startAccountUpdateTimer() {
>         guard !isPolling else { return }
>         isPolling = true
> ```

With this current design, we never set `isPolling` to `false` so this will run exactly once.

I'm not sure whether that's the intended design, but in that case, it sounds like we would want to cancel `accountUpdateTimer` in `stopTunnel` and set this flag to false there as well.

Please let me know if I misunderstood this. 
___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift` line 106 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU6AKXW8Ls0VqGAmd48:-NU6AKXW8Ls0VqGAmd49:b-gqn0i4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17dbf6875b613d0f6e3e4540e0fb647ffec639/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeInteractor.swift#L106)):*
> ```Swift
>         }
>         timer.schedule(wallDeadline: .now() + accountUpdateTimerInterval, repeating: accountUpdateTimerInterval)
>         timer.activate()
> ```

We have another potential race condition that's slightly more dangerous.
As per the docs, `The system may fire a timer sooner than the value in the wallDeadline parameter.`

Once again, in practice I think it's unlikely to happen as the `accountUpdateTimerInterval` is quite large (60 seconds)
If the timers were shorter however, that could have bad consequences.

As a general practice, I would advise to cancel the previous timer before activating the new one.

I would suggest moving `timer.activate()` at the end of this function, and calling `accountUpdateTimer?.cancel()` before that happens


<!-- Sent from Reviewable.io -->

2023-04-28 12:42 UTC, pronebird reviewed
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift` line 94 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU66BsX-puPyx2VXpzY:-NU6mFxL8WFPbj-pBdXx:bv5rgn8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17dbf6875b613d0f6e3e4540e0fb647ffec639/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeInteractor.swift#L94)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

There are some potential race conditions here.

Say we have thread A and thread B running here this function.
L94-95: This method is not thread safe, thread A could be pre-empted at L94 before the if check, whilst thread B runs L95.
Now we have 2 dispatch source timers running.

In practice, I haven't checked how we use `OutOfTimeInteractor`, so we could be safe, but I think it's still worth being said.
</blockquote></details>

We use interactor exclusively from main thread, so there is no need to worry about any other thread in here.
___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift` line 106 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU6AKXW8Ls0VqGAmd48:-NU6mQcu06YS-2ZhoGf0:b87nv56) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17dbf6875b613d0f6e3e4540e0fb647ffec639/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeInteractor.swift#L106)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We have another potential race condition that's slightly more dangerous.
As per the docs, `The system may fire a timer sooner than the value in the wallDeadline parameter.`

Once again, in practice I think it's unlikely to happen as the `accountUpdateTimerInterval` is quite large (60 seconds)
If the timers were shorter however, that could have bad consequences.

As a general practice, I would advise to cancel the previous timer before activating the new one.

I would suggest moving `timer.activate()` at the end of this function, and calling `accountUpdateTimer?.cancel()` before that happens
</blockquote></details>

Both timer and this function run on main queue. So the timer will either fire before execution of this function or after. It's really a deeper discussion on how libdispatch handles cancellation and how timers work.


<!-- Sent from Reviewable.io -->

2023-04-28 13:38 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU6AuYWECXSEnXeYCPQ:-NU72Bzz9FwJJtzK9En4:b-pbdqz3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17dbf6875b613d0f6e3e4540e0fb647ffec639/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeInteractor.swift#L28)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Nit: What are we polling here ?

The way we use this boolean is to have idempotency in `startAccountUpdateTimer` 
I think a name like `updateTimerIsRunning` would be more explicit. 
</blockquote></details>

Agreed.
___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift` line 94 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU66BsX-puPyx2VXpzY:-NU6y37k0pievCwlUtdh:b-s89c7w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17dbf6875b613d0f6e3e4540e0fb647ffec639/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeInteractor.swift#L94)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

We use interactor exclusively from main thread, so there is no need to worry about any other thread in here.
</blockquote></details>

I assume no change is needed then?
___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift` line 95 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU6BpZh8kTpX5xvQtNv:-NU733YXBrjjsLCHxgr5:b-w95xfv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17dbf6875b613d0f6e3e4540e0fb647ffec639/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeInteractor.swift#L95)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

With this current design, we never set `isPolling` to `false` so this will run exactly once.

I'm not sure whether that's the intended design, but in that case, it sounds like we would want to cancel `accountUpdateTimer` in `stopTunnel` and set this flag to false there as well.

Please let me know if I misunderstood this. 
</blockquote></details>

There was previously a function to cancel the timer in which the isPolling would change. That was removed since the timer will cancel itself when the viewcontroller (along with this class) is deinitialized. As such, a cancel function timer was no longer needed, although iPolling was not removed along with it. I'll add the cancel function back again to make things more complete (and clear) for future use.
___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift` line 106 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU6AKXW8Ls0VqGAmd48:-NU74RMQ9oWQf5ysiO4G:bajnyn8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17dbf6875b613d0f6e3e4540e0fb647ffec639/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeInteractor.swift#L106)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

But as a general rule of thumb, I agree.
</blockquote></details>

No change, then?


<!-- Sent from Reviewable.io -->

2023-05-02 09:25 UTC, buggmagnet approved these changes
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift` line 95 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU6BpZh8kTpX5xvQtNv:-NUQlMTp76fnSgR8UwgN:b-ubdbv7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17dbf6875b613d0f6e3e4540e0fb647ffec639/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeInteractor.swift#L95)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

There was previously a function to cancel the timer in which the isPolling would change. That was removed since the timer will cancel itself when the viewcontroller (along with this class) is deinitialized. As such, a cancel function timer was no longer needed, although iPolling was not removed along with it. I'll add the cancel function back again to make things more complete (and clear) for future use.
</blockquote></details>

We discussed this offline and decided to remove the `cancelAccountUpdateTimer` function as long as it's not in use
___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift` line 106 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU6AKXW8Ls0VqGAmd48:-NUQlUl44NVIli2_EDbv:b-1g6dw8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17dbf6875b613d0f6e3e4540e0fb647ffec639/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeInteractor.swift#L106)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

No change, then?
</blockquote></details>

nit: I would personally have preferred a change just for the sake of enforcing good habits, and for the sake of consistently having them even if it doesn't matter here


<!-- Sent from Reviewable.io -->

2023-05-02 09:51 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift` line 95 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU6BpZh8kTpX5xvQtNv:-NUQrb5z7fU53qbFHIxn:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17dbf6875b613d0f6e3e4540e0fb647ffec639/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeInteractor.swift#L95)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We discussed this offline and decided to remove the `cancelAccountUpdateTimer` function as long as it's not in use
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-04 13:23 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift` line 106 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-NU6AKXW8Ls0VqGAmd48:-NUXB7Y82OmMuN6LciWf:b82yoa9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c17dbf6875b613d0f6e3e4540e0fb647ffec639/ios/MullvadVPN/View%20controllers/OutOfTime/OutOfTimeInteractor.swift#L106)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit: I would personally have preferred a change just for the sake of enforcing good habits, and for the sake of consistently having them even if it doesn't matter here
</blockquote></details>

Seems to be addressed 


<!-- Sent from Reviewable.io -->

2023-05-04 13:34 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620#-:-NUay5gh-1HH68bXDdDm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-04 15:40 UTC, merged