Add creation date to device name in Too many devices view
mullvad/mullvadvpn-app pull request #4626
Opened 2023-04-27 13:30 UTC by mojganii

Users has been requesting to see the device creation date in the Too many devices view and so their request has been granted. 🎉 The creation date for the device is to be shown underneath the device name.

The list-items height has been made higher, but only in this specific view!

2023-04-27 15:09 UTC, pronebird requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Extensions/DateFormatter+Custom.swift` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626#-NU2E9cBBed_t3F57dDI:-NU2E9cBBed_t3F57dDJ:bmio2ns) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d811c3a504f24e901085a9af625fbfc4c4c5eb9/ios/MullvadVPN/Extensions/DateFormatter%2BCustom.swift#L12)):*
> ```Swift
> 
> extension DateFormatter {
>     static func localizedString(from: Date, format: String) -> String {
> ```

Perhaps we don't need this helper as it's so rudimental.
___
*[`ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift` line 110 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626#-NU2CJej4ZhMmrEoscV0:-NU2CJej4ZhMmrEoscV1:b-nl0y3p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d811c3a504f24e901085a9af625fbfc4c4c5eb9/ios/MullvadVPN/View%20controllers/DeviceList/DeviceManagementViewController.swift#L110)):*
> ```Swift
>                 createdDate: DateFormatter.localizedString(
>                     from: restDevice.created,
>                     format: "yyyy-mm-dd"
> ```

This is a standard ISO8601 format with time component left out. 

Maybe pass a `Date` to view model and add a property on `DeviceViewModel` to produce `String` from `Date`.

```swift
let formattedString = ISO8601DateFormatter.string(from: <#Date#>, timeZone: .gmt, formatOptions: [.withFullDate])
```

GMT is used to avoid any shifts based on device TZ as all dates we receive from server are likely in UTC (or GMT which seems to be the same thing?).
___
*[`ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift` line 270 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626#-NU2AKYb-qXnOQ2X8zS7:-NU2AKYb-qXnOQ2X8zS8:b-mx73rz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d811c3a504f24e901085a9af625fbfc4c4c5eb9/ios/MullvadVPN/View%20controllers/DeviceList/DeviceManagementViewController.swift#L270)):*
> ```Swift
>     let id: String
>     let name: String
>     let createdDate: String
> ```

It should either be `creationDate` or `dateCreated` in proper English I think.


<!-- Sent from Reviewable.io -->

2023-04-27 15:32 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626)* status: all files reviewed, 3 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift` line 110 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626#-NU2CJej4ZhMmrEoscV0:-NU2JN1-EjWWDqQSitXR:b-p18l9u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d811c3a504f24e901085a9af625fbfc4c4c5eb9/ios/MullvadVPN/View%20controllers/DeviceList/DeviceManagementViewController.swift#L110)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This is a standard ISO8601 format with time component left out. 

Maybe pass a `Date` to view model and add a property on `DeviceViewModel` to produce `String` from `Date`.

```swift
let formattedString = ISO8601DateFormatter.string(from: <#Date#>, timeZone: .gmt, formatOptions: [.withFullDate])
```

GMT is used to avoid any shifts based on device TZ as all dates we receive from server are likely in UTC (or GMT which seems to be the same thing?).
</blockquote></details>

gmt is available for iOS 16.0 above . 
___
*[`ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift` line 270 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626#-NU2AKYb-qXnOQ2X8zS7:-NU2JkFiCPrf9sHGD5u4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d811c3a504f24e901085a9af625fbfc4c4c5eb9/ios/MullvadVPN/View%20controllers/DeviceList/DeviceManagementViewController.swift#L270)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

It should either be `creationDate` or `dateCreated` in proper English I think.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-27 16:54 UTC, pronebird requested changes
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift` line 110 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626#-NU2CJej4ZhMmrEoscV0:-NU2Yjg22gx3YX-ebR9C:ba09432) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d811c3a504f24e901085a9af625fbfc4c4c5eb9/ios/MullvadVPN/View%20controllers/DeviceList/DeviceManagementViewController.swift#L110)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

gmt is available for iOS 16.0 above . 
</blockquote></details>

How about `TimeZone(secondsFromGMT: 0)` then? We really don't want dates to drift due to user timezone.

It's incredible that it's fallible, because `NSTimeZone(forSecondsFromGMT: 0)` is not :)

Without force unwrapping this is the way:

```swift
extension TimeZone {
    static var utc: TimeZone {
        return NSTimeZone(forSecondsFromGMT: 0) as TimeZone
    }
}
```

I am talking to @pinkisemils about this, whether using `.current` is ok or we should really stick to UTC because we'll get support tickets if what we show on the web does not match what we show in the app.


<!-- Sent from Reviewable.io -->

2023-04-28 09:04 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626)* status: 2 of 4 files reviewed, all discussions resolved

___
*[`ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift` line 110 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626#-NU2CJej4ZhMmrEoscV0:-NU65o7n7MbWo2_4IJ7h:b-xv6guv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d811c3a504f24e901085a9af625fbfc4c4c5eb9/ios/MullvadVPN/View%20controllers/DeviceList/DeviceManagementViewController.swift#L110)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

How about `TimeZone(secondsFromGMT: 0)` then? We really don't want dates to drift due to user timezone.

It's incredible that it's fallible, because `NSTimeZone(forSecondsFromGMT: 0)` is not :)

Without force unwrapping this is the way:

```swift
extension TimeZone {
    static var utc: TimeZone {
        return NSTimeZone(forSecondsFromGMT: 0) as TimeZone
    }
}
```

I am talking to @pinkisemils about this, whether using `.current` is ok or we should really stick to UTC because we'll get support tickets if what we show on the web does not match what we show in the app.

</blockquote></details>

Seems like it's fine. We should use `.current` TZ.


<!-- Sent from Reviewable.io -->

2023-04-28 10:04 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @mojganii)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626#-NU6Ivl3EGV4QIVkostP:-NU6Ivl3EGV4QIVkostQ:b-svbckd) (no related file):*
Based on discussion on Slack, we should be using default formatter (not ISO) and instead use digits only, so I think `.short` date style should work just fine:


```swift
DateFormatter.localizedString(from: date, dateStyle: .short, timeStyle: .none)
```

___


<!-- Sent from Reviewable.io -->

2023-04-28 12:42 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @pronebird)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626#-NU6Ivl3EGV4QIVkostP:-NU6sUm50Qh8t8khPc8F:b-896fix) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Based on discussion on Slack, we should be using default formatter (not ISO) and instead use digits only, so I think `.short` date style should work just fine:


```swift
DateFormatter.localizedString(from: date, dateStyle: .short, timeStyle: .none)
```
</blockquote></details>

Done.

___
___
*[`ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift` line 110 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626#-NU2CJej4ZhMmrEoscV0:-NU6sYeZ9bvET90PYvLx:b32wtd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d811c3a504f24e901085a9af625fbfc4c4c5eb9/ios/MullvadVPN/View%20controllers/DeviceList/DeviceManagementViewController.swift#L110)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Seems like it's fine. We should use `.current` TZ.
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2023-04-28 14:29 UTC, pronebird reviewed
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-28 14:31 UTC, merged