Handle account expiry transitions
mullvad/mullvadvpn-app pull request #4627
Opened 2023-04-27 13:59 UTC by pronebird

1. Move constants used in notification providers into `NotificationConfiguration`
2. Change notification style to present banner with sound too. Since we use provisional push notifications, banner and sound will only happen if users toggle them in System settings for the app (via notifications section). Out of box we'll always be quite.
3. Device state observers will now receive previous device state along with the current one, which should help with business logic. Note that `DeviceState` changes are posted even when account data or device data change, that's why receiving two consecutive `DeviceState.loggedIn`  states in a row is totally possible. In that case if you really care to react to specific changes, make sure you compare current and previous device state before taking action.
4. Working with `DeviceState` is a bit cumbersome, so there is a new helper that you could find useful when mutating the associated values stored in `DeviceState.loggedIn` variant. 
    ```swift 
    /**
      Mutates account and device data when in logged in state, otherwise does nothing.
    */
    mutating func updateData(_ body: (inout StoredAccountData, inout StoredDeviceData) -> Void)
    ```
5. Handle transitions to and from expired state. Fixes a bug when the app would end up being on a previous screen (Login) after adding time on account.

2023-04-27 23:14 UTC, rablador requested changes
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4627)* status: all files reviewed, 5 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 632 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4627#-NU3wM8H7dlIuebrAycQ:-NU3wM8I4ZNl16MO2ADy:b-avg5ik) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd6a183e3a55f196133f82100e65dd22106765e6/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L632)):*
> ```Swift
>     }
> 
>     private func deviceStateDidChange(_ newDeviceState: DeviceState, previousDeviceState: DeviceState) {
> ```

Nit: "newDeviceState" is clearer in meaning, but should probably still be just "deviceState" for consitency with the rest of the code.
___
*[`ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift` line 92 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4627#-NU3yRFZ4m-MQFin9Ua3:-NU3yRFZ4m-MQFin9Ua4:b-8av9qk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd6a183e3a55f196133f82100e65dd22106765e6/ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift#L92)):*
> ```Swift
>      Mutates account and device data when in logged in state, otherwise does nothing.
>      */
>     mutating func updateData(_ body: (inout StoredAccountData, inout StoredDeviceData) -> Void) {
> ```

Amen.
___
*[`ios/MullvadVPN/TunnelManager/TunnelBlockObserver.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4627#-NU3uziY6N9Z_235BAUM:-NU3uziY6N9Z_235BAUN:b-u464wn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd6a183e3a55f196133f82100e65dd22106765e6/ios/MullvadVPN/TunnelManager/TunnelBlockObserver.swift#L14)):*
> ```Swift
>     typealias DidLoadConfigurationHandler = (TunnelManager) -> Void
>     typealias DidUpdateTunnelStatusHandler = (TunnelManager, TunnelStatus) -> Void
>     typealias DidUpdateDeviceStateHandler = (TunnelManager, DeviceState, DeviceState) -> Void
> ```

How about something like this for readability?



_Code snippet:_
```Swift
typealias PreviousDeviceState = DeviceState
[...]
typealias DidUpdateDeviceStateHandler = (TunnelManager, DeviceState, PreviousDeviceState) -> Void
```
___
*[`ios/MullvadVPN/TunnelManager/TunnelBlockObserver.swift` line 48 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4627#-NU3ykPI0iHVH3wi-mE-:-NU3ykPI0iHVH3wi-mE0:b-r61aj1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd6a183e3a55f196133f82100e65dd22106765e6/ios/MullvadVPN/TunnelManager/TunnelBlockObserver.swift#L48)):*
> ```Swift
>     func tunnelManager(
>         _ manager: TunnelManager,
>         didUpdateDeviceState newDeviceState: DeviceState,
> ```

Nit: Change to "deviceState" for consistency.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 1006 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4627#-NU3z6yfEnVu5c52Kfwm:-NU3z6yfEnVu5c52Kfwn:bc32bep) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd6a183e3a55f196133f82100e65dd22106765e6/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L1006)):*
> ```Swift
>      }
> 
>      Task {
> ```

Cool, modern concurrency API :)


<!-- Sent from Reviewable.io -->

2023-04-28 10:17 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4627)* status: 16 of 19 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 632 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4627#-NU3wM8H7dlIuebrAycQ:-NU6MM4Q3WyazFyl1qrY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd6a183e3a55f196133f82100e65dd22106765e6/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L632)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: "newDeviceState" is clearer in meaning, but should probably still be just "deviceState" for consitency with the rest of the code.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/TunnelManager/TunnelBlockObserver.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4627#-NU3uziY6N9Z_235BAUM:-NU6KX553NF1JwkQDCui:bmmzo6l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd6a183e3a55f196133f82100e65dd22106765e6/ios/MullvadVPN/TunnelManager/TunnelBlockObserver.swift#L14)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

How about something like this for readability?
</blockquote></details>

It's possible to annotate as:

```swift
typealias DidUpdateDeviceStateHandler = (_ tunnelManager: TunnelManager, _ newDeviceState: DeviceState, _ previousDeviceState: DeviceState) -> Void
```

Then Xcode will also auto-complete variables as it expands the closure. Is that an intention? If so that's Done.
___
*[`ios/MullvadVPN/TunnelManager/TunnelBlockObserver.swift` line 48 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4627#-NU3ykPI0iHVH3wi-mE-:-NU6MKeY5aVsdpE_h2ew:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd6a183e3a55f196133f82100e65dd22106765e6/ios/MullvadVPN/TunnelManager/TunnelBlockObserver.swift#L48)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Change to "deviceState" for consistency.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 1006 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4627#-NU3z6yfEnVu5c52Kfwm:-NU6Kqkw9Dcd4z3WlXbL:bkoztse) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd6a183e3a55f196133f82100e65dd22106765e6/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L1006)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Cool, modern concurrency API :)
</blockquote></details>

Yeah except `Task.sleep()` does not accept seconds until iOS 16 so that helper above its kind obligatory :S Otherwise it looks cleaner than callback hell.


<!-- Sent from Reviewable.io -->

2023-04-28 13:04 UTC, rablador approved these changes
> Reviewed 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4627)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/MullvadVPN/TunnelManager/TunnelBlockObserver.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4627#-NU3uziY6N9Z_235BAUM:-NU6woMQAf360iPJtEsG:bsfwd71) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd6a183e3a55f196133f82100e65dd22106765e6/ios/MullvadVPN/TunnelManager/TunnelBlockObserver.swift#L14)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

It's possible to annotate as:

```swift
typealias DidUpdateDeviceStateHandler = (_ tunnelManager: TunnelManager, _ newDeviceState: DeviceState, _ previousDeviceState: DeviceState) -> Void
```

Then Xcode will also auto-complete variables as it expands the closure. Is that an intention? If so that's Done.
</blockquote></details>

That's fine as well, although slighly more verbose.


<!-- Sent from Reviewable.io -->

2023-04-28 14:40 UTC, pronebird reviewed
> Dismissed @rablador from a discussion.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4627)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-28 14:47 UTC, merged