Dns settings text additions droid 123
mullvad/mullvadvpn-app pull request #4628
Opened 2023-04-27 15:55 UTC by sabercodic

2023-04-28 11:34 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628)* status: all files reviewed, 4 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/res/values/strings.xml` line 189 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-NU6C7kNEmcTmAqt2THg:-NU6d2_G4K731GQcwOYM:b-f0ipej) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9309a546db5cd85cf5c5a05f50739712b8c37670/android/app/src/main/res/values/strings.xml#L189)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

These are supposed to be the same so we shouldn't need to duplicate.
</blockquote></details>

We probably also want to include a dot in this one, but not the toast


<!-- Sent from Reviewable.io -->

2023-05-02 14:14 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ContentBlockersInfoDialog.kt` line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-NU6CQoGAtiPz2DqWb5l:-NUQz5mY3kmrgzLEdTXI:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9309a546db5cd85cf5c5a05f50739712b8c37670/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ContentBlockersInfoDialog.kt#L17)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can `buildString` be used here instead of varargs? Will `HtmlText` still work in that case? I believe that would improve readability. In that case please also use it as a named argument
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt` line 74 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-NU6DZGi9St0L3ysKrqr:-NUQz8YgBMUvyWpsIGlk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9309a546db5cd85cf5c5a05f50739712b8c37670/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt#L74)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

See other comment regarding `varargs`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AdvancedFragment.kt` line 89 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-NU6FT0vCiMhpnDEgjmH:-NURo9Lz6NUublhiz67E:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9309a546db5cd85cf5c5a05f50739712b8c37670/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AdvancedFragment.kt#L89)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe it would be better to handle this within the Screen since we want go get rid of the fragments. Perhaps something like the following approach using `LaunchedEffect` could work? https://stackoverflow.com/a/71036376
</blockquote></details>

Done.
___
*[`android/app/src/main/res/values/strings.xml` line 189 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-NU6C7kNEmcTmAqt2THg:-NURoC527lNPzXBuVbA3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9309a546db5cd85cf5c5a05f50739712b8c37670/android/app/src/main/res/values/strings.xml#L189)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We probably also want to include a dot in this one, but not the toast
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-02 15:11 UTC, albin-mullvad requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628)* status: all files reviewed, 3 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 132 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-NURzpFoA_2dc-V_8yWq:-NURzpFoA_2dc-V_8yWr:b-xf61pu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7df8235c4983641a48ca13a3f06c7312d815d305/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L132)):*
> ```Kotlin
>     onBackClick: () -> Unit = {},
>     onStopEvent: () -> Unit = {},
>     toastMessagesSharedFlow: SharedFlow<String>? = null
> ```

Why is this nullable with a default value? I suggest skipping that part.



_Code quote:_
```Kotlin
toastMessagesSharedFlow: SharedFlow<String>? = null
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 144 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-NUS-rd9AVbt8q8bMdap:-NUS-rd9AVbt8q8bMdaq:b-7kze29) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7df8235c4983641a48ca13a3f06c7312d815d305/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L144)):*
> ```Kotlin
>                 onSave = { onSaveMtuClick() },
>                 onRestoreDefaultValue = { onRestoreMtuClick() },
>                 onDismiss = { onCancelMtuDialogClicked() },
> ```

Why are there trailing commas added to this and many other functions? Do you have some auto-formatting thing enabled that does this?



_Code quote:_
```Kotlin
,
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 217 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-NUS-3RC71VCKU-WRYMl:-NUS-3RC71VCKU-WRYMm:b-xnouj2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7df8235c4983641a48ca13a3f06c7312d815d305/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L217)):*
> ```Kotlin
>                         }
>                     }
>                 }
> ```

This looks much more complex than the previously linked approach. Didn't that approach work?

(https://stackoverflow.com/questions/71033789/how-to-handle-one-shot-operations-in-jetpack-compose/71036376#71036376)



_Code quote:_
```Kotlin
                if (event == Lifecycle.Event.ON_CREATE) {
                    lifecycleOwner.lifecycleScope.launch {
                        toastMessagesSharedFlow?.flowWithLifecycle(
                            lifecycleOwner.lifecycle,
                            Lifecycle.State.CREATED,
                        )?.collect { msg ->
                            ContextCompat.getMainExecutor(context).execute {
                                Toast.makeText(context, msg, Toast.LENGTH_SHORT).show()
                            }
                        }
                    }
                }
```


<!-- Sent from Reviewable.io -->

2023-05-02 16:06 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 132 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-NURzpFoA_2dc-V_8yWq:-NUSCjRV-gS_lt-K0H4J:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7df8235c4983641a48ca13a3f06c7312d815d305/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L132)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why is this nullable with a default value? I suggest skipping that part.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 144 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-NUS-rd9AVbt8q8bMdap:-NUSClYw2Y8H58NMs7cL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7df8235c4983641a48ca13a3f06c7312d815d305/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L144)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why are there trailing commas added to this and many other functions? Do you have some auto-formatting thing enabled that does this?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt` line 217 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-NUS-3RC71VCKU-WRYMl:-NUSCnUs6SPKg2dc1AZM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7df8235c4983641a48ca13a3f06c7312d815d305/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt#L217)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This looks much more complex than the previously linked approach. Didn't that approach work?

(https://stackoverflow.com/questions/71033789/how-to-handle-one-shot-operations-in-jetpack-compose/71036376#71036376)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-02 16:17 UTC, albin-mullvad requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`-- commits` line 9 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-NUSEhom9-yAG16bDfH6):*
Some of the info dialog feedback fixes seem to be included in this commit. Please make sure those are part of the correct commit(s) and that the rest of the git history is correct.



_Code quote:_
```
Add warning toast for changing settings
```


<!-- Sent from Reviewable.io -->

2023-05-03 07:18 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`-- commits` line 9 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-NUSEhom9-yAG16bDfH6):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Some of the info dialog feedback fixes seem to be included in this commit. Please make sure those are part of the correct commit(s) and that the rest of the git history is correct.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-03 08:41 UTC, albin-mullvad requested changes
Please clean up the trailing commas throughout these commits, otherwise looks good!

> Reviewed 11 of 11 files at r7, 10 of 10 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-:-NUVl6eY0q5VSqFq23IN:b-qoz6ka)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-03 09:36 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-:-NUVy14k9Wtc74Yep5hf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-03 09:36 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-:-NUVy14k9Wtc74Yep5hf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-03 09:44 UTC, albin-mullvad approved these changes
> Reviewed 3 of 4 files at r10, 1 of 1 files at r12, 6 of 6 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-03 09:55 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/res/values/strings.xml` line 188 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628#-NUW1PTD02fmJFLUrUj3:-NUW1PTD02fmJFLUrUj4:b-dxlzy8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4d0f69030c6909f3fa6ffc28da7150bf8ba1507d/android/app/src/main/res/values/strings.xml#L188)):*
> ```XML
>     </string>
>     <string name="settings_changes_effect_warning_short">DNS settings might not go into effect immediately</string>
>     <string name="settings_changes_effect_warning_content_blocker">Changes to DNS related settings might not go into effect immediately due to cached results</string>
> ```

Missing dot in the end. Wasn't this issue fixed before?



_Code quote:_
```XML
Changes to DNS related settings might not go into effect immediately due to cached results
```


<!-- Sent from Reviewable.io -->

2023-05-03 10:07 UTC, albin-mullvad reviewed
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)



<!-- Sent from Reviewable.io -->

2023-05-03 10:08 UTC, albin-mullvad approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-03 10:40 UTC, merged