Cache known good api mode ios 133
mullvad/mullvadvpn-app pull request #4641
Opened 2023-05-02 13:04 UTC by buggmagnet

The scope of this ticket has slightly changed, this PR introduces a `TransportStrategy` that defines when to use a direct URLSession for reaching the API, or when to proxy requests via Shadowsocks.

At this moment, the selection of the Shadowsocks relay endpoint is still random, and the API is still hardcoded in the rust library.

Those modifications will come after we rework how the `AddressCache` works in IOS-149

2023-05-02 13:08 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641)* status: 0 of 8 files reviewed, 3 unresolved discussions

___
*[`ios/MullvadRESTTests/TransportStrategyTests.swift` line 52 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#-NURZYs2A-QlkIalN4oj:-NURZYs2A-QlkIalN4ok:b8z652o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0336c287f2550dded3cb8146c9d1c939e8bb749b/ios/MullvadRESTTests/TransportStrategyTests.swift#L52)):*
> to attempting a direct connection
This  should say "to suggest a direct connection" instead
___
*[`ios/MullvadRESTTests/TransportStrategyTests.swift` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#-NURZhd_1ciC70qtulST:-NURZhd_1ciC70qtulSU:brfj3kc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0336c287f2550dded3cb8146c9d1c939e8bb749b/ios/MullvadRESTTests/TransportStrategyTests.swift#L60)):*
> ```Swift
>         var strategy = REST.TransportStrategy()
> 
>         // First timeout should force to transport to shadowSocks
> ```

Replace "force" with "suggest"
and "attempting a direction connection" with "suggesting a direct connection"
___
*[`ios/MullvadVPN/TransportMonitor/TransportMonitor.swift` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#-NURZtFvAXEmbagCCtZ6:-NURZtFvAXEmbagCCtZ7:bns37z1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0336c287f2550dded3cb8146c9d1c939e8bb749b/ios/MullvadVPN/TransportMonitor/TransportMonitor.swift#L75)):*
> ```Swift
>     // MARK: Private API
> 
>     private func selectTransport(_ transport: RESTTransport?, useShadowsocksTransport: Bool) -> RESTTransport? {
> ```

Comment this method


<!-- Sent from Reviewable.io -->

2023-05-02 18:35 UTC, MrChocolatine commented on ios/MullvadVPN/TransportMonitor/TransportMonitor.swift
> +        }
```suggestion
        }

        return transport
```

2023-05-03 09:20 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @MrChocolatine and @pinkisemils)

___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 38 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#-NUS3xOY6as7pl4-Y0vo:-NUVuOos0FetjHmm28Vk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7cc3d3fd34b4d3a65c188a51543398515d56b24c/ios/MullvadREST/RESTTransportStrategy.swift#L38)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Timing out shouldn't necessitate a complete change - instead any kind of an error should just iterate forward. I apologize if this wasn't clear, and I am walking back on special casing timeouts here.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/TransportMonitor/TransportMonitor.swift` line 100 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#gh-1182909027:-NUVhfa6-SzZavMvY0vk:b-jsh6zc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7cc3d3fd34b4d3a65c188a51543398515d56b24c/ios/MullvadVPN/TransportMonitor/TransportMonitor.swift#L100)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

```suggestion
        }

        return transport
```
</blockquote></details>

Indeed, thanks !


<!-- Sent from Reviewable.io -->

2023-05-03 14:27 UTC, pinkisemils approved these changes
> Reviewed 2 of 8 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641)* status: all files reviewed, 1 unresolved discussion (waiting on @MrChocolatine)



<!-- Sent from Reviewable.io -->

2023-05-04 09:46 UTC, pronebird reviewed
> Reviewed 4 of 8 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641)* status: all files reviewed, 1 unresolved discussion (waiting on @MrChocolatine)

___
*[`ios/MullvadRESTTests/TransportStrategyTests.swift` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#-NUX607F0jWvsU4P4Vpf:-NUX607F0jWvsU4P4Vpg:b-jgppey) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a1564ea8dfded4783bde77f1d0f5d382d4ebd1b/ios/MullvadRESTTests/TransportStrategyTests.swift#L25)):*
> ```Swift
>     func testDefaultConnectionTransportIsDirectURLSession() {
>         let strategy = REST.TransportStrategy()
>         assertStrategy(.useURLSession, actual: strategy.connectionTransport())
> ```

FYI I think if you flip the order off arguments, i.e `strategy.connectionTransport()` first then the second argument will be inferred and hence no need for helper as `XCTAssertEqual` should just work.


<!-- Sent from Reviewable.io -->

2023-05-04 11:22 UTC, rablador requested changes
> Reviewed 2 of 8 files at r1, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @MrChocolatine)

___
*[`ios/MullvadREST/RESTTransport.swift` line 27 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#-NU_yCncAHXhz1ATk2x2:-NU_yCncAHXhz1ATk2x3:bm4x5sn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a1564ea8dfded4783bde77f1d0f5d382d4ebd1b/ios/MullvadREST/RESTTransport.swift#L27)):*
> ```Swift
> 
>     /// Requests a Shadowsocks transport
>     /// - Returns: A transport layer that proxies the requests to a local Shadowsocks proxy instance locally
> ```

Nit: local/locally repetition.
___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 42 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#-NUa07qg60mwXQXE_n2p:-NUa07qh8y0S_f2gIakW:b-cg4pmj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a1564ea8dfded4783bde77f1d0f5d382d4ebd1b/ios/MullvadREST/RESTTransportStrategy.swift#L42)):*
> ```Swift
>         /// The suggested connection transport
>         ///
>         /// - Returns: `.useURLSession` for every 3rd failed attempt, `.useShadowSocks` otherwise
> ```

`isMultiple(of: 3)` is easier to read I think. Eg.:



_Code snippet:_
```Swift
if connectionAttempts.isMultiple(of: 3) {
    return .useUrlSession
    [...]
}
```
___
*[`ios/MullvadRESTTests/TransportStrategyTests.swift` line 18 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#-NUa1Oeh50pdfUICBc8F:-NUa1Oei-qmqo1N-Sodo:b-pnov3p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a1564ea8dfded4783bde77f1d0f5d382d4ebd1b/ios/MullvadRESTTests/TransportStrategyTests.swift#L18)):*
> ```Swift
>         for index in 0 ... 12 {
>             let expectedResult: REST.TransportStrategy.Transport = index % 3 == 0 ? .useURLSession : .useShadowSocks
>             XCTAssertEqual(expectedResult, strategy.connectionTransport())
> ```

Use extension function `assertStrategy` here too?


<!-- Sent from Reviewable.io -->

2023-05-04 11:22 UTC, rablador reviewed
> Reviewed 2 of 8 files at r1, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @MrChocolatine)



<!-- Sent from Reviewable.io -->

2023-05-04 11:39 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641)* status: all files reviewed, 4 unresolved discussions (waiting on @MrChocolatine, @pronebird, and @rablador)

___
*[`ios/MullvadREST/RESTTransport.swift` line 27 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#-NU_yCncAHXhz1ATk2x2:-NUaX0vT4hTGjsrIY3cA:b-896fjx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a1564ea8dfded4783bde77f1d0f5d382d4ebd1b/ios/MullvadREST/RESTTransport.swift#L27)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: local/locally repetition.
</blockquote></details>

Done
___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 42 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#-NUa07qg60mwXQXE_n2p:-NUaWlnO11i4p4q1V8rb:b-5dypms) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a1564ea8dfded4783bde77f1d0f5d382d4ebd1b/ios/MullvadREST/RESTTransportStrategy.swift#L42)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

`isMultiple(of: 3)` is easier to read I think. Eg.:
</blockquote></details>

Definitely, I had forgotten this was a thing, thanks !
___
*[`ios/MullvadRESTTests/TransportStrategyTests.swift` line 18 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#-NUa1Oeh50pdfUICBc8F:-NUaVwFd12FSaSq6_9Zz:bj61xbx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a1564ea8dfded4783bde77f1d0f5d382d4ebd1b/ios/MullvadRESTTests/TransportStrategyTests.swift#L18)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Use extension function `assertStrategy` here too?
</blockquote></details>

I was about to, but with @pronebird's good suggestion, I'll just remove the helper function now.
___
*[`ios/MullvadRESTTests/TransportStrategyTests.swift` line 23 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#-NUaYI17-w9V8tLIJXw7:-NUaYI17-w9V8tLIJXw8:bu60qo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a1564ea8dfded4783bde77f1d0f5d382d4ebd1b/ios/MullvadRESTTests/TransportStrategyTests.swift#L23)):*
> ```Swift
>     }
> 
>     func testDefaultConnectionTransportIsDirectURLSession() {
> ```

I just realized that this test is unnecessary since it's already covered by `testEveryThirdConnectionAttemptsIsDirect` 
I will remove it.
___
*[`ios/MullvadRESTTests/TransportStrategyTests.swift` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#-NUX607F0jWvsU4P4Vpf:-NUaVGXo-JQb24yE7_8S:brcle9f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a1564ea8dfded4783bde77f1d0f5d382d4ebd1b/ios/MullvadRESTTests/TransportStrategyTests.swift#L25)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI I think if you flip the order off arguments, i.e `strategy.connectionTransport()` first then the second argument will be inferred and hence no need for helper as `XCTAssertEqual` should just work.
</blockquote></details>

TIL !
It's gonna take some time rewiring my brain, I took the habit of writing my expectations with the expected result first, because when a test fails, I want to see what's expected first before looking at what's being tested to understand the failure better.


<!-- Sent from Reviewable.io -->

2023-05-04 12:38 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r4, all commit messages.
> Dismissed @MrChocolatine from a discussion.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#-:-NUalHjYDLPMV-oyHe66:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadRESTTests/TransportStrategyTests.swift` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641#-NUX607F0jWvsU4P4Vpf:-NUak6G6EvX9IkWTQoza:bbic6lh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1a1564ea8dfded4783bde77f1d0f5d382d4ebd1b/ios/MullvadRESTTests/TransportStrategyTests.swift#L25)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

TIL !
It's gonna take some time rewiring my brain, I took the habit of writing my expectations with the expected result first, because when a test fails, I want to see what's expected first before looking at what's being tested to understand the failure better.

</blockquote></details>

Yeah that's suboptimal that Swift can't look left and right before figuring out the type. Perhaps it's worth to report as improvement to the compiler team. The other way around is to spell the entire type or use an alias inside the test case so it's less verbose. But I think it looks logical in this case as we compare the result of strategy type with a constant value.


<!-- Sent from Reviewable.io -->

2023-05-04 13:30 UTC, rablador approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-04 20:01 UTC, merged