Add custom port selection to settings
mullvad/mullvadvpn-app pull request #4656
Opened 2023-05-04 12:10 UTC by rablador

Allow users to select which port to connect to the WireGuard server over. On mobile the port is currently chosen randomly as the port constraint is set to Any and we don't expose any way to change it.

Mimic desktop port selection. It should be possible to select between "Automatic", a few hardcoded known good ports, and custom where the user enters what port they want to use.

2023-05-12 07:46 UTC, buggmagnet requested changes
> Reviewed 1 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 1 of 18 files reviewed, 21 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadTypes/RelayConstraints.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDa7870zSh9Vk85zvW:-NVDa7870zSh9Vk85zvX:bkdyogm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadTypes/RelayConstraints.swift#L13)):*
> ```Swift
> public struct RelayConstraints: Codable, Equatable, CustomDebugStringConvertible {
>     public var location: RelayConstraint<RelayLocation>
>     public var port: RelayConstraint<UInt16>?
> ```

It's already defaulted to `.any` in `init`
It's safe to remove this optional 

This should simplify line 18 to 
```
        output += "port: \(port))"
```
___
*[`ios/MullvadTypes/RelayConstraints.swift` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVD_qzPAYS6QkX3qmCj:-NVD_qzQ1Brzu6Td5CeD:b-krzuzo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadTypes/RelayConstraints.swift#L17)):*
> ```Swift
>     public var debugDescription: String {
>         var output = "RelayConstraints { "
>         output += "location: \(String(reflecting: location)), "
> ```

`reflecting` is not needed here, `RelayConstraint` already implements `CustomDebugStringConvertible`
___
*[`ios/MullvadVPN/Extensions/UISearchBar+Appearance.swift` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDdACXBTirhhA7UEPr:-NVDdACXBTirhhA7UEPs:b9hygl0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/Extensions/UISearchBar%2BAppearance.swift#L44)):*
> ```Swift
>             textField.backgroundColor = backgroundColor
> 
>             if let customTextField = searchBar as? CustomTextField {
> ```

nit: This is fine for now, but if we need to introduce more customizable text fields in the future, we should consider using a switch statement instead 

```
            switch searchBar {
            case let customTextField as CustomTextField:
                customTextField.placeholderTextColor = placeholderTextColor
            default:
                textField.attributedPlaceholder = NSAttributedString(
                    string: searchBar.placeholder ?? "",
                    attributes: [.foregroundColor: placeholderTextColor])
            }
```
___
*[`ios/MullvadVPN/Extensions/UITextField+Padding.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDdefD1LXX42obFAs1:-NVDdefD1LXX42obFAs2:b-h1bacy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/Extensions/UITextField%2BPadding.swift#L11)):*
> ```Swift
> import UIKit
> 
> extension UITextField {
> ```

This extension isn't used anywhere, did we introduce it for future use or do we want to remove it ?
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift` line 140 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDgST2ERA4573dbT5V:-NVDgST2ERA4573dbT5W:b73xc7r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesCellFactory.swift#L140)):*
> ```Swift
>             guard let cell = cell as? SelectableSettingsCell else { return }
> 
>             let portString: String
> ```

This feels a bit heavy to read.
How about this instead ? 
```
            var portString = NSLocalizedString(
                "WIRE_GUARD_PORT_CELL_LABEL",
                tableName: "Preferences",
                value: "Automatic",
                comment: ""
            )
            if let port {
                portString = String(port)
            }
```

Thanks to @pronebird's recent upgrade of the compiler, we can take advantage of the new `if let` declaration
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDiQSQ0aAE_rVz4CLM:-NVDiQSR1PQAM4lNVW5s:b-lizgj8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L79)):*
> ```Swift
>         case blockAdultContent
>         case blockGambling
>         case wireGuardPort(_ port: UInt16?)
> ```

Is nil meant to represent an automatic port selection ?
If so, I wonder if we could make it more explicit.
Let me think about it.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 199 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDjDGP7rHzQYU4Glty:-NVDjDGP7rHzQYU4Gltz:b-idt62o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L199)):*
> ```Swift
>     }
> 
>     func resetToLastPortSelection() -> Bool {
> ```

This function name could be improved IMHO
What are we resetting ?
Likely the wireGuardPort cell. Therefore the name should reflect that. 
Something along the lines of `revertWireGuardPortCellToLastSelection` ?

Why is this returning a Bool ?
From this function's context alone, I can't tell.

This probably means this method is already doing too much.
If it's resetting the wireguard port cell to a previous selection, it shouldn't be doing anything else.

I need to think more about it, but my gut feeling tells me this could, and maybe should be doing less things.

We could remove one level of "If Doom Pyramid" by starting the function with a guard statement instead.

```
    func resetToLastPortSelection() -> Bool {
        guard let customPortCell = getCustomPortCell(), customPortCell.textField.isEditing else {
            return false
        }
        if customPortCell.isValidInput {
            customPortCell.confirmInput()
        } else if let port = viewModel.wireGuardPort, viewModel.wireGuardPortIsCustom {
            customPortCell.setInput(String(port))
            customPortCell.confirmInput()
        } else {
            customPortCell.reset()
            Item.wireGuardPorts.forEach { item in
                if case let .wireGuardPort(port) = item, port == viewModel.wireGuardPort {
                    selectRow(at: indexPath(for: .wireGuardPort(port)))

                    return
                }
            }
        }
        return true
    }
```
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 371 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDmuwmBBjgPmSYMlHs:-NVDmuwmBBjgPmSYMlHt:by69s2h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L371)):*
> ```Swift
>                 .dequeueReusableHeaderFooterView(
>                     withIdentifier: HeaderFooterReuseIdentifiers.contentBlockerHeader.rawValue
>                 ) as! SettingsHeaderView
> ```

Whenever I see a forced unwrapped optional (except in test code) I'm asking myself "Does it have to be this forced unwrapped ?" And the answer is almost always no.


```
            guard let view = tableView
                .dequeueReusableHeaderFooterView(
                    withIdentifier: HeaderFooterReuseIdentifiers.contentBlockerHeader.rawValue
                ) as? SettingsHeaderView else { return nil }
            configureWireguardPortsHeader(view)
            return view
```

This won't blow up if the forced cast fails, takes the same amount of lines, and is guaranteed to behave the same way.

Alternatively, we could have `configureWireguardPortsHeader` accept optionals and start that function with an `if let` statement instead. 
___
*[`ios/Mullva [...]

2023-05-12 09:54 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 1 of 20 files reviewed, 18 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadTypes/RelayConstraints.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDa7870zSh9Vk85zvW:-NVE0nva2AbYgpBaaFOL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadTypes/RelayConstraints.swift#L13)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It's already defaulted to `.any` in `init`
It's safe to remove this optional 

This should simplify line 18 to 
```
        output += "port: \(port))"
```
</blockquote></details>

Done.
___
*[`ios/MullvadTypes/RelayConstraints.swift` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVD_qzPAYS6QkX3qmCj:-NVE0oJ3-QEeymFSt2zV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadTypes/RelayConstraints.swift#L17)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

`reflecting` is not needed here, `RelayConstraint` already implements `CustomDebugStringConvertible`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift` line 140 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDgST2ERA4573dbT5V:-NVE1f_5-BgXyoj4Ggke:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesCellFactory.swift#L140)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This feels a bit heavy to read.
How about this instead ? 
```
            var portString = NSLocalizedString(
                "WIRE_GUARD_PORT_CELL_LABEL",
                tableName: "Preferences",
                value: "Automatic",
                comment: ""
            )
            if let port {
                portString = String(port)
            }
```

Thanks to @pronebird's recent upgrade of the compiler, we can take advantage of the new `if let` declaration
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDiQSQ0aAE_rVz4CLM:-NVE1iwV-bO1m0zZRWVr:b-uyhcs4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L79)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Is nil meant to represent an automatic port selection ?
If so, I wonder if we could make it more explicit.
Let me think about it.
</blockquote></details>

It is. When there's no assigned port the app should default to automatic.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 199 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDjDGP7rHzQYU4Glty:-NVE2BEx710qUPZqNK2V:b-92zcsj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L199)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This function name could be improved IMHO
What are we resetting ?
Likely the wireGuardPort cell. Therefore the name should reflect that. 
Something along the lines of `revertWireGuardPortCellToLastSelection` ?

Why is this returning a Bool ?
From this function's context alone, I can't tell.

This probably means this method is already doing too much.
If it's resetting the wireguard port cell to a previous selection, it shouldn't be doing anything else.

I need to think more about it, but my gut feeling tells me this could, and maybe should be doing less things.

We could remove one level of "If Doom Pyramid" by starting the function with a guard statement instead.

```
    func resetToLastPortSelection() -> Bool {
        guard let customPortCell = getCustomPortCell(), customPortCell.textField.isEditing else {
            return false
        }
        if customPortCell.isValidInput {
            customPortCell.confirmInput()
        } else if let port = viewModel.wireGuardPort, viewModel.wireGuardPortIsCustom {
            customPortCell.setInput(String(port))
            customPortCell.confirmInput()
        } else {
            customPortCell.reset()
            Item.wireGuardPorts.forEach { item in
                if case let .wireGuardPort(port) = item, port == viewModel.wireGuardPort {
                    selectRow(at: indexPath(for: .wireGuardPort(port)))

                    return
                }
            }
        }
        return true
    }
```

</blockquote></details>

It's bloated and horrible indeed, but it's also a victim of the complexity of the UX. I'll see if I can find some low-hanging fruit to fix.
Regarding the return values, they're "needed" to determine whether or not the section collapse (from which this function is called) should be delayed or not. That could be moved outside though, by repeating some code.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 371 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDmuwmBBjgPmSYMlHs:-NVEGzKqAIRvvxGKd9DL:bxyy7gq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L371)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Whenever I see a forced unwrapped optional (except in test code) I'm asking myself "Does it have to be this forced unwrapped ?" And the answer is almost always no.


```
            guard let view = tableView
                .dequeueReusableHeaderFooterView(
                    withIdentifier: HeaderFooterReuseIdentifiers.contentBlockerHeader.rawValue
                ) as? SettingsHeaderView else { return nil }
            configureWireguardPortsHeader(view)
            return view
```

This won't blow up if the forced cast fails, takes the same amount of lines, and is guaranteed to behave the same way.

Alternatively, we could have `configureWireguardPortsHeader` accept optionals and start that function with an `if let` statement instead. 
</blockquote></details>

Carried over from old code. Will fix.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDbm2H40Clm0aVdzr6:-NVEI3hX5BcKW98XmB6R:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L60)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's make sure we remove this before merging 
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 64 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDb_w72ZCy7a-x7zY1:-NVEIJYj3-cJaaRuXFF9:b-lpxcqq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L64)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Was this meant to be `resetToLastPortSelection` instead ?
</blockquote></details>

Changed to revertWireGuardPortCellToLastSelection.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 136 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDqSeTDCEL-hDpHkCI:-NVEIQrO0hdYMUNAlqmg:b-vo2fza) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9 [...]

2023-05-12 09:58 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 1 of 21 files reviewed, 18 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/View controllers/Settings/SettingsInputCell.swift` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDttsoArM6P8v7wPyN:-NVENzWA5HMRgWFFeLLt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Settings/SettingsInputCell.swift#L79)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Would it make sense to have this custom `UIEdgeInsets` in the `UIMetrics` enum instead ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-12 10:37 UTC, pronebird requested changes
> Reviewed 2 of 18 files at r1, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 3 of 21 files reviewed, 19 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift` line 140 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDgST2ERA4573dbT5V:-NVETOzH4O19tn9_Fu-Y:bi4ov2f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesCellFactory.swift#L140)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@buggmagnet  you're welcome! I am a not sure if `swiftformat` understands this syntax though as we haven't merged https://github.com/mullvad/mullvadvpn-app/pull/4675 yet
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDiQSQ0aAE_rVz4CLM:-NVEVXUeASk_zj2ltJkt:bkn6fce) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L79)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It is. When there's no assigned port the app should default to automatic.
</blockquote></details>

You could introduce a type if needed to make it more explicit.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 249 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVEWZ3KBwM9DuW0bXQr:-NVEWZ3L7yLefg_MUtia:b29eh20) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/10a452b9c7ae1a007519ffacf9ad116400207aa7/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L249)):*
> ```Swift
>         case let .wireGuardPort(port):
>             if port == viewModel.wireGuardPort {
>                 selectRow(at: indexPath)
> ```

I believe the way it works with `willDisplay` is that you modify `cell.isSelected = <flag>` in here instead of calling selectRowAtIndexPath... Unless I miss something.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 136 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDqSeTDCEL-hDpHkCI:-NVEUHswAnemn-fTifws:ba2qzzi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L136)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

🙂👍
</blockquote></details>

Keep in mind that it will crash in release builds too so perhaps you want `assertionFailure`?
___
*[`ios/MullvadVPN/Extensions/UITextField+Padding.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDdefD1LXX42obFAs1:-NVETE_dAVU_Co0qumul:bu01ejl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/Extensions/UITextField%2BPadding.swift#L11)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`CustomTextField` supports text margins.


<!-- Sent from Reviewable.io -->

2023-05-12 11:16 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 3 of 21 files reviewed, 19 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift` line 140 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDgST2ERA4573dbT5V:-NVE_luc-inAnGQ2UNqZ:b-g8xmew) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesCellFactory.swift#L140)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

@buggmagnet  you're welcome! I am a not sure if `swiftformat` understands this syntax though as we haven't merged https://github.com/mullvad/mullvadvpn-app/pull/4675 yet
</blockquote></details>

Will wait a little then.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDiQSQ0aAE_rVz4CLM:-NVE_rzv4-w6OP4xKk4o:ba4eg2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L79)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You could introduce a type if needed to make it more explicit.
</blockquote></details>

I kind of think that no port is neat and simple. If you guys insist I can rework it though.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 249 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVEWZ3KBwM9DuW0bXQr:-NVEe_oY89lzJkP36Dp1:b-88wb9a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/10a452b9c7ae1a007519ffacf9ad116400207aa7/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L249)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I believe the way it works with `willDisplay` is that you modify `cell.isSelected = <flag>` in here instead of calling selectRowAtIndexPath... Unless I miss something.
</blockquote></details>

Yeah, that's probably better.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 136 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDqSeTDCEL-hDpHkCI:-NVEejPt3Zz0cGCGMY7E:b7ew7b0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L136)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Keep in mind that it will crash in release builds too so perhaps you want `assertionFailure`?
</blockquote></details>

Ah, that wasn't my intention! Will change.
___
*[`ios/MullvadVPN/Extensions/UITextField+Padding.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDdefD1LXX42obFAs1:-NVEf46k64c-BDFN3K3k:b7gaite) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/Extensions/UITextField%2BPadding.swift#L11)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`CustomTextField` supports text margins.
</blockquote></details>

Yeah, I changed to CustomTextField after buggmagnet looked at the code.


<!-- Sent from Reviewable.io -->

2023-05-12 12:01 UTC, buggmagnet requested changes
> Reviewed 2 of 18 files at r1, 3 of 8 files at r2, 2 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 10 of 22 files reviewed, 5 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/SettingsCoordinator.swift` line 174 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVEijKt8f1HTMUOruv_:-NVEijKt8f1HTMUOruva:bj088xp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e81b9a83ad413c0c083c190b3f8ca3d772680b5e/ios/MullvadVPN/Coordinators/App/SettingsCoordinator.swift#L174)):*
> ```Swift
>                 interactor: interactorFactory.makePreferencesInteractor()
>             )
>             if let relays = try? relayCacheTracker.getCachedRelays() {
> ```

This looks like a leaky abstraction.
If the `PreferencesViewController` needs access to `CachedRelays` then it should be dependency injected.

It doesn't feel right to set this property from `SettingsCoordinator`
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDiQSQ0aAE_rVz4CLM:-NVEl2sPAHsIPJUkwHKN:bw949fn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L79)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I kind of think that no port is neat and simple. If you guys insist I can rework it though.
</blockquote></details>

It's a bit awkward but let's leave it as is for now IMHO
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 199 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDjDGP7rHzQYU4Glty:-NVElIjU7EVSeatToCmi:bp6dx4s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L199)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It's bloated and horrible indeed, but it's also a victim of the complexity of the UX. I'll see if I can find some low-hanging fruit to fix.
Regarding the return values, they're "needed" to determine whether or not the section collapse (from which this function is called) should be delayed or not. That could be moved outside though, by repeating some code.
</blockquote></details>

Fair enough, maybe let's add a comment then to explain the why if we can't solve this in a straightforward way.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewModel.swift` line 295 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDrd6755iAKnfHYgXD:-NVEn-Rw-fkzQd3_36TO:b-l9peqz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewModel.swift#L295)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I agree, but it's worded that way to be similar to the already existing validation function for DNS input above. Would be easier to understand in itself if changed, but harder to understand as a "companion" function to the DNS validation function. 🤷
</blockquote></details>

Well, in that case, nothing prevents us from renaming both if it's better !
I'll leave the decision up to you.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsCell.swift` line 11 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVEo60u0gOpwQ4vLdQM:-NVEo60u0gOpwQ4vLdQN:bch0vdi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e81b9a83ad413c0c083c190b3f8ca3d772680b5e/ios/MullvadVPN/View%20controllers/Settings/SettingsCell.swift#L11)):*
> ```Swift
> import UIKit
> 
> private let contentContainerSubviewMaxCount = 2
> ```

This only pertains to`SettingsCell`, let's move it there
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsInputCell.swift` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDuOxKC_DP6SOyplNB:-NVEpOb89PpqxcLeIgee:b-26mz2r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Settings/SettingsInputCell.swift#L22)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Not sure I agree. The callback is fired when user has confirmed input (by pressing return on keyboard or the done toolbar button. So the confirmation happens then, after which the callback is picked up by the cell factory to apply the port.
</blockquote></details>

I see what you mean, I read the implementation too fast. 
It kinda feels awkard to read but that might just be me.


<!-- Sent from Reviewable.io -->

2023-05-12 13:25 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 10 of 22 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/App/SettingsCoordinator.swift` line 174 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVEijKt8f1HTMUOruv_:-NVF3_Ui8grZLPXz6L5e:bc5vou5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e81b9a83ad413c0c083c190b3f8ca3d772680b5e/ios/MullvadVPN/Coordinators/App/SettingsCoordinator.swift#L174)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This looks like a leaky abstraction.
If the `PreferencesViewController` needs access to `CachedRelays` then it should be dependency injected.

It doesn't feel right to set this property from `SettingsCoordinator`

</blockquote></details>

I think that would break the current pattern of coordinator as observer for relay updates and (provider of data), like in `SelectLocationCoordinator`/`SelectLocationViewController`. I could move that part into `PreferencesInteractor` instead, thus decoupling it from the coordinator. Or do you have any other suggestions?
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 199 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVDjDGP7rHzQYU4Glty:-NVF1iG2C9s7Db7seLyf:bv3eyrq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L199)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Fair enough, maybe let's add a comment then to explain the why if we can't solve this in a straightforward way.
</blockquote></details>

 I do think it's better now. Do you think it needs more love?
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsCell.swift` line 11 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVEo60u0gOpwQ4vLdQM:-NVF2JF36oXkRHT3HnPs:b-loldik) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e81b9a83ad413c0c083c190b3f8ca3d772680b5e/ios/MullvadVPN/View%20controllers/Settings/SettingsCell.swift#L11)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This only pertains to`SettingsCell`, let's move it there
</blockquote></details>

Instead of at the top? I feel it's easier to find raw configs for a file/class at the top.


<!-- Sent from Reviewable.io -->

2023-05-12 15:01 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 9 of 22 files reviewed, 9 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadTypes/RelayConstraints.swift` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVD_qzPAYS6QkX3qmCj:-NVELJTR1n_X_zENlkSs:b32v57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9004aabfd48bd7d9c9639046fcab8b011e0771f6/ios/MullvadTypes/RelayConstraints.swift#L17)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

`reflecting` is not needed here, `RelayConstraint` already implements `CustomDebugStringConvertible`
</blockquote></details>

+1
___
*[`ios/MullvadVPN/Coordinators/App/SettingsCoordinator.swift` line 174 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVEijKt8f1HTMUOruv_:-NVFL2OD1jBegEA-mWwS:b-8vlw4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e81b9a83ad413c0c083c190b3f8ca3d772680b5e/ios/MullvadVPN/Coordinators/App/SettingsCoordinator.swift#L174)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I think that would break the current pattern of coordinator as observer for relay updates and (provider of data), like in `SelectLocationCoordinator`/`SelectLocationViewController`. I could move that part into `PreferencesInteractor` instead, thus decoupling it from the coordinator. Or do you have any other suggestions?
</blockquote></details>

in this case dependency injection is a better approach.it's better to move it into `PreferencesInteractor`.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift` line 157 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVFLcHdDEMmx5fdxrt8:-NVFLcHdDEMmx5fdxrt9:be1d6ba) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c015983be8913c31ddc3ea8570c3486849cb93f/ios/MullvadVPN/View%20controllers/Preferences/PreferencesCellFactory.swift#L157)):*
> ```Swift
>             guard let cell = cell as? SettingsInputCell else { return }
> 
>             cell.titleLabel.text = NSLocalizedString(
> ```

i think we should do something for strings and assets in the project.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 73 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVFJvHyDOuoCzGHTdha:-NVFJvHyDOuoCzGHTdhb:b-2s47y5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c015983be8913c31ddc3ea8570c3486849cb93f/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L73)):*
> ```Swift
>     }
> 
>     enum Item: Hashable {
> ```

I think it's better to set string for raw value and conform identifiable protocol for creating accessibilityIdentifier
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 841 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVFPA8D8iHq7oT0Xz9W:-NVFPA8D8iHq7oT0Xz9X:b-9n5fuf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c015983be8913c31ddc3ea8570c3486849cb93f/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L841)):*
> ```Swift
> 
>     func didPressInfoButton(for item: InfoButtonItem) {
>         delegate?.preferencesDataSource(self, didPressInfoButton: item)
> ```

function is a behavioural part. maybe  source in function name is not good idea. for example : showInfo(_ for item : Item) could be a better option or something like that.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSourceDelegate.swift` line 22 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVFQl5B3jnouoroUelD:-NVFQl5B3jnouoroUelE:b-iq50r8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c015983be8913c31ddc3ea8570c3486849cb93f/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSourceDelegate.swift#L22)):*
> ```Swift
>     )
> 
>     func preferencesDataSource(
> ```

function name concerning like the previous comment.


<!-- Sent from Reviewable.io -->

2023-05-15 10:44 UTC, pronebird requested changes
> Reviewed 3 of 18 files at r1, 1 of 3 files at r3, 1 of 2 files at r12, 9 of 10 files at r14.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 19 of 23 files reviewed, 14 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift` line 157 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVFLcHdDEMmx5fdxrt8:-NVTu4jZ8cou3mm-qbVS:b4lick) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c015983be8913c31ddc3ea8570c3486849cb93f/ios/MullvadVPN/View%20controllers/Preferences/PreferencesCellFactory.swift#L157)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Yes, leaving this for future issue.
</blockquote></details>

@buggmagnet  I think what Morgan meant was to use swiftgen or similar if I recall her previous comments from before. That requires some careful consideration though.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 249 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVEWZ3KBwM9DuW0bXQr:-NVTu_Mp3cgjHEP8umVo:balad0h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/10a452b9c7ae1a007519ffacf9ad116400207aa7/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L249)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Actually, nope, seems not. Calling `cell.isSelected` directly seemingly circumvents the actual selection state when calling eg. `tableView.deselectRow`. This leads to cells not being correctly deselected.
</blockquote></details>

I think `willDisplay` is only meant to be used to modify cell state set by table view before presenting it on screen. 

It seems that what you should do instead is restore selection after updating the data source and reloading the table with new data instead of doing it each time the cell is presented.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 73 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVFJvHyDOuoCzGHTdha:-NVTwsA75BVmgx5So2Uy:b33ddc6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c015983be8913c31ddc3ea8570c3486849cb93f/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L73)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

We can't have cases with arguments in enums with a raw type, so that would probably change the current implementation enough to be out of scope for this PR. Unless I'm missing something that would make it easy to switch.
</blockquote></details>

Not sure I follow or how would that work for items with associated values.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 109 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVTxC5b82Ne8KCnZEit:-NVTxC5b82Ne8KCnZEiu:b-aoub5s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7388a27c2005050fa1a9acc5bb9c7d489a503532/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L109)):*
> ```Swift
>                 return "blockAdultContent"
>             case .wireGuardPort:
>                 return "wireGuardPort"
> ```

Maybe return `.wireGuardPort(\(port))` to keep accessibility identifiers unique. This is mostly used for screenshot script to navigate around UI.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 327 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVTx__PBfZT1kHPl1s5:-NVTx__PBfZT1kHPl1s6:btfww7g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7388a27c2005050fa1a9acc5bb9c7d489a503532/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L327)):*
> ```Swift
> 
>     func tableView(_ tableView: UITableView, shouldHighlightRowAt indexPath: IndexPath) -> Bool {
>         return tableView.cellForRow(at: indexPath) is SelectableSettingsCell
> ```

You probably better of relying on `Item` from data source than specific cell subclass.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 330 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVTxytd7DtCF-80N3jT:-NVTxytd7DtCF-80N3jU:b-fufzne) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7388a27c2005050fa1a9acc5bb9c7d489a503532/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L330)):*
> ```Swift
>     }
> 
>     func tableView(_ tableView: UITableView, willSelectRowAt indexPath: IndexPath) -> IndexPath? {
> ```

Why do you need to modify that?
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 341 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVTy2obBH-T6mb3tH61:-NVTy2obBH-T6mb3tH62:b-tiudga) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7388a27c2005050fa1a9acc5bb9c7d489a503532/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L341)):*
> ```Swift
> 
>     func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
>         lastSelectedIndexPath = indexPath
> ```

`tableView` supports `indexPathForSelectedRow ` or `indexPathsForSelectedRows` (for multiple selection). I'd say that you should perhaps rely on data model more than index paths. Index paths may change, data remains the same or change as well but your single source of truth should be the data.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 518 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVTxs2G-6co-58RHuin:-NVTxs2G-6co-58RHuio:b8gif1e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7388a27c2005050fa1a9acc5bb9c7d489a503532/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L518)):*
> ```Swift
>         }
> 
>         if oldSnapshot.indexOfSection(.wireGuardPorts) != nil {
> ```

Nit: there is no `contains`  or something?
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsInputCell.swift` line 54 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVTzP-B5nsdiJVNGwP7:-NVTzP-B5nsdiJVNGwP8:b-hl04ot) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7388a27c2005050fa1a9acc5bb9c7d489a503532/ios/MullvadVPN/View%20controllers/Settings/SettingsInputCell.swift#L54)):*
> ```Swift
>         if selected {
>             if textField.text?.isEmpty ?? false {
>                 textField.becomeFirstResponder()
> ```

FYI I don't quite have any alternative to this right now but it feels wrong to bring keyboard from `setSelected()` which is called by table view on many occasions. It feels that the table view controller should be able to bring keyboard on screen at the right time.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsStaticTextFooterView.swift` line 33 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVU-ZSV9OoRvio9Xb4o:-NVU-ZSV9OoRvio9Xb4p:b42rrlz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7388a27c2005050fa1a9acc5bb9c7d489a503532/ios/MullvadVPN/View%20controllers/Settings/SettingsStaticTextFooterView.swift#L33)):*
> ```Swift
>             titleLabel.trailingAnchor
>                 .constraint(equalTo: contentView.layoutMarginsGuide.trailingAnchor),
>             contentView.layoutMarginsGuide.bottomAnchor.constraint(equalTo: titleLabel.bottomAnchor, constant: 8)
> ```

FYI there is a method that enables you to apply standard spacing "after" X. I am not sure why that's needed here but here's that.


<!-- Sent from Reviewable.io -->

2023-05-15 10:44 UTC, pronebird reviewed
> Reviewed 2 of 18 files at r1, 2 of 8 files at r2, 1 of 3 files at r9, 1 of 10 files at r14.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 21 of 23 files reviewed, 14 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)



<!-- Sent from Reviewable.io -->

2023-05-15 14:13 UTC, rablador reviewed
> Dismissed @mojganii from a discussion.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 19 of 23 files reviewed, 14 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 249 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVEWZ3KBwM9DuW0bXQr:-NVUFTdE5JI9z5cqSTDB:bzjwqr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/10a452b9c7ae1a007519ffacf9ad116400207aa7/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L249)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think `willDisplay` is only meant to be used to modify cell state set by table view before presenting it on screen. 

It seems that what you should do instead is restore selection after updating the data source and reloading the table with new data instead of doing it each time the cell is presented.
</blockquote></details>

Problem with restoring state after a data source update is that the reload is animated, meaning their will be a slight delay before the selection is applied afterwards.

However, looking at the documentation, isn't `willDisplay` good for the things we're looking to do?

"This method gives the delegate a chance to override state-based properties set earlier by the table view, such as selection and background color."
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 109 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVTxC5b82Ne8KCnZEit:-NVU89fs9hK_JkUu5Gz8:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7388a27c2005050fa1a9acc5bb9c7d489a503532/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L109)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe return `.wireGuardPort(\(port))` to keep accessibility identifiers unique. This is mostly used for screenshot script to navigate around UI.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 327 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVTx__PBfZT1kHPl1s5:-NVUM78lEJqJVVHCHe1E:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7388a27c2005050fa1a9acc5bb9c7d489a503532/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L327)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You probably better of relying on `Item` from data source than specific cell subclass.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 330 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVTxytd7DtCF-80N3jT:-NVUMHuxCzIeS74dtICE:b-hn3jen) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7388a27c2005050fa1a9acc5bb9c7d489a503532/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L330)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Why do you need to modify that?
</blockquote></details>

I don't! Removed...
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 341 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVTy2obBH-T6mb3tH61:-NVUYvIR3h05ajYBmzDb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7388a27c2005050fa1a9acc5bb9c7d489a503532/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L341)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`tableView` supports `indexPathForSelectedRow ` or `indexPathsForSelectedRows` (for multiple selection). I'd say that you should perhaps rely on data model more than index paths. Index paths may change, data remains the same or change as well but your single source of truth should be the data.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 518 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVTxs2G-6co-58RHuin:-NVUZdjeD1vJzQDj1jyx:b3g012v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7388a27c2005050fa1a9acc5bb9c7d489a503532/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L518)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: there is no `contains`  or something?
</blockquote></details>

Reworked to check for existance of section identifier.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsInputCell.swift` line 54 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVTzP-B5nsdiJVNGwP7:-NVUbrK31-M8B6JvuYyu:bhefs4w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7388a27c2005050fa1a9acc5bb9c7d489a503532/ios/MullvadVPN/View%20controllers/Settings/SettingsInputCell.swift#L54)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI I don't quite have any alternative to this right now but it feels wrong to bring keyboard from `setSelected()` which is called by table view on many occasions. It feels that the table view controller should be able to bring keyboard on screen at the right time.
</blockquote></details>

I moved it out into the data source instead, now only triggering when explicitly told to do so.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsStaticTextFooterView.swift` line 33 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVU-ZSV9OoRvio9Xb4o:-NVUbDFL8z1j1ESXn09N:b-uzerik) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7388a27c2005050fa1a9acc5bb9c7d489a503532/ios/MullvadVPN/View%20controllers/Settings/SettingsStaticTextFooterView.swift#L33)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI there is a method that enables you to apply standard spacing "after" X. I am not sure why that's needed here but here's that.
</blockquote></details>

Ah, updated now. It's for some extra padding below text based footers (after consulting with Matilda).


<!-- Sent from Reviewable.io -->

2023-05-15 15:35 UTC, pronebird requested changes
> Reviewed 1 of 2 files at r15, 1 of 3 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 22 of 23 files reviewed, 9 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift` line 157 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVFLcHdDEMmx5fdxrt8:-NVUpZTk9MAkn988Puka:bgdfl0u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c015983be8913c31ddc3ea8570c3486849cb93f/ios/MullvadVPN/View%20controllers/Preferences/PreferencesCellFactory.swift#L157)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

@buggmagnet  I think what Morgan meant was to use swiftgen or similar if I recall her previous comments from before. That requires some careful consideration though.
</blockquote></details>

I meant to say Mojgan. Auto-correction malfunctioned.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 249 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVEWZ3KBwM9DuW0bXQr:-NVUoh1NEK9lNtpSFOR1:b-39dsx0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/10a452b9c7ae1a007519ffacf9ad116400207aa7/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L249)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Problem with restoring state after a data source update is that the reload is animated, meaning their will be a slight delay before the selection is applied afterwards.

However, looking at the documentation, isn't `willDisplay` good for the things we're looking to do?

"This method gives the delegate a chance to override state-based properties set earlier by the table view, such as selection and background color."
</blockquote></details>

Unless I have some misconception about that, what I think it means is that `willDisplay()` enables you to customize appearance of cell before it is rendered. State-based properties set earlier by table view are `isSelected`, `isHighlighted`, cosmetic props on cell and some others.

When you call `selectRow()` from `willDisplay` it calls `cell.setSelected(<bool>, animated: <bool>)` and I think `tableView` also sets `indexPathForSelectedRow` to the given index path which seems a bit too heavy to each time this method is called. Which I think if you swipe cells very high up so they go offscreen then they should call `willDisplay` again as you release the finger and cells slide down.

I think you should maintain selection manually, i.e model should tell you what's currently selected and not table view. 

Either way since we have data model behind, we can infer which cells are selected and mark them as such from `willDisplay()`.

```swift
func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
     guard let item = self.itemIdentifier(for: indexPath) else { return }

     if case let .wireguardPort(portNumber) = item {
          cell.isSelected = portNumber == viewModel.wireGuardPort
     }

}

func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
     guard let item = self.itemIdentifier(for: indexPath) else { return }
     
     if case let .wireguardPort(portNumber) = item {
          viewModel.wireGuardPort = portNumber
          
          updateDataSource()
     }
}

var indexPathForSelectedPort: IndexPath? {
     // Find item that corresponds to the port stored in view model
     let selectedItem = snapshot().itemIdentifiers(inSection: .customDNS).first { item in 
          guard case let .wireguardPort(portNumber) = item else { return false }
          
          return viewModel.wireGuardPort == portNumber
     }

     return selectedItem.flatMap { self.indexPath(for: $0) }
}

func updateDataSource() {
     // reload data source or whatever we do with diffable DS
     tableView.reloadData() 

     // restore selection
     indexPathForSelectedPort.flatMap { tableView.selectRow(at: $0, animated: false, scroll: .none) }
}
```


<!-- Sent from Reviewable.io -->

2023-05-16 09:08 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 21 of 23 files reviewed, 8 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 249 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVEWZ3KBwM9DuW0bXQr:-NVYnn6BDnOktelXU00g:b-lmdulo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/10a452b9c7ae1a007519ffacf9ad116400207aa7/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L249)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Unless I have some misconception about that, what I think it means is that `willDisplay()` enables you to customize appearance of cell before it is rendered. State-based properties set earlier by table view are `isSelected`, `isHighlighted`, cosmetic props on cell and some others.

When you call `selectRow()` from `willDisplay` it calls `cell.setSelected(<bool>, animated: <bool>)` and I think `tableView` also sets `indexPathForSelectedRow` to the given index path which seems a bit too heavy to each time this method is called. Which I think if you swipe cells very high up so they go offscreen then they should call `willDisplay` again as you release the finger and cells slide down.

I think you should maintain selection manually, i.e model should tell you what's currently selected and not table view. 

Either way since we have data model behind, we can infer which cells are selected and mark them as such from `willDisplay()`.

```swift
func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
     guard let item = self.itemIdentifier(for: indexPath) else { return }

     if case let .wireguardPort(portNumber) = item {
          cell.isSelected = portNumber == viewModel.wireGuardPort
     }

}

func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
     guard let item = self.itemIdentifier(for: indexPath) else { return }
     
     if case let .wireguardPort(portNumber) = item {
          viewModel.wireGuardPort = portNumber
          
          updateDataSource()
     }
}

var indexPathForSelectedPort: IndexPath? {
     // Find item that corresponds to the port stored in view model
     let selectedItem = snapshot().itemIdentifiers(inSection: .customDNS).first { item in 
          guard case let .wireguardPort(portNumber) = item else { return false }
          
          return viewModel.wireGuardPort == portNumber
     }

     return selectedItem.flatMap { self.indexPath(for: $0) }
}

func updateDataSource() {
     // reload data source or whatever we do with diffable DS
     tableView.reloadData() 

     // restore selection
     indexPathForSelectedPort.flatMap { tableView.selectRow(at: $0, animated: false, scroll: .none) }
}
```
</blockquote></details>

We need to take the custom port into consideration as well, so I made a variant on the suggestion above. Works well in practice, but please have a look at the code :)


<!-- Sent from Reviewable.io -->

2023-05-16 09:44 UTC, buggmagnet requested changes
> Reviewed 3 of 18 files at r1, 1 of 3 files at r3, 1 of 1 files at r8, 1 of 2 files at r12, 5 of 10 files at r14, 1 of 2 files at r15, 2 of 3 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 21 of 23 files reviewed, 11 unresolved discussions (waiting on @mojganii, @pronebird, and @rablador)

___
*[`ios/MullvadTypes/RelayConstraints.swift` line 17 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVYo7BN5i-P0RofmCFi:-NVYo7BN5i-P0RofmCFj:b-kim1zr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2adb7df050d42a6803446eb12e44e507907b4c5e/ios/MullvadTypes/RelayConstraints.swift#L17)):*
> ```Swift
>     public var debugDescription: String {
>         var output = "RelayConstraints { "
>         output += "location: \(String(reflecting: location)), "
> ```

`output += "location: \(location),`
___
*[`ios/MullvadVPN/Coordinators/App/SettingsCoordinator.swift` line 132 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVYoGFH94IJ72kIZXTr:-NVYoGFH94IJ72kIZXTs:b-ail3o2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2adb7df050d42a6803446eb12e44e507907b4c5e/ios/MullvadVPN/Coordinators/App/SettingsCoordinator.swift#L132)):*
> ```Swift
>     }
> 
> //    // MARK: - RelayCacheTrackerObserver
> ```

If it's unused, please delete these lines
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 854 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVYt9Pg3w397NX9iK1M:-NVYt9Ph273AANWLLtbR:b-qsfs22) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2adb7df050d42a6803446eb12e44e507907b4c5e/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L854)):*
> ```Swift
>     }
> 
>     func didChangeCustomPortEntry(_ inputString: String) -> Bool {
> ```

This function name is misleading IMHO

I suggest renaming it to `selectCustomPortEntry` to reflect what it does.

It's  especially important given how it's used, for example

```
                let isValidInput = delegate?.didChangeCustomPortEntry(String(port)) ?? false
```

Just from that line, I don't expect it to change the current row selection, and yet it does.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsInputCell.swift` line 11 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVYuV1f0yIcPJEXyA1f:-NVYuV1g27nnN6EsNXjg:bnqvnf3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2adb7df050d42a6803446eb12e44e507907b4c5e/ios/MullvadVPN/View%20controllers/Settings/SettingsInputCell.swift#L11)):*
> ```Swift
> import UIKit
> 
> private var textFieldSize = CGSize(width: 100, height: 30)
> ```

Please move this inside the class's declaration
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsInputCell.swift` line 17 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVYurrt5GLJcyjqxwIV:-NVYurrt5GLJcyjqxwIW:bdqh2s7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2adb7df050d42a6803446eb12e44e507907b4c5e/ios/MullvadVPN/View%20controllers/Settings/SettingsInputCell.swift#L17)):*
> ```Swift
>     var toolbarDoneButton = UIBarButtonItem()
> 
>     var isValidInput = true { didSet {
> ```

This is very confusing to read.

I suggest instead to just have the `didSet` here
```
    var isValidInput: Bool {
        didSet {
            updateTextFieldInputValidity()
        }
    }
```

and set `isValidInput` to true before the call to `super.init` 
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsInputCell.swift` line 88 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVYvuxi-1zXnqf7XjdP:-NVYvuxi-1zXnqf7XjdQ:bbipbde) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2adb7df050d42a6803446eb12e44e507907b4c5e/ios/MullvadVPN/View%20controllers/Settings/SettingsInputCell.swift#L88)):*
> ```Swift
>         textField.inputAccessoryView = toolbar
> 
>         toolbar.sizeToFit()
> ```

Maybe I'm missing context here, but wouldn't it make more sense to move this call to _after_ we set the toolbar items ?


<!-- Sent from Reviewable.io -->

2023-05-16 10:01 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 21 of 23 files reviewed, 11 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadTypes/RelayConstraints.swift` line 17 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVYo7BN5i-P0RofmCFi:-NVYxjnsCW6RSOGMCONw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2adb7df050d42a6803446eb12e44e507907b4c5e/ios/MullvadTypes/RelayConstraints.swift#L17)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

`output += "location: \(location),`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/SettingsCoordinator.swift` line 132 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVYoGFH94IJ72kIZXTr:-NVYxWTBBSSVvpyqD3Mu:b5od0bv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2adb7df050d42a6803446eb12e44e507907b4c5e/ios/MullvadVPN/Coordinators/App/SettingsCoordinator.swift#L132)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

If it's unused, please delete these lines
</blockquote></details>

Ah, forgot.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 854 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVYt9Pg3w397NX9iK1M:-NVYyRC-DjV5jQzfo-Px:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2adb7df050d42a6803446eb12e44e507907b4c5e/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L854)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This function name is misleading IMHO

I suggest renaming it to `selectCustomPortEntry` to reflect what it does.

It's  especially important given how it's used, for example

```
                let isValidInput = delegate?.didChangeCustomPortEntry(String(port)) ?? false
```

Just from that line, I don't expect it to change the current row selection, and yet it does.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsInputCell.swift` line 11 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVYuV1f0yIcPJEXyA1f:-NVYzvBv1Hyw3153y5Ta:b-7gnwgv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2adb7df050d42a6803446eb12e44e507907b4c5e/ios/MullvadVPN/View%20controllers/Settings/SettingsInputCell.swift#L11)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Please move this inside the class's declaration
</blockquote></details>

Moving it into the class makes compiler complain about properties being used before self is available. Removed it instead.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsInputCell.swift` line 17 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVYurrt5GLJcyjqxwIV:-NVYz1j1AJ10zdQIVfl_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2adb7df050d42a6803446eb12e44e507907b4c5e/ios/MullvadVPN/View%20controllers/Settings/SettingsInputCell.swift#L17)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This is very confusing to read.

I suggest instead to just have the `didSet` here
```
    var isValidInput: Bool {
        didSet {
            updateTextFieldInputValidity()
        }
    }
```

and set `isValidInput` to true before the call to `super.init` 
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsInputCell.swift` line 88 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVYvuxi-1zXnqf7XjdP:-NVYz4iS9t7pwu8AHWf1:bedn6gr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2adb7df050d42a6803446eb12e44e507907b4c5e/ios/MullvadVPN/View%20controllers/Settings/SettingsInputCell.swift#L88)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Maybe I'm missing context here, but wouldn't it make more sense to move this call to _after_ we set the toolbar items ?
</blockquote></details>

It was an attempt to quell the autolayout demons by helping the toolbar get a non-hardcoded initial size. It seemed to work at first, but when I tested some more I did find errors in the log after all. Changed implementation.


<!-- Sent from Reviewable.io -->

2023-05-17 10:13 UTC, pronebird reviewed
> Reviewed 4 of 5 files at r22.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 22 of 23 files reviewed, 12 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadTypes/RelayConstraints.swift` line 16 at r22](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVd9YgfALWZxvEAILGC:-NVd9YgfALWZxvEAILGD:b-hn1bxd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9bb4b61a3045ffdc1fa56d38d54022d721497a34/ios/MullvadTypes/RelayConstraints.swift#L16)):*
> ```Swift
> 
>     public var debugDescription: String {
>         var output = "RelayConstraints { "
> ```

Nit: you could probably inline it into `return "<output here>"`. Not sure how long it would be but defo less than 120 chars per line.
___
*[`ios/MullvadVPN/View controllers/Settings/SettingsInputCell.swift` line 88 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVYvuxi-1zXnqf7XjdP:-NVdA4598UX4NF9DEsV_:boii0h5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2adb7df050d42a6803446eb12e44e507907b4c5e/ios/MullvadVPN/View%20controllers/Settings/SettingsInputCell.swift#L88)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It was an attempt to quell the autolayout demons by helping the toolbar get a non-hardcoded initial size. It seemed to work at first, but when I tested some more I did find errors in the log after all. Changed implementation.
</blockquote></details>

ps: I think `sizeToFit()` is used to simply set default width and height of toolbar as opposed to passing `UIScreen.main.bounds.width` and `44`.


<!-- Sent from Reviewable.io -->

2023-05-17 10:22 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 22 of 23 files reviewed, 11 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 73 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVFJvHyDOuoCzGHTdha:-NVdDWTTE1laj8A5sHLv:b-tblky2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c015983be8913c31ddc3ea8570c3486849cb93f/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L73)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Not sure I follow or how would that work for items with associated values.
</blockquote></details>

@mojganii Do you want to follow up on this discussion or should I close it?


<!-- Sent from Reviewable.io -->

2023-05-17 12:07 UTC, pronebird requested changes
> Reviewed 1 of 1 files at r23.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: all files reviewed, 13 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewModel.swift` line 152 at r23](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVd_dxh5HJiz9pOEUIX:-NVd_dxh5HJiz9pOEUIY:b-sudsgk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61d7d2193f2844670a5ab0c23d799ea1808de71b/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewModel.swift#L152)):*
> ```Swift
> 
>     var customWireGuardPort: UInt16? {
>         if let port = wireGuardPort {
> ```

Nit: you could `wireGuardPort.flatMap { .. }` to avoid `return nil` at the end.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewModel.swift` line 175 at r23](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVda4u04CUhk5YGy43P:-NVda4u04CUhk5YGy43Q:b-rriocv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61d7d2193f2844670a5ab0c23d799ea1808de71b/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewModel.swift#L175)):*
> ```Swift
>     /// Produce merged view model keeping entry `identifier` for matching DNS entries.
>     func merged(_ other: PreferencesViewModel) -> PreferencesViewModel {
>         var mergedViewModel = PreferencesViewModel()
> ```

it does feel that we mostly copy fields except we merge custom DNS entries to avoid duplicates etc.. I think for the most part we could copy everything and then filter domains, i.e:

```swift
var otherDNS = other.customDNSDomains
var currentDNS = customDNSDomains

var mergedViewModel = other
mergedViewModel.customDNSDomains = // filtered domains
```

Also you never copy `availableWireGuardPortRanges`. Not sure maybe we don't have to?
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewModel.swift` line 283 at r23](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVd_0vh-NYbUPjCe3Es:-NVd_0vh-NYbUPjCe3Et:b-slj48g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61d7d2193f2844670a5ab0c23d799ea1808de71b/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewModel.swift#L283)):*
> ```Swift
> 
>     /// Returns true if the given port is in within the supported ranges.
>     func isPortWithinValidWireGuardRanges(_ string: String) -> Bool {
> ```

This could be simplified by passing `UInt16` input instead.


<!-- Sent from Reviewable.io -->

2023-05-17 12:21 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: all files reviewed, 15 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 398 at r23](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVdbZ9A2ize9-PtW-mS:-NVdbZ9A2ize9-PtW-mT:bvpcrx8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61d7d2193f2844670a5ab0c23d799ea1808de71b/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L398)):*
> ```Swift
>                     withIdentifier: HeaderFooterReuseIdentifiers.customDNSFooter.rawValue
>                 )
>             configureFooterView(reusableView as! SettingsStaticTextFooterView)
> ```

May I ask you to refactor this to avoid force wrapping, i.e:

```swift
(reusableView as? SettingsStaticTextFooterView).flatMap { configureFooterView($0) }
```
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 537 at r23](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVdbtHiDoZPIycF0Apj:-NVdbtHiDoZPIycF0Apk:b-qpambj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61d7d2193f2844670a5ab0c23d799ea1808de71b/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L537)):*
> ```Swift
>         }
> 
>         apply(newSnapshot, animatingDifferences: animated) { [weak self] in
> ```

FYI these two lines repeats a few times, we could perhaps add a helper to do that. Also marked another place where it repeats below.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 770 at r23](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVdc3ns4fE1bisOgniB:-NVdc3ns4fE1bisOgniC:b-5n1yqc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61d7d2193f2844670a5ab0c23d799ea1808de71b/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L770)):*
> ```Swift
>                 headerView.isExpanded.toggle()
> 
>                 self?.apply(snapshot, animatingDifferences: true) {
> ```

And repeats here as well.


<!-- Sent from Reviewable.io -->

2023-05-17 14:47 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 20 of 23 files reviewed, 14 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 398 at r23](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVdbZ9A2ize9-PtW-mS:-NVdjIEjEpMopSRSXj59:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61d7d2193f2844670a5ab0c23d799ea1808de71b/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L398)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

May I ask you to refactor this to avoid force wrapping, i.e:

```swift
(reusableView as? SettingsStaticTextFooterView).flatMap { configureFooterView($0) }
```
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 770 at r23](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVdc3ns4fE1bisOgniB:-NVdlAaMApet0hYmrZsk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61d7d2193f2844670a5ab0c23d799ea1808de71b/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L770)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

And repeats here as well.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewModel.swift` line 175 at r23](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVda4u04CUhk5YGy43P:-NVeAPDl5rhfKGyc1HPR:b-lo3n3r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61d7d2193f2844670a5ab0c23d799ea1808de71b/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewModel.swift#L175)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

it does feel that we mostly copy fields except we merge custom DNS entries to avoid duplicates etc.. I think for the most part we could copy everything and then filter domains, i.e:

```swift
var otherDNS = other.customDNSDomains
var currentDNS = customDNSDomains

var mergedViewModel = other
mergedViewModel.customDNSDomains = // filtered domains
```

Also you never copy `availableWireGuardPortRanges`. Not sure maybe we don't have to?
</blockquote></details>

Done. Plus, `availableWireGuardPortRanges` should be added as well.
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewModel.swift` line 283 at r23](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVd_0vh-NYbUPjCe3Es:-NVdlDGg5EOQuBnawbrE:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/61d7d2193f2844670a5ab0c23d799ea1808de71b/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewModel.swift#L283)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This could be simplified by passing `UInt16` input instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-25 08:27 UTC, pronebird approved these changes
> Reviewed 7 of 9 files at r25, 4 of 4 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: all files reviewed, 10 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2023-05-29 13:04 UTC, pronebird requested changes
> Reviewed 23 of 23 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: all files reviewed, 12 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift` line 38 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NWba4E-15nHll2tMPrx:-NWba4E-15nHll2tMPry:byhtbqh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8968c28660e8a1c5cc69e4bce0a90889a32939f1/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotificationProvider.swift#L38)):*
> ```Swift
>         let stylingOptions = NSAttributedString.MarkdownStylingOptions(font: .systemFont(ofSize: 14.0))
> 
>         return NSMutableAttributedString(markdownString: string, options: stylingOptions) { markdownType, string in
> ```

Just noticed, does it have to be mutable or we can return `NSAttrbiutedString` instead?
___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 0 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NWbb4hKBnDaJcfJ9CJB:-NWbb4hKBnDaJcfJ9CJC:b4zn0lz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8968c28660e8a1c5cc69e4bce0a90889a32939f1/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L0)):*
Is it really deleted?


<!-- Sent from Reviewable.io -->

2023-05-29 14:10 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: all files reviewed, 12 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift` line 73 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NVFJvHyDOuoCzGHTdha:-NWbpa_m0ue-MfK537Y6:b-grk0q0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2c015983be8913c31ddc3ea8570c3486849cb93f/ios/MullvadVPN/View%20controllers/Preferences/PreferencesDataSource.swift#L73)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

@mojganii Do you want to follow up on this discussion or should I close it?
</blockquote></details>

close it


<!-- Sent from Reviewable.io -->

2023-05-29 14:11 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-:-NWbqMnZ4R5f_L2Notkv:bnfp4nl)* status: all files reviewed, 11 unresolved discussions (waiting on @buggmagnet and @rablador)



<!-- Sent from Reviewable.io -->

2023-05-29 14:18 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 10 files at r14, 2 of 5 files at r22, 1 of 1 files at r23, 4 of 6 files at r24, 5 of 9 files at r25, 3 of 4 files at r26, 23 of 23 files at r27, 3 of 22 files at r28.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-:-NWbs3zo14Se0PldtGp0:bnfp4nl)* status: 23 of 42 files reviewed, 5 unresolved discussions (waiting on @mojganii, @pronebird, and @rablador)



<!-- Sent from Reviewable.io -->

2023-05-29 14:27 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: 22 of 42 files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift` line 38 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NWba4E-15nHll2tMPrx:-NWbtNbv9Jenuz-QohEG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8968c28660e8a1c5cc69e4bce0a90889a32939f1/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotificationProvider.swift#L38)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Just noticed, does it have to be mutable or we can return `NSAttrbiutedString` instead?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line  at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656#-NWbb4hKBnDaJcfJ9CJB:-NWbtP2D5vVwGrNAkHLK:b-ou50ma) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8968c28660e8a1c5cc69e4bce0a90889a32939f1/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Is it really deleted?
</blockquote></details>

Error on my part!


<!-- Sent from Reviewable.io -->

2023-06-06 08:03 UTC, pronebird reviewed
> Reviewed 17 of 22 files at r28, 8 of 8 files at r30.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2023-06-06 14:03 UTC, merged