Add text style and dimensions to use in compose
mullvad/mullvadvpn-app pull request #4665
Opened 2023-05-08 09:45 UTC by Pururun

This is an attempt to add text styles and dimensions in a way to does not use xml but instead using something more native to compose.

It uses `List` as a proof of concept.

Also it tries to migrate away from using static colors and instead use colors defined in the theme. This is enable support for things like dark/light theme in the future.

**Dimensions**
Dimensions are setup in a data class called dimensions. There's also a default implementation called `defaultDimensions`. The dimensions file that is actually used is called `Dimen` and that can depending on what configurations we want to use use different implementations of `Dimensions`. This should be more or less be similar to how `dimensions.xml` works. If we feel lik it we can support for more configurations in the future.

**TextStyle**
Currently I have added one new text style `listItemText` as an extension. This is following the android documentation on how to add more types of text styles to the typography. I've also added a material 3 Typography class so that we can change the default text styles in the future, but that should be done in collaboration with design.

Finally I've added an object for static font sizes. This is how font sizes are defined in the material 3 typography for default text styles so I've tried to follow that. The intention is not to use those directly in the compose files, but rather use text styles.

Resources:
**Dimensions**
https://proandroiddev.com/supporting-different-screen-sizes-on-android-with-jetpack-compose-f215c13081bd
**TextStyle**
https://www.jetpackcompose.net/themes-in-jetpack-compose
https://developer.android.com/jetpack/compose/designsystems/custom#extending-material

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4665)

2023-05-11 13:21 UTC, albin-mullvad requested changes
> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4665)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt` line 143 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4665#-NV9uyeN-8ubr8WA2DV8:-NV9uyeN-8ubr8WA2DV9:b-sf6hfv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e7dae88b7e03eab4294e464864919762513a815b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt#L143)):*
> ```Kotlin
> 
> private val TextColor: Color
>     @Composable get() = MaterialTheme.colorScheme.onPrimary
> ```

Seems like we would need define colors like these in many views if we follow this pattern. Can it be made more conventient?



_Code quote:_
```Kotlin
private val BackgroundColor: Color
    @Composable get() = MaterialTheme.colorScheme.primary

private val TextColor: Color
    @Composable get() = MaterialTheme.colorScheme.onPrimary
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/Typeface.kt` line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4665#-NV9wqzbBH28mgaovEq1:-NV9wqzbBH28mgaovEq2:b-bbzq93) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e7dae88b7e03eab4294e464864919762513a815b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/Typeface.kt#L9)):*
> ```Kotlin
> import androidx.compose.ui.unit.TextUnit
> 
> // Add text styles not in the material theme here
> ```

Any idea of how many styles will be added here compared with the theme?



_Code quote:_
```Kotlin
// Add text styles not in the material theme here
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/Typeface.kt` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4665#-NV9wzE05Fo_NJf371BT:-NV9wzE05Fo_NJf371BU:bzdm8vf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e7dae88b7e03eab4294e464864919762513a815b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/Typeface.kt#L10)):*
> ```Kotlin
> 
> // Add text styles not in the material theme here
> val Typography.listItemText: TextStyle
> ```

Can this style name be algined with one of the text styles in Zeplin?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/TypeScale.kt` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4665#-NV9xu066Sscwl5QRpGi:-NV9xu066Sscwl5QRpGj:bjkuhuh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e7dae88b7e03eab4294e464864919762513a815b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/TypeScale.kt#L6)):*
> ```Kotlin
> 
> object TypeScale {
>     val ListItemTextSize = 18.sp
> ```

Is this list item specific or can it have a more generic name? For example we currently have a dimen called `text_medium_plus` 



_Code quote:_
```Kotlin
ListItemTextSize
```


<!-- Sent from Reviewable.io -->

2023-05-12 09:40 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4665)* status: all files reviewed, 4 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/TypeScale.kt` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4665#-NV9xu066Sscwl5QRpGi:-NVEIRRl8WJm_n2vKvn7:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e7dae88b7e03eab4294e464864919762513a815b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/TypeScale.kt#L6)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this list item specific or can it have a more generic name? For example we currently have a dimen called `text_medium_plus` 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-12 09:48 UTC, albin-mullvad reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4665)* status: all files reviewed, 3 unresolved discussions (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2023-05-12 11:55 UTC, albin-mullvad reviewed
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4665)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/TypeScale.kt` line 6 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4665#-NVEnVVF7nOEjoVEFLCq:-NVEnVVF7nOEjoVEFLCr:b3765h7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d1b1ef00e414b8affd1dd9358805a3d6fb870244/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/TypeScale.kt#L6)):*
> ```Kotlin
> 
> //Do not use these font sizes directly
> //Instead use the styles defined in Typeface and/or the standard styles in the material theme
> ```

Please change the formatting of this comment to include a space after `//` and to not break the line before `100` unless necessary.



_Code quote:_
```Kotlin
//Do not use these font sizes directly
//Instead use the styles defined in Typeface and/or the standard styles in the material theme
```


<!-- Sent from Reviewable.io -->

2023-05-12 13:02 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4665)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/TypeScale.kt` line 6 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4665#-NVEnVVF7nOEjoVEFLCq:-NVF2XzM5Z1nIXRB7Inq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d1b1ef00e414b8affd1dd9358805a3d6fb870244/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/TypeScale.kt#L6)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Please change the formatting of this comment to include a space after `//` and to not break the line before `100` unless necessary.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-12 13:19 UTC, albin-mullvad approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4665)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-12 13:25 UTC, merged