Sometimes the device/time-left header disappears
mullvad/mullvadvpn-app pull request #4666
Opened 2023-05-08 11:34 UTC by mojganii

Sometimes the device header disappears in the no time left view, possibly in others. This obviously shouldn't happen.

- add `prefersNotificationBarHidden` into `RootContainment` to avoid showing in app banner notification header in some viewControllers login view controller.the default value is false.
- trigger device name in app banner in just case user state is changed from logged out to logged in
- fix spelling mistakes for `RootConfiguration` & `didUpdateDeviceState` closure

2023-05-08 12:12 UTC, rablador requested changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Containers/Root/RootContainerViewController.swift` line 782 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NUvDt6x1aDNCOyYcU4R:-NUvDt6x1aDNCOyYcU4S:ba8hul3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/98c8a75809af5dedcb12df3e28da923b0f104ef3/ios/MullvadVPN/Containers/Root/RootContainerViewController.swift#L782)):*
> ```Swift
>     }
> 
>     private func hideNotificationView(_ isHidden: Bool) {
> ```

Is the intention to explicitly hide the view or dismiss the notification. If the latter, consider using `NotificationController.setNotifications` with an empty list instead.


<!-- Sent from Reviewable.io -->

2023-05-08 13:48 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Containers/Root/RootContainerViewController.swift` line 782 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NUvDt6x1aDNCOyYcU4R:-NUvax9kCixdcF8UwplS:b-dqvpx6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/98c8a75809af5dedcb12df3e28da923b0f104ef3/ios/MullvadVPN/Containers/Root/RootContainerViewController.swift#L782)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

i think this way makes the code more readable instead of set notifications with an empty array
</blockquote></details>

As discussed on Slack, I agree that it is less readable with a call passing an empty array, but if `NotificationController` is kept in memory and we simply hide the whole view I'm a little concerned that we'll up in a bad state. On the other hand, if hiding is only temporary (ie, all logic runs behind the scenes until we show the view again), then maybe it's fine.


<!-- Sent from Reviewable.io -->

2023-05-08 14:27 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/Containers/Root/RootContainerViewController.swift` line 782 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NUvDt6x1aDNCOyYcU4R:-NUvk1-R4ZkKEeimrDhq:bn9vyaz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/98c8a75809af5dedcb12df3e28da923b0f104ef3/ios/MullvadVPN/Containers/Root/RootContainerViewController.swift#L782)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

As discussed on Slack, I agree that it is less readable with a call passing an empty array, but if `NotificationController` is kept in memory and we simply hide the whole view I'm a little concerned that we'll up in a bad state. On the other hand, if hiding is only temporary (ie, all logic runs behind the scenes until we show the view again), then maybe it's fine.
</blockquote></details>

It publishes notifications once.by default the value of this flag is false that means view should show the notification unless we explicitly define in a particular part of views  we don't want to show any notifications 


<!-- Sent from Reviewable.io -->

2023-05-08 14:47 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-:-NUvp6x88nGDSOzd0ZPA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-05-08 14:47 UTC, buggmagnet approved these changes
> Reviewed 6 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-05-08 21:16 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-09 09:06 UTC, rablador requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NUzkXvx1D6Hy_vcmNot:-NUzkXvx1D6Hy_vcmNou:b-e0sip4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f26f533dc81b8b080c6f17e4a693f94453fd0f2b/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotificationProvider.swift#L24)):*
> ```Swift
>         didSet {
>             // Invalidate notification after one second for the sake of transition animation
>             DispatchQueue.global().asyncAfter(deadline: .now() + .seconds(1), execute: .init(block: { [weak self] in
> ```

This can probably be called async on the main queue directly.


<!-- Sent from Reviewable.io -->

2023-05-09 09:30 UTC, pronebird requested changes
> Reviewed 5 of 10 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: all files reviewed, 5 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 711 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NUzkznbBLXDEX34VO5G:-NUzkznbBLXDEX34VO5H:bg0q71l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f26f533dc81b8b080c6f17e4a693f94453fd0f2b/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L711)):*
> ```Swift
>         case let .loggedIn(accountData, _):
>             updateOutOfTimeTimer(accountData: accountData)
>             updateView(deviceState: deviceState, showDeviceInfo: false)
> ```

This will execute each time we update `accountData` which will hide device info once again.

I spoke about that the other week that when user buys more credit the same state will be returned but new data, for example:

```swift
switch (previousDeviceState, deviceState) {
  case let (.loggedIn(oldAccountData, _), .loggedIn(newAccountData, _)):
      // oldAccountData.expiry => 2023-05-09 00:00:00
      // newAccountData.expiry => 2023-06-09 00:00:00
}
```
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 870 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NUzjiDB16U36uWwq_js:-NUzjiDB16U36uWwq_jt:bfb2m8x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f26f533dc81b8b080c6f17e4a693f94453fd0f2b/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L870)):*
> ```Swift
>         let showsDeviceInfo = !notifications
>             .contains(where: { $0.identifier == RegisteredDeviceInAppNotificationProvider.identifier }) && tunnelManager
>             .deviceState.isLoggedIn
> ```

Perhaps you don't need to check for `deviceState.isLoggedIn` since this notification should not be in the list when that happens.
___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift` line 87 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NUzi4Cq5mrozWqbGpHt:-NUzi4Cq5mrozWqbGpHu:bg471m5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f26f533dc81b8b080c6f17e4a693f94453fd0f2b/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotificationProvider.swift#L87)):*
> ```Swift
>         tunnelObserver =
>             TunnelBlockObserver(didUpdateDeviceState: { [weak self] tunnelManager, deviceState, previousDeviceState in
>                 if previousDeviceState == .loggedOut,
> ```

Nit: it would be a bit easier to follow as a switch over `(previousDeviceState, deviceState)`
___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift` line 91 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NUzkBQEDm7Dm8kpbIvS:-NUzkBQEDm7Dm8kpbIvT:b-162cdb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f26f533dc81b8b080c6f17e4a693f94453fd0f2b/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotificationProvider.swift#L91)):*
> ```Swift
>                 {
>                     self?.storedDeviceData = deviceState.deviceData
>                     self?.showsInAppNotification = true
> ```

Transition is only delayed when moving from `loggedOut -> loggedIn` state in the UI, so perhaps it would be better to delay it here and call `invalidate()` directly. 

When going `loggedIn -> (loggedOut || revoked)` you could call `invalidate()` immediately without delay since there is nothing to wait for.


<!-- Sent from Reviewable.io -->

2023-05-09 09:58 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: all files reviewed, 5 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NUzkXvx1D6Hy_vcmNot:-NUzwUX45DI13Ec_5TQR:b-f75ma4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f26f533dc81b8b080c6f17e4a693f94453fd0f2b/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotificationProvider.swift#L24)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

yep.
</blockquote></details>

What's this `.init`?


<!-- Sent from Reviewable.io -->

2023-05-10 08:32 UTC, pronebird requested changes
> Reviewed 1 of 10 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: all files reviewed, 6 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift` line 85 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NV3mHzN296meB18us95:-NV3mHzN296meB18us96:b-dx28jo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5bea3123004d00a73ba16bcf652263e9cb884e2c/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotificationProvider.swift#L85)):*
> ```Swift
>                     DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(1), execute: .init(block: { [weak self] in
>                         self?.invalidate()
>                         self?.isNewDeviceRegistered = false
> ```

Perhaps you should only do that when user taps the button? Then tell the delegate that that happened by calling `sendAction()`


<!-- Sent from Reviewable.io -->

2023-05-10 10:29 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: 5 of 10 files reviewed, 6 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 711 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NUzkznbBLXDEX34VO5G:-NUzvU7v4aYDSuhvpwwN:b-thkr97) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f26f533dc81b8b080c6f17e4a693f94453fd0f2b/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L711)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This will execute each time we update `accountData` which will hide device info once again.

I spoke about that the other week that when user buys more credit the same state will be returned but new data, for example:

```swift
switch (previousDeviceState, deviceState) {
  case let (.loggedIn(oldAccountData, _), .loggedIn(newAccountData, _)):
      // oldAccountData.expiry => 2023-05-09 00:00:00
      // newAccountData.expiry => 2023-06-09 00:00:00
}
```
</blockquote></details>

this in app notification is for showing device name that is in StoredDeviceData.so my current condition is based on what we discussed last week and it doesn't break.when user turns into from logged out to logged in it invalidate itself and return value for notificationDescriptor and when goes from login to invoke or logged out it invalidate itself with nil value for notificationDescriptor.
Any way,I thought maybe is better to choose meaningful label for that flag to make it easier to be understandable. 
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 870 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NUzjiDB16U36uWwq_js:-NV3W5BB5EYLBnpm-5Uw:b-3oalvg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f26f533dc81b8b080c6f17e4a693f94453fd0f2b/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L870)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Perhaps you don't need to check for `deviceState.isLoggedIn` since this notification should not be in the list when that happens.
</blockquote></details>

after refactoring notification part and adding send block and call it in different method at application coordinator, yes there is no need.
___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NUzkXvx1D6Hy_vcmNot:-NV3Y4uZDiShX-o88yPp:bep2vpt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f26f533dc81b8b080c6f17e4a693f94453fd0f2b/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotificationProvider.swift#L24)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

What's this `.init`?
</blockquote></details>

I used dispatch work item form of this function(different form of the function).but I changed it and followed current codebase
___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift` line 87 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NUzi4Cq5mrozWqbGpHt:-NV3YNIf9qUyLQ1JIbaf:b-pgend1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f26f533dc81b8b080c6f17e4a693f94453fd0f2b/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotificationProvider.swift#L87)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: it would be a bit easier to follow as a switch over `(previousDeviceState, deviceState)`
</blockquote></details>

Nope,I don't want to use default case for handling the left states.
___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift` line 91 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NUzkBQEDm7Dm8kpbIvS:-NUzuOh_9oiC4ICmihS3:b-4kd15e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f26f533dc81b8b080c6f17e4a693f94453fd0f2b/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotificationProvider.swift#L91)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Transition is only delayed when moving from `loggedOut -> loggedIn` state in the UI, so perhaps it would be better to delay it here and call `invalidate()` directly. 

When going `loggedIn -> (loggedOut || revoked)` you could call `invalidate()` immediately without delay since there is nothing to wait for.
</blockquote></details>

ok,I'll set the delay just for turning logged out into logged in
___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift` line 85 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NV3mHzN296meB18us95:-NV4ARCj57h6H6_ExR-U:bxy6b53) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5bea3123004d00a73ba16bcf652263e9cb884e2c/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotificationProvider.swift#L85)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Perhaps you should only do that when user taps the button? Then tell the delegate that that happened by calling `sendAction()`
</blockquote></details>

I need to prevent this flag after invalidate the notification.I am creating this flag for InAppNotificationDescriptor.there is one case that user once logged in immediately do logged out.so the banner is still available. moreover, when we are showing the banner I think the best best is this flag gets off 


<!-- Sent from Reviewable.io -->

2023-05-10 11:58 UTC, pronebird reviewed
> Dismissed @rablador from a discussion.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @buggmagnet, @mojganii, and @rablador)



<!-- Sent from Reviewable.io -->

2023-05-10 19:35 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: 5 of 19 files reviewed, 1 unresolved discussion (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift` line 85 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NV3mHzN296meB18us95:-NV69MbH9w97G1TbTUCE:b-896fja) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5bea3123004d00a73ba16bcf652263e9cb884e2c/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotificationProvider.swift#L85)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

But this case handles `.loggedOut -> .loggedIn` transition only. 

The condition that handles `.loggedIn` -> .`loggedOut || .revoked` is below. What you do here is you make it look like new device is no longer registered after 1s delay. 

Instead you should only forget that new device was created when:

1. User logs out, i.e `.loggedIn` -> `.loggedOut`
2. User taps the dismiss button in the notification banner.

_To make it clear, the new device is only created when user moves from loggedOut to loggedIn state. If user moves from loggedIn to loggedOut or revoked state it means that there is no longer need to tell user that a new device is created_
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2023-05-11 07:44 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 5 files at r5, 12 of 12 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-:-NV8lFZ67rWAi3ihy_rS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-11 07:48 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/NotificationProviderIdentifier.swift` line 1 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NV8lmE81GLsmbuTbF19:-NV8lmE81GLsmbuTbF1A:b-5hytrb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ab95e9043377bc6724639ae6030279df9fdb66a/ios/MullvadVPN/Notifications/Notification%20Providers/NotificationProviderIdentifier.swift#L1)):*
> ```Swift
> //
> ```

Maybe we should move it into `ios/MullvadVPN/Notifications` since this is where the `NotificationProviderProtocol` is defined and it depends on this type since this change.


<!-- Sent from Reviewable.io -->

2023-05-11 07:48 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/NotificationProviderIdentifier.swift` line 1 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NV8lmE81GLsmbuTbF19:-NV8m4HE66S-5UP0FV1X:b-wqkeu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ab95e9043377bc6724639ae6030279df9fdb66a/ios/MullvadVPN/Notifications/Notification%20Providers/NotificationProviderIdentifier.swift#L1)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe we should move it into `ios/MullvadVPN/Notifications` since this is where the `NotificationProviderProtocol` is defined and it depends on this type since this change.
</blockquote></details>

I mean move the file one level up, not the code itself.


<!-- Sent from Reviewable.io -->

2023-05-11 07:57 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: 17 of 19 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/NotificationProviderIdentifier.swift` line 1 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NV8lmE81GLsmbuTbF19:-NV8mxqgED6ObhtsYfkj:brpz7mj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9ab95e9043377bc6724639ae6030279df9fdb66a/ios/MullvadVPN/Notifications/Notification%20Providers/NotificationProviderIdentifier.swift#L1)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I mean move the file one level up, not the code itself.
</blockquote></details>

ok, it makes sense.


<!-- Sent from Reviewable.io -->

2023-05-11 08:21 UTC, rablador approved these changes
> Reviewed 2 of 5 files at r5, 10 of 12 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-05-11 08:21 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-05-11 09:27 UTC, buggmagnet requested changes
> Reviewed 1 of 4 files at r2, 1 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 713 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NV8tWsk0J3rV6C6x69c:-NV8tWsk0J3rV6C6x69d:b-h1ck84) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4efbb7020a36a611bc6d8711980bd81e4188f954/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L713)):*
> ```Swift
>             let shouldHideDeviceInfo = previousDeviceState == .loggedOut
>             updateOutOfTimeTimer(accountData: accountData)
>             updateView(deviceState: deviceState, showDeviceInfo: !shouldHideDeviceInfo)
> ```

This is more complex than it needs to be.
We're introducing a boolean value, that we then reverse and don't reuse. 

Let's change this instead to 
`updateView(deviceState: deviceState, showDeviceInfo: previousDeviceState != .loggedOut)`


<!-- Sent from Reviewable.io -->

2023-05-11 12:35 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 713 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NV8tWsk0J3rV6C6x69c:-NV9mpFpEhGPys62qTNC:b2u0xvf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4efbb7020a36a611bc6d8711980bd81e4188f954/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L713)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This is more complex than it needs to be.
We're introducing a boolean value, that we then reverse and don't reuse. 

Let's change this instead to 
`updateView(deviceState: deviceState, showDeviceInfo: previousDeviceState != .loggedOut)`

</blockquote></details>

I don't agree to bring this condition into function parameters.it makes the code more complex to understand but with a meaningful variable it gets a better vision. 


<!-- Sent from Reviewable.io -->

2023-05-11 14:34 UTC, buggmagnet approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 713 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666#-NV8tWsk0J3rV6C6x69c:-NVADnwG3NHTqBjADM_6:bst2wzw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4efbb7020a36a611bc6d8711980bd81e4188f954/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L713)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I don't agree to bring this condition into function parameters.it makes the code more complex to understand but with a meaningful variable it gets a better vision. 
</blockquote></details>

We discussed this offline. 
The conclusion was to keep the `shouldHideDeviceInfo` but have it done this way instead to avoid the double boolean check
```
            let shouldHideDeviceInfo = previousDeviceState != .loggedOut
            updateOutOfTimeTimer(accountData: accountData)
            updateView(deviceState: deviceState, showDeviceInfo: shouldHideDeviceInfo)
```


<!-- Sent from Reviewable.io -->

2023-05-11 15:44 UTC, merged