Hide brand name when header bar when buttons overlap it
mullvad/mullvadvpn-app pull request #4697
Opened 2023-05-16 13:58 UTC by pronebird

2023-05-23 12:08 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4697)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/MullvadVPN/Containers/Root/HeaderBarView.swift` line 135 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4697#-NW7TNgC5_supdS3IYwq:-NW7TNgC5_supdS3IYwr:blyhh3c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7bfeb90fa5346304cf33e1a975c936e3d7c606f6/ios/MullvadVPN/Containers/Root/HeaderBarView.swift#L135)):*
> ```Swift
>                 multiplier: 1
>             )
>             brandNameImageView.topAnchor.constraint(
> ```

why didn't you set the `brandNameImageView` centerY of `logoImageView`?


<!-- Sent from Reviewable.io -->

2023-05-23 13:24 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4697)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Containers/Root/HeaderBarView.swift` line 135 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4697#-NW7TNgC5_supdS3IYwq:-NW7jUz23Ww_A7VRloj4:bo71zbk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7bfeb90fa5346304cf33e1a975c936e3d7c606f6/ios/MullvadVPN/Containers/Root/HeaderBarView.swift#L135)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

why didn't you set the `brandNameImageView` centerY of `logoImageView`?
</blockquote></details>

We have the inverse constraint already set:

```swift
logoImageView.centerYAnchor.constraint(equalTo: brandNameImageView.centerYAnchor)
```


<!-- Sent from Reviewable.io -->

2023-05-23 15:26 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4697#-:-NW8D-ocDWAunWpMc221:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-24 07:22 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4697)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-24 08:36 UTC, merged