Run new CLI before stopping old daemon on macOS
mullvad/mullvadvpn-app pull request #4699
Opened 2023-05-16 15:00 UTC by dlon

This PR updates the macOS installer scripts to run the new CLI before blocking the internet during upgrades. We hope that it may force macOS to check the validity of the certificate.

Fixes DES-210.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699)

2023-05-17 07:45 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`dist-assets/pkg-scripts/postinstall` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699#-NVceC9u5y9pzXXnDtMI:-NVceC9u5y9pzXXnDtMJ:byzpzvv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b2eab275fa444741a3d076a20fe694c0985ff4/dist-assets/pkg-scripts/postinstall#L15)):*
> ```
> 
> # Run CLI to force macOS to check the certificate
> # Then shut down the already running daemon, if one exists
> ```

Please add to this comment that this is a temporary workaround that we think is needed only when upgrading from an app signed with the `Amagicom AB` certificates. And that it can probably be removed when we stop supporting app version `2023.3`.
___
*[`dist-assets/pkg-scripts/postinstall` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699#-NVcei0x1pfUTh7W0NOV:-NVcei0x1pfUTh7W0NOW:b1s0z6m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b2eab275fa444741a3d076a20fe694c0985ff4/dist-assets/pkg-scripts/postinstall#L18)):*
> ```
> "$INSTALL_DIR/Mullvad VPN.app/Contents/Resources/mullvad" || true
> "$TMPDIR/mullvad-setup" prepare-restart || \
>     echo "Failed to send 'prepare-restart' command to old mullvad-daemon"
> ```

Can we really run this with the *new* version of `mullvad-setup`. Then we must always make sure that `mullvad-setup` of version `x` supports talking to daemons of version `y` where `y <= x` for all `x` and `y`. That does not sound ideal. It was done in `preinstall` for a reason I guess.


<!-- Sent from Reviewable.io -->

2023-05-17 08:14 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`dist-assets/pkg-scripts/postinstall` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699#-NVceC9u5y9pzXXnDtMI:-NVclTVo2lU1pQXfvruz:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b2eab275fa444741a3d076a20fe694c0985ff4/dist-assets/pkg-scripts/postinstall#L15)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Please add to this comment that this is a temporary workaround that we think is needed only when upgrading from an app signed with the `Amagicom AB` certificates. And that it can probably be removed when we stop supporting app version `2023.3`.
</blockquote></details>

Done.
___
*[`dist-assets/pkg-scripts/postinstall` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699#-NVcei0x1pfUTh7W0NOV:-NVcjuNYDNMODpKdf7hz:bgf06gi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b2eab275fa444741a3d076a20fe694c0985ff4/dist-assets/pkg-scripts/postinstall#L18)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we really run this with the *new* version of `mullvad-setup`. Then we must always make sure that `mullvad-setup` of version `x` supports talking to daemons of version `y` where `y <= x` for all `x` and `y`. That does not sound ideal. It was done in `preinstall` for a reason I guess.
</blockquote></details>

This is using the old `mullvad-setup`. I don't think you can find it anywhere in `preinstall`, so it is copied to `$TMPDIR` in `preinstall` and then run in `postinstall` :see_no_evil:.


<!-- Sent from Reviewable.io -->

2023-05-17 08:16 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`dist-assets/pkg-scripts/postinstall` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699#-NVcei0x1pfUTh7W0NOV:-NVclk5T-3LWQv8puvb-:brp6nav) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b2eab275fa444741a3d076a20fe694c0985ff4/dist-assets/pkg-scripts/postinstall#L18)):*
> I don't think you can find it anywhere in `preinstall`, so it is copied

The new CLI cannot be found in `preinstall`, so the existing `mullvad-setup` is copied to a temp dir in `preinstall` and run in `postinstall`.


<!-- Sent from Reviewable.io -->

2023-05-22 08:59 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`dist-assets/pkg-scripts/postinstall` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699#-NVceC9u5y9pzXXnDtMI:-NW1fPBS1PzM39_xruqh:b-4usczu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b2eab275fa444741a3d076a20fe694c0985ff4/dist-assets/pkg-scripts/postinstall#L15)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nit. It's `Mullvad VPN AB`, not `Mullvad AB`.
___
*[`dist-assets/pkg-scripts/postinstall` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699#-NVcei0x1pfUTh7W0NOV:-NW1fT-09eSaVSMsj7YR:bwiq64a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b2eab275fa444741a3d076a20fe694c0985ff4/dist-assets/pkg-scripts/postinstall#L18)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

> I don't think you can find it anywhere in `preinstall`, so it is copied

The new CLI cannot be found in `preinstall`, so the existing `mullvad-setup` is copied to a temp dir in `preinstall` and run in `postinstall`.
</blockquote></details>

Oh dear... Well, I don't have a better solution either. But please remove `$TMPDIR/mullvad-setup`. We should not leave that binary around when the upgrade/install has finished.


<!-- Sent from Reviewable.io -->

2023-05-22 15:33 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[`dist-assets/pkg-scripts/postinstall` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699#-NVceC9u5y9pzXXnDtMI:-NW34ia87k6JwaY7ntlQ:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b2eab275fa444741a3d076a20fe694c0985ff4/dist-assets/pkg-scripts/postinstall#L15)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nit. It's `Mullvad VPN AB`, not `Mullvad AB`.
</blockquote></details>

Fixed.
___
*[`dist-assets/pkg-scripts/postinstall` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699#-NVcei0x1pfUTh7W0NOV:-NW34k8P-gL696ovNukg:b2d5tdy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b2eab275fa444741a3d076a20fe694c0985ff4/dist-assets/pkg-scripts/postinstall#L18)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Oh dear... Well, I don't have a better solution either. But please remove `$TMPDIR/mullvad-setup`. We should not leave that binary around when the upgrade/install has finished.
</blockquote></details>

`$TMPDIR` is already removed by the installer itself.
___
*[`dist-assets/pkg-scripts/preinstall` line 14 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699#-NW1fBFb8FhM9eILUX6X:-NW34rynAbMrE53oSzPo:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4c923633c88d212e50cc1539801947616d2e2782/dist-assets/pkg-scripts/preinstall#L14)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can you please add a comment about why this is needed. Since it's a requirement for *another* script to run it becomes very hard to understand this script in isolation without knowing a lot about the general install process.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-23 07:56 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699#-:-NW6b0ok6FE4kVVI0Y7j:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2023-05-23 08:01 UTC, merged