Add alert if user disconnects when there's no connectivity
mullvad/mullvadvpn-app pull request #4709
Opened 2023-05-19 09:06 UTC by rablador

If the app has no network access and the user disconnects the tunnel, the "Secure my connection" and "Switch location" buttons will be disabled until network access is restored. This puts the user in a vulnerable state and leaking traffic. To make sure the user understands this and does not accidentally disconnect, a new alert will be shown before disconnecting the tunnel.

2023-05-19 11:54 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709#-:-NVnr6twCWuHhrWMpYjb:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-22 10:24 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709)* status: 0 of 2 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709#-NW1xGF84u_-TwXO6MDc:-NW1xGF84u_-TwXO6MDd:bh62do3) (no related file):*
FYI

1. If user re-enters the app from push notification, we may attempt to present account view above alert which probably wouldn't work. Ideally we should somehow make router aware of alerts when they are presented and perhaps make them exclusive. This would certainly spill into some architectural changes.
2. It would be better to handle navigation within coordinator instead of presenting alert view controller from within view controller itself. While some part of the code still does things the old fashion way, it's certainly something I thought we should move away from and in favor of using coordinators.

___


<!-- Sent from Reviewable.io -->

2023-05-22 12:01 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709)* status: 0 of 2 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709#-NW1xGF84u_-TwXO6MDc:-NW2Iavb5OxIw8GD2uU2:bqzovcl) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI

1. If user re-enters the app from push notification, we may attempt to present account view above alert which probably wouldn't work. Ideally we should somehow make router aware of alerts when they are presented and perhaps make them exclusive. This would certainly spill into some architectural changes.
2. It would be better to handle navigation within coordinator instead of presenting alert view controller from within view controller itself. While some part of the code still does things the old fashion way, it's certainly something I thought we should move away from and in favor of using coordinators.
</blockquote></details>

1. Should we perhaps defer this to another issue?
2. Alright, so delegate alert presentation to the coordinator and present on `rootViewController`?

___


<!-- Sent from Reviewable.io -->

2023-05-23 11:21 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709)* status: 0 of 3 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709#-NW1xGF84u_-TwXO6MDc:-NW7Km7u3C_LfrG4nbND:b-nktoji) (no related file):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

1. Should we perhaps defer this to another issue?
2. Alright, so delegate alert presentation to the coordinator and present on `rootViewController`?
</blockquote></details>

1. Perhaps but we definitely should add a task to handle alerts in some way.
2. Yes.

___


<!-- Sent from Reviewable.io -->

2023-05-23 11:24 UTC, pronebird requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-05-24 08:49 UTC, mojganii reviewed
when the app runs and there is no connectivity we saw in app banner that tells to user doesn't has access to the network and the relevant buttons are disabled that looks great but when I connect the network the app still stays on disabled mode and it doesn't update UI and dismiss the banner.I think you should fix this part.
Moreover, maybe it's not the scope of this task but something like this goes for tunnel as well.I connect via tunnel and I disconnect the internet and the app shows me I have a secure connection while there is no connectivity.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709#-:-NWBs6VMBszSt1jvYIST:bvb7bu4)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-05-24 09:01 UTC, mojganii requested changes
Please, have a look at my comment above.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709#-:-NWBzHGy3aynJCqNrlEC:blb81ae)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-05-24 11:49 UTC, rablador reviewed
First issue: I haven't been able to reproduce this myself. Are you testing on simulator or device?
Second issue: This is by design. If you connect to the tunnel first, then lose connection, you'll still be protected (secure "connection") unless you disconnect (which is the reason for this new popup).

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709#-:-NWC_GFn2ASzMiSYKVPF:b-byrvie)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709#-NW1xGF84u_-TwXO6MDc:-NWCZTcsC5gir182aZHr:b-896fix) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

1. Perhaps but we definitely should add a task to handle alerts in some way.
2. Yes.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-05-25 07:42 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709#-:-NWGqnty9cPKs26CfiDS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-05-25 08:25 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-25 08:25 UTC, pronebird approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-25 14:05 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-25 14:06 UTC, merged