Pass the API endpoint to Shadowsocks instead of hardcoding it
mullvad/mullvadvpn-app pull request #4722
Opened 2023-05-22 13:24 UTC by buggmagnet

This PR removes hardcoding the API address in the Shadowsocks proxy crate, and instead gets it at runtime from the `AddressCache` in the Swift part, and forwards it to the Rust part

2023-05-22 15:35 UTC, pinkisemils requested changes
> Reviewed 1 of 11 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadREST/shadowsocks-proxy/src/ffi.rs` line 57 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722#-NW34aPP8uX8ziRrZoSJ:-NW34aPP8uX8ziRrZoSK:b-j13uwx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/364a7164010e64169f404fbf5764dba3462d028b/ios/MullvadREST/shadowsocks-proxy/src/ffi.rs#L57)):*
> ```XML
>     };
> 
>     let bridge_socket = SocketAddr::new(bridge_ip, port);
> ```

This is most definitely not a socket - it's just a bridge socket address (IP address and port in a single structure). The same goes for the `forward_socket` a few lines up,
___
*[`ios/MullvadREST/shadowsocks-proxy/src/lib.rs` line 20 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722#-NW34pOG6JfuyDiBXau3:-NW34pOG6JfuyDiBXau4:blfp3mc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/364a7164010e64169f404fbf5764dba3462d028b/ios/MullvadREST/shadowsocks-proxy/src/lib.rs#L20)):*
> ```XML
> pub fn run_forwarding_proxy(
>     forward_socket: SocketAddr,
>     bridge_socket: SocketAddr,
> ```

These should be called `forward_address` and `bridge_address`, or maybe even as verbose as `forward_socket_addr` and `bridge_socket_addr`. 


<!-- Sent from Reviewable.io -->

2023-05-23 06:16 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`ios/MullvadREST/shadowsocks-proxy/src/ffi.rs` line 57 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722#-NW34aPP8uX8ziRrZoSJ:-NW6EuLj7V2dojNA6YJZ:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/364a7164010e64169f404fbf5764dba3462d028b/ios/MullvadREST/shadowsocks-proxy/src/ffi.rs#L57)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This is most definitely not a socket - it's just a bridge socket address (IP address and port in a single structure). The same goes for the `forward_socket` a few lines up,
</blockquote></details>

Done
___
*[`ios/MullvadREST/shadowsocks-proxy/src/lib.rs` line 20 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722#-NW34pOG6JfuyDiBXau3:-NW6Ei7Q7C-gbPS05xgu:b6ciq56) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/364a7164010e64169f404fbf5764dba3462d028b/ios/MullvadREST/shadowsocks-proxy/src/lib.rs#L20)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

These should be called `forward_address` and `bridge_address`, or maybe even as verbose as `forward_socket_addr` and `bridge_socket_addr`. 
</blockquote></details>

Indeed, thanks for catching that. I've changed the name in `lib.rs` and `ffi.rs` it will be more consistent now.


<!-- Sent from Reviewable.io -->

2023-05-23 08:12 UTC, rablador reviewed
> Reviewed 7 of 11 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2023-05-23 09:08 UTC, rablador reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2023-05-23 09:11 UTC, pronebird reviewed
> Reviewed 7 of 11 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`ios/MullvadREST/URLSessionTransport.swift` line 40 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722#-NW6r4xU0-obOLtWx6rF:-NW6r4xU0-obOLtWx6rG:b-acavyi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b10d0f8fa4cf9ef20de7c6126c72f0b4d970cbf2/ios/MullvadREST/URLSessionTransport.swift#L40)):*
> ```Swift
>         private let shadowSocksProxy: ShadowSocksProxy
>         /// The IPv4 representation of the loopback address used by `shadowSocksProxy`
>         private let localhost = "127.0.0.1"
> ```

FYI "\(IPv4Address.loopback)" should be equivalent.


<!-- Sent from Reviewable.io -->

2023-05-23 10:20 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

___
*[`ios/MullvadREST/ShadowSocksProxy.swift` line 65 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722#-NW756Zl1dXZ64CEBXz-:-NW756Zm-24d4wY2tFh8:bhbrkhi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b10d0f8fa4cf9ef20de7c6126c72f0b4d970cbf2/ios/MullvadREST/ShadowSocksProxy.swift#L65)):*
> ```Swift
>         _ = withUnsafeMutablePointer(to: &proxyConfig) { config in
>             start_shadowsocks_proxy(
>                 (forwardAddress.rawValue as NSData).bytes,
> ```

This is a very clever toll bridging technique that enables us to access the underlying bytes buffer. 

However I am concerned about lifetime of the pointer returned by `NSData` object and maybe my concerns are baseless, I thought to share that perhaps copying those bytes into Swift array would make things simpler and more explicit and also avoid going via Objective-C class:

```
var forwardAddressBytes = forwardAddress.rawValue.map { $0 }
var bridgeAddressBytes = bridgeAddress.rawValue.map { $0 }

// Get the raw bytes access to `proxyConfig`
_ = withUnsafeMutablePointer(to: &proxyConfig) { config in
    start_shadowsocks_proxy(
        &forwardAddressBytes,
        UInt(forwardAddressBytes.count),
        forwardPort,
        &bridgeAddressBytes,
        UInt(bridgeAddressBytes.count),
        bridgePort,
        password,
        UInt(password.count),
        cipher,
        UInt(cipher.count),
        config
    )
}
```


<!-- Sent from Reviewable.io -->

2023-05-23 10:59 UTC, mojganii approved these changes
> Reviewed 7 of 11 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @pinkisemils)



<!-- Sent from Reviewable.io -->

2023-05-24 07:47 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722)* status: 9 of 12 files reviewed, 3 unresolved discussions (waiting on @mojganii, @pinkisemils, @pronebird, and @rablador)

___
*[`ios/MullvadREST/ShadowSocksProxy.swift` line 65 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722#-NW756Zl1dXZ64CEBXz-:-NWBcc4CD7O5gzjgySty:b-vt9d0g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b10d0f8fa4cf9ef20de7c6126c72f0b4d970cbf2/ios/MullvadREST/ShadowSocksProxy.swift#L65)):*
Both approaches should be valid as far as I'm aware. 
I went for that approach to avoid thinking about the lifetime of objects, since we know that the `bytes` held by `forwardAddress` will be valid for the lifetime of the `ShadowsocksProxy` instance.

But the documentation also specifies that 
> When you call a function that is declared as taking an UnsafePointer<Type> argument, you can pass any of the following:
> ...
> A [Type] value, which is passed as a pointer to the start of the array.

That being said, your suggestion doesn't rely on ObjC bridging which is a more future proof solution, so I will go with that (although no need to create the temp variables IMHO)

Thanks for the suggestion !
___
*[`ios/MullvadREST/URLSessionTransport.swift` line 40 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722#-NW6r4xU0-obOLtWx6rF:-NWBeSkh8wzV4UBzQS0_:b-idvfe2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b10d0f8fa4cf9ef20de7c6126c72f0b4d970cbf2/ios/MullvadREST/URLSessionTransport.swift#L40)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI "\(IPv4Address.loopback)" should be equivalent.
</blockquote></details>

TIL !
However this is relying on the fact that `IPv4Address` implements `CustomDebugStringConvertible` and if the implementation ever changes, this will suddenly break. 
I don't think we should be relying on this in production.


<!-- Sent from Reviewable.io -->

2023-05-24 08:18 UTC, pinkisemils reviewed
You do have to run a `cargo fmt` to get this past the CI.

> Reviewed 6 of 11 files at r1, 2 of 2 files at r3, 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722#-:-NWBp5L0BXI9RDqyndk0:b5twqif)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @mojganii, @pronebird, and @rablador)



<!-- Sent from Reviewable.io -->

2023-05-24 09:17 UTC, buggmagnet reviewed
Ah thanks I was wondering what was wrong with the code

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722#-:-NWC29YI-ziX_ytAKLPv:b-y7vn2e)* status: 7 of 12 files reviewed, 1 unresolved discussion (waiting on @mojganii, @pinkisemils, @pronebird, and @rablador)



<!-- Sent from Reviewable.io -->

2023-05-24 10:40 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722)* status: 7 of 12 files reviewed, all discussions resolved (waiting on @mojganii, @pinkisemils, and @rablador)

___
*[`ios/MullvadREST/URLSessionTransport.swift` line 40 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722#-NW6r4xU0-obOLtWx6rF:-NWCImh1ElpD5JueqRQn:b-gi80ik) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b10d0f8fa4cf9ef20de7c6126c72f0b4d970cbf2/ios/MullvadREST/URLSessionTransport.swift#L40)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

TIL !
However this is relying on the fact that `IPv4Address` implements `CustomDebugStringConvertible` and if the implementation ever changes, this will suddenly break. 
I don't think we should be relying on this in production.
</blockquote></details>

God I hope it does not change. It's been this way since forever and there is quite a bit of code that relies on that.


<!-- Sent from Reviewable.io -->

2023-05-24 11:54 UTC, rablador approved these changes
> Reviewed 3 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-25 13:07 UTC, pronebird requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadREST/ShadowSocksProxy.swift` line 14 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722#-NWI08CJ3Ugpiyrs-0qP:-NWI08CJ3Ugpiyrs-0qQ:bvahr2u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e88bebd28511fef0e0c1f13bafc6dc2642540a1/ios/MullvadREST/ShadowSocksProxy.swift#L14)):*
> ```Swift
> 
> /// A Swift wrapper around a Rust implementation of Shadowsocks proxy instance
> public class ShadowsocksProxy {
> ```

Could you please align the file name with class name please?


<!-- Sent from Reviewable.io -->

2023-05-25 14:37 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/MullvadREST/ShadowSocksProxy.swift` line 14 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722#-NWI08CJ3Ugpiyrs-0qP:-NWIKyzo26kbIATLvJ8g:b-elpgso) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e88bebd28511fef0e0c1f13bafc6dc2642540a1/ios/MullvadREST/ShadowSocksProxy.swift#L14)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Could you please align the file name with class name please?
</blockquote></details>

We decided to address this in another PR


<!-- Sent from Reviewable.io -->

2023-05-25 16:14 UTC, pinkisemils approved these changes
> Reviewed 2 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-05-25 16:44 UTC, merged