Add tunnel interface to output of `mullvad status -v`
mullvad/mullvadvpn-app pull request #4726
Opened 2023-05-23 12:16 UTC by MarkusPettersson98

With this change, `mullvad status -v` will print the name of the tunnel interface when the app is in a connected state. This PR aims to implement the feature requested in #4676.

2023-05-23 13:06 UTC, dlon requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`talpid-types/src/net/mod.rs` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726#-NW7dUYi6H05qRfIyaqr:-NW7dUYi6H05qRfIyaqs:bgnvc20) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2bd5111d1937a9995ebdcd09fbd6fc737b695581/talpid-types/src/net/mod.rs#L37)):*
> ```XML
>                 obfuscation: None,
>                 entry_endpoint: None,
>                 tunnel_interface: String::new(),
> ```

I'm not a fan of this being set to an empty string. It makes it easy to forget about.

The `tunnel_interface` field should probably be optional to make it clearer that it may not be present.

Maybe the `TunnelEndpoint` should also be constructed from a `TunnelParameters`, and an optional `TunnelMetadata` or interface name?

```
impl TunnelEndpoint {

   fn new(parameters: TunnelParameters, metadata: TunnelMetadata) {
        // ...
    }

}
```


<!-- Sent from Reviewable.io -->

2023-05-23 13:20 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-cli/src/format.rs` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726#-NW7ki986crjB_uN0NkD:-NW7ki986crjB_uN0NkE:bt4ws10) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2bd5111d1937a9995ebdcd09fbd6fc737b695581/mullvad-cli/src/format.rs#L19)):*
> ```XML
>             if verbose {
>                 println!("Tunnel interface: {}", endpoint.tunnel_interface)
>             };
> ```

Nit: This semicolon can be removed.


<!-- Sent from Reviewable.io -->

2023-05-23 13:45 UTC, dlon requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`talpid-types/src/net/mod.rs` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726#-NW7dUYi6H05qRfIyaqr:-NW7l9q176L9BHUQ7kDP:b4r6auv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2bd5111d1937a9995ebdcd09fbd6fc737b695581/talpid-types/src/net/mod.rs#L37)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Initializing `tunnel_interface` as an empty `String` is bad, I agree. However, I would like to keep the `tunnel_interface` as `String` rather than `Option<String>`, since the tunnel name will exist when the `TunnelEndpoint` is created (as `tunnel_interface` is grabbed directly from `TunnelMetadata`, which defines its `interface` field as `String`).

The constructor for `TunnelEndpoint` you suggested would solve this issue, I will look into that :rocket: 
</blockquote></details>

`tunnel_interface` will never initialized in the connecting state (early on). It will effectively always be optional if we're to share this struct between the two tunnel states, so it makes sense to make that clear, IMO.


<!-- Sent from Reviewable.io -->

2023-05-23 14:01 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`talpid-types/src/net/mod.rs` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726#-NW7dUYi6H05qRfIyaqr:-NW7uSc6D7E2H7R1fy0I:bw63w08) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2bd5111d1937a9995ebdcd09fbd6fc737b695581/talpid-types/src/net/mod.rs#L37)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`tunnel_interface` will never initialized in the connecting state (early on). It will effectively always be optional if we're to share this struct between the two tunnel states, so it makes sense to make that clear, IMO.
</blockquote></details>

Fair point!


<!-- Sent from Reviewable.io -->

2023-05-23 15:35 UTC, dlon requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726)* status: all files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`talpid-types/src/net/mod.rs` line 212 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726#-NW89pZo0GsNJ2sWLkDZ:-NW89pZo0GsNJ2sWLkD_:b-yst6kw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7cf5993662b2c77bdaaa5d42fe8a6cbfe3d90f62/talpid-types/src/net/mod.rs#L212)):*
> ```XML
> 
> #[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
> #[serde(rename = "tunnel_metadata")]
> ```

Why the renaming? I'm not sure we ever serialize or deserialize this struct to begin with, so we might even be able to remove `Serialize` and `Deserialize` from this and also from `TunnelEndpoint`. I could be wrong, though. But the rename could probably be removed, at least.
___
*[`talpid-types/src/net/mod.rs` line 214 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726#-NW89eN2Duf1RIpo-gwR:-NW89eN2Duf1RIpo-gwS:bul2r1w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7cf5993662b2c77bdaaa5d42fe8a6cbfe3d90f62/talpid-types/src/net/mod.rs#L214)):*
> ```XML
> #[serde(rename = "tunnel_metadata")]
> #[cfg_attr(target_os = "android", derive(IntoJava))]
> #[cfg_attr(target_os = "android", jnix(package = "net.mullvad.talpid.net"))]
> ```

These two attributes aren't useful here, I think:

```rust
#[cfg_attr(target_os = "android", derive(IntoJava))]
#[cfg_attr(target_os = "android", jnix(package = "net.mullvad.talpid.net"))]
```

For one, we're skipping this for Android anyway. Also, this generates code for converting the type from Rust to a Java analogue, but there is no such type.
___
*[`talpid-types/src/net/mod.rs` line 215 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726#-NW8AkVxCD3G0JN1HYcw:-NW8AkVxCD3G0JN1HYcx:b2gt2xk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7cf5993662b2c77bdaaa5d42fe8a6cbfe3d90f62/talpid-types/src/net/mod.rs#L215)):*
> ```XML
> #[cfg_attr(target_os = "android", derive(IntoJava))]
> #[cfg_attr(target_os = "android", jnix(package = "net.mullvad.talpid.net"))]
> pub struct TunnelMetadata {
> ```

Isn't it a bit confusing to have this plus another `TunnelMetadata` in  `talpid-tunnel`? They're not supposed to be distinct types, right?

What do you think of storing `Option<String>` in `TunnelEndpoint` on the Rust side for now and just constructing a `proto::TunnelMetadata` from that (`tunnel_interface.map(|iface| proto::TunnelMeta { interface })`) in `mullvad-management-interface`?


<!-- Sent from Reviewable.io -->

2023-05-24 07:04 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`talpid-types/src/net/mod.rs` line 212 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726#-NW89pZo0GsNJ2sWLkDZ:-NWBZRa25dl13nXwC6sC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7cf5993662b2c77bdaaa5d42fe8a6cbfe3d90f62/talpid-types/src/net/mod.rs#L212)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Why the renaming? I'm not sure we ever serialize or deserialize this struct to begin with, so we might even be able to remove `Serialize` and `Deserialize` from this and also from `TunnelEndpoint`. I could be wrong, though. But the rename could probably be removed, at least.
</blockquote></details>

Done.
___
*[`talpid-types/src/net/mod.rs` line 214 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726#-NW89eN2Duf1RIpo-gwR:-NWBZSHjAbxMwMAKakJv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7cf5993662b2c77bdaaa5d42fe8a6cbfe3d90f62/talpid-types/src/net/mod.rs#L214)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

These two attributes aren't useful here, I think:

```rust
#[cfg_attr(target_os = "android", derive(IntoJava))]
#[cfg_attr(target_os = "android", jnix(package = "net.mullvad.talpid.net"))]
```

For one, we're skipping this for Android anyway. Also, this generates code for converting the type from Rust to a Java analogue, but there is no such type.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-24 07:15 UTC, dlon approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-24 08:27 UTC, merged

2023-10-11 09:43 UTC, seguri commented
Released with 2023.5