Create custom alert dialogs
mullvad/mullvadvpn-app pull request #4731
Opened 2023-05-24 14:55 UTC by rablador

To help users further to understand the device concept, an info button next to the device name in the account view is added. It opens an info dialog that explains the device concept.

2023-05-25 09:16 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 0 of 17 files reviewed, 1 unresolved discussion

___
*[`ios/MullvadVPN/View controllers/Account/AccountContentView.swift` line 159 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWHB-iu4yagpT2ukgJX:-NWHB-iv-t4lQwcpTDNj:buhgkxp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dbee1261d8d8e387cca7dd5349a238f360ac4a02/ios/MullvadVPN/View%20controllers/Account/AccountContentView.swift#L159)):*
> ```Swift
>         addConstrainedSubviews([contentContainerView, infoButton]) {
>             contentContainerView.pinEdgesToSuperview()
>             infoButton.leadingAnchor.constraint(equalToSystemSpacingAfter: deviceLabel.trailingAnchor, multiplier: 1)
> ```

We could have a nicer solution here with two stackviews, one with the device label + button and one with that stackview and the title label. However, it seems to restrict the use of increased tap areas, so I moved the button outside instead.


<!-- Sent from Reviewable.io -->

2023-05-25 13:23 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Account/AccountViewController.swift` line 93 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWHCeeE1ltF3wrpa9sW:-NWI2HMFAXewlxJ4mG4R:b-spn5ym) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d52a409cce0aaf9a9d09bdbd17eab10524907f/ios/MullvadVPN/View%20controllers/Account/AccountViewController.swift#L93)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Not sold on the idea of creating direct dependencies like this, but it's frequently used elsewhere in this class. On the plus side, it removes a somewhat long and awkward callback chain.
</blockquote></details>

I'd add `var infoButtonAction: (() -> Void)?` on `AccountDeviceRow`. Every other subview in `AccountDeviceRow` is private and we could keep it that way to isolate outsiders from knowing too much about implementation details of that particular view. What was done before was not refined properly to provide the appropriate level of isolation for historical reasons.


<!-- Sent from Reviewable.io -->

2023-05-25 13:40 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 0 of 17 files reviewed, 6 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Account/AccountContentView.swift` line 121 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWI4DDo72FEnhGbOLm_:-NWI4DDo72FEnhGbOLma:b-5jc0t6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d52a409cce0aaf9a9d09bdbd17eab10524907f/ios/MullvadVPN/View%20controllers/Account/AccountContentView.swift#L121)):*
> ```Swift
>     }
> 
>     let infoButton: UIButton = {
> ```

All other subviews are private here. Let's keep it this way shall we?
___
*[`ios/MullvadVPN/View controllers/Account/AccountContentView.swift` line 122 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWI4LSb2s01_kVMqxEO:-NWI4LSb2s01_kVMqxEP:b-3b10qg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d52a409cce0aaf9a9d09bdbd17eab10524907f/ios/MullvadVPN/View%20controllers/Account/AccountContentView.swift#L122)):*
> ```Swift
> 
>     let infoButton: UIButton = {
>         let button = IncreasedHitButton(type: .custom)
> ```

`.system` buttons implement a nice fade effect. Unless there is a certain reason to use `.custom`, then I would suggest to stick with `.system`.
___
*[`ios/MullvadVPN/View controllers/Account/AccountViewController.swift` line 285 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWI6VUs3vM1Ld_2XeZQ:-NWI6VUt25FSbhSU5xTX:b-g1v6uk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d52a409cce0aaf9a9d09bdbd17eab10524907f/ios/MullvadVPN/View%20controllers/Account/AccountViewController.swift#L285)):*
> ```Swift
>     }
> 
>     @objc private func showAccountDeviceInfo() {
> ```

I think we should start moving all view controller presentations into coordinators as opposed to driving the flow from view controllers themselves.
___
*[`ios/MullvadVPN/View controllers/Account/AccountViewController.swift` line 287 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWI6zJ90cnS_WFo1RH0:-NWI6zJ90cnS_WFo1RH1:b-uu6r5e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d52a409cce0aaf9a9d09bdbd17eab10524907f/ios/MullvadVPN/View%20controllers/Account/AccountViewController.swift#L287)):*
> ```Swift
>     @objc private func showAccountDeviceInfo() {
>         let messages = [
>             NSLocalizedString(
> ```

A bit unusual to see array of strings being passed int custom alert. Maybe we could squash them into one multiline string?

```swift
NSLocalizedString(... , value: """
Paragraph A

Paragraph B

Paragraph C
""")
````


<!-- Sent from Reviewable.io -->

2023-05-25 13:42 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 0 of 17 files reviewed, 6 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/View controllers/Account/AccountViewController.swift` line 93 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWHCeeE1ltF3wrpa9sW:-NWI6xL6CCxs7TPnRr5j:b-hsitbe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d52a409cce0aaf9a9d09bdbd17eab10524907f/ios/MullvadVPN/View%20controllers/Account/AccountViewController.swift#L93)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I'd add `var infoButtonAction: (() -> Void)?` on `AccountDeviceRow`. Every other subview in `AccountDeviceRow` is private and we could keep it that way to isolate outsiders from knowing too much about implementation details of that particular view. What was done before was not refined properly to provide the appropriate level of isolation for historical reasons.
</blockquote></details>

That's what I started out with... 🫠
___
*[`ios/MullvadVPN/View controllers/Account/AccountViewController.swift` line 285 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWI6VUs3vM1Ld_2XeZQ:-NWI84Tu7BGTnPZUjaJD:b-y1dyd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d52a409cce0aaf9a9d09bdbd17eab10524907f/ios/MullvadVPN/View%20controllers/Account/AccountViewController.swift#L285)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think we should start moving all view controller presentations into coordinators as opposed to driving the flow from view controllers themselves.
</blockquote></details>

Yeah, that was discussed in a recent PR. Didn't want to move things around too much here, but I can do the refactor now that's been pointed out.
___
*[`ios/MullvadVPN/View controllers/Account/AccountViewController.swift` line 287 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWI6zJ90cnS_WFo1RH0:-NWI8HV368K2y7NwYQau:b-o7nm59) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d52a409cce0aaf9a9d09bdbd17eab10524907f/ios/MullvadVPN/View%20controllers/Account/AccountViewController.swift#L287)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

A bit unusual to see array of strings being passed int custom alert. Maybe we could squash them into one multiline string?

```swift
NSLocalizedString(... , value: """
Paragraph A

Paragraph B

Paragraph C
""")
````
</blockquote></details>

It's mostly for the sake of being able to specify the spacing between paragraphs.


<!-- Sent from Reviewable.io -->

2023-05-25 14:42 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 15 of 17 files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/View controllers/Account/AccountContentView.swift` line 121 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWI4DDo72FEnhGbOLm_:-NWIAXEPAys6yoc7LZeX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d52a409cce0aaf9a9d09bdbd17eab10524907f/ios/MullvadVPN/View%20controllers/Account/AccountContentView.swift#L121)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

All other subviews are private here. Let's keep it this way shall we?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Account/AccountContentView.swift` line 122 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWI4LSb2s01_kVMqxEO:-NWIAUhr10VGaNxmM1AC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d52a409cce0aaf9a9d09bdbd17eab10524907f/ios/MullvadVPN/View%20controllers/Account/AccountContentView.swift#L122)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`.system` buttons implement a nice fade effect. Unless there is a certain reason to use `.custom`, then I would suggest to stick with `.system`.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Account/AccountViewController.swift` line 93 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWHCeeE1ltF3wrpa9sW:-NWILGwO7hG_FoKy79xC:b-n838mw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d52a409cce0aaf9a9d09bdbd17eab10524907f/ios/MullvadVPN/View%20controllers/Account/AccountViewController.swift#L93)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

If you really want a decoupled solution, you can use the reponder chain like so

```
    @objc private func didTapInfoButton() {
        UIApplication.shared.sendAction(#selector(AccountViewController.showAccountDeviceInfo), to: nil, from: self, for: nil)
    }
```

with 
```
    @objc func showAccountDeviceInfo(_ sender: UIControl) { ... }
```
</blockquote></details>

@pronebird Wanted to keep the style is all. Reverting back to the original impl.
@buggmagnet That's some wild stuff 😯


<!-- Sent from Reviewable.io -->

2023-05-25 15:27 UTC, pronebird reviewed
> Reviewed 1 of 2 files at r5, 1 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 14 of 18 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 146 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWIVoWq4H5SA264HFKQ:-NWIVoWq4H5SA264HFKR:b-6s6gyn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d081f092634a272ae469ef10fce1051ce5774358/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L146)):*
> ```Swift
>                 "DEVICE_INFO_DIALOG_MESSAGE_PART_1",
>                 tableName: "Account",
>                 value: "This is the name assigned to the device. Each device logged in on a Mullvad account gets a unique name that helps you identify it when you manage your devices in the app or on the website.\n\nYou can have up to 5 devices logged in on one Mullvad account.\n\nIf you log out, the device and the device name is removed. When you log back in again, the device will get a new name.",
> ```

FYI I don't mind `\n\n` inside but it would be much simpler to read if it was formatted as a multiline literal:

```swift
NSLocalizedString(
    "DEVICE_INFO_DIALOG_MESSAGE",
    tableName: "Account",
    value: """
    This is the name assigned to the device. Each device logged in on a Mullvad account gets a unique name that helps you identify it when you manage your devices in the app or on the website.

    You can have up to 5 devices logged in on one Mullvad account.

    If you log out, the device and the device name is removed. When you log back in again, the device will get a new name.
    """,
    comment: ""
    )
]

```


<!-- Sent from Reviewable.io -->

2023-05-26 07:45 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 14 of 18 files reviewed, 5 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 77 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWM-WyV0MBVkA3mwnBM:-NWM-WyV0MBVkA3mwnBN:b-762qoq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d081f092634a272ae469ef10fce1051ce5774358/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L77)):*
> ```Swift
> 
>         containerView.arrangedSubviews.last.flatMap {
>             print(($0 as! UILabel).font.lineHeight)
> ```

Leftover of print() based debugging
___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 82 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWM-fDT6q1PBfLYysa1:-NWM-fDT6q1PBfLYysa2:b8tkoaz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d081f092634a272ae469ef10fce1051ce5774358/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L82)):*
> ```Swift
> 
>     /// Layout margins for container (main view) in `CustomAlertViewController`
>     static let customAlertContainerMargins = NSDirectionalEdgeInsets(
> ```

Me and @mojganii are onto something new, we group constants into sub-namespaces with enums in `UIMetrics`:

```swift
enum UIMetrics {
    enum Alerts {
        static let containerMargins = ...
        static let containerSpacing = ..
    }
}
```

So perhaps you could group all constants related to custom alerts under `enum` and don't worry, we'll refine the rest over time. This also aligns with how things are done in `UIColor+Palette`.


<!-- Sent from Reviewable.io -->

2023-05-26 08:20 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 14 of 18 files reviewed, 7 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 53 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWM7imA5hDJJeoV4hLX:-NWM7imA5hDJJeoV4hLY:b-rylte3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d081f092634a272ae469ef10fce1051ce5774358/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L53)):*
> ```Swift
>     // MARK: - Alerts
> 
>     func showLogoutAlert() {
> ```

nit: For the sake of terminology I would rename this `presentLogoutAlert`.

I think you used `show` because all the other methods are already called `show` so that's fine to leave as is too for consistency's sake.
___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 146 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWIVoWq4H5SA264HFKQ:-NWM5-x74YIw4BzUqRgx:bpwlxml) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d081f092634a272ae469ef10fce1051ce5774358/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L146)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI I don't mind `\n\n` inside but it would be much simpler to read if it was formatted as a multiline literal:

```swift
NSLocalizedString(
    "DEVICE_INFO_DIALOG_MESSAGE",
    tableName: "Account",
    value: """
    This is the name assigned to the device. Each device logged in on a Mullvad account gets a unique name that helps you identify it when you manage your devices in the app or on the website.

    You can have up to 5 devices logged in on one Mullvad account.

    If you log out, the device and the device name is removed. When you log back in again, the device will get a new name.
    """,
    comment: ""
    )
]

```
</blockquote></details>

+1 for multiline literals 
___
*[`ios/MullvadVPN/View controllers/Account/AccountViewController.swift` line 93 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWHCeeE1ltF3wrpa9sW:-NWM5HbN96MIQBgBGfWf:bezh9g1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d52a409cce0aaf9a9d09bdbd17eab10524907f/ios/MullvadVPN/View%20controllers/Account/AccountViewController.swift#L93)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

@pronebird Wanted to keep the style is all. Reverting back to the original impl.
@buggmagnet That's some wild stuff 😯
</blockquote></details>

@rablador That's the funky thing, it's not even wild, it's just the way the responder chain has been designed for.
It's really helpful in those cases where you have a cascade of sub menus where pressing the submost "OK" or "Cancel" button will cancel all the menus in cascade.

Instead of bubbling up events, or have a plethora of delegates or block based callbacks, you just let the responder chain find the correct target, and send an event to it directly. 

Also you get a really loose coupling of objects, which means code that is easy to delete / modify without consequences.
___
*[`ios/MullvadVPN/View controllers/Account/AccountViewController.swift` line 132 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWM6clw2TFJvf6zAZEf:-NWM6clw2TFJvf6zAZEg:b-kspqht) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d081f092634a272ae469ef10fce1051ce5774358/ios/MullvadVPN/View%20controllers/Account/AccountViewController.swift#L132)):*
> ```Swift
>     // MARK: - Private
> 
>     @objc private func doLogout() {
> ```

The word `do` [doesn't add saliency](https://www.swift.org/documentation/api-design-guidelines/#promote-clear-usage), we can rename this `logout` 


<!-- Sent from Reviewable.io -->

2023-05-26 10:19 UTC, pronebird reviewed
> Reviewed 4 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: all files reviewed, 4 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Account/AccountContentView.swift` line 159 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWHB-iu4yagpT2ukgJX:-NWM0OBX3GIUfwTm27QS:b-1ipdk2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dbee1261d8d8e387cca7dd5349a238f360ac4a02/ios/MullvadVPN/View%20controllers/Account/AccountContentView.swift#L159)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

We could have a nicer solution here with two stackviews, one with the device label + button and one with that stackview and the title label. However, it seems to restrict the use of increased tap areas, so I moved the button outside instead.
</blockquote></details>

It's fine


<!-- Sent from Reviewable.io -->

2023-05-26 10:26 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: all files reviewed, 4 unresolved discussions

___
*[`ios/MullvadVPN/View controllers/Account/AccountViewController.swift` line 287 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWI6zJ90cnS_WFo1RH0:-NWME47b2VzcXkdjvPPX:bh2a157) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d52a409cce0aaf9a9d09bdbd17eab10524907f/ios/MullvadVPN/View%20controllers/Account/AccountViewController.swift#L287)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

So can we use a blank line for that or is it too criminal? 

I don't insist on revamping `NSAttributedString(markdownString: ...)` with support for paragraph parsing and styling like we have for `**` tags in there.
</blockquote></details>

Sure, we can do that. I couldn't get the paragraphSpacing attribute to work when there are two line breaks in the string, but it works well with one. What's a good approach herw? Simply replacing "\n\n" with "\n" seems like it could miss some cases.


<!-- Sent from Reviewable.io -->

2023-05-26 11:41 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 17 of 18 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 53 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWM7imA5hDJJeoV4hLX:-NWMf4ryCuz-mnC_FOeW:bp6zdra) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d081f092634a272ae469ef10fce1051ce5774358/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L53)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit: For the sake of terminology I would rename this `presentLogoutAlert`.

I think you used `show` because all the other methods are already called `show` so that's fine to leave as is too for consistency's sake.
</blockquote></details>

This function calls into `interactor.logout()` so that a should be something along the lines of `logout()`. It does however present an alert to block user from doing anything else in the meanwhile.
___
*[`ios/MullvadVPN/View controllers/Account/AccountViewController.swift` line 287 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWI6zJ90cnS_WFo1RH0:-NWMfP5A9o3szRcHdG4N:bbgm4fp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d52a409cce0aaf9a9d09bdbd17eab10524907f/ios/MullvadVPN/View%20controllers/Account/AccountViewController.swift#L287)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Sure, we can do that. I couldn't get the paragraphSpacing attribute to work when there are two line breaks in the string, but it works well with one. What's a good approach herw? Simply replacing "\n\n" with "\n" seems like it could miss some cases.
</blockquote></details>

I'd parse `\n\n` to extract paragraphs and then apply NSParagraphStyle to the entire thing. I have sketched support for paragraphs in here: https://gist.github.com/pronebird/73edceb3daf1b266ef91a6bad6ea16ae


<!-- Sent from Reviewable.io -->

2023-05-29 09:41 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 1 of 23 files reviewed, 4 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 77 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWM-WyV0MBVkA3mwnBM:-NWMcxM6D2ZhA03ClD6w:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d081f092634a272ae469ef10fce1051ce5774358/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L77)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Leftover of print() based debugging
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 53 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWM7imA5hDJJeoV4hLX:-NWMc7fZ5BdPUnZvLD9R:bbtzpql) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d081f092634a272ae469ef10fce1051ce5774358/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L53)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This function calls into `interactor.logout()` so that a should be something along the lines of `logout()`. It does however present an alert to block user from doing anything else in the meanwhile.
</blockquote></details>

Guess it's ok to keep, then?
___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 82 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWM-fDT6q1PBfLYysa1:-NWMcYzC5e5XV7ahsZoJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d081f092634a272ae469ef10fce1051ce5774358/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L82)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Me and @mojganii are onto something new, we group constants into sub-namespaces with enums in `UIMetrics`:

```swift
enum UIMetrics {
    enum Alerts {
        static let containerMargins = ...
        static let containerSpacing = ..
    }
}
```

So perhaps you could group all constants related to custom alerts under `enum` and don't worry, we'll refine the rest over time. This also aligns with how things are done in `UIColor+Palette`.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Account/AccountViewController.swift` line 287 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWI6zJ90cnS_WFo1RH0:-NWas5YpAFwKS-ONIOH3:b-ttgqsg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/67d52a409cce0aaf9a9d09bdbd17eab10524907f/ios/MullvadVPN/View%20controllers/Account/AccountViewController.swift#L287)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I'd parse `\n\n` to extract paragraphs and then apply NSParagraphStyle to the entire thing. I have sketched support for paragraphs in here: https://gist.github.com/pronebird/73edceb3daf1b266ef91a6bad6ea16ae
</blockquote></details>

After som discussion I/we settled on keeping strings intact and instead parsing out paragraphs based on the proposal above.
___
*[`ios/MullvadVPN/View controllers/Account/AccountViewController.swift` line 132 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWM6clw2TFJvf6zAZEf:-NWMcuKI2LYkSKSiKnHL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d081f092634a272ae469ef10fce1051ce5774358/ios/MullvadVPN/View%20controllers/Account/AccountViewController.swift#L132)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

The word `do` [doesn't add saliency](https://www.swift.org/documentation/api-design-guidelines/#promote-clear-usage), we can rename this `logout` 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-30 06:52 UTC, pronebird reviewed
> Reviewed 4 of 18 files at r8, 3 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 8 of 24 files reviewed, 4 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift` line 38 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWfQIcE7rfFt6W5mfTO:-NWfQIcFD0QrZHURS2T_:b7qi4fl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dcca37ed85b822610c22dbf8ca8e25f0b3012f54/ios/MullvadVPN/Notifications/Notification%20Providers/RegisteredDeviceInAppNotificationProvider.swift#L38)):*
> ```Swift
>         let stylingOptions = NSAttributedString.MarkdownStylingOptions(font: .systemFont(ofSize: 14.0))
> 
>         return NSMutableAttributedString(markdownString: string, options: stylingOptions) { markdownType, string in
> ```

Maybe we could instantiate non-mutable version of attributed string instead?


<!-- Sent from Reviewable.io -->

2023-05-30 09:14 UTC, pronebird reviewed
> Reviewed 11 of 18 files at r8, 4 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 22 of 24 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 53 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWM7imA5hDJJeoV4hLX:-NWfQtrX7B3FmTUfymdF:b-iq2h4i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d081f092634a272ae469ef10fce1051ce5774358/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L53)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Guess it's ok to keep, then?
</blockquote></details>

I was thinking that it should be called `logOut()` as opposed to `showLogoutAlert()` because in essence it begins the logout process and UI that we show alongside is not really the point but rather comes along to block user from doing anything else.


<!-- Sent from Reviewable.io -->

2023-05-30 10:52 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 22 of 24 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 53 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWM7imA5hDJJeoV4hLX:-NWgGkLy8EQMPj71vcGD:bybveqp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d081f092634a272ae469ef10fce1051ce5774358/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L53)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I was thinking that it should be called `logOut()` as opposed to `showLogoutAlert()` because in essence it begins the logout process and UI that we show alongside is not really the point but rather comes along to block user from doing anything else.
</blockquote></details>

Sure, but it's a little weird that the calling function is `accountViewControllerDidLogOut`. Perhaps we should rename that to `accountViewControllerShouldLogOut` or something.


<!-- Sent from Reviewable.io -->

2023-06-01 07:38 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 22 of 24 files reviewed, 4 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/View controllers/Account/AccountViewController.swift` line 19 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NWgoNDFB5OrzeuHIxdQ:-NWpsOTjDoY1c1yuh6xz:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2b99caa29a3c7cbb7874f2384a66c2067d8c6dd/ios/MullvadVPN/View%20controllers/Account/AccountViewController.swift#L19)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

wasn't it better to show different destinations with enum instead of defining different functions?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-05 14:33 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 1 of 27 files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 12 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NXAwj8k0xbLGk_XKTKM:-NXAwj8k0xbLGk_XKTKN:b-d5a3df) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa4c480eb0f8b0708c2566cc53dd35e1e39f9481/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L12)):*
> ```Swift
> import UIKit
> 
> enum AccountDismissReason: Equatable {
> ```

the name doesn't make sense for me.Maybe AccountDismissPurpose it's better option


<!-- Sent from Reviewable.io -->

2023-06-08 15:28 UTC, pronebird reviewed
> Reviewed 13 of 25 files at r12.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)



<!-- Sent from Reviewable.io -->

2023-06-14 12:47 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 177 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NXPEg1yC-blxaXPXGPE:-NXtvpao9agV-tsEHQmF:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa4c480eb0f8b0708c2566cc53dd35e1e39f9481/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L177)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You probably want this to be strong
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 12 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NXAwj8k0xbLGk_XKTKM:-NXtw1aeDj5xBti9SNzr:b-nmcya2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa4c480eb0f8b0708c2566cc53dd35e1e39f9481/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L12)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

We do not dismiss account view because user wants to log out (the purpose) but we dismiss account because user has already logged out (the reason), i.e logout happens while account controller is still on screen.
</blockquote></details>

No change needed I assume.


<!-- Sent from Reviewable.io -->

2023-06-16 11:40 UTC, buggmagnet requested changes
> Reviewed 12 of 25 files at r12, 6 of 16 files at r13, 7 of 10 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 25 of 28 files reviewed, 8 unresolved discussions (waiting on @mojganii, @pronebird, and @rablador)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelState.kt` line 23 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NY2wSj26gLTxZDRxbpg:-NY2wSj26gLTxZDRxbph:bt1z1ht) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90647cff9b85ccb1230c4f5bb91015d4389fbac5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelState.kt#L23)):*
> ```Kotlin
>                                 included.filter { appData -> !appData.isSystemApp }
>                             }
>                             .sortedBy { it.name },
> ```

It looks like this shouldn't be here, can you revert that change ?
___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 177 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NXPEg1yC-blxaXPXGPE:-NY3-0DY7IsoIxQLc61S:ba17mgn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa4c480eb0f8b0708c2566cc53dd35e1e39f9481/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L177)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Given the recent findings, let's leave this as, it will be fixed in `IOS-200` 
___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 9 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NY2x5_I9yp4yJdi8AxC:-NY2x5_I9yp4yJdi8AxD:bflrm3t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90647cff9b85ccb1230c4f5bb91015d4389fbac5/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L9)):*
> ```Swift
> //
> 
> import MullvadREST
> ```

That import is not needed, let's remove it
___
*[`ios/MullvadVPN/Extensions/StorePaymentManagerError+Display.swift` line 10 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NY2xMJ12m6sr5H_JRGC:-NY2xMJ12m6sr5H_JRGD:b77zdko) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90647cff9b85ccb1230c4f5bb91015d4389fbac5/ios/MullvadVPN/Extensions/StorePaymentManagerError%2BDisplay.swift#L10)):*
> ```Swift
> 
> import Foundation
> import MullvadREST
> ```

Import not needed
___
*[`ios/MullvadVPN/Extensions/StorePaymentManagerError+Display.swift` line 88 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NY2xtTw4ISDcID_3zIA:-NY2xtTw4ISDcID_3zIB:b3kwcwv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90647cff9b85ccb1230c4f5bb91015d4389fbac5/ios/MullvadVPN/Extensions/StorePaymentManagerError%2BDisplay.swift#L88)):*
> ```Swift
>     }
> 
>     func getDisplayErrorTitle(context: REST.CreateApplePaymentResponse.Context) -> String {
> ```

This breaks domain logic between `REST.CreateApplePaymentResponse.Context` and `StorePaymentManagerError`

Really, this should be in `REST.CreateApplePaymentResponse.Context`

```
extension REST.CreateApplePaymentResponse {
    enum Context {
        case purchase
        case restoration
        
        var errorTitle: String {
            switch self {
            case .purchase:  return NSLocalizedString(
                "CANNOT_COMPLETE_PURCHASE_ALERT_TITLE",
                tableName: "Payment",
                value: "Cannot complete the purchase",
                comment: ""
            )
            case .restoration:
                return NSLocalizedString(
                    "RESTORE_PURCHASES_FAILURE_ALERT_TITLE",
                    tableName: "Payment",
                    value: "Cannot restore purchases",
                    comment: ""
                )
            }
        }
    }
```
___
*[`ios/MullvadVPN/View controllers/Account/PaymentAlertPresenter.swift` line 68 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NY2zTS5CD-SXtxO-xrg:-NY2zTS5CD-SXtxO-xrh:b-cie5se) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90647cff9b85ccb1230c4f5bb91015d4389fbac5/ios/MullvadVPN/View%20controllers/Account/PaymentAlertPresenter.swift#L68)):*
> ```Swift
>     }
> 
>     private func getOkButtonTextWithKey(_ key: String) -> String {
> ```

Let's rename this `okButtonTextForKey` (or at least remove the `get` prefix)



_Code quote:_
```Swift
getOkButtonTextWithKey
```


<!-- Sent from Reviewable.io -->

2023-06-16 13:35 UTC, pronebird reviewed
> Dismissed @buggmagnet and @mojganii from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 25 of 28 files reviewed, 7 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 177 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NXPEg1yC-blxaXPXGPE:-NY3OaIm4m9tj8F6uNyg:bhbjzu7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa4c480eb0f8b0708c2566cc53dd35e1e39f9481/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L177)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Given the recent findings, let's leave this as, it will be fixed in `IOS-200` 
</blockquote></details>

I don't think it's a problem. `dismiss()` runs animation and `0.5s` retain is not an issue. The retain cycle happens in operation if I get it right.


<!-- Sent from Reviewable.io -->

2023-06-19 07:41 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 23 of 29 files reviewed, 7 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 177 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NXPEg1yC-blxaXPXGPE:-NYHU_1kCWlWeJ2hSjJF:b-xib3z0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa4c480eb0f8b0708c2566cc53dd35e1e39f9481/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L177)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I don't think it's a problem. `dismiss()` runs animation and `0.5s` retain is not an issue. The retain cycle happens in operation if I get it right.
</blockquote></details>

Will leave as-is then.
___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 9 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NY2x5_I9yp4yJdi8AxC:-NYHUhcQ3BOGhNzYKYEB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90647cff9b85ccb1230c4f5bb91015d4389fbac5/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L9)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

That import is not needed, let's remove it
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Account/PaymentAlertPresenter.swift` line 68 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NY2zTS5CD-SXtxO-xrg:-NYHXw2P9EcjDTixBaXG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90647cff9b85ccb1230c4f5bb91015d4389fbac5/ios/MullvadVPN/View%20controllers/Account/PaymentAlertPresenter.swift#L68)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's rename this `okButtonTextForKey` (or at least remove the `get` prefix)
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelState.kt` line 23 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NY2wSj26gLTxZDRxbpg:-NYHUTrBBfek34JOXxlb:b-773c1n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90647cff9b85ccb1230c4f5bb91015d4389fbac5/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelState.kt#L23)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It looks like this shouldn't be here, can you revert that change ?
</blockquote></details>

Must have been a rebase error. Fixed.
___
*[`ios/MullvadVPN/Extensions/StorePaymentManagerError+Display.swift` line 10 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NY2xMJ12m6sr5H_JRGC:-NYHUkPcDA6Rc_8yylnZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90647cff9b85ccb1230c4f5bb91015d4389fbac5/ios/MullvadVPN/Extensions/StorePaymentManagerError%2BDisplay.swift#L10)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Import not needed
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Extensions/StorePaymentManagerError+Display.swift` line 88 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-NY2xtTw4ISDcID_3zIA:-NYHXlk19doFWOwOvpqB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/90647cff9b85ccb1230c4f5bb91015d4389fbac5/ios/MullvadVPN/Extensions/StorePaymentManagerError%2BDisplay.swift#L88)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This breaks domain logic between `REST.CreateApplePaymentResponse.Context` and `StorePaymentManagerError`

Really, this should be in `REST.CreateApplePaymentResponse.Context`

```
extension REST.CreateApplePaymentResponse {
    enum Context {
        case purchase
        case restoration
        
        var errorTitle: String {
            switch self {
            case .purchase:  return NSLocalizedString(
                "CANNOT_COMPLETE_PURCHASE_ALERT_TITLE",
                tableName: "Payment",
                value: "Cannot complete the purchase",
                comment: ""
            )
            case .restoration:
                return NSLocalizedString(
                    "RESTORE_PURCHASES_FAILURE_ALERT_TITLE",
                    tableName: "Payment",
                    value: "Cannot restore purchases",
                    comment: ""
                )
            }
        }
    }
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-21 13:13 UTC, pronebird reviewed
> Reviewed 5 of 16 files at r13, 7 of 10 files at r14, 4 of 5 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2023-06-21 13:13 UTC, pronebird reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731#-:-NYT4igg6zeVm-Jm_2ZQ:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2023-06-22 10:43 UTC, pronebird reviewed
> Reviewed 3 of 5 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: 27 of 29 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2023-06-22 10:43 UTC, pronebird reviewed
> Reviewed 2 of 5 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2023-06-22 14:34 UTC, merged