Implement redeeming voucher UI part ios 193
mullvad/mullvadvpn-app pull request #4789
Opened 2023-06-13 08:21 UTC by mojganii

in the account flow, user is able to add more credit through voucher code.

- The voucher code can be a combination of letter and number with 16 length that is grouped by `-` in 4 
- The `Redeem` button shouldn't be enabled till the above condition is met
- when user enters a valid voucher code and presses `Redeem` button.the service is revoked and if it's successful we show the `successful view` with the time is been added to the account.
- when the response of service wan't successful.we stay at the redeem voucher code and show the error message under `voucher text filed`

2023-06-13 14:51 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: 14 of 21 files reviewed, 9 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 60 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXopOTCEDJ-O-Zqtysg:-NXp-g7N36UgwZD9npyb:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b62cca4be3219fb53cf484b5293a2fbe841e9cea/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L60)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: formatter went haywire in here. Could you please manually fix such instances. `interactor` and `.tunnelManager` could easily fit on the same line
</blockquote></details>

Done
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 2 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXotduR-KCdjcToeUd4:-NXp082q6xTmzIv5YYiN:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b62cca4be3219fb53cf484b5293a2fbe841e9cea/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L2)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Consider renaming the file too.
</blockquote></details>

Done
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXotBkq-i2ulQp3HLJy:-NXp-pZvATPLFD-oqGSo:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b62cca4be3219fb53cf484b5293a2fbe841e9cea/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L10)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Consider moving it to the bottom of this file as it's a private extension and anyone opening this file would have to start by reading a private extension instead of focusing on a public type.
</blockquote></details>

Done
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 172 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXorHn2EyBazrpU4ZTR:-NXp16_ZB-tnJZSKpfpA:badm1vi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b62cca4be3219fb53cf484b5293a2fbe841e9cea/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L172)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Pretty sure that `frameOfPresentedViewInContainerView` should reflect the adjustment. Does it work properly with device rotation or multi tasking on iPad?
</blockquote></details>

we support `portrait` orientaion on iPhone, there is no need to worry about rotation on iPhone.please,correct me if I'm wrong.
when it comes to iPad.I've tested multi tasking I didn't see any problem.
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 176 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXorv19AJUFAhg5Xx-0:-NXp1ZXCETBivMG7mtWy:b-o2061c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b62cca4be3219fb53cf484b5293a2fbe841e9cea/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L176)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Should it re-position the view when `useFullScreenPresentationInCompactWidth = true`?
</blockquote></details>

Nope,I'll check the value `isInFullScreenPresentation` before making adjustment.
___
*[`ios/MullvadVPN/View controllers/Account/AccountInteractor.swift` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXouL8VEk4fMqiCcS--:-NXp0mJX5o_AlIzY1OOQ:bx1oil0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9be10ce8dea8cd373a1302bad5014dc19a765a0e/ios/MullvadVPN/View%20controllers/Account/AccountInteractor.swift#L16)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Private types should not be exposed. Interactor should handle business logic and only expose a minimal interface the view controllers need to function.
</blockquote></details>

I need to pass `Tunnel Manager` to next interactor.it's data passing object and I'm not able to maintain the object.but I've made a mistake and I shouldn't have made storePaymentManager exposable.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/AccountRedeemVoucherController.swift` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXowXgF8cHBiT4XDulB:-NXp5FWl0BSIcIIbLJla:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b62cca4be3219fb53cf484b5293a2fbe841e9cea/ios/MullvadVPN/View%20controllers/RedeemVoucher/AccountRedeemVoucherController.swift#L21)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Instead of managing children from parent view controller, we should consider making this a coordinator. Then we could also present it from parent coordinator providing custom presentation configuration etc.


```swift
class RedeemVoucherCoordinator: Coordinator, Presentable {
   let navigationController: UINavigationController?

   init(navigationController: UINavigationController = .init()) {
        self.navigationController = nvaigationController
   }
  
   func start() {
        // begin the flow
   }

   var presentedViewController: UIViewController {
        return navigationController
   }
}
```
</blockquote></details>

Done
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/AccountRedeemVoucherController.swift` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXox2oyCjZ9Ckq0BcuD:-NXpBAxt3AwrX_XQiAC2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b62cca4be3219fb53cf484b5293a2fbe841e9cea/ios/MullvadVPN/View%20controllers/RedeemVoucher/AccountRedeemVoucherController.swift#L21)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`UINavigationControllerDelegate` seems to be unused.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/AccountRedeemVoucherController.swift` line 56 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXoz67k9_SSuRT7IYo7:-NXpBdgS2PnWE_LqCl7X:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b62cca4be3219fb53cf484b5293a2fbe841e9cea/ios/MullvadVPN/View%20controllers/RedeemVoucher/AccountRedeemVoucherController.swift#L56)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You can omit `MullvadREST.`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherInteractor.swift` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXozF0MAGJDHKPKRBA2:-NXpBs7c7RoLTFzqcTlI:b38t83m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b62cca4be3219fb53cf484b5293a2fbe841e9cea/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherInteractor.swift#L24)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: cold probably fit on the same line
</blockquote></details>

it's formatter preferences 


<!-- Sent from Reviewable.io -->

2023-06-13 15:20 UTC, pronebird requested changes
> Reviewed 3 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: 17 of 21 files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 61 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXpJUmkEDYo2Pkoerno:-NXpJUmkEDYo2Pkoernp:bgid2o2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L61)):*
> ```Swift
>                 interactor: RedeemVoucherInteractor(tunnelManager: interactor.tunnelManager)
>             )
>             coordinator.start()
> ```

`AccountCoordinator` implements `Presenting` so the parent could initiate modal presentation, i.e:

```swift
// Will push controller into navigation context and start the flow
coordinator.start()

// Present navigation controller modally, optionally providing presentation configuration
self.presentChild(coordinator, animated: true, configuration: ModalPresentationConfiguration(...))
```

`AccountCoordiantor` should then maintain strong reference to `coordinator` until it's dismissed (via `coordinator.dismiss(animated:)`
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 172 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXorHn2EyBazrpU4ZTR:-NXpIdx493I9ZxsZSGZz:bdimuzn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b62cca4be3219fb53cf484b5293a2fbe841e9cea/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L172)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

we support `portrait` orientaion on iPhone, there is no need to worry about rotation on iPhone.please,correct me if I'm wrong.
when it comes to iPad.I've tested multi tasking I didn't see any problem.
</blockquote></details>

iPad supports rotation but if you reckon it works then fine by me
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherInteractor.swift` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXozF0MAGJDHKPKRBA2:-NXpJ0jC3u3g5ynuUtCV:ban46ew) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b62cca4be3219fb53cf484b5293a2fbe841e9cea/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherInteractor.swift#L24)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it's formatter preferences 
</blockquote></details>

It has issues when breaking down long lines so I usually make sure it does not create a deep indentation like this where there is enough space to fit the whole line of code.


<!-- Sent from Reviewable.io -->

2023-06-13 15:23 UTC, pronebird requested changes
> Reviewed 2 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: 19 of 21 files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherCoordinator.swift` line 32 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXpLWy5-1WLORdweSxr:-NXpLWy6BKx2bFmoJl-V:buqlqnq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherCoordinator.swift#L32)):*
> ```Swift
>         let controller = AccountRedeemVoucherController(interactor: interactor)
> 
>         navigationController.present(controller, animated: true)
> ```

Hmmm I thought we were pushing redeem voucher into navigation controller or have I misunderstood this?


<!-- Sent from Reviewable.io -->

2023-06-13 15:37 UTC, pronebird reviewed
> Reviewed 2 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: all files reviewed, 7 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2023-06-14 14:51 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: 14 of 22 files reviewed, 18 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 61 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXpJUmkEDYo2Pkoerno:-NXtcRgxC6DffvP-qJbU:b-7rl0jr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L61)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`AccountCoordinator` implements `Presenting` so the parent could initiate modal presentation, i.e:

```swift
// Will push controller into navigation context and start the flow
coordinator.start()

// Present navigation controller modally, optionally providing presentation configuration
self.presentChild(coordinator, animated: true, configuration: ModalPresentationConfiguration(...))
```

`AccountCoordiantor` should then maintain strong reference to `coordinator` until it's dismissed (via `coordinator.dismiss(animated:)`
</blockquote></details>

done 
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 279 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXtbNiN608m5JeuCUbr:-NXu7cBCBh5OxE2Lfe27:b-ffiht1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L279)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It's nice to semantically have everything under UIMetrics, but in my opinion collecting all margins and such in one place is the main reason for it. Putting it into an extension means spreading it out over many files, which sort of defeats the purpose.

There are more instances of this in the PR.
</blockquote></details>

I disagree to put all of them at the same file when we are using them once.it depends on the domain.if it's using in different places we should put it in the main file otherwise we can put it at the file with the restricted access level.the goal of UIMetrics is name spacing as I understood 
___
*[`ios/MullvadVPN/View controllers/Account/AccountContentView.swift` line 33 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXtcS5WAtmuzUsqpY2k:-NXtukou5kaMxCkRCJOJ:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/Account/AccountContentView.swift#L33)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Views inside stackviews don't implicitly need to set `translatesAutoresizingMaskIntoConstraints`.

There are more instances of this in the PR.
</blockquote></details>

done
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift` line 5 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXtfsvW16m7rA9fUwuZ:-NXu8ihaAzcDEoszm3wd:bl95zby) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherContentView.swift#L5)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Author is Mojgan? :)
</blockquote></details>

other people worked on it before I've been taking over the task and polishing some places
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift` line 169 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXth0tt3U0lBaMtavV7:-NXu99hqEbzHj8aCz-M3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherContentView.swift#L169)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

"isRedeemButtonEnabled" reads better I think.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift` line 247 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXti3ZKE_AcGddc6y3y:-NXuAL2G9ZezanZozGdJ:b-2hwweg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherContentView.swift#L247)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

You can/should use `view.addConstrainedSubviews` instead, along with functions like `view.pinEdges` for layouting constraints. 
</blockquote></details>

I prefer to use the classic way.is the extension fully tested?
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherCoordinator.swift` line 32 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXpLWy5-1WLORdweSxr:-NXuAk1f7p5xqy1UyVqV:b-mk5v4x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherCoordinator.swift#L32)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Hmmm I thought we were pushing redeem voucher into navigation controller or have I misunderstood this?
</blockquote></details>

let's take a look at the latest changes
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherSucceededViewController.swift` line 5 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXtjPng7YMDHs3GnQYo:-NXuAxhM1fXdcdIsa162:brdy8ye) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherSucceededViewController.swift#L5)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Author is Mojgan?
</blockquote></details>

Same as before.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherSucceededViewController.swift` line 102 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXtllMRAUGF5A_GIrHD:-NXuB3gT1kzz_9yzBC8o:bjquptk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherSucceededViewController.swift#L102)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

You can/should use `view.addConstrainedSubviews` instead, along with functions like `view.pinEdges` for layouting constraints. 
</blockquote></details>

same as before
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherViewController.swift` line 57 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXtmPrW4ZoMwUEAkp3f:-NXuBPF0BQmfQYgS_PZw:bo2lfrt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherViewController.swift#L57)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It doesn't seem like contentView does anything bad if we try to enable it while already enabled. If it would, however, can't we put the failsafe inside contentView instead (ie, closer to the source)?
</blockquote></details>

Nope,in content view based on this flag makes decision to show or hide keyboard.so we cannot put the code there.moreover, `viewWillAppear` often calls multiple times in view life cycle  hierarchy  that's why I need to be sure it's the first time and I'll make the textfield ready to input
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherViewController.swift` line 73 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXtmihf9R2u9zqe64NG:-NXuChNP5NML2mjAr7iu:bjquptk) ([raw file](https://github.com/mullvad/mullvad [...]

2023-06-16 07:51 UTC, rablador requested changes
> Reviewed 7 of 8 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: all files reviewed, 13 unresolved discussions (waiting on @mojganii, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 62 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NY25mOL08TjkDdP9Ymn:-NY25mOL08TjkDdP9Ymo:b-4atgty) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62d52237f7ed3b1561af101851b14c5ed5e1ed02/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L62)):*
> ```Swift
>             )
>             coordinator.didFinish = { [weak self] coordinator in
>                 self?.dismiss(animated: true)
> ```

More of a question here, but should one dismiss on self or on the coordinator? I know that both works. @pronebird 
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 279 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXtbNiN608m5JeuCUbr:-NY26-r56nVLK3utbQzv:bg20ru8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L279)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I disagree to put all of them at the same file when we are using them once.it depends on the domain.if it's using in different places we should put it in the main file otherwise we can put it at the file with the restricted access level.the goal of UIMetrics is name spacing as I understood 
</blockquote></details>

Ok, that's a fair point, but on the other hand, if we don't collect them centrally, how do we know if there's anything to reuse when similar metrics are needed?
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift` line 247 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXti3ZKE_AcGddc6y3y:-NY26ov4Ev33F2UA-7TD:b-t0mpq4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherContentView.swift#L247)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I prefer to use the classic way.is the extension fully tested?
</blockquote></details>

It's not covered by tests I think, but it's getting more and more use. I think this is more a matter of reducing boiler plate and standardising how we handle autolayout.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherViewController.swift` line 57 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXtmPrW4ZoMwUEAkp3f:-NY29W0w7H_APagwkGkr:bcx155t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherViewController.swift#L57)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Nope,in content view based on this flag makes decision to show or hide keyboard.so we cannot put the code there.moreover, `viewWillAppear` often calls multiple times in view life cycle  hierarchy  that's why I need to be sure it's the first time and I'll make the textfield ready to input
</blockquote></details>

I was thinking that a similar function could be inside contentView instead of the property setter, thereby letting outside callers simply try to enable without doing checks. But it's not important, more a suggestion.


<!-- Sent from Reviewable.io -->

2023-06-16 12:55 UTC, pronebird requested changes
> Reviewed 5 of 8 files at r4, 3 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: all files reviewed, 8 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 62 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NY25mOL08TjkDdP9Ymn:-NY2xOIf3UojSTROXrK5:b2ogekp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62d52237f7ed3b1561af101851b14c5ed5e1ed02/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L62)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

More of a question here, but should one dismiss on self or on the coordinator? I know that both works. @pronebird 
</blockquote></details>

My preference is usually to put this responsibility on parent. Parent presents, parent dismisses its child. However, shouldn't this call do `coordinator.dismiss(true)` instead?
___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 65 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NY2y3R71yz9Ar_DZn7a:-NY2y3R71yz9Ar_DZn7b:b12w4az) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62d52237f7ed3b1561af101851b14c5ed5e1ed02/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L65)):*
> ```Swift
>             }
>             coordinator.didCancel = { [weak self] coordinator in
>                 self?.dismiss(animated: true)
> ```

Shouldn't this call do `coordinator.dismiss(animated: true)` instead?
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 279 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXtbNiN608m5JeuCUbr:-NY36Ddf7RUBA2sf0JH3:byfu4vh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L279)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Ok, that's a fair point, but on the other hand, if we don't collect them centrally, how do we know if there's anything to reuse when similar metrics are needed?
</blockquote></details>

This refactoring seems to be out of scope of this PR and I always ask you guys and girls to keep each PR as scoped and focused on solving a particular issue as possible. Because each change draws scrutiny, comments, opinions, etc... However keep the change since you've already implemented it.

Historically the point of `UIMetrics` and `UIColor+Pallete` is not only reusability but also customization point for the entire UI. To make it easier to adjust colors and margins etc... This happened before with desktop where margins, sizes etc. were adjusted once. I think it's much easier to do that when certain metrics are concentrated in one place than when they are spread across the entire codebase.

Frankly I think `UIColor+Pallete` and `UIMetrics` seem to be connected quite a bit, so perhaps we could combine both of them in the future the way Mojgan did it here. 
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 159 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NY3EJqqCEdwz_XF8_2Y:-NY3EJqqCEdwz_XF8_2Z:b7b6p8f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62d52237f7ed3b1561af101851b14c5ed5e1ed02/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L159)):*
> ```Swift
> 
>     private func addKeyboardResponder() {
>         keyboardResponder = .init(targetView: presentedView!, handler: { [weak self] view, adjustment in
> ```

Force unwrapping.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift` line 247 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXti3ZKE_AcGddc6y3y:-NY2zjSMAhjJbs2HUJd_:b-npbupn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherContentView.swift#L247)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It's not covered by tests I think, but it's getting more and more use. I think this is more a matter of reducing boiler plate and standardising how we handle autolayout.
</blockquote></details>

FYI

It's not fully tested but we're working on improving it and we could certainly add tests for it or improve the interface to reduce amount of boilerplate. More people involved would also help to improve and test it. 

What you prefer is certainly a valid way to build constraints but eventually you'll realize that you repeat a lot of code and that many things can be done faster with helper tools. Such as this is why you use stack views. Some of the most common constraints are the ones where you need to pin views to edges.

I don't insist on hard introduction into our constraint builder but I think eventually we'll have to reduce amount of boilerplate and that seems to be one way to do so.

A lot of code here can be replaced with:

```
voucherCodeStackView.pinEdgesToSuperviewMargins(.all().excluding(.bottom))
actionsStackView.pinEdgesToSuperviewMargins(.all().excluding(.top))
```

`view.addConstrainedSubviews()` also makes sure to set `translatesAutoresizingMaskIntoConstraints = false` for you.


<!-- Sent from Reviewable.io -->

2023-06-16 13:03 UTC, pronebird requested changes
> Reviewed 1 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: all files reviewed, 9 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherSucceededCoordinator.swift` line 11 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NY3HkAJ9jlb4-gNDUTc:-NY3HkAJ9jlb4-gNDUTd:b-fjaavr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62d52237f7ed3b1561af101851b14c5ed5e1ed02/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherSucceededCoordinator.swift#L11)):*
> ```Swift
> import Foundation
> import UIKit
> ```

This coordinator is mostly empty and not doing much of coordination. Unless I miss something, I think we can merge it into ` RedeemVoucherCoordinator`.


<!-- Sent from Reviewable.io -->

2023-06-16 14:14 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: 14 of 22 files reviewed, 9 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 65 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NY2y3R71yz9Ar_DZn7a:-NY3GxRgARjo4C1zBZhT:b-896fjx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62d52237f7ed3b1561af101851b14c5ed5e1ed02/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L65)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Shouldn't this call do `coordinator.dismiss(animated: true)` instead?
</blockquote></details>

Done
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift` line 247 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXti3ZKE_AcGddc6y3y:-NY3Hy5b4oI_HIynyRrJ:birdvb2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherContentView.swift#L247)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI

It's not fully tested but we're working on improving it and we could certainly add tests for it or improve the interface to reduce amount of boilerplate. More people involved would also help to improve and test it. 

What you prefer is certainly a valid way to build constraints but eventually you'll realize that you repeat a lot of code and that many things can be done faster with helper tools. Such as this is why you use stack views. Some of the most common constraints are the ones where you need to pin views to edges.

I don't insist on hard introduction into our constraint builder but I think eventually we'll have to reduce amount of boilerplate and that seems to be one way to do so.

A lot of code here can be replaced with:

```
voucherCodeStackView.pinEdgesToSuperviewMargins(.all().excluding(.bottom))
actionsStackView.pinEdgesToSuperviewMargins(.all().excluding(.top))
```

`view.addConstrainedSubviews()` also makes sure to set `translatesAutoresizingMaskIntoConstraints = false` for you.
</blockquote></details>

I got your point.before we were using `SnapKit` for avoiding repetition.but let me use this extension when it's fully tested. 


<!-- Sent from Reviewable.io -->

2023-06-16 17:43 UTC, pronebird requested changes
> Reviewed 1 of 4 files at r5, 7 of 8 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: all files reviewed, 8 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 31 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NY4IM9k97vLUMrho9_T:-NY4IM9k97vLUMrho9_U:bjp3ryd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41df1ade144805aab4224efc27e061a023e80983/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L31)):*
> ```Swift
>     }
> 
>     enum Transition {
> ```

`Transition` is a very generic word as it can refer to any kind of transition. Maybe `FormSheetTransition`?


<!-- Sent from Reviewable.io -->

2023-06-19 07:29 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: 20 of 22 files reviewed, 8 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 62 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NY25mOL08TjkDdP9Ymn:-NYHWdzIENi1udFEY7Wl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62d52237f7ed3b1561af101851b14c5ed5e1ed02/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L62)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

My preference is usually to put this responsibility on parent. Parent presents, parent dismisses its child. However, shouldn't this call do `coordinator.dismiss(true)` instead?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 279 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXtbNiN608m5JeuCUbr:-NYHWkV_8541hkIIdjRo:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L279)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This refactoring seems to be out of scope of this PR and I always ask you guys and girls to keep each PR as scoped and focused on solving a particular issue as possible. Because each change draws scrutiny, comments, opinions, etc... However keep the change since you've already implemented it.

Historically the point of `UIMetrics` and `UIColor+Pallete` is not only reusability but also customization point for the entire UI. To make it easier to adjust colors and margins etc... This happened before with desktop where margins, sizes etc. were adjusted once. I think it's much easier to do that when certain metrics are concentrated in one place than when they are spread across the entire codebase.

Frankly I think `UIColor+Pallete` and `UIMetrics` seem to be connected quite a bit, so perhaps we could combine both of them in the future the way Mojgan did it here. 

</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 159 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NY3EJqqCEdwz_XF8_2Y:-NYHYUjO6_nNtXoUuhgk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62d52237f7ed3b1561af101851b14c5ed5e1ed02/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L159)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Force unwrapping.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 31 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NY4IM9k97vLUMrho9_T:-NYHWzBZBY6CRYI5q_bJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41df1ade144805aab4224efc27e061a023e80983/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L31)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`Transition` is a very generic word as it can refer to any kind of transition. Maybe `FormSheetTransition`?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherInteractor.swift` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXozF0MAGJDHKPKRBA2:-NYHXDXy-AxyUmXItXUn:b4mpq3u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b62cca4be3219fb53cf484b5293a2fbe841e9cea/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherInteractor.swift#L24)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

It has issues when breaking down long lines so I usually make sure it does not create a deep indentation like this where there is enough space to fit the whole line of code.
</blockquote></details>

when I change this CI/CD pipe line doesn't pass swift format step.let it stay with current format.


<!-- Sent from Reviewable.io -->

2023-06-19 07:35 UTC, buggmagnet requested changes
> Reviewed 6 of 20 files at r1, 1 of 6 files at r2, 2 of 7 files at r3, 1 of 8 files at r4, 1 of 4 files at r5, 5 of 8 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: 20 of 22 files reviewed, 12 unresolved discussions (waiting on @mojganii, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift` line 62 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NY25mOL08TjkDdP9Ymn:-NYHPvXB8Cm7fiq-CVQv:b-ig5rtp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62d52237f7ed3b1561af101851b14c5ed5e1ed02/ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift#L62)):*
Just my 2 cents regarding dismissing in general, if we take a look at [UIKit dismissal on view controllers](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621505-dismiss) it says the following
> The presenting view controller is responsible for dismissing the view controller it presented. If you call this method on the presented view controller itself, UIKit asks the presenting view controller to handle the dismissal.

We should try to follow that philosophy if possible because that means we can assume the same functioning model as UIKit in regards to dismissal, which in turns makes it easier to reason about our own code
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 159 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NYHNwxU7s61SEX8OExr:-NYHNwxU7s61SEX8OExs:bs3kdwd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41df1ade144805aab4224efc27e061a023e80983/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L159)):*
> ```Swift
> 
>     private func addKeyboardResponder() {
>         keyboardResponder = .init(targetView: presentedView!, handler: { [weak self] view, adjustment in
> ```

Please only use `.init` when the [receiver is a metatype](https://google.github.io/swift/#initializers-1)

The same goes for line 165
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift` line 247 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXti3ZKE_AcGddc6y3y:-NYHSx8DEdXF7PgxDPEi:b7fkd1t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherContentView.swift#L247)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I got your point.before we were using `SnapKit` for avoiding repetition.but let me use this extension when it's fully tested. 
</blockquote></details>

@mojganii  I understand your reticense in refusing to use untested code, but the point of having that extension is not just about preferences, it's also about having a uniform code. 

I'm sure @pronebird thought really hard about how to improve the situation with regards to Autolayout, and we should not let his efforts go to waste "because it's untested" otherwise, we wouldn't be making any progress.

If you have genuine reasons to not use the proposed extensions, please make a case for it, otherwise I would like to ask kindly that you reconsider the suggestions made.
By not wanting to do that, not only you make it harder for the next person that will read the code, but it also creates unnecessary tension in the team, and nobody wins in this situation.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherCoordinator.swift` line 16 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NYHWGRJ7lSvfNp4EHkb:-NYHWGRJ7lSvfNp4EHkc:b-jmur8w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41df1ade144805aab4224efc27e061a023e80983/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherCoordinator.swift#L16)):*
> ```Swift
>     private let navigationController: UINavigationController
>     private let viewController: RedeemVoucherViewController
>     var didFinish: ((RedeemVoucherCoordinator) -> Void)?
> ```

I looked at where `didFinish` and `didCancel` were used, and I'm not sure why we have those. 

The only place I found was in `AccountCoordinator` and we do the following 

```
            coordinator.didFinish = { redeemVoucherCoordinator in
                redeemVoucherCoordinator.dismiss(animated: true)
            }
            coordinator.didCancel = { redeemVoucherCoordinator in
                redeemVoucherCoordinator.dismiss(animated: true)
            }
```

Unless I'm misunderstanding something, we don't need to do that, and we could do the following instead

```
extension RedeemVoucherCoordinator: RedeemVoucherViewControllerDelegate {
    func redeemVoucherDidSucceed(
        _ controller: RedeemVoucherViewController,
        with response: REST.SubmitVoucherResponse
    ) {
        let viewController = RedeemVoucherSucceededViewController(timeAddedComponents: response.dateComponents)
        viewController.delegate = self
        navigationController.pushViewController(viewController, animated: true)
    }

    func redeemVoucherDidCancel(_ controller: RedeemVoucherViewController) {
        dismiss(animated: true)
    }
}

extension RedeemVoucherCoordinator: RedeemVoucherSucceededViewControllerDelegate {
    func redeemVoucherSucceededViewControllerDidFinish(_ controller: RedeemVoucherSucceededViewController) {
        dismiss(animated: true)
    }
}

```
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherSucceededViewController.swift` line 142 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NYHZAiQ7bFkpPSPUP9m:-NYHZAiQ7bFkpPSPUP9n:b-twlli9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41df1ade144805aab4224efc27e061a023e80983/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherSucceededViewController.swift#L142)):*
> ```Swift
> }
> 
> private extension DateComponents {
> ```

This shouldn't be an extension on `DateComponents` because we don't reuse it anywhere else, and it's just needed here.

I suggest turning this into a function on `RedeemVoucherSucceededViewController` instead
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/VoucherTextField.swift` line 54 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NYHYIbB3r52n_8lJO6g:-NYHYIbB3r52n_8lJO6h:biyr9l2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41df1ade144805aab4224efc27e061a023e80983/ios/MullvadVPN/View%20controllers/RedeemVoucher/VoucherTextField.swift#L54)):*
> ```Swift
>         replacementString string: String
>     ) -> Bool {
>         return inputFormatter.textField(
> ```

We can omit `return` here


<!-- Sent from Reviewable.io -->

2023-06-19 08:25 UTC, pronebird reviewed
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: all files reviewed, 10 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherInteractor.swift` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXozF0MAGJDHKPKRBA2:-NYHiK0z7byfHssItnbj:bebk72p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b62cca4be3219fb53cf484b5293a2fbe841e9cea/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherInteractor.swift#L24)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

when I change this CI/CD pipe line doesn't pass swift format step.let it stay with current format.
</blockquote></details>

Try re-formatting code after your change. Usually when the string fits on the same line, then it will keep it untouched. If it breaks it on multiple lines after re-formatting then leave it the way the formatter likes it. Otherwise, I am not blocking PR because of formatting.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherSucceededViewController.swift` line 142 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NYHZAiQ7bFkpPSPUP9m:-NYHjHbZ2nM7WcUZzD_S:bdr6n9b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41df1ade144805aab4224efc27e061a023e80983/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherSucceededViewController.swift#L142)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This shouldn't be an extension on `DateComponents` because we don't reuse it anywhere else, and it's just needed here.

I suggest turning this into a function on `RedeemVoucherSucceededViewController` instead
</blockquote></details>

I don't disagree, but note that it's a private extension so it will not be visible outside of this file.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/VoucherTextField.swift` line 54 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NYHYIbB3r52n_8lJO6g:-NYHjf8D0Puik0dfvZXG:b-jedylm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41df1ade144805aab4224efc27e061a023e80983/ios/MullvadVPN/View%20controllers/RedeemVoucher/VoucherTextField.swift#L54)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We can omit `return` here
</blockquote></details>

I think this has to be addressed with formatter, instead of case-by-case, because it's not critical (the code is functional with or without return statement) but it stalls the review.


<!-- Sent from Reviewable.io -->

2023-06-19 08:32 UTC, rablador reviewed
> Reviewed 5 of 8 files at r6, 1 of 1 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: all files reviewed, 10 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherCoordinator.swift` line 16 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NYHWGRJ7lSvfNp4EHkb:-NYHlP-j9rIutl_zRf8L:b-9ebcfl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41df1ade144805aab4224efc27e061a023e80983/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherCoordinator.swift#L16)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I looked at where `didFinish` and `didCancel` were used, and I'm not sure why we have those. 

The only place I found was in `AccountCoordinator` and we do the following 

```
            coordinator.didFinish = { redeemVoucherCoordinator in
                redeemVoucherCoordinator.dismiss(animated: true)
            }
            coordinator.didCancel = { redeemVoucherCoordinator in
                redeemVoucherCoordinator.dismiss(animated: true)
            }
```

Unless I'm misunderstanding something, we don't need to do that, and we could do the following instead

```
extension RedeemVoucherCoordinator: RedeemVoucherViewControllerDelegate {
    func redeemVoucherDidSucceed(
        _ controller: RedeemVoucherViewController,
        with response: REST.SubmitVoucherResponse
    ) {
        let viewController = RedeemVoucherSucceededViewController(timeAddedComponents: response.dateComponents)
        viewController.delegate = self
        navigationController.pushViewController(viewController, animated: true)
    }

    func redeemVoucherDidCancel(_ controller: RedeemVoucherViewController) {
        dismiss(animated: true)
    }
}

extension RedeemVoucherCoordinator: RedeemVoucherSucceededViewControllerDelegate {
    func redeemVoucherSucceededViewControllerDidFinish(_ controller: RedeemVoucherSucceededViewController) {
        dismiss(animated: true)
    }
}

```
</blockquote></details>

Isn't this touching on the same idea further up in the review that parent controllers should dismiss their children? I seems we might not need two callbacks leading to the same thing though.


<!-- Sent from Reviewable.io -->

2023-06-19 09:02 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: all files reviewed, 10 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherCoordinator.swift` line 16 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NYHWGRJ7lSvfNp4EHkb:-NYHo02f0rR7bRfUda26:bci8e7u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41df1ade144805aab4224efc27e061a023e80983/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherCoordinator.swift#L16)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Isn't this touching on the same idea further up in the review that parent controllers should dismiss their children? I seems we might not need two callbacks leading to the same thing though.
</blockquote></details>

We can replace two callbacks with one, for example only leave `didFinish()` and call it in either case.

However since the parent coordinator `AccountCoordinator` presents the `RedeemVoucherCoordinator` modally, it should also be responsible for dismissing it.

Same principle in relation to UIKit was mentioned by @buggmagnet in the review for some other PR.


<!-- Sent from Reviewable.io -->

2023-06-19 09:04 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: all files reviewed, 10 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 159 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NYHNwxU7s61SEX8OExr:-NYH_kr37u5vWSaVdF65:bq2lusx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41df1ade144805aab4224efc27e061a023e80983/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L159)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Please only use `.init` when the [receiver is a metatype](https://google.github.io/swift/#initializers-1)

The same goes for line 165
</blockquote></details>

I forgot.done
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift` line 247 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXti3ZKE_AcGddc6y3y:-NYHaWz_7vP3wPxVzxRn:baguaa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherContentView.swift#L247)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

@mojganii  I understand your reticense in refusing to use untested code, but the point of having that extension is not just about preferences, it's also about having a uniform code. 

I'm sure @pronebird thought really hard about how to improve the situation with regards to Autolayout, and we should not let his efforts go to waste "because it's untested" otherwise, we wouldn't be making any progress.

If you have genuine reasons to not use the proposed extensions, please make a case for it, otherwise I would like to ask kindly that you reconsider the suggestions made.
By not wanting to do that, not only you make it harder for the next person that will read the code, but it also creates unnecessary tension in the team, and nobody wins in this situation.
</blockquote></details>

It doesn't mean I want not to consider the his efforts and my comment doesn't mean I don't want to use as I mentioned `let me replace when it's fully tested`.it's about UI breaking.I don't think so using extension for the important part like UI without fully tested is a protest.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherCoordinator.swift` line 16 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NYHWGRJ7lSvfNp4EHkb:-NYHaVOX8CcIfjG8QK7o:b-l306pm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41df1ade144805aab4224efc27e061a023e80983/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherCoordinator.swift#L16)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I looked at where `didFinish` and `didCancel` were used, and I'm not sure why we have those. 

The only place I found was in `AccountCoordinator` and we do the following 

```
            coordinator.didFinish = { redeemVoucherCoordinator in
                redeemVoucherCoordinator.dismiss(animated: true)
            }
            coordinator.didCancel = { redeemVoucherCoordinator in
                redeemVoucherCoordinator.dismiss(animated: true)
            }
```

Unless I'm misunderstanding something, we don't need to do that, and we could do the following instead

```
extension RedeemVoucherCoordinator: RedeemVoucherViewControllerDelegate {
    func redeemVoucherDidSucceed(
        _ controller: RedeemVoucherViewController,
        with response: REST.SubmitVoucherResponse
    ) {
        let viewController = RedeemVoucherSucceededViewController(timeAddedComponents: response.dateComponents)
        viewController.delegate = self
        navigationController.pushViewController(viewController, animated: true)
    }

    func redeemVoucherDidCancel(_ controller: RedeemVoucherViewController) {
        dismiss(animated: true)
    }
}

extension RedeemVoucherCoordinator: RedeemVoucherSucceededViewControllerDelegate {
    func redeemVoucherSucceededViewControllerDidFinish(_ controller: RedeemVoucherSucceededViewController) {
        dismiss(animated: true)
    }
}

```
</blockquote></details>

as a few before comments, the current preferences, the parent is responsible for starting and ending the flow 
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherSucceededViewController.swift` line 142 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NYHZAiQ7bFkpPSPUP9m:-NYHdJfV0tjblUbm8nM9:bqloxf7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41df1ade144805aab4224efc27e061a023e80983/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherSucceededViewController.swift#L142)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I don't disagree, but note that it's a private extension so it will not be visible outside of this file.
</blockquote></details>

it's with private access level.


<!-- Sent from Reviewable.io -->

2023-06-19 09:13 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: all files reviewed, 10 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherInteractor.swift` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXozF0MAGJDHKPKRBA2:-NYHueymEJJy3FrfbGLe:b7aigzr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b62cca4be3219fb53cf484b5293a2fbe841e9cea/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherInteractor.swift#L24)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Try re-formatting code after your change. Usually when the string fits on the same line, then it will keep it untouched. If it breaks it on multiple lines after re-formatting then leave it the way the formatter likes it. Otherwise, I am not blocking PR because of formatting.
</blockquote></details>

I did the instruction you've mentioned.but formatter is eager to break it into multiple lines.
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/VoucherTextField.swift` line 54 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NYHYIbB3r52n_8lJO6g:-NYHtfVK5hVvDgNXPGsL:bgnb3iu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41df1ade144805aab4224efc27e061a023e80983/ios/MullvadVPN/View%20controllers/RedeemVoucher/VoucherTextField.swift#L54)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think this has to be addressed with formatter, instead of case-by-case, because it's not critical (the code is functional with or without return statement) but it stalls the review.
</blockquote></details>

I agree.there are different places with different format.It should be addressed by formatter


<!-- Sent from Reviewable.io -->

2023-06-19 12:27 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: 19 of 22 files reviewed, 8 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift` line 247 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXti3ZKE_AcGddc6y3y:-NYIbex8D0KTSKavY9ZG:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherContentView.swift#L247)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

It doesn't mean I want not to consider the his efforts and my comment doesn't mean I don't want to use as I mentioned `let me replace when it's fully tested`.it's about UI breaking.I don't think so using extension for the important part like UI without fully tested is a protest.
</blockquote></details>

Done
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherSucceededViewController.swift` line 102 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXtllMRAUGF5A_GIrHD:-NYIbpf87HxbPPe_V2Bh:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherSucceededViewController.swift#L102)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

same as before
</blockquote></details>

Done
___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherViewController.swift` line 73 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NXtmihf9R2u9zqe64NG:-NYIbujP9r7YZ8E98AwB:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b3af3c690ed50853e5fd08f6e4a4c08f71e7bba7/ios/MullvadVPN/View%20controllers/RedeemVoucher/RedeemVoucherViewController.swift#L73)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

same as before
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-19 12:35 UTC, buggmagnet approved these changes
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: all files reviewed, 6 unresolved discussions (waiting on @mojganii, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/View controllers/RedeemVoucher/VoucherTextField.swift` line 54 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-NYHYIbB3r52n_8lJO6g:-NYIczKUAaAwJNkbGsi1:bkpz1cc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/41df1ade144805aab4224efc27e061a023e80983/ios/MullvadVPN/View%20controllers/RedeemVoucher/VoucherTextField.swift#L54)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I agree.there are different places with different format.It should be addressed by formatter
</blockquote></details>

It's just good housekeeping. We don't need to wait to have a formatter to have good coding practices. 


<!-- Sent from Reviewable.io -->

2023-06-20 10:49 UTC, rablador reviewed
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)



<!-- Sent from Reviewable.io -->

2023-06-20 10:49 UTC, rablador approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-:-NYNQ40z9VYaCtLbupzO:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)



<!-- Sent from Reviewable.io -->

2023-06-20 11:30 UTC, pronebird reviewed
> Dismissed @rablador from a discussion.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2023-06-20 11:31 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789#-:-NYNZeSCCj6kFGJpm1kW:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2023-06-20 11:32 UTC, pronebird approved these changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2023-06-20 11:41 UTC, buggmagnet approved these changes
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4789)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii and @rablador)



<!-- Sent from Reviewable.io -->

2023-06-20 12:01 UTC, merged