Add filtering to location selection
mullvad/mullvadvpn-app pull request #4794
Opened 2023-06-14 12:52 UTC by rablador

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)

2023-06-22 06:52 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 0 of 38 files reviewed, 1 unresolved discussion

___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYO6FUX2mFVBOur8hHm:-NYO6FUX2mFVBOur8hHn:b-5zedi7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad9a99f409b35c92b8b84b10745032c857e5b1eb/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L82)):*
> ```Swift
>     }
> 
>     enum FilterView {
> ```

I am overdoing it here...?


<!-- Sent from Reviewable.io -->

2023-06-22 09:41 UTC, buggmagnet reviewed
> Reviewed 10 of 36 files at r1, 1 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 11 of 38 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYO6FUX2mFVBOur8hHm:-NYXMcix0B7DgAbNq8Ym:b-al9fcr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad9a99f409b35c92b8b84b10745032c857e5b1eb/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L82)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I am overdoing it here...?
</blockquote></details>

No it's beautiful :purple_heart: 


<!-- Sent from Reviewable.io -->

2023-06-22 14:01 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 11 of 38 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/RelayFilter/RelayFilterCellFactory.swift` line 63 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYYMK7LAFcSXE15MRA0:-NYYMK7LAFcSXE15MRA1:bcwong2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786caf33b313753f5d7299f2aeddec08d98aa1c/ios/MullvadVPN/View%20controllers/RelayFilter/RelayFilterCellFactory.swift#L63)):*
> ```Swift
>         guard let cell = cell as? CheckableSettingsCell else { return }
> 
>         var title = ""
> ```

nit: This doesn't need to be a `var` if you do it the following way. The intent declaration is stronger IMHO as a `let`

```swift
        let title: String
        switch item {
        case .allProviders:
            title = "All providers"
            setFontWeight(.semibold, to: cell.titleLabel)
        case let .provider(name):
            title = name
            setFontWeight(.regular, to: cell.titleLabel)
        default:
            title = ""
            assertionFailure("Item mismatch. Got: \(item)")
        }

        cell.titleLabel.text = NSLocalizedString(
            "RELAY_FILTER_CELL_LABEL",
            tableName: "Relay filter provider cell",
            value: title,
            comment: ""
        )
```


<!-- Sent from Reviewable.io -->

2023-06-26 06:58 UTC, pronebird requested changes
> Reviewed 15 of 36 files at r1, 10 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 36 of 38 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/SelectLocationCoordinator.swift` line 107 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYqSArKELSR9_bUid9Q:-NYqSArKELSR9_bUid9R:b-8urzui) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786caf33b313753f5d7299f2aeddec08d98aa1c/ios/MullvadVPN/Coordinators/App/SelectLocationCoordinator.swift#L107)):*
> ```Swift
>     }
> 
>     private func makeRelayFilterCoordinator(forModalPresentation isModalPresentation: Bool)
> ```

On desktop we push filter into navigation stack.


<!-- Sent from Reviewable.io -->

2023-06-26 06:58 UTC, pronebird reviewed
> Reviewed 1 of 36 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 37 of 38 files reviewed, 3 unresolved discussions (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-06-26 06:59 UTC, pronebird reviewed
> Reviewed 11 of 36 files at r1, 1 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: all files reviewed, 3 unresolved discussions (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-06-29 18:59 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: all files reviewed, 6 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/App/SelectLocationCoordinator.swift` line 107 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYqSArKELSR9_bUid9Q:-NZ7RAUbBusCu0a0WMkS:bg1obuv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786caf33b313753f5d7299f2aeddec08d98aa1c/ios/MullvadVPN/Coordinators/App/SelectLocationCoordinator.swift#L107)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

On desktop we push filter into navigation stack.
</blockquote></details>

I know, but it doesn't really make sense to me. AFAIK navigation items (like items in a list etc) usually go horisontally while new flows start vertically. The select location vc is an example of this, popping up over the map. I can change it, but especially on mobile I really think it feels natural to have it as a modal.
___
*[`ios/MullvadVPN/View controllers/RelayFilter/RelayFilterCellFactory.swift` line 63 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYYMK7LAFcSXE15MRA0:-NZ7SJY_0o6MyblWM67E:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786caf33b313753f5d7299f2aeddec08d98aa1c/ios/MullvadVPN/View%20controllers/RelayFilter/RelayFilterCellFactory.swift#L63)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit: This doesn't need to be a `var` if you do it the following way. The intent declaration is stronger IMHO as a `let`

```swift
        let title: String
        switch item {
        case .allProviders:
            title = "All providers"
            setFontWeight(.semibold, to: cell.titleLabel)
        case let .provider(name):
            title = name
            setFontWeight(.regular, to: cell.titleLabel)
        default:
            title = ""
            assertionFailure("Item mismatch. Got: \(item)")
        }

        cell.titleLabel.text = NSLocalizedString(
            "RELAY_FILTER_CELL_LABEL",
            tableName: "Relay filter provider cell",
            value: title,
            comment: ""
        )
```
</blockquote></details>

Done
___
*[`ios/MullvadVPN/View controllers/RelayFilter/RelayFilterViewController.swift` line 104 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYqgDGV43ieEvPZhhC6:-NZ7SVEmEDlwEtyQBYiv:b-os2t4l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786caf33b313753f5d7299f2aeddec08d98aa1c/ios/MullvadVPN/View%20controllers/RelayFilter/RelayFilterViewController.swift#L104)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit: How about renaming `applyFilter` and renaming `didApplyFilter` to `onApplyFilter` ?

Here we haven't applied anything yet, we're just bubbling up the interaction, so I'm not super keen on calling this `didApplyFilter` 

Doing this would make the call site look like this 

```
        relayFilterViewController.onApplyFilter = { [weak self] filter in
            guard let self else { return }

            var relayConstraints = tunnelManager.settings.relayConstraints
            relayConstraints.filter = .only(filter) // Here we actually apply the filter
```
</blockquote></details>

From a UI standpoint the user did apply the filter, but I can also agree that it makes more sense with "on" from a system standpoint. Will change it.
___
*[`ios/MullvadVPN/View controllers/RelayFilter/RelayFilterViewModel.swift` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYqiuQO9zmZGDn8VlYD:-NZ7TRsTD0inGHQvU8jK:bo6ap9z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786caf33b313753f5d7299f2aeddec08d98aa1c/ios/MullvadVPN/View%20controllers/RelayFilter/RelayFilterViewModel.swift#L18)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

`Set` already conforms to `Collection` where you added the `caseInsensitiveSorted` method, so you don't need to wrap this in an `Array` 

```
func uniqueProviders(_ relays: [Relay]) -> [String] {
    Set(relays.map { $0.provider }).caseInsensitiveSorted()
}

func uniqueProvidersWithArray(_ relays: [Relay]) -> [String] {
    Array(Set(relays.map { $0.provider })).caseInsensitiveSorted()
}

print(uniqueProviders(providers) == uniqueProvidersWithArray(providers)) // prints "true"
```
</blockquote></details>

Indeed!
___
*[`ios/MullvadVPN/View controllers/RelayFilter/RelayFilterViewModel.swift` line 65 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYqdUOp0NOK9VwoLIjg:-NZ7TWLF3xKaD0W_scEf:bmwqtyz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786caf33b313753f5d7299f2aeddec08d98aa1c/ios/MullvadVPN/View%20controllers/RelayFilter/RelayFilterViewModel.swift#L65)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We can remove all those `get` prefixes, they don't add anything meaningful to the method names
</blockquote></details>

I like them when part of function declarations (denoting an action), as opposed to variable declarations. @mojganii @pronebird, please chip in so that we can have consensus going forward.
___
*[`ios/MullvadVPN/Views/CheckboxView.swift` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYqo-3OEKLXpKqXAfQL:-NZ7UjZ434Ur_iPxTByj:b-y866xf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786caf33b313753f5d7299f2aeddec08d98aa1c/ios/MullvadVPN/Views/CheckboxView.swift#L32)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Is there any reason why we do this before the call to `super.init` ?
It looks like it's an innocent mistake, or a code smell, but it doesn't look right IMHO
</blockquote></details>

Compiler reasons: `Property 'self.isChecked' not initialized at super.init call`
Can give isChecked a default value if that's better.
___
*[`ios/RelaySelector/RelaySelector.swift` line 71 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYqyBnw5ni1AX6EurgK:-NZ7WYpI9M2ZHhluMlyj:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786caf33b313753f5d7299f2aeddec08d98aa1c/ios/RelaySelector/RelaySelector.swift#L71)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

If you switch the checks around, it's much, much easier to understand, here's what it would look like 

```swift
    public static func relayMatchesFilter(_ relay: REST.ServerRelay, filter: RelayFilter) -> Bool {
        if case let .only(providers) = filter.providers {
            if providers.contains(relay.provider) == false {
                return false
            }
        }

        switch filter.ownership {
        case .any:
            return true
        case .owned:
            return relay.owned
        case .rented:
            return relay.owned == false
        }
    }
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-30 07:50 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 33 of 38 files reviewed, 6 unresolved discussions (waiting on @mojganii and @pronebird)

___
*[`ios/MullvadVPN/View controllers/RelayFilter/RelayFilterViewModel.swift` line 65 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYqdUOp0NOK9VwoLIjg:-NZAGA0t3EeueXjV4a-P:b-h1q1le) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786caf33b313753f5d7299f2aeddec08d98aa1c/ios/MullvadVPN/View%20controllers/RelayFilter/RelayFilterViewModel.swift#L65)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I like them when part of function declarations (denoting an action), as opposed to variable declarations. @mojganii @pronebird, please chip in so that we can have consensus going forward.
</blockquote></details>

It's part of the [Swift API design guidelines](https://www.swift.org/documentation/api-design-guidelines/#promote-clear-usage) 
Namely "Every word should convey salient information at the use site"

Here the word `get` doesn't add anything. `ownership(for: myItem)`  already states that calling this gives us the ownership for the item.


<!-- Sent from Reviewable.io -->

2023-07-03 11:37 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 33 of 38 files reviewed, 6 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/View controllers/RelayFilter/RelayFilterViewModel.swift` line 65 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYqdUOp0NOK9VwoLIjg:-NZQXc_V8x2AOmPb4tIZ:bqdxfmx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786caf33b313753f5d7299f2aeddec08d98aa1c/ios/MullvadVPN/View%20controllers/RelayFilter/RelayFilterViewModel.swift#L65)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It's part of the [Swift API design guidelines](https://www.swift.org/documentation/api-design-guidelines/#promote-clear-usage) 
Namely "Every word should convey salient information at the use site"

Here the word `get` doesn't add anything. `ownership(for: myItem)`  already states that calling this gives us the ownership for the item.
</blockquote></details>

Fair enough. Will change.


<!-- Sent from Reviewable.io -->

2023-08-03 09:21 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 5 files at r3, 17 of 19 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-:-Nauh0E4Cve2DDBhMy0g:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/Views/CheckboxView.swift` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYqo-3OEKLXpKqXAfQL:-Naudqt9A9zogqAq-RsW:bb0gzar) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786caf33b313753f5d7299f2aeddec08d98aa1c/ios/MullvadVPN/Views/CheckboxView.swift#L32)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Compiler reasons: `Property 'self.isChecked' not initialized at super.init call`
Can give isChecked a default value if that's better.
</blockquote></details>

Can you then fix the property declaration to contain the default value?

```swift
var isChecked: Bool = false { 
    didSet {
        checkmarkView.alpha = isChecked ? 1 : 0
    }
}
```
___
*[`ios/RelaySelector/RelaySelector.swift` line 72 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NaufVAv2ZpZe5HyenoW:-NaufVAv2ZpZe5HyenoX:b-8yntzj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a75c802336203e9217740adfa379393e2947c3af/ios/RelaySelector/RelaySelector.swift#L72)):*
> ```Swift
>     /// Determines whether a `REST.ServerRelay` satisfies the given relay filter.
>     public static func relayMatchesFilter(_ relay: REST.ServerRelay, filter: RelayFilter) -> Bool {
>         if case let .only(providers) = filter.providers {
> ```

Nit, if case and nested `if` can be merged into single if statement.


<!-- Sent from Reviewable.io -->

2023-08-03 12:45 UTC, buggmagnet reviewed
> Reviewed 1 of 36 files at r1, 1 of 5 files at r3, 10 of 19 files at r4, 3 of 14 files at r6, 2 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 28 of 39 files reviewed, 1 unresolved discussion (waiting on @mojganii and @pronebird)

___
*[`ios/MullvadVPN/Views/CheckboxView.swift` line 32 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYqo-3OEKLXpKqXAfQL:-NavQaYe3oBgD8MEwTvB:b-7rl0jr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2786caf33b313753f5d7299f2aeddec08d98aa1c/ios/MullvadVPN/Views/CheckboxView.swift#L32)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Can you then fix the property declaration to contain the default value?

```swift
var isChecked: Bool = false { 
    didSet {
        checkmarkView.alpha = isChecked ? 1 : 0
    }
}
```
</blockquote></details>

done 
___
*[`ios/RelaySelector/RelaySelector.swift` line 72 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NaufVAv2ZpZe5HyenoW:-NavQZt_7ub2g72S4dxD:b-7rl0jr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a75c802336203e9217740adfa379393e2947c3af/ios/RelaySelector/RelaySelector.swift#L72)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit, if case and nested `if` can be merged into single if statement.
</blockquote></details>

done 


<!-- Sent from Reviewable.io -->

2023-08-10 07:26 UTC, buggmagnet reviewed
> Reviewed 1 of 7 files at r7, 2 of 17 files at r9, 5 of 10 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 27 of 39 files reviewed, all discussions resolved (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-08-11 07:56 UTC, pronebird requested changes
> Reviewed 1 of 7 files at r7, 2 of 2 files at r8, 1 of 17 files at r9, 2 of 10 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 30 of 39 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 100 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NbY_OiN-WSigTVQTkPe:-NbY_OiN-WSigTVQTkPf:bbafmu1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c68cd89004f96c88090467ca79c1e98c43cb51a/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L100)):*
> ```Swift
>     /// Common layout margins for row views presentation
>     /// Similar to `settingsCellLayoutMargins` however maintains equal horizontal spacing
>     static let rowViewLayoutMargins = NSDirectionalEdgeInsets(top: 16, leading: 24, bottom: 16, trailing: 24)
> ```

See constants under `UIMetrics.UITableView`, seems like duplication.
___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 103 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NbYZjHE4bIm3cPhf6GP:-NbYZjHFBQ3-KQV5Ld4Z:b-q069m5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c68cd89004f96c88090467ca79c1e98c43cb51a/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L103)):*
> ```Swift
> 
>     /// Common layout margins for settings cell presentation
>     static let settingsCellLayoutMargins = NSDirectionalEdgeInsets(top: 16, leading: 24, bottom: 16, trailing: 12)
> ```

I think this was moved under `UIMetrics.SettingsCell.layoutMargins`
___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 106 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NbYZtkiEn6sC_7Qx8CP:-NbYZtkiEn6sC_7Qx8CQ:b6207lc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c68cd89004f96c88090467ca79c1e98c43cb51a/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L106)):*
> ```Swift
> 
>     /// Common layout margins for text field in settings input cell presentation
>     static let settingsInputCellTextFieldLayoutMargins = UIEdgeInsets(
> ```

See if you can find a similar constant in `UIMetrics.SettingsCell` or perhaps define one in there
___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 117 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NbY_XCW-_aP9Bhgvxl_:-NbY_XCW-_aP9Bhgvxla:b-4lls6e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c68cd89004f96c88090467ca79c1e98c43cb51a/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L117)):*
> ```Swift
> 
>     /// Common cell indentation width
>     static let cellIndentationWidth: CGFloat = 16
> ```

I think that was moved to `UIMetrics.TableView`
___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 132 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NbY_wL_7h-gXWHUjvE8:-NbY_wL_7h-gXWHUjvE9:bhybnlo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c68cd89004f96c88090467ca79c1e98c43cb51a/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L132)):*
> ```Swift
> 
>     /// Spacing used between distinct sections of views
>     static let sectionSpacing: CGFloat = 24
> ```

Was it also moved to `UIMetrics.UITableView` namespace?


<!-- Sent from Reviewable.io -->

2023-08-11 07:57 UTC, pronebird reviewed
> Reviewed 1 of 14 files at r6, 1 of 17 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 31 of 39 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)



<!-- Sent from Reviewable.io -->

2023-08-11 08:04 UTC, pronebird reviewed
> Reviewed 1 of 10 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: all files reviewed, 5 unresolved discussions (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-08-11 08:12 UTC, pronebird reviewed
> Reviewed 2 of 10 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 37 of 39 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)



<!-- Sent from Reviewable.io -->

2023-08-11 08:14 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 37 of 39 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 100 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NbY_OiN-WSigTVQTkPe:-NbYe-rF4t6ECxFXDmYZ:b-9mm33z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c68cd89004f96c88090467ca79c1e98c43cb51a/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L100)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

See constants under `UIMetrics.UITableView`, seems like duplication.
</blockquote></details>

Fixed. Rebase issue?
___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 103 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NbYZjHE4bIm3cPhf6GP:-NbYe0G_CitZVPbqsBCG:b-9mm33z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c68cd89004f96c88090467ca79c1e98c43cb51a/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L103)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think this was moved under `UIMetrics.SettingsCell.layoutMargins`
</blockquote></details>

Fixed. Rebase issue?
___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 106 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NbYZtkiEn6sC_7Qx8CP:-NbYe0YW5Y6e0YjE6Wa3:b-9mm33z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c68cd89004f96c88090467ca79c1e98c43cb51a/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L106)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

See if you can find a similar constant in `UIMetrics.SettingsCell` or perhaps define one in there
</blockquote></details>

Fixed. Rebase issue?
___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 117 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NbY_XCW-_aP9Bhgvxl_:-NbYe0tLDIxKyqwMK6sZ:b-9mm33z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c68cd89004f96c88090467ca79c1e98c43cb51a/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L117)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think that was moved to `UIMetrics.TableView`
</blockquote></details>

Fixed. Rebase issue?
___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 132 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NbY_wL_7h-gXWHUjvE8:-NbYe2pkAXRByWemSM7i:b-9mm33z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7c68cd89004f96c88090467ca79c1e98c43cb51a/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L132)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Was it also moved to `UIMetrics.UITableView` namespace?
</blockquote></details>

Fixed. Rebase issue?


<!-- Sent from Reviewable.io -->

2023-08-11 08:41 UTC, pronebird requested changes
> Reviewed 1 of 2 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 39 of 40 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/RelayFilter/RelayFilterViewModel.swift` line 123 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NbYk5yy0X97CSkYzq-N:-NbYk5yy0X97CSkYzq-O:bg8x1iz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0ee5605c931fab649fd96e9094d9d73877ef9924/ios/MullvadVPN/View%20controllers/RelayFilter/RelayFilterViewModel.swift#L123)):*
> ```Swift
>         case .rented:
>             return rentedProviders
>         default:
> ```

Maybe use `any` instead of `default`, unless I miss something `Ownership` is an enum type with three variants right?


<!-- Sent from Reviewable.io -->

2023-08-11 08:41 UTC, pronebird reviewed
> Reviewed 1 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-08-11 09:07 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/MullvadVPN/View controllers/RelayFilter/RelayFilterViewModel.swift` line 123 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NbYk5yy0X97CSkYzq-N:-NbYqI50ArJcX5CnVOfn:b-edrihb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0ee5605c931fab649fd96e9094d9d73877ef9924/ios/MullvadVPN/View%20controllers/RelayFilter/RelayFilterViewModel.swift#L123)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe use `any` instead of `default`, unless I miss something `Ownership` is an enum type with three variants right?
</blockquote></details>

Indeed, updated.


<!-- Sent from Reviewable.io -->

2023-08-15 10:50 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-12 14:13 UTC, buggmagnet requested changes
> Reviewed 2 of 36 files at r1, 1 of 19 files at r4, 13 of 24 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 31 of 42 files reviewed, 4 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Extensions/UIBarButtonItem+Blocks.swift` line 2 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgZC6YP-V9t-Kaxiucx:-NgZC6YP-V9t-Kaxiucy:b-bhiq6x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f239a4c7a1b547c7a87bbdfdcf3dbd00e74e3a3/ios/MullvadVPN/Extensions/UIBarButtonItem%2BBlocks.swift#L2)):*
> ```Swift
> //
> //  UIBarButtonItem+Blocks.swift
> ```

This file was deleted and shouldn't be here.
___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 68 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgZCpVxABCC7xhhJo1M:-NgZCpVxABCC7xhhJo1N:b-3pb48r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad9a99f409b35c92b8b84b10745032c857e5b1eb/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L68)):*
> ```Swift
>     }
> 
>     enum SettingsCell {
> ```

A lot of these deletions look like regressions, did  you get a merge issue when rebasing from `main` ?
IMHO we should checkout the version from the current `main` and retroactively add what's missing for the work needed for the filters here. 
___
*[`ios/MullvadVPN/View controllers/Account/AccountContentView.swift` line 84 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgZDeBF-7hRa_9uzMd3:-NgZDeBF-7hRa_9uzMd4:b-h2zrve) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a61a0cd20092ac722884d785602f2fa18d2b4aa8/ios/MullvadVPN/View%20controllers/Account/AccountContentView.swift#L84)):*
> ```Swift
>         stackView.translatesAutoresizingMaskIntoConstraints = false
>         stackView.axis = .vertical
>         stackView.spacing = UIMetrics.TableView.sectionSpacing
> ```

Why are there changes here ? It seems unrelated to filtering location in the relay filter
___
*[`ios/MullvadVPN/View controllers/DeviceList/DeviceManagementContentView.swift` line 215 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgZDpWO4IRpm7l-0qDy:-NgZDpWO4IRpm7l-0qDz:b-lew17l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f239a4c7a1b547c7a87bbdfdcf3dbd00e74e3a3/ios/MullvadVPN/View%20controllers/DeviceList/DeviceManagementContentView.swift#L215)):*
> ```Swift
>         }
> 
>         if animated {
> ```

Same as the previous comment, please remove those changes as they are not related to this PR


<!-- Sent from Reviewable.io -->

2023-10-12 14:15 UTC, buggmagnet requested changes
It looks like there are many unrelated changes in this PR, likely due to a rebasing conflict. 
I think we should extract the fundamental changes in this PR (all the new elements, such as the pill cells, the relay filter data source changes etc...), delete this branch and start again from a fresh main.

It's hard to figure out what changes are necessary in this PR, but it looks like a lot of them are regressions rather than changes.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-:-NgZE8pB5skceejidj5g:b-645mum)* status: 31 of 42 files reviewed, 4 unresolved discussions (waiting on @pronebird and @rablador)



<!-- Sent from Reviewable.io -->

2023-10-13 09:32 UTC, rablador reviewed
The rebase from main was huge due to this branch going stale. I have quickly looked through the full diff and it looks sane.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-:-NgcND-dEG1nqwuEPGEf:b28xj1x)* status: 31 of 42 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/Extensions/UIBarButtonItem+Blocks.swift` line 2 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgZC6YP-V9t-Kaxiucx:-NgcN8822i8Erx6rx25Z:bcpreqg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f239a4c7a1b547c7a87bbdfdcf3dbd00e74e3a3/ios/MullvadVPN/Extensions/UIBarButtonItem%2BBlocks.swift#L2)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This file was deleted and shouldn't be here.
</blockquote></details>

Probably an old change due to rebase. I have deleted the file now.
___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 68 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgZCpVxABCC7xhhJo1M:-NgcMiAI4hQEm0NILnyy:b5aobxd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad9a99f409b35c92b8b84b10745032c857e5b1eb/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L68)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

A lot of these deletions look like regressions, did  you get a merge issue when rebasing from `main` ?
IMHO we should checkout the version from the current `main` and retroactively add what's missing for the work needed for the filters here.
</blockquote></details>

UIMetrics had a lot of merge conflicts, so I cleaned up things a bit. This has led to some changes trickling down the code base, but nothing big or complicated.
___
*[`ios/MullvadVPN/View controllers/Account/AccountContentView.swift` line 84 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgZDeBF-7hRa_9uzMd3:-NgcMwZuAvVaDZ_zFtWn:b-93vxlw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a61a0cd20092ac722884d785602f2fa18d2b4aa8/ios/MullvadVPN/View%20controllers/Account/AccountContentView.swift#L84)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Why are there changes here ? It seems unrelated to filtering location in the relay filter
</blockquote></details>

Probably an old change due to rebase. It's correct in its current form.
___
*[`ios/MullvadVPN/View controllers/DeviceList/DeviceManagementContentView.swift` line 215 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgZDpWO4IRpm7l-0qDy:-NgcN64F9VR5qHMWSMWt:b-93vxlw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f239a4c7a1b547c7a87bbdfdcf3dbd00e74e3a3/ios/MullvadVPN/View%20controllers/DeviceList/DeviceManagementContentView.swift#L215)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Same as the previous comment, please remove those changes as they are not related to this PR
</blockquote></details>

Probably an old change due to rebase. It's correct in its current form.


<!-- Sent from Reviewable.io -->

2023-10-17 07:54 UTC, buggmagnet requested changes
> Reviewed 1 of 17 files at r9, 1 of 10 files at r10, 1 of 3 files at r12, 1 of 1 files at r13, 9 of 24 files at r14, 2 of 2 files at r15, 1 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 41 of 43 files reviewed, 4 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Extensions/UIBarButtonItem+Blocks.swift` line 2 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgZC6YP-V9t-Kaxiucx:-Ngsi5kx2qYWAWjpqA4c:bm47d46) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f239a4c7a1b547c7a87bbdfdcf3dbd00e74e3a3/ios/MullvadVPN/Extensions/UIBarButtonItem%2BBlocks.swift#L2)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Probably an old change due to rebase. I have deleted the file now.
</blockquote></details>

The file is still there
___
*[`ios/MullvadVPN/View controllers/RelayFilter/RelayFilterDataSource.swift` line 53 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgwTV7s6Zuu5NOpKEt0:-NgwTV7s6Zuu5NOpKEt1:b53mzso) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb69f11060442f24f94126dece0f9d535c13ca1f/ios/MullvadVPN/View%20controllers/RelayFilter/RelayFilterDataSource.swift#L53)):*
> ```Swift
>         tableView.delegate = self
> 
>         registerClasses()
> ```

We probably want to register those and create the data snapshots before we set ourselves to be the `tableView.delegate` 
___
*[`ios/MullvadVPN/View controllers/RelayFilter/RelayFilterDataSource.swift` line 297 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgwULaL6zzRAGgISziJ:-NgwULaL6zzRAGgISziK:b-odmnh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb69f11060442f24f94126dece0f9d535c13ca1f/ios/MullvadVPN/View%20controllers/RelayFilter/RelayFilterDataSource.swift#L297)):*
> ```Swift
> 
>         if select {
>             tableView?.selectRow(at: indexPath, animated: false, scrollPosition: .none)
> ```

We can remove the last parameter, it's the default value already


<!-- Sent from Reviewable.io -->

2023-10-17 08:27 UTC, pronebird reviewed
> Reviewed 12 of 24 files at r14, 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Coordinators/SelectLocationCoordinator.swift` line 25 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgwgFONDBQJMNqT6dDJ:-NgwgFONDBQJMNqT6dDK:broeqg8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00ae7c231af62b87bdd7a96c603c1598404434c1/ios/MullvadVPN/Coordinators/SelectLocationCoordinator.swift#L25)):*
> ```Swift
>     }
> 
>     var presentationContext: UIViewController {
> ```

Nit: we have default implementation for `Presenting` when `Presentable` is implemented.
___
*[`ios/MullvadVPN/Extensions/UIBarButtonItem+Blocks.swift` line 2 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgZC6YP-V9t-Kaxiucx:-NgwgXYK1M7sA1KdEVSf:bk3wkmm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f239a4c7a1b547c7a87bbdfdcf3dbd00e74e3a3/ios/MullvadVPN/Extensions/UIBarButtonItem%2BBlocks.swift#L2)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

The file is still there
</blockquote></details>

This file is absent in `main`. I believe we switched to using `UIAction` since migration to iOS 14.


<!-- Sent from Reviewable.io -->

2023-10-17 09:14 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 36 of 43 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/SelectLocationCoordinator.swift` line 25 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgwgFONDBQJMNqT6dDJ:-NgwuL8_7HVCfJV1vyi_:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00ae7c231af62b87bdd7a96c603c1598404434c1/ios/MullvadVPN/Coordinators/SelectLocationCoordinator.swift#L25)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: we have default implementation for `Presenting` when `Presentable` is implemented.
</blockquote></details>

Removed.
___
*[`ios/MullvadVPN/View controllers/RelayFilter/RelayFilterDataSource.swift` line 53 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgwTV7s6Zuu5NOpKEt0:-NgwtbioB_i5GcpnSlLB:b1mkrjq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb69f11060442f24f94126dece0f9d535c13ca1f/ios/MullvadVPN/View%20controllers/RelayFilter/RelayFilterDataSource.swift#L53)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We probably want to register those and create the data snapshots before we set ourselves to be the `tableView.delegate`
</blockquote></details>

Doesn't matter, but it might look more logical so I can change it.
___
*[`ios/MullvadVPN/View controllers/RelayFilter/RelayFilterDataSource.swift` line 297 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgwULaL6zzRAGgISziJ:-NgwtGjR5vFR9s2uMDsS:b-d5v76r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb69f11060442f24f94126dece0f9d535c13ca1f/ios/MullvadVPN/View%20controllers/RelayFilter/RelayFilterDataSource.swift#L297)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We can remove the last parameter, it's the default value already
</blockquote></details>

It's not optional.
___
*[`ios/MullvadVPN/Extensions/UIBarButtonItem+Blocks.swift` line 2 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgZC6YP-V9t-Kaxiucx:-Ngwrx_m6Gz7ioahfCsN:b-tbfua) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f239a4c7a1b547c7a87bbdfdcf3dbd00e74e3a3/ios/MullvadVPN/Extensions/UIBarButtonItem%2BBlocks.swift#L2)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This file is absent in `main`. I believe we switched to using `UIAction` since migration to iOS 14.
</blockquote></details>

Weird, I deleted it. Well, deleted again.


<!-- Sent from Reviewable.io -->

2023-10-17 11:54 UTC, buggmagnet approved these changes
> Reviewed 1 of 10 files at r10, 6 of 8 files at r17.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794)* status: 42 of 44 files reviewed, 4 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/View controllers/RelayFilter/RelayFilterDataSource.swift` line 297 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NgwULaL6zzRAGgISziJ:-NgxSZS65AipAjRgNqcW:b4zutcl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb69f11060442f24f94126dece0f9d535c13ca1f/ios/MullvadVPN/View%20controllers/RelayFilter/RelayFilterDataSource.swift#L297)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It's not optional.
</blockquote></details>

Indeed ! 


<!-- Sent from Reviewable.io -->

2023-10-17 12:18 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> It feels really nice to be able to finally merge this !

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-:-NgxZbRw2f5rcL9Rc5Wy:b-l99k4e)* status: 42 of 44 files reviewed, 1 unresolved discussion (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-10-17 12:21 UTC, merged