Print the old account number even if device is revoked
mullvad/mullvadvpn-app pull request #4800
Opened 2023-06-19 09:00 UTC by MarkusPettersson98

`mullvad account get` will now print the old account number, even when the device has revoked. A minor QOL thing for the CLI users out there.

Previously:
```
$ mullvad account get
The current device has been revoked
```
Now:
```
$ mullvad account get
The current device has been revoked
Mullvad account: xxxxxxxxxxxxxxxx
```

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4800)

2023-06-20 12:15 UTC, Jontified requested changes
This should be added to the changelog!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4800#-:-NYNioGP9eClhDdme86C:b-vgt0oc)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-20 13:10 UTC, MarkusPettersson98 reviewed
Done!

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4800#-:-NYNvTSBBPuF9QnDFMPR:b-896fja)* status: 1 of 2 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-21 07:27 UTC, Jontified approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4800#-:-NYRqZZqD6tD2SMmzxC5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-21 11:13 UTC, merged

2023-06-21 11:13 UTC, Jontified approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4800)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->