update-handling-of-device-concept-and-time-left-ios-198
mullvad/mullvadvpn-app pull request #4803
Opened 2023-06-19 15:00 UTC by mojganii

after discussion design, we are supposed to change the priority of notifications based on these orders : 

1. tunnel status notification (highest priority)
2. close to expiry date  system notification
3. close to expiry date  in-app notification
4. creation device in app notification

changing these orders raised up another problem. currently in the app we don't show the device name and time left when the `new device created`  in-app banner notification is shown.therefore when user comes from logged out to logged and if the  `time left` is less than 3 days, `close to expiry date`  in-app notification shows while the `new device created` is below that and user is not able to figure out the `device name` till adding more credit to dismiss `close to expiry date`  in-app notification.

for solving the problem, the decision is made to show device name when user is logged in and show `time left` when user has credit more than 3 days.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4803)

2023-06-20 11:25 UTC, pronebird requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4803)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Containers/Root/HeaderBarView.swift` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4803#-NYNQWa_D-cZ_B_PdP5w:-NYNQWa_D-cZ_B_PdP5x:b-xnhtuz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3e6704718899e6b0e530fcaf26375def88c49a6a/ios/MullvadVPN/Containers/Root/HeaderBarView.swift#L183)):*
> ```Swift
>     }
> 
>     private func update(name: String?) {
> ```

We have three functions called `update()` which is sub-optimal. 

You could improve this by declaring properties just like you did for `isAccountButtonHidden`, i.e 

```swifft
var deviceName: String? {
   didSet {
        // update UI
   }
}
var accountExpiry: Date? {
   didSet {
        // update UI
   }
}
```

`deviceName` is already defined as `UILabel` and can be renamed to `deviceNameLabel` to solve the name clash.
___
*[`ios/MullvadVPN/Containers/Root/HeaderBarView.swift` line 221 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4803#-NYNPSe98MTm-CLcLaJ8:-NYNPSe98MTm-CLcLaJ9:b-gtg51r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3e6704718899e6b0e530fcaf26375def88c49a6a/ios/MullvadVPN/Containers/Root/HeaderBarView.swift#L221)):*
> ```Swift
> }
> 
> extension HeaderBarView {
> ```

Extension can be removed and `update(configuration:)` could re-join class definition. Especially because `update(name:)` and `update(expiry:)` and `isAccountButtonHidden` are already a part of the class definition. 
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 260 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4803#-NYNUjLk5Xy5woWLyV3W:-NYNUjLk5Xy5woWLyV3X:b-1fd3xq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3e6704718899e6b0e530fcaf26375def88c49a6a/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L260)):*
> ```Swift
>     // MARK: - Private
> 
>     private var isPresentingAccountExpiryBanner = false
> ```

What if we move `deviceState` and this flag into a model that would help us produce the root configuration reliably and consistently? For example:

```swift
struct DeviceBarState {
   var isPresentingAccountExpiryBanner: Bool
   var deviceState: DeviceState
}

extension DeviceBarState {
    var rootConfiguration: RootConfiguration {
            // I haven't looked too closely at this code so maybe it's not functional
            return RootConfiguration(
                deviceName: deviceState.deviceData?.capitalizedName,
                expiry: (isPresentingAccountExpiryBanner || deviceState.accountData?.isExpired ?? false)
                    ? nil
                    : deviceState.accountData?.expiry,
                showsAccountButton: deviceState.isLoggedIn
            )
    }
}
```


<!-- Sent from Reviewable.io -->

2023-06-20 11:45 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4803)* status: all files reviewed, 3 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/Containers/Root/HeaderBarView.swift` line 183 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4803#-NYNQWa_D-cZ_B_PdP5w:-NYNaWl3-fbdjhlUi2TO:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3e6704718899e6b0e530fcaf26375def88c49a6a/ios/MullvadVPN/Containers/Root/HeaderBarView.swift#L183)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

We have three functions called `update()` which is sub-optimal. 

You could improve this by declaring properties just like you did for `isAccountButtonHidden`, i.e 

```swifft
var deviceName: String? {
   didSet {
        // update UI
   }
}
var accountExpiry: Date? {
   didSet {
        // update UI
   }
}
```

`deviceName` is already defined as `UILabel` and can be renamed to `deviceNameLabel` to solve the name clash.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Containers/Root/HeaderBarView.swift` line 221 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4803#-NYNPSe98MTm-CLcLaJ8:-NYNaem330TRUFQFpmo9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3e6704718899e6b0e530fcaf26375def88c49a6a/ios/MullvadVPN/Containers/Root/HeaderBarView.swift#L221)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Extension can be removed and `update(configuration:)` could re-join class definition. Especially because `update(name:)` and `update(expiry:)` and `isAccountButtonHidden` are already a part of the class definition. 
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 260 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4803#-NYNUjLk5Xy5woWLyV3W:-NYNb-7n5tr2-oShVWMi:bd7p6s6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3e6704718899e6b0e530fcaf26375def88c49a6a/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L260)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

What if we move `deviceState` and this flag into a model that would help us produce the root configuration reliably and consistently? For example:

```swift
struct DeviceBarState {
   var isPresentingAccountExpiryBanner: Bool
   var deviceState: DeviceState
}

extension DeviceBarState {
    var rootConfiguration: RootConfiguration {
            // I haven't looked too closely at this code so maybe it's not functional
            return RootConfiguration(
                deviceName: deviceState.deviceData?.capitalizedName,
                expiry: (isPresentingAccountExpiryBanner || deviceState.accountData?.isExpired ?? false)
                    ? nil
                    : deviceState.accountData?.expiry,
                showsAccountButton: deviceState.isLoggedIn
            )
    }
}
```
</blockquote></details>

I thought about this approach.but after careful consideration I came up to the solution I've done.that's why considering a model(struct) to get configuration maybe is not a good solution.


<!-- Sent from Reviewable.io -->

2023-06-22 09:09 UTC, rablador reviewed
> Reviewed 1 of 5 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4803)* status: all files reviewed, 5 unresolved discussions (waiting on @mojganii and @pronebird)



<!-- Sent from Reviewable.io -->

2023-06-22 13:15 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4803)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Containers/Root/HeaderBarView.swift` line 125 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4803#-NYSzPoR5qSkltRhtxFd:-NYYB1Yi8G2zw3lyo86i:b-nodt80) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/be01ab2b5972d0819c6d2828fcbdb2996aa143ed/ios/MullvadVPN/Containers/Root/HeaderBarView.swift#L125)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit: please replace the direct call to `.init` to `String(`
</blockquote></details>

done.It takes time to get accustomed 
___
*[`ios/MullvadVPN/Containers/Root/HeaderBarView.swift` line 149 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4803#-NYSzbNzC7fAfhYrcIG6:-NYYB7poEuhavTVD7NKs:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/be01ab2b5972d0819c6d2828fcbdb2996aa143ed/ios/MullvadVPN/Containers/Root/HeaderBarView.swift#L149)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit: Same as L125
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-06-26 07:02 UTC, pronebird reviewed
> Reviewed 4 of 4 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4803)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2023-06-26 09:52 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4803#-:-NYr6Uc4-X1h21AkgcNe:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-06-26 14:35 UTC, pronebird approved these changes

2023-06-26 14:43 UTC, merged