Join `set location` and `set hostname` into one command
mullvad/mullvadvpn-app pull request #4804
Opened 2023-06-20 08:13 UTC by MarkusPettersson98

This PR merges the functionallity of `mullvad relay set hostname` into the `mullvad relay set location` command.

The `relay set location` command used to require the full format of `<COUNTRY> <CITY> <HOSTNAME>` to select a specific relay, while `relay set hostname`  only received a hostname and figured the country and city out. 

Now, the arguments to `relay set location` are *either* a geographical location or a hostname: `relay set location <COUNTRY> <CITY> <HOSTNAME> | <HOSTNAME>` . The command will keep working as it used to, while being a bit smarter about hostnames.

E.g., here I select one of the relays in Gothenburg:
```bash
$ mullvad relay set location se-got-wg-004
Relay constraints updated

$ mullvad status
Connected to se-got-wg-004 in Gothenburg, Sweden
```

This logic also applies to the multihop option, so one can specify a relay as an entry point directly by its hostname.
E.g., here I select another one of the relays in Gothenburg as entry point:

```bash
$ mullvad relay set tunnel wireguard --use-multihop on entry-location se-got-wg-101
Relay constraints updated

$ mullvad status
Connected to se-got-wg-004 in Gothenburg, Sweden via se-got-wg-101
```

The help messages for both `mullvad relay set location` and `mullvad relay set tunnel wireguard` has been augmented with examples to clarify how the commands can be used.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4804)

2023-06-20 12:38 UTC, Jontified requested changes
Update changelog and test that everything works as it should if you haven't already.
I think this change should probably also be applied to bridges since it's basically the same thing.
`mullvad bridge set location`

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4804#-:-NYNkYAC2cJc8hfbew2E:b3xln3e)* status: all files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-cli/src/cmds/relay.rs` line 433 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4804#-NYNmmeS6P5qAGmhiVNR:-NYNmmeS6P5qAGmhiVNS:b-fjm2an) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70768f0f6ad3868caf5b64fbaf01e4e5c650973b/mullvad-cli/src/cmds/relay.rs#L433)):*
> ```XML
>         let countries = Self::get_filtered_relays().await?;
>         let constraint = if let Some(location_constraint) =
>             find_relay_by_hostname(&countries, &location_constraint_args.country)
> ```

I think adding a small comment that we're not actually passing the country here but instead optimistically assuming the hostname exists in the country field is warranted, otherwise it's pretty confusing.
___
*[`mullvad-cli/src/cmds/relay.rs` line 546 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4804#-NYNnMvp6C8YtPpiouY6:-NYNnMvp6C8YtPpiouY7:b-175yy6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70768f0f6ad3868caf5b64fbaf01e4e5c650973b/mullvad-cli/src/cmds/relay.rs#L546)):*
> ```XML
>             let countries = Self::get_filtered_relays().await?;
>             wireguard_constraints.entry_location = if let Some(location_constraint) =
>                 find_relay_by_hostname(&countries, &entry.country)
> ```

I guess it would be nice to have a similar comment as the one above mentioned here. It's almost warranted to change the field name imo, but perhaps that's not necessary. I think the comment should be really short, something like:
`// country field might contain the hostname here`
___
*[`mullvad-cli/src/cmds/relay.rs` line 618 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4804#-NYNmH-n59FD5WbuJlMC:-NYNmH-n59FD5WbuJlMD:b-asq2h1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70768f0f6ad3868caf5b64fbaf01e4e5c650973b/mullvad-cli/src/cmds/relay.rs#L618)):*
> ```XML
>         .flat_map(|country| country.cities.clone())
>         .flat_map(|city| city.relays)
>         .find(|relay| relay.hostname == hostname)
> ```

Use `to_lowercase()` on both hostnames here to avoid any problem with capitalization.


<!-- Sent from Reviewable.io -->

2023-06-20 14:41 UTC, MarkusPettersson98 reviewed
Done!

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4804#-:-NYOFI0DCLoiRGQ7j7xR:b-896fja)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @Jontified)

___
*[`mullvad-cli/src/cmds/relay.rs` line 433 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4804#-NYNmmeS6P5qAGmhiVNR:-NYOFA0h7GOq68KR6-Gw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70768f0f6ad3868caf5b64fbaf01e4e5c650973b/mullvad-cli/src/cmds/relay.rs#L433)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

I think adding a small comment that we're not actually passing the country here but instead optimistically assuming the hostname exists in the country field is warranted, otherwise it's pretty confusing.
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/relay.rs` line 546 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4804#-NYNnMvp6C8YtPpiouY6:-NYOF9SS760MKt5sXP01:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70768f0f6ad3868caf5b64fbaf01e4e5c650973b/mullvad-cli/src/cmds/relay.rs#L546)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

I guess it would be nice to have a similar comment as the one above mentioned here. It's almost warranted to change the field name imo, but perhaps that's not necessary. I think the comment should be really short, something like:
`// country field might contain the hostname here`
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/relay.rs` line 618 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4804#-NYNmH-n59FD5WbuJlMC:-NYNxwiW0LlUWZ_UXaLZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70768f0f6ad3868caf5b64fbaf01e4e5c650973b/mullvad-cli/src/cmds/relay.rs#L618)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Use `to_lowercase()` on both hostnames here to avoid any problem with capitalization.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-20 14:52 UTC, Jontified requested changes
> Reviewed 1 of 2 files at r4, 3 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4804)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`mullvad-cli/src/cmds/bridge.rs` line 48 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4804#-NYOH1SO1QIo9NGvIohX:-NYOH1SO1QIo9NGvIohY:b-u45snn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/739a06ac002e4f7b1b3fa694f46847e9ee09b76c/mullvad-cli/src/cmds/bridge.rs#L48)):*
> ```XML
>   Select bridge using a country, city and hostname:
> 
> \tmullvad bridge set location se got se-got-wg-004
> ```

Example should probably use an openVPN bridge rather than a `wg` relay.


<!-- Sent from Reviewable.io -->

2023-06-21 11:22 UTC, Jontified approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4804)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-06-21 11:45 UTC, merged