Rework change log to be compliant with our design
mullvad/mullvadvpn-app pull request #4821
Opened 2023-06-22 14:48 UTC by rablador

Our current changelog differs greatly from what we have on other platforms - instead, it should be the same as other platforms.

This PR reuses CustomAlertViewController for showing changelogs.

2023-06-22 15:30 UTC, pronebird requested changes
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYYhpD2D0runV7S7gH_:-NYYhpD2D0runV7S7gHa:b-9jbpdk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L47)):*
> ```Swift
>     var didDismiss: (() -> Void)?
> 
>     let containerView: UIStackView = {
> ```

Did you make it `internal` it by mistake?


<!-- Sent from Reviewable.io -->

2023-06-26 07:07 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYqW1GK06WeH21gY08k:-NYqW1GK06WeH21gY08l:b-jh3rul) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L14)):*
> ```Swift
> final class ChangeLogCoordinator: Coordinator {
>     private let logger = Logger(label: "ChangeLogCoordinator")
>     private let alertPresenter = AlertPresenter()
> ```

Maybe AlertPresenter does something else besides just queuing up VC for presentation, but wouldn't making this coordinator `Presentable` result in a more lightweight way to handle this?


<!-- Sent from Reviewable.io -->

2023-06-26 07:07 UTC, pronebird reviewed
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-06-26 11:04 UTC, buggmagnet requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: all files reviewed, 5 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYr7ct77zOGco3EYny0:-NYr7ct8BOkGXMJBoKGr:b-3zz2q6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L82)):*
> ```Swift
>     }
> 
>     private func setUp(title: String?, icon: Icon?, addMessageCallback: () -> Void) {
> ```

I'm guessing it was not possible to do otherwise, but I think we're running on thin ice here.
We run this before `viewDidLoad` so any implicit (or accidental) calls to `self.view` would trigger `loadView` and `viewDidLoad` in turn which will have unexpected effect.

Can we acknowledge this here and add a comment that says something along the lines of "This code runs before `viewDidLoad` do not do implicit calls to `self.view`" ?
___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 162 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYr8VN2E9hMQkp3nH5d:-NYr8VN2E9hMQkp3nH5e:bz6sz9s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L162)):*
> ```Swift
>         label.attributedText = NSAttributedString(
>             markdownString: message,
>             options: .init(font: font, paragraphStyle: style)
> ```

Suggestion
Remove `MarkdownStylingOptions` from the `NSAttributedString` extension so we can have the following instead.
```swift
options: MarkdownStylingOptions(font: font, paragraphStyle: style)
```
That avoids the call to `.init` and it adds visual noise to have `MarkdownStylingOptions` in an extension rather than as a standalone type.
___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYrMKoaAVMVFr8zxlRg:-NYrMKob76C43l_eWehH:b49iujw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L18)):*
> ```Swift
>     let navigationController: RootContainerViewController
> 
>     var didFinish: ((ChangeLogCoordinator) -> Void)?
> ```

This doesn't seem to be used anywhere, can we delete it ?
___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYr9wGT7NSdEs1Bpje-:-NYr9wGT7NSdEs1Bpje0:b-gktdlj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L58)):*
> ```Swift
>     }
> 
>     private func getChangeLogText() -> NSAttributedString? {
> ```

nit:  `changeLogText` is plenty enough 


<!-- Sent from Reviewable.io -->

2023-06-26 14:01 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: all files reviewed, 6 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 105 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYs-WND6xXuARvKfvk1:-NYs-WND6xXuARvKfvk2:bmh6lx6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L105)):*
> ```Swift
>         view.backgroundColor = .black.withAlphaComponent(0.5)
> 
>         let containerViewWidthConstraint = containerView.widthAnchor
> ```

We have `func withPriority(_ priority: UILayoutPriority) -> Self` extension on `NSLayoutConstraint`.


<!-- Sent from Reviewable.io -->

2023-06-26 14:05 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: all files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 162 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYr8VN2E9hMQkp3nH5d:-NYs-wY0CDdGAR8Nqzvv:b-wqxpl3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L162)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Suggestion
Remove `MarkdownStylingOptions` from the `NSAttributedString` extension so we can have the following instead.
```swift
options: MarkdownStylingOptions(font: font, paragraphStyle: style)
```
That avoids the call to `.init` and it adds visual noise to have `MarkdownStylingOptions` in an extension rather than as a standalone type.

</blockquote></details>

Although it was done in sympathy with standard `AttributedString.MarkdownParsingOptions`, I agree that those calls to `.init()` make it nearly impossible to guess the underlying type.


<!-- Sent from Reviewable.io -->

2023-06-29 19:51 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: all files reviewed, 6 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYYhpD2D0runV7S7gH_:-NZ7WobwBG65hJLHNyJa:br2jotc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L47)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Did you make it `internal` it by mistake?
</blockquote></details>

No, it's referenced in an extension in `ChangeLogCoordinator`.
___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYr7ct77zOGco3EYny0:-NZ7XKPsAu4vNqebx79V:b-wzas9g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L82)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I'm guessing it was not possible to do otherwise, but I think we're running on thin ice here.
We run this before `viewDidLoad` so any implicit (or accidental) calls to `self.view` would trigger `loadView` and `viewDidLoad` in turn which will have unexpected effect.

Can we acknowledge this here and add a comment that says something along the lines of "This code runs before `viewDidLoad` do not do implicit calls to `self.view`" ?
</blockquote></details>

Will this ever be a problem? The setup is only an extension of the init, which requires certain things passed as params. AFAIK the setup function will never be run after view load.
___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 105 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYs-WND6xXuARvKfvk1:-NZ7YkbDApJE3aCoq88f:bzftu3a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L105)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

We have `func withPriority(_ priority: UILayoutPriority) -> Self` extension on `NSLayoutConstraint`.
</blockquote></details>

Sweet!
___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 162 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYr8VN2E9hMQkp3nH5d:-NZ7_nJO9CN5Ue29YaJd:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L162)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Although it was done in sympathy with standard `AttributedString.MarkdownParsingOptions`, I agree that those calls to `.init()` make it nearly impossible to guess the underlying type.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYqW1GK06WeH21gY08k:-NZ7apnqEN5_-UNtB5KP:b4h1g3f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L14)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe AlertPresenter does something else besides just queuing up VC for presentation, but wouldn't making this coordinator `Presentable` result in a more lightweight way to handle this?
</blockquote></details>

Yeah, I guess I mixed up the intention of the custom alert controller with a "regular" alert. Those are all presented with an AlertPresenter, but I don't think it's necessary here.
___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYrMKoaAVMVFr8zxlRg:-NZ7aFuPB64ulLkugDkk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L18)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This doesn't seem to be used anywhere, can we delete it ?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYr9wGT7NSdEs1Bpje-:-NZ7f6F46ZHqdylqeyHm:b-r0e453) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L58)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit:  `changeLogText` is plenty enough 
</blockquote></details>

See https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYqdUOp0NOK9VwoLIjg.
@mojganii @pronebird, please chip in.


<!-- Sent from Reviewable.io -->

2023-07-03 08:56 UTC, buggmagnet approved these changes
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: all files reviewed, 5 unresolved discussions (waiting on @mojganii, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYr7ct77zOGco3EYny0:-NZPwRDI6YsaUpFqf3i1:bdrdz7q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L82)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Will this ever be a problem? The setup is only an extension of the init, which requires certain things passed as params. AFAIK the setup function will never be run after view load.
</blockquote></details>

Not necessarily, I'm just concerned about future ourselves needing to do a quick fix and not realizing immediately if something's up. 


<!-- Sent from Reviewable.io -->

2023-07-03 09:17 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 111 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NZPykfC6nBTdjWF104m:-NZPykfC6nBTdjWF104n:blbeiy9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/225712fded30ba3f12df31816052e6ad1640e873/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L111)):*
> ```Swift
>             containerView.widthAnchor
>                 .constraint(lessThanOrEqualToConstant: UIMetrics.preferredFormSheetContentSize.width)
>                 .withPriority(.required)
> ```

nit: as far as I know `default priority` for UIKit constraint is required and there is no need to be set
___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYr9wGT7NSdEs1Bpje-:-NZQ1Gs29m7xYSR9Tu5_:bh4ntl1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L58)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

See https://reviewable.io/reviews/mullvad/mullvadvpn-app/4794#-NYqdUOp0NOK9VwoLIjg.
@mojganii @pronebird, please chip in.
</blockquote></details>

if consider that property it can be `changeLogText` otherwise with function definition `getChangeLogText` is better option 
___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NZQ0EOq4YMDIsnUyKsC:-NZQ0EOq4YMDIsnUyKsD:bpnb2j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/225712fded30ba3f12df31816052e6ad1640e873/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L41)):*
> ```Swift
>         )
> 
>         alertController.addVersionHeader()
> ```

What's not it better to consider `title` with `NSAttributedString` and overloading initialiser for that instead of using hacking way to add label version?


<!-- Sent from Reviewable.io -->

2023-07-03 11:31 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: all files reviewed, 6 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYr7ct77zOGco3EYny0:-NZQSuvZ3MH-EbxWZOZo:b-q74j0m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L82)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Not necessarily, I'm just concerned about future ourselves needing to do a quick fix and not realizing immediately if something's up. 
</blockquote></details>

Ok, I'll add a comment.
___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 111 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NZPykfC6nBTdjWF104m:-NZQT-906Velg39ibpfG:bo6ap9z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/225712fded30ba3f12df31816052e6ad1640e873/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L111)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit: as far as I know `default priority` for UIKit constraint is required and there is no need to be set
</blockquote></details>

Indeed!
___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NYr9wGT7NSdEs1Bpje-:-NZQUPhW7_h_L8DtgzP3:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb42af072809905ce2ca5ad0e3435e77db70dd7d/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L58)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

if consider that property it can be `changeLogText` otherwise with function definition `getChangeLogText` is better option 
</blockquote></details>

Done
___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NZQ0EOq4YMDIsnUyKsC:-NZQVZI550F2--BYU-yi:bsmdgrf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/225712fded30ba3f12df31816052e6ad1640e873/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L41)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

What's not it better to consider `title` with `NSAttributedString` and overloading initialiser for that instead of using hacking way to add label version?
</blockquote></details>

Do you mean a header and title in the same attributed string? Or do you mean that the alert view controller should have another init with header as param?

The reason I added version header like this (with a small hack) is that alerts usually have a uniform look, except for the change log. The change log is not really an alert controller per se, but it shares almost all behavior and visuals.


<!-- Sent from Reviewable.io -->

2023-07-03 12:27 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: 10 of 12 files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NZQ0EOq4YMDIsnUyKsC:-NZQhGah2s_yf5wMtrM8:bk8ikrd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/225712fded30ba3f12df31816052e6ad1640e873/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L41)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Do you mean a header and title in the same attributed string? Or do you mean that the alert view controller should have another init with header as param?

The reason I added version header like this (with a small hack) is that alerts usually have a uniform look, except for the change log. The change log is not really an alert controller per se, but it shares almost all behavior and visuals.
</blockquote></details>

I meant to consider title and body properties  `NSAttributedString`.but the second option you've mentioned seems reasonabl to me.
header, title and body...


<!-- Sent from Reviewable.io -->

2023-07-05 12:40 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: 10 of 12 files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NZQ0EOq4YMDIsnUyKsC:-NZa2yFbDcvcWzdpiQx9:bc2s3ey) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/225712fded30ba3f12df31816052e6ad1640e873/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L41)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I meant to consider title and body properties  `NSAttributedString`.but the second option you've mentioned seems reasonabl to me.
header, title and body...
</blockquote></details>

I think the question here is if we want a permanently available header in the custom alert view controller or if the one in the change log is a one-shot solution.


<!-- Sent from Reviewable.io -->

2023-07-05 12:44 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: 10 of 12 files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NZQ0EOq4YMDIsnUyKsC:-NZa3jiU-I_EJzq4soik:by3ufzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/225712fded30ba3f12df31816052e6ad1640e873/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L41)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I think the question here is if we want a permanently available header in the custom alert view controller or if the one in the change log is a one-shot solution.
</blockquote></details>

I should mention that the title in the change log has slightly different margins compared to regular alerts as well, hence this code snippet:

``` 
if let title = containerView.arrangedSubviews.first {
    containerView.setCustomSpacing(8, after: title)
}
```


<!-- Sent from Reviewable.io -->

2023-07-05 13:04 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: 5 of 12 files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NZQ0EOq4YMDIsnUyKsC:-NZa8oL--RhyfYh3U7Sq:bad1mf6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/225712fded30ba3f12df31816052e6ad1640e873/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L41)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I should mention that the title in the change log has slightly different margins compared to regular alerts as well, hence this code snippet:

``` 
if let title = containerView.arrangedSubviews.first {
    containerView.setCustomSpacing(8, after: title)
}
```
</blockquote></details>

In any case, made a change, please look at it :)


<!-- Sent from Reviewable.io -->

2023-07-06 07:06 UTC, buggmagnet approved these changes
Still 
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-:-NZe0Vcu2atlMo66wXA-:bze9599)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii and @pronebird)



<!-- Sent from Reviewable.io -->

2023-07-06 11:30 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: all files reviewed, 3 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 82 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NZew8ZY6nQowoYCdRyZ:-NZew8ZY6nQowoYCdRy_:b-bq3m67) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81d8ad7f85296b2bb34c0d88b083cddcf3a19369/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L82)):*
> ```Swift
>     }
> 
>     required init?(coder: NSCoder) {
> ```

it's better to block creation custom alert controller via user interface when we are going to make of it trough code.


<!-- Sent from Reviewable.io -->

2023-07-07 09:11 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii and @pronebird)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 82 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NZew8ZY6nQowoYCdRyZ:-NZjbnB2CLouwL7D5vTc:b-76bhbv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81d8ad7f85296b2bb34c0d88b083cddcf3a19369/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L82)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it's better to block creation custom alert controller via user interface when we are going to make of it trough code.
</blockquote></details>

How could that be done?


<!-- Sent from Reviewable.io -->

2023-07-31 08:24 UTC, mojganii approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: all files reviewed, 4 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 82 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NZew8ZY6nQowoYCdRyZ:-Naf-EEM-aXYEv9X9sxr:b-wm705j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/81d8ad7f85296b2bb34c0d88b083cddcf3a19369/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L82)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

How could that be done?
</blockquote></details>

nit :just revert this part.having coder initializer with `assert` is enough.
___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 137 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-Naf0qPEBezB0Ytw-qck:-Naf0qPEBezB0Ytw-qcl:b-wuv06x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36bc711658466fc6644c663dc6d24357164f5a5a/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L137)):*
> ```Swift
>     }
> 
>     func addHeader(_ title: String) {
> ```

nit :should it be accessible after making an instance from the object while others functions are private? 


<!-- Sent from Reviewable.io -->

2023-08-03 09:27 UTC, pronebird requested changes
> Reviewed 2 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 12 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-Naui0YMD7bmeCl0vcOi:-Naui0YMD7bmeCl0vcOj:bjj0fng) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36bc711658466fc6644c663dc6d24357164f5a5a/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L12)):*
> ```Swift
> import UIKit
> 
> final class ChangeLogCoordinator: Coordinator, Presentable {
> ```

It does not have to be `Presentable` because `start()` presents custom alert manually. `Presentable` itself makes it possible to leverage coordinator facilities for modal presentation.


<!-- Sent from Reviewable.io -->

2023-08-03 09:29 UTC, pronebird reviewed
> Reviewed 2 of 7 files at r1, 3 of 9 files at r2, 4 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-08-03 09:37 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 482 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NaujFHj2tPFRjEgh11W:-NaujFHj2tPFRjEgh11X:b2xsay9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36bc711658466fc6644c663dc6d24357164f5a5a/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L482)):*
> ```Swift
>         coordinator.start(animated: false)
> 
>         beginHorizontalFlow(animated: false) { [weak self] in
> ```

This part is a bit confusing to me. We used to present change log inside of horizontal flow controller. But changelog became an alert which is being presented modally above horizontal flow controller. It seems that we need to change the way things work here.


<!-- Sent from Reviewable.io -->

2023-08-04 12:58 UTC, buggmagnet requested changes
Not sure why for now, but on iPad the changelog doesn't appear at all, it looks like there's an animation that flashes the screen, however the changelog disappears immediately

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-:-Nb-c0Cs-tXdEyHURfdb:bj77biq)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 482 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-NaujFHj2tPFRjEgh11W:-Nb-aReL1U7gxgnVviMR:bfrf8ul) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36bc711658466fc6644c663dc6d24357164f5a5a/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L482)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This part is a bit confusing to me. We used to present change log inside of horizontal flow controller. But changelog became an alert which is being presented modally above horizontal flow controller. It seems that we need to change the way things work here.
</blockquote></details>

This is consistent with the requirements design in zeplin. Let's discuss this offline


<!-- Sent from Reviewable.io -->

2023-08-07 09:12 UTC, rablador reviewed
Added fix for changelog not showing on iPad. Not sure it's the correct way, but it works as intended on both platforms now.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-:-NbEG51aBUpAjszvGX-K:bitysu8)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/Classes/CustomAlertViewController.swift` line 137 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-Naf0qPEBezB0Ytw-qck:-NbDvD772sxQlSo69fhw:b-8imvvj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36bc711658466fc6644c663dc6d24357164f5a5a/ios/MullvadVPN/Classes/CustomAlertViewController.swift#L137)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit :should it be accessible after making an instance from the object while others functions are private? 
</blockquote></details>

No, changed it to private again.
___
*[`ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift` line 12 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-Naui0YMD7bmeCl0vcOi:-NbDwROU7korNJEqRaDD:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36bc711658466fc6644c663dc6d24357164f5a5a/ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift#L12)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

It does not have to be `Presentable` because `start()` presents custom alert manually. `Presentable` itself makes it possible to leverage coordinator facilities for modal presentation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-10 09:20 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4821#-:-NbTjrt-DhakMcem4uxQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-08-10 09:22 UTC, merged