Update relay selector docs to include udp2tcp
mullvad/mullvadvpn-app pull request #4834
Opened 2023-06-27 11:06 UTC by pinkisemils

The relay selector docs didn't have a notion of an obfuscator, so I updated them.

I also found that a public method in the relay selector module was used solely in tests, so I made it private and only compiled for tests.

2023-06-27 12:42 UTC, dlon reviewed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834)* status: all files reviewed, 4 unresolved discussions (waiting on @pinkisemils)

___
*[`docs/relay-selector.md` line 9 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834#-NYwr1b7EJXi2utWsnYx:-NYwr1b7EJXi2utWsnYy:b-79iwpm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70c833c693d02bb6bf467a34db158c2dd28b1980/docs/relay-selector.md#L9)):*
> ```Markdown
> - Transport protocol - TCP or UDP
> - Tunnel protocol - WireGuard or OpenVPN
> - Obfuscator - a service that obfuscates WireGuard traffic, often running on the same WireGuard
> ```

Would it not be more useful to define "obfuscation" here?
___
*[`docs/relay-selector.md` line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834#-NYwop-n1BcMPbJELEiz:-NYwop-n1BcMPbJELEj-:b-icwvm5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70c833c693d02bb6bf467a34db158c2dd28b1980/docs/relay-selector.md#L59)):*
Maybe transport protocol should not even mentioned here? That's a OpenVPN-specific constraint, so the fact that it's not applicable goes without saying, in my opinion.

> without any other protocol constraints

Are there any such constraints?
___
*[`docs/relay-selector.md` line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834#-NYwqjDS-CGaLNUYLWn2:-NYwqjDS-CGaLNUYLWn3:buisxfv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70c833c693d02bb6bf467a34db158c2dd28b1980/docs/relay-selector.md#L59)):*
> ```Markdown
> 
> - If the tunnel protocol is specified as WireGuard without any other protocol
>   constraints and obfuscator mode is set to _auto_, then the transport protocol
> ```

We should probably call it "obfuscation mode", not "obfuscator mode". That's what we usually call it.
___
*[`mullvad-relay-selector/src/lib.rs` line 872 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834#-NYwoB_rD_B8GXtLfvWd:-NYwoB_s5UGD6BbZovS3:bhxuuun) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70c833c693d02bb6bf467a34db158c2dd28b1980/mullvad-relay-selector/src/lib.rs#L872)):*
> ```XML
>     }
> 
>     #[cfg(test)]
> ```

Could we move this into the `test` module?


<!-- Sent from Reviewable.io -->

2023-06-27 13:35 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[`mullvad-relay-selector/src/lib.rs` line 872 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834#-NYwoB_rD_B8GXtLfvWd:-NYx31MJE3HFBFWNusxf:b-9wovum) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70c833c693d02bb6bf467a34db158c2dd28b1980/mullvad-relay-selector/src/lib.rs#L872)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could we move this into the `test` module?
</blockquote></details>

Didn't know it was legal to have an impl block for a type defined in a parent module. Super cool!


<!-- Sent from Reviewable.io -->

2023-06-27 14:26 UTC, MrChocolatine commented on docs/relay-selector.md
> +  endpoints exist and any port will be matched. If obfuscation is set to auto:
For consistency.

```suggestion
  endpoints exist and any port will be matched. If obfuscation is set to _auto_:
```

2023-06-27 14:26 UTC, MrChocolatine commented on docs/relay-selector.md
> +be used.
```suggestion
Currently, there is only a single type of obfuscator - _udp2tcp_, and it's only used if its mode is
set to _On_ or _Auto_ and the user has selected WireGuard to be the only tunnel protocol to
be used.
```

2023-07-03 07:16 UTC, dlon requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834)* status: all files reviewed, 3 unresolved discussions (waiting on @pinkisemils)

___
*[`docs/relay-selector.md` line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834#-NYwop-n1BcMPbJELEiz:-NZParW7AB2CZvrbHIFk:b-1imeqa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70c833c693d02bb6bf467a34db158c2dd28b1980/docs/relay-selector.md#L59)):*
> any port will be matched

Not necessarily true.


<!-- Sent from Reviewable.io -->

2023-07-03 09:12 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834)* status: all files reviewed, 4 unresolved discussions (waiting on @pinkisemils)

___
*[`docs/relay-selector.md` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834#-NZPz_kw3fozf8Ips9yu:-NZPz_kw3fozf8Ips9yv:b-7xar89) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f6eba8c675748eb96880bb954299c477de5f1e0d/docs/relay-selector.md#L10)):*
I have mentioned this in the past. But this is not the correct description of obfuscation IMO. When we use shadowsocks towards bridges for tunneling OpenVPN traffic, that's also obfuscation. I think this description is better:

> Obfuscation - Putting WireGuard, OpenVPN or API traffic inside a protocol designed to make it harder to fingerprint or block the contained traffic. This is used to circumvent censorship. Mullvad hosts many different obfuscation protocols. Some are hosted directly on the VPN relays, but most are hosted on separate bridge servers. Even if most obfuscation protocols used include encryption, that encryption is not to be treated as secure. We only use the obfuscation protocol for its obfuscating properties, not for any security properties it might have.


<!-- Sent from Reviewable.io -->

2023-07-05 18:49 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dlon, @faern, and @MrChocolatine)

___
*[`docs/relay-selector.md` line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834#-NYwop-n1BcMPbJELEiz:-NZbLOeDDwNzxQlfxIN0:b-b07o27) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70c833c693d02bb6bf467a34db158c2dd28b1980/docs/relay-selector.md#L59)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

> any port will be matched

Not necessarily true.
</blockquote></details>

There are no other relevant constraints, I've simplified this sentence now.
___
*[`docs/relay-selector.md` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834#-NZPz_kw3fozf8Ips9yu:-NZbM8IE8twhtxR9fBgB:b6g3t4c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f6eba8c675748eb96880bb954299c477de5f1e0d/docs/relay-selector.md#L10)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I have mentioned this in the past. But this is not the correct description of obfuscation IMO. When we use shadowsocks towards bridges for tunneling OpenVPN traffic, that's also obfuscation. I think this description is better:

> Obfuscation - Putting WireGuard, OpenVPN or API traffic inside a protocol designed to make it harder to fingerprint or block the contained traffic. This is used to circumvent censorship. Mullvad hosts many different obfuscation protocols. Some are hosted directly on the VPN relays, but most are hosted on separate bridge servers. Even if most obfuscation protocols used include encryption, that encryption is not to be treated as secure. We only use the obfuscation protocol for its obfuscating properties, not for any security properties it might have.
</blockquote></details>

This is a far better definition.
___
*[`docs/relay-selector.md` line 60 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834#gh-1243839967:-NZbLOIZEPoUHUhD6lWT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f6eba8c675748eb96880bb954299c477de5f1e0d/docs/relay-selector.md#L60)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

For consistency.

```suggestion
  endpoints exist and any port will be matched. If obfuscation is set to _auto_:
```
</blockquote></details>

Done.
___
*[`docs/relay-selector.md` line 123 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834#gh-1243844356:-NZbLNVG0VpfeBtDECnY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f6eba8c675748eb96880bb954299c477de5f1e0d/docs/relay-selector.md#L123)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

```suggestion
Currently, there is only a single type of obfuscator - _udp2tcp_, and it's only used if its mode is
set to _On_ or _Auto_ and the user has selected WireGuard to be the only tunnel protocol to
be used.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-05 19:17 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834)* status: all files reviewed, 3 unresolved discussions (waiting on @faern and @MrChocolatine)



<!-- Sent from Reviewable.io -->

2023-07-07 07:47 UTC, merged