Enable Shadowsocks bridges selection via RelaySelector
mullvad/mullvadvpn-app pull request #4856
Opened 2023-06-29 14:53 UTC by buggmagnet

This PR introduces the ability for `RelaySelector` to select a Shadowsocks bridge that is filtered using the User's prefered relay chosen via the UI.

Due to how we propagate `relayConstraints` in the application, as long as the users do not choose a relay, a Shadowsocks bridge close to Sweden will be chosen by default.

I tried to implement filtering by Haversine distance (as the desktop clients do) but I decided to do that in a future work instead as to keep the PR impact minimal for `RelaySelector` 

How to test ?

This will only affect Shadowsocks bridges, so it's not immediately obvious how to test this. 
I would recommend forcing Shadowsocks transports to be used by default (set the `connectionAttempts` to `1` in `TransportStrategy`) and then select a Relay.

Due to how we cache the current Shadowsocks connection and selected endpoint at the moment, this is more likely to have an impact when the user experiences poor connectivity (more chances to switch transports in that case).

To that effect, you could disable the Shadowsocks caching for testing purposes and break on the selected relay to check whether it's close to what was chosen in the UI.

2023-06-30 06:14 UTC, pronebird requested changes
> Reviewed 5 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856)* status: 5 of 8 files reviewed, 6 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadREST/ServerRelaysResponse.swift` line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856#-NZ9qxcvBzLxyE3Hz5UC:-NZ9qxcvBzLxyE3Hz5UD:bpdugs0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/073ff6afae15ed838931999a95c7db7688e88e7d/ios/MullvadREST/ServerRelaysResponse.swift#L51)):*
> ```Swift
>         public let weight: UInt64
>         public let includeInCountry: Bool
>         // Unused, therefore not included in `CodingKeys`
> ```

 Please avoid using `Codbale` this way and adding unused fields into concrete types. 

Use generics and protocols instead if you need to filter by common properties of a group of structs while preserving concrete types, i.e:

```
protocol CommonType {
    var weight: UInt64 { get set }
}

struct TypeA: CommonType, Codable {
    var weight: UInt64
}

struct TypeB: CommonType, Codable {
    var weight: UInt64
}


func filter<T>(_ values: [T]) -> [T] where T: CommonType {
    return values.filter { s in
        return s.weight < 2
    }
}

let values: [TypeA] = [TypeA(weight: 1), TypeA(weight: 2)]
let filtered = filter(values)

```
___
*[`ios/MullvadTransport/TransportProvider.swift` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856#-NZ9pZcA4eFF2qjW23LR:-NZ9pZcA4eFF2qjW23LS:b4kxefu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/073ff6afae15ed838931999a95c7db7688e88e7d/ios/MullvadTransport/TransportProvider.swift#L26)):*
> ```Swift
>     private var currentTransport: RESTTransport?
>     private let parallelRequestsMutex = NSLock()
>     private var relayConstraints = RelayConstraints(location: .any)
> ```

This will lead to transport using `any` constraint until user changes location. This will happen on each run from what I understand. Default constraint we have is bound to Sweden. 

This code would not suffer this problem if you used a block to provide relay constraints `() -> RelayConstraints`.
___
*[`ios/MullvadTypes/RelayConstraints.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856#-NZ9oJgcEI5m6F2QJahT:-NZ9oJgcEI5m6F2QJahU:b-b68zxk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/073ff6afae15ed838931999a95c7db7688e88e7d/ios/MullvadTypes/RelayConstraints.swift#L15)):*
> ```Swift
> }
> 
> public class RelayConstraintsUpdater: ConstraintsPropagation {
> ```

This abstraction still looks foreign to me and should be replaced with `() -> RelayConstraints`. Keep it simple.
___
*[`ios/MullvadVPN/AppDelegate.swift` line 108 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856#-NZ9n0I_BjHVHHvnJV-S:-NZ9n0I_BjHVHHvnJV-T:b-3oir9l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/073ff6afae15ed838931999a95c7db7688e88e7d/ios/MullvadVPN/AppDelegate.swift#L108)):*
> ```Swift
>             addressCache: addressCache,
>             shadowsocksCache: shadowsocksCache,
>             constraintsUpdater: constraintsUpdater
> ```

Should be replaced with `() -> RelayConstraints`, i.e: 

```swift
constraintsProvider: { tunnelManager.settings.relayConstraints }
```
___
*[`ios/PacketTunnel/PacketTunnelProvider.swift` line 153 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856#-NZ9navB-6NQbOsD9SvO:-NZ9navB-6NQbOsD9SvP:b-kmbt7l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/073ff6afae15ed838931999a95c7db7688e88e7d/ios/PacketTunnel/PacketTunnelProvider.swift#L153)):*
> ```Swift
>             addressCache: addressCache,
>             shadowsocksCache: shadowsocksCache,
>             constraintsUpdater: constraintsUpdater
> ```

Could be replaced with or something along these lines:

```
constraintsProvider: {
  self.dispatchQueue.sync {
    // read and store it in makeConfiguration
    return self.relayConstraints
  }
}
```
___
*[`ios/RelaySelector/RelaySelector.swift` line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856#-NZ9lo1S8fWtOlAx2m0X:-NZ9lo1S8fWtOlAx2m0Y:blqsnm0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/073ff6afae15ed838931999a95c7db7688e88e7d/ios/RelaySelector/RelaySelector.swift#L82)):*
> ```Swift
>         return RelaySelectorResult(
>             endpoint: endpoint,
>             relay: relayWithLocation.relay as! REST.ServerRelay,
> ```

Force unwrap does not look right. Please use generics and/or protocols to negotiate the actual type with compiler.


<!-- Sent from Reviewable.io -->

2023-06-30 06:15 UTC, pronebird reviewed
> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856)* status: all files reviewed, 6 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2023-06-30 09:08 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/RelaySelector/RelaySelector.swift` line 210 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856#-NZAX-tv5wdIhZYhbQ7r:-NZAX-tv5wdIhZYhbQ7s:bw4u2lj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/073ff6afae15ed838931999a95c7db7688e88e7d/ios/RelaySelector/RelaySelector.swift#L210)):*
> ```Swift
>     }
> 
>     private static func mapRelayBridgesIn(_ response: REST.ServerRelaysResponse) -> [RelayWithLocation] {
> ```

You could merge two of those mapXXX functions into one, for example:


```swift
protocol AnyRelayProtocol {
    var hostname: String { get }
    var location: String { get }
    var weight: UInt64 { get }
    var active: Bool { get }
    var includeInCountry: Bool { get }
}

extension REST.ServerRelay: AnyRelayProtocol {}
extension REST.BridgeRelay: AnyRelayProtocol {}

private struct RelayWithLocation<T: AnyRelayProtocol> {
    let relay: T
    let location: Location
}
```

Then mapping each individual representation of either bridge or wg relay can be done using generic function:

```swift
private static func mapAnyRelay<T: AnyRelayProtocol>(
    relays: [T],
    locations: [String: REST.ServerLocation]
) -> [RelayWithLocation<T>] {
    relays.compactMap { relay in
        guard let serverLocation = locations[relay.location] else { return nil }
        return makeRelayWithLocationFrom(serverLocation, relay: relay)
    }
}

/* Can be called with:

let serverResponse: REST.ServerRelaysResponse = ...

// Bridges
mapAnyRelay(relays: serverResponse.bridge.relays, locations: serverResponse.locations)

// WG relays
mapAnyRelay(relays: serverResponse.wireguard.relays, locations: serverResponse.locations)

*/
```

Following the same example the rest of functions can be generic too and used interchangeably, i.e:

```swift
static func pickRandomRelay<T: AnyRelayProtocol>(relays: [RelayWithLocation<T>]) -> RelayWithLocation<T>?

static func makeRelayWithLocationFrom<T: AnyRelayProtocol>(
    _ serverLocation: REST.ServerLocation,
    relay: T
) -> RelayWithLocation<T>?

static func applyConstraints<T: AnyRelayProtocol>(
    _ constraints: RelayConstraints,
    relays: [RelayWithLocation<T>]
) -> [RelayWithLocation<T>]
```

For the most part only signature change is needed to make it work. This is the beauty of protocols/generics.


<!-- Sent from Reviewable.io -->

2023-06-30 09:25 UTC, pronebird submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/RelaySelector/RelaySelector.swift` line 210 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856#-NZAX-tv5wdIhZYhbQ7r:-NZAZNa-0SelmmfBcEIf:bhd8agc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/073ff6afae15ed838931999a95c7db7688e88e7d/ios/RelaySelector/RelaySelector.swift#L210)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You could merge two of those mapXXX functions into one, for example:


```swift
protocol AnyRelayProtocol {
    var hostname: String { get }
    var location: String { get }
    var weight: UInt64 { get }
    var active: Bool { get }
    var includeInCountry: Bool { get }
}

extension REST.ServerRelay: AnyRelayProtocol {}
extension REST.BridgeRelay: AnyRelayProtocol {}

private struct RelayWithLocation<T: AnyRelayProtocol> {
    let relay: T
    let location: Location
}
```

Then mapping each individual representation of either bridge or wg relay can be done using generic function:

```swift
private static func mapAnyRelay<T: AnyRelayProtocol>(
    relays: [T],
    locations: [String: REST.ServerLocation]
) -> [RelayWithLocation<T>] {
    relays.compactMap { relay in
        guard let serverLocation = locations[relay.location] else { return nil }
        return makeRelayWithLocationFrom(serverLocation, relay: relay)
    }
}

/* Can be called with:

let serverResponse: REST.ServerRelaysResponse = ...

// Bridges
mapAnyRelay(relays: serverResponse.bridge.relays, locations: serverResponse.locations)

// WG relays
mapAnyRelay(relays: serverResponse.wireguard.relays, locations: serverResponse.locations)

*/
```

Following the same example the rest of functions can be generic too and used interchangeably, i.e:

```swift
static func pickRandomRelay<T: AnyRelayProtocol>(relays: [RelayWithLocation<T>]) -> RelayWithLocation<T>?

static func makeRelayWithLocationFrom<T: AnyRelayProtocol>(
    _ serverLocation: REST.ServerLocation,
    relay: T
) -> RelayWithLocation<T>?

static func applyConstraints<T: AnyRelayProtocol>(
    _ constraints: RelayConstraints,
    relays: [RelayWithLocation<T>]
) -> [RelayWithLocation<T>]
```

For the most part only signature change is needed to make it work. This is the beauty of protocols/generics.
</blockquote></details>

Commit with the above changes: https://github.com/mullvad/mullvadvpn-app/commit/f44c79cbd8b4641cbbdd33a4c2e1e2755f3093df


<!-- Sent from Reviewable.io -->

2023-07-03 07:56 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856)* status: all files reviewed, 7 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadTransport/TransportProvider.swift` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856#-NZ9pZcA4eFF2qjW23LR:-NZPbl853PELee_vp-02:beyacys) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/073ff6afae15ed838931999a95c7db7688e88e7d/ios/MullvadTransport/TransportProvider.swift#L26)):*
I will reply to this comment as most of your other comments are saying the same thing (don't use a protocol, use a closure instead).

> This will lead to transport using `any` constraint until user changes location.

When I wrote this, I hadn't realized we defaulted to Sweden. I guess that's fair, but I will argue that this default is not necessarily the best choice for our users, as it penalizes our users that are not based in Europe. But that's beyond the point  of this so I will change that.

> This code would not suffer this problem if you used a block to provide relay constraints `() -> RelayConstraints`.

That is not correct. `TunnelManager` has the following default
`private var _tunnelSettings = TunnelSettingsV2()` 

It's only updated when we call `scheduleSettingsUpdate` which itself is called when `setRelayConstraints` is called.

So the outcome would be exactly the same.
And lastly, to answer to another comment

> This abstraction still looks foreign to me and should be replaced with `() -> RelayConstraints`. Keep it simple.

It's not because it looks foreign to you that it's not a good choice, or "not simple".
Using closures to provide arguments is generally a design smell. Here's a very crude example that illustrates why.

```swift
func myApi(_ param1: () -> String, param2: () -> Int, param3: () -> Bool) { }

```

Now the callsite looks like this
```swift

myApi {
    <#code#>
} param2: {
    <#code#>
} param3: {
    <#code#>
}

```

There are many instances where a closure as a parameter makes sense (usually in the form of a callback to do async processing). However,`TransportProvider` is not one of those.
___
*[`ios/RelaySelector/RelaySelector.swift` line 210 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856#-NZAX-tv5wdIhZYhbQ7r:-NZPbWbN07D37Wvp6R-7:bcpn9ev) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/073ff6afae15ed838931999a95c7db7688e88e7d/ios/RelaySelector/RelaySelector.swift#L210)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Commit with the above changes: https://github.com/mullvad/mullvadvpn-app/commit/f44c79cbd8b4641cbbdd33a4c2e1e2755f3093df
</blockquote></details>

Thanks for the suggestion, this is ultimately what I wanted to do, but you expressed it in a nicer way.
I'll cherry pick your commit for that fix.


<!-- Sent from Reviewable.io -->

2023-07-03 10:48 UTC, rablador reviewed
> Reviewed 8 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadTransport/TransportProvider.swift` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856#-NZ9pZcA4eFF2qjW23LR:-NZQ72LM755G8W45TQUv:bgo6yuc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/073ff6afae15ed838931999a95c7db7688e88e7d/ios/MullvadTransport/TransportProvider.swift#L26)):*
> There are many instances where a closure as a parameter makes sense (usually in the form of a callback to do async processing). [...]

I (generally) agree with this. And while I also think that the intent is better expressed with the explicit `RelayConstraintsUpdater`, it IS nice to get rid of the default constraints. It might not matter right now, if TunnelSettingsV2 is initialised with the default values anyway, but it's not exactly futureproof.


<!-- Sent from Reviewable.io -->

2023-07-05 12:21 UTC, buggmagnet reviewed
> Dismissed @pronebird from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadTransport/TransportProvider.swift` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856#-NZ9pZcA4eFF2qjW23LR:-NZ_yyNcBxjLU9vcMMaf:b-tph529) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/073ff6afae15ed838931999a95c7db7688e88e7d/ios/MullvadTransport/TransportProvider.swift#L26)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

> There are many instances where a closure as a parameter makes sense (usually in the form of a callback to do async processing). [...]

I (generally) agree with this. And while I also think that the intent is better expressed with the explicit `RelayConstraintsUpdater`, it IS nice to get rid of the default constraints. It might not matter right now, if TunnelSettingsV2 is initialised with the default values anyway, but it's not exactly futureproof.
</blockquote></details>

Yes, we need a better design for the future, but we will have to do with that for now.
___
*[`ios/RelaySelector/RelaySelector.swift` line 82 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856#-NZ9lo1S8fWtOlAx2m0X:-NZa--LP4c6LPUSe_kH_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/073ff6afae15ed838931999a95c7db7688e88e7d/ios/RelaySelector/RelaySelector.swift#L82)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Force unwrap does not look right. Please use generics and/or protocols to negotiate the actual type with compiler.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-05 12:23 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856)* status: all files reviewed, 4 unresolved discussions (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-07-05 13:25 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856)* status: all files reviewed, 4 unresolved discussions (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-07-06 11:58 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856#-:-NZf3QBg4tsXYg-9VlqR:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-07-07 10:32 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4856)* status: all files reviewed, 4 unresolved discussions (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-07-10 11:13 UTC, merged