Implement redeeming voucher on creation account
mullvad/mullvadvpn-app pull request #4867
Opened 2023-07-04 15:32 UTC by mojganii

this pr enables users to redeem voucher code when they create account through the app.

after pressing `Create account ` on `Login` view, the app is been transmitted to `Welcome` page the shows  `account number`  and `device name` beside some informative data , such as : 

-  more info about device name  can be shown with  ⓘ
- add more credit via redeeming voucher code
- buy more credit via in-app purchase(I didn't work on it yet, just the button is aligned on the UI and I'm gonna work on it for the future PR )

when user is successful to expand the time through redeeming voucher code, the succeeded page with the added time is shown.when user presses `Next` button at the page, a confirmation page is shown to user that is included `Start using the app` that takes him into the app and an external link that shows `ninja privacy`.

***when create account request is made, we set `isNew` flag `true` in `StoredAccountData`.and when the expiry date is been increased we flipped that to `false`.therefore if user at the middle of creation account close the app when the app is relaunched, User goes to creation account step if the account is still expired***

2023-07-07 10:45 UTC, rablador requested changes
On a fresh device the router briefly stops at the "out of time"-view before proceeding to the intended view.

[Simulator Screen Recording - iPhone 14 Pro - 2023-07-07 at 12.24.40.mp4](https://files.reviewableusercontent.io/images/reviewable/1230209/4q_5CmktnSR0OTTXkyDH9P82/Simulator%20Screen%20Recording%20-%20iPhone%2014%20Pro%20-%202023-07-07%20at%2012.24.40.mp4)

On a device where account creation has been completed once it works as intended, but the device info view and header bar buttons become visible on the login screen before proceeding to next view. This is nothing new, but it stands out more when the next view removes them again.

[Simulator Screen Recording - iPhone 14 Pro - 2023-07-07 at 12.25.59.mp4](https://files.reviewableusercontent.io/images/reviewable/1230209/JNNHKbRx4hA2Lj4Q7FCDezR_/Simulator%20Screen%20Recording%20-%20iPhone%2014%20Pro%20-%202023-07-07%20at%2012.25.59.mp4)

> Reviewed 1 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-:-NZjsqgzDbKxnnrLxtnx:b-w4vxbv)* status: 1 of 23 files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Containers/Root/HeaderBarView.swift` line 109 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZjkiKKETOUxWhXfxeu:-NZjkiKKETOUxWhXfxev:b-hdizzn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Containers/Root/HeaderBarView.swift#L109)):*
> ```Swift
>     }
> 
>     var isHiddenDeviceInfo = false {
> ```

`isDeviceInfoHidden` reads better I think.


<!-- Sent from Reviewable.io -->

2023-07-07 13:17 UTC, mojganii reviewed
regarding the first video, after talking to @rablador,the latest changes has been pulled and I didn't set the problem.the second comment is beyond the PR but I fixed it

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-:-NZkTJZv4CIX5bldNktt:b-wu5qsc)* status: 1 of 23 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/Containers/Root/HeaderBarView.swift` line 109 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZjkiKKETOUxWhXfxeu:-NZkTRlk6Ujp3Aoqcfjr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Containers/Root/HeaderBarView.swift#L109)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

`isDeviceInfoHidden` reads better I think.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-07 13:44 UTC, rablador requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867)* status: 0 of 24 files reviewed, 14 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Containers/Root/RootContainerViewController.swift` line 514 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZjx_P26F-CBIlTU7X4:-NZjx_P26F-CBIlTU7X5:b-zc0ydl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Containers/Root/RootContainerViewController.swift#L514)):*
> ```Swift
>             self.updateHeaderBarStyleFromChildPreferences(animated: shouldAnimate)
>             self.updateHeaderBarHiddenFromChildPreferences(animated: shouldAnimate)
>             self.updatePrefersNotificationBarHiddenFromChildPreferences()
> ```

`updateNotificationBarHiddenFromChildPreferences` to be consistent with the naming of the other delegate functions.
___
*[`ios/MullvadVPN/Containers/Root/RootContainerViewController.swift` line 674 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZjyGGs6dBDruKZSb2o:-NZjyGGt6lu5y80KZLTN:b93oihe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Containers/Root/RootContainerViewController.swift#L674)):*
> ```Swift
>     private func updatePrefersNotificationBarHiddenFromChildPreferences() {
>         if let notificationController,
>            let child = topViewController as? RootContainment {
> ```

`conforming` for consistency with other functions doing similar things.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 578 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZkL5Lz4fKS_V2YB2aO:-NZkL5Lz4fKS_V2YB2aP:b-xypv83) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L578)):*
> ```Swift
>         coordinator.didFinishPayment = { [weak self] coordinator in
>             guard let self else { return }
>             if shouldDismissOutOfTime() {
> ```

Is out of time route present at this point?
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 833 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZkMsmp0d8So-Yi3IZm:-NZkMsmp0d8So-Yi3IZn:b-hwxsj7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L833)):*
> ```Swift
>     // MARK: - Settings
> 
>     /**
> ```

I know this is old code, but could we move these vars up to the top of the class instead? That's where I'd usually go look for these things.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 972 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZkOd6F22f7VHvzlcqT:-NZkOd6F22f7VHvzlcqU:b-p5i8yq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L972)):*
> ```Swift
>         configuration = RootConfiguration(
>             deviceName: deviceState.deviceData?.capitalizedName,
>             expiry: (isPresentingAccountExpiryBanner || (deviceState.accountData?.isExpired ?? true))
> ```

Isn't it enough to only check the accountData here? The banner should be (although I'm assuming) dependent on data in any case.
___
*[`ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZkQjIq9cv9y4S5A7LP:-NZkQjIq9cv9y4S5A7LQ:bd236la) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift#L36)):*
> ```Swift
> 
>     func start(animated: Bool) {
>         guard case var .loggedIn(storedAccountData, storedDeviceData) = tunnelManager.deviceState else {
> ```

1. Can be `let` instead.
2. Can we ever end up here? If so, shouldn't this check be done from the calling side, thus keeping this coordinator clean from "hidden" dependencies.
___
*[`ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift` line 57 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZkT1A_0fOeLKNZH_qD:-NZkT1A_0fOeLKNZH_qE:b-xjsd4d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift#L57)):*
> ```Swift
>         }
>         navigationController.setViewControllers(
>             Array(navigationController.viewControllers[0 ..< index]),
> ```

This will pop all vc:s after the current one as well. Is this intentional?
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Completed/SetupAccountCompletedContentView.swift` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZk_5jiCdzSCexU8vXn:-NZk_5jiCdzSCexU8vXo:brkrkct) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/View%20controllers/CreationAccount/Completed/SetupAccountCompletedContentView.swift#L22)):*
> ```Swift
> 
>     private let titleLabel: UILabel = {
>         let label = UILabel(frame: .zero)
> ```

Can be simply `UILabel()` for same effect.
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Completed/SetupAccountCompletedContentView.swift` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZkZxcJ93uONXbT8GBq:-NZkZxcK6Tnl7aJ-f3XW:bwhzq2l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/View%20controllers/CreationAccount/Completed/SetupAccountCompletedContentView.swift#L23)):*
> ```Swift
>     private let titleLabel: UILabel = {
>         let label = UILabel(frame: .zero)
>         if let fontDescriptor = UIFontDescriptor.preferredFontDescriptor(withTextStyle: .largeTitle)
> ```

There's already an extension for this, ie:
`UIFont.preferredFont(forTextStyle: .largeTitle, weight: .bold)`
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Completed/SetupAccountCompletedContentView.swift` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZk_MR86TzVr3xa_aYU:-NZk_MR86TzVr3xa_aYV:b-v9czwr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/View%20controllers/CreationAccount/Completed/SetupAccountCompletedContentView.swift#L36)):*
> ```Swift
>         }
>         label.textColor = .white
>         label.adjustsFontForContentSizeCategory = true
> ```

Views residing inside stack views get this set automatically.
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeContentView.swift` line 127 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZk_q2i96ozj4dLYJBm:-NZk_q2i96ozj4dLYJBn:b-wv4ws5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeContentView.swift#L127)):*
> ```Swift
>             tableName: "Welcome",
>             value: """
>             To start using the app,you first need to \
> ```

Missing space: `app, you`.
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeContentView.swift` line 223 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZka1V64CVJSVbSkg39:-NZka1V64CVJSVbSkg3A:bf1mxvx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeContentView.swift#L223)):*
> ```Swift
>         textsStackView.setCustomSpacing(UIMetrics.padding16, after: subtitleLabel)
>         textsStackView.addArrangedSubview(accountNumberLabel)
>         textsStackView.setCustomSpacing(UIMetrics.padding8, after: accountNumberLabel)
> ```

Looking at the Zeplin designs I belive there should be more spacing below the account number.
___
*[ [...]

2023-07-10 10:05 UTC, buggmagnet requested changes
> Reviewed 18 of 23 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867)* status: 21 of 24 files reviewed, 29 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 833 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZkMsmp0d8So-Yi3IZm:-NZynWG66k2dvy0mLnWo:bpyrgpb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L833)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I know this is old code, but could we move these vars up to the top of the class instead? That's where I'd usually go look for these things.
</blockquote></details>

It seems to me this could be an extension instead, but I agree with @rablador here. We should have variable declarations all in the same place.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 190 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZyiqS9EzAcvSSUlbyn:-NZyiqS9EzAcvSSUlbyo:b-hafifn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L190)):*
> ```Swift
> 
>             if dismissedRoute.route == .outOfTime {
>                 let coordinator = dismissedRoute.coordinator as! OutOfTimeCoordinator
> ```

Let's avoid the force unwrapping like this

```swift
guard let outOfTimeCoordinator = dismissedRoute.coordinator as? OutOfTimeCoordinator else {
    completion() // Maybe log an error here 
    return
}

outOfTimeCoordinator.popFromNavigationStack(
    animated: context.isAnimated,
    completion: completion
)

outOfTimeCoordinator.removeFromParent()
```



_Code quote:_
```Swift
let coordinator = dismissedRoute.coordinator as! OutOfTimeCoordinator
```
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 199 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZyj6w-BMO25moTx57h:-NZyj6w-BMO25moTx57i:bcrssn1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L199)):*
> ```Swift
>                 coordinator.removeFromParent()
>             } else if dismissedRoute.route == .welcome {
>                 let coordinator = dismissedRoute.coordinator as! WelcomeCoordinator
> ```

Same remark as above, please avoid force unwrapping
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 776 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZylvhiBF6E2xRTwqIk:-NZylvhiBF6E2xRTwqIl:bqh8lxc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L776)):*
> ```Swift
>         case let .loggedIn(accountData, _):
> 
>             // It is already at creation account wizard
> ```

Please don't use the term `wizard` 
First of all, this is not a term that's used on iOS / macOS, and more importantly a `wizard` usually refers to an external program GUI that installs a program, which is not something we have on iOS.

Instead we can use `// Account creation is being shown` 



_Code quote:_
```Swift
// It is already at creation account wizard
```
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 967 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZyo6h_CBiSc8Z19Zn0:-NZyo6h_CBiSc8Z19Zn1:b-3znem7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L967)):*
> ```Swift
> }
> 
> struct RootDeviceInfoViewModel {
> ```

If `RootConfiguration` gets its own file, this struct should also get the same treatment.
In this case that's a bit overkill, so instead let's move this struct declaration into `RootConfiguration.swift`
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift` line 354 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZyoYQw60FaO7GzQjbh:-NZyoYQw60FaO7GzQjbi:b-l1kv1y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift#L354)):*
> ```Swift
> 
>     /**
>      Returns `true` is the given route  is currently being presented.
> ```

Returns true **if** the given route...
___
*[`ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift` line 98 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZypzea77K-0eCeO56n:-NZypzea77K-0eCeO56o:b-aeklz5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift#L98)):*
> ```Swift
>     }
> 
>     func didRequestToPurchaseCredit(controller: WelcomeViewController) {}
> ```

This is not used anywhere and doesn't seem to do anything. Let's delete this
___
*[`ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift` line 100 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZyqB_F3LLd47P2sNSL:-NZyqB_F3LLd47P2sNSM:bkt5be5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift#L100)):*
> ```Swift
>     func didRequestToPurchaseCredit(controller: WelcomeViewController) {}
> 
>     func didRequestToRedeemVoucher(controller: WelcomeViewController) {
> ```

nit: Let's rename this `redeemVoucher`
Same for `showInfo` above, let's keep names sweet and to the point when it makes sense to do so.
___
*[`ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift` line 47 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZyqdMJ1MjoIzDpWOrE:-NZyqdMJ1MjoIzDpWOrF:b-6dbyvp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift#L47)):*
> ```Swift
> 
>     /// be set `true` when account is created and  be flipped to `false` when user adds more credit
>     var isNew = false
> ```

I need to think more about this, but so far, I think we should not have `isNew` here.
It's essentially acting as a one time only flag, just to show a different screen when a user creates a new account.
___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 115 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZyrxxa0GTv4jAWj6dD:-NZyrxxa0GTv4jAWj6dE:b-bxiqj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L115)):*
> ```Swift
>     static let headerBarBrandNameHeight: CGFloat = 18
> 
>     /// padding
> ```

This comment doesn't add anything useful. 
The variables below are already named `padding` on top of that.

Instead this should describe where those paddings are used, or _how_ they are used (or ideally both)
For example 

```swift

/// Various paddings used in `WelcomeContentView` 
static let welcomeScreenTitlePadding = 8

```
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Completed/SetupAccountCompletedContentView.swift` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZz2zwx2vRHt_EIFYGS:-NZz2zwx2vRHt_EIFYGT:b-cdilq2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/View%20controllers/CreationAccount/Completed/SetupAccountCompletedContentView.swift#L12)):*
> ```Swift
> 
> protocol SetupAccountCompletedContentViewDelegate: AnyObject {
>     func didTapPrivacyButton(view: SetupAccountCompletedContentView, button: AppButton)
> ```

These names don't tell us much, given that we use them in conjuction with the `Action` enum defined below, we could rename  [...]

2023-07-10 12:45 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867)* status: 21 of 24 files reviewed, 29 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Containers/Root/RootContainerViewController.swift` line 514 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZjx_P26F-CBIlTU7X4:-NZzXLrmDIrs4DD-fkrV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Containers/Root/RootContainerViewController.swift#L514)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

`updateNotificationBarHiddenFromChildPreferences` to be consistent with the naming of the other delegate functions.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Containers/Root/RootContainerViewController.swift` line 674 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZjyGGs6dBDruKZSb2o:-NZzXSfXAAXYYP7CX37-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Containers/Root/RootContainerViewController.swift#L674)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

`conforming` for consistency with other functions doing similar things.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 578 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZkL5Lz4fKS_V2YB2aO:-NZzZww-BofXq02klFRL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L578)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Is out of time route present at this point?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 833 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZkMsmp0d8So-Yi3IZm:-NZz_zio6rvWeXioM_qj:b3kre) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L833)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It seems to me this could be an extension instead, but I agree with @rablador here. We should have variable declarations all in the same place.
</blockquote></details>

?
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 972 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZkOd6F22f7VHvzlcqT:-NZzamVo5Ip7UXV1Yyqz:b-jrvlza) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L972)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Isn't it enough to only check the accountData here? The banner should be (although I'm assuming) dependent on data in any case.
</blockquote></details>

No, because when the app banner shows or the time  is out, we shouldn't show time left
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 190 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZyiqS9EzAcvSSUlbyn:-NZzXaUz2QOKTIVSb5KR:btpgorh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L190)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's avoid the force unwrapping like this

```swift
guard let outOfTimeCoordinator = dismissedRoute.coordinator as? OutOfTimeCoordinator else {
    completion() // Maybe log an error here 
    return
}

outOfTimeCoordinator.popFromNavigationStack(
    animated: context.isAnimated,
    completion: completion
)

outOfTimeCoordinator.removeFromParent()
```
</blockquote></details>

do we have any chance to have mismatch coordinators with the route(if yes it says there is something wrong with the development and programmer should catch error)? force wrapping is not all the time bad when you are sure it's exist.moreover if we are gonna to consider this I need to touch other parts as well.
but for making improvement I agree to make assert for this part to make programmer something is wrong with his/her code.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 199 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZyj6w-BMO25moTx57h:-NZzZLXz7I0TzzC9jN2h:b-4mblca) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L199)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Same remark as above, please avoid force unwrapping
</blockquote></details>

as I mentioned before
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 776 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZylvhiBF6E2xRTwqIk:-NZz_5O62ZxE6M028gUb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L776)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Please don't use the term `wizard` 
First of all, this is not a term that's used on iOS / macOS, and more importantly a `wizard` usually refers to an external program GUI that installs a program, which is not something we have on iOS.

Instead we can use `// Account creation is being shown` 
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 967 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZyo6h_CBiSc8Z19Zn0:-NZzaCxK2JyuPieTIab_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L967)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

If `RootConfiguration` gets its own file, this struct should also get the same treatment.
In this case that's a bit overkill, so instead let's move this struct declaration into `RootConfiguration.swift`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift` line 354 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZyoYQw60FaO7GzQjbh:-NZzbIaN0pia88xHg9sZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift#L354)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Returns true **if** the given route...
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZkQjIq9cv9y4S5A7LP:-NZzbolH612_yaOo_0PF:b-d8gwjy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/206a2e17409a94ebc53fb93e0bda20a529ca0d0b/ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift#L36)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

1. Can be `let` instead.
2. Can we ever end up here? If so, shouldn't this check be done from the calling side, thus keeping this coordinator clean from "hidden" dependencies.
</blockquote></details>

as far as I know, one of the responsibility of the coordinator is making dependencies if I followed you.sending these parameters as arguments from calling part causes having tunnel manager as a dependency for redeeming voucher part and sending data from outside.do you think it's a good way send them via parameters when we have access them from internal variables?
___
*[`ios/MullvadVPN/Coordinators/App/Welcome [...]

2023-07-10 13:51 UTC, buggmagnet reviewed
> Reviewed 1 of 5 files at r2, 5 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867)* status: 19 of 25 files reviewed, 24 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 190 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZyiqS9EzAcvSSUlbyn:-N_-0ESG1bXGUVwnJP_S:b-qx7ozd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L190)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

do we have any chance to have mismatch coordinators with the route(if yes it says there is something wrong with the development and programmer should catch error)? force wrapping is not all the time bad when you are sure it's exist.moreover if we are gonna to consider this I need to touch other parts as well.
but for making improvement I agree to make assert for this part to make programmer something is wrong with his/her code.

</blockquote></details>

It's not about whether it can happen or not. 
It's more about promoting best practices via [continuous refactoring](https://www.codit.eu/blog/continuous-refactoring/)

The only way we can make the codebase easier to work with, is by making improvements whenever there's an opportunity and the cost is not too big.

Thank you for making the change, I appreciate it 
___
*[`ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift` line 98 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZypzea77K-0eCeO56n:-N_-1QHT0ol2z6px2szf:bqy67xj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift#L98)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

as I mentioned before, for keeping the PR small, this PR is just for redeeming voucher but I need to implement in-app purchase as well.I'll define this part as TODO
</blockquote></details>

Fair enough
___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 115 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZyrxxa0GTv4jAWj6dD:-N_-1cPw7i-iIdQkkYu7:b-9vaa13) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L115)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I disagree. in the app we have different padding that is multiple 8.it's not just for welcome page, it's comment part of design that we are defining with different name and label.
</blockquote></details>

What I'm trying to say is that if I read the following 

```swift
    /// padding
    static let padding8: CGFloat = 8
```

It doesn't tell me anything useful. I see a variable named `padding` and its value is 8.
But I already knew that from the variable name. So the comment doesn't add value or context.

Look at the other comments in that file, for example the one above
```swift
    /// Height of brand name. Width is automatically produced based on aspect ratio.
    static let headerBarBrandNameHeight: CGFloat = 18
```

It gives a lot of additional context. It's better to write no comment than write a comment that doesn't add value, or is misleading.

At least, please update the `padding` comment to something that adds value.
They all seem to be used in `UIStackView` elements.
Here's an example
```swift

    /// Various paddings used throughout the app to visually separate elements in StackViews 
    static let padding8: CGFloat = 8
```
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Completed/SetupAccountCompletedContentView.swift` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZz0C8nDt84BzFlHs4K:-N_-3Ml3Cn6nx5QtsWvy:b6c2hkl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/View%20controllers/CreationAccount/Completed/SetupAccountCompletedContentView.swift#L18)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

agree
</blockquote></details>

Then please modify it ? :angel: 


<!-- Sent from Reviewable.io -->

2023-07-12 07:07 UTC, buggmagnet approved these changes
> Reviewed 1 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867)* status: 19 of 25 files reviewed, 19 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeViewController.swift` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4867#-NZzFdKX8mBnDtu1at3w:-N_7u0Sq77gvpID-RBVy:b-egri6y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b234a783083f02ad985dd383de298ad30711fa52/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeViewController.swift#L59)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

what does it bring for us? both of them in my opinion have the same priority 
</blockquote></details>

It matters because sometimes this is what makes the difference between an empty UI and a full UI.
Especially when you use layout constraints, the layout is dependant on what elements are showing.
And you have more chances to end up with an incorrect layout if the layout is calculated when an element is empty rather than when it's full. 


<!-- Sent from Reviewable.io -->

2023-07-12 09:19 UTC, merged