Migrate account view to compose
mullvad/mullvadvpn-app pull request #4906
Opened 2023-07-17 15:32 UTC by sabercodic

migrate account screen into compose 

Fixes: DROID-63

2023-07-18 13:14 UTC, albin-mullvad reviewed
> Reviewed 4 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906)* status: all files reviewed, 8 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d2Pnz4nQLKMnRut-Q):*
typo: `account`



_Code quote:_
```
acount
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 49 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d2Z4K9H60jqZ4XgRi:-N_d2Z4K9H60jqZ4XgRj:b-mucz7b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L49)):*
> ```Kotlin
>             AccountUiState(
>                 deviceName = "Test Name",
>                 accountNumber = "1234567890",
> ```

I suggest using 16 digits to look similar to the most regular account number length, eg `1234123412341234`



_Code quote:_
```Kotlin
1234567890
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d5FZD54fgkxtvPD4w:-N_d5FZD54fgkxtvPD4x:bkm5s2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L58)):*
> ```Kotlin
> @ExperimentalMaterial3Api
> @Composable
> fun AccountScreen(
> ```

Can't we use some common scaffolding? E.g. it looks very similar to settings.



_Code quote:_
```Kotlin
AccountScreen
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d74UP13EsuAUU0WyS:-N_d74UQAqjlKagmruRM:brvmt7t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt#L16)):*
> ```Kotlin
>     private val expiryFormatter = DateFormat.getDateTimeInstance(dateStyle, timeStyle)
> 
>     var expiryString = accountExpiry?.toDate()?.let { expiryFormatter.format(it) } ?: ""
> ```

I suggest handling moving this formatting logic to the existing `DateExtensions`



_Code quote:_
```Kotlin
    private val expiryFormatter = DateFormat.getDateTimeInstance(dateStyle, timeStyle)

    var expiryString = accountExpiry?.toDate()?.let { expiryFormatter.format(it) } ?: ""
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 93 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d3NuEBvb8vphN1Vel:-N_d3NuEBvb8vphN1Vem:bbm6hgb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L93)):*
> ```Kotlin
>     viewModel { SelectLocationViewModel(get()) }
>     viewModel { SettingsViewModel(get(), get()) }
>     viewModel { AccountViewModel(get(), get()) }
> ```

I suggest placing this in alphabetical order within the VM section.



_Code quote:_
```Kotlin
AccountViewModel
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 20 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d4IipCIHUWneMUO51:-N_d4IipCIHUWneMUO52:b-867chd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L20)):*
> ```Kotlin
>     private var deviceRepository: DeviceRepository
> ) : ViewModel() {
>     private val showAccountNumber = MutableStateFlow<Boolean>(false)
> ```

Should be part of the combined flow in order to properly update the state.



_Code quote:_
```Kotlin
showAccountNumber
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d4_a5-rAfhzoAurGE:-N_d4_a5-rAfhzoAurGF:b-dshssj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L58)):*
> ```Kotlin
>     fun onCopyAccountNumberClick() {}
>     fun onManageAccountClick(context: Context) {
>         deviceRepository.deviceState.value.token()?.let { context.openAccountPageInBrowser(it) }
> ```

We usually want to avoid interactions with the context in the VM. This call should instead be made form the view.



_Code quote:_
```Kotlin
context.openAccountPageInBrowser(it)
```
___
*[`android/app/src/main/res/values/strings.xml` line 222 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d4DwGB-jC8CUxBuS7:-N_d4DwGB-jC8CUxBuS8:b-yzp11y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/res/values/strings.xml#L222)):*
> ```XML
>     <string name="device_management_name_description">This is the name assigned to the device. Each device logged in on a Mullvad account gets a unique name that helps you identify it when you manage your devices in the app or on the website.</string>
>     <string name="device_management_device_limits">You can have up to 5 devices logged in on one Mullvad account.</string>
>     <string name="device_management_refresh_name">If you log out, the device and the device name is removed. When you log back in again, the device will get a new name.</string>
> ```

Will these be used in this PR?



_Code quote:_
```XML
    <string name="device_management_name_description">This is the name assigned to the device. Each device logged in on a Mullvad account gets a unique name that helps you identify it when you manage your devices in the app or on the website.</string>
    <string name="device_management_device_limits">You can have up to 5 devices logged in on one Mullvad account.</string>
    <string name="device_management_refresh_name">If you log out, the device and the device name is removed. When you log back in again, the device will get a new name.</string>
```


<!-- Sent from Reviewable.io -->

2023-07-25 07:09 UTC, albin-mullvad reviewed
> Reviewed 2 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906)* status: 5 of 12 files reviewed, 7 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaArauaD8g8pwppSJL-:-NaArauaD8g8pwppSJL0:b5eq0s6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a1e44567909b102a43727f9f3d90e1f317a9ee4a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt#L25)):*
> ```Kotlin
>     val indentedCellStartPadding: Dp = 38.dp,
>     val infoButtonVerticalPadding: Dp = 13.dp,
>     val informationIconSize: Dp = 28.dp,
> ```

Is this size different than other info buttons?



_Code quote:_
```Kotlin
informationIconSize
```


<!-- Sent from Reviewable.io -->

2023-07-25 15:22 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906)* status: 5 of 12 files reviewed, 7 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 49 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d2Z4K9H60jqZ4XgRi:-Na6ekoeEyZoUqQVHKd0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L49)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest using 16 digits to look similar to the most regular account number length, eg `1234123412341234`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d74UP13EsuAUU0WyS:-NaBmjSvE5z1vXIvZHhV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt#L16)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest handling moving this formatting logic to the existing `DateExtensions`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaArauaD8g8pwppSJL-:-NaBzmzO3jwy2FAOJq3b:b-3xaiof) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a1e44567909b102a43727f9f3d90e1f317a9ee4a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt#L25)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this size different than other info buttons?
</blockquote></details>

Naming was wrong, fixed.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 93 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d3NuEBvb8vphN1Vel:-NaBqn4o4ENXX9rzcWkx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L93)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest placing this in alphabetical order within the VM section.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 20 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d4IipCIHUWneMUO51:-NaBz-I2B8trXbVmuknH:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L20)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should be part of the combined flow in order to properly update the state.
</blockquote></details>

Removed.
___
*[`android/app/src/main/res/values/strings.xml` line 222 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d4DwGB-jC8CUxBuS7:-NaBziwEDvHc0LXqEZkF:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/res/values/strings.xml#L222)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Will these be used in this PR?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-25 20:37 UTC, albin-mullvad reviewed
> Reviewed 5 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906)* status: 6 of 13 files reviewed, 8 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d74UP13EsuAUU0WyS:-NaDkL-Y74RYtj4n6gBM:blwhmlk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt#L16)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

As part of using an extension my idea was to also skip the `var` and instead just either (1) use the extension function in the view or (2) set in the ui state as `String` rather than `DateTime`.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt` line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaDlF1W6KIjIm3eb0jn:-NaDlF1W6KIjIm3eb0jo:bfp8hhv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc18f4d8a3cd90c5bd8246251f2e59f0ee760823/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt#L13)):*
> ```Kotlin
>     var accountExpiry: DateTime?
> ) {
>     val deviceName = deviceName.capitalizeFirstCharOfEachWord()
> ```

It's unnessary to store this value. Just call the extension function from the view instead.



_Code quote:_
```Kotlin
val deviceName = deviceName.capitalizeFirstCharOfEachWord()
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt` line 45 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaDj09K9zc8x5jeiAlU:-NaDj09K9zc8x5jeiAlV:b-yezjqs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc18f4d8a3cd90c5bd8246251f2e59f0ee760823/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt#L45)):*
> ```Kotlin
>     val sideMargin: Dp = 22.dp,
>     val smallPadding: Dp = 8.dp,
>     val spinnerSize: Dp = 28.dp,
> ```

We already have `loadingSpinnerSize` and `progressIndicatorSize` and this another naming. These should be named in a common way and be prefix with something like `small*`, `medium*` and `large*`



_Code quote:_
```Kotlin
val spinnerSize: Dp = 28.dp,
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt` line 50 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaDjrxA9gbDpI53UQSq:-NaDjrxA9gbDpI53UQSr:b-7sfeiu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc18f4d8a3cd90c5bd8246251f2e59f0ee760823/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt#L50)):*
> ```Kotlin
>     }
> 
>     /*
> ```

Please keep reference stuff like this locally, at least when the code is being reviewed.



_Code quote:_
```Kotlin
 /*
```


<!-- Sent from Reviewable.io -->

2023-07-26 09:55 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906)* status: 4 of 13 files reviewed, 8 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt` line 50 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaDjrxA9gbDpI53UQSq:-NaGc0uZBaPnCIAd07dS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc18f4d8a3cd90c5bd8246251f2e59f0ee760823/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt#L50)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Please keep reference stuff like this locally, at least when the code is being reviewed.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d4_a5-rAfhzoAurGE:-NaGc4cbDkAtf41P_fDx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L58)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We usually want to avoid interactions with the context in the VM. This call should instead be made form the view.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-26 13:30 UTC, albin-mullvad reviewed
> Reviewed 2 of 9 files at r3, 4 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906)* status: 10 of 13 files reviewed, 14 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 7 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaGeUm-B4AT1tMlmQHy):*
typo



_Code quote:_
```
e
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AccountNumberView.kt` line 8 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHNxl1BaxGaDAydD7u:-NaHNxl1BaxGaDAydD7v:b-brhmge) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AccountNumberView.kt#L8)):*
> ```Kotlin
> 
> @Composable
> fun AccountNumberView(accountNumber: String, isShown: Boolean) {
> ```

I suggest changing this arg name since it's not about hiding/showing. I'm not sure about the best suitable arg name, but something like "obfuscate" seems less confusing imo.



_Code quote:_
```Kotlin
isShown
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableInformationView.kt` line 28 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHNPc04HnusI_8WUfS:-NaHNPc16-jtkIFxOQ8b:bju6d7d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableInformationView.kt#L28)):*
> ```Kotlin
> 
> @Composable
> fun CopyableInformationView(content: String) {
> ```

This is both for copying and "obfuscating" (with dots), right? In that case the name should reflect that.



_Code quote:_
```Kotlin
CopyableInformationView(
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/InformationView.kt` line 35 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHNGje566c80xlGEdx:-NaHNGje566c80xlGEdy:bjxj9gy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/InformationView.kt#L35)):*
> ```Kotlin
> fun InformationView(
>     content: String,
>     error: String? = null,
> ```

Are we showing any errors in the account view? :thinking: 



_Code quote:_
```Kotlin
error: String? = null,
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 96 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHN51Z6xXhPpkHKzSS:-NaHN51Z6xXhPpkHKzST:b-507d17) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L96)):*
> ```Kotlin
>     ) {
>         LaunchedEffect(Unit) {
>             viewActionSharedFlow.distinctUntilChanged().collect { viewAction ->
> ```

This one should not be needed since.



_Code quote:_
```Kotlin
distinctUntilChanged()
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d74UP13EsuAUU0WyS:-NaHHGbMCxPEPMmze0KX:bbietj8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt#L16)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As part of using an extension my idea was to also skip the `var` and instead just either (1) use the extension function in the view or (2) set in the ui state as `String` rather than `DateTime`.
</blockquote></details>

This feedback still applies, including for the device name.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt` line 33 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHHRnODeVRA5hGKf2D:-NaHHRnODeVRA5hGKf2E:b-cnsttb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt#L33)):*
> ```Kotlin
>                     AccountScreen(
>                         uiState = state,
>                         viewActionSharedFlow = vm.viewActions,
> ```

I suggest chaning to just `viewActions`



_Code quote:_
```Kotlin
viewActionSharedFlow
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt` line 38 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHHobL4RrcT-NJ4qdU:-NaHHobL4RrcT-NJ4qdV:bmol9li) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt#L38)):*
> ```Kotlin
>     }
> 
> fun String.copyToClipboard(
> ```

This should be a `Context` extension rather than a `String` extension.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt` line 49 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHHxlr4gDeOg9W_wNh:-NaHHxlr4gDeOg9W_wNi:b-zci7rs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt#L49)):*
> ```Kotlin
>     clipboard.setPrimaryClip(clipData)
> 
>     Toast.makeText(context, toastMessage, Toast.LENGTH_SHORT).show()
> ```

Can we toast only on Sdk versions where the built-in copy prompt isn't show? Either in this PR or create a new Linear issue.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt` line 64 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHKoxU4xO3FPaaebMd:-NaHKoxU4xO3FPaaebMe:b-6m3epq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt#L64)):*
> ```Kotlin
> fun String.groupPasswordModeWithSpaces(groupCharSize: Int = 4): String {
>     return BIG_DOT_CHAR.repeat(this.length).groupWithSpaces(groupCharSize)
> }
> ```

We should try to avoid creating too many `String` extensions if possible since those are global unless they are explicitly scoped. Perhaps they can be moved to the `AccountNumberView` unless/until used somewhere else?



_Code quote:_
```Kotlin
fun String.groupWithSpaces(groupCharSize: Int = 4): String {
    return fold(StringBuilder()) { formattedText, nextDigit ->
            if ((formattedText.length % (groupCharSize + 1)) == groupCharSize) {
                formattedText.append(SPACE_CHAR)
            }
            formattedText.append(nextDigit)
        }
        .toString()
}

fun String.groupPasswordModeWithSpaces(groupCharSize: Int = 4): String {
    return BIG_DOT_CHAR.repeat(this.length).groupWithSpaces(groupCharSize)
}
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 21 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaGf4q-82p4xp-rzLPV:-NaGf4q-82p4xp-rzLPW:b-vv85gk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L21)):*
> ```Kotlin
>     private var accountRepository: AccountRepository,
>     deviceRepository: DeviceRepository,
>     private var serviceConnectionManager: ServiceConnectionManager
> ```

I suggest putting the `private var` arguments first.



_Code quote:_
```Kotlin
    private var accountRepository: AccountRepository,
    deviceRepository: DeviceRepository,
    private var serviceConnectionManager: ServiceConnectionManager
```


<!-- Sent from Reviewable.io -->

2023-07-27 13:23 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906)* status: 10 of 13 files reviewed, 16 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AccountNumberView.kt` line 8 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHNxl1BaxGaDAydD7u:-NaMMtlt2vbt-Nz5Vtq1:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AccountNumberView.kt#L8)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest changing this arg name since it's not about hiding/showing. I'm not sure about the best suitable arg name, but something like "obfuscate" seems less confusing imo.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableInformationView.kt` line 28 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHNPc04HnusI_8WUfS:-NaMSPth2bdiax-yHokN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableInformationView.kt#L28)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This is both for copying and "obfuscating" (with dots), right? In that case the name should reflect that.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableInformationView.kt` line 32 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaLTLtO1g-SrSVenX0e:-NaMPulE6gKij0aFFeeC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableInformationView.kt#L32)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Skip defining `val`:s for these 
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableInformationView.kt` line 34 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaLTeo673SzqqtsapZP:-NaMQoxO9Ef3gbxTyhZQ:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableInformationView.kt#L34)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why do we need a `return` here?
</blockquote></details>

Removed.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/InformationView.kt` line 35 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHNGje566c80xlGEdx:-NaMM03p6FGxLhjmeq4u:b-hfpv0l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/InformationView.kt#L35)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Are we showing any errors in the account view? :thinking: 
</blockquote></details>

removed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/InformationView.kt` line 98 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaLTteO3BGlM52LZAjQ:-NaML4AI6HT4oza0lN_S:b-dzhda6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/InformationView.kt#L98)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The intention of `NOTHING` is a bit unclear. Please clarify and perhaps come up with a more descriptive name.
</blockquote></details>

It just transformed from attr xml file, changed into SHOW_VIEW 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 58 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d5FZD54fgkxtvPD4w:-NaMV2sxCy_Ar9PI1mUl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L58)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can't we use some common scaffolding? E.g. it looks very similar to settings.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt` line 96 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHN51Z6xXhPpkHKzSS:-NaMVJWQ-Mv2S5jdNSVb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt#L96)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This one should not be needed since.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-N_d74UP13EsuAUU0WyS:-NaLbAam7-8mR8U30WBh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d06fe7080cc7150e2d54e6c357d1e9fc5fb20ef4/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt#L16)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This feedback still applies, including for the device name.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt` line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaDlF1W6KIjIm3eb0jn:-NaLasZ7BNnjDjsKyAiJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc18f4d8a3cd90c5bd8246251f2e59f0ee760823/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt#L13)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

It's unnessary to store this value. Just call the extension function from the view instead.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt` line 45 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaDj09K9zc8x5jeiAlU:-NaMJG_T4kn0dozYMHpB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc18f4d8a3cd90c5bd8246251f2e59f0ee760823/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt#L45)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We already have `loadingSpinnerSize` and `progressIndicatorSize` and this another naming. These should be named in a common way and be prefix with something like `small*`, `medium*` and `large*`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt` line 33 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHHRnODeVRA5hGKf2D:-NaMVqDH0DtytzYoVhka:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt#L33)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest chaning to just `viewActions`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt` line 38 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHHobL4RrcT-NJ4qdU:-NaLcYCl84E-8IbHGe05:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt#L38)):*
<details><summa [...]

2023-07-27 20:56 UTC, albin-mullvad requested changes
> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906)* status: all files reviewed, 5 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AccountNumberView.kt` line 8 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHNxl1BaxGaDAydD7u:-NaO5edD6kkcbz-1teZT:bwp624l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AccountNumberView.kt#L8)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The new name doesn't sound gramatically correct. I suggest `doObfuscateWithPasswordDots`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 71 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaO73Mk3bQIGoOYI0f0:-NaO73Mk3bQIGoOYI0f1:b-hum4uo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/564ff2211f421a8df42b08e5eda7af7eb94d2f5e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L71)):*
> ```Kotlin
>     clipboard.setPrimaryClip(clipData)
> 
>     Toast.makeText(this, toastMessage, Toast.LENGTH_SHORT).show()
> ```

I believe it's better to skip the `Toast` here and instead handle that on the callsite.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt` line 33 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHHRnODeVRA5hGKf2D:-NaO3WLW12BwSgZVqlh6:b-tw14dk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt#L33)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: missing `s` in the end
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt` line 49 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHHxlr4gDeOg9W_wNh:-NaO5E-g2IubdomRtAlN:b-pto5sj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt#L49)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Starting Android 13 the system toast will show based on documentation: https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#:~:text=Starting%20in%20Android%2013%2C%20the,preview%20of%20the%20copied%20content.
Should I apply SDK check or investigate more on detecting system events? 
</blockquote></details>

If it's just a sdk version check I think it's best to just do it now.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 42 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaO4h249CPvfX4WPlXk:-NaO4h249CPvfX4WPlXl:b-stq9uu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/564ff2211f421a8df42b08e5eda7af7eb94d2f5e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L42)):*
> ```Kotlin
>                 AccountUiState(deviceName = "", accountNumber = "", accountExpiry = null)
>             )
>     val uiState =
> ```

nit: add newline before this line
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 58 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaO4k9e9xhlarw8A8TU:-NaO4k9e9xhlarw8A8TV:b-stq9uu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/564ff2211f421a8df42b08e5eda7af7eb94d2f5e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L58)):*
> ```Kotlin
>         }
>     }
>     fun onLogoutClick() {
> ```

nit: add newline before this line


<!-- Sent from Reviewable.io -->

2023-07-28 09:39 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906)* status: 8 of 27 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AccountNumberView.kt` line 8 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHNxl1BaxGaDAydD7u:-NaQ_mVa6DpZg3DOnpEF:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AccountNumberView.kt#L8)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The new name doesn't sound gramatically correct. I suggest `doObfuscateWithPasswordDots`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt` line 71 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaO73Mk3bQIGoOYI0f0:-NaQ_rXB6_S1D3Cd9sT7:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/564ff2211f421a8df42b08e5eda7af7eb94d2f5e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt#L71)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe it's better to skip the `Toast` here and instead handle that on the callsite.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt` line 49 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaHHxlr4gDeOg9W_wNh:-NaQ_YDy8DmVz3-we9vH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf938f9c50aef9471ed1e7d628b3b8937bf476b6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt#L49)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

If it's just a sdk version check I think it's best to just do it now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-28 09:44 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 19 of 19 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-:-NaQsepZ86toWZcbJ7qK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-07-28 14:19 UTC, albin-mullvad requested changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906)* status: all files reviewed, 10 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 40 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRrBSfEBIRlwGwPBqm:-NaRrBSfEBIRlwGwPBqn:b-prmrip) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L40)):*
> ```Kotlin
>     private val accountExpiryState = MutableStateFlow(AccountExpiry.Missing)
> 
>     private val mockAuthTokenCache: AuthTokenCache = mockk()
> ```

Move to the other mocks



_Code quote:_
```Kotlin
private val mockAuthTokenCache: AuthTokenCache = mockk()
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 41 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRpiUm3urhRUkXLFtV:-NaRpiUm3urhRUkXLFtW:b-2534og) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L41)):*
> ```Kotlin
> 
>     private val mockAuthTokenCache: AuthTokenCache = mockk()
>     private val mockAccountAndDevice: AccountAndDevice =
> ```

Rename to `dummyAccountAndDevice`



_Code quote:_
```Kotlin
mockAccountAndDevice
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 47 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRr28zDZLPEdthh2Uf:-NaRr28zDZLPEdthh2Ug:b-66gntf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L47)):*
> ```Kotlin
>                 id = "fake_id",
>                 name = "fake_name",
>                 pubkey = ByteArray(1234),
> ```

Use an empty array here instead.



_Code quote:_
```Kotlin
 ByteArray(1234)
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 72 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRqxlJ62XkmKNdfrjm:-NaRqxlJ62XkmKNdfrjn:b-ag4gy0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L72)):*
> ```Kotlin
>     @After
>     fun tearDown() {
>         viewModel.viewModelScope.coroutineContext.cancel()
> ```

Is this one necssary?



_Code quote:_
```Kotlin
viewModel.viewModelScope.coroutineContext.cancel()
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 77 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRqHWrDkeCX31yhjj-:-NaRqHWrDkeCX31yhjj0:botvarq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L77)):*
> ```Kotlin
> 
>     @Test
>     fun test_account_log_in_state() =
> ```

Skip underscores to align the name with the logout test.



_Code quote:_
```Kotlin
test_account_log_in_state
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 78 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRrHmv0P6VIaZLHVJg:-NaRrHmv0P6VIaZLHVJh:b-vw0uf9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L78)):*
> ```Kotlin
>     @Test
>     fun test_account_log_in_state() =
>         runTest(testCoroutineRule.testDispatcher) {
> ```

Is this one necessary?



_Code quote:_
```Kotlin
testCoroutineRule.testDispatcher
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 82 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRqTMH3cYzwk6uirv7:-NaRqTMH3cYzwk6uirv8:b-3yvgij) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L82)):*
> ```Kotlin
>             viewModel.uiState.test {
>                 var result = awaitItem()
>                 assertNotEquals("1111222233334444", result.accountNumber)
> ```

Are we not expecting the initial state here? In that case I suggest asserting on that class instead.



_Code quote:_
```Kotlin
assertNotEquals("1111222233334444", result.accountNumber)
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 84 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRq2om0eRBKPmmmoyI:-NaRq2om0eRBKPmmmoyJ:bad60e9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L84)):*
> ```Kotlin
>                 assertNotEquals("1111222233334444", result.accountNumber)
>                 deviceState.value = DeviceState.LoggedIn(accountAndDevice = mockAccountAndDevice)
>                 accountExpiryState.value = AccountExpiry.Missing
> ```

Is this necessary?



_Code quote:_
```Kotlin
accountExpiryState.value = AccountExpiry.Missing
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 86 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRqoR-3hqJ5-TPibpa:-NaRqoR-3hqJ5-TPibpb:bcdh3fa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L86)):*
> ```Kotlin
>                 accountExpiryState.value = AccountExpiry.Missing
>                 result = awaitItem()
>                 assertEquals("1111222233334444", result.accountNumber)
> ```

I suggest using the "dummy" property here instead



_Code quote:_
```Kotlin
"1111222233334444"
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 92 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRpb5CCBu0O8ChZs4P:-NaRpb5CCBu0O8ChZs4Q:b-60lwm1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L92)):*
> ```Kotlin
>     @Test
>     fun testOnLogoutClick() {
> ```

nit: remove this empty line


<!-- Sent from Reviewable.io -->

2023-07-28 14:42 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906)* status: all files reviewed, 9 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 40 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRrBSfEBIRlwGwPBqm:-NaRtPO_BpkySikZAJKg:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L40)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Move to the other mocks
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 41 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRpiUm3urhRUkXLFtV:-NaRtPq641Oq5rnqnBOJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L41)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Rename to `dummyAccountAndDevice`
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 47 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRr28zDZLPEdthh2Uf:-NaRtkVs2ejtj1Duff-Q:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L47)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Use an empty array here instead.
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 72 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRqxlJ62XkmKNdfrjm:-NaRtsOuEsOgZEZjbqFh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L72)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this one necssary?
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 77 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRqHWrDkeCX31yhjj-:-NaRu2U98AiTa1iDK6em:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L77)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Skip underscores to align the name with the logout test.
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 78 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRrHmv0P6VIaZLHVJg:-NaRuIw78oXAcrrVSwtE:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L78)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this one necessary?
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 82 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRqTMH3cYzwk6uirv7:-NaRurYr89SMOXbhD-gb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L82)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Are we not expecting the initial state here? In that case I suggest asserting on that class instead.
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 84 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRq2om0eRBKPmmmoyI:-NaRvC7UCLJxOmL8RCCj:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L84)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this necessary?
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 86 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906#-NaRqoR-3hqJ5-TPibpa:-NaRvCcY5jW1H3CStmjB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/831875c213f03567a7466214d004c9392c03c92c/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L86)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest using the "dummy" property here instead
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-28 14:47 UTC, albin-mullvad approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-07-28 14:59 UTC, albin-mullvad approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4906)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-07-28 15:17 UTC, merged