Cache the TransportStrategy counter and reuse it between processes
mullvad/mullvadvpn-app pull request #4921
Opened 2023-07-24 11:56 UTC by buggmagnet

This PR implements caching the `connectionAttempts` from the `TransportStrategy` in order to provide a better UX.

Suppose only network connections via shadowsocks would work.
The first request made by the application at launch time would always fail.

In this PR, we start recording the number of failures so that the next time the application (or network extension) is launched, we will directly select the last successful connection mode (i.e. one that did not fail)

The connection attempt cached value is shared by both processes via `UserDefaults` shared by the same application group.

2023-07-31 12:38 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-NafsfUfDmwSXbirmUhC:-NafsfUfDmwSXbirmUhD:b-ie1va5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/MullvadREST/RESTTransportStrategy.swift#L2)):*
> ```Swift
> //
> //  RESTTransportStrategy.swift
> ```

I believe that it slipped the name of the class is not equal to this
___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-NafqUSYESZuaPPITo1w:-NafqUSYESZuaPPITo1x:b-y1o9ui) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/MullvadREST/RESTTransportStrategy.swift#L32)):*
> ```Swift
>     private let attemptsRecorder: AttemptsRecording
> 
>     public init(connectionAttempts: Int = 0, attemptsRecorder: AttemptsRecording) {
> ```

when we have cached value in `UserDefaults`,there is no need to take connection attempt as a parameter. `AttemptsRecording` can have method for reading value and set it internally in the class.
if there is for the sake of test,let's go that with mocking `AttemptsRecording` as I saw it's already implemented 
___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-Naftrpe5BgZ-68aQIOo:-Naftrpe5BgZ-68aQIOp:b-3yvsom) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/MullvadREST/RESTTransportStrategy.swift#L41)):*
> ```Swift
>     /// Every third failure results in a direct transport suggestion.
>     public mutating func didFail() {
>         let (partial, isOverflow) = connectionAttempts.addingReportingOverflow(1)
> ```

as I understood,this line increases 1 to the value of `connectionAttempts` with caring about overflow flag,how it understands about whether the result is a multiple of 3 or not,while we have another `isMultiple`  for that.It looked liked to me when overflow happens let's go 2 otherwise add the counter.maybe it's better to change the comment for this part
___
*[`ios/MullvadVPN/AppDelegate.swift` line 106 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-Nafwc8o9uSQL1ydIxvN:-Nafwc8o9uSQL1ydIxvO:bqyxzm3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/MullvadVPN/AppDelegate.swift#L106)):*
> ```Swift
>         // This init cannot fail as long as the security group identifier is valid
>         let sharedUserDefaults = UserDefaults(suiteName: ApplicationConfiguration.securityGroupIdentifier)!
>         let connectionAttempts = sharedUserDefaults
> ```

it should be retrieved from the you storage protocol
___
*[`ios/Shared/ApplicationConfiguration.swift` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-Nafx7jd8wMHx0_WCwa_:-Nafx7jd8wMHx0_WCwaa:b-q2800b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/Shared/ApplicationConfiguration.swift#L41)):*
> ```Swift
> 
>     /// `UserDefaults` key shared by both processes. Used to cache and synchronize connection attempts between them.
>     static let connectionAttemptsSharedCacheKey = "ConnectionAttemptsSharedCacheKey"
> ```

it's better to consider that in your protocol storage.there is no need to be available in the whole of the application


<!-- Sent from Reviewable.io -->

2023-07-31 13:19 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-NafsfUfDmwSXbirmUhC:-Nag3nx_3jmqd66-KHjv:buhy53) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/MullvadREST/RESTTransportStrategy.swift#L2)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I believe that it slipped the name of the class is not equal to this
</blockquote></details>

Indeed, nice catch !
___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-NafqUSYESZuaPPITo1w:-Nag48Lz77zgSKSOaD4W:b-1hl9jd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/MullvadREST/RESTTransportStrategy.swift#L32)):*
> AttemptsRecording can have method for reading value and set it internally in the class.
I disagree, the point is that it's a write only protocol, is doesn't need to read values. That would break separation of concerns.
___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-Naftrpe5BgZ-68aQIOo:-Nag4qVC--4CVhbraTsQ:bcnyzwt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/MullvadREST/RESTTransportStrategy.swift#L41)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

as I understood,this line increases 1 to the value of `connectionAttempts` with caring about overflow flag,how it understands about whether the result is a multiple of 3 or not,while we have another `isMultiple`  for that.It looked liked to me when overflow happens let's go 2 otherwise add the counter.maybe it's better to change the comment for this part
</blockquote></details>

I'm really sorry but I don't understand your comment. What are you suggesting to change, and to what ?
___
*[`ios/Shared/ApplicationConfiguration.swift` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-Nafx7jd8wMHx0_WCwa_:-Nag5VdDDxmBPzULHmg5:bdk28up) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/Shared/ApplicationConfiguration.swift#L41)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it's better to consider that in your protocol storage.there is no need to be available in the whole of the application
</blockquote></details>

Do you mean moving this value to the `AttemptsRecording` file ?


<!-- Sent from Reviewable.io -->

2023-07-31 13:26 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/Shared/ApplicationConfiguration.swift` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-Nafx7jd8wMHx0_WCwa_:-Nag737B4ZUYGe6yLBwl:b2nign3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/Shared/ApplicationConfiguration.swift#L41)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Do you mean moving this value to the `AttemptsRecording` file ?
</blockquote></details>

yep
___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-NafqUSYESZuaPPITo1w:-Nag6KmN6psGnlHqPIZy:b-4us8ig) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/MullvadREST/RESTTransportStrategy.swift#L32)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

> AttemptsRecording can have method for reading value and set it internally in the class.
I disagree, the point is that it's a write only protocol, is doesn't need to read values. That would break separation of concerns.
</blockquote></details>

it has nothing to do separation of concerns when you are feeding that from your storage.I believe that is related to single source of truth.


<!-- Sent from Reviewable.io -->

2023-07-31 19:50 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-NafqUSYESZuaPPITo1w:-NahQm0e1opBGSMbYJKO:b-6jbzwz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/MullvadREST/RESTTransportStrategy.swift#L32)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

If we read from `UserDefaults` every time instead of keeping a local counter, it would break the `Equatable` implementation, and in turn the way `TransportProvider` guarantees that multiple requests failing at the same time do not change the `TransportStrategy` several times in a row.
</blockquote></details>

there is no need to read that everytime, when we check if there is a value for that on memory or not.if there is not then load from `UserDefaults`.It doesn't make sense to me to store the value from `AttemptsRecording` and read that out of the abstraction.
maybe it's better to know other.
___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-Naftrpe5BgZ-68aQIOo:-NahQUg_Dd34RJ88hmaI:batsiq6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/MullvadREST/RESTTransportStrategy.swift#L41)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I'm really sorry but I don't understand your comment. What are you suggesting to change, and to what ?
</blockquote></details>

the comment is not the thing is doing.it means to me, if there is overflow after adding 1 to the value of `connectionAttempts`,reset the value to 2( `Shadowsocks`)  otherwise keep the counter. the way we are choosing the transport type is in `connectionTransport()`.there is no need to repeat the here.
```
      **let** (partial, isOverflow) = connectionAttempts.addingReportingOverflow(1)

        // reset the value to 2 when overflowing, otherwise keep the counter

        connectionAttempts = isOverflow ? 2 : partial
```


<!-- Sent from Reviewable.io -->

2023-08-01 07:40 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadREST/RESTTransportStrategy.swift` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-Naftrpe5BgZ-68aQIOo:-NajzHAn81Y3qCtAgy-E:bfym3in) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/MullvadREST/RESTTransportStrategy.swift#L41)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

the comment is not the thing is doing.it means to me, if there is overflow after adding 1 to the value of `connectionAttempts`,reset the value to 2( `Shadowsocks`)  otherwise keep the counter. the way we are choosing the transport type is in `connectionTransport()`.there is no need to repeat the here.
```
      **let** (partial, isOverflow) = connectionAttempts.addingReportingOverflow(1)

        // reset the value to 2 when overflowing, otherwise keep the counter

        connectionAttempts = isOverflow ? 2 : partial
```
</blockquote></details>

We are not repeating anything here. 
This is handling the edge case scenario where we reach `Int.max` and we need to loop over. 
If we were reverting to `1` instead of `2` it would break the "every third failure loops back to trying to directly connect" algorithm.

The comment is explaining why we go directly to 2 instead of going back to 1. I will add a small addendum to make it extra clear.


<!-- Sent from Reviewable.io -->

2023-08-01 09:08 UTC, mojganii approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2023-08-01 09:14 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 106 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-Nafwc8o9uSQL1ydIxvN:-NakN2D75cgNbM04cAGg:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/MullvadVPN/AppDelegate.swift#L106)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it should be retrieved from the you storage protocol
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-01 10:44 UTC, pronebird requested changes
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921)* status: 1 of 9 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 105 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-Nakc9dL9isZkVTLNYMf:-Nakc9dL9isZkVTLNYMg:b-7wtu49) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b494a57e6adf3e654c0824639e8abd67b319e13/ios/MullvadVPN/AppDelegate.swift#L105)):*
> ```Swift
> 
>         // This init cannot fail as long as the security group identifier is valid
>         let sharedUserDefaults = UserDefaults(suiteName: ApplicationConfiguration.securityGroupIdentifier)!
> ```

I think that `TransportStrategy` could accept `UserDefaults` and use it directly to read the initial value from preferences and then update it as it goes.

Current implementation is somewhat fragmented and spread across many places in the app:

1. The user defaults key resides in `ApplicationConfiguration` and global for the app.
2. `AppDelegate` knows that it needs to read `Int` value from a specific key in order to initialize `TransportStrategy`.
3. `UserDefaults` extension that implements `AttemptsRecording` knows that it needs to store `Int` value using the specific key from `ApplicationConfiguration`.
4. `UserDefaults+Extensions` resides in `TunnelManager` which is a bit odd as it's not really used in there.

It would be much simpler if all this was isolated within `TransportStrategy` and `AppDelegate` would only care about creating `UserDefaults` instance and passing it over to `TransportStrategy`, i.e:

```swift
private static let userDefaultsKey = "<user default key>"

let userDefaults: UserDefaults
var connectionAttempts: Int

public init(userDefaults: UserDefaults) {
    connectionAttempts = userDefaults.integer(forKey: Self.userDefaultsKey)
    self.userDefaults = userDefaults
}

private func persist() {
    userDefaults.set(connectionAttempts, forKey: Self.userDefaultsKey)
}
```

For mocking, instead of `UserDefaults` you could pass some protocol which `UserDefaults` either conform to or some interstitial struct that implements it.

This way the implementation detail in regards of where and how the connection attempts are stored remains hidden within transport strategy.


<!-- Sent from Reviewable.io -->

2023-08-01 10:46 UTC, pronebird reviewed
> Reviewed 6 of 9 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2023-08-01 12:32 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921)* status: 3 of 9 files reviewed, 4 unresolved discussions (waiting on @mojganii and @pronebird)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 105 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-Nakc9dL9isZkVTLNYMf:-NakzZ6e2DoSvhv93GYE:buyec6o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b494a57e6adf3e654c0824639e8abd67b319e13/ios/MullvadVPN/AppDelegate.swift#L105)):*
I wanted to avoid keeping a reference to `UserDefaults` because it opens a can of worms, which is also why I created the `AttemptsRecording` abstraction. This class shouldn't know that it's backing data to `UserDefaults`. It should just "write" somewhere IMHO.

But since both you and @mojganii  suggested that we should be more straightforward in `UserDefaults` usage here, I will go with this suggestion.

For unit tests I just remembered we can still use it, and use the `removePersistentDomain(forName:)`  API in order to reset `UserDefaults` and avoid affecting other tests.

> `UserDefaults+Extensions` resides in `TunnelManager` which is a bit odd as it's not really used in there.

I wasn't entirely sure where to put it initially. With this suggestion we don't need the extension anymore.


<!-- Sent from Reviewable.io -->

2023-08-01 14:28 UTC, pronebird reviewed
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/Shared/ApplicationConfiguration.swift` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-Nafx7jd8wMHx0_WCwa_:-NalUWaT120BNpK_esUd:b-vw73ub) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/Shared/ApplicationConfiguration.swift#L41)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It has to be available from both the Packet Tunnel and the main application, so regardless how we cut it, it will be available to the whole app anyway, I didn't feel like creating an enum for storing a single value. Maybe in the future if we have more related settings in that way, we can regroup them together.
</blockquote></details>

With the most recent change, this key is now a part of `TransportStrategy` so we could perhaps remove it here.


<!-- Sent from Reviewable.io -->

2023-08-01 14:29 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-:-NalUkZf0Qisw5c3CO78:bnfp4nl)* status: all files reviewed, 3 unresolved discussions



<!-- Sent from Reviewable.io -->

2023-08-01 14:53 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @mojganii and @pronebird)

___
*[`ios/Shared/ApplicationConfiguration.swift` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-Nafx7jd8wMHx0_WCwa_:-Nal_gQD2LHblpJkg9eI:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/62f24f910996c8402398eac6ffd6f47b070b2982/ios/Shared/ApplicationConfiguration.swift#L41)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

With the most recent change, this key is now a part of `TransportStrategy` so we could perhaps remove it here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-01 15:06 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4921#-:-NalcaNr63k_S60hdxoW:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2023-08-01 15:08 UTC, closed without merging