Add a UI for wireguard obfuscation preferences
mullvad/mullvadvpn-app pull request #4929
Opened 2023-07-26 10:52 UTC by buggmagnet

Part 2 of adding UDP-over-TCP obfuscation.

This PR only creates a UI for the upcoming WireGuard obfuscation settings.
There is no change to the `PreferencesViewModel` yet because I first want to refactor
`TunnelSettingsV2` to become generic in a different pull request.

The same goes for disabling the port selection when obfuscation is turned off.
It will all come in different PRs

2023-08-03 12:43 UTC, pronebird requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4929)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/Settings/SettingsHeaderView.swift` line 123 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4929#-NavQCOk-eCP_6nEb_5g:-NavQCOlDNcxksqEPAWm:bql2mg1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f400ed71c4a5a53c3ae3148662437d6b8d91e36b/ios/MullvadVPN/View%20controllers/Settings/SettingsHeaderView.swift#L123)):*
> ```Swift
>     private func updateAccessibilityCustomActions() {
>         #warning(
>             "SettingsHeaderView is reused for more than content blockers now, this code doesn't seem correct anymore."
> ```

We really need to address this.


<!-- Sent from Reviewable.io -->

2023-08-03 13:37 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4929)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/MullvadVPN/View controllers/Settings/SettingsHeaderView.swift` line 123 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4929#-NavQCOk-eCP_6nEb_5g:-NavbRmZBTVrGavNjL7a:brnmiwp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f400ed71c4a5a53c3ae3148662437d6b8d91e36b/ios/MullvadVPN/View%20controllers/Settings/SettingsHeaderView.swift#L123)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

We really need to address this.
</blockquote></details>

Yes, I don't remember the context anymore, but I found that in another PR and didn't want to leave it unadressed, and at the same time, it was outside of the scope for that PR.


<!-- Sent from Reviewable.io -->

2023-08-04 09:49 UTC, albin-mullvad commented
@ivandrofly the feature was merged in #4644 a while ago and we're currently working on stabilizing some parts of the app before we are ready to release it.

2023-08-08 13:29 UTC, pronebird approved these changes
> Reviewed 2 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4929)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-08 13:29 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4929#-:-NbKKfsm6TE1G20f70xu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-09 07:36 UTC, merged