implement in-app purchase in account flow
mullvad/mullvadvpn-app pull request #4979
Opened 2023-08-04 14:21 UTC by mojganii

It sounds like the new account flow is designed to provide a smooth onboarding experience for users while also offering useful information about device concepts relevant to the steps they are in. Additionally, the greeting page allows users to add more credit by redeeming vouchers that were previously implemented. Furthermore, this update introduces in-app purchases, giving users the option to make purchases within the app.

2023-08-07 09:04 UTC, buggmagnet requested changes
> Reviewed 3 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 3 of 24 files reviewed, 12 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Classes/AccountFlow.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbDuMNf4b_UK625yJEP:-NbDuMNf4b_UK625yJEQ:b-r6oxcj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Classes/AccountFlow.swift#L13)):*
> ```Swift
>     private static let userDefaultsKey = "isOnboarding"
> 
>     static var isOnboarding: Bool {
> ```

This is introducing a global shared state, and that's definitely a big no no.
Please remove this, and use dependency injection to introduce this parameter where it's needed.
___
*[`ios/MullvadVPN/Coordinators/App/AddCreditSucceededCoordinator.swift` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbDv9XqAlmbeny9QPHo:-NbDv9XrDv4-43pNP7fT:b9l71x8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Coordinators/App/AddCreditSucceededCoordinator.swift#L45)):*
> ```Swift
>     func titleForAction(in controller: AddCreditSucceededViewController) -> String {
>         NSLocalizedString(
>             "REDEEM_VOUCHER_DISMISS_BUTTON",
> ```

Why has this been copied from `SettingsRedeemVoucherCoordinator` ?
Is it supposed to be the same text ? Because it isn't at the moment.
___
*[`ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift` line 133 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbDwexh9U3A_ivHZ-aE:-NbDwexi1KQF73wJ0krg:bp7wbcs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift#L133)):*
> ```Swift
> 
>         coordinator.didCancel = { [weak self] coordinator in
>             guard let self else { return }
> ```

You don't call methods on `self` here so there is no need to weakify self
Furthermore, there's a warning that even tells you that it's defined but never used.
`Value 'self' was defined but never used; consider replacing with boolean test`
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE-Kuf7Is-zh1yLbgI:-NbE-Kuf7Is-zh1yLbgJ:b-ke771o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L12)):*
nit: We can omit saying it's a flag in those kind of comments, because it's a comment about the variable.
Instead we could replace it with
> Indicates whether the presentation controller should use a fullscreen presentation when in a compact width environment
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE03u_A2yNtciJm9SU:-NbE03u_A2yNtciJm9SV:b-7rdscf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L46)):*
> ```Swift
> 
>     /**
>      Change the position of  `presentedView` if  `FormSheetPresentationOptions.adjustViewWhenKeyboardAppears` is `true`
> ```

nit: You have a couple of extra spaces in that sentence 
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 72 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE0McL1Ym292q9SsWL:-NbE0McL1Ym292q9SsWM:b-yjhvb5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L72)):*
> ```Swift
>     init(
>         presentedViewController: UIViewController,
>         presenting presentingViewController: UIViewController?,
> ```

`presentingViewController` doesn't need to be optional 
___
*[`ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE0xgGEaYL4kmMHDl5:-NbE0xgGEaYL4kmMHDl6:b1pacme) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c02098a983aa33e70f56f9153022d3916f71283c/ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift#L47)):*
> ```Swift
> 
>     /// Set to `true` when the account is created and flipped to `false` when the user adds more credit.
>     var isNew = false
> ```

nit
So we added this flag for the last release to remove it now it seems.
We need to be more careful about these changes, in hindsight this feels like it was not thought through at all.

We clearly need to become better at planning future work ahead to avoid these kind of changes in the future.
___
*[`ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE1ipJEPPTEtXdXuRB:-NbE1ipJEPPTEtXdXuRC:b-eqkr36) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c02098a983aa33e70f56f9153022d3916f71283c/ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift#L65)):*
> ```Swift
>         // This leads to a reset of the settings. If the key isn't present, consider the account not new to avoid the issue.
>         let isNewAccount = try? container.decode(Bool.self, forKey: .isNew)
>         self.isNew = isNewAccount ?? false
> ```

Did you try upgrading from a previous official release to see if the settings were wiped after upgrading ?
We need to make sure this doesn't happen again
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE3Fl86BHPQlyI555f:-NbE3Fl86BHPQlyI555g:b-t45c3i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L29)):*
> ```Swift
> 
>     deinit {
>         accountUpdateTimer?.cancel()
> ```

This only ever gets called if we go through the account flow (including buying a subscription) 
This is problematic, every time we log out and log in again, this creates multiple timers that will poll account update. 
After a couple of log in and outs, I had 13 requests done in just 1 minute.

We need to find a better way to cancel this timer earlier. For starters, we should cancel this timer if the user logs out.
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE5XZn1HTuLE37eYKd:-NbE5XZn1HTuLE37eYKe:b-kqf4m0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L45)):*
> ```Swift
>     }
> 
>     private(set) var product: SKProduct? = nil
> ```

Why do we keep this `product` around ?
We don't do anything with it
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 96 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE66JA3HASRY88YD5V:-NbE66JA3HASRY88YD5W:b-ypf77e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L96)):*
> ```Swift
> 
>     private func addObservers() {
>         let tunnelObserver =
> ```

There's a lot of logic here, which means there are a lot of potential bugs waiting to happen.
We should refactor this logic into an independent logic object that could be unit tested
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 114 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE8fRP7Zvn4MgOneFN:-NbE8fRP7Zvn4MgOn [...]

2023-08-07 09:56 UTC, pronebird reviewed
> Reviewed 3 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 5 of 24 files reviewed, 12 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Classes/AccountFlow.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbDuMNf4b_UK625yJEP:-NbEPyxQ0aTvEdpzZZ7l:b-aem9ug) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Classes/AccountFlow.swift#L13)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This is introducing a global shared state, and that's definitely a big no no.
Please remove this, and use dependency injection to introduce this parameter where it's needed.
</blockquote></details>

More on that: If I remember that right and correct me if I am wrong, but I think new account flow is triggered each time user creates an account. `StoredAccountData` gained `isNew: Bool` a little while ago and I thought that was done for that purpose.


<!-- Sent from Reviewable.io -->

2023-08-07 10:18 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 5 of 24 files reviewed, 13 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 701 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbEUw4qDS2gtElRxr0C:-NbEUw4qDS2gtElRxr0D:b-mzk9sz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L701)):*
> ```Swift
>                 preferredContentSize: preferredFormSheetContentSize,
>                 modalPresentationStyle: .custom,
>                 transitioningDelegate: SecondaryContextTransitioningDelegate(adjustViewWhenKeyboardAppears: false)
> ```

Probably should be a regular`FormSheetTransitioningDelegate()`


<!-- Sent from Reviewable.io -->

2023-08-07 10:40 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 5 of 24 files reviewed, 14 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 68 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE_Lu-430SjKTZro6I:-NbE_Lu-430SjKTZro6J:bs886w6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L68)):*
> ```Swift
>     }
> 
>     private let option: FormSheetPresentationOptions
> ```

Nit: plural `options` with S at the end, and not just a single `option` perhaps?


<!-- Sent from Reviewable.io -->

2023-08-07 11:17 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 5 of 24 files reviewed, 14 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 72 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE0McL1Ym292q9SsWL:-NbEfcrd5Y7kbXP4Ifdb:b2vlm6n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L72)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

`presentingViewController` doesn't need to be optional 
</blockquote></details>

It's defined as optional in `UIPresentationController.init()`. https://developer.apple.com/documentation/uikit/uipresentationcontroller/1618328-init


<!-- Sent from Reviewable.io -->

2023-08-07 12:43 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 5 of 24 files reviewed, 14 unresolved discussions (waiting on @mojganii and @pronebird)

___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 72 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE0McL1Ym292q9SsWL:-NbF0MiV1HF6f7QNMmwq:b-blpkde) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L72)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

It's defined as optional in `UIPresentationController.init()`. https://developer.apple.com/documentation/uikit/uipresentationcontroller/1618328-init
</blockquote></details>

Looks like I missed the part declaring the conformance to`UIViewControllerTransitioningDelegate` .

My bad, sorry !


<!-- Sent from Reviewable.io -->

2023-08-07 15:48 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 5 of 24 files reviewed, 12 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/App/AddCreditSucceededCoordinator.swift` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbDv9XqAlmbeny9QPHo:-NbFR_l3-CSlgMF7f7fS:b-udgss6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Coordinators/App/AddCreditSucceededCoordinator.swift#L45)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Why has this been copied from `SettingsRedeemVoucherCoordinator` ?
Is it supposed to be the same text ? Because it isn't at the moment.
</blockquote></details>

the page is reusing for the second step of cretionaccount when the account has been added more time via redeeming voucher or in-purchase.also we have redeeming voucher on account view as well that ,  that's why every usage defines the own title.the same goes for header.just I need to change the key.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 701 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbEUw4qDS2gtElRxr0C:-NbFS83XC40jIn7AeAoI:b48uusw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L701)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Probably should be a regular`FormSheetTransitioningDelegate()`
</blockquote></details>

when the `horizontalSizeClass` is `.compact`,shouldn't it better to be fullscreen?the main reason I've considered `SecondaryContextTransitioningDelegate` is the point I've mentioned 
___
*[`ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift` line 133 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbDwexh9U3A_ivHZ-aE:-NbFUVM9BwjLklYBGdZV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift#L133)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

You don't call methods on `self` here so there is no need to weakify self
Furthermore, there's a warning that even tells you that it's defined but never used.
`Value 'self' was defined but never used; consider replacing with boolean test`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE03u_A2yNtciJm9SU:-NbFVJAn9aXiyUf-3Bq_:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L46)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit: You have a couple of extra spaces in that sentence 
</blockquote></details>

Done
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 68 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE_Lu-430SjKTZro6I:-NbFVNLF9tFalv5jAby3:b-a1i3nm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L68)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: plural `options` with S at the end, and not just a single `option` perhaps?
</blockquote></details>

I thought I fixed that.Done!
___
*[`ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE0xgGEaYL4kmMHDl5:-NbFWMcf7nzx9ERzJa41:b-ejqcxx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c02098a983aa33e70f56f9153022d3916f71283c/ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift#L47)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
So we added this flag for the last release to remove it now it seems.
We need to be more careful about these changes, in hindsight this feels like it was not thought through at all.

We clearly need to become better at planning future work ahead to avoid these kind of changes in the future.
</blockquote></details>

I totally agree! 
but please,consider that the feature was under development and It's not be released until I'm done with in-app purchase part.so it means I can feel free to do changes if it needs otherwise I would definitely be careful about changes and I would take care of backward compatibility.
but sometimes it happens and we just need to do some stuff during migration.


<!-- Sent from Reviewable.io -->

2023-08-08 07:10 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 5 of 24 files reviewed, 12 unresolved discussions (waiting on @mojganii and @pronebird)

___
*[`ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE0xgGEaYL4kmMHDl5:-NbIxKdOEEQ_z9EFEo-_:b-se1ofv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c02098a983aa33e70f56f9153022d3916f71283c/ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift#L47)):*
Just to clarify, this was not a critic of the decision you took here.
More like a general reflexion about our team and the way we do things as a whole.

> that the feature was under development and It's not be released until I'm done with in-app purchase part.

Fair enough, I just checked the latest release we have on the AppStore (`2023.3`) and it doesn't have the `isNew` flag, so this change should be fine. 


<!-- Sent from Reviewable.io -->

2023-08-08 08:11 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 6 of 24 files reviewed, 12 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE5XZn1HTuLE37eYKd:-NbJBnXL1jNDvx5iA4Kh:brqxt3k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L45)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Why do we keep this `product` around ?
We don't do anything with it
</blockquote></details>

I think it's accessed outside of interactor, from view controller.


<!-- Sent from Reviewable.io -->

2023-08-11 14:38 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 2 of 34 files reviewed, 11 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 701 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbEUw4qDS2gtElRxr0C:-NbTOo8LDYUx_Jc0mhuZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L701)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`SecondaryContextPresentationController ` created by `SecondaryContextTransitioningDelegate` is only used by `ApplicationCoordinator.secondaryNavigationContainer` because it tweaks header bar in response to size class changes. 

In your case you probably don't need that and so you could create `FormSheetTransitioningDelegate` and pass the desired options in there. 

In regards of fullscreen or not. Actually it should behave as normal modal in compact but I really don't know how to change modal presentation when that happens. Last time I tried, it didn't work and I am not sure we can easily fix that. So perhaps let's say it should be fullscreen.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE3Fl86BHPQlyI555f:-NbZyalZ3bK204gS-kZr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L29)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This only ever gets called if we go through the account flow (including buying a subscription) 
This is problematic, every time we log out and log in again, this creates multiple timers that will poll account update. 
After a couple of log in and outs, I had 13 requests done in just 1 minute.

We need to find a better way to cancel this timer earlier. For starters, we should cancel this timer if the user logs out.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 96 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE66JA3HASRY88YD5V:-NbTVUDJC8mFhL2hzVlr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L96)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

There's a lot of logic here, which means there are a lot of potential bugs waiting to happen.
We should refactor this logic into an independent logic object that could be unit tested
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 114 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE8fRP7Zvn4MgOneFN:-NbJD9k16gSygWFiDs9-:ba3dfob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L114)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

`Date` [already has a method](https://developer.apple.com/documentation/foundation/nsdate/1408823-datebyaddingtimeinterval) that can substract a `TimeInterval` from a `Date` object. Let's remove this.
</blockquote></details>

Removed
___
*[`ios/MullvadVPN/Classes/AccountFlow.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbDuMNf4b_UK625yJEP:-NbTVboO3JbTv9UUqTn3:b-93cm99) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Classes/AccountFlow.swift#L13)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

More on that: If I remember that right and correct me if I am wrong, but I think new account flow is triggered each time user creates an account. `StoredAccountData` gained `isNew: Bool` a little while ago and I thought that was done for that purpose.
</blockquote></details>

talked offline
___
*[`ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE0xgGEaYL4kmMHDl5:-NbTPE5RASKclWllDveX:b-pnwt59) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c02098a983aa33e70f56f9153022d3916f71283c/ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift#L47)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Just to clarify, this was not a critic of the decision you took here.
More like a general reflexion about our team and the way we do things as a whole.

> that the feature was under development and It's not be released until I'm done with in-app purchase part.

Fair enough, I just checked the latest release we have on the AppStore (`2023.3`) and it doesn't have the `isNew` flag, so this change should be fine. 
</blockquote></details>

Talked offline
___
*[`ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE1ipJEPPTEtXdXuRB:-Nb_126j5Lo7pQ__rznR:b-oiobdv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c02098a983aa33e70f56f9153022d3916f71283c/ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift#L65)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Did you try upgrading from a previous official release to see if the settings were wiped after upgrading ?
We need to make sure this doesn't happen again
</blockquote></details>

works fine


<!-- Sent from Reviewable.io -->

2023-08-14 09:20 UTC, pronebird requested changes
> Reviewed 9 of 28 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 11 of 34 files reviewed, 13 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Classes/AppPreferences.swift` line 38 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnGL0ICHGPXK5Xi9oT:-NbnGL0ICHGPXK5Xi9oU:b26tnkb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Classes/AppPreferences.swift#L38)):*
> ```Swift
>     }
> 
>     init(key: String, defaultValue: Value, container: UserDefaults = .standard) {
> ```

FYI If you'd like to go with SwiftUI `@AppStorage` approach where the default value is assigned instead of being passed over `defaultValue` then you could modify the initializer to the following:

```swift
init(wrappedValue: Value, _ key: String, container: UserDefaults = .standard) {
    self.defaultValue = wrappedValue
    self.container = container
    self.key = key
}
```

Then properties in AppPreferences would be defined as:

```swift
final class AppPreferences: AppPreferencesDataSource {
    @AppStorage("username", container: UserDefaults(suiteName: "net.mullvad.suite"))
    var username = "pronebird"

    @AppStorage("isDeveloper")
    var isDeveloper = true
}
```
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 508 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnK_X2AwnPBgeSK5aA:-NbnK_X2AwnPBgeSK5aB:bo3dfli) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L508)):*
> ```Swift
>             self?.appPreferences.lastSeenChangeLogVersion = Bundle.main.shortVersion
>             self?.continueFlow(animated: false)
>             completion(coordinator)
> ```

The `completion()` call was meant to be called after finishing VC animation. Therefore it should be called right after `coordinator.start(animated: false)` and not from `didFinish()`.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 959 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnJ60LCRqnLWURNEN_:-NbnJ60LCRqnLWURNENa:b-ys0lmi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L959)):*
> ```Swift
> 
> fileprivate extension AppPreferencesDataSource {
>     var isSeen: Bool {
> ```

Missing subject here for "seen", i.e `is<Subject>Seen`. 
___
*[`ios/MullvadVPN/Coordinators/App/LoginCoordinator.swift` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnJe3W8yDWegNWv8Dr:-NbnJe3W8yDWegNWv8Ds:b-u35uyk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/LoginCoordinator.swift#L30)):*
> ```Swift
>         tunnelManager: TunnelManager,
>         devicesProxy: REST.DevicesProxy,
>         appPreferences: AppPreferencesDataSource
> ```

Unused parameter


<!-- Sent from Reviewable.io -->

2023-08-14 09:44 UTC, pronebird requested changes
> Reviewed 1 of 28 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 12 of 34 files reviewed, 14 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/Configurations/Version.xcconfig` line 5 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnLUcK2BpPrEoA505S:-NbnLUcK2BpPrEoA505T:b-ckru6n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/Configurations/Version.xcconfig#L5)):*
> ```
> 
> // Marketing version, aka major.minor
> MARKETING_VERSION = 2023.21
> ```

Probably committed by mistake


<!-- Sent from Reviewable.io -->

2023-08-14 12:20 UTC, rablador requested changes
> Reviewed 6 of 24 files at r1, 28 of 28 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: all files reviewed, 19 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Classes/AppPreferences.swift` line 38 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnGL0ICHGPXK5Xi9oT:-Nbni1wF6kMO3zAKbf1A:b5bq81i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Classes/AppPreferences.swift#L38)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI If you'd like to go with SwiftUI `@AppStorage` approach where the default value is assigned instead of being passed over `defaultValue` then you could modify the initializer to the following:

```swift
init(wrappedValue: Value, _ key: String, container: UserDefaults = .standard) {
    self.defaultValue = wrappedValue
    self.container = container
    self.key = key
}
```

Then properties in AppPreferences would be defined as:

```swift
final class AppPreferences: AppPreferencesDataSource {
    @AppStorage("username", container: UserDefaults(suiteName: "net.mullvad.suite"))
    var username = "pronebird"

    @AppStorage("isDeveloper")
    var isDeveloper = true
}
```
</blockquote></details>

This is better I think. However, I don't think the key should be a string, since a simple misspelling could mess things up quite badly in worst case scenario.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 96 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnzDtEB42WSAv1zkdD:-NbnzDtEB42WSAv1zkdE:b-lv3v4i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L96)):*
> ```Swift
>         /*
>          Uncomment if you'd like to test TOS again
>          TermsOfService.unsetAgreed()
> ```

Remove or update to `isAgreedToTermsOfService`.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 300 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnlLcXBQVQFmwCQomi:-NbnlLcXBQVQFmwCQomj:b-a9ck60) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L300)):*
> ```Swift
>         }
> 
>         guard appPreferences.isSeen else {
> ```

This param name needs a change, since only "isSeen" currently gives no clue as to what has been seen.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 303 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnlDEeBz90uLSta57G:-NbnlDEeBz90uLSta57H:b-31wqjr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L303)):*
> ```Swift
>             return .changelog
>         }
>         guard appPreferences.isShownOnboarding else {
> ```

nit: Some spacing between guards.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 508 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnK_X2AwnPBgeSK5aA:-Nbnlncn4QdjnnTbpG3N:bz2fg9x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L508)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

The `completion()` call was meant to be called after finishing VC animation. Therefore it should be called right after `coordinator.start(animated: false)` and not from `didFinish()`.
</blockquote></details>

I think this change was introduced to handle presentation bugs due to messed up routing. Right, @mojganii? In reality `didFinish` here means that presentation was finished, which might be misleading since for most other coordinators it means they're being dismissed.
___
*[`ios/MullvadVPN/View controllers/ChangeLog/ChangeLogInteractor.swift` line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnrQdRAcBB7HFidXXq:-NbnrQdRAcBB7HFidXXr:b-a6uh16) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/View%20controllers/ChangeLog/ChangeLogInteractor.swift#L17)):*
> ```Swift
>     private let logger = Logger(label: "ChangeLogInteractor")
>     var viewModel: ChangeLogViewModel {
>         do {
> ```

Changelog will never change dynamically and therefore doesn't need to be fetched and created dynamically. I think this whole portion could go into the viewmodel below instead. Or all of it into its own file.
___
*[`ios/MullvadVPN/View controllers/ChangeLog/ChangeLogInteractor.swift` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbntSsu3pJgPkg0bz2I:-NbntSsu3pJgPkg0bz2J:b-gcu1ge) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/View%20controllers/ChangeLog/ChangeLogInteractor.swift#L42)):*
> ```Swift
> 
>         } catch {
>             logger.error(error: error, message: "Cannot read changelog from bundle.")
> ```

I know it's outside the scope of this PR, but perhaps we shouldn't even present a changelog modal at all in the changelog cannot be read from file.
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE3Fl86BHPQlyI555f:-NbnuhQxEzgBcxAHJIAd:bi4y5oi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L29)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we could make the timer externally accessible like in similar interactors (eg. changelog and out of time) and then start/stop in tandem with view lifecycle instead.


<!-- Sent from Reviewable.io -->

2023-08-15 11:09 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: all files reviewed, 19 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 508 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnK_X2AwnPBgeSK5aA:-Nbsr369DG9KILRKdj3k:blj8hva) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L508)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I think this change was introduced to handle presentation bugs due to messed up routing. Right, @mojganii? In reality `didFinish` here means that presentation was finished, which might be misleading since for most other coordinators it means they're being dismissed.
</blockquote></details>

@rablador this should be addressed in a separate PR.

`completion` call is meant to signal to the router that coordinator and its VC were presented on screen. If this call is postponed until later than the router is effectively paralyzed.


<!-- Sent from Reviewable.io -->

2023-08-15 12:08 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: all files reviewed, 19 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 508 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnK_X2AwnPBgeSK5aA:-Nbt4kz949VjTUVLMPAM:b-w1mkfy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L508)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

@rablador this should be addressed in a separate PR.

`completion` call is meant to signal to the router that coordinator and its VC were presented on screen. If this call is postponed until later than the router is effectively paralyzed.
</blockquote></details>

I agree. And based on our discussion on Slack, a poc for the fix is already in the works.


<!-- Sent from Reviewable.io -->

2023-08-21 12:12 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 21 of 39 files reviewed, 17 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Classes/AppPreferences.swift` line 38 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnGL0ICHGPXK5Xi9oT:-NcM0eDjCTIYIuS58gE3:b86sx8k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Classes/AppPreferences.swift#L38)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This is better I think. However, I don't think the key should be a string, since a simple misspelling could mess things up quite badly in worst case scenario.
</blockquote></details>

Done!
key is always `String`.just we can define this as an enum
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 96 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnzDtEB42WSAv1zkdD:-NcM2YrP2HfIdFPlZek4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L96)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Remove or update to `isAgreedToTermsOfService`.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 300 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnlLcXBQVQFmwCQomi:-NcM2aP56DnGYmDAPMOp:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L300)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This param name needs a change, since only "isSeen" currently gives no clue as to what has been seen.
</blockquote></details>

Done
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 303 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnlDEeBz90uLSta57G:-NcM2o-YA6Y5wyMzh-hV:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L303)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

nit: Some spacing between guards.
</blockquote></details>

Done
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 508 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnK_X2AwnPBgeSK5aA:-NcM3OmR00Hn0KzfhEVv:b-xfwpmm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L508)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I agree. And based on our discussion on Slack, a poc for the fix is already in the works.
</blockquote></details>

`didFinish` revokes when user taps `Got it!` to flip the flag
___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 959 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnJ60LCRqnLWURNEN_:-NcM3fM62vEWJw2gDcjl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L959)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Missing subject here for "seen", i.e `is<Subject>Seen`. 
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/LoginCoordinator.swift` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnJe3W8yDWegNWv8Dr:-NcM3uvkAqpJKv-7ZD9d:b-ol6nfp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/LoginCoordinator.swift#L30)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Unused parameter
</blockquote></details>

it's filled by ` SceneDelegate`.it's dependency injection
___
*[`ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE-Kuf7Is-zh1yLbgI:-NcM4l5827Xa2E0x0sHK:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/Presentation%20controllers/FormsheetPresentationController.swift#L12)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit: We can omit saying it's a flag in those kind of comments, because it's a comment about the variable.
Instead we could replace it with
> Indicates whether the presentation controller should use a fullscreen presentation when in a compact width environment
</blockquote></details>

Done
___
*[`ios/MullvadVPN/View controllers/ChangeLog/ChangeLogInteractor.swift` line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnrQdRAcBB7HFidXXq:-NcM5Bjg-Qlwf2R-pHl-:b-ozo51x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/View%20controllers/ChangeLog/ChangeLogInteractor.swift#L17)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Changelog will never change dynamically and therefore doesn't need to be fetched and created dynamically. I think this whole portion could go into the viewmodel below instead. Or all of it into its own file.
</blockquote></details>

I'll take this part into `init` but it called one time
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE5XZn1HTuLE37eYKd:-NcMyaSm01LhPOtPdeRF:b-4bw3sb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L45)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think it's accessed outside of interactor, from view controller.
</blockquote></details>

yes,it is
___
*[`ios/Configurations/Version.xcconfig` line 5 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnLUcK2BpPrEoA505S:-Nc6Yd_Q9VH6qyWBbwuR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/Configurations/Version.xcconfig#L5)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Probably committed by mistake
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-21 13:56 UTC, pronebird requested changes
> Reviewed 1 of 28 files at r2, 6 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 27 of 39 files reviewed, 17 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/LoginCoordinator.swift` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnJe3W8yDWegNWv8Dr:-NcNFHcF2EfLPd301idO:b-w8p9oa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/LoginCoordinator.swift#L30)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it's filled by ` SceneDelegate`.it's dependency injection
</blockquote></details>

That's great but I don't see `appPreferences` being used anywhere here. If dependency is not used then it's not needed.
___
*[`ios/MullvadVPN/Coordinators/App/OutOfTimeCoordinator.swift` line 78 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NcNF8HC9JmBIpSV5eyQ:-NcNF8HC9JmBIpSV5eyR:b-z4xej) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/808bb3a90bd94981ed599b7054b2dedeebc5857a/ios/MullvadVPN/Coordinators/App/OutOfTimeCoordinator.swift#L78)):*
> ```Swift
>     }
> 
>     func didUpdateDeviceState(deviceState: DeviceState) {
> ```

Is it unused?
___
*[`ios/MullvadVPN/View controllers/ChangeLog/ChangeLogInteractor.swift` line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnrQdRAcBB7HFidXXq:-NcNLzZOBte88fQBApB0:bld6qcu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/View%20controllers/ChangeLog/ChangeLogInteractor.swift#L17)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I'll take this part into `init` but it called one time
</blockquote></details>

I agree with Jon. I would simply put all that into view model and keep it simple, i.e:

```swift
struct ChangeLogViewModel {
   var header: String {
       return Bundle.main.shortVersion
   }

   var title: String {
       return NSLocalizedString(...)
   }

   func attributedBody(with font: UIFont) -> NSAttributedString {
       return NSAttributedString(/* transform body */)
   }

   var body: String

   private init(body: String) { 
      self.body = body 
   }

   static func createFromFile() throws -> ChangeLogViewModel {
      return ChangeLogViewModel(body: try readFromFile())
   }
}
```


<!-- Sent from Reviewable.io -->

2023-08-21 14:34 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 26 of 39 files reviewed, 17 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/LoginCoordinator.swift` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnJe3W8yDWegNWv8Dr:-NcNRlolEBEHEezUtCFQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/Coordinators/App/LoginCoordinator.swift#L30)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

That's great but I don't see `appPreferences` being used anywhere here. If dependency is not used then it's not needed.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/OutOfTimeCoordinator.swift` line 78 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NcNF8HC9JmBIpSV5eyQ:-NcNPJbl0sp-lzzIoYX4:b-ke8io0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/808bb3a90bd94981ed599b7054b2dedeebc5857a/ios/MullvadVPN/Coordinators/App/OutOfTimeCoordinator.swift#L78)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Is it unused?
</blockquote></details>

toady, I tried to redeem voucher on account view, while the account was out of time.when the time has been added via voucher code,the out of time view was still there and it is not disappeared .then I found it out we didn't consider adding time via different ways in `OutOfTimeView` case that's why I've added this into interactor and it's revoked in `OutOfTimeViewController`
___
*[`ios/MullvadVPN/View controllers/ChangeLog/ChangeLogInteractor.swift` line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnrQdRAcBB7HFidXXq:-NcNQaR61gqZnfjZp0fG:b-p4uw30) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/View%20controllers/ChangeLog/ChangeLogInteractor.swift#L17)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I agree with Jon. I would simply put all that into view model and keep it simple, i.e:

```swift
struct ChangeLogViewModel {
   var header: String {
       return Bundle.main.shortVersion
   }

   var title: String {
       return NSLocalizedString(...)
   }

   func attributedBody(with font: UIFont) -> NSAttributedString {
       return NSAttributedString(/* transform body */)
   }

   var body: String

   private init(body: String) { 
      self.body = body 
   }

   static func createFromFile() throws -> ChangeLogViewModel {
      return ChangeLogViewModel(body: try readFromFile())
   }
}
```
</blockquote></details>

it's not a good idea to read file into view model.let's keep that in interactor
___
*[`ios/MullvadVPN/View controllers/ChangeLog/ChangeLogInteractor.swift` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbntSsu3pJgPkg0bz2I:-NcNQlFQ0Tc8tqnIeVWL:b-oy10dx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/View%20controllers/ChangeLog/ChangeLogInteractor.swift#L42)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I know it's outside the scope of this PR, but perhaps we shouldn't even present a changelog modal at all in the changelog cannot be read from file.
</blockquote></details>

does it happen before publishment? if we are going to prevent from happening this scenario we should understand if it's possible to read file before evaluating next route that it brings more code and complexity into `ApplicationCoordinator` that I believe it's not worth based on costs and benefits
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbE3Fl86BHPQlyI555f:-NcNSEEG07EQYPLlRFEo:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14a2d6202a6eaf8f615d5934681aa3c9e0c3c8d2/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L29)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I think we could make the timer externally accessible like in similar interactors (eg. changelog and out of time) and then start/stop in tandem with view lifecycle instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-21 15:06 UTC, pronebird requested changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 27 of 39 files reviewed, 15 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 520 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NcNblFB2fHDPc-mChCR:-NcNblFB2fHDPc-mChCS:b-fjg38) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/808bb3a90bd94981ed599b7054b2dedeebc5857a/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L520)):*
> ```Swift
> 
>         coordinator.didFinish = { [weak self] coordinator in
>             self?.appPreferences.lastSeenChangeLogVersion = Bundle.main.shortVersion
> ```

Could you please extract that line into a function, next to where you have `var isLatestChangesSeen` declared in `AppPreferences`, i.e:

```swift
extension AppPreferences {
   func markChangeLogSeen() {
      lastSeenChangeLogVersion = Bundle.main.shortVersion
   }
}
```

So that we keep that logic around `Bundle.main.shortVersion` close to each other.
___
*[`ios/MullvadVPN/View controllers/ChangeLog/ChangeLogInteractor.swift` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbntSsu3pJgPkg0bz2I:-NcNahfU8gCTdYTSB0qN:bmytpmi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/View%20controllers/ChangeLog/ChangeLogInteractor.swift#L42)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

does it happen before publishment? if we are going to prevent from happening this scenario we should understand if it's possible to read file before evaluating next route that it brings more code and complexity into `ApplicationCoordinator` that I believe it's not worth based on costs and benefits
</blockquote></details>

We have a `shouldPresent()` hook in router delegate for which we could discard presentation of changelog, if  changelog is missing rom bundle or it's simply empty. This is likely going to be implemented in the future, but not now.


<!-- Sent from Reviewable.io -->

2023-08-21 15:52 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 27 of 39 files reviewed, 15 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/OutOfTimeCoordinator.swift` line 78 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NcNF8HC9JmBIpSV5eyQ:-NcNeO1a1YDoJX3nP0dT:b-dpytip) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/808bb3a90bd94981ed599b7054b2dedeebc5857a/ios/MullvadVPN/Coordinators/App/OutOfTimeCoordinator.swift#L78)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

toady, I tried to redeem voucher on account view, while the account was out of time.when the time has been added via voucher code,the out of time view was still there and it is not disappeared .then I found it out we didn't consider adding time via different ways in `OutOfTimeView` case that's why I've added this into interactor and it's revoked in `OutOfTimeViewController`
</blockquote></details>

Oh I just figured out that it's a delegate method, maybe we should follow the same convention when defining delegate methods so they don't look so wildly different.

For example:

```
func <who>Did<what>(_ who: <Who>)
```

or 
```
func <who>(_ who: <Who>, did<What>: <What>)
```

__But more importantly__, we seem to have some indirection and feeding of the same data obtained from tunnel observer back into UI.

1.  As of now `OutOfTimeViewControllerDelegate` pings coordinator with two important events, when it starts and ends handling payment.
2. New delegate method was added `didUpdateDeviceState()` which in essence just loops back to delegate with some arbitrary information like device state.

What I would do differently:

1. I think coordinator could tap directly into interactor to obtain `deviceState` if it needs it. Because `OutOfTimeViewController` certainly does not need it.
2. `OutOfTimeInteractor` should not export crude data like `DeviceState` but instead should expose meaningful event. For example:

```swift
class OutOfTimeInteractor {
    // Called when account transitions from expired to active state:
    var accountDidBecomeActive: (() -> Void)?
}
```

And I think`didUpdateDeviceState` should actually check if account is transitioning from expired to active state, i.e:


```swift
let tunnelObserver = TunnelBlockObserver(
   // ... redacted...

   didUpdateDeviceState: { [weak self] tunnelManager, deviceState, previousDeviceState in
       let wasActive = previousDeviceState.accountData?.isExpired == false
       let isActive = deviceState.accountData?.isExpired == false

       // Make sure we only trigger the event when account actually gains time
       if wasActive && isActive {
           self?.accountDidBecomeActive() // should tell coordinator when time is actually added to account
       }
   }
)
```
___
*[`ios/MullvadVPN/View controllers/ChangeLog/ChangeLogInteractor.swift` line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnrQdRAcBB7HFidXXq:-NcNcXT03-eHu_UIYZwg:bmy1oxg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/View%20controllers/ChangeLog/ChangeLogInteractor.swift#L17)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it's not a good idea to read file into view model.let's keep that in interactor
</blockquote></details>

Fine but do you think generating attributed string from within view model would be better than exposing interactor to anything more than just reading changelog and passing a String to view model?


<!-- Sent from Reviewable.io -->

2023-08-22 10:08 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 25 of 40 files reviewed, 15 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift` line 520 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NcNblFB2fHDPc-mChCR:-NcRG9tk7ovEpaJtX_ar:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/808bb3a90bd94981ed599b7054b2dedeebc5857a/ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift#L520)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Could you please extract that line into a function, next to where you have `var isLatestChangesSeen` declared in `AppPreferences`, i.e:

```swift
extension AppPreferences {
   func markChangeLogSeen() {
      lastSeenChangeLogVersion = Bundle.main.shortVersion
   }
}
```

So that we keep that logic around `Bundle.main.shortVersion` close to each other.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/App/OutOfTimeCoordinator.swift` line 78 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NcNF8HC9JmBIpSV5eyQ:-NcRhpDW9ME2MwbCXO2J:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/808bb3a90bd94981ed599b7054b2dedeebc5857a/ios/MullvadVPN/Coordinators/App/OutOfTimeCoordinator.swift#L78)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Oh I just figured out that it's a delegate method, maybe we should follow the same convention when defining delegate methods so they don't look so wildly different.

For example:

```
func <who>Did<what>(_ who: <Who>)
```

or 
```
func <who>(_ who: <Who>, did<What>: <What>)
```

__But more importantly__, we seem to have some indirection and feeding of the same data obtained from tunnel observer back into UI.

1.  As of now `OutOfTimeViewControllerDelegate` pings coordinator with two important events, when it starts and ends handling payment.
2. New delegate method was added `didUpdateDeviceState()` which in essence just loops back to delegate with some arbitrary information like device state.

What I would do differently:

1. I think coordinator could tap directly into interactor to obtain `deviceState` if it needs it. Because `OutOfTimeViewController` certainly does not need it.
2. `OutOfTimeInteractor` should not export crude data like `DeviceState` but instead should expose meaningful event. For example:

```swift
class OutOfTimeInteractor {
    // Called when account transitions from expired to active state:
    var accountDidBecomeActive: (() -> Void)?
}
```

And I think`didUpdateDeviceState` should actually check if account is transitioning from expired to active state, i.e:


```swift
let tunnelObserver = TunnelBlockObserver(
   // ... redacted...

   didUpdateDeviceState: { [weak self] tunnelManager, deviceState, previousDeviceState in
       let wasActive = previousDeviceState.accountData?.isExpired == false
       let isActive = deviceState.accountData?.isExpired == false

       // Make sure we only trigger the event when account actually gains time
       if wasActive && isActive {
           self?.accountDidBecomeActive() // should tell coordinator when time is actually added to account
       }
   }
)
```
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/ChangeLog/ChangeLogInteractor.swift` line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NbnrQdRAcBB7HFidXXq:-NcRhsMS9tknVUUHF8fU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/55b4a955c50092a3a0c064e4c1338662f340ec29/ios/MullvadVPN/View%20controllers/ChangeLog/ChangeLogInteractor.swift#L17)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Fine but do you think generating attributed string from within view model would be better than exposing interactor to anything more than just reading changelog and passing a String to view model?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-22 11:05 UTC, pronebird requested changes
> Reviewed 2 of 28 files at r2, 4 of 18 files at r3, 9 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 38 of 40 files reviewed, 15 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/AddCreditSucceededCoordinator.swift` line 49 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NcRtoS51ljg8Kjc_G9N:-NcRtoS51ljg8Kjc_G9O:b-3g5pl0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c8aa5d93f020822566360b5942b911f7b1191626/ios/MullvadVPN/Coordinators/App/AddCreditSucceededCoordinator.swift#L49)):*
> ```Swift
>     }
> 
>     func titleForAction(in controller: AddCreditSucceededViewController) -> String {
> ```

`controller` is unused. Maybe then remove it?
___
*[`ios/MullvadVPN/Coordinators/App/AddCreditSucceededCoordinator.swift` line 58 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NcRtt1yAezvWikIrs-T:-NcRtt1yAezvWikIrs-U:b-3g5pl0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c8aa5d93f020822566360b5942b911f7b1191626/ios/MullvadVPN/Coordinators/App/AddCreditSucceededCoordinator.swift#L58)):*
> ```Swift
>     }
> 
>     func header(in controller: AddCreditSucceededViewController) -> String {
> ```

`controller` is unused. Maybe then remove it?


<!-- Sent from Reviewable.io -->

2023-08-22 11:06 UTC, pronebird reviewed
> Reviewed 1 of 24 files at r1, 1 of 28 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 38 of 40 files reviewed, 15 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)



<!-- Sent from Reviewable.io -->

2023-08-22 11:07 UTC, pronebird reviewed
> Reviewed 1 of 24 files at r1, 2 of 28 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 38 of 40 files reviewed, 15 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)



<!-- Sent from Reviewable.io -->

2023-08-22 11:10 UTC, pronebird reviewed
> Reviewed 1 of 24 files at r1, 3 of 28 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 38 of 40 files reviewed, 15 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)



<!-- Sent from Reviewable.io -->

2023-08-22 11:37 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: 35 of 41 files reviewed, 15 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/App/AddCreditSucceededCoordinator.swift` line 49 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NcRtoS51ljg8Kjc_G9N:-NcRx16T8tR_tRjGn3Eq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c8aa5d93f020822566360b5942b911f7b1191626/ios/MullvadVPN/Coordinators/App/AddCreditSucceededCoordinator.swift#L49)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`controller` is unused. Maybe then remove it?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-22 12:33 UTC, rablador approved these changes
> Reviewed 9 of 18 files at r3, 1 of 2 files at r4, 10 of 10 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: all files reviewed, 13 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/Classes/AppPreferences.swift` line 50 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NcSD2HPCNMzIRxyeSQX:-NcSD2HPCNMzIRxyeSQY:bo5cpot) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/36d339eb9977eb73374a207988c7b5eabc863038/ios/MullvadVPN/Classes/AppPreferences.swift#L50)):*
> ```Swift
> 
> final class AppPreferences: AppPreferencesDataSource {
>     @AppStorage(.isShownOnboarding)
> ```

Nice :)


<!-- Sent from Reviewable.io -->

2023-08-22 12:33 UTC, rablador reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-:-NcSE9xiA5EAvJEFit0i:bnfp4nl)* status: all files reviewed, 13 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)



<!-- Sent from Reviewable.io -->

2023-08-23 09:01 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-:-NcWbz7BEr4272l4pWHU:bnfp4nl)* status: all files reviewed, 11 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2023-08-23 09:54 UTC, pronebird reviewed
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: all files reviewed, 11 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Coordinators/App/AddCreditSucceededCoordinator.swift` line 49 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NcRtoS51ljg8Kjc_G9N:-NcWn1hc3JaOaWc3jX3H:b-9omzl8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c8aa5d93f020822566360b5942b911f7b1191626/ios/MullvadVPN/Coordinators/App/AddCreditSucceededCoordinator.swift#L49)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry I realized it's a delegate. Please keep it the way you had it before.
___
*[`ios/MullvadVPN/Coordinators/App/AddCreditSucceededCoordinator.swift` line 58 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979#-NcRtt1yAezvWikIrs-T:-NcWo4Zz5j-7n3ZFdV-Y:b-vzm71r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c8aa5d93f020822566360b5942b911f7b1191626/ios/MullvadVPN/Coordinators/App/AddCreditSucceededCoordinator.swift#L58)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Done.
</blockquote></details>

My bad. It's a delegate. Delegates like to receive an object that calls them, so let's revert back to what we had. :S


<!-- Sent from Reviewable.io -->

2023-08-23 11:48 UTC, pronebird reviewed
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4979)* status: all files reviewed, 11 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2023-08-23 11:52 UTC, merged