Ensure the app fetches account data whenever it enters the new account flow view
mullvad/mullvadvpn-app pull request #4998
Opened 2023-08-09 11:46 UTC by rablador

Since it's possible to pay for account time in many ways in the app, and it's possible to do it on a completely different device, when in the new account flow, the app should try to pro-actively deduce if time has been added. So, whenever it enters a new account flow view, it should fetch new account data from the API.

2023-08-09 14:33 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998#-:-NbPhzH7-69vFYOdzN0l:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-10 07:36 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 48 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998#-NbTM0oG5G9wmb0oVA0o:-NbTM0oG5G9wmb0oVA0p:b-wa4s1t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78f683ea586cb3415973faf8cc9bbbe856c05915/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L48)):*
> ```Swift
>     }
> 
>     func startAccountUpdateTimer() {
> ```

We also need a `stopAccountUpdateTimer` method here otherwise this timer will keep running forever.

Since we tie it to `viewDidLoad` but there's no more `viewDidUnload` I would suggest moving both `startAccountUpdateTimer` (and its stop equivalent) to `viewWillAppear` and `viewWillDisappear` respectively for example


<!-- Sent from Reviewable.io -->

2023-08-10 13:00 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998#-NbUX2Gk5ZjUMIO7ZEt1:-NbUX2Gk5ZjUMIO7ZEt2:bqko35q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78f683ea586cb3415973faf8cc9bbbe856c05915/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L13)):*
> ```Swift
> 
> /// Interval used for periodic polling account updates.
> private let accountUpdateTimerInterval: TimeInterval = 60
> ```

I think it belongs the scope of interactor.
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 48 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998#-NbTM0oG5G9wmb0oVA0o:-NbUWHuR3dlr7i3d8oY2:bil8g0o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78f683ea586cb3415973faf8cc9bbbe856c05915/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L48)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We also need a `stopAccountUpdateTimer` method here otherwise this timer will keep running forever.

Since we tie it to `viewDidLoad` but there's no more `viewDidUnload` I would suggest moving both `startAccountUpdateTimer` (and its stop equivalent) to `viewWillAppear` and `viewWillDisappear` respectively for example
</blockquote></details>

can't he stop the timer on the deinit of interactor instead of `viewWillDisappear` ? if it is going to be placed on `viewWillAppear` please be sure it's not revoked multiple times on view life cycle


<!-- Sent from Reviewable.io -->

2023-08-10 14:02 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998#-NbUX2Gk5ZjUMIO7ZEt1:-NbUji5kA7T87c27jXRh:b-79jju8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78f683ea586cb3415973faf8cc9bbbe856c05915/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L13)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I think it belongs the scope of interactor.
</blockquote></details>

Good catch ! Yes please don't make it a global
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 48 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998#-NbTM0oG5G9wmb0oVA0o:-NbUjpQ8CzzI8RDl2w3y:b-yolp90) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78f683ea586cb3415973faf8cc9bbbe856c05915/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L48)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

can't he stop the timer on the deinit of interactor instead of `viewWillDisappear` ? if it is going to be placed on `viewWillAppear` please be sure it's not revoked multiple times on view life cycle
</blockquote></details>

Good point, that would be equally good. Please do test that the `WelcomeInteractor` gets properly deallocated if we go that way.

As a side note, I usually don't like to put code in `deinit` because it's hard to write unit tests for.
So I would still prefer if we avoid that, but if we go the `deinit` way, let's not make it a habit. 


<!-- Sent from Reviewable.io -->

2023-08-11 08:44 UTC, pronebird reviewed
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 48 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998#-NbTM0oG5G9wmb0oVA0o:-NbYlALo5Zf0XpKaQ8y-:bctwve1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78f683ea586cb3415973faf8cc9bbbe856c05915/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L48)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Good point, that would be equally good. Please do test that the `WelcomeInteractor` gets properly deallocated if we go that way.

As a side note, I usually don't like to put code in `deinit` because it's hard to write unit tests for.
So I would still prefer if we avoid that, but if we go the `deinit` way, let's not make it a habit. 
</blockquote></details>

I somewhat agree that it would be better to use view lifecycle for that so that even if we have a bug or leak, that we don't bombard our server with requests


<!-- Sent from Reviewable.io -->

2023-08-11 08:51 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998#-NbUX2Gk5ZjUMIO7ZEt1:-NbYeYdQ9y7YvuxF643U:b2ij78o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78f683ea586cb3415973faf8cc9bbbe856c05915/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L13)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Good catch ! Yes please don't make it a global
</blockquote></details>

Just following the same pattern from similar use case elsewhere. I can scope it though.
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift` line 48 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998#-NbTM0oG5G9wmb0oVA0o:-NbYmXowBDPzkezOabz-:bvb18t5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/78f683ea586cb3415973faf8cc9bbbe856c05915/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeInteractor.swift#L48)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I somewhat agree that it would be better to use view lifecycle for that so that even if we have a bug or leak, that we don't bombard our server with requests
</blockquote></details>

Fixed! Also updated OutOfTimeInteractor (which has a similar timer) with a stop function as well.


<!-- Sent from Reviewable.io -->

2023-08-16 08:55 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998#-:-NbxYcv1ESfmyrNhnWKM:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2023-08-16 19:00 UTC, merged