CI: use xcode test-plan
mullvad/mullvadvpn-app pull request #5017
Opened 2023-08-16 19:08 UTC by pronebird

The CI tests have been broken since introduction of test plans. This PR fixes the GH integration with the following amends:

- Disable: MullvadVPNScreenshots -- this is the target used by fastlane snapshot. This won't work on CI and needs further discussion
- Add PacketTunnelCoreTests to test plan

2023-08-17 07:39 UTC, rablador requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5017)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/TestPlans/MullvadVPNCI.xctestplan` line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5017#-Nc1QiQUCuYjL7C4dm5S:-Nc1QiQV0hxdbpiRsmis:b-kupqfd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8596203f672b3ae1d96aff6d3ab0a1567902f8f/ios/TestPlans/MullvadVPNCI.xctestplan#L61)):*
> ```
>     },
>     {
>       "target" : {
> ```

Why is this not parallelizable?


<!-- Sent from Reviewable.io -->

2023-08-17 07:39 UTC, rablador reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5017)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-08-17 11:14 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5017)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/TestPlans/MullvadVPNCI.xctestplan` line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5017#-Nc1QiQUCuYjL7C4dm5S:-Nc2BvoD2qrRREKFb2-U:b-omy51f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e8596203f672b3ae1d96aff6d3ab0a1567902f8f/ios/TestPlans/MullvadVPNCI.xctestplan#L61)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Why is this not parallelizable?
</blockquote></details>

Fixed. Also converted all targets to TestPlan


<!-- Sent from Reviewable.io -->

2023-08-17 11:48 UTC, pronebird reviewed
I found that CI was indeed functional however xcpretty does not understand an output from parallel testing so it simply swallowed it. I have replaced xcpretty with xcbeautify which seems to work just fine.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5017#-:-Nc2JmjW8f8L7P4jrXSr:b6qprj8)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-08-18 09:10 UTC, rablador approved these changes
> Reviewed 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5017)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-18 10:23 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5017)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-18 10:37 UTC, merged