Coordinate alert presentation
mullvad/mullvadvpn-app pull request #5044
Opened 2023-08-24 13:20 UTC by rablador

Part of the codebase still displays alerts using AlertPresenter, which is not coordinated with the app router and could potentially break the UI.

We should make sure that alerts are exclusive and that no other route is presented above them, and also that the routing/coordinator system is somehow aware of them.

2023-08-29 09:13 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-:-Nd-ZPOg3i83i9Q27xw5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-08-29 11:09 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/MullvadVPN/View controllers/Alert/AlertPresentation.swift` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-Nd-Vwu64mvU2z-jaij9:-Nd-wGKS4vB2Nbr44256:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c42cb2d2d794a558cd398390e19cbd51448d74c9/ios/MullvadVPN/View%20controllers/Alert/AlertPresentation.swift#L12)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think you don't necessarily have to use `ObjectIdentifier(NSUUID())`. You could probably do `var id = UUID()` since `UUID` is `Hashable` and that's the only requirement set by `Identifiable`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-29 12:42 UTC, pronebird reviewed
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-29 13:21 UTC, pronebird reviewed
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-30 08:15 UTC, pronebird commented
Please rebase

2023-08-30 12:20 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 19 of 28 files reviewed, 1 unresolved discussion (waiting on @pronebird and @rablador)

___
*[`ios/Untitled-1.diff` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-Nd5N0Hz3zvUutyGlOyU:-Nd5N0Hz3zvUutyGlOyV:bkmhtd5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22e18e5bfab538bc4f7138a5f368dcbc51efd27c/ios/Untitled-1.diff#L1)):*
> ```Diff
> diff --git a/ios/MullvadVPN/Classes/AppRoutes.swift b/ios/MullvadVPN/Classes/AppRoutes.swift
> ```

It looks like you accidentally commited the diff file


<!-- Sent from Reviewable.io -->

2023-08-30 12:20 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 19 of 28 files reviewed, 1 unresolved discussion (waiting on @pronebird and @rablador)

___
*[`ios/Untitled-1.diff` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-Nd5N0Hz3zvUutyGlOyU:-Nd5Nn6UClu2WrEqEHQJ:bypeag5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22e18e5bfab538bc4f7138a5f368dcbc51efd27c/ios/Untitled-1.diff#L1)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It looks like you accidentally commited the diff file
</blockquote></details>

but <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> otherwise !


<!-- Sent from Reviewable.io -->

2023-08-30 12:56 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 19 of 28 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @pronebird)

___
*[`ios/Untitled-1.diff` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-Nd5N0Hz3zvUutyGlOyU:-Nd5W3jC1wAVbbG150g_:bt2vr0y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22e18e5bfab538bc4f7138a5f368dcbc51efd27c/ios/Untitled-1.diff#L1)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

but <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> otherwise !
</blockquote></details>

Fixed!


<!-- Sent from Reviewable.io -->

2023-08-31 07:19 UTC, buggmagnet approved these changes
> Reviewed 3 of 23 files at r2, 1 of 5 files at r3, 3 of 9 files at r6, 4 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 22 of 28 files reviewed, 1 unresolved discussion (waiting on @pronebird and @rablador)

___
*[`ios/Untitled-1.diff` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-Nd5N0Hz3zvUutyGlOyU:-Nd9SULh8SDhsZRm9uE2:bjhfo7n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22e18e5bfab538bc4f7138a5f368dcbc51efd27c/ios/Untitled-1.diff#L1)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Fixed!
</blockquote></details>

:cool: <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> :flamingo: :rainbow: :unicorn: 


<!-- Sent from Reviewable.io -->

2023-08-31 14:18 UTC, pronebird requested changes
> Reviewed 1 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 23 of 28 files reviewed, 2 unresolved discussions (waiting on @rablador)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdAw8yB2ArArJi-TbpV:-NdAw8yC1rCs3pFg9MeZ:b2tvc71) (no related file):*
As Marco reported today: alert is handled by app coordinator and presented by app coordinator, however it doesn't know how deep the modal stack is. 

Currently there is a cute trick in `Presenting` implementation of `ApplicationCoordinator` which doesn't work if we have more than 2 modals above:

```swift
// ApplicationCoordinator.swift
var presentationContext: UIViewController {
    primaryNavigationContainer.presentedViewController ?? primaryNavigationContainer
}
```

One idea is how to tackle this is to use present alerts from coordinator requesting them instead of app coordinator.

___


<!-- Sent from Reviewable.io -->

2023-08-31 14:23 UTC, pronebird requested changes
> Reviewed 1 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 23 of 28 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Alert/AlertPresentation.swift` line 18 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdAxzpo1ma2bLNpbAag:-NdAxzpo1ma2bLNpbAah:b-dovpcc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72691ac67e6ea48a9bc990bd08b1af0205d405d8/ios/MullvadVPN/View%20controllers/Alert/AlertPresentation.swift#L18)):*
> ```Swift
> 
> struct AlertPresentation: Identifiable, CustomDebugStringConvertible {
>     let id = UUID()
> ```

We should look into using unique names (i.e `device-info-alert`) instead of random UUID() because the routing system should filter out duplicate routes if we have multiple of them queued up one after another.


<!-- Sent from Reviewable.io -->

2023-08-31 14:23 UTC, pronebird reviewed
> Reviewed 3 of 9 files at r6, 2 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 25 of 28 files reviewed, 3 unresolved discussions (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-09-01 13:20 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 8 of 29 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @pronebird)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdAw8yB2ArArJi-TbpV:-NdFqw_J4o2vQESpd0Ef:b-896fix) (no related file):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

As Marco reported today: alert is handled by app coordinator and presented by app coordinator, however it doesn't know how deep the modal stack is. 

Currently there is a cute trick in `Presenting` implementation of `ApplicationCoordinator` which doesn't work if we have more than 2 modals above:

```swift
// ApplicationCoordinator.swift
var presentationContext: UIViewController {
    primaryNavigationContainer.presentedViewController ?? primaryNavigationContainer
}
```

One idea is how to tackle this is to use present alerts from coordinator requesting them instead of app coordinator.
</blockquote></details>

Done.

___
___
*[`ios/MullvadVPN/View controllers/Alert/AlertPresentation.swift` line 18 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdAxzpo1ma2bLNpbAag:-NdFqyFP-obx9vSAKMTZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72691ac67e6ea48a9bc990bd08b1af0205d405d8/ios/MullvadVPN/View%20controllers/Alert/AlertPresentation.swift#L18)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

We should look into using unique names (i.e `device-info-alert`) instead of random UUID() because the routing system should filter out duplicate routes if we have multiple of them queued up one after another.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-04 09:37 UTC, pronebird reviewed
> Reviewed 2 of 9 files at r6, 2 of 18 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 12 of 29 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/Alert/AlertPresenter.swift` line 19 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdUX-kM7m7cU_3v1Acv:-NdUX-kM7m7cU_3v1Acw:b6mdbqz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/MullvadVPN/View%20controllers/Alert/AlertPresenter.swift#L19)):*
> ```Swift
> 
>     func dismissAlert(presentation: AlertPresentation, animated: Bool) {
>         context.applicationRouter?.dismiss(.alert(presentation, context), animated: animated)
> ```

FYI I still think that `AppRoute.alert(<id>)` should only carry ID and nothing else and metadata should be passed alongside via call to `present(.., animated: ..., metadata: ..., ...)` because to dismiss the alert the one has to construct the entire `AlertPresentation` which at least violates interface segregation from SOLID because the router only need an id to identify the presented route and it doesn't need button handlers or any other things. It works for current scenario where you have `AlertPresentation` handy but it won't work for contexts where you don't have it around.


<!-- Sent from Reviewable.io -->

2023-09-04 09:43 UTC, pronebird requested changes
> Reviewed 2 of 18 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 14 of 29 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/Routing/Coordinator.swift` line 111 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdUZLRi8SoY9UOFW7DB:-NdUZLRi8SoY9UOFW7DC:bimc6wi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/Routing/Coordinator.swift#L111)):*
> ```Swift
>     public func presentChild(
>         _ child: some Presentable,
>         context: (any Presenting)? = nil,
> ```

Context is `self` in this case. Maybe call `presentChild` on the coordinator that is supposed to present modal?


<!-- Sent from Reviewable.io -->

2023-09-04 09:49 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 14 of 29 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Coordinators/InAppPurchaseCoordinator.swift` line 14 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdUZx_14cnVkeb3p8cY:-NdUZx_14cnVkeb3p8cZ:b-tgo3i8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/MullvadVPN/Coordinators/InAppPurchaseCoordinator.swift#L14)):*
> ```Swift
> import UIKit
> 
> class InAppPurchaseCoordinator: Coordinator, Presenting, Presentable {
> ```

FYI thinking that we could provide default implementation of`Presenting` when `Self: Presentable`

```swift
extension Presenting where Self: Presentable {
    public var presentationContext: UIViewController {
        return presentedViewController
    }
}
```


<!-- Sent from Reviewable.io -->

2023-09-04 09:58 UTC, pronebird requested changes
> Reviewed 3 of 18 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 17 of 29 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 658 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdUbhlp-3CBHpNrFpBl:-NdUbhlp-3CBHpNrFpBm:b-ffz9bu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L658)):*
> ```Swift
> 
>         let context = (context as? (any Presenting))
>         presentChild(coordinator, context: context, animated: animated) {
> ```

Why not `context.presentChild`? Perhaps add a requirement for context to be `Presenting`


<!-- Sent from Reviewable.io -->

2023-09-04 14:05 UTC, buggmagnet requested changes
> Reviewed 1 of 19 files at r1, 10 of 18 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 24 of 29 files reviewed, 7 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Coordinators/WelcomeCoordinator.swift` line 88 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdVP8vV0zfxN1CunxQm:-NdVP8vW1CehFCTBB30w:bpuwaqk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/MullvadVPN/Coordinators/WelcomeCoordinator.swift#L88)):*
> ```Swift
>     func didRequestToShowInfo(controller: WelcomeViewController) {
>         let message = NSLocalizedString(
>             "WELCOME_DEVICE_CONCEPET_TEXT_DIALOG",
> ```

FYI Typo
`CONCEPET`
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 137 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdVR6Q3A2Q-_65kDmMN:-NdVR6Q3A2Q-_65kDmMO:bv0usyo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L137)):*
> ```Swift
>                 value: """
>                     When this feature is enabled it stops the device from contacting certain \
>                     domains or websites known for distributing ads, malware, trackers and more. \
> ```

There is a visual regression here because of the extra space 
![Screenshot 2023-09-04 at 15.44.22.png](https://files.reviewableusercontent.io/images/reviewable/129761703/mrqEWTlAdxk_wG_hHdgFWfYZ/Screenshot%202023-09-04%20at%2015.44.22.png)
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 148 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdVRdWs4oQZomHOB9sc:-NdVRdWs4oQZomHOB9sd:b-jt9a0l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L148)):*
> ```Swift
>                 tableName: "ContentBlockers",
>                 value: """
>                     Warning: The malware blocker is not an anti-virus and should not be treated as such, \
> ```

Here too
![Screenshot 2023-09-04 at 15.47.09.png](https://files.reviewableusercontent.io/images/reviewable/129761703/reQxeWHPRdkMpf2gTDc0kcy1/Screenshot%202023-09-04%20at%2015.47.09.png)
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 181 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdVRQyUBS6Ruu4eBExk:-NdVRQyUBS6Ruu4eBExl:b-usssx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L181)):*
> ```Swift
>                 tableName: "WireGuardObfuscation",
>                 value: """
>                     Obfuscation hides the WireGuard traffic inside another protocol. \
> ```

Here too 
![Screenshot 2023-09-04 at 15.45.57.png](https://files.reviewableusercontent.io/images/reviewable/129761703/zk9BKc-FHysFYzbjNnR41LDa/Screenshot%202023-09-04%20at%2015.45.57.png)
___
*[`ios/Untitled-1.diff` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-Nd5N0Hz3zvUutyGlOyU:-NdVVepQ44-pd-mbGmOB:b-l51cls) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22e18e5bfab538bc4f7138a5f368dcbc51efd27c/ios/Untitled-1.diff#L1)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

:cool: <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> :flamingo: :rainbow: :unicorn:
</blockquote></details>

It looks like we introduced visual regressions by fixing linter bugs. 
I suggest to remove the fixes for linting and fix them in a separate PR instead.


<!-- Sent from Reviewable.io -->

2023-09-04 21:58 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 24 of 29 files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/WelcomeCoordinator.swift` line 88 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdVP8vV0zfxN1CunxQm:-NdXBzBh3S59t9eSZqoC:b44tpx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/MullvadVPN/Coordinators/WelcomeCoordinator.swift#L88)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

FYI Typo
`CONCEPET`
</blockquote></details>

👍
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 137 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdVR6Q3A2Q-_65kDmMN:-NdXBoMLERj24NWGpd5a:b-bqivd7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L137)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

There is a visual regression here because of the extra space 
![Screenshot 2023-09-04 at 15.44.22.png](https://files.reviewableusercontent.io/images/reviewable/129761703/mrqEWTlAdxk_wG_hHdgFWfYZ/Screenshot%202023-09-04%20at%2015.44.22.png)
</blockquote></details>

Will fix!
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 148 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdVRdWs4oQZomHOB9sc:-NdXBrUp-h75Uv76UF_3:b-bqivd7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L148)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Here too
![Screenshot 2023-09-04 at 15.47.09.png](https://files.reviewableusercontent.io/images/reviewable/129761703/reQxeWHPRdkMpf2gTDc0kcy1/Screenshot%202023-09-04%20at%2015.47.09.png)
</blockquote></details>

Will fix!
___
*[`ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift` line 181 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdVRQyUBS6Ruu4eBExk:-NdXBs-R4R0htMej1p6w:b-bqivd7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/MullvadVPN/View%20controllers/Preferences/PreferencesViewController.swift#L181)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Here too 
![Screenshot 2023-09-04 at 15.45.57.png](https://files.reviewableusercontent.io/images/reviewable/129761703/zk9BKc-FHysFYzbjNnR41LDa/Screenshot%202023-09-04%20at%2015.45.57.png)
</blockquote></details>

Will fix!


<!-- Sent from Reviewable.io -->

2023-09-06 13:47 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 13 of 31 files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 658 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdUbhlp-3CBHpNrFpBl:-NdegkHT0-nH6YBYquBX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L658)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Why not `context.presentChild`? Perhaps add a requirement for context to be `Presenting`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/InAppPurchaseCoordinator.swift` line 14 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdUZx_14cnVkeb3p8cY:-NdeiY3b68_BsqCbh5V-:b-pbdqz3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/MullvadVPN/Coordinators/InAppPurchaseCoordinator.swift#L14)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI thinking that we could provide default implementation of`Presenting` when `Self: Presentable`

```swift
extension Presenting where Self: Presentable {
    public var presentationContext: UIViewController {
        return presentedViewController
    }
}
```
</blockquote></details>

Agreed.
___
*[`ios/MullvadVPN/View controllers/Alert/AlertPresenter.swift` line 19 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdUX-kM7m7cU_3v1Acv:-NdegtEM2zbrCEZkalmY:b-d1t42r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/MullvadVPN/View%20controllers/Alert/AlertPresenter.swift#L19)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI I still think that `AppRoute.alert(<id>)` should only carry ID and nothing else and metadata should be passed alongside via call to `present(.., animated: ..., metadata: ..., ...)` because to dismiss the alert the one has to construct the entire `AlertPresentation` which at least violates interface segregation from SOLID because the router only need an id to identify the presented route and it doesn't need button handlers or any other things. It works for current scenario where you have `AlertPresentation` handy but it won't work for contexts where you don't have it around.
</blockquote></details>

Implementation changed to reflect this.
___
*[`ios/Routing/Coordinator.swift` line 111 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdUZLRi8SoY9UOFW7DB:-Nd_8WHD1gwJaxTHiG2e:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a26e42425e944a99f5b1b8c7ab8dee48a959f24/ios/Routing/Coordinator.swift#L111)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Context is `self` in this case. Maybe call `presentChild` on the coordinator that is supposed to present modal?
</blockquote></details>

Done.
___
*[`ios/Untitled-1.diff` line 1 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-Nd5N0Hz3zvUutyGlOyU:-Nd_8YRE-ZADZULFH4Ho:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22e18e5bfab538bc4f7138a5f368dcbc51efd27c/ios/Untitled-1.diff#L1)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It looks like we introduced visual regressions by fixing linter bugs. 
I suggest to remove the fixes for linting and fix them in a separate PR instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-06 14:17 UTC, pronebird requested changes
> Reviewed 1 of 9 files at r6, 11 of 18 files at r8, 13 of 16 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 30 of 31 files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 652 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-Ndep6VVAAtpzjrQ2qBQ:-Ndep6VWCWAXtg79obdL:bfimrdq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bbd7a748557539ec4a83a6dc83845cfda19a9c3/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L652)):*
> ```Swift
> 
>         coordinator.didFinish = { [weak self] in
>             self?.router.dismiss(.alert(metadata.presentation.id))
> ```

You could use `router.dismiss(context.route)` here.
___
*[`ios/Routing/Router/ApplicationRouterTypes.swift` line 20 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdepeWhBFIAaVxKbnKl:-NdepeWhBFIAaVxKbnKm:bcnjhpg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bbd7a748557539ec4a83a6dc83845cfda19a9c3/ios/Routing/Router/ApplicationRouterTypes.swift#L20)):*
> ```Swift
> }
> 
> extension PendingRoute: Equatable {
> ```

FYI I realize `Any?` and `Equatable` aren't best friends.. I hope this impl not gonna cause some ruckus vs. what we had before.
___
*[`ios/Routing/Router/ApplicationRouterTypes.swift` line 192 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdeqTPd0qPrSAFpIPQL:-NdeqTPd0qPrSAFpIPQM:b-ubdy5u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bbd7a748557539ec4a83a6dc83845cfda19a9c3/ios/Routing/Router/ApplicationRouterTypes.swift#L192)):*
> ```Swift
> 
> extension RoutePresentationContext: Equatable {
>     public static func == (lhs: RoutePresentationContext<RouteType>, rhs: RoutePresentationContext<RouteType>) -> Bool {
> ```

If you don't use `Equatable` with `RoutePresentationContext` then perhaps you don't have to implement it.


<!-- Sent from Reviewable.io -->

2023-09-06 14:19 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 30 of 31 files reviewed, 9 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/Routing/Router/ApplicationRouter.swift` line 56 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-Ndeqk3YCzl-AmvM2tpH:-Ndeqk3YCzl-AmvM2tpI:b-sjzrml) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bbd7a748557539ec4a83a6dc83845cfda19a9c3/ios/Routing/Router/ApplicationRouter.swift#L56)):*
> ```Swift
>      Enqueue route for presetnation.
>      */
>     public func present(_ route: RouteType, animated: Bool = true) {
> ```

I think that we should accept `metadata: Any? = nil` in here. Then the mullvad vpn app could define a strictly typed helper to present alerts, i.e:

```swift
extension ApplicationRouter<AppRoute> {
    func presentAlert(animated: Bool = true, metadata: AlertMetadata) {
        present(.alert(metadata.alertPresentation.id), animated: animated, metadata: metadata)
    }
}
```
___
*[`ios/Routing/Router/ApplicationRouter.swift` line 381 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdeqgBl3-A7gGIGeUEG:-NdeqgBl3-A7gGIGeUEH:brzrutb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bbd7a748557539ec4a83a6dc83845cfda19a9c3/ios/Routing/Router/ApplicationRouter.swift#L381)):*
> ```Swift
> 
> extension ApplicationRouter {
>     public func presentAlert(route: RouteType, metadata: Any) {
> ```

Should be in MullvadVPN as it's impl. detail of our app.


<!-- Sent from Reviewable.io -->

2023-09-06 14:19 UTC, pronebird reviewed
> Reviewed 1 of 16 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: all files reviewed, 9 unresolved discussions (waiting on @buggmagnet and @rablador)



<!-- Sent from Reviewable.io -->

2023-09-06 14:29 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: all files reviewed, 9 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift` line 652 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-Ndep6VVAAtpzjrQ2qBQ:-Ndes402DKXb8MOxFIWT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bbd7a748557539ec4a83a6dc83845cfda19a9c3/ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift#L652)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

You could use `router.dismiss(context.route)` here.
</blockquote></details>

Done.
___
*[`ios/Routing/Router/ApplicationRouter.swift` line 56 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-Ndeqk3YCzl-AmvM2tpH:-Ndes9ZLDayNtygoqL67:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bbd7a748557539ec4a83a6dc83845cfda19a9c3/ios/Routing/Router/ApplicationRouter.swift#L56)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I think that we should accept `metadata: Any? = nil` in here. Then the mullvad vpn app could define a strictly typed helper to present alerts, i.e:

```swift
extension ApplicationRouter<AppRoute> {
    func presentAlert(animated: Bool = true, metadata: AlertMetadata) {
        present(.alert(metadata.alertPresentation.id), animated: animated, metadata: metadata)
    }
}
```
</blockquote></details>

Done.
___
*[`ios/Routing/Router/ApplicationRouter.swift` line 381 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdeqgBl3-A7gGIGeUEG:-NdesAbyDPTj_Lh0ScTb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bbd7a748557539ec4a83a6dc83845cfda19a9c3/ios/Routing/Router/ApplicationRouter.swift#L381)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Should be in MullvadVPN as it's impl. detail of our app.
</blockquote></details>

Done.
___
*[`ios/Routing/Router/ApplicationRouterTypes.swift` line 20 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdepeWhBFIAaVxKbnKl:-NdesDe20dPui2lBSDWL:bff2dcc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bbd7a748557539ec4a83a6dc83845cfda19a9c3/ios/Routing/Router/ApplicationRouterTypes.swift#L20)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI I realize `Any?` and `Equatable` aren't best friends.. I hope this impl not gonna cause some ruckus vs. what we had before.
</blockquote></details>

They sure aren't. I'm thinking operation should be enough to distinguish PendingRoutes though. It's essentially the same as before the change.
___
*[`ios/Routing/Router/ApplicationRouterTypes.swift` line 192 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdeqTPd0qPrSAFpIPQL:-NdetJR32R80S3ktUebe:b-qbrdyx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bbd7a748557539ec4a83a6dc83845cfda19a9c3/ios/Routing/Router/ApplicationRouterTypes.swift#L192)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

If you don't use `Equatable` with `RoutePresentationContext` then perhaps you don't have to implement it.
</blockquote></details>

Hmm, this was removed earlier. Have I missed pushing a revision?


<!-- Sent from Reviewable.io -->

2023-09-06 15:39 UTC, pronebird requested changes
> Reviewed 11 of 15 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 27 of 31 files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Classes/AppRoutes.swift` line 97 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-Ndf71eyBI59Ojz4q0W2:-Ndf71ez5U5dBWVEntg3:betlpy7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/974f5c3c2df9464a767cc617f4b5c10f63648600/ios/MullvadVPN/Classes/AppRoutes.swift#L97)):*
> ```Swift
>      Alert route.
>      */
>     case alert(String)
> ```

You probably still want a unique ID within `.alert` case, so that queueing up two unique alerts in a row wouldn't result in the latter being dropped because the former is still being presented. (`alert` == `alert` but `alert("a") != alert("b")`
___
*[`ios/MullvadVPN/View controllers/Alert/AlertPresenter.swift` line 27 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-Ndf5zPp-xnczskBhn4l:-Ndf5zPp-xnczskBhn4m:b-u6dmdh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eca7ee572befff28a75f1aa01d96e0cf1c0d6971/ios/MullvadVPN/View%20controllers/Alert/AlertPresenter.swift#L27)):*
> ```Swift
> 
> extension ApplicationRouter {
>     func presentAlert(route: RouteType, metadata: Any) {
> ```

You probably meant to have this implemented like this:

```swift
func presentAlert(identifier: String, animated: Bool, metadata: AlertMetadata)  {
  present(.alert(identifier), animated: animated, metadata: metadata)
}
```

This way you have strictly typed metadata and `.alert` route supplied together, a bond between them two. Poor man' associated value.
___
*[`ios/Routing/Router/ApplicationRouterTypes.swift` line 192 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdeqTPd0qPrSAFpIPQL:-Ndf5odo8599Zdt7Q9_w:bfrvjre) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8bbd7a748557539ec4a83a6dc83845cfda19a9c3/ios/Routing/Router/ApplicationRouterTypes.swift#L192)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Hmm, this was removed earlier. Have I missed pushing a revision?
</blockquote></details>

Probably. Nevermind.


<!-- Sent from Reviewable.io -->

2023-09-06 15:40 UTC, pronebird reviewed
> Reviewed 1 of 15 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 28 of 31 files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @rablador)



<!-- Sent from Reviewable.io -->

2023-09-08 08:32 UTC, pronebird reviewed
> Reviewed 2 of 15 files at r11, 1 of 12 files at r12.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 17 of 32 files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Operations/PresentAlertOperation.swift` line 12 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdnnEzJ1UUwahBeMWZ2:-NdnnEzJ1UUwahBeMWZ3:bdozvr8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/350719c2879dd4cf0272d5f4e86c0c9c0c8138c9/ios/MullvadVPN/Operations/PresentAlertOperation.swift#L12)):*
> ```Swift
> import UIKit
> 
> final class PresentAlertOperation: AsyncOperation {
> ```

FYI technically if you present alerts with the router now then you could remove that operation. It was specifically use to sequence alerts.
___
*[`ios/MullvadVPN/View controllers/Alert/AlertPresenter.swift` line 17 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdnnjYpDe8owtJyMSiz:-NdnnjYpDe8owtJyMSj-:b8glcan) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/caf5d2fd41c01dcad2c2211be22ca8aee30a03f7/ios/MullvadVPN/View%20controllers/Alert/AlertPresenter.swift#L17)):*
> ```Swift
>         context.applicationRouter?.presentAlert(
>             route: .alert(presentation.id),
>             animated: true,
> ```

Nit: `animated` is passed as an argument to `showAlert()` but not used. Perhaps feed it into `presentAlert()`


<!-- Sent from Reviewable.io -->

2023-09-08 08:39 UTC, pronebird reviewed
> Reviewed 9 of 12 files at r12, 5 of 6 files at r13, 1 of 1 files at r14, 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Classes/AppRoutes.swift` line 97 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-Ndf71eyBI59Ojz4q0W2:-Ndnv6zLBBzexG5zuo1x:b-n2q58y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/974f5c3c2df9464a767cc617f4b5c10f63648600/ios/MullvadVPN/Classes/AppRoutes.swift#L97)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nit: It would be amiss of me to not mention that you could describe in the comment that the string value must be a unique string used to distinguish between different kinds of alerts used within the app and that it's used to produce a unique route (alert+<string>). Also switch cases support providing anonymous labels as hints, i.e `alert(_ alertId: String)`. But it's fully optional.


<!-- Sent from Reviewable.io -->

2023-09-08 08:58 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Classes/AppRoutes.swift` line 97 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-Ndf71eyBI59Ojz4q0W2:-Ndo-nAyBYdfmh63IT16:b-896fiz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/974f5c3c2df9464a767cc617f4b5c10f63648600/ios/MullvadVPN/Classes/AppRoutes.swift#L97)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: It would be amiss of me to not mention that you could describe in the comment that the string value must be a unique string used to distinguish between different kinds of alerts used within the app and that it's used to produce a unique route (alert+<string>). Also switch cases support providing anonymous labels as hints, i.e `alert(_ alertId: String)`. But it's fully optional.
</blockquote></details>

Done,
___
*[`ios/MullvadVPN/Operations/PresentAlertOperation.swift` line 12 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdnnEzJ1UUwahBeMWZ2:-Ndnx2At3_vrNZCRXrYa:bejctyg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/350719c2879dd4cf0272d5f4e86c0c9c0c8138c9/ios/MullvadVPN/Operations/PresentAlertOperation.swift#L12)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI technically if you present alerts with the router now then you could remove that operation. It was specifically use to sequence alerts.
</blockquote></details>

Seems it was removed from project but now from disk. Will fix.
___
*[`ios/MullvadVPN/View controllers/Alert/AlertPresenter.swift` line 17 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-NdnnjYpDe8owtJyMSiz:-Ndny6Jt6g94W3mChIOM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/caf5d2fd41c01dcad2c2211be22ca8aee30a03f7/ios/MullvadVPN/View%20controllers/Alert/AlertPresenter.swift#L17)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: `animated` is passed as an argument to `showAlert()` but not used. Perhaps feed it into `presentAlert()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-08 12:05 UTC, pronebird reviewed
> Reviewed 1 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 29 of 32 files reviewed, 4 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2023-09-08 12:05 UTC, pronebird reviewed
> Reviewed 1 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 30 of 32 files reviewed, 4 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2023-09-12 13:18 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 7 files at r17, 2 of 2 files at r19, 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-:-Ne8XgDcASKPDFoycSms:bnfp4nl)* status: 35 of 36 files reviewed, 4 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2023-09-13 12:47 UTC, pronebird reviewed
> Reviewed 1 of 3 files at r18, 3 of 3 files at r21, 1 of 11 files at r22.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044)* status: 27 of 37 files reviewed, 4 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2023-09-13 14:25 UTC, buggmagnet approved these changes
Great job ! <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 2 of 23 files at r2, 1 of 5 files at r3, 3 of 16 files at r9, 1 of 2 files at r10, 2 of 15 files at r11, 8 of 12 files at r12, 3 of 6 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, 2 of 4 files at r16, 4 of 7 files at r17, 1 of 3 files at r18, 1 of 2 files at r19, 1 of 3 files at r21, 10 of 11 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5044#-:-NeDvgaBDTTll2RbkR-P:b-hkixnc)* status: 36 of 37 files reviewed, 1 unresolved discussion (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-09-13 14:28 UTC, merged