[WIP] Google play in app purchases
mullvad/mullvadvpn-app pull request #5125
Opened 2023-09-07 07:17 UTC by Pururun

Working PR for in app billing.

2023-11-09 09:45 UTC, albin-mullvad requested changes
> Reviewed 1 of 10 files at r1, 3 of 15 files at r12, 1 of 2 files at r13, 5 of 58 files at r21, 2 of 3 files at r26, 7 of 59 files at r29, 8 of 11 files at r30, 29 of 62 files at r31, 4 of 6 files at r32, 1 of 1 files at r41, 1 of 1 files at r42, 1 of 11 files at r44, 6 of 57 files at r45.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 30 of 95 files reviewed, 12 unresolved discussions (waiting on @Pururun and @sabercodic)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinRpJwBp4vOTSu5EzF:-NinRpJxAb28EbsaC3Ew:b-nwcxip) (no related file):*
Since this PR is rather large, I'll split my review up into multiple parts. Here are some initial comments:

___
___
*[`android/build.gradle.kts` line 2 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nijasmt1E7JhaJlMEiT:-Nijasmt1E7JhaJlMEiU:bfwxz72) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f7b581ba3633c8ea645211197311890702c55a6/android/build.gradle.kts#L2)):*
> ```Kotlin
> import com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask
> ```

Was this auto-formatted? Unless enforced by some formatting script this should probably be reverted.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt` line 5 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijbLKBB8MGgfliUUvV:-NijbLKBB8MGgfliUUvW:b8wbjs9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt#L5)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.lib.payment.PaymentRepository
> 
> // Just an example:
> ```

I guess this one should be cleaned up? At least the comments, which I believe I wrote :laughing: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/LoadingDialog.kt` line 22 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijiBA_7c06Gqu70orH:-NijiBA_7c06Gqu70orI:b-5dsix1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/LoadingDialog.kt#L22)):*
> ```Kotlin
> 
> @Composable
> fun LoadingDialog(
> ```

Does it make sense for this to be its own dialog? Seems like this could be a variant/state of some existing dialog. For instance, it seems to me like the transitions to and from this could end up being a bit strange :thinking:

I suggest we discuss this in the team before making any changes.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/OutOfTimeUiState.kt` line 9 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nijbr1O-qrLNGD0vLcj:-Nijbr1O-qrLNGD0vLck:b-9jxxtd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/OutOfTimeUiState.kt#L9)):*
> ```Kotlin
>     val tunnelState: TunnelState = TunnelState.Disconnected,
>     val deviceName: String = "",
>     val billingPaymentState: PaymentState = PaymentState.Loading,
> ```

Can you elaborate on how this works? Why is the default state "loading"?



_Code quote:_
```Kotlin
PaymentState.Loading
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/WelcomeDialogState.kt` line 3 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nijjlx591Q0NMRqwszf:-Nijjlx591Q0NMRqwszg:b-f6exhx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/WelcomeDialogState.kt#L3)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.compose.state
> 
> sealed interface WelcomeDialogState {
> ```

We also have a device info dialog on this screen now. Do these different dialog states play along nicely?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/WelcomeUiState.kt` line 10 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nijk1wF2ce6d3xu8egA:-Nijk1wF2ce6d3xu8egB:b-pcalmo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/WelcomeUiState.kt#L10)):*
> ```Kotlin
>     val accountNumber: String? = null,
>     val deviceName: String? = null,
>     val billingPaymentState: PaymentState = PaymentState.Loading,
> ```

Can you elborate on how this work? Does it make sense for the default state to be "loading"?
___
*[`android/app/src/oss/kotlin/net/mullvad/mullvadvpn/di/PaymentModule.kt` line 7 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijeeE49dEVdoWEXDM1:-NijeeE49dEVdoWEXDM2:b-5wj016) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/oss/kotlin/net/mullvad/mullvadvpn/di/PaymentModule.kt#L7)):*
> ```Kotlin
> import org.koin.dsl.module
> 
> val paymentModule = module { single { PaymentProvider(null) } }
> ```

This could potentially be improved by using an interface and here use something like `EmptyPaymentProvider`



_Code quote:_
```Kotlin
 PaymentProvider(null) 
```
___
*[`android/lib/billing/src/main/AndroidManifest.xml` line 4 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijfB_J2BszJApebxQT:-NijfB_J2BszJApebxQU:b-1uiap4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/lib/billing/src/main/AndroidManifest.xml#L4)):*
> ```XML
> <manifest xmlns:android="http://schemas.android.com/apk/res/android">
> 
> </manifest>
> ```

Can probably be a single line



_Code quote:_
```XML
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

</manifest>
```
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/PlayPurchaseRepository.kt` line 15 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijfTWC7OPaRdjTgt_h:-NijfTWC7OPaRdjTgt_i:bjoubqp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/PlayPurchaseRepository.kt#L15)):*
> ```Kotlin
> 
> class PlayPurchaseRepository(private val messageHandler: MessageHandler) {
>     suspend fun purchaseInitialisation(): PlayPurchaseInitResult {
> ```

I suggest `initializePlayPurchase`, `initializePurchase`, `initPurchase` or `initPlayPurchase`.

Also, since I don't remember, is the init tied to a specific product or arey they tied together at a later point?



_Code quote:_
```Kotlin
 purchaseInitialisation
```
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/PlayPurchaseRepository.kt` line 25 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nijfine88IgWeT08B_m:-Nijfine88IgWeT08B_n:be3xya5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/PlayPurchaseRepository.kt#L25)):*
> ```Kotlin
>     }
> 
>     suspend fun purchaseVerification(purchase: PlayPurchase): PlayPurchaseVerifyResult {
> ```

I suggest `verifyPurchase` or `verifyPlayPurchase`



_Code quote:_
```Kotlin
purchaseVerification
```
___
*[`android/lib/payment/src/main/AndroidManifest.xml` line 4 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijdbViANdd-ufECX53:-NijdbViANdd-ufECX54:b-nyt2rf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/lib/payment/src/main/AndroidManifest.xml#L4)):*
> ```XML
> <manifest xmlns:android="http://schemas.android.com/apk/res/android">
> 
> </manifest>
> ```

I believe these can be a single line



_Code quote:_
```XML
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

</manifest>
```
___
*[`android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/p [...]

2023-11-09 10:20 UTC, Rawa requested changes
> Reviewed 6 of 62 files at r31, 1 of 6 files at r37, 1 of 1 files at r39, 1 of 1 files at r42, 2 of 11 files at r44, 29 of 57 files at r45, 1 of 1 files at r47, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 60 of 95 files reviewed, 31 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt` line 7 at r39](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijV9N-3P4k5iu4k3qq:-NijV9N-3P4k5iu4k3qr:b5l5s71) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eda66428798e4727f8ee2683b7fce20d53bb5719/android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt#L7)):*
> ```Kotlin
> // Just an example:
> // * Do not place in root module.
> data class PaymentProvider(val paymentRepository: PaymentRepository?)
> ```

Do we need this one? Looks weird that we have a data class with a paymentRepository inside? and why does it have to be nullable? Is this for DI to avoid nullable?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt` line 14 at r39](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijVZex-5BMQiIcInQ6:-NijVZex-5BMQiIcInQ7:b-94s2n1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eda66428798e4727f8ee2683b7fce20d53bb5719/android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt#L14)):*
> ```Kotlin
> data class PaymentProviderWithMultiplePaymentTypes(
>     val paymentOptions: Map<PaymentType, PaymentRepository>
> )
> ```

Looks like a nicer solution from a DI perspective, but would the wrapping class be needed at all? Shouldn't koin be able to handle providing the map depending on what payment types there are? If we only support one payment method for now we might consider removing this class for now?

https://insert-koin.io/docs/reference/koin-annotations/definitions#injecting-a-list-of-dependencies---listt
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt` line 10 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinPvAC4s9vGTGrk0YP:-NinPvAC4s9vGTGrk0YQ:b-ey8fzy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt#L10)):*
> ```Kotlin
> 
> // Another payment provider option with support of multiple payment options.
> typealias PaymentType = String
> ```

Would be nice if it was a value class :angel: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt` line 109 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinSarL0dEij_kpExlX:-NinSarL0dEij_kpExlY:bcwqesd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt#L109)):*
> ```Kotlin
> 
> @Composable
> fun PlayPaymentButton(
> ```

Not sure if this is something that belongs in the `compose/buttons/` since it does much more than just be a button. Maybe it should be named something else?

It would also be nice if this was part of the billing repository and only added if we include billing into the app (e.g like dynamic feature), but this is maybe a bit over the top to do.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt` line 123 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinTbLz3ez14j7fLYoE:-NinTbLz3ez14j7fLYoF:bjwhone) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt#L123)):*
> ```Kotlin
>                 color = MaterialTheme.colorScheme.onBackground,
>                 modifier =
>                     modifier.size(
> ```

`modifier.size(Dimens.progressIndicatorSize)` no need to specify both when they are the same
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt` line 135 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinV6ZP9SoNatChvASC:-NinV6ZP9SoNatChvASD:bwjhb29) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt#L135)):*
> ```Kotlin
>             billingPaymentState.products.forEach { product ->
>                 Column(modifier = modifier) {
>                     if (product.status != PaymentStatus.AVAILABLE) {
> ```

We should use a when statement here to be more explicit, after this if statement we check for `VERIFICATION_IN_PROGRESS` and then assume it is pending.

E.g: 
```
val statusMessageResource = when (product.status) {
    PaymentStatus.VERIFICATION_IN_PROGRESS -> ...
    ...
}

if(statusMessageResource != null) {
     ...
}
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt` line 154 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinVizsAVpbqjC9DclK:-NinVizsAVpbqjC9DclL:b8va90t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt#L154)):*
> ```Kotlin
>                     }
>                     VariantButton(
>                         text = stringResource(id = R.string.add_30_days_time_x, product.price),
> ```

Would be nice if we derive the name from the product, but maybe for later when we hit multiple types of products.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentAvailabilityDialog.kt` line 12 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinWjUZ0b0IyKodKthf:-NinWjUZ0b0IyKodKthg:bvdwffy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentAvailabilityDialog.kt#L12)):*
> ```Kotlin
> 
> @Composable
> fun PaymentAvailabilityDialog(paymentAvailability: PaymentState, onTryAgain: () -> Unit) {
> ```

Naming of this dialog is confusing. The dialog is visible when payment is not available but name makes it seem like it is the opposite. `PaymentUnavailabilityDialog`?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentAvailabilityDialog.kt` line 12 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinXEfT2vbBCa-gwo0w:-NinXEfT2vbBCa-gwo0x:b-g6b9cf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentAvailabilityDialog.kt#L12)):*
> ```Kotlin
> 
> @Composable
> fun PaymentAvailabilityDialog(paymentAvailability: PaymentState, onTryAgain: () -> Unit) {
> ```

onTryAgain = retry?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentAvailabilityDialog.kt` line 19 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinWS5x2whZUKjBJr5Q:-NinWS5x2whZUKjBJr5R:bqdulde) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentAvailabilityDialog.kt#L19)):*
> ```Kotlin
>             showPaymentAvailabilityDialog = true
>         }
>     }
> ```

wouldn't this be the same? 
`var showPaymentAvailabilityDialog by remember(paymentAvailability) { mutableStateOf(paymentAvailability is PaymentState.Error) }`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentBillingErrorDialog.kt` line 16 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinXIzQ-nqpuOirw7vP:-NinXIzQ-nqpuOirw7vQ:b-7k25a5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/a [...]

2023-11-09 10:20 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 60 of 95 files reviewed, 32 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt` line 126 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinZ1Ko04bncYPo6b5w:-NinZ1Ko04bncYPo6b5x:b92w1j8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt#L126)):*
> ```Kotlin
>         paymentAvailability = uiState.billingPaymentState,
>         onTryAgain = onTryFetchProductsAgain
>     )
> ```

On this level it looks like these two could potentially be rendered at the same time. Imo we should either have some sort of when-statement on this level (example 1 below) or have a single dialog composable  (example 2 below) that contains all dialogs or dialog states (e.g. availability and result).

Leaving this as comment here, but it's probably best to discuss it in another forum than the PR/Reviewable.

Example 1:
```
when (uiState.paymentDialogState) {
    PaymentAvailability -> PaymentAvailabilityDialog(...)
    PaymentResult -> PurchaseResultDialog(...)
    else -> ...
}
```

Example 2:
```
if (uiState.showPaymentDialog) {
    PaymentDialog(...)
}
```

```
fun PaymentDialog(paymentDialogState: PaymentDialogState) {
    when(paymentDialogState) {
        PaymentAvailability -> PaymentAvailabilityDialog(...)
        ...
    }
}
```



_Code quote:_
```Kotlin
    uiState.purchaseResult?.let {
        PurchaseResultDialog(
            purchaseResult = uiState.purchaseResult,
            onTryAgain = onTryVerificationAgain,
            onCloseDialog = onClosePurchaseResultDialog
        )
    }

    PaymentAvailabilityDialog(
        paymentAvailability = uiState.billingPaymentState,
        onTryAgain = onTryFetchProductsAgain
    )
```


<!-- Sent from Reviewable.io -->

2023-11-09 11:41 UTC, Rawa requested changes
> Reviewed 1 of 58 files at r21, 9 of 57 files at r45, 1 of 1 files at r46.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 24 of 95 files reviewed, 42 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt` line 153 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nina_sr56mxmsuhMDX8:-Nina_sr56mxmsuhMDX9:b2bl9hp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt#L153)):*
> ```Kotlin
>     private fun fetchPaymentAvailability(delay: Long = 0L) {
>         viewModelScope.launch {
>             delay(delay)
> ```

We do we start with a delay?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt` line 156 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinaR0W1xbopAHyebkR:-NinaR0W1xbopAHyebkS:b-wh279v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt#L156)):*
> ```Kotlin
>             paymentRepository
>                 ?.queryPaymentAvailability()
>                 ?.debounce(PAYMENT_AVAILABILITY_DEBOUNCE) // This is added to avoid flickering
> ```

What flickering would occur? Should they be the same type of state?
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 134 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Ning-rr5x12L-vMA6pL:-Ning-rr5x12L-vMA6pM:b-wozuci) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L134)):*
> ```Kotlin
>             paymentAvailability.tryEmit(PaymentAvailability.ProductsUnavailable)
>             val result = awaitItem().billingPaymentState
>             assertIs<PaymentState.NoPayment>(result)
> ```

Reading it from this perspective it might be a bit confusing. `PaymentState.NoPayment` when products are unavailable?
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModelTest.kt` line 199 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NingxqN4ewrYGPsCHmV:-NingxqN4ewrYGPsCHmW:b-nkf1z5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModelTest.kt#L199)):*
> ```Kotlin
>     fun testBillingProductsGenericErrorState() = runTest {
>         // Arrange
>         val mockPaymentAvailability = PaymentAvailability.Error.Other(mockk())
> ```

We should just name it `val paymentAvailabilityError` so the test below becomes more readable. Sounds in the test like we emit payment availability while it is actually not available. Maybe the core problem is the name of `PaymentAvailability`? 
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt` line 27 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nini6_N8tEA5AnSfeDr:-Nini6_N8tEA5AnSfeDs:b-6are0y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt#L27)):*
> ```Kotlin
> ) : PaymentRepository {
> 
>     override suspend fun queryPaymentAvailability(): Flow<PaymentAvailability> = flow {
> ```

Should not have to be suspend since we return a flow.
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt` line 92 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Ninpqz-3vm9KJZWnNy9:-Ninpqz-3vm9KJZWnNyA:bz8hy6k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt#L92)):*
> ```Kotlin
>                 PurchaseEvent.UserCanceled -> emit(event.toPurchaseResult())
>             }
>         } ?: emit(PurchaseResult.Error.BillingError(null))
> ```

Include this is the when statement and avoid `?.let`:
```
when(event) {
   ...
    null ->
}
```
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt` line 94 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinqIbR8s9kr2ZlXmHe:-NinqIbR8s9kr2ZlXmHf:bdaabgg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt#L94)):*
> ```Kotlin
>         } ?: emit(PurchaseResult.Error.BillingError(null))
> 
>         return@flow
> ```

Unnecessary return?
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt` line 97 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinqOUp6hzn4bKE7Aqo:-NinqOUp6hzn4bKE7Aqp:b5g0og3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt#L97)):*
> ```Kotlin
>     }
> 
>     override suspend fun verifyPurchases(): Flow<VerificationResult> = flow {
> ```

suspend not needed.
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt` line 102 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinrABL1_XNopGs_ojI:-NinrABL1_XNopGs_ojJ:b-ybrukg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt#L102)):*
> ```Kotlin
>         when {
>             purchases.billingResult.responseCode == BillingResponseCode.OK &&
>                 purchases.purchasesList.isNotEmpty() -> {
> ```

`BillingResponseCode.OK && purchases.purchasesList.isNotEmpty()` We do this in several places, maybe it would make sense to create our own type from a purchase? so we effectively can use when on the result? 
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt` line 179 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinrYz069VG16e2K7Lg:-NinrYz069VG16e2K7Lh:b-nex1k1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt#L179)):*
> ```Kotlin
>             Purchase.PurchaseState.PURCHASED -> PaymentStatus.VERIFICATION_IN_PROGRESS
>             Purchase.PurchaseState.PENDING -> PaymentStatus.PENDING
>             else -> PaymentStatus.AVAILABLE
> ```

For my understanding it seems like AVAILABLE is more like IDLE? (that is not doing anything waiting for interaction) Is it needed at all? Does it make sense for it to be null when nothing is happening?


<!-- Sent from Reviewable.io -->

2023-11-09 12:34 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 24 of 95 files reviewed, 41 unresolved discussions (waiting on @albin-mullvad, @Rawa, and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt` line 109 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinSarL0dEij_kpExlX:-NinhHuQ0hcSJuGDDMFh:bb8l2lz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt#L109)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Not sure if this is something that belongs in the `compose/buttons/` since it does much more than just be a button. Maybe it should be named something else?

It would also be nice if this was part of the billing repository and only added if we include billing into the app (e.g like dynamic feature), but this is maybe a bit over the top to do.
</blockquote></details>

We could make it dynamic if there's a nice way of doing it. 

Yes there should be some kind component around this since it can be multiple buttons etc.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt` line 123 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinTbLz3ez14j7fLYoE:-Nini1cD4lxOAnfM7FVR:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt#L123)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`modifier.size(Dimens.progressIndicatorSize)` no need to specify both when they are the same
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt` line 135 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinV6ZP9SoNatChvASC:-NinjZxHCACIbj5sIDA1:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt#L135)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should use a when statement here to be more explicit, after this if statement we check for `VERIFICATION_IN_PROGRESS` and then assume it is pending.

E.g: 
```
val statusMessageResource = when (product.status) {
    PaymentStatus.VERIFICATION_IN_PROGRESS -> ...
    ...
}

if(statusMessageResource != null) {
     ...
}
```
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt` line 154 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinVizsAVpbqjC9DclK:-NinjCUD0amlOh6jZO2d:bk68d4i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/PlayPaymentButton.kt#L154)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Would be nice if we derive the name from the product, but maybe for later when we hit multiple types of products.
</blockquote></details>

Yeah while there are some support for multiple products I have not fully implemented it. I think any such occurrence where we assume that there is only one product can be solved when we actually need to solve it.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentAvailabilityDialog.kt` line 12 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinWjUZ0b0IyKodKthf:-Ninjsga11W3kbnSRkkF:b-3dlpqm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentAvailabilityDialog.kt#L12)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Naming of this dialog is confusing. The dialog is visible when payment is not available but name makes it seem like it is the opposite. `PaymentUnavailabilityDialog`?
</blockquote></details>

Changed it to `PaymentAvailabilityErrorDialog`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentAvailabilityDialog.kt` line 12 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinXEfT2vbBCa-gwo0w:-NinvsfG1rCGna61sA_W:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentAvailabilityDialog.kt#L12)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

onTryAgain = retry?
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentAvailabilityDialog.kt` line 19 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinWS5x2whZUKjBJr5Q:-NinvLI2-I01hZD8sNUo:b-rr8g9u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentAvailabilityDialog.kt#L19)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

wouldn't this be the same? 
`var showPaymentAvailabilityDialog by remember(paymentAvailability) { mutableStateOf(paymentAvailability is PaymentState.Error) }`
</blockquote></details>

I did not know that, sweet. Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentBillingErrorDialog.kt` line 16 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinXIzQ-nqpuOirw7vP:-NinwoVw145G41DeKYPo:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentBillingErrorDialog.kt#L16)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

retry
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PurchaseResultDialog.kt` line 78 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinXX_8-6TjSAzb5hbh:-NinzNOS3X9fV8awE9Rw:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/PurchaseResultDialog.kt#L78)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

retry
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt` line 104 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinYZLu9qMMomcLkeaH:-NinzO3q9maofUjBsXcr:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt#L104)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

onRetryX instead of onTryXAgain
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/OutOfTimeUiState.kt` line 9 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nijbr1O-qrLNGD0vLcj:-NinzdMd7qSzjsh_ZO63:b33eatr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/OutOfTimeUiState.kt#L9)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I believe by default we load in the products from the billingPayment library.
</blockquote></details>

This is a left over from when the payment state worked differently. It should probably b [...]

2023-11-09 13:06 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 24 of 95 files reviewed, 41 unresolved discussions (waiting on @albin-mullvad, @Rawa, and @sabercodic)

___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt` line 27 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nini6_N8tEA5AnSfeDr:-Nio9IbOEGFECOYtFUPp:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt#L27)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should not have to be suspend since we return a flow.
</blockquote></details>

Done
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt` line 92 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Ninpqz-3vm9KJZWnNy9:-Nio9Jn-Cu79ckdD9VLk:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt#L92)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Include this is the when statement and avoid `?.let`:
```
when(event) {
   ...
    null ->
}
```
</blockquote></details>

Done
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt` line 94 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinqIbR8s9kr2ZlXmHe:-Nio9Kky27yTggk4a2LD:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt#L94)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Unnecessary return?
</blockquote></details>

Done
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt` line 97 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinqOUp6hzn4bKE7Aqo:-Nio9hzrBLv67pWIeaf5:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt#L97)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

suspend not needed.
</blockquote></details>

Done
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/PlayPurchaseRepository.kt` line 15 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijfTWC7OPaRdjTgt_h:-NioA_vN4Dk9XTwt-O4S:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/PlayPurchaseRepository.kt#L15)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest `initializePlayPurchase`, `initializePurchase`, `initPurchase` or `initPlayPurchase`.

Also, since I don't remember, is the init tied to a specific product or arey they tied together at a later point?
</blockquote></details>

Done
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/PlayPurchaseRepository.kt` line 25 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nijfine88IgWeT08B_m:-NioAao6DIyAx8BHcm25:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/PlayPurchaseRepository.kt#L25)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest `verifyPurchase` or `verifyPlayPurchase`
</blockquote></details>

Done
___
*[`android/lib/payment/src/main/AndroidManifest.xml` line 4 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijdbViANdd-ufECX53:-NioB9GA6yHSM5aJYrH_:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/lib/payment/src/main/AndroidManifest.xml#L4)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe these can be a single line
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-09 13:27 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 23 of 95 files reviewed, 41 unresolved discussions (waiting on @albin-mullvad, @Rawa, and @sabercodic)

___
*[`android/lib/billing/src/main/AndroidManifest.xml` line 4 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijfB_J2BszJApebxQT:-NioE2gP0VraEsKCUByF:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/lib/billing/src/main/AndroidManifest.xml#L4)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can probably be a single line
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-09 13:29 UTC, Rawa requested changes
> Reviewed 1 of 59 files at r29, 4 of 11 files at r44, 11 of 57 files at r45, 1 of 11 files at r52, 13 of 57 files at r53, 7 of 15 files at r59, 1 of 1 files at r61, 7 of 56 files at r64, 1 of 1 files at r66, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 32 of 95 files reviewed, 38 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 152 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NioBcEd3-cgh2o_U3Gx:-NioBcEd3-cgh2o_U3Gy:b-alrdt2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L152)):*
> ```Kotlin
>     private fun updateAccountExpiry() {
>         accountRepository.fetchAccountExpiry()
>     }
> ```

It feels like we do all this payment logic the exactly the same on several places, I'm not sure if possible but it would be nice if we could break it out to some other piece of logic that all the Welcome, OutOfTime and Account screen can reuse.
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt` line 152 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NioC7P34xV8KlWd2gdH:-NioC7P34xV8KlWd2gdI:b7itgpe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt#L152)):*
> ```Kotlin
>                     )
>             // Launch the billing flow
>             billingClient.launchBillingFlow(activity, billingFlowParams)
> ```

An idea (not necessarily a great one ^^), what if we instead of returning the BillingResult return a "PurchaseFlowStarter" lambda where the user of the billing repository can pass the activity? Would it make sense? Then we don't have to do the juggling with the Activity in another module.
___
*[`android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PaymentStatus.kt` line 4 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NioBCxoE5BjIG8nxSth:-NioBCxoE5BjIG8nxSti:b-nnwco9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PaymentStatus.kt#L4)):*
> ```Kotlin
> 
> enum class PaymentStatus {
>     AVAILABLE,
> ```

AVAILABLE = IDLE? or no status?
___
*[`android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PaymentProduct.kt` line 3 at r61](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NioB5Mb7E8LauXRq9UO:-NioB5Mb7E8LauXRq9UP:blkv0mg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/132c3b3edf2a601d49e043c669c8704b7495ef26/android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PaymentProduct.kt#L3)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.lib.payment.model
> 
> data class PaymentProduct(val productId: String, val price: String, val status: PaymentStatus)
> ```

Would be nice if we used `value class` for productId and price, so it is hard to mix them up.


<!-- Sent from Reviewable.io -->

2023-11-09 15:30 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 32 of 95 files reviewed, 31 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 134 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Ning-rr5x12L-vMA6pL:-Niog8iI0ZKPRabJS2ni:b-r1tikv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L134)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Yes I guess it could be called `NoProducts`? But it would do the same thing as `NoPayment`
</blockquote></details>

If the reason you get NoPayment is the direct cause of there not being any products I it would be way more clear to call it `NoProductsFound` or similar.


<!-- Sent from Reviewable.io -->

2023-11-09 16:06 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 30 of 96 files reviewed, 31 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt` line 7 at r39](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijV9N-3P4k5iu4k3qq:-Niop6wd9XtOxO5OLWec:bi27cvu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eda66428798e4727f8ee2683b7fce20d53bb5719/android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt#L7)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Do we need this one? Looks weird that we have a data class with a paymentRepository inside? and why does it have to be nullable? Is this for DI to avoid nullable?
</blockquote></details>

For DI purposes.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt` line 14 at r39](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijVZex-5BMQiIcInQ6:-NiopD2Y0HLiQscjyx9Y:b-fjkzzk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eda66428798e4727f8ee2683b7fce20d53bb5719/android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt#L14)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Looks like a nicer solution from a DI perspective, but would the wrapping class be needed at all? Shouldn't koin be able to handle providing the map depending on what payment types there are? If we only support one payment method for now we might consider removing this class for now?

https://insert-koin.io/docs/reference/koin-annotations/definitions#injecting-a-list-of-dependencies---listt
</blockquote></details>

Problem is that Koin does not support null.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt` line 5 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijbLKBB8MGgfliUUvV:-Niop5OXEFSW-CHfFZyr:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt#L5)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I guess this one should be cleaned up? At least the comments, which I believe I wrote :laughing:
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt` line 10 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinPvAC4s9vGTGrk0YP:-NiopCFe9xpxlYe4new1:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/PaymentProvider.kt#L10)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Would be nice if it was a value class :angel:
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-09 16:23 UTC, albin-mullvad requested changes
> Reviewed 1 of 2 files at r55, 1 of 68 files at r62, 1 of 11 files at r63, 2 of 56 files at r64, 1 of 2 files at r69.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 36 of 96 files reviewed, 26 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/WelcomeDialogState.kt` line 3 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nijjlx591Q0NMRqwszf:-NiosUu562M-j0NNURjE:btwtcwb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/WelcomeDialogState.kt#L3)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

It should probably be added.
</blockquote></details>

Yeah, I guess it depends how things are split up, but since it's currently called `WelcomeDialogState` it might make sense. If all dialogs of the welcome screen are not included, this interface should probably be renamed to something payment/billing specific.


<!-- Sent from Reviewable.io -->

2023-11-10 14:16 UTC, albin-mullvad requested changes
> Reviewed 1 of 58 files at r21, 1 of 59 files at r29, 7 of 11 files at r63, 18 of 56 files at r64, 4 of 10 files at r67, 1 of 1 files at r71, 1 of 1 files at r72.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 65 of 98 files reviewed, 26 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/oss/kotlin/net/mullvad/mullvadvpn/di/PaymentModule.kt` line 7 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijeeE49dEVdoWEXDM1:-NisgRmw0_9ls5YN_Dc2:bbhgwqv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/oss/kotlin/net/mullvad/mullvadvpn/di/PaymentModule.kt#L7)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This could potentially be improved by using an interface and here use something like `EmptyPaymentProvider`
</blockquote></details>

As discussed, let's keep it as-is for now
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/extension/ProductDetailsResultToPaymentAvailability.kt` line 19 at r72](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nishvy615Fd6Uv43xLD:-Nishvy615Fd6Uv43xLE:b-bypnny) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b65f677f4cc46a6ca8d3dfbe6dd959ae920ad289/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/extension/ProductDetailsResultToPaymentAvailability.kt#L19)):*
> ```Kotlin
>         this.billingResult.responseCode == BillingClient.BillingResponseCode.OK ->
>             PaymentAvailability.ProductsAvailable(
>                 this.productDetailsList?.toPaymentProducts(productIdToPaymentStatus) ?: emptyList()
> ```

We can't end up with the empty list here since that's already catched by the prior when-branch, right? In this case I believe it make sense structure it like this:

```
this.billingResult.responseCode == BillingClient.BillingResponseCode.OK -> {
    if (hasProducts)
        ProductsAvailable(list)
    else {
        ProductsUnavailable
    }
}

```



_Code quote:_
```Kotlin
emptyList()
```


<!-- Sent from Reviewable.io -->

2023-11-13 00:09 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 59 of 100 files reviewed, 23 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/LoadingDialog.kt` line 22 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijiBA_7c06Gqu70orH:-Nj4xaE1DC7DU6-I2Ww6:b-vyzcfb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/LoadingDialog.kt#L22)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Does it make sense for this to be its own dialog? Seems like this could be a variant/state of some existing dialog. For instance, it seems to me like the transitions to and from this could end up being a bit strange :thinking:

I suggest we discuss this in the team before making any changes.
</blockquote></details>

It has been merged into the PaymentDialog.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt` line 126 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinZ1Ko04bncYPo6b5w:-Nj4xoYy9TSpVMXTgfxM:bvo10l6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt#L126)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

On this level it looks like these two could potentially be rendered at the same time. Imo we should either have some sort of when-statement on this level (example 1 below) or have a single dialog composable  (example 2 below) that contains all dialogs or dialog states (e.g. availability and result).

Leaving this as comment here, but it's probably best to discuss it in another forum than the PR/Reviewable.

Example 1:
```
when (uiState.paymentDialogState) {
    PaymentAvailability -> PaymentAvailabilityDialog(...)
    PaymentResult -> PurchaseResultDialog(...)
    else -> ...
}
```

Example 2:
```
if (uiState.showPaymentDialog) {
    PaymentDialog(...)
}
```

```
fun PaymentDialog(paymentDialogState: PaymentDialogState) {
    when(paymentDialogState) {
        PaymentAvailability -> PaymentAvailabilityDialog(...)
        ...
    }
}
```
</blockquote></details>

Both dialogs was merged into one dialog.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt` line 331 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinZ0zRDpMVGIkkhfUo:-Nj4znXf6A0j9ct_iDaa:b2do8w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt#L331)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Maybe it would be more clear no make PlayPaymentButton always fillMaxWidth? Not fully intuitive that it can change size depending if it is loading or not.
</blockquote></details>

Can we discuss this in person how to solve this?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/OutOfTimeUiState.kt` line 9 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nijbr1O-qrLNGD0vLcj:-Nj4zrnMDrEOR9ROaCPX:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/OutOfTimeUiState.kt#L9)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This is a left over from when the payment state worked differently. It should probably be PaymentState.NoPayment as that is what is default in the view model.
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/PaymentState.kt` line 13 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinZoBJ80u01mpl-KBX:-Nj4uE_E7pGB_gE5uRiM:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/PaymentState.kt#L13)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I think it should just be named Generic and Billing, when referencing in code it will be:
```
PaymentState.Error.GenericError
PaymentState.Error.BillingError
```
Personally I think this is nicer:
```
PaymentState.Error.Generic
PaymentState.Error.Billing
```
Alternatively you can make put them outside the sealed interface of Error but still keep the inheritence, to make it like this:
```
PaymentState.GenericError
PaymentState.BillingError
```
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/WelcomeDialogState.kt` line 3 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nijjlx591Q0NMRqwszf:-Nj4uUEG8D7oYxC_2u_L:b-n8wxzf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/WelcomeDialogState.kt#L3)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Yeah, I guess it depends how things are split up, but since it's currently called `WelcomeDialogState` it might make sense. If all dialogs of the welcome screen are not included, this interface should probably be renamed to something payment/billing specific.
</blockquote></details>

Just realised that it was no longer used so I just deleted it.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/WelcomeDialogState.kt` line 4 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nin_PeL8gPeMdAsgCFy:-Nj4udGwBaLekmc9m93B:bm55sta) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/WelcomeDialogState.kt#L4)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Not needed, if there is no dialog, there is no WelcomeDialogState at all.
</blockquote></details>

Not used, see above comment. 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/WelcomeUiState.kt` line 10 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nijk1wF2ce6d3xu8egA:-Nj4uuCL1KEP9_P_cxsb:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/WelcomeUiState.kt#L10)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

See comment above, this is an oversight.
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt` line 153 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nina_sr56mxmsuhMDX8:-Nj4uzGn6LsPLfhGIlO2:bo8zo8t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt#L153)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

If you would press retry on the dialog the states would update so quickly that the dialog would not show again.
</blockquote></details>

Removed now.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 134 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Ning-rr5x12L-vMA6pL:-Nj4wIjQ846LBp8prPDF:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L134)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary [...]

2023-11-13 06:19 UTC, albin-mullvad requested changes
> Reviewed 1 of 11 files at r63, 6 of 56 files at r64, 3 of 9 files at r73, 5 of 24 files at r74, 5 of 9 files at r75.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 78 of 100 files reviewed, 20 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/LoadingDialog.kt` line 22 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijiBA_7c06Gqu70orH:-Nj6IiNf4xtRnYh8o9Va:bmsx7r4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/LoadingDialog.kt#L22)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

It has been merged into the PaymentDialog.
</blockquote></details>

Nice! This file/class should also be removed, right?
___
*[`android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/PaymentRepository.kt` line 10 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nijl-oY8-mrJTz_9xzr:-Nj6IuD12DriYAxd_0gk:bw7wrp6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/PaymentRepository.kt#L10)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done
</blockquote></details>

It still seem to have the same name. Was this change pushed? :thinking: 


<!-- Sent from Reviewable.io -->

2023-11-13 07:46 UTC, albin-mullvad requested changes
> Reviewed 1 of 9 files at r73, 2 of 24 files at r74, 2 of 9 files at r75.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 83 of 100 files reviewed, 23 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt` line 151 at r75](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nj6adv969sYk4LMyUyH:-Nj6adv969sYk4LMyUyI:b-h1rvrk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8174801395f2baed5dea074dd36713819c126505/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt#L151)):*
> ```Kotlin
>     retryFetchProducts: () -> Unit,
>     retryVerification: () -> Unit,
>     onCloseDialog: (paymentSuccessful: Boolean) -> Unit
> ```

nit: `isPaymentSuccessful`



_Code quote:_
```Kotlin
paymentSuccessful
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialogData.kt` line 13 at r75](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nj6as4P3w2K14rOyXXp:-Nj6as4P3w2K14rOyXXq:b-7k1xk7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8174801395f2baed5dea074dd36713819c126505/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialogData.kt#L13)):*
> ```Kotlin
> )
> 
> data class DialogAction(
> ```

I suggest prefixing this one with Payment to keep the name consistent with the other classes/enums in this file.



_Code quote:_
```Kotlin
DialogAction
```
___
*[`android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PaymentAvailability.kt` line 10 at r75](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nj6cpGl72rwuQ8_qb0U:-Nj6cpGl72rwuQ8_qb0V:bblcg5k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8174801395f2baed5dea074dd36713819c126505/android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PaymentAvailability.kt#L10)):*
> ```Kotlin
>     data object ProductsUnavailable : PaymentAvailability
> 
>     data object NoProductsFounds : PaymentAvailability
> ```

Just out of curiosity, do we need to distinguish between these two?



_Code quote:_
```Kotlin
    data object ProductsUnavailable : PaymentAvailability

    data object NoProductsFounds : PaymentAvailability
```


<!-- Sent from Reviewable.io -->

2023-11-13 08:21 UTC, Rawa reviewed
> Reviewed 1 of 56 files at r64, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 84 of 100 files reviewed, 12 unresolved discussions (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2023-11-13 08:24 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 84 of 100 files reviewed, 11 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/LoadingDialog.kt` line 22 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NijiBA_7c06Gqu70orH:-Nj6jIGhA4s5RYPnDcTT:b-83wjno) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/LoadingDialog.kt#L22)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Nice! This file/class should also be removed, right?
</blockquote></details>

Yeah missed that one since it was not named payment something..
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt` line 151 at r75](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nj6adv969sYk4LMyUyH:-Nj6jsTD7nnIsj2we_rg:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8174801395f2baed5dea074dd36713819c126505/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt#L151)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: `isPaymentSuccessful`
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialogData.kt` line 13 at r75](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nj6as4P3w2K14rOyXXp:-Nj6lHUM-4WfPD2S5rYa:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8174801395f2baed5dea074dd36713819c126505/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialogData.kt#L13)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest prefixing this one with Payment to keep the name consistent with the other classes/enums in this file.
</blockquote></details>

Done
___
*[`android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/PaymentRepository.kt` line 10 at r42](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nijl-oY8-mrJTz_9xzr:-Nj6lWDyCFh9MU8y1YDN:bbninpm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d51768bc12c83b115cdeb6205da542b931c4c91/android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/PaymentRepository.kt#L10)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

It still seem to have the same name. Was this change pushed? :thinking:
</blockquote></details>

Oh it seems that I confused what you wanted to change from to what you wanted to change to. My bad. Fixed now.
___
*[`android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PaymentAvailability.kt` line 10 at r75](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nj6cpGl72rwuQ8_qb0U:-Nj6lxBe1nzD5JK9XN7k:bdachlt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8174801395f2baed5dea074dd36713819c126505/android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PaymentAvailability.kt#L10)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Just out of curiosity, do we need to distinguish between these two?
</blockquote></details>

I was suggested by @Rawa to make the code cleaner, it does not change what we show on the screen.


<!-- Sent from Reviewable.io -->

2023-11-13 08:35 UTC, albin-mullvad reviewed
> Reviewed 2 of 9 files at r76.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 84 of 100 files reviewed, 7 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PaymentAvailability.kt` line 10 at r75](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nj6cpGl72rwuQ8_qb0U:-Nj6o8Vo9SVjb4zDbRp-:bzgo8u2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8174801395f2baed5dea074dd36713819c126505/android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PaymentAvailability.kt#L10)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I was suggested by @Rawa to make the code cleaner, it does not change what we show on the screen.
</blockquote></details>

Alright, sounds good if we see a benifit of having both :thumbsup: 


<!-- Sent from Reviewable.io -->

2023-11-13 10:08 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 84 of 100 files reviewed, 6 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 152 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NioBcEd3-cgh2o_U3Gx:-Nj75N0eCHNh7ZpT9Cmt:bez8jcj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L152)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

It feels like we do all this payment logic the exactly the same on several places, I'm not sure if possible but it would be nice if we could break it out to some other piece of logic that all the Welcome, OutOfTime and Account screen can reuse.
</blockquote></details>

Moved the code to a use case.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt` line 156 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NinaR0W1xbopAHyebkR:-Nj75T-c74Gj9pzl0BOm:bo9x3in) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt#L156)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

So the thinking here is that there are two times when we ask for payment availability, when you enter the screen and after a purchase has been made, regardless if it was successful or not. In the first case it can take some time and it might be useful to show a spinner or some other indication that it is loading. In the other case the update happens almost immediately so the spinner is shown only for a very short amount of time. So by adding this debunk we do not show the spinner unless the action is delayed for some reason.
</blockquote></details>

I will run some tests and see if this debounce is still necessary.
___
*[`android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PaymentProduct.kt` line 3 at r61](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NioB5Mb7E8LauXRq9UO:-Nj78hmm3NqZz1LM-4Sz:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/132c3b3edf2a601d49e043c669c8704b7495ef26/android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PaymentProduct.kt#L3)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Would be nice if we used `value class` for productId and price, so it is hard to mix them up.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-13 10:33 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 80 of 103 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt` line 152 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NioC7P34xV8KlWd2gdH:-Nj7EXD6CUYjyZ9UhGCj:b-xryd1u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt#L152)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

An idea (not necessarily a great one ^^), what if we instead of returning the BillingResult return a "PurchaseFlowStarter" lambda where the user of the billing repository can pass the activity? Would it make sense? Then we don't have to do the juggling with the Activity in another module.
</blockquote></details>

Added some kind of function that returns an activity, not sure if this is an improvement.


<!-- Sent from Reviewable.io -->

2023-11-13 11:51 UTC, albin-mullvad requested changes
> Reviewed 1 of 9 files at r76, 5 of 15 files at r77, 2 of 12 files at r79.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 86 of 103 files reviewed, 7 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt` line 152 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NioC7P34xV8KlWd2gdH:-Nj7W3AU8PaKUAK2B34k:b-rogim) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt#L152)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Added some kind of function that returns an activity, not sure if this is an improvement.
</blockquote></details>

Looks better than before imo :thumbsup: 
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt` line 209 at r78](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nj7Cja39jr8l7EIvo0r:-Nj7Cja46bNpLr5vC4oi:bfb2qzi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/227b34dfe8ace93fc0d85bb243881f7801a2ad66/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt#L209)):*
> ```Kotlin
> 
>     companion object {
>         private const val PRODUCT_ID = "test"
> ```

I assume this one will/should get cleaned up? :thinking: 



_Code quote:_
```Kotlin
private const val PRODUCT_ID = "test"
```


<!-- Sent from Reviewable.io -->

2023-11-13 12:21 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 86 of 103 files reviewed, 7 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt` line 209 at r78](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-Nj7Cja39jr8l7EIvo0r:-Nj7cA3a-nMCUvcC-S90:b8lefp3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/227b34dfe8ace93fc0d85bb243881f7801a2ad66/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt#L209)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I assume this one will/should get cleaned up? :thinking:
</blockquote></details>

Nice find. Removed.


<!-- Sent from Reviewable.io -->

2023-11-14 10:48 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 75 of 104 files reviewed, 7 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt` line 152 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NioC7P34xV8KlWd2gdH:-NjCR2bB4v9lbocLu_dW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt#L152)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Looks better than before imo :thumbsup:
</blockquote></details>

Done.
___
*[`android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PurchaseResult.kt` line 11 at r26](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NfLxIiR4HHh_Nf18HWS:-Nj88C7R5AFvD2EBd7os:b-lghyua) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1055ef1aafaf8ecec200418b074564df987849ba/android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PurchaseResult.kt#L11)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This is done like it is now because it mirrors the implementation in the daemon. We could look into improving this, but I think it perhaps is best to do some time in the future instead?
</blockquote></details>

It seems like this file has been changed a lot so this comment is no longer valid?


<!-- Sent from Reviewable.io -->

2023-11-14 12:07 UTC, Rawa requested changes
> Reviewed 1 of 24 files at r74, 1 of 12 files at r79, 2 of 7 files at r81, 2 of 15 files at r82.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 81 of 104 files reviewed, 8 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/extension/PurchasesResultExtensions.kt` line 14 at r82](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjCg7zLEixmpMyx4oVf:-NjCg7zLEixmpMyx4oVg:bsmsyi6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc948d2fbee8bf273cd9b31b22dfa02b5adf4ef7/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/extension/PurchasesResultExtensions.kt#L14)):*
> ```Kotlin
>             true
>         }
>     }
> ```

Not sure how much this extension function makes sense. We could have one that is `nonPendingPurchases()`, but if I'm loking to get all purchases I think:
`result.purchasesList`
is as easy as 
`results.purchases(false)`
___
*[`android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/ProductPrice.kt` line 3 at r82](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjCfNkSC4CTLyaqKgut:-NjCfNkSC4CTLyaqKguu:b-p59m9m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc948d2fbee8bf273cd9b31b22dfa02b5adf4ef7/android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/ProductPrice.kt#L3)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.lib.payment.model
> 
> @JvmInline value class ProductPrice(val value: String)
> ```

@JvmInline on the line above I think, like the other value class `ProductId`
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/model/PurchaseEvent.kt` line 11 at r82](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjChPl04wgUEQAWZ9G5:-NjChPl04wgUEQAWZ9G6:b-j95se1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc948d2fbee8bf273cd9b31b22dfa02b5adf4ef7/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/model/PurchaseEvent.kt#L11)):*
> ```Kotlin
>     data class Error(val exception: BillingException) : PurchaseEvent
> 
>     data class PurchaseCompleted(val purchases: List<Purchase>) : PurchaseEvent
> ```

`PurchaseEvent.PurchaseCompleted` -> `PurchaseEvent.Complete`
___
*[`android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PaymentProduct.kt` line 7 at r82](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjChdxCCHdmeUGvwzaI:-NjChdxCCHdmeUGvwzaJ:bjpn40d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc948d2fbee8bf273cd9b31b22dfa02b5adf4ef7/android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PaymentProduct.kt#L7)):*
> ```Kotlin
>     val price: ProductPrice,
>     val status: PaymentStatus?
> )
> ```

:star: 
___
*[`android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PurchaseResult.kt` line 27 at r82](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjCfHLiBX9Bs3lFJVzT:-NjCfHLiBX9Bs3lFJVzU:bb70w76) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc948d2fbee8bf273cd9b31b22dfa02b5adf4ef7/android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/PurchaseResult.kt#L27)):*
> ```Kotlin
>     }
> 
>     fun isTerminatingState(): Boolean = this is Completed || this is Error
> ```

Nice


<!-- Sent from Reviewable.io -->

2023-11-14 12:22 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 81 of 104 files reviewed, 10 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt` line 164 at r82](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjCkCe80XywG9pR6XKc:-NjCkCe80XywG9pR6XKd:bvfab6r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc948d2fbee8bf273cd9b31b22dfa02b5adf4ef7/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt#L164)):*
> ```Kotlin
>                     ?: paymentStateError?.let { paymentAvailabilityErrorDialogData() }
>             mutableStateOf(dialogData)
>         }
> ```

This looks very confusing (also PaymentDialog does not always show a dialog). We maybe should create a class used in the view layer to help describe this dialog better? E.g
```
sealed interface PaymentDialogViewState {
    data class Error(val error: Payment.StateError): PaymentDialogViewState
    data class Result(val result: PurchaseResult): PaymentDialogViewState
}
```

then we can use `derivedStateOf` to create this viewState from purchaseResult and paymentStateError and then conditionally call PaymentDialog depending if we have a PaymentDialogViewState or not.

Ping me if it doesn't make sense :sweat_smile: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt` line 185 at r82](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjCjdFP0GuifmWU5qzi:-NjCjdFP0GuifmWU5qzj:b-yo1umz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc948d2fbee8bf273cd9b31b22dfa02b5adf4ef7/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt#L185)):*
> ```Kotlin
> 
> @Composable
> private fun ShowPaymentDialog(
> ```

Not sure what we should name it but a composable should not be prefixed with `Show` maybe we can call it PaymentDialog since it is the actual Dialog and name the other composable something else?


<!-- Sent from Reviewable.io -->

2023-11-14 12:23 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 81 of 104 files reviewed, 10 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt` line 164 at r82](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjCkCe80XywG9pR6XKc:-NjCm72pBqnEzLj0F7Va:b-5e1rpd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc948d2fbee8bf273cd9b31b22dfa02b5adf4ef7/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt#L164)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This looks very confusing (also PaymentDialog does not always show a dialog). We maybe should create a class used in the view layer to help describe this dialog better? E.g
```
sealed interface PaymentDialogViewState {
    data class Error(val error: Payment.StateError): PaymentDialogViewState
    data class Result(val result: PurchaseResult): PaymentDialogViewState
}
```

then we can use `derivedStateOf` to create this viewState from purchaseResult and paymentStateError and then conditionally call PaymentDialog depending if we have a PaymentDialogViewState or not.

Ping me if it doesn't make sense :sweat_smile:
</blockquote></details>

I guess this would be the same as having something that creates the `paymentDialogData` outside of `PaymentDialog` and always consuming paymentDialogData in this composable.


<!-- Sent from Reviewable.io -->

2023-11-14 12:47 UTC, albin-mullvad reviewed
> Reviewed 1 of 15 files at r77, 1 of 12 files at r79, 4 of 7 files at r81, 10 of 15 files at r82.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 81 of 105 files reviewed, 9 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 52 at r81](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjCMGsC46bwraqHiVNN:-NjCMGsC46bwraqHiVNO:bdas7v2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d51cf87f5102b14ed2fc029d04d388f9cae4f5ee/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L52)):*
> ```Kotlin
>                     purchaseResult = purchaseResult,
>                     billingPaymentState =
>                         paymentAvailability?.toPaymentState() ?: PaymentState.Loading
> ```

Doesn't it make more sense that the default/fallback state is something like `Idle` or "not ongoing"? I asked a similar question before, but couldn't find it now



_Code quote:_
```Kotlin
PaymentState.Loading
```


<!-- Sent from Reviewable.io -->

2023-11-14 13:24 UTC, albin-mullvad reviewed
> Reviewed 4 of 18 files at r83, 1 of 17 files at r84.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 80 of 105 files reviewed, 6 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 52 at r81](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjCMGsC46bwraqHiVNN:-NjCzVir1Xq9EkgHy47Z:b-ux0ur8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d51cf87f5102b14ed2fc029d04d388f9cae4f5ee/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L52)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Yes this makes sense, having it be loading made sense before when we did not have a flow that emitted a lot of states. I set it to null as idle state as that is the same as for the purchase flow.
</blockquote></details>

Sounds good :thumbsup: 
___
*[`android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/ProductPrice.kt` line 3 at r82](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjCfNkSC4CTLyaqKgut:-NjCxfK6BI7rMlJ_5aSH:b-ih0ut5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc948d2fbee8bf273cd9b31b22dfa02b5adf4ef7/android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/model/ProductPrice.kt#L3)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

@JvmInline on the line above I think, like the other value class `ProductId`
</blockquote></details>

Blame `ktfmt` :laughing: 


<!-- Sent from Reviewable.io -->

2023-11-14 13:27 UTC, albin-mullvad reviewed
> Reviewed 7 of 18 files at r83.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 83 of 105 files reviewed, 6 unresolved discussions (waiting on @Pururun and @Rawa)



<!-- Sent from Reviewable.io -->

2023-11-14 14:18 UTC, albin-mullvad requested changes
> Reviewed 2 of 18 files at r83, 12 of 17 files at r84.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 86 of 105 files reviewed, 8 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/lib/billing/src/androidTest/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepositoryTest.kt` line 1 at r84](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjD9pJU-A7j0xzLDiZe:-NjD9pJU-A7j0xzLDiZf:b-kwno0x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b93a89ffc58d20e860a597eda24f910ed40d8d7f/android/lib/billing/src/androidTest/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepositoryTest.kt#L1)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.lib.billing
> ```

Would it be possible to add some test to check the `ensureConnected`/ mutex behavior? That would also reduce the risk of future regression.
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt` line 137 at r84](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjDB-ox8IDa2d6SWotQ:-NjDB-ox8IDa2d6SWotR:b-t44hnh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b93a89ffc58d20e860a597eda24f910ed40d8d7f/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt#L137)):*
> ```Kotlin
>                     .build()
> 
>             // Get the activity from Koin
> ```

This might be a bit misleading since we're not directly getting it from Koin as we did before



_Code quote:_
```Kotlin
// Get the activity from Koin
```


<!-- Sent from Reviewable.io -->

2023-11-14 15:22 UTC, Rawa approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-:-NjDQFta6TBl96uPjZJL:bnfp4nl)* status: 93 of 105 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @Pururun)



<!-- Sent from Reviewable.io -->

2023-11-14 15:27 UTC, albin-mullvad reviewed
> Reviewed 2 of 17 files at r84, 4 of 12 files at r85, 1 of 1 files at r86.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 100 of 105 files reviewed, 6 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 121 at r86](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjDJs8a3pAn0Ntjw4T_:-NjDJs8a3pAn0Ntjw4Ta:b-waunek) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0375045f5a3e5fa3df5774a82b42a50de299b886/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L121)):*
> ```Kotlin
>             when (status) {
>                 PaymentStatus.PENDING ->
>                     paymentUseCase.setPurchaseResult(PurchaseResult.Completed.Pending)
> ```

I'm not sure I follow the flow here. Why does the UI tell the use case which result/state the use case should be in?



_Code quote:_
```Kotlin
                PaymentStatus.PENDING ->
                    paymentUseCase.setPurchaseResult(PurchaseResult.Completed.Pending)
```


<!-- Sent from Reviewable.io -->

2023-11-14 16:20 UTC, albin-mullvad requested changes
> Reviewed 1 of 58 files at r21, 1 of 56 files at r64, 4 of 24 files at r74, 1 of 17 files at r84, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: all files reviewed, 12 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreenTest.kt` line 45 at r86](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjD_WxwDmBf5Ec-716d:-NjD_WxwDmBf5Ec-716e:bl6qz0s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0375045f5a3e5fa3df5774a82b42a50de299b886/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreenTest.kt#L45)):*
> ```Kotlin
>                 openConnectScreen = {},
>                 onPurchaseBillingProductClick = {},
>                 onTryVerificationAgain = {},
> ```

I believe this test is a bit out-of-date since these functions were renamed. I guess we also have some changed/new test cases. Otherwise looks good.



_Code quote:_
```Kotlin
onTryVerificationAgain
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt` line 164 at r82](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjCkCe80XywG9pR6XKc:-NjDaC0IAfIUsYtpLg5P:bu93u7r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc948d2fbee8bf273cd9b31b22dfa02b5adf4ef7/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt#L164)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I guess this would be the same as having something that creates the `paymentDialogData` outside of `PaymentDialog` and always consuming paymentDialogData in this composable.
</blockquote></details>

As discussed offline, this improvement would be nice to include in the PR :thumbsup: 
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 51 at r86](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjDZIri0QF_Q6z74TE2:-NjDZIri0QF_Q6z74TE3:b-vj1hii) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0375045f5a3e5fa3df5774a82b42a50de299b886/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L51)):*
> ```Kotlin
>     private val deviceState: MutableStateFlow<DeviceState> = MutableStateFlow(DeviceState.Initial)
>     private val purchaseResult =
>         MutableSharedFlow<PurchaseResult>(extraBufferCapacity = 1, replay = 1)
> ```

Why do we need replay for all of these tests? I'm concered that might result in false-positive test results since it's different behavior than the real implementation.



_Code quote:_
```Kotlin
replay = 1
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModelTest.kt` line 209 at r86](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjDYfKnCuOPuu24QXBS:-NjDYfKnCuOPuu24QXBT:bdahw2a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0375045f5a3e5fa3df5774a82b42a50de299b886/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModelTest.kt#L209)):*
> ```Kotlin
>             serviceConnectionState.value =
>                 ServiceConnectionState.ConnectedReady(mockServiceConnectionContainer)
>             // It should emit no payment
> ```

Do we need these comments? Can it be clarified by the assert code itself etc? This comment applies to other tests in this file.



_Code quote:_
```Kotlin
// It should emit no payment
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModelTest.kt` line 167 at r86](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjDZt-fD1949gyzPW0e:-NjDZt-fD1949gyzPW0f:b-mxbutr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0375045f5a3e5fa3df5774a82b42a50de299b886/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModelTest.kt#L167)):*
> ```Kotlin
>                     )
>                 serviceConnectionState.value =
>                     ServiceConnectionState.ConnectedReady(mockServiceConnectionContainer)
> ```

Is the change of order here significant?



_Code quote:_
```Kotlin
                serviceConnectionState.value =
                    ServiceConnectionState.ConnectedReady(mockServiceConnectionContainer)
```
___
*[`android/lib/billing/src/androidTest/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepositoryTest.kt` line 48 at r86](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjDafvpEFzY0mXficgZ:-NjDafvpEFzY0mXficg_:b-z7w2ub) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0375045f5a3e5fa3df5774a82b42a50de299b886/android/lib/billing/src/androidTest/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepositoryTest.kt#L48)):*
> ```Kotlin
>     private val mockBillingClient: BillingClient = mockk()
> 
>     private val listenerSlot: CapturingSlot<PurchasesUpdatedListener> = CapturingSlot()
> ```

nit: I suggest clarifying by renaming to something like `purchaseListenerSlot` or `purchaseUpdatedListenerSlot`



_Code quote:_
```Kotlin
listenerSlot
```
___
*[`android/lib/billing/src/test/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepositoryTest.kt` line 56 at r86](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjDbevg4A4FsqNdRSNz:-NjDbevg4A4FsqNdRSO-:b-lamaqw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0375045f5a3e5fa3df5774a82b42a50de299b886/android/lib/billing/src/test/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepositoryTest.kt#L56)):*
> ```Kotlin
>     }
> 
>     @After fun tearDown() {}
> ```

Remove if not used.


<!-- Sent from Reviewable.io -->

2023-11-14 23:20 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 88 of 107 files reviewed, 12 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt` line 164 at r82](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjCkCe80XywG9pR6XKc:-NjF6sog9N5RQ2kX7Jl3:br611zk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc948d2fbee8bf273cd9b31b22dfa02b5adf4ef7/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt#L164)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As discussed offline, this improvement would be nice to include in the PR :thumbsup:
</blockquote></details>

State and dialog data is now calculated in the vm. And the dialog no longer accepts null. 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt` line 121 at r86](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjDJs8a3pAn0Ntjw4T_:-NjF74R64kYkkAoBRIX7:b-v6s1o3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0375045f5a3e5fa3df5774a82b42a50de299b886/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt#L121)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I'm not sure I follow the flow here. Why does the UI tell the use case which result/state the use case should be in?
</blockquote></details>

Removed. 
___
*[`android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt` line 137 at r84](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjDB-ox8IDa2d6SWotQ:-NjF7StU5F-YoNLV9Bf6:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b93a89ffc58d20e860a597eda24f910ed40d8d7f/android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt#L137)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This might be a bit misleading since we're not directly getting it from Koin as we did before
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/PlayPayment.kt` line 158 at r86](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjDEDXa3Xs_CapNbVc5:-NjF6mUI49S9k0HxDhIj:bvp45uw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0375045f5a3e5fa3df5774a82b42a50de299b886/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/PlayPayment.kt#L158)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Isn't this already known by the VM?
</blockquote></details>

This is no longer needed.


<!-- Sent from Reviewable.io -->

2023-11-14 23:47 UTC, albin-mullvad reviewed
> Reviewed 20 of 20 files at r87, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: all files reviewed, 10 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt` line 131 at r87](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjFBxFg3oacUBqxnBFz:-NjFBxFg3oacUBqxnBG-:b-l0vyqu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72ae830af4e6a346d9697f4cbad7b2fdb3249499/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt#L131)):*
> ```Kotlin
>     onCloseDialog: (isPaymentSuccessful: Boolean) -> Unit
> ) {
>     val onClick: (Boolean, PaymentClickAction) -> Unit = { isPaymentSuccessful, action ->
> ```

nit: I suggest renaming `onClick` (and perhaps clarified a bit?) to avoid the following which is used later in this function:

```
onClick = { ... , it.onClick) }
```


<!-- Sent from Reviewable.io -->

2023-11-15 08:18 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 100 of 108 files reviewed, 9 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreenTest.kt` line 45 at r86](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjD_WxwDmBf5Ec-716d:-NjH2VgBAfWfq30mF5Hi:b-6tbvzl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0375045f5a3e5fa3df5774a82b42a50de299b886/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreenTest.kt#L45)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe this test is a bit out-of-date since these functions were renamed. I guess we also have some changed/new test cases. Otherwise looks good.
</blockquote></details>

Fixed and added some tests


<!-- Sent from Reviewable.io -->

2023-11-15 08:45 UTC, albin-mullvad reviewed
> Reviewed 8 of 8 files at r88, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: all files reviewed, 9 unresolved discussions (waiting on @Rawa)



<!-- Sent from Reviewable.io -->

2023-11-15 09:36 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 105 of 108 files reviewed, 9 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 51 at r86](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjDZIri0QF_Q6z74TE2:-NjHJPdZCVaAjbZUSwX4:bnnrx10) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0375045f5a3e5fa3df5774a82b42a50de299b886/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L51)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why do we need replay for all of these tests? I'm concered that might result in false-positive test results since it's different behavior than the real implementation.
</blockquote></details>

That was a left over when the code was structured very differently. As far as I remembered it was of the limitations of shared flow that meant that for some tests to work I had to add it. Which I guess is another reminder that if your tests are too complicated your code is probably to... Anyway replaced all of the with state flows as that is what they actually are in the code.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModelTest.kt` line 199 at r47](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NingxqN4ewrYGPsCHmV:-NjHJ6X-9rm6RD6-Metc:b-ioqc59) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dd302f28d7550cf0eac5320019ba213e43da3ecf/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModelTest.kt#L199)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should just name it `val paymentAvailabilityError` so the test below becomes more readable. Sounds in the test like we emit payment availability while it is actually not available. Maybe the core problem is the name of `PaymentAvailability`?
</blockquote></details>

Renamed all `mockPaymentAvailability`.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModelTest.kt` line 209 at r86](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjDYfKnCuOPuu24QXBS:-NjHJC01BU9MfmjrVFdr:becpe3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0375045f5a3e5fa3df5774a82b42a50de299b886/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModelTest.kt#L209)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Do we need these comments? Can it be clarified by the assert code itself etc? This comment applies to other tests in this file.
</blockquote></details>

Simplified a lot of tests, so these comments are unnecessary now and thus removed.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModelTest.kt` line 167 at r86](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjDZt-fD1949gyzPW0e:-NjHK4MFEh5fV6FOj4BE:b1jvl3k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0375045f5a3e5fa3df5774a82b42a50de299b886/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModelTest.kt#L167)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is the change of order here significant?
</blockquote></details>

I don't think so. Restored.


<!-- Sent from Reviewable.io -->

2023-11-15 10:26 UTC, albin-mullvad reviewed
> Reviewed 2 of 3 files at r89, 1 of 1 files at r90, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: all files reviewed, 6 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt` line 51 at r86](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjDZIri0QF_Q6z74TE2:-NjHQycXAsVukJBfQtN1:bbbjjkh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0375045f5a3e5fa3df5774a82b42a50de299b886/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt#L51)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

That was a left over when the code was structured very differently. As far as I remembered it was of the limitations of shared flow that meant that for some tests to work I had to add it. Which I guess is another reminder that if your tests are too complicated your code is probably to... Anyway replaced all of the with state flows as that is what they actually are in the code.
</blockquote></details>

I see! Nice that it could be simplified a bit now
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModelTest.kt` line 209 at r86](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjDYfKnCuOPuu24QXBS:-NjHQOfrAgsNbVIjSwlV:b-dl13u1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0375045f5a3e5fa3df5774a82b42a50de299b886/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModelTest.kt#L209)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Simplified a lot of tests, so these comments are unnecessary now and thus removed.
</blockquote></details>

Nice! :thumbsup: 


<!-- Sent from Reviewable.io -->

2023-11-15 12:18 UTC, albin-mullvad reviewed
> Reviewed 1 of 1 files at r91, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: all files reviewed, 6 unresolved discussions (waiting on @Pururun and @Rawa)



<!-- Sent from Reviewable.io -->

2023-11-15 12:24 UTC, albin-mullvad reviewed
> Reviewed 1 of 1 files at r92, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: all files reviewed, 6 unresolved discussions (waiting on @Pururun and @Rawa)



<!-- Sent from Reviewable.io -->

2023-11-15 12:34 UTC, albin-mullvad reviewed
> Reviewed 2 of 2 files at r93, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt` line 131 at r87](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjFBxFg3oacUBqxnBFz:-NjHyLS31E6w9TNreFf_:bkudh8q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72ae830af4e6a346d9697f4cbad7b2fdb3249499/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt#L131)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: I suggest renaming `onClick` (and perhaps clarified a bit?) to avoid the following which is used later in this function:

```
onClick = { ... , it.onClick) }
```
</blockquote></details>

Basically to more easily be able to distinguish the two `onClick` functions when reading the code


<!-- Sent from Reviewable.io -->

2023-11-15 13:10 UTC, albin-mullvad reviewed
> Reviewed 2 of 75 files at r94, 9 of 11 files at r95, 15 of 57 files at r96, 1 of 1 files at r97, 54 of 58 files at r98, 3 of 3 files at r99, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2023-11-15 23:19 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: 105 of 110 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt` line 131 at r87](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjFBxFg3oacUBqxnBFz:-NjKGvZu8GcnUA9oUncK:bmlvuo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/72ae830af4e6a346d9697f4cbad7b2fdb3249499/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/payment/PaymentDialog.kt#L131)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Basically to more easily be able to distinguish the two `onClick` functions when reading the code
</blockquote></details>

Tidied up the code a bit and renamed it to `clickResolver` instead.
___
*[`android/lib/billing/src/androidTest/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepositoryTest.kt` line 1 at r84](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjD9pJU-A7j0xzLDiZe:-NjKBghxAnybo-RYkuUf:b-7jnol6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b93a89ffc58d20e860a597eda24f910ed40d8d7f/android/lib/billing/src/androidTest/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepositoryTest.kt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Would it be possible to add some test to check the `ensureConnected`/ mutex behavior? That would also reduce the risk of future regression.
</blockquote></details>

Added two tests.


<!-- Sent from Reviewable.io -->

2023-11-16 08:03 UTC, albin-mullvad approved these changes
> Reviewed 4 of 5 files at r100, 34 of 34 files at r101, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/lib/billing/src/androidTest/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepositoryTest.kt` line 1 at r84](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjD9pJU-A7j0xzLDiZe:-NjM8RJ24hIXBH7JU1hl:b-9qjxal) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b93a89ffc58d20e860a597eda24f910ed40d8d7f/android/lib/billing/src/androidTest/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepositoryTest.kt#L1)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Added two tests.
</blockquote></details>

Nice! :rocket: 
___
*[`android/lib/billing/src/androidTest/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepositoryTest.kt` line 339 at r101](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-NjM7DOy65tZ3P_Z9A2X:-NjM7DOy65tZ3P_Z9A2Y:b-p1yucf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c02236c5a5f0bf25bf9bb4acd2ca7543c91172f9/android/lib/billing/src/androidTest/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepositoryTest.kt#L339)):*
> ```Kotlin
>         // Act
>         billingRepository.queryPurchases()
> ```

nit: add `// Assert` comment for consistency


<!-- Sent from Reviewable.io -->

2023-11-16 08:07 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-:-NjM9gzf69IAYFTXaWKg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2023-11-16 08:08 UTC, sabercodic approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 58 files at r45, 1 of 1 files at r47, 5 of 58 files at r53, 1 of 1 files at r61.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-:-NjMA8DBA-A3n0AkFTW4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2023-11-16 08:23 UTC, albin-mullvad approved these changes
Fantastic job with this PR! :rocket: 

> Reviewed 2 of 2 files at r102, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125#-:-NjMDQTgE1-appwXURZr:b-oi9pz6)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-16 08:56 UTC, albin-mullvad approved these changes
> Reviewed 1 of 1 files at r103, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-16 09:48 UTC, albin-mullvad approved these changes
> Reviewed 5 of 5 files at r104, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5125)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-16 10:11 UTC, merged