Unify android build server script with the desktop equivalent
mullvad/mullvadvpn-app pull request #5161
Opened 2023-09-18 15:36 UTC by albin-mullvad

The scripts deviated some time ago so this commits aims to unify the android script with the desktop equivalent in terms of its structure as well as how it handles versioning and artifacts.

2023-09-18 18:08 UTC, raksooo reviewed
That output doesn't look right to me. Shouldn't it be the following?
```
upload
├── MullvadVPN-2023.6-beta1-dev-<hash>.aab
├── MullvadVPN-2023.6-beta1-dev-<hash>.apk
└── MullvadVPN-2023.6-beta1-dev-<hash>.sha256
```
where `MullvadVPN-2023.6-beta1-dev-<hash>.sha256` contains the hash for both files? Both files are are available when `upload` command is called so I don't understand why this happens.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5161#-:-NedSr_946dW0CQcWjQe:b-5vkvu6)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-19 06:51 UTC, albin-mullvad reviewed
Yeah, that's probably right. I might have missed something. I noticed that the upload script didn't work as expected when running it locally, which is probably related to this.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5161#-:-NegBrXt6vc-lmhsV_3h:b-nx8yhv)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-09-19 07:19 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5161)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`ci/buildserver-build-android.sh` line 112 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5161#-NegHhkiDIprKVQGNlQQ:-NegHhkiDIprKVQGNlQR:bm8f5qd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27ac0e490504359831c1d84eeadce78a2af771d8/ci/buildserver-build-android.sh#L112)):*
> ```Shell
>     fi
> 
>     (cd "$artifact_dir" && upload "$version") || return 1
> ```

Can't we just do:
```
cd $artifact_dir
upload "$version"
```
The script already has `set -eu` flag on top so any error should cancel execution? This would also go for the other cases of `return 1`
___
*[`ci/buildserver-build-android.sh` line 114 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5161#-NegFVeS3oO_Vp688RNE:-NegFVeS3oO_Vp688RNF:b-btp2me) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27ac0e490504359831c1d84eeadce78a2af771d8/ci/buildserver-build-android.sh#L114)):*
> ```Shell
>     (cd "$artifact_dir" && upload "$version") || return 1
>     # shellcheck disable=SC2216
>     yes | rm -r "$artifact_dir"
> ```

If we are piping in `yes` we might as well just do:  `rm -rf "$artifact_dir"` directly?


<!-- Sent from Reviewable.io -->

2023-09-19 11:57 UTC, raksooo approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5161)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Rawa)



<!-- Sent from Reviewable.io -->

2023-09-19 14:07 UTC, albin-mullvad reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5161)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @raksooo and @Rawa)

___
*[`ci/buildserver-build-android.sh` line 112 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5161#-NegHhkiDIprKVQGNlQQ:-NehkuEK4s9z4QH5i0v3:bwff840) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27ac0e490504359831c1d84eeadce78a2af771d8/ci/buildserver-build-android.sh#L112)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

It would have to be
```
pushd "$artifact_dir"
upload "$version"
popd
```

But yeah that would be easier to read.
</blockquote></details>

@Rawa agreed to keep this as-is since it's the same as the desktop script, right?
___
*[`ci/buildserver-build-android.sh` line 114 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5161#-NegFVeS3oO_Vp688RNE:-NehkdXf5on3mTpDdS-P:bwff840) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27ac0e490504359831c1d84eeadce78a2af771d8/ci/buildserver-build-android.sh#L114)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

If we are piping in `yes` we might as well just do:  `rm -rf "$artifact_dir"` directly?
</blockquote></details>

@Rawa agreed to keep this as-is since it's the same as the desktop script, right?


<!-- Sent from Reviewable.io -->

2023-09-20 07:12 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5161)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @raksooo)

___
*[`ci/buildserver-build-android.sh` line 114 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5161#-NegFVeS3oO_Vp688RNE:-NelQbo95KkwYMl2OB0Y:b-av6if2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27ac0e490504359831c1d84eeadce78a2af771d8/ci/buildserver-build-android.sh#L114)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

@Rawa agreed to keep this as-is since it's the same as the desktop script, right?
</blockquote></details>

Correct! :+1: 


<!-- Sent from Reviewable.io -->

2023-09-20 10:21 UTC, raksooo approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5161)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`ci/buildserver-build-android.sh` line 112 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5161#-NegHhkiDIprKVQGNlQQ:-Nem5o2j9VzpQysGcatw:b9oyhqa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/27ac0e490504359831c1d84eeadce78a2af771d8/ci/buildserver-build-android.sh#L112)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

@Rawa agreed to keep this as-is since it's the same as the desktop script, right?
</blockquote></details>

Yes, it's the same. Sounds good!


<!-- Sent from Reviewable.io -->

2023-09-21 09:28 UTC, merged