Migrate redeem voucher dialog into compose
mullvad/mullvadvpn-app pull request #5166
Opened 2023-09-19 15:43 UTC by sabercodic

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)

2023-09-20 08:33 UTC, Pururun reviewed
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 7 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Neleymn92l0u92y5W2k:-Neleymn92l0u92y5W2l:b-chh9nf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L54)):*
> ```Kotlin
> fun RedeemVoucherDialog(
>     uiState: VoucherDialogUiState,
>     viewActions: SharedFlow<Unit>,
> ```

It's a bit more readable and somewhat more scalable to have named actions, instead of just one action with unit. If it's not too much work.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 60 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelfF953XYp6oNM_IhV:-NelfF953XYp6oNM_IhW:bbowea3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L60)):*
> ```Kotlin
>     val voucher = remember { mutableStateOf("") }
> 
>     LaunchedEffect(Unit) { viewActions.collect { onDismiss() } }
> ```

See above, you could add an if statement here if we had named actions to make it easier to read.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelfVJjEFAVGDsL6joR:-NelfVJjEFAVGDsL6joS:ba086gh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L79)):*
> ```Kotlin
>                             contentColor = MaterialTheme.colorScheme.onSurface,
>                             disabledContentColor =
>                                 MaterialTheme.colorScheme.onSurface.copy(alpha = AlphaInactive),
> ```

This is a new thing, but I think we should be adding `compositeOver` so we are not displaying alpha components. 
So it would be `MaterialTheme.colorScheme.onSurface.copy(alpha = AlphaInactive).compositeOver(MaterialTheme.colorScheme.surface)`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelghnf3AMYwch07ad6:-Nelghnf3AMYwch07ad7:b-34vmyd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L81)):*
> ```Kotlin
>                                 MaterialTheme.colorScheme.onSurface.copy(alpha = AlphaInactive),
>                             disabledContainerColor =
>                                 MaterialTheme.colorScheme.surface.copy(alpha = AlphaDisabled)
> ```

See above
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelglW2CJYUJcT2ZNJr:-NelglW2CJYUJcT2ZNJs:b-6jnxsb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L113)):*
> ```Kotlin
>                     placeholderText = stringResource(id = R.string.voucher_hint),
>                     placeHolderColor =
>                         MaterialTheme.colorScheme.onPrimary.copy(alpha = AlphaDisabled),
> ```

See comment about alpha above
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 137 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelgvSi8TxWDize0c-m:-NelgvSi8TxWDize0c-n:b-d9er2l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L137)):*
> ```Kotlin
> }
> 
> private fun formatOtherVouchers(text: AnnotatedString): TransformedText {
> ```

This could be an extension function and maybe placed in a separate file?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt` line 90 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelhUC19VJiRsHnJ0CL:-NelhUC19VJiRsHnJ0CM:b-6jnxsb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt#L90)):*
> ```Kotlin
>             MaterialTheme.colorScheme.onPrimary
>         } else {
>             MaterialTheme.colorScheme.onPrimary.copy(AlphaInactive)
> ```

See comment about alpha above


<!-- Sent from Reviewable.io -->

2023-09-20 09:15 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 16 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NellqRf3gE6KlNOcYfk:-NellqRf3gE6KlNOcYfl:b27ltty) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L58)):*
> ```Kotlin
>     onDismiss: () -> Unit
> ) {
>     val voucher = remember { mutableStateOf("") }
> ```

`var voucher by remember { mutableStateof("") }`
I think using the by delegate would make it more readable since we are activity changing and updating the voucher variable.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelmQXDC22ocYs2ic0K:-NelmQXDC22ocYs2ic0L:b-yopq9u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L107)):*
> ```Kotlin
>                     },
>                     onValueChanged = { input ->
>                         voucher.value = input.uppercase().format().replace(" ", "").replace("-", "")
> ```

Why do we have to remove "-" and " "? Can we convert it automatically instead?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 124 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelmt_5E9RYbQDex4pB:-Nelmt_5E9RYbQDex4pC:b-4ekbp0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L124)):*
> ```Kotlin
>                 if (uiState.message != null) {
>                     Text(
>                         text = uiState.message!!,
> ```

Why do we need `!!`, if we had a null check above? Maybe 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 137 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelgvSi8TxWDize0c-m:-Neloj6fBV6NYDNhb2QH:b-7u1gk7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L137)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This could be an extension function and maybe placed in a separate file?
</blockquote></details>

Also would be it possible to do in a simpler way? It looks a bit too complex, I did this one for AccountNumber, maybe it can be used as a reference:
https://github.com/mullvad/mullvadvpn-app/blob/b42e5e0262d021d955a9926ac18ea7971e0cd94b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/AccountTokenVisualTransformation.kt
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelnE0L7WXZmcPFQ-cO:-NelnE0L7WXZmcPFQ-cP:bazv64r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt#L6)):*
> ```Kotlin
>     var message: String? = null,
>     var isError: Boolean = false,
>     var showLoading: Boolean = false
> ```

None of these should be `var`in my opinion.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelnsg07Wf3fZQR6UOw:-Nelnsg07Wf3fZQR6UOx:bmn8ufl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt#L14)):*
> ```Kotlin
>     data object Verifying : VoucherDialogViewModelState()
> 
>     data class Success(var message: String?) : VoucherDialogViewModelState()
> ```

Should not be `var`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelpa5h7QrVuEHOSWts:-Nelpa5h7QrVuEHOSWtt:b7chpyt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt#L65)):*
> ```Kotlin
> ) {
>     val shape = RoundedCornerShape(4.dp)
>     val textFieldHeight = 44.dp
> ```

We should avoid having a fixed textFieldHeight.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/RedeemVoucherDialogFragment.kt` line 34 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelq0a62WeVdYdfy5mS:-Nelq0a62WeVdYdfy5mT:b-ts7ysj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/RedeemVoucherDialogFragment.kt#L34)):*
> ```Kotlin
>                         viewActions = vm.viewActions,
>                         onRedeem = { vm.onRedeem(it) },
>                         onDismiss = { onDismiss(voucherDialog!!) }
> ```

Is `!!` necessary? Looks like it is already marked as `lateinit var`?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelqxOlASXhX3sWHzKU:-NelqxOlASXhX3sWHzKV:b-8lsand) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L27)):*
> ```Kotlin
>     val viewActions = _viewActions.asSharedFlow()
> 
>     private var voucherRedeemer: VoucherRedeemer? = null
> ```

Does this really have to be nullable? Can't we inject it?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelr8Kw-KLQIt_6mLoh:-Nelr8Kw-KLQIt_6mLoi:b-7ou2lk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L40)):*
> ```Kotlin
>     fun onRedeem(voucherCode: String) {
>         serviceConnectionManager.serviceNotifier.subscribe(this) { connection ->
>             voucherRedeemer = connection?.voucherRedeemer
> ```

Not sure if it makes sense that the voucherRedeemer can be null? If it is, then it should be an error to the user as well I believe. This function ends up becoming fail silent if voucherRedeemer is `null`. Probably better to `!!` it then if it really is necessary.


<!-- Sent from Reviewable.io -->

2023-09-20 15:50 UTC, Rawa reviewed
> Reviewed 4 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 16 unresolved discussions (waiting on @Pururun and @sabercodic)



<!-- Sent from Reviewable.io -->

2023-09-21 08:58 UTC, Pururun reviewed
> Reviewed 3 of 5 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 19 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 71 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Neqx3oz-uLn3CBlJKaB:-Neqx3oz-uLn3CBlJKaC:b7ixw2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/183a2a9467983070b4fecbb60b0d935383fe7f85/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L71)):*
> ```Kotlin
>     private fun setError(error: VoucherSubmissionError) {
>         viewModelScope.launch {
>             val message =
> ```

I think we should not call `getString` in view model
___
*[`wireguard/libwg/go.mod` line 13 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NeqxRJ26f0pee02LZtC:-NeqxRJ26f0pee02LZtD:b-3is68b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/183a2a9467983070b4fecbb60b0d935383fe7f85/wireguard/libwg/go.mod#L13)):*
> ```XML
> 	golang.org/x/crypto v0.0.0-20220722155217-630584e8d5aa // indirect
> 	golang.org/x/net v0.0.0-20220809184613-07c6da5e1ced // indirect
> 	golang.zx2c4.com/wintun v0.0.0-20211104114900-415007cec224 // indirect
> ```

Should probably not be in this commit.
___
*[`wireguard/libwg/go.sum` line 8 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NeqxW9i2W-SwuMGxBEv:-NeqxW9i2W-SwuMGxBEw:b-3is68b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/183a2a9467983070b4fecbb60b0d935383fe7f85/wireguard/libwg/go.sum#L8)):*
> ```
> golang.org/x/sys v0.0.0-20220808155132-1c4a2a72c664/go.mod h1:oPkhp1MJrh7nUepCBck5+mAzfO9JrbApNNgaTdGDITg=
> golang.zx2c4.com/wintun v0.0.0-20211104114900-415007cec224 h1:Ug9qvr1myri/zFN6xL17LSCBGFDnphBBhzmILHsM5TY=
> golang.zx2c4.com/wintun v0.0.0-20211104114900-415007cec224/go.mod h1:deeaetjYA+DHMHg+sMSMI58GrEteJUUzzw7en6TJQcI=
> ```

Should probably not be in this commit.


<!-- Sent from Reviewable.io -->

2023-09-21 13:48 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 18 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Neleymn92l0u92y5W2k:-Nerkirk-BjFEi8b47_I:b-5j8y46) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L54)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

It's a bit more readable and somewhat more scalable to have named actions, instead of just one action with unit. If it's not too much work.
</blockquote></details>

Removed, its not needed anymore
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelfVJjEFAVGDsL6joR:-NerlV9XDukpsttj7kzY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L79)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This is a new thing, but I think we should be adding `compositeOver` so we are not displaying alpha components. 
So it would be `MaterialTheme.colorScheme.onSurface.copy(alpha = AlphaInactive).compositeOver(MaterialTheme.colorScheme.surface)`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelghnf3AMYwch07ad6:-NerlVW77uXXmE7sKU24:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L81)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelmQXDC22ocYs2ic0K:-NerlkwlDSz2pQgprQkS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L107)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Why do we have to remove "-" and " "? Can we convert it automatically instead?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelglW2CJYUJcT2ZNJr:-NerlrVR8AeHj-_Vk9Bx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L113)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

See comment about alpha above
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 124 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelmt_5E9RYbQDex4pB:-Nerlw0x3DNkyedwFzMl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L124)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Why do we need `!!`, if we had a null check above? Maybe
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 137 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelgvSi8TxWDize0c-m:-NerxFnS60u9owfLSKrj:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L137)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Also would be it possible to do in a simpler way? It looks a bit too complex, I did this one for AccountNumber, maybe it can be used as a reference:
https://github.com/mullvad/mullvadvpn-app/blob/b42e5e0262d021d955a9926ac18ea7971e0cd94b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/AccountTokenVisualTransformation.kt
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelnE0L7WXZmcPFQ-cO:-NerxLhk3mQ9zHPWDYNe:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt#L6)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

None of these should be `var`in my opinion.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelnsg07Wf3fZQR6UOw:-NerxMQa8RMTFqe3mG8_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt#L14)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should not be `var`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelpa5h7QrVuEHOSWts:-NeryCY4CBHdYH9fNY6G:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt#L65)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should avoid having a fixed textFieldHeight.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt` line 90 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelhUC19VJiRsHnJ0CL:-Nery9_z3m5lth64JG_7:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt#L90)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

See comment about alpha above
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/RedeemVoucherDialogFragment.kt` line 34 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelq0a62WeVdYdfy5mS:-NeryIUM-S_yh6_7pPYN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/RedeemVoucherDialogFragment.kt#L34)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Is `!!` necessary? Looks like it is already marked as `lateinit var`?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 71 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Neqx3oz-uLn3CBlJKaB:-NeryuRW [...]

2023-09-22 09:58 UTC, Pururun reviewed
> Reviewed 33 of 33 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 14 unresolved discussions (waiting on @Rawa and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 218 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NewGxjv3nfakJkaE9Z3:-NewGxjv3nfakJkaE9Z4:bc86kwh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/668bbf078475d1b8f3c1a98707838ec5a8440692/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L218)):*
> ```Kotlin
>                                 text =
>                                     if (uiState is VoucherDialogUiState.Error) uiState.errorMessage
>                                     else "",
> ```

Is this an expected state? Will not look weird for a user or how will it look when this happens?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt` line 66 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NewI0-46xtxsxtBC0wM:-NewI0-46xtxsxtBC0wN:b6y8nuz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/668bbf078475d1b8f3c1a98707838ec5a8440692/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt#L66)):*
> ```Kotlin
>     textAlign: TextAlign = TextAlign.Start
> ) {
>     val shape = RoundedCornerShape(4.dp)
> ```

Could be replaced by `MaterialTheme.shapes.small` if we want to avoid magic numbers.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 27 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NewIl4z2cB33AbpRUiW:-NewIl4z2cB33AbpRUiX:b-71d5zu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/668bbf078475d1b8f3c1a98707838ec5a8440692/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L27)):*
> ```Kotlin
> 
>     private var voucherRedeemer: VoucherRedeemer? =
>         serviceConnectionManager.connectionState.value.readyContainer()?.voucherRedeemer
> ```

Probably better to do something like this:
(From `ConnectionViewModel`)



_Code snippet:_
```Kotlin
private val _shared: SharedFlow<ServiceConnectionContainer> =
        serviceConnectionManager.connectionState
            .flatMapLatest { state ->
                if (state is ServiceConnectionState.ConnectedReady) {
                    flowOf(state.container)
                } else {
                    emptyFlow()
                }
            }
            .shareIn(viewModelScope, SharingStarted.WhileSubscribed())
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 53 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NewJD0gAJRjZv0ye_9I:-NewJD0gAJRjZv0ye_9J:b-awhnjg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/668bbf078475d1b8f3c1a98707838ec5a8440692/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L53)):*
> ```Kotlin
>                 VoucherDialogUiState.Success(
>                     if (days > 60) {
>                         resources.getQuantityString(
> ```

Probably better to move this out of the view model


<!-- Sent from Reviewable.io -->

2023-09-27 07:04 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 7 of 36 files reviewed, 16 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 224 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfKRXYqAZFRwV3BstBq:-NfKRXYqAZFRwV3BstBr:bdq1xy0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/39f91a19f8a4b14e601e9130764cd93f51000f98/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L224)):*
> ```Kotlin
>                 }
>             }
>         },
> ```

There is a lot of depth to this function, is it possible to maybe refactor some out?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 233 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfKJSjL10jnXciJaKGu:-NfKJSjL10jnXciJaKGv:b-mugprn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/39f91a19f8a4b14e601e9130764cd93f51000f98/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L233)):*
> ```Kotlin
> const val ACCOUNT_TOKEN_CHUNK_SIZE = 4
> 
> private fun vouchersVisualTransformation(text: AnnotatedString, maxSize: Int): TransformedText {
> ```

It would be nicer to directly implement VisualTransformation interface:
```
VisualTransformation { annotatedString -> 
    // Implementation goes here
} ```

and move then logic of maxSize to the onValueChange handler.
```

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelnsg07Wf3fZQR6UOw:-NfFPjA16aiEdMdOJrdF:bedthnv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt#L14)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Seems like `data class Success(var message: String) : VoucherDialogUiState()` still uses `var`, maybe latest has not been pushed?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt` line 3 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfFPew14bBT1biTJhYZ:-NfFPew14bBT1biTJhY_:b-r6tlow) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/39f91a19f8a4b14e601e9130764cd93f51000f98/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt#L3)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.compose.state
> 
> sealed class VoucherDialogUiState {
> ```

`sealed interface`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelpa5h7QrVuEHOSWts:-NfFOMpg2VwXinqshWz_:b-h6jkj2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt#L65)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If height is a fixed value, it will clip text when user has it set large fonts. We should avoid using `height` `modifier` on anything that contains text
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt` line 146 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfKRovB5T10mXmBawOs:-NfKRovB5T10mXmBawOt:btxfnq3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/39f91a19f8a4b14e601e9130764cd93f51000f98/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt#L146)):*
> ```Kotlin
>                     onFocusChange(focusState.isFocused)
>                 }
>                 .height(textFieldHeight)
> ```

Here is where we should avoid using height, otherwise it might not render nicely when users have large fonts


<!-- Sent from Reviewable.io -->

2023-09-27 11:26 UTC, Pururun requested changes
> Reviewed 1 of 23 files at r5, 6 of 9 files at r6, 23 of 23 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 19 unresolved discussions (waiting on @Rawa and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt` line 42 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfLMmS518TZbb8siKOl:-NfLMmS518TZbb8siKOm:b-us6x7j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/154601482c9417bcf5fbd403b1cdebc9d569f298/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt#L42)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.lib.theme.MullvadWhite10
> 
> internal const val EMPTY_STRING = ""
> ```

Any specific reason this is `internal`?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/AccountExpiryConstant.kt` line 6 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfLMy8K8Sc-35WE9bZo:-NfLMy8K8Sc-35WE9bZp:btolqo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/154601482c9417bcf5fbd403b1cdebc9d569f298/android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/AccountExpiryConstant.kt#L6)):*
> ```Kotlin
> const val SECONDS_PER_DAY: Long = 86400
> const val SECONDS_PER_MONTH: Long = 2592000
> const val SECONDS_PER_YEAR: Long = 31104000
> ```

Is there a better way to show this since it's just look like magic numbers?
___
*[`gui/locales/messages.pot` line 1605 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfLNnENCNbrcpI_o_ZI:-NfLNnENCNbrcpI_o_ZJ:b-3fpakw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/154601482c9417bcf5fbd403b1cdebc9d569f298/gui/locales/messages.pot#L1605)):*
> ```pot
> msgstr ""
> 
> msgid "%d months was added to your account."
> ```

I guess all these strings were added by the script by mistake? This PR should not add any copy right?


<!-- Sent from Reviewable.io -->

2023-09-28 16:54 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 30 of 37 files reviewed, 19 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NellqRf3gE6KlNOcYfk:-NfRfd8oBzybPZuVmrcy:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L58)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`var voucher by remember { mutableStateof("") }`
I think using the by delegate would make it more readable since we are activity changing and updating the voucher variable.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 218 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NewGxjv3nfakJkaE9Z3:-NfBnFTl1AtQKWCQll6x:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/668bbf078475d1b8f3c1a98707838ec5a8440692/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L218)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Is this an expected state? Will not look weird for a user or how will it look when this happens?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt` line 66 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NewI0-46xtxsxtBC0wM:-NewcPVd3EWz4BOvtBSE:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/668bbf078475d1b8f3c1a98707838ec5a8440692/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt#L66)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Could be replaced by `MaterialTheme.shapes.small` if we want to avoid magic numbers.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-02 12:30 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 17 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 224 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfKRXYqAZFRwV3BstBq:-Nfjnr6m44lLRho8b-r4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/39f91a19f8a4b14e601e9130764cd93f51000f98/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L224)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

There is a lot of depth to this function, is it possible to maybe refactor some out?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 233 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfKJSjL10jnXciJaKGu:-Nfk9PrX4Wgica0MvJl3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/39f91a19f8a4b14e601e9130764cd93f51000f98/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L233)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

It would be nicer to directly implement VisualTransformation interface:
```
VisualTransformation { annotatedString -> 
    // Implementation goes here
} ```

and move then logic of maxSize to the onValueChange handler.
```

</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelnsg07Wf3fZQR6UOw:-Nfjr2xAANk7VBpMGWyK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt#L14)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Seems like `data class Success(var message: String) : VoucherDialogUiState()` still uses `var`, maybe latest has not been pushed?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt` line 3 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfFPew14bBT1biTJhYZ:-Nfjr7RK-ETAYGPwUB6c:b-69nqf7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/39f91a19f8a4b14e601e9130764cd93f51000f98/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt#L3)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`sealed interface`
</blockquote></details>

please check again, implementation changed, so is this still required?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt` line 18 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfjWZF59CCTsQpJJOYp:-Nfjr-fd9_YxVcYb084E:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/801f0b19311806dddbf8a458efe1ddc308de8813/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VoucherDialogUiState.kt#L18)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This should be a `val`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelpa5h7QrVuEHOSWts:-Nfjri6U6dQ_iDB6Y5hY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt#L65)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

If height is a fixed value, it will clip text when user has it set large fonts. We should avoid using `height` `modifier` on anything that contains text
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt` line 146 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfKRovB5T10mXmBawOs:-NfjrlbGDO4Eng_u7nQe:b-hfpv0l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/39f91a19f8a4b14e601e9130764cd93f51000f98/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/GroupedTextField.kt#L146)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Here is where we should avoid using height, otherwise it might not render nicely when users have large fonts
</blockquote></details>

removed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/AccountExpiryConstant.kt` line 6 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfLMy8K8Sc-35WE9bZo:-NfjsYUZ2RAlMuHArjkb:b-aozrqc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/154601482c9417bcf5fbd403b1cdebc9d569f298/android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/AccountExpiryConstant.kt#L6)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Is there a better way to show this since it's just look like magic numbers?
</blockquote></details>

replaced by system constants
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NelqxOlASXhX3sWHzKU:-NfkK6dV5HgPGRfo0q6z:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L27)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Does this really have to be nullable? Can't we inject it?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Nelr8Kw-KLQIt_6mLoh:-NfkK889E7gPmzVBHK0H:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38b04d37b16cb9879bc0421f00df301c2adcc212/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L40)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Not sure if it makes sense that the voucherRedeemer can be null? If it is, then it should be an error to the user as well I believe. This function ends up becoming fail silent if voucherRedeemer is `null`. Probably better to `!!` it then if it really is necessary.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 27 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NewIl4z2cB33AbpRUiW:-NfkK73ZDrnnmELlVxz2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/668bbf078475d1b8f3c1a98707838ec5a8440692/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L27)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Probably better to do something like this:
(From `ConnectionViewModel`)
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 53 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NewJD0gAJRjZv0ye_9I:-NfkLv6LDUEzMG8RnUqB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/668bbf078475d1b8f3c1a98707838ec5a8440692/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L53)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Probably better to move this out of the view model
</blockquote></details>

Done.
___
*[`gui/local [...]

2023-10-02 12:37 UTC, Pururun approved these changes
> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 11 unresolved discussions (waiting on @Rawa)

___
*[`gui/locales/messages.pot` line 1605 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfLNnENCNbrcpI_o_ZI:-NfkNvvm4pcMnEMWj9Mb:bd8do77) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/154601482c9417bcf5fbd403b1cdebc9d569f298/gui/locales/messages.pot#L1605)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

these messages belong to redeem voucher success  screen
</blockquote></details>

Ah nice. :+1: 


<!-- Sent from Reviewable.io -->

2023-10-02 12:52 UTC, Rawa requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 99 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfkQu5NC393XPX3Ki_Z:-NfkQu5O9mcAzgJvH7Vo:bvwh1um) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a253f2756e1dbb6faaaa1b250f2f10049228c8a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L99)):*
> ```Kotlin
>     onDismiss: () -> Unit
> ) {
>     //    val voucher = remember { mutableStateOf("") }
> ```

Can we remove?


<!-- Sent from Reviewable.io -->

2023-10-03 09:03 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 35 of 38 files reviewed, 1 unresolved discussion (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 99 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfkQu5NC393XPX3Ki_Z:-NfokuTkDoL4cnNHWd4N:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a253f2756e1dbb6faaaa1b250f2f10049228c8a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L99)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Can we remove?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-03 14:51 UTC, Pururun approved these changes
> Reviewed 5 of 6 files at r13, 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)



<!-- Sent from Reviewable.io -->

2023-10-04 13:26 UTC, Rawa approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-:-NfurTxd1tD5Q-QhZV2F:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-04 13:26 UTC, Rawa approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-05 08:36 UTC, Pururun approved these changes
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-05 11:52 UTC, Pururun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-:-NfzfZ9mC97k4h7ryZV2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-05 13:13 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/lib/resource/src/main/res/values/plurals.xml` line 50 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfzxAXD-O40aLKf4fp4:-NfzxAXD-O40aLKf4fp5:b-g8in21) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35f27a9a1003ef092ccc6b85096cf9f1cc9cb999/android/lib/resource/src/main/res/values/plurals.xml#L50)):*
> ```XML
>         <item quantity="one">1 month was added to your account.</item>
>         <item quantity="other">%d months was added to your account.</item>
>     </plurals>
> ```

I'm not sure these are correct or enough. The vouchers we sell are for 6 or 12 months. Also, wouldn't it make sense to split it into something plurals like `1 day`/`1 month` and a string like `% was added to your account`?



_Code quote:_
```XML
    <plurals name="days_added_to_your_account">
        <item quantity="one">1 day was added to your account.</item>
        <item quantity="other">%d days was added to your account.</item>
    </plurals>
    <plurals name="months_added_to_your_account">
        <item quantity="one">1 month was added to your account.</item>
        <item quantity="other">%d months was added to your account.</item>
    </plurals>
```


<!-- Sent from Reviewable.io -->

2023-10-06 07:29 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/lib/resource/src/main/res/values/plurals.xml` line 50 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfzxAXD-O40aLKf4fp4:-Ng2pgfb8Zrv3L8FrUxT:b-rv0sno) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35f27a9a1003ef092ccc6b85096cf9f1cc9cb999/android/lib/resource/src/main/res/values/plurals.xml#L50)):*
> it into something plurals like `1 day`/`1 month` and a string like `% was added to your account`

I think this is a tricky one, do we know that all languages would structure the rest of the sentence in the same way given the first part is day, hour, month, year etc? I wouldn't be surprised if the second part of a sentence may change a little if we are talking about day/month/year depending the language. (e.g if the words are masculine, feminine or neutral or other crazy linguistics)


<!-- Sent from Reviewable.io -->

2023-10-06 07:45 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 34 of 57 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Pururun)

___
*[`android/lib/resource/src/main/res/values/plurals.xml` line 50 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NfzxAXD-O40aLKf4fp4:-Ng2wbgG6ZC-OmVoitKN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/35f27a9a1003ef092ccc6b85096cf9f1cc9cb999/android/lib/resource/src/main/res/values/plurals.xml#L50)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

> it into something plurals like `1 day`/`1 month` and a string like `% was added to your account`

I think this is a tricky one, do we know that all languages would structure the rest of the sentence in the same way given the first part is day, hour, month, year etc? I wouldn't be surprised if the second part of a sentence may change a little if we are talking about day/month/year depending the language. (e.g if the words are masculine, feminine or neutral or other crazy linguistics)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-09 06:11 UTC, albin-mullvad requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 34 of 57 files reviewed, 2 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`-- commits` line 11 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Ng3ixbxCHHakc9EHlGB):*
Cleanup



_Code quote:_
```
 Remove unused file
```
___
*[`-- commits` line 12 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Ng3izRx-sVjHGBDmPMo):*
Can this be done in a separate commit like we usually try to do?



_Code quote:_
```
Update changeLog
```


<!-- Sent from Reviewable.io -->

2023-10-09 07:21 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 34 of 57 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`-- commits` line 11 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Ng3ixbxCHHakc9EHlGB):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Cleanup
</blockquote></details>

Done.
___
*[`-- commits` line 12 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Ng3izRx-sVjHGBDmPMo):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this be done in a separate commit like we usually try to do?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-09 09:21 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 34 of 57 files reviewed, 2 unresolved discussions (waiting on @Pururun and @sabercodic)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgIiMYdDYvksXkiY5zS:-NgIiMYdDYvksXkiY5zT:bv1m19b) (no related file):*
Is the looks of the input text field aligned with the dialogs in VPN Settings? The input text field background looks different and the text is more bold :thinking: 

I also noticed that the corners of the Zeplin design use rounded corners for the input text field.

![voucher-bold-and-space.png](https://files.reviewableusercontent.io/images/reviewable/90636006/AobJ7YCgIPil2Td3zMXMMkZF/voucher-bold-and-space.png)

___
___
*[`-- commits` line 11 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Ng3ixbxCHHakc9EHlGB):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still there
___
*[`-- commits` line 12 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Ng3izRx-sVjHGBDmPMo):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still there


<!-- Sent from Reviewable.io -->

2023-10-09 10:54 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 32 of 57 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Pururun)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgIiMYdDYvksXkiY5zS:-NgJ3gpZ2OLXxEx9L6B9:b-r0mqu4) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is the looks of the input text field aligned with the dialogs in VPN Settings? The input text field background looks different and the text is more bold :thinking: 

I also noticed that the corners of the Zeplin design use rounded corners for the input text field.

![voucher-bold-and-space.png](https://files.reviewableusercontent.io/images/reviewable/90636006/AobJ7YCgIPil2Td3zMXMMkZF/voucher-bold-and-space.png)
</blockquote></details>

Text field replaced

___
___
*[`-- commits` line 11 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Ng3ixbxCHHakc9EHlGB):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Still there
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-09 11:22 UTC, Pururun reviewed
> Reviewed 1 of 23 files at r17, 20 of 21 files at r19, 1 of 1 files at r20, 3 of 3 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgIiMYdDYvksXkiY5zS:-NgJ7_7h8HVCDUjLvIfQ:b-gu46im) (no related file):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Text field replaced
</blockquote></details>

To clarify, we are now more or less using the same input field as the other dialog. They are not 100% according to design, but it is probably better to fix the input field for all dialogs at the same time. I added a linear issue here:

https://linear.app/mullvad/issue/DROID-393/improve-text-field-appearance

___


<!-- Sent from Reviewable.io -->

2023-10-09 11:49 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 53 of 57 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Pururun)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgIiMYdDYvksXkiY5zS:-NgJGB_i4pRv-bg2lIrB:b-896fix) (no related file):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

To clarify, we are now more or less using the same input field as the other dialog. They are not 100% according to design, but it is probably better to fix the input field for all dialogs at the same time. I added a linear issue here:

https://linear.app/mullvad/issue/DROID-393/improve-text-field-appearance
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-10-09 12:07 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 53 of 57 files reviewed, 2 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`-- commits` line 11 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Ng3ixbxCHHakc9EHlGB):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, it's still there. Please check properly before claiming it's done since this is wasting time.


<!-- Sent from Reviewable.io -->

2023-10-09 12:23 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 53 of 57 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`-- commits` line 11 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-Ng3ixbxCHHakc9EHlGB):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

No, it's still there. Please check properly before claiming it's done since this is wasting time.
</blockquote></details>

My bad, I pulled last changes from @Pururun push and I did not check remove it again


<!-- Sent from Reviewable.io -->

2023-10-09 13:36 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 4 unresolved discussions (waiting on @sabercodic)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJX8QvEII6iVKzD46J:-NgJX8QvEII6iVKzD46K:bsf5w3m) (no related file):*
The top padding of the success dialog icon doesn't look correct according to other dialog icons. Perhaps also too much bottom padding. Please make sure all paddings are correct.

![voucher-success-padding.png](https://files.reviewableusercontent.io/images/reviewable/90636006/X5Paes0ZWwdKBDHjg0CI43Hi/voucher-success-padding.png)

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJXnHc7zyDBtg7B9zn:-NgJXnHc7zyDBtg7B9zo:by9ah7y) (no related file):*
The input behavior is a bit different from desktop.

The current behavior in this PR is that if I enter "ABCD" and then try to enter the hyphen (`-`) according to the voucher code, I will simply not be allowed, which might be very confusing. If I enter another character it will however be automatically added before the new character. Is this the same as before the migration? To me it would make sense to not block the user from entering a hyphen on the correct place :thinking:  

As a comparison, on desktop the hyphen will be automatically added immediately after entering the "D" from the above example.

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJZq3R6yEFdj4ZqvQZ:-NgJZq3R6yEFdj4ZqvQ_:b-p551mc) (no related file):*
Can the underline be removed? Is it caused by auto-suggestion or auto-complete? We shouldn't have that enabled. See difference between letter input and number input on the attached screenshots:

![voucher-dialog-letters.png](https://files.reviewableusercontent.io/images/reviewable/90636006/THXycCx_4HKoLm28apEpsr4T/voucher-dialog-letters.png)
![voucher-dialog-digits.png](https://files.reviewableusercontent.io/images/reviewable/90636006/kiOLcAhZ8u6VhK_NKCT-SmFP/voucher-dialog-digits.png)

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJaLHW-YsCB8vlBIRa:-NgJaLHW-YsCB8vlBIRb:bgc1o0w) (no related file):*
There seem to be a few DPAD issues with this dialog:
* After opening the dialog, it's not possible to click down to enter the text field. Clicking down twice will focus the Cancel button.
* After opening the dialog, it's necessary to click up twice to reach the Cancel button.

The first one is probably specific to this PR, however the second one might be common with other dialogs and can perhaps we handled in a separate PR?

___


<!-- Sent from Reviewable.io -->

2023-10-09 14:37 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @sabercodic)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJZq3R6yEFdj4ZqvQZ:-NgJrBDrEKaNpOi67P4x:b8n84zw) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can the underline be removed? Is it caused by auto-suggestion or auto-complete? We shouldn't have that enabled. See difference between letter input and number input on the attached screenshots:

![voucher-dialog-letters.png](https://files.reviewableusercontent.io/images/reviewable/90636006/THXycCx_4HKoLm28apEpsr4T/voucher-dialog-letters.png)
![voucher-dialog-digits.png](https://files.reviewableusercontent.io/images/reviewable/90636006/kiOLcAhZ8u6VhK_NKCT-SmFP/voucher-dialog-digits.png)
</blockquote></details>

@albin-mullvad In regards to the underline issue it seems to be related to the keyboard type that you set, so for example keyboard type number does not show it, but most other keyboard types do. The only keyboard type that does not show the underline is password and that one has a few other quirks. For example it will obfuscated any text in your clipboard.

___


<!-- Sent from Reviewable.io -->

2023-10-09 14:52 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun and @sabercodic)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJZq3R6yEFdj4ZqvQZ:-NgJuQOe-SJ8LTwBJ80R:bwnthqe) (no related file):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

@albin-mullvad In regards to the underline issue it seems to be related to the keyboard type that you set, so for example keyboard type number does not show it, but most other keyboard types do. The only keyboard type that does not show the underline is password and that one has a few other quirks. For example it will obfuscated any text in your clipboard.
</blockquote></details>

Does that mean we can't use the password keyboard type? In what way does it obfuscate things? The documentation here doesn't say much: https://developer.android.com/reference/kotlin/androidx/compose/ui/text/input/KeyboardType#Password()

___


<!-- Sent from Reviewable.io -->

2023-10-10 07:58 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: all files reviewed, 4 unresolved discussions (waiting on @albin-mullvad)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJX8QvEII6iVKzD46J:-NgJjpp88Msgpykse7CT:b-5f5nrb) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The top padding of the success dialog icon doesn't look correct according to other dialog icons. Perhaps also too much bottom padding. Please make sure all paddings are correct.

![voucher-success-padding.png](https://files.reviewableusercontent.io/images/reviewable/90636006/X5Paes0ZWwdKBDHjg0CI43Hi/voucher-success-padding.png)
</blockquote></details>

should I consider other dialogs? or Zepline?
https://zpl.io/29mWd8e

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJZq3R6yEFdj4ZqvQZ:-NgNUsje61dswR4mPK5B:b-896fix) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Does that mean we can't use the password keyboard type? In what way does it obfuscate things? The documentation here doesn't say much: https://developer.android.com/reference/kotlin/androidx/compose/ui/text/input/KeyboardType#Password()
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJaLHW-YsCB8vlBIRa:-NgNZdrt-fYNu-EaXLwE:b-896fix) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

There seem to be a few DPAD issues with this dialog:
* After opening the dialog, it's not possible to click down to enter the text field. Clicking down twice will focus the Cancel button.
* After opening the dialog, it's necessary to click up twice to reach the Cancel button.

The first one is probably specific to this PR, however the second one might be common with other dialogs and can perhaps we handled in a separate PR?
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJXnHc7zyDBtg7B9zn:-NgNZflx9Jad1PQy6zpI:bmv1fxd) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The input behavior is a bit different from desktop.

The current behavior in this PR is that if I enter "ABCD" and then try to enter the hyphen (`-`) according to the voucher code, I will simply not be allowed, which might be very confusing. If I enter another character it will however be automatically added before the new character. Is this the same as before the migration? To me it would make sense to not block the user from entering a hyphen on the correct place :thinking:  

As a comparison, on desktop the hyphen will be automatically added immediately after entering the "D" from the above example.
</blockquote></details>

This visual transformation is a replica of login input, Should I change it?

___


<!-- Sent from Reviewable.io -->

2023-10-10 08:18 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 55 of 57 files reviewed, 5 unresolved discussions (waiting on @Pururun and @sabercodic)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJX8QvEII6iVKzD46J:-NgNcQLx5ZaSjdDAmMI6:bcb5v75) (no related file):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

should I consider other dialogs? or Zepline?
https://zpl.io/29mWd8e
</blockquote></details>

Can you check with Matilda whether that Zeplin design is correct since the icon padding is different from the other dialogs?

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJXnHc7zyDBtg7B9zn:-NgNe9fS03rA8kKG_3Tv:b3qcukt) (no related file):*
Please answer this question:

> Is this the same as before the migration?

___
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt` line 161 at r26](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgNdes42Og0sBHPVhnl:-NgNdes42Og0sBHPVhnm:bkt5jas) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14ae580f8c06f783a9a9d4c0d0560f469716fdb1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt#L161)):*
> ```Kotlin
>                             focusManager.moveFocus(FocusDirection.Up)
>                             true
>                         }
> ```

Will removing these not affect the DPAD navigation in other text fields in the settings view? I mean there was a reason we added these.



_Code quote:_
```Kotlin
                        KeyEvent.KEYCODE_DPAD_DOWN -> {
                            focusManager.moveFocus(FocusDirection.Down)
                            true
                        }
                        KeyEvent.KEYCODE_DPAD_UP -> {
                            focusManager.moveFocus(FocusDirection.Up)
                            true
                        }
```


<!-- Sent from Reviewable.io -->

2023-10-10 08:41 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 55 of 57 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @Pururun)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJXnHc7zyDBtg7B9zn:-NgNh1sV2y_LD-X7KJxP:buydspf) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Please answer this question:

> Is this the same as before the migration?
</blockquote></details>

No, There was bugs in previous implementation in voucher input
![WhatsApp Image 2023-10-10 at 10.37.52 AM.jpeg](https://files.reviewableusercontent.io/images/reviewable/112686638/KducPOHd_H7pPV7zIVNhYZgK/WhatsApp%20Image%202023-10-10%20at%2010.37.52%20AM.jpeg)
[WhatsApp Video 2023-10-10 at 10.39.11 AM.mp4](https://files.reviewableusercontent.io/images/reviewable/112686638/-_P9KnzmhUIQL6WkexYHMwP6/WhatsApp%20Video%202023-10-10%20at%2010.39.11%20AM.mp4)

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJX8QvEII6iVKzD46J:-NgNjrYx0sn0SrUUz4SS:bb7oryy) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can you check with Matilda whether that Zeplin design is correct since the icon padding is different from the other dialogs?
</blockquote></details>

sure

___
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt` line 161 at r26](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgNdes42Og0sBHPVhnl:-NgNgbej9cKA4xI3dA88:b-fjr944) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14ae580f8c06f783a9a9d4c0d0560f469716fdb1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt#L161)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Will removing these not affect the DPAD navigation in other text fields in the settings view? I mean there was a reason we added these.
</blockquote></details>

We added this one when MTU input was in setting page(not inside the dialog) to not correct DPAD, it is not needed anymore


<!-- Sent from Reviewable.io -->

2023-10-10 09:04 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 55 of 57 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJZq3R6yEFdj4ZqvQZ:-NgNo_Dp-g2rEhu7_OTr:b-jcpo59) (no related file):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@albin-mullvad To clarify.
1. No I don't think this means that we can not use password keyboard type.
2. What I'm referring to is past from clipboard action that can appear on some keyboards, see screenshot below.
![Screenshot 2023-10-10 at 11.01.49.png](https://files.reviewableusercontent.io/images/reviewable/1643265/4RbrmI1dkgJXOnkLDkEB8GVU/Screenshot%202023-10-10%20at%2011.01.49.png)

___


<!-- Sent from Reviewable.io -->

2023-10-10 09:29 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 55 of 57 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @Pururun)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJX8QvEII6iVKzD46J:-NgNu2LH9MOaxQUKZjqt:bauskkm) (no related file):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

sure
</blockquote></details>

Matilda confirmed padding difference and asked for following Zeplin designs  

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJZq3R6yEFdj4ZqvQZ:-NgNuZps2qWvF2Fs5NG2:b-8evw72) (no related file):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

@albin-mullvad To clarify.
1. No I don't think this means that we can not use password keyboard type.
2. What I'm referring to is past from clipboard action that can appear on some keyboards, see screenshot below.
![Screenshot 2023-10-10 at 11.01.49.png](https://files.reviewableusercontent.io/images/reviewable/1643265/4RbrmI1dkgJXOnkLDkEB8GVU/Screenshot%202023-10-10%20at%2011.01.49.png)
</blockquote></details>

@albin-mullvad @Pururun  which input type should we use here?

___


<!-- Sent from Reviewable.io -->

2023-10-10 10:50 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 54 of 58 files reviewed, 3 unresolved discussions (waiting on @Pururun and @sabercodic)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJX8QvEII6iVKzD46J:-NgOAasF4QuzygkiGgrQ:b8ca10o) (no related file):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Matilda confirmed padding difference and asked for following Zeplin designs
</blockquote></details>

Alright, sounds good!

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJZq3R6yEFdj4ZqvQZ:-NgOB-eG229nosgy5c9n:b4tmde8) (no related file):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

@albin-mullvad @Pururun  which input type should we use here?
</blockquote></details>

I believe we should use the password keyboard type unless it's causing any issues.

@Pururun do you agree?

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJXnHc7zyDBtg7B9zn:-NgOBLaN-LMC-vht0W71:bu4e6h1) (no related file):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

No, There was bugs in previous implementation in voucher input
![WhatsApp Image 2023-10-10 at 10.37.52 AM.jpeg](https://files.reviewableusercontent.io/images/reviewable/112686638/KducPOHd_H7pPV7zIVNhYZgK/WhatsApp%20Image%202023-10-10%20at%2010.37.52%20AM.jpeg)
[WhatsApp Video 2023-10-10 at 10.39.11 AM.mp4](https://files.reviewableusercontent.io/images/reviewable/112686638/-_P9KnzmhUIQL6WkexYHMwP6/WhatsApp%20Video%202023-10-10%20at%2010.39.11%20AM.mp4)
</blockquote></details>

Yes, there seem to be some various issue with the old voucher dialog, however in terms of separators/hyphens it would:
* Automatically add hyphens if not typed.
* Allow the user to add hyphens manually.

Can we support the same in this migration?

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJaLHW-YsCB8vlBIRa:-NgOC35T1WZZQMy9AY4W:b-ttm46) (no related file):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It does still not seem to fully work as expected. I'll do some more testing.

___


<!-- Sent from Reviewable.io -->

2023-10-10 10:56 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 54 of 58 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @Pururun)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJXnHc7zyDBtg7B9zn:-NgOD7MuB7jUiano6oxA:bi17emi) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Yes, there seem to be some various issue with the old voucher dialog, however in terms of separators/hyphens it would:
* Automatically add hyphens if not typed.
* Allow the user to add hyphens manually.

Can we support the same in this migration?
</blockquote></details>

It will be a little hard because we use VisualTransformation to show "-"

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJaLHW-YsCB8vlBIRa:-NgODlC908cEFUfXUoLX:b91bbp5) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

It does still not seem to fully work as expected. I'll do some more testing.
</blockquote></details>

Sounds good, I already tested all usages

___


<!-- Sent from Reviewable.io -->

2023-10-10 12:41 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 54 of 58 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJZq3R6yEFdj4ZqvQZ:-NgOaX_h2j1A9nUghsne:b24r09o) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe we should use the password keyboard type unless it's causing any issues.

@Pururun do you agree?
</blockquote></details>

Yes agree with using password keyboard type.

___


<!-- Sent from Reviewable.io -->

2023-10-10 13:00 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 54 of 58 files reviewed, 4 unresolved discussions (waiting on @Pururun and @sabercodic)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJXnHc7zyDBtg7B9zn:-NgOdJhgAmESjWV07Dej:b-tszhqp) (no related file):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

It will be a little hard because we use VisualTransformation to show "-"
</blockquote></details>

Perhaps it's easiest to change the logic to work similar to desktop? Basically to make the `VisualTransformation` show the hyphen before the user enters the 5th/9th/13th etc character. It should ofc skip showing the last one after the 16th character, which I assume we would have to hardcode.

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJaLHW-YsCB8vlBIRa:-NgOewcFBWxxLLci1_Yd:b7a605v) (no related file):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Sounds good, I already tested all usages
</blockquote></details>

I still seem to need double up/down DPAD clicks to reach stuff, but I'll try it somewhere else than my emulator.

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgObyj1EP3EmYU9Ctlj:-NgObyj1EP3EmYU9Ctlk:bn8b8gn) (no related file):*
When testing this on my emulator, clicking enter on my physical keyboard after filling in a voucher seem to just dismiss the dialog. I believe it's the case both for valid and invalid vouchers. 

___
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt` line 161 at r26](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgNdes42Og0sBHPVhnl:-NgNtQSa6zY6YNaMrJit:b6k8ni8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14ae580f8c06f783a9a9d4c0d0560f469716fdb1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt#L161)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

We added this one when MTU input was in setting page(not inside the dialog) to not correct DPAD, it is not needed anymore
</blockquote></details>

I'm not sure that was the reason since I don't believe we merged the migration PR in a state where it was part directly of the settings view. 


<!-- Sent from Reviewable.io -->

2023-10-10 15:51 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 54 of 58 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @Pururun)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJXnHc7zyDBtg7B9zn:-NgOo8Np8ZmvX1jq1y5z:b-896fix) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Perhaps it's easiest to change the logic to work similar to desktop? Basically to make the `VisualTransformation` show the hyphen before the user enters the 5th/9th/13th etc character. It should ofc skip showing the last one after the 16th character, which I assume we would have to hardcode.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJaLHW-YsCB8vlBIRa:-NgOoRX-DDthjAASDvhj:b-wnt3y1) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I still seem to need double up/down DPAD clicks to reach stuff, but I'll try it somewhere else than my emulator.
</blockquote></details>

This is an existing DPAD problem for Compose dialogs inside DialogFragment (such as MTU dialog)

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgObyj1EP3EmYU9Ctlj:-NgP7s1G5gh9DaAy-p3Z:b-886gsx) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

When testing this on my emulator, clicking enter on my physical keyboard after filling in a voucher seem to just dismiss the dialog. I believe it's the case both for valid and invalid vouchers.
</blockquote></details>

Fixed

___
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt` line 161 at r26](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgNdes42Og0sBHPVhnl:-NgP7nw72eLrWoDStKLr:b-z2a3wb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14ae580f8c06f783a9a9d4c0d0560f469716fdb1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt#L161)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I'm not sure that was the reason since I don't believe we merged the migration PR in a state where it was part directly of the settings view.
</blockquote></details>

Reverted as discussed.


<!-- Sent from Reviewable.io -->

2023-10-11 07:10 UTC, albin-mullvad requested changes
> Reviewed 1 of 3 files at r30.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 54 of 58 files reviewed, 1 unresolved discussion (waiting on @Pururun and @sabercodic)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJaLHW-YsCB8vlBIRa:-NgSYRM_8k0c0qKAedkJ:bvcrw5z) (no related file):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

This is an existing DPAD problem for Compose dialogs inside DialogFragment (such as MTU dialog)
</blockquote></details>

I'm not sure it's specifically for `DialogFragment` since we only use that for the voucher, I believe it might be some issue with `AlertDialog` or how we use them, but let's work on a overall improvement for that in a separate PR. Can you create a Linear issue?

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJXnHc7zyDBtg7B9zn:-NgSZeRQ8oQ1TRTbZLwT:btojbfd) (no related file):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great!

___
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt` line 161 at r26](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgNdes42Og0sBHPVhnl:-NgSZLT89pbC_wR7MgDh:b-vlyut0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14ae580f8c06f783a9a9d4c0d0560f469716fdb1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt#L161)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Reverted as discussed.
</blockquote></details>

Why was the escape and up/down order changed?


<!-- Sent from Reviewable.io -->

2023-10-11 07:26 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: 54 of 58 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Pururun)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJaLHW-YsCB8vlBIRa:-NgSbOQ5AS-wROSGi3cy:b-oe3w2x) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I'm not sure it's specifically for `DialogFragment` since we only use that for the voucher, I believe it might be some issue with `AlertDialog` or how we use them, but let's work on a overall improvement for that in a separate PR. Can you create a Linear issue?
</blockquote></details>

Done.
https://linear.app/mullvad/issue/DROID-401/investigate-and-fix-the-dpad-navigation-bug-on-alert-dialog

___
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt` line 161 at r26](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgNdes42Og0sBHPVhnl:-NgSbx2K1QtWIp0VPvAj:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/14ae580f8c06f783a9a9d4c0d0560f469716fdb1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt#L161)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Why was the escape and up/down order changed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-11 07:33 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r31.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-:-NgSdlcQA0yLyvtxPjsV:bnfp4nl)* status: 54 of 58 files reviewed, all discussions resolved (waiting on @Pururun)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166#-NgJaLHW-YsCB8vlBIRa:-NgSctRr3xWHN7LG0REm:b-6mhyx0) (no related file):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
https://linear.app/mullvad/issue/DROID-401/investigate-and-fix-the-dpad-navigation-bug-on-alert-dialog
</blockquote></details>

Great, thanks!

___


<!-- Sent from Reviewable.io -->

2023-10-11 07:40 UTC, Pururun approved these changes
> Reviewed 1 of 3 files at r28, 1 of 1 files at r29, 2 of 3 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5166)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-11 09:13 UTC, merged