PacketTunnel: introduce proper state + blocked state
mullvad/mullvadvpn-app pull request #5183
Opened 2023-09-22 08:20 UTC by pronebird

<TBD>

2023-09-25 13:34 UTC, rablador requested changes
> Reviewed 1 of 17 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 2 of 66 files reviewed, 5 unresolved discussions (waiting on @pronebird)

___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 138 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfAoXjZ9So10OoptqEF:-NfAoXjZ9So10OoptqEG:b-cxo34t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c2c576ea8de84c443c05d843485453c29cf0b7c/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L138)):*
> ```Swift
>                 parsedOptions.selectorResult = selectorResult
>             } else {
>                 parsedOptions.launchSource = tunnelOptions.isOnDemand() ? .onDemand : .system
> ```

This should already be the default (from init), so no need to set it again.
___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 112 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBER8d9dDLsO_H8SNx:-NfBER8d9dDLsO_H8SNy:bec0xv7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L112)):*
> ```Swift
>     }
> 
>     override func wake() {
> ```

Why not keeping to async here?
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 178 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBCbnWB6tKKUgyGbjW:-NfBCbnWB6tKKUgyGbjX:bmf8f51) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63d0b2a38045f4c5f5757394e6bd54d0801cd10f/ios/PacketTunnelCore/Actor/Actor.swift#L178)):*
> ```Swift
>      - Parameter date: date when last key rotation took place.
>      */
>     public func notifyKeyRotated(date: Date? = nil) async {
> ```

Nit: This is perhaps more of a "notifyKeyRotation" rather than the key actually have been rotated. If rotation fails (or is attempted), the actor will still be notified with a "last rotation date".
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 196 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBBPA09VnmTGthCA2a:-NfBBPA09VnmTGthCA2b:b-iehefz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63d0b2a38045f4c5f5757394e6bd54d0801cd10f/ios/PacketTunnelCore/Actor/Actor.swift#L196)):*
> ```Swift
>             case var .connecting(connState):
>                 if mutateConnectionState(&connState) {
>                     state = .connecting(connState)
> ```

Why do we set the same state again?
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 231 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBDlVN-kVdOq77gobW:-NfBDlVN-kVdOq77gobX:b58qzdu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63d0b2a38045f4c5f5757394e6bd54d0801cd10f/ios/PacketTunnelCore/Actor/Actor.swift#L231)):*
> ```Swift
> 
>     /**
>      Cients should call this method to notify actor when device becomes awake.
> ```

Nit: "Clients"


<!-- Sent from Reviewable.io -->

2023-09-26 11:11 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 22 of 68 files reviewed, 8 unresolved discussions (waiting on @rablador)

___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 138 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfAoXjZ9So10OoptqEF:-NfGAL5r4BIp7rNoHqW_:bvmpjpt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c2c576ea8de84c443c05d843485453c29cf0b7c/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L138)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This should already be the default (from init), so no need to set it again.
</blockquote></details>

Different value is being set. This branch infers that if relay selector is not present then it means the system launched the packet tunnel. I refined the `else` branch. Please double check.


<!-- Sent from Reviewable.io -->

2023-09-26 11:40 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 21 of 68 files reviewed, 6 unresolved discussions (waiting on @rablador)

___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 112 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBER8d9dDLsO_H8SNx:-NfGDWXF-qZrnveG8iUe:b-p37x78) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L112)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Why not keeping to async here?
</blockquote></details>

`wake()` is defined as non-async in the superclass.
___
*[`ios/PacketTunnel/PacketTunnelProvider/SettingsReader.swift` line 49 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBnWy74t9hzX_xPbTl:-NfGAy5iCeYyNEy5d9M9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnel/PacketTunnelProvider/SettingsReader.swift#L49)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: "Converts"
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 196 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBBPA09VnmTGthCA2a:-NfGBAHNEdSrjlvu8JMX:b317nwa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63d0b2a38045f4c5f5757394e6bd54d0801cd10f/ios/PacketTunnelCore/Actor/Actor.swift#L196)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Why do we set the same state again?
</blockquote></details>

The actor only mutates the associated value (`ConnectionState`) in here. It will later call `reconnectTunnel()` (see the task created in `startKeySwitchTask()`)
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 231 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBDlVN-kVdOq77gobW:-NfGFR_g-Y5HQxYQ3yWq:be11e1w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63d0b2a38045f4c5f5757394e6bd54d0801cd10f/ios/PacketTunnelCore/Actor/Actor.swift#L231)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: "Clients"
</blockquote></details>

Was it fixed?
___
*[`ios/PacketTunnelCore/Actor/State.swift` line 81 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfB_KQD3egKlu-n-HUo:-NfGFUdBEJkyVAIw5XEf:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnelCore/Actor/State.swift#L81)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: "Certain"
</blockquote></details>

Done
___
*[`ios/PacketTunnelCore/Actor/TaskQueue.swift` line 74 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBcoFQ0rHLJoIFy9tR:-NfGFpTqD2fJS0Zopx0R:b8226fl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnelCore/Actor/TaskQueue.swift#L74)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Can be simplified: `queuedTasks.removeAll { $0.id == taskId }`
</blockquote></details>

 `removeAll()` iterates over all of elements in array that why I prefer `firstIndex() + remove(at:)` combo since it's expected to have only one task with the same ID in the queue.


<!-- Sent from Reviewable.io -->

2023-09-26 12:29 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 20 of 68 files reviewed, 10 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 398 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBiMpTE09qpYBrIeGa:-NfBiMpTE09qpYBrIeGb:b-cb1xao) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnelCore/Actor/Actor.swift#L398)):*
> ```Swift
>      */
>     private func tryStart(nextRelay: NextRelay = .random) async throws {
>         func makeConnectionState(settings: Settings) throws -> ConnectionState? {
> ```

This is a big enough function to warrant standing on its own, was there a specific reason to inline it like this ?
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 572 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBnNwU9kql4EyUWA32:-NfBnNwU9kql4EyUWA33:b-j9t3z8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnelCore/Actor/Actor.swift#L572)):*
> ```Swift
>      - Parameter reason: reason why the actor is entering error state.
>      */
>     private func setErrorStateInner(with reason: BlockedStateReason) async {
> ```

nit
I don't know if it's worth, but we can use the swift 5.9 "switch as expression" feature to avoid repeating the state change like so

```swift
private func setErrorStateInner(with reason: BlockedStateReason) async {
    let blockedState: BlockedState? = switch state {
    case .initial:
        BlockedState(
            reason: reason,
            relayConstraints: nil,
            currentKey: nil,
            keyPolicy: .useCurrent,
            networkReachability: defaultPathObserver.defaultPath?.networkReachability ?? .undetermined,
            recoveryTask: startRecoveryTaskIfNeeded(reason: reason),
            priorState: state.priorState!
        )

    case let .connected(connState), let .connecting(connState), let .reconnecting(connState):
        BlockedState(
            reason: reason,
            relayConstraints: connState.relayConstraints,
            currentKey: nil,
            keyPolicy: connState.keyPolicy,
            networkReachability: connState.networkReachability,
            priorState: state.priorState!
        )

    // Funky / ugly syntax here, but necessary to return a single value that the compiler can type check
    case var .error(blockedState): { 
            if blockedState.reason != reason {
                blockedState.reason = reason
            }
            return blockedState
        }()

    case .disconnecting, .disconnected:
        nil
    }

    if let blockedState {
        state = .error(blockedState)
        await configureAdapterForErrorState()
    }
}
```
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 379 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfFYhZM3OQFUKV-gEXW:-NfFYhZM3OQFUKV-gEXX:bzb1vuz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfe97cb937e4fa7ba2d4e3ef9602cb21df8cdd80/ios/PacketTunnelCore/Actor/Actor.swift#L379)):*
> ```Swift
> 
> // MARK: - Network Reachability
> ```

It would be nice to split this into multiple files if possible 
like `Actor+Reachability` etc...
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 637 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfF_VsXCUBWSzz0YvB6:-NfF_VsXCUBWSzz0YvB7:b-5xak31) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfe97cb937e4fa7ba2d4e3ef9602cb21df8cdd80/ios/PacketTunnelCore/Actor/Actor.swift#L637)):*
> ```Swift
>         case .random:
>             return try relaySelector.selectRelay(
>                 with: relayConstraints,
> ```

Shouldn't this be any relay constraints in case of the `.random` selection ? Or are we trying to still respect whatever constraint was chosen by the user here ?


<!-- Sent from Reviewable.io -->

2023-09-26 13:41 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 20 of 68 files reviewed, 10 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 398 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBiMpTE09qpYBrIeGa:-NfGdrtoBKxHh4ZJgv5x:b-2f1dt9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnelCore/Actor/Actor.swift#L398)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This is a big enough function to warrant standing on its own, was there a specific reason to inline it like this ?
</blockquote></details>

No particular reason I think. I'll move it into separate function.
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 572 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBnNwU9kql4EyUWA32:-NfGiBHn1EQUQPNv7-05:bf08ihy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnelCore/Actor/Actor.swift#L572)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
I don't know if it's worth, but we can use the swift 5.9 "switch as expression" feature to avoid repeating the state change like so

```swift
private func setErrorStateInner(with reason: BlockedStateReason) async {
    let blockedState: BlockedState? = switch state {
    case .initial:
        BlockedState(
            reason: reason,
            relayConstraints: nil,
            currentKey: nil,
            keyPolicy: .useCurrent,
            networkReachability: defaultPathObserver.defaultPath?.networkReachability ?? .undetermined,
            recoveryTask: startRecoveryTaskIfNeeded(reason: reason),
            priorState: state.priorState!
        )

    case let .connected(connState), let .connecting(connState), let .reconnecting(connState):
        BlockedState(
            reason: reason,
            relayConstraints: connState.relayConstraints,
            currentKey: nil,
            keyPolicy: connState.keyPolicy,
            networkReachability: connState.networkReachability,
            priorState: state.priorState!
        )

    // Funky / ugly syntax here, but necessary to return a single value that the compiler can type check
    case var .error(blockedState): { 
            if blockedState.reason != reason {
                blockedState.reason = reason
            }
            return blockedState
        }()

    case .disconnecting, .disconnected:
        nil
    }

    if let blockedState {
        state = .error(blockedState)
        await configureAdapterForErrorState()
    }
}
```
</blockquote></details>

Good idea let me try it.
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 379 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfFYhZM3OQFUKV-gEXW:-NfGcbJBAtbyB3WT6kJb:b-lluohd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfe97cb937e4fa7ba2d4e3ef9602cb21df8cdd80/ios/PacketTunnelCore/Actor/Actor.swift#L379)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It would be nice to split this into multiple files if possible 
like `Actor+Reachability` etc...
</blockquote></details>

Ok I wasn't sure but I'll look into doing that.
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 637 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfF_VsXCUBWSzz0YvB6:-NfGcoI98Zcdn_k_6PlZ:b-gb6q0o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfe97cb937e4fa7ba2d4e3ef9602cb21df8cdd80/ios/PacketTunnelCore/Actor/Actor.swift#L637)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Shouldn't this be any relay constraints in case of the `.random` selection ? Or are we trying to still respect whatever constraint was chosen by the user here ?
</blockquote></details>

The latter. "random" means to pick a random relay satisfying constraints chosen by user. If constraints yield zero relays then we enter blocked state (error).


<!-- Sent from Reviewable.io -->

2023-09-26 14:25 UTC, rablador requested changes
> Reviewed 8 of 63 files at r1, 5 of 17 files at r2, 1 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 31 of 73 files reviewed, 10 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 138 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfAoXjZ9So10OoptqEF:-NfGrWZI0v0e04go-GAb:b1vda8e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c2c576ea8de84c443c05d843485453c29cf0b7c/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L138)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Different value is being set. This branch infers that if relay selector is not present then it means the system launched the packet tunnel. I refined the `else` branch. Please double check.
</blockquote></details>

Ah, I'm silly, didn't actually read properly...
___
*[`ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift` line 54 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfFmEB02GH8Nns5DV2R:-NfFmEB02GH8Nns5DV2S:b7zwq1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift#L54)):*
> ```Swift
> 
>         let dispatchGroup = DispatchGroup()
>         dispatchGroup.enter()
> ```

Why do we use a group for this?
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 196 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBBPA09VnmTGthCA2a:-NfGrdZE2wF-U4Yky8HN:b-e9ym5t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63d0b2a38045f4c5f5757394e6bd54d0801cd10f/ios/PacketTunnelCore/Actor/Actor.swift#L196)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

The actor only mutates the associated value (`ConnectionState`) in here. It will later call `reconnectTunnel()` (see the task created in `startKeySwitchTask()`)
</blockquote></details>

Yeah, I saw this during test session with @buggmagnet today. Nevermind, lost myself in code and just missed that param was inout.
___
*[`ios/PacketTunnelCore/Actor/State+Extensions.swift` line 119 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfGPGY61nAIn_o-9aJ6:-NfGPGY7704Eknk_UFDz:b-fize4j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnelCore/Actor/State%2BExtensions.swift#L119)):*
> ```Swift
>     var shouldRestartAutomatically: Bool {
>         switch self {
>         case .deviceLocked, .outdatedSchema:
> ```

@buggmagnet  here, typing on my keyboard.
In practice,  whenever we return`.outdatedSchema`, we _need_  the user to restart the app for the schema update to apply.
This means we will get stuck in a boot loop, endlessly trying to start (and fail) the tunnel. I'm not sure this is the correct approach in this case. 
We should probably return false here, and wait for the user to relaunch the app, since we will already be in a blocked state.


<!-- Sent from Reviewable.io -->

2023-09-26 15:19 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 33 of 73 files reviewed, 8 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift` line 54 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfFmEB02GH8Nns5DV2R:-NfH1vuQ3zhzfrecVBvY:b-iuhdmw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift#L54)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Why do we use a group for this?
</blockquote></details>

It's used to block current thread until either the response is received from `adapter.getRuntimeConfiguration { .. }` or timeout (1 second). Tunnel Monitor calls this function to obtain WG adapter stats (bytes received/sent) etc..


<!-- Sent from Reviewable.io -->

2023-09-27 07:42 UTC, rablador requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 32 of 73 files reviewed, 8 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift` line 54 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfFmEB02GH8Nns5DV2R:-NfK_Sgq5aN2JnVdCNJU:b-ovx7lr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift#L54)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

It's used to block current thread until either the response is received from `adapter.getRuntimeConfiguration { .. }` or timeout (1 second). Tunnel Monitor calls this function to obtain WG adapter stats (bytes received/sent) etc..
</blockquote></details>

Initially felt strange to use a group for a single value, but I guess it's a convenient to observe both the result and timeout simultaneosly.


<!-- Sent from Reviewable.io -->

2023-09-27 11:43 UTC, rablador requested changes
> Reviewed 12 of 63 files at r1, 9 of 17 files at r2, 11 of 14 files at r5, 1 of 2 files at r7, 3 of 7 files at r8, 1 of 2 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: all files reviewed, 12 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 80 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfLA8PgC-iO64590Rmx:-NfLA8PgC-iO64590Rmy:b-tpheos) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0836b44950cda43e0cb19173d599a8457a08d3d3/ios/PacketTunnelCore/Actor/Actor.swift#L80)):*
> ```Swift
>      - Can be cancelled by a subsequent call to `stop()`. In that case the original invocation of `start()` returns once actor moved to disconnected state.
> 
>      - Important: Internal implementation must not call this method from operation executing on `TaskQueue`.
> ```

Emphasise "not" here, making it easier to discern. tryStart() below says the opposite, so the distinction makes it easier to not introduce bugs.
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 122 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfLAPjs35rgbNuoAE50:-NfLAPjs35rgbNuoAE51:bvelidi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0836b44950cda43e0cb19173d599a8457a08d3d3/ios/PacketTunnelCore/Actor/Actor.swift#L122)):*
> ```Swift
>      Stop the tunnel.
> 
>      - Important: Internal implementation must not call this method from operation executing on `TaskQueue`.
> ```

Emphasise "not" here, making it easier to discern?
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 158 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfLARSH3D0hq0eP7EVA:-NfLARSH3D0hq0eP7EVB:bvelidi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0836b44950cda43e0cb19173d599a8457a08d3d3/ios/PacketTunnelCore/Actor/Actor.swift#L158)):*
> ```Swift
>      Reconnect the tunnel to new relay.
> 
>      - Important: Internal implementation must not call this method from operation executing on `TaskQueue`.
> ```

Emphasise "not" here, making it easier to discern?
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 179 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfLATKj11A5WyMhnV3Z:-NfLATKj11A5WyMhnV3_:bwqb7pq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0836b44950cda43e0cb19173d599a8457a08d3d3/ios/PacketTunnelCore/Actor/Actor.swift#L179)):*
> ```Swift
>      - Reactivate default path observation (disabled when configuring tunnel adapter)
> 
>      - Important: This method must only be invoked as a part of operation scheduled on `TaskQueue`.
> ```

Emphasise "only" here, making it easier to discern. start() above says the opposite, so the distinction makes it easier to not introduce bugs.
___
*[`ios/PacketTunnelCoreTests/TaskSleepTests.swift` line 15 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfLNgkbDgPBK872u-uP:-NfLNgkcBy-A_aqNHQVq:b-r6sx6v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0836b44950cda43e0cb19173d599a8457a08d3d3/ios/PacketTunnelCoreTests/TaskSleepTests.swift#L15)):*
> ```Swift
>     func testCancellation() async throws {
>         let task = Task {
>             try await Task.sleepUsingContinuousClock(for: .seconds(1))
> ```

Could/should sleepUsingContinuousClock be altered to return a task handle and enable cancellation that way?


<!-- Sent from Reviewable.io -->

2023-09-27 18:06 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: all files reviewed, 12 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift` line 54 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfFmEB02GH8Nns5DV2R:-NfMm9_Y-ftMi1NgIvKX:b4yj911) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift#L54)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Initially felt strange to use a group for a single value, but I guess it's a convenient to observe both the result and timeout simultaneosly.
</blockquote></details>

I think `DispatchSemaphore` can be used instead but I'd really rather not touch it in this PR :laughing: 
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 398 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBiMpTE09qpYBrIeGa:-NfMo58xDFRW7KBYEBsh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnelCore/Actor/Actor.swift#L398)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

No particular reason I think. I'll move it into separate function.
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 572 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBnNwU9kql4EyUWA32:-NfMoAZcB5P0oRINoW1q:bxaxfwz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnelCore/Actor/Actor.swift#L572)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Good idea let me try it.
</blockquote></details>

Mhm I had some issues with switch expression so eventually I found that using a helper function looked cleaner, especially after breaking actor on many files.
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 379 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfFYhZM3OQFUKV-gEXW:-NfMnwNtEeD7zOizd37s:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfe97cb937e4fa7ba2d4e3ef9602cb21df8cdd80/ios/PacketTunnelCore/Actor/Actor.swift#L379)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Ok I wasn't sure but I'll look into doing that.
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCore/Actor/State+Extensions.swift` line 119 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfGPGY61nAIn_o-9aJ6:-NfMmvMDCB4dsLyXMvka:bolschp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f362d01aca6d29cb366019064ba74b9dfac6ac/ios/PacketTunnelCore/Actor/State%2BExtensions.swift#L119)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

@buggmagnet  here, typing on my keyboard.
In practice,  whenever we return`.outdatedSchema`, we _need_  the user to restart the app for the schema update to apply.
This means we will get stuck in a boot loop, endlessly trying to start (and fail) the tunnel. I'm not sure this is the correct approach in this case. 
We should probably return false here, and wait for the user to relaunch the app, since we will already be in a blocked state.
</blockquote></details>

Agree. Normally we send IPC message to reconnect the tunnel after migrating settings in the main process, so perhaps we don't have to be stuck doing this. I'll fix that tomorrow.
___
*[`ios/PacketTunnelCoreTests/TaskSleepTests.swift` line 15 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfLNgkbDgPBK872u-uP:-NfMlxcM1JFZcZsElOMx:b-92qe2f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0836b44950cda43e0cb19173d599a8457a08d3d3/ios/PacketTunnelCoreTests/TaskSleepTests.swift#L15)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Could/should sleepUsingContinuousClock be altered to return a task handle and enable cancellation that way?
</blockquote></details>

`Task.sleep()` works the same way, so I don't think we need to deviate from the general design.


<!-- Sent from Reviewable.io -->

2023-09-28 11:06 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 59 of 78 files reviewed, 11 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 178 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBCbnWB6tKKUgyGbjW:-NfQRHx_EJVOZBg8xbsn:bpufz4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63d0b2a38045f4c5f5757394e6bd54d0801cd10f/ios/PacketTunnelCore/Actor/Actor.swift#L178)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: This is perhaps more of a "notifyKeyRotation" rather than the key actually have been rotated. If rotation fails (or is attempted), the actor will still be notified with a "last rotation date".
</blockquote></details>

I'll address this a bit later once we're through the channel part.
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 80 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfLA8PgC-iO64590Rmx:-NfQQPzt3edg442pwl2M:bnj41o6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0836b44950cda43e0cb19173d599a8457a08d3d3/ios/PacketTunnelCore/Actor/Actor.swift#L80)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Emphasise "not" here, making it easier to discern. tryStart() below says the opposite, so the distinction makes it easier to not introduce bugs.
</blockquote></details>

This was removed since all this work is now being initiated on behalf of the worker task. One cool thing in Xcode, you can right click on the function and select "show callers" to find what parts of code call into function.
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 122 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfLAPjs35rgbNuoAE50:-NfQR1vq-1rBoi2WtiPs:b8wkpty) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0836b44950cda43e0cb19173d599a8457a08d3d3/ios/PacketTunnelCore/Actor/Actor.swift#L122)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Emphasise "not" here, making it easier to discern?
</blockquote></details>

This was removed since all this work is now being initiated on behalf of the worker task.
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 158 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfLARSH3D0hq0eP7EVA:-NfQRBuB25_1-fPIeQsK:b8wkpty) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0836b44950cda43e0cb19173d599a8457a08d3d3/ios/PacketTunnelCore/Actor/Actor.swift#L158)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Emphasise "not" here, making it easier to discern?
</blockquote></details>

This was removed since all this work is now being initiated on behalf of the worker task.
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 179 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfLATKj11A5WyMhnV3Z:-NfQRY_h5gf-MWqfx2DF:b-547kl8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0836b44950cda43e0cb19173d599a8457a08d3d3/ios/PacketTunnelCore/Actor/Actor.swift#L179)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Emphasise "only" here, making it easier to discern. start() above says the opposite, so the distinction makes it easier to not introduce bugs.
</blockquote></details>

This was removed. All of this is now called from the worker task consuming commands from the channel.


<!-- Sent from Reviewable.io -->

2023-09-28 15:00 UTC, buggmagnet requested changes
> Reviewed 20 of 63 files at r1, 2 of 17 files at r2, 1 of 2 files at r7, 1 of 4 files at r10, 6 of 19 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 65 of 78 files reviewed, 18 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/PacketTunnel/WireGuardAdapter/WireGuardAdapter+Async.swift` line 14 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfQz-njDVIkyhGJ5VR7:-NfQz-njDVIkyhGJ5VR8:bvnh49i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnel/WireGuardAdapter/WireGuardAdapter%2BAsync.swift#L14)):*
> ```Swift
> extension WireGuardAdapter {
>     func start(tunnelConfiguration: TunnelConfiguration) async throws {
>         return try await withUnsafeThrowingContinuation { continuation in
> ```

Any specific reason why we don't use the `checked` variants here instead ? (`withCheckedThrowingContinuation`)
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 78 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfQzsrQDagvwmVg6rEt:-NfQzsrQDagvwmVg6rEu:b-g5um5s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor.swift#L78)):*
> ```Swift
>      */
>     private nonisolated func consumeCommands(channel: CommandChannel) {
>         Task.detached { [weak self] () in
> ```

nit:
We don't need the `()` here I think ?
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 92 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfR-S0f2Gqlhgd9d4OX:-NfR-S0f2Gqlhgd9d4OY:b2b50o0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor.swift#L92)):*
> ```Swift
> 
>                 case let .reconnect(nextRelay, stopTunnelMonitor):
>                     try? await reconnect(to: nextRelay, shouldStopTunnelMonitor: stopTunnelMonitor)
> ```

It would be nice to log here why we couldn't reconnect instead of silently ignoring the error
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 181 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfR9KeY8_KljtwQJx73:-NfR9KeY8_KljtwQJx74:b-q51flx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor.swift#L181)):*
> ```Swift
>     private func reconnect(to nextRelay: NextRelay, shouldStopTunnelMonitor: Bool) async throws {
>         // Sleep a bit to provide a debounce in case we get a barrage of calls to reconnect.
>         try await Task.sleep(duration: timings.reconnectDebounce)
> ```

Do we still need this with the coalescing mechanism of the channels ?
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 272 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfRBF4oCOEG2qXCiVl2:-NfRBF4oCOEG2qXCiVl3:bt1n2r0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor.swift#L272)):*
> ```Swift
>         case .initial:
>             return ConnectionState(
>                 selectedRelay: try selectRelay(
> ```

Would it make sense for `ConnectionState` to consume `RelaySelectorWrapper` instead ?
___
*[`ios/PacketTunnelCore/Actor/Actor+ConnectionMonitoring.swift` line 52 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfRCpwY6zAxRsE37zq3:-NfRCpwY6zAxRsE37zq4:bw0vqnj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor%2BConnectionMonitoring.swift#L52)):*
> ```Swift
>     /// Increment connection attempt counter and reconnect the tunnel.
>     private func onHandleConnectionRecovery() async {
>         func mutateConnectionState(_ connState: inout ConnectionState) {
> ```

I'm not sure what's happening here, why do we do this ?
In the switch where it's used, all the cases are declared with `var`, therefore making `connState` mutable. 

The function could be simplified as such
```swift


    private func onHandleConnectionRecovery2() async {
        switch state {
        case var .connecting(connState):
            connState.incrementAttemptCount()
            state = .connecting(connState)

        case var .reconnecting(connState):
            connState.incrementAttemptCount()
            state = .reconnecting(connState)

        case var .connected(connState):
            connState.incrementAttemptCount()
            state = .connected(connState)

        case .initial, .disconnected, .disconnecting, .error:
            // Explcit return to prevent reconnecting the tunnel.
            return
        }

        // Tunnel monitor should already be paused at this point so don't stop it to avoid a reset of its internal
        // counters.
        commandChannel.send(.reconnect(.random, stopTunnelMonitor: false))
    }
```
___
*[`ios/PacketTunnelCore/Actor/Actor+ErrorState.swift` line 92 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfREUyWC7R3Eyb_QKTI:-NfREUyWC7R3Eyb_QKTJ:ba8xh47) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor%2BErrorState.swift#L92)):*
> ```Swift
> 
>     /**
>      Configure tunnel with empty WireGuard configuration that consumes all traffic on device and emitates the blocked state akin to the one we have on desktop
> ```

We shouldn't mention the desktop client.

It's not relevant to understand how this works,
and if the desktop team decides to change how they do blocking state, it's unlikely that they will modify this comment to reflect that.
___
*[`ios/PacketTunnelCore/Actor/AutoCancellingTask.swift` line 14 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfRFPr_7SVEpNm63rkN:-NfRFPr_7SVEpNm63rkO:b92qdnk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/AutoCancellingTask.swift#L14)):*
> ```Swift
> public final class AutoCancellingTask {
>     private var task: AnyTask?
>     private let taskLock = NSLock()
> ```

This lock doesn't protect anything.
Setting `task` from multiple threads is not a problem since no one can read `task`
No thread can run `init` or `deinit` in parallel


<!-- Sent from Reviewable.io -->

2023-09-28 18:10 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 65 of 78 files reviewed, 18 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnel/WireGuardAdapter/WireGuardAdapter+Async.swift` line 14 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfQz-njDVIkyhGJ5VR7:-NfR_2Wb345H3EfBCRSR:bwoedzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnel/WireGuardAdapter/WireGuardAdapter%2BAsync.swift#L14)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Any specific reason why we don't use the `checked` variants here instead ? (`withCheckedThrowingContinuation`)
</blockquote></details>

This is rather exception, because I trust that `WireGuardAdapter` always calls the completion handler.

Checked continuations have an overhead, since they do runtime sanity checks to ensure that continuations aren't released before being resumed.
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 78 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfQzsrQDagvwmVg6rEt:-NfRpVN01bYWX6KklMR5:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor.swift#L78)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit:
We don't need the `()` here I think ?
</blockquote></details>

Removed.
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 92 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfR-S0f2Gqlhgd9d4OX:-NfR_rsd8txb0R6XCkhm:bvo9vvp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor.swift#L92)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It would be nice to log here why we couldn't reconnect instead of silently ignoring the error
</blockquote></details>

`reconnect(to nextRelay: NextRelay, shouldStopTunnelMonitor: Bool)` logs error internally except for `Task.sleep()` cancellation which I don't believe should happen currently. Case can be made to make it non-throwing at all.
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 181 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfR9KeY8_KljtwQJx73:-NfRaECq8G0hXogl5Zak:bwh63bx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor.swift#L181)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Do we still need this with the coalescing mechanism of the channels ?
</blockquote></details>

Technically we don't need it anymore, but I kept a short 100ms delay as a safeguard to let tunnel device cooldown and ensure that consecutive IPC events have enough time to hit the channel.

Coalescing should work as long as there is a back pressure in the channel. The good question is also whether debounce should be moved towards the channel but as you said, we should aim for finishing this work sooner than later. 😅
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 272 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfRBF4oCOEG2qXCiVl2:-NfRh-uH5DlQNhyo-SxC:b-hoj3n0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor.swift#L272)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Would it make sense for `ConnectionState` to consume `RelaySelectorWrapper` instead ?
</blockquote></details>

I see the connection. Half of dependencies we inject into `RelaySelectorWrapper` are basically the ones stored in `ConnectionState`. But how would we select the relay then, since we still need to store newly `selectedRelay`?

Something else I have in mind would be to pass `ConnectionState?` into `selectRelay()` so it could pick up `currentRelay` and `connectionAttemptCount` from there or fill them with blanks when we don't have existing connection state yet. How's that sounds?
___
*[`ios/PacketTunnelCore/Actor/Actor+ConnectionMonitoring.swift` line 52 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfRCpwY6zAxRsE37zq3:-NfRhgIX4lY0S46K-VsL:b-n0r6jt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor%2BConnectionMonitoring.swift#L52)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I'm not sure what's happening here, why do we do this ?
In the switch where it's used, all the cases are declared with `var`, therefore making `connState` mutable. 

The function could be simplified as such
```swift


    private func onHandleConnectionRecovery2() async {
        switch state {
        case var .connecting(connState):
            connState.incrementAttemptCount()
            state = .connecting(connState)

        case var .reconnecting(connState):
            connState.incrementAttemptCount()
            state = .reconnecting(connState)

        case var .connected(connState):
            connState.incrementAttemptCount()
            state = .connected(connState)

        case .initial, .disconnected, .disconnecting, .error:
            // Explcit return to prevent reconnecting the tunnel.
            return
        }

        // Tunnel monitor should already be paused at this point so don't stop it to avoid a reset of its internal
        // counters.
        commandChannel.send(.reconnect(.random, stopTunnelMonitor: false))
    }
```
</blockquote></details>

The intent was to aggregate "business logic" into a single function. Inlined as per your suggestion.
___
*[`ios/PacketTunnelCore/Actor/Actor+ErrorState.swift` line 92 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfREUyWC7R3Eyb_QKTI:-NfRmBzp3dIrrZsGBOX8:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor%2BErrorState.swift#L92)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We shouldn't mention the desktop client.

It's not relevant to understand how this works,
and if the desktop team decides to change how they do blocking state, it's unlikely that they will modify this comment to reflect that.
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCore/Actor/AutoCancellingTask.swift` line 14 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfRFPr_7SVEpNm63rkN:-NfRjEdg7IffWapXFJHQ:bp66ht) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/AutoCancellingTask.swift#L14)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This lock doesn't protect anything.
Setting `task` from multiple threads is not a problem since no one can read `task`
No thread can run `init` or `deinit` in parallel
</blockquote></details>

Removed as the issue I had in mind is no longer relevant.


<!-- Sent from Reviewable.io -->

2023-09-29 07:26 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 59 of 78 files reviewed, 18 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnelCore/Actor/Actor+ConnectionMonitoring.swift` line 52 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfRCpwY6zAxRsE37zq3:-NfUoRgMAB2R7U50lISD:b3bvrvx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor%2BConnectionMonitoring.swift#L52)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

The intent was to aggregate "business logic" into a single function. Inlined as per your suggestion.
</blockquote></details>

In hindsight I think we could even move the increment into `reconnect(to:stopTunnelMonitor:)` and instead of passing `stopTunnelMonitor: Bool` we could pass a reason for reconnect, i.e:

```
enum ReconnectReason {
  case userInitiated, connectionLoss
}
```


<!-- Sent from Reviewable.io -->

2023-09-29 09:33 UTC, rablador requested changes
> Reviewed 5 of 19 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 63 of 78 files reviewed, 12 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/PacketTunnelCore/Actor/CommandChannel.swift` line 28 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfR6S0KCiVGt3OZEIVd:-NfR6S0KCiVGt3OZEIVe:b-2v68vr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/CommandChannel.swift#L28)):*
> ```Swift
> 
>  Consuming commands can be implemented using a for-await loop. Note that using a loop should also serialize the command handling as the next command will not
>  be consumed until the body of the loop does not complete the iteration.
> ```

"does not complete" -> "completes"
___
*[`ios/PacketTunnelCore/Actor/CommandChannel.swift` line 153 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfRAkgW1en5vN2Duru3:-NfRAkgW1en5vN2Duru4:byd98h0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/CommandChannel.swift#L153)):*
> ```Swift
>             defer { i -= 1 }
> 
>             assert(i < buffer.count)
> ```

Can this ever be false?


<!-- Sent from Reviewable.io -->

2023-09-29 09:58 UTC, buggmagnet requested changes
> Reviewed 2 of 19 files at r11, 4 of 8 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 69 of 78 files reviewed, 10 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/PacketTunnel/WireGuardAdapter/WireGuardAdapter+Async.swift` line 14 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfQz-njDVIkyhGJ5VR7:-NfUh3xa5dv719HYmCPG:boa2imn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnel/WireGuardAdapter/WireGuardAdapter%2BAsync.swift#L14)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This is rather exception, because I trust that `WireGuardAdapter` always calls the completion handler.

Checked continuations have an overhead, since they do runtime sanity checks to ensure that continuations aren't released before being resumed.
</blockquote></details>

Unless we measure it, saying "this has overhead" is usually not a good argument, or a good enough reason to use an unsafe API over a safe one.
Please use the checked version instead. 
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 92 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfR-S0f2Gqlhgd9d4OX:-NfUi3kv1pgJ0zT2BdiM:betl4zh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor.swift#L92)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`reconnect(to nextRelay: NextRelay, shouldStopTunnelMonitor: Bool)` logs error internally except for `Task.sleep()` cancellation which I don't believe should happen currently. Case can be made to make it non-throwing at all.
</blockquote></details>

Considering this is a `nonisolated` function that schedules a detached task that we don't keep around, we will not be able to cancel it currently. This means that the inner `Task.sleep` also won't get cancelled either.
In that case, please make `private func reconnect(to nextRelay: NextRelay, shouldStopTunnelMonitor: Bool)` non throwing
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 272 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfRBF4oCOEG2qXCiVl2:-NfUnpJa3-LHvY1pop-C:b-b5dt7c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor.swift#L272)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I see the connection. Half of dependencies we inject into `RelaySelectorWrapper` are basically the ones stored in `ConnectionState`. But how would we select the relay then, since we still need to store newly `selectedRelay`?

Something else I have in mind would be to pass `ConnectionState?` into `selectRelay()` so it could pick up `currentRelay` and `connectionAttemptCount` from there or fill them with blanks when we don't have existing connection state yet. How's that sounds?
</blockquote></details>

Eh let's scratch that for now, I hadn't realized that `RelaySelectorWrapper` was defined in `PacketTunnel`.
IMHO it shouldn't, and should stay in the `RelaySelector` package.
___
*[`ios/PacketTunnelCore/Actor/Actor+KeyPolicy.swift` line 60 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfV1-jSB1CGk6plkbB4:-NfV1-jT540Z71rmWX30:b-ju5y98) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Actor%2BKeyPolicy.swift#L60)):*
> ```Swift
>                 if let currentKey = blockedState.currentKey {
>                     blockedState.lastKeyRotation = lastKeyRotation
>                     blockedState.keyPolicy = .usePrior(currentKey, startKeySwitchTask())
> ```

I'm not sure I understand the logic here, why do we force a key switch when we are in the blocked state ?
Can you write a comment that explains why ?
___
*[`ios/PacketTunnelCore/Actor/Actor+KeyPolicy.swift` line 154 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfUz9V5BbLibRs2LHUu:-NfUz9V5BbLibRs2LHUv:bzqy6x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Actor%2BKeyPolicy.swift#L154)):*
> ```Swift
>             return false
> 
>         case let .usePrior(_, autoCancellingTask):
> ```

:warning: Immutable value 'autoCancellingTask' was never used; consider replacing with '_' or removing it


<!-- Sent from Reviewable.io -->

2023-09-29 14:18 UTC, buggmagnet requested changes
> Reviewed 13 of 63 files at r1, 11 of 17 files at r2, 10 of 14 files at r5, 9 of 19 files at r11, 4 of 8 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: all files reviewed, 25 unresolved discussions (waiting on @pronebird)

___
*[`ios/PacketTunnelCore/Actor/Actor+SleepCycle.swift` line 17 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfWH-4T8GQ5MGhy2yWv:-NfWH-4T8GQ5MGhy2yWw:b-xd0cpu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Actor%2BSleepCycle.swift#L17)):*
> ```Swift
>      `NEPacketTunnelProvider` provides the corresponding lifecycle method.
> 
>      - Important: It's safe to call this method from any thread.
> ```

nit

I think we don't need to point out when a method is thread safe.
This should already be implied by the `nonisolated` function (since it means it cannot modify the isolated parts in the actor).
If you look at Apple documentation, they usually say something along the lines of "All the methods in XXX are thread safe" 

Essentially, we should assume thread safety by default, and specify when something is not thread safe, since documentation is hard to read,
it's better to only point out the important stuff in doc to avoid cognitive load when reading documentation.
___
*[`ios/PacketTunnelCore/Actor/Command.swift` line 20 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfVpBtA-091CE5Xn6YQ:-NfVpBtA-091CE5Xn6YR:b-w6ob64) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Command.swift#L20)):*
> ```Swift
> 
>     /// Reconnect tunnel.
>     /// `stopTunnelMonitor = false` is only used when tunnel monitor is paused in response to connectivity loss and shouldn't be stopped explciitly,
> ```

typo
`explciitly`
___
*[`ios/PacketTunnelCore/Actor/Command.swift` line 40 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfVpQEGEcFTY7-R5UTo:-NfVpQEH19d_lgHzJEwb:b-8da2l5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Command.swift#L40)):*
> ```Swift
> 
>     /// Format command for log output.
>     func logFormat() -> String {
> ```

Why not make `Command` conform to `CustomDebugStringConvertible` instead ?
___
*[`ios/PacketTunnelCore/Actor/ConfigurationBuilder.swift` line 37 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfW1rco-vnJfpx6JRwJ:-NfW1rco-vnJfpx6JRwK:bj05ngb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/ConfigurationBuilder.swift#L37)):*
> ```Swift
>         return TunnelPeer(
>             endpoint: .ipv4(endpoint.ipv4Relay),
>             publicKey: PublicKey(rawValue: endpoint.publicKey)!
> ```

We already make this var return `TunnelPeer?` 
So let's not force unwrap here, but return nil if we couldn't construct `PublicKey` 
___
*[`ios/PacketTunnelCore/Actor/State+Extensions.swift` line 24 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfW5rtH1JjC35UISr-T:-NfW5rtH1JjC35UISr-U:b-9or9tj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/State%2BExtensions.swift#L24)):*
> ```Swift
>             return .reconnecting
>         case .disconnecting, .disconnected, .error:
>             return nil
> ```

Since this pretty much should never happen, and if it did, it would be a serious programming mistake, how about we put a `fatalError` (with a pretty clear error message) here instead, and make the return type non optional ?
___
*[`ios/PacketTunnelCore/Actor/State+Extensions.swift` line 56 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfW7iQe7PWdFi7UOKQ6:-NfW7iQe7PWdFi7UOKQ7:b-xl5qhg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/State%2BExtensions.swift#L56)):*
> ```Swift
>     // MARK: - Logging
> 
>     func logFormat() -> String {
> ```

Same remark about `CustomDebugStringConvertible`
___
*[`ios/PacketTunnelCore/Actor/Protocols/RelaySelectorProtocol.swift` line 14 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfW8LFx20wTNi53WsjQ:-NfW8LFx20wTNi53WsjR:bkt47rt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Protocols/RelaySelectorProtocol.swift#L14)):*
> ```Swift
> 
> /// Protocol describing a type that can select a relay.
> public protocol RelaySelectorProtocol {
> ```

This file should really be in `RelaySelector` and not in `PacketTunnelCore`
___
*[`ios/PacketTunnelCore/TunnelMonitor/TunnelMonitorProtocol.swift` line 22 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfW9WK024GcVB6jXf50:-NfW9WK024GcVB6jXf51:bhgldnf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/TunnelMonitor/TunnelMonitorProtocol.swift#L22)):*
nit
When defining a protocol, we don't need to say "protocol that..."
We're already in the context, we know we're dealing with a protocol

We can simply say "A type that can provide tunnel monitoring" here for instance.

There are 5 instances of the phrase "protocol that" at the time of writing this, so not a big deal, but let's not make a habit out of this either.

For example, the `Error` protocol starts as such
> A type representing an error value that can be thrown.
___
*[`ios/PacketTunnelCoreTests/ActorTests.swift` line 112 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfWALMNCNobhkHNnek1:-NfWALMNCNobhkHNnek2:b-kp6yv8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCoreTests/ActorTests.swift#L112)):*
> ```Swift
>      4. An actor should transition through `.connecting` towards`.connected` state.
>      */
>     func testLockedDeviceErrorOnBoot() async throws {
> ```

This test is currently broken since the introduction of channels. I haven't investigated why, but let's make sure to fix this.
___
*[`ios/PacketTunnelCoreTests/TaskSleepTests.swift` line 20 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfWDhZR8HHvQgRovq8a:-NfWDhZR8HHvQgRovq8b:b-jburlt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCoreTests/TaskSleepTests.swift#L20)):*
> ```Swift
>         task.cancel()
> 
>         do {
> ```

nit
I would have suggested the following simplification
```swift
XCTAssertThrowsError(Task { try await task.value }) { error in
    XCTAssertTrue(error is CancellationError)
}
```

BUT that makes the test fail, because suddenly the operation becomes non throwing.
Go figure ¯\\\_ (ツ)\_/¯
___
*[`ios/PacketTunnelCoreTests/Mocks/MockRelaySelector.swift` line 28 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfWEI2J4Zt4KKhtjwlO:-NfWEI2J4Zt4KKhtjwlP:b2ss6j4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCoreTests/Mocks/MockRelaySelector.swift#L28)):*
> ```Swift
> }
> 
> extension MockRelaySelector {
> ```

We should consolidate all the mocked relays we defined in `RelaySelectorTests` in here (if possible)
namely the (very long) `private let sampleRelays = REST.ServerRelaysResponse(` variable
___
*[`ios/PacketTunnelCoreTests/Mocks/MockSettingsReader.swift` line 15 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfWEnfy72zwbLItzSxA:-NfWEnfy72zwbLItzSxB:bb2fjz9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCoreTests/Mocks/MockSettingsReader.swift#L15)):*
> ```Swift
> import class WireGuardKitTypes.PrivateKey
> 
> struct Moc [...]

2023-09-29 17:06 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 65 of 78 files reviewed, 25 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnel/WireGuardAdapter/WireGuardAdapter+Async.swift` line 14 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfQz-njDVIkyhGJ5VR7:-NfVhzJ94Mab3ULBm58r:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnel/WireGuardAdapter/WireGuardAdapter%2BAsync.swift#L14)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Unless we measure it, saying "this has overhead" is usually not a good argument, or a good enough reason to use an unsafe API over a safe one.
Please use the checked version instead.
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 178 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfBCbnWB6tKKUgyGbjW:-NfWqnfOEhYVjTFNzZmQ:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/63d0b2a38045f4c5f5757394e6bd54d0801cd10f/ios/PacketTunnelCore/Actor/Actor.swift#L178)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I'll address this a bit later once we're through the channel part.
</blockquote></details>

Fixed
___
*[`ios/PacketTunnelCore/Actor/Actor.swift` line 92 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfR-S0f2Gqlhgd9d4OX:-NfWqLzCCVW8wKHn0zO1:b5rioyy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/Actor.swift#L92)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Considering this is a `nonisolated` function that schedules a detached task that we don't keep around, we will not be able to cancel it currently. This means that the inner `Task.sleep` also won't get cancelled either.
In that case, please make `private func reconnect(to nextRelay: NextRelay, shouldStopTunnelMonitor: Bool)` non throwing
</blockquote></details>

Fixed.

Yeah, there is a bit of a chicken and egg problem with that task as it calls into "self". Maybe adding explicit call to start handling commands would be better?
___
*[`ios/PacketTunnelCore/Actor/Actor+KeyPolicy.swift` line 60 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfV1-jSB1CGk6plkbB4:-NfVrZtg0kd_ZJQt9Sus:b35sue) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Actor%2BKeyPolicy.swift#L60)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I'm not sure I understand the logic here, why do we force a key switch when we are in the blocked state ?
Can you write a comment that explains why ?
</blockquote></details>

Because key rotation may still happen while in blocked state and because key policy is preserved between states. 

However:
- The tunnel should not be reconnected automatically when in blocked state at the time of transition from `.usePrior` to `.useCurrent`. 
- We should consume `currentKey` when moving it into `.usePrior` key policy to prevent it from being reused later.

I have addressed that in a separate commit.
___
*[`ios/PacketTunnelCore/Actor/Actor+KeyPolicy.swift` line 154 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfUz9V5BbLibRs2LHUu:-NfVvfKr1G796tEa4ubJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Actor%2BKeyPolicy.swift#L154)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

:warning: Immutable value 'autoCancellingTask' was never used; consider replacing with '_' or removing it
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCore/Actor/Actor+SleepCycle.swift` line 17 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfWH-4T8GQ5MGhy2yWv:-NfWczemD3RUfOD38miE:beqiwbh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Actor%2BSleepCycle.swift#L17)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit

I think we don't need to point out when a method is thread safe.
This should already be implied by the `nonisolated` function (since it means it cannot modify the isolated parts in the actor).
If you look at Apple documentation, they usually say something along the lines of "All the methods in XXX are thread safe" 

Essentially, we should assume thread safety by default, and specify when something is not thread safe, since documentation is hard to read,
it's better to only point out the important stuff in doc to avoid cognitive load when reading documentation.
</blockquote></details>

Deep. Fixed.
___
*[`ios/PacketTunnelCore/Actor/Command.swift` line 40 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfVpQEGEcFTY7-R5UTo:-NfWdlzM2RBSDdbcgK1m:brz1lia) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Command.swift#L40)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Why not make `Command` conform to `CustomDebugStringConvertible` instead ?
</blockquote></details>

Because we don't use `debugPrint()`. `logFormat()` is used specifically for log output that we receive with problem reports.
___
*[`ios/PacketTunnelCore/Actor/CommandChannel.swift` line 28 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfR6S0KCiVGt3OZEIVd:-NfVhwk39XfYW0zwhrVu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/CommandChannel.swift#L28)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

"does not complete" -> "completes"
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCore/Actor/CommandChannel.swift` line 153 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfRAkgW1en5vN2Duru3:-NfVaWR84XZhAvTdSjWz:b-ltfh38) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e757cb1bcd35ca32f29e279f9c3671a36b819ca7/ios/PacketTunnelCore/Actor/CommandChannel.swift#L153)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Can this ever be false?
</blockquote></details>

Only if coalescing algo within the loop does not properly adjust `i`.
___
*[`ios/PacketTunnelCore/Actor/ConfigurationBuilder.swift` line 37 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfW1rco-vnJfpx6JRwJ:-NfWefQx7M2HSZQsr2qI:b-8o8nkl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/ConfigurationBuilder.swift#L37)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We already make this var return `TunnelPeer?` 
So let's not force unwrap here, but return nil if we couldn't construct `PublicKey`
</blockquote></details>

@rablador raised and fixed this today, perhaps he could push his changes on top. 

In short if we cannot construct `PublicKey()` from raw data, then we should enter blocked state. Returning `nil` here would configure empty WG tunnel which is not the intention when `endpoint` is provided. 

This is extreme edge case as that means that our relay list contains malformed public keys. In conversation with @rablador we figured that throwing an error from here would be better as it would bubble up to `tryStart()` and cause actor to enter error state.
___
*[`ios/PacketTunnelCore/Actor/State+Extensions.swift` line 24 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfW5rtH1JjC35UISr-T:-NfWi09a0wYNRGWRC1W9:b-7gjwj0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Act [...]

2023-10-02 07:26 UTC, buggmagnet reviewed
> Reviewed 4 of 13 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 69 of 78 files reviewed, 19 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/PacketTunnelCore/Actor/Actor+KeyPolicy.swift` line 60 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfV1-jSB1CGk6plkbB4:-NfjFritAgDm_VD5aiaV:b-b297xw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Actor%2BKeyPolicy.swift#L60)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Because key rotation may still happen while in blocked state and because key policy is preserved between states. 

However:
- The tunnel should not be reconnected automatically when in blocked state at the time of transition from `.usePrior` to `.useCurrent`. 
- We should consume `currentKey` when moving it into `.usePrior` key policy to prevent it from being reused later.

I have addressed that in a separate commit.
</blockquote></details>

But if we're in a blocked state, we will be blocking all traffic, as done so in `configureAdapterForErrorState`
```swift
// Configure tunnel with empty WireGuard configuration that consumes all traffic on device
// emulating a firewall blocking all traffic.

private func configureAdapterForErrorState() async {
    do {
        let configurationBuilder = ConfigurationBuilder(
            privateKey: PrivateKey(),
            interfaceAddresses: []
        )
        try await tunnelAdapter.start(configuration: configurationBuilder.makeConfiguration())
    } catch {
        logger.error(error: error, message: "Unable to configure the tunnel for error state.")
    }
}

```

So key rotations shouldn't work in the first place. Or am I misunderstanding something ?
Or does this mean key rotation operations will leak outside of the tunnel ?


<!-- Sent from Reviewable.io -->

2023-10-02 07:52 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 69 of 78 files reviewed, 15 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/PacketTunnelCore/Actor/Command.swift` line 20 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfVpBtA-091CE5Xn6YQ:-NfjHKrx76dINgmV3wXA:b-fxg7wt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Command.swift#L20)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

typo
`explciitly`
</blockquote></details>

typo
`explcitly` 🙃
___
*[`ios/PacketTunnelCore/Actor/Command.swift` line 40 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfVpQEGEcFTY7-R5UTo:-NfjI8Zd84d09SbYxILL:bjvgif9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Command.swift#L40)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Because we don't use `debugPrint()`. `logFormat()` is used specifically for log output that we receive with problem reports.
</blockquote></details>

That's doing exactly the same thing with `CustomStringConvertible` though
```swift
struct Point: CustomStringConvertible {
    var description: String { "x:\(x) y:\(y)" }
    
    let x: Int
    let y: Int

    func logFormat() -> String {
        "x:\(x) y:\(y)"
    }
}

let p = Point(x: 1, y: 2)
print(p) // x:1 y:2
print(p.logFormat()) // x:1 y:2
```

Not a big deal I guess, but not really necessary to complicate our lives that way either.
___
*[`ios/PacketTunnelCore/Actor/Protocols/RelaySelectorProtocol.swift` line 14 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfW8LFx20wTNi53WsjQ:-NfjLM23CZLpX1gDXFHx:b-6ztvti) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Protocols/RelaySelectorProtocol.swift#L14)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

It's a direct dependency of `PacketTunnelActor` and implemented in `PacketTunnel` by `RelaySelectorWrapper`. `RelaySelector` could live without this protocol, actor cannot. So I think we should keep it where it's being used/consumed.
</blockquote></details>

The problem with that approach is that this creates an implicit chain dependency between `PacketTunnelCore`  and`RelaySelector`.

Let's say package XYZ is consuming `PacketTunnelCore` which declares this protocol, now it also has to consume `RelaySelector` even if it doesn't need it. 

In our case, it's not a big deal since `RelaySelector` is pretty much everywhere, but otherwise, I would say that this breaks the Interface Segregation Principle (No code should depend on interfaces it does not use) 

Not going to be blocking on that, but I don't encourage this either.


<!-- Sent from Reviewable.io -->

2023-10-04 06:58 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 69 of 78 files reviewed, 15 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/PacketTunnelCore/Actor/Actor+KeyPolicy.swift` line 60 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfV1-jSB1CGk6plkbB4:-NftTdto0pB5A61KQrIR:bwy68nm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Actor%2BKeyPolicy.swift#L60)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

But if we're in a blocked state, we will be blocking all traffic, as done so in `configureAdapterForErrorState`
```swift
// Configure tunnel with empty WireGuard configuration that consumes all traffic on device
// emulating a firewall blocking all traffic.

private func configureAdapterForErrorState() async {
    do {
        let configurationBuilder = ConfigurationBuilder(
            privateKey: PrivateKey(),
            interfaceAddresses: []
        )
        try await tunnelAdapter.start(configuration: configurationBuilder.makeConfiguration())
    } catch {
        logger.error(error: error, message: "Unable to configure the tunnel for error state.")
    }
}

```

So key rotations shouldn't work in the first place. Or am I misunderstanding something ?
Or does this mean key rotation operations will leak outside of the tunnel ?
</blockquote></details>

Nevermind, I had forgotten that the packet tunnel process itself will still have internet, and so technically, we can still try key rotation operations in a blocked state.


<!-- Sent from Reviewable.io -->

2023-10-04 09:08 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 69 of 78 files reviewed, 15 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnelCore/Actor/Actor+KeyPolicy.swift` line 60 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfV1-jSB1CGk6plkbB4:-Nftqg-SBRiGeVHoYMSA:b-d8d74s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Actor%2BKeyPolicy.swift#L60)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Nevermind, I had forgotten that the packet tunnel process itself will still have internet, and so technically, we can still try key rotation operations in a blocked state.
</blockquote></details>

That's correct. We may still rotate the key bypassing VPN.
___
*[`ios/PacketTunnelCore/Actor/Protocols/RelaySelectorProtocol.swift` line 14 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfW8LFx20wTNi53WsjQ:-Nftr_43Cnqbonfgj_QU:b-qyom9s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Protocols/RelaySelectorProtocol.swift#L14)):*
> Let's say package XYZ is consuming `PacketTunnelCore` which declares this protocol, now it also has to consume `RelaySelector` even if it doesn't need it.

It has to be consumed either way because `RelaySelectorResult` is defined in `RelaySelector`.

> In our case, it's not a big deal since `RelaySelector` is pretty much everywhere, but otherwise, I would say that this breaks the c (No code should depend on interfaces it does not use)

Technically this can fixed. I can have a look at how the output requirement can be formalized. 


<!-- Sent from Reviewable.io -->

2023-10-04 09:20 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 69 of 78 files reviewed, 15 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnelCore/Actor/Command.swift` line 40 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfVpQEGEcFTY7-R5UTo:-Nftwdqb7iZGlgAtc5Uc:b-7gg4jw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Command.swift#L40)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

That's doing exactly the same thing with `CustomStringConvertible` though
```swift
struct Point: CustomStringConvertible {
    var description: String { "x:\(x) y:\(y)" }
    
    let x: Int
    let y: Int

    func logFormat() -> String {
        "x:\(x) y:\(y)"
    }
}

let p = Point(x: 1, y: 2)
print(p) // x:1 y:2
print(p.logFormat()) // x:1 y:2
```

Not a big deal I guess, but not really necessary to complicate our lives that way either.
</blockquote></details>

I did it exactly this way a few years back, and then decided in favor of explicit function to format a struct specifically for logging because it's explicit in intent and it doesn't get in a way when debugging. 

For instance `Date.logFormatDate()` specifically formats date suitable for logging and not for output into Xcode console when debugging or in any other context.


<!-- Sent from Reviewable.io -->

2023-10-04 09:33 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 62 of 79 files reviewed, 13 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnelCore/Actor/Command.swift` line 20 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfVpBtA-091CE5Xn6YQ:-Nfu0gZbCOCDFHkgxWwu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Command.swift#L20)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

typo
`explcitly` 🙃
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCore/TunnelMonitor/TunnelMonitorProtocol.swift` line 22 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfW9WK024GcVB6jXf50:-Nfu0KRS8LAoCoK_4Dxl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/TunnelMonitor/TunnelMonitorProtocol.swift#L22)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
When defining a protocol, we don't need to say "protocol that..."
We're already in the context, we know we're dealing with a protocol

We can simply say "A type that can provide tunnel monitoring" here for instance.

There are 5 instances of the phrase "protocol that" at the time of writing this, so not a big deal, but let's not make a habit out of this either.

For example, the `Error` protocol starts as such
> A type representing an error value that can be thrown.
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCoreTests/ActorTests.swift` line 112 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfWALMNCNobhkHNnek1:-Nfu0rjK4Vzx6Gf_i8dh:b-obgfuz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCoreTests/ActorTests.swift#L112)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Some of the changes I have introduced lately mutate state in a few steps vs. one which causes more updates than anticipated before.  Connecting state fires twice and the corresponding expectation fails because it only expects to be fulfilled once. So I think I will have to look how I register state transitions using expectations.
</blockquote></details>

This test will be re-introduced in the follow up work by you and Jon, as agreed today during the call.


<!-- Sent from Reviewable.io -->

2023-10-04 13:10 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 54 of 83 files reviewed, 13 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnelCore/Actor/Protocols/RelaySelectorProtocol.swift` line 14 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfW8LFx20wTNi53WsjQ:-NfumhJYBleL9IWzd5Yl:b-bvbqpr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Protocols/RelaySelectorProtocol.swift#L14)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

> Let's say package XYZ is consuming `PacketTunnelCore` which declares this protocol, now it also has to consume `RelaySelector` even if it doesn't need it.

It has to be consumed either way because `RelaySelectorResult` is defined in `RelaySelector`.

> In our case, it's not a big deal since `RelaySelector` is pretty much everywhere, but otherwise, I would say that this breaks the c (No code should depend on interfaces it does not use)

Technically this can fixed. I can have a look at how the output requirement can be formalized.
</blockquote></details>

I have prepared a quick draft commit in https://github.com/mullvad/mullvadvpn-app/commit/37424904c67d4b8cf8e39ed5dea58a0f4f15c43d that replaces the use of `RelaySelectorResult` with `SelectedRelay` type exported from PacketTunnelCore in order to remove dependency on `RelaySelector`. Also it makes it possible to reconnect the tunnel using different options, i.e by passing `NextRelay` enum type instead of `RelaySelectorResult` as it used to be. I believe this can be useful.
___
*[`ios/PacketTunnelCoreTests/Mocks/PacketTunnelActor+Mocks.swift` line 15 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfWGcwTB1qROkR-flk0:-NfujJlhBvHlWF-cfGe6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCoreTests/Mocks/PacketTunnelActor%2BMocks.swift#L15)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Can we lower those to smaller values like 50ms or 10ms ?
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCoreTests/Mocks/MockSettingsReader.swift` line 15 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfWEnfy72zwbLItzSxA:-Nfun_cW22sCrhKXnYUr:b-yanrwo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCoreTests/Mocks/MockSettingsReader.swift#L15)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
This is kind of a big ask, so we don't need to do this here BUT [Mocks are not stubs](https://martinfowler.com/articles/mocksArentStubs.html).

Now I'm being super pedantic here, but ideally those should named Stubs probably.

Since we already have expectations built in `XCTest` we don't really need mocks in general.
</blockquote></details>

As I understood it applies to all test objects. Renamed the types based on proposed nomenclature. Also put Mock/Stub/Fake at end of type name and not in front as it used to be.
___
*[`ios/PacketTunnelCoreTests/Mocks/MockTunnelMonitor.swift` line 89 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfWGEMBEu6VXcjtmeso:-NfujHZtEqTp_AIHdjHb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCoreTests/Mocks/MockTunnelMonitor.swift#L89)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We can easily go down to 50ms or even 10ms here, gotta go fast ! :rocket:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-04 14:11 UTC, buggmagnet approved these changes
> Reviewed 5 of 13 files at r14, 7 of 8 files at r15, 2 of 2 files at r16, 4 of 13 files at r17, 9 of 9 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 81 of 83 files reviewed, 7 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/PacketTunnelCore/Actor/Protocols/RelaySelectorProtocol.swift` line 14 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfW8LFx20wTNi53WsjQ:-Nfv-H1W1JtztesaxKqd:bodovxt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Protocols/RelaySelectorProtocol.swift#L14)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I have prepared a quick draft commit in https://github.com/mullvad/mullvadvpn-app/commit/37424904c67d4b8cf8e39ed5dea58a0f4f15c43d that replaces the use of `RelaySelectorResult` with `SelectedRelay` type exported from PacketTunnelCore in order to remove dependency on `RelaySelector`. Also it makes it possible to reconnect the tunnel using different options, i.e by passing `NextRelay` enum type instead of `RelaySelectorResult` as it used to be. I believe this can be useful.
</blockquote></details>

Thanks, it's very appreciated ! If we can merge it after merging this PR, that will be nice. 
I will look at it soon
___
*[`ios/PacketTunnelCoreTests/Mocks/MockRelaySelector.swift` line 28 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfWEI2J4Zt4KKhtjwlO:-Nfv-fpn99qhluKYmq5a:b-ikiid6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCoreTests/Mocks/MockRelaySelector.swift#L28)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Maybe we could put them in JSON instead.
</blockquote></details>

I moved it around to get it globally for tests (not super proud) since I needed it somewhere else for the `TunnelManager` tests, but probably in the future we could (should ?) do that. I'll think about it.
___
*[`ios/PacketTunnelCoreTests/Mocks/MockSettingsReader.swift` line 15 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfWEnfy72zwbLItzSxA:-Nfv-u8i0jJD_lxrZFlO:b7bkqi3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCoreTests/Mocks/MockSettingsReader.swift#L15)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

As I understood it applies to all test objects. Renamed the types based on proposed nomenclature. Also put Mock/Stub/Fake at end of type name and not in front as it used to be.
</blockquote></details>

Really nice, thanks !


<!-- Sent from Reviewable.io -->

2023-10-05 09:16 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 81 of 83 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnelCore/Actor/Protocols/RelaySelectorProtocol.swift` line 14 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfW8LFx20wTNi53WsjQ:-Nfz5oIk00qsk1O9QFyj:bijb78g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/Protocols/RelaySelectorProtocol.swift#L14)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Thanks, it's very appreciated ! If we can merge it after merging this PR, that will be nice. 
I will look at it soon
</blockquote></details>

Agree. Let's do it after this PR.
___
*[`ios/PacketTunnelCoreTests/Mocks/MockRelaySelector.swift` line 28 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfWEI2J4Zt4KKhtjwlO:-Nfz6Rzz47GP6Wy30ir9:buyjnlr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCoreTests/Mocks/MockRelaySelector.swift#L28)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I moved it around to get it globally for tests (not super proud) since I needed it somewhere else for the `TunnelManager` tests, but probably in the future we could (should ?) do that. I'll think about it.
</blockquote></details>

Cool. Then let's not touch anything in this PR and address it later.


<!-- Sent from Reviewable.io -->

2023-10-05 11:14 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: 73 of 87 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnelCore/Actor/State+Extensions.swift` line 56 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfW7iQe7PWdFi7UOKQ6:-NfzXnVs32WChGHeU3Ri:by7li57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/State%2BExtensions.swift#L56)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Same remark about `CustomDebugStringConvertible`
</blockquote></details>

I left the answer on one of similar remarks. So I assume this is just a left over.


<!-- Sent from Reviewable.io -->

2023-10-05 11:23 UTC, rablador requested changes
> Reviewed 4 of 19 files at r11, 1 of 8 files at r12, 2 of 3 files at r13, 9 of 14 files at r14, 8 of 8 files at r15, 2 of 2 files at r16, 4 of 17 files at r17, 7 of 9 files at r18, 2 of 2 files at r19, 2 of 2 files at r20, 1 of 1 files at r21, 8 of 8 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 136 at r22](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfzZPOU6jLrt1t5KrPH:-NfzZPOU6jLrt1t5KrPI:b-6h7lvd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5f95b5d6dbc9bfba843465b1893c7eaddd3d73b/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L136)):*
> ```Swift
>             if !allIPAddresses.isEmpty, !isLoggedSameIP {
>                 isLoggedSameIP = true
>                 logIfDeviceHasSameIP(than: allIPAddresses)
> ```

than -> as
___
*[`ios/PacketTunnelCore/Actor/Actor+ConnectionMonitoring.swift` line 72 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfzPai6CWgK17sZQIDC:-NfzPai6CWgK17sZQIDD:boocxmt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82974e1554b00619ef847961d23b44d6ace5477f/ios/PacketTunnelCore/Actor/Actor%2BConnectionMonitoring.swift#L72)):*
> ```Swift
>         // Tunnel monitor should already be paused at this point so don't stop it to avoid a reset of its internal
>         // counters.
>         commandChannel.send(.reconnect(.random, stopTunnelMonitor: false))
> ```

There was some talk about adding something like a `ReconnectionReason` to reconnect command to remove the need for separately mutating state when incerementing the attempt count. We didn't really "finish" the discussion, but I guess the proposed change was put on hold then?
___
*[`ios/PacketTunnelCore/Actor/Actor+KeyPolicy.swift` line 95 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfzVOAiD50x-lWJaarC:-NfzVOAiD50x-lWJaarD:b-x0gue4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82974e1554b00619ef847961d23b44d6ace5477f/ios/PacketTunnelCore/Actor/Actor%2BKeyPolicy.swift#L95)):*
> ```Swift
>     func switchToCurrentKey() {
>         if switchToCurrentKeyInner() {
>             commandChannel.send(.reconnect(.random))
> ```

Why not reconnect to .current? There are more instances in the code base where .random is selected.
___
*[`ios/PacketTunnelCore/Actor/ConfigurationBuilder.swift` line 37 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfW1rco-vnJfpx6JRwJ:-NfzZecv9zak3Rv97Mn3:b7nuquh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0dc454ff340e8e4b5f73a3417342468b5eb05dbb/ios/PacketTunnelCore/Actor/ConfigurationBuilder.swift#L37)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

@rablador raised and fixed this today, perhaps he could push his changes on top. 

In short if we cannot construct `PublicKey()` from raw data, then we should enter blocked state. Returning `nil` here would configure empty WG tunnel which is not the intention when `endpoint` is provided. 

This is extreme edge case as that means that our relay list contains malformed public keys. In conversation with @rablador we figured that throwing an error from here would be better as it would bubble up to `tryStart()` and cause actor to enter error state.
</blockquote></details>

This has been adressed a separate PR that branches off another branch (and ultimately this one). I think it's fine if we merge it after this PR has been merged.
___
*[`ios/PacketTunnelCoreTests/Mocks/PacketTunnelActor+Mocks.swift` line 25 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfzX7Ih7e69kwQ0kxEy:-NfzX7Ih7e69kwQ0kxEz:b-k3vbyw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82974e1554b00619ef847961d23b44d6ace5477f/ios/PacketTunnelCoreTests/Mocks/PacketTunnelActor%2BMocks.swift#L25)):*
> ```Swift
>         tunnelAdapter: TunnelAdapterProtocol = TunnelAdapterDummy(),
>         tunnelMonitor: TunnelMonitorProtocol = TunnelMonitorStub.nonFallible(),
>         defaultPathObserver: DefaultPathObserverProtocol = DefaultPathObserverFake(),
> ```

"Dummy"...?


<!-- Sent from Reviewable.io -->

2023-10-05 11:48 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: all files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/PacketTunnelCore/Actor/Actor+ConnectionMonitoring.swift` line 72 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfzPai6CWgK17sZQIDC:-Nfzd1aTAUr2eAXMED6J:bfitmd9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82974e1554b00619ef847961d23b44d6ace5477f/ios/PacketTunnelCore/Actor/Actor%2BConnectionMonitoring.swift#L72)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I don't think it was discussed outside of our private conversation. This can be addressed separately if you feel so. I think that I poked around a bit and the change wasn't as straightforward as I thought but I could revisit that of course.
</blockquote></details>

No, it was just between us. And no, let's leave it for now if it means extra work.
___
*[`ios/PacketTunnelCore/Actor/Actor+KeyPolicy.swift` line 95 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfzVOAiD50x-lWJaarC:-NfzdSAwB3bZEp3O_0lI:b-ho8l50) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82974e1554b00619ef847961d23b44d6ace5477f/ios/PacketTunnelCore/Actor/Actor%2BKeyPolicy.swift#L95)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I believe I was told to use random to prevent any kind of potential for tracing a connection between the same client using old and new keys.
</blockquote></details>

Aha, didn't know that. Ok, that's fine then since we'll still be adhering to the relay constraints.
___
*[`ios/PacketTunnelCoreTests/Mocks/PacketTunnelActor+Mocks.swift` line 25 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfzX7Ih7e69kwQ0kxEy:-NfzeV5tDdd_Ao6OAH93:bqp6cxk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82974e1554b00619ef847961d23b44d6ace5477f/ios/PacketTunnelCoreTests/Mocks/PacketTunnelActor%2BMocks.swift#L25)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Path observer uses a memory storage to simulate path observer, so t's not a dummy but fake. @buggmagnet shared a link to the article which breaks down the differences. Did I get it wrong?
</blockquote></details>

Probably not, just that it stood out as something we really don't use in the app elsewhere. Nevermind :)


<!-- Sent from Reviewable.io -->

2023-10-06 09:48 UTC, buggmagnet approved these changes
> Reviewed 1 of 8 files at r15, 2 of 2 files at r19, 2 of 2 files at r20, 1 of 1 files at r21, 8 of 8 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: all files reviewed, 5 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/PacketTunnelCoreTests/Mocks/PacketTunnelActor+Mocks.swift` line 25 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfzX7Ih7e69kwQ0kxEy:-Ng3N5ao2KugtG6AvdR5:b-9fgpmp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82974e1554b00619ef847961d23b44d6ace5477f/ios/PacketTunnelCoreTests/Mocks/PacketTunnelActor%2BMocks.swift#L25)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Probably not, just that it stood out as something we really don't use in the app elsewhere. Nevermind :)
</blockquote></details>

@rablador here's the link I posted : [mocks are not stubs](https://martinfowler.com/articles/mocksArentStubs.html)
In most of our test cases, we use stubs (an object that returns pre baked responses)

I'm being nitpicky here and ultimately I think we'll be fine with either dummies or stubs in most of our tests.
It's just that I want to make sure we use the correct terminology so that new comers, or people who read our codebase don't get the wrong idea.


<!-- Sent from Reviewable.io -->

2023-10-06 11:23 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @pronebird)

___
*[`ios/PacketTunnelCoreTests/Mocks/PacketTunnelActor+Mocks.swift` line 25 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5183#-NfzX7Ih7e69kwQ0kxEy:-Ng3iP1u6Rh1jFauleGB:b-yvvhfu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82974e1554b00619ef847961d23b44d6ace5477f/ios/PacketTunnelCoreTests/Mocks/PacketTunnelActor%2BMocks.swift#L25)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

@rablador here's the link I posted : [mocks are not stubs](https://martinfowler.com/articles/mocksArentStubs.html)
In most of our test cases, we use stubs (an object that returns pre baked responses)

I'm being nitpicky here and ultimately I think we'll be fine with either dummies or stubs in most of our tests.
It's just that I want to make sure we use the correct terminology so that new comers, or people who read our codebase don't get the wrong idea.
</blockquote></details>

Got it. According to the article, "Fake" seems correct here.


<!-- Sent from Reviewable.io -->

2023-10-09 10:10 UTC, merged