Migrate problem report view to compose droid 58
mullvad/mullvadvpn-app pull request #5200
Opened 2023-09-27 12:02 UTC by Rawa

Migrate report problem view to compose

- Move some fullscreen logic to dialogs
- Removes old views
- Reworks MullvadProblemReport
- Adds alternative to add color to scroll view (used in view logs)

2023-09-27 12:40 UTC, Pururun requested changes
> Reviewed 20 of 25 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200)* status: all files reviewed, 31 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 45 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLaaiaBXfyya4kt6iU:-NfLaaiaBXfyya4kt6iV:bpki6e9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L45)):*
> ```Kotlin
>                 Image(
>                     painter = painterResource(id = R.drawable.icon_alert),
>                     contentDescription = "Remove",
> ```

This should be translated no?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 46 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLaWIjADO8Qm8vp9s_:-NfLaWIjADO8Qm8vp9sa:b-tusrxf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L46)):*
> ```Kotlin
>                     painter = painterResource(id = R.drawable.icon_alert),
>                     contentDescription = "Remove",
>                     modifier = Modifier.width(50.dp).height(50.dp)
> ```

Please avoid hardcoded dimensions
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 53 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLaeXiAMwRSRRTUhCv:-NfLaeXiAMwRSRRTUhCw:bq6aj9g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L53)):*
> ```Kotlin
>             Text(
>                 text = stringResource(id = R.string.confirm_no_email),
>                 color = colorResource(id = R.color.white),
> ```

Please use compose colors, preferably from the theme.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLaijQ-WDOHMQUNOj1:-NfLaijQ-WDOHMQUNOj2:b-js437t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L54)):*
> ```Kotlin
>                 text = stringResource(id = R.string.confirm_no_email),
>                 color = colorResource(id = R.color.white),
>                 fontSize = dimensionResource(id = R.dimen.text_small).value.sp,
> ```

Please use compose text sizes.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 63 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLamYX315ys5NhzHHY:-NfLamYX315ys5NhzHHZ:b-iasujm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L63)):*
> ```Kotlin
>                 colors =
>                     ButtonDefaults.buttonColors(
>                         containerColor = colorResource(id = R.color.red),
> ```

Compose colors!
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 64 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLaoBC-PVH4bVlrS3_:-NfLaoBC-PVH4bVlrS3a:b-kwrnb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L64)):*
> ```Kotlin
>                     ButtonDefaults.buttonColors(
>                         containerColor = colorResource(id = R.color.red),
>                         contentColor = Color.White
> ```

If possible please use theme colors.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 75 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLarXlA3V5P3RfzW5_:-NfLarXlA3V5P3RfzW5a:b-iasuj9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L75)):*
> ```Kotlin
>                 colors =
>                     ButtonDefaults.buttonColors(
>                         containerColor = colorResource(id = R.color.blue),
> ```

Compose colors.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 76 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLatai8FSBjLbIotqv:-NfLatai8FSBjLbIotqw:bes2gr0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L76)):*
> ```Kotlin
>                     ButtonDefaults.buttonColors(
>                         containerColor = colorResource(id = R.color.blue),
>                         contentColor = Color.White
> ```

Theme colors
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 82 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLavru2qL4cWeUM9fo:-NfLavru2qL4cWeUM9fp:b-iasuj9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L82)):*
> ```Kotlin
>             )
>         },
>         containerColor = colorResource(id = R.color.darkBlue)
> ```

Compose colors.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemStateDialog.kt` line 83 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLaJBVDp-LgYV2QkOF:-NfLaJBWAKnk7KHJdYDQ:b-tgd9y4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemStateDialog.kt#L83)):*
> ```Kotlin
>                 Text(
>                     text = stringResource(id = R.string.sending),
>                     color = colorResource(id = R.color.white),
> ```

Please use compose colors instead.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemStateDialog.kt` line 84 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLaPZ6-yuvcAnXHk3h:-NfLaPZ6-yuvcAnXHk3i:b-8n79zt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemStateDialog.kt#L84)):*
> ```Kotlin
>                     text = stringResource(id = R.string.sending),
>                     color = colorResource(id = R.color.white),
>                     fontSize = dimensionResource(id = R.dimen.text_small).value.sp,
> ```

Please use compose dimensions instead.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemStateDialog.kt` line 97 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLazvh4eFrNwH8nAJe:-NfLazvh4eFrNwH8nAJf:b-yykb8d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemStateDialog.kt#L97)):*
> ```Kotlin
>                 dismissOnBackPress = false,
>             ),
>         containerColor = colorResource(id = R.color.darkBlue)
> ```

Compose colors
___
*[`android/app/src/main/kotlin/net/mul [...]

2023-09-27 13:03 UTC, albin-mullvad reviewed
> Reviewed 10 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200)* status: all files reviewed, 32 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/MinLoadingConstant.kt` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLXDx02IbZNTp-ZVqx:-NfLXDx02IbZNTp-ZVqy:bp688x6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06bf31448ac4307767678c8b96591dc2b75f363f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/MinLoadingConstant.kt#L0)):*
Can this file be named something more generic so that we can include other loading constants in the same file?


<!-- Sent from Reviewable.io -->

2023-09-27 13:23 UTC, Pururun reviewed
Don't forget to update the change log

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-:-NfLngG038E-IxQEcibL:b-3f7n1)* status: all files reviewed, 32 unresolved discussions (waiting on @Rawa)



<!-- Sent from Reviewable.io -->

2023-09-27 13:39 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200)* status: 18 of 28 files reviewed, 32 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 45 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLaaiaBXfyya4kt6iU:-NfLknTe6MzAdDiaErzG:b-ax7ni4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L45)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This should be translated no?
</blockquote></details>

Removed it, we seemingly don't have a good contentDescription for a warning dialog.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 46 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLaWIjADO8Qm8vp9s_:-NfLkteI99FGeEmCit6M:b-4b5g9p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L46)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Please avoid hardcoded dimensions
</blockquote></details>

Good catch, fixed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 53 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLaeXiAMwRSRRTUhCv:-NfLl37VD_IgkvbvdLwE:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L53)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Please use compose colors, preferably from the theme.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLaijQ-WDOHMQUNOj1:-NfLmr134txBj5DhiT9f:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L54)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Please use compose text sizes.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 63 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLamYX315ys5NhzHHY:-NfLmrVg1_fL5Hdpr-8n:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L63)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Compose colors!
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 64 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLaoBC-PVH4bVlrS3_:-NfLms8x3ji4CBvmn-AS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L64)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

If possible please use theme colors.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 75 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLarXlA3V5P3RfzW5_:-NfLmssg9zWbba3JnGhv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L75)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Compose colors.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 76 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLatai8FSBjLbIotqv:-NfLmt5e7UCfFu4DTUOu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L76)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Theme colors
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt` line 82 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLavru2qL4cWeUM9fo:-NfLmtXZ9QeB-U-6jZkc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt#L82)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Compose colors.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemStateDialog.kt` line 83 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLaJBVDp-LgYV2QkOF:-NfLmu2772wN2F6tLoAC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemStateDialog.kt#L83)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Please use compose colors instead.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemStateDialog.kt` line 84 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLaPZ6-yuvcAnXHk3h:-NfLmvEW5F-HpCluJ_W6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemStateDialog.kt#L84)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Please use compose dimensions instead.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemStateDialog.kt` line 97 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLazvh4eFrNwH8nAJe:-NfLmvcb2QN-uFzXxvKY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemStateDialog.kt#L97)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Compose colors
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemStateDialog.kt` line 121 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLb21W3LIyzDC4sdJW:-NfLnANK9XbG9Ufib-R9:bss4a2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56fe418bcc6a716e2efe273a75d5ca92ce01079e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemStateDialog.kt#L121)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Translated?
</blockquote></details>

Removed.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemStateDialog.kt` line 122 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-ap [...]

2023-09-27 13:42 UTC, albin-mullvad reviewed
> Reviewed 1 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200)* status: 18 of 28 files reviewed, 32 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/MinLoadingConstant.kt` line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLXDx02IbZNTp-ZVqx:-NfLrsVy-C6loKZPVKTq:b-qownwa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/06bf31448ac4307767678c8b96591dc2b75f363f/android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/MinLoadingConstant.kt#L)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Maybe "TimingConstant" ?
</blockquote></details>

Yes, `AnimationConstant` or `TimingConstant` works! :thumbsup: 


<!-- Sent from Reviewable.io -->

2023-09-27 14:05 UTC, Pururun requested changes
> Reviewed 2 of 4 files at r3, 1 of 1 files at r4, 4 of 6 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt` line 56 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLxEIj3kl96r0bXhpx:-NfLxEIk62oxQzpA3Vne:b-f2geei) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2392f28934bca7cabca4b1c3323c9eabab047e0c/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt#L56)):*
> ```Kotlin
>     val verticalSpace: Dp = 20.dp,
>     val verticalSpacer: Dp = 1.dp,
>     val dialogIconSize: Dp = 48.dp
> ```

Dimens should be in alphabetical order.


<!-- Sent from Reviewable.io -->

2023-09-28 07:09 UTC, Pururun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-:-NfPbcuL4WPLJraS_bhd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt` line 56 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfLxEIj3kl96r0bXhpx:-NfPbWN7Bh4zj4YEuu4M:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2392f28934bca7cabca4b1c3323c9eabab047e0c/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt#L56)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Dimens should be in alphabetical order.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-10-02 14:11 UTC, Pururun approved these changes
> Reviewed 24 of 29 files at r11, 33 of 33 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-02 14:16 UTC, Pururun approved these changes
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-02 14:49 UTC, Pururun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-:-NfkrHzqAiZ2DNmJ2m4e:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-03 08:26 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200)* status: all files reviewed, 4 unresolved discussions (waiting on @sabercodic)

___
*[`-- commits` line 3 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfkoCs3CgKia5AuYXiQ):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

There is a new file in this commit that removed later(MinLoadingConstant.kt), any reason for it?
</blockquote></details>

We renamed it to TimingConstants.kt after review.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt` line 197 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfkqPhzExd8kiDQqSEm:-NfobhFY7uUsOQfPJ65m:bx09l5d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4ebffad24bb64ef1a9927b8e31f137351a0ce01/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt#L197)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Is this related to this PR?
</blockquote></details>

Yes, we reused the textfield colors in another ProblemReport so I broke it out to a separate file to reuse the colors from the login screen.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ReportProblemScreen.kt` line 211 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfksCne4F2A4PBd_n-e:-NfobpDa2z-Gr1s_P4_D:b-9qk2oi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4ebffad24bb64ef1a9927b8e31f137351a0ce01/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ReportProblemScreen.kt#L211)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Will we do content through extensions?
</blockquote></details>

The reason is to keep the `ColumnScope` and not have to redefine the column in each of the states, since it is private to this file I think it is cleanest way to do it, rather than redefining the Column with padding etc. 3 times.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt` line 83 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfksPgI9Doq-N0uEpPI:-Nfoc2mtB0qDjye0qwaq:b-arqzj8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4ebffad24bb64ef1a9927b8e31f137351a0ce01/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt#L83)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Is not it better to show spinner in screen center
</blockquote></details>

How do you mean? Center vertically as well?


<!-- Sent from Reviewable.io -->

2023-10-03 08:35 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200)* status: 57 of 58 files reviewed, 4 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ReportProblemScreen.kt` line 211 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfksCne4F2A4PBd_n-e:-NfoemC4B5RnvF9HNam6:b-locgba) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4ebffad24bb64ef1a9927b8e31f137351a0ce01/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ReportProblemScreen.kt#L211)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

The reason is to keep the `ColumnScope` and not have to redefine the column in each of the states, since it is private to this file I think it is cleanest way to do it, rather than redefining the Column with padding etc. 3 times.
</blockquote></details>

Idea is to keep it more in line of context receivers (We are in the context of a Column), rather than thinking of it as an extension function of ColumnScope. Later the syntax would be more like this:


```
@Composable
context(ColumnScope)
fun SendingContent() {
    ...
}
```

Does it make sense?


<!-- Sent from Reviewable.io -->

2023-10-03 13:03 UTC, sabercodic approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-:-Nfpck9u20t57NuqlhB5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt` line 83 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfksPgI9Doq-N0uEpPI:-Nfoj8ah859oUpiEtYcB:b2nign6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4ebffad24bb64ef1a9927b8e31f137351a0ce01/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt#L83)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

How do you mean? Center vertically as well?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2023-10-04 07:54 UTC, sabercodic reviewed
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)



<!-- Sent from Reviewable.io -->

2023-10-04 07:54 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt` line 83 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-NfksPgI9Doq-N0uEpPI:-NftfKXd6AYTfsKcArX1:b-oq5c1v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4ebffad24bb64ef1a9927b8e31f137351a0ce01/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt#L83)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

yes
</blockquote></details>

The loading are top aligned in the Split tunnels page, so I assumed that it was so. There was no design for showing the loading bar.


<!-- Sent from Reviewable.io -->

2023-10-04 08:13 UTC, sabercodic approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-04 08:13 UTC, sabercodic approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5200#-:-NftjxwBCKEYF2TMNq-i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-04 08:32 UTC, merged