Fix clipboard paste bug
mullvad/mullvadvpn-app pull request #5271
Opened 2023-10-11 13:45 UTC by sabercodic

2023-10-11 14:12 UTC, Pururun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-:-NgU48ci4FuMtRPRVAdw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-11 14:55 UTC, Rawa approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-11 14:55 UTC, Rawa approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-:-NgUE6Kv0W1F-3cyRlk7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-12 12:28 UTC, Pururun reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NgYqYwUDpb8-gDksYLi:-NgYqYwUDpb8-gDksYLj:br8kxhr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/89382f276bf8d9ef268105f93608987743cea2d3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L36)):*
> ```Kotlin
>     private val voucherInput = MutableStateFlow(LoginUiState.INITIAL.accountNumberInput)
> 
>     lateinit var voucherRedeemer: VoucherRedeemer
> ```

I'm not sure I like this change, to make something public just to enable tests feels a bit weird. Maybe we can keep it this way and when we have updated the messaging architecture we can revert this and make the tests better.


<!-- Sent from Reviewable.io -->

2023-10-13 07:32 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NgYqYwUDpb8-gDksYLi:-Ngbw5696L8vv9QMo0S8:bu7purk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/89382f276bf8d9ef268105f93608987743cea2d3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L36)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I'm not sure I like this change, to make something public just to enable tests feels a bit weird. Maybe we can keep it this way and when we have updated the messaging architecture we can revert this and make the tests better.
</blockquote></details>

Yes, this should not be exposed. I wonder why this isn't catched by our compose test case @Rawa :thinking: 

Test name: `ensure public properties use permitted names`


<!-- Sent from Reviewable.io -->

2023-10-13 07:33 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NgYqYwUDpb8-gDksYLi:-Ngbx0sN1uoe4wGLL4aS:b7qpohb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/89382f276bf8d9ef268105f93608987743cea2d3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L36)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Yes, this should not be exposed. I wonder why this isn't catched by our compose test case @Rawa :thinking: 

Test name: `ensure public properties use permitted names`
</blockquote></details>

compose -> konsist *


<!-- Sent from Reviewable.io -->

2023-10-13 11:33 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NgYqYwUDpb8-gDksYLi:-NgcnvEtB7qGItzVRzC2:b-7qq7u2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/89382f276bf8d9ef268105f93608987743cea2d3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L36)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

compose -> konsist *
</blockquote></details>

Here's a PR to fix the konsist issue: https://github.com/mullvad/mullvadvpn-app/pull/5288


<!-- Sent from Reviewable.io -->

2023-10-16 06:19 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @Pururun and @sabercodic)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 59 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Ngr7FDI6j8o72w_45cY:-Ngr7FDI6j8o72w_45cZ:b-gksxu6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3407ded4090d01e916c2f31d62cb2c88585344ab/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L59)):*
> ```Kotlin
>     @Test
>     fun test_submit_invalid_voucher() = runTest {
>         val voucher = DUMMY_VALID_VOUCHER
> ```

We call this test `test_submit_invalid_voucher` but we send in a  DUMMY_VALID_VOUCHER.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 69 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Ngr7Xk0Ep7qHeoibARa:-Ngr7Xk0Ep7qHeoibARb:b-voyit2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3407ded4090d01e916c2f31d62cb2c88585344ab/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L69)):*
> ```Kotlin
>         // Act, Assert
>         viewModel.onRedeem(voucher)
>         coVerify(exactly = 1) { mockVoucherRedeemer.submit(voucher) }
> ```

Do we actually `test_submit_invalid_voucher`? To be me it looks like we verify that if we call viewModel.onRedeem we will have a call to voucherRedeemer.submit with the same voucher? No matter if the voucher is valid or invalid?


<!-- Sent from Reviewable.io -->

2023-10-17 07:20 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NgYqYwUDpb8-gDksYLi:-NgcoCOb8SRwggE8I1KQ:b-7pvwig) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/89382f276bf8d9ef268105f93608987743cea2d3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L36)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Here's a PR to fix the konsist issue: https://github.com/mullvad/mullvadvpn-app/pull/5288
</blockquote></details>

great
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 59 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Ngr7FDI6j8o72w_45cY:-NgsQS2o1e17UHfAhvhw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3407ded4090d01e916c2f31d62cb2c88585344ab/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L59)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We call this test `test_submit_invalid_voucher` but we send in a  DUMMY_VALID_VOUCHER.
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 69 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Ngr7Xk0Ep7qHeoibARa:-NgsQSKm6GsJG_21ZlVW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3407ded4090d01e916c2f31d62cb2c88585344ab/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L69)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Do we actually `test_submit_invalid_voucher`? To be me it looks like we verify that if we call viewModel.onRedeem we will have a call to voucherRedeemer.submit with the same voucher? No matter if the voucher is valid or invalid?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-06 12:07 UTC, albin-mullvad requested changes
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 36 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NgYqYwUDpb8-gDksYLi:-NiZFT7E1tQ0g4oZk4oG:b-7132gn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/89382f276bf8d9ef268105f93608987743cea2d3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L36)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

great
</blockquote></details>

There's a reason the konsist test was added and we should not introduce code that isn't compliant with it. This property shouldn't be public and that hasn't been addressed.


<!-- Sent from Reviewable.io -->

2023-11-09 09:30 UTC, Pururun requested changes
> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, 3 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 29 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NinPcJ7BAHKOgHxOY-j:-NinPcJ7BAHKOgHxOY-k:b-1n5x9k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c1a71372b05718653e4a189c521ab898ce062ecd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L29)):*
> ```Kotlin
> 
> class VoucherDialogViewModel(
>     val serviceConnectionManager: ServiceConnectionManager,
> ```

This should be private.


<!-- Sent from Reviewable.io -->

2023-11-09 09:51 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 29 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NinPcJ7BAHKOgHxOY-j:-NinUYGJ2XOYSvl_4HDu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c1a71372b05718653e4a189c521ab898ce062ecd/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L29)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This should be private.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-09 10:13 UTC, Pururun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-:-NinZc6rC-kyvdIAtMUB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)



<!-- Sent from Reviewable.io -->

2023-11-09 10:49 UTC, albin-mullvad requested changes
> Reviewed 1 of 2 files at r1, 3 of 4 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 3 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 42 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NingKMGCu5X40FpSdv-:-NingKMGCu5X40FpSdv0:b-uu72w7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d320ac59dfd0e65b0fd7d27e04ea9f47e81ca4b2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L42)):*
> ```Kotlin
> 
> private const val VALID_VOUCHER_CHARACTER_REGEX_PATTERN = "^[A-Za-z0-9- \r\n]*$"
> private const val IGNORED_VOUCHER_CHARACTER_REGEX_PATTERN = """[- \n\r]"""
> ```

Can we add some VM and/or screen tests related to all the special cases that we now handle?



_Code quote:_
```Kotlin
private const val VALID_VOUCHER_CHARACTER_REGEX_PATTERN = "^[A-Za-z0-9- \r\n]*$"
private const val IGNORED_VOUCHER_CHARACTER_REGEX_PATTERN = """[- \n\r]"""
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 48 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NinbIjK9gjZAlPDWXWH:-NinbIjK9gjZAlPDWXWI:b-cllto) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d320ac59dfd0e65b0fd7d27e04ea9f47e81ca4b2/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L48)):*
> ```Kotlin
>     @Before
>     fun setUp() {
>         MockKAnnotations.init(this)
> ```

Is this call needed? I don't believe there are any mockk annotations to initialize



_Code quote:_
```Kotlin
MockKAnnotations.init(this)
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 67 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Ning_HpE6nLUBIlV-DH:-Ning_HpE6nLUBIlV-DI:b-nxomgm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d320ac59dfd0e65b0fd7d27e04ea9f47e81ca4b2/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L67)):*
> ```Kotlin
> 
>     @Test
>     fun test_submit_voucher() = runTest {
> ```

We should probably test more than a single case. Or is that not needed for some reason? :thinking: 



_Code quote:_
```Kotlin
test_submit_voucher
```


<!-- Sent from Reviewable.io -->

2023-11-09 12:24 UTC, albin-mullvad reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 3 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 42 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NingKMGCu5X40FpSdv-:-Nio1B25CODKt6uHELqU:bn5m2qj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d320ac59dfd0e65b0fd7d27e04ea9f47e81ca4b2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L42)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can we add some VM and/or screen tests related to all the special cases that we now handle?
</blockquote></details>

Maybe we can even break this pattern matching logic out to easily create a set of tests for it? It's very hard to review or make sure it works as expected otherwise.


<!-- Sent from Reviewable.io -->

2023-11-10 08:33 UTC, Rawa approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 42 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NingKMGCu5X40FpSdv-:-NisM2kmBzFD0U9LBgHq:b-uu5a35) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d320ac59dfd0e65b0fd7d27e04ea9f47e81ca4b2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L42)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Maybe we can even break this pattern matching logic out to easily create a set of tests for it? It's very hard to review or make sure it works as expected otherwise.
</blockquote></details>

I also believe logical pieces like this generally shouldn't be handled in the UI, it is generally nicer to let the viewmodel do the work.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 67 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Ning_HpE6nLUBIlV-DH:-NisImku9rxmAo22c-jc:bjo4goy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d320ac59dfd0e65b0fd7d27e04ea9f47e81ca4b2/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L67)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We should probably test more than a single case. Or is that not needed for some reason? :thinking:
</blockquote></details>

Yeah agree, it would be nice to test that we get the right errors etc.


<!-- Sent from Reviewable.io -->

2023-11-13 10:01 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 3 unresolved discussions (waiting on @Rawa and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 42 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NingKMGCu5X40FpSdv-:-Nj75ePe99wU_TJQ5AGM:b-aebnvk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d320ac59dfd0e65b0fd7d27e04ea9f47e81ca4b2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L42)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I also believe logical pieces like this generally shouldn't be handled in the UI, it is generally nicer to let the viewmodel do the work.
</blockquote></details>

I think a class or object called something like VoucherValidator that only validates voucher input would make sense. Such a class could be used either in the UI or in the VM, depending on the rest of the implementation. That way, we can easily and in a isolated way test that a set of input is parsed/validated correctly in a set of tests (perhaps parameterized?).
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 67 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Ning_HpE6nLUBIlV-DH:-Nj76Nju4JVJDJATdfoF:b-i5ro88) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d320ac59dfd0e65b0fd7d27e04ea9f47e81ca4b2/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L67)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Yeah agree, it would be nice to test that we get the right errors etc.
</blockquote></details>

Related to this comment, please see the other comment regarding moving out the voucher validation logic


<!-- Sent from Reviewable.io -->

2023-11-13 13:28 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 48 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NinbIjK9gjZAlPDWXWH:-Nj7fBzT7U-wYyeMcOKF:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d320ac59dfd0e65b0fd7d27e04ea9f47e81ca4b2/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L48)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this call needed? I don't believe there are any mockk annotations to initialize
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 67 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Ning_HpE6nLUBIlV-DH:-Nj7rGlQDOnAd8tJdbaP:bpb3wf6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d320ac59dfd0e65b0fd7d27e04ea9f47e81ca4b2/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L67)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Related to this comment, please see the other comment regarding moving out the voucher validation logic
</blockquote></details>

Should we add more tests within this PR or I should create new PR?


<!-- Sent from Reviewable.io -->

2023-11-13 13:56 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @Pururun, @Rawa, and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt` line 15 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Nj7wuu851k2TekZ294n:-Nj7wuu851k2TekZ294o:b-r72qn6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1dfff3ddf1157f2f84b0c94f2778e95937b86937/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt#L15)):*
> ```Kotlin
> 
> fun String.trimAsVoucher(): String =
>     this.replace(Regex(IGNORED_VOUCHER_CHARACTER_REGEX_PATTERN), "")
> ```

We should avoid making this function a string extension since it will bloat the string function list thoughout the project. Did you see my linked suggestion? 

https://github.com/mullvad/mullvadvpn-app/pull/5271#pullrequestreview-1726957350



_Code quote:_
```Kotlin
fun String.trimAsVoucher(): String =
    this.replace(Regex(IGNORED_VOUCHER_CHARACTER_REGEX_PATTERN), "")
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 67 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Ning_HpE6nLUBIlV-DH:-Nj7tWn32CcZgE9E58ar:b-rj45ok) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d320ac59dfd0e65b0fd7d27e04ea9f47e81ca4b2/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L67)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Should we add more tests within this PR or I should create new PR?
</blockquote></details>

The tests should be added in this PR. That's usually how we do it unless we have a good reason to not do so. Having them as part of the PR where we add/change the logic can help us ensure that the new logic is correct.


<!-- Sent from Reviewable.io -->

2023-11-16 08:37 UTC, albin-mullvad requested changes
> Reviewed 1 of 7 files at r12, 1 of 2 files at r13, 1 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @Pururun and @sabercodic)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjMEn1Z95uDJ-TnVupz:-NjMEn1Z95uDJ-TnVuq-:b-de752w) (no related file):*
As talked about offline, we should add parameterized tests for `VoucherRegexHelper`

___
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/VoucherRegexHelper.kt` line 1 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjMGHhH7yQViUhYcT2V:-NjMGHhI2YfQTtrUZV_N:bdn41zi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e86eae8d65af070b940b51560d9c9af943086ae0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/VoucherRegexHelper.kt#L1)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.util
> ```

Nice improvement with this one :thumbsup: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 71 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjMFUXb3t2mzPsdHLr6:-NjMFUXb3t2mzPsdHLr7:b3evykw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e86eae8d65af070b940b51560d9c9af943086ae0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L71)):*
> ```Kotlin
>     }
> 
>     fun validateVoucher(voucher: String): Boolean = VoucherRegexHelper.validate(voucher)
> ```

This function violates one of our Konsist tests: https://github.com/mullvad/mullvadvpn-app/blob/67710f3e2ef57ecbe60c1bcb444ab047f11f79a5/android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/ViewModelTests.kt#L28C34-L28C34

I believe @Rawa had some suggestion on how to best include the calls to `validate` and `trim`. Can you chime in?
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 57 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjME-bO4TFfZauf0NUc:-NjME-bO4TFfZauf0NUd:bwauuvv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e86eae8d65af070b940b51560d9c9af943086ae0/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L57)):*
> ```Kotlin
>     @Test
>     @Ignore("TODO: Fix this failing test and then enable it again.")
>     fun test_submit_invalid_voucher() = runTest {
> ```

We should test submitting both valid and invalid vouchers. In those tests `VoucherRegexHelper` should be mocked.


<!-- Sent from Reviewable.io -->

2023-11-16 14:44 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: 4 of 10 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 221 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjNYLck2j0lpeWgUAxt:-NjNYLck2j0lpeWgUAxu:b-wmyqu7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e86eae8d65af070b940b51560d9c9af943086ae0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L221)):*
> ```Kotlin
>     onRedeem: (voucherCode: String) -> Unit,
>     onVoucherInputChange: (String) -> Unit = {},
>     voucherValidator: (voucher: String) -> Boolean = { true }
> ```

We do this in several places, and it seems dangerous. If we miss the argument we wouldn't do any validation.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 71 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjMFUXb3t2mzPsdHLr6:-NjNYbML8XPuQVQIw5jG:bw3hlo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e86eae8d65af070b940b51560d9c9af943086ae0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L71)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This function violates one of our Konsist tests: https://github.com/mullvad/mullvadvpn-app/blob/67710f3e2ef57ecbe60c1bcb444ab047f11f79a5/android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/ViewModelTests.kt#L28C34-L28C34

I believe @Rawa had some suggestion on how to best include the calls to `validate` and `trim`. Can you chime in?
</blockquote></details>

Yes, we should do this logic directly in the view model. We already have a `voucherInput` in this view model and we trim when the view edit that value. Not sure exactly why we need validation in UI layer since we will already have the trim, but if we want to notify if it is valid or not we can just include that into the viewstate. We already have the latest voucherInput value from when we combine into `uiState` 

Ping me if I'm not clear or if you want to pair-program it togheter :+1: 


<!-- Sent from Reviewable.io -->

2023-11-17 17:03 UTC, albin-mullvad requested changes
> Reviewed 6 of 9 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: 10 of 13 files reviewed, 6 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt` line 40 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjTDmnwBW33UEC3PEbe:-NjTDmnwBW33UEC3PEbf:b-zdgjhp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaa4a60a68a99b583145d8854e8f2070501d601e/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt#L40)):*
> ```Kotlin
>     @Before
>     fun setup() {
>         MockKAnnotations.init(this)
> ```

There's no `@MockK` annotations in this test, so this one can be skipped.



_Code quote:_
```Kotlin
MockKAnnotations.init(this)
```
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt` line 51 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjTE4lT0sPa9tEWh2ky:-NjTE4lT0sPa9tEWh2kz:be8fk0i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaa4a60a68a99b583145d8854e8f2070501d601e/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt#L51)):*
> ```Kotlin
> 
>         // Act
>         val vm = VoucherDialogViewModel(mockServiceConnectionManager, mockResources)
> ```

Is there any reason for not mocking the vm?



_Code quote:_
```Kotlin
val vm = VoucherDialogViewModel(mockServiceConnectionManager, mockResources)
```


<!-- Sent from Reviewable.io -->

2023-11-20 09:39 UTC, albin-mullvad requested changes
> Reviewed 2 of 9 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 15 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt` line 51 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjTE4lT0sPa9tEWh2ky:-Njg57rn5REgkfDvZCvH:b89ql5e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaa4a60a68a99b583145d8854e8f2070501d601e/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt#L51)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is there any reason for not mocking the vm?
</blockquote></details>

Mocking also means removing a lot of other mocked stuff, like for example: `mockServiceConnectionManager` & `mockResources`
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt` line 45 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Njg4hje14RexVnDR1B4:-Njg4hje14RexVnDR1B5:bwpwiq3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt#L45)):*
> ```Kotlin
> 
>     @Test
>     fun testInsertInvalidVoucher() {
> ```

There should probably be two tests here, one for inserting a voucher with "valid" and one with "Invalid" format
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt` line 63 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Njfuc8L-jwWeRTVxd1B:-Njfuc8L-jwWeRTVxd1C:biirihk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt#L63)):*
> ```Kotlin
> 
>         // Sets the TextField value
>         composeTestRule.onNodeWithTag(VOUCHER_INPUT_TEST_TAG).performTextInput(DUMMY_VALID_VOUCHER)
> ```

This seem to differ from the test name `testInsertInvalidVoucher`



_Code quote:_
```Kotlin
performTextInput(DUMMY_VALID_VOUCHER)
```
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt` line 83 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Njfuqvz0MXoHl-Z5jLc:-Njfuqvz0MXoHl-Z5jLd:bzdzq9h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt#L83)):*
> ```Kotlin
>                 onDismiss = mockedClickHandler
>             )
>         }
> ```

I suggest moving this to `Arrange`. Same for the other test.



_Code quote:_
```Kotlin
        composeTestRule.setContentWithTheme {
            RedeemVoucherDialogScreen(
                uiState = VoucherDialogUiState.INITIAL,
                onVoucherInputChange = {},
                onRedeem = {},
                onDismiss = mockedClickHandler
            )
        }
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/utils/RedeemVoucherHelperTest.kt` line 13 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjfsZWk9RWQiTsyFeVd:-NjfsZWk9RWQiTsyFeVe:b10o2f8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/test/kotlin/net/mullvad/mullvadvpn/utils/RedeemVoucherHelperTest.kt#L13)):*
> ```Kotlin
> 
> @RunWith(Parameterized::class)
> class RedeemVoucherHelperTest(private val isValid: Boolean, private val voucher: String) {
> ```

I suggest renaming to `VoucherRegexHelperParameterizedTest`



_Code quote:_
```Kotlin
RedeemVoucherHelperTest
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/utils/RedeemVoucherHelperTest.kt` line 31 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjfqsWU63sZfxyxXVNW:-NjfqsWU63sZfxyxXVNX:bjickix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/test/kotlin/net/mullvad/mullvadvpn/utils/RedeemVoucherHelperTest.kt#L31)):*
> ```Kotlin
>                 arrayOf(false, non_acceptable_inputs_for_voucher[0]),
>                 arrayOf(false, non_acceptable_inputs_for_voucher[1]),
>                 arrayOf(false, non_acceptable_inputs_for_voucher[2])
> ```

It's hard to get an overview regarding which vouchers and valid and not by looking at this? Can you structure it in a way where you can see the boolean next to the actual voucher? Perhaps also switching argument order and using a constant for the boolean would be nice to clarify that `true`/`false` actually means. 

My suggestions would structure it like this:
```
 arrayOf("AAAA-AAAA-1111-2222", IS_ACCEPTED_FORMAT)
 // ...
 arrayOf("AAAA_BBBB_CCCC_DDDD", IS_UNACCEPTED_FORMAT)
```



_Code quote:_
```Kotlin
                arrayOf(true, acceptable_inputs_for_voucher[0]),
                arrayOf(true, acceptable_inputs_for_voucher[1]),
                arrayOf(true, acceptable_inputs_for_voucher[2]),
                arrayOf(true, acceptable_inputs_for_voucher[3]),
                arrayOf(true, acceptable_inputs_for_voucher[4]),
                arrayOf(true, acceptable_inputs_for_voucher[5]),
                arrayOf(true, acceptable_inputs_for_voucher[6]),
                arrayOf(true, acceptable_inputs_for_voucher[7]),
                arrayOf(false, non_acceptable_inputs_for_voucher[0]),
                arrayOf(false, non_acceptable_inputs_for_voucher[1]),
                arrayOf(false, non_acceptable_inputs_for_voucher[2])
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/utils/RedeemVoucherHelperTest.kt` line 54 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjfsJcACF1pS3qjLp5_:-NjfsJcB2mY9wZUDe63-:bgdndlh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/test/kotlin/net/mullvad/mullvadvpn/utils/RedeemVoucherHelperTest.kt#L54)):*
> ```Kotlin
> 
>     @Test
>     fun shouldReturnExpectedResultForVoucherCheck() {
> ```

I suggest renaming to `testVoucherFormat`



_Code quote:_
```Kotlin
shouldReturnExpectedResultForVoucherCheck
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 45 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjftbqkB2a-ZFic48KP:-NjftbqkB2a-ZFic48KQ:b-wy638c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L45)):*
> ```Kotlin
> 
>     private val mockVoucherSubmissionOkResult: VoucherSubmissionResult.Ok =
>         VoucherSubmissionResult.Ok(mockVoucherSubmission)
> ```

Should probably be moved to the test itself. Same for `mockVoucherSubmissionErrorResult`



_Code quote:_
```Kotlin
    private val mockVoucherSubmissionOkResult: VoucherSubmissionResult.Ok =
        VoucherSubmissionResult.Ok(mockVoucherSubmission)
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 87 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjfthY2-rlI9BQjsErD:-NjfthY2-rlI9BQjsErE:b5s5zxc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L87)):*
> ```Kotlin
> 
>     @Test
>     fun testInsertValidVoucher() = runTest {
> ```

Why is this quite different from the `testSubmitVoucher`? I assume they should be almost identical
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 103 at r16](https://reviewable.io/reviews/mullvad/mullvad [...]

2023-11-22 16:25 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: 8 of 13 files reviewed, 13 unresolved discussions (waiting on @albin-mullvad)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjMEn1Z95uDJ-TnVupz:-Njfr9AuEM89DG_5Ki3Q:bb6un1j) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

As talked about offline, we should add parameterized tests for `VoucherRegexHelper`
</blockquote></details>

Done

___
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt` line 40 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjTDmnwBW33UEC3PEbe:-NjfrNcX2moK_1xFJ47Z:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaa4a60a68a99b583145d8854e8f2070501d601e/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt#L40)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

There's no `@MockK` annotations in this test, so this one can be skipped.
</blockquote></details>

Done.
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt` line 51 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjTE4lT0sPa9tEWh2ky:-NjfuOYe6qF3xGkwK9BY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaa4a60a68a99b583145d8854e8f2070501d601e/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt#L51)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is there any reason for not mocking the vm?
</blockquote></details>

Done.
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt` line 45 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Njg4hje14RexVnDR1B4:-NjrMoFEA5ygrfhKqYdq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt#L45)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

There should probably be two tests here, one for inserting a voucher with "valid" and one with "Invalid" format
</blockquote></details>

Done.
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt` line 63 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Njfuc8L-jwWeRTVxd1B:-Njm6xviB8O5VegYEmPO:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt#L63)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This seem to differ from the test name `testInsertInvalidVoucher`
</blockquote></details>

Done.
___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt` line 83 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Njfuqvz0MXoHl-Z5jLc:-NjrNaxR1JVPhWsAR4m6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt#L83)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest moving this to `Arrange`. Same for the other test.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 221 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjNYLck2j0lpeWgUAxt:-NjR_UGb65HCCEGUtnyp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e86eae8d65af070b940b51560d9c9af943086ae0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L221)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We do this in several places, and it seems dangerous. If we miss the argument we wouldn't do any validation.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 71 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjMFUXb3t2mzPsdHLr6:-NjR_VCN5uP-1fInpvBa:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e86eae8d65af070b940b51560d9c9af943086ae0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L71)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Yes, we should do this logic directly in the view model. We already have a `voucherInput` in this view model and we trim when the view edit that value. Not sure exactly why we need validation in UI layer since we will already have the trim, but if we want to notify if it is valid or not we can just include that into the viewstate. We already have the latest voucherInput value from when we combine into `uiState` 

Ping me if I'm not clear or if you want to pair-program it togheter :+1:
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 45 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjftbqkB2a-ZFic48KP:-NjrR-pR7qECGpSwf8pv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L45)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should probably be moved to the test itself. Same for `mockVoucherSubmissionErrorResult`
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 103 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Njft-YYBjwIx08oc9sU:-NjrSak53s9GGCvGe9Mq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L103)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The `Act` and `Assert` can be easily separated here
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt` line 15 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Nj7wuu851k2TekZ294n:-Nj8D6rQ3-0xds7kWS5J:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1dfff3ddf1157f2f84b0c94f2778e95937b86937/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt#L15)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

We should avoid making this function a string extension since it will bloat the string function list thoughout the project. Did you see my linked suggestion? 

https://github.com/mullvad/mullvadvpn-app/pull/5271#pullrequestreview-1726957350
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/utils/RedeemVoucherHelperTest.kt` line 13 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjfsZWk9RWQiTsyFeVd:-Njg67Wb3k_7GHO2Sca5:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/test/kotlin/net/mullvad/mullvadvpn/utils/RedeemVoucherHelperTest.kt#L13)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest renaming to `VoucherRegexHelperParameterizedTest`
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/utils/RedeemVoucherHelperTest.kt` line 31 at r16](https://reviewable.io/reviews/mull [...]

2023-11-22 16:26 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: 8 of 13 files reviewed, 13 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt` line 51 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjTE4lT0sPa9tEWh2ky:-NjrqZrv294ztNT4HV-5:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aaa4a60a68a99b583145d8854e8f2070501d601e/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt#L51)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-22 16:47 UTC, Pururun approved these changes
> Reviewed 5 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 13 unresolved discussions (waiting on @albin-mullvad)



<!-- Sent from Reviewable.io -->

2023-11-23 08:57 UTC, albin-mullvad requested changes
> Reviewed 4 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 7 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt` line 26 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjrwV6z33WodAjLfGG_:-NjrwV6z33WodAjLfGGa:b6h5aje) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58ca7263ccbdedbe7a3ae4f2c87fddfb5001a147/android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt#L26)):*
> ```Kotlin
>     @get:Rule val composeTestRule = createComposeRule()
> 
>     private var uiState = VoucherDialogUiState.INITIAL
> ```

I suggest using this one directly in each test instead



_Code quote:_
```Kotlin
VoucherDialogUiState.INITIAL
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt` line 236 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjvLuBz9OX7RdStnoaj:-NjvLuBz9OX7RdStnoak:bsp9xv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58ca7263ccbdedbe7a3ae4f2c87fddfb5001a147/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt#L236)):*
> ```Kotlin
>         onValueChanged = { input ->
>             voucherInput = input
>             onVoucherInputChange(input)
> ```

Should we really update two places?



_Code quote:_
```Kotlin
            voucherInput = input
            onVoucherInputChange(input)
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 35 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjvNpjS2GR09zUqhWG7:-NjvNpjS2GR09zUqhWG8:b5vqq2g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58ca7263ccbdedbe7a3ae4f2c87fddfb5001a147/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L35)):*
> ```Kotlin
> 
>     private val vmState = MutableStateFlow<VoucherDialogState>(VoucherDialogState.Default)
>     private val voucherInput = MutableStateFlow(VoucherDialogUiState.INITIAL.voucherInput)
> ```

What's the reason for using the `voucherInput` string rather than the `VoucherDialogUiState.INITIAL` state here?



_Code quote:_
```Kotlin
VoucherDialogUiState.INITIAL.voucherInput
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 45 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjftbqkB2a-ZFic48KP:-Njs8MGG0ujtQhGZuSCH:bckue20) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L45)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I also mentioned `mockVoucherSubmissionErrorResult` so that we keep it consistent
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/utils/RedeemVoucherHelperTest.kt` line 31 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NjfqsWU63sZfxyxXVNW:-NjvGYmO9RiS8DS5AYpS:b-7l90hh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6893e6622e0eb5c389edd1d8ae12773ff9568ecb/android/app/src/test/kotlin/net/mullvad/mullvadvpn/utils/RedeemVoucherHelperTest.kt#L31)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

Done.
</blockquote></details>

As shown in my example above, can we also move the vouchers to top-level array to avoid two levels of arrays?


<!-- Sent from Reviewable.io -->

2023-11-24 12:11 UTC, albin-mullvad requested changes
> Reviewed 5 of 5 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 4 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 52 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Nk-XVa94xLPPQicAT6q:-Nk-XVa94xLPPQicAT6r:b-kp98g9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c65bd7147e8f2000a8f9df390ba630d909153e74/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L52)):*
> ```Kotlin
>         every { mockServiceConnectionContainer.connectionProxy } returns mockConnectionProxy
> 
>         serviceConnectionState.value
> ```

Clean up



_Code quote:_
```Kotlin
serviceConnectionState.value
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 79 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Nk-idC8-OK4ql2Npu3l:-Nk-idC8-OK4ql2Npu3m:b-i3venf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c65bd7147e8f2000a8f9df390ba630d909153e74/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L79)):*
> ```Kotlin
>         coEvery { mockVoucherRedeemer.submit(voucher) } returns
>             VoucherSubmissionResult.Ok(mockVoucherSubmission)
>         // Act
> ```

Missing newline
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 93 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Nk-eLrI6K5SP21q8Qcu:-Nk-eLrI6K5SP21q8Qcv:b-5iew9s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c65bd7147e8f2000a8f9df390ba630d909153e74/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L93)):*
> ```Kotlin
> 
>         // Arrange
>         val uiStates = viewModel.uiState
> ```

This can be skipped



_Code quote:_
```Kotlin
val uiStates = viewModel.uiState
```
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 104 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Nk0E0bBAsEY_fR4w-5A:-Nk0E0bBAsEY_fR4w-5B:bjd7xv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c65bd7147e8f2000a8f9df390ba630d909153e74/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L104)):*
> ```Kotlin
> 
>         // Assert
>         Assert.assertTrue(uiStates.value.voucherViewModelState is VoucherDialogState.Default)
> ```

Shouldn't the `VoucherSubmissionError.OtherError` result in a error dialog state rather than the default state?

Also, we should probably await uiState updates here.



_Code quote:_
```Kotlin
Assert.assertTrue(uiStates.value.voucherViewModelState is VoucherDialogState.Default)
```


<!-- Sent from Reviewable.io -->

2023-11-27 09:56 UTC, Rawa requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: all files reviewed, 5 unresolved discussions (waiting on @sabercodic)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 63 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NkFBup87UgpZc7nrcMS:-NkFBup87UgpZc7nrcMT:b-lkf9ru) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c65bd7147e8f2000a8f9df390ba630d909153e74/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L63)):*
> ```Kotlin
>                 is VoucherSubmissionResult.Ok -> handleAddedTime(result.submission.timeAdded)
>                 is VoucherSubmissionResult.Error -> setError(result.error)
>                 else -> {
> ```

Generally I think we should avoid using `else` in when statements, it is better to be explicit. In this case if `voucherRedeemer` is `null` we will give `VoucherDialogState.Default` is this correct?


<!-- Sent from Reviewable.io -->

2023-11-27 10:41 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: 12 of 13 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 63 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NkFBup87UgpZc7nrcMS:-NkFMQRrEYcRWR7s1VEl:b-tmwc7h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c65bd7147e8f2000a8f9df390ba630d909153e74/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L63)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Generally I think we should avoid using `else` in when statements, it is better to be explicit. In this case if `voucherRedeemer` is `null` we will give `VoucherDialogState.Default` is this correct?
</blockquote></details>

This block of code did not change on this PR, I will refactor this part in different PR
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 52 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Nk-XVa94xLPPQicAT6q:-Nk0LA_24uLSVJZV7gBw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c65bd7147e8f2000a8f9df390ba630d909153e74/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L52)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Clean up
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 79 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Nk-idC8-OK4ql2Npu3l:-Nk0LLbH0u6cilLozrgq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c65bd7147e8f2000a8f9df390ba630d909153e74/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L79)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Missing newline
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 93 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Nk-eLrI6K5SP21q8Qcu:-Nk0LYPHDUuVXgTwxRTa:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c65bd7147e8f2000a8f9df390ba630d909153e74/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L93)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This can be skipped
</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt` line 104 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-Nk0E0bBAsEY_fR4w-5A:-NkFMI0N-8X7GI3WCfeK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c65bd7147e8f2000a8f9df390ba630d909153e74/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt#L104)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Shouldn't the `VoucherSubmissionError.OtherError` result in a error dialog state rather than the default state?

Also, we should probably await uiState updates here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-27 13:21 UTC, albin-mullvad approved these changes
Nice, gj! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r19, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-:-NkFwG6MBwr9tIHH3wGn:b-scwkdg)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)



<!-- Sent from Reviewable.io -->

2023-11-27 13:59 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 63 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NkFBup87UgpZc7nrcMS:-NkG3j4N9Tg1el578ejM:byb3yyq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c65bd7147e8f2000a8f9df390ba630d909153e74/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L63)):*
<details><summary><i>Previously, sabercodic wrote…</i></summary><blockquote>

This block of code did not change on this PR, I will refactor this part in different PR
</blockquote></details>

Ah, yes before it was `lateinit` so technically not nullable but the same type of error could happen. I'm fine with that we fix it in another PR, just make sure we don't miss to make a new ticket/PR about it


<!-- Sent from Reviewable.io -->

2023-11-27 14:10 UTC, albin-mullvad approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 63 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NkFBup87UgpZc7nrcMS:-NkG6DCE4E0UpLY0hltY:bjp3c89) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c65bd7147e8f2000a8f9df390ba630d909153e74/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L63)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Ah, yes before it was `lateinit` so technically not nullable but the same type of error could happen. I'm fine with that we fix it in another PR, just make sure we don't miss to make a new ticket/PR about it
</blockquote></details>

@sabercodic will you create and link an issue here?


<!-- Sent from Reviewable.io -->

2023-11-27 14:31 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt` line 63 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271#-NkFBup87UgpZc7nrcMS:-NkGBBU0CP5Zw9JHF35e:b-s4py9q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c65bd7147e8f2000a8f9df390ba630d909153e74/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt#L63)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

@sabercodic will you create and link an issue here?
</blockquote></details>

https://linear.app/mullvad/issue/DROID-541/code-clean-up-for-conditional-statements


<!-- Sent from Reviewable.io -->

2023-11-27 14:32 UTC, albin-mullvad approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-27 15:30 UTC, albin-mullvad approved these changes
> Reviewed 2 of 2 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5271)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-27 16:24 UTC, merged