Put app in blocked state on tunnel start if relay constraints cannot be satisfied
mullvad/mullvadvpn-app pull request #5300
Opened 2023-10-16 11:33 UTC by rablador

On tunnel start, if no valid relay can be selected app-side we let the packet tunnel take care of it instead. This will put the app in blocked state.

This PR takes care of issue the following issue as well:
https://linear.app/mullvad/issue/IOS-351/removing-relay-filters-does-not-exit-blocked-state

2023-10-16 11:57 UTC, pronebird requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/TunnelManager/StartTunnelOperation.swift` line 69 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300#-NgsJwxaDMturY-6zjry:-NgsJwxaDMturY-6zjrz:b5ilfzu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38931c591b271679701b9b12dc81fc822152685a/ios/MullvadVPN/TunnelManager/StartTunnelOperation.swift#L69)):*
> ```Swift
>             self.dispatchQueue.async {
>                 do {
>                     try self.startTunnel(tunnel: try result.get())
> ```

Nit: AFAIK one `try` in front is enough as it implies `try result.get()` too.
___
*[`ios/PacketTunnelCore/IPC/PacketTunnelOptions.swift` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300#-NgsKFma8darLqDiDsk8:-NgsKFma8darLqDiDsk9:bhjeg4p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38931c591b271679701b9b12dc81fc822152685a/ios/PacketTunnelCore/IPC/PacketTunnelOptions.swift#L43)):*
> ```Swift
>     }
> 
>     public mutating func setSelectedRelay(_ value: SelectedRelay?) throws {
> ```

`getSelectedRelay()` will probably break because it decodes `SelectedRelay.self`. Instead you could omit encoding `nil` values altogether. Do not pass `nil` to indicate absence of value, instead avoid passing `nil` altogether.


<!-- Sent from Reviewable.io -->

2023-10-16 12:28 UTC, pronebird requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 213 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300#-NgsNpPF5Nz2M4ZtkkbH:-NgsNpPF5Nz2M4ZtkkbI:b-yr0aa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38931c591b271679701b9b12dc81fc822152685a/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L213)):*
> ```Swift
>             dispatchQueue: internalQueue,
>             interactor: TunnelInteractorProxy(self),
>             selectedRelay: try? selectRelay(),
> ```

Prefer to keep the actual work inside of operation body (`main`) and not outside to avoid working with stale data. For example relay constraints could be changed before `StartTunnelOperation` begins execution.


<!-- Sent from Reviewable.io -->

2023-10-16 12:29 UTC, pronebird reviewed
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300)* status: all files reviewed, 3 unresolved discussions (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2023-10-16 13:10 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 213 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300#-NgsNpPF5Nz2M4ZtkkbH:-NgsapCZA5bJpz2MH1uQ:beu9rln) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38931c591b271679701b9b12dc81fc822152685a/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L213)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Prefer to keep the actual work inside of operation body (`main`) and not outside to avoid working with stale data. For example relay constraints could be changed before `StartTunnelOperation` begins execution.
</blockquote></details>

Sounds right, on it.
___
*[`ios/PacketTunnelCore/IPC/PacketTunnelOptions.swift` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300#-NgsKFma8darLqDiDsk8:-NgsXGJOCDmykyQzGkuX:byftu5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38931c591b271679701b9b12dc81fc822152685a/ios/PacketTunnelCore/IPC/PacketTunnelOptions.swift#L43)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`getSelectedRelay()` will probably break because it decodes `SelectedRelay.self`. Instead you could omit encoding `nil` values altogether. Do not pass `nil` to indicate absence of value, instead avoid passing `nil` altogether.
</blockquote></details>

Ah, yes, my bad. However, we do want to remove the value if there's no selected relay, right?


<!-- Sent from Reviewable.io -->

2023-10-16 13:55 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[`ios/PacketTunnelCore/IPC/PacketTunnelOptions.swift` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300#-NgsKFma8darLqDiDsk8:-NgslDQUAEKSPL5bYS6U:b-751sgp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38931c591b271679701b9b12dc81fc822152685a/ios/PacketTunnelCore/IPC/PacketTunnelOptions.swift#L43)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Ah, yes, my bad. However, we do want to remove the value if there's no selected relay, right?
</blockquote></details>

My bad again. I just realised we creatre new PacketTunnelOptions before this call, so simply setting nothing is the way to go.


<!-- Sent from Reviewable.io -->

2023-10-16 14:42 UTC, buggmagnet requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/TunnelManager/StartTunnelOperation.swift` line 76 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300#-Ngsvw5x9WLxfhfS37po:-Ngsvw5y5DIrBdzWbWD5:bsmt7qr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00ae7c231af62b87bdd7a96c603c1598404434c1/ios/MullvadVPN/TunnelManager/StartTunnelOperation.swift#L76)):*
> ```Swift
> 
>     private func startTunnel(tunnel: Tunnel) throws {
>         let selectedRelay = try? interactor.selectRelay()
> ```

Was there any reason to not use a more straightforward approach ?

```swift
    private func startTunnel(tunnel: Tunnel) throws {
        let selectedRelay = try interactor.selectRelay()
        var tunnelOptions = PacketTunnelOptions()

        try tunnelOptions.setSelectedRelay(selectedRelay)
        interactor.setTunnel(tunnel, shouldRefreshTunnelState: false)

        interactor.updateTunnelStatus { tunnelStatus in
            tunnelStatus = TunnelStatus()
            tunnelStatus.packetTunnelStatus.tunnelRelay = selectedRelay.packetTunnelRelay
            tunnelStatus.state = .connecting(selectedRelay.packetTunnelRelay)
        }

        try tunnel.start(options: tunnelOptions.rawOptions())
    }
```


<!-- Sent from Reviewable.io -->

2023-10-16 14:45 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/TunnelManager/StartTunnelOperation.swift` line 76 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300#-Ngsvw5x9WLxfhfS37po:-NgswcCeCG3Zqzm3Pdwu:b2kb567) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00ae7c231af62b87bdd7a96c603c1598404434c1/ios/MullvadVPN/TunnelManager/StartTunnelOperation.swift#L76)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Was there any reason to not use a more straightforward approach ?

```swift
    private func startTunnel(tunnel: Tunnel) throws {
        let selectedRelay = try interactor.selectRelay()
        var tunnelOptions = PacketTunnelOptions()

        try tunnelOptions.setSelectedRelay(selectedRelay)
        interactor.setTunnel(tunnel, shouldRefreshTunnelState: false)

        interactor.updateTunnelStatus { tunnelStatus in
            tunnelStatus = TunnelStatus()
            tunnelStatus.packetTunnelStatus.tunnelRelay = selectedRelay.packetTunnelRelay
            tunnelStatus.state = .connecting(selectedRelay.packetTunnelRelay)
        }

        try tunnel.start(options: tunnelOptions.rawOptions())
    }
```
</blockquote></details>

As far as I understand, if `interactor.selectRelay()` throws we won't set up a tunnel and start it, which means we cannot enter a blocked state.


<!-- Sent from Reviewable.io -->

2023-10-16 14:47 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/TunnelManager/StartTunnelOperation.swift` line 76 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300#-Ngsvw5x9WLxfhfS37po:-Ngsx24b2jf8Tf0dD6i2:bohenqc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00ae7c231af62b87bdd7a96c603c1598404434c1/ios/MullvadVPN/TunnelManager/StartTunnelOperation.swift#L76)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Yeah I quickly realized what I wrote wouldn't work, so I deleted the comment... Too late !
</blockquote></details>

It can never be unseen!


<!-- Sent from Reviewable.io -->

2023-10-16 14:49 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300#-:-NgsxXeaEwhugLdsq8P0:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-10-17 07:18 UTC, pronebird reviewed
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`ios/PacketTunnelCore/IPC/PacketTunnelOptions.swift` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300#-NgsKFma8darLqDiDsk8:-NgwUxSMAEgTcO3UrTaC:btqqu5l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/38931c591b271679701b9b12dc81fc822152685a/ios/PacketTunnelCore/IPC/PacketTunnelOptions.swift#L43)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

My bad again. I just realised we creatre new PacketTunnelOptions before this call, so simply setting nothing is the way to go.
</blockquote></details>

Correct.


<!-- Sent from Reviewable.io -->

2023-10-17 07:19 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300#-:-NgwV4oH8-nQzHjSptHc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-17 07:37 UTC, merged