Introduce observed state IOS-343
mullvad/mullvadvpn-app pull request #5302
Opened 2023-10-16 13:00 UTC by pronebird

As we discussed the other day, actor `State` contains class references and some internal data which should not be retained outside of actor nor of any interest to client code.

This PR adds `ObservedState` which is a value type with all private data stripped out. It's also implements `Equatable, Codable`. In essence it mirrors `State` stripping metadata that should not be shared with the client code.

Worth to note: this work is a stepping stone to sharing actor state over IPC because since iOS 16.5 Apple introduced timeout for `NE.startTunnel()` and therefore we will have to switch the tunnel into `connected` state immediately upon start to avoid being forcefully stopped by the system while in reconnection loop. 

On the tunnel manager side we'd have to work with actor state directly and therefore I think that `ObservedState` shared over IPC will supersede `PacketTunnelStatus` entirely, `SelectedRelay` will supersede `PacketTunnelRelay`.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302)

2023-10-16 14:43 UTC, rablador requested changes
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302)* status: all files reviewed, 1 unresolved discussion (waiting on @pronebird)

___
*[`ios/PacketTunnelCore/Actor/ObservedState+Extensions.swift` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302#-NgsrFnVBJwHiJkW6Jeq:-NgsrFnVBJwHiJkW6Jer:b49acod) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eeacdb412072deaa056674068adbb67d8b2cccb9/ios/PacketTunnelCore/Actor/ObservedState%2BExtensions.swift#L27)):*
> ```Swift
>                 status.isNetworkReachable = false
>             case .undetermined:
>                 // TODO: fix me
> ```

This should either be fixed or removed.


<!-- Sent from Reviewable.io -->

2023-10-17 07:15 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/PacketTunnelCore/Actor/ObservedState+Extensions.swift` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302#-NgsrFnVBJwHiJkW6Jeq:-NgwU7MX0XfB1AejUcT7:bnxkswf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eeacdb412072deaa056674068adbb67d8b2cccb9/ios/PacketTunnelCore/Actor/ObservedState%2BExtensions.swift#L27)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This should either be fixed or removed.
</blockquote></details>

If `PacketTunnelStatus` is indeed going away, then we don't have to take action immediately. Let's iterate.


<!-- Sent from Reviewable.io -->

2023-10-18 09:32 UTC, buggmagnet requested changes
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302)* status: all files reviewed, 4 unresolved discussions (waiting on @pronebird)

___
*[`ios/PacketTunnelCore/Actor/ObservedState+Extensions.swift` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302#-Nh0nPO9CfaQD4uyc5we:-Nh0nPOA7fHPRiV2tZHJ:b-8d6g7g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa30bbc04a6d105babdf144c9fa4dba6fd4ab15e/ios/PacketTunnelCore/Actor/ObservedState%2BExtensions.swift#L27)):*
> ```Swift
>                 status.isNetworkReachable = false
>             case .undetermined:
>                 // TODO: fix me
> ```

Should this TODO still be here ?
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+Extensions.swift` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302#-Nh0nmOd-oCu-f5f6Y6t:-Nh0nmOd-oCu-f5f6Y6u:buy08w8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa30bbc04a6d105babdf144c9fa4dba6fd4ab15e/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BExtensions.swift#L15)):*
> ```Swift
>     /// Note that the stream yields current value when created.
>     public var observedStates: AsyncStream<ObservedState> {
>         return AsyncStream { continuation in
> ```

`return` can be omitted here
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+Extensions.swift` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302#-Nh11__66fBCC0AbglHG:-Nh11__66fBCC0AbglHH:b9595j5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa30bbc04a6d105babdf144c9fa4dba6fd4ab15e/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BExtensions.swift#L15)):*
> ```Swift
>     /// Note that the stream yields current value when created.
>     public var observedStates: AsyncStream<ObservedState> {
>         return AsyncStream { continuation in
> ```

I don't know how I feel about this.
Technically there is a chance that `state` and `observedState` mismatch since the observed values are produced using an `AsyncStream` which means we cannot guarantee that `state` and `Observed` state are always matching.

Can we perhaps put an assert here to verify that they are matching ? Or maybe a warning log message ?
Maybe we could write a test that guarantees that we cannot have mismatching states, or that if we do, it's okay ?

I'm more erring on the side of caution here.
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+Extensions.swift` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302#-Nh0nxUGENQVN3sAc-pa:-Nh0nxUGENQVN3sAc-pb:bsy33tj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa30bbc04a6d105babdf144c9fa4dba6fd4ab15e/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BExtensions.swift#L16)):*
> ```Swift
>     public var observedStates: AsyncStream<ObservedState> {
>         return AsyncStream { continuation in
>             let cancellable = self.$observedState.sink { newState in
> ```

`self` should be removed 


<!-- Sent from Reviewable.io -->

2023-10-18 10:36 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCore/Actor/ObservedState+Extensions.swift` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302#-Nh0nPO9CfaQD4uyc5we:-Nh1H5N28Cc4K5idRd5X:b9pgb2p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa30bbc04a6d105babdf144c9fa4dba6fd4ab15e/ios/PacketTunnelCore/Actor/ObservedState%2BExtensions.swift#L27)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Should this TODO still be here ?
</blockquote></details>

Yes, what changed?
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+Extensions.swift` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302#-Nh11__66fBCC0AbglHG:-Nh1HiAs1Vc6VAvN30AW:b9awgpb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa30bbc04a6d105babdf144c9fa4dba6fd4ab15e/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BExtensions.swift#L15)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I don't know how I feel about this.
Technically there is a chance that `state` and `observedState` mismatch since the observed values are produced using an `AsyncStream` which means we cannot guarantee that `state` and `Observed` state are always matching.

Can we perhaps put an assert here to verify that they are matching ? Or maybe a warning log message ?
Maybe we could write a test that guarantees that we cannot have mismatching states, or that if we do, it's okay ?

I'm more erring on the side of caution here.
</blockquote></details>

How come? `ObservedState` is produced from `didSet` in `var state: State` and `@Published` property should immediately emit new value.
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+Extensions.swift` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302#-Nh0nmOd-oCu-f5f6Y6t:-Nh1Lp6Q5k5e5NQChAHp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa30bbc04a6d105babdf144c9fa4dba6fd4ab15e/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BExtensions.swift#L15)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

`return` can be omitted here
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+Extensions.swift` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302#-Nh0nxUGENQVN3sAc-pa:-Nh1Loc47NdCfm95_ES8:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa30bbc04a6d105babdf144c9fa4dba6fd4ab15e/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BExtensions.swift#L16)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

`self` should be removed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-18 11:13 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/PacketTunnelCore/Actor/ObservedState+Extensions.swift` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302#-Nh0nPO9CfaQD4uyc5we:-Nh1OZtVDlrx6VArSmkS:brlqaj7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c396de9356e4c8bfbd635daf8359b7e163c8bd48/ios/PacketTunnelCore/Actor/ObservedState%2BExtensions.swift#L27)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Yes, what changed?
</blockquote></details>

Just wanted to check, that's all 
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+Extensions.swift` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302#-Nh11__66fBCC0AbglHG:-Nh1TgW7E7jmEx9o6LxS:b-opk145) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c396de9356e4c8bfbd635daf8359b7e163c8bd48/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BExtensions.swift#L15)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

How come? `ObservedState` is produced from `didSet` in `var state: State` and `@Published` property should immediately emit new value.
</blockquote></details>

Imagine the following scenario:
```swift
for await newState in await actor.observedStates {
    // Do expensive and long computation here
}
```
While the long and expensive computation runs here, the `state` can change any number of times. 
Those changes won't be perceived before the long computation happened.

Since we don't coalesce the states in any way, that code depending on `observedStates` cannot assume safely that the observed state will be the actor's real state. 


<!-- Sent from Reviewable.io -->

2023-10-18 12:51 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+Extensions.swift` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302#-Nh11__66fBCC0AbglHG:-Nh1ehKpDAkQHM413nwO:b-rfmfpf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c396de9356e4c8bfbd635daf8359b7e163c8bd48/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BExtensions.swift#L15)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Imagine the following scenario:
```swift
for await newState in await actor.observedStates {
    // Do expensive and long computation here
}
```
While the long and expensive computation runs here, the `state` can change any number of times. 
Those changes won't be perceived before the long computation happened.

Since we don't coalesce the states in any way, that code depending on `observedStates` cannot assume safely that the observed state will be the actor's real state.
</blockquote></details>

This behavior matches what we had when accessing `var states: AsyncStream<State>` directly. 

In practice packet tunnel does not suspend within the iteration and the `state` does not change that frequently. 

If packet tunnel ever needs to suspend within iteration then I think it would be appropriate to consider one of the following: 

- Move long-running tasks from within the body of the loop into background task.
- Filter intermediate values by using`.bufferingNewest(1)` buffering strategy with `AsyncStream`.

The latest state can still be accessed directly by calling into `await actor.observedState` which I think `AppMessageHandler` will be returning in request to get tunnel status in the work that @rablador  is doing today.


<!-- Sent from Reviewable.io -->

2023-10-18 12:53 UTC, pronebird reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/PacketTunnelCore/Actor/ObservedState+Extensions.swift` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302#-Nh0nPO9CfaQD4uyc5we:-Nh1q3246Tq_GsPRIaEM:bj2t74m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c396de9356e4c8bfbd635daf8359b7e163c8bd48/ios/PacketTunnelCore/Actor/ObservedState%2BExtensions.swift#L27)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Just wanted to check, that's all
</blockquote></details>

I see. @rablador will be removing this in his work. I am keeping it as scoped as possible.


<!-- Sent from Reviewable.io -->

2023-10-18 14:39 UTC, buggmagnet approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+Extensions.swift` line 15 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5302#-Nh11__66fBCC0AbglHG:-Nh2DSzY7U2rvxFyl9ul:bqy67xj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c396de9356e4c8bfbd635daf8359b7e163c8bd48/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BExtensions.swift#L15)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This behavior matches what we had when accessing `var states: AsyncStream<State>` directly. 

In practice packet tunnel does not suspend within the iteration and the `state` does not change that frequently. 

If packet tunnel ever needs to suspend within iteration then I think it would be appropriate to consider one of the following: 

- Move long-running tasks from within the body of the loop into background task.
- Filter intermediate values by using`.bufferingNewest(1)` buffering strategy with `AsyncStream`.

The latest state can still be accessed directly by calling into `await actor.observedState` which I think `AppMessageHandler` will be returning in request to get tunnel status in the work that @rablador  is doing today.
</blockquote></details>

Fair enough


<!-- Sent from Reviewable.io -->

2023-10-18 14:49 UTC, merged