Fix InlinedApi lint issue
mullvad/mullvadvpn-app pull request #5314
Opened 2023-10-17 14:47 UTC by sabercodic

2023-11-06 12:16 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/EndToEndTest.kt` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314#-NiZYaQjCM41obu0liZZ:-NiZYaQjCM41obu0liZ_:bebe14g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0ab9a7d555b97edbb131c3cb26ee83a8d39a92ef/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/EndToEndTest.kt#L29)):*
> ```Kotlin
>     val permissionRule: GrantPermissionRule =
>         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
>             GrantPermissionRule.grant(Manifest.permission.READ_MEDIA_IMAGES)
> ```

This doesn't look correct since:
* We don't use storage for images.
* Any change like this would required some sort of data migration logic. Or is that not the case?



_Code quote:_
```Kotlin
READ_MEDIA_IMAGES
```


<!-- Sent from Reviewable.io -->

2023-11-06 12:41 UTC, albin-mullvad requested changes
Is it for 13+ or 14+? The Linear issue and PR says different things.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314#-:-NiZdUT2CSSjx_7ZfPQb:biy5z3e)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314#-NiZdLKc0n0pVKl1iSsA):*
Can you clarify what this fixes in the commit message?



_Code quote:_
```
Fix InlinedApi lint issue
```
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/EndToEndTest.kt` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314#-NiZYaQjCM41obu0liZZ:-NiZczGg7lZNB96mzrNV:bm3muvg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0ab9a7d555b97edbb131c3cb26ee83a8d39a92ef/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/EndToEndTest.kt#L29)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This doesn't look correct since:
* We don't use storage for images.
* Any change like this would required some sort of data migration logic. Or is that not the case?
</blockquote></details>

Sorry NVM, I confused this with also being used outside of the e2e/debug code. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 


<!-- Sent from Reviewable.io -->

2023-11-13 09:53 UTC, albin-mullvad reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314)* status: all files reviewed, 2 unresolved discussions (waiting on @sabercodic)



<!-- Sent from Reviewable.io -->

2023-11-13 10:55 UTC, sabercodic reviewed
13+

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314#-:-Nj7J1tH0JktzlSUb1-b:b2ngy04)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314#-NiZdLKc0n0pVKl1iSsA):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Also clarify the PR title :pray:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-13 11:15 UTC, albin-mullvad reviewed
I also updated the PR description since it was outdated

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314#-:-Nj7NvWjCusJLmId_efI:b-rv1rib)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)



<!-- Sent from Reviewable.io -->

2023-11-17 15:54 UTC, albin-mullvad reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314#-Nj74zr66NR7ulZ2dGd-:-NjSzA3ABrMnsWTDATlP:b-h5fo58) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Has this been verified to work on both newer and older API levels? Our tests run on API levels back to version 26.
</blockquote></details>

@sabercodic ping! Did you verify that this works as expected both on the range of supported API levels?

___


<!-- Sent from Reviewable.io -->

2023-11-17 16:47 UTC, albin-mullvad reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314#-Nj74zr66NR7ulZ2dGd-:-NjTA96W1u0Zxib_VABc:b-i7rlko) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

@sabercodic ping! Did you verify that this works as expected both on the range of supported API levels?
</blockquote></details>

^ ~~both~~

___


<!-- Sent from Reviewable.io -->

2023-12-13 12:00 UTC, albin-mullvad reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314)* status: all files reviewed, 1 unresolved discussion (waiting on @sabercodic)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314#-Nj74zr66NR7ulZ2dGd-:-NlY2-gS7jrzspyp7Mky:b4bw6fv) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

^ ~~both~~
</blockquote></details>

@sabercodic ping!

___


<!-- Sent from Reviewable.io -->

2023-12-13 12:10 UTC, sabercodic reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314#-Nj74zr66NR7ulZ2dGd-:-NkKrLYuCWIru1v-7nJ7:brauhi5) (no related file):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

@sabercodic ping!
</blockquote></details>

Yes I verified. Tested on different api levels from 26 to 34

___


<!-- Sent from Reviewable.io -->

2023-12-13 12:14 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314#-:-NlY5JcHCy4dsaIUiFkw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-12-13 12:58 UTC, merged