Add ability to select TCP/UDP for localhost SOCKS5 API access method
mullvad/mullvadvpn-app pull request #5320
Opened 2023-10-18 12:02 UTC by MarkusPettersson98

Previously, the API access method "SOCKS5 running on localhost" assumed that the transport protocol used for configuring the firewall should be TCP. This covers the majority of obfuscation protocols, but far from all. If we support both TCP and UDP we should cover ~99% of all use cases.

This PR allows outgoing API traffic to be _configured_ to be either TCP or UDP. For now, only the "SOCKS5 running on localhost" access method uses this configuration option.

2023-10-18 12:26 UTC, dlon requested changes
> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320)* status: 7 of 9 files reviewed, 5 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-api/src/proxy.rs` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1igsK76bVb75NSaQd:-Nh1igsK76bVb75NSaQe:bdsaaq6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b0bf1e84c48f8d319235dfbef9aff252db1e98c/mullvad-api/src/proxy.rs#L75)):*
> ```XML
>                     write!(
>                         f,
>                         "Socks5 {}/{} via localhost:{}",
> ```

We implement `Display` for `Endpoint`, so I think you can print `endpoint` directly.
___
*[`mullvad-cli/src/cmds/api_access.rs` line 333 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1hbBA1ovNOkWZf5DN:-Nh1hbBA1ovNOkWZf5DO:bx3zqga) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b0bf1e84c48f8d319235dfbef9aff252db1e98c/mullvad-cli/src/cmds/api_access.rs#L333)):*
> ```XML
>         /// protocols, such as ICMP. However, by supporting both TCP and UDP we
>         /// should cover ~99% of all use cases.
>         #[arg(default_value_t = TransportProtocol::Tcp)]
> ```

The "justification" for leaving out ICMP probably doesn't belong in user-facing documentation.

Also, *if* this should have a default value, it should probably not be a positional argument.
___
*[`mullvad-daemon/src/api.rs` line 260 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1hRc56h1YEU_gBdlt:-Nh1hRc56h1YEU_gBdlu:b-sax1hv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b0bf1e84c48f8d319235dfbef9aff252db1e98c/mullvad-daemon/src/api.rs#L260)):*
> ```XML
>                 // Wait for the firewall policy to be updated.
>                 let _ = result_rx.await;
>                 log::debug!("API endpoint: {}", endpoint);
> ```

Nit: `{endpoint}`
___
*[`mullvad-management-interface/proto/management_interface.proto` line 346 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1fO_H9PyETeQllfsw:-Nh1fO_I7V_0BZxTd-B3:bw0usy6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b0bf1e84c48f8d319235dfbef9aff252db1e98c/mullvad-management-interface/proto/management_interface.proto#L346)):*
> ```proto
>     uint32 port = 2;
>     uint32 local_port = 3;
>     TransportProtocol peer_transport_protocol = 4;
> ```

The transport protocol should probably be grouped with `ip` and `port`, since they're referring to the same endpoint.

I suggest making the fields adjacent to each other and renamed to `remote_ip`, `remote_port`, and `remote_transport`, or something along those lines.

Or perhaps we should add a new message equivalent to `talpid_types::net::Endpoint`.
___
*[`mullvad-types/src/access_method.rs` line 207 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1gyWs6OF3a2G9xc3j:-Nh1gyWs6OF3a2G9xc3k:bf20694) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b0bf1e84c48f8d319235dfbef9aff252db1e98c/mullvad-types/src/access_method.rs#L207)):*
> ```XML
>     pub peer: SocketAddr,
>     /// The transport protocol which should be allowed in the firewall.
>     pub peer_transport_protol: TransportProtocol,
> ```

Could `peer` just be an `Endpoint`?
___
*[`mullvad-types/src/access_method.rs` line 207 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1jHYt0K2VRfrrv0ax:-Nh1jHYt0K2VRfrrv0ay:b-e84qe0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b0bf1e84c48f8d319235dfbef9aff252db1e98c/mullvad-types/src/access_method.rs#L207)):*
> protol
Should be "protocol", but see above.


<!-- Sent from Reviewable.io -->

2023-10-18 12:44 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`mullvad-api/src/proxy.rs` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1igsK76bVb75NSaQd:-Nh1mcMS3RHzoDLj5hbJ:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b0bf1e84c48f8d319235dfbef9aff252db1e98c/mullvad-api/src/proxy.rs#L75)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We implement `Display` for `Endpoint`, so I think you can print `endpoint` directly.
</blockquote></details>

done
___
*[`mullvad-cli/src/cmds/api_access.rs` line 333 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1hbBA1ovNOkWZf5DN:-Nh1mdOr3vMVuvFZfBzJ:b-ua0pwi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b0bf1e84c48f8d319235dfbef9aff252db1e98c/mullvad-cli/src/cmds/api_access.rs#L333)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The "justification" for leaving out ICMP probably doesn't belong in user-facing documentation.

Also, *if* this should have a default value, it should probably not be a positional argument.
</blockquote></details>

done
Agree, it has since been removed.
___
*[`mullvad-daemon/src/api.rs` line 260 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1hRc56h1YEU_gBdlt:-Nh1n2hhB7NcvmE8E83u:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b0bf1e84c48f8d319235dfbef9aff252db1e98c/mullvad-daemon/src/api.rs#L260)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: `{endpoint}`
</blockquote></details>

done
___
*[`mullvad-management-interface/proto/management_interface.proto` line 346 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1fO_H9PyETeQllfsw:-Nh1n4A43IjLjKHaz4sx:bdj4tcd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b0bf1e84c48f8d319235dfbef9aff252db1e98c/mullvad-management-interface/proto/management_interface.proto#L346)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The transport protocol should probably be grouped with `ip` and `port`, since they're referring to the same endpoint.

I suggest making the fields adjacent to each other and renamed to `remote_ip`, `remote_port`, and `remote_transport`, or something along those lines.

Or perhaps we should add a new message equivalent to `talpid_types::net::Endpoint`.
</blockquote></details>

Good point!

I assume that the message
```protobuf
message Endpoint {
  string address = 1;
  TransportProtocol protocol = 2;
}
```
is just that, but we could do better by not having `address` be a `string`, but instead something equivalent to `std::net::SocketAddr`. Let's think about that, but for now I'm moving + renaming the fields in the `Socks5Local` message.
___
*[`mullvad-types/src/access_method.rs` line 207 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1jHYt0K2VRfrrv0ax:-Nh1o0qa5THK-SmqMRxP:bmorqta) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b0bf1e84c48f8d319235dfbef9aff252db1e98c/mullvad-types/src/access_method.rs#L207)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

> protol
Should be "protocol", but see above.
</blockquote></details>

done
:sweat_smile: 
___
*[`mullvad-types/src/access_method.rs` line 207 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1gyWs6OF3a2G9xc3j:-Nh1o31H2miWgjcMDY4A:b-xovkfe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b0bf1e84c48f8d319235dfbef9aff252db1e98c/mullvad-types/src/access_method.rs#L207)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could `peer` just be an `Endpoint`?
</blockquote></details>

Yes, I think that is more appropriate


<!-- Sent from Reviewable.io -->

2023-10-18 13:07 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`mullvad-types/src/access_method.rs` line 207 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1gyWs6OF3a2G9xc3j:-Nh1tFgr2bMjYmhVDiZO:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b0bf1e84c48f8d319235dfbef9aff252db1e98c/mullvad-types/src/access_method.rs#L207)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Yes, I think that is more appropriate
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-18 13:07 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`mullvad-types/src/access_method.rs` line 207 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1jHYt0K2VRfrrv0ax:-Nh1tSlZ7_0BnkZFQ4yV:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b0bf1e84c48f8d319235dfbef9aff252db1e98c/mullvad-types/src/access_method.rs#L207)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

done
:sweat_smile:
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-18 13:10 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`mullvad-management-interface/proto/management_interface.proto` line 346 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1fO_H9PyETeQllfsw:-Nh1uBWf5pu-9u02IQFq:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b0bf1e84c48f8d319235dfbef9aff252db1e98c/mullvad-management-interface/proto/management_interface.proto#L346)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Good point!

I assume that the message
```protobuf
message Endpoint {
  string address = 1;
  TransportProtocol protocol = 2;
}
```
is just that, but we could do better by not having `address` be a `string`, but instead something equivalent to `std::net::SocketAddr`. Let's think about that, but for now I'm moving + renaming the fields in the `Socks5Local` message.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-18 15:05 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-cli/src/cmds/api_access.rs` line 128 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1x-oS4OcaQX4PtHdf:-Nh2GplU4xRAZ8itGTGc:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb393e020ab4c24821ad5f9757b9e29d794e56a2/mullvad-cli/src/cmds/api_access.rs#L128)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could we group `remote_ip`, `remote_port`, and `remote_transport` here as well?
</blockquote></details>

done
___
*[`mullvad-cli/src/cmds/api_access.rs` line 332 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1xPk6-5fB4mvwQ0NK:-Nh2GrEZ9o6hx2fKVMJC:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb393e020ab4c24821ad5f9757b9e29d794e56a2/mullvad-cli/src/cmds/api_access.rs#L332)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`remote_transport` is less ambiguous.
</blockquote></details>

done
___
*[`mullvad-types/src/access_method.rs` line 277 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1xnd1EL44SiUJkRQu:-Nh2IkR997f4ERIWTEF0:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb393e020ab4c24821ad5f9757b9e29d794e56a2/mullvad-types/src/access_method.rs#L277)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could we make this the third argument? I'd also suggest renaming those three parameters to: `remote_ip`, `remote_port`, and `remote_transport`.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-10-18 15:07 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-types/src/access_method.rs` line 258 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-Nh1zW_x0Ma26BfUCE75:-Nh2Jpru4hBE4_n_THro:b-skwaev) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb393e020ab4c24821ad5f9757b9e29d794e56a2/mullvad-types/src/access_method.rs#L258)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do we even need this? I didn't see any references to it. Maybe `from_args` should replace `new` as the only constructor here.
</blockquote></details>

That was a strange side-step from the style of the other `CustomAccessMethod`s constructors. `Socks5Local` now has one fallible constructor (`from_args`) and one infallible constructor (`new`).


<!-- Sent from Reviewable.io -->

2023-10-19 20:51 UTC, dlon approved these changes
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-26 14:51 UTC, dlon reviewed
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320)* status: all files reviewed, 4 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`talpid-core/src/firewall/macos.rs` line 294 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-NhgNgES-FDVL5YPzoIl:-NhgNgES-FDVL5YPzoIm:bfa8cjw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79c4f3b5b232f5c2b3d9e173133f7cdf456a74fd/talpid-core/src/firewall/macos.rs#L294)):*
> ```XML
>     fn get_allowed_endpoint_rule(
>         &self,
>         allowed_endpoint: AllowedEndpoint,
> ```

I think you can avoid `.clone()` by borrowing here.
___
*[`talpid-types/src/net/mod.rs` line 290 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-NhgNxG068Ht3chetYPV:-NhgNxG068Ht3chetYPW:b-p1hbmk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79c4f3b5b232f5c2b3d9e173133f7cdf456a74fd/talpid-types/src/net/mod.rs#L290)):*
> ```XML
>         Self {
>             endpoint,
>             clients: Vec::new(),
> ```

Perhaps just add `derive(Default)` on `AllowedEndpoint` and get rid of the conditional compilation here.

Also, shouldn't `clients` always be provided as an argument here?
___
*[`talpid-types/src/net/mod.rs` line 332 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-NhgQwBq0hUPgjPzYDbT:-NhgQwBr8ZLu5yHHnnd1:b90f0um) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79c4f3b5b232f5c2b3d9e173133f7cdf456a74fd/talpid-types/src/net/mod.rs#L332)):*
> ```XML
> #[cfg(windows)]
> #[derive(Debug, Clone, Eq, PartialEq)]
> pub struct AllowedClients(std::sync::Arc<[PathBuf]>);
> ```

Is there any reason to wrap it in an arc?
___
*[`talpid-types/src/net/mod.rs` line 383 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-NhgOb_342b_sVTuZ5nq:-NhgOb_342b_sVTuZ5nr:bnp385g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79c4f3b5b232f5c2b3d9e173133f7cdf456a74fd/talpid-types/src/net/mod.rs#L383)):*
> ```XML
>     /// The most secure client(s) is our own, which runs as root.
>     fn default() -> Self {
>         AllowedClients::Root
> ```

You can use the `#[default]` attribute on the enum variant with `#[derive(Default)]`.


<!-- Sent from Reviewable.io -->

2023-10-26 14:51 UTC, dlon reviewed
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320)* status: all files reviewed, 4 unresolved discussions (waiting on @MarkusPettersson98)



<!-- Sent from Reviewable.io -->

2023-11-07 15:12 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`talpid-types/src/net/mod.rs` line 383 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-NhgOb_342b_sVTuZ5nq:-NieKT3XBEoG0WrhHPXy:bfjgmen) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79c4f3b5b232f5c2b3d9e173133f7cdf456a74fd/talpid-types/src/net/mod.rs#L383)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

done
</blockquote></details>

Ultimately ended up scraping `Default` for `AllowedClients` :smile: 


<!-- Sent from Reviewable.io -->

2023-11-07 15:17 UTC, dlon approved these changes
> Reviewed 1 of 2 files at r8, 7 of 11 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-api/src/proxy.rs` line 163 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-NieM3g26k_n-fLKg_vE:-NieM3g26k_n-fLKg_vF:b-myscsm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/737040723c74c660c8f239c97d48d60a8535cb21/mullvad-api/src/proxy.rs#L163)):*
> ```XML
>             }
>             ApiConnectionMode::Direct | ApiConnectionMode::Proxied(_) => {
>                 let daemon_exe = std::env::current_exe().expect("failed to obtain executable path");
> ```

It would be nice if we didn't have to duplicate this.


<!-- Sent from Reviewable.io -->

2023-11-07 18:40 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-api/src/proxy.rs` line 163 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320#-NieM3g26k_n-fLKg_vE:-Nif464G6on36WISsV2U:b-kc25o5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/737040723c74c660c8f239c97d48d60a8535cb21/mullvad-api/src/proxy.rs#L163)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It would be nice if we didn't have to duplicate this.
</blockquote></details>

Yes, it would indeed. I suspect that this will be natural to include in upcoming refactoring done in https://github.com/mullvad/mullvadvpn-app/pull/5370, so I will postpone this change till that PR.


<!-- Sent from Reviewable.io -->

2023-11-07 19:15 UTC, merged