Improve geoip check
mullvad/mullvadvpn-app pull request #5339
Opened 2023-10-20 23:11 UTC by dlon

2023-10-21 10:58 UTC, faern commented
Can this PR get a more detailed description please?

2023-10-23 07:53 UTC, MarkusPettersson98 requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5339#-:-NhQUwVu4S5JjLclqmur:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`mullvad-api/src/rest.rs` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5339#-NhQVmsK3cUBYtCF1k5R:-NhQVmsK3cUBYtCF1k5S:bbxc1yr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29270b9d4d76c6430873fea3d8b07ad3474dbd8e/mullvad-api/src/rest.rs#L22)):*
> ```XML
> use mullvad_types::account::AccountToken;
> use std::{
>     error::Error as StdError,
> ```

This allows us to remove the `use std::error::Error` in `map_aborted`:

https://github.com/mullvad/mullvadvpn-app/blob/29270b9d4d76c6430873fea3d8b07ad3474dbd8e/mullvad-api/src/rest.rs#L111-L114


<!-- Sent from Reviewable.io -->

2023-10-23 08:43 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5339)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`mullvad-api/src/rest.rs` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5339#-NhQVmsK3cUBYtCF1k5R:-NhQgxTN0EAxrChx_9P2:b9xenlk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29270b9d4d76c6430873fea3d8b07ad3474dbd8e/mullvad-api/src/rest.rs#L22)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This allows us to remove the `use std::error::Error` in `map_aborted`:

https://github.com/mullvad/mullvadvpn-app/blob/29270b9d4d76c6430873fea3d8b07ad3474dbd8e/mullvad-api/src/rest.rs#L111-L114
</blockquote></details>

Ah. Good catch.


<!-- Sent from Reviewable.io -->

2023-10-23 11:08 UTC, MarkusPettersson98 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5339#-:-NhRDH8gCAIP86hHKL_y:bnfp4nl)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2023-10-23 16:49 UTC, merged