Add refresh AccountCache from VoucherRedeemer
mullvad/mullvadvpn-app pull request #5345
Opened 2023-10-23 13:13 UTC by Rawa

This PR includes a temporary workaround to allow VoucherRedeemer to update the AccountCache (expiryTime) once the user has redeemed a voucher through the app.

2023-10-26 08:36 UTC, Pururun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

I think we should wait with merging until Albin is back though.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5345#-:-Nhf7-Nk9zF93H5LYk36:bd2ylb5)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-08 09:29 UTC, albin-mullvad requested changes
Let's go ahead with this workaround :thumbsup: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5345#-:-NiiFeaHCWQ7iTt2Rcfp:b-p8suw9)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/VoucherRedeemer.kt` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5345#-NiiFNetCwhGFN3Gcnwo:-NiiFNetCwhGFN3Gcnwp:bpkpmtp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae55543a70aad3e496ad299bf5978310ef474b9/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/VoucherRedeemer.kt#L43)):*
> ```Kotlin
>                     if (result is VoucherSubmissionResult.Ok) {
>                         val accountExpiry =
>                             AccountExpiry.Available(result.submission.newExpiry.parseAsDateTime()!!)
> ```

Is the intention to crash if the date parsing fails? Would probably be nice to avoid crashing the service if possible, since that would also kill the tunnel.



_Code quote:_
```Kotlin
parseAsDateTime()!!
```


<!-- Sent from Reviewable.io -->

2023-11-10 07:42 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5345)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/VoucherRedeemer.kt` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5345#-NiiFNetCwhGFN3Gcnwo:-Nis9rk5EmSA6qrGq8le:bezd9ny) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae55543a70aad3e496ad299bf5978310ef474b9/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/VoucherRedeemer.kt#L43)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is the intention to crash if the date parsing fails? Would probably be nice to avoid crashing the service if possible, since that would also kill the tunnel.
</blockquote></details>

I see what you mean with crashing the service, but at the same time if we get something that is not able to be parsed to a DateTime we really want it to crash because the interface between service and daemon is faulty. If we just fail silently with some log it might be that we miss it and let it sneak out as a bug.


<!-- Sent from Reviewable.io -->

2023-11-15 12:09 UTC, albin-mullvad reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5345)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/VoucherRedeemer.kt` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5345#-NiiFNetCwhGFN3Gcnwo:-NjHsRit806wNw6Wdf5N:b3pageq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bae55543a70aad3e496ad299bf5978310ef474b9/android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/VoucherRedeemer.kt#L43)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I see what you mean with crashing the service, but at the same time if we get something that is not able to be parsed to a DateTime we really want it to crash because the interface between service and daemon is faulty. If we just fail silently with some log it might be that we miss it and let it sneak out as a bug.
</blockquote></details>

As we discussed offline, using `!!` comes with a certain risk so we'll create a separate issue to look into this further. @Pururun let's add null safety to this PR.

@Rawa  please create an issue and share here 🙏


<!-- Sent from Reviewable.io -->

2023-11-15 13:40 UTC, Pururun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5345#-:-NjICUXzAzvrTIH-a2cy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-15 13:43 UTC, merged