Add packer scripts to create VMs and install Xcode on them.
mullvad/mullvadvpn-app pull request #5359
Opened 2023-10-25 09:35 UTC by buggmagnet

This PR adds packer scripts that can create a VM and install Xcode on it.

2023-10-26 11:48 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359)* status: 1 of 13 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`ci/ios/create-vm/scripts/run-xcode-first-launch.sh` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#-NhfGaeR5Z_lSeUPBVL9:-NhfnsoD5TefOet7NlgG:b-8katgk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22a0cdb3ccf34d03e3c7197ec075b6c6b6c71219/ci/ios/create-vm/scripts/run-xcode-first-launch.sh#L13)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Do we need this for a build? I don't believe so.
</blockquote></details>

This was discussed offline, the conclusion was we will try to build without it, and if it works, we will delete this line.
___
*[`ci/ios/create-vm/vm_shared_folder/Xcode_15.0.1_REPLACE_ME_WITH_A_REAL_XCODE.xip` line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#-NhfGeVn92gtEQuYJOru:-Nhfo44DEdphYcBjl3II:b-yq2skt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22a0cdb3ccf34d03e3c7197ec075b6c6b6c71219/ci/ios/create-vm/vm_shared_folder/Xcode_15.0.1_REPLACE_ME_WITH_A_REAL_XCODE.xip#L)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I don't think we need this file here either.
</blockquote></details>

We will remove this file as it's already explained in the `README.md` file


<!-- Sent from Reviewable.io -->

2023-10-26 14:08 UTC, pinkisemils requested changes
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359)* status: 2 of 13 files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

___
*[`ci/ios/create-vm/install-xcode.pkr.hcl` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#-Nhg-SDk48Yl2PQfTnh4:-Nhg-SDk48Yl2PQfTnh5:buswxwu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22a0cdb3ccf34d03e3c7197ec075b6c6b6c71219/ci/ios/create-vm/install-xcode.pkr.hcl#L0)):*
The file name is a bit misleading, this one installs far more than just xcode.


<!-- Sent from Reviewable.io -->

2023-10-26 14:53 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359)* status: 2 of 13 files reviewed, 3 unresolved discussions (waiting on @pinkisemils)

___
*[`ci/ios/create-vm/install-xcode.pkr.hcl` line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#-Nhg-SDk48Yl2PQfTnh4:-NhgTOBKCTWbXNC2f3DP:b-215s7h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22a0cdb3ccf34d03e3c7197ec075b6c6b6c71219/ci/ios/create-vm/install-xcode.pkr.hcl#L)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The file name is a bit misleading, this one installs far more than just xcode.
</blockquote></details>

That's true. What do you think of `install-xcode-and-dependencies.pkr.hcl` ?


<!-- Sent from Reviewable.io -->

2023-10-26 15:10 UTC, pinkisemils requested changes
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359)* status: 3 of 13 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ci/ios/create-vm/install-xcode.pkr.hcl` line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#-Nhg-SDk48Yl2PQfTnh4:-NhgX8CiCXbjXksA9HhX:b-xxna5k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22a0cdb3ccf34d03e3c7197ec075b6c6b6c71219/ci/ios/create-vm/install-xcode.pkr.hcl#L)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

That's true. What do you think of `install-xcode-and-dependencies.pkr.hcl` ?
</blockquote></details>

I'd say `install-build-dependencies.pkr.hcl` would work best.


<!-- Sent from Reviewable.io -->

2023-10-26 15:41 UTC, pinkisemils submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359)* status: 3 of 13 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ci/ios/create-vm/README.md` line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#-NhgdF3i4XA8n33f4Fh3:-NhgdF3i4XA8n33f4Fh4:b-qsh42q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22a0cdb3ccf34d03e3c7197ec075b6c6b6c71219/ci/ios/create-vm/README.md#L40)):*
> ```Markdown
> 
> # Sanity checks before running packer
> It is a good idea to keep logs, the `logs` folder is provided to that effect.
> ```

This also needs an entry about having to run `packer init` against `install-vanilla-ventura.pkr.hcl` at least.


<!-- Sent from Reviewable.io -->

2023-10-28 11:17 UTC, MrChocolatine commented on ci/ios/create-vm/README.md
The headings used for this file are inconsistent.

- You start with a heading level 3 `###`
- next one is a level 2 `##`
- then all the following headings are level 1 `#`

Also, a `> [!IMPORTANT]` bloc seems incorrectly formatted, I included a suggestion below.

I believe you may want something like:

```markdown
# Creating new macOS VMs to build MullvadVPN iOS in a CI environment

...

## Prerequisites

...

### VM requirements

...

### How to install Tart

...

### How to install Packer

...

### How to install shellcheck

> [!IMPORTANT]
> ### Prerequisite setup before running packer
> - ... 

### Sanity checks before running packer

...

## Create the VM image via Packer

...

## Install Xcode on the VM image via Packer
```

2023-10-28 11:39 UTC, MrChocolatine commented on ci/ios/create-vm/scripts/install-brew-dependencies.sh
> +if which brew
I would recommend a safer alternative to check if a program is in the user's `PATH`:

```bash
if command -v brew &>/dev/null; then
    # `brew` is in PATH
fi
```

https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script/677212#677212

2023-10-28 11:56 UTC, MrChocolatine commented on ci/ios/create-vm/scripts/install-brew.sh
> +    echo >&1 "brew is already installed, nothing to do here"
Are all these `echo >&1 ...` necessary, since `stdout` is already the default? (=> `&1`)

2023-10-28 12:00 UTC, MrChocolatine commented on ci/ios/create-vm/README.md
> +The logs will be overwritten with each packer command you issue.
```suggestion
> [!NOTE] 
> The logs will be overwritten with each packer command you issue.
```

2023-10-28 12:01 UTC, MrChocolatine commented on ci/ios/create-vm/README.md
> +- Edit the variables named `xcode_version` and `xcode_xip_name`
```suggestion
> [!IMPORTANT] 
> ### Prerequisite setup before running packer
> - Get a copy of the Xcode version you want to install on the VM in a xip format
> - Copy that file into the folder named `vm_shared_folder`
> - Open the file named `variables.pkrvars.hcl`
> - Edit the variables named `xcode_version` and `xcode_xip_name`
```

2023-10-30 09:04 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359)* status: 1 of 13 files reviewed, 7 unresolved discussions (waiting on @MrChocolatine and @pinkisemils)

___
*[`ci/ios/create-vm/README.md` line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#-NhgdF3i4XA8n33f4Fh3:-Nhzmzxv8i7XaXAb82aV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22a0cdb3ccf34d03e3c7197ec075b6c6b6c71219/ci/ios/create-vm/README.md#L40)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This also needs an entry about having to run `packer init` against `install-vanilla-ventura.pkr.hcl` at least.
</blockquote></details>

Done.
___
*[`ci/ios/create-vm/README.md` line 0 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#gh-1375236520:-NhzeoDgCX7frkDFbEZ7:b8s0s2k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ffb487ce6505167d6457ff700fc7f8541681347/ci/ios/create-vm/README.md#L0)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

The headings used for this file are inconsistent:
- You start with a heading level 3 `###`
- next one is a level 2 `##`
- then all the following headings are level 1 `#`

You may want something like:

```markdown
# Creating new macOS VMs to build MullvadVPN iOS in a CI environment

...

## Prerequisites

...

### VM requirements

...

### How to install Tart

...

### How to install Packer

...

### How to install shellcheck

### Prerequisite setup before running packer

> [!IMPORTANT]
> - ... 

### Sanity checks before running packer

...

## Create the VM image via Packer

...

## Install Xcode on the VM image via Packer
```
</blockquote></details>

@MrChocolatine looks like you found out I am not good at writing markdown files :see_no_evil: :laughing: 
Thanks for the suggestion, I will rework those headings
___
*[`ci/ios/create-vm/README.md` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#gh-1375241990:-Nhzg8Se9XMT-fqlskSM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ffb487ce6505167d6457ff700fc7f8541681347/ci/ios/create-vm/README.md#L28)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

```suggestion
### Prerequisite setup before running packer

> [!IMPORTANT] 
> - Get a copy of the Xcode version you want to install on the VM in a xip format
> - Copy that file into the folder named `vm_shared_folder`
> - Open the file named `variables.pkrvars.hcl`
> - Edit the variables named `xcode_version` and `xcode_xip_name`
```
</blockquote></details>

Done.
___
*[`ci/ios/create-vm/README.md` line 46 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#gh-1375241899:-NhzgKSI1XZcByKnfti9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ffb487ce6505167d6457ff700fc7f8541681347/ci/ios/create-vm/README.md#L46)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

```suggestion
> [!NOTE] 
> The logs will be overwritten with each packer command you issue.
```
</blockquote></details>

Done.
___
*[`ci/ios/create-vm/scripts/install-brew.sh` line 7 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#gh-1375241367:-NhzgLawBrgi6Ry-GY2d:baf555m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ffb487ce6505167d6457ff700fc7f8541681347/ci/ios/create-vm/scripts/install-brew.sh#L7)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

Are all these `echo >&1 ...` necessary, since `stdout` is already the default? (=> `&1`)
</blockquote></details>


I couldn't find documentation anywhere on how to have `echo` commands output back to the terminal that ran the `packer` command, so I randomly tried a test script that did the equivalent of `echo "hello" >&1`

That issued on stdout in the terminal I ran the packer command.
I also tried `echo "hello" >&2` which also did print the command back to my terminal, but in red color. I assume it was going to `stderr` too, although I haven't verified that.
___
*[`ci/ios/create-vm/scripts/install-brew-dependencies.sh` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#gh-1375239208:-NhzmGw58-vpQ7RdloAF:bqx7dl3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7ffb487ce6505167d6457ff700fc7f8541681347/ci/ios/create-vm/scripts/install-brew-dependencies.sh#L8)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

I would recommend a safer alternative to check if a program is in the user's `PATH`:

```bash
if command -v brew &>/dev/null; then
    # `brew` is in PATH
fi
```

https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script/677212#677212
</blockquote></details>

TIL about `command -v` 
cool trick, thanks !
___
*[`ci/ios/create-vm/install-xcode.pkr.hcl` line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#-Nhg-SDk48Yl2PQfTnh4:-Nhzeitr-4SH-G-nONUo:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/22a0cdb3ccf34d03e3c7197ec075b6c6b6c71219/ci/ios/create-vm/install-xcode.pkr.hcl#L)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I'd say `install-build-dependencies.pkr.hcl` would work best.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-30 10:22 UTC, MrChocolatine commented
@buggmagnet 

> I also tried echo "hello" >&2 which also did print the command back to my terminal, but in red color. I assume it was going to stderr too, although I haven't verified that.

Indeed

2023-10-30 10:24 UTC, MrChocolatine commented
@buggmagnet 

> I also tried echo "hello" >&2 which also did print the command back to my terminal, but in red color. I assume it was going to stderr too, although I haven't verified that.

Indeed, `0` is for `stdin`, `1` for `stdout` and `2` for `stderr`.

2024-08-05 08:48 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359)* status: 0 of 14 files reviewed, 8 unresolved discussions (waiting on @MrChocolatine and @pinkisemils)

___
*[`ci/ios/create-vm/install-vanilla-ventura.pkr.hcl` line 63 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#-O3WiRyCDtb52L84M9kd:-O3WiRyCDtb52L84M9ke:b-vzh5q1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/639cfb1de9d116415e56b98534e7c1dfd0d90201/ci/ios/create-vm/install-vanilla-ventura.pkr.hcl#L63)):*
> ```HCL
>     "<wait10s><leftShiftOn><tab><leftShiftOff><spacebar>",
>     # Enable Voice Over
>     "<wait10s><leftAltOn><f5><leftAltOff><wait5s>v",
> ```

Looks like an extra "v" character snuck in there, we should probably remove this.


<!-- Sent from Reviewable.io -->

2024-08-07 08:42 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359)* status: 0 of 14 files reviewed, 9 unresolved discussions (waiting on @MrChocolatine and @pinkisemils)

___
*[`ci/ios/create-vm/install-build-dependencies.pkr.hcl` line 105 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#-O3g-BbS1_6nMUS8ct4n:-O3g-BbS1_6nMUS8ct4o:b-3rt81s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/639cfb1de9d116415e56b98534e7c1dfd0d90201/ci/ios/create-vm/install-build-dependencies.pkr.hcl#L105)):*
> ```HCL
> 
>   // Add Apple root certs
>   privisioner "shell" {
> ```

`provisioner` instead of `privisioner`


<!-- Sent from Reviewable.io -->

2024-08-07 11:14 UTC, rablador reviewed
> Reviewed 3 of 13 files at r1, 1 of 1 files at r2, 5 of 7 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359)* status: all files reviewed, 7 unresolved discussions (waiting on @MrChocolatine and @pinkisemils)

___
*[`ci/ios/create-vm/install-vanilla-ventura.pkr.hcl` line 63 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#-O3WiRyCDtb52L84M9kd:-O3gSKA85QUZ0TulZR4X:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/639cfb1de9d116415e56b98534e7c1dfd0d90201/ci/ios/create-vm/install-vanilla-ventura.pkr.hcl#L63)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Looks like an extra "v" character snuck in there, we should probably remove this.
</blockquote></details>

Done.
___
*[`ci/ios/create-vm/install-build-dependencies.pkr.hcl` line 105 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#-O3g-BbS1_6nMUS8ct4n:-O3gSFrPEo5-0KZ2SFJ0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/639cfb1de9d116415e56b98534e7c1dfd0d90201/ci/ios/create-vm/install-build-dependencies.pkr.hcl#L105)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

`provisioner` instead of `privisioner`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-07 14:18 UTC, buggmagnet reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359#-:-O3hC6QdD4gou4ed52nR:bnfp4nl)* status: 8 of 14 files reviewed, 7 unresolved discussions (waiting on @MrChocolatine, @pinkisemils, and @rablador)



<!-- Sent from Reviewable.io -->

2024-08-09 12:17 UTC, rablador approved these changes
> Reviewed 5 of 5 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359)* status: all files reviewed, 7 unresolved discussions (waiting on @MrChocolatine and @pinkisemils)



<!-- Sent from Reviewable.io -->

2024-08-09 13:58 UTC, merged