Migrate settings to Version3 and introduce incremental migration scheme.
mullvad/mullvadvpn-app pull request #5367
Opened 2023-10-26 09:13 UTC by buggmagnet

This PR introduces a version 3 of the settings that includes UDP over TCP obfuscation settings.
This PR also introduces back the migration scheme.
I took a couple of decisions in this PR that we already discussed beforehand, but for the sake of documentation
- We do not handle a special migration from V1 to V2 anymore, because there's a very low chance we still have users running on settings V1.
- V1 to V2 upgrade is just taking the compatible settings forward (such as DNS options and Relay Filter)

# Open question
How do we want to handle version downgrade ? That's mostly a question for ourselves since users cannot downgrade the app. 
I decided to go for nothing to migrate, but we can also trigger a reset of the settings. I think it wouldn't be convenient for us though.

This PR is mostly done, but there is some refactoring I want to do in `MigrationManager` to avoid reading the settings twice for example.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367)

2023-10-26 12:13 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367)* status: 0 of 15 files reviewed, 1 unresolved discussion

___
*[`ios/MullvadSettings/TunnelSettings.swift` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhfsoNP1qPJfEIPtL2_:-NhfsoNP1qPJfEIPtL2a:bh1wcud) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6c7c2999a8431e68df4044f951ca9d9bba3cf8dd/ios/MullvadSettings/TunnelSettings.swift#L16)):*
> ```Swift
> 
> /// Protocol all TunnelSettings must adhere to, for upgrade purposes.
> public protocol TunnelSettings: Codable {
> ```

This is intentionally close to the protocol defined in `Migration.swift` 
At the moment, we don't need a migration type that involves doing API calls.
If we ever do, we can make `TunnelSettings` adhere to that protocol, or create migration classes that implement the protocol with minimal amount of changes. 


<!-- Sent from Reviewable.io -->

2023-10-26 13:32 UTC, rablador requested changes
> Reviewed 14 of 14 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadSettings/MigrationManager.swift` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhfrMyA3eAcw1LZCNd9:-NhfrMyA3eAcw1LZCNdA:bo29csg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a379f24bce4661a1dc84bc403345e7e17abf1d57/ios/MullvadSettings/MigrationManager.swift#L89)):*
> ```Swift
>         }
> 
>         var versionTypeCopy = savedSchema
> ```

Why all this variable juggling?
___
*[`ios/MullvadSettings/SettingsManager.swift` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-Nhg-TBQ24WSP9ziAXrD:-Nhg-TBQ24WSP9ziAXrE:bbkytcv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a379f24bce4661a1dc84bc403345e7e17abf1d57/ios/MullvadSettings/SettingsManager.swift#L36)):*
> ```Swift
> 
>     #else
>     public static let store: SettingsStore = KeychainSettingsStore(
> ```

Can't we just change this to a var and call it a day?
___
*[`ios/MullvadSettings/TunnelSettings.swift` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhfsoNP1qPJfEIPtL2_:-Nhg3f0T2wKhJh_VXEQW:bmbyc81) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6c7c2999a8431e68df4044f951ca9d9bba3cf8dd/ios/MullvadSettings/TunnelSettings.swift#L16)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This is intentionally close to the protocol defined in `Migration.swift` 
At the moment, we don't need a migration type that involves doing API calls.
If we ever do, we can make `TunnelSettings` adhere to that protocol, or create migration classes that implement the protocol with minimal amount of changes.
</blockquote></details>

Not following this. And even if the reasoning is sound, no implementation so far uses any of the supplied arguments.
___
*[`ios/MullvadVPNTests/MigrationManagerTests.swift` line 48 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-Nhg5Ay21PHex8vMsR_o:-Nhg5Ay21PHex8vMsR_p:byisxfj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a379f24bce4661a1dc84bc403345e7e17abf1d57/ios/MullvadVPNTests/MigrationManagerTests.swift#L48)):*
> ```Swift
>         try SettingsManager.writeSettings(settings)
> 
>         let nothingToMigrationExpectation = expectation(description: "No migration")
> ```

Nit: "migrate"
___
*[`ios/MullvadVPNTests/MigrationManagerTests.swift` line 127 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhgAG2W-_hrLuwlNrx9:-NhgAG2W-_hrLuwlNrxA:b-kj4okn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a379f24bce4661a1dc84bc403345e7e17abf1d57/ios/MullvadVPNTests/MigrationManagerTests.swift#L127)):*
> ```Swift
>     }
> 
>     private func migrateToLatest(_ settings: any TunnelSettings, version: SchemaVersion) throws {
> ```

Nit-ish: version can probably be derived from TunnelSettings instead. That way there can be no discrepancies in the supplied args.


<!-- Sent from Reviewable.io -->

2023-10-26 14:31 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367)* status: all files reviewed, 5 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadSettings/MigrationManager.swift` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhfrMyA3eAcw1LZCNd9:-NhgN1Al2ps_qlYbmhDu:b-6a9kuy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a379f24bce4661a1dc84bc403345e7e17abf1d57/ios/MullvadSettings/MigrationManager.swift#L89)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Why all this variable juggling?
</blockquote></details>

I'm not sure what to answer. Those variables are reused in the `repeat` loop to incrementally upgrade the settings.
How would you write this ?
___
*[`ios/MullvadSettings/SettingsManager.swift` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-Nhg-TBQ24WSP9ziAXrD:-NhgNK421JLt2mHfw6e6:blcszuy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a379f24bce4661a1dc84bc403345e7e17abf1d57/ios/MullvadSettings/SettingsManager.swift#L36)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Can't we just change this to a var and call it a day?
</blockquote></details>

Ideally we shouldn't have to do this, but since `SettingsManager` is architectured to be globally available it's complicated to use it, or use any components that depend on it in tests.
I didn't want to refactor `SettingsManager` so this is the 2nd best approach I could think of to avoid changing it, but still make it safely usable in tests.
___
*[`ios/MullvadSettings/TunnelSettings.swift` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhfsoNP1qPJfEIPtL2_:-NhgOBwGC8Q5wwvZDXaE:b-3bq2rw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6c7c2999a8431e68df4044f951ca9d9bba3cf8dd/ios/MullvadSettings/TunnelSettings.swift#L16)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Not following this. And even if the reasoning is sound, no implementation so far uses any of the supplied arguments.
</blockquote></details>

You are correct. I wanted to get the team's feeling on that, happy to remove all the currently unused arguments.
___
*[`ios/MullvadVPNTests/MigrationManagerTests.swift` line 48 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-Nhg5Ay21PHex8vMsR_o:-NhgOOIoDXjp4M-IhVax:bwhfj2k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a379f24bce4661a1dc84bc403345e7e17abf1d57/ios/MullvadVPNTests/MigrationManagerTests.swift#L48)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: "migrate"
</blockquote></details>

🫠 I made that mistake everywhere
___
*[`ios/MullvadVPNTests/MigrationManagerTests.swift` line 127 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhgAG2W-_hrLuwlNrx9:-NhgMie28iV6genrUaFD:b-fusuw2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a379f24bce4661a1dc84bc403345e7e17abf1d57/ios/MullvadVPNTests/MigrationManagerTests.swift#L127)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit-ish: version can probably be derived from TunnelSettings instead. That way there can be no discrepancies in the supplied args.
</blockquote></details>

Not sure what you mean by that. `TunnelSettings` do not provide a version attached to it.
Do you mean that we should include the version in the `TunnelSettings` protocol ?


<!-- Sent from Reviewable.io -->

2023-10-27 09:15 UTC, rablador requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadSettings/MigrationManager.swift` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhfrMyA3eAcw1LZCNd9:-NhkN8Xs0l_zgU-4BVNg:b2n8f6n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a379f24bce4661a1dc84bc403345e7e17abf1d57/ios/MullvadSettings/MigrationManager.swift#L89)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I'm not sure what to answer. Those variables are reused in the `repeat` loop to incrementally upgrade the settings.
How would you write this ?
</blockquote></details>

`guard var savedSchema` and `var savedSettings` would eliminate the need for both `versionTypeCopy` and `latestSettings`.
___
*[`ios/MullvadSettings/SettingsManager.swift` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-Nhg-TBQ24WSP9ziAXrD:-NhkOlETCngdvlTPx4F_:bagh5tr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a379f24bce4661a1dc84bc403345e7e17abf1d57/ios/MullvadSettings/SettingsManager.swift#L36)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Ideally we shouldn't have to do this, but since `SettingsManager` is architectured to be globally available it's complicated to use it, or use any components that depend on it in tests.
I didn't want to refactor `SettingsManager` so this is the 2nd best approach I could think of to avoid changing it, but still make it safely usable in tests.
</blockquote></details>

Well, I tried my own suggestion and it seems `ApplicationSecurityGroupIdentifier` is nil at the time of unit test setup, so that clearly didn't work...
___
*[`ios/MullvadSettings/TunnelSettings.swift` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhfsoNP1qPJfEIPtL2_:-NhkPdYh8nYP2wQ6E_X-:bp72j2n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6c7c2999a8431e68df4044f951ca9d9bba3cf8dd/ios/MullvadSettings/TunnelSettings.swift#L16)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

You are correct. I wanted to get the team's feeling on that, happy to remove all the currently unused arguments.
</blockquote></details>

I'll let the others chime in, but I don't think we should keep them.
___
*[`ios/MullvadVPNTests/MigrationManagerTests.swift` line 127 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhgAG2W-_hrLuwlNrx9:-NhkEXlm7RTekZtSiOyp:bu56oo6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a379f24bce4661a1dc84bc403345e7e17abf1d57/ios/MullvadVPNTests/MigrationManagerTests.swift#L127)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Not sure what you mean by that. `TunnelSettings` do not provide a version attached to it.
Do you mean that we should include the version in the `TunnelSettings` protocol ?
</blockquote></details>

We could do something like the snippet below to determine version instead. It's not super elegant, but that way we don't need to specify version twice att call, ie `migrateToLatest(TunnelSettingsV1)`, reducing potential discrepancies and bugs.



_Code snippet:_
```Swift

switch settings {
    case is TunnelSettingsV1:
[...]
```


<!-- Sent from Reviewable.io -->

2023-10-27 13:29 UTC, pronebird requested changes
> Reviewed 2 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadSettings/MigrationManager.swift` line 74 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhlD-eu67Chm9DF3vm5:-NhlD-eu67Chm9DF3vm6:bvja4ji) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e0aff91fa43829fd27b57fcb38439a02b537029d/ios/MullvadSettings/MigrationManager.swift#L74)):*
> ```Swift
> 
>         // Special case downgrade attempts as nothing to do
>         guard settingsVersion < SchemaVersion.current.rawValue else {
> ```

`!=` is the correct operator here. App downgrades should reset all settings, you have a condition below that checks for unknown version.
___
*[`ios/MullvadSettings/TunnelSettings.swift` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhfsoNP1qPJfEIPtL2_:-Nhl9gBj0H93dHJe-ELH:bl18e0d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6c7c2999a8431e68df4044f951ca9d9bba3cf8dd/ios/MullvadSettings/TunnelSettings.swift#L16)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I'll let the others chime in, but I don't think we should keep them.
</blockquote></details>

If the method is not async nor has a completion handler then passing any REST facilities is pointless imo, because they are asynchronous and especially. Just remove the unused parameters as @rablador  said.
___
*[`ios/MullvadSettings/TunnelSettings.swift` line 32 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhlC1PmB-F9auMLjMaa:-NhlC1PmB-F9auMLjMab:bflq5pm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e0aff91fa43829fd27b57fcb38439a02b537029d/ios/MullvadSettings/TunnelSettings.swift#L32)):*
> ```Swift
>     case v2 = 2
> 
>     /// V2 format with wireGuard obfuscation options, stored as `TunnelSettingsV3`.
> ```

Ultra nit: wireguard is typically written with a capital W, i.e WireGuard
___
*[`ios/MullvadSettings/TunnelSettings.swift` line 51 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhlBs7M7EBAXMLP5nfy:-NhlBs7M7EBAXMLP5nfz:bak8meu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e0aff91fa43829fd27b57fcb38439a02b537029d/ios/MullvadSettings/TunnelSettings.swift#L51)):*
> ```Swift
>     }
> 
>     var nextVersionType: any TunnelSettings.Type {
> ```

This is the same as `nextVersion.settingsType`


<!-- Sent from Reviewable.io -->

2023-10-27 14:23 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367)* status: 10 of 16 files reviewed, 6 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadSettings/MigrationManager.swift` line 89 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhfrMyA3eAcw1LZCNd9:-NhlSMmT30Z0t8L1dOsh:bot8l35) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a379f24bce4661a1dc84bc403345e7e17abf1d57/ios/MullvadSettings/MigrationManager.swift#L89)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

`guard var savedSchema` and `var savedSettings` would eliminate the need for both `versionTypeCopy` and `latestSettings`.
</blockquote></details>

Oh good point ! That's still readable with less variables. 
___
*[`ios/MullvadSettings/MigrationManager.swift` line 74 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhlD-eu67Chm9DF3vm5:-NhlUn5Y2bD9Cp3DsxEh:b-833mka) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e0aff91fa43829fd27b57fcb38439a02b537029d/ios/MullvadSettings/MigrationManager.swift#L74)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

`!=` is the correct operator here. App downgrades should reset all settings, you have a condition below that checks for unknown version.
</blockquote></details>

Ok, I wasn't 100% if this was the desired behaviour, but thinking about it longer, it's easier to wipe settings on downgrade than not doing anything, and potentially having inconsistent and weird results.
___
*[`ios/MullvadSettings/SettingsManager.swift` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-Nhg-TBQ24WSP9ziAXrD:-NhlSU-h79N6Tdv6S1vl:b5mc7u5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a379f24bce4661a1dc84bc403345e7e17abf1d57/ios/MullvadSettings/SettingsManager.swift#L36)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Well, I tried my own suggestion and it seems `ApplicationSecurityGroupIdentifier` is nil at the time of unit test setup, so that clearly didn't work...
</blockquote></details>

Yes, we could set an identifier in the bundle for UnitTests but ehh. 
___
*[`ios/MullvadSettings/TunnelSettings.swift` line 16 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhfsoNP1qPJfEIPtL2_:-NhlT3QL5rGpyNGGcKia:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6c7c2999a8431e68df4044f951ca9d9bba3cf8dd/ios/MullvadSettings/TunnelSettings.swift#L16)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

If the method is not async nor has a completion handler then passing any REST facilities is pointless imo, because they are asynchronous and especially. Just remove the unused parameters as @rablador  said.
</blockquote></details>

Done
___
*[`ios/MullvadSettings/TunnelSettings.swift` line 32 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhlC1PmB-F9auMLjMaa:-NhlT6C6BbQ-iZdZEg01:b-bs5s3l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e0aff91fa43829fd27b57fcb38439a02b537029d/ios/MullvadSettings/TunnelSettings.swift#L32)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Ultra nit: wireguard is typically written with a capital W, i.e WireGuard
</blockquote></details>

Genuine mistake, thanks for catching it !
___
*[`ios/MullvadSettings/TunnelSettings.swift` line 51 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhlBs7M7EBAXMLP5nfy:-NhlTfnL7FRrXoQ0av0A:binzez2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e0aff91fa43829fd27b57fcb38439a02b537029d/ios/MullvadSettings/TunnelSettings.swift#L51)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

This is the same as `nextVersion.settingsType`
</blockquote></details>

Actually I ended up not using that, and will remove it


<!-- Sent from Reviewable.io -->

2023-10-27 14:28 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367)* status: 10 of 16 files reviewed, 6 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPNTests/MigrationManagerTests.swift` line 127 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhgAG2W-_hrLuwlNrx9:-NhlWSwN6EJbyzwDFsFA:bv3zr3a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a379f24bce4661a1dc84bc403345e7e17abf1d57/ios/MullvadVPNTests/MigrationManagerTests.swift#L127)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

We could do something like the snippet below to determine version instead. It's not super elegant, but that way we don't need to specify version twice att call, ie `migrateToLatest(TunnelSettingsV1)`, reducing potential discrepancies and bugs.
</blockquote></details>

I see what you mean, but I think it would be awkward if we had more than 3 versions (which we probably will have in the future) we would have to keep updating this function with more switch cases and wouldn't scale well IMHO


<!-- Sent from Reviewable.io -->

2023-10-27 14:31 UTC, pronebird reviewed
> Reviewed 2 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367)* status: 10 of 16 files reviewed, 6 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadSettings/WireGuardObfuscationSettings.swift` line 11 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhlWZq38oC3evl_sBSX:-NhlWZq38oC3evl_sBSY:btdp3zz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e0aff91fa43829fd27b57fcb38439a02b537029d/ios/MullvadSettings/WireGuardObfuscationSettings.swift#L11)):*
> ```Swift
> import Foundation
> 
> public enum WireGuardObfuscationState: Codable {
> ```

FYI

It's designed differently on desktop, selected obfuscation method can be off, auto, udp2tcp. 

Technically more obfuscation protocols will be added in the future so the list can be extended. 

Port setting you have basically apply to udp2tcp - that's just a particular kind of obfuscator.

Maybe it's simpler this way for now and you can always do migration. I don't know. But I would be remiss if I didn't mention that.


<!-- Sent from Reviewable.io -->

2023-10-30 13:47 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367)* status: 10 of 16 files reviewed, 5 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadSettings/WireGuardObfuscationSettings.swift` line 11 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367#-NhlWZq38oC3evl_sBSX:-Ni-pNlCBG7SEl2oFSUr:b-qu4fp4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e0aff91fa43829fd27b57fcb38439a02b537029d/ios/MullvadSettings/WireGuardObfuscationSettings.swift#L11)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

FYI

It's designed differently on desktop, selected obfuscation method can be off, auto, udp2tcp. 

Technically more obfuscation protocols will be added in the future so the list can be extended. 

Port setting you have basically apply to udp2tcp - that's just a particular kind of obfuscator.

Maybe it's simpler this way for now and you can always do migration. I don't know. But I would be remiss if I didn't mention that.
</blockquote></details>

Fair enough, thanks for letting me know.
As you pointed out, I went for simplicity this time. Let's see what the future holds out, but I'm not too worried in how complex it will be to update to.


<!-- Sent from Reviewable.io -->

2023-10-30 13:56 UTC, rablador approved these changes
> Reviewed 6 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5367)* status: all files reviewed, 3 unresolved discussions (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-10-30 14:05 UTC, merged