show outgoing connection on map
mullvad/mullvadvpn-app pull request #5396
Opened 2023-11-03 09:01 UTC by mojganii

this PR introduces a valuable feature that enhances the user experience by showing outgoing addresses in the connection view. This information is especially useful when access to exit IPs is available, and the implementation ensures the accuracy and completeness of the displayed data by making two network requests and waiting for their successful completion.these actions are taken to achieve the result :

1.**Network Requests for IP Addresses**: To gather the necessary information, two network requests are initiated, one for IPv4 and the other for IPv6 addresses. These requests are essential for determining the exit IP address associated with the established tunnel.
2. **Wait for Completion:** The system intelligently waits for both of these requests to be completed successfully, ensuring that we have comprehensive data for both IPv4 and IPv6 addresses if they are available .
3. **Exit Addresses Display**: Once both IPv4 and IPv6 address data are done, the connection view is updated to prominently display the exit addresses.

<table style="height: 568px; width: 600px; border-collapse: collapse; margin-left: auto; margin-right: auto;" cellspacing="20" cellpadding="28">
<tbody>
<tr>
    <th>Before</th>
    <th colspan="5">After</th>
</tr>
<tr>
<td style="width: 50%;"><img src="https://github.com/mullvad/mullvadvpn-app/assets/129863230/a931dee0-62dd-4e07-9347-073702cb9af5"  width="160" height="284" /></td>
<td style="width: 50%;"><img src="https://github.com/mullvad/mullvadvpn-app/assets/129863230/ce5812f6-e15b-4e1e-b8c2-8d2395188e4b"  width="160" height="284" /></td>
</tr>
</tbody>
</table>

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)

2023-11-07 15:53 UTC, rablador reviewed
> Reviewed 2 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 2 of 15 files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 94 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NieTUfe8IOj8Y0TUUBm:-NieTUfe8IOj8Y0TUUBn:b-h365xv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7461215221267bf8ea9f085339f0c385dc8d2397/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L94)):*
> ```Swift
>         let exitIP: Bool
> 
>         enum CodingKeys: String, CodingKey {
> ```

This struct already conforms to Codable, so no need to encode or decode manually. This enum, along with `init(from decoder: Decoder)` and `encode(to encoder: Encoder)`, can be removed.
___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 98 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NieTw7y0P4-ZgwCAgY4:-NieTw7y0P4-ZgwCAgY5:b-udpr7g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7461215221267bf8ea9f085339f0c385dc8d2397/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L98)):*
> ```Swift
>         }
> 
>         init(ip: T, exitIP: Bool) {
> ```

This init is never used and should be ok to remove.
___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 116 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NieU1bnE4Hkh5F2IhZl:-NieU1bnE4Hkh5F2IhZm:bnovo2s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7461215221267bf8ea9f085339f0c385dc8d2397/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L116)):*
> ```Swift
> 
>         static func == (
>             lhs: OutgoingConnectionProxy.OutgoingConnectionData<T>,
> ```

Nit: `OutgoingConnectionProxy.OutgoingConnectionData<T>` can be substituted with `Self` instead to increase readability.


<!-- Sent from Reviewable.io -->

2023-11-08 10:25 UTC, rablador requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 2 of 15 files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 94 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NieTUfe8IOj8Y0TUUBm:-NiiSXqd4VGCF5k2gvK8:b3h194p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7461215221267bf8ea9f085339f0c385dc8d2397/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L94)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This struct already conforms to Codable, so no need to encode or decode manually. This enum, along with `init(from decoder: Decoder)` and `encode(to encoder: Encoder)`, can be removed.
</blockquote></details>

Update: We actually need the mapping enum here, because of `exitIP = "mullvad_exit_ip"`, but the rest is ok to remove.


<!-- Sent from Reviewable.io -->

2023-11-08 12:26 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 1 of 15 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 94 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NieTUfe8IOj8Y0TUUBm:-NiiryMJBwOH8RwNjh4R:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7461215221267bf8ea9f085339f0c385dc8d2397/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L94)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Update: We actually need the mapping enum here, because of `exitIP = "mullvad_exit_ip"`, but the rest is ok to remove.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 98 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NieTw7y0P4-ZgwCAgY4:-Niis-Jx6DCzqYiprKWt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7461215221267bf8ea9f085339f0c385dc8d2397/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L98)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This init is never used and should be ok to remove.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 116 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NieU1bnE4Hkh5F2IhZl:-NiitLkEEM9ryCHWAeuH:b-3cslex) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7461215221267bf8ea9f085339f0c385dc8d2397/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L116)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: `OutgoingConnectionProxy.OutgoingConnectionData<T>` can be substituted with `Self` instead to increase readability.
</blockquote></details>

indeed!


<!-- Sent from Reviewable.io -->

2023-11-08 12:35 UTC, rablador requested changes
> Reviewed 13 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/Tunnel/OutgoingConnectionService.swift` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NiirGc11IO9aEUDdluH:-NiirGc11IO9aEUDdluI:bhxnflg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7461215221267bf8ea9f085339f0c385dc8d2397/ios/MullvadVPN/View%20controllers/Tunnel/OutgoingConnectionService.swift#L67)):*
> ```Swift
> 
>     var outAddress: String? {
>         let v4 = ipv4.exitIP ? ipv4.ip : nil
> ```

This can be compressed a bit, also only adding the line break if there are two items to separate them:



_Code snippet:_
```Swift
        let v4: IPAddress? = ipv4.exitIP ? ipv4.ip : nil
        let v6: IPAddress? = ipv6.flatMap { $0.exitIP ? $0.ip : nil }

        let string = [v4, v6].compactMap { $0 }.map { $0.debugDescription }.joined(separator: "\n")
        return string.isEmpty ? nil : string
```
___
*[`ios/MullvadVPNTests/OutgoingConnectionServiceTests.swift` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NiivQ-M7nqrC3_r8ri-:-NiivQ-M7nqrC3_r8ri0:bbm2x8p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7461215221267bf8ea9f085339f0c385dc8d2397/ios/MullvadVPNTests/OutgoingConnectionServiceTests.swift#L35)):*
> ```Swift
>         let result = try await outgoingConnectionService.getOutgoingConnectionInfo()
>         if result.ipv4 == .mock,
>            let ipv6 = result.ipv6,
> ```

Just `result.ipv6 == .mock` works too.


<!-- Sent from Reviewable.io -->

2023-11-09 10:08 UTC, pronebird requested changes
> Reviewed 14 of 15 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 91 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NinXOYJ6eMy2Q1RiEvy:-NinXOYJ6eMy2Q1RiEvz:budjsqy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L91)):*
> ```Swift
> 
>     struct OutgoingConnectionData<T: IPAddressType>: Codable, Equatable {
>         let ip: T?
> ```

Can `ip` really be `nil`?
___
*[`ios/MullvadVPN/View controllers/Tunnel/OutgoingConnectionService.swift` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NiirGc11IO9aEUDdluH:-NinXegfCMdJOyddVzBL:b-bcdght) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7461215221267bf8ea9f085339f0c385dc8d2397/ios/MullvadVPN/View%20controllers/Tunnel/OutgoingConnectionService.swift#L67)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This can be compressed a bit, also only adding the line break if there are two items to separate them:
</blockquote></details>

@rablador transforming IP to string can be done using `"\(ipAddress)"`, no need to call `debugDescription` directly.


<!-- Sent from Reviewable.io -->

2023-11-09 14:11 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 91 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NinXOYJ6eMy2Q1RiEvy:-NinfvhOA0JBZ0fi7reo:bgwgy4w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L91)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Can `ip` really be `nil`?
</blockquote></details>

After checking the server response I figured out it cannot be optional. 
___
*[`ios/MullvadVPN/View controllers/Tunnel/OutgoingConnectionService.swift` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NiirGc11IO9aEUDdluH:-NinDOlAAVVWXPhwidSv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7461215221267bf8ea9f085339f0c385dc8d2397/ios/MullvadVPN/View%20controllers/Tunnel/OutgoingConnectionService.swift#L67)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This can be compressed a bit, also only adding the line break if there are two items to separate them:
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/OutgoingConnectionServiceTests.swift` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NiivQ-M7nqrC3_r8ri-:-NioMspz9z3SXpDGG0D9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7461215221267bf8ea9f085339f0c385dc8d2397/ios/MullvadVPNTests/OutgoingConnectionServiceTests.swift#L35)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Just `result.ipv6 == .mock` works too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-09 15:28 UTC, buggmagnet requested changes
That's really good work ! 

> Reviewed 7 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-:-NioggXB9lCiD93-qYMZ:bx6zp3s)* status: 11 of 15 files reviewed, 13 unresolved discussions (waiting on @mojganii, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/SceneDelegate.swift` line 73 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-Nio9ENq8Zte_3owxAxa:-Nio9ENq8Zte_3owxAxb:b-wwlewi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/SceneDelegate.swift#L73)):*
> ```Swift
>             accountsProxy: appDelegate.accountsProxy,
>             outgoingConnectionService: OutgoingConnectionService(
>                 outgoingConnectionProxy: OutgoingConnectionProxy(urlSession: .shared)
> ```

We don't want to cache the result of calls `to am.i.mullvad.net`, therefore we don't want to use the `.shared` sessions.

Please use `URLSessionConfiguration.ephemeral` instead for getting a `URLSession` object
___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 83 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioVJIl8TGpSXbp8nQC:-NioVJIl8TGpSXbp8nQD:bu6u8i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L83)):*
> ```Swift
> }
> 
> extension OutgoingConnectionProxy {
> ```

IMHO `OutgoingConnectionData` should be in its own file and not part of `OutgoingConnectionProxy` 

The protocol signature would look simpler as well
```swift
protocol OutgoingConnectionHandling {
    func getIPV6(retryStrategy: REST.RetryStrategy) async throws -> IPV6ConnectionData
    func getIPV4(retryStrategy: REST.RetryStrategy) async throws -> IPV4ConnectionData
}

```
___
*[`ios/MullvadVPN/View controllers/Tunnel/OutgoingConnectionService.swift` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioYboUEavqbb6AbCTx:-NioYboUEavqbb6AbCTy:b-yetoj7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/View%20controllers/Tunnel/OutgoingConnectionService.swift#L30)):*
> ```Swift
> 
>     func getOutgoingConnectionInfo() async throws -> OutgoingConnectionInfo {
>         try await withThrowingTaskGroup(of: OutgoingConnectionResult.self) { taskGroup -> OutgoingConnectionInfo in
> ```


We can simplify this.
However, technically we are not running the calls in parallel but that shouldn't matter in practice. Also we're shaving 40 lines. IMHO it's worth it.

```swift
func getOutgoingConnectionInfo() async throws -> OutgoingConnectionInfo {
    let ipv4 = try await outgoingConnectionProxy.getIPV4(retryStrategy: .default)
    let ipv6 = try await outgoingConnectionProxy.getIPV6(retryStrategy: .noRetry)

    return OutgoingConnectionInfo(ipv4: ipv4, ipv6: ipv6)
}

```

I don't think we should be touching the task priority until we have good reason to believe that this would be significantly better for the UX.
If we absolutely need to, then we can change the call site instead (which I still think we shouldn't)

```swift
outgoingConnectionTask = Task(priority: .userInitiated) { [weak self] in
    guard let outgoingConnectionInfo = try await self?.outgoingConnectionService
        .getOutgoingConnectionInfo() else {
        return
    }
    await self?.didGetOutGoingAddress?(outgoingConnectionInfo)
}

```
___
*[`ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift` line 153 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NiofFGc81OSXatmaapG:-NiofFGc81OSXatmaapH:b-6bn07n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/View%20controllers/Tunnel/TunnelControlView.swift#L153)):*
> ```Swift
>         if let tunnelRelay = tunnelState.relay {
>             connectionPanel.dataSource = ConnectionPanelData(
>                 inAddress: "\(tunnelRelay.endpoint.ipv4Relay) UDP",
> ```

We shouldn't be hardcoding `UDP` here since it's depending on whether we're using the UDP-over-TCP obfuscation.

Maybe let's add a TODO comment for now that we will be solving this soon.
___
*[`ios/MullvadVPN/View controllers/Tunnel/TunnelViewControllerInteractor.swift` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NiogVqZ1t8J9v4ZNLYs:-NiogVqZ1t8J9v4ZNLYt:b-a3l107) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/View%20controllers/Tunnel/TunnelViewControllerInteractor.swift#L42)):*
> ```Swift
>         self.outgoingConnectionService = outgoingConnectionService
> 
>         let tunnelObserver = TunnelBlockObserver(
> ```

Is there anyway we can do this when we start the tunnel instead of the init ?
___
*[`ios/MullvadVPNTests/MockURLProtocol.swift` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioRlCQ7FuU27IrJ2ds:-NioRlCQ7FuU27IrJ2dt:bl7piul) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPNTests/MockURLProtocol.swift#L12)):*
> ```Swift
> 
> class MockURLProtocol: URLProtocol {
>     static var error: Error?
> ```

Same remark as in `OutgoingConnectionProxyStub`, this should not be `static`
___
*[`ios/MullvadVPNTests/OutgoingConnectionProxy+Stub.swift` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioR7CjDSDU0zAYNljO:-NioR7CjDSDU0zAYNljP:b-2to0sj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPNTests/OutgoingConnectionProxy%2BStub.swift#L12)):*
> ```Swift
> 
> struct OutgoingConnectionProxyStub: OutgoingConnectionHandling {
>     static var hasError = false
> ```

Please let's not use `static` unless we absolutely have to. It always leads to hard to test designs and unwanted shared states.

Here in particular, it makes it so that all the `OutgoingConnectionProxyStub` have the same error state which is definitely not what we want when running multiple tests in parallel.
___
*[`ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioARt2EugA95O2tPty:-NioARt2EugA95O2tPtz:b8f1zsb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift#L18)):*
> ```Swift
>     private let encoder: JSONEncoder = REST.Coding.makeJSONEncoder()
> 
>     override func setUp() {
> ```

You can use `setUpWithError() throws` and remove the `force try` as well as the `swiftlint:disable` commands instead 

Remember to also use `tearDownWithError() throws` as well in that case
___
*[`ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift` line 34 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioB08k95LulEe3axoj:-NioB08k95LulEe3axok:b4ugqmh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift#L34)):*
> ```Swift
>     func testNoInternetConnection() async throws {
>         let failureExpectation = expectation(description: "should fail")
>         let successExpectation = expectation(description: "should not succeed")
> ```

There are a couple of things we can improve in this test.

- Expectations :
Because we are using inverted expectations here, when this fails, the message produced will be 
`Fulfilled inverted expectation "should not succeed".` 
Which is a double negation. 

In essence, we should keep the same kind messaging so that the error is easy to read and understand.
In this case, it would make sense to read `Fulfilled inverted expectation "Received IPv4".`

- Expectation descriptions :
A message such as "should fail" is not very descriptive. What are we expecting here ? We shouldn't have to read what the code does when a test fail to know _what_ fai [...]

2023-11-10 12:53 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 11 of 15 files reviewed, 12 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/SceneDelegate.swift` line 73 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-Nio9ENq8Zte_3owxAxa:-NiohmTj0WyVRezg-qUf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/SceneDelegate.swift#L73)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We don't want to cache the result of calls `to am.i.mullvad.net`, therefore we don't want to use the `.shared` sessions.

Please use `URLSessionConfiguration.ephemeral` instead for getting a `URLSession` object
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Tunnel/OutgoingConnectionService.swift` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioYboUEavqbb6AbCTx:-NiohzRT5RDj9457OE7t:b-wu3ntu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/View%20controllers/Tunnel/OutgoingConnectionService.swift#L30)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We can simplify this.
However, technically we are not running the calls in parallel but that shouldn't matter in practice. Also we're shaving 40 lines. IMHO it's worth it.

```swift
func getOutgoingConnectionInfo() async throws -> OutgoingConnectionInfo {
    let ipv4 = try await outgoingConnectionProxy.getIPV4(retryStrategy: .default)
    let ipv6 = try await outgoingConnectionProxy.getIPV6(retryStrategy: .noRetry)

    return OutgoingConnectionInfo(ipv4: ipv4, ipv6: ipv6)
}

```

I don't think we should be touching the task priority until we have good reason to believe that this would be significantly better for the UX.
If we absolutely need to, then we can change the call site instead (which I still think we shouldn't)

```swift
outgoingConnectionTask = Task(priority: .userInitiated) { [weak self] in
    guard let outgoingConnectionInfo = try await self?.outgoingConnectionService
        .getOutgoingConnectionInfo() else {
        return
    }
    await self?.didGetOutGoingAddress?(outgoingConnectionInfo)
}

```
</blockquote></details>

but task group does it parallely.regarding the task priority I think we need to change it for better UX
___
*[`ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift` line 153 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NiofFGc81OSXatmaapG:-NioiP5r4Dcg6Rb4g8D0:bltvybu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/View%20controllers/Tunnel/TunnelControlView.swift#L153)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We shouldn't be hardcoding `UDP` here since it's depending on whether we're using the UDP-over-TCP obfuscation.

Maybe let's add a TODO comment for now that we will be solving this soon.
</blockquote></details>

I'll put todo for that
___
*[`ios/MullvadVPN/View controllers/Tunnel/TunnelViewControllerInteractor.swift` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NiogVqZ1t8J9v4ZNLYs:-Nioji3J7iFlu4KHRMAp:b-3meg1x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/View%20controllers/Tunnel/TunnelViewControllerInteractor.swift#L42)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Is there anyway we can do this when we start the tunnel instead of the init ?
</blockquote></details>

is it the responsibility of tunnel to fetch exit ip.I don't think so.
___
*[`ios/MullvadVPNTests/MockURLProtocol.swift` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioRlCQ7FuU27IrJ2ds:-NitGb3g6fBlEY1rgdSd:b-a0mh7e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPNTests/MockURLProtocol.swift#L12)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Same remark as in `OutgoingConnectionProxyStub`, this should not be `static`
</blockquote></details>

if I'm gonna eliminate static variable in this particular part I need to go protocol-oriented for url-session and data task and so on that takes much efforts and bring more complexity.do you have any solution for this part?
___
*[`ios/MullvadVPNTests/OutgoingConnectionProxy+Stub.swift` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioR7CjDSDU0zAYNljO:-NiomBiS5ojjiXmuM9-f:b-jnts5j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPNTests/OutgoingConnectionProxy%2BStub.swift#L12)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Please let's not use `static` unless we absolutely have to. It always leads to hard to test designs and unwanted shared states.

Here in particular, it makes it so that all the `OutgoingConnectionProxyStub` have the same error state which is definitely not what we want when running multiple tests in parallel.
</blockquote></details>

fair enough 
___
*[`ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioARt2EugA95O2tPty:-Nion-k80fCO74I4m7Ex:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift#L18)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

You can use `setUpWithError() throws` and remove the `force try` as well as the `swiftlint:disable` commands instead 

Remember to also use `tearDownWithError() throws` as well in that case
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/OutgoingConnectionServiceTests.swift` line 54 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioSOWwEP4eytJE3UFL:-NionKvO7Z9eLbVOWP6M:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPNTests/OutgoingConnectionServiceTests.swift#L54)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
Technically, this is a [stub, not a mock](https://martinfowler.com/articles/mocksArentStubs.html#TheDifferenceBetweenMocksAndStubs)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-13 07:53 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 5 of 16 files reviewed, 8 unresolved discussions (waiting on @mojganii, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/View controllers/Tunnel/OutgoingConnectionService.swift` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioYboUEavqbb6AbCTx:-Nj6MpDd5rL9C8Z0_KRV:b-e0o3oj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/View%20controllers/Tunnel/OutgoingConnectionService.swift#L30)):*
> but task group does it parallely.
Yes but there are a couple of considerations at play here:
- We are only running 2 tasks
- We are doing network calls
- 3 lines of code is vastly easier to understand than 40 with a custom built enum

There's very likely more overhead to try to run 2 tasks in parallel rather than running them one after the other given how simple the calls are (and how fast iPhone processors are nowadays)
And since it's networking code, on a bad connection, it won't make any difference whether the tasks are running in parallel rather than in sequence.

> I think we need to change it for better UX
Doing this will in the best case, not do anything, and in the worst case, make the whole system perform worse.
This is a good example of the [Priority Inversion problem](https://en.wikipedia.org/wiki/Priority_inversion).
However, the swift async runtime should help us in those situations, hopefully. Happy to talk more about why that's a problematic design, but not in this comment.
___
*[`ios/MullvadVPNTests/MockURLProtocol.swift` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioRlCQ7FuU27IrJ2ds:-Nj6djR8E134O52LOUkU:bxua40e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPNTests/MockURLProtocol.swift#L12)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

if I'm gonna eliminate static variable in this particular part I need to go protocol-oriented for url-session and data task and so on that takes much efforts and bring more complexity.do you have any solution for this part?
</blockquote></details>

Technically, the only part where we use that `URLSession` object is in `OutgoingConnectionProxy` where we do 
`let (data, response) = try await urlSession.data(from: url)` 

Ideally, we should have extracted that call to a single interface, then we wouldn't need all this mocking of `URLProtocol` and the complicated setup of tests.
That's a bit unfortunate, but it's not the end of the world.

I will create a cleanup janitor task instead, it's not critical.


<!-- Sent from Reviewable.io -->

2023-11-13 09:36 UTC, pronebird reviewed
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 6 of 16 files reviewed, 7 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/View controllers/Tunnel/OutgoingConnectionService.swift` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioYboUEavqbb6AbCTx:-Nj6v_FY16o58UByxegb:b-9g9fcm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/View%20controllers/Tunnel/OutgoingConnectionService.swift#L30)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

> but task group does it parallely.
Yes but there are a couple of considerations at play here:
- We are only running 2 tasks
- We are doing network calls
- 3 lines of code is vastly easier to understand than 40 with a custom built enum

There's very likely more overhead to try to run 2 tasks in parallel rather than running them one after the other given how simple the calls are (and how fast iPhone processors are nowadays)
And since it's networking code, on a bad connection, it won't make any difference whether the tasks are running in parallel rather than in sequence.

> I think we need to change it for better UX
Doing this will in the best case, not do anything, and in the worst case, make the whole system perform worse.
This is a good example of the [Priority Inversion problem](https://en.wikipedia.org/wiki/Priority_inversion).
However, the swift async runtime should help us in those situations, hopefully. Happy to talk more about why that's a problematic design, but not in this comment.
</blockquote></details>

Let's not get into micro optimizations.

Parallelization for IP lookup requests makes sense. This part looks right to me. 

However I think that using `async let` binding to run two tasks in parallel and then collect the result would be simpler way to approach this.

```swift
async let ipv4Result = getIPv4(..)
async let ipv6Result = getIPv6(..)

OutgoingConnectionInfo(
  ipv4: try await ipv4Result, 
  ipv6: try? await ipv6Result
)
```


<!-- Sent from Reviewable.io -->

2023-11-13 10:24 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 6 of 16 files reviewed, 7 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/View controllers/Tunnel/OutgoingConnectionService.swift` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioYboUEavqbb6AbCTx:-Nj7-T7l59YDc5DvlYsn:boyt2k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/View%20controllers/Tunnel/OutgoingConnectionService.swift#L30)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

> but task group does it parallely.
Yes but there are a couple of considerations at play here:
- We are only running 2 tasks
- We are doing network calls
- 3 lines of code is vastly easier to understand than 40 with a custom built enum

There's very likely more overhead to try to run 2 tasks in parallel rather than running them one after the other given how simple the calls are (and how fast iPhone processors are nowadays)
And since it's networking code, on a bad connection, it won't make any difference whether the tasks are running in parallel rather than in sequence.

> I think we need to change it for better UX
Doing this will in the best case, not do anything, and in the worst case, make the whole system perform worse.
This is a good example of the [Priority Inversion problem](https://en.wikipedia.org/wiki/Priority_inversion).
However, the swift async runtime should help us in those situations, hopefully. Happy to talk more about why that's a problematic design, but not in this comment.
</blockquote></details>

accepted
___
*[`ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift` line 34 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioB08k95LulEe3axoj:-Nj7CBM_0W-2X0HptxYX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift#L34)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

There are a couple of things we can improve in this test.

- Expectations :
Because we are using inverted expectations here, when this fails, the message produced will be 
`Fulfilled inverted expectation "should not succeed".` 
Which is a double negation. 

In essence, we should keep the same kind messaging so that the error is easy to read and understand.
In this case, it would make sense to read `Fulfilled inverted expectation "Received IPv4".`

- Expectation descriptions :
A message such as "should fail" is not very descriptive. What are we expecting here ? We shouldn't have to read what the code does when a test fail to know _what_ failed.
A much better message would be "Did not receive IPv4". 
That way, if the test fails, this is what we would see "Asynchronous wait failed [...] with unfulfilled expectations: "Did not receive IPv4".
Now we know that we expected to not receive IPV4, and that the expectation was not fullfilled, therefore, we did receive an IPv4. We probably know how to fix this.

- Expectation names :
As important as the message, usually, we try to name the expectation according to what's being expected.
In this case, a good name would be `let noIPv4Expectation = expectation(description: "Did not receive IPv4")` for example.

- Catching the error :

Unfortunately, the `XCTest` API is not well suited for `async` results, otherwise, I would have said to use `XCTAssertThrowsError` which is suited for that.

So I wrote a helper method to help with that
```swift
extension XCTest {
    func XCTAssertThrowsErrorAsync<T: Sendable>(
        _ expression: @autoclosure () async throws -> T,
        _ message: @autoclosure () -> String = "",
        file: StaticString = #filePath,
        line: UInt = #line,
        _ errorHandler: (_ error: Error) -> Void = { _ in }
    ) async {
        do {
            _ = try await expression()
            XCTFail(message(), file: file, line: line)
        } catch {
            errorHandler(error)
        }
    }
}
```

Here's what the rewritten test looks like now 

```swift
func testGetIPv4FailsWhenNotConnected() async throws {
    let noIPv4Expectation = expectation(description: "Did not receive IPv4")
    MockURLProtocol.error = URLError(URLError.notConnectedToInternet)
    MockURLProtocol.requestHandler = nil

    await XCTAssertThrowsErrorAsync(try await outgoingConnectionProxy.getIPV4(retryStrategy: .noRetry)) { error in
        noIPv4Expectation.fulfill()
        XCTAssertEqual((error as? URLError)?.code, .notConnectedToInternet)
    }
    await fulfillment(of: [noIPv4Expectation], timeout: 1)
}

```

I suggest rewriting the other tests in this file with these improvements in mind
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-13 10:55 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 6 of 16 files reviewed, 7 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 83 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioVJIl8TGpSXbp8nQC:-Nj7HqaO0hhz-6coQuug:b4em6ar) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L83)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

IMHO `OutgoingConnectionData` should be in its own file and not part of `OutgoingConnectionProxy` 

The protocol signature would look simpler as well
```swift
protocol OutgoingConnectionHandling {
    func getIPV6(retryStrategy: REST.RetryStrategy) async throws -> IPV6ConnectionData
    func getIPV4(retryStrategy: REST.RetryStrategy) async throws -> IPV4ConnectionData
}

```
</blockquote></details>

It's a personal preferences.I'm fan of keeping protocols in individual files.let's know other's opinion.
@pronebird @rablador 


<!-- Sent from Reviewable.io -->

2023-11-13 11:43 UTC, buggmagnet approved these changes
> Reviewed 1 of 15 files at r1, 1 of 4 files at r3, 7 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 14 of 16 files reviewed, 5 unresolved discussions (waiting on @mojganii, @pronebird, and @rablador)

___
*[`ios/MullvadVPNTests/MockURLProtocol.swift` line 12 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioRlCQ7FuU27IrJ2ds:-Nj7U9QC0o6RDNdCFqey:bt45rrh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPNTests/MockURLProtocol.swift#L12)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Technically, the only part where we use that `URLSession` object is in `OutgoingConnectionProxy` where we do 
`let (data, response) = try await urlSession.data(from: url)` 

Ideally, we should have extracted that call to a single interface, then we wouldn't need all this mocking of `URLProtocol` and the complicated setup of tests.
That's a bit unfortunate, but it's not the end of the world.

I will create a cleanup janitor task instead, it's not critical.
</blockquote></details>

IOS-383 has been created for that
___
*[`ios/MullvadVPNTests/OutgoingConnectionProxy+Stub.swift` line 12 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-Nj7UNsN3u8AP96WPpp6:-Nj7UNsN3u8AP96WPpp7:b-oi2ysu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aab41f1b519852fc8a8d9eccb351aec6fe3ea888/ios/MullvadVPNTests/OutgoingConnectionProxy%2BStub.swift#L12)):*
> ```Swift
> 
> struct OutgoingConnectionProxyStub: OutgoingConnectionHandling {
>     var hasError = false
> ```

nit
Technically we don't need this `hasError`
We could have just made error an Optional, and then in the get function do
```swift
guard let error else { return ipVXXX }
throw error
```

But not a big deal


<!-- Sent from Reviewable.io -->

2023-11-13 12:42 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 14 of 16 files reviewed, 6 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 15 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-Nj7fgUjAMBknnrgmP3H:-Nj7fgUkCY7mk5ts0SGc:b-qt10zn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aab41f1b519852fc8a8d9eccb351aec6fe3ea888/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L15)):*
> ```Swift
> 
> protocol OutgoingConnectionHandling {
>     func getIPV6(retryStrategy: REST.RetryStrategy) async throws -> OutgoingConnectionProxy.IPV6ConnectionData
> ```

The protocol should not reference a type from a concrete implementation. 

Consider moving the `IPV*ConnectionData` outside of concrete implementation, perhaps somewhere next to protocol. 

Alternatively use a protocol to describe the return type and conform the concrete implementation to it, i.e:

```swift
protocol OutgoingConnectionnDataProtocol<IPAddressType> {
   associated type IPAddressType: IPAddress

   var ip: IPAddressType { get }
   var isMullvadExit: Bool { get }
}
```


<!-- Sent from Reviewable.io -->

2023-11-13 12:45 UTC, pronebird requested changes
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 15 of 16 files reviewed, 7 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/View controllers/Tunnel/TunnelViewControllerInteractor.swift` line 46 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-Nj7hMfT6h2usdirLGpS:-Nj7hMfT6h2usdirLGpT:badwyhk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f544b7129410edfc84e3c3a18eacfaafececfdb/ios/MullvadVPN/View%20controllers/Tunnel/TunnelViewControllerInteractor.swift#L46)):*
> ```Swift
>                 guard let self else { return }
>                 outgoingConnectionTask?.cancel()
>                 switch tunnelStatus.state {
> ```

Fallthrough and default case are somewhat considered enemies unless used with care, akin to `goto` in the good old days. Since you're only interested in `connected` state, you could rewrite it as a simple `if case .connected = ..` and then you eliminate both `fallthrough` and `default` case this way.


<!-- Sent from Reviewable.io -->

2023-11-13 12:53 UTC, pronebird reviewed
> Reviewed 5 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: all files reviewed, 7 unresolved discussions (waiting on @mojganii and @rablador)



<!-- Sent from Reviewable.io -->

2023-11-13 13:34 UTC, rablador approved these changes
> Reviewed 2 of 4 files at r3, 8 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pronebird)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 83 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NioVJIl8TGpSXbp8nQC:-Nj7qIq51xwwpRHyTOnc:b-o6k8fj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/95e79f8bf177e42bd93a1c9b135baf9287500210/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L83)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

I don't mind it either way (in separate file or in here). You could however prefer a separate file if you want to mock the actual implementation, for example when you only need to include the protocol definition in the tests bundle.
</blockquote></details>

I think it's fine to combine them if they're tightly coupled/associated with each other.
___
*[`ios/MullvadVPN/View controllers/Tunnel/TunnelViewControllerInteractor.swift` line 46 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-Nj7hMfT6h2usdirLGpS:-Nj7s7Vz5lTy1lY0xB2H:b32v57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f544b7129410edfc84e3c3a18eacfaafececfdb/ios/MullvadVPN/View%20controllers/Tunnel/TunnelViewControllerInteractor.swift#L46)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Fallthrough and default case are somewhat considered enemies unless used with care, akin to `goto` in the good old days. Since you're only interested in `connected` state, you could rewrite it as a simple `if case .connected = ..` and then you eliminate both `fallthrough` and `default` case this way.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2023-11-13 19:22 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 13 of 19 files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadVPN/View controllers/Tunnel/TunnelViewControllerInteractor.swift` line 46 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-Nj7hMfT6h2usdirLGpS:-Nj97f1XBZQmPywwJxGk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5f544b7129410edfc84e3c3a18eacfaafececfdb/ios/MullvadVPN/View%20controllers/Tunnel/TunnelViewControllerInteractor.swift#L46)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-14 08:50 UTC, rablador approved these changes
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @pronebird)



<!-- Sent from Reviewable.io -->

2023-11-14 10:44 UTC, buggmagnet approved these changes
> Reviewed 1 of 4 files at r3, 3 of 6 files at r8, 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 18 of 19 files reviewed, 5 unresolved discussions (waiting on @mojganii, @pronebird, and @rablador)



<!-- Sent from Reviewable.io -->

2023-11-14 11:30 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r5, 1 of 6 files at r8, 1 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 18 of 19 files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadREST/RESTDefaults.swift` line 17 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NjCTy8X1dkKLgUF7QIN:-NjCTy8Y20TgShOcvDuw:b-2y8ioh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b90ae3cea1892a711912a5ef63cec34c54292d44/ios/MullvadREST/RESTDefaults.swift#L17)):*
> ```Swift
> 
>     /// Exit ipV4  API hostname.
>     public static let ipV4APIHostname = "ipv4.am.i.mullvad.net"
> ```

Nit: Maybe we should call it `exitIPv4Hostname` and `exitIPv6Hostname` instead because IPv4/6 API hostname sounds like the way we reach to `api.mullvad.net`. These are two different services however.


<!-- Sent from Reviewable.io -->

2023-11-14 11:44 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 18 of 19 files reviewed, 4 unresolved discussions (waiting on @buggmagnet, @pronebird, and @rablador)

___
*[`ios/MullvadREST/RESTDefaults.swift` line 17 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NjCTy8X1dkKLgUF7QIN:-NjCcB2O93lZJRVIjQhT:b-896fjx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b90ae3cea1892a711912a5ef63cec34c54292d44/ios/MullvadREST/RESTDefaults.swift#L17)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Nit: Maybe we should call it `exitIPv4Hostname` and `exitIPv6Hostname` instead because IPv4/6 API hostname sounds like the way we reach to `api.mullvad.net`. These are two different services however.
</blockquote></details>

Done
___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 15 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-Nj7fgUjAMBknnrgmP3H:-NjCcaLPDT6z6GxAueek:b-b6ub6z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aab41f1b519852fc8a8d9eccb351aec6fe3ea888/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L15)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

The protocol should not reference a type from a concrete implementation. 

Consider moving the `IPV*ConnectionData` outside of concrete implementation, perhaps somewhere next to protocol. 

Alternatively use a protocol to describe the return type and conform the concrete implementation to it, i.e:

```swift
protocol OutgoingConnectionnDataProtocol<IPAddressType> {
   associated type IPAddressType: IPAddress

   var ip: IPAddressType { get }
   var isMullvadExit: Bool { get }
}
```
</blockquote></details>

this approach adds more complexity. Apple is using the same format for `Codable`



_Code snippet:_
```Swift
public typealias Codable = Decodable & Encodable
```


<!-- Sent from Reviewable.io -->

2023-11-14 12:51 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: 18 of 19 files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 15 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-Nj7fgUjAMBknnrgmP3H:-NjCr4Md8OyfH-jVPzsP:b7uyam6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aab41f1b519852fc8a8d9eccb351aec6fe3ea888/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L15)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

this approach adds more complexity. Apple is using the same format for `Codable`
</blockquote></details>

Extract the concrete value types 
___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 88 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NjCs_PIEUE8jq2U-aWh:-NjCs_PIEUE8jq2U-aWi:b-bjkod1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b90ae3cea1892a711912a5ef63cec34c54292d44/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L88)):*
> ```Swift
> 
>         } catch {
>             throw error
> ```

do-catch is superficial as it doesn't do anything but rethrow an error. You can eliminate it to streamline the code.


<!-- Sent from Reviewable.io -->

2023-11-14 15:11 UTC, rablador approved these changes
> Reviewed 3 of 3 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2023-11-15 08:41 UTC, buggmagnet approved these changes
> Reviewed 1 of 9 files at r4, 1 of 6 files at r8, 1 of 3 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2023-11-15 11:09 UTC, pronebird reviewed
> Reviewed 1 of 9 files at r4, 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2023-11-15 11:21 UTC, pronebird reviewed
> Reviewed 2 of 9 files at r4, 2 of 3 files at r9, 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2023-11-15 12:37 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 15 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-Nj7fgUjAMBknnrgmP3H:-NjHyWIh3hu8hCzZ3khB:b-gs1285) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aab41f1b519852fc8a8d9eccb351aec6fe3ea888/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L15)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Extract the concrete value types
</blockquote></details>

To follow up on that. If the `IPv{4|6}ConnectionData` is a requirement of the `OutgoingConnectionHandling` protocol, then it's better to keep the connection data type around the protocol and not embed it into the concrete implementation to avoid cross-dependencies.


<!-- Sent from Reviewable.io -->

2023-11-15 13:27 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2023-11-15 13:55 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: all files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 15 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-Nj7fgUjAMBknnrgmP3H:-NjHvB85-kYemjCInR6p:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aab41f1b519852fc8a8d9eccb351aec6fe3ea888/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L15)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Extract the concrete value types
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 88 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-NjCs_PIEUE8jq2U-aWh:-NjHvdRtE05Mdn8TUmGk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b90ae3cea1892a711912a5ef63cec34c54292d44/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L88)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

do-catch is superficial as it doesn't do anything but rethrow an error. You can eliminate it to streamline the code.
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/OutgoingConnectionProxy+Stub.swift` line 12 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-Nj7UNsN3u8AP96WPpp6:-NjI1lSd1Q15cnSxY8gZ:b-7rl0kd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aab41f1b519852fc8a8d9eccb351aec6fe3ea888/ios/MullvadVPNTests/OutgoingConnectionProxy%2BStub.swift#L12)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
Technically we don't need this `hasError`
We could have just made error an Optional, and then in the get function do
```swift
guard let error else { return ipVXXX }
throw error
```

But not a big deal
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-11-15 14:01 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396#-:-NjIHRDO3-kUKsrli_uT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-15 14:55 UTC, buggmagnet reviewed
> Reviewed 6 of 7 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5396)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-15 14:58 UTC, merged