Update iOS changelog
mullvad/mullvadvpn-app pull request #5404
Opened 2023-11-07 15:49 UTC by pinkisemils

I've updated the changelog to be somewhat current. Do tell me if it's missing some recent changes.

2023-11-07 15:51 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5404)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ios/CHANGELOG.md` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5404#-NieT_263nGHgcrQWV8o:-NieT_263nGHgcrQWV8p:bbk55o2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4c10d91936fd51f048c398632f8c8e64619ae7d/ios/CHANGELOG.md#L32)):*
> ```Markdown
> ## [2023.6 - 2023-10-12]
> ### Removed
> - Remove voucher redemption from the app
> ```

Correct me if I am wrong, but I don't believe we were able to release voucher redemption and therefore this changes never made it to production.


<!-- Sent from Reviewable.io -->

2023-11-07 16:42 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5404)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ios/CHANGELOG.md` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5404#-NieeQooCwO1OvzXiVYS:-NieeQooCwO1OvzXiVYT:b-dhwyfz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4c10d91936fd51f048c398632f8c8e64619ae7d/ios/CHANGELOG.md#L25)):*
> ```Markdown
> 
> ## [Unreleased]
> ### Added
> ```

Packet tunnel: start timeout (60s) introduced since iOS 16.5 was fixed by @rablador 


<!-- Sent from Reviewable.io -->

2023-11-07 20:35 UTC, MrChocolatine commented on ios/CHANGELOG.md
> +- Remove voucher redemption from the app
Simply because I see your changes add a final stop to all entries.

```suggestion
- Remove voucher redemption from the app.
```

2023-11-08 12:46 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5404)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2023-11-09 16:23 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5404)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @MrChocolatine, @pronebird, and @rablador)

___
*[`ios/CHANGELOG.md` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5404#-NieeQooCwO1OvzXiVYS:-NiotDIj3KVCGgknF_Ky:biyd1e9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4c10d91936fd51f048c398632f8c8e64619ae7d/ios/CHANGELOG.md#L25)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Packet tunnel: start timeout (60s) introduced since iOS 16.5 was fixed by @rablador
</blockquote></details>

We don't need to list bugfixes for bugs that have not been released :wink: 
___
*[`ios/CHANGELOG.md` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5404#gh-1385532684:-NiotClcAKndcwQLI10J:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4c10d91936fd51f048c398632f8c8e64619ae7d/ios/CHANGELOG.md#L32)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

Simply because I see your changes add a final stop to all entries.

```suggestion
- Remove voucher redemption from the app.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-10 09:02 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5404#-:-NisSwlH8nKCWLfBTc9I:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @MrChocolatine, @pronebird, and @rablador)



<!-- Sent from Reviewable.io -->

2023-11-10 09:03 UTC, merged

2023-11-10 09:11 UTC, mojganii reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5404#-:-NisV2o0Dit4dCKaPMwF:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @MrChocolatine, @pronebird, and @rablador)



<!-- Sent from Reviewable.io -->