Save WireGuard obfuscation settings choice and move DNS settings to a custom view
mullvad/mullvadvpn-app pull request #5433
Opened 2023-11-14 10:27 UTC by buggmagnet

This PR is mostly accomplishing 2 goals:
- Wiring up the WireGuard obfuscation settings to be saved in the tunnel settings
- Separating the WireGuard settings and the DNS settings into 2 different screens

The PR looks big, but most of the code is just being moved around.
The aim was to declutter `PreferencesDataSource`, parts of it were moved to `CustomDNSDataSource`

Here's what it looked like before the changes
![Screenshot 2023-11-14 at 11 25 04](https://github.com/mullvad/mullvadvpn-app/assets/129761703/f777e75d-1705-4476-9657-c0e1e19be3c9)

Here's what it looks like after the changes

![Screenshot 2023-11-14 at 11 25 36](https://github.com/mullvad/mullvadvpn-app/assets/129761703/ae2f1749-44b6-4315-aea0-a973a4205e9c)

![Screenshot 2023-11-14 at 11 25 49](https://github.com/mullvad/mullvadvpn-app/assets/129761703/8ca0211b-b4f3-43fa-a70e-b9a9dcb85b02)

2023-11-15 08:26 UTC, rablador requested changes
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5433)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/Preferences/CustomDNSDataSource.swift` line 247 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5433#-NjDOk780k5Dyo7cI6wR:-NjDOk780k5Dyo7cI6wS:byquu61) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05da1a8f24c72cd9b9318c96d232fdf0feff4b66/ios/MullvadVPN/View%20controllers/Preferences/CustomDNSDataSource.swift#L247)):*
> ```Swift
>     // MARK: - UITableViewDelegate
> 
>     func tableView(_ tableView: UITableView, shouldHighlightRowAt indexPath: IndexPath) -> Bool {
> ```

Do we need this?
___
*[`ios/MullvadVPN/View controllers/Preferences/CustomDNSDataSource.swift` line 358 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5433#-NjDRC32-2iOja84847R:-NjDRC32-2iOja84847S:b-fpb02y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05da1a8f24c72cd9b9318c96d232fdf0feff4b66/ios/MullvadVPN/View%20controllers/Preferences/CustomDNSDataSource.swift#L358)):*
> ```Swift
>     private func updateSnapshot(animated: Bool = false, completion: (() -> Void)? = nil) {
>         var newSnapshot = NSDiffableDataSourceSnapshot<Section, Item>()
>         let oldSnapshot = snapshot()
> ```

Diffdatasource figures things out this internally and does the diffing by itself, so I think we should remove oldSnapshot and get the identifiers from Item enum directly instead.


<!-- Sent from Reviewable.io -->

2023-11-15 13:27 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5433)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Preferences/CustomDNSDataSource.swift` line 247 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5433#-NjDOk780k5Dyo7cI6wR:-NjI6UaHCoSRoIAdqSmi:b-947p1c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05da1a8f24c72cd9b9318c96d232fdf0feff4b66/ios/MullvadVPN/View%20controllers/Preferences/CustomDNSDataSource.swift#L247)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Do we need this?
</blockquote></details>

[highlightedRows.mov](https://files.reviewableusercontent.io/images/reviewable/129761703/cZLebM8wSNGk7b_WWRBr5KWP/highlightedRows.mov)
This is what happens if we don't have it (notice how the rows change colors as I tap on them)
___
*[`ios/MullvadVPN/View controllers/Preferences/CustomDNSDataSource.swift` line 358 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5433#-NjDRC32-2iOja84847R:-NjI8xruAJcgcN87AVex:boqdph7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05da1a8f24c72cd9b9318c96d232fdf0feff4b66/ios/MullvadVPN/View%20controllers/Preferences/CustomDNSDataSource.swift#L358)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Diffdatasource figures things out this internally and does the diffing by itself, so I think we should remove oldSnapshot and get the identifiers from Item enum directly instead.
</blockquote></details>

I tried to implement that, but it didn't work. 

My understanding is that we still need the old snapshot when we collapse sections, and when we toggle editing mode to avoid the section collapsing if was expanded prior to that I think.

Or maybe I misunderstood your suggestion, how would it look ?

Here's what I tried

```swift
var newSnapshot = NSDiffableDataSourceSnapshot<Section, Item>()
newSnapshot.appendSections(Section.allCases)
newSnapshot.appendItems(Item.contentBlockers, toSection: .contentBlockers)

```


<!-- Sent from Reviewable.io -->

2023-11-16 12:28 UTC, rablador requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5433)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/Preferences/CustomDNSDataSource.swift` line 358 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5433#-NjDRC32-2iOja84847R:-NjN1-aODbuU92fQJoJi:byr1pis) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05da1a8f24c72cd9b9318c96d232fdf0feff4b66/ios/MullvadVPN/View%20controllers/Preferences/CustomDNSDataSource.swift#L358)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I tried to implement that, but it didn't work. 

My understanding is that we still need the old snapshot when we collapse sections, and when we toggle editing mode to avoid the section collapsing if was expanded prior to that I think.

Or maybe I misunderstood your suggestion, how would it look ?

Here's what I tried

```swift
var newSnapshot = NSDiffableDataSourceSnapshot<Section, Item>()
newSnapshot.appendSections(Section.allCases)
newSnapshot.appendItems(Item.contentBlockers, toSection: .contentBlockers)

```
</blockquote></details>

Ah yes, entering edit mode makes things more complicated. Ok, let's leave it as it is.


<!-- Sent from Reviewable.io -->

2023-11-21 10:44 UTC, rablador approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5433)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-22 15:34 UTC, merged