Error handling for location argument in CLI 435
mullvad/mullvadvpn-app pull request #5462
Opened 2023-11-17 14:41 UTC by Serock3

Make the CLI arguments that parse `LocationArgs` validate the input. Specifically, make sure that the country or host exists and, if hostname is given, then validate the server type (e.g. only bridge host for the bridge command).

Some braking changes to the CLI were done, see the changelog.

You can no longer enter the blocked state through `mullvad relay set location xx`. Instead a hidden command `mullvad debug block-connection` was added. See issue https://linear.app/mullvad/issue/DES-453/update-test-instructions-to-use-new-block-command about updating test instruction.

2023-11-17 15:15 UTC, MrChocolatine commented on CHANGELOG.md
> +- Validate that hostname matches correct server type type for CLI commands `mullvad relay set location`, `mullvad bridge set location` and `mullvad relay set tunnel wireguard entry location`
```suggestion
- Validate that hostname matches correct server type for CLI commands `mullvad relay set location`, `mullvad bridge set location` and `mullvad relay set tunnel wireguard entry location`
```

2023-11-22 08:44 UTC, MarkusPettersson98 requested changes
Great job! :tada: 
See my (minor) comments. After you are done squashing, I will sign the `Cargo.lock`-file and merge this PR for you :blush: 

> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5462#-:-NjqBgjZ-rG7FCaxrSSj:b4vygnx)* status: all files reviewed, 5 unresolved discussions (waiting on @Serock3)

___
*[`mullvad-cli/src/cmds/relay.rs` line 345 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5462#-Njq4rNQAQhNkaUR1iYD:-Njq4rNQAQhNkaUR1iYE:b-mszdob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/506fe115792396e73b00075ded20538a2b0235f5/mullvad-cli/src/cmds/relay.rs#L345)):*
> ```XML
> 
>     async fn list() -> Result<()> {
>         let mut countries = get_active_non_bridge_relays().await?;
> ```

If I would be a little nit-picky here, I suggest changing this function's name to `get_active_relays`. 
Bridge relays are most often talked about as just bridges, and "non-bridge" relays are refereed to as just relays.



_Code quote:_
```XML
get_active_non_bridge_relays()
```
___
*[`mullvad-cli/src/cmds/relay.rs` line 935 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5462#-Njq7B9t68VNpHlr8soQ:-Njq7B9t68VNpHlr8soR:b-iwro0g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/506fe115792396e73b00075ded20538a2b0235f5/mullvad-cli/src/cmds/relay.rs#L935)):*
> ```XML
> /// Parses the [`LocationArgs`] into a [`Constraint<GeographicLocationConstraint>`].
> ///
> /// See the documentation of [SetCommands] (`mullvad relay set location`) for a description
> ```

These should be the swapped:
```
[`mullvad relay set location`](SetCommands)
```
Love the detailed doc-comments with links! :raised_hands: 



_Code quote:_
```XML
[SetCommands] (`mullvad relay set location`)
```
___
*[`mullvad-cli/src/cmds/relay.rs` line 967 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5462#-Njq8t1b2EWkxafut0yp:-Njq8t1b2EWkxafut0yq:b-7iwyew) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/506fe115792396e73b00075ded20538a2b0235f5/mullvad-cli/src/cmds/relay.rs#L967)):*
> ```XML
>             Constraint::from(location_constraint_args);
> 
>         // If the location constraint was not "any", the validate the country/city
> ```

then*



_Code quote:_
```XML
the
```
___
*[`mullvad-cli/src/cmds/relay.rs` line 981 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5462#-Njq97VY-KEeRDDCPLO6:-Njq97VY-KEeRDDCPLO7:bit2jh8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/506fe115792396e73b00075ded20538a2b0235f5/mullvad-cli/src/cmds/relay.rs#L981)):*
> ```XML
> 
> /// Return a list of all relays that are active and not bridges
> pub async fn get_active_non_bridge_relays() -> Result<Vec<RelayListCountry>> {
> ```

See previous comment regarding the naming of relays / bridges :blush: 



_Code quote:_
```XML
get_active_non_bridge_relays()
```


<!-- Sent from Reviewable.io -->

2023-11-23 13:44 UTC, Serock3 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5462)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @MarkusPettersson98 and @MrChocolatine)

___
*[`CHANGELOG.md` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5462#gh-1397469501:-NjrPAU0Bms_d2BP1Z9W:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0c3777e0647c046857c76cb7ff414d7207f47bd6/CHANGELOG.md#L62)):*
<details><summary><i>Previously, MrChocolatine wrote…</i></summary><blockquote>

```suggestion
- Validate that hostname matches correct server type for CLI commands `mullvad relay set location`, `mullvad bridge set location` and `mullvad relay set tunnel wireguard entry location`
```
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/relay.rs` line 345 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5462#-Njq4rNQAQhNkaUR1iYD:-NjrPCLY1AWv7XRuN07k:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/506fe115792396e73b00075ded20538a2b0235f5/mullvad-cli/src/cmds/relay.rs#L345)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

If I would be a little nit-picky here, I suggest changing this function's name to `get_active_relays`. 
Bridge relays are most often talked about as just bridges, and "non-bridge" relays are refereed to as just relays.
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/relay.rs` line 935 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5462#-Njq7B9t68VNpHlr8soQ:-NjrPDVu1-EB1vWOUlyu:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/506fe115792396e73b00075ded20538a2b0235f5/mullvad-cli/src/cmds/relay.rs#L935)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

These should be the swapped:
```
[`mullvad relay set location`](SetCommands)
```
Love the detailed doc-comments with links! :raised_hands:
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/relay.rs` line 967 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5462#-Njq8t1b2EWkxafut0yp:-NjrPEPE0s0drC2Qp8nG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/506fe115792396e73b00075ded20538a2b0235f5/mullvad-cli/src/cmds/relay.rs#L967)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

then*
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/relay.rs` line 981 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5462#-Njq97VY-KEeRDDCPLO6:-NjrPE7mBnktJL12DO6O:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/506fe115792396e73b00075ded20538a2b0235f5/mullvad-cli/src/cmds/relay.rs#L981)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

See previous comment regarding the naming of relays / bridges :blush:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-23 13:47 UTC, MarkusPettersson98 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5462#-:-NjwQu1qB8qv0MFRlkPM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MrChocolatine)



<!-- Sent from Reviewable.io -->

2023-11-23 14:17 UTC, MarkusPettersson98 approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5462)* status: all files reviewed, 1 unresolved discussion (waiting on @MrChocolatine)



<!-- Sent from Reviewable.io -->

2023-11-23 14:36 UTC, merged