Have the PacketTunnel use UDP-over-TCP Obfuscation
mullvad/mullvadvpn-app pull request #5489
Opened 2023-11-23 08:23 UTC by buggmagnet

This PR makes the `PacketTunnelActor` use the `UDPOverTCPObfuscator` via the generic `ProtocolObfuscator`
The following considerations were taken into account:
- We plan to have multiple obfuscators in the future (Hence the generic `ProtocolObfuscator`)
- The retry logic is based on the desktop's [RelaySelector logic](https://github.com/mullvad/mullvadvpn-app/blob/main/mullvad-relay-selector/src/lib.rs) and [documentation](https://github.com/mullvad/mullvadvpn-app/blob/main/docs/relay-selector.md#default-constraints-for-tunnel-endpoints)
- I decided to not implement the logic inside our `RelaySelector` to avoid code bloat

### How to test
- Build the app
- Go to Settings > VPN Settings
- Select any of the options in WireGuard Obfuscation and UDP-over-TCP port

### How to verify UDP-over-TCP Obfuscation is in use
- Connect your debugger to the packet tunnel
- Open the Debug Navigator in Xcode
- Tap on the `Network` pane
- Verify that the endpoint you're connected to is using the TCP protocol (you should see either port 80 or 5001 based on what option you chose)

### Not included in this PR
- The UI won't reflect the protocol used when connected to the tunnel, this will come in a future PR

2023-11-24 08:13 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489)* status: 0 of 21 files reviewed, 1 unresolved discussion

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 250 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-Nk-Nabn4SPD6EJ2Q8hl:-Nk-Nabn4SPD6EJ2Q8hm:b-2htxf3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fc75674153bafb42bfe6456380f4fa3ff32b7027/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L250)):*
> ```Swift
> 
>         var endpoint = connectionState.selectedRelay.endpoint
>         endpoint = protocolObfuscator.obfuscate(
> ```

Working on the next part, I'm realizing this place is a bit too late in the process to get the obfuscator info, because at this point, the `connectionState` is already realized, meaning we cannot resurface the transport layer in there (whether we are connecting via TCP or UDP to the `MullvadEndpoint`, and therefore cannot get the correct info to show in the UI.

Please disregard where we do this for now, it will be fixed in the next PR.


<!-- Sent from Reviewable.io -->

2023-11-28 10:38 UTC, rablador requested changes
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 249 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkK3Ng60kEQLawu3gGL:-NkK3Ng60kEQLawu3gGM:b-yp26bw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L249)):*
> ```Swift
>         }
> 
>         var endpoint = connectionState.selectedRelay.endpoint
> ```

Nit: Keep a let assignment here and supply `connectionState.selectedRelay.endpoint` directly to the `obfuscate` function instead. Less confusing in what's used for what.
___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkK611481SSKZZZuw2C:-NkK611481SSKZZZuw2D:b-jqmgvd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L26)):*
> ```Swift
>         let shouldObfuscate = switch settings.obfuscation.state {
>         case .automatic:
>             retryAttempts % 4 == 2 || retryAttempts % 4 == 3
> ```

A small comment on why selection is done this way would be great.
___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkK6uKfEwLJNMuBpYtE:-NkK6uKfEwLJNMuBpYtF:b2y82hs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L38)):*
> ```Swift
>         }
>         var tcpPort = settings.obfuscation.port
>         if settings.obfuscation.port == .automatic {
> ```

Nit: `if tcpPort == [...] {`
___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkK75A2B0N9I1Ao22cE:-NkK75A2B0N9I1Ao22cF:bd2258o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L39)):*
> ```Swift
>         var tcpPort = settings.obfuscation.port
>         if settings.obfuscation.port == .automatic {
>             tcpPort = retryAttempts % 2 == 0 ? .port80 : .port5001
> ```

This is not really random, but maybe that's ok.
___
*[`ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkKAeT23XZkiwR5zIWe:-NkKAeT23XZkiwR5zIWf:bmi5fao) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift#L75)):*
> ```Swift
>     }
> 
>     func testObfuscateAutomaticIsPort80EveryThirdAttempts() throws {
> ```

Every third attempt, but test states 6 retries?
___
*[`ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift` line 83 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkKAtx3C57qo4cKnoI8:-NkKAtx3C57qo4cKnoI9:b-a1rmsq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift#L83)):*
> ```Swift
>     }
> 
>     func testObfuscateAutomaticIsPort5001EveryFourthAttempts() throws {
> ```

Every fourth attempt, but test states 7 retries?


<!-- Sent from Reviewable.io -->

2023-11-28 12:55 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489)* status: all files reviewed, 7 unresolved discussions (waiting on @rablador)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 249 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkK3Ng60kEQLawu3gGL:-NkKpC1N20VNN1Vu5HAQ:bx40i2m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L249)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Keep a let assignment here and supply `connectionState.selectedRelay.endpoint` directly to the `obfuscate` function instead. Less confusing in what's used for what.
</blockquote></details>

As I wrote in the other comment, please ignore this part, it will get ironed out in the next PR.
___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkK611481SSKZZZuw2C:-NkKzkLM0Wzz03jCQ1Xc:b-3okdf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L26)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

A small comment on why selection is done this way would be great.
</blockquote></details>

Agreed, I've added comments to the function to explain where the logic is sourced from
___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkK6uKfEwLJNMuBpYtE:-NkKvyfvDxJfEOs7IQQQ:b-8wzub6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L38)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: `if tcpPort == [...] {`
</blockquote></details>

I'm sorry, but I don't understand your suggestion. Can you clarify ?
___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkK75A2B0N9I1Ao22cE:-NkKw50h6ambvWobOvao:b37k58m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L39)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This is not really random, but maybe that's ok.
</blockquote></details>

It's not meant to be random, if obfuscation is on, we always alternate between ports 80 and 5001.
___
*[`ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkKAeT23XZkiwR5zIWe:-NkKzdyB6AM-Ym1qRgOR:b-x50yh8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift#L75)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Every third attempt, but test states 6 retries?
</blockquote></details>

6 is a multiple of 3
___
*[`ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift` line 83 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkKAtx3C57qo4cKnoI8:-NkKzYs6AZiwVXzBK-Bd:bj308t9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift#L83)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Every fourth attempt, but test states 7 retries?
</blockquote></details>

Remember, we start counting from 0


<!-- Sent from Reviewable.io -->

2023-11-29 09:26 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489)* status: 20 of 21 files reviewed, 10 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkLjqNPBIU3QO-zLOdc:-NkLjqNPBIU3QO-zLOdd:b-rigzy6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c05db76412a36cec1a7e627222437692ced9d1bb/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L59)):*
> ```Swift
>         relaySelector: RelaySelectorProtocol,
>         settingsReader: SettingsReaderProtocol,
>         protocolObfuscator: ProtocolObfuscation = ProtocolObfuscator<UDPOverTCPObfuscator>()
> ```

since the you considered obfuscation generic for the matter of that it can have different implementation.may be it's not a good idea consider that as a default value in constructor.I would suggest let it pass when it's been creating
___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkK75A2B0N9I1Ao22cE:-NkPMU8i-I9lBeR1PePp:btj24vg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L39)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It's not meant to be random, if obfuscation is on, we always alternate between ports 80 and 5001.
</blockquote></details>

the above comment goes for this if we are going to alternate between ports in diffrent implementaion
___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkPKlsO6vZ9uuR6x0kV:-NkPKlsO6vZ9uuR6x0kW:budwid9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c05db76412a36cec1a7e627222437692ced9d1bb/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L33)):*
> ```Swift
>     public func obfuscate(_ endpoint: MullvadEndpoint, settings: Settings, retryAttempts: UInt = 0) -> MullvadEndpoint {
>         var obfuscatedEndpoint = endpoint
>         let shouldObfuscate = switch settings.obfuscation.state {
> ```

If I were you I would keep it as a comupted property into file scope.specially it can be used in the other objects that conform `ProtocolObfuscation`



_Code snippet:_
```Swift
fileprivate extension WireGuardObfuscationState {
    var shouldObfuscate  : Bool {
        switch settings.obfuscation.state {
        case .automatic:
            retryAttempts % 4 == 2 || retryAttempts % 4 == 3
        case .on:
            true
        case .off:
            false
        }
    }
}
```
___
*[`ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift` line 91 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkPODci0dyc9s7o5YjP:-NkPODci0dyc9s7o5YjQ:b98nbpf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c05db76412a36cec1a7e627222437692ced9d1bb/ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift#L91)):*
> ```Swift
>     }
> 
>     func validate(
> ```

nit :they should  be private


<!-- Sent from Reviewable.io -->

2023-11-29 10:04 UTC, rablador requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489)* status: all files reviewed, 8 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkK6uKfEwLJNMuBpYtE:-NkLXKS83FcREGgQdw6s:b-g7ceth) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L38)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I'm sorry, but I don't understand your suggestion. Can you clarify ?
</blockquote></details>

You assign `tcpPort` and then on the next line use `settings.obfuscation.port` instead of the newly assigned variable.
___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkK75A2B0N9I1Ao22cE:-NkLXXIADj_muXu-Y1O9:b-48zcge) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L39)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

the above comment goes for this if we are going to alternate between ports in diffrent implementaion
</blockquote></details>

Looked at the retry logic documentation now and it checks out.
___
*[`ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkKAeT23XZkiwR5zIWe:-NkLXifi0eDGgKjNSPl4:b-n8g1e3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift#L75)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

6 is a multiple of 3
</blockquote></details>

Hehe, yes, indeed, but that's not the problem. This test and the next look inconsistent when put next to each other since - at a glance - the first seems to have a retry count starting from 1 and the other 0. Reading through the retry logic documentation it's clear how this works, but if the tests had 2 and 3 for retry counts they would read more intuititvely.

Maybe doing it the current way is better since it tests the logic further down the chain of retries, but one would probably need to read up on the documentation to fully understand it.
___
*[`ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift` line 83 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkKAtx3C57qo4cKnoI8:-NkPX3Mz5mw9mX4Xkit9:b-otilcs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift#L83)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Remember, we start counting from 0
</blockquote></details>

See comment above.


<!-- Sent from Reviewable.io -->

2023-11-29 13:28 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489)* status: all files reviewed, 6 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkLjqNPBIU3QO-zLOdc:-NkQDjD39m9J37SHUNue:bxwbob9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c05db76412a36cec1a7e627222437692ced9d1bb/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L59)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

since the you considered obfuscation generic for the matter of that it can have different implementation.may be it's not a good idea consider that as a default value in constructor.I would suggest let it pass when it's been creating
</blockquote></details>

For now we don't have any other obfuscation, more will come, and when that happens, we can change this.
Otherwise, sure I can change where it's passed.
___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkK6uKfEwLJNMuBpYtE:-NkPt0mlEbsiZn_PYIO3:b8wkpw9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L38)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

You assign `tcpPort` and then on the next line use `settings.obfuscation.port` instead of the newly assigned variable.
</blockquote></details>

_ooohhhhh_ I see. Yes you're absolutely right, thanks for catching that !
___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkK75A2B0N9I1Ao22cE:-NkQFav_0rs9uU2Fyz_I:b-kaia83) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L39)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Looked at the retry logic documentation now and it checks out.
</blockquote></details>

I'll mark this as resolved then 
___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkPKlsO6vZ9uuR6x0kV:-NkPscUOCjt2oQQYCypj:bq51kbi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c05db76412a36cec1a7e627222437692ced9d1bb/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L33)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

If I were you I would keep it as a comupted property into file scope.specially it can be used in the other objects that conform `ProtocolObfuscation`
</blockquote></details>

How do you pass the `retryAttempts` in that computed property ?
___
*[`ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkKAeT23XZkiwR5zIWe:-NkQDRGu5TIshZ6gvz50:bncjcdd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cf50d88d64286fc9f3ab04c8e7a20ed70beebff6/ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift#L75)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Hehe, yes, indeed, but that's not the problem. This test and the next look inconsistent when put next to each other since - at a glance - the first seems to have a retry count starting from 1 and the other 0. Reading through the retry logic documentation it's clear how this works, but if the tests had 2 and 3 for retry counts they would read more intuititvely.

Maybe doing it the current way is better since it tests the logic further down the chain of retries, but one would probably need to read up on the documentation to fully understand it.
</blockquote></details>

Yes sorry I should have made that clearer in my previous answer.
A value of 3 would fail the test because of the requirements.
This is why I used 6 here instead. 
___
*[`ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift` line 91 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkPODci0dyc9s7o5YjP:-NkQFnLi8Y3gna00xUN4:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c05db76412a36cec1a7e627222437692ced9d1bb/ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift#L91)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit :they should  be private
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-29 15:30 UTC, rablador approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2023-11-29 16:39 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkPKlsO6vZ9uuR6x0kV:-NkQuHmX2sWvBlV2q8jZ:b45h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c05db76412a36cec1a7e627222437692ced9d1bb/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L33)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

How do you pass the `retryAttempts` in that computed property ?
</blockquote></details>





_Code snippet:_
```Swift
fileprivate extension WireGuardObfuscationState {
    var shouldObfuscate  : (Int) -> Bool {
        { retryAttempts in
            switch self {
            case .automatic:
                retryAttempts % 4 == 2 || retryAttempts % 4 == 3
            case .on:
                true
            case .off:
                false
            }
        }
    }
}
```


<!-- Sent from Reviewable.io -->

2023-11-30 08:47 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2023-11-30 08:52 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift` line 33 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489#-NkPKlsO6vZ9uuR6x0kV:-NkUQPN14FwgxSq-RiX5:b-xkejwb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c05db76412a36cec1a7e627222437692ced9d1bb/ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift#L33)):*
> ```Swift
>     public func obfuscate(_ endpoint: MullvadEndpoint, settings: Settings, retryAttempts: UInt = 0) -> MullvadEndpoint {
>         var obfuscatedEndpoint = endpoint
>         let shouldObfuscate = switch settings.obfuscation.state {
> ```

This was discussed offline and we decided to not go for that approach.


<!-- Sent from Reviewable.io -->

2023-11-30 08:53 UTC, mojganii approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5489)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-30 09:26 UTC, merged