Add API access methods UI/part of backend
mullvad/mullvadvpn-app pull request #5530
Opened 2023-11-30 09:59 UTC by pronebird

This PR introduces the UI and a part of backend for managing API access methods.

### Backend

- AccessMethodRepository - a manager around API access method storage.
- PersistentAccessMethod - a persistent model stored within the access method storage and managed by the repo.
- PersistentProxyConfiguration - a persistent proxy configuration for an access method. Part of PersistentAccessMethod.
- ProxyConfigurationTester - an object responsible for testing API access method configuration. Typically operates on PersistentAccessMethod.
- ShadowsocksCipher - a wrapper type for SS cipher.

#### Backend limitations

- Only provides an in-memory storage.
- It's not wired up into the transport system we have.

### User interface

User interface is implemented using:

- Diffable data sources.
- Combine, mostly `CurrentValueSubject` as it provides a two-way channel, but also is a reference type and can easily be shared between objects.
- Many view controllers use child table view controllers. That's because table view controllers automatically adjust content insets for keyboard.

#### File structure

Current structure puts everything related to the API access methods under `Coordinators/Settings/APIAccess`. As we discussed earlier, I think the file structure should be reworked and perhaps most of it should be uprooted somewhere else and united with `View Controllers/.

Everything under APIAccess is structured either grouped by class of objects having some purpose or by sub-route (i.e Add/Edit/List).

#### Relationships

- Coordinators are at the top, manage view controllers using delegates.
- View controllers are injected with a vide model and intercator object that implements business logic. 
- Interactors mostly follow command pattern and most of methods they implement do not take any arguments. That's because all dependencies are injected by coordinator and the view model is shared between. That makes working with UI a little easier.
- Part of interactor may mutate the view model, this is the case when testing API methods. This eliminates some code duplication.
- View controllers use a sink to react to changes to view model and reconfigure the diffable data source and some other parts of UI.

#### Custom sheet

Part of UI is implemented using a custom action sheet which is put as an overlay above the view controllers when testing existing API access method or adding a new method. See `AccessMethodActionSheetPresentation`.

2023-11-30 12:02 UTC, rablador requested changes
> Reviewed 7 of 96 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: 6 of 96 files reviewed, 5 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/AccessMethodRepository/AccessMethodRepository.swift` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkV-f-E4EzcGS-p0r9X:-NkV-f-E4EzcGS-p0r9Y:b7b0cmt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97e92a7a40c3964822fa537e490087aaa483ba03/ios/MullvadVPN/AccessMethodRepository/AccessMethodRepository.swift#L41)):*
> ```Swift
> 
>     func add(_ method: PersistentAccessMethod) {
>         guard !memoryStore.contains(where: { $0.id == method.id }) else { return }
> ```

Perhaps `PersistentAccessMethod` can adhere to Equatable to facilitate checks like this and others below?
___
*[`ios/MullvadVPN/AccessMethodRepository/AccessMethodRepositoryProtocol.swift` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkV03a79KCJGDfDFI28:-NkV03a79KCJGDfDFI29:bsg0yq2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97e92a7a40c3964822fa537e490087aaa483ba03/ios/MullvadVPN/AccessMethodRepository/AccessMethodRepositoryProtocol.swift#L20)):*
> ```Swift
>     func add(_ method: PersistentAccessMethod)
> 
>     /// Persist modified access method locating existing entry by id.
> ```

Update rather than persist, right?
___
*[`ios/MullvadVPN/AccessMethodRepository/AccessMethodRepositoryProtocol.swift` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkV0FHoEjv2cJZ_LbGT:-NkV0FHoEjv2cJZ_LbGU:b-2hi9r5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97e92a7a40c3964822fa537e490087aaa483ba03/ios/MullvadVPN/AccessMethodRepository/AccessMethodRepositoryProtocol.swift#L33)):*
> ```Swift
>     func fetch(by id: UUID) -> PersistentAccessMethod?
> 
>     /// Fetch all access method from the persistent store.
> ```

Nit: method(s), here and below.
___
*[`ios/MullvadVPN/Containers/Navigation/CustomNavigationController.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkV5abh9SX_kJFN6IFq:-NkV5abh9SX_kJFN6IFr:beym3nt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97e92a7a40c3964822fa537e490087aaa483ba03/ios/MullvadVPN/Containers/Navigation/CustomNavigationController.swift#L11)):*
> ```Swift
> import UIKit
> 
> /// Custom navigation controller that applies the
> ```

Documentation ends mid-sentence.
___
*[`ios/MullvadVPN/Containers/Navigation/CustomNavigationController.swift` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkV5nvM87pxOacOhJ3h:-NkV5nvM87pxOacOhJ3i:b-zftqfr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/97e92a7a40c3964822fa537e490087aaa483ba03/ios/MullvadVPN/Containers/Navigation/CustomNavigationController.swift#L30)):*
> ```Swift
>         super.viewDidLayoutSubviews()
> 
>         // Navigation bar updates the prompt color on layout so we have to force out own appearance on each layout pass.
> ```

Nit: out -> our


<!-- Sent from Reviewable.io -->

2023-11-30 12:03 UTC, rablador reviewed
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: 7 of 96 files reviewed, 3 unresolved discussions (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-11-30 15:47 UTC, rablador requested changes
> Reviewed 2 of 96 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: 20 of 96 files reviewed, 11 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Add/AddAccessMethodViewController.swift` line 252 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkVuSrg7bIphLiAuRFX:-NkVuSrg7bIphLiAuRFY:b-833co7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Add/AddAccessMethodViewController.swift#L252)):*
> ```Swift
>         snapshot.appendItems([.protocol], toSection: .protocol)
>         // Reconfigure the protocol item on the access method change.
>         if let previousValue, previousValue.method != newValue.method {
> ```

Nit: `previousValue doesn't need unwrapping.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/ShadowsocksSectionHandler.swift` line 48 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkVnsvv7VP-wEocRx5Q:-NkVnsvw4g34VctJIRt8:brmqanr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/ShadowsocksSectionHandler.swift#L48)):*
> ```Swift
>         contentConfiguration.editingEvents.onChange = subject.bindTextAction(to: \.shadowsocks.port)
>         contentConfiguration.textFieldProperties = .withSmartFeaturesDisabled()
>         if case .phone = cell.traitCollection.userInterfaceIdiom {
> ```

Why distinguish here?
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksSectionHandler.swift` line 50 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkVt2ZYExFOj4PlUYyx:-NkVt2ZYExFOj4PlUYyy:brmqanr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksSectionHandler.swift#L50)):*
> ```Swift
>         contentConfiguration.editingEvents.onChange = subject.bindTextAction(to: \.socks.port)
>         contentConfiguration.textFieldProperties = .withSmartFeaturesDisabled()
>         if case .phone = cell.traitCollection.userInterfaceIdiom {
> ```

Why distinguish here?


<!-- Sent from Reviewable.io -->

2023-11-30 16:34 UTC, rablador requested changes
> Reviewed 5 of 96 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: 25 of 96 files reviewed, 13 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Add/AddAccessMethodViewController.swift` line 260 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkVv9iS6jdaFxiSlwpr:-NkVv9iS6jdaFxiSlwps:bc0bc40) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Add/AddAccessMethodViewController.swift#L260)):*
> ```Swift
>         }
> 
>         switch newValue.method {
> ```

This switch should go inside the `if newValue.method.hasProxyConfiguration` condition above. If the section isn't present and there's an attempt to add items to it, the app will crash. Maybe in practice one doesn't exist without the other, but I think it's better to be on the safe side.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/ButtonCellContentView.swift` line 49 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkW2OhH3uVZVCD0k17_:-NkW2OhH3uVZVCD0k17a:br61wza) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/ButtonCellContentView.swift#L49)):*
> ```Swift
>     }
> 
>     func configureSubviews(previousConfiguration: ButtonCellContentConfiguration? = nil) {
> ```

This is slightly confusing, since at a glance you would expect that by applying a config you update the view with new data (rather than old). `previousConfiguration` is only passed along here to remove an existing action in `configureActions()`, so maybe it would be better to scrap this function and call `configureButton()` and `configureActions(previousConfiguration: previousConfiguration)` directly from the `var configuration: UIContentConfiguration` setter instead.


<!-- Sent from Reviewable.io -->

2023-12-01 09:16 UTC, rablador requested changes
> Reviewed 6 of 96 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: 33 of 96 files reviewed, 16 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/SwitchCellContentConfiguration.swift` line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkZaA7S-sbWLtxRSJDu:-NkZaA7S-sbWLtxRSJDv:busgi01) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/SwitchCellContentConfiguration.swift#L13)):*
> ```Swift
> /// Content configuration presenting a label and switch control.
> struct SwitchCellContentConfiguration: UIContentConfiguration, Equatable {
>     struct TextProperties: Equatable {
> ```

Duplicate, use the one at the bottom instead.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/SwitchCellContentView.swift` line 97 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkZbfW98AcmTeXV6hjT:-NkZbfW98AcmTeXV6hjU:bp0af9j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/SwitchCellContentView.swift#L97)):*
> ```Swift
> 
>     // MARK: - Accessibility
> ```

If we use the accessibility traits of the switch control, do we really need to set anything in the setters below?
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/TextCellContentConfiguration.swift` line 75 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkZciIJA8TzgeNhGLAd:-NkZciIJA8TzgeNhGLAe:b-sxzrlt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/TextCellContentConfiguration.swift#L75)):*
> ```Swift
> 
>     /// Text field configuration.
>     struct TextFieldProperties: Equatable {
> ```

Although a comprehensive is good in terms of completeness, perhaps we can trim the list where the default is usually desirable anyway. Then we can re-add attributes as needed. Also, we already introduce helpers for common use cases in `extension TextCellContentConfiguration.TextFieldProperties` below, so maybe those could do some of the heavy lifting as well.


<!-- Sent from Reviewable.io -->

2023-12-01 10:51 UTC, rablador reviewed
> Reviewed 3 of 96 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: 36 of 96 files reviewed, 17 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/TextCellContentView.swift` line 109 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkZhNj_E2yTH3OkUdwl:-NkZhNj_E2yTH3OkUdwm:bb8rtfr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/TextCellContentView.swift#L109)):*
> ```Swift
>     }
> 
>     @objc private func handleTap(_ gestureRecognizer: UIGestureRecognizer) {
> ```

Nit: Comment about why we do this.


<!-- Sent from Reviewable.io -->

2023-12-04 13:14 UTC, rablador requested changes
> Reviewed 18 of 96 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: 54 of 96 files reviewed, 26 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksSectionHandler.swift` line 14 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkosPl3EhEJEhk63SjJ:-NkosPl3EhEJEhk63SjK:b-hxmtyq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksSectionHandler.swift#L14)):*
> ```Swift
> /// Type responsible for handling cells in socks table view section.
> struct SocksSectionHandler {
>     let tableStyle: UITableView.Style
> ```

This variable is never used.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift` line 287 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkoaoBz2kG_HD89eWv-:-NkoaoBz2kG_HD89eWv0:b-wcboi9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift#L287)):*
> ```Swift
>     private func onDelete() {
>         interactor.deleteAccessMethod()
>         delegate?.controllerDidDeleteAccessMethod(self)
> ```

Nit: I think the controller here is implied and necessary to spell out.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift` line 292 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkoazBy3aDb9ZDG15c0:-NkoazBy3aDb9ZDG15c1:b-wcboi9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift#L292)):*
> ```Swift
>     private func onSave() {
>         interactor.saveAccessMethod()
>         delegate?.controllerDidSaveAccessMethod(self)
> ```

Nit: I think the controller here is implied and necessary to spell out.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/ProxyConfigurationInteractorProtocol.swift` line 30 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkobS2U5EuErBSoWeT2:-NkobS2U5EuErBSoWeT3:b50fp1e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/ProxyConfigurationInteractorProtocol.swift#L30)):*
> ```Swift
> extension ProxyConfigurationInteractorProtocol {
>     /// Start testing proxy configuration with data from view model.
>     func startProxyConfigurationTest() {
> ```

Can't we remove this variation by simply adding a default nil value to the original function above?
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodCoordinator.swift` line 46 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-Nkowmxn9RwkBfdJRZCY:-Nkowmxn9RwkBfdJRZCZ:bfjkdok) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodCoordinator.swift#L46)):*
> ```Swift
>     private func edit(item: ListAccessMethodItem) {
>         // Remove previous edit coordinator to prevent accumulation.
>         childCoordinators.filter { $0 is EditAccessMethodCoordinator }.forEach { $0.removeFromParent() }
> ```

Why do we do this here? Shouldn't `popToList()` handle this?
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodCoordinator.swift` line 77 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-Nkox6aG5lnaYYPoNlOU:-Nkox6aG5lnaYYPoNlOV:b-iqvglr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodCoordinator.swift#L77)):*
> ```Swift
>         // swiftlint:enable line_length
> 
>         let aboutController = AboutViewController(markdown: aboutMarkdown)
> ```

Nit: Perhaps the constructor can accept a title as well, to let the view controller handle the assignment itself?
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodCoordinator.swift` line 86 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkoxKzr95-8McGaKsc5:-NkoxKzr95-8McGaKsc6:b-435jzw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodCoordinator.swift#L86)):*
> ```Swift
>         )
> 
>         aboutController.navigationItem.rightBarButtonItem = UIBarButtonItem(
> ```

Nit: I think this can be assumed to be standard and therefore handled inside the view controller.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Sheet/Content view/AccessMethodActionSheetConfiguration.swift` line 22 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkothGK43y2JYuVFHOl:-NkothGK43y2JYuVFHOm:b-k0g1u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Sheet/Content%20view/AccessMethodActionSheetConfiguration.swift#L22)):*
> ```Swift
>     ///
>     /// In this context, the sheet only offers user to cancel testing the access method.
>     case proxyConfiguration
> ```

I think we should call this "testing" or something instead, to better reflect what I actually does.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Sheet/Content view/AccessMethodActionSheetContentConfiguration.swift` line 33 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkopYDd4XFQ1dXks9lp:-NkopYDd4XFQ1dXks9lq:bladaoy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Sheet/Content%20view/AccessMethodActionSheetContentConfiguration.swift#L33)):*
> ```Swift
> 
> extension AccessMethodActionSheetContentConfiguration.Status {
>     /// The text label descirbing the status of testing and suitable for user presentation.
> ```

-> "describing"


<!-- Sent from Reviewable.io -->

2023-12-04 14:23 UTC, rablador requested changes
> Reviewed 14 of 96 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: 68 of 96 files reviewed, 30 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodViewController.swift` line 49 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-Nkp-Stv7kzQpJqgCCkz:-Nkp-Stv7kzQpJqgCCl-:bneeuf6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodViewController.swift#L49)):*
> ```Swift
>     }
> 
>     override func viewDidLoad() {
> ```

Nit: Setup has been tidier in other view controllers. Perhaps we can keep it similarly structured?
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodViewController.swift` line 127 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-Nkp2xyz8YobmytOkTsB:-Nkp2xz-5S3jW8rmAdmE:bbzbb4p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodViewController.swift#L127)):*
> ```Swift
>         snapshot.appendItems(itemIdentifiers, toSection: .primary)
> 
>         for newFetchedItem in newFetchedItems {
> ```

Do we really need to do this, seeing that we replace the whole data source with new items on each update anyway?
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodViewControllerDelegate.swift` line 14 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-Nkp3FHu7JRi7n50xj6k:-Nkp3FHu7JRi7n50xj6l:b-7crxh9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodViewControllerDelegate.swift#L14)):*
> ```Swift
>     /// The view controller requests the delegate to present the about view.
>     ///
>     /// - Parameter controller: the calling view controller.
> ```

Nit: I think controller can be implied here, not necessary to include in name.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodViewControllerDelegate.swift` line 19 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-Nkp3OuJD_hhHf8-nHek:-Nkp3OuJD_hhHf8-nHel:b-7crxh9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodViewControllerDelegate.swift#L19)):*
> ```Swift
>     /// The view controller requests the delegate to present the add new method controller.
>     ///
>     /// - Parameter controller: the calling view controller.
> ```

Nit: I think controller can be implied here, not necessary to include in name.


<!-- Sent from Reviewable.io -->

2023-12-04 15:59 UTC, rablador requested changes
> Reviewed 12 of 96 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: 80 of 96 files reviewed, 36 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/PersistentProxyConfiguration+ViewModel.swift` line 15 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkpDTy99mmQ41vj8rkD:-NkpDTyA2NPXAOr_cn3c:b-grot5y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/PersistentProxyConfiguration%2BViewModel.swift#L15)):*
> ```Swift
>     var socksViewModel: AccessMethodViewModel.Socks {
>         guard case let .socks5(config) = self else {
>             return AccessMethodViewModel.Socks()
> ```

This can only happen to an error somewhere, right? If so, I think we should log it. Same for `shadowsocksViewModel` below.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Pickers/AccessMethodProtocolPicker.swift` line 47 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkpEvUp01S7rjoo0vPw:-NkpEvUp01S7rjoo0vPx:b-au9196) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Pickers/AccessMethodProtocolPicker.swift#L47)):*
> ```Swift
>         let method: AccessMethodKind
> 
>         var id: AccessMethodKind { method }
> ```

Nit: Do we need an explicit when it's the same as `medthod`?
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Pickers/ListItemPickerViewController.swift` line 74 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkpQCwx2StUKFUjrN1j:-NkpQCwy1ayat58xzn6n:b3qix90) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Pickers/ListItemPickerViewController.swift#L74)):*
> ```Swift
>         guard !scrolledToSelection else { return }
> 
>         scrolledToSelection = true
> ```

Do we want to set this regardless of if a scroll was made or not?
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Sheet/Content view/AccessMethodActionSheetContentView.swift` line 126 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkpU6TYE1mxhaEl2ymu:-NkpU6TYE1mxhaEl2ymv:bexxiaf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Sheet/Content%20view/AccessMethodActionSheetContentView.swift#L126)):*
> ```Swift
> 
>         // Text label is always the last one, so only add it into the stack if it's not there yet.
>         if textLabel.superview == nil {
> ```

Nit: This is fine, but `if horizontalStackView.arrangedSubviews.contains(textLabel)` feels a little more in line with UI API:s.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Sheet/Presentation/AccessMethodActionSheetPresentation.swift` line 84 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkpVJs4BCmlw5Dn3Mc2:-NkpVJs4BCmlw5Dn3Mc3:bk37ocx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Sheet/Presentation/AccessMethodActionSheetPresentation.swift#L84)):*
> ```Swift
>             self.presentationView.alpha = 0
>         } completion: { position in
>             guard position == .end else { return }
> ```

We should not depend on `.end` here since it only tells us where the animation ended rather than that it ended at the end. If the animation stops at eg. the beginning the view will never be removed.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Sheet/Presentation/AccessMethodActionSheetPresentationView.swift` line 12 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NkpYLy97usYmdZl_yz4:-NkpYLy97usYmdZl_yz5:bz9uwjv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/Coordinators/Settings/APIAccess/Sheet/Presentation/AccessMethodActionSheetPresentationView.swift#L12)):*
> ```Swift
> 
> /// The sheet presentation view implementing a layout similar to the one used by system action sheet.
> class AccessMethodActionSheetPresentationView: UIView {
> ```

Nit: This view mimicks some of the behavior of a UIContentView + config. Maybe it should be converted to a real one instead?


<!-- Sent from Reviewable.io -->

2023-12-04 16:29 UTC, rablador reviewed
> Reviewed 14 of 96 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: all files reviewed, 36 unresolved discussions (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-12-07 15:48 UTC, buggmagnet requested changes
> Reviewed 13 of 96 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: all files reviewed, 39 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/AccessMethodRepository/AccessMethodRepository.swift` line 55 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-Nl3vGA140oPl5yeHPmd:-Nl3vGA140oPl5yeHPme:b-ze8wzf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/AccessMethodRepository/AccessMethodRepository.swift#L55)):*
> ```Swift
>         guard let index = memoryStore.firstIndex(where: { $0.id == id }) else { return }
> 
>         // Prevent removing methods that have static UUIDs and always present.
> ```

nit:
`and are always present`
___
*[`ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift` line 13 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-Nl3w2fU0s6v5Yum67Gs:-Nl3w2fU0s6v5Yum67Gt:b-fexzy7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift#L13)):*
> ```Swift
> 
> /// A concrete implementation of an access method proxy configuration.
> class ProxyConfigurationTester: ProxyConfigurationTesterProtocol {
> ```

nit
Let's schedule to remove this once we have a real implementation
___
*[`ios/MullvadVPN/AccessMethodRepository/ShadowsocksCipher.swift` line 12 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-Nl3wDJv2U5T0dF3dIsL:-Nl3wDJv2U5T0dF3dIsM:bmmr8bj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/882a253122a878aafd85e2aaad32efe3d5a74f10/ios/MullvadVPN/AccessMethodRepository/ShadowsocksCipher.swift#L12)):*
> ```Swift
> 
> /// Type representing a shadowsocks cipher.
> struct ShadowsocksCipher: RawRepresentable, CustomStringConvertible, Equatable, Hashable, Codable {
> ```

this could (should ?) probably be an enum


<!-- Sent from Reviewable.io -->

2023-12-08 13:01 UTC, buggmagnet reviewed
> Reviewed 7 of 96 files at r1, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: 94 of 96 files reviewed, 40 unresolved discussions (waiting on @pronebird and @rablador)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/DynamicBackgroundConfiguration.swift` line 12 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-Nl8VID66HG3Ork-FrRe:-Nl8VID66HG3Ork-FrRf:blkc8ag) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa856b899ece5cc3e39197398d29e564eaf0b7e7/ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/DynamicBackgroundConfiguration.swift#L12)):*
> ```Swift
> 
> /// Types providing dynamic background configuration based on cell configuration state.
> protocol DynamicBackgroundConfiguration: UITableViewCell {
> ```

Why is this inheriting from `UITableViewCell` ?


<!-- Sent from Reviewable.io -->

2023-12-08 14:38 UTC, rablador reviewed
> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: all files reviewed, 39 unresolved discussions (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-12-12 14:21 UTC, rablador reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: all files reviewed, 39 unresolved discussions (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-12-13 08:56 UTC, buggmagnet reviewed
> Reviewed 56 of 96 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: all files reviewed, 41 unresolved discussions (waiting on @pronebird)

___
*[`ios/MullvadVPN/Containers/Navigation/UINavigationBar+Appearance.swift` line 15 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-Nl8h0oWCxbB9DJcBOBt:-Nl8h0oWCxbB9DJcBOBu:b-gx2fcn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa856b899ece5cc3e39197398d29e564eaf0b7e7/ios/MullvadVPN/Containers/Navigation/UINavigationBar%2BAppearance.swift#L15)):*
> ```Swift
>     /// - Note: Navigation bar does not provide the appearance configuration for the prompt.
>     func overridePromptColor() {
>         let promptView = subviews.first { $0.description.contains("Prompt") }
> ```

This looks like a hack that doesn't seem reliable to me.
If we really need to identify subviews, we can always use the `tag` property on `UIView` instead. 
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksItemIdentifier.swift` line 12 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530#-NlS6q0eE7q4lUSLJzW0:-NlS6q0f9pnE9H827JdW:b-6ck5u5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa856b899ece5cc3e39197398d29e564eaf0b7e7/ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksItemIdentifier.swift#L12)):*
> ```Swift
> 
> /// Item identifier used by diffable data sources implementing socks configuration.
> enum SocksItemIdentifier: Hashable, CaseIterable {
> ```

This could probably be merged with the `ShadowSocksIdentifier` cheaply


<!-- Sent from Reviewable.io -->

2023-12-13 09:28 UTC, buggmagnet reviewed
> Reviewed 13 of 96 files at r1, 1 of 3 files at r2, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: all files reviewed, 41 unresolved discussions (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-12-13 14:56 UTC, buggmagnet approved these changes
> Reviewed 11 of 11 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5530)* status: all files reviewed, 41 unresolved discussions (waiting on @pronebird)



<!-- Sent from Reviewable.io -->

2023-12-13 15:00 UTC, merged