Move exit location logic to daemon
mullvad/mullvadvpn-app pull request #5542
Opened 2023-12-01 14:24 UTC by Serock3

Fixes: DES-514

Currently, the daemon exposes an API for fetching current location, which in turn contacts [am.i.mullvad.net](http://am.i.mullvad.net/). If this fails, each front end needs its own logic for retrying the call to the daemon, which is not ideal. We want the daemon itself handle retries in the REST API and notify frontends when the out IP is available.

This PR removes the `GetCurrentLocation rpc`. The frontends already listen for updates to the tunnel state, and `TunnelState::Connected` contains `GeoIpLocation`. The `ipv4` and  `ipv6` fields of this `GeoIpLocation` are currently null, so we should fill them with information from [am.i.mullvad.net](http://am.i.mullvad.net/). The daemon will leave the fields empty at first before issuing the [am.i.mullvad.net](http://am.i.mullvad.net/) request, when the response arrives it sends another `TunnelState::Connected` even to the frontends. To get location information after disconnecting, we add `GeoIpLocation` to `TunnelState::Disconnected`

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542)

2023-12-01 19:37 UTC, dlon reviewed
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @Serock3)

___
*[`mullvad-cli/src/cmds/status.rs` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-NkalVJi7Po5g6GUxvEX:-NkalVJi7Po5g6GUxvEY:bym7vb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a374f6a13229f2969d4c902b8d9d8922b40be078/mullvad-cli/src/cmds/status.rs#L41)):*
> ```XML
>                     }
> 
>                     let location = match new_state {
> ```

What do you think of simply doing this?

```rust
  if args.location {
      match new_state {
          TunnelState::Connected {
              location: Some(location),
              ..
          }
          | TunnelState::Disconnected(Some(location)) => {
              print_location(&location)
          }
          _ => (),
      }
  }
```
IMO, not finding a location is not an error, but opinions may vary.
___
*[`mullvad-daemon/src/lib.rs` line 1073 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nkan2Eb8Dq6rfzJs9D7:-Nkan2Eb8Dq6rfzJs9D8:bj6hedk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a374f6a13229f2969d4c902b8d9d8922b40be078/mullvad-daemon/src/lib.rs#L1073)):*
> ```XML
>                         .await
>                         .ok();
>                 even_listener.notify_new_state(make_tunnel_state(location));
> ```

We're not saving the `TunnelState` to `self.tunnel_state` here. Would you agree that we should keep them in sync?

One "reasonable" way of doing this might be to send `InternalDaemonEvent::TunnelStateTransition` instead of notifying `event_listener`directly. Or a new `InternalDaemonEvent` variant if reusing this one is a bad idea.
___
*[`mullvad-daemon/src/lib.rs` line 1073 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-NkaqVW0-TWk9bL6XaQG:-NkaqVW0-TWk9bL6XaQH:b2enpwd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a374f6a13229f2969d4c902b8d9d8922b40be078/mullvad-daemon/src/lib.rs#L1073)):*
> ```XML
>                         .await
>                         .ok();
>                 even_listener.notify_new_state(make_tunnel_state(location));
> ```

This differs from the previous code, in that we only previously appended `ipv4` and `ipv6` to the known location info in the connected state. Have you thought about whether it makes sense to change this?
___
*[`mullvad-daemon/src/lib.rs` line 1073 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nkar_Rj56mL1ZShkdtY:-Nkar_Rj56mL1ZShkdtZ:bo9q2pn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a374f6a13229f2969d4c902b8d9d8922b40be078/mullvad-daemon/src/lib.rs#L1073)):*
> ```XML
>                         .await
>                         .ok();
>                 even_listener.notify_new_state(make_tunnel_state(location));
> ```

Why notify when `location.is_none()`? Would it not make more sense to do nothing in this case?
___
*[`mullvad-daemon/src/lib.rs` line 1075 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-NkamFr5CKIhJ8k4Nh3s:-NkamFr5CKIhJ8k4Nh3t:b-81s31x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a374f6a13229f2969d4c902b8d9d8922b40be078/mullvad-daemon/src/lib.rs#L1075)):*
> ```XML
>                 even_listener.notify_new_state(make_tunnel_state(location));
>             })
>             .abort_handle(),
> ```

Nit: You can call `abort` directly on `JoinHandle<()>`


<!-- Sent from Reviewable.io -->

2023-12-08 10:10 UTC, dlon reviewed
> Reviewed 1 of 2 files at r2, 3 of 4 files at r3, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542)* status: 9 of 16 files reviewed, 2 unresolved discussions (waiting on @Serock3)

___
*[`mullvad-daemon/src/lib.rs` line 1047 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nl7t4baCUrrR48ELJ7j:-Nl7t4baCUrrR48ELJ7k:br7fngo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e3d784a0235c3d3e7d4b0c04fa736e9da19482e/mullvad-daemon/src/lib.rs#L1047)):*
> ```XML
>     ///
>     /// See [`Daemon::handle_location_event()`]
>     async fn fetch_am_i_mullvad(&mut self) {
> ```

Nit: This does not need to be async.
___
*[`mullvad-daemon/src/lib.rs` line 1057 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nl7tth7485eMGc_tY4e:-Nl7tth7485eMGc_tY4f:b-2yc8fr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e3d784a0235c3d3e7d4b0c04fa736e9da19482e/mullvad-daemon/src/lib.rs#L1057)):*
> ```XML
>         }
> 
>         let use_ipv6 = self.settings.tunnel_options.generic.enable_ipv6;
> ```

This setting is independent of whether the "real" network has IPv6 connectivity. I'm not sure what the right approach is. Maybe this could always be `true` when disconnected?


<!-- Sent from Reviewable.io -->

2023-12-08 15:42 UTC, Serock3 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542)* status: 7 of 16 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`mullvad-daemon/src/lib.rs` line 1047 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nl7t4baCUrrR48ELJ7j:-Nl8MjbBEBRcXB-s1Ok8:brdg18u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e3d784a0235c3d3e7d4b0c04fa736e9da19482e/mullvad-daemon/src/lib.rs#L1047)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: This does not need to be async.
</blockquote></details>

Thanks, it's fixed now. Why isn't that a clippy warning?
___
*[`mullvad-daemon/src/lib.rs` line 1057 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nl7tth7485eMGc_tY4e:-Nl94v-qEGKQFU_a0iEL:bns9jzh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2e3d784a0235c3d3e7d4b0c04fa736e9da19482e/mullvad-daemon/src/lib.rs#L1057)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This setting is independent of whether the "real" network has IPv6 connectivity. I'm not sure what the right approach is. Maybe this could always be `true` when disconnected?
</blockquote></details>

I made the disconnected state use the wireguard setting as we discussed


<!-- Sent from Reviewable.io -->

2023-12-15 11:43 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542)* status: 5 of 49 files reviewed, 1 unresolved discussion (waiting on @dlon and @Serock3)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 100 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-NlhH3so6cdi-MeSWJoW:-NlhH3so6cdi-MeSWJoX:bhlpxfj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2d7c975757c0c81ca83a3db9fe0de06180b9307d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L100)):*
> ```Kotlin
>                                 is TunnelState.Connected -> tunnelRealState.location
>                                 is TunnelState.Disconnecting -> lastKnownDisconnectedLocation
>                                 is TunnelState.Error -> lastKnownDisconnectedLocation
> ```

What location do we show on desktop if we have TunnelState error @raksooo? Would it be different if they are blocking or not blocking? Does connecting also display tunnel state or is this something we cache?


<!-- Sent from Reviewable.io -->

2023-12-18 10:54 UTC, Rawa reviewed
> Reviewed 1 of 42 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542)* status: 6 of 49 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 100 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-NlhH3so6cdi-MeSWJoW:-NlwZ1rIEayfxIwkmlG7:b9b3l65) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2d7c975757c0c81ca83a3db9fe0de06180b9307d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L100)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

What location do we show on desktop if we have TunnelState error @raksooo? Would it be different if they are blocking or not blocking? Does connecting also display tunnel state or is this something we cache?
</blockquote></details>

I've talked with @raksooo about this and aligned so it is the same behaviour as on desktop.


<!-- Sent from Reviewable.io -->

2023-12-18 11:01 UTC, Pururun requested changes
> Reviewed 1 of 3 files at r12, 3 of 42 files at r16, 7 of 7 files at r17, 28 of 32 files at r18, 3 of 3 files at r19, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/test/ComposeTestTagConstants.kt` line 27 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-NlwZz4-6I_PD92-Fl95:-NlwZz4-6I_PD92-Fl96:b6ndqvn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d337e05f20374a5bc80b0c7e8dcfbbf10131201d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/test/ComposeTestTagConstants.kt#L27)):*
> ```Kotlin
> const val CONNECT_BUTTON_TEST_TAG = "connect_button_test_tag"
> const val RECONNECT_BUTTON_TEST_TAG = "reconnect_button_test_tag"
> const val LOCATION_INFO_TEST_TAG = "location_info_test_tag"
> ```

Why was this change made? It is no longer aligned with the other test tags.


<!-- Sent from Reviewable.io -->

2023-12-18 11:04 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542)* status: 46 of 49 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/test/ComposeTestTagConstants.kt` line 27 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-NlwZz4-6I_PD92-Fl95:-NlwaB8A2rtYlSDOh1XO:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d337e05f20374a5bc80b0c7e8dcfbbf10131201d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/test/ComposeTestTagConstants.kt#L27)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Why was this change made? It is no longer aligned with the other test tags.
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2023-12-18 13:21 UTC, Serock3 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-:-Nlx1on8-Cri_cOHnv2S:bg7igk9)* status: 10 of 52 files reviewed, 1 unresolved discussion (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/test/ComposeTestTagConstants.kt` line 27 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-NlwZz4-6I_PD92-Fl95:-NlwcXbr4CzxoJPqY6Af:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d337e05f20374a5bc80b0c7e8dcfbbf10131201d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/test/ComposeTestTagConstants.kt#L27)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Fixed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-18 14:34 UTC, albin-mullvad reviewed
> Reviewed 27 of 30 files at r27.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542)* status: 37 of 52 files reviewed, 2 unresolved discussions (waiting on @Pururun, @Rawa, and @Serock3)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 159 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-NlxL4SL7k_WKXH0m4hB:-NlxL4SL7k_WKXH0m4hC:b13uwtx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L159)):*
> ```Kotlin
>             .filter { it.location == null }
>             .map { it.location }
>             .onStart { emit(null) }
> ```

Is this aligned with how this case is handled in the desktop app? Also, is it working reliably?



_Code quote:_
```Kotlin
    private fun ConnectionProxy.lastKnownLocation(): Flow<GeoIpLocation?> =
        tunnelRealStateFlow()
            .filterIsInstance<TunnelState.Disconnected>()
            .filter { it.location == null }
            .map { it.location }
            .onStart { emit(null) }
```


<!-- Sent from Reviewable.io -->

2023-12-18 22:30 UTC, Pururun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r21, 3 of 41 files at r22, 1 of 38 files at r25, 7 of 7 files at r26, 3 of 30 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-:-Nlz2ICK-7FX5UewMXhe:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)



<!-- Sent from Reviewable.io -->

2023-12-19 08:58 UTC, MarkusPettersson98 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542)* status: all files reviewed, 8 unresolved discussions (waiting on @Serock3)

___
*[`mullvad-cli/src/format.rs` line 54 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm06nFo2coS4Bp5m08z:-Nm06nFo2coS4Bp5m09-:b-8m4fnj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/mullvad-cli/src/format.rs#L54)):*
> ```XML
>     };
>     if let Some(location) = location {
>         print!("Your connection appears from: {}", location.country);
> ```

Nit: This phrasing seems a bit cut short to me. Would it make sense to extend it a little bit to make it grammatically correct? :blush: 

`Your connection appears to be from: `



_Code quote:_
```XML
Your connection appears from:
```
___
*[`mullvad-cli/src/cmds/status.rs` line 21 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm087BfENNEmDdffWJK:-Nm087BfENNEmDdffWJL:b-9ims1s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/mullvad-cli/src/cmds/status.rs#L21)):*
> ```XML
>     verbose: bool,
> 
>     // TODO: changelog about removing location flag
> ```

Has this been added to the changelog yet? If so, remove this comment :blush: 



_Code quote:_
```XML
// TODO: changelog about removing location flag
```
___
*[`mullvad-cli/src/cmds/status.rs` line 39 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm08VS78zzT2cDexyta:-Nm08VS78zzT2cDexytb:b-cypido) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/mullvad-cli/src/cmds/status.rs#L39)):*
> ```XML
>                         // When we enter the connected or disconnected state, am.i.mullvad.net will
>                         // be polled to get IP information. When it arrives, we will get another
>                         // tunnel state of the same enum type, but with the IP  filled in. This
> ```

Nit: Some extra whitespace snuck into this comment. Could you trim it a bit? :blush: 
___
*[`mullvad-cli/src/cmds/status.rs` line 95 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm08jMJ6h2edlTNYD8d:-Nm08jMJ6h2edlTNYD8e:b-fb9shr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/mullvad-cli/src/cmds/status.rs#L95)):*
> ```XML
>         println!("Tunnel state: {state:#?}");
>     } else {
>         // TODO: respect location arg?
> ```

Should this `TODO` be handled in this PR, or is the fix blocked on something that is not yet implemented? :blush:



_Code quote:_
```XML
// TODO: respect location arg?
```
___
*[`mullvad-daemon/src/geoip.rs` line 75 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm09KFq0De_Vz25bj57:-Nm09KFq0De_Vz25bj58:b-vpch80) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/mullvad-daemon/src/geoip.rs#L75)):*
> ```XML
>         // Increment request ID
>         self.request_id = self.request_id.wrapping_add(1);
>         let request_id_copy = self.request_id;
> ```

Nit: Could this (implicit) copy be grouped with the other clones just before invoking `tokio::spawn`? :blush: 

```rust
let request_id_copy = self.request_id;
let rest_service = self.rest_service.clone();
let location_sender = self.location_sender.clone();
tokio::spawn(async move {
    if let Ok(merged_location) = get_geo_location_with_retry(use_ipv6, rest_service).await {
        let _ = location_sender.send(InternalDaemonEvent::LocationEvent((
            request_id_copy,
            merged_location,
        )));
    }
});
```



_Code quote:_
```XML
let request_id_copy = self.request_id;
```
___
*[`mullvad-daemon/src/lib.rs` line 374 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0BkQ0BjTNGtaT3FOc:-Nm0BkQ0BjTNGtaT3FOd:b-7pbdsb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/mullvad-daemon/src/lib.rs#L374)):*
> ```XML
>     DeviceMigrationEvent(Result<PrivateAccountAndDevice, device::Error>),
>     /// A geographical location has has been received from am.i.mullvad.net
>     LocationEvent((usize, GeoIpLocation)),
> ```

Would it make sense to define a dedicated type for this `InternalDaemonEvent` to give `usize` and `GeoIpLocation` descriptive names?
I could imagine the type to look something like:
```rust
struct LocationEventData {
    /// Keep track of which request led to this event being triggered
    request_id: usize,
    /// New location information
    location: GeoIpLocation,
}

...

pub(crate) enum InternalDaemonEvent {
...
    LocationEvent(LocationEventData),
...
}
```
It would automate the naming of these variables for any caller pattern matching on `LocationEvent`, which I think is a huge win :trophy:
```rust
match event {
    LocationEvent(LocationEventData { request_id, location }) => {
        self.handle_location_event(request_id, location)
    }
    ...
}
```



_Code quote:_
```XML
    /// A geographical location has has been received from am.i.mullvad.net
    LocationEvent((usize, GeoIpLocation)),
```
___
*[`mullvad-daemon/src/lib.rs` line 882 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0G4O3EBJ2VC1mxCQy:-Nm0G4O3EBJ2VC1mxCQz:b-4gze4q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/mullvad-daemon/src/lib.rs#L882)):*
> ```XML
>         } else {
>             self.fetch_am_i_mullvad()
>         }
> ```

It would be nice to have some comment explaining _why_ `fetch_am_i_mullvad` is invoked in this else-branch. At the moment, I'm a bit puzzled as to why this is not the case for both branches :blush: 



_Code quote:_
```XML
        } else {
            self.fetch_am_i_mullvad()
        }
```


<!-- Sent from Reviewable.io -->

2023-12-19 09:51 UTC, Jontified requested changes
> Reviewed 2 of 9 files at r1, 3 of 4 files at r3, 1 of 3 files at r12, 4 of 42 files at r16, 7 of 7 files at r17, 32 of 32 files at r18, 1 of 3 files at r21, 3 of 41 files at r22, 1 of 38 files at r25, 7 of 7 files at r29, 30 of 30 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542)* status: all files reviewed, 13 unresolved discussions (waiting on @MarkusPettersson98 and @Serock3)

___
*[`CHANGELOG.md` line 38 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0TRkM4WCwE9aXEteY:-Nm0TRkM4WCwE9aXEteZ:b-9alc88) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44189079d129d28bc35fddf01302affdbbc2f120/CHANGELOG.md#L38)):*
> ```Markdown
> ### Changed
> - Remove `--location` flag from `mullvad status` CLI. Location and IP will now always
>   be printed (if available). `mullvad status listen` does no longer print location info.
> ```

`does no longer print` => `no longer prints`
___
*[`mullvad-cli/src/cmds/status.rs` line 21 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0AJNz4b6iOtJ0NG5A:-Nm0AJNz4b6iOtJ0NG5B:bb7462z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44189079d129d28bc35fddf01302affdbbc2f120/mullvad-cli/src/cmds/status.rs#L21)):*
> ```XML
>     verbose: bool,
> 
>     // TODO: changelog about removing location flag
> ```

TODO
___
*[`mullvad-cli/src/cmds/status.rs` line 95 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0AcTt4cJj2DzhCNd-:-Nm0AcTt4cJj2DzhCNd0:b-at9qrn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44189079d129d28bc35fddf01302affdbbc2f120/mullvad-cli/src/cmds/status.rs#L95)):*
> ```XML
>         println!("Tunnel state: {state:#?}");
>     } else {
>         // TODO: respect location arg?
> ```

TODO
I don't think there is a good reason to keep the flag. We are moving this information into `state` and will be printing that regardless.
We could avoid printing location in state and keep the flag, but that seems needlessly complex.
We could print only the location if the user provides the flag but then we're breaking the CLI regardless and it seems unnecessary.
___
*[`mullvad-daemon/src/geoip.rs` line 106 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0IfXjEexgadS8EW-E:-Nm0IfXjEexgadS8EW-F:b-h1un52) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44189079d129d28bc35fddf01302affdbbc2f120/mullvad-daemon/src/geoip.rs#L106)):*
> ```XML
>         move || send_location_request(rest_service.clone(), use_ipv6),
>         move |result| match result {
>             Err(error) => error.is_network_error(),
> ```

What is the reason for this change? Is it because we don't have access to API availability or for some other reason?
___
*[`mullvad-daemon/src/lib.rs` line 1038 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0KN8T7BJpn5w5-g9D:-Nm0KN8T7BJpn5w5-g9E:bomz3o2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44189079d129d28bc35fddf01302affdbbc2f120/mullvad-daemon/src/lib.rs#L1038)):*
> ```XML
>         self.tunnel_state = tunnel_state.clone();
>         self.event_listener.notify_new_state(tunnel_state);
>         self.fetch_am_i_mullvad();
> ```

I am wondering what the privacy implications are of pinging this every time we do a state transition, it would seem like this isn't a problem in the `Connected` state but when we're disconnected do we want the app to ping this?
Not sure what the current state of the app is with regards to this. Perhaps all the frontends will ping `am.i.mullvad` when you're disconnected?
___
*[`mullvad-daemon/src/lib.rs` line 374 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0BkQ0BjTNGtaT3FOc:-Nm0J3c76bBHytFwKMq5:b-cnsqwb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/mullvad-daemon/src/lib.rs#L374)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Would it make sense to define a dedicated type for this `InternalDaemonEvent` to give `usize` and `GeoIpLocation` descriptive names?
I could imagine the type to look something like:
```rust
struct LocationEventData {
    /// Keep track of which request led to this event being triggered
    request_id: usize,
    /// New location information
    location: GeoIpLocation,
}

...

pub(crate) enum InternalDaemonEvent {
...
    LocationEvent(LocationEventData),
...
}
```
It would automate the naming of these variables for any caller pattern matching on `LocationEvent`, which I think is a huge win :trophy:
```rust
match event {
    LocationEvent(LocationEventData { request_id, location }) => {
        self.handle_location_event(request_id, location)
    }
    ...
}
```
</blockquote></details>

Dedicated type seems reasonable


<!-- Sent from Reviewable.io -->

2023-12-19 14:29 UTC, Serock3 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542)* status: 11 of 53 files reviewed, 10 unresolved discussions (waiting on @dlon, @Jontified, @MarkusPettersson98, and @Pururun)

___
*[`CHANGELOG.md` line 38 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0TRkM4WCwE9aXEteY:-Nm1FlSG33rH6WYuUJOR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44189079d129d28bc35fddf01302affdbbc2f120/CHANGELOG.md#L38)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

`does no longer print` => `no longer prints`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt` line 159 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-NlxL4SL7k_WKXH0m4hB:-Nm1G0ZJ2nG5-bgyMQUj:b-3axafs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt#L159)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this aligned with how this case is handled in the desktop app? Also, is it working reliably?
</blockquote></details>

Looks good with the change to !=
___
*[`mullvad-cli/src/format.rs` line 54 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm06nFo2coS4Bp5m08z:-Nm0ISJS6hnplRswc1Yg:b-47vjlu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/mullvad-cli/src/format.rs#L54)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit: This phrasing seems a bit cut short to me. Would it make sense to extend it a little bit to make it grammatically correct? :blush: 

`Your connection appears to be from: `
</blockquote></details>

My reasoning was that it would make sense with the location filled in, e.g. "Your connection appears to be from: Sweden, Gothenburg, IPv4 x.x.x.x". Do you have any suggestions for better phrasing?
___
*[`mullvad-cli/src/cmds/status.rs` line 21 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0AJNz4b6iOtJ0NG5A:-Nm1Gi2vE3SG1tT9FlNX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44189079d129d28bc35fddf01302affdbbc2f120/mullvad-cli/src/cmds/status.rs#L21)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

TODO
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/status.rs` line 95 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0AcTt4cJj2DzhCNd-:-Nm1HFv106g13Nqb27uT:b-l3asf6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44189079d129d28bc35fddf01302affdbbc2f120/mullvad-cli/src/cmds/status.rs#L95)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

TODO
I don't think there is a good reason to keep the flag. We are moving this information into `state` and will be printing that regardless.
We could avoid printing location in state and keep the flag, but that seems needlessly complex.
We could print only the location if the user provides the flag but then we're breaking the CLI regardless and it seems unnecessary.
</blockquote></details>

Yup, the --location flag is removed in this PR for that reason, I just missed to clean up this comment. 
___
*[`mullvad-cli/src/cmds/status.rs` line 21 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm087BfENNEmDdffWJK:-Nm1GbVS9zHL88dB59K6:bhhmfj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/mullvad-cli/src/cmds/status.rs#L21)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Has this been added to the changelog yet? If so, remove this comment :blush:
</blockquote></details>

It has, good catch! Fixed.
___
*[`mullvad-cli/src/cmds/status.rs` line 95 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm08jMJ6h2edlTNYD8d:-Nm1H1zj7xxe6H_AwSUt:b-sq3tja) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/mullvad-cli/src/cmds/status.rs#L95)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Should this `TODO` be handled in this PR, or is the fix blocked on something that is not yet implemented? :blush:
</blockquote></details>

Yup, the location flag is removed, forgot about the comment. Thanks.
___
*[`mullvad-daemon/src/geoip.rs` line 106 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0IfXjEexgadS8EW-E:-Nm1INnxC45HXm7ysiNq:bbh70nz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44189079d129d28bc35fddf01302affdbbc2f120/mullvad-daemon/src/geoip.rs#L106)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

What is the reason for this change? Is it because we don't have access to API availability or for some other reason?
</blockquote></details>

I implemented the previous version of this retry-strategy which checks for API availability and @dlon pointed out that it isn't needed in this case (I can't quite remember the reasoning, perhaps because it isn't a user initiated action? You would have to ask him). 
___
*[`mullvad-daemon/src/geoip.rs` line 75 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm09KFq0De_Vz25bj57:-Nm1ICBqEEIS_Cr4vHWW:b-3yf22) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/mullvad-daemon/src/geoip.rs#L75)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit: Could this (implicit) copy be grouped with the other clones just before invoking `tokio::spawn`? :blush: 

```rust
let request_id_copy = self.request_id;
let rest_service = self.rest_service.clone();
let location_sender = self.location_sender.clone();
tokio::spawn(async move {
    if let Ok(merged_location) = get_geo_location_with_retry(use_ipv6, rest_service).await {
        let _ = location_sender.send(InternalDaemonEvent::LocationEvent((
            request_id_copy,
            merged_location,
        )));
    }
});
```
</blockquote></details>

Sure. Fixed.
___
*[`mullvad-daemon/src/lib.rs` line 1038 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0KN8T7BJpn5w5-g9D:-Nm1LC3iANECZi-9Zk4X:blxjorj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44189079d129d28bc35fddf01302affdbbc2f120/mullvad-daemon/src/lib.rs#L1038)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

I am wondering what the privacy implications are of pinging this every time we do a state transition, it would seem like this isn't a problem in the `Connected` state but when we're disconnected do we want the app to ping this?
Not sure what the current state of the app is with regards to this. Perhaps all the frontends will ping `am.i.mullvad` when you're disconnected?
</blockquote></details>

 
Yes, that is the implication, and we have discussed it. The frontends already poll your geoip every time you disconnect as far as I am aware, so fixing that was not deemed to block this PR. Probably a better solution would be to cache your disconnected location and only update it, say, every 30 minutes.
___
*[`mullvad-daemon/src/lib.rs` line 374 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0BkQ0BjTNGtaT3FOc:-Nm1K3i70rqVzKH5G-cc:b-daztlb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/mullvad-daemon/src/lib.rs#L374)):*
<details><summary><i>Previously, Jontified wrote…</i></summary><blockquote>

Dedicated type seems reasonable
</blockquote></details>

Very good suggestion. Implemented it.
___
*[`mullvad-daemon/src/lib.rs` line 882 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0G4O3EBJ2VC1mxCQy:-Nm1T_FED0bXio-QmIoq:b-886gsx) ([raw file](http [...]

2023-12-20 09:21 UTC, MarkusPettersson98 approved these changes
> Reviewed 5 of 42 files at r31, 7 of 7 files at r32, 30 of 30 files at r33, 1 of 38 files at r34, 7 of 7 files at r35, 30 of 30 files at r36, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542)* status: all files reviewed, 5 unresolved discussions (waiting on @dlon and @Jontified)

___
*[`mullvad-daemon/src/lib.rs` line 882 at r27](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0G4O3EBJ2VC1mxCQy:-Nm1VrYq3_AUmzXcPKrC:bk09f7s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9e9682f4e0471355ed932a28515189421285293b/mullvad-daemon/src/lib.rs#L882)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Fixed
</blockquote></details>

:raised_hands:


<!-- Sent from Reviewable.io -->

2023-12-20 10:37 UTC, Serock3 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542)* status: all files reviewed, 4 unresolved discussions (waiting on @Jontified)

___
*[`mullvad-daemon/src/geoip.rs` line 106 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5542#-Nm0IfXjEexgadS8EW-E:-Nm5lJHn-yL1_iIXQyP_:b-slqebi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44189079d129d28bc35fddf01302affdbbc2f120/mullvad-daemon/src/geoip.rs#L106)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

I implemented the previous version of this retry-strategy which checks for API availability and @dlon pointed out that it isn't needed in this case (I can't quite remember the reasoning, perhaps because it isn't a user initiated action? You would have to ask him).
</blockquote></details>

am.i.mullvad.net is a separate rest API (not entirely sure why), so using using the normal API availability handle was a bug.


<!-- Sent from Reviewable.io -->

2023-12-21 12:37 UTC, merged