Block all traffic when device is connecting or reconnecting
mullvad/mullvadvpn-app pull request #5547
Opened 2023-12-04 14:31 UTC by buggmagnet

This PR extend's @pinkisemils's fix for blocking traffic when in error state to the `connecting` and `reconnecting` states too.

2023-12-04 14:33 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5547)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift` line 123 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5547#-NkpEmUU-baeFpii5Mzh:-NkpEmUU-baeFpii5Mzi:b-a8dyl2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/103068f2c227d1ab02ebe799d82d574b0e61db27/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BErrorState.swift#L123)):*
> ```Swift
>             config.interfaceAddresses = [IPAddressRange(from: "10.64.0.1/8")!]
>             config.peer = TunnelPeer(
>                 endpoint: .ipv4(IPv4Endpoint(string: "127.0.0.1:9090")!),
> ```

What's the likelihood of someone having a socks5 proxy running at that same address @pinkisemils  ?
Otherwise we could simply choose a random port instead here, and keep the localhost address.


<!-- Sent from Reviewable.io -->

2023-12-05 11:08 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5547)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift` line 123 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5547#-NkpEmUU-baeFpii5Mzh:-NktcHd49YZLT_PY_JfC:b-jcq1m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/103068f2c227d1ab02ebe799d82d574b0e61db27/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BErrorState.swift#L123)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I'm saying socks5 cause I saw a couple of examples for user ran services on localhost, I think 8080 is also a popular one.
</blockquote></details>

Picking a random port would be better. You can also specify a random octet for the last part of the address - 127.0.0.123 is also a valid localhost address.


<!-- Sent from Reviewable.io -->

2023-12-05 12:05 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5547)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+NetworkReachability.swift` line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5547#-Nktr-019DG-vSzTPhc6:-Nktr-019DG-vSzTPhc7:b-7dh5p4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/103068f2c227d1ab02ebe799d82d574b0e61db27/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BNetworkReachability.swift#L59)):*
> ```Swift
>                 state = .connecting(connState)
>                 Task {
>                     await blockAllTrafficUntilDeviceIsConnected()
> ```

Setting the tunnel config here is moot - the existing tunnel config should already be blocking traffic. And reconfiguring the tunnel to be blocking is moot too - the tunnel will be reconfigured to connect anyway.


<!-- Sent from Reviewable.io -->

2023-12-05 12:35 UTC, rablador reviewed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5547)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2023-12-05 13:43 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5547)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift` line 123 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5547#-NkpEmUU-baeFpii5Mzh:-NkuCiun5mPa9c87oLC1:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/103068f2c227d1ab02ebe799d82d574b0e61db27/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BErrorState.swift#L123)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Picking a random port would be better. You can also specify a random octet for the last part of the address - 127.0.0.123 is also a valid localhost address.
</blockquote></details>

Done
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+NetworkReachability.swift` line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5547#-Nktr-019DG-vSzTPhc6:-Nku8Qvc9gI1_TwXhGrc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/103068f2c227d1ab02ebe799d82d574b0e61db27/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BNetworkReachability.swift#L59)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Setting the tunnel config here is moot - the existing tunnel config should already be blocking traffic. And reconfiguring the tunnel to be blocking is moot too - the tunnel will be reconfigured to connect anyway.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-05 13:50 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5547)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+KeyPolicy.swift` line 137 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5547#-NkuEKR92vSelthUzC81:-NkuEKR92vSelthUzC82:bisbva2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e6537d5c8f79d83d07e2682c25eb39dfeac5319b/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BKeyPolicy.swift#L137)):*
> ```Swift
>                 state = .connecting(connState)
>                 Task {
>                     await blockAllTrafficUntilDeviceIsConnected()
> ```

When in the connecting state, the app will end up calling `adapter.start(realWireGuardConfiguration)` soon after anyway - I don't think this matters much. The point of this change *would* be to change the DNS config to the config that's passed to WireGuard before we've received a ping back from the relay and then only set the DNS config.


<!-- Sent from Reviewable.io -->

2023-12-05 13:54 UTC, rablador reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5547)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @pinkisemils)



<!-- Sent from Reviewable.io -->

2023-12-05 14:14 UTC, closed without merging