Update API access methods functionality UI to conform with designs
mullvad/mullvadvpn-app pull request #5637
Opened 2024-01-02 15:57 UTC by rablador

2024-01-17 14:53 UTC, buggmagnet requested changes
The designs specify that the method currently in use should have a label "In use" below its title

![Screenshot 2024-01-17 at 12.16.20.png](https://files.reviewableusercontent.io/images/reviewable/129761703/oeqBX3XfyYd0fX-JDuINBQG8/Screenshot%202024-01-17%20at%2012.16.20.png)

> Reviewed 53 of 66 files at r1, 8 of 9 files at r2, 6 of 7 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-:-NoM7bAd0RsuzWSLHWL2:bi3pccr)* status: all files reviewed, 12 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadSettings/AccessMethodRepository.swift` line 53 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMdmReC0U9evMD1Lj0:-NoMdmReC0U9evMD1Lj1:b-skcu1a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56752c02fc91eb874fab6e1321ea65ccae27abbf/ios/MullvadSettings/AccessMethodRepository.swift#L53)):*
> ```Swift
>             try writeApiAccessMethods(storedMethods)
>         } catch {
>             print("Could not update access methods: \(storedMethods) \nError: \(error)")
> ```

Shouldn't we use our logging API for this instead ?
This comment is valid of all the `print` uses 
___
*[`ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift` line 19 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMf0xVAnI1vW5nvy7O:-NoMf0xVAnI1vW5nvy7P:b9qbp06) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift#L19)):*
> ```Swift
>     static let shared = ProxyConfigurationTester()
> 
>     init() {}
> ```

nit
I'm guessing this was meant to be a singleton, but we didn't define the `init` as private which defeats the purpose of having a singleton in the first place.

Just a nit because I will fix it in my upcoming work 
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/ShadowsocksSectionHandler.swift` line 57 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoM9KhP1aapPJqwSWaA:-NoM9KhP1aapPJqwSWaB:bw4jy5i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56752c02fc91eb874fab6e1321ea65ccae27abbf/ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/ShadowsocksSectionHandler.swift#L57)):*
> ```Swift
>         var contentConfiguration = TextCellContentConfiguration()
>         contentConfiguration.text = itemIdentifier.text
>         contentConfiguration.setPlaceholder(type: .required)
> ```

Apologies if that was not discussed properly, but it turns out the password is `.optional` for the shadowsocks case in the end.
We can revert this change back to `.optional` 
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodInteractor.swift` line 15 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMhwCW7xyR3yDqcawo:-NoMhwCW7xyR3yDqcawp:bxg2js) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodInteractor.swift#L15)):*
> ```Swift
> struct EditAccessMethodInteractor: EditAccessMethodInteractorProtocol {
>     let subject: CurrentValueSubject<AccessMethodViewModel, Never>
>     let repo: AccessMethodRepositoryProtocol
> ```

Let's not use abbreviations if we can afford writing the full word.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift` line 334 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMjyNCAOID4wD4oDfW:-NoMjyNCAOID4wD4oDfX:b-qhddrc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift#L334)):*
> ```Swift
>                 "METHOD_SETTINGS_SAVE_PROMPT",
>                 tableName: "APIAccess",
>                 value: "Delete \(subject.value.name)?",
> ```

If the method was defined without a name, we just show "Delete ?" here.
We should probably add the default name we show in the methods list in that case, and set that as the method name.

![Screenshot 2024-01-17 at 15.08.06.png](https://files.reviewableusercontent.io/images/reviewable/129761703/N1wF0s0y83Z7W94mp_s_2Q28/Screenshot%202024-01-17%20at%2015.08.06.png)
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsValidationErrorContentView.swift` line 64 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMpj6b6SP5JPcNMaJl:-NoMpj6b6SP5JPcNMaJm:b-bjuhlt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsValidationErrorContentView.swift#L64)):*
> ```Swift
>     }
> 
>     private func configureSubviews(previousConfiguration: MethodSettingsValidationErrorContentConfiguration? = nil) {
> ```

`previousConfiguration` doesn't seem to be used here, is it really needed ?
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift` line 310 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMRGJWEP6qSYy4n7bo:-NoMRGJWEP6qSYy4n7bp:bflbu6v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56752c02fc91eb874fab6e1321ea65ccae27abbf/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift#L310)):*
> ```Swift
>                 "METHOD_SETTINGS_SAVING_CHANGES",
>                 tableName: "APIAccess",
>                 value: "Saving changes...",
> ```

This should say "Adding method..." if we are adding the method , and "Saving changes..." if we are saving changes
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift` line 555 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMs0_z56m3l1WlqSVg:-NoMs0_z56m3l1WlqSVh:b-304yvs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift#L555)):*
> ```Swift
>     }
> 
>     // swiftlint:disable:next file_length
> ```

nit
I wonder if we could split this file to avoid doing this :thinking: 
Or maybe just regroup the Misc / Cell handling stuff in a different file ? I don't know, not a big deal probably.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodKind.swift` line 47 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoM6dC34nUEXt-KBg40:-NoM6dC486iDR38Q44Gm:b-f1m3gh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56752c02fc91eb874fab6e1321ea65ccae27abbf/ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodKind.swift#L47)):*
> ```Swift
>             NSLocalizedString("DIRECT", tableName: "APIAccess", value: "Direct", comment: "")
>         case .bridges:
>             NSLocalizedString("BRIDGES", tableName: "APIAccess", value: "Bridges", comment: "")
> ```

The specs mention the copy "Mullvad bridges"
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodKind.swift` line 51 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMQn7P0itRNsjZYfGx:-NoMQn7P0itRNsjZYfGy:b-pzblum) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56752c02fc91eb874fab6e1321ea65ccae27abbf/ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodKind.swift#L51)):*
> ```Swift
>             NSLocalizedString("SHADOWSOCKS", tableName: "APIAccess", value: "Shadowsocks", comment: "")
>         case .socks5:
>             NSLocalizedString("SOCKS_V5", tableName: "APIAccess", value: "Socks5", comment: "")
> ```

According to the specs, it should be "SOCKS5" (all uppercase)
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodValidationError.swift` line 71 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMsjlXBHPYCZB [...]

2024-01-18 17:04 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637)* status: all files reviewed, 16 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadSettings/AccessMethodRepository.swift` line 53 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMdmReC0U9evMD1Lj0:-NoS1fj-7bXDIUfr6elY:b32v57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56752c02fc91eb874fab6e1321ea65ccae27abbf/ios/MullvadSettings/AccessMethodRepository.swift#L53)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Shouldn't we use our logging API for this instead ?
This comment is valid of all the `print` uses
</blockquote></details>

+1
___
*[`ios/MullvadSettings/AccessMethodRepository.swift` line 98 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoS1svgCVRJTWa1c8et:-NoS1svgCVRJTWa1c8eu:bbcwj3n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadSettings/AccessMethodRepository.swift#L98)):*
> ```Swift
>             try writeApiAccessMethods(storedMethods)
>         } catch {
>             print("Could not update access methods: \(storedMethods) \nError: \(error)")
> ```

we can log it with `debug` level
___
*[`ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift` line 19 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMf0xVAnI1vW5nvy7O:-NoS2Jhp0gfeNOzDOnFA:bw7yolm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift#L19)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
I'm guessing this was meant to be a singleton, but we didn't define the `init` as private which defeats the purpose of having a singleton in the first place.

Just a nit because I will fix it in my upcoming work
</blockquote></details>

as I remember we avoid using `singleton` which is anti design pattern. do we really need to share this object across classes instead of injecting that as a dependency?
___
*[`ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift` line 23 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoS3Dqj5acFMZeSi8oh:-NoS3Dqj5acFMZeSi8oi:brzz5xm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift#L23)):*
> ```Swift
>     func start(configuration: PersistentProxyConfiguration, completion: @escaping (Error?) -> Void) {
>         let workItem = DispatchWorkItem {
>             let randomResult = (0 ... 255).randomElement()?.isMultiple(of: 2) ?? true
> ```

nit : IMHO I would rather put `Todo` annotation instead of making a random result
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodInteractor.swift` line 15 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMhwCW7xyR3yDqcawo:-NoS3mRE2eWm38jpE4Lh:b32v57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodInteractor.swift#L15)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's not use abbreviations if we can afford writing the full word.
</blockquote></details>

+1
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift` line 117 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoS56Qf4om00Jis4cC0:-NoS56Qf4om00Jis4cC1:b-saq3pf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift#L117)):*
> ```Swift
>     override func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat {
>         guard let sectionIdentifier = dataSource?.snapshot().sectionIdentifiers[section] else { return 0 }
>         let marginToDeleteMethodItem: CGFloat = 24
> ```

Use `UIMetrics`, please.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift` line 24 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoS7zZxDXHHot6OZB2U:-NoS7zZxDXHHot6OZB2V:bu3bnfq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift#L24)):*
> ```Swift
>     private var contentValidationErrors: [AccessMethodFieldValidationError] = []
> 
>     private var dataSource: UITableViewDiffableDataSource<
> ```

nit: maybe it was better to create typealias for this. 


<!-- Sent from Reviewable.io -->

2024-01-19 14:17 UTC, rablador reviewed
I waited with this one on purpose, since the mechanics for the method currently in use wasn't available to me until now. I'll add it.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-:-NoS0gw-5PGHhLcSqtdd:bi83zsa)* status: all files reviewed, 14 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadSettings/AccessMethodRepository.swift` line 53 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMdmReC0U9evMD1Lj0:-NoS57RU63l8vdtdwUFx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56752c02fc91eb874fab6e1321ea65ccae27abbf/ios/MullvadSettings/AccessMethodRepository.swift#L53)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`ios/MullvadSettings/AccessMethodRepository.swift` line 98 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoS1svgCVRJTWa1c8et:-NoWlvPh4qhSxM6j8STk:byn9plz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadSettings/AccessMethodRepository.swift#L98)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

we can log it with `debug` level
</blockquote></details>

I put .error for all actual errors. Sounds ok?
___
*[`ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift` line 23 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoS3Dqj5acFMZeSi8oh:-NoWmD3SBrwhYH1IB1wD:bwbb7gf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift#L23)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit : IMHO I would rather put `Todo` annotation instead of making a random result
</blockquote></details>

This whole thing will go away when we connect the real testing.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/ShadowsocksSectionHandler.swift` line 57 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoM9KhP1aapPJqwSWaA:-NoS6pzKCEVVckfh9voX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56752c02fc91eb874fab6e1321ea65ccae27abbf/ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/ShadowsocksSectionHandler.swift#L57)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Apologies if that was not discussed properly, but it turns out the password is `.optional` for the shadowsocks case in the end.
We can revert this change back to `.optional`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodInteractor.swift` line 15 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMhwCW7xyR3yDqcawo:-NoS7Wzr0zS_cLri1GFp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodInteractor.swift#L15)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift` line 117 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoS56Qf4om00Jis4cC0:-NoX32rT8BOg8YEat-HR:b-vi2jsv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift#L117)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Use `UIMetrics`, please.
</blockquote></details>

This is a very specific metric that's not going to be used elsewhere. Do we really need to add more to UIMetrics because of it?
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift` line 334 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMjyNCAOID4wD4oDfW:-NoS8Fr5EtP13aUNeq5i:bew5rzn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift#L334)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

If the method was defined without a name, we just show "Delete ?" here.
We should probably add the default name we show in the methods list in that case, and set that as the method name.

![Screenshot 2024-01-17 at 15.08.06.png](https://files.reviewableusercontent.io/images/reviewable/129761703/N1wF0s0y83Z7W94mp_s_2Q28/Screenshot%202024-01-17%20at%2015.08.06.png)
</blockquote></details>

Name has been changed to required field, so this is not relevant anymore.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsValidationErrorContentView.swift` line 64 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMpj6b6SP5JPcNMaJl:-NoS9bcw3fVfRKENT8yK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsValidationErrorContentView.swift#L64)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

`previousConfiguration` doesn't seem to be used here, is it really needed ?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift` line 310 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMRGJWEP6qSYy4n7bo:-NoS9qr13o_0fEMHMxd8:bqof21n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56752c02fc91eb874fab6e1321ea65ccae27abbf/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift#L310)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This should say "Adding method..." if we are adding the method , and "Saving changes..." if we are saving changes
</blockquote></details>

Since we're using the same vc for both scenarios there's currently no way to differentiate between new and existing. We could add methods to the interactor for this or do something else to get the right "context", but perhaps changing to "Saving method..." would be simpler?
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift` line 24 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoS7zZxDXHHot6OZB2U:-NoWyMbR1aeVQfQ3BuUP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift#L24)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit: maybe it was better to create typealias for this.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift` line 555 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMs0_z56m3l1WlqSVg:-NoWetOO2P7fZSkk43rw:bm9ztx5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift#L555)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
I wonder if we could split this file to avoid doing this :thinking: 
Or maybe just regroup the Misc / Cell handling stuff in a different file ? I don't know, not a big deal probably.
</blockquote></details>

Yeah, I was thinking about this, but it felt like it could make things a little disjointed. Gave it a try now anyway.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodKind.swift` line 47 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoM6 [...]

2024-01-22 10:18 UTC, mojganii approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637)* status: 53 of 74 files reviewed, 12 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-01-23 08:57 UTC, buggmagnet approved these changes
> Reviewed 20 of 21 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637)* status: 73 of 74 files reviewed, 4 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift` line 117 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoS56Qf4om00Jis4cC0:-NopJXKg1CNvsX4PUHaD:bdtv6h2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift#L117)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This is a very specific metric that's not going to be used elsewhere. Do we really need to add more to UIMetrics because of it?
</blockquote></details>

Given the discussion from yesterday, I think it's ok to keep it locally 
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift` line 310 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMRGJWEP6qSYy4n7bo:-NopQWJeBCXL4uu_waFt:bmeq0b6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56752c02fc91eb874fab6e1321ea65ccae27abbf/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift#L310)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Since we're using the same vc for both scenarios there's currently no way to differentiate between new and existing. We could add methods to the interactor for this or do something else to get the right "context", but perhaps changing to "Saving method..." would be simpler?
</blockquote></details>

Let's just have "saving changes..." everywhere then, that's what we seem to have right now, and it's functionally correct. 
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift` line 228 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NopQgrR5a2CLNzXc4Wt:-NopQgrR5a2CLNzXc4Wu:bowzao5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e29a4d4308cd8711535bdaba6fcf866c00954b7f/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift#L228)):*
> ```Swift
> 
>         validateInput()
>         dataSoruceConfiguration?.updateDataSource(
> ```

nit
`Soruce` isntead of `Source` 
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel+Persistent.swift` line 103 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMszojDvbmO2To5CAI:-NopRJUl7Xb9KcaOMhFX:b-mc5kco) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel%2BPersistent.swift#L103)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Done. What about shadowsocks?
</blockquote></details>

Let's discuss with the team 


<!-- Sent from Reviewable.io -->

2024-01-23 09:15 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-:-Nopa_ypDntEHu0QdDn1:bnfp4nl)* status: 73 of 74 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @rablador)



<!-- Sent from Reviewable.io -->

2024-01-24 09:10 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637)* status: 62 of 75 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift` line 117 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoS56Qf4om00Jis4cC0:-NouV-RpE2nVRRDtTyBY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift#L117)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Given the discussion from yesterday, I think it's ok to keep it locally
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift` line 310 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMRGJWEP6qSYy4n7bo:-NouVRB5AIEQVO7-TNCE:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56752c02fc91eb874fab6e1321ea65ccae27abbf/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift#L310)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's just have "saving changes..." everywhere then, that's what we seem to have right now, and it's functionally correct.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift` line 228 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NopQgrR5a2CLNzXc4Wt:-NouVUIwEb9ddvLRST9e:bd4d9te) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e29a4d4308cd8711535bdaba6fcf866c00954b7f/ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift#L228)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
`Soruce` isntead of `Source`
</blockquote></details>

I think we should go with `dataSaurus` instead. :D
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel+Persistent.swift` line 103 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-NoMszojDvbmO2To5CAI:-Nouj8RQDDKGBvQSuSgb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4095783c2c6eccced1ba694e600f0f636232cc59/ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel%2BPersistent.swift#L103)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's discuss with the team
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-24 15:38 UTC, buggmagnet requested changes
> Reviewed 13 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodKind.swift` line 45 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-Now6hIEEAwks-S2b0yH:-Now6hIEEAwks-S2b0yI:byfkr0v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00443e031e8d066f95ed722f4c510d84285d7922/ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodKind.swift#L45)):*
> ```Swift
>         switch self {
>         case .direct, .bridges:
>             ""
> ```

I'm not sure I follow, why do we return an empty string here ?


<!-- Sent from Reviewable.io -->

2024-01-24 21:35 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodKind.swift` line 45 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-Now6hIEEAwks-S2b0yH:-NoxNyfU1J0ySu8jkgQu:btvs2pi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/00443e031e8d066f95ed722f4c510d84285d7922/ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodKind.swift#L45)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I'm not sure I follow, why do we return an empty string here ?
</blockquote></details>

`localizedDescription` is used in `func toListItem() -> ListAccessMethodItem` in `ListAccessMethodInteractor`, but for the default (ie direct and bridges) items we don't want any secondary text except when they're disabled. It's a necessary evil unless we want to change some (minor) foundations Andrej laid.


<!-- Sent from Reviewable.io -->

2024-01-25 08:25 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637#-:-NoziLwf8lMEkX4GKA4G:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-01-25 09:24 UTC, buggmagnet approved these changes
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5637)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-01-25 15:58 UTC, merged