Add login UI tests
mullvad/mullvadvpn-app pull request #5678
Opened 2024-01-11 14:01 UTC by niklasberglund

The first basic login tests. Will implement more login-related tests later on to cover more of the login flow(more tests documented in https://linear.app/mullvad/document/tests-09cbefd4a4a6). Using Page Object Pattern(AKA Page Object Model) where code looking for elements, tapping them etc is abstracted away into page classes. So the test cases are very high level and easy to read, making it easy to verify that the tests are testing what they should and it's easier to maintain and create new tests reusing existing page classes.

A new `.xcconfig` file template has been added under `Configurations` so you need to copy the template for example by `cd Configurations ; cp UITests.xcconfig.template UITests.xcconfig` or Xcode might complain. To run the tests the variables on the configuration need to be populated with valid account numbers.

The tests are in the `MullvadVPNUITests` test plan and they can be launched for example from the test navigator in Xcode.
![image](https://github.com/mullvad/mullvadvpn-app/assets/331986/670bbfe7-f200-4141-9ce2-cfc3f42e11be)

2024-01-11 14:47 UTC, pinkisemils approved these changes
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-01-11 15:20 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678)* status: all files reviewed, 10 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 1713 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnt5i8a82JOH-MVBmXw:-Nnt5i8a82JOH-MVBmXx:b-o7ls7q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPN.xcodeproj/project.pbxproj#L1713)):*
> ```
> 		7AF9BE942A40461100DBFEDB /* RelayFilterView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = RelayFilterView.swift; sourceTree = "<group>"; };
> 		7AF9BE962A41C71F00DBFEDB /* RelayFilterChipView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = RelayFilterChipView.swift; sourceTree = "<group>"; };
> 		852969252B4D9C1F007EAD4C /* MullvadVPNUITests.xctest */ = {isa = PBXFileReference; explicitFileType = wrapper.cfbundle; includeInIndex = 0; path = MullvadVPNUITests.xctest; sourceTree = BUILT_PRODUCTS_DIR; };
> ```

We usually sort every file by name alphabetically
If you right click on the `Pages` group, you can select "Sort by name" and it should do it automatically for you
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnsu0IX6mGH-ldEPUIp:-Nnsu0IX6mGH-ldEPUIq:b-nul2ub) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L11)):*
> ```Swift
> import XCTest
> 
> final class AccountTests: XCTestCase {
> ```

We don't need to declare classes as `final`, the compiler can infer it for us, and will automatically do the right thing (and write it on our behalf) most of the time.

It's the same line of reasoning as to why we want to avoid writing `self` most of the time if we can avoid it. 
So that when we see it, we can think "This is intentional, and I need to think carefully about why it was put there in the first place"
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-NnsslfoAg3hWVAkpxkm:-NnsslfoAg3hWVAkpxkn:brkj7sh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L12)):*
> ```Swift
> 
> final class AccountTests: XCTestCase {
>     let noTimeAccountNumber = Bundle(for: AccountTests.self).infoDictionary?["MullvadNoTimeAccountNumber"] as! String
> ```

Given that a lot (if not all ?) of the UI tests will likely start from a clean slate, I think we can generalize a bit how to access those properties. 

Something as simple as the below example should suffice for now 
```swift
class BaseUITest: XCTestCase {
    // swiftlint:disable force_cast
    let noTimeAccountNumber = Bundle(for: AccountTests.self).infoDictionary?["MullvadNoTimeAccountNumber"] as! String
    let hasTimeAccountNumber = Bundle(for: AccountTests.self).infoDictionary?["MullvadHasTimeAccountNumber"] as! String
    let fiveWireGuardKeysAccountNumber = Bundle(for: AccountTests.self)
        .infoDictionary?["MullvadFiveWireGuardKeysAccountNumber"] as! String
    // swiftlint:enable force_cast
}

class AccountTests: BaseUITest {
```
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-NnsvUCGB6kTzVJkmtCe:-NnsvUCGB6kTzVJkmtCf:beah9b8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L25)):*
> ```Swift
>     func testLogin() throws {
>         let app = XCUIApplication()
>         app.launch()
> ```

If we ever want to run the UI automation suite manually, this will most likely fail if we had a previous build running, or a previous UI test running.
It's not super important for now, but for the future, we should uninstall the app in each class of UITests we run before launching the app.
I'm thinking something along the lines of (Or this can probably also be in the `BaseUITest` class)

```swift
class SomeUITest: BaseUITest {

    class override func setUp() {
        uninstallApplication()
        let app = XCUIApplication()
        app.launch()
    }
}

```

Alternatively, we can force a logout at the end of each test, and clear the cached account.
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnsw3lH77UOGjeGuQNC:-Nnsw3lH77UOGjeGuQND:b3mp2xh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L28)):*
> ```Swift
> 
>         TermsOfServicePage(app)
>             .tapAgree()
> ```

This is good, but I think we can do even better.

Here we don't really know what "agree" is, what are we agreeing to ?
Here's a suggestion:

```swift
TermsOfServicePage(app)
    .AgreeToTermsAndConditions()
```
IMHO UI Tests should read like a good book, it's easier to understand the intent if the test tells me what is supposed to be achieved rather than what it is trying to do.
The distinction is subtle, but important.

Here it's just a button to tap, so that's easy. 
But let's imagine that it would have been a flow like "enter password, wait 2 seconds, go accept 2FA token, turn around 3 times in a counter clockwise rotation on your chair"
`tapAgree` wouldn't quite cut it.

This way, the underlying implementation can change, but the intent stays the same. 
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnsz1FJ7nJPSeuMNd3t:-Nnsz1FJ7nJPSeuMNd3u:b-nhpf6x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L53)):*
> ```Swift
>         LoginPage(app)
>             .tapAccountNumberTextField()
>             .enterText("1234123412341234")
> ```

We try to avoid magic numbers as much as possible, also technically, "1234123412341234" _is_ a valid account number.

suggestion
```swift
let incorrectAccountNumber = "0000000000000000"
LoginPage(app)
    .tapAccountNumberTextField()
    .enterText(incorrectAccountNumber)
```
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnt3I0XCmmjuk1pDWOW:-Nnt3I0XCmmjuk1pDWOX:b44w6j2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L55)):*
> ```Swift
>             .enterText("1234123412341234")
>             .tapAccountNumberSubmitButton()
>             .verifyFailIconShown()
> ```

nit
I don't think we should verify that an image exists instead to verify that.
Instead we should verify that the text `Login Failed` is shown. 
We should also be mindful that this will need eventually to read localized text.
There is a subtext that is showing why the login failed, which we will want to verify in the future as well.

I'm on the fence on this, on one hand, this is good enough for now.
On the other hand, we will have to change that in the future when we want to validate localization too.
___
*[`ios/MullvadVPNUITests/Pages/LoginPage.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnt5Cmf2BabTMjNbU1H:-Nnt5Cmf2BabTMjNbU1I:b-yn8var) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/Pages/LoginPage.swift#L13)):*
> ```Swift
> 
> class LoginPage: Page {
>     @discardableResult override init(_ app: XCUIApplication) {
> ```

nit
We could probably use the new macro features introduced in swift 5.9 to automatically mark all functions / variables `@discardableResult` in this class :thinking: 
___
*[`ios/MullvadVPNUITests/Pages/Page.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/m [...]

2024-01-12 09:46 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678)* status: 13 of 17 files reviewed, 10 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 1713 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnt5i8a82JOH-MVBmXw:-NntFDqvAFTGQmMKMM-I:b-2129zc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPN.xcodeproj/project.pbxproj#L1713)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We usually sort every file by name alphabetically
If you right click on the `Pages` group, you can select "Sort by name" and it should do it automatically for you
</blockquote></details>

Good, done 👍
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnsu0IX6mGH-ldEPUIp:-NnwuFyw0NqMhj6dWrAS:b-kbtfbq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L11)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We don't need to declare classes as `final`, the compiler can infer it for us, and will automatically do the right thing (and write it on our behalf) most of the time.

It's the same line of reasoning as to why we want to avoid writing `self` most of the time if we can avoid it. 
So that when we see it, we can think "This is intentional, and I need to think carefully about why it was put there in the first place"
</blockquote></details>

Makes sense. Removed `final`
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-NnsslfoAg3hWVAkpxkm:-NntKyWzCnipXHBvXo-U:bl7j4r8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L12)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Given that a lot (if not all ?) of the UI tests will likely start from a clean slate, I think we can generalize a bit how to access those properties. 

Something as simple as the below example should suffice for now 
```swift
class BaseUITest: XCTestCase {
    // swiftlint:disable force_cast
    let noTimeAccountNumber = Bundle(for: AccountTests.self).infoDictionary?["MullvadNoTimeAccountNumber"] as! String
    let hasTimeAccountNumber = Bundle(for: AccountTests.self).infoDictionary?["MullvadHasTimeAccountNumber"] as! String
    let fiveWireGuardKeysAccountNumber = Bundle(for: AccountTests.self)
        .infoDictionary?["MullvadFiveWireGuardKeysAccountNumber"] as! String
    // swiftlint:enable force_cast
}

class AccountTests: BaseUITest {
```
</blockquote></details>

Yes, good idea 👍 Created a base class
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-NnsvUCGB6kTzVJkmtCe:-NntAanUCTQMKwysDL-1:b15ckt8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L25)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

If we ever want to run the UI automation suite manually, this will most likely fail if we had a previous build running, or a previous UI test running.
It's not super important for now, but for the future, we should uninstall the app in each class of UITests we run before launching the app.
I'm thinking something along the lines of (Or this can probably also be in the `BaseUITest` class)

```swift
class SomeUITest: BaseUITest {

    class override func setUp() {
        uninstallApplication()
        let app = XCUIApplication()
        app.launch()
    }
}

```

Alternatively, we can force a logout at the end of each test, and clear the cached account.
</blockquote></details>

Yes! This is something I haven't implemented a solution for yet and been thinking of as outside of the scope of this first PR, but maybe it shouldn't be. The tests in this PR assume the app isn't installed on the phone. I should've added that to the description. Added it now but let me know if it's something that should be part of this PR even.

Been looking into how to start XCUITest tests with a clear state but it doesn't seem trivial or like there's a very good programmatic solution from what I've found so far. Pondering creating a separate ticket for this. How does that sound?
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnsw3lH77UOGjeGuQNC:-NntLTwE7jycfu8v7Rfv:br7x7l8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L28)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This is good, but I think we can do even better.

Here we don't really know what "agree" is, what are we agreeing to ?
Here's a suggestion:

```swift
TermsOfServicePage(app)
    .AgreeToTermsAndConditions()
```
IMHO UI Tests should read like a good book, it's easier to understand the intent if the test tells me what is supposed to be achieved rather than what it is trying to do.
The distinction is subtle, but important.

Here it's just a button to tap, so that's easy. 
But let's imagine that it would have been a flow like "enter password, wait 2 seconds, go accept 2FA token, turn around 3 times in a counter clockwise rotation on your chair"
`tapAgree` wouldn't quite cut it.

This way, the underlying implementation can change, but the intent stays the same.
</blockquote></details>

The `tapAgree` method isn't following the convention other methods follow and should be named `tapAgreeButton`. Does that make it more clear? 

All those two lines do is verify `TermsOfServiceContentView` shows and then taps the accept button to accept the terms.
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnsz1FJ7nJPSeuMNd3t:-NntBBzC112-Hy14MKzA:bnpo2c3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L53)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We try to avoid magic numbers as much as possible, also technically, "1234123412341234" _is_ a valid account number.

suggestion
```swift
let incorrectAccountNumber = "0000000000000000"
LoginPage(app)
    .tapAccountNumberTextField()
    .enterText(incorrectAccountNumber)
```
</blockquote></details>

True. Is account number`0000000000000000` guaranteed to be invalid so using that instead solves the issue or should it also be broken out of the code to the configuration file? 
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnt3I0XCmmjuk1pDWOW:-NntBjBl5T00le0ATxa5:b-zi2f0j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L55)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
I don't think we should verify that an image exists instead to verify that.
Instead we should verify that the text `Login Failed` is shown. 
We should also be mindful that this will need eventually to read localized text.
There is a subtext that is showing why the login failed, which we will want to verify in the future as well.

I'm on the fence on this, on one hand, this is good enough for now.
On the other hand, we will have to change that in the future when we want to validate localization too.
</blockquote></details>

At first I also wanted to look for the label, but why I finally went with checking the image name instead of checking the label is because it is a status label that is reused so it's  [...]

2024-01-15 09:10 UTC, mojganii approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678)* status: 13 of 17 files reviewed, 10 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-NnsvUCGB6kTzVJkmtCe:-NoBMd0U4Z_eA02bbvna:b-y6e2er) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L25)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Yes! This is something I haven't implemented a solution for yet and been thinking of as outside of the scope of this first PR, but maybe it shouldn't be. The tests in this PR assume the app isn't installed on the phone. I should've added that to the description. Added it now but let me know if it's something that should be part of this PR even.

Been looking into how to start XCUITest tests with a clear state but it doesn't seem trivial or like there's a very good programmatic solution from what I've found so far. Pondering creating a separate ticket for this. How does that sound?
</blockquote></details>

I agree with @buggmagnet 


<!-- Sent from Reviewable.io -->

2024-01-15 10:02 UTC, buggmagnet requested changes
> Reviewed 12 of 16 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678)* status: all files reviewed, 7 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-NnsvUCGB6kTzVJkmtCe:-NoBHyx64DhuMBGDC8vW:b-cd0ilm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L25)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Yes! This is something I haven't implemented a solution for yet and been thinking of as outside of the scope of this first PR, but maybe it shouldn't be. The tests in this PR assume the app isn't installed on the phone. I should've added that to the description. Added it now but let me know if it's something that should be part of this PR even.

Been looking into how to start XCUITest tests with a clear state but it doesn't seem trivial or like there's a very good programmatic solution from what I've found so far. Pondering creating a separate ticket for this. How does that sound?
</blockquote></details>

Sounds good, I'll create a separate ticket for that :thumbsup: 
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnsw3lH77UOGjeGuQNC:-NoBKzPR9pzc7ZmYO0Op:b-swy38d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L28)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

The `tapAgree` method isn't following the convention other methods follow and should be named `tapAgreeButton`. Does that make it more clear? 

All those two lines do is verify `TermsOfServiceContentView` shows and then taps the accept button to accept the terms.
</blockquote></details>

nit:
Turning this into a nitpick cause it's not super important at this stage.

Yes it would make it more clear, but this isn't exactly what I was trying to say.
Please take with a grain of salt what I'm proposing here because it might be early optimization, but what I'm suggesting is that the test looks like this 

```swift
/// Validates that the user can login with a valid account number
func testLoginWithValidAccountNumber() throws {
    let app = XCUIApplication()
    app.launch()

    TermsOfServicePage(app)
        .agreeToTermsAndServiceConditions()

    LoginPage(app)
        .verifyLoginWith(
            app,
            validAccountNumber: self.noTimeAccountNumber
        )
}

```

The idea is that the test doesn't require looking at the functions to see what it does, and what it tries to validate, it's very self explanatory.
There's a TOS page, which will need to agree to conditions, then there's a login page where you enter an account number.

IMHO we shouldn't need to read more than that to see what the test is about.

That being said, it's okay if you prefer to just rename `tapAgree` to `tapAgreeButton` and move on.
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnsz1FJ7nJPSeuMNd3t:-NoBNU5QExZoe-8Rtw5M:b-wuyy4t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L53)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

True. Is account number`0000000000000000` guaranteed to be invalid so using that instead solves the issue or should it also be broken out of the code to the configuration file?
</blockquote></details>

Let's assume it is for now, I will check around and come back to you with a better answer than "I'm almost sure it is, but not quite"
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnt3I0XCmmjuk1pDWOW:-NoBNeL11a7zfG987Lx5:ba9xot9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L55)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

At first I also wanted to look for the label, but why I finally went with checking the image name instead of checking the label is because it is a status label that is reused so it's the same label object for all login states. And trying to avoid checking for specific text strings because it's so easy to break checks against specific strings. There is also an additional check on the line underneath, `waitForPageToBeShown()` which verifies that we're still on the login page so the user haven't been sent to the tunnel control page you get to after being logged in.
</blockquote></details>

Fair enough, let's keep it like this for now then :thumbsup: 
___
*[`ios/MullvadVPNUITests/BaseTestCase.swift` line 14 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-NoBNkz94pV1HHX_h55L:-NoBNkz94pV1HHX_h55M:b-40wxb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f952d65d99522f8e378da9c324fc5488356fca43/ios/MullvadVPNUITests/BaseTestCase.swift#L14)):*
> ```Swift
> class BaseTestCase: XCTestCase {
>     // swiftlint:disable force_cast
>     let noTimeAccountNumber = Bundle(for: AccountTests.self).infoDictionary?["MullvadNoTimeAccountNumber"] as! String
> ```

I know I made the original suggestion _but_ I forgot one important detail.  We should rename this `BaseUITestCase` to avoid clashing with Unit Tests (if we ever get to have a `BaseUnitTestCase`), also the bundle class refered to should be this one, it's likely to out-live `AccountTests` if we ever get rid of them.

```swift
class BaseUITestCase: XCTestCase {
    // swiftlint:disable force_cast
    let noTimeAccountNumber = Bundle(for: BaseUITestCase.self).infoDictionary?["MullvadNoTimeAccountNumber"] as! String
    let hasTimeAccountNumber = Bundle(for: BaseUITestCase.self).infoDictionary?["MullvadHasTimeAccountNumber"] as! String
    let fiveWireGuardKeysAccountNumber = Bundle(for: BaseUITestCase.self)
        .infoDictionary?["MullvadFiveWireGuardKeysAccountNumber"] as! String
    // swiftlint:enable force_cast
}
```
___
*[`ios/MullvadVPNUITests/Pages/LoginPage.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnt5Cmf2BabTMjNbU1H:-NoBOWjV68G60YttPlyC:bpglu89) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/Pages/LoginPage.swift#L13)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

That would be neat! The app target is using Swift 5.0. I'm not sure how much 5.0 and 5.9 differs, would it be okay to use different Swift versions for these targets?
</blockquote></details>

Xcode 15 ships with the swift 5.9 compiler. Which means we can already use the features from that version.
If you run the following command, you will likely get the same input (or at least, the same version)
```
[~/Code/mullvadvpn-app/ios (test-app-login-ios-428)]% xcrun swift --version
swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx13.0
```

What you see (probably) in "Swift Language Version" means little nowadays since Swift reached ABI stability in version 5.0. (It was more important when swift didn't have ABI stability, and when the syntax was still evolving a lot)

What really matters is which tool we use, and that means we choose to tie which swift version we can use, with which Xcode version we use (I'm taking a shortcut here).

Let's not bother too much with this for now, we can take time to do this later if it proves to be too much boilerplate
___
*[`ios/MullvadVPNUITes [...]

2024-01-15 14:47 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678)* status: 0 of 73 files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 28 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnsw3lH77UOGjeGuQNC:-NoBZhv162dOCWVGwUGq:b65egsq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L28)):*
Ah, I see your point. In the past I've made the same suggestion as you but I was convinced to not go with this higher abstraction. There's some big benefits of automated test cases reading the same as manual test cases which list all the steps, such as making it easier to maintain test cases and be sure that all functionality is covered. With a higher abstraction level the steps are less visible, you'd have to jump around in the code to figure out exactly what user actions the tests are doing. And some flows such as login will be slightly different in different test cases also - for instance there are two submit buttons. 

> That being said, it's okay if you prefer to just rename `tapAgree` to `tapAgreeButton` and move on.

Renamed it to `tapAgreeButton`. If I haven't convinced you yet I'll try to do so with time! 😊
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnsz1FJ7nJPSeuMNd3t:-NoBaQYY9EggV109ad9I:b-ka6gyi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L53)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's assume it is for now, I will check around and come back to you with a better answer than "I'm almost sure it is, but not quite"
</blockquote></details>

Maybe it doesn't answer our question but for the Android end to end tests there's a configurable `invalid_test_account_token` https://github.com/mullvad/mullvadvpn-app/tree/main/android/test/e2e

Have changed the invalid account number to `number`0000000000000000``
___
*[`ios/MullvadVPNUITests/BaseTestCase.swift` line 14 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-NoBNkz94pV1HHX_h55L:-NoBgWOmCOOe1-livacT:bxpv4l0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f952d65d99522f8e378da9c324fc5488356fca43/ios/MullvadVPNUITests/BaseTestCase.swift#L14)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I know I made the original suggestion _but_ I forgot one important detail.  We should rename this `BaseUITestCase` to avoid clashing with Unit Tests (if we ever get to have a `BaseUnitTestCase`), also the bundle class refered to should be this one, it's likely to out-live `AccountTests` if we ever get rid of them.

```swift
class BaseUITestCase: XCTestCase {
    // swiftlint:disable force_cast
    let noTimeAccountNumber = Bundle(for: BaseUITestCase.self).infoDictionary?["MullvadNoTimeAccountNumber"] as! String
    let hasTimeAccountNumber = Bundle(for: BaseUITestCase.self).infoDictionary?["MullvadHasTimeAccountNumber"] as! String
    let fiveWireGuardKeysAccountNumber = Bundle(for: BaseUITestCase.self)
        .infoDictionary?["MullvadFiveWireGuardKeysAccountNumber"] as! String
    // swiftlint:enable force_cast
}
```
</blockquote></details>

Good point! Renamed it to `BaseUITestCase`


<!-- Sent from Reviewable.io -->

2024-01-15 16:24 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678)* status: 0 of 73 files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

___
*[`ios/MullvadVPNUITests/Pages/LoginPage.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnt5Cmf2BabTMjNbU1H:-NoCvzbMAmxxOxLFRUil:b-5d9yw1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/Pages/LoginPage.swift#L13)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Xcode 15 ships with the swift 5.9 compiler. Which means we can already use the features from that version.
If you run the following command, you will likely get the same input (or at least, the same version)
```
[~/Code/mullvadvpn-app/ios (test-app-login-ios-428)]% xcrun swift --version
swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx13.0
```

What you see (probably) in "Swift Language Version" means little nowadays since Swift reached ABI stability in version 5.0. (It was more important when swift didn't have ABI stability, and when the syntax was still evolving a lot)

What really matters is which tool we use, and that means we choose to tie which swift version we can use, with which Xcode version we use (I'm taking a shortcut here).

Let's not bother too much with this for now, we can take time to do this later if it proves to be too much boilerplate
</blockquote></details>

Sounds good, let's see later then
___
*[`ios/MullvadVPNUITests/Pages/Page.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnt094I35eAWR81WPNp:-NoCw3sZ34Y6CvxDAuou:b-ai4pe1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/Pages/Page.swift#L25)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

> Should the time it takes to navigate to a page differ though?
Most likely not. But since we're trying to avoid magic values in general, it's better to have this at least as a constant defined somewhere.
What do you think ?
</blockquote></details>

Agree. I created a constant for the timeout value.


<!-- Sent from Reviewable.io -->

2024-01-16 10:55 UTC, buggmagnet approved these changes
> Reviewed 3 of 17 files at r11, 2 of 59 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678)* status: 5 of 73 files reviewed, 2 unresolved discussions (waiting on @mojganii, @niklasberglund, and @pinkisemils)

___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-NnsvUCGB6kTzVJkmtCe:-NoGtnJo-gve7tjh1trh:bogqn4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L25)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Sounds good, I'll create a separate ticket for that :thumbsup:
</blockquote></details>

@niklasberglund I created `IOS-456` in regards to this
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5678#-Nnsz1FJ7nJPSeuMNd3t:-NoGu3919A3z5EatOliG:b-n0svj1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a2ade8a1fa60248f7d6aa3a33915153faeafc978/ios/MullvadVPNUITests/AccountTests.swift#L53)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Maybe it doesn't answer our question but for the Android end to end tests there's a configurable `invalid_test_account_token` https://github.com/mullvad/mullvadvpn-app/tree/main/android/test/e2e

Have changed the invalid account number to `number`0000000000000000``
</blockquote></details>

nice !


<!-- Sent from Reviewable.io -->

2024-01-16 11:43 UTC, merged