Add ad blocking test for iOS
mullvad/mullvadvpn-app pull request #5701
Opened 2024-01-17 16:17 UTC by niklasberglund

Implemented test covering the ad blocking functionality. This PR introduces the attributes `MULLVAD_IOS_DEVICE_PIN_CODE` and `MULLVAD_AD_SERVING_DOMAIN` which need to be added to your `Configurations/UITests.xcconfig` file.

The test assumes a blank state, so the app should be uninstalled before running the test. It can be tried out by running the test `testAdBlockingViaDNS`.

<img width="372" alt="image" src="https://github.com/mullvad/mullvadvpn-app/assets/331986/fdaff867-be23-46d4-9d5f-901af65cf8ca">

2024-01-17 16:36 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701)* status: 0 of 18 files reviewed, 1 unresolved discussion

___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoNGFKb-LP18_HA9wJL:-NoNGFKb-LP18_HA9wJM:b2ozytn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/RelayTests.swift#L84)):*
> ```Swift
> 
>         if let urlError = requestError as? URLError {
>             if urlError.code == .cannotFindHost {
> ```

I'm not entirely sure whether this is a good way to verify that the domain can or cannot be resolved. Does DNS lookup do a better job at verifying that the domain is resolvable? There's also a limitation that this will only work when the domain points to a host running a HTTP server.


<!-- Sent from Reviewable.io -->

2024-01-19 10:26 UTC, buggmagnet requested changes
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701)* status: all files reviewed, 6 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoVvS306Pm5m9O67Q7v:-NoVvS306Pm5m9O67Q7w:bos3m7r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L0)):*
That usually happens when you switch branches from the CLI, sometimes Ccode gets conflicted and automatically deletes that file.
We actually need that file, please re-checkout that file from main like so
`git checkout main -- MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved`
___
*[`ios/MullvadVPNUITests/BaseUITestCase.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoVxoKH7JXzXNz2m6Tj:-NoVxoKH7JXzXNz2m6Tk:bmxwpzt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/BaseUITestCase.swift#L15)):*
> ```Swift
>     public static let defaultTimeout = 10.0
> 
>     // swiftlint:disable force_cast line_length
> ```

Superfluous Disable Command Violation: SwiftLint rule 'line_length' did not trigger a violation in the disabled region; remove the disable command (superfluous_disable_command)
___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoVx0ZI1_pt6cTrC9L-:-NoVx0ZI1_pt6cTrC9L0:b-59m9ef) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/RelayTests.swift#L56)):*
> ```Swift
>     }
> 
>     /// Verify that  ad serving domain is reachable by making sure the host can be found when sending HTTP request to it
> ```

Verify that `an` ad serving...
___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoW1dk523W6AuQlkPwb:-NoW1dk523W6AuQlkPwc:b-uey0qt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/RelayTests.swift#L81)):*
> ```Swift
>         task.resume()
> 
>         _ = semaphore.wait(timeout: .distantFuture)
> ```

This is a surefire way to deadlock the test when things go wrong. Since we are running with `XCTest`, we can take advantage of its asynchronous waiting APIs instead

```swift
    private func canReachAdServingDomain() -> Bool {
        guard let url = URL(string: "http://\(adServingDomain)") else { return false }
        var requestError: Error?

        let urlErrorExpectation = expectation(description: "URLSession encountered an error")
        let task = URLSession.shared.dataTask(with: url) { _, _, error in
            requestError = error
            urlErrorExpectation.fulfill()
        }

        task.resume()

        wait(for: [urlErrorExpectation], timeout: 30)

        if let urlError = requestError as? URLError {
            if urlError.code == .cannotFindHost {
                return false
            }
        }

        return true
    }
```
___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoNGFKb-LP18_HA9wJL:-NoWBlqu9t0lolqsJX_P:b-vqo7d1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/RelayTests.swift#L84)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

I'm not entirely sure whether this is a good way to verify that the domain can or cannot be resolved. Does DNS lookup do a better job at verifying that the domain is resolvable? There's also a limitation that this will only work when the domain points to a host running a HTTP server.
</blockquote></details>

I dug a bit around, I think this error code is the correct one to use.
If we want to be extra sure, when that happens, we can assert that the `response` parameter in the callback (the 2nd, before the error) is `nil`, which will be the case when the DNS is blocked. 
___
*[`ios/MullvadVPNUITests/Pages/SettingsPage.swift` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoWErKOBFM6iijFHYno:-NoWErKPAUQna774mZH0:b8tpj7b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/Pages/SettingsPage.swift#L20)):*
> ```Swift
> 
>     @discardableResult func tapVPNSettingsCell() -> Self {
>         app.tables[AccessibilityIdentifier.settingsTableView.rawValue]
> ```

To avoid calling `rawValue` everywhere, we could use write extension that does it on our behalf like so

```swift
extension XCUIElementQuery {
    subscript(key: any RawRepresentable<String>) -> XCUIElement {
        self[key.rawValue]
    }
}
```

It makes reading a nicer experience 

```swift
    @discardableResult func tapVPNSettingsCell() -> Self {
        app.tables[AccessibilityIdentifier.settingsTableView]
            .cells[AccessibilityIdentifier.preferencesCell]
            .tap()

        return self
    }
````


<!-- Sent from Reviewable.io -->

2024-01-19 15:55 UTC, rablador requested changes
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701)* status: all files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @niklasberglund)

___
*[`ios/MullvadVPNUITests/BaseUITestCase.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoVxoKH7JXzXNz2m6Tj:-NoXPIXCE3NwwMUeAba_:bj8a292) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/BaseUITestCase.swift#L15)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Superfluous Disable Command Violation: SwiftLint rule 'line_length' did not trigger a violation in the disabled region; remove the disable command (superfluous_disable_command)
</blockquote></details>

Also, please line break it somehow. Eg. 



_Code snippet:_
```Swift
Bundle(for: BaseUITestCase.self)
    .infoDictionary?["MullvadNoTimeAccountNumber"] as! String
```
___
*[`ios/MullvadVPNUITests/Pages/SettingsPage.swift` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoWErKOBFM6iijFHYno:-NoXQpo89maz_pc6txAe:b32v57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/Pages/SettingsPage.swift#L20)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

To avoid calling `rawValue` everywhere, we could use write extension that does it on our behalf like so

```swift
extension XCUIElementQuery {
    subscript(key: any RawRepresentable<String>) -> XCUIElement {
        self[key.rawValue]
    }
}
```

It makes reading a nicer experience 

```swift
    @discardableResult func tapVPNSettingsCell() -> Self {
        app.tables[AccessibilityIdentifier.settingsTableView]
            .cells[AccessibilityIdentifier.preferencesCell]
            .tap()

        return self
    }
````
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2024-01-22 08:21 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701)* status: 9 of 21 files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPNUITests/BaseUITestCase.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoVxoKH7JXzXNz2m6Tj:-NoWej4G6GqW7Pcwk-W7:byscv74) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/BaseUITestCase.swift#L15)):*
Ah yes 👍 There was a line exceeding the limit before but it has been moved.

> Also, please line break it somehow. Eg.

Oops, I see now that some were separated to multiple lines but some not. Totally agree that they should all follow the same format. Not sure all separated into multiple lines is clearer, see first code snippet below where the lines have been separated into two, and second code snippet which disables `line_length` and let these lines be long. How do you think?



_Code snippet (i):_
```Swift
    // swiftlint:disable force_cast
    let noTimeAccountNumber = Bundle(for: BaseUITestCase.self)
        .infoDictionary?["MullvadNoTimeAccountNumber"] as! String
    let hasTimeAccountNumber = Bundle(for: BaseUITestCase.self)
        .infoDictionary?["MullvadHasTimeAccountNumber"] as! String
    let fiveWireGuardKeysAccountNumber = Bundle(for: BaseUITestCase.self)
        .infoDictionary?["MullvadFiveWireGuardKeysAccountNumber"] as! String
    let iOSDevicePinCode = Bundle(for: BaseUITestCase.self)
        .infoDictionary?["MullvadIOSDevicePinCode"] as! String
    let adServingDomain = Bundle(for: BaseUITestCase.self)
        .infoDictionary?["MullvadAdServingDomain"] as! String
    // swiftlint:enable force_cast
```



_Code snippet (ii):_
```Swift
    // swiftlint:disable force_cast line_length
    let noTimeAccountNumber = Bundle(for: BaseUITestCase.self).infoDictionary?["MullvadNoTimeAccountNumber"] as! String
    let hasTimeAccountNumber = Bundle(for: BaseUITestCase.self).infoDictionary?["MullvadHasTimeAccountNumber"] as! String
    let fiveWireGuardKeysAccountNumber = Bundle(for: BaseUITestCase.self).infoDictionary?["MullvadFiveWireGuardKeysAccountNumber"] as! String
    let iOSDevicePinCode = Bundle(for: BaseUITestCase.self).infoDictionary?["MullvadIOSDevicePinCode"] as! String
    let adServingDomain = Bundle(for: BaseUITestCase.self).infoDictionary?["MullvadAdServingDomain"] as! String
    // swiftlint:enable force_cast line_length
```
___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoVx0ZI1_pt6cTrC9L-:-NoWjAxD3s50xekV5dCt:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/RelayTests.swift#L56)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Verify that `an` ad serving...
</blockquote></details>

Fixed
___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoW1dk523W6AuQlkPwb:-NoWkeJX4jLOWTuR-wMx:b-fkywll) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/RelayTests.swift#L81)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This is a surefire way to deadlock the test when things go wrong. Since we are running with `XCTest`, we can take advantage of its asynchronous waiting APIs instead

```swift
    private func canReachAdServingDomain() -> Bool {
        guard let url = URL(string: "http://\(adServingDomain)") else { return false }
        var requestError: Error?

        let urlErrorExpectation = expectation(description: "URLSession encountered an error")
        let task = URLSession.shared.dataTask(with: url) { _, _, error in
            requestError = error
            urlErrorExpectation.fulfill()
        }

        task.resume()

        wait(for: [urlErrorExpectation], timeout: 30)

        if let urlError = requestError as? URLError {
            if urlError.code == .cannotFindHost {
                return false
            }
        }

        return true
    }
```
</blockquote></details>

Ah yes, `.distantFuture` is not a good choice for timeout. Is wait preferred over semaphore? It's in a layer under the testing code, and using semaphore feels more natural than `expectation` to me here because the expectation is not on some specific data but used to wait for response.
___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 84 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoNGFKb-LP18_HA9wJL:-NoXE_3cAYJmIwusDUM1:bird6xi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/RelayTests.swift#L84)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I dug a bit around, I think this error code is the correct one to use.
If we want to be extra sure, when that happens, we can assert that the `response` parameter in the callback (the 2nd, before the error) is `nil`, which will be the case when the DNS is blocked.
</blockquote></details>

Thanks for verifying! See the updated code where both `.cannotFindHost` error and `nil` value for `response` is taken into account.
___
*[`ios/MullvadVPNUITests/Pages/SettingsPage.swift` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoWErKOBFM6iijFHYno:-NoXENu-1c0MtvtsR7wj:bri491m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/Pages/SettingsPage.swift#L20)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

To avoid calling `rawValue` everywhere, we could use write extension that does it on our behalf like so

```swift
extension XCUIElementQuery {
    subscript(key: any RawRepresentable<String>) -> XCUIElement {
        self[key.rawValue]
    }
}
```

It makes reading a nicer experience 

```swift
    @discardableResult func tapVPNSettingsCell() -> Self {
        app.tables[AccessibilityIdentifier.settingsTableView]
            .cells[AccessibilityIdentifier.preferencesCell]
            .tap()

        return self
    }
````
</blockquote></details>

Reads much better 👍 Have added the extension and removed all `.rawValue`.
___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoVvS306Pm5m9O67Q7v:-NoWeTOk9RD7LHbjUbAD:b22psr6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

That usually happens when you switch branches from the CLI, sometimes Ccode gets conflicted and automatically deletes that file.
We actually need that file, please re-checkout that file from main like so
`git checkout main -- MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved`
</blockquote></details>

Oops! Added it again


<!-- Sent from Reviewable.io -->

2024-01-22 09:19 UTC, rablador approved these changes
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701)* status: all files reviewed, 6 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPNUITests/BaseUITestCase.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoVxoKH7JXzXNz2m6Tj:-NokRJQn4D6E3GVWQLqN:b-2ob90t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/BaseUITestCase.swift#L15)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Ah yes 👍 There was a line exceeding the limit before but it has been moved.

> Also, please line break it somehow. Eg.

Oops, I see now that some were separated to multiple lines but some not. Totally agree that they should all follow the same format. Not sure all separated into multiple lines is clearer, see first code snippet below where the lines have been separated into two, and second code snippet which disables `line_length` and let these lines be long. How do you think?
</blockquote></details>

I think the first snippet is fine. We usually follow the swiftlint rather than disable it, with some exceptions where needed of course.


<!-- Sent from Reviewable.io -->

2024-01-22 17:02 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701)* status: 20 of 21 files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPNUITests/BaseUITestCase.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoVxoKH7JXzXNz2m6Tj:-Nom6cV80HP-rWxQbHRb:bld9chs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/BaseUITestCase.swift#L15)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I think the first snippet is fine. We usually follow the swiftlint rather than disable it, with some exceptions where needed of course.
</blockquote></details>

Sounds good. Have changed it to follow the format of the first snippet.


<!-- Sent from Reviewable.io -->

2024-01-23 08:49 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701)* status: all files reviewed, 6 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-01-23 14:41 UTC, buggmagnet requested changes
> Reviewed 11 of 12 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund and @rablador)

___
*[`ios/MullvadVPNUITests/BaseUITestCase.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoVxoKH7JXzXNz2m6Tj:-NoqfGti4lfEdTXwoW22:bg1kpza) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/BaseUITestCase.swift#L15)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Sounds good. Have changed it to follow the format of the first snippet.
</blockquote></details>

Yeah I would say usually as long as swiftlint + swiftformat don't complain about it, then I won't either, we've put those tools in place because we used to have endless arguments about how code should look like.
___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoW1dk523W6AuQlkPwb:-NoqfwzP9KeyBTurcXbU:b-rvbi2y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/RelayTests.swift#L81)):*
There are a couple of problems with that piece of code
- The return value of `semaphore.wait(timeout: .now() + 10)`, is not checked, so we don't know whether the code timed out, or did run to completion.
By using an expectation, we get the desired outcome, if that network call didn't run as expected, we fail the test (which would / should fail anyway)

- If the test were using the swift `async` runtime, it would be a violation of the contract that "a thread must always be allowed to progress" which semaphore prevents, which would lead to either undefined behaviour, runtime crashes, or deadlocks.

> the expectation is not on some specific data but used to wait for response.

The expectation is asserting essentially that the completion was calledback, right now, if it doesn't happen, this function is relying on the call site to indicate failure.


<!-- Sent from Reviewable.io -->

2024-01-24 09:25 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-NoW1dk523W6AuQlkPwb:-NouiIyfC38deBwquZQb:bet187u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bfc8813c24faa437eed7a66608c1d408d9696ef8/ios/MullvadVPNUITests/RelayTests.swift#L81)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

There are a couple of problems with that piece of code
- The return value of `semaphore.wait(timeout: .now() + 10)`, is not checked, so we don't know whether the code timed out, or did run to completion.
By using an expectation, we get the desired outcome, if that network call didn't run as expected, we fail the test (which would / should fail anyway)

- If the test were using the swift `async` runtime, it would be a violation of the contract that "a thread must always be allowed to progress" which semaphore prevents, which would lead to either undefined behaviour, runtime crashes, or deadlocks.

> the expectation is not on some specific data but used to wait for response.

The expectation is asserting essentially that the completion was calledback, right now, if it doesn't happen, this function is relying on the call site to indicate failure.
</blockquote></details>

Ah yes, if the timeout is reached `resultIndicatesDNSBlock` will be `false` since that's the initial value, which will be incorrect in that case. Could rewrite a bit to fix but it's easier to understand the code if checking whether timeout was reached 👍 

I'm not opposed to changing the syntax. Isn't the difference between `wait` and `DispatchSemaphore` semantical, or do they also work in different ways? For an application it would be bad to write synchronous code but for tests I'd say it's preferred, want to avoid asynchronous code in test case abstraction layer.


<!-- Sent from Reviewable.io -->

2024-01-24 13:20 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701#-:-NovcLKT4JtYpFJ8Va27:bnfp4nl)* status: 19 of 21 files reviewed, all discussions resolved (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2024-01-24 13:25 UTC, merged