Add mock api test for testing the account history feature
mullvad/mullvadvpn-app pull request #5711
Opened 2024-01-22 13:28 UTC by Pururun

Tests that the last account number is shown after logging out of an account. Also checks that clicking on that number will log the user into the account again.

2024-01-22 13:33 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5711)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/AccountHistoryMockApiTest.kt` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5711#-NolMeqEAYLaR_KsK2Ws:-NolMeqEAYLaR_KsK2Wt:boho1bd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58be0d56de1b7a8006abf15913a12c2fbad6546f/android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/AccountHistoryMockApiTest.kt#L39)):*
> ```Kotlin
>         device.findObjectWithTimeout(By.text("UNSECURED CONNECTION"))
>         app.clickAccountCog()
>         app.clickActionButtonByText("Log out")
> ```

I think that whenever possible we should, try and add a test tag and refer to that instead, this will lower the chance of test breaking when strings get updated. It will also allow us to test in other languages later as well.


<!-- Sent from Reviewable.io -->

2024-01-22 14:55 UTC, albin-mullvad reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5711)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/AccountHistoryMockApiTest.kt` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5711#-NolMeqEAYLaR_KsK2Ws:-NoleNvp2Z-0a0V-ydGS:bdje9xx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58be0d56de1b7a8006abf15913a12c2fbad6546f/android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/AccountHistoryMockApiTest.kt#L39)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I think that whenever possible we should, try and add a test tag and refer to that instead, this will lower the chance of test breaking when strings get updated. It will also allow us to test in other languages later as well.
</blockquote></details>

I believe there's value in testing what's presented on screen compared to verifying a underlying tag. Since we currently rely on texts for a lot of tests (except for where we can't) I believe it would be a good idea to discuss this in the team before we start changing it.


<!-- Sent from Reviewable.io -->

2024-01-23 11:57 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5711)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/AccountHistoryMockApiTest.kt` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5711#-NolMeqEAYLaR_KsK2Ws:-NoqAG-z1kb754s9AnjV:b7jl8c0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58be0d56de1b7a8006abf15913a12c2fbad6546f/android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/AccountHistoryMockApiTest.kt#L39)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe there's value in testing what's presented on screen compared to verifying a underlying tag. Since we currently rely on texts for a lot of tests (except for where we can't) I believe it would be a good idea to discuss this in the team before we start changing it.
</blockquote></details>

Since we already using a check to "UNSECURED CONNECTION" in multiple places to check for being logged in I made all of the call `app.ensureLoggedIn()` so we can changed it in all places if we need it in the future.


<!-- Sent from Reviewable.io -->

2024-01-24 11:57 UTC, albin-mullvad approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5711)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/AccountHistoryMockApiTest.kt` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5711#-NolMeqEAYLaR_KsK2Ws:-NovJsRp0XjP0dKJgpjI:b-7pt5h0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58be0d56de1b7a8006abf15913a12c2fbad6546f/android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/AccountHistoryMockApiTest.kt#L39)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Since we already using a check to "UNSECURED CONNECTION" in multiple places to check for being logged in I made all of the call `app.ensureLoggedIn()` so we can changed it in all places if we need it in the future.
</blockquote></details>

I suggest we go ahead with this and re-visit it when we have our meeting about testing. @Rawa sounds OK?


<!-- Sent from Reviewable.io -->

2024-01-25 12:23 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5711)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/AccountHistoryMockApiTest.kt` line 39 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5711#-NolMeqEAYLaR_KsK2Ws:-Np-Zo4w5XXVMGN_SblX:b-a78ad4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58be0d56de1b7a8006abf15913a12c2fbad6546f/android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/AccountHistoryMockApiTest.kt#L39)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

The main problem I have with is that we basically declare all our strings in our tests, which doesn't make much sense to me. If possible I believe that should be avoidable, alternatively that we start depending on our resources to actually match those. But for me it is fine to go ahead with this at the moment, we can always change this later and we are not introducing something new.
</blockquote></details>

We have a linear issue for that: https://linear.app/mullvad/issue/DROID-610/share-constants-between-test-modules


<!-- Sent from Reviewable.io -->

2024-01-25 16:11 UTC, merged