Allow users to import settings by pasting json blobs
mullvad/mullvadvpn-app pull request #5722
Opened 2024-01-24 13:37 UTC by rablador

2024-01-29 11:39 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722)* status: 0 of 14 files reviewed, 22 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadSettings/IPOverride.swift` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJQ5RN1aBPblYPXJot:-Np09Z2i7xRN0R605w4R:b-d7zi21) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadSettings/IPOverride.swift#L30)):*
> ```Swift
>     }
> 
>     init(hostname: String, ipv4Address: IPv4Address?, ipv6Address: IPv6Address?) throws {
> ```

do we really needs to consider `nil` values for IPs when they are imported through Json text or file in constructor? It makes sense to consider variables optional that's why user inputs invalid json format which  we have but in constructor we knew these values should be valid and required. It's used in Unit test but I am thinking maybe this covers our assumption for unit case : 



_Code snippet:_
```Swift
    public init(hostname: String, ipv4Address: IPv4Address, ipv6Address: IPv6Address) {
        self.hostname = hostname
        self.ipv4Address = ipv4Address
        self.ipv6Address = ipv6Address
    }
```
___
*[`ios/MullvadSettings/IPOverrideRepository.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJRpUL-nBjF1Zw-Q3_:-NpJRpUL-nBjF1Zw-Q3a:b-ax41rv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadSettings/IPOverrideRepository.swift#L14)):*
> ```Swift
>     func add(_ overrides: [IPOverride])
>     func fetchAll() -> [IPOverride]
>     func fetchByHostname(_ hostname: String) -> IPOverride?
> ```

for the code consistency let's keep the function name like the thing we have for `fetch(by id: UUID)` in `AccessMethodRepositoryProtocol`

`func fetch(by hostname: String)`
___
*[`ios/MullvadSettings/IPOverrideRepository.swift` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJUpfsBB-Im_q-TRJz:-NpJUpfsBB-Im_q-TRK-:bzgy5hu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadSettings/IPOverrideRepository.swift#L16)):*
> ```Swift
>     func fetchByHostname(_ hostname: String) -> IPOverride?
>     func deleteAll()
>     func parseData(_ data: Data) throws -> [IPOverride]
> ```

the same goes for here:
`func parse(data: Data)  throws-> [IPOverride]`
___
*[`ios/MullvadSettings/IPOverrideRepository.swift` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJVHAr6yOcVfxORzq4:-NpJVHAr6yOcVfxORzq5:bfkrqjj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadSettings/IPOverrideRepository.swift#L26)):*
> ```Swift
> 
>         overrides.forEach { override in
>             if let existingOverrideIndex = storedOverrides.firstIndex(where: { $0.hostname == override.hostname }) {
> ```

do user really add/update the json? or any time user import them through file or text, shouldn't it be replaced with the old one?
___
*[`ios/MullvadSettings/IPOverrideRepository.swift` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJU7QC-0SmzGFMyWW6:-NpJU7QC-0SmzGFMyWW7:b-4ghfbb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadSettings/IPOverrideRepository.swift#L46)):*
> ```Swift
>             try writeIpOverrides(storedOverrides)
>         } catch {
>             print("Could not add override(s): \(overrides) \nError: \(error)")
> ```

let's keep it in `log`
___
*[`ios/MullvadSettings/IPOverrideRepository.swift` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJVq7M1TJ5tdY442CZ:-NpJVq7M1TJ5tdY442C_:b-4ghfbb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadSettings/IPOverrideRepository.swift#L62)):*
> ```Swift
>             try SettingsManager.store.delete(key: .ipOverrides)
>         } catch {
>             print("Could not delete all overrides. \nError: \(error)")
> ```

let's keep it in `log`
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJcOfGARjhdCPQWMrL:-NpJcOfGARjhdCPQWMrM:b-u7lqmp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift#L14)):*
> ```Swift
> import UIKit
> 
> class IPOverrideCoordinator: Coordinator, Presenting, SettingsChildCoordinator {
> ```

it seems we mixed the `Intercator` with `Coordinator`. in my opinion Coordinator is responsible for routing between deiffrent views not controlling the status and business logic
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJXW0DCTNQR4VbEHpK:-NpJXW0DCTNQR4VbEHpL:b657jum) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift#L18)):*
> ```Swift
>     let repository: IPOverrideRepositoryProtocol
> 
>     lazy var ipOverrideViewController: IPOverrideViewController = {
> ```

keep it `private`
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJbSwG1sgWAwG1d_aG:-NpJbSwHBQnsxlSprhlW:b-wvmvuh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift#L35)):*
> ```Swift
>     func start(animated: Bool) {
>         navigationController.pushViewController(ipOverrideViewController, animated: animated)
>         resetToDefaultStatus()
> ```

can not it be done in `IPOverrideTextViewController`? 
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJbck502c7YYHEEfno:-NpJbck502c7YYHEEfnp:b-q4j3l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift#L38)):*
> ```Swift
>     }
> 
>     private func showImportTextView() {
> ```

nit: this part could be put in and there is no need to make fiction for the thing calls once 

` func controllerShouldShowTextImportView(_ controller: IPOverrideViewController)`
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJcxmw6HwiQ9HWORlK:-NpJcxmw6HwiQ9HWORlL:b5c99d4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift#L79)):*
> ```Swift
>         } catch {
>             ipOverrideViewController.setStatus(.importFailed(context))
>             print("Error importing ip overrides: \(error)")
> ```

having print is valid for logging?
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideStatus.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJd7j_9GNqZ2KO7Zpm:-NpJd7j_9GNqZ2KO7Zpn:b-hai10t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideStatus.swift#L11)):*
> ```Swift
> import UIKit
> 
> enum IPOverrideStatus {
> ```

nit we could comform `CustomStringConvertible` and take advantage from `description` for `statusTitle`



_Code snippet:_
```Swift
enum IPOverrideStatus : CustomStringConvertible {
    case active, noImports, importSuccessful(Context), importFailed(Context)

    enum Context {
       [...]

2024-01-30 10:46 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722)* status: 0 of 14 files reviewed, 22 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadSettings/IPOverride.swift` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJQ5RN1aBPblYPXJot:-NpOoA2Z8qDSa45B7lC-:bkgs9kn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadSettings/IPOverride.swift#L30)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

do we really needs to consider `nil` values for IPs when they are imported through Json text or file in constructor? It makes sense to consider variables optional that's why user inputs invalid json format which  we have but in constructor we knew these values should be valid and required. It's used in Unit test but I am thinking maybe this covers our assumption for unit case :
</blockquote></details>

According to spec, only one of the two is required, which means that users can input json without values for either ipv4 or ipv6.
___
*[`ios/MullvadSettings/IPOverrideRepository.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJRpUL-nBjF1Zw-Q3_:-NpOp-zr5HQIf3UVWm1w:b-8h59pc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadSettings/IPOverrideRepository.swift#L14)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

for the code consistency let's keep the function name like the thing we have for `fetch(by id: UUID)` in `AccessMethodRepositoryProtocol`

`func fetch(by hostname: String)`
</blockquote></details>

Yes and no. I agree with the naming convention in general, but UUID has a specific type, which makes `fetch(by: <UUID>)` make sense at call site. For hostname requiring a string, `fetch(by: <String>)` doesn't tell you anything about what's required without looking at documentation or full function definition.
___
*[`ios/MullvadSettings/IPOverrideRepository.swift` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJUpfsBB-Im_q-TRJz:-NpOpfJ36QSSkyVfxcFd:bwe6zgp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadSettings/IPOverrideRepository.swift#L16)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

the same goes for here:
`func parse(data: Data)  throws-> [IPOverride]`
</blockquote></details>

This one I agree with. :)
___
*[`ios/MullvadSettings/IPOverrideRepository.swift` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJVHAr6yOcVfxORzq4:-NpOq4Ba1t2GcP3npM-8:bn639fp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadSettings/IPOverrideRepository.swift#L26)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

do user really add/update the json? or any time user import them through file or text, shouldn't it be replaced with the old one?
</blockquote></details>

The spec says that we should add to the list rather than replace it. Also, only affected values should be changes, eg. only the ipv4 address if ipv6 isn't in the data.
___
*[`ios/MullvadSettings/IPOverrideRepository.swift` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJU7QC-0SmzGFMyWW6:-NpOqOAH3CWhjzpaYSac:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadSettings/IPOverrideRepository.swift#L46)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

let's keep it in `log`
</blockquote></details>

Done.
___
*[`ios/MullvadSettings/IPOverrideRepository.swift` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJVq7M1TJ5tdY442CZ:-NpOqd3S-4V42KcmgRCw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadSettings/IPOverrideRepository.swift#L62)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

let's keep it in `log`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJcOfGARjhdCPQWMrL:-NpOr80aA0aIY6xv-fHp:b-uniy6x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift#L14)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it seems we mixed the `Intercator` with `Coordinator`. in my opinion Coordinator is responsible for routing between deiffrent views not controlling the status and business logic
</blockquote></details>

I'll see if I can move things around a bit.
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJXW0DCTNQR4VbEHpK:-NpOrMmX4-LfYTMynU2U:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift#L18)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

keep it `private`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJbSwG1sgWAwG1d_aG:-NpOrXEX71NaU3LF-VtM:b7ba18q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift#L35)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

can not it be done in `IPOverrideTextViewController`?
</blockquote></details>

I'll move things around a bit.
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJbck502c7YYHEEfno:-NpOrq4DEf3J7UgNY4k4:b7ba18q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift#L38)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit: this part could be put in and there is no need to make fiction for the thing calls once 

` func controllerShouldShowTextImportView(_ controller: IPOverrideViewController)`
</blockquote></details>

I'll move things around a bit.
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift` line 79 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJcxmw6HwiQ9HWORlK:-NpOrru91gb-0MBQ1cnN:bgejem6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift#L79)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

having print is valid for logging?
</blockquote></details>

Changed to log.
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideStatus.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJd7j_9GNqZ2KO7Zpm:-NpOyBTkEivZz-s8CLx8:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideStatus.swift#L11)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit we could comform `CustomStringConvertible` and take advantage from `description` for `statusTitle`
</blockquote></details>

Fixed.
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideStatus.swift` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/57 [...]

2024-01-30 11:57 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722)* status: 0 of 15 files reviewed, 22 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpJcOfGARjhdCPQWMrL:-NpPDehP9ziH0ihkJ45J:b-d1b8o8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d877771031ee027db51f661d52ac4b7b7ebc0b8c/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift#L14)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I'll see if I can move things around a bit.
</blockquote></details>

I mostly wanted to keep things simple since, but I agree that it does break pattern.


<!-- Sent from Reviewable.io -->

2024-02-02 14:00 UTC, buggmagnet requested changes
> Reviewed 3 of 14 files at r1, 7 of 10 files at r2, 4 of 6 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722)* status: 15 of 16 files reviewed, 28 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadSettings/IPOverride.swift` line 36 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpdUm9ZDPmWVXksoaFK:-NpdUm9ZDPmWVXksoaFL:boata9o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a28ef2af3cd91a89a1e8225cb8bbeb0182b72d0/ios/MullvadSettings/IPOverride.swift#L36)):*
> ```Swift
> 
>         if self.ipv4Address.isNil && self.ipv6Address.isNil {
>             throw NSError(domain: "IPOverrideInitDomain", code: NSFormattingError)
> ```

We could / should probably add a constant for the domain / and why not use a custom error here too ?
___
*[`ios/MullvadSettings/IPOverrideRepository.swift` line 25 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-Npdb-7dDEPnLGNosNW6:-Npdb-7dDEPnLGNosNW7:braf8q2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a28ef2af3cd91a89a1e8225cb8bbeb0182b72d0/ios/MullvadSettings/IPOverrideRepository.swift#L25)):*
> ```Swift
>     public init() {}
> 
>     public func add(_ overrides: [IPOverride]) {
> ```

Wouldn't it be simpler to use sets here (unless I misunderstood this) ?

```swift
public func add(_ overrides: [IPOverride]) {
    let storedOverrides = Set(fetchAll())
    var overridesSet = Set(overrides)
    overridesSet.formUnion(storedOverrides)
    do {
        try writeIpOverrides(overridesSet.map { $0 })
    } catch {
        logger.error("Could not add override(s): \(overrides) \nError: \(error)")
    }
}
```
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift` line 37 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-Npe229c4yN7r5UIIpmD:-Npe229c4yN7r5UIIpmE:b-g2m28e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a28ef2af3cd91a89a1e8225cb8bbeb0182b72d0/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift#L37)):*
> ```Swift
>     }
> 
>     func `import`(url: URL) {
> ```

I like the name of the API here :thumbsup: 
swifty style, looks good !
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift` line 63 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-Npe2JOP3WHQfyfxdlHx:-Npe2JOP3WHQfyfxdlHy:b-wjxbj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a28ef2af3cd91a89a1e8225cb8bbeb0182b72d0/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift#L63)):*
> ```Swift
>         }
> 
>         setDefaultStatus(delay: .seconds(10))
> ```

It would be nice to have a comment explaining the 10 seconds delay
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift` line 244 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpdZZIE22H5id9vu8xR:-NpdZZIE22H5id9vu8xS:b-nu6zz5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a28ef2af3cd91a89a1e8225cb8bbeb0182b72d0/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift#L244)):*
> ```Swift
>     func documentPicker(_ controller: UIDocumentPickerViewController, didPickDocumentsAt urls: [URL]) {
>         if let url = urls.first {
>             interactor.import(url: url)
> ```

This won't work unless you do the following changes
```swift
guard url.startAccessingSecurityScopedResource() else {
    return //Indicate that we couldn't access the ressource here, maybe throw ?
}
interactor.import(url: url)
url.stopAccessingSecurityScopedResource()
```
___
*[`ios/MullvadVPNTests/IPOverrideRepositoryTests.swift` line 49 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-Npe4kse8-CeUBL35zez:-Npe4ksf8vPjz8VLyFPJ:behuved) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a28ef2af3cd91a89a1e8225cb8bbeb0182b72d0/ios/MullvadVPNTests/IPOverrideRepositoryTests.swift#L49)):*
> ```Swift
>         let override1 = try IPOverride(hostname: "Host 1", ipv4Address: .any, ipv6Address: nil)
>         let override2 = try IPOverride(hostname: "Host 1", ipv4Address: .allHostsGroup, ipv6Address: .broadcast)
>         repository.add([override1, override2])
> ```

Technically, a user cannot add 2 different overrides in one action
It would be better IMHO to mimic the users action to make sure we test the right things
```swift
        let override1 = try IPOverride(hostname: "Host 1", ipv4Address: .any, ipv6Address: nil)
        repository.add([override1])
        let override2 = try IPOverride(hostname: "Host 1", ipv4Address: .allHostsGroup, ipv6Address: .broadcast)
        repository.add([override2])
```
___
*[`ios/MullvadVPNTests/IPOverrideTests.swift` line 16 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-Npe6PBr6BqA5iO-ykus:-Npe6PBsEMt1XMpmD_Ra:bfe35xz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a28ef2af3cd91a89a1e8225cb8bbeb0182b72d0/ios/MullvadVPNTests/IPOverrideTests.swift#L16)):*
> ```Swift
> 
>     func testCanParseOverrides() throws {
>         XCTAssertNoThrow(try parseData(from: overrides))
> ```

We should also make sure that the values are correclty imported given that we're relying on Apple's parser for IPv4 and IPv6 addresses, at least make sure that they're compatible with our own types `AnyIPaddress`


<!-- Sent from Reviewable.io -->

2024-02-02 20:54 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722)* status: 15 of 16 files reviewed, 28 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pinkisemils)

___
*[`ios/MullvadSettings/IPOverride.swift` line 36 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpdUm9ZDPmWVXksoaFK:-NpfX14a34WveT90yYV1:bqd4fcz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a28ef2af3cd91a89a1e8225cb8bbeb0182b72d0/ios/MullvadSettings/IPOverride.swift#L36)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We could / should probably add a constant for the domain / and why not use a custom error here too ?
</blockquote></details>

Done, created a custom error.
___
*[`ios/MullvadSettings/IPOverrideRepository.swift` line 25 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-Npdb-7dDEPnLGNosNW6:-NpfSxCY-ybN83piLFUj:b-bfhpvc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a28ef2af3cd91a89a1e8225cb8bbeb0182b72d0/ios/MullvadSettings/IPOverrideRepository.swift#L25)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Wouldn't it be simpler to use sets here (unless I misunderstood this) ?

```swift
public func add(_ overrides: [IPOverride]) {
    let storedOverrides = Set(fetchAll())
    var overridesSet = Set(overrides)
    overridesSet.formUnion(storedOverrides)
    do {
        try writeIpOverrides(overridesSet.map { $0 })
    } catch {
        logger.error("Could not add override(s): \(overrides) \nError: \(error)")
    }
}
```
</blockquote></details>

Indeed. I'm just not sure about the spec here. I interpreted it as replacing only values that are clashing, down to individual values inside the overrides themselves. Looking at it again it might be enough to simply replace the entirety of a host with a new one. Waiting for answer from @pinkisemils.
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift` line 37 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-Npe229c4yN7r5UIIpmD:-NpfTIow0Y7_lGfPwOjc:b32vhw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a28ef2af3cd91a89a1e8225cb8bbeb0182b72d0/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift#L37)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I like the name of the API here :thumbsup: 
swifty style, looks good !
</blockquote></details>

:)
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift` line 63 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-Npe2JOP3WHQfyfxdlHx:-NpeE0SQ8KJHw2wZ2rOc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a28ef2af3cd91a89a1e8225cb8bbeb0182b72d0/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift#L63)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It would be nice to have a comment explaining the 10 seconds delay
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift` line 244 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-NpdZZIE22H5id9vu8xR:-NpfN5Ua8f0bb9EGpveu:b-1ggt5y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a28ef2af3cd91a89a1e8225cb8bbeb0182b72d0/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift#L244)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This won't work unless you do the following changes
```swift
guard url.startAccessingSecurityScopedResource() else {
    return //Indicate that we couldn't access the ressource here, maybe throw ?
}
interactor.import(url: url)
url.stopAccessingSecurityScopedResource()
```
</blockquote></details>

It seems to be dependent on where you store your files. Eg. ` Downloads` doesn't require scope, but I think we need this change anyway since people can store file basically anywhere.
___
*[`ios/MullvadVPNTests/IPOverrideRepositoryTests.swift` line 49 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-Npe4kse8-CeUBL35zez:-NpfNZYL7PlawGcjeN1D:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a28ef2af3cd91a89a1e8225cb8bbeb0182b72d0/ios/MullvadVPNTests/IPOverrideRepositoryTests.swift#L49)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Technically, a user cannot add 2 different overrides in one action
It would be better IMHO to mimic the users action to make sure we test the right things
```swift
        let override1 = try IPOverride(hostname: "Host 1", ipv4Address: .any, ipv6Address: nil)
        repository.add([override1])
        let override2 = try IPOverride(hostname: "Host 1", ipv4Address: .allHostsGroup, ipv6Address: .broadcast)
        repository.add([override2])
```
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/IPOverrideTests.swift` line 16 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-Npe6PBr6BqA5iO-ykus:-NpfOMuT6WYyC10hoGjm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7a28ef2af3cd91a89a1e8225cb8bbeb0182b72d0/ios/MullvadVPNTests/IPOverrideTests.swift#L16)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We should also make sure that the values are correclty imported given that we're relying on Apple's parser for IPv4 and IPv6 addresses, at least make sure that they're compatible with our own types `AnyIPaddress`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-06 16:01 UTC, buggmagnet approved these changes
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722)* status: all files reviewed, 24 unresolved discussions (waiting on @mojganii, @pinkisemils, and @rablador)

___
*[`ios/MullvadVPN/Extensions/URL+Scoping.swift` line 13 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-Npz7bWKAP_gI1ixSkfu:-Npz7bWKAP_gI1ixSkfv:bx8dg4i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79012fb979f6ffb8e8670d31f2d691fddc7dae60/ios/MullvadVPN/Extensions/URL%2BScoping.swift#L13)):*
> ```Swift
> extension URL {
>     func securelyScoped(_ completionHandler: (Self) -> Void) {
>         if startAccessingSecurityScopedResource() {
> ```

I know I wrote that snippet, but we should probably indicate failure if `startAccessingSecurityScopedResource()` returns `false`, otherwise the UI will just deadlock won't it ?
Because we will never end up calling `resetToDefaultStatus` 

It's okay to fix this in the followup PR


<!-- Sent from Reviewable.io -->

2024-02-06 16:11 UTC, mojganii approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet, @pinkisemils, and @rablador)



<!-- Sent from Reviewable.io -->

2024-02-07 08:02 UTC, buggmagnet approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii and @rablador)



<!-- Sent from Reviewable.io -->

2024-02-07 08:12 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Extensions/URL+Scoping.swift` line 13 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722#-Npz7bWKAP_gI1ixSkfu:-Nq1bxI-6hAPTExQgKGJ:b-lnhtfp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/79012fb979f6ffb8e8670d31f2d691fddc7dae60/ios/MullvadVPN/Extensions/URL%2BScoping.swift#L13)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I know I wrote that snippet, but we should probably indicate failure if `startAccessingSecurityScopedResource()` returns `false`, otherwise the UI will just deadlock won't it ?
Because we will never end up calling `resetToDefaultStatus` 

It's okay to fix this in the followup PR
</blockquote></details>

Will follow up in next PR.


<!-- Sent from Reviewable.io -->

2024-02-07 08:19 UTC, merged