Improve DeviceListScreen
mullvad/mullvadvpn-app pull request #5754
Opened 2024-02-02 09:18 UTC by Pururun

- Display loading state with a spinner
- Fix alignment of success icon when the device list is empty
- Fix remove icon size
- Remove alpha from remove icon
- Add more preview cases
- Fix dates not showing in preview

Compared to previous version:
![Screenshot 2024-02-02 at 10 19 09](https://github.com/mullvad/mullvadvpn-app/assets/1643265/7187ac6f-86ba-46d0-afbe-5e4bd8b9de10)

New loading state:
![Screenshot_20240202_092355](https://github.com/mullvad/mullvadvpn-app/assets/1643265/50e0c436-ccd1-4a55-82bf-bb90950aa8ce)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5754)

2024-02-02 15:24 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5754)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt` line 235 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5754#-NpeP_Z1CkTXRZXFio-p:-NpeP_Z25pgnCMJArfJD:b-5xrh7b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9734ed7ce2ad8364a5f3b3fc694d5373d9fc04c6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt#L235)):*
> ```Kotlin
>                         .fillMaxWidth(),
>                 verticalArrangement =
>                     if (state.isLoading) {
> ```

Feel a bit confusing to have if/else statements here for loading and it makes it a bit heard to read. Maybe it would be easier to replace the entire content to have a composable for e.g DeviceListContent & DeviceListLoading?
___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5754#-NpeOtwdEtDF_779S00L:-NpeOtwdEtDF_779S00M:bykqtlf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9734ed7ce2ad8364a5f3b3fc694d5373d9fc04c6/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt#L35)):*
> ```Kotlin
>     val countryRowPadding: Dp = 18.dp,
>     val customPortBoxMinWidth: Dp = 80.dp,
>     val deleteIconSize: Dp = 18.dp,
> ```

This size looks too small to be according to the Material guidelines? Feels like this icon should be at least 24x24 with 1 padding around.

https://m3.material.io/components/icon-buttons/specs#e8988ae0-50d6-4192-929e-c4558bcac4e1


<!-- Sent from Reviewable.io -->

2024-02-05 10:07 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5754)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt` line 235 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5754#-NpeP_Z1CkTXRZXFio-p:-NpsjCpw1peoaqnAupZt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9734ed7ce2ad8364a5f3b3fc694d5373d9fc04c6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt#L235)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Feel a bit confusing to have if/else statements here for loading and it makes it a bit heard to read. Maybe it would be easier to replace the entire content to have a composable for e.g DeviceListContent & DeviceListLoading?
</blockquote></details>

Done.
___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5754#-NpeOtwdEtDF_779S00L:-NpsjDL-D9-kpwUjDvWN:b6wzlxy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9734ed7ce2ad8364a5f3b3fc694d5373d9fc04c6/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt#L35)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This size looks too small to be according to the Material guidelines? Feels like this icon should be at least 24x24 with 1 padding around.

https://m3.material.io/components/icon-buttons/specs#e8988ae0-50d6-4192-929e-c4558bcac4e1
</blockquote></details>

Will talk to design.


<!-- Sent from Reviewable.io -->

2024-02-07 09:50 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5754)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5754#-NpeOtwdEtDF_779S00L:-Nq1y9HrAq54DWIrTdzk:be2y0on) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9734ed7ce2ad8364a5f3b3fc694d5373d9fc04c6/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt#L35)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Will talk to design.
</blockquote></details>

Updated to 24dp as requested.


<!-- Sent from Reviewable.io -->

2024-02-07 09:52 UTC, Rawa approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5754)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-02-07 12:33 UTC, merged