Added the beginning of unit tests fro StartTunnelOperation
mullvad/mullvadvpn-app pull request #5758
Opened 2024-02-02 14:15 UTC by acb-mv

This is the first step in an ongoing process of adding unit tests for logic. This creates a unit test class for StartTunnelOperation and a (currently incomplete) mock of TunnelInteractor for use in it. The two tests currently implemented check that establishing tunnels fails if not logged in, and that in the disconnecting state, the next operation is set to reconnect. Additional logic will need to be tested, though this will involve teasing out intertwined logic and isolating it.

2024-02-02 15:26 UTC, buggmagnet requested changes
Great start ! 

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758#-:-NpeQSfv99dgifIP1GUC:b-svn4qz)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @acb-mv and @mojganii)

___
*[`ios/build-rust-library.sh` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758#-NpeJXDdEEiqLcqHfwY9:-NpeJXDdEEiqLcqHfwYA:bjqigjv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c0cba92009c2c32f91c580b9eaba884103e1fee5/ios/build-rust-library.sh#L56)):*
> ```Shell
>         "$HOME"/.cargo/bin/cargo build -p "$FFI_TARGET" --lib --target aarch64-apple-ios
>       else
>         "$HOME"/.cargo/bin/cargo build -p "$FFI_TARGET" --lib $RELFLAG --target aarch64-apple-ios-sim
> ```

it should be consistent with the other targets, why is only this line unquoted ?
___
*[`ios/MullvadVPNTests/StartTunnelOperationTests.swift` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758#-NpeJp0FCGy2VmrRVTxu:-NpeJp0FCGy2VmrRVTxv:bewws43) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c0cba92009c2c32f91c580b9eaba884103e1fee5/ios/MullvadVPNTests/StartTunnelOperationTests.swift#L16)):*
> ```Swift
> 
> 
> final class StartTunnelOperationTests: XCTestCase {
> ```

I know Xcode adds the `final` keyword automatically, but the swift compiler is smart enough to do it.
It's not a big deal here, but in genera, unless we want to make the intent explicit that we want a class to be final, we can omit the keyword
___
*[`ios/MullvadVPNTests/StartTunnelOperationTests.swift` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758#-NpeLU15BQ9Qz8UDJViX:-NpeLU15BQ9Qz8UDJViY:bj753ml) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c0cba92009c2c32f91c580b9eaba884103e1fee5/ios/MullvadVPNTests/StartTunnelOperationTests.swift#L23)):*
> ```Swift
>         let operationQueue = AsyncOperationQueue()
>         let settings = LatestTunnelSettings()
>         let expectation = XCTestExpectation(description:"")
> ```

A couple of things to note here 

Let's try to have meaningful description, when we look at failure logs, it will be much easier to see.
In the logs, this will appear as `Failed due to unwaited expectation ''.` which doesn't really help to see what went wrong.
However if it says instead : `Failed due to unwaited expectation 'Failed login attempt'` 
It's much clearer to see what went wrong.

What is expected here ? The name `expectation` doesn't tell me anything.

Suggestion
```swift
let failedLogin = expectation(description: "Failed login attempt")
```

But most importantly, you should really call the `expectation` function, otherwise the created expectation won't count the number of times it's been fulfilled

```swift
    func testExpectations() throws {
        let exp1 = XCTestExpectation(description: "First expectation")
        exp1.fulfill()
        exp1.fulfill()
        exp1.fulfill()
        wait(for: [exp1]) // ✅ No failure here

        let exp2 = expectation(description: "Second expectation") // ❌ Failed due to unwaited expectation 'Second expectation'.

        exp2.fulfill()
        exp2.fulfill() // ❌ API violation - multiple calls made to -[XCTestExpectation fulfill] for Second expectation. (NSInternalInconsistencyException)
        exp2.fulfill()
        wait(for: [exp2])
    }

```
___
*[`ios/MullvadVPNTests/StartTunnelOperationTests.swift` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758#-NpePtq7EgUaK8AarDWo:-NpePtq7EgUaK8AarDWp:b-d62w22) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c0cba92009c2c32f91c580b9eaba884103e1fee5/ios/MullvadVPNTests/StartTunnelOperationTests.swift#L36)):*
> ```Swift
>         
>         operationQueue.addOperation(operation)
>         wait(for: [expectation], timeout: 10.0)
> ```

No need to wait for so long, 1 second should be more than enough no ?


<!-- Sent from Reviewable.io -->

2024-02-02 15:28 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @acb-mv and @mojganii)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758#-NpeQZkdE4M8-Cl9tLJU:-NpeQZkdE4M8-Cl9tLJV:b-8medjd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c0cba92009c2c32f91c580b9eaba884103e1fee5/ios/MullvadVPN.xcodeproj/project.pbxproj#L41)):*
> ```
> 		0697D6E728F01513007A9E99 /* TransportMonitor.swift in Sources */ = {isa = PBXBuildFile; fileRef = 0697D6E628F01513007A9E99 /* TransportMonitor.swift */; };
> 		06AC116228F94C450037AF9A /* ApplicationConfiguration.swift in Sources */ = {isa = PBXBuildFile; fileRef = 58BFA5CB22A7CE1F00A6173D /* ApplicationConfiguration.swift */; };
> 		44DD7D242B6CFFD70005F67F /* StartTunnelOperationTests.swift in Sources */ = {isa = PBXBuildFile; fileRef = 44DD7D232B6CFFD70005F67F /* StartTunnelOperationTests.swift */; };
> ```

Whenever we add new files, we try to keep them alphabetically ordered. 
If you right click on the `MullvadVPNTests` folder, and select `Sort by Name` it should do the right thing


<!-- Sent from Reviewable.io -->

2024-02-06 08:58 UTC, buggmagnet reviewed
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @acb-mv and @mojganii)

___
*[`ios/MullvadVPNTests/StartTunnelOperationTests.swift` line 23 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758#-NpxccdB8z66T5kxAjbU:-NpxccdB8z66T5kxAjbV:b6snj9b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceaadb83a04be4bdda49958f7998c57e85b0d3ab/ios/MullvadVPNTests/StartTunnelOperationTests.swift#L23)):*
To quote the [swift API design guidelines](https://www.swift.org/documentation/api-design-guidelines/#naming)
> **Avoid abbreviations.** Abbreviations, especially non-standard ones, are effectively terms-of-art, because understanding depends on correctly translating them into their non-abbreviated forms.
___
*[`ios/MullvadVPNTests/StartTunnelOperationTests.swift` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758#-NpxcUpQ65wp0PE7ehAN:-NpxcUpQ65wp0PE7ehAO:bj2cdcs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceaadb83a04be4bdda49958f7998c57e85b0d3ab/ios/MullvadVPNTests/StartTunnelOperationTests.swift#L27)):*
> ```Swift
>             dispatchQueue: testQueue,
>             interactor: MockTunnelInteractor(isConfigurationLoaded: true, settings: settings, deviceState: .loggedOut)) { result in
>                 
> ```

Please don't forget to run `swiftformat` before pushing changes


<!-- Sent from Reviewable.io -->

2024-02-07 10:26 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/build-rust-library.sh` line 56 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758#-NpeJXDdEEiqLcqHfwY9:-Nq243Da0-MQbG30Q9vJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c0cba92009c2c32f91c580b9eaba884103e1fee5/ios/build-rust-library.sh#L56)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

it should be consistent with the other targets, why is only this line unquoted ?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758#-NpeQZkdE4M8-Cl9tLJU:-Npsp8kH09if9CJTMPKE:b-l720p6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c0cba92009c2c32f91c580b9eaba884103e1fee5/ios/MullvadVPN.xcodeproj/project.pbxproj#L41)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Whenever we add new files, we try to keep them alphabetically ordered. 
If you right click on the `MullvadVPNTests` folder, and select `Sort by Name` it should do the right thing
</blockquote></details>

Fair enough. 
I have been thinking that the tests project structure should probably mirror the structure of the app whose code is being tested, rather than being flat. What do you think?
___
*[`ios/MullvadVPNTests/StartTunnelOperationTests.swift` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758#-NpeJp0FCGy2VmrRVTxu:-Nq1sl-R-QR6jMFb2L5v:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c0cba92009c2c32f91c580b9eaba884103e1fee5/ios/MullvadVPNTests/StartTunnelOperationTests.swift#L16)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I know Xcode adds the `final` keyword automatically, but the swift compiler is smart enough to do it.
It's not a big deal here, but in genera, unless we want to make the intent explicit that we want a class to be final, we can omit the keyword
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/StartTunnelOperationTests.swift` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758#-NpeLU15BQ9Qz8UDJViX:-Nq25RmBBAAjBJAdK3Ki:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c0cba92009c2c32f91c580b9eaba884103e1fee5/ios/MullvadVPNTests/StartTunnelOperationTests.swift#L23)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

A couple of things to note here 

Let's try to have meaningful description, when we look at failure logs, it will be much easier to see.
In the logs, this will appear as `Failed due to unwaited expectation ''.` which doesn't really help to see what went wrong.
However if it says instead : `Failed due to unwaited expectation 'Failed login attempt'` 
It's much clearer to see what went wrong.

What is expected here ? The name `expectation` doesn't tell me anything.

Suggestion
```swift
let failedLogin = expectation(description: "Failed login attempt")
```

But most importantly, you should really call the `expectation` function, otherwise the created expectation won't count the number of times it's been fulfilled

```swift
    func testExpectations() throws {
        let exp1 = XCTestExpectation(description: "First expectation")
        exp1.fulfill()
        exp1.fulfill()
        exp1.fulfill()
        wait(for: [exp1]) // ✅ No failure here

        let exp2 = expectation(description: "Second expectation") // ❌ Failed due to unwaited expectation 'Second expectation'.

        exp2.fulfill()
        exp2.fulfill() // ❌ API violation - multiple calls made to -[XCTestExpectation fulfill] for Second expectation. (NSInternalInconsistencyException)
        exp2.fulfill()
        wait(for: [exp2])
    }

```
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/StartTunnelOperationTests.swift` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758#-NpePtq7EgUaK8AarDWo:-Nq1rgYlDvD34kzR3pCr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c0cba92009c2c32f91c580b9eaba884103e1fee5/ios/MullvadVPNTests/StartTunnelOperationTests.swift#L36)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

No need to wait for so long, 1 second should be more than enough no ?
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/StartTunnelOperationTests.swift` line 23 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758#-NpxccdB8z66T5kxAjbU:-Nq1sj_CAl77SEhXXuTA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceaadb83a04be4bdda49958f7998c57e85b0d3ab/ios/MullvadVPNTests/StartTunnelOperationTests.swift#L23)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

To quote the [swift API design guidelines](https://www.swift.org/documentation/api-design-guidelines/#naming)
> **Avoid abbreviations.** Abbreviations, especially non-standard ones, are effectively terms-of-art, because understanding depends on correctly translating them into their non-abbreviated forms.
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/StartTunnelOperationTests.swift` line 27 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758#-NpxcUpQ65wp0PE7ehAN:-Nq1rhim8x9mUfGIXKwm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceaadb83a04be4bdda49958f7998c57e85b0d3ab/ios/MullvadVPNTests/StartTunnelOperationTests.swift#L27)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Please don't forget to run `swiftformat` before pushing changes
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-07 14:18 UTC, merged