Refactor LocationDataSource for  custom lists
mullvad/mullvadvpn-app pull request #5778
Opened 2024-02-06 16:28 UTC by mojganii

Enhance `LocationDataSource` for seamless integration with multi-section support, a prerequisite for custom lists.

2024-02-09 15:28 UTC, rablador reviewed
> Reviewed 5 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778)* status: 5 of 11 files reviewed, 9 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqCuecH0GWtqYnZUZWK:-NqCuecH0GWtqYnZUZWL:becd725) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L26)):*
> ```Swift
>                 countryNode.showsChildren = false
> 
>                 if text.isEmpty || countryNode.displayName.fuzzyMatch(text) {
> ```

We already check for empty text at the start of the function, so that shouldn't be needed here.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDE-f09CWFx8DgYzI4:-NqDE-f09CWFx8DgYzI5:b-qrcqks) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L18)):*
> ```Swift
>     private let tableView: UITableView
>     private let locationCellFactory: LocationCellFactory
>     private var datasources: [LocationDataSourceProtocol] = []
> ```

Nit: dataSources
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 54 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDG5xODVy-QbmCgHVs:-NqDG5xODVy-QbmCgHVt:bpsud3f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L54)):*
> ```Swift
>         }
>         var list: [[LocationCellViewModel]] = []
>         for section in 0 ..< datasources.count {
> ```

Nit: Seeing that we don't use the index anyway, we might as well do `dataSources.forEach { section in ... }`. Both here and in other parts of the code.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 99 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDHCAY8fbChxFViCzU:-NqDHCAY8fbChxFViCzV:buniui4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L99)):*
> ```Swift
> 
>         let sections = Array(SelectLocationGroup.allCases)
>         snapshot.appendSections(sections)
> ```

Nit: No need to cast `SelectLocationGroup.allCases` to array, right?
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 120 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDHqpB1c0MPyiSgcD1:-NqDHqpB1c0MPyiSgcD2:beab65k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L120)):*
> ```Swift
>     }
> 
>     private func item(for indexPath: IndexPath) -> LocationCellViewModel? {
> ```

Nit: Do we need this abstraction?
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 125 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDI4V_3oxbCnQO6csw:-NqDI4V_3oxbCnQO6csx:b-9g7nry) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L125)):*
> ```Swift
> 
>     private func setSelectedRelayLocation(
>         _ relayLocation: LocationCellViewModel?,
> ```

Nit: This is technically a data source item and should perhaps be called `item` instead of `relayLocation`.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 134 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDIX4U71o0m8MdVpMs:-NqDIX4V7KJR_bc2FnB-:brmm5d7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L134)):*
> ```Swift
>                 let group = item.group
>                 var locationList = snapshot().itemIdentifiers(inSection: group)
>                 guard !locationList.contains(item) else {
> ```

I don't think this will ever be evaluated to `true`. If there is an `item`, that item has a `group`, shouldn't the group by default contain the item in the list of items in that group?
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 156 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDJwWf9T8R02T4N1kt:-NqDJwWg0ezzvQl2-Obc:b-t3g8rz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L156)):*
> ```Swift
>                     at: indexPath.row + 1
>                 )
>                 var list: [[LocationCellViewModel]] = Array(repeating: [], count: datasources.count)
> ```

It should be enough to simply pass `locationList` to ùpdateDataSnapshot` below since it contains all we need. If there is no selection we already stop execution and skip snapshot update at:



_Code snippet:_
```Swift
guard let indexPath = indexPath(for: topLocation), let topNode = node(for: topLocation) else {
    return
}
```
___
*[`ios/MullvadVPN/View controllers/SelectLocation/SelectLocationGroup.swift` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDNth9-PKmHlen9xSE:-NqDNth9-PKmHlen9xSF:bnipifr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/SelectLocationGroup.swift#L10)):*
> ```Swift
> 
> import Foundation
> enum SelectLocationGroup: Hashable, CustomStringConvertible, CaseIterable {
> ```

Nit: I'd rather call this `SelectLocationSection` since that's what it's used for. Makes it clearer when reading the code in `SelectLocationDataSource`.


<!-- Sent from Reviewable.io -->

2024-02-09 15:55 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778)* status: 5 of 11 files reviewed, 13 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 208 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDXgB3DoUur1jroPzR:-NqDXgB3DoUur1jroPzS:bulh3ir) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L208)):*
> ```Swift
> 
> extension LocationDataSource: LocationCellEventHandler {
>     func collapseCell(for item: LocationCellViewModel) {
> ```

Nit: We're both expanding and collapsing cells here. Should probably be called `toggleCells` or the like.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDV78P-sbEEd1OQ5lO:-NqDV78P-sbEEd1OQ5lP:b-5wi3jk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L215)):*
> ```Swift
>             let group = SelectLocationGroup.allCases[indexPath.section]
>             node.showsChildren = !isExpanded
>             locationCellFactory.configureCell(
> ```

Is this to reload the cell (ie, update the chevron)? In that case I think `snapshot().reconfigureOrReloadItems` is better suited.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 228 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDXL5y45eYfTLvi2SE:-NqDXL5y45eYfTLvi2SF:b-4x01rk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L228)):*
> ```Swift
>                 locationList.removeLocations(locationsToEdit)
>             }
>             var list: [[LocationCellViewModel]] = Array(repeating: [], count: datasources.count)
> ```

It should be enough to simply pass `locationList` to updateDataSnapshot()` below since we return early if no expandable cell is found.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 276 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDZtUfAb81ckcx5amI:-NqDZtUfAb81ckcx5amJ:b-ejlv76) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L276)):*
> ```Swift
>     private func scrollToSelectedRelay() {
>         indexPathForSelectedRelay().flatMap {
>             tableView.scrollToRow(at: $0, at: .middle, animated: false)
> ```

Can't we use the `scroll(to location)` function above?


<!-- Sent from Reviewable.io -->

2024-02-09 15:59 UTC, rablador reviewed
> Reviewed 6 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778)* status: all files reviewed, 13 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-02-09 16:42 UTC, buggmagnet requested changes
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778)* status: all files reviewed, 21 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDVvIjD-fJgSe_A9yn:-NqDVvIjD-fJgSe_A9yo:b-q24h4o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L18)):*
> ```Swift
> 
>     func search(by text: String) -> [RelayLocation] {
>         if text.isEmpty {
> ```

We can avoid a level of nesting by switching this condition around 
```swift
guard text.isEmpty == false else {
    return locationList
}
```
___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDULgL2M5PBnp9GYeg:-NqDULgL2M5PBnp9GYeh:bkmrotf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L37)):*
> ```Swift
> 
>                     if cityNode.displayName.fuzzyMatch(text) || relaysContainSearchString {
>                         if !filteredLocations.contains(where: { $0 == countryNode.location }) {
> ```

nit
we can do `filteredLocations.contains(countryNode.location)` here
___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDV9GW50p1z5W3yPKI:-NqDV9GW50p1z5W3yPKJ:b-e6vj1r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L45)):*
> ```Swift
> 
>                         if relaysContainSearchString {
>                             cityNode.children.map { $0.location }.forEach {
> ```

This used to be `filteredLocations.append(contentsOf: cityNode.children.map { $0.location })` 
I think we shouldn't change it for the sake of changing it, let's revert it to what it was before 
___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDXkpV45I0O9FNPEBG:-NqDXkpV45I0O9FNPEBH:b-xproba) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L58)):*
> ```Swift
>     }
> 
>     func reload(
> ```

You don't need to prepend the package name here, this should work
```swift
    func reload(
        _ response: REST.ServerRelaysResponse,
        relays: [REST.ServerRelay]
    ) -> [RelayLocation] {
```
___
*[`ios/MullvadVPN/View controllers/SelectLocation/CustomListsDataSource.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDbVEzDM3KsgBJHizQ:-NqDbVEzDM3KsgBJHizR:b-27g6th) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/CustomListsDataSource.swift#L18)):*
> ```Swift
> 
>     func search(by text: String) -> [RelayLocation] {
>         return []
> ```

No need for the `return` statement here
___
*[`ios/MullvadVPN/View controllers/SelectLocation/CustomListsDataSource.swift` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDbKW20WBzUdatyMAp:-NqDbKW20WBzUdatyMAq:b-vx7uwn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/CustomListsDataSource.swift#L24)):*
> ```Swift
>         _ response: MullvadREST.REST.ServerRelaysResponse,
>         relays: [MullvadREST.REST.ServerRelay]
>     ) -> [RelayLocation] {
> ```

We don't need to specify the package
```swift
    func reload(
        _ response: REST.ServerRelaysResponse,
        relays: [REST.ServerRelay]
    ) -> [RelayLocation] {
        locationList
    }
```
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDd1ex1sBQu_DqOwDA:-NqDd1ex1sBQu_DqOwDB:b-p4danb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L66)):*
> ```Swift
>     func indexPathForSelectedRelay() -> IndexPath? {
>         selectedRelayLocation.flatMap {
>             return indexPath(for: $0)
> ```

No need for `return` here
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDiEiE182qSzGs0eaj:-NqDiEiE182qSzGs0eak:b-x2i4ue) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L81)):*
> ```Swift
>         }
>         updateDataSnapshot(with: list, reloadExisting: !searchString.isEmpty)
>         if searchString.isEmpty {
> ```

We can remove most uses of `self` here
```swift
if searchString.isEmpty {
    setSelectedRelayLocation(selectedRelayLocation, animated: false, completion: {
        self.scrollToSelectedRelay()
    })
} else {
    scrollToTop(animated: false)
}
```


<!-- Sent from Reviewable.io -->

2024-02-15 11:52 UTC, rablador reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778)* status: all files reviewed, 21 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-02-19 12:51 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDVvIjD-fJgSe_A9yn:-Nr072Zh6CnBfMC-3uC6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L18)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We can avoid a level of nesting by switching this condition around 
```swift
guard text.isEmpty == false else {
    return locationList
}
```
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqCuecH0GWtqYnZUZWK:-Nr073gKD3T_jU_a6Ls2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L26)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

We already check for empty text at the start of the function, so that shouldn't be needed here.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDULgL2M5PBnp9GYeg:-Nr07CNN8HQR1Bad1P60:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L37)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
we can do `filteredLocations.contains(countryNode.location)` here
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDV9GW50p1z5W3yPKI:-Nr0AVf53IhlAOrsy3gi:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L45)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This used to be `filteredLocations.append(contentsOf: cityNode.children.map { $0.location })` 
I think we shouldn't change it for the sake of changing it, let's revert it to what it was before
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 58 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDXkpV45I0O9FNPEBG:-Nr0AcISCeHVAy9OZRLX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L58)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

You don't need to prepend the package name here, this should work
```swift
    func reload(
        _ response: REST.ServerRelaysResponse,
        relays: [REST.ServerRelay]
    ) -> [RelayLocation] {
```
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/CustomListsDataSource.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDbVEzDM3KsgBJHizQ:-Nr0AhO8CfDoFeSCHVNM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/CustomListsDataSource.swift#L18)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

No need for the `return` statement here
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/CustomListsDataSource.swift` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDbKW20WBzUdatyMAp:-Nr0AjQZ4k6lE5rp8t1q:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/CustomListsDataSource.swift#L24)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We don't need to specify the package
```swift
    func reload(
        _ response: REST.ServerRelaysResponse,
        relays: [REST.ServerRelay]
    ) -> [RelayLocation] {
        locationList
    }
```
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDE-f09CWFx8DgYzI4:-Nr0AokuBjtZteUTWCX3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L18)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: dataSources
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDd1ex1sBQu_DqOwDA:-Nr0BLpv80G1KiOB8pkq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L66)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

No need for `return` here
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 81 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDiEiE182qSzGs0eaj:-Nr0BTUQ-jSNqBLkFTb7:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L81)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We can remove most uses of `self` here
```swift
if searchString.isEmpty {
    setSelectedRelayLocation(selectedRelayLocation, animated: false, completion: {
        self.scrollToSelectedRelay()
    })
} else {
    scrollToTop(animated: false)
}
```
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 99 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDHCAY8fbChxFViCzU:-Nr0B_0yCYrFdik2c4YA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L99)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: No need to cast `SelectLocationGroup.allCases` to array, right?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 120 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDHqpB1c0MPyiSgcD1:-Nr0Bp107XHGhEcp-Ryx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L120)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Do we need this abstraction?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 208 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-NqDXgB3DoUur1jroPzR:-Nr0IY1DCl56zc7gWwZG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a6727eea78c93e31f31897446bb9fe0e571c333f/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L208)):*
<details><summary><i>Previously, rablador (Jon Petersson) wr [...]

2024-02-19 12:53 UTC, rablador reviewed
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-02-19 13:07 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-02-19 13:59 UTC, acb-mv requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778)* status: all files reviewed, 12 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 23 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-Nr0aqzaB16v0Dwd-IvM:-Nr0aqzaB16v0Dwd-IvN:b-304xum) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/812a9e4f36b8e199fff2ac25f25121984064db4b/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L23)):*
> ```Swift
> 
>         var filteredLocations: [RelayLocation] = []
>         locationList.forEach { location in
> ```

I'm wondering if this could not be done as a `let filteredLocations = locationList.filter { ... }`. 
___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 69 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-Nr0bcUmCMHJddYyLos9:-Nr0bcUmCMHJddYyLosA:b-hmngdg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/812a9e4f36b8e199fff2ac25f25121984064db4b/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L69)):*
> ```Swift
>             let relayLocation = RelayLocation.hostname(countryCode, cityCode, relay.hostname)
> 
>             for ascendantOrSelf in relayLocation.ascendants + [relayLocation] {
> ```

This may be beyond the scope of this ticket, but `ascendants` is not a standard opposite of `descendants`; that would be `ancestors`.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 74 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-Nr0c3NADim2x0TlWJtM:-Nr0c3NADim2x0TlWJtN:b7fa6vv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/812a9e4f36b8e199fff2ac25f25121984064db4b/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L74)):*
> ```Swift
> 
>         var list: [[LocationCellViewModel]] = []
>         for section in 0 ..< SelectLocationSection.allCases.count {
> ```

or this could be something like 
```swift
let list = SelectLocationSection.allCases.enumerated.map { (section, group) in
  dataSources[section]
    .search(by: searchString)
    .map { LocationCellViewModel(group: group, location: $0) }
}
```
Avoiding a mutable variable and some imperative code.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 129 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-Nr0d4Uf7FK0hfNqqQ2W:-Nr0d4Uf7FK0hfNqqQ2X:b-biad6e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/812a9e4f36b8e199fff2ac25f25121984064db4b/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L129)):*
> ```Swift
>     ) {
>         selectedRelayLocation = relayLocation
>         selectedRelayLocation
> ```

`flatMap`is a function that is used for returning a value. Using it purely for a side-effect is a bit unclear (much like using `map` in place of `for _ in _`), and seems like a code smell to me.

Given that the body of the method is inside the fruitless `flatMap`, I'd be more inclined to replace the opening line with a 
`guard let item = selectedRelayLocation else { return }`
or similar.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 195 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-Nr0eK4J7e7dATy1aBk0:-Nr0eK4J7e7dATy1aBk1:b-uwmf2c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/812a9e4f36b8e199fff2ac25f25121984064db4b/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L195)):*
> ```Swift
>     func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
>         itemIdentifier(for: indexPath)
>             .flatMap { item in
> ```

Another `flatMap`used where a `guard let` would be more suitable.


<!-- Sent from Reviewable.io -->

2024-02-19 14:31 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
Besides the suggestions left by @acb-mv  that should be addressed, this looks good !

> Reviewed 6 of 7 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-:-Nr0lpeN32eLE4sgGVHz:bsafdnm)* status: all files reviewed, 5 unresolved discussions (waiting on @acb-mv and @mojganii)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 129 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-Nr0d4Uf7FK0hfNqqQ2W:-Nr0jRcQ1ecZpmCM40hg:b-ozrm7n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/812a9e4f36b8e199fff2ac25f25121984064db4b/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L129)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

`flatMap`is a function that is used for returning a value. Using it purely for a side-effect is a bit unclear (much like using `map` in place of `for _ in _`), and seems like a code smell to me.

Given that the body of the method is inside the fruitless `flatMap`, I'd be more inclined to replace the opening line with a 
`guard let item = selectedRelayLocation else { return }`
or similar.
</blockquote></details>

Wholeheartedly agree !


<!-- Sent from Reviewable.io -->

2024-02-19 15:23 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778)* status: all files reviewed, 5 unresolved discussions (waiting on @acb-mv and @mojganii)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 23 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-Nr0aqzaB16v0Dwd-IvM:-Nr0tjj20xbPAeALdYtp:b-1vg687) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/812a9e4f36b8e199fff2ac25f25121984064db4b/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L23)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

I'm wondering if this could not be done as a `let filteredLocations = locationList.filter { ... }`.
</blockquote></details>

We're building a tree-like structure of nodes, so we cannot filter out one location at a time. Each country can have a number of cities, which in turn can have a number or servers.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 69 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-Nr0bcUmCMHJddYyLos9:-Nr0upeeBNpM8g9kPaPY:bcsawr5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/812a9e4f36b8e199fff2ac25f25121984064db4b/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L69)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

This may be beyond the scope of this ticket, but `ascendants` is not a standard opposite of `descendants`; that would be `ancestors`.
</blockquote></details>

Let's change it.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 74 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-Nr0c3NADim2x0TlWJtM:-Nr0vUal6hUHb5K6YOVr:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/812a9e4f36b8e199fff2ac25f25121984064db4b/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L74)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

or this could be something like 
```swift
let list = SelectLocationSection.allCases.enumerated.map { (section, group) in
  dataSources[section]
    .search(by: searchString)
    .map { LocationCellViewModel(group: group, location: $0) }
}
```
Avoiding a mutable variable and some imperative code.
</blockquote></details>

Done
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 129 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-Nr0d4Uf7FK0hfNqqQ2W:-Nr0v_Is0Q_mtsS_YxrP:bhlf3ka) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/812a9e4f36b8e199fff2ac25f25121984064db4b/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L129)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Wholeheartedly agree !
</blockquote></details>

The original author of much of the code base was fond of it, so it has sort of been sticking with us since then. I think it's nifty, but I don't mind changing it. The PR is littered with `flatMap` though, so there will be many changes to make it consistent.


<!-- Sent from Reviewable.io -->

2024-02-19 15:38 UTC, rablador reviewed
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778)* status: all files reviewed, 5 unresolved discussions (waiting on @acb-mv and @mojganii)



<!-- Sent from Reviewable.io -->

2024-02-19 15:41 UTC, acb-mv approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 23 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-Nr0aqzaB16v0Dwd-IvM:-Nr10HGN7dzy0lZ_f8mp:b-24kv6k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/812a9e4f36b8e199fff2ac25f25121984064db4b/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L23)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

We're building a tree-like structure of nodes, so we cannot filter out one location at a time. Each country can have a number of cities, which in turn can have a number or servers.
</blockquote></details>

That could be a use case for a `flatMap` on lists (i.e., one that for each list member produces a list of 0 or more items).
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 129 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-Nr0d4Uf7FK0hfNqqQ2W:-Nr10Xsh8JzKyb1X7jua:b-uqst6a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/812a9e4f36b8e199fff2ac25f25121984064db4b/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L129)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

The original author of much of the code base was fond of it, so it has sort of been sticking with us since then. I think it's nifty, but I don't mind changing it. The PR is littered with `flatMap` though, so there will be many changes to make it consistent.
</blockquote></details>

Ah yes. 
`flatMap` is nifty, though I'd use it only as a functional expression, returning a value and (usually) having no side-effects.
Anyway, we can tidy things up as we get to them.


<!-- Sent from Reviewable.io -->

2024-02-20 09:29 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778)* status: all files reviewed, 3 unresolved discussions (waiting on @acb-mv)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift` line 23 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-Nr0aqzaB16v0Dwd-IvM:-Nr4oNi1Auns252-fEfq:b-k9rq4j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/812a9e4f36b8e199fff2ac25f25121984064db4b/ios/MullvadVPN/View%20controllers/SelectLocation/AllLocationDataSource.swift#L23)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

That could be a use case for a `flatMap` on lists (i.e., one that for each list member produces a list of 0 or more items).
</blockquote></details>

Yes, but my bad, it's not really a tree, but more like a specific order, eg.: `[country, city, city, server, server]`. Each loop has to take into consideration wether there are matching children and whether those children have or have not already included their parents in the resulting array. Pretty convoluted. I'll leave it as-is for now, but I'd be more than happy to have it simplified sometime.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 129 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-Nr0d4Uf7FK0hfNqqQ2W:-Nr4dfx79ad4CpPM6fy7:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/812a9e4f36b8e199fff2ac25f25121984064db4b/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L129)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Ah yes. 
`flatMap` is nifty, though I'd use it only as a functional expression, returning a value and (usually) having no side-effects.
Anyway, we can tidy things up as we get to them.
</blockquote></details>

Fixed
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 195 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778#-Nr0eK4J7e7dATy1aBk0:-Nr4dkcGDInqq0K5fwmI:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/812a9e4f36b8e199fff2ac25f25121984064db4b/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L195)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Another `flatMap`used where a `guard let` would be more suitable.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-02-20 10:08 UTC, rablador reviewed
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778)* status: all files reviewed, 3 unresolved discussions (waiting on @acb-mv)



<!-- Sent from Reviewable.io -->

2024-02-20 10:27 UTC, buggmagnet approved these changes
> Reviewed 2 of 4 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5778)* status: all files reviewed, 3 unresolved discussions (waiting on @acb-mv)



<!-- Sent from Reviewable.io -->

2024-02-21 08:34 UTC, merged