Adjust relay selector to support custom lists
mullvad/mullvadvpn-app pull request #5788
Opened 2024-02-07 23:44 UTC by rablador

When a custom list enabled, the relay selector should match relays by location using the custom list - if a relay matches any of the location constraints in a custom list, it should be added to the list of eligible relays to be picked by the roulette selection.

2024-02-09 08:55 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadTypes/RelayConstraints.swift` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788#-NqC3GXxE_jNdhHa58tW:-NqC3GXyCT90QXRXuJpe:undefined) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5aac813175308893f3e9ae06b7949e0d441ab62f/ios/MullvadTypes/RelayConstraints.swift#L31)):*
> ```Swift
>         self.customListId = customListId
>     }
> }
> ```





_Code snippet:_
```Swift
public struct RelayLocationList: Codable, Equatable {
    public let id: UUID?
    public let locations: [RelayLocation]
    
    public init(customListId: UUID? = nil ,locations: [RelayLocation]) {
        self.locations = locations
        self.id = customListId
    }
}
```
___
*[`ios/MullvadTypes/RelayConstraints.swift` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788#-NqC3v6zBpnYEvA0z0II:-NqC3v6zBpnYEvA0z0IJ:b-ngiu2j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5aac813175308893f3e9ae06b7949e0d441ab62f/ios/MullvadTypes/RelayConstraints.swift#L46)):*
> ```Swift
>     public init(
>         locations: RelayConstraint<RelayLocationPersistent> =
>             .only(RelayLocationPersistent(locations: [.country("se")], customListId: nil)),
> ```

removing nit from constructor


<!-- Sent from Reviewable.io -->

2024-02-09 14:34 UTC, buggmagnet reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2024-02-12 09:03 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadTypes/RelayConstraints.swift` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788#-NqC3GXxE_jNdhHa58tW:-NqRYTg9BfGx8ylhlVgu:b-m802my) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5aac813175308893f3e9ae06b7949e0d441ab62f/ios/MullvadTypes/RelayConstraints.swift#L31)):*
> ```Swift
>         self.customListId = customListId
>     }
> }
> ```

I renamed it `RelayLocations` and added the default param.
___
*[`ios/MullvadTypes/RelayConstraints.swift` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788#-NqC3v6zBpnYEvA0z0II:-NqRYa8J-JAe97zPIaLq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5aac813175308893f3e9ae06b7949e0d441ab62f/ios/MullvadTypes/RelayConstraints.swift#L46)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

removing nit from constructor
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-12 10:34 UTC, buggmagnet reviewed
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-02-13 07:37 UTC, buggmagnet requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788)* status: all files reviewed, 4 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 3305 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788#-NqWOAUG8oIciXsXCeTb:-NqWOAUG8oIciXsXCeTc:b417lkx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c2ebb912ae46b586a39a4407cfecc59cd45b6b2b/ios/MullvadVPN.xcodeproj/project.pbxproj#L3305)):*
> ```
> 			sourceTree = "<group>";
> 		};
> 		7A038FDD2B7A56CF00950251 /* Recovered References */ = {
> ```

This looks like it shouldn't be here, can you make sure to delete this folder ?
___
*[`ios/MullvadVPNTests/StartTunnelOperationTests.swift` line 92 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788#-NqWOW1S8fbhNzn5GgrH:-NqWOW1S8fbhNzn5GgrI:bcp0yn2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/88fcf983529fce74023575cdfb4c70c28f4130d7/ios/MullvadVPNTests/StartTunnelOperationTests.swift#L92)):*
> ```Swift
>             dispatchQueue: testQueue,
>             interactor: interactor
>         ) { result in
> ```

Those are already fixed on main 


<!-- Sent from Reviewable.io -->

2024-02-13 08:07 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 3305 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788#-NqWOAUG8oIciXsXCeTb:-NqWSAp8A9tn42Icv21g:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c2ebb912ae46b586a39a4407cfecc59cd45b6b2b/ios/MullvadVPN.xcodeproj/project.pbxproj#L3305)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This looks like it shouldn't be here, can you make sure to delete this folder ?
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/StartTunnelOperationTests.swift` line 92 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788#-NqWOW1S8fbhNzn5GgrH:-NqWSASJ74QtitfrgbG-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/88fcf983529fce74023575cdfb4c70c28f4130d7/ios/MullvadVPNTests/StartTunnelOperationTests.swift#L92)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Those are already fixed on main
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-19 14:20 UTC, acb-mv reviewed
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2024-02-20 09:24 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788#-:-Nr4p4Yj49MBOeFeAy5Y:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-02-23 11:17 UTC, acb-mv approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-02-26 08:14 UTC, buggmagnet approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-02-26 08:26 UTC, merged