Android GL maps
mullvad/mullvadvpn-app pull request #5797
Opened 2024-02-09 11:49 UTC by Rawa

This PR introduces a map view that renders maps in OpenGL

2024-02-09 12:34 UTC, Pururun requested changes
> Reviewed 39 of 39 files at r1, 4 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: 29 of 43 files reviewed, 20 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 196 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqClVYBAUb9DD2MzDeL:-NqClVYBAUb9DD2MzDeM:b5anpdi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L196)):*
> ```Kotlin
>         timeLeft = uiState.daysLeftUntilExpiry
>     ) {
>         var bias by remember { mutableFloatStateOf(0.5f) }
> ```

Magical number
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 200 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqClatv3ftSuOl7khvI:-NqClatv3ftSuOl7khvJ:b-g9v9w7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L200)):*
> ```Kotlin
>             modifier = Modifier.padding(top = it.calculateTopPadding()),
>             uiState.animateMap,
>             uiState.location?.toLatLng() ?: gothenburgLatLng,
> ```

Would it not be better to call it something like fallbackLatLng instead of gothenburgLatLng?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 201 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqClpaF5QS-iXjxLsC_:-NqClpaF5QS-iXjxLsCa:bdwceod) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L201)):*
> ```Kotlin
>             uiState.animateMap,
>             uiState.location?.toLatLng() ?: gothenburgLatLng,
>             marker = uiState.tunnelRealState.toMarker(uiState.location),
> ```

Maybe we should use named parameters everywhere here to make it clearer what the different locations are used for?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 208 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCm2QY5nUrUvVyX05_:-NqCm2QY5nUrUvVyX05a:b-u7va4j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L208)):*
> ```Kotlin
>         ) {
>             val (divider) = createRefs()
>             Divider(
> ```

I guess this is is one kind of debug line to use for testing? If we want to keep it maybe we should hide it behind a flag?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 239 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCmB0P5XEW5kGgMUdR:-NqCmB0P5XEW5kGgMUdS:b-jxqcg5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L239)):*
> ```Kotlin
>                 onClickDismissNewDevice = onDismissNewDeviceClick,
>             )
>             Slider(
> ```

See comment above about debug ui features.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 249 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCmKgLBcUeWm_MJvw9:-NqCmKgLBcUeWm_MJvwA:b-hyoy0j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L249)):*
> ```Kotlin
>             if (
>                 uiState.tunnelRealState is TunnelState.Connecting ||
>                     uiState.tunnelRealState is TunnelState.Disconnecting
> ```

Why was this removed?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 347 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCmRX_56adfwjMUYpI:-NqCmRX_56adfwjMUYpJ:b87njmn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L347)):*
> ```Kotlin
> fun GeoIpLocation.toLatLng() = LatLng(Latitude(latitude.toFloat()), Longitude(longitude.toFloat()))
> 
> val gothenburgLatLng = LatLng(Latitude(57.7065f), Longitude(11.967f))
> ```

This should probably be a constant somewhere, and be call fallback or default position.
___
*[`android/lib/map/build.gradle.kts` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCmjMu36QuSeeKMpte:-NqCmjMu36QuSeeKMptf:b-qds92m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/build.gradle.kts#L12)):*
> ```Kotlin
>     defaultConfig {
>         minSdk = Versions.Android.minSdkVersion
>         testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
> ```

Maybe nitpick, but I guess we don't need a runner if we don't have any tests?
___
*[`android/lib/map/src/androidTest/java/net/mullvad/mullvadvpn/lib/map/ExampleInstrumentedTest.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCmuUN5ETWKVAfY271:-NqCmuUN5ETWKVAfY272:boovlh4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/androidTest/java/net/mullvad/mullvadvpn/lib/map/ExampleInstrumentedTest.kt#L17)):*
> ```Kotlin
>  */
> @RunWith(AndroidJUnit4::class)
> class ExampleInstrumentedTest {
> ```

Should probably be removed
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt` line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCn4yX6T00Xq9hD9PN:-NqCn4yX6T00Xq9hD9PO:bhqe2ul) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt#L40)):*
> ```Kotlin
>             )
>         }
>     Log.d("MullvadMap", "CameraLocation: ${mapViewState.cameraLatLng}")
> ```

Would this be considered a log that could potentially leak data?
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCnEjN1Hul0A_cj2nB:-NqCnEjN1Hul0A_cj2nC:b-g8cwr0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt#L45)):*
> ```Kotlin
> 
> @Composable
> fun animatedMapViewState(
> ```

Since this is a composable, should it start with a capital letter? Not sure about the rules exactly here.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCnpYo6rWELDop3QN6:-NqCnpYo6rWELDop3QN7:b99ryny) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt#L49)):*
> ```Kotlin
>     marker: Marker?,
>     percent: Float,
> ): MapViewState {
> ```

This whole function is good :)
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt` line 99 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCni1p65JEN3NHuVZN:-NqCni1p65JEN3NHuVZO:bm46qrh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt#L99)):*
> ```Kotlin
>                         } else {
>                             durationMillis = duration
>                             1.25f at duration / 3 using EaseInOut
> ```

Magical numbers
___
*[`androi [...]

2024-02-09 15:47 UTC, albin-mullvad requested changes
> Reviewed 12 of 39 files at r1, 1 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: 29 of 43 files reviewed, 26 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 196 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqDWioE40SdBot1Y8DW:-NqDWioE40SdBot1Y8DX:b-inv5bu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L196)):*
> ```Kotlin
>         timeLeft = uiState.daysLeftUntilExpiry
>     ) {
>         var bias by remember { mutableFloatStateOf(0.5f) }
> ```

Can this variable be clarified a bit?



_Code quote:_
```Kotlin
bias
```
___
*[`android/config/detekt.yml` line 764 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqDWsyM8Fh7Er51aNIL:-NqDWsyM8Fh7Er51aNIM:bxofw4p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/config/detekt.yml#L764)):*
> ```YAML
>     excludeCommentStatements: false
>     excludeRawStrings: true
>     ignoreAnnotated: ['Test']
> ```

Temporary ignore during development?



_Code quote:_
```YAML
ignoreAnnotated: ['Test']
```
___
*[`android/lib/map/src/main/AndroidManifest.xml` line 4 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqDX2y2CIO0W5JHkRyR:-NqDX2y2CIO0W5JHkRyS:bih0a5b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/lib/map/src/main/AndroidManifest.xml#L4)):*
> ```XML
> <manifest xmlns:android="http://schemas.android.com/apk/res/android">
> 
> </manifest>
> ```

Bad file ending. Also, the manifest tag can be single line: `<manifest ... />`
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/GlobeColors.kt` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqDXhGK6ymD3zfmQ4VE:-NqDXhGK6ymD3zfmQ4VF:b-xff0u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/GlobeColors.kt#L13)):*
> ```Kotlin
>     val landColorArray = landColor.toFloatArray()
>     val oceanColorArray = oceanColor.toFloatArray()
>     val contourColorArray = contourColor.toFloatArray()
> ```

Do we need backing fields for these or can they be "plain" getters?



_Code quote:_
```Kotlin
    val landColorArray = landColor.toFloatArray()
    val oceanColorArray = oceanColor.toFloatArray()
    val contourColorArray = contourColor.toFloatArray()
```
___
*[`android/lib/map/src/main/res/raw/vertex_shader.glsl` line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqDWVRB4NyqaqsP_8Q-:-NqDWVRC9fjvjm5g3jlH:b-rd9g5x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/lib/map/src/main/res/raw/vertex_shader.glsl#L9)):*
> ```GLSL
>     gl_Position = uProjectionMatrix * uModelViewMatrix * vec4(aVertexPosition, 1.0);
>     vColor = uColor;
> }
> ```

Bad file ending
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/LatLng.kt` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqDQQio1JLtnIVvIyMT:-NqDQQio1JLtnIVvIyMU:b6asczj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/LatLng.kt#L6)):*
> ```Kotlin
> import kotlin.math.sqrt
> 
> data class LatLng(val latitude: Latitude, val longitude: Longitude) {
> ```

nit: I suggest switching to `LatLong`



_Code quote:_
```Kotlin
LatLng
```


<!-- Sent from Reviewable.io -->

2024-02-12 10:05 UTC, albin-mullvad requested changes
> Reviewed 7 of 39 files at r1, 3 of 18 files at r2, 2 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: 28 of 43 files reviewed, 28 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/lib/map/build.gradle.kts` line 44 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqRkIhY4wjfzl8jxBP_:-NqRkIhY4wjfzl8jxBPa:b-h5imcc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0b61d3ff3ae005e40ecede22dad83384ba1fc58/android/lib/map/build.gradle.kts#L44)):*
> ```Kotlin
> 
>     implementation(Dependencies.AndroidX.lifecycleRuntimeKtx)
> }
> ```

Bad file ending. Maybe we should add an automatic check for that if it's not already checked?
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/ShaderComposable.kt` line 1 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqRl8oq4Q0uhXyb9GuT:-NqRl8orCaJMvh8guoO6:b-nq8pu4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0b61d3ff3ae005e40ecede22dad83384ba1fc58/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/ShaderComposable.kt#L1)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.lib.map.internal
> ```

Can probably be removed?
___
*[`android/lib/map/src/main/res/raw/vertex_shader.glsl` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqRlQFaBHBVa8TD8tj0:-NqRlQFaBHBVa8TD8tj1:b-539h80) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/res/raw/vertex_shader.glsl#L1)):*
> ```GLSL
> attribute vec3 aVertexPosition;
> ```

This is identical or very similar to the desktop shared, right? Can we add a comment with a link to that one perhaps?
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/LatLng.kt` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqDQQio1JLtnIVvIyMT:-NqRlcSt4We6koMlHXoJ:bceaplo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/LatLng.kt#L6)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: I suggest switching to `LatLong`
</blockquote></details>

Thanks for fixing :slightly_smiling_face: 


<!-- Sent from Reviewable.io -->

2024-02-12 10:14 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: 28 of 43 files reviewed, 31 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/config/detekt.yml` line 764 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqDWsyM8Fh7Er51aNIL:-NqRnhZS-_tGqz-rQxfl:b-tat96q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/config/detekt.yml#L764)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Temporary ignore during development?
</blockquote></details>

Seems fixed now
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqRn8dc-dcBKGPw93Fj:-NqRn8dc-dcBKGPw93Fk:bskd46s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0b61d3ff3ae005e40ecede22dad83384ba1fc58/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt#L88)):*
> ```Kotlin
> const val SHORT_ANIMATION_MILLIS = 1700
> const val MIN_ANIMATION_MILLIS = 1300
> const val MAX_ANIMATION_MILLIS = 2500
> ```

Would be nice to not define these constants as part of the `Map` itself, but rather include some type of configuration structure.



_Code quote:_
```Kotlin
const val SECURE_ZOOM = 1.25f
const val UNSECURE_ZOOM = 1.35f
const val DISTANCE_DURATION_SCALE_FACTOR = 20
const val SHORT_ANIMATION_MILLIS = 1700
const val MIN_ANIMATION_MILLIS = 1300
const val MAX_ANIMATION_MILLIS = 2500
```
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/MapConfig.kt` line 8 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqRmspTCX6m38B3dKGN:-NqRmspTCX6m38B3dKGO:b78h3zc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0b61d3ff3ae005e40ecede22dad83384ba1fc58/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/MapConfig.kt#L8)):*
> ```Kotlin
>     val globeColors: GlobeColors =
>         GlobeColors(
>             landColor = Color(0.16f, 0.302f, 0.45f),
> ```

Some magic colors here. I guess these should be defined somewhere?
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/Constants.kt` line 5 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqRmMSHAsfYUdDLqVIG:-NqRmMSHAsfYUdDLqVIH:b6qqyar) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0b61d3ff3ae005e40ecede22dad83384ba1fc58/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/Constants.kt#L5)):*
> ```Kotlin
> internal const val VERTEX_COMPONENT_SIZE = 3
> internal const val COLOR_COMPONENT_SIZE = 4
> ```

nit: what does this empty line represent? It's probably most clear to either skip it or to add comments for each "section"
___
*[`android/lib/map/src/main/res/raw/fragment_shader.glsl` line 1 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqRlx49C8Z4En_u3olD:-NqRlx49C8Z4En_u3olE:b-9olbk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0b61d3ff3ae005e40ecede22dad83384ba1fc58/android/lib/map/src/main/res/raw/fragment_shader.glsl#L1)):*
> ```GLSL
> varying lowp vec4 vColor;
> ```

This is identical or very similar to the desktop shader, right? Can we add a comment with a link to that one perhaps?
___
*[`android/lib/map/src/main/res/raw/vertex_shader.glsl` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqRlQFaBHBVa8TD8tj0:-NqRlz1L3HcjaePy_ULv:b-o1kf5w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/res/raw/vertex_shader.glsl#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

This is identical or very similar to the desktop shared, right? Can we add a comment with a link to that one perhaps?
</blockquote></details>

desktop shader*


<!-- Sent from Reviewable.io -->

2024-02-12 14:52 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: 27 of 46 files reviewed, 31 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 196 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqClVYBAUb9DD2MzDeL:-NqSmbyy2w6hFlA55_gw:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L196)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Magical number
</blockquote></details>

Fixed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 208 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCm2QY5nUrUvVyX05_:-NqSmecs2MLCsCtHpdcQ:b-pttslv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L208)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I guess this is is one kind of debug line to use for testing? If we want to keep it maybe we should hide it behind a flag?
</blockquote></details>

It was used for creating the view, it has been removed now.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 239 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCmB0P5XEW5kGgMUdR:-NqSmjf454FVla7pyXUZ:ba3dfob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L239)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

See comment above about debug ui features.
</blockquote></details>

Removed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 196 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqDWioE40SdBot1Y8DW:-NqSmbjEBVs90Xp4Tygl:b-s3cjwp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L196)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this variable be clarified a bit?
</blockquote></details>

This was very much VIP, but fixed now.
___
*[`android/lib/map/build.gradle.kts` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCmjMu36QuSeeKMpte:-NqSn7_DA0F2OfWArrEH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/build.gradle.kts#L12)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Maybe nitpick, but I guess we don't need a runner if we don't have any tests?
</blockquote></details>

Done.
___
*[`android/lib/map/build.gradle.kts` line 44 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqRkIhY4wjfzl8jxBP_:-NqSn3BKDP95z_0OJuEG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0b61d3ff3ae005e40ecede22dad83384ba1fc58/android/lib/map/build.gradle.kts#L44)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Bad file ending. Maybe we should add an automatic check for that if it's not already checked?
</blockquote></details>

Done.
___
*[`android/lib/map/src/androidTest/java/net/mullvad/mullvadvpn/lib/map/ExampleInstrumentedTest.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCmuUN5ETWKVAfY271:-NqSnCrN6aY7bvOs55o5:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/androidTest/java/net/mullvad/mullvadvpn/lib/map/ExampleInstrumentedTest.kt#L17)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should probably be removed
</blockquote></details>

Done.
___
*[`android/lib/map/src/main/AndroidManifest.xml` line 4 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqDX2y2CIO0W5JHkRyR:-NqSnIqp1rffR1HEF_id:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/lib/map/src/main/AndroidManifest.xml#L4)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Bad file ending. Also, the manifest tag can be single line: `<manifest ... />`
</blockquote></details>

Done.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt` line 40 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCn4yX6T00Xq9hD9PN:-NqSnJxm3_mp2JeDr6F_:bhn9gca) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt#L40)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Would this be considered a log that could potentially leak data?
</blockquote></details>

Used while developing, removed
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt` line 45 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCnEjN1Hul0A_cj2nB:-NqRFzJI2YCDS_F-8EHo:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt#L45)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Since this is a composable, should it start with a capital letter? Not sure about the rules exactly here.
</blockquote></details>

Done.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCnpYo6rWELDop3QN6:-NqRFzwv0znCagV9FVhh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt#L49)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This whole function is good :)
</blockquote></details>

Done.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/GlobeColors.kt` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqDXhGK6ymD3zfmQ4VE:-NqRGBnuEBh8HkPTE5Ky:bxe781s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/GlobeColors.kt#L13)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Do we need backing fields for these or can they be "plain" getters?
</blockquote></details>

I'm not sure how much it would impact performance but since we use land, ocean and contour color every time we draw I felt i was unnecessary to convert it to FloatArray each single Draw.
___
*[`android/lib/map/src/main/res/raw/vertex_shader.glsl` line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqDWVRB4NyqaqsP_8Q-:-NqRGkp5DqqNgQZRxzPe:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/lib/map/src/main/res/raw/vertex_shader.glsl#L9)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Bad file ending
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-13 14:07 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: 17 of 48 files reviewed, 29 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 200 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqClatv3ftSuOl7khvI:-NqXk9oz8u3q68DE3HG4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L200)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Would it not be better to call it something like fallbackLatLng instead of gothenburgLatLng?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 201 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqClpaF5QS-iXjxLsC_:-NqXkBBQEongOMT2Atxr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L201)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Maybe we should use named parameters everywhere here to make it clearer what the different locations are used for?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 249 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCmKgLBcUeWm_MJvw9:-NqXkG8T-mhsRTY1slEI:bn3b8yu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L249)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Why was this removed?
</blockquote></details>

Irrelevant since last push I believe
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 347 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCmRX_56adfwjMUYpI:-NqXkcvbBCuN5VwvOHC0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L347)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This should probably be a constant somewhere, and be call fallback or default position.
</blockquote></details>

Done.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt` line 99 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCni1p65JEN3NHuVZN:-NqXkiT04YRXCmFIx_CK:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt#L99)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Magical numbers
</blockquote></details>

Done.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt` line 108 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCnuxWDhVQa_ZVpdob:-NqXkj210rQvLYdU4MLU:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt#L108)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Magical number
</blockquote></details>

Done.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt` line 112 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCnwpk5eQWKccXP_-n:-NqXkjPx3vAoKKJYnIjo:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt#L112)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Magical number
</blockquote></details>

Done.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqRn8dc-dcBKGPw93Fj:-NqXkqM51s30Y7K6b3Hj:b7de9yz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0b61d3ff3ae005e40ecede22dad83384ba1fc58/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt#L88)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Would be nice to not define these constants as part of the `Map` itself, but rather include some type of configuration structure.
</blockquote></details>

I've fixed some of these remarks. Map module now provides a default camera animation with contains the last 4 properties, the secure/unsecure zoom has now been removed and replaced with baseZoom which the user of the library can provide. If someone want to do other animations we they can always implement their own animation.

Do you still feel we should make the animation part more open/flexible? I'm open for discussion/ideas.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/LocationMarkerColors.kt` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCr12vCuRcJxAllDmL:-NqXm8RE8okM60cEhpzq:b739cj0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/LocationMarkerColors.kt#L8)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Magical numbers
</blockquote></details>

Moved them out to companion object, do we a even have a better idea where to place them?
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/Marker.kt` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCoJE89jviERmNLK1c:-NqXmGe94IErVh1TiTBv:b739cj0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/Marker.kt#L5)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Magic number
</blockquote></details>

Moved them out to companion object, do we a even have a better idea where to place them?
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/Constants.kt` line 5 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqRmMSHAsfYUdDLqVIG:-NqXmI874ooHrPuU4Pb4:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0b61d3ff3ae005e40ecede22dad83384ba1fc58/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/Constants.kt#L5)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: what does this empty line represent? It's probably most clear to either skip it or to add comments for each "section"
</blockquote></details>

Fixed
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt` line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCpIye9YpGmIp89yhR:-NqXmuMK5VvvOJepYuic:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt#L61)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Could vp be replaced by something more verbose?
</blockquote></details>

Done.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLSurfaceView.kt` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCpRKiBG7j0ItTZkT2:-NqXmd007vZ18kwnB-98:b-886gsx) ([raw file](https://gi [...]

2024-02-13 15:30 UTC, albin-mullvad requested changes
Amazing! :star_struck: 

> Reviewed 1 of 10 files at r3, 2 of 7 files at r6, 11 of 24 files at r7, 3 of 6 files at r8, 9 of 13 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-:-NqY2Vk3CASpYddB6vAL:bp3yw8s)* status: 31 of 49 files reviewed, 23 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 270 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqY3M3y51MtRU78bBcL:-NqY3M3y51MtRU78bBcM:bn8gxo7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff338500bd121aeb15371b69012bea6c6476b541/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L270)):*
> ```Kotlin
>                             )
>                                 1f
>                             else 0f
> ```

Not pretty, but I guess I can blame `ktfmt`? :laughing: 



_Code quote:_
```Kotlin
                            if (
                                uiState.tunnelRealState is TunnelState.Connecting ||
                                    uiState.tunnelRealState is TunnelState.Disconnecting
                            )
                                1f
                            else 0f
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 277 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqY4ET404YyqXtDkrmO:-NqY4ET404YyqXtDkrmP:b-cdfwjv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff338500bd121aeb15371b69012bea6c6476b541/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L277)):*
> ```Kotlin
>                             val offsetY = it.positionInParent().y + it.size.height / 2
>                             progressIndicatorBias =
>                                 offsetY / it.parentLayoutCoordinates?.size?.height?.toFloat()!!
> ```

Is there any risk of this floating point being zero?



_Code quote:_
```Kotlin
it.parentLayoutCoordinates?.size?.height?.toFloat()!!
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/AnimationConstant.kt` line 19 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqY2udV02Bk87wI1Cc6:-NqY2udV02Bk87wI1Cc7:b-z2ric7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff338500bd121aeb15371b69012bea6c6476b541/android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/AnimationConstant.kt#L19)):*
> ```Kotlin
> const val UNSECURE_ZOOM = 1.20f
> const val SECURE_ZOOM_ANIMATION_MILLIS = 2000
> val fallbackLatLong = LatLong(Latitude(57.7065f), Longitude(11.967f))
> ```

Gothenburg coordinates? Would perhaps be nice to clarify as a comment or as part of the name in that case?
___
*[`android/lib/map/build.gradle.kts` line 1 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqY0KF09ZAPwJc2lz3w:-NqY0KF09ZAPwJc2lz3x:bvjqe7r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff338500bd121aeb15371b69012bea6c6476b541/android/lib/map/build.gradle.kts#L1)):*
> ```Kotlin
> import com.android.build.gradle.internal.tasks.factory.dependsOn
> ```

Probably no longer needed (?)



_Code quote:_
```Kotlin
dependsOn
```
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqRn8dc-dcBKGPw93Fj:-NqY1nMqBMvGOtS5MQ5i:bu03hd1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f0b61d3ff3ae005e40ecede22dad83384ba1fc58/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/Map.kt#L88)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I've fixed some of these remarks. Map module now provides a default camera animation with contains the last 4 properties, the secure/unsecure zoom has now been removed and replaced with baseZoom which the user of the library can provide. If someone want to do other animations we they can always implement their own animation.

Do you still feel we should make the animation part more open/flexible? I'm open for discussion/ideas.
</blockquote></details>

Nice, sounds good! We don't need to make it more open or flexible at this point imo
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/GlobeColors.kt` line 13 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqDXhGK6ymD3zfmQ4VE:-NqY0cG37dZEnufdR6Bt:bysyaov) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/GlobeColors.kt#L13)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I'm not sure how much it would impact performance but since we use land, ocean and contour color every time we draw I felt i was unnecessary to convert it to FloatArray each single Draw.
</blockquote></details>

Fair enough :thumbsup: 
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/LocationMarkerColors.kt` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCr12vCuRcJxAllDmL:-NqY0l1Z627hhvG3yl6C:bht10at) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/LocationMarkerColors.kt#L8)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Moved them out to companion object, do we a even have a better idea where to place them?
</blockquote></details>

Sounds good! :thumbsup: 
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLSurfaceView.kt` line 15 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqY14Q9Cb8bmpHvDPP0:-NqY14Q9Cb8bmpHvDPP1:b-u09gva) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff338500bd121aeb15371b69012bea6c6476b541/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLSurfaceView.kt#L15)):*
> ```Kotlin
>         setEGLContextClientVersion(2)
> 
>         debugFlags = DEBUG_CHECK_GL_ERROR or DEBUG_LOG_GL_CALLS
> ```

Should any of these perhaps be disabled or used depending on build type?



_Code quote:_
```Kotlin
debugFlags = DEBUG_CHECK_GL_ERROR or DEBUG_LOG_GL_CALLS
```


<!-- Sent from Reviewable.io -->

2024-02-13 17:37 UTC, albin-mullvad reviewed
> Reviewed 1 of 7 files at r6, 1 of 13 files at r9, 1 of 2 files at r10, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: 38 of 49 files reviewed, 23 unresolved discussions (waiting on @Pururun and @Rawa)



<!-- Sent from Reviewable.io -->

2024-02-14 08:00 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: 35 of 49 files reviewed, 20 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 270 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqY3M3y51MtRU78bBcL:-Nqab1tr9pVX-hO111AE:bkn8i9y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff338500bd121aeb15371b69012bea6c6476b541/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L270)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Not pretty, but I guess I can blame `ktfmt`? :laughing:
</blockquote></details>

Yes, ktfmt :( but I've fixed by doing some refactoring
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 277 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqY4ET404YyqXtDkrmO:-Nqab0Fb1BHaZeN6I6cR:bt2vr0y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff338500bd121aeb15371b69012bea6c6476b541/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L277)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is there any risk of this floating point being zero?
</blockquote></details>

Fixed!
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/LocationMarkerColors.kt` line 8 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCr12vCuRcJxAllDmL:-NqabSR862Sy1G8gciZE:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0fb805aafed4ae9c9ddbac34a604ff1924dce466/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/LocationMarkerColors.kt#L8)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Sounds good! :thumbsup:
</blockquote></details>

Done.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLSurfaceView.kt` line 15 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqY14Q9Cb8bmpHvDPP0:-NqabU0jEPdhUj6qQGAf:b-12k221) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff338500bd121aeb15371b69012bea6c6476b541/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLSurfaceView.kt#L15)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should any of these perhaps be disabled or used depending on build type?
</blockquote></details>

True! Good catch!


<!-- Sent from Reviewable.io -->

2024-02-14 08:00 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: 35 of 49 files reviewed, 20 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/AnimationConstant.kt` line 19 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqY2udV02Bk87wI1Cc6:-NqacOwrBzWHu5t2jfRM:b-3rf7ev) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff338500bd121aeb15371b69012bea6c6476b541/android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/AnimationConstant.kt#L19)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Gothenburg coordinates? Would perhaps be nice to clarify as a comment or as part of the name in that case?
</blockquote></details>

Clarified with comment


<!-- Sent from Reviewable.io -->

2024-02-14 08:33 UTC, albin-mullvad reviewed
> Reviewed 1 of 39 files at r1, 1 of 2 files at r10, 1 of 1 files at r11, 3 of 3 files at r13, 5 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: 40 of 49 files reviewed, 21 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 277 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqY4ET404YyqXtDkrmO:-Nqag7Ya7k-JretbUk9i:b-mdhhxf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff338500bd121aeb15371b69012bea6c6476b541/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L277)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Fixed!
</blockquote></details>

The following can still potentially (if `height=0f`) be zero causing a division by zero (float)? Or perhaps I'm missing something. Even though it might be mostly theoretical issue I believe it could be nice to somehow safe-guard :thinking:



_Code snippet:_
```Kotlin
it.size.height.toFloat()
```
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt` line 216 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqahu2J0AmMSh0emWLG:-Nqahu2J0AmMSh0emWLH:b-gop2et) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6de358893e8eca987545a1a7712eedf329af7bd0/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt#L216)):*
> ```Kotlin
>     }
>         """
>                 .trimIndent()
> ```

Just a thought: maybe it would make sense to move the shader code to some separate class/file to avoid cluttering this file? Also would make it possible to share between the markers and globe if the shaders are the identical :thinking: 
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Latitude.kt` line 9 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqajTRcBeOGqlvXcdG7:-NqajTRcBeOGqlvXcdG8:b-qu7jgp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/175e3f34e8f1c78bef8acb1ab0a5df611f0f93fc/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Latitude.kt#L9)):*
> ```Kotlin
>     init {
>         require(value in LATITUDE_RANGE) {
>             "Latitude, $value, must be between $MIN_LATITUDE_VALUE and $MAX_LATITUDE_VALUE $value"
> ```

typo: should the last `$value` be part of this error message? 


<!-- Sent from Reviewable.io -->

2024-02-14 11:46 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: 40 of 49 files reviewed, 21 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 277 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqY4ET404YyqXtDkrmO:-NqbLinQCp2pA3W1R-Tz:b6yc6v5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff338500bd121aeb15371b69012bea6c6476b541/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L277)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The following can still potentially (if `height=0f`) be zero causing a division by zero (float)? Or perhaps I'm missing something. Even though it might be mostly theoretical issue I believe it could be nice to somehow safe-guard :thinking:
</blockquote></details>

Yeah, it would be if the view is for some reason height of 0 pixels. Not sure if this can happen but added an if statement to check it.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt` line 216 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqahu2J0AmMSh0emWLG:-NqbPC1cBQj1kgzsuzoE:bxl2w77) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6de358893e8eca987545a1a7712eedf329af7bd0/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt#L216)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Just a thought: maybe it would make sense to move the shader code to some separate class/file to avoid cluttering this file? Also would make it possible to share between the markers and globe if the shaders are the identical :thinking:
</blockquote></details>

They are indeed identical for the fragmentshader code but the vertexshader are different (very slightly but still different, maybe they could be the same?). It would be a bit weird to separate only the fragmentshader code but not the vertexshader. 

I'm also not sure exactly how they might change over time and they are separated in the desktop app thus I kept them separated. For now I feel they are the closest to the object that uses the shader, if they are the same for multiple objects I think it makes sense to start looking at refactoring it out from the object itself.
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Latitude.kt` line 9 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqajTRcBeOGqlvXcdG7:-NqbOGsf5sKoGjyeJZpn:b4m36va) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/175e3f34e8f1c78bef8acb1ab0a5df611f0f93fc/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Latitude.kt#L9)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

typo: should the last `$value` be part of this error message?
</blockquote></details>

Nice find, I also clarified the error message a little bit.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/RememberPrevious.kt` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCoA2f6tVUCvoiICEq:-NqbL7705JJVgosZTQSo:b20xd8e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/RememberPrevious.kt#L13)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I guess we can put into some kind of compose-ui module?
</blockquote></details>

Managed to remove it completely


<!-- Sent from Reviewable.io -->

2024-02-14 11:50 UTC, albin-mullvad reviewed
> Reviewed 2 of 10 files at r15.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: 36 of 49 files reviewed, 19 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 277 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqY4ET404YyqXtDkrmO:-NqbRia1AO5z9L3ZTC7L:b-bb3892) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ff338500bd121aeb15371b69012bea6c6476b541/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L277)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Yeah, it would be if the view is for some reason height of 0 pixels. Not sure if this can happen but added an if statement to check it.
</blockquote></details>

Nice :thumbsup: 


<!-- Sent from Reviewable.io -->

2024-02-15 09:26 UTC, Pururun requested changes
> Reviewed 1 of 5 files at r4, 1 of 7 files at r6, 1 of 24 files at r7, 1 of 13 files at r9, 1 of 6 files at r14, 7 of 10 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: all files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 245 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg3DuL7qpkXaH5Z7m4:-Nqg3DuL7qpkXaH5Z7m5:b-dk99oc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L245)):*
> ```Kotlin
>                             top = Dimens.mediumPadding
>                         )
>                         .alpha(if (uiState.showLoading) 1f else 0f)
> ```

For clarity we could use `AlphaVisible` and `AlphaInvisible` here
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/Marker.kt` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqCoJE89jviERmNLK1c:-Nqg40a35prQMDNUahIM:b-5uz333) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189c36988e17dea8cd84ead6cf3b5950225b2f3/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/data/Marker.kt#L5)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Moved them out to companion object, do we a even have a better idea where to place them?
</blockquote></details>

I think that is fine


<!-- Sent from Reviewable.io -->

2024-02-15 10:01 UTC, albin-mullvad requested changes
> Reviewed 1 of 24 files at r7, 1 of 13 files at r9, 1 of 6 files at r14, 7 of 10 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: all files reviewed, 15 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/CameraAnimation.kt` line 26 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqgCQe140svfTNC1I38:-NqgCQe2AFpai5eVnUSL:b-js3kfj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/CameraAnimation.kt#L26)):*
> ```Kotlin
> 
> @Composable
> fun animatedCameraPosition(
> ```

Capitalize



_Code quote:_
```Kotlin
animatedCameraPosition
```
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt` line 18 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg6Uq0DlyGoCJlaq3S:-Nqg6Uq0DlyGoCJlaq3T:bxnbny8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt#L18)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.model.COMPLETE_ANGLE
> 
> internal class MapGLRenderer(private val resources: Resources) : GLSurfaceView.Renderer {
> ```

Would be nice to not pass along resources down to the renderer and globe.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt` line 39 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg8OZs-yjmzEW1afz9:-Nqg8OZs-yjmzEW1afzA:b-fjtr4c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt#L39)):*
> ```Kotlin
> 
>     override fun onSurfaceCreated(unused: GL10, config: EGLConfig) {
>         globe = Globe(resources)
> ```

Might be a good idea to introduce some type of factory if we need to instantiate the globe (if we can't inject it)
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt` line 47 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg8KQ_80Rgin5tzThg:-Nqg8KQ_80Rgin5tzThh:bxgefqu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt#L47)):*
> ```Kotlin
>         GLES20.glEnable(GLES20.GL_CULL_FACE)
>         GLES20.glCullFace(GLES20.GL_BACK)
> ```

nit: remove empty line?
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt` line 54 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg8uTI46Unq3e1ahRk:-Nqg8uTI46Unq3e1ahRl:b4i5lgx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt#L54)):*
> ```Kotlin
>     private val projectionMatrix = newIdentityMatrix()
> 
>     override fun onDrawFrame(gl10: GL10) {
> ```

nit: there are many empty lines in this function and it's a bit hard to intepret what they signify. Is it intentional or can it be cleaned up a bit? Maybe adding some comment would be another way of clarifying the code?
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt` line 106 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg7v2ICtjrFt8JPi01:-Nqg7v2ICtjrFt8JPi02:bmeglwm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt#L106)):*
> ```Kotlin
>         GLES20.glViewport(0, 0, width, height)
> 
>         val ratio: Float = width.toFloat() / height.toFloat()
> ```

Potential divide by zero (float)



_Code quote:_
```Kotlin
height.toFloat()
```
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/Globe.kt` line 105 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg9ex-7zRjj3HxjWB2:-Nqg9ex-7zRjj3HxjWB3:b-9xrscs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/Globe.kt#L105)):*
> ```Kotlin
>             LAND_OCEAN_SCALE_FACTOR
>         )
>         drawBufferElements(
> ```

nit: it's a bit inconsistent with empty lines between some of the function calls. I suggest either making it consistent or adding comments if the lines are used as "code sections"
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt` line 34 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqgAO3586FQsww8NdR4:-NqgAO3586FQsww8NdR5:b-pgc7ei) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt#L34)):*
> ```Kotlin
>                 colors.shadowColor,
>                 colors.shadowColor.copy(alpha = 0.0f),
>             ), // shadow
> ```

nit: capitalize



_Code quote:_
```Kotlin
shadow
```
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt` line 41 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqgAKUo4kzXxJqOk1mU:-NqgAKUpEcBGFiCvvIbc:b-pgc7ei) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt#L41)):*
> ```Kotlin
>                 colors.ringBorderColor,
>                 colors.ringBorderColor,
>             ), // white ring
> ```

nit: capitalize



_Code quote:_
```Kotlin
white
```
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt` line 57 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqgAWpCAAnzcg5h9Ig1:-NqgAWpCAAnzcg5h9Ig2:bzc7ztj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt#L57)):*
> ```Kotlin
>     private data class AttribLocations(val vertexPosition: Int, val vertexColor: Int)
> 
>     private data class UniformLocation(val projectionMatrix: Int, val modelViewMatrix: Int)
> ```

Would be nice to move these so that all `val`s are grouped



_Code quote:_
```Kotlin
    private data class AttribLocations(val vertexPosition: Int, val vertexColor: Int)

    private data class UniformLocation(val projectionMatrix: Int, val modelViewMatrix: Int)
```
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt` line 157 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqgAv9A9oYx-aGA7L3C:-NqgAv9BD2OQ4hnzM1Hp:bo0zqtt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt#L157)):*
> ```Kotlin
>         for (i in 1 until points) {
> 
>             val angle = (i.toFloat() / numEdges) * 2f * Math.PI
> ```

Potential divide by zero



_Code quote:_
```Kotlin
numEdges
```
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Latitude.kt` line 36 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqgBNKt8bM8EKiAk6oB:-NqgBNKu2BZKY-eAUPse:b-js3kfj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Latitude.kt#L36)):*
> ``` [...]

2024-02-15 10:12 UTC, albin-mullvad reviewed
> Reviewed 1 of 5 files at r4, 1 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: all files reviewed, 15 unresolved discussions (waiting on @Pururun and @Rawa)



<!-- Sent from Reviewable.io -->

2024-02-15 11:49 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: 44 of 49 files reviewed, 9 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 245 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg3DuL7qpkXaH5Z7m4:-NqgMPENAVnMuP7wVJ7E:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L245)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

For clarity we could use `AlphaVisible` and `AlphaInvisible` here
</blockquote></details>

Fixed
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/CameraAnimation.kt` line 26 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqgCQe140svfTNC1I38:-NqgMINNDJsB8X5bg-yR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/CameraAnimation.kt#L26)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Capitalize
</blockquote></details>

Done.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt` line 47 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg8KQ_80Rgin5tzThg:-NqgMb-q6L12Td-owEcR:be10vrc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt#L47)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: remove empty line?
</blockquote></details>

I grouped them because they are related, first we enable GL_CULL_FACE feature and then configure it, same for GL_BLEND. I've added comments to make it more clear.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt` line 54 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg8uTI46Unq3e1ahRk:-NqgNqGUEEeQ6fN_-pY3:b-mnxs2w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt#L54)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: there are many empty lines in this function and it's a bit hard to intepret what they signify. Is it intentional or can it be cleaned up a bit? Maybe adding some comment would be another way of clarifying the code?
</blockquote></details>

There are some intentions into the grouping of code, I've added comments to clarify
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt` line 106 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg7v2ICtjrFt8JPi01:-NqgVxG0DOalj3g9XXe-:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt#L106)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Potential divide by zero (float)
</blockquote></details>

Fixed
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/Globe.kt` line 105 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg9ex-7zRjj3HxjWB2:-NqgWDj91jtrf6zaNwuX:b-bizqfb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/Globe.kt#L105)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: it's a bit inconsistent with empty lines between some of the function calls. I suggest either making it consistent or adding comments if the lines are used as "code sections"
</blockquote></details>

Added comments
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt` line 57 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqgAWpCAAnzcg5h9Ig1:-Nqg_90c6Y2Q5yMKvsZP:b5p6nn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt#L57)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Would be nice to move these so that all `val`s are grouped
</blockquote></details>

I removed the rings as a class value and reorganized them a bit, is it more clear now?
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt` line 157 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqgAv9A9oYx-aGA7L3C:-NqgWqM--M1yBR9tZlD2:b-bd0l8w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt#L157)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Potential divide by zero
</blockquote></details>

Added a require higher up to make sure numEdges is above 2.
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Latitude.kt` line 51 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqgBd5v924geiD98c9B:-NqgYZpV1cLS-5X-BGaX:blej08x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Latitude.kt#L51)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Maybe a dumb question: can this `else` occur? Aren't all the cases already covered? :thinking:
</blockquote></details>

It should not be able to occur but kotlin does not understand that :disappointed: 


<!-- Sent from Reviewable.io -->

2024-02-15 11:56 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: 44 of 49 files reviewed, 9 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt` line 18 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg6Uq0DlyGoCJlaq3S:-Nqgab9mAVenZ67OxRE6:b-h1a1yw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt#L18)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Would be nice to not pass along resources down to the renderer and globe.
</blockquote></details>

I'd agree that it would be nice, but at the same time it sort of requires the resources to be able to load in it's assets. The alternative it to provide the 5 ByteArray already loaded into memory. Feels like that might be more odd?
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt` line 39 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg8OZs-yjmzEW1afz9:-Nqgaux52HabkD_rUuJF:bro3uuq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt#L39)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Might be a good idea to introduce some type of factory if we need to instantiate the globe (if we can't inject it)
</blockquote></details>

I'm not sure how a factory would help in this case, would it be to avoid passing the resources? Where would we create the factory? And whom would be responsible for it? Lets discuss offline, I'm open for ideas!


<!-- Sent from Reviewable.io -->

2024-02-15 12:22 UTC, Pururun approved these changes
> Reviewed 5 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797)* status: all files reviewed, 7 unresolved discussions (waiting on @albin-mullvad)



<!-- Sent from Reviewable.io -->

2024-02-15 13:29 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-:-Nqgx2y13jyjm1dgybya:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt` line 18 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg6Uq0DlyGoCJlaq3S:-Nqgx6Pl5VOFZB9DVHsW:bycoec2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt#L18)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I'd agree that it would be nice, but at the same time it sort of requires the resources to be able to load in it's assets. The alternative it to provide the 5 ByteArray already loaded into memory. Feels like that might be more odd?
</blockquote></details>

As discussed offline we can let it be as-is for now.
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt` line 39 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-Nqg8OZs-yjmzEW1afz9:-NqgwUbpDCVrke3qLPuL:ba2enq0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt#L39)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I'm not sure how a factory would help in this case, would it be to avoid passing the resources? Where would we create the factory? And whom would be responsible for it? Lets discuss offline, I'm open for ideas!
</blockquote></details>

As discuss, we'll keep it as-is for now
___
*[`android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt` line 57 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqgAWpCAAnzcg5h9Ig1:-NqgwoF73eL2IiebGd_q:bh943eq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/shapes/LocationMarker.kt#L57)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I removed the rings as a class value and reorganized them a bit, is it more clear now?
</blockquote></details>

Yes, looks good!
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Latitude.kt` line 51 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5797#-NqgBd5v924geiD98c9B:-NqgwxwA8Z5iLyB1iqxh:b-va9t2s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/87ed9e3ab2248c84baf867c95a1110c99207c623/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Latitude.kt#L51)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

It should not be able to occur but kotlin does not understand that :disappointed:
</blockquote></details>

Indeed :cry: 


<!-- Sent from Reviewable.io -->

2024-02-15 13:32 UTC, merged