Allow deleting custom lists
mullvad/mullvadvpn-app pull request #5820
Opened 2024-02-15 16:28 UTC by rablador

It should be possible to delete a custom list.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820)

2024-03-01 09:55 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 178 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820#-Nrt5-bv5BJgcLt7WV0U:-NrtR85C-3zKq_Oi7dlS:bvsdmhw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1189e5f3d0617ad4a6f12f28b72cb6907db08ac9/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L178)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Shouldn't those table names be different ? (i.e. custom list table names ?) 

This message is valid for all localised strings in custom lists
</blockquote></details>

Yeah, my bad, I'll change it.


<!-- Sent from Reviewable.io -->

2024-03-04 15:11 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820)* status: 15 of 18 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 161 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820#-Ns8zYOn1xeIG5sghFSw:-Ns8zYOn1xeIG5sghFSx:bqjlbta) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e3af6b9750a44da1b7a4d7883b9f5a7b695899a6/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L161)):*
> ```Swift
> 
>     private func onDelete() {
>         showDeleteAlert()
> ```

FMPOV I don't see any point of making function for `showDeleteAlert`. the body of `showDeleteAlert` can be put in the `onDelete` directly
___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 171 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820#-Ns9-H5s2s-yk2Z1GvTB:-Ns9-H5s2s-yk2Z1GvTC:b5oqg9k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e3af6b9750a44da1b7a4d7883b9f5a7b695899a6/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L171)):*
> ```Swift
>                 "CUSTOM_LISTS_DELETE_PROMPT",
>                 tableName: "CustomLists",
>                 value: "Delete \(subject.value.name)?",
> ```

based on the Figma's design it should be `Delete custom list “the name of custom list”?`

![Frame 6.jpg](https://files.reviewableusercontent.io/images/reviewable/129863230/r_nNYMSAndlg-9ynLIjZvyrw/Frame%206.jpeg)
___
*[`ios/MullvadVPN/Coordinators/CustomLists/EditCustomListCoordinator.swift` line 28 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820#-Ns901Zp0YmKRom0O8Ti:-Ns901Zp0YmKRom0O8Tj:b-cix3ww) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e3af6b9750a44da1b7a4d7883b9f5a7b695899a6/ios/MullvadVPN/Coordinators/CustomLists/EditCustomListCoordinator.swift#L28)):*
> ```Swift
>         navigationController: UINavigationController,
>         customListInteractor: CustomListInteractorProtocol,
>         customList: CustomList
> ```

I think it should be part of `interactor`.


<!-- Sent from Reviewable.io -->

2024-03-04 15:46 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820)* status: 15 of 18 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 161 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820#-Ns8zYOn1xeIG5sghFSw:-Ns92PH92yM9aYGzkON5:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e3af6b9750a44da1b7a4d7883b9f5a7b695899a6/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L161)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

FMPOV I don't see any point of making function for `showDeleteAlert`. the body of `showDeleteAlert` can be put in the `onDelete` directly
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 171 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820#-Ns9-H5s2s-yk2Z1GvTB:-Ns92245BtlbQDMmH3Ga:b-mjrdwc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e3af6b9750a44da1b7a4d7883b9f5a7b695899a6/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L171)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

based on the Figma's design it should be `Delete custom list “the name of custom list”?`

![Frame 6.jpg](https://files.reviewableusercontent.io/images/reviewable/129863230/r_nNYMSAndlg-9ynLIjZvyrw/Frame%206.jpeg)
</blockquote></details>

Yeah, but api access methods has a similar view that only says "Delete <list>". I thought it should be consistent, but perhaps it's better to follow the designs.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/EditCustomListCoordinator.swift` line 28 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820#-Ns901Zp0YmKRom0O8Ti:-Ns94X9d4qZJ8i7TZ-os:bhzbyu0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e3af6b9750a44da1b7a4d7883b9f5a7b695899a6/ios/MullvadVPN/Coordinators/CustomLists/EditCustomListCoordinator.swift#L28)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I think it should be part of `interactor`.
</blockquote></details>

I thought about it, but the custom list supplied to `EditCustomListCoordinator` is specific to that coordinator only and has no relation to `CustomListInteractorProtocol` or views where `CustomListInteractorProtocal` is used.


<!-- Sent from Reviewable.io -->

2024-03-05 12:30 UTC, buggmagnet reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820)* status: 16 of 18 files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 171 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820#-Ns9-H5s2s-yk2Z1GvTB:-NsD_aVuEM4WfM89JMQC:bxouayl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e3af6b9750a44da1b7a4d7883b9f5a7b695899a6/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L171)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Yeah, but api access methods has a similar view that only says "Delete <list>". I thought it should be consistent, but perhaps it's better to follow the designs.
</blockquote></details>


I just talked to the design team about this, they said "we should follow what the desktop does" 
Here included is a screenshot of the desktop.

We can follow the copy at least, if the **bold** title is too complicated to make, we can skip it for now

![Screenshot 2024-03-05 at 13.28.04.png](https://files.reviewableusercontent.io/images/reviewable/129761703/xoU1a3ArO7ThqmM_tQLxh6TH/Screenshot%202024-03-05%20at%2013.28.04.png)


<!-- Sent from Reviewable.io -->

2024-03-05 14:04 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820)* status: 14 of 19 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 171 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820#-Ns9-H5s2s-yk2Z1GvTB:-NsDvXNk6qAHjWjDayE3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e3af6b9750a44da1b7a4d7883b9f5a7b695899a6/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L171)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I just talked to the design team about this, they said "we should follow what the desktop does" 
Here included is a screenshot of the desktop.

We can follow the copy at least, if the **bold** title is too complicated to make, we can skip it for now

![Screenshot 2024-03-05 at 13.28.04.png](https://files.reviewableusercontent.io/images/reviewable/129761703/xoU1a3ArO7ThqmM_tQLxh6TH/Screenshot%202024-03-05%20at%2013.28.04.png)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-06 15:09 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820#-:-NsJJ2ix4Fxyk_e3fXOh:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`ios/MullvadVPN/Coordinators/CustomLists/EditCustomListCoordinator.swift` line 28 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820#-Ns901Zp0YmKRom0O8Ti:-NsJIng892BLs2TUoKXe:ber3lbh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e3af6b9750a44da1b7a4d7883b9f5a7b695899a6/ios/MullvadVPN/Coordinators/CustomLists/EditCustomListCoordinator.swift#L28)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I thought about it, but the custom list supplied to `EditCustomListCoordinator` is specific to that coordinator only and has no relation to `CustomListInteractorProtocol` or views where `CustomListInteractorProtocal` is used.
</blockquote></details>

nit: maybe I need to change the place of the dependency.for now let's leave it


<!-- Sent from Reviewable.io -->

2024-03-07 07:41 UTC, merged