Add split tunneling for macOS
mullvad/mullvadvpn-app pull request #5844
Opened 2024-02-22 09:36 UTC by dlon

See the title. The implementation has some known limitations. It's missing IPv6 support, which will probably be fixed before this is merged.

2024-02-22 11:17 UTC, MrChocolatine commented
Yay, great to see this feature finally being worked on.

2024-03-12 11:50 UTC, MarkusPettersson98 requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 32 of 37 files reviewed, 51 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 77 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmFxlE--2cTgqNgQne:-NsmFxlFCQC2lVgTX4k_:b9kvc7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L77)):*
> ```XML
>         let dup = self.file.try_clone().unwrap();
>         (ReadHalf(dup), WriteHalf(self.file))
>     }
> ```

Return a `Result<(ReadHalf, WriteHalf), Error>` instead of calling `unwrap`



_Code quote:_
```XML
    pub fn split(self) -> (ReadHalf, WriteHalf) {
        let dup = self.file.try_clone().unwrap();
        (ReadHalf(dup), WriteHalf(self.file))
    }
```
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 100 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmHUa3E6wPP-FAmYKe:-NsmHUa3E6wPP-FAmYKf:byt2esq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L100)):*
> ```XML
>                     }
>                     return Err(Error::OpenBpfDevice(error));
>                 }
> ```

Nit: Split up into multiple match-branches

```rust
// Find a free bpf device
for dev_num in 0..MAX_BPF_COUNT {
    // Open as O_RDWR
    match File::options()
        .read(true)
        .write(true)
        .open(format!("/dev/bpf{dev_num}"))
    {
        Err(error) if error.raw_os_error() == Some(EBUSY) => continue,
        Err(error) => return Err(Error::OpenBpfDevice(error)),
        Ok(file) => {
            log::trace!("Opened BPF device: /dev/bpf{dev_num}");
            return Ok(file);
        }
    }
}
```



_Code quote:_
```XML
                Err(error) => {
                    if error.raw_os_error() == Some(EBUSY) {
                        // This BPF device is in use
                        continue;
                    }
                    return Err(Error::OpenBpfDevice(error));
                }
```
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 107 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmI8na-sIluPyE0S1P:-NsmI8na-sIluPyE0S1Q:b-186dbk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L107)):*
> ```XML
> 
>     pub fn set_nonblocking(&self, enabled: bool) -> Result<(), Error> {
>         let mut flags = unsafe { libc::fcntl(self.as_raw_fd(), F_GETFL) };
> ```

Would be nice to add a comment regarding the use of `unsafe`



_Code quote:_
```XML
        let mut flags = unsafe { libc::fcntl(self.as_raw_fd(), F_GETFL) };
```
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 117 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmIKSyEDLapZSPzpvj:-NsmIKSyEDLapZSPzpvk:b-186dbk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L117)):*
> ```XML
>         }
> 
>         let result = unsafe { libc::fcntl(self.as_raw_fd(), F_SETFL, flags) };
> ```

Would be nice to add a comment regarding the use of `unsafe`



_Code quote:_
```XML
        let result = unsafe { libc::fcntl(self.as_raw_fd(), F_SETFL, flags) };
```
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 126 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmJP0a3sZRUUaHQBly:-NsmJP0a3sZRUUaHQBlz:b-186dbk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L126)):*
> ```XML
>     pub fn get_stats(&self) -> Result<Stats, Error> {
>         let mut raw_stats: bpf_stat = unsafe { mem::zeroed() };
>         unsafe { ioctl!(self.file.as_raw_fd(), BIOCGSTATS, &mut raw_stats) }?;
> ```

Would be nice to add a comment regarding the use of `unsafe`



_Code quote:_
```XML
        let mut raw_stats: bpf_stat = unsafe { mem::zeroed() };
        unsafe { ioctl!(self.file.as_raw_fd(), BIOCGSTATS, &mut raw_stats) }?;
```
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 136 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmJRnHCgwWTedgGeBj:-NsmJRnHCgwWTedgGeBk:b-186dbk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L136)):*
> ```XML
>     /// Set BIOCSETIF
>     pub fn set_interface(&self, name: &str) -> Result<(), Error> {
>         let mut ifr: ifreq = unsafe { std::mem::zeroed() };
> ```

Would be nice to add a comment regarding the use of `unsafe`



_Code quote:_
```XML
        let mut ifr: ifreq = unsafe { std::mem::zeroed() };
```
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 150 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmJV1x5bqKBjNSxvZE:-NsmJV1x5bqKBjNSxvZF:b-186dbk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L150)):*
> ```XML
>             );
>             ioctl!(self.file.as_raw_fd(), BIOCSETIF, &ifr)
>         }
> ```

Would be nice to add a comment regarding the use of `unsafe`



_Code quote:_
```XML
        unsafe {
            std::ptr::copy_nonoverlapping(
                name_bytes.as_ptr(),
                &mut ifr.ifr_name as *mut _ as *mut _,
                name_bytes.len(),
            );
            ioctl!(self.file.as_raw_fd(), BIOCSETIF, &ifr)
        }
```
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 156 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmJX5D7NP4sMqooHX1:-NsmJX5D7NP4sMqooHX2:bw2t0y9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L156)):*
> ```XML
>     pub fn set_immediate(&self, enable: bool) -> Result<(), Error> {
>         let enable: c_int = if enable { 1 } else { 0 };
>         unsafe { ioctl!(self.file.as_raw_fd(), BIOCIMMEDIATE, &enable) }
> ```

You get the point



_Code quote:_
```XML
        unsafe { ioctl!(self.file.as_raw_fd(), BIOCIMMEDIATE, &enable) }
```
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 162 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmJZMI9XDovQeJSKyi:-NsmJZMI9XDovQeJSKyj:blk9jjx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L162)):*
> ```XML
>     pub fn set_see_sent(&self, enable: bool) -> Result<(), Error> {
>         let enable: c_int = if enable { 1 } else { 0 };
>         unsafe { ioctl!(self.file.as_raw_fd(), BIOCSSEESENT, &enable) }
> ```

unsafe without safety reasoning



_Code quote:_
```XML
        unsafe { ioctl!(self.file.as_raw_fd(), BIOCSSEESENT, &enable) }
```
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmS9Nu8sklOQxaFhAF:-NsmS9NvDQKDalcJd33x:blk9jjx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L168)):*
> ```XML
>     pub fn set_header_complete(&self, enable: bool) -> Result<(), Error> {
>         let enable: c_int = if enable { 1 } else { 0 };
>         unsafe { ioctl!(self.file.as_raw_fd(), BIOCSHDRCMPLT, &enable) }
> ```

unsafe without safety reasoning



_Code quote:_
```XML
unsafe { ioctl!(self.file.as_raw_fd(), BIOCSHDRCMPLT, &enable) }
```
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 173 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmSCpCD1LZFiF5ARIV:-NsmSCpCD1LZFiF5ARIW:blk9jjx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L173)):*
> ```XML
>     pub fn set_want_p [...]

2024-03-12 13:24 UTC, MarkusPettersson98 requested changes
> Reviewed 1 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 33 of 37 files reviewed, 65 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 48 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nsm_mue5kANs7bcOFqF:-Nsm_mue5kANs7bcOFqG:bdxo3vp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/process.rs#L48)):*
> ```XML
> 
>         let excluded_paths = vec![];
>         states.exclude_paths(excluded_paths);
> ```

Nit inline `excluded_paths`, or skip calling `exclude_paths` entirely if possible :blush:



_Code quote:_
```XML
        let excluded_paths = vec![];
        states.exclude_paths(excluded_paths);
```
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 134 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmfBXY8h-G60FoB5HF:-NsmfBXY8h-G60FoB5HG:b-scrk3v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/process.rs#L134)):*
> ```XML
>     processes: HashMap<u32, ProcessInfo>,
>     exclude_paths: Vec<PathBuf>,
> }
> ```

Is there a particular reason why `exclude_paths` is not a `HashSet`? :blush: 



_Code quote:_
```XML
#[derive(Debug)]
struct InnerProcessStates {
    processes: HashMap<u32, ProcessInfo>,
    exclude_paths: Vec<PathBuf>,
}
```
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 148 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmeYA516tp1AncdbMY:-NsmeYA516tp1AncdbMZ:b-w5xy0w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/process.rs#L148)):*
> ```XML
>         for pid in procs {
>             let path = process_path(pid).map_err(|error| Error::FindProcessPath(error, pid))?;
>             let ppid = process_info(pid)
> ```

`ppid` is a bit of an obscure name for `parent_pid` imho :blush:



_Code quote:_
```XML
 let ppid =
```
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 153 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nsmegw15r6iB4N779qw:-Nsmegw15r6iB4N779qx:b-1leq47) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/process.rs#L153)):*
> ```XML
>                     log::error!("Failed to obtain parent pid for {pid}: {error}");
>                     0
>                 });
> ```

Is it valid to say that the parent PID is 0 if a real parent PID can not be found? I guess that the init process has to be the parent in that case, and if that is the intention here it would be nice with a small comment on what is meant with PID 0 :blush:



_Code quote:_
```XML
                .unwrap_or_else(|error| {
                    log::error!("Failed to obtain parent pid for {pid}: {error}");
                    0
                });
```
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 175 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmfWd_9BoUmww8wgCV:-NsmfWd_9BoUmww8wgCW:b-nq3b1x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/process.rs#L175)):*
> ```XML
>                 .filter(|old_path| paths.contains(old_path))
>                 .cloned()
>                 .collect();
> ```

If `InnerProcessStates.excluded_paths` was modeled as a set, this would be the intersection between `self.excluded_paths` and `paths`, right? :blush:
It would kind of force the `paths` argument to be either `impl IntoIterator<Item = PathBuf>` or a `HashSet<PathBuf>`, but I think it could simplify some of the code in this function a bit :blush:



_Code quote:_
```XML
            // Remove no-longer excluded paths from exclusion list
            let mut new_exclude_paths: Vec<_> = info
                .excluded_by_paths
                .iter()
                .filter(|old_path| paths.contains(old_path))
                .cloned()
                .collect();
```
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 252 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmhHKhEl8IRU72n93X:-NsmhHKhEl8IRU72n93Y:bfcgvvl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/process.rs#L252)):*
> ```XML
>         if info.excluded_by_paths.contains(&info.exec_path) {
>             return;
>         }
> ```

Do we return early here because process corresponding to `pid` is already excluded? Would be nice with a comment :blush:



_Code quote:_
```XML
        if info.excluded_by_paths.contains(&info.exec_path) {
            return;
        }
```
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 273 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nsmi3Js4p3OqgMBpM6S:-Nsmi3Js4p3OqgMBpM6T:b-iv3x3s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/process.rs#L273)):*
> ```XML
> /// Obtain a list of all pids
> fn list_pids() -> io::Result<Vec<u32>> {
>     let num_pids = unsafe { proc_listallpids(ptr::null_mut(), 0) };
> ```

Unsafe with safety argument :(



_Code quote:_
```XML
    let num_pids = unsafe { proc_listallpids(ptr::null_mut(), 0) };
```
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 279 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nsmjt1tAAWwKFW2gj9X:-Nsmjt1tAAWwKFW2gj9Y:b-4oz21b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/process.rs#L279)):*
> ```XML
>     let mut pids = vec![0u32; usize::try_from(num_pids).unwrap()];
> 
>     let buf_sz = (u32::BITS as usize / 8 * (num_pids as usize)) as i32;
> ```

Isn't this the same as `std::mem::size_of::<u32>()`? :blush:

If your are okay with it, I would suggest writing this piece of code as
```rust
let buf_sz = num_pids as usize * std::mem::size_of::<u32>();
let num_pids = unsafe { proc_listallpids(pids.as_mut_ptr() as *mut c_void, buf_sz as i32) };
```



_Code quote:_
```XML
u32::BITS as usize / 8
```
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 280 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmiTbO6_BnQBhWhc5v:-NsmiTbO6_BnQBhWhc5w:b-iv3x3s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/process.rs#L280)):*
> ```XML
> 
>     let buf_sz = (u32::BITS as usize / 8 * (num_pids as usize)) as i32;
>     let num_pids = unsafe { proc_listallpids(pids.as_mut_ptr() as *mut c_void, buf_sz) };
> ```

Unsafe with safety argument :(



_Code quote:_
```XML
    let num_pids = unsafe { proc_listallpids(pids.as_mut_ptr() as *mut c_void, buf_sz) };
```
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 309 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmlE8ADeOEw_KjLZZm:-NsmlE8ADeOEw_KjLZZn:bnorh68) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/process.rs#L309)):*
> ```XML
> 
> fn process_info(pid: u32) -> io::Result<proc_bsdinfo> {
>     let mut info: proc_bsdinfo = unsafe { std::mem::zeroed() };
> ```

Unsafe without safety argument :(



_Code quote:_
```XML
    let mut info: proc_bsdinfo = unsafe { std::mem::zeroed() };
```
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 319 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmlIXU18J_P20BhL6q:-NsmlIXU18J_P20BhL6r:bnorh68) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/process.rs#L319)):*
> ```XML
>             mem::size_of::<proc_bsdin [...]

2024-03-13 07:51 UTC, MarkusPettersson98 commented
[docs/split-tunneling.md](https://github.com/mullvad/mullvadvpn-app/blob/macos-add-split-tunnel/docs/split-tunneling.md) should be updated as well :rocket:

2024-03-21 16:10 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 27 of 38 files reviewed, 65 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`talpid-core/src/split_tunnel/macos/mod.rs` line 95 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NslrFY2E_HutQguZtmR:-NtWlTmi0RZOSV7jcR4y:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/mod.rs#L95)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Instead of returning early here, split this into two match-branches:

```rust
match &mut self.state {
    State::NoExclusions { .. } if paths.is_empty() => Ok(()), // Maybe we should log here? Maybe not
    State::NoExclusions { .. } => {
        log::debug!("Initializing process monitor");
        ..
    }
    ..
}
```
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/mod.rs` line 105 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NslrhWJ4W6HOWxMoi2G:-NtWlYh-2HPKkfJMlu6P:b-cfzrot) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/mod.rs#L105)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This dance with `std::mem::replace` is a bit harder to follow then to re-structure the error handling a bit. It would be nice to avoid the `unreachable!` branch as well. What do you think about the following code?

```rust
match &mut self.state {
    State::NoExclusions { route_manager, vpn_interface } => {
        log::debug!("Initializing process monitor");
        match process::ProcessMonitor::spawn() {
            Err(err) => {
                // It is probably a good idea to log the error here
                *self.state = State::Failed;
            }
            Ok(process) => {
                process.states().exclude_paths(paths);
                self.state = State::HasProcessMonitor {
                    route_manager,
                    process,
                };
                self.set_tunnel(vpn_interface).await
            }
        }
    }
    ..
} 
```
</blockquote></details>

Doesn't work, as discussed. But this should definitely be improved.
___
*[`talpid-core/src/split_tunnel/macos/mod.rs` line 158 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsluMr33v1BiQo2LUCd:-NtWlgfpBCC2vYJ8C3qz:b-q64pkt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/mod.rs#L158)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I'll make the same argument here: I think the use of `std::mem::replace` is needlessly complex, and it would be nice to avoid the use of `unreachable!` in this case :blush:
</blockquote></details>

See above.
___
*[`talpid-core/src/split_tunnel/macos/mod.rs` line 162 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsluilX6-x-0mbdJHnP:-NtWlhsT0vw9uUoWNVf4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/mod.rs#L162)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Split this condition check + early return into a separate branch, see above comment about the similar change suggestion :blush:
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/mod.rs` line 170 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nslv2kJ-qu_E_QdWMZ2:-NtWljnM4Cmt0qd9X-w7:b-q64pkt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/mod.rs#L170)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

See above comment about error handling with `std::mem::replace` :smile:
</blockquote></details>

See above.
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 153 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nsmegw15r6iB4N779qw:-NtREYCk5dOVstXXTcJD:bp9ehtg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/process.rs#L153)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Is it valid to say that the parent PID is 0 if a real parent PID can not be found? I guess that the init process has to be the parent in that case, and if that is the intention here it would be nice with a small comment on what is meant with PID 0 :blush:
</blockquote></details>

That's a good question. Arguably, the grandparent is the real new parent, but I'm not sure what the technically correct answer is.
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 175 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmfWd_9BoUmww8wgCV:-NtRF9oD4GqcfWr6WNrx:b4jzu53) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/process.rs#L175)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

If `InnerProcessStates.excluded_paths` was modeled as a set, this would be the intersection between `self.excluded_paths` and `paths`, right? :blush:
It would kind of force the `paths` argument to be either `impl IntoIterator<Item = PathBuf>` or a `HashSet<PathBuf>`, but I think it could simplify some of the code in this function a bit :blush:
</blockquote></details>

Yep. I'll switch to using sets.
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 279 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nsmjt1tAAWwKFW2gj9X:-NtRGgAfDjcBT2Nk3oyz:b-idcglj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/process.rs#L279)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Isn't this the same as `std::mem::size_of::<u32>()`? :blush:

If your are okay with it, I would suggest writing this piece of code as
```rust
let buf_sz = num_pids as usize * std::mem::size_of::<u32>();
let num_pids = unsafe { proc_listallpids(pids.as_mut_ptr() as *mut c_void, buf_sz as i32) };
```
</blockquote></details>

Yes. That was a bit silly.
___
*[`talpid-core/src/tunnel_state_machine/connected_state.rs` line 156 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nsi5yvPArGn9wp99rVu:-NtRHS9R1iz-vDyTMS2S:b-ucfkn4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/tunnel_state_machine/connected_state.rs#L156)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit: Call `cloned` instead of mapping `to_owned` :blush: 

```rust
let redirect_interface = shared_values.split_tunnel.interface().cloned();
```
</blockquote></details>

Thanks.
___
*[`talpid-core/src/tunnel_state_machine/mod.rs` line 368 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NslbuT2-U_YRmddJuxW:-NtRIGiP3M0Ujk3sc12Y:b-pbdqzg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/tunnel_state_machine/mod.rs#L368)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit: Prefer to specify the type explicitly instead of using `into`:

```rust
.map(TargetType::from)
```
</blockquote></details>

Agreed!
___
*[`talpid-core/src/tunnel_state_machine/mod.rs` line 501 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsiAOq44ApZaAJ_Yb8F:-NtRII7R-bHSiV [...]

2024-03-22 13:31 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 22 of 38 files reviewed, 53 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`talpid-core/src/firewall/macos.rs` line 398 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NslmALN-Jc7VU1_y7En:-Nt_WNLX4gxUKuxwQfxA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/firewall/macos.rs#L398)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Why is `get_tcp_flags` a closure rather than `pfctl::TcpFlags` directly? :blush: 

```rust
fn get_allow_tunnel_rules(
    &self,
    tunnel_interface: &str,
    allowed_traffic: &AllowedTunnelTraffic,
) -> Result<Vec<pfctl::FilterRule>> {
    self.get_allow_tunnel_rules_inner(tunnel_interface, allowed_traffic, Self::get_tcp_flags())
}

fn get_allow_established_tunnel_rules(
    &self,
    tunnel_interface: &str,
    allowed_traffic: &AllowedTunnelTraffic,
) -> Result<Vec<pfctl::FilterRule>> {
    self.get_allow_tunnel_rules_inner(tunnel_interface, allowed_traffic, 
        pfctl::TcpFlags::new(
            &[pfctl::TcpFlag::Syn, pfctl::TcpFlag::Ack],
            &[pfctl::TcpFlag::Syn, pfctl::TcpFlag::Ack],
        )
    )
}

fn get_allow_tunnel_rules_inner(
    &self,
    tunnel_interface: &str,
    allowed_traffic: &AllowedTunnelTraffic,
    get_tcp_flags: pfctl::TcpFlags,
) -> Result<Vec<pfctl::FilterRule>> { .. }
```
</blockquote></details>

Done.
___
*[`talpid-core/src/firewall/macos.rs` line 768 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nslo3z61cn96netmpoj:-Nt_XSFl7gV85M0M72fa:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/firewall/macos.rs#L768)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

A note about the safety would be nice :blush:
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 77 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmFxlE--2cTgqNgQne:-Nt_YWmg4ERYtUbmKDg0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L77)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Return a `Result<(ReadHalf, WriteHalf), Error>` instead of calling `unwrap`
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 107 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmI8na-sIluPyE0S1P:-Nt_a5t25_Le3HwU-dzY:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L107)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Would be nice to add a comment regarding the use of `unsafe`
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 117 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmIKSyEDLapZSPzpvj:-Nt_a6Ml4aZuJWhr2s3K:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L117)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Would be nice to add a comment regarding the use of `unsafe`
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 126 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmJP0a3sZRUUaHQBly:-Nt_a7A8BcgOA6x_CS44:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L126)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Would be nice to add a comment regarding the use of `unsafe`
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 136 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmJRnHCgwWTedgGeBj:-Nt_aKOGBxCNCGbb9SW3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L136)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Would be nice to add a comment regarding the use of `unsafe`
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 150 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmJV1x5bqKBjNSxvZE:-Nt_aLcWDI4oo01PFmXk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L150)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Would be nice to add a comment regarding the use of `unsafe`
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 156 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmJX5D7NP4sMqooHX1:-Nt_aNlqE8eKJ1a9b85Y:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L156)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

You get the point
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 162 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmJZMI9XDovQeJSKyi:-Nt_aOuE3hMBz9Im5UMe:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L162)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

unsafe without safety reasoning
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmS9Nu8sklOQxaFhAF:-Nt_aPMkDIOe-RphG3fh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L168)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

unsafe without safety reasoning
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 173 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmSCpCD1LZFiF5ARIV:-Nt_aPlM5KIvDwbulgVQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L173)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

unsafe without safety reasoning
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 179 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmSF_r0jyBhjPKMnYU:-Nt_aQKtCxlYqfzK2vzG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L179)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

unsafe without safety reasoning
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 187 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmSHJI4yWvyu3cppbb:-Nt_aRGP-pjqYUjqW-Uz:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L187)):* [...]

2024-03-25 09:16 UTC, dlon reviewed
> Reviewed 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 18 of 38 files reviewed, 49 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`talpid-core/src/split_tunnel/macos/include/bindings.h` line 9 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nsi3Q640B24RU1CCwr_:-Ntok_GjCMHnyBtwiyrm:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/include/bindings.h#L9)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Done.
___
*[`talpid-core/src/tunnel_state_machine/disconnected_state.rs` line 222 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nsi9lLnAFggrIQIQpWa:-Ntomc7A7ieyLKeF8nnL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/tunnel_state_machine/disconnected_state.rs#L222)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Dito
</blockquote></details>

Done.
___
*[`talpid-core/src/tunnel_state_machine/disconnecting_state.rs` line 83 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nsi9pkpCSYGgR_DMtJx:-Ntomd432wqfFJc9dHwv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/tunnel_state_machine/disconnecting_state.rs#L83)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Dito
</blockquote></details>

Done.
___
*[`talpid-core/src/tunnel_state_machine/disconnecting_state.rs` line 132 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nsi9rSu1f8cKbyISCvH:-Ntomdll2HBqzKmdWwhb:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/tunnel_state_machine/disconnecting_state.rs#L132)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Dito
</blockquote></details>

Done.
___
*[`talpid-core/src/tunnel_state_machine/disconnecting_state.rs` line 182 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nsi9tECE2PrbVUBuhP1:-Ntomeuc3Nv0iF0_2cB3:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/tunnel_state_machine/disconnecting_state.rs#L182)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Dito
</blockquote></details>

Done.
___
*[`talpid-core/src/tunnel_state_machine/error_state.rs` line 219 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nsi9w581HM_NFd6sBA7:-NtomfnY5ZfB3kvbDxTw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/tunnel_state_machine/error_state.rs#L219)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Dito
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-25 15:49 UTC, MarkusPettersson98 requested changes
> Reviewed 2 of 5 files at r4, 1 of 6 files at r5, 1 of 8 files at r6, 1 of 1 files at r7, 2 of 12 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 18 of 41 files reviewed, 9 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 301 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmTUKg2iZ7AvTTBDo5:-Ntab4Qg3T9sxsx5zbux:bdeavht) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/bpf.rs#L301)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. I've also refactored the handling of BPF payloads.
</blockquote></details>

:fire: 
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 315 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtabCYh3ymh15O22Skv:-NtabCYh3ymh15O22Skw:b-m0xvc3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a10eadda10accb23728229931ef154c1609ebd20/talpid-core/src/split_tunnel/macos/bpf.rs#L315)):*
> ```XML
>         }
> 
>         let hdr = unsafe { &*(self.data.as_ptr() as *const u8 as *const bpf_hdr) };
> ```

Unsafe without safety reasoning



_Code quote:_
```XML
let hdr = unsafe { &*(self.data.as_ptr() as *const u8 as *const bpf_hdr) };
```
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 175 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsmfWd_9BoUmww8wgCV:-NtqFQgR5D963vS89a9E:bncfle7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/split_tunnel/macos/process.rs#L175)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Yep. I'll switch to using sets.
</blockquote></details>

:fire:
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 273 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtqGRXK75XhyVF1YnXx:-NtqGRXLCONrUstoxFXz:b9f4zt5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/process.rs#L273)):*
> ```XML
>     let buf_sz = (num_pids as usize * std::mem::size_of::<u32>()) as i32;
>     // SAFETY: 'pids' is large enough to contain 'num_pids' processes
>     let num_pids = unsafe { proc_listallpids(pids.as_mut_ptr() as *mut c_void, buf_sz) };
> ```

This might be too nitpicky, but it feels wrong to perform a cast from `u32` to `i32`, which may silently overflow the result, and pass that to unsafe code. It should be fine, as `num_pids` *should* not be large enough for this to be a problem. But I also feel like simply checking the conversion at runtime and propagating the error is a low enough cost to say "just do it" :blush: 



_Code quote:_
```XML
    let buf_sz = (num_pids as usize * std::mem::size_of::<u32>()) as i32;
    // SAFETY: 'pids' is large enough to contain 'num_pids' processes
    let num_pids = unsafe { proc_listallpids(pids.as_mut_ptr() as *mut c_void, buf_sz) };
```
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 164 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtaDvJi6KLF1St99UWF:-NtaDvJi6KLF1St99UWG:b8eywas) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a10eadda10accb23728229931ef154c1609ebd20/talpid-core/src/split_tunnel/macos/tun.rs#L164)):*
> ```XML
>     vpn_interface: Option<VpnInterface>,
>     classify: impl Fn(&PktapPacket) -> RoutingDecision + Send + 'static,
> ) -> Result<SplitTunnelHandle, Error> {
> ```

Clean API+docs! :purple_heart:



_Code quote:_
```XML
/// Create split tunnel device and handle all packets using `classify`. Handle any changes to the
/// default interface or gateway.
///
/// # Note
///
/// `classify` receives an Ethernet frame. The Ethernet header is not valid at this point, however.
/// Only the IP header and payload are.
pub async fn create_split_tunnel(
    default_interface: DefaultInterface,
    vpn_interface: Option<VpnInterface>,
    classify: impl Fn(&PktapPacket) -> RoutingDecision + Send + 'static,
) -> Result<SplitTunnelHandle, Error> {
```
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 172 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtaDt0QCNW5aZf4m9nn:-NtaDt0QCNW5aZf4m9no:bb7462z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a10eadda10accb23728229931ef154c1609ebd20/talpid-core/src/split_tunnel/macos/tun.rs#L172)):*
> ```XML
> 
>     // Add IPv6 address
>     // TODO: Only add IPv6 address if there's either a tun or a non-tun IPv6 route
> ```

TODO



_Code quote:_
```XML
    // TODO: Only add IPv6 address if there's either a tun or a non-tun IPv6 route
```
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 214 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtaENe755lYCsUkqTmq:-NtaENe86DjSGN5KLlCs:bjkjap0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a10eadda10accb23728229931ef154c1609ebd20/talpid-core/src/split_tunnel/macos/tun.rs#L214)):*
> ```XML
>     default_interface: DefaultInterface,
>     vpn_interface: Option<VpnInterface>,
> }
> ```

I get what the point of this data type is, but it is a bit hard to parse as is :sweat_smile: Think of maybe adding some type aliases and/or doc comments!



_Code quote:_
```XML
struct RedirectHandle {
    abort_tx: broadcast::Sender<()>,
    ingress_task: tokio::task::JoinHandle<(
        tokio::io::ReadHalf<tun::AsyncDevice>,
        tokio::io::WriteHalf<tun::AsyncDevice>,
    )>,
    classify_task: tokio::task::JoinHandle<
        Result<
            (
                PktapStream,
                Box<dyn Fn(&PktapPacket) -> RoutingDecision + Send + 'static>,
            ),
            Error,
        >,
    >,
    default_interface: DefaultInterface,
    vpn_interface: Option<VpnInterface>,
}
```
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 228 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtaF6HzAWGhDq942n9o:-NtaF6HzAWGhDq942n9p:b-v90o9d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a10eadda10accb23728229931ef154c1609ebd20/talpid-core/src/split_tunnel/macos/tun.rs#L228)):*
> ```XML
>         ),
>         Error,
>     > {
> ```

I'm a bit surprised that `clippy` doesn' t complain about complex types :sweat_smile:
Try to make it obvious what is being returned from this function :smile: 



_Code quote:_
```XML
    ) -> Result<
        (
            tun::AsyncDevice,
            PktapStream,
            Box<dyn Fn(&PktapPacket) -> RoutingDecision + Send + 'static>,
            DefaultInterface,
            Option<VpnInterface>,
        ),
        Error,
    > {
```
___
*[`talpid-core/src/tunnel_state_machine/mod.rs` line 515 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsiAoroElLUFriN7edi:-NtaaCfCE4FFA_SRhSZI:btsh6wn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/tunnel_state_machine/mod.rs#L515)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The `maybe_` prefix is because it only starts the machinery if
</blockquote></details>

If .. ? :smile: 
___
*[`talpid-core/src/tunnel_state_machine/mod.rs` line 539 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtqHcAu4YYZAFYAWgEg:-NtqHcAv85LlylmI9L5N:b-9lerig) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/tunnel_state_machine/mod.rs#L539)):*
> ```XML
>                     "{}",
>                     error.display_chain_with_msg("Failed to set VPN interface for split tunnel")
>                 );
> ```

Nit: The logging could be performed inside of [inspect_err](https://doc.rust-lang.org/std/result/enum.Result.html#method.inspect_err), and the mapping from `error` to `ErrorStateCause` could be contained within `map_err` :blush:

```rust
        self.runtime
            .block_on(sel [...]

2024-03-25 16:02 UTC, MarkusPettersson98 requested changes
> Reviewed 3 of 12 files at r9, 1 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 22 of 41 files reviewed, 9 unresolved discussions (waiting on @dlon)

___
*[`talpid-routing/src/unix/macos/interface.rs` line 269 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtqKjII7XiPMKlO3phN:-NtqKjII7XiPMKlO3phO:b6xxowj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-routing/src/unix/macos/interface.rs#L269)):*
> ```XML
>                 log::debug!("Missing IP for primary interface \"{name}\"");
>                 None
>             })?;
> ```

I like the chaining of `and_then`! But perhaps there are similarities between `get_primary_interface` and `network_services` that could be shared? The `filter_map` in `network_services` is out of this world :sweat_smile: 



_Code quote:_
```XML
        let first_ip = global_dict
            .find(ip_key)
            .map(|s| unsafe { CFType::wrap_under_get_rule(*s) })
            .and_then(|s| s.downcast::<CFArray>())
            .and_then(|ips| {
                ips.get(0)
                    .map(|ip| unsafe { CFType::wrap_under_get_rule(*ip) })
            })
            .and_then(|s| s.downcast::<CFString>())
            .and_then(|ip| ip.to_string().parse().ok())
            .or_else(|| {
                log::debug!("Missing IP for primary interface \"{name}\"");
                None
            })?;
```


<!-- Sent from Reviewable.io -->

2024-03-25 16:26 UTC, MarkusPettersson98 requested changes
> Reviewed 1 of 5 files at r3, 4 of 12 files at r9, 2 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 30 of 41 files reviewed, 11 unresolved discussions (waiting on @dlon)

___
*[`mullvad-daemon/src/lib.rs` line 1912 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtqP7UK18pDopLOId3w:-NtqP7UK18pDopLOId3x:b-cu3bdt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/mullvad-daemon/src/lib.rs#L1912)):*
> ```XML
>         } else {
>             vec![]
>         };
> ```

May I suggest
```rust
        let tunnel_list: Vec<OsString> = match update {
            ExcludedPathsUpdate::SetPaths(ref paths) if settings.split_tunnel.enable_exclusions => {
                paths.iter().map(OsString::from).collect()
            },
            ExcludedPathsUpdate::SetState(true) => {
                settings.split_tunnel.apps.iter().map(OsString::from).collect()
            },
            _ => vec![],
        };
```

Avoids introducing intermediary variables and keeps the relevant iterators closer to the match-arms that they belong to :blush:



_Code quote:_
```XML
        let new_list = match update {
            ExcludedPathsUpdate::SetPaths(ref paths) => paths.iter(),
            ExcludedPathsUpdate::SetState(_) => settings.split_tunnel.apps.iter(),
        };
        let new_state = match update {
            ExcludedPathsUpdate::SetPaths(_) => settings.split_tunnel.enable_exclusions,
            ExcludedPathsUpdate::SetState(state) => state,
        };

        let tunnel_list = if new_state {
            new_list.map(OsString::from).collect()
        } else {
            vec![]
        };
```
___
*[`talpid-routing/src/unix/mod.rs` line 107 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtqLzKPCJbejqS7TTnJ:-NtqLzKQEPs090BmNWAM:b-xqwkl1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-routing/src/unix/mod.rs#L107)):*
> ```XML
>         oneshot::Sender<Result<Option<Route>, PlatformError>>,
>     ),
> }
> ```

Would it make sense to declare this enum separately for macOS and Linux? :blush:

```rust
/// Commands for the underlying route manager object.
#[cfg(target_os = "linux")]
#[derive(Debug)]
pub(crate) enum RouteManagerCommand {
    AddRoutes(
        HashSet<RequiredRoute>,
        oneshot::Sender<Result<(), PlatformError>>,
    ),
    ClearRoutes,
    Shutdown(oneshot::Sender<()>),
    CreateRoutingRules(bool, oneshot::Sender<Result<(), PlatformError>>),
    ClearRoutingRules(oneshot::Sender<Result<(), PlatformError>>),
    NewChangeListener(oneshot::Sender<mpsc::UnboundedReceiver<CallbackMessage>>),
    GetMtuForRoute(IpAddr, oneshot::Sender<Result<u16, PlatformError>>),
    /// Attempt to fetch a route for the given destination with an optional firewall mark.
    GetDestinationRoute(
        IpAddr,
        Option<Fwmark>,
        oneshot::Sender<Result<Option<Route>, PlatformError>>,
    ),
}

/// Commands for the underlying route manager object.
#[cfg(target_os = "macos")]
#[derive(Debug)]
pub(crate) enum RouteManagerCommand {
    AddRoutes(
        HashSet<RequiredRoute>,
        oneshot::Sender<Result<(), PlatformError>>,
    ),
    ClearRoutes,
    Shutdown(oneshot::Sender<()>),
    RefreshRoutes,
    NewDefaultRouteListener(oneshot::Sender<mpsc::UnboundedReceiver<DefaultRouteEvent>>),
    GetDefaultRoutes(oneshot::Sender<(Option<DefaultRoute>, Option<DefaultRoute>)>),
    /// Return gateway for V4 and V6
    GetDefaultGateway(oneshot::Sender<(Option<Gateway>, Option<Gateway>)>),
}
```



_Code quote:_
```XML
/// Commands for the underlying route manager object.
#[derive(Debug)]
pub(crate) enum RouteManagerCommand {
    AddRoutes(
        HashSet<RequiredRoute>,
        oneshot::Sender<Result<(), PlatformError>>,
    ),
    ClearRoutes,
    Shutdown(oneshot::Sender<()>),
    #[cfg(target_os = "macos")]
    RefreshRoutes,
    #[cfg(target_os = "macos")]
    NewDefaultRouteListener(oneshot::Sender<mpsc::UnboundedReceiver<DefaultRouteEvent>>),
    #[cfg(target_os = "macos")]
    GetDefaultRoutes(oneshot::Sender<(Option<DefaultRoute>, Option<DefaultRoute>)>),
    /// Return gateway for V4 and V6
    #[cfg(target_os = "macos")]
    GetDefaultGateway(oneshot::Sender<(Option<Gateway>, Option<Gateway>)>),
    #[cfg(target_os = "linux")]
    CreateRoutingRules(bool, oneshot::Sender<Result<(), PlatformError>>),
    #[cfg(target_os = "linux")]
    ClearRoutingRules(oneshot::Sender<Result<(), PlatformError>>),
    #[cfg(target_os = "linux")]
    NewChangeListener(oneshot::Sender<mpsc::UnboundedReceiver<CallbackMessage>>),
    #[cfg(target_os = "linux")]
    GetMtuForRoute(IpAddr, oneshot::Sender<Result<u16, PlatformError>>),
    /// Attempt to fetch a route for the given destination with an optional firewall mark.
    #[cfg(target_os = "linux")]
    GetDestinationRoute(
        IpAddr,
        Option<Fwmark>,
        oneshot::Sender<Result<Option<Route>, PlatformError>>,
    ),
}
```


<!-- Sent from Reviewable.io -->

2024-03-26 14:27 UTC, MarkusPettersson98 requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 28 of 41 files reviewed, 18 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 115 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Ntu5lo54_VZZRLy9Xhk:-Ntu5lo54_VZZRLy9Xhl:bdtpcnv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/tun.rs#L115)):*
> ```XML
>     redir_handle: Option<RedirectHandle>,
>     tun_name: String,
> }
> ```

Does `redir_handle` really need to be an `Option<RedirectHandle>`? Changing the type to simply `RedirectHandle` seems straightforward from my own investigations :blush:



_Code quote:_
```XML
pub struct SplitTunnelHandle {
    redir_handle: Option<RedirectHandle>,
    tun_name: String,
}
```
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 279 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Ntu7c7iDhhyjlC0Cpk_:-Ntu7c7iDhhyjlC0Cpka:b-hr6nii) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/tun.rs#L279)):*
> ```XML
>     vpn_interface: Option<VpnInterface>,
>     mut classify: Box<dyn Fn(&PktapPacket) -> RoutingDecision + Send + 'static>,
> ) -> Result<RedirectHandle, Error> {
> ```

This function is pretty dense .. If the code can't be made more descriptive than it already is, please add some documentation explaining the scaffolding that is done and what the spawned tasks do



_Code quote:_
```XML
async fn redirect_packets_for_pktap_stream(
    tun_device: tun::AsyncDevice,
    mut pktap_stream: PktapStream,
    default_interface: DefaultInterface,
    vpn_interface: Option<VpnInterface>,
    mut classify: Box<dyn Fn(&PktapPacket) -> RoutingDecision + Send + 'static>,
) -> Result<RedirectHandle, Error> {
```
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 542 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Ntu95XnDLcRZrSPpjou:-Ntu95XnDLcRZrSPpjov:b-vkm59b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/tun.rs#L542)):*
> ```XML
>         // Drop attempt to send packets to tun IP on the real interface
>         return;
>     }
> ```

Silently dropping this packet might lead to headache in the future (?). Would it make sense to insert a `log::trace!` statement here? :blush:



_Code quote:_
```XML
    if ip.get_destination() == vpn_addr {
        // Drop attempt to send packets to tun IP on the real interface
        return;
    }
```
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 563 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Ntu9M2C4ZyJPM78zmnG:-Ntu9M2C4ZyJPM78zmnH:b-vkm59b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/tun.rs#L563)):*
> ```XML
>         // Drop attempt to send packets to tun IP on the real interface
>         return;
>     }
> ```

Silently dropping this packet might lead to headache in the future (?). Would it make sense to insert a `log::trace!` statement here? :blush:



_Code quote:_
```XML
    if ip.get_destination() == vpn_addr {
        // Drop attempt to send packets to tun IP on the real interface
        return;
    }
```
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 688 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtuO7P73INVacQt9t_F:-NtuO7P73INVacQt9t_G:b-5ydddx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/tun.rs#L688)):*
> ```XML
>             Err(error) => Some(Err(Error::GetNextPacket(error))),
>         }
>     }))
> ```

Nit: This is equivalent to
```rust
Ok(stream.filter_map(|pkt| async { pkt.map_err(Error::GetNextPacket).transpose() }))
```

With most of the noise out of the way, I think the end of this function could be re-written into this nice piece of code:

```rust
    let stream = cap
        .stream(PktapCodec::new(utun_iface.to_owned()))
        .map_err(Error::CreateStream)?
        .filter_map(|pkt| async { pkt.map_err(Error::GetNextPacket).transpose() });

    Ok(stream)
```



_Code quote:_
```XML
    Ok(stream.filter_map(|pkt| async {
        match pkt {
            Ok(Some(pkt)) => Some(Ok(pkt)),
            Ok(None) => None,
            Err(error) => Some(Err(Error::GetNextPacket(error))),
        }
    }))
```
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 735 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Ntv1WmzCrqsZuwhNISu:-Ntv1WmzCrqsZuwhNISv:b-7asu0c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/tun.rs#L735)):*
> ```XML
>         let mut frame = MutableEthernetPacket::owned(vec![0u8; 14 + data.len() - 4]).unwrap();
> 
>         let raw_family = i32::from_ne_bytes(data[0..4].try_into().unwrap());
> ```

I think logging + propagating `None`is more robust than using `unwrap` in this case

```rust
        // TODO: Wasteful. Could share single buffer if handling one frame at a time (assuming no
        // concurrency is needed). Allocating the frame here is purely done for efficiency reasons.
        let ethertype = data[0..4]
            .try_into()
            .inspect_err(|error| log::error!(".."))
            .ok()
            .map(i32::from_ne_bytes)
            .and_then(|family| match family {
                AF_INET => Some(EtherTypes::Ipv4),
                AF_INET6 => Some(EtherTypes::Ipv6),
                _ => None,
            })?;

        let mut frame = MutableEthernetPacket::owned(vec![0u8; 14 + data.len() - 4])?;
        frame.set_ethertype(ethertype);
        frame.set_payload(&data[4..]);
```



_Code quote:_
```XML
        let mut frame = MutableEthernetPacket::owned(vec![0u8; 14 + data.len() - 4]).unwrap();

        let raw_family = i32::from_ne_bytes(data[0..4].try_into().unwrap());
```
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 760 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Ntv9-ZM6GS8_291P-Am:-Ntv9-ZNEPfJE2Q4HLNE:b-ioz610) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/tun.rs#L760)):*
> ```XML
>     let mut errbuf = [0u8; PCAP_ERRBUF_SIZE as usize];
> 
>     let pcap = unsafe { pcap_create(b"pktap\0".as_ptr() as *const _, errbuf.as_mut_ptr() as _) };
> ```

C-string literals! :tada: 

```rust
c"pktap"
```



_Code quote:_
```XML
b"pktap\0"
```


<!-- Sent from Reviewable.io -->

2024-03-27 18:23 UTC, dlon reviewed
> Reviewed 1 of 5 files at r3, 3 of 12 files at r9, 1 of 3 files at r10, 1 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 21 of 41 files reviewed, 18 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-daemon/src/lib.rs` line 1912 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtqP7UK18pDopLOId3w:-Nu-wbcs0JH9MBpRYHkN:b-ytzzth) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/mullvad-daemon/src/lib.rs#L1912)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

May I suggest
```rust
        let tunnel_list: Vec<OsString> = match update {
            ExcludedPathsUpdate::SetPaths(ref paths) if settings.split_tunnel.enable_exclusions => {
                paths.iter().map(OsString::from).collect()
            },
            ExcludedPathsUpdate::SetState(true) => {
                settings.split_tunnel.apps.iter().map(OsString::from).collect()
            },
            _ => vec![],
        };
```

Avoids introducing intermediary variables and keeps the relevant iterators closer to the match-arms that they belong to :blush:
</blockquote></details>

Nice suggestion! Done.
___
*[`talpid-core/src/split_tunnel/macos/bpf.rs` line 315 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtabCYh3ymh15O22Skv:-Nu06qY697hnVt5JS9mf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a10eadda10accb23728229931ef154c1609ebd20/talpid-core/src/split_tunnel/macos/bpf.rs#L315)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Unsafe without safety reasoning
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 172 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtaDt0QCNW5aZf4m9nn:-Nu-y8GZCJ82AHALQHZo:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a10eadda10accb23728229931ef154c1609ebd20/talpid-core/src/split_tunnel/macos/tun.rs#L172)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 214 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtaENe755lYCsUkqTmq:-Nu04XFW195R91tRqX7n:b-at48gb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a10eadda10accb23728229931ef154c1609ebd20/talpid-core/src/split_tunnel/macos/tun.rs#L214)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I get what the point of this data type is, but it is a bit hard to parse as is :sweat_smile: Think of maybe adding some type aliases and/or doc comments!
</blockquote></details>

That wasn't pretty. :sweat_smile: I managed to make it simpler and added some docs.
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 228 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtaF6HzAWGhDq942n9o:-Nu04Jyv5hRehDSIWZyz:b-t5psjk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a10eadda10accb23728229931ef154c1609ebd20/talpid-core/src/split_tunnel/macos/tun.rs#L228)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I'm a bit surprised that `clippy` doesn' t complain about complex types :sweat_smile:
Try to make it obvious what is being returned from this function :smile:
</blockquote></details>

I split this function into two instead. Do you find it more readable?
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 115 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Ntu5lo54_VZZRLy9Xhk:-Nu-xwUR-gEi0140nhnM:btnylej) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/tun.rs#L115)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Does `redir_handle` really need to be an `Option<RedirectHandle>`? Changing the type to simply `RedirectHandle` seems straightforward from my own investigations :blush:
</blockquote></details>

You're right. Nice catch!
___
*[`talpid-core/src/tunnel_state_machine/mod.rs` line 515 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NsiAoroElLUFriN7edi:-Nu06UeuEU9FF-2O6Bj4:b-ebj74f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/tunnel_state_machine/mod.rs#L515)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

If .. ? :smile:
</blockquote></details>

It's gone :smile: 


<!-- Sent from Reviewable.io -->

2024-03-28 16:13 UTC, dlon reviewed
> Reviewed 9 of 13 files at r13.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 19 of 41 files reviewed, 15 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 273 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtqGRXK75XhyVF1YnXx:-Nu3CzAI70AwLbAgVBu7:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/process.rs#L273)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This might be too nitpicky, but it feels wrong to perform a cast from `u32` to `i32`, which may silently overflow the result, and pass that to unsafe code. It should be fine, as `num_pids` *should* not be large enough for this to be a problem. But I also feel like simply checking the conversion at runtime and propagating the error is a low enough cost to say "just do it" :blush:
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 279 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Ntu7c7iDhhyjlC0Cpk_:-Nu3EvGw-K5PiM14Hyfv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/tun.rs#L279)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This function is pretty dense .. If the code can't be made more descriptive than it already is, please add some documentation explaining the scaffolding that is done and what the spawned tasks do
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 542 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Ntu95XnDLcRZrSPpjou:-Nu3G4g_5HukER0fwZm7:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/tun.rs#L542)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Silently dropping this packet might lead to headache in the future (?). Would it make sense to insert a `log::trace!` statement here? :blush:
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 563 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Ntu9M2C4ZyJPM78zmnG:-Nu3G5RvCp855oAUaqMj:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/tun.rs#L563)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Silently dropping this packet might lead to headache in the future (?). Would it make sense to insert a `log::trace!` statement here? :blush:
</blockquote></details>

Done.
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 688 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtuO7P73INVacQt9t_F:-Nu3GVEn0H0Fi4LBGyP_:bjvyb7f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/tun.rs#L688)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Nit: This is equivalent to
```rust
Ok(stream.filter_map(|pkt| async { pkt.map_err(Error::GetNextPacket).transpose() }))
```

With most of the noise out of the way, I think the end of this function could be re-written into this nice piece of code:

```rust
    let stream = cap
        .stream(PktapCodec::new(utun_iface.to_owned()))
        .map_err(Error::CreateStream)?
        .filter_map(|pkt| async { pkt.map_err(Error::GetNextPacket).transpose() });

    Ok(stream)
```
</blockquote></details>

Nice! Fixed.
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 735 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Ntv1WmzCrqsZuwhNISu:-Nu4pLhw0nMTlTwE8rUs:bg8yd1r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/tun.rs#L735)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I think logging + propagating `None`is more robust than using `unwrap` in this case

```rust
        // TODO: Wasteful. Could share single buffer if handling one frame at a time (assuming no
        // concurrency is needed). Allocating the frame here is purely done for efficiency reasons.
        let ethertype = data[0..4]
            .try_into()
            .inspect_err(|error| log::error!(".."))
            .ok()
            .map(i32::from_ne_bytes)
            .and_then(|family| match family {
                AF_INET => Some(EtherTypes::Ipv4),
                AF_INET6 => Some(EtherTypes::Ipv6),
                _ => None,
            })?;

        let mut frame = MutableEthernetPacket::owned(vec![0u8; 14 + data.len() - 4])?;
        frame.set_ethertype(ethertype);
        frame.set_payload(&data[4..]);
```
</blockquote></details>

Panicking is probably preferable here. (Discussed offline.)
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 760 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Ntv9-ZM6GS8_291P-Am:-Nu3HX-d3ygkCCh2mvIR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-core/src/split_tunnel/macos/tun.rs#L760)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

C-string literals! :tada: 

```rust
c"pktap"
```
</blockquote></details>

Done.
___
*[`talpid-routing/src/unix/macos/interface.rs` line 269 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtqKjII7XiPMKlO3phN:-Nu4nHGzBR4dcEEm-XBs:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/65ca81979cb1b3fa1836ca184327c566d8e236e7/talpid-routing/src/unix/macos/interface.rs#L269)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I like the chaining of `and_then`! But perhaps there are similarities between `get_primary_interface` and `network_services` that could be shared? The `filter_map` in `network_services` is out of this world :sweat_smile:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-04 14:15 UTC, MarkusPettersson98 requested changes
> Reviewed 2 of 13 files at r13, 1 of 5 files at r14, 3 of 3 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 23 of 41 files reviewed, 6 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/firewall/mod.rs` line 128 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nsi2DtuAqDFkgYT5yf4:-Nsi2Dtv38dQWMdNOdA4:boevy6a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/firewall/mod.rs#L128)):*
> ```XML
>         /// Interface to redirect (VPN tunnel) traffic to
>         #[cfg(target_os = "macos")]
>         redirect_interface: Option<String>,
> ```

Nit Would be nice with a more descriptive type than `Option<String>`.. :smile:



_Code quote:_
```XML
        /// Interface to redirect (VPN tunnel) traffic to
        #[cfg(target_os = "macos")]
        redirect_interface: Option<String>,
```
___
*[`talpid-core/src/firewall/mod.rs` line 144 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nsi2NSmBgLVSYHZMdDv:-Nsi2NSmBgLVSYHZMdDw:boevy6a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeda415c42a07de3ef926ff5439e052becd5a8b/talpid-core/src/firewall/mod.rs#L144)):*
> ```XML
>         /// Interface to redirect (VPN tunnel) traffic to
>         #[cfg(target_os = "macos")]
>         redirect_interface: Option<String>,
> ```

Nit Would be nice with a more descriptive type than `Option<String>`.. :smile:



_Code quote:_
```XML
        /// Interface to redirect (VPN tunnel) traffic to
        #[cfg(target_os = "macos")]
        redirect_interface: Option<String>,
```
___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 120 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NudO3h-6iQmTl3B9kXY:-NudO3h-6iQmTl3B9kXZ:b15ktxr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b04ecf48d6dde8fc9671e73227c67b421ca5674/talpid-core/src/split_tunnel/macos/process.rs#L120)):*
> ```XML
>                                 }
>                             }
>                             Err(Error::MonitorFailed(io::Error::new(io::ErrorKind::Other, format!("eslogger stopped unexpectedly: {status}"))))
> ```

Tip Can use [`std::io::Error::other`](https://doc.rust-lang.org/std/io/struct.Error.html#method.other) instead of constructing this particular IO error manually :blush:



_Code quote:_
```XML
 Err(Error::MonitorFailed(io::Error::new(io::ErrorKind::Other, format!("eslogger stopped unexpectedly: {status}"))))
```
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 214 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtaENe755lYCsUkqTmq:-NucvbALCa84BUImxpje:bk09f7s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a10eadda10accb23728229931ef154c1609ebd20/talpid-core/src/split_tunnel/macos/tun.rs#L214)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

That wasn't pretty. :sweat_smile: I managed to make it simpler and added some docs.
</blockquote></details>

:raised_hands:
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 228 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NtaF6HzAWGhDq942n9o:-Nucw2Mi6i6CYl0RvcOW:b-595bbz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a10eadda10accb23728229931ef154c1609ebd20/talpid-core/src/split_tunnel/macos/tun.rs#L228)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I split this function into two instead. Do you find it more readable?
</blockquote></details>

Yes, definitely! Nice job! :smile:
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 172 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NucuX_H4SPD6A0MvOpz:-NucuX_H4SPD6A0MvOq-:b-arhuzu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b04ecf48d6dde8fc9671e73227c67b421ca5674/talpid-core/src/split_tunnel/macos/tun.rs#L172)):*
> ```XML
>             io::ErrorKind::Other,
>             "ifconfig failed",
>         )));
> ```

Tip use [io::Error::other](https://doc.rust-lang.org/std/io/struct.Error.html#method.other) instead of manuall specifying the type

```rust
        return Err(Error::AddIpv6Address(io::Error::other(
            "ifconfig failed",
        )));
```



_Code quote:_
```XML
        return Err(Error::AddIpv6Address(io::Error::new(
            io::ErrorKind::Other,
            "ifconfig failed",
        )));
```
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 264 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nud00jB2x80Fqg4zlum:-Nud00jB2x80Fqg4zlun:b-uublth) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b04ecf48d6dde8fc9671e73227c67b421ca5674/talpid-core/src/split_tunnel/macos/tun.rs#L264)):*
> ```XML
> /// Monitor outgoing traffic on `st_tun_device` using `pktap_stream`. A routing decision is made for
> /// each packet using `classify`. Based on this, a packet is forced out on either
> /// `default_interface` or `vpn_interface`.
> ```

Based on this, a packet is either dropped or forced out on either `default_interface` or `vpn_interface`.



_Code quote:_
```XML
/// each packet using `classify`. Based on this, a packet is forced out on either
/// `default_interface` or `vpn_interface`.
```
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 295 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nud3VxuBsR9qQqZkYmj:-Nud3VxuBsR9qQqZkYmk:bk13d4z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b04ecf48d6dde8fc9671e73227c67b421ca5674/talpid-core/src/split_tunnel/macos/tun.rs#L295)):*
> ```XML
>         bpf::BpfStream::from_read_half(default_read).map_err(Error::CreateDefaultBpf)?;
> 
>     let (abort_tx, abort_rx) = broadcast::channel(5);
> ```

I think the capacity could safely be reduced to `1` :blush:



_Code quote:_
```XML
   let (abort_tx, abort_rx) = broadcast::channel(5);
```
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 772 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NudMAzC63GExgtFHLbb:-NudMAzC63GExgtFHLbc:b-no5pkw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b04ecf48d6dde8fc9671e73227c67b421ca5674/talpid-core/src/split_tunnel/macos/tun.rs#L772)):*
> ```XML
> 
>         frame.set_ethertype(ethertype);
>         frame.set_payload(&data[4..]);
> ```

Tip Perfect use case for [`slice::split_first_chunk!`](https://doc.rust-lang.org/stable/std/primitive.slice.html#method.split_first_chunk)

```rust
        let (raw_family, payload) = data.split_first_chunk::<4>()?;
        let ethertype = match i32::from_ne_bytes(*raw_family) {
            AF_INET => EtherTypes::Ipv4,
            AF_INET6 => EtherTypes::Ipv6,
            _ => return None,
        };

        frame.set_ethertype(ethertype);
        frame.set_payload(payload);
```



_Code quote:_
```XML
        let raw_family = i32::from_ne_bytes(data[0..4].try_into().unwrap());
        let ethertype = match raw_family {
            AF_INET => EtherTypes::Ipv4,
            AF_INET6 => EtherTypes::Ipv6,
            _ => return None,
        };

        frame.set_ethertype(ethertype);
        frame.set_payload(&data[4..]);
```


<!-- Sent from Reviewable.io -->

2024-04-04 14:17 UTC, MarkusPettersson98 requested changes
> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 26 of 41 files reviewed, 7 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 762 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NudT05-0KZK7iWWsNJo:-NudT05-0KZK7iWWsNJp:b-owfump) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4232c25600e846d5b92b45e0b8823d996d177148/talpid-core/src/split_tunnel/macos/tun.rs#L762)):*
> ```XML
>             // Ignore incoming packets
>             return None;
>         }
> ```

Leave a comment (FIXME?) stating that this can be removed once macOS13 is no longer supported :blush:



_Code quote:_
```XML
        if header.pth_flags ^ PTH_FLAG_DIR_OUT == 0 {
            // Ignore incoming packets
            return None;
        }
```


<!-- Sent from Reviewable.io -->

2024-04-04 15:26 UTC, MarkusPettersson98 reviewed
> Reviewed 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 26 of 41 files reviewed, 5 unresolved discussions (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2024-04-04 15:28 UTC, dlon reviewed
> Reviewed 2 of 37 files at r1, 1 of 13 files at r13, 1 of 5 files at r14, 2 of 3 files at r16, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 26 of 41 files reviewed, 4 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 120 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NudO3h-6iQmTl3B9kXY:-Nudekz9BAMXXUOPyx8L:btvmx9d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b04ecf48d6dde8fc9671e73227c67b421ca5674/talpid-core/src/split_tunnel/macos/process.rs#L120)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Tip Can use [`std::io::Error::other`](https://doc.rust-lang.org/std/io/struct.Error.html#method.other) instead of constructing this particular IO error manually :blush:
</blockquote></details>

Nice! Didn't know that this was stable.
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 295 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nud3VxuBsR9qQqZkYmj:-NudfH-29EuxdYZWocAR:bjg6x97) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b04ecf48d6dde8fc9671e73227c67b421ca5674/talpid-core/src/split_tunnel/macos/tun.rs#L295)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I think the capacity could safely be reduced to `1` :blush:
</blockquote></details>

Yep. Done.
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 772 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NudMAzC63GExgtFHLbb:-NudgKkC31iREsqM2TJg:b-k6guu2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0b04ecf48d6dde8fc9671e73227c67b421ca5674/talpid-core/src/split_tunnel/macos/tun.rs#L772)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Tip Perfect use case for [`slice::split_first_chunk!`](https://doc.rust-lang.org/stable/std/primitive.slice.html#method.split_first_chunk)

```rust
        let (raw_family, payload) = data.split_first_chunk::<4>()?;
        let ethertype = match i32::from_ne_bytes(*raw_family) {
            AF_INET => EtherTypes::Ipv4,
            AF_INET6 => EtherTypes::Ipv6,
            _ => return None,
        };

        frame.set_ethertype(ethertype);
        frame.set_payload(payload);
```
</blockquote></details>

Nice one.
___
*[`talpid-core/src/split_tunnel/macos/tun.rs` line 762 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-NudT05-0KZK7iWWsNJo:-NudfKVw16iC4rVdxAT9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4232c25600e846d5b92b45e0b8823d996d177148/talpid-core/src/split_tunnel/macos/tun.rs#L762)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Leave a comment (FIXME?) stating that this can be removed once macOS13 is no longer supported :blush:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-04 15:38 UTC, MarkusPettersson98 reviewed
> Reviewed 1 of 1 files at r21.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 26 of 41 files reviewed, 2 unresolved discussions (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2024-04-08 08:57 UTC, MarkusPettersson98 reviewed
> Reviewed 4 of 4 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 29 of 41 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/split_tunnel/macos/process.rs` line 35 at r22](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-Nuwu7FFEWSXDZjrPLoC:-Nuwu7FFEWSXDZjrPLoD:b-6us8se) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33ec8cde87614e84ffba5b9ab4d090202ea4f712/talpid-core/src/split_tunnel/macos/process.rs#L35)):*
> ```XML
>     /// Only macOS 13 and later is supported
>     #[error("Unsupported macOS version")]
>     UnsupportedMacosVersion,
> ```

Would it be nice to parameterize this error variant over the different version numbers? Then they could be used in the error messages :blush:

```rust
    /// Only some versions of macOS is supported
    #[error("Unsupported macOS version: Got version {actual} but expected at least version {need}")]
    UnsupportedMacosVersion { actual: String, need: String },
```



_Code quote:_
```XML
    /// Only macOS 13 and later is supported
    #[error("Unsupported macOS version")]
    UnsupportedMacosVersion,
```


<!-- Sent from Reviewable.io -->

2024-04-11 09:43 UTC, MarkusPettersson98 reviewed
> Reviewed 9 of 10 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 35 of 48 files reviewed, 2 unresolved discussions (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2024-04-11 21:21 UTC, dlon reviewed
> Reviewed 1 of 1 files at r21, 1 of 14 files at r25.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844)* status: 28 of 51 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)



<!-- Sent from Reviewable.io -->

2024-04-30 12:43 UTC, MarkusPettersson98 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-:-Nwj16Db3XjHJnxIfKdl:bnfp4nl)* status: 44 of 53 files reviewed, all discussions resolved (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2024-04-30 14:25 UTC, hulthe approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> i guess x)

> Reviewed 3 of 14 files at r25, 1 of 1 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5844#-:-NwjOKBT9AopJnkjmquP:b3nwv1c)* status: 47 of 53 files reviewed, all discussions resolved (waiting on @dlon)



<!-- Sent from Reviewable.io -->

2024-04-30 14:30 UTC, merged

2026-02-24 16:51 UTC, pronebird commented on talpid-core/src/split_tunnel/macos/tun.rs
> +                    handle_incoming_data(&mut tun_writer, payload, vpn_v4, vpn_v6).await;
Is this correct to assume that this is a some sort of NAT because packets teleport between ST and default interface and they need to make their way back?

2026-02-25 07:59 UTC, dlon commented on talpid-core/src/split_tunnel/macos/tun.rs
> +                    handle_incoming_data(&mut tun_writer, payload, vpn_v4, vpn_v6).await;
Pretty much