Test account creation and deletion
mullvad/mullvadvpn-app pull request #5855
Opened 2024-02-23 16:35 UTC by niklasberglund

Implemented create and delete account tests. To test run `createAccount` and `deleteAccount` under `AccountTests`. This PR is building upon changes from https://github.com/mullvad/mullvadvpn-app/pull/5824 so it will be easier to review after it has been merged.

Leaving this as a draft right now because there's no good way of validating the existence of account in `MullvadApi.swift` - the way it is implemented right now is not robust.

2024-02-27 09:26 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: 0 of 33 files reviewed, 1 unresolved discussion

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 7534 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NrdsKxMBPWOZYhJXI3N:-NrdsKxMBPWOZYhJXI3O:b-n6gq5l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPN.xcodeproj/project.pbxproj#L7534)):*
> ```
> 				"PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]" = "MullvadVPN app integration tests";
> 				SECURITY_GROUP_IDENTIFIER = "";
> 				SWIFT_ACTIVE_COMPILATION_CONDITIONS = "DEBUG MULLVAD_ENVIRONMENT_STAGING";
> ```

The `MULLVAD_ENVIRONMENT_STAGING`and `MULLVAD_ENVIRONMENT_PRODUCTION` flags are no longer used in this PR. They are used by the PR for problem report test though. Thinking they might as well remain here to avoid merge conflict or should be removed here?


<!-- Sent from Reviewable.io -->

2024-02-27 10:48 UTC, rablador requested changes
> Reviewed 4 of 30 files at r1, 29 of 29 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: all files reviewed, 7 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 7534 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NrdsKxMBPWOZYhJXI3N:-NrdxNbG0v9_dr1Ybk5X:bd660xr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPN.xcodeproj/project.pbxproj#L7534)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

The `MULLVAD_ENVIRONMENT_STAGING`and `MULLVAD_ENVIRONMENT_PRODUCTION` flags are no longer used in this PR. They are used by the PR for problem report test though. Thinking they might as well remain here to avoid merge conflict or should be removed here?
</blockquote></details>

They should be removed if this PR doesn't use them.
___
*[`ios/MullvadVPNUITests/README.md` line 27 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nre784F1ULd4gLL84QR:-Nre784F1ULd4gLL84QS:b-t7oe6o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/README.md#L27)):*
> ```Markdown
> 
> ## GitHub setup
> 1. Ask GitHub admin for new runner token and set it up according to the steps presented, pass `--labels ios-test` to `config.sh` when running it.
> ```

What are the presented steps?
___
*[`ios/MullvadVPNUITests/README.md` line 33 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nre6xpZC7EW_5vI0hhY:-Nre6xpZC7EW_5vI0hhZ:bv4wx5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/README.md#L33)):*
> ```Markdown
>   - `IOS_NO_TIME_ACCOUNT_NUMBER`
>   - `IOS_TEST_DEVICE_IDENTIFIER_UUID` - unique identifier for the test device. Create new identifier with `uuidgen`.
>   - `IOS_TEST_DEVICE_UDID` - the iOS device's UDID.
> ```

What are these strange characters? Hard return?
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 39 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nre7Wf731841ERxaEuW:-Nre7Wf87wqcXIzeiv9m:b14hg46) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L39)):*
> ```Swift
>     }
> 
>     public static func getAPIIPAddress() throws -> String {
> ```

Nit: I know that we're currently not consistent about this, but I generally like camel casing abbreviations as well, eg. `getApiIpAddress`. Not sure if we should change anything though, since this class uses mostly uppercase abbreviations.
___
*[`ios/MullvadVPNUITests/Pages/AccountDeletionPage.swift` line 26 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nre86393rFThz1KJtAK:-Nre86393rFThz1KJtAL:b3gklnm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/Pages/AccountDeletionPage.swift#L26)):*
> ```Swift
> 
>     @discardableResult func tapDeleteAccountButton() -> Self {
>         guard let pageAccessibilityIdentifier = self.pageAccessibilityIdentifier else {
> ```

How come we do a specific check only for this identifier?
___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 38 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NreAJIv745jeSUPROPx:-NreAJIv745jeSUPROPy:b5g3z42) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L38)):*
> ```Swift
>         }
> 
>         if iOSDevicePinCode.isEmpty == false {
> ```

Should the test fail here instead?
___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 81 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NreARQCBsjuc2GuApEC:-NreARQCBsjuc2GuApED:byaieag) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L81)):*
> ```Swift
>     }
> 
>     func discardChangeLogIfShown() {
> ```

Nit: dismiss[ChangeLog...]


<!-- Sent from Reviewable.io -->

2024-02-27 14:41 UTC, rablador reviewed
> Reviewed 33 of 33 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: all files reviewed, 6 unresolved discussions (waiting on @niklasberglund)



<!-- Sent from Reviewable.io -->

2024-02-27 15:16 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: all files reviewed, 6 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 7534 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NrdsKxMBPWOZYhJXI3N:-NrenXZw7RESFVPIJOpw:brmh0es) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPN.xcodeproj/project.pbxproj#L7534)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

They should be removed if this PR doesn't use them.
</blockquote></details>

Removed 👌
___
*[`ios/MullvadVPNUITests/README.md` line 27 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nre784F1ULd4gLL84QR:-NreCymOAC7l_X9Vdsa0:b-cpsovh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/README.md#L27)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

What are the presented steps?
</blockquote></details>

Right, it's not very clear here. When creating a new runner in GitHub you're guided to run a setup script with a wizard asking you for labels and name of runner. A GitHub admin should give the information from the screenshot and from there the process is quite straightforward. Should it be clarified more in the README?

![image.png](https://files.reviewableusercontent.io/images/reviewable/331986/2BnTwktxCMsUbhsWHKI3mAXg/image.png)
___
*[`ios/MullvadVPNUITests/README.md` line 33 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nre6xpZC7EW_5vI0hhY:-NrenZpP37d0j00rIHWx:bo3imd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/README.md#L33)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

What are these strange characters? Hard return?
</blockquote></details>

Good question. I don't know, but VSCode really wanted to add them after this list. It resulted in a new line and small indentation(two spaces). Have removed them now.
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 39 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nre7Wf731841ERxaEuW:-NrenoF6BY9rLehWELwf:bqwob7p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L39)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: I know that we're currently not consistent about this, but I generally like camel casing abbreviations as well, eg. `getApiIpAddress`. Not sure if we should change anything though, since this class uses mostly uppercase abbreviations.
</blockquote></details>

I wasn't sure whether there's a convention for the codebase. Seen both. Here it's a bit awkward because `MullvadAPIWrapper` wraps `MullvadApi` 😄 Personally I like upper-casing abbreviations since Apple do it and it seems to be the most common convention in Swift?
___
*[`ios/MullvadVPNUITests/Pages/AccountDeletionPage.swift` line 26 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nre86393rFThz1KJtAK:-NreEGk41V5FehzagyXA:b-tyur43) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/Pages/AccountDeletionPage.swift#L26)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

How come we do a specific check only for this identifier?
</blockquote></details>

Not sure if this answers your question but `pageAccessibilityIdentifier` is the only optional used in this method, and the chaining of `app.otherElements[pageAccessibilityIdentifier].buttons[AccessibilityIdentifier.deleteButton]` instead of  just`app.otherElements[AccessibilityIdentifier.deleteButton]` is necessary because there's another button in the view hierarchy named `deleteButton` - a button that isn't visible to the user but exists in the view hiearchy. It would probably be better to make sure the accessibility identifiers are unique though!
___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 38 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NreAJIv745jeSUPROPx:-NrepYEN98fWADm-t_sX:bmrntnv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L38)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Should the test fail here instead?
</blockquote></details>

It is valid to not use any pin actually, and required for the devices used with the GitHub runner unfortunately. So that tests can run without a human manually entering the pin code every time tests run. If the device don't have any pin code this enter pin code step will be skipped and the VPN permission is still allowed as intended.
___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 81 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NreARQCBsjuc2GuApEC:-NrepBYSA3ut0CKLhvdS:b-3y62cn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L81)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: dismiss[ChangeLog...]
</blockquote></details>

Much better 👍 Renamed to `dismissChangeLogIfShown`


<!-- Sent from Reviewable.io -->

2024-02-28 08:05 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: all files reviewed, 3 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/README.md` line 27 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nre784F1ULd4gLL84QR:-NrijJeGDvNwHe3Sucqx:bq287gn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/README.md#L27)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Right, it's not very clear here. When creating a new runner in GitHub you're guided to run a setup script with a wizard asking you for labels and name of runner. A GitHub admin should give the information from the screenshot and from there the process is quite straightforward. Should it be clarified more in the README?

![image.png](https://files.reviewableusercontent.io/images/reviewable/331986/2BnTwktxCMsUbhsWHKI3mAXg/image.png)
</blockquote></details>

I think it's enough to just point out in the doc comment that these steps are on a certain page on github.
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 39 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nre7Wf731841ERxaEuW:-NrijZLj6lmZ-SVW6EjO:b-j63l9q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L39)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

I wasn't sure whether there's a convention for the codebase. Seen both. Here it's a bit awkward because `MullvadAPIWrapper` wraps `MullvadApi` 😄 Personally I like upper-casing abbreviations since Apple do it and it seems to be the most common convention in Swift?
</blockquote></details>

Let's keep it as it is now then 👍
___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 38 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NreAJIv745jeSUPROPx:-Nrijr8E9M5c7uCV5Fpx:b2nhlkw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L38)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

It is valid to not use any pin actually, and required for the devices used with the GitHub runner unfortunately. So that tests can run without a human manually entering the pin code every time tests run. If the device don't have any pin code this enter pin code step will be skipped and the VPN permission is still allowed as intended.
</blockquote></details>

Ok!


<!-- Sent from Reviewable.io -->

2024-02-28 08:48 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: all files reviewed, 9 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 13 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nrinjxa76BMhaCgvOaE:-Nrinjxa76BMhaCgvOaF:bp7szi9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L13)):*
> ```Swift
> 
> enum MullvadAPIError: Error {
>     case incorrectConfigurationFormat
> ```

it seems we are using this case for `inavlidURL`.isn't it a better name?
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 14 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nrin99B6Wh1660JaX0o:-Nrin99B6Wh1660JaX0p:b-dy7aog) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L14)):*
> ```Swift
> enum MullvadAPIError: Error {
>     case incorrectConfigurationFormat
>     case requestError
> ```

the error case is not well-defined which shows when it happens.
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 35 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NrioD5LAT39gZRnwVnw:-NrioD5LAT39gZRnwVnx:b-l4xlqd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L35)):*
> ```Swift
>     }
> 
>     public static func getAPIHostname() -> String {
> ```

do really we need to have another function that returns the static variable?
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 60 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NriqJFnE0uJ9ChGvbur:-NriqJFnE0uJ9ChGvbus:b-kuhcea) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L60)):*
> ```Swift
> 
>         for _ in 0 ..< 44 {
>             bytes.append(UInt8.random(in: 0 ..< 255))
> ```

you can make it shorter.



_Code snippet:_
```Swift
let bytes = (0..<44).map({_ in UInt8.random(in: UInt8.min ..< UInt8.max)})
```
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 72 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nrisaix1ga6KnpF-p-S:-Nrisaix1ga6KnpF-p-T:b-i8puny) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L72)):*
> ```Swift
>         } catch {
>             XCTFail("Failed to create account using app API")
>             return String()
> ```

cannot we use `try` & `catch`?
___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 38 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nrisscs5JLEC2R3qgLd:-Nrisscs5JLEC2R3qgLe:b-n0jfam) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L38)):*
> ```Swift
>         }
> 
>         if iOSDevicePinCode.isEmpty == false {
> ```

nit : 



_Code snippet:_
```Swift
if !iOSDevicePinCode.isEmpty {}
```


<!-- Sent from Reviewable.io -->

2024-03-01 12:47 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: 30 of 33 files reviewed, 9 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPNUITests/README.md` line 27 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nre784F1ULd4gLL84QR:-NrkGosAENl1iJmAVwG1:b53yo48) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3d803f42e551faa825673f9832245c0bd4096f7f/ios/MullvadVPNUITests/README.md#L27)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I think it's enough to just point out in the doc comment that these steps are on a certain page on github.
</blockquote></details>

Reworded it a bit
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 13 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nrinjxa76BMhaCgvOaE:-NrkHDuo9ooAL4d2Q2sf:b3izn8d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L13)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it seems we are using this case for `inavlidURL`.isn't it a better name?
</blockquote></details>

That would point more to what went wrong. I intended to keep them generic and reusable but it's not reused for any other "incorrect configuration format error" so it makes sense to rename it to be more specific 👍 How about `invalidEndpointFormatError`? 
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 14 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nrin99B6Wh1660JaX0o:-NrkI-Tz0Owkx1kgVKuH:b-oxb4bz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L14)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

the error case is not well-defined which shows when it happens.
</blockquote></details>

`requestError` is thrown when there's a client or server-side error so it's very generic. It could be broken down more but I think it should very rarely happen and might be over-engineering to identify different types of errors?
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 35 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NrioD5LAT39gZRnwVnw:-NrkIV6T-aRxwPYPOev5:b-rbtpuo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L35)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

do really we need to have another function that returns the static variable?
</blockquote></details>

No, I made this a static method for consistency since others are. But it doesn't need to be. Changed to `static let`.
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 60 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NriqJFnE0uJ9ChGvbur:-NrkMLm22iFglcv_X-2l:bxre1jy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L60)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

you can make it shorter.
</blockquote></details>

Personally I prefer readability over shorter code and find the one-liner a bit complex. Is there any agreed upon convention on shorter vs longer code among the group? Google's style guide don't mention it what I could find.
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 72 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nrisaix1ga6KnpF-p-S:-NrkJg9D6WdUFNShXMu0:bq1ov87) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L72)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

cannot we use `try` & `catch`?
</blockquote></details>

Avoiding catching errors in the test case layer to keep it easy to read so that it reads like a description of what the test does. The test should not attempt to recover from a failed API request. There could be error handling here instead like retries.
___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 38 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nrisscs5JLEC2R3qgLd:-NrkLsLX9qqknT1PCeHs:b6jwgjk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L38)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit :
</blockquote></details>

I usually avoid `!` for negating conditions and instead do `== false` because it's easier to read and avoid mistakes but don't have any strong opinion. If using `!` is usually used in the code base I'll follow this convention instead 👍 Have updated this line to use `!`.


<!-- Sent from Reviewable.io -->

2024-03-01 13:41 UTC, rablador approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: all files reviewed, 7 unresolved discussions (waiting on @mojganii and @niklasberglund)

___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 38 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nrisscs5JLEC2R3qgLd:-NruEcAF9cxk3TveBSqK:bjmkydg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L38)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

I usually avoid `!` for negating conditions and instead do `== false` because it's easier to read and avoid mistakes but don't have any strong opinion. If using `!` is usually used in the code base I'll follow this convention instead 👍 Have updated this line to use `!`.
</blockquote></details>

We have settled for both being ok for the time being. Although I personally like `!` more. 🙃


<!-- Sent from Reviewable.io -->

2024-03-01 14:17 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: all files reviewed, 7 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 38 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nrisscs5JLEC2R3qgLd:-NruN-Fk0TWHjQc_FhFv:b460jns) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L38)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

We have settled for both being ok for the time being. Although I personally like `!` more. 🙃
</blockquote></details>

No matter my preference I'd be happy to follow the group's preference though 😊


<!-- Sent from Reviewable.io -->

2024-03-01 15:35 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: all files reviewed, 7 unresolved discussions (waiting on @mojganii and @niklasberglund)

___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 38 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nrisscs5JLEC2R3qgLd:-NrudvB89y5DUev3VJxs:b-bhy23) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L38)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

No matter my preference I'd be happy to follow the group's preference though 😊
</blockquote></details>

It's a split opinion, so do whichever at the moment ;)


<!-- Sent from Reviewable.io -->

2024-03-05 13:21 UTC, buggmagnet requested changes
> Reviewed 23 of 33 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: all files reviewed, 9 unresolved discussions (waiting on @mojganii, @niklasberglund, and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 3109 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NsDiQxD-6mL19TX-PRR:-NsDiQxD-6mL19TX-PRS:b-da026v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5dabfa9101686aa1d0805a795ce72ebf507c0a6d/ios/MullvadVPN.xcodeproj/project.pbxproj#L3109)):*
> ```
> 				7A88DCDD2A8FABBE00D2FF0E /* RoutingTests */,
> 				58CE5E61224146200008646E /* Products */,
> 				584F991F2902CBDD001F858D /* Frameworks */,
> ```

It looks like there are too many files in this folder.

Can you delete the two files that are highlighted in the screenshot ?
![Screenshot 2024-03-05 at 14.07.40.png](https://files.reviewableusercontent.io/images/reviewable/129761703/fATSK2RWDph1-r354wIaGHc7/Screenshot%202024-03-05%20at%2014.07.40.png)
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 3110 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NsDgPzf2eugxvm031Hd:-NsDgPzf2eugxvm031He:b6lyjrv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5dabfa9101686aa1d0805a795ce72ebf507c0a6d/ios/MullvadVPN.xcodeproj/project.pbxproj#L3110)):*
> ```
> 				58CE5E61224146200008646E /* Products */,
> 				584F991F2902CBDD001F858D /* Frameworks */,
> 				85EC620B2B838B3A005AFFB5 /* Recovered References */,
> ```

We should delete this folder
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 35 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NrioD5LAT39gZRnwVnw:-NsDjEz0E41OMi-bWRD7:bsqcyk3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L35)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

No, I made this a static method for consistency since others are. But it doesn't need to be. Changed to `static let`.
</blockquote></details>

nit
@mojganii There's a good distinction between a function and a getter.
One indicates that something is read-only whilst the other might not be. 

If you don't have access to the source code, there's no way to know whether whether a variable can be written to, whereas a function hints strongly that it cannot be written to. 
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 60 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NriqJFnE0uJ9ChGvbur:-NsDjsNhByHeLU3qLEWD:bykwlnv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L60)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Personally I prefer readability over shorter code and find the one-liner a bit complex. Is there any agreed upon convention on shorter vs longer code among the group? Google's style guide don't mention it what I could find.
</blockquote></details>

Readability trumps all but correctness. 
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 72 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nrisaix1ga6KnpF-p-S:-NsDk_om3sLq2m8XOMZ_:br3aqo0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L72)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Avoiding catching errors in the test case layer to keep it easy to read so that it reads like a description of what the test does. The test should not attempt to recover from a failed API request. There could be error handling here instead like retries.
</blockquote></details>

In most cases the API should just work, since it's all locally controlled dependencies.
The UI Tests won't work without the API, so it's fine to work with the assumption that it always does the correct thing, and as written here, make the current test fail in case the API fails.  
___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 38 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nrisscs5JLEC2R3qgLd:-NsDl6BHDkC2cw9f7UR3:b133vyt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L38)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It's a split opinion, so do whichever at the moment ;)
</blockquote></details>

I need to go on a crusade here... I've been (hopelessly) trying to advocate for `condition == false` and `condition == true` as it's IMHO way easier to read than `!condition` 

Please, let's stop having discussions on this. There is no team consensus, so everyone has to accept the status quo that it's up to the developer's personal preference to write statements how they see fit.


<!-- Sent from Reviewable.io -->

2024-03-05 14:05 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: all files reviewed, 8 unresolved discussions (waiting on @mojganii and @niklasberglund)



<!-- Sent from Reviewable.io -->

2024-03-07 13:27 UTC, rablador approved these changes
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: all files reviewed, 8 unresolved discussions (waiting on @mojganii and @niklasberglund)



<!-- Sent from Reviewable.io -->

2024-03-08 10:02 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: 30 of 36 files reviewed, 8 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 3109 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NsDiQxD-6mL19TX-PRR:-NsSVhE_Ck7XnE1deleB:b-we3ymd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5dabfa9101686aa1d0805a795ce72ebf507c0a6d/ios/MullvadVPN.xcodeproj/project.pbxproj#L3109)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It looks like there are too many files in this folder.

Can you delete the two files that are highlighted in the screenshot ?
![Screenshot 2024-03-05 at 14.07.40.png](https://files.reviewableusercontent.io/images/reviewable/129761703/fATSK2RWDph1-r354wIaGHc7/Screenshot%202024-03-05%20at%2014.07.40.png)
</blockquote></details>

Deleted 👌
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 3110 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NsDgPzf2eugxvm031Hd:-NsSViwPEvuH4VdEs4KL:bcxlim0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5dabfa9101686aa1d0805a795ce72ebf507c0a6d/ios/MullvadVPN.xcodeproj/project.pbxproj#L3110)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We should delete this folder
</blockquote></details>

Have fixed the file references under it and deleted the folder


<!-- Sent from Reviewable.io -->

2024-03-11 11:47 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-:-NshKhjtE2_rmO_kdDqG:bnfp4nl)* status: 34 of 36 files reviewed, 4 unresolved discussions (waiting on @buggmagnet, @niklasberglund, and @rablador)

___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 14 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-Nrin99B6Wh1660JaX0o:-NshKB_J6pl20d2p0FA8:b-886o9q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5d5021d6bc60ef24c1bf436382e3319d36d33e46/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L14)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

`requestError` is thrown when there's a client or server-side error so it's very generic. It could be broken down more but I think it should very rarely happen and might be over-engineering to identify different types of errors?
</blockquote></details>

Fine!


<!-- Sent from Reviewable.io -->

2024-03-11 12:07 UTC, rablador approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-:-NshPJUKBTx6p_XZfUKQ:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @niklasberglund)



<!-- Sent from Reviewable.io -->

2024-03-11 12:22 UTC, buggmagnet requested changes
> Reviewed 5 of 33 files at r5, 2 of 4 files at r7, 4 of 6 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: all files reviewed, 5 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 3550 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NshRRGrBQGfCTf6yNqo:-NshRRGsE9XPIMakLKGk:b-2xpomb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa4bd9ad377ed7f632e87c3c4a29308e0df32f98/ios/MullvadVPN.xcodeproj/project.pbxproj#L3550)):*
> ```
> 			isa = PBXGroup;
> 			children = (
> 				85B267602B849ADB0098E3CD /* mullvad-api.h */,
> ```

Please move this file and the `MullvadApi.swift` file inside the `MullvadVPNUITests` folder
___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 0 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NshR_wn99QhoZcDv9Sm:-NshR_wo3sRVn1VB7tvt:b9y7i5c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa4bd9ad377ed7f632e87c3c4a29308e0df32f98/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L0)):*
This file shouldn't be deleted, please run the following command from the `ios` folder
`git checkout main -- MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/`


<!-- Sent from Reviewable.io -->

2024-03-11 13:28 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line  at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NshR_wn99QhoZcDv9Sm:-NshgK9F4Dp0TNZiOg9a:bmy8lqv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa4bd9ad377ed7f632e87c3c4a29308e0df32f98/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This file shouldn't be deleted, please run the following command from the `ios` folder
`git checkout main -- MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/`
</blockquote></details>

Again! Have restored it


<!-- Sent from Reviewable.io -->

2024-03-11 14:40 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-:-NshxFpr6WDyZ7s_RBWa:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 3550 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5855#-NshRRGrBQGfCTf6yNqo:-NshxD3XDsI5fUPZspNe:brtswzq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fa4bd9ad377ed7f632e87c3c4a29308e0df32f98/ios/MullvadVPN.xcodeproj/project.pbxproj#L3550)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

It looks like `MullvadApi.swift` already is in the `MullvadVPNUITests` folder or am I missing something :thinking: 

Maybe its a good idea to move`mullvad-api.h` but would it make sense to treat as a separate issue? Its not introduced by this PR and is part of the build step Emils set up so it might require some modifications in multiple files. If it is to be consumed by more targets in the future maybe it makes sense to keep it outside of the targets' sub folders.
</blockquote></details>

Fair enough, let's not do that here then.


<!-- Sent from Reviewable.io -->

2024-03-11 14:50 UTC, merged