Add problem report test
mullvad/mullvadvpn-app pull request #5867
Opened 2024-02-26 16:02 UTC by niklasberglund

Created test for submitting problem reports. On stagemole all problem reports are ignored and not sent to support, therefor the current implementation fails if not running against stagemole in order to avoid spamming support. Please let me know if you have feedback on this approach. Without any safeguard it would be easy to accidentally run the test against production.

This PR includes some fixes to the `MullvadVPNUITests` build configuration to make the `Staging` configuration run - before it was only set up for `Debug` configuration . `continueAfterFailure = false` was also moved from `AccountTests` to `BaseUITestCase` so that it is set for all tests, not only tests under `AccountTests`.

To test this PR run `testSendProblemReport` under `SettingsTests`. Note that you need to change to run `Staging` configuration(`Debug` is the default configuration) and `NO_TIME_ACCOUNT_NUMBER` and `HAS_TIME_ACCOUNT_NUMBER` must be set for `Staging` configuration:

```
NO_TIME_ACCOUNT_NUMBER[config=Debug] = <production-account-number-here>
NO_TIME_ACCOUNT_NUMBER[config=Staging] = <staging-account-number-here>
HAS_TIME_ACCOUNT_NUMBER[config=Debug] = <production-account-number-here>
HAS_TIME_ACCOUNT_NUMBER[config=Staging] = <staging-account-number-here>
```

2024-02-26 17:17 UTC, acb-mv approved these changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5867)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @mojganii and @rablador)



<!-- Sent from Reviewable.io -->

2024-02-27 07:45 UTC, buggmagnet requested changes
> Reviewed 8 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5867)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @acb-mv, @mojganii, @niklasberglund, and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 605 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5867#-NrdS0-x6owhnQuZOWzf:-NrdS0-x6owhnQuZOWzg:b-tk56i5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a10c877582f321122027590535d9851b42fac0e/ios/MullvadVPN.xcodeproj/project.pbxproj#L605)):*
> ```
> 		8529693A2B4F0238007EAD4C /* TermsOfServicePage.swift in Sources */ = {isa = PBXBuildFile; fileRef = 852969392B4F0238007EAD4C /* TermsOfServicePage.swift */; };
> 		8529693C2B4F0257007EAD4C /* Alert.swift in Sources */ = {isa = PBXBuildFile; fileRef = 8529693B2B4F0257007EAD4C /* Alert.swift */; };
> 		8532E6872B8CCED600ACECD1 /* ProblemReportSubmittedPage.swift in Sources */ = {isa = PBXBuildFile; fileRef = 8532E6862B8CCED600ACECD1 /* ProblemReportSubmittedPage.swift */; };
> ```

Don't forget to order files by name when you add a new file
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 7485 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5867#-NrdTRBAC3vgQbsgMvCD:-NrdTRBAC3vgQbsgMvCE:b-xrsgmw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a10c877582f321122027590535d9851b42fac0e/ios/MullvadVPN.xcodeproj/project.pbxproj#L7485)):*
> ```
> 		A93A1D062B59145C00F7796C /* Staging */ = {
> 			isa = XCBuildConfiguration;
> 			baseConfigurationReference = 852969382B4ED818007EAD4C /* UITests.xcconfig */;
> ```

Curious about these changes, was there something that was not configured properly in the xcode project file ?
___
*[`ios/MullvadVPNUITests/AccountTests.swift` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5867#-NrdWX__61YC7NgkeZc8:-NrdWX__61YC7NgkeZc9:b-jldb7u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a10c877582f321122027590535d9851b42fac0e/ios/MullvadVPNUITests/AccountTests.swift#L12)):*
> ```Swift
> 
> class AccountTests: LoggedOutUITestCase {
>     override func setUpWithError() throws {
> ```

:warning: `Unneeded Overridden Functions Violation: Remove overridden functions that don't do anything except call their super (unneeded_override)`
___
*[`ios/MullvadVPNUITests/SettingsTests.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5867#-NrdVUb8-TkZsf1hWzqa:-NrdVUb8-TkZsf1hWzqb:bzhwfc4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a10c877582f321122027590535d9851b42fac0e/ios/MullvadVPNUITests/SettingsTests.swift#L14)):*
> ```Swift
> class SettingsTests: LoggedOutUITestCase {
>     func testSendProblemReport() throws {
>         #if !MULLVAD_ENVIRONMENT_STAGING
> ```

Instead of doing this (which also leaves a permanent warning when not running the staging environmnent which is not great) 

We can do the following
```swift
#if !MULLVAD_ENVIRONMENT_STAGING
let shouldSkipTest = true
#else
let shouldSkipTest = false
#endif

try XCTSkipIf(shouldSkipTest, "This test should only run in the Staging environment")

```


<!-- Sent from Reviewable.io -->

2024-02-27 10:50 UTC, rablador approved these changes
> Reviewed 7 of 10 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5867)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @acb-mv, @buggmagnet, @mojganii, and @rablador)



<!-- Sent from Reviewable.io -->

2024-02-28 07:57 UTC, buggmagnet approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5867)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-02-28 07:58 UTC, merged