Relay selector evaluates only first location constraint when a custom list is selected
mullvad/mullvadvpn-app pull request #5874
Opened 2024-02-28 11:50 UTC by rablador

Fixes the bug by evaluating all locations before returning the result.

2024-02-29 09:51 UTC, acb-mv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5874)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadREST/Relay/RelaySelector.swift` line 157 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5874#-NroFtVZ6leiguKaSf0b:-NroFtV_1qR6K8wD3hpe:b70e8ec) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/999ca6373e66313d96a9e7040a839207e6fa15a3/ios/MullvadREST/Relay/RelaySelector.swift#L157)):*
> ```Swift
>                 return true
>             case let .only(relayConstraint):
>                 // At least one location must match the relay under test.
> ```

There's a lot of logic in this loop; wouldn't it make sense to move it to RelayLocation, perhaps a `RelayWithLocation.matches(Location)` method or similar?


<!-- Sent from Reviewable.io -->

2024-02-29 10:07 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5874)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv)

___
*[`ios/MullvadREST/Relay/RelaySelector.swift` line 157 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5874#-NroFtVZ6leiguKaSf0b:-NroKCYqC0rXnQmvQXMC:bks2uxu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/999ca6373e66313d96a9e7040a839207e6fa15a3/ios/MullvadREST/Relay/RelaySelector.swift#L157)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

There's a lot of logic in this loop; wouldn't it make sense to move it to RelayLocation, perhaps a `RelayWithLocation.matches(Location)` method or similar?
</blockquote></details>

Yeah, that's a good idea I think. I 'll look at it 👍


<!-- Sent from Reviewable.io -->

2024-02-29 10:46 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5874)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv)

___
*[`ios/MullvadREST/Relay/RelaySelector.swift` line 157 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5874#-NroFtVZ6leiguKaSf0b:-NroSma6ABpm2cIsd8T6:b-t1g1ni) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/999ca6373e66313d96a9e7040a839207e6fa15a3/ios/MullvadREST/Relay/RelaySelector.swift#L157)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Yeah, that's a good idea I think. I 'll look at it 👍
</blockquote></details>

Can you create a test case that fails with the previous version, and is fixed by the changes here ?


<!-- Sent from Reviewable.io -->

2024-02-29 11:02 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5874)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv)

___
*[`ios/MullvadREST/Relay/RelaySelector.swift` line 157 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5874#-NroFtVZ6leiguKaSf0b:-NroWEDo0AzvXCQoUsz3:b4cv6zq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/999ca6373e66313d96a9e7040a839207e6fa15a3/ios/MullvadREST/Relay/RelaySelector.swift#L157)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Can you create a test case that fails with the previous version, and is fixed by the changes here ?
</blockquote></details>

Sure thing.


<!-- Sent from Reviewable.io -->

2024-03-01 15:34 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5874)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv)

___
*[`ios/MullvadREST/Relay/RelaySelector.swift` line 157 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5874#-NroFtVZ6leiguKaSf0b:-NruWU7ZE69xTsXuWG49:b-xwlul8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/999ca6373e66313d96a9e7040a839207e6fa15a3/ios/MullvadREST/Relay/RelaySelector.swift#L157)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Sure thing.
</blockquote></details>

In order to create such a test I need to make this function internal rather than private. I can't rely on on testing `evaluate` above, since the result will be random each time.


<!-- Sent from Reviewable.io -->

2024-03-04 08:12 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5874#-:-Ns7WNIl-v7XtGydtdis:bnfp4nl)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @acb-mv)



<!-- Sent from Reviewable.io -->

2024-03-04 09:38 UTC, acb-mv reviewed
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5874)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-03-04 16:05 UTC, merged