Run shellcheck as a github workflow
mullvad/mullvadvpn-app pull request #5876
Opened 2024-02-28 13:39 UTC by hulthe

2024-02-28 15:17 UTC, hulthe commented on ci/ios/buildserver-build-ios.sh
> +TAG_PATTERN_TO_BUILD="^ios/"
https://www.shellcheck.net/wiki/SC2128

2024-02-28 15:17 UTC, hulthe commented on ci/ios/buildserver-build-ios.sh
> +        mapfile -t tags < <(run_git tag | grep "$TAG_PATTERN_TO_BUILD")
https://www.shellcheck.net/wiki/SC2207

2024-02-28 15:17 UTC, hulthe commented on ci/ios/buildserver-build-ios.sh
> +        mapfile -t tags < <(run_git tag | grep "$TAG_PATTERN_TO_BUILD")
note: only supported on bash 4.4+, but that was released in 2017 so should be fine.
also not posix compatible, but I assume that's not something we care about

2024-02-28 15:17 UTC, hulthe commented on ci/ios/run-in-vm.sh
> +ssh admin@"$(tart ip "$VM_NAME")" bash /dev/stdin < "$SCRIPT"
https://www.shellcheck.net/wiki/SC2002

2024-02-28 15:17 UTC, hulthe commented on ci/ios/run-in-vm.sh
> +ssh admin@"$(tart ip "$VM_NAME")" bash /dev/stdin < "$SCRIPT"
not sure what the comment above is about? should be looked into before merging

2024-02-28 15:17 UTC, hulthe commented on dist-assets/linux/before-remove.sh
> +if [[ "$1" =~ $is_number_re ]] && [ "$1" -gt 0 ]; then
https://www.shellcheck.net/wiki/SC2086

2024-02-28 15:17 UTC, hulthe commented on dist-assets/linux/mullvad-gui-launcher.sh
> +exec "$SCRIPT_DIR/mullvad-gui" "$SANDBOX_FLAG" "${WAYLAND_FLAGS[@]}" "$@"
https://www.shellcheck.net/wiki/SC2086

2024-02-28 15:17 UTC, hulthe commented on dist-assets/pkg-scripts/postinstall
> +exec > $LOG_DIR/postinstall.log 2>&1
https://www.shellcheck.net/wiki/SC2069
I assume this wasn't intentional

2024-02-28 15:17 UTC, hulthe commented on dist-assets/pkg-scripts/preinstall
> +exec > $LOG_DIR/preinstall.log 2>&1
https://www.shellcheck.net/wiki/SC2069
I assume this wasn't intentional

2024-02-28 15:17 UTC, hulthe commented on dist-assets/uninstall_macos.sh
> +read -r -p "Do you want to delete the Mullvad VPN settings? (y/n) "
https://www.shellcheck.net/wiki/SC2162

2024-02-28 15:17 UTC, hulthe commented on ios/build-wireguard-go.sh
> +/usr/bin/make -C "$WIREGUARD_KIT_GO_PATH" "$ACTION"
https://www.shellcheck.net/wiki/SC2086

2024-02-28 15:17 UTC, hulthe commented on test/ci-runtests.sh
> +        --account "${ACCOUNT_TOKEN:?Error: ACCOUNT_TOKEN not set}" \
https://www.shellcheck.net/wiki/SC2153

2024-02-28 15:17 UTC, hulthe commented on wireguard/libwg/build-android.sh
> +    pwd
https://www.shellcheck.net/wiki/SC2005

2024-02-28 15:17 UTC, hulthe commented on wireguard/libwg/build-android.sh
> +    chmod 777 "$(dirname "$STRIPPED_LIB_PATH")"
https://www.shellcheck.net/wiki/SC2174

2024-02-28 15:17 UTC, hulthe commented on wireguard/libwg/build-android.sh
> +    chmod 777 "$(dirname "$STRIPPED_LIB_PATH")"
note: I assume this is not what the author intended. Worth fixing?

2024-02-29 12:17 UTC, faern requested changes
Some of the scripts (most notably the iOS scripts) I don't feel like I can verify correctly. Can you please have someone in the iOS team test these changes out and verify they work as expected? I know we have previously had issuse where shellcheck recommendations break iOS scripts.

> Reviewed 7 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876#-:-Nromxo0B48Xj5VPcfQ8:btimi9s)* status: 7 of 12 files reviewed, 16 unresolved discussions (waiting on @hulthe)

___
*[`.github/workflows/shellcheck.yml` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876#-Nrohrd33WPvL1yP2MGT:-Nrohrd33WPvL1yP2MGU:b-el4mvw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/668c58e9c783b76cf223d41a8f8069aff3976eeb/.github/workflows/shellcheck.yml#L5)):*
> ```YAML
>   push:
>     branches:
>       - main
> ```

Is this needed on push? We don't run other CI jobs on push really, except a few, but they have special reasons. As long as we check all PRs, `main` should never get corrupted. I'm not saying I'm completely against this, just that it's different from the pattern we usually have. I'm open to suggested improvements.
___
*[`.github/workflows/shellcheck.yml` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876#-NrompKXB0mMTPGYmvip:-NrompKXB0mMTPGYmviq:b-gvzj9l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/668c58e9c783b76cf223d41a8f8069aff3976eeb/.github/workflows/shellcheck.yml#L8)):*
> ```YAML
> 
> name: "Trigger: Push action"
> permissions: {}
> ```

Are these two lines needed? we don't really specify them for other jobs. I think this will work fine without? :thinking: 
___
*[`.github/workflows/shellcheck.yml` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876#-NroigOd7FckwfNvBLLR:-NroigOd7FckwfNvBLLS:b-5oru94) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/668c58e9c783b76cf223d41a8f8069aff3976eeb/.github/workflows/shellcheck.yml#L17)):*
> ```YAML
>       - uses: actions/checkout@v3
>       - name: Run ShellCheck
>         uses: ludeeus/action-shellcheck@master
> ```

Would it make sense to pin this to a release of the action instead of `master`? Mostly to stop sudden breakage. The CI fails often enough without depending on moving targets :joy: Seems like `2.0.0` is the latest release.
___
*[`.github/workflows/shellcheck.yml` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876#-Nroj5_B3xFybziwf_8Y:-Nroj5_B3xFybziwf_8Z:b-l10nd4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/668c58e9c783b76cf223d41a8f8069aff3976eeb/.github/workflows/shellcheck.yml#L20)):*
> ```YAML
>         with:
>           ignore_names: >-
>             gradlew
> ```

We really only have a single `gradlew` file that we want to ignore. So it feels like we can specify this more exactly with:
```
ignore_paths: >-
  android/gradlew
```
I feel like this more exactly express what we want to ignore.


<!-- Sent from Reviewable.io -->

2024-03-01 07:23 UTC, faern reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876)* status: 8 of 12 files reviewed, 11 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-03-05 07:59 UTC, buggmagnet requested changes
> Reviewed 10 of 12 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876)* status: all files reviewed, 14 unresolved discussions (waiting on @hulthe)

___
*[`ci/ios/buildserver-build-ios.sh` line 96 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876#-NsCXJL75CKLF9674Giw:-NsCXJL75CKLF9674Gix:b-3bm7fz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d84ea9d86a6545615203e85ead131c8d9761c3b/ci/ios/buildserver-build-ios.sh#L96)):*
> ```Shell
>         run_git fetch --prune --tags 2> /dev/null || continue
>         local tags
>         mapfile -t tags < <(run_git tag | grep "$TAG_PATTERN_TO_BUILD")
> ```

```
bash-3.2$ mapfile 
bash: mapfile: command not found
```

It looks like this builtin does not exists on bash for macOS. I think we should revert this change.
___
*[`ci/ios/run-in-vm.sh` line 27 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876#-NsCXs5LEZwYHwuCPvji:-NsCXs5LEZwYHwuCPvjj:byfe3a6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d84ea9d86a6545615203e85ead131c8d9761c3b/ci/ios/run-in-vm.sh#L27)):*
> ```Shell
> # apparently, there's a difference between piping into zsh like this and doing
> # a <(echo $SCRIPT).
> ssh admin@"$(tart ip "$VM_NAME")" bash /dev/stdin < "$SCRIPT"
> ```

We can remove the above comment as it will be invalid after this change.
I just tested this, and that seems to work, so this change should be fine. 
___
*[`ios/build-wireguard-go.sh` line 41 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876#-NsCa7mpD-KAt6adXSa0:-NsCa7mpD-KAt6adXSa1:bks8e26) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d84ea9d86a6545615203e85ead131c8d9761c3b/ios/build-wireguard-go.sh#L41)):*
> ```Shell
> 
> # Run make
> /usr/bin/make -C "$WIREGUARD_KIT_GO_PATH" "$ACTION"
> ```

This is intentionally done without quotes, this script is ran from within Xcode, and it won't always have an argument. 

If we add quotes here, we will pass an empty string as an argument which will make our build fail, please revert this change.


<!-- Sent from Reviewable.io -->

2024-03-05 09:58 UTC, hulthe reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876)* status: 9 of 12 files reviewed, 14 unresolved discussions (waiting on @buggmagnet)

___
*[`ci/ios/buildserver-build-ios.sh` line 96 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876#-NsCXJL75CKLF9674Giw:-NsD2Cyc1-C5IVqv4SZr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d84ea9d86a6545615203e85ead131c8d9761c3b/ci/ios/buildserver-build-ios.sh#L96)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

```
bash-3.2$ mapfile 
bash: mapfile: command not found
```

It looks like this builtin does not exists on bash for macOS. I think we should revert this change.
</blockquote></details>

Done.
___
*[`ci/ios/run-in-vm.sh` line 27 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876#-NsCXs5LEZwYHwuCPvji:-NsD2EQV1ElrTbaLhbEc:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d84ea9d86a6545615203e85ead131c8d9761c3b/ci/ios/run-in-vm.sh#L27)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We can remove the above comment as it will be invalid after this change.
I just tested this, and that seems to work, so this change should be fine.
</blockquote></details>

Done.
___
*[`ios/build-wireguard-go.sh` line 41 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876#-NsCa7mpD-KAt6adXSa0:-NsD2Ej06cFfzXBLJlT_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d84ea9d86a6545615203e85ead131c8d9761c3b/ios/build-wireguard-go.sh#L41)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This is intentionally done without quotes, this script is ran from within Xcode, and it won't always have an argument. 

If we add quotes here, we will pass an empty string as an argument which will make our build fail, please revert this change.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-05 10:00 UTC, buggmagnet approved these changes
My review pertains only to iOS specific changes, but <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
Thank you for doing this!

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876#-:-NsD2aSxEKZ_bQMcUt1D:b4w8dwd)* status: all files reviewed, 11 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-03-05 10:10 UTC, faern approved these changes
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876)* status: all files reviewed, 11 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-03-05 10:38 UTC, merged