Make the 'Clear all overrides' button only active when there are overrides
mullvad/mullvadvpn-app pull request #5912
Opened 2024-03-07 08:55 UTC by rablador

Currently, the button is always active. According to the specs, we should make sure it is not active if there are no overrides being enabled.

2024-03-07 08:57 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5912)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift` line 90 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5912#-NsN7CRW54O2-69EiNm0:-NsN7CRW54O2-69EiNm1:b-43565v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ee5a8039463ff19f974fc079e61f5f64cd7fcc0d/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift#L90)):*
> ```Swift
>     }
> 
>     private func resetToDefaultStatus(delay: Duration = .zero) {
> ```

Added semi-related improvement here as well. Currently there can be weird timings for the status messages depending on user behavior (and patience).


<!-- Sent from Reviewable.io -->

2024-03-07 13:19 UTC, buggmagnet requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5912)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift` line 94 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5912#-NsO2Wl45IWadbhVDauI:-NsO2Wl45IWadbhVDauJ:b-xxoyjt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c2b4952160d74542cd829cae1f7032c7fa54b5d/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift#L94)):*
> ```Swift
> 
>         let statusWorkItem = DispatchWorkItem { [weak self] in
>             guard let self else { return }
> ```

Calling `cancel` on dispatchWorkItems doesn't actually cancel the execution if the item has already scheduled.
We should check here as well  that the item itself is not cancelled
```swift
guard let self, self.statusWorkItem?.isCancelled == false else { return }
``` 


<!-- Sent from Reviewable.io -->

2024-03-07 13:28 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5912)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift` line 94 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5912#-NsO2Wl45IWadbhVDauI:-NsO5Ik67SH--WmoiEGs:b-l7rjqi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c2b4952160d74542cd829cae1f7032c7fa54b5d/ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift#L94)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Calling `cancel` on dispatchWorkItems doesn't actually cancel the execution if the item has already scheduled.
We should check here as well  that the item itself is not cancelled
```swift
guard let self, self.statusWorkItem?.isCancelled == false else { return }
```
</blockquote></details>

Aha! Didn't know that. My intention was to cancel it altogether.


<!-- Sent from Reviewable.io -->

2024-03-11 07:57 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5912#-:-NsgVxLR2uEfWp8FH1dp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-03-11 08:05 UTC, merged