Run `cargo deny` in the test framework
mullvad/mullvadvpn-app pull request #5942
Opened 2024-03-12 10:05 UTC by MarkusPettersson98

This PR adds a new CI job for the test framework CI - run `cargo deny` to guard against supply chain vulnerabilities.
This is one step towards bringing the CI for the test framework on par with main workspace CI.

## Open questions
~~In some sense it would be nice to have a separate `deny.toml` in the `test` workspace, but on the other hand it would be hard to keep them in sync with everything that should be shared across them. For now, I put the `test` workspace specific `RUSTSEC` advisories to allow temporarily in the main `deny.toml` :shrug:~~

Answer: Duplicate `deny.toml` in the `test` workspace and modify as needed :scroll: :pen: 

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5942)

2024-03-12 10:27 UTC, MarkusPettersson98 commented
Right, `openssl` is banned from the main workspace. We probably need two separate `deny.toml` files then :facepalm:

2024-03-13 15:12 UTC, faern requested changes
Unfortunately that we need to duplicate so much deny-info. But let's merge this so we get the CI up to speed at least. Hopefully we can simplify it at a later point in time. <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5942#-:-NssMfHU2r_sVqGmvPUc:b141hzu)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`.github/workflows/testframework-rust-supply-chain.yml` line 7 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5942#-NssMLbBB0XpLmjnkclV:-NssMLbBB0XpLmjnkclW:b-k3qfc1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fbdcee377a133c45ab92247b0c01779d8bfe9226/.github/workflows/testframework-rust-supply-chain.yml#L7)):*
> ```YAML
>     paths:
>       - .github/workflows/testframework-rust-supply-chain.yml
>       - deny.toml
> ```

This is now the wrong `deny.toml`


<!-- Sent from Reviewable.io -->

2024-03-13 15:20 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5942)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`.github/workflows/testframework-rust-supply-chain.yml` line 7 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5942#-NssMLbBB0XpLmjnkclV:-NssOQdN7boH0nVGMD8i:b-cbuvjv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fbdcee377a133c45ab92247b0c01779d8bfe9226/.github/workflows/testframework-rust-supply-chain.yml#L7)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This is now the wrong `deny.toml`
</blockquote></details>

Well spotted, fixed!


<!-- Sent from Reviewable.io -->

2024-03-13 15:42 UTC, faern approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5942)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-03-13 15:47 UTC, merged