Enable building features in crates on iOS
mullvad/mullvadvpn-app pull request #5944
Opened 2024-03-12 10:46 UTC by buggmagnet

This PR will enable us building rust crate features by passing a second argument to the `build-rust-library.sh` script. 

For example
`build-rust-library.sh mullvad-api api-override`

If we need to build more than one feature flag, we can pass in a single argument, all the features separated by spaces
`build-rust-library.sh mullvad-api "featureA featureB featureC"`

2024-03-12 11:02 UTC, niklasberglund requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5944)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/build-rust-library.sh` line 5 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5944#-NsmI6TkCqv0fYujeIKy:-NsmI6TkCqv0fYujeIKz:b1wtl00) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/683c807a92e911a615063738866c32a11a20cc5d/ios/build-rust-library.sh#L5)):*
> ```Shell
> set -euvx
> 
> if [ "$#" -gt 2 ]
> ```

Nit: the previous condition also guarded against 0 arguments. This condition could for example be `[ "$#" -gt 2 ] || [ "$#" -eq 0 ]` to also guard against 0 arguments
___
*[`ios/build-rust-library.sh` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5944#-NsmItPf6r-f5rGgG9jN:-NsmItPf6r-f5rGgG9jO:byaiwmu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/683c807a92e911a615063738866c32a11a20cc5d/ios/build-rust-library.sh#L8)):*
> If we need to build more than one feature flag, we can pass in a single argument, all the features separated by spaces  
`build-rust-library.sh mullvad-api "featureA featureB featureC"`

Found this usage information very helpful, should it be added here as well? Without this info and by looking at the help text here I would assume the syntax `build-rust-library.sh mullvad-api featureA featureB featureC` is valid but it isn't.


<!-- Sent from Reviewable.io -->

2024-03-12 12:57 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5944)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`ios/build-rust-library.sh` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5944#-NsmItPf6r-f5rGgG9jN:-NsmipgX0RXU2HGdmSqI:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/683c807a92e911a615063738866c32a11a20cc5d/ios/build-rust-library.sh#L8)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

> If we need to build more than one feature flag, we can pass in a single argument, all the features separated by spaces  
`build-rust-library.sh mullvad-api "featureA featureB featureC"`

Found this usage information very helpful, should it be added here as well? Without this info and by looking at the help text here I would assume the syntax `build-rust-library.sh mullvad-api featureA featureB featureC` is valid but it isn't.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-12 15:38 UTC, niklasberglund approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5944#-:-NsnJ9fY9pFhtFdfPMF2:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-03-13 12:14 UTC, rablador reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5944)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @niklasberglund)

___
*[`ios/build-rust-library.sh` line 16 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5944#-Nsrj0oP9hCwMjDmP98y:-Nsrj0oQ3BmsCpDdnSG9:b-qxtbwe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c29a0acacdb0e6fbfafdcd7c99911aab943ca711/ios/build-rust-library.sh#L16)):*
> ```Shell
> 
> # Enable cargo features by passing feature names to this script, i.e. build-rust-library.sh mullvad-api api-override
> # If more than one feature flag needs to be enabled, pass in a single argument all the features flags separated by spaces
> ```

nit: "argument _of_ all"?


<!-- Sent from Reviewable.io -->

2024-03-14 07:36 UTC, merged