Adjust UI to allow adding elements to a custom list ios 490
mullvad/mullvadvpn-app pull request #5968
Opened 2024-03-18 12:09 UTC by mojganii

This pull request introduces a feature that allows users to add/edit locations within a custom list  from  all available locations. However, there are certain limitations in place to ensure the integrity of the process. Specifically, users cannot add elements to the list that are already encompassed within the list above. Additionally, if a user selects all children directly from the list, it does not imply that the parent was explicitly chosen. 

<pre>
<table >

  <tbody>
    <tr>
      <td><img src = "https://github.com/mullvad/mullvadvpn-app/assets/129863230/fba5f868-e12c-4bfd-b246-e9c687e39cd7" width ="200" height="500"></td>
    </tr>
  </tbody>
</table>
</pre>

2024-03-19 13:23 UTC, rablador requested changes
> Reviewed 19 of 19 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968)* status: all files reviewed, 15 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationCell.swift` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtH1Ghe9HX_ejZ823Fu:-NtH1Ghe9HX_ejZ823Fv:b-fk6r8p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationCell.swift#L1)):*
> ```Swift
> //
> ```

Could this class perhaps have inherited from LocationCell to reuse most of the base functionality there?
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtH7obP8HykmpzO_Qib:-NtH7obP8HykmpzO_Qic:b-sblhkc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L36)):*
> ```Swift
>     ) {
>         self.tableView = tableView
>         self.nodes = allLocations.map {
> ```

I think it'd be better if the nodes passed into the class are already copied and "flattened" rather than having a non-related state.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtHApHoDJUZenmeUJyy:-NtHApHoDJUZenmeUJyz:bgj2s96) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L74)):*
> ```Swift
>             locationsList.append(viewModel)
> 
>             // Determine the node should be expanded.
> ```

Nit: Determine "if"
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtKpXKG0LrNVudkg6AM:-NtKpXKG0LrNVudkg6AN:b1k4v43) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L75)):*
> ```Swift
> 
>             // Determine the node should be expanded.
>             guard customListLocationNode.children.contains(where: { node.allChildren.contains($0) }) else {
> ```

`contains` in `contains` can be hard to grasp. Also, this code is present in more places in this file. Perhaps we could make an aptly named function of it?
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 91 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtKfqTA699N02SntBt3:-NtKfqTA699N02SntBt4:b-4g3jp1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L91)):*
> ```Swift
>         }
>         updateDataSnapshot(with: [locationsList], completion: {
>             // Scroll to the first selected location
> ```

I'm not sure if this is the best behavior. Since we don't have just one particular item of interest, I think it feels odd (and a little random) to jump to a selected item at all. I might as well want to add items from a node at the top, but with the scrolling I need to go up there manually again.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 198 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtL_lPq12flP3p_0T3-:-NtL_lPq12flP3p_0T30:b-uoy9rx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L198)):*
> ```Swift
>         var locationList = snapshot().itemIdentifiers
>         let item = locationList[index]
>         let isSelected = !item.isSelected
> ```

Nit: I think the `!` should be applied when used below instead. That way `isSelected = item.isSelected` translates 1:1.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 216 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLbFL8C8GCVn1PPwMt:-NtLbFL8C8GCVn1PPwMu:by5641g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L216)):*
> ```Swift
> 
> extension AddLocationsDataSource {
>     private func scroll(to item: AddLocationCellViewModel, animated: Bool) {
> ```

This function is almost identical to a function in `LocationDataSource`. The only this that differs is the view model, but perhaps we can replace that will a protocol?
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 242 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLceqs7_euH-9pelbh:-NtLceqs7_euH-9pelbi:bl6jmc3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L242)):*
> ```Swift
> 
> fileprivate extension [AddLocationCellViewModel] {
>     mutating func addSubNodes(from item: AddLocationCellViewModel, at indexPath: IndexPath) {
> ```

Just like above, this function only differs from its `LocationDataSource` counterpart in terms of view model (and section, but that can be handled through a param or something I think).
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 255 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLcaKo4v7NozKzM6py:-NtLcaKo4v7NozKzM6pz:bko2irc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L255)):*
> ```Swift
>     }
> 
>     mutating func recursivelyRemoveSubNodes(from node: LocationNode) {
> ```

This function IS identical to a function in `LocationDataSource`. Can we reuse somehow?
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 267 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLedEa1xGL3dr6icYx:-NtLedEa1xGL3dr6icYy:bbwypxi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L267)):*
> ```Swift
> 
> fileprivate extension [AddLocationCellViewModel] {
>     mutating func deselectAncestors(from node: LocationNode?) {
> ```

Could `node.forEachAncestor` be used here instead (to reuse logic already covered by tests)?
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 277 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLepGr9r0XRcZMkWQ6:-NtLepGr9r0XRcZMkWQ7:b-g5i90) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L277)):*
> ```Swift
>     }
> 
>     mutating func toggleSelectionSubNodes(from node: LocationNode, isSelected: Bool) {
> ```

Could `node.forEachDescendant` be used here instead (to reuse logic already covered by tests)?
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 303 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLjYrG2VuDLow3NUem:-NtLjYrG2VuDLow3NUen:b-uyn7kc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L303)):*
> ```Swift
>         removeSubNodes(node: selectedLocation)
>     }
> ```

The functions below all use recursion for traversing the node tree. Could we make use of `.forEachDescendant` and `.forEachAncestor` here?
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsViewController.swift` line 23 at r1](https://reviewable.io/re [...]

2024-03-19 14:28 UTC, buggmagnet requested changes
> Reviewed 9 of 19 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968)* status: all files reviewed, 19 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddCustomListCoordinator.swift` line 87 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLqyz60pTmlprz7plt:-NtLqyz73UvzFBcr8WAK:by49krb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/03ef6a827cc7da565cf477650076ec2fd1c4cbe0/ios/MullvadVPN/Coordinators/CustomLists/AddCustomListCoordinator.swift#L87)):*
> ```Swift
>         )
> 
>         coordinator.didFinish = { customList in
> ```

I think there is a cyclic reference between `AddLocationsCoordinator` and `AddCustomListCoordinator` here.

`AddCustomListCoordinator` adds `AddLocationsCoordinator` as a child.
But also `AddLocationsCoordinator` captures `self` (`AddCustomListCoordinator` in this case) in its `didFinish` closure (which it retains) )
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddCustomListCoordinator.swift` line 94 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLu5PJASe-Ma8I0wjG:-NtLu5PJASe-Ma8I0wjH:b8or949) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/03ef6a827cc7da565cf477650076ec2fd1c4cbe0/ios/MullvadVPN/Coordinators/CustomLists/AddCustomListCoordinator.swift#L94)):*
> ```Swift
>                 tableSections: self.subject.value.tableSections
>             ))
>             self.removeFromParent()
> ```

This gets called everytime we select a different location when editing location, 
Correct me if I'm wrong, but I think this is not the intended behaviour ?
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationCell.swift` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtH1Ghe9HX_ejZ823Fu:-NtLxhMeAYhTdLIChDzP:b-qrmi0k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationCell.swift#L1)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Could this class perhaps have inherited from LocationCell to reuse most of the base functionality there?
</blockquote></details>

Heavily agree !
___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 119 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtM53gT6gi_Ti4rF7SW:-NtM53gT6gi_Ti4rF7SX:bw10pzd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/03ef6a827cc7da565cf477650076ec2fd1c4cbe0/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L119)):*
> ```Swift
>         )
> 
>         dataSourceConfiguration?.didSelectItem = { item in
> ```

[weak self] to avoid a retain cycle here 
___
*[`ios/MullvadVPN/Coordinators/CustomLists/EditCustomListCoordinator.swift` line 84 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtM6CDAA2iX9GhP0L7w:-NtM6CDAA2iX9GhP0L7x:b-jl6ykp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/03ef6a827cc7da565cf477650076ec2fd1c4cbe0/ios/MullvadVPN/Coordinators/CustomLists/EditCustomListCoordinator.swift#L84)):*
> ```Swift
>         )
> 
>         coordinator.didFinish = { customList in
> ```

[weak self] to avoid a retain cycle here


<!-- Sent from Reviewable.io -->

2024-03-21 10:19 UTC, buggmagnet requested changes
> Reviewed 2 of 19 files at r1, 12 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968)* status: 20 of 22 files reviewed, 21 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/Coordinators/LocationCoordinator.swift` line 42 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtVDs965SKYsq-Ss6wk:-NtVDs965SKYsq-Ss6wl:b-d8jloc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/992a1f1c14e30c940eb81e9599ee0afc50076396/ios/MullvadVPN/Coordinators/LocationCoordinator.swift#L42)):*
> ```Swift
>     }
> 
>     deinit {
> ```

Let's remove this 
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsCoordinator.swift` line 60 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtVUlaR9dXPfZTC2o0D:-NtVUlaR9dXPfZTC2o0E:b-271j2u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/992a1f1c14e30c940eb81e9599ee0afc50076396/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsCoordinator.swift#L60)):*
> ```Swift
>     }
> 
>     func didOnBack() {
> ```

`didOnBack` doesn't read well, how about `onBack` ? Or `didBack` if you want to keep the `did` convention.


<!-- Sent from Reviewable.io -->

2024-03-21 21:11 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968)* status: 20 of 22 files reviewed, 19 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Coordinators/LocationCoordinator.swift` line 42 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtVDs965SKYsq-Ss6wk:-NtXoIHj35psDkTJn-U0:bz1i509) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/992a1f1c14e30c940eb81e9599ee0afc50076396/ios/MullvadVPN/Coordinators/LocationCoordinator.swift#L42)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's remove this
</blockquote></details>

It was underdevelopment.Sure
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddCustomListCoordinator.swift` line 87 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLqyz60pTmlprz7plt:-NtQ9U_UENnhqlmJ4xBS:bgqtdj7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/03ef6a827cc7da565cf477650076ec2fd1c4cbe0/ios/MullvadVPN/Coordinators/CustomLists/AddCustomListCoordinator.swift#L87)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I think there is a cyclic reference between `AddLocationsCoordinator` and `AddCustomListCoordinator` here.

`AddCustomListCoordinator` adds `AddLocationsCoordinator` as a child.
But also `AddLocationsCoordinator` captures `self` (`AddCustomListCoordinator` in this case) in its `didFinish` closure (which it retains) )
</blockquote></details>

there were some retain cycle in different part of the Custom list which were fixed. 
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddCustomListCoordinator.swift` line 94 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLu5PJASe-Ma8I0wjG:-NtQKjLx-b3HD1dNpOFj:blbmm62) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/03ef6a827cc7da565cf477650076ec2fd1c4cbe0/ios/MullvadVPN/Coordinators/CustomLists/AddCustomListCoordinator.swift#L94)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This gets called everytime we select a different location when editing location, 
Correct me if I'm wrong, but I think this is not the intended behaviour ?
</blockquote></details>

indeed this code should be revoked when the controller is popped .
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationCell.swift` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtH1Ghe9HX_ejZ823Fu:-NtSGjTJ1Qniw4QfsH2M:bbcgt3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationCell.swift#L1)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Heavily agree !
</blockquote></details>

let me disagree with this.it's the ui for adding location to custom list and the other one in using in select location, however cells have similar appearance but the fictionality is different. to be honest I don't see any advantage to do this.

I tried to implement them with different configuration through `UIContentConfiguration` but It brought much more than complexity for no good reason
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsCoordinator.swift` line 60 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtVUlaR9dXPfZTC2o0D:-NtXp0v73pqxoz6S4KO2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/992a1f1c14e30c940eb81e9599ee0afc50076396/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsCoordinator.swift#L60)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

`didOnBack` doesn't read well, how about `onBack` ? Or `didBack` if you want to keep the `did` convention.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 36 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtH7obP8HykmpzO_Qib:-NtXpFv2-OezQPahrPfP:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L36)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I think it'd be better if the nodes passed into the class are already copied and "flattened" rather than having a non-related state.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 74 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtHApHoDJUZenmeUJyy:-NtSITpo0nV3xsAOTRKn:bb7f2mf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L74)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Determine "if"
</blockquote></details>

done
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 91 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtKfqTA699N02SntBt3:-NtSIrAw1lESVx3V1jsz:b-ns8pkl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L91)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I'm not sure if this is the best behavior. Since we don't have just one particular item of interest, I think it feels odd (and a little random) to jump to a selected item at all. I might as well want to add items from a node at the top, but with the scrolling I need to go up there manually again.
</blockquote></details>

I don't have a strong opinion on this matter, especially considering that we have the freedom to make changes to iOS for the initial iteration.I removed that
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 242 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLceqs7_euH-9pelbh:-NtXqCc02YUlDZ5KYeI4:b971k7k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L242)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Just like above, this function only differs from its `LocationDataSource` counterpart in terms of view model (and section, but that can be handled through a param or something I think).
</blockquote></details>

I tried to take care of reusability as much as I can. I have a draft version for that work.I'm pressed the time let's do that any refactoring when I'm back or I would be happy if you would like to do that.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 255 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLcaKo4v7NozKzM6py:-NtVDaCVE2ytWzyYSbnb:b-k29pe4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L255)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This function IS identical to a function in `LocationDataSource`. Can we reuse somehow?
</blockquote></details>

they have different view model.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 267 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLedEa1xGL3dr6icYx:-NtV4d5U2NRKa3eAFblR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L267)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Could `node.forEachAncestor` be used here instead (to reuse logic already covered by tests)?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/Ad [...]

2024-03-22 09:22 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968)* status: 10 of 23 files reviewed, 19 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtKpXKG0LrNVudkg6AM:-Nt_Jcpn6DbwCTsoUVR-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L75)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

`contains` in `contains` can be hard to grasp. Also, this code is present in more places in this file. Perhaps we could make an aptly named function of it?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 198 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtL_lPq12flP3p_0T3-:-Nt_Jlb--c1XHcdAPk8o:b-2o0qk9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L198)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: I think the `!` should be applied when used below instead. That way `isSelected = item.isSelected` translates 1:1.
</blockquote></details>

it contains the fresh toggled value after `selection` or 'deselection'.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 216 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLbFL8C8GCVn1PPwMt:-Nt_JqFo1ZKXJw5fqQB0:b1v50hg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L216)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This function is almost identical to a function in `LocationDataSource`. The only this that differs is the view model, but perhaps we can replace that will a protocol?
</blockquote></details>

it's tidying them up or reusing UI elements, doesn't offer any benefits. Is that correct? If so, could you provide more context or clarify your statement further?


<!-- Sent from Reviewable.io -->

2024-03-25 14:59 UTC, rablador requested changes
> Reviewed 7 of 14 files at r4, 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968)* status: all files reviewed, 12 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @mojganii)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsViewController.swift` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLkY2I06OsOXOjk2gM:-Ntq521NAV_VkyrhTVnS:b-rk5fuw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsViewController.swift#L23)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I would prefer keep them separated as much as I can. in my opinion they are different views with diffrent functionality. tiding them to gather specially when it comes to appearance doesn't appeal to me
</blockquote></details>

@buggmagnet or @acb-mv What are your takes on this?
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsViewController.swift` line 84 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-Ntq5QKu4vwHstfOARCV:-Ntq5QKu4vwHstfOARCW:b-ctmdrt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eaeac9067e9eddb8533bae8700cf784155a71934/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsViewController.swift#L84)):*
> ```Swift
>         dataSource = AddLocationsDataSource(
>             tableView: tableView,
>             allLocations: nodes.copy(),
> ```

Nit: "copyAndFlatten"?


<!-- Sent from Reviewable.io -->

2024-03-28 09:25 UTC, rablador requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968)* status: 12 of 29 files reviewed, 12 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @mojganii)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 216 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLbFL8C8GCVn1PPwMt:-Nu3N2mi-unAAn2xGSbH:b-a1p77j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L216)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it's tidying them up or reusing UI elements, doesn't offer any benefits. Is that correct? If so, could you provide more context or clarify your statement further?
</blockquote></details>

Did some shuffling and refactoring to combine as much as possible.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 242 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLceqs7_euH-9pelbh:-Nu3N8Sl29TSQQaTXXtm:b-a1p77j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L242)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I tried to take care of reusability as much as I can. I have a draft version for that work.I'm pressed the time let's do that any refactoring when I'm back or I would be happy if you would like to do that.
</blockquote></details>

Did some shuffling and refactoring to combine as much as possible.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift` line 255 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtLcaKo4v7NozKzM6py:-Nu3N9E40YXp7xsPHdAZ:b-a1p77j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift#L255)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

they have different view model.
</blockquote></details>

Did some shuffling and refactoring to combine as much as possible.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/AddLocationCell.swift` line 1 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NtH1Ghe9HX_ejZ823Fu:-Nu3NCzd2h_AxwaILUgz:b-a1p77j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ac7f83b1d571080b8bb130bcec637caa52f33c14/ios/MullvadVPN/Coordinators/CustomLists/AddLocationCell.swift#L1)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

let me disagree with this.it's the ui for adding location to custom list and the other one in using in select location, however cells have similar appearance but the fictionality is different. to be honest I don't see any advantage to do this.

I tried to implement them with different configuration through `UIContentConfiguration` but It brought much more than complexity for no good reason
</blockquote></details>

Did some shuffling and refactoring to combine as much as possible.


<!-- Sent from Reviewable.io -->

2024-04-02 05:59 UTC, buggmagnet requested changes
[CustomFail.mov](https://files.reviewableusercontent.io/images/reviewable/129761703/ueOzwn74qsr8T9O2_ZpEyqbP/CustomFail.mov)

Those changes are really good !
However, now we are automatically connecting whenever we edit a custom list even if it's not a user selection, or if another relay was already selected.

> Reviewed 5 of 13 files at r5, 9 of 17 files at r6, 3 of 6 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-:-NuSNjDP7UsTzD6okYir:b-7shcan)* status: all files reviewed, 10 unresolved discussions (waiting on @acb-mv and @mojganii)

___
*[`ios/MullvadVPN/Coordinators/LocationCoordinator.swift` line 19 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NuSH5z78oU0EOWuqGqz:-NuSH5z78oU0EOWuqGr-:b-8pa02u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8da82120e59170b8dde0bbbe5be7ff5472cfe1c0/ios/MullvadVPN/Coordinators/LocationCoordinator.swift#L19)):*
> ```Swift
>     private let relayCacheTracker: RelayCacheTracker
>     private var cachedRelays: CachedRelays?
>     private var customListRepository: CustomListRepositoryProtocol
> ```

This should be declared as `let` now 


<!-- Sent from Reviewable.io -->

2024-04-02 11:34 UTC, rablador reviewed
We run `tunnelManager.startTunnel()` when saving the lists, but changing to `tunnelManager.reconnectTunnel()` will to the trick.

> Reviewed 9 of 17 files at r6, 3 of 6 files at r7, 7 of 7 files at r8, 1 of 1 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-:-NuT_8uKC7hdDbDAaASv:b-z8eorl)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Coordinators/LocationCoordinator.swift` line 19 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-NuSH5z78oU0EOWuqGqz:-NuT_Pou-7MM5rKOjNQe:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8da82120e59170b8dde0bbbe5be7ff5472cfe1c0/ios/MullvadVPN/Coordinators/LocationCoordinator.swift#L19)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This should be declared as `let` now
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-02 11:37 UTC, rablador reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-04-02 14:22 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r9, 3 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968#-:-NuUB2C_5qCPQXG2V9w0:bnfp4nl)* status: all files reviewed, 3 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-04-03 09:09 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968)* status: all files reviewed, 3 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-04-03 14:35 UTC, buggmagnet approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-05 07:34 UTC, buggmagnet approved these changes
> Reviewed 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5968)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-05 07:48 UTC, merged