Add vulnerability scanning with OSV scanner
mullvad/mullvadvpn-app pull request #6001
Opened 2024-03-21 12:32 UTC by faern

Adding (yet another) scanner for known vulnerabilities in our dependency tree(s). This one actually checks some places we have not looked at before.

Draft until I have played around with it and figured out more exactly how we want to use it.

2024-07-02 08:39 UTC, albin-mullvad reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001)* status: all files reviewed, 6 unresolved discussions (waiting on @faern)

___
*[`osv-scanner.toml` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0mXj4Y--0bTqFQ94W2:-O0mXj4Y--0bTqFQ94W3:bvlfusm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e501306e54029c9f92ba6419ac89e1bde77362fc/osv-scanner.toml#L10)):*
> ```TOML
> # * The default should be to ignore a vulnerability for three months.
> # * A vulnerability can be ignored for up to a year at most (Use extremely sparsely).
> # * If anything above three months is used, write a short comment about why this ignore is longer.
> ```

I would prefer keeping the reason for longer ignores in the reason block since:
* For longer reasons multiple lines might be necessary.
* The `reason` information might be relevant in generated reports and/or on the GH Security tab/page. I'm not sure how it works, but might be worth considering.

I don't have a super strong opinon though, so I'm also fine going with the suggested approach.
___
*[`.github/workflows/osv-scanner.yml` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0mQhiR3d-HdWNQ70z6:-O0mQhiR3d-HdWNQ70z7:b-shx53r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e501306e54029c9f92ba6419ac89e1bde77362fc/.github/workflows/osv-scanner.yml#L2)):*
> ```YAML
> ---
> # Copyright 2024 Google LLC
> ```

Just to double check, do we need to include this copyright for such a trivial configuration file?
___
*[`.github/workflows/osv-scanner.yml` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0mR49eB4kd_JBXGImr:-O0mR49eB4kd_JBXGIms:b6eydho) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e501306e54029c9f92ba6419ac89e1bde77362fc/.github/workflows/osv-scanner.yml#L19)):*
> ```YAML
> 
> on:
>   pull_request:
> ```

Just a thought here: we could limit this to same paths as the signature lockfile protection, right? Even though this workflow is quite lite it would be nice to limit the amount of workflows triggered per PR since we already have a ton
___
*[`.github/workflows/osv-scanner.yml` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0mS-7F9X4rRB1wjrGm:-O0mS-7F9X4rRB1wjrGn:b-80z19o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e501306e54029c9f92ba6419ac89e1bde77362fc/.github/workflows/osv-scanner.yml#L33)):*
> ```YAML
>   # Only need to read contents
>   contents: read
>   # Needed to read the workflow from another repository(???)
> ```

TODO?



_Code quote:_
```YAML
???
```
___
*[`gui/scripts/osv-scanner.toml` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0mYTR4DXuBfegWUAF2:-O0mYTR4DXuBfegWUAF3:b-jaw914) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e501306e54029c9f92ba6419ac89e1bde77362fc/gui/scripts/osv-scanner.toml#L17)):*
> ```TOML
> # libwebp bundled with Pillow is vulnerable to CVE-2023-5129
> [[IgnoredVulns]]
> id = "GHSA-56pw-mpj4-fxww"
> ```

Should this be `CVE-2023-5129`? :thinking: 



_Code quote:_
```TOML
GHSA-56pw-mpj4-fxww
```
___
*[`test/osv-scanner.toml` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0ma0HP5dp8igQUSLXj:-O0ma0HP5dp8igQUSLXk:b97armu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e501306e54029c9f92ba6419ac89e1bde77362fc/test/osv-scanner.toml#L0)):*
Just a reminder to add the following:

```
# See repository root `osv-scanner.toml` for instructions and rules for this file.
```


<!-- Sent from Reviewable.io -->

2024-07-02 13:07 UTC, albin-mullvad reviewed
> Reviewed 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001)* status: all files reviewed, 5 unresolved discussions (waiting on @faern)

___
*[`-- commits` line 32 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0nYKSg7jdpgXJzkXh_):*
Feel free to squash these with the prior commit (`Ignore android vulnerabilities reported by osv-scanner`) :slightly_smiling_face: 



_Code quote:_
```
- 6d3d928 by Albin (albin-mullvad):
  Move android osv-scanner config to gradle dir

- 684004a by Albin (albin-mullvad):
  Try fix name reference
```
___
*[`test/osv-scanner.toml` line 1 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0nXoyh59r7zbngpaKf:-O0nXoyh59r7zbngpaKg:b-64qxly) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c5c8ebe574eed2bd294d234555574c373b0a8083/test/osv-scanner.toml#L1)):*
> ```TOML
> # See repository root `osv-scanner.toml` for instructions and rules for this file.
> ```

Reviewable seem to complain about the file ending


<!-- Sent from Reviewable.io -->

2024-07-02 13:25 UTC, faern reviewed
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001)* status: 6 of 12 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad)

___
*[`gui/scripts/osv-scanner.toml` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0mYTR4DXuBfegWUAF2:-O0n7g2K95qk1XsweuuF:bdg84zs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e501306e54029c9f92ba6419ac89e1bde77362fc/gui/scripts/osv-scanner.toml#L17)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should this be `CVE-2023-5129`? :thinking:
</blockquote></details>

It does not list that as an alias on osv.dev. That CVE is part of the references, but it's not the only reference. If I change it to the CVE then `osv-scanner` does not understand the ignore and warn about it as it's not an alias.
Not all `ID`s need to be CVEs, it's just recommended to try to use the original ID when available.
___
*[`test/osv-scanner.toml` line  at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0ma0HP5dp8igQUSLXj:-O0n9O5I35dfz6YIz5ZN:b-896fja) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e501306e54029c9f92ba6419ac89e1bde77362fc/test/osv-scanner.toml#L)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Just a reminder to add the following:

```
# See repository root `osv-scanner.toml` for instructions and rules for this file.
```
</blockquote></details>

Done!
___
*[`test/osv-scanner.toml` line 1 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0nXoyh59r7zbngpaKf:-O0nbTyE5lzCSzOVkCBu:b-a4wcvi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c5c8ebe574eed2bd294d234555574c373b0a8083/test/osv-scanner.toml#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Reviewable seem to complain about the file ending
</blockquote></details>

Oops. Done.
___
*[`.github/workflows/osv-scanner.yml` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0mQhiR3d-HdWNQ70z6:-O0n2v_G9Cku-k8xuUhL:b6lg0oy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e501306e54029c9f92ba6419ac89e1bde77362fc/.github/workflows/osv-scanner.yml#L2)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Just to double check, do we need to include this copyright for such a trivial configuration file?
</blockquote></details>

I now replaced all of this with their recommended setup from https://google.github.io/osv-scanner/github-action/#scan-on-pull-request instead. I hope this works nicer and has less boilerplate.
___
*[`.github/workflows/osv-scanner.yml` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0mR49eB4kd_JBXGImr:-O0nARFa42hXwZGtUAlm:b-a558rx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e501306e54029c9f92ba6419ac89e1bde77362fc/.github/workflows/osv-scanner.yml#L19)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Just a thought here: we could limit this to same paths as the signature lockfile protection, right? Even though this workflow is quite lite it would be nice to limit the amount of workflows triggered per PR since we already have a ton
</blockquote></details>

Is there another way than duplicating the relevant subset of that list? That makes it slightly error prone towards missing new/moved/renamed lockfiles.
___
*[`android/osv-scanner.toml` line 66 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0n3b4fBN0JJTxHjxwJ:-O0n3b4fBN0JJTxHjxwK:bjchntk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8dd56279833023964687bc0896b69c8fdfb8f5ec/android/osv-scanner.toml#L66)):*
> ```TOML
> 
> [[IgnoredVulns]]
> name = "org.bouncycastle:bcpkix-jdk18on"
> ```

This has a `name` but no `id`. I have not seen this before. Is there no ID to assign it or how come this is so different? :thinking: 


<!-- Sent from Reviewable.io -->

2024-07-02 14:08 UTC, albin-mullvad reviewed
> Reviewed 5 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001)* status: all files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`.github/workflows/verify-locked-down-signatures.yml` line 28 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0nbHyM1VKZxS-4ru3J:-O0nbHyM1VKZxS-4ru3K:b-dusvtq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3b33844d8f28121b1d0131125c7e19c66535e326/.github/workflows/verify-locked-down-signatures.yml#L28)):*
> ```YAML
>       - building/android-container-image.txt
>       - building/sigstore/**
>       - '**/osv-scanner.toml'
> ```

I'm not sure the ignore path is needed here since no other path should include `osv-scanner.toml` files? :thinking: But I guess it doesn't hurt
___
*[`gui/scripts/osv-scanner.toml` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0mYTR4DXuBfegWUAF2:-O0neuXp3CNOzrCJQvnx:b-n55f24) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e501306e54029c9f92ba6419ac89e1bde77362fc/gui/scripts/osv-scanner.toml#L17)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It does not list that as an alias on osv.dev. That CVE is part of the references, but it's not the only reference. If I change it to the CVE then `osv-scanner` does not understand the ignore and warn about it as it's not an alias.
Not all `ID`s need to be CVEs, it's just recommended to try to use the original ID when available.
</blockquote></details>

Alright :thumbsup: 
___
*[`.github/workflows/osv-scanner.yml` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0mQhiR3d-HdWNQ70z6:-O0neFFI6_yHXmskhNdm:b4c9lyr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e501306e54029c9f92ba6419ac89e1bde77362fc/.github/workflows/osv-scanner.yml#L2)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I now replaced all of this with their recommended setup from https://google.github.io/osv-scanner/github-action/#scan-on-pull-request instead. I hope this works nicer and has less boilerplate.
</blockquote></details>

:thumbsup: 
___
*[`.github/workflows/osv-scanner.yml` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0mR49eB4kd_JBXGImr:-O0neyai0nc548wqR91j:b-d6wtvm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e501306e54029c9f92ba6419ac89e1bde77362fc/.github/workflows/osv-scanner.yml#L19)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is there another way than duplicating the relevant subset of that list? That makes it slightly error prone towards missing new/moved/renamed lockfiles.
</blockquote></details>

Yeah, I guess that might not be possible since we didn't use that in the signature verification workflow :thinking: I guess we can skip it for now
___
*[`android/osv-scanner.toml` line 66 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0n3b4fBN0JJTxHjxwJ:-O0nh1Ge-PFIh-Cs-2wo:b-7u5ypb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8dd56279833023964687bc0896b69c8fdfb8f5ec/android/osv-scanner.toml#L66)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This has a `name` but no `id`. I have not seen this before. Is there no ID to assign it or how come this is so different? :thinking:
</blockquote></details>

There were tons of vulnerabilities for this crypto library that we also don't rely on in the production app (since all crypto is done in rust and go) so I therefore just ignore all for its `name` until we've investigated those further during the coming month


<!-- Sent from Reviewable.io -->

2024-07-03 13:09 UTC, albin-mullvad approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`osv-scanner.toml` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0mXj4Y--0bTqFQ94W2:-O0sgjyi8t57pFcXTSV1:b-9uyu53) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e501306e54029c9f92ba6419ac89e1bde77362fc/osv-scanner.toml#L10)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

> For longer reasons multiple lines might be necessary.

I don't see why you could not put multi line *comments* about the same thing? I don't understand this argument.

> The `reason` information might be relevant in generated reports and/or on the GH Security tab/page. I'm not sure how it works, but might be worth considering.

Yes, the structured `reason` is nice that it can be included in reports I guess. But this does not talk about the "reason" for the expiry time. Confusing with two things named "reason". I don't understand how this is an argument for including the expiry time here.

I see the `reason` field as *why can we safely ignore this*, and that usually has nothing to do with time. It's more of "We can ignore this because we don't call that function" or something like this. The time aspect is more of "After time X we need to re-evaluate whether or not we call into the bad function".

I don't have a super strong stance here neither. But it just feels like the reason is not time sensitive, and when we bump an expiry time usually the reason a CVE can be ignored does not change, but the argument for the new expiry time might.
</blockquote></details>

Alright, let's got with the current approach and revisit the topic in case it doesn't work
___
*[`.github/workflows/verify-locked-down-signatures.yml` line 28 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0nbHyM1VKZxS-4ru3J:-O0sgQ5J5X6Kpf_MN1e8:b-m9s09g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3b33844d8f28121b1d0131125c7e19c66535e326/.github/workflows/verify-locked-down-signatures.yml#L28)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This entry makes the osv-scanner files *included*. I wanted changes to these files to require signatures, since they are affecting the security of the supply chain. They should also be changed rather infrequently.

But sadly that did not work. The parsing of this list in the bash script was not smart enough :( So I'll remove it for now, maybe we can fix it later, it's not critical.
</blockquote></details>

Ah, sorry, my mistake! :see_no_evil: 


<!-- Sent from Reviewable.io -->

2024-07-03 13:25 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001)* status: 11 of 12 files reviewed, 1 unresolved discussion

___
*[`osv-scanner.toml` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0mXj4Y--0bTqFQ94W2:-O0sknyR0qNbhcPftcml:b-4yu8rt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e501306e54029c9f92ba6419ac89e1bde77362fc/osv-scanner.toml#L10)):*
FYI: One place the `reason` is used is when running from the CLI. Then it will print something like:

> CVE-2023-44271 and 3 aliases have been filtered out because: Only used internally, on trusted input. This tool is also scheduled for removal completely, so not worth trying to upgrade


<!-- Sent from Reviewable.io -->

2024-07-03 14:01 UTC, albin-mullvad reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-07-04 08:07 UTC, faern commented
This PR is now more or less ready for final review. The things missing are:

* Some entries in `gui/osv-scanner.toml` have inadequate `reason`s and have not been proven to be solvable by a package upgrade yet. Awaiting input from @raksooo 
* `rexml` in `ci/ios/upload-vm/Gemfile.lock` is still a problem. Awaiting an upgrade of this package from @buggmagnet

2024-07-04 08:39 UTC, albin-mullvad reviewed
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @faern)



<!-- Sent from Reviewable.io -->

2024-07-04 14:30 UTC, raksooo requested changes
> Reviewed 1 of 4 files at r1, 3 of 4 files at r4, 3 of 5 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 2 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`gui/osv-scanner.toml` line 14 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0yFto3Ben-e2TKI7_H:-O0yFto3Ben-e2TKI7_I:b-ygmdue) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/252e381d673e07f7ab398c47a2a3150711b1e7c0/gui/osv-scanner.toml#L14)):*
> ```TOML
> id = "CVE-2020-7608" # GHSA-p9pc-299p-vxgp
> ignoreUntil = 2024-09-05
> reason = ""
> ```

This package is used to parse commands run by either us or trusted libraries.
___
*[`gui/osv-scanner.toml` line 26 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0yFCt9DfPKAIvDr1s0:-O0yFCt9DfPKAIvDr1s1:b-wfvq1y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/252e381d673e07f7ab398c47a2a3150711b1e7c0/gui/osv-scanner.toml#L26)):*
> ```TOML
> id = "CVE-2024-4068" # GHSA-grv7-fg5c-xmjg
> ignoreUntil = 2024-09-05
> reason = ""
> ```

reason:
```
This package is only used to match paths from either us or trusted libraries.
```


<!-- Sent from Reviewable.io -->

2024-07-09 05:29 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @raksooo)

___
*[`gui/osv-scanner.toml` line 14 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0yFto3Ben-e2TKI7_H:-O1Kw7Mx2i2_QIqW2c2X:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/252e381d673e07f7ab398c47a2a3150711b1e7c0/gui/osv-scanner.toml#L14)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

This package is used to parse commands run by either us or trusted libraries.
</blockquote></details>

Done.
___
*[`gui/osv-scanner.toml` line 26 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O0yFCt9DfPKAIvDr1s0:-O1KwQ-aAXDMd5AX8MiQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/252e381d673e07f7ab398c47a2a3150711b1e7c0/gui/osv-scanner.toml#L26)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

reason:
```
This package is only used to match paths from either us or trusted libraries.
```
</blockquote></details>

Done.
___
*[`android/gradle/osv-scanner.toml` line 74 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001#-O1KxjZz-F2zj6pX2DTW:-O1KxjZz-F2zj6pX2DTX:btts93) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c6b0dc3a7821834fd9af8edf3ab67261a2845db3/android/gradle/osv-scanner.toml#L74)):*
> ```TOML
> ecosystem = "Maven"
> ignore = true
> effectiveUntil = 2024-08-02
> ```

Wow. Accidentally missed another one again! Unless they fix this in `osv-scanner` itself we must almost look into other ways of sanitizing these config files for errors that make us ignore things forever :see_no_evil: https://github.com/google/osv-scanner/issues/1098


<!-- Sent from Reviewable.io -->

2024-07-09 05:31 UTC, faern reviewed
> Reviewed 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @raksooo)



<!-- Sent from Reviewable.io -->

2024-07-09 05:56 UTC, merged