Fix a race condition bug involving timers and async tasks
mullvad/mullvadvpn-app pull request #6045
Opened 2024-04-02 08:13 UTC by buggmagnet

This PR fixes a subtle bug where a `DispatchSourceTimer` is used alongside swift async code in an unsafe way.

2024-04-02 09:02 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCore/Actor/Task+Duration.swift` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045#-NuT1kG692vt9QlN8YFL:-NuT1kG692vt9QlN8YFM:b-kqtwnr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/34925be2b9112bed1d8ef4f94ad88bb3d80e89f5/ios/PacketTunnelCore/Actor/Task%2BDuration.swift#L53)):*
> ```Swift
>                 var hasResumed = false
>                 timer.setEventHandler {
>                     hasResumed = true
> ```

Is it never possible for this event handler to be invoked after the the continuation has already been cancelled?


<!-- Sent from Reviewable.io -->

2024-04-02 10:08 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ios/PacketTunnelCore/Actor/Task+Duration.swift` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045#-NuT1kG692vt9QlN8YFL:-NuTGqk-56FygDg39AjE:bdzr8fk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/34925be2b9112bed1d8ef4f94ad88bb3d80e89f5/ios/PacketTunnelCore/Actor/Task%2BDuration.swift#L53)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Is it never possible for this event handler to be invoked after the the continuation has already been cancelled?
</blockquote></details>

The default repeating interval is `.never` so the timer won't fire its event handler more than once unless explicitly specified.


<!-- Sent from Reviewable.io -->

2024-04-02 10:09 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ios/PacketTunnelCore/Actor/Task+Duration.swift` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045#-NuT1kG692vt9QlN8YFL:-NuTHAbw1qHpSgeBoQtG:bthsx6b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/34925be2b9112bed1d8ef4f94ad88bb3d80e89f5/ios/PacketTunnelCore/Actor/Task%2BDuration.swift#L53)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

The default repeating interval is `.never` so the timer won't fire its event handler more than once unless explicitly specified.
</blockquote></details>

If the continuation is cancelled before the timer fires, then it gets cancelled and its event handler shouldn't be scheduled anymore


<!-- Sent from Reviewable.io -->

2024-04-02 12:04 UTC, rablador requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

___
*[`ios/PacketTunnelCoreTests/TaskSleepTests.swift` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045#-NuTgRZr9dbn2ZVxdtkG:-NuTgRZr9dbn2ZVxdtkH:b-eurkta) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/34925be2b9112bed1d8ef4f94ad88bb3d80e89f5/ios/PacketTunnelCoreTests/TaskSleepTests.swift#L35)):*
> ```Swift
>             var task = recoveryTask()
>             try await Task.sleep(duration: .milliseconds(10))
>             task.doAnythingToSilenceAWarning()
> ```

What does this do?


<!-- Sent from Reviewable.io -->

2024-04-02 15:15 UTC, pinkisemils reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2024-04-02 15:15 UTC, pinkisemils reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2024-04-03 07:31 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnelCore/Actor/Task+Duration.swift` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045#-NuT1kG692vt9QlN8YFL:-NuUN9JVAESb86cbJEpN:b-cmnw4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/34925be2b9112bed1d8ef4f94ad88bb3d80e89f5/ios/PacketTunnelCore/Actor/Task%2BDuration.swift#L53)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

If the continuation is cancelled before the timer fires, then it gets cancelled and its event handler shouldn't be scheduled anymore
</blockquote></details>

And the event handler and cancel handler are guaranteed to never be executed concurrently?


<!-- Sent from Reviewable.io -->

2024-04-03 07:40 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/PacketTunnelCore/Actor/Task+Duration.swift` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045#-NuT1kG692vt9QlN8YFL:-NuXtiK62CWTKhogTogd:b-e5ymo2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/34925be2b9112bed1d8ef4f94ad88bb3d80e89f5/ios/PacketTunnelCore/Actor/Task%2BDuration.swift#L53)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

And the event handler and cancel handler are guaranteed to never be executed concurrently?
</blockquote></details>

[The docs](https://developer.apple.com/documentation/dispatch/dispatchsourceprotocol/1780989-setcancelhandler) answer my question.


<!-- Sent from Reviewable.io -->

2024-04-03 07:50 UTC, pinkisemils approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2024-04-03 09:05 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-03 14:41 UTC, pinkisemils approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-04 11:22 UTC, pinkisemils approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-04 11:33 UTC, merged