Lint against single use lifetimes
mullvad/mullvadvpn-app pull request #6051
Opened 2024-04-02 11:27 UTC by faern

Removes superfluous lifetime definitions. Simplifying the code. Here is the docs for this lint: https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#single-use-lifetimes

Since we obviously had a pretty large number of these, I think the lint can help us keep code simpler. The only potential red flag I see is the lint docs saying "Also, there are some known false positives". I did not stumble over any false positives (that I noticed) when doing this small refactoring. If it turns out to be too troublesome we can disable the lint again. Or add `#[allow(single_use_lifetimes)]` to the places where it does not work as intended.

2024-04-02 12:08 UTC, MarkusPettersson98 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6051#-:-NuThIfFE4JWN-s1IyWJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-02 13:05 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6051)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @MarkusPettersson98)

___
*[`talpid-core/src/dns/windows/tcpip.rs` line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6051#-NuTtvSj2XlC2S_2C3Zp:-NuTtvSj2XlC2S_2C3Zq:b-eyzy3v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8055f26560e63c74120b999f4132c21e1066e170/talpid-core/src/dns/windows/tcpip.rs#L113)):*
> ```XML
>     guid: &str,
>     service: &str,
>     nameservers: impl Iterator<Item = &IpAddr>,
> ```

This is probably a false positive of this lint. I could not solve it. Since `impl Trait` requires named lifetimes, but that lifetime becomes a single use lifetime, and the lint will trigger.. But since `IpAddr` is a `Copy` type, the more idiomatic thing to do would be to iterate over them by value. So I decided to solve the problem like this instead.

If we in the future hit the same issue with a non-copy type we can just ignore the lint on a case by case basis with `#[allow(single_use_lifetimes)]`


<!-- Sent from Reviewable.io -->

2024-04-02 13:52 UTC, MarkusPettersson98 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6051#-:-NuU4NDC390cB7scgPhE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`talpid-core/src/dns/windows/tcpip.rs` line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6051#-NuTtvSj2XlC2S_2C3Zp:-NuU46Nz8BryOUON7PBm:bug3vu5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8055f26560e63c74120b999f4132c21e1066e170/talpid-core/src/dns/windows/tcpip.rs#L113)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This is probably a false positive of this lint. I could not solve it. Since `impl Trait` requires named lifetimes, but that lifetime becomes a single use lifetime, and the lint will trigger.. But since `IpAddr` is a `Copy` type, the more idiomatic thing to do would be to iterate over them by value. So I decided to solve the problem like this instead.

If we in the future hit the same issue with a non-copy type we can just ignore the lint on a case by case basis with `#[allow(single_use_lifetimes)]`
</blockquote></details>

I think this is a reasonable take :shipit:


<!-- Sent from Reviewable.io -->

2024-04-02 14:18 UTC, Serock3 approved these changes
The changes made here seem to make the code more readable, so I am in favor

2024-04-02 14:18 UTC, Serock3 commented on talpid-core/src/dns/windows/tcpip.rs
> +        servers.iter().copied().filter(|addr| addr.is_ipv4()),
Super tiny nit:
```suggestion
        servers.iter().filter(|addr| addr.is_ipv4()).copied(),
```

2024-04-02 14:18 UTC, Serock3 commented on talpid-core/src/dns/windows/tcpip.rs
> +        servers.iter().copied().filter(|addr| addr.is_ipv6()),
Same here
```suggestion
        servers.iter().filter(|addr| addr.is_ipv6()).copied(),
```

2024-04-02 14:19 UTC, Serock3 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6051#-:-NuUAVIO4rsFxHGJUGXn:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`talpid-core/src/dns/windows/tcpip.rs` line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6051#-NuTtvSj2XlC2S_2C3Zp:-NuUAWmf2gkAowXx41UY:b-cstnkg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8055f26560e63c74120b999f4132c21e1066e170/talpid-core/src/dns/windows/tcpip.rs#L113)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I think this is a reasonable take :shipit:
</blockquote></details>

I agree


<!-- Sent from Reviewable.io -->

2024-04-02 16:30 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6051)* status: all files reviewed, 2 unresolved discussions (waiting on @Serock3)

___
*[`talpid-core/src/dns/windows/tcpip.rs` line 96 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6051#gh-1547975878:-NuUcXuBBW5WiQLWeCkC:b-vq67vj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da24e37dcd621a2b11241a1aa672045ae53d84a8/talpid-core/src/dns/windows/tcpip.rs#L96)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Super tiny nit:
```suggestion
        servers.iter().filter(|addr| addr.is_ipv4()).copied(),
```
</blockquote></details>

Why is this better? I suppose you mean because then we don't need to copy the items that don't match the filter? But these types are super tiny, and the program need to read their memory anyway to compute `is_ipv4`, so I'm sure the iterator chain will dereference the memory of all items not matching the filter anyway.

`Copy` in general is usually for small simple types, so copying them around is usually not a noticeable cost. I would very much understand the reasoning if it was `.cloned()` we were talking about.

I can change the code, because I don't have a strong opinion. I just want to know what your rationale is here.


<!-- Sent from Reviewable.io -->

2024-04-03 09:42 UTC, Serock3 requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6051)* status: all files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`talpid-core/src/dns/windows/tcpip.rs` line 96 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6051#gh-1547975878:-NuYJVjJBypIMVuD3mDt:b-2ope7b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/da24e37dcd621a2b11241a1aa672045ae53d84a8/talpid-core/src/dns/windows/tcpip.rs#L96)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why is this better? I suppose you mean because then we don't need to copy the items that don't match the filter? But these types are super tiny, and the program need to read their memory anyway to compute `is_ipv4`, so I'm sure the iterator chain will dereference the memory of all items not matching the filter anyway.

`Copy` in general is usually for small simple types, so copying them around is usually not a noticeable cost. I would very much understand the reasoning if it was `.cloned()` we were talking about.

I can change the code, because I don't have a strong opinion. I just want to know what your rationale is here.
</blockquote></details>

My rationale is that I thought it said`.cloned()` :slightly_smiling_face:, if it's a `Copy` type then it doesn't really matter. Putting the filter first looks a bit more natural to me but that's just taste I guess.


<!-- Sent from Reviewable.io -->

2024-04-03 09:50 UTC, Serock3 approved these changes
> Reviewed 12 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6051)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-03 10:58 UTC, merged