Avoid rendering bitmaps above 100MB
mullvad/mullvadvpn-app pull request #6071
Opened 2024-04-04 13:45 UTC by Rawa

Also add a out of memory check for even larger app icons.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6071)

2024-04-04 14:17 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6071#-:-NudT9DH7qRE9KDi02k4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-04 14:43 UTC, Pururun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6071#-:-NudZ0pMDHMuwEdOPwWg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-05 07:13 UTC, albin-mullvad reviewed
@Rawa please update the changelog as well

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6071#-:-Nuh5jtTEhMiPB9Zk1of:b-ri30cs)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-05 07:40 UTC, Rawa reviewed
Updated :heavy_check_mark: 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6071#-:-NuhBn5Q9UVvVfTdHEaG:b-ewwp4e)* status: 3 of 9 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-05 07:46 UTC, albin-mullvad requested changes
The git history looks a bit strange with unrelated things :thinking: Please have a look at that 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6071#-:-NuhD1dF6YARP-64Z6kA:bq6qp6n)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`CHANGELOG.md` line 56 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6071#-NuhCuQ5Ajqseepfh_TC:-NuhCuQ5Ajqseepfh_TD:b5c6371) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9814ada8d471bd4f56e15eeb82017f1f5f6b5774/CHANGELOG.md#L56)):*
> ```Markdown
> 
> #### Android
> ```

Skip this empty line


<!-- Sent from Reviewable.io -->

2024-04-05 13:20 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6071#-:-NuiPdPP7mWY9DT45Bcn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-05 13:43 UTC, merged