Intercept back button when leaving an unsaved custom list ios 584
mullvad/mullvadvpn-app pull request #6079
Opened 2024-04-07 20:38 UTC by rablador

Due to the complexity of changes that can be applied to a custom list, it's best to have the users confirm their changes with a deliberate save action.

Thus, when  a user is clicking to go back from editing a custom list and the list has not been saved yet, the user should be prompted if they want to discard their changes or to go back to editing.

We also need to take menu navigation (long press on back button) into consideration by enforcing the same behaviour when eg. the user tries to navigate directly from add locations view to the list of custom lists.

2024-04-07 21:13 UTC, rablador reviewed
Clarifications:
I opted to go with Combine and a subject to keep track of changes made to the custom list being added/edited. This constant tracking is necessary becuase the user can either pop the last view controller from the navigation controller by simply pressing back, OR pop to a specific view controller from anywhere by long pressing back. Passing custom list objects around and trying to account for this unpredictable behavior seemed less ideal.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-:-NuuNptE21AsTNCPOvfz:bmw9axd)* status: 0 of 12 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-08 12:14 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Containers/Navigation/CustomNavigationController.swift` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-Nux8T9w4afqbDnkf-UU:-Nux8T9w4afqbDnkf-UV:btl5fa4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f64945411314811340af8808e75d7a3b8a0b263/ios/MullvadVPN/Containers/Navigation/CustomNavigationController.swift#L12)):*
> ```Swift
> 
> /// Custom navigation controller that applies the custom appearance to itself.
> class CustomNavigationController: InterceptibleNavigationController {
> ```

Is there any reason to use `InterceptibleNavigationController` solely during editing mode in a custom list, rather than inheriting `CustomNavigationController` from `InterceptibleNavigationController`?



_Code snippet (i):_
```Swift
class InterceptibleNavigationController: CustomNavigationController {
    var shouldPopViewController: ((UIViewController) -> Bool)?
    var shouldPopToViewController: ((UIViewController) -> Bool)?

    // Called when popping the last view controller, eg. by pressing a nacvigation bar back button.
    override func popViewController(animated: Bool) -> UIViewController? {
        guard let viewController = viewControllers.last else { return nil }

        if shouldPopViewController?(viewController) == true {
            return super.popViewController(animated: animated)
        } else {
            return nil
        }
    }

    // Called when popping to a specific view controller, eg. by long pressing a nacvigation bar
    // back button (revealing a navigation menu) and selecting a destination view controller.
    override func popToViewController(_ viewController: UIViewController, animated: Bool) -> [UIViewController]? {
        if shouldPopToViewController?(viewController) == true {
            return super.popToViewController(viewController, animated: animated)
        } else {
            return nil
        }
    }
}
```



_Code snippet (ii):_
```Swift
 private func showAddCustomList(nodes: [LocationNode]) {
        let coordinator = AddCustomListCoordinator(
            navigationController: CustomNavigationController(),
            interactor: CustomListInteractor(
                repository: customListRepository
            ),
            nodes: nodes
        )

        coordinator.didFinish = { [weak self] addCustomListCoordinator in
            addCustomListCoordinator.dismiss(animated: true)
            self?.locationViewController?.refreshCustomLists()
        }

        coordinator.start()
        presentChild(coordinator, animated: true)
    }

    private func showEditCustomLists(nodes: [LocationNode]) {
        let coordinator = ListCustomListCoordinator(
            navigationController: InterceptibleNavigationController(),
            interactor: CustomListInteractor(repository: customListRepository),
            tunnelManager: tunnelManager,
            nodes: nodes
        )

        coordinator.didFinish = { [weak self] listCustomListCoordinator in
            listCustomListCoordinator.dismiss(animated: true)
            self?.locationViewController?.refreshCustomLists()
        }

        coordinator.start()
        presentChild(coordinator, animated: true)

        coordinator.presentedViewController.presentationController?.delegate = self
    }
```
___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-NuxFVIL1wXKp7ma-rJC:-NuxFVIL1wXKp7ma-rJD:bs3g91) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f64945411314811340af8808e75d7a3b8a0b263/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L30)):*
> ```Swift
>     private var validationErrors: Set<CustomListFieldValidationError> = []
> 
>     private var customListHasUnsavedChanges: Bool {
> ```

we can make it shorter.



_Code snippet:_
```Swift
    private var customListHasUnsavedChanges: Bool {
        return interactor.fetchAll().first(where: { $0.id == subject.value.id }) != subject.value.customList
    }
```
___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 109 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-NuxYFkxDlSnV8KZywK0:-NuxYFkxDlSnV8KZywK1:bane7h7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f64945411314811340af8808e75d7a3b8a0b263/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L109)):*
> ```Swift
> 
>     private func interceptNavigation(_ navigationController: InterceptibleNavigationController) {
>         navigationController.shouldPopViewController = { [weak self] viewController in
> ```

When I took these steps at the custom list the `SelectLocation` doesn't refresh:
1- update the locations of a custom list and save it
3- the location list didn't get updated at `Select location` view
___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 260 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-NuxbjSzCRhnUChsm88V:-NuxbjSzCRhnUChsm88W:b-v15n9r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f64945411314811340af8808e75d7a3b8a0b263/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L260)):*
> ```Swift
>                     handler: {
>                         // Reset subject/view model to no longer having unsaved changes.
>                         if let list = self.interactor.fetchAll().first(where: { $0.id == self.subject.value.id }) {
> ```

nit : use `flatMap` seems much more sensiable.

 



_Code snippet:_
```Swift
     // Reset subject/view model to no longer having unsaved changes.
                        self.interactor.fetchAll().first(where: { $0.id == self.subject.value.id }).flatMap({
                      
                                self.subject.value.update(with: $0)
                        })
```


<!-- Sent from Reviewable.io -->

2024-04-08 14:27 UTC, acb-mv requested changes
> Reviewed 4 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079)* status: 4 of 12 files reviewed, 6 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Classes/InterceptibleNavigationController.swift` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-Nuy0Xv_9hGipclE3KwW:-Nuy0Xva8NAqcLJ_caJY:bmyoxjp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f64945411314811340af8808e75d7a3b8a0b263/ios/MullvadVPN/Classes/InterceptibleNavigationController.swift#L19)):*
> ```Swift
>         guard let viewController = viewControllers.last else { return nil }
> 
>         if shouldPopViewController?(viewController) == true {
> ```

Firstly, the `== true` is redundant, and secondly, if `shouldPopViewController` is `nil`, this will be regarded as `false`. Did you by any chance mean `if shouldPopViewController?(viewController) ?? true`? 
___
*[`ios/MullvadVPN/Classes/InterceptibleNavigationController.swift` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-Nuy0tuX-ZbsnjZChYMX:-Nuy0tuYEPoO3kF-0-AS:b-r67kjo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f64945411314811340af8808e75d7a3b8a0b263/ios/MullvadVPN/Classes/InterceptibleNavigationController.swift#L29)):*
> ```Swift
>     // back button (revealing a navigation menu) and selecting a destination view controller.
>     override func popToViewController(_ viewController: UIViewController, animated: Bool) -> [UIViewController]? {
>         if shouldPopToViewController?(viewController) == true {
> ```

See the comment for `popViewController`, in particular about what to do if the callbacks are `nil`.  My instincts would suggest that if the instantiator neglected to provide one of these callbacks, they'd want it to be assumed to be `true`, giving unmodified behaviour.


<!-- Sent from Reviewable.io -->

2024-04-09 07:16 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079)* status: 4 of 12 files reviewed, 6 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @mojganii)

___
*[`ios/MullvadVPN/Classes/InterceptibleNavigationController.swift` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-Nuy0Xv_9hGipclE3KwW:-Nv0da516bJhHO1zwufy:b-5mkbif) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f64945411314811340af8808e75d7a3b8a0b263/ios/MullvadVPN/Classes/InterceptibleNavigationController.swift#L19)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Firstly, the `== true` is redundant, and secondly, if `shouldPopViewController` is `nil`, this will be regarded as `false`. Did you by any chance mean `if shouldPopViewController?(viewController) ?? true`?
</blockquote></details>

`if shouldPopViewController?(viewController) {` triggers a complaint from the compiler since an optional (in this case `Bool?`) cannot be used as boolean. By doing the above we can fall back on `false` if `shouldPopViewController` is `nil` as you mentioned, or `true` if it's not and indeed `true`.

You are right in the comment below though, we should probably evaluate to `true` if the closure is `nil`. I'll change it.
___
*[`ios/MullvadVPN/Classes/InterceptibleNavigationController.swift` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-Nuy0tuX-ZbsnjZChYMX:-Nv0fQ_57bcrpmXJBUv7:b-otilcs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f64945411314811340af8808e75d7a3b8a0b263/ios/MullvadVPN/Classes/InterceptibleNavigationController.swift#L29)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

See the comment for `popViewController`, in particular about what to do if the callbacks are `nil`.  My instincts would suggest that if the instantiator neglected to provide one of these callbacks, they'd want it to be assumed to be `true`, giving unmodified behaviour.
</blockquote></details>

See comment above.
___
*[`ios/MullvadVPN/Containers/Navigation/CustomNavigationController.swift` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-Nux8T9w4afqbDnkf-UU:-Nv0dQQ9DZ8Dx9KAQXRc:b-ai6b8z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f64945411314811340af8808e75d7a3b8a0b263/ios/MullvadVPN/Containers/Navigation/CustomNavigationController.swift#L12)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Is there any reason to use `InterceptibleNavigationController` solely during editing mode in a custom list, rather than inheriting `CustomNavigationController` from `InterceptibleNavigationController`?
</blockquote></details>

Yeah, it's a better idea to do it the other way around, thereby only using it in custom list edit mode. I'll change it.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-NuxFVIL1wXKp7ma-rJC:-Nv0f_oo1YtKx0kksKhP:b-u3hf3f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f64945411314811340af8808e75d7a3b8a0b263/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L30)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

we can make it shorter.
</blockquote></details>

In my opinion that's also harder to read, so I'd rather keep it a little longer.
___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 109 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-NuxYFkxDlSnV8KZywK0:-Nv0gE254RqnPW0f2TR9:bo46z9v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f64945411314811340af8808e75d7a3b8a0b263/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L109)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

When I took these steps at the custom list the `SelectLocation` doesn't refresh:
1- update the locations of a custom list and save it
3- the location list didn't get updated at `Select location` view
</blockquote></details>

That's strange. I'm testing it now and it gets updated as expected. Can you reproduce it easily?
___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 260 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-NuxbjSzCRhnUChsm88V:-Nv0h_h363Nk_vurIejx:b-geyw9s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f64945411314811340af8808e75d7a3b8a0b263/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L260)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit : use `flatMap` seems much more sensiable.
</blockquote></details>

I agree that it's neat, but I believe the team agreed on not using flatmap this way. @buggmagnet @acb-mv ?


<!-- Sent from Reviewable.io -->

2024-04-09 08:20 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079)* status: all files reviewed, 5 unresolved discussions (waiting on @acb-mv and @rablador)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 109 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-NuxYFkxDlSnV8KZywK0:-Nv0wDi9-1vnDruTez-f:b28l1yz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f64945411314811340af8808e75d7a3b8a0b263/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L109)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

That's strange. I'm testing it now and it gets updated as expected. Can you reproduce it easily?
</blockquote></details>

talked offline.


<!-- Sent from Reviewable.io -->

2024-04-10 11:34 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079)* status: 10 of 16 files reviewed, 5 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @mojganii)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 100 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-Nv6mPxz63bi31vZEFAz:-Nv6mPxz63bi31vZEFB-:b-niiofp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/236557dbc464b6c27872e14af1e80c37e9a6ae89/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L100)):*
> ```Swift
>     }
> 
>     /// Refreshes the custom list section and keeps all modifications intact (selection and expanded states).
> ```

It's all so complex and convoluted... 😭


<!-- Sent from Reviewable.io -->

2024-04-10 14:19 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079)* status: 8 of 16 files reviewed, 6 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 30 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-Nv7LrK-0OhWmZxGApo0:-Nv7LrK-0OhWmZxGApo1:bq94smp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2ac9458aeebc9c1d568cb32eb70638c8dab1f412/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L30)):*
> ```Swift
>     private var validationErrors: Set<CustomListFieldValidationError> = []
> 
>     private var persistedCustomList: CustomList? {
> ```

nit : you can eliminate return. moreover, `customList` name is enough, isn't it?
___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 34 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-Nv7LaqN0egf7f5RS3VJ:-Nv7LaqO8IdG-6QqUodF:bqfqm0r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2ac9458aeebc9c1d568cb32eb70638c8dab1f412/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L34)):*
> ```Swift
>     }
> 
>     private var customListHasUnsavedChanges: Bool {
> ```

isn't `hasUnsavedChanges` good enough?


<!-- Sent from Reviewable.io -->

2024-04-15 09:29 UTC, acb-mv requested changes
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079)* status: all files reviewed, 7 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift` line 260 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-NuxbjSzCRhnUChsm88V:-NvW3wYD1YlGOXDXSmt2:bhir6ph) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f64945411314811340af8808e75d7a3b8a0b263/ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift#L260)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

What I don't like in @mojganii's suggestion is that `$0` is used twice in a row, which makes it harder to understand what argument is passed where.
</blockquote></details>

`flatMap` should be used for functional operations which return a value, rather than producing side effects. I'd rewrite @mojganii 's example as 



_Code snippet:_
```Swift
if let match = self.interactor.fetchAll().first(where: { $0.id == self.subject.value.id }) {
    subject.value.update(with: match)
}
```
___
*[`ios/MullvadVPN/Classes/InterceptableNavigationController.swift` line 11 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-NvW3ab-48DeVE9JMpPe:-NvW3ab-48DeVE9JMpPf:b-1adoe0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/650f426588f46962f849bd6ee7f875d77c3b66cd/ios/MullvadVPN/Classes/InterceptableNavigationController.swift#L11)):*
> ```Swift
> import UIKit
> 
> class InterceptableNavigationController: CustomNavigationController {
> ```

IMHO, "Interceptible" is the correct spelling (technically)


<!-- Sent from Reviewable.io -->

2024-04-15 10:29 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079)* status: all files reviewed, 7 unresolved discussions (waiting on @acb-mv and @mojganii)

___
*[`ios/MullvadVPN/Classes/InterceptableNavigationController.swift` line 11 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-NvW3ab-48DeVE9JMpPe:-NvWIOic71FJY6XhJFL_:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/650f426588f46962f849bd6ee7f875d77c3b66cd/ios/MullvadVPN/Classes/InterceptableNavigationController.swift#L11)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

IMHO, "Interceptible" is the correct spelling (technically)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-16 08:47 UTC, acb-mv approved these changes
> Reviewed 3 of 4 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079)* status: all files reviewed, 4 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-04-16 09:15 UTC, mojganii approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079)* status: all files reviewed, 3 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-04-16 09:39 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r6, 2 of 4 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-:-NvaGiVE4-2MZ5y1w35Y:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift` line 100 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079#-Nv6mPxz63bi31vZEFAz:-NvaAW2d4B5eOLEe1a_z:b-aqug9s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/236557dbc464b6c27872e14af1e80c37e9a6ae89/ios/MullvadVPN/View%20controllers/SelectLocation/LocationDataSource.swift#L100)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It's all so complex and convoluted... 😭
</blockquote></details>

:people_hugging: 


<!-- Sent from Reviewable.io -->

2024-04-16 09:41 UTC, merged