Prevent duplicate list names in custom lists
mullvad/mullvadvpn-app pull request #6105
Opened 2024-04-10 12:59 UTC by rablador

It shouldn't be possible to save a custom list with an already existing list name.

2024-04-12 08:02 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6105)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadSettings/CustomListRepository.swift` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6105#-NvGIOpK1aZTfU6_99fb:-NvGIOpK1aZTfU6_99fc:b7tk4m3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecf69cf93ab5164dc662d84797e7a52ebc9de8d2/ios/MullvadSettings/CustomListRepository.swift#L43)):*
> ```Swift
> 
>         let persistedListWithSameName = lists.first {
>             $0.name.localizedCaseInsensitiveCompare(list.name) == .orderedSame
> ```

do we really to compare the `localized value ` of a name? I'm of the opinion it's just a name regardless of its language.
___
*[`ios/MullvadSettings/CustomListRepository.swift` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6105#-NvGIYEVACByIPA6ogJc:-NvGIYEVACByIPA6ogJd:bacorw6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecf69cf93ab5164dc662d84797e7a52ebc9de8d2/ios/MullvadSettings/CustomListRepository.swift#L46)):*
> ```Swift
>         }
> 
>         if let persistedListWithSameName, persistedListWithSameName.id != list.id {
> ```

nit : duplicatedName


<!-- Sent from Reviewable.io -->

2024-04-12 08:06 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6105)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadSettings/CustomListRepository.swift` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6105#-NvGIYEVACByIPA6ogJc:-NvGKhDh-pjQThNxlnJf:b-s653q5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecf69cf93ab5164dc662d84797e7a52ebc9de8d2/ios/MullvadSettings/CustomListRepository.swift#L46)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit : duplicatedName
</blockquote></details>

the name of class defines the object takes the responsibility of storing, having `persisted` is redundant.


<!-- Sent from Reviewable.io -->

2024-04-12 14:51 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6105)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadSettings/CustomListRepository.swift` line 46 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6105#-NvGIYEVACByIPA6ogJc:-NvHlW2PAGcX5D2X9wRO:b-etvc3a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ecf69cf93ab5164dc662d84797e7a52ebc9de8d2/ios/MullvadSettings/CustomListRepository.swift#L46)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It's the same variable, just that it's unwrapped here, just like `guard let self else ...`.

I think it's good to distinguish where the two lists comes from. One is passed in to the function as param, the other is loaded from store. `listWithSameName` feels a little too ambiguous for me.
</blockquote></details>

Did some refactoring to make it a little less obtuse.


<!-- Sent from Reviewable.io -->

2024-04-15 09:12 UTC, acb-mv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6105)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-04-15 09:19 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6105#-:-NvW0wGJ3df3GTLcG_AQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-15 09:29 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6105#-:-NvW4drO3crpAFZeoqHI:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-15 09:30 UTC, merged