Mock data for screenshot test
mullvad/mullvadvpn-app pull request #6227
Opened 2024-05-06 21:07 UTC by mojganii

This PR introduces mocking data for snapshot testing with the following key assumptions:

- The account view must refresh instantly and display `37 days` of remaining time.
- The device name is set to `Secure Mole`.
- The app is always connected to `se-got-wg-10`'.

2024-05-07 07:57 UTC, buggmagnet requested changes
This doesn't compile for me, how did you manage to run the Screenshot tests ?

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227#-:-NxH2SUb-L_WNcXPynU4:b-wboqjz)* status: 0 of 21 files reviewed, 4 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/AppDelegate.swift` line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227#-NxH-fAJ0P-dFrE2Zgyl:-NxH-fAJ0P-dFrE2Zgym:bl5xfrt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db196c76110bd85b3bf14e89403296b412b0818b/ios/MullvadVPN/AppDelegate.swift#L50)):*
> ```Swift
>     private(set) var configuredTransportProvider: ProxyConfigurationTransportProvider!
>     private(set) var ipOverrideRepository = IPOverrideRepository()
>     private var launchArguments: LaunchArguments?
> ```

This doesn't need to be optional, all the values in that `struct` are already defined at init time.
___
*[`ios/MullvadVPN/AppDelegate.swift` line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227#-NxH-orJ8fSis02VHlso:-NxH-orJ8fSis02VHlsp:b-ay51po) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db196c76110bd85b3bf14e89403296b412b0818b/ios/MullvadVPN/AppDelegate.swift#L61)):*
> ```Swift
>         launchArguments = ProcessInfo.processInfo.decode(LaunchArguments.self)
> 
>         if launchArguments?.isDisabledAnimations ?? false {
> ```

With the other suggestions I made, we could change this to 
```swift
        if let overridenLaunchArguments = try? ProcessInfo.processInfo.decode(LaunchArguments.self) {
            launchArguments = overridenLaunchArguments
        }

        if launchArguments.isDisabledAnimations {
            UIView.setAnimationsEnabled(false)
        }
```

The first line is a bit longer, but we don't need to unwrap the optional which is slightly nicer IMHO
___
*[`ios/Shared/LaunchArguments.swift` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227#-NxGztlI1evsnVruzwnE:-NxGztlI1evsnVruzwnF:brnxbgr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db196c76110bd85b3bf14e89403296b412b0818b/ios/Shared/LaunchArguments.swift#L31)):*
> ```Swift
> 
>     // Disable animations to speed up tests.
>     public var isDisabledAnimations = false
> ```

We can rename this `disableAnimations` 
it makes it easier to read
`if launchArguments.disableAnimations == false { ... }`
___
*[`ios/Shared/LaunchArguments.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227#-NxGx6Wo2fZXBc59WE69:-NxGx6Wo2fZXBc59WE6A:b-pp3qri) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db196c76110bd85b3bf14e89403296b412b0818b/ios/Shared/LaunchArguments.swift#L55)):*
> ```Swift
> 
> private extension Decodable {
>     static func decode(from json: String) -> Self? {
> ```

It doesn't make sense to have an encoding API that throws, but a decoding that doesn't from an API design perspective.
Since `JSONDecoder` APIs are already `throws`, we should take advantage of that.

Suggestion
```swift

public extension ProcessInfo {
    func decode<T: Taggable & Decodable>(_: T.Type) throws -> T {
        guard let environment = environment[T.tag] else {
            throw DecodingError.valueNotFound(
                T.self,
                DecodingError.Context(codingPath: [], debugDescription: "\(T.self) not found in environment")
            )
        }
        return try T.decode(from: environment)
    }
}

extension Encodable {
    public func toJSON(_ encoder: JSONEncoder = JSONEncoder()) throws -> String {
        let data = try encoder.encode(self)
        let result = String(decoding: data, as: UTF8.self)
        return result
    }
}

private extension Decodable {
    static func decode(from json: String) throws -> Self {
        guard let data = json.data(using: .utf8) else {
            throw DecodingError.valueNotFound(
                Self.self,
                DecodingError.Context(codingPath: [], debugDescription: "Could not convert \(json) into UTF-8 Data")
            )
        }

        return try JSONDecoder().decode(self, from: data)
    }
}

```

The bonus is that it makes the screenshot tests easier to read by removing the optional bindings, and taking advantage of throwing APIs.

```swift
    override func setUpWithError() throws {
        // Put setup code here. This method is called before the invocation of
        // each test method in the class.

        // In UI tests it is usually best to stop immediately when a failure occurs.
        continueAfterFailure = false

        let argumentsJsonString = try LaunchArguments(
            target: .screenshots,
            isDisabledAnimations: true
        ).toJSON()
        app.launchEnvironment[LaunchArguments.tag] = argumentsJsonString

    }

```


<!-- Sent from Reviewable.io -->

2024-05-07 08:51 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227)* status: all files reviewed, 8 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 8588 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227#-NxHETRY0xCoqWM6Dj7X:-NxHETRY0xCoqWM6Dj7Y:b-jiyp1f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db196c76110bd85b3bf14e89403296b412b0818b/ios/MullvadVPN.xcodeproj/project.pbxproj#L8588)):*
> ```
> 				MODULE_VERIFIER_SUPPORTED_LANGUAGES = "objective-c objective-c++";
> 				MODULE_VERIFIER_SUPPORTED_LANGUAGE_STANDARDS = "gnu17 gnu++20";
> 				PRODUCT_BUNDLE_IDENTIFIER = Mojgan.MullvadMockData;
> ```

This should be `$(APPLICATION_IDENTIFIER).MullvadMockData`
This applies for all the configurations


<!-- Sent from Reviewable.io -->

2024-05-07 08:53 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227)* status: all files reviewed, 9 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 8566 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227#-NxHFVbb2dn3j1UZ8gQ2:-NxHFVbb2dn3j1UZ8gQ3:b-m0yo7o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db196c76110bd85b3bf14e89403296b412b0818b/ios/MullvadVPN.xcodeproj/project.pbxproj#L8566)):*
> ```
> 				CLANG_CXX_LANGUAGE_STANDARD = "gnu++20";
> 				CLANG_WARN_UNGUARDED_AVAILABILITY = YES_AGGRESSIVE;
> 				CODE_SIGN_STYLE = Automatic;
> ```

This should be ` CODE_SIGN_IDENTITY = "Apple Development";`


<!-- Sent from Reviewable.io -->

2024-05-07 10:30 UTC, rablador approved these changes
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadMockData/MullvadREST/DevicesProxy+Stubs.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227#-NxGwm-Z3b4wSIyLVV35:-NxHaHjdBbTPMfYoqq8L:b8cxrqy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db196c76110bd85b3bf14e89403296b412b0818b/ios/MullvadMockData/MullvadREST/DevicesProxy%2BStubs.swift#L15)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I couldn't follow what you meant.
</blockquote></details>

Oops, my bad, I forgot to remove it!


<!-- Sent from Reviewable.io -->

2024-05-08 08:28 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227)* status: 20 of 21 files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 8566 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227#-NxHFVbb2dn3j1UZ8gQ2:-NxMBmO7CEXpqb0GyPFr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db196c76110bd85b3bf14e89403296b412b0818b/ios/MullvadVPN.xcodeproj/project.pbxproj#L8566)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This should be ` CODE_SIGN_IDENTITY = "Apple Development";`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 8588 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227#-NxHETRY0xCoqWM6Dj7X:-NxMBlviEXV7PrVXz_HG:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db196c76110bd85b3bf14e89403296b412b0818b/ios/MullvadVPN.xcodeproj/project.pbxproj#L8588)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This should be `$(APPLICATION_IDENTIFIER).MullvadMockData`
This applies for all the configurations
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-10 07:15 UTC, rablador reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-05-10 08:28 UTC, acb-mv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-05-13 09:20 UTC, buggmagnet requested changes
> Reviewed 9 of 21 files at r1, 11 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227)* status: all files reviewed, 4 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 884 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227#-NxlCyDuCmKp2_62rn8k:-NxlCyDuCmKp2_62rn8l:b4asrbe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/547e9f3d73d041f3a9665cc73583dd95df9212d4/ios/MullvadVPN.xcodeproj/project.pbxproj#L884)):*
> ```
> 		F0ACE3262BE4E6C7006D5333 /* MullvadTypes.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = 58D223D5294C8E5E0029F5F8 /* MullvadTypes.framework */; platformFilter = ios; };
> 		F0ACE3282BE4E712006D5333 /* WireGuardKitTypes in Frameworks */ = {isa = PBXBuildFile; productRef = F0ACE3272BE4E712006D5333 /* WireGuardKitTypes */; };
> 		F0ACE32A2BE4E712006D5333 /* WireGuardKitTypes in Embed Frameworks */ = {isa = PBXBuildFile; productRef = F0ACE3272BE4E712006D5333 /* WireGuardKitTypes */; settings = {ATTRIBUTES = (CodeSignOnCopy, ); }; };
> ```

This `ATTRIBUTES` shouldn't be here, we don't need to embed `WireGuardKitTypes` into MullvadMockData.

Please go to the `Build Phases` section of  the`MullvadMockData`  target, and disable the check box named `CodeSignOnCopy` 
![Screenshot 2024-05-13 at 11.11.23.png](https://files.reviewableusercontent.io/images/reviewable/129761703/kyS52QI5FAZllxk2l76dInMz/Screenshot%202024-05-13%20at%2011.11.23.png)
___
*[`ios/Shared/LaunchArguments.swift` line 31 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227#-NxGztlI1evsnVruzwnE:-NxlE3yu5DxdPVSWtLjO:bhs5a73) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db196c76110bd85b3bf14e89403296b412b0818b/ios/Shared/LaunchArguments.swift#L31)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

the new name implies  the data type of property.let's keep it `isDisabledAnimations`
</blockquote></details>

Could you clarify what you mean ?
Also `launchArguments.isDisabledAnimations ` doesn't read like an english sentence. 
If you want to keep the`is/are` prefix, then we can rename it `areAnimationsDisabled` so it reads naturally.
___
*[`ios/MullvadMockData/MullvadREST/DevicesProxy+Stubs.swift` line 15 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227#-NxlAvwF2MMngjeYD7ig:-NxlAvwF2MMngjeYD7ih:b-i5cqjq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/547e9f3d73d041f3a9665cc73583dd95df9212d4/ios/MullvadMockData/MullvadREST/DevicesProxy%2BStubs.swift#L15)):*
> ```Swift
> 
> struct DevicesProxyStub: DeviceHandling {
>     var deviceResult: Result<Device, Error>?
> ```

It doesn't really make sense from an API point of view to have an `Optional` `Result` type, since it already has a `failure` case.
It would look cleaner if we default it to fail with a dummy error, and this would skip all the optionals unwraps down the line.

```swift
struct DevicesProxyStubError: Error {}

struct DevicesProxyStub: DeviceHandling {
    var deviceResult: Result<Device, Error> = .failure(DevicesProxyStubError())

```

before
```swift
if let result = deviceResult {
    completion(result)
}```

after
```swift
completion(deviceResult)
```


<!-- Sent from Reviewable.io -->

2024-05-13 11:18 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227#-:-Nxlf6Le4ef-KmKoM3KY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-05-13 11:19 UTC, merged