Implement PQ PSK
mullvad/mullvadvpn-app pull request #6232
Opened 2024-05-08 08:50 UTC by buggmagnet

This PR implements Post Quantum key exchange in the iOS application.
It's using the `talpid-tunnel-config-client` rust crate to do the key negotiation.

@dlon @pinkisemils are assigned for reviewing the Rust side of changes.
@rablador @mojganii are assigned for reviewing the Swift side of changes.
@acb-mv and @buggmagnet  co-authored this PR.

We currently have an ongoing bug in the Swift side of changes where the reflected state of the connection
is not accurate if one switches between PQ PSK and regular connection within the lifetime of the tunnel manager.
It's mostly a UI issue, the post quantum security feature is respected from the connection's point of view.

⚠️ As this was done in a feature branch, the code is not gated to only build in the `DEBUG` config. ⚠️ 
We are planning to fix the UI issues before merging this to main if we deem it good enough, otherwise we will gate keep it behind the `DEBUG` flag.

2024-05-08 12:26 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 0 of 51 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`Cargo.lock` line 4077 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxN952W7JooqquTpUk1:-NxN952W7JooqquTpUk2:bl1mje2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/Cargo.lock#L4077)):*
> ```TOML
>  "libc",
>  "log",
>  "oslog",
> ```

These commits need to be signed. Ideally, all changes to lockfiles are isolated to specific signed commites, i.e. the commits changing lock files don't change anything else but lock files.


<!-- Sent from Reviewable.io -->

2024-05-08 12:32 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 0 of 51 files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

___
*[`Cargo.toml` line 83 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxN9y629C8EtX-RYPFC:-NxN9y629C8EtX-RYPFD:b-xsdxhc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/Cargo.toml#L83)):*
> ```TOML
> windows-sys = "0.52.0"
> 
> chrono = { version = "0.4.26", default-features = false }
> ```

Useless whitespace change.
___
*[`ios/MullvadPostQuantum/MullvadPostQuantum.h` line 12 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNBDFV8phKyXkLGl6q:-NxNBDFV8phKyXkLGl6r:by7skz3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/ios/MullvadPostQuantum/MullvadPostQuantum.h#L12)):*
> ```objc
> 
> //! Project version number for MullvadPostQuantum.
> FOUNDATION_EXPORT double MullvadPostQuantumVersionNumber;
> ```

Are these used anywhere?


<!-- Sent from Reviewable.io -->

2024-05-08 14:36 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 5 of 51 files reviewed, 6 unresolved discussions (waiting on @pinkisemils)

___
*[`Cargo.lock` line 4077 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxN952W7JooqquTpUk1:-NxNbcnN9nxkAg7Xhf4D:b24s4ex) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/Cargo.lock#L4077)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

These commits need to be signed. Ideally, all changes to lockfiles are isolated to specific signed commites, i.e. the commits changing lock files don't change anything else but lock files.
</blockquote></details>

I've singled out the commit that lists those changes to sign it. 
___
*[`Cargo.toml` line 83 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxN9y629C8EtX-RYPFC:-NxNbugt64sKwEYu54ua:b-5bmycy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/Cargo.toml#L83)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Useless whitespace change.
</blockquote></details>

Shouldn't that file be linted / formatted automatically ?
I didn't do this change intentionally, my IDE did it on my behalf. Let me know if you want me to remove the change. I think it's harmless.


<!-- Sent from Reviewable.io -->

2024-05-08 15:08 UTC, dlon requested changes
> Reviewed 4 of 51 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 10 of 51 files reviewed, 18 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

___
*[`talpid-tunnel-config-client/src/lib.rs` line 129 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNZeIH7r5NAVjSHRbj:-NxNZeIH7r5NAVjSHRbk:bnz4vo9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/lib.rs#L129)):*
> ```XML
>     enable_post_quantum: bool,
>     enable_daita: bool,
>     #[cfg(target_os = "ios")] mut client: EphemeralPeerClient<Channel>,
> ```

This can be split this into two functions. One that takes a `client` and no `service_address`, and another one (the original) that takes `service_address` and only creates a client then calls the new function. It probably doesn't have to be conditional on iOS.
___
*[`talpid-tunnel-config-client/src/lib.rs` line 129 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxN_7It4ijSQ3ghJvpA:-NxN_7It4ijSQ3ghJvpB:b-cwb0lx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/lib.rs#L129)):*
> ```XML
>     enable_post_quantum: bool,
>     enable_daita: bool,
>     #[cfg(target_os = "ios")] mut client: EphemeralPeerClient<Channel>,
> ```

You can use `RelayConfigService` instead of `EphemeralPeerClient<Channel>`
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs` line 13 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNX4PE-Llsd6HBfzWP:-NxNX4PE-Llsd6HBfzWQ:b1x79ni) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs#L13)):*
> run_ios_runtime

Can this not just be called `run_post_quantum_psk_exchange` or something? I don't think the caller needs to know what "iOS runtime" is.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNfwO3-uAbx37jBdB3:-NxNfwO3-uAbx37jBdB4:bnzyvu9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L88)):*
> ```XML
> 
>     fn is_shutdown(&self) -> bool {
>         self.shutdown.load(atomic::Ordering::SeqCst)
> ```

Should this wake the read/write task?
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 104 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNdKE57nQH--fG6xDJ:-NxNdKE57nQH--fG6xDK:bjho8qu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L104)):*
> ```XML
>         buf: &[u8],
>     ) -> std::task::Poll<Result<usize>> {
>         let raw_sender = Box::into_raw(Box::new(self.write_tx.clone()));
> ```

This is leaky. The box should be created in `if !self.write_in_progress { ... }` below.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 104 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNgJ9KDgR_cl_-ad8d:-NxNgJ9KDgR_cl_-ad8e:bbp53eg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L104)):*
> ```XML
>         buf: &[u8],
>     ) -> std::task::Poll<Result<usize>> {
>         let raw_sender = Box::into_raw(Box::new(self.write_tx.clone()));
> ```

This isn't properly cleaned up unless`handle_sent` is called. Is that guaranteed to happen? I think wrapping `write_tx` in an `Arc` and passing a pointer to a `Weak`might solve this.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 119 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNdUVwE1aJ40DyMRN7:-NxNdUVwE1aJ40DyMRN8:b-b1ija0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L119)):*
> ```XML
>                     return Poll::Ready(Err(connection_closed_err()));
>                 }
>                 if self.write_in_progress {
> ```

This can be simplified to

```
if !self.write_in_progress {
    let raw_sender = Box::into_raw(Box::new(self.write_tx.clone()));
    unsafe {
        swift_nw_tcp_connection_send(
            self.tcp_connection,
            buf.as_ptr() as _,
            buf.len(),
            raw_sender as _,
        );
    }
    self.write_in_progress = true;
}
Poll::Pending
```
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 156 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNd-ZDC86xhLQUYWzS:-NxNd-ZDC86xhLQUYWzT:b-3wwnp7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L156)):*
> ```XML
>         buf: &mut tokio::io::ReadBuf<'_>,
>     ) -> std::task::Poll<std::io::Result<()>> {
>         let raw_sender = Box::into_raw(Box::new(self.read_tx.clone()));
> ```

This is leaky. The box should be created in `if !self.read_in_progress { ... }` below.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 156 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNgbLH83tdHeYPTNDv:-NxNgbLH83tdHeYPTNDw:b-ecgf7h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L156)):*
> ```XML
>         buf: &mut tokio::io::ReadBuf<'_>,
>     ) -> std::task::Poll<std::io::Result<()>> {
>         let raw_sender = Box::into_raw(Box::new(self.read_tx.clone()));
> ```

This isn't properly cleaned up unless`handle_recv` is called. Is that guaranteed to happen? I think wrapping `read_tx` in an `Arc` and passing a pointer to a `Weak`might solve this.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 172 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNc_WM7mKW4V7S79Ks:-NxNc_WM7mKW4V7S79Kt:b-fmuq74) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L172)):*
> ```XML
>             }
>             std::task::Poll::Pending => {
>                 if self.read_in_progress {
> ```

This can be simplified to

```
if !self.read_in_progress {
    let raw_sender = Box::into_raw(Box::new(self.read_tx.clone()));
    unsafe {
        swift_nw_tcp_connection_read(self.tcp_connection, raw_sender as _);
    }
    self.read_in_progress = true;
}
Poll::Pending
```
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNbLy06Z89d7jOGoD0:-NxNbLy06Z89d7jOGoD1:b7d9pff) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L25)):*
> ```XML
>         let send_tx: Arc<mpsc::UnboundedSender<()>> = unsafe { Arc::from_raw(self.context as _) };
>         let _ = send_tx.send(());
>         std::mem::forget(send_tx);
> ```

Calling `Arc::increment_strong_count(self.context)` at the start of the function (before `from_raw`) is probably a bit nicer.
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNh56R7tiVK2nNOO7i:-NxNh56R7tiVK2nNOO7j:b-5aay29) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
> ```XML
> /// The TCP connection must be created to go through the tunnel.
> /// # Safety
> /// This function is safe to call
> ```

The remark about [...]

2024-05-10 08:06 UTC, rablador requested changes
> Reviewed 5 of 51 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 13 of 51 files reviewed, 19 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

___
*[`ios/MullvadPostQuantum/MullvadPostQuantum.h` line 12 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNBDFV8phKyXkLGl6q:-NxWMsIkEfqlXqflFz8O:bhovcxb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/ios/MullvadPostQuantum/MullvadPostQuantum.h#L12)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Are these used anywhere?
</blockquote></details>

These are auto-generated when creating a new frameworks, but I guess we could remove them unless we actually use them. They are in most (all?) of our existing frameworks though.
___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 26 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWXK5x97lOOr7MJocv:-NxWXK5x97lOOr7MJocw:b-abjs8h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L26)):*
> ```Swift
>     let rawData = Data(bytes: data, count: Int(dataLength))
> 
>     // The guarantee that no more than 2 writes happen in parallel is done by virtue of not returning the execution context
> ```

No more than 2 writes?


<!-- Sent from Reviewable.io -->

2024-05-10 09:53 UTC, rablador requested changes
> Reviewed 19 of 51 files at r1, 1 of 2 files at r2, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 32 of 51 files reviewed, 27 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 17 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWZ4Nh3sLt9gWA-4Uj:-NxWZ4Nh3sLt9gWA-4Uk:bvwolso) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L17)):*
> ```Swift
> @_cdecl("swift_nw_tcp_connection_send")
> func tcpConnectionSend(
>     connection: UnsafeMutableRawPointer?,
> ```

Nit: We use "raw" prefix for raw pointer params in `receivePostQuantumKey` below. It's kind of nice info I think.
___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 20 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWYNo54A64cJfyrMtP:-NxWYNo54A64cJfyrMtQ:b-mnud61) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L20)):*
> ```Swift
>     data: UnsafeMutableRawPointer,
>     dataLength: UInt,
>     sender: UnsafeMutableRawPointer?
> ```

Nit: Perhaps sender could be renamed to something that describes what it is.
___
*[`ios/MullvadPostQuantum/PostQuantumKeyNegotiator.swift` line 30 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWaLqt6X_T2-OtP1aB:-NxWaLqt6X_T2-OtP1aC:bs0bw7s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/MullvadPostQuantum/PostQuantumKeyNegotiator.swift#L30)):*
> ```Swift
>         var cancelToken = PostQuantumCancelToken()
> 
>         // TODO: Any non 0 return is considered a failure, and should be handled gracefully
> ```

Is there a PR or issue for this?
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 6826 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWiN6OC0koCnngmNk_:-NxWiN6OC0koCnngmNka:b-fqsjnr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/MullvadVPN.xcodeproj/project.pbxproj#L6826)):*
> ```
> 				PRODUCT_NAME = "$(TARGET_NAME)";
> 				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
> 				SWIFT_STRICT_CONCURRENCY = minimal;
> ```

Is this intentional?
___
*[`ios/PacketTunnel/PostQuantumKeyExchangeActor.swift` line 45 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWlIQuC-Q-6vOLJHJe:-NxWlIQuC-Q-6vOLJHJf:b-llap8e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/PacketTunnel/PostQuantumKeyExchangeActor.swift#L45)):*
> ```Swift
>     func startNegotiation(with privateKey: PrivateKey) {
>         let negotiator = PostQuantumKeyNegotiator()
> ```

Discussed offline, but we should have gateway and port stored or derived from somewhere else.
___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 257 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWqVe2EkVNskKVGhoE:-NxWqVe2EkVNskKVGhoF:bnpqgwj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L257)):*
> ```Swift
>     }
> 
>     func createTCPConnectionForPQPSK(_ gatewayAddress: String) -> NWTCPConnection {
> ```

This function is unused and can be removed.
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 257 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWspgr2SobCqkElVVE:-NxWspgr2SobCqkElVVF:b-8x88d4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L257)):*
> ```Swift
>         state = .connecting(connectionState)
> 
>         defer {
> ```

Nit: Since the function doesn't throw we can remove `defer` here and put the code on the bottom instead.
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 289 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWu2fg0Zk82UNIo4Nr:-NxWu2fg0Zk82UNIo4Ns:b-m4mhoo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L289)):*
> ```Swift
>         let settings: Settings = try settingsReader.read()
> 
>         if settings.quantumResistance.isEnabled {
> ```

Can we move this to its own function instead to declutter `tryStart`?


<!-- Sent from Reviewable.io -->

2024-05-10 10:34 UTC, rablador requested changes
> Reviewed 22 of 51 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 28 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

___
*[`ios/PacketTunnelCore/Actor/ConfigurationBuilder.swift` line 30 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWvxM-1XOj57U37UEP:-NxWvxM-1XOj57U37UEQ:b-2izicu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/PacketTunnelCore/Actor/ConfigurationBuilder.swift#L30)):*
> ```Swift
>     var endpoint: MullvadEndpoint?
>     var allowedIPs: [IPAddressRange]
>     // or should this go in MullvadEndpoint?
> ```

Seems fine to have it here since `privateKey` is here, no?


<!-- Sent from Reviewable.io -->

2024-05-10 11:30 UTC, acb-mv commented
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 257 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWqVe2EkVNskKVGhoE:-NxXGHMUEZJBAekO13Sp:b-896fjx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L257)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This function is unused and can be removed.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-05-10 11:47 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 50 of 51 files reviewed, 27 unresolved discussions (waiting on @dlon, @pinkisemils, and @rablador)

___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 26 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWXK5x97lOOr7MJocv:-NxWaq8i1fWM_U_XzuyA:b-2s5alu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L26)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

No more than 2 writes?
</blockquote></details>

It's actually incorrect, all writes are sequentials, so no more than a single write should happen in parallel. I will update this comment. 
___
*[`talpid-routing/src/unix/mod.rs` line 21 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNK7hA0dZf_NImb95a:-NxWuBMGDtAWpn2RoB-b:b-1gu7cp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-routing/src/unix/mod.rs#L21)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I don't believe we should be using `talpid-routing` on iOS.
</blockquote></details>

Yes, I must have had that change for something I thought was related, but turned out wasn't. Thanks for flagging this, I will revert this to being macos only.
___
*[`talpid-tunnel-config-client/Cargo.toml` line 33 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNLITcDayOtCeoLp91:-NxWum2GCY4TK4lk8FVL:b-l1jgok) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44dcda5625ddbbc2bceb4689de28d837f6526ced/talpid-tunnel-config-client/Cargo.toml#L33)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This shouldn't be a dev dependency for all other platforms. The tokio dependency should only be added for the iOS target.
</blockquote></details>

This was discussed offline. We will leave this as is for now, but in the future, we will have an abstraction of tokio in mullvad-types that will be consumed by all the iOS rust code so that the `rt-multi-thread` feature can be used as a dev-dependency.
___
*[`talpid-tunnel-config-client/src/lib.rs` line 129 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxN_7It4ijSQ3ghJvpA:-NxX0sgq33C5MKJcXBD5:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/lib.rs#L129)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You can use `RelayConfigService` instead of `EphemeralPeerClient<Channel>`
</blockquote></details>

Done
___
*[`talpid-tunnel-config-client/src/lib.rs` line 203 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNLtptD2iesMIhIVn4:-NxWzRWeDDxtncfnYsKD:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/lib.rs#L203)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

No need to create these variables, the if statement can be the sole expression in this function.
</blockquote></details>

Done.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs` line 13 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNX4PE-Llsd6HBfzWP:-NxX0wE4ChqXR5dwsFmR:b-g5ducu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs#L13)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

> run_ios_runtime

Can this not just be called `run_post_quantum_psk_exchange` or something? I don't think the caller needs to know what "iOS runtime" is.
</blockquote></details>

Yes, that's a good suggestion !
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNh56R7tiVK2nNOO7i:-NxWt6od0MU1RlLPS5p3:b-3zh8uv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The remark about safety should be replaced with a real explanation or be removed.
</blockquote></details>

Thanks for flagging this, I will update this comment to add useful information.


<!-- Sent from Reviewable.io -->

2024-05-10 13:03 UTC, acb-mv commented
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 289 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWu2fg0Zk82UNIo4Nr:-NxXaUxy2Ws48keNi9hy:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L289)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Can we move this to its own function instead to declutter `tryStart`?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-05-10 13:53 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 44 of 51 files reviewed, 26 unresolved discussions (waiting on @dlon, @pinkisemils, and @rablador)

___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 104 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNdKE57nQH--fG6xDJ:-NxXcn3X7SXd305kpVvk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L104)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is leaky. The box should be created in `if !self.write_in_progress { ... }` below.
</blockquote></details>

Done.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 104 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNgJ9KDgR_cl_-ad8d:-NxXd-1J0BPkvwXzcuxT:b-5vvcdp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L104)):*
`handle_sent` / `handle_read` are guaranteed to be called, otherwise we would leak anyway since the control is in the `NWTCPConnection` instance's hand.

> I think wrapping `write_tx` in an `Arc` and passing a pointer to a `Weak`might solve this.
Ok I'll try to do that.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 119 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNdUVwE1aJ40DyMRN7:-NxXdzsk5ArQvC7rAV3G:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L119)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This can be simplified to

```
if !self.write_in_progress {
    let raw_sender = Box::into_raw(Box::new(self.write_tx.clone()));
    unsafe {
        swift_nw_tcp_connection_send(
            self.tcp_connection,
            buf.as_ptr() as _,
            buf.len(),
            raw_sender as _,
        );
    }
    self.write_in_progress = true;
}
Poll::Pending
```
</blockquote></details>

Done.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 156 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNd-ZDC86xhLQUYWzS:-NxXe5ZF0zbn61llS-KE:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L156)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is leaky. The box should be created in `if !self.read_in_progress { ... }` below.
</blockquote></details>

Done.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 156 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNgbLH83tdHeYPTNDv:-NxXe6-Y7KbToy78Jv_u:b-xwmjil) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L156)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This isn't properly cleaned up unless`handle_recv` is called. Is that guaranteed to happen? I think wrapping `read_tx` in an `Arc` and passing a pointer to a `Weak`might solve this.
</blockquote></details>

Ok I will try to address that.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 172 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNc_WM7mKW4V7S79Ks:-NxXeywQ6Rnkxy4VHM4Q:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L172)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This can be simplified to

```
if !self.read_in_progress {
    let raw_sender = Box::into_raw(Box::new(self.read_tx.clone()));
    unsafe {
        swift_nw_tcp_connection_read(self.tcp_connection, raw_sender as _);
    }
    self.read_in_progress = true;
}
Poll::Pending
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-10 14:08 UTC, rablador reviewed
> Reviewed 1 of 1 files at r5, 4 of 5 files at r6, 1 of 1 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 23 unresolved discussions (waiting on @buggmagnet, @dlon, and @pinkisemils)



<!-- Sent from Reviewable.io -->

2024-05-13 07:33 UTC, rablador reviewed
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 23 unresolved discussions (waiting on @buggmagnet, @dlon, and @pinkisemils)



<!-- Sent from Reviewable.io -->

2024-05-13 07:47 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 26 unresolved discussions (waiting on @buggmagnet, @dlon, @pinkisemils, and @rablador)

___
*[`ios/MullvadPostQuantum/MullvadPostQuantum.h` line 12 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNBDFV8phKyXkLGl6q:-NxiaL871ZiI1bzVjTjp:bpq6pqu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/ios/MullvadPostQuantum/MullvadPostQuantum.h#L12)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

These are auto-generated when creating a new frameworks, but I guess we could remove them unless we actually use them. They are in most (all?) of our existing frameworks though.
</blockquote></details>

Xcode applies your app's version number to all included frameworks which means this can be removed.
___
*[`ios/MullvadPostQuantum/PostQuantumKeyNegotiator.swift` line 38 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxidrqEBunruf0ktu8x:-NxidrqEBunruf0ktu8y:b-j24m74) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/acf95f61d485c1993781e94283bdd0021880f1bd/ios/MullvadPostQuantum/PostQuantumKeyNegotiator.swift#L38)):*
> ```Swift
>             &cancelToken
>         )
>         guard result == 0 else {
> ```

don't we have error handling in a better manner?
___
*[`ios/PacketTunnel/PostQuantumKeyExchangeActor.swift` line 51 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxihBoj8k4IaMVVUvfw:-NxihBoj8k4IaMVVUvfx:b-v0m2xj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/acf95f61d485c1993781e94283bdd0021880f1bd/ios/PacketTunnel/PostQuantumKeyExchangeActor.swift#L51)):*
> ```Swift
>         let inTunnelTCPConnection = createTCPConnection(endpoint)
> 
>         let ephemeralSharedKey = PrivateKey() // This will become the new private key of the device
> ```

nit: isn't better to put the comment above of the code to keep the consistency?
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 257 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWspgr2SobCqkElVVE:-Nxkrgw310IhzulJ_pM3:b32v57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L257)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Since the function doesn't throw we can remove `defer` here and put the code on the bottom instead.
</blockquote></details>

+1
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 352 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxksgDq7Qpt7spJnd5d:-NxksgDq7Qpt7spJnd5e:b4jac5y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/acf95f61d485c1993781e94283bdd0021880f1bd/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L352)):*
> ```Swift
>      connection restricted to the negotiation host and entering the negotiating state.
>      */
>     private func tryStartPostQuantumNegotiation(
> ```

nit : I suggest to put all functions are PQ related in an extension in the same file or `PacketTunnelActor+PostQuantum`



_Code snippet:_
```Swift
/**
 summery about PQ
 */
extension PacketTunnelActor {
   
    private func tryStartPostQuantumNegotiation(
        withSettings settings: Settings,
        nextRelay: NextRelay,
        reason: ReconnectReason
    ) async throws
    {}
}
```


<!-- Sent from Reviewable.io -->

2024-05-13 09:28 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 48 of 52 files reviewed, 23 unresolved discussions (waiting on @buggmagnet, @dlon, @pinkisemils, and @rablador)

___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 17 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWZ4Nh3sLt9gWA-4Uj:-NxlEu7_6QNqH_2_K8gm:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L17)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: We use "raw" prefix for raw pointer params in `receivePostQuantumKey` below. It's kind of nice info I think.
</blockquote></details>

Done
___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 20 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWYNo54A64cJfyrMtP:-NxlGkpG8Sui9DXSlcI5:bdfri62) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L20)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Perhaps sender could be renamed to something that describes what it is.
</blockquote></details>

It appears to be a Rust object of type `UnboundedSender`. @buggmagnet : any thoughts?
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 257 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWspgr2SobCqkElVVE:-NxlDC9e6B1-0yHm98r7:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L257)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 352 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxksgDq7Qpt7spJnd5d:-NxlCUBB14-XTNt4EU4G:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/acf95f61d485c1993781e94283bdd0021880f1bd/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L352)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit : I suggest to put all functions are PQ related in an extension in the same file or `PacketTunnelActor+PostQuantum`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-05-13 10:09 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 45 of 52 files reviewed, 22 unresolved discussions (waiting on @buggmagnet, @dlon, @mojganii, @pinkisemils, and @rablador)

___
*[`ios/MullvadPostQuantum/PostQuantumKeyNegotiator.swift` line 30 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWaLqt6X_T2-OtP1aB:-NxlPaN_28cUJh3-Zu4O:b-tndbaa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/MullvadPostQuantum/PostQuantumKeyNegotiator.swift#L30)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Is there a PR or issue for this?
</blockquote></details>

I've now fixed this by threading failure states through.
___
*[`ios/MullvadPostQuantum/PostQuantumKeyNegotiator.swift` line 38 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxidrqEBunruf0ktu8x:-NxlK3Bk9PYSakAmJCR2:bootbyb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/acf95f61d485c1993781e94283bdd0021880f1bd/ios/MullvadPostQuantum/PostQuantumKeyNegotiator.swift#L38)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

don't we have error handling in a better manner?
</blockquote></details>

The error in this case would be failure to set up a Rust runtime; the key negotiation happens asynchronously and is not returned from this function. I'll rename the function to better reflect this and handle this case.
___
*[`ios/PacketTunnel/PostQuantumKeyExchangeActor.swift` line 51 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxihBoj8k4IaMVVUvfw:-NxlQ-BF9IsJW1dnJyW_:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/acf95f61d485c1993781e94283bdd0021880f1bd/ios/PacketTunnel/PostQuantumKeyExchangeActor.swift#L51)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit: isn't better to put the comment above of the code to keep the consistency?
</blockquote></details>

Done
___
*[`ios/PacketTunnelCore/Actor/ConfigurationBuilder.swift` line 30 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWvxM-1XOj57U37UEP:-NxlQ28F0q9tggY3Rfch:bqy67xj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/PacketTunnelCore/Actor/ConfigurationBuilder.swift#L30)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Seems fine to have it here since `privateKey` is here, no?
</blockquote></details>

Fair enough


<!-- Sent from Reviewable.io -->

2024-05-13 13:04 UTC, rablador reviewed
> Reviewed 2 of 3 files at r10, 1 of 1 files at r12, 2 of 3 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 20 unresolved discussions (waiting on @buggmagnet, @dlon, @mojganii, and @pinkisemils)



<!-- Sent from Reviewable.io -->

2024-05-13 13:40 UTC, dlon reviewed
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 14 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pinkisemils)

___
*[`talpid-routing/src/unix/mod.rs` line 21 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNK7hA0dZf_NImb95a:-Nxm9TJa5vaSzEV1a--2:b-k8dxyz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-routing/src/unix/mod.rs#L21)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Yes, I must have had that change for something I thought was related, but turned out wasn't. Thanks for flagging this, I will revert this to being macos only.
</blockquote></details>

`any()` is redundant.
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNh56R7tiVK2nNOO7i:-Nxm8EWq31KQBsLs3ZWa:b-unybyt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Thanks for flagging this, I will update this comment to add useful information.
</blockquote></details>

Is this correct? I think they must be 32-byte arrays.
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 94 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-Nxm9rK2841F94o3vQaD:-Nxm9rK2841F94o3vQaE:bfsjnlx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3525f8e759980dfc34a96c36a6125cfe6deb4ea2/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L94)):*
> ```XML
> /// # Safety
> /// `public_key` and `ephemeral_key` must be valid respective `PublicKey` and `PrivateKey` types.
> /// They will not be valid after this function is called, and thus must be copied here.
> ```

This has nothing to do with this function. The function doesn't invalidate the arrays. It does copy them so that the caller doesn't have to worry about keeping them around, but I'm not sure that's worth mentioning.
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 95 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-Nxm8Wt09hVSJrFLzJrK:-Nxm8Wt09hVSJrFLzJrL:b2nh78a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3525f8e759980dfc34a96c36a6125cfe6deb4ea2/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L95)):*
> a


<!-- Sent from Reviewable.io -->

2024-05-14 07:46 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 48 of 52 files reviewed, 13 unresolved discussions (waiting on @mojganii, @pinkisemils, and @rablador)

___
*[`ios/MullvadPostQuantum/PostQuantumKeyNegotiator.swift` line 38 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxidrqEBunruf0ktu8x:-NxliiuhCCN91mRBus6e:b-nkiky7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/acf95f61d485c1993781e94283bdd0021880f1bd/ios/MullvadPostQuantum/PostQuantumKeyNegotiator.swift#L38)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

The error in this case would be failure to set up a Rust runtime; the key negotiation happens asynchronously and is not returned from this function. I'll rename the function to better reflect this and handle this case.
</blockquote></details>

@mojganii Unfortunately, one of the downsides of calling Rust across the FFI is that we have to use a common denominator that both languages can call into. In this case, we are bound by C specifications.
C doesn't have `throw` statements, or generics, the best we can do is either `inout` parameters, or return values.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 677 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxmAl635CiTFJjRj0gi:-NxpxQ6A0as0ZFgaXYs4:b-jzvj12) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/591aca8dc2523da1b1700e3ca921353e964fb1ae/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L677)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Are we not certain the connection will work anymore?
</blockquote></details>

The previous comment was misleading, so I deleted it. Also this slightly improves the UX of the PQ connection, otherwise, it will feel really sluggish.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 6826 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWiN6OC0koCnngmNk_:-NxlkjIjC4MNrhkDsTje:brfpxzy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/MullvadVPN.xcodeproj/project.pbxproj#L6826)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Is this intentional?
</blockquote></details>

I think it's okay, it's the default option if it's not set at the moment.
___
*[`ios/PacketTunnel/PostQuantumKeyExchangeActor.swift` line 45 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWlIQuC-Q-6vOLJHJe:-Nxq-ES41QC9z3YbR3T9:b7q7mpo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/PacketTunnel/PostQuantumKeyExchangeActor.swift#L45)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Discussed offline, but we should have gateway and port stored or derived from somewhere else.
</blockquote></details>

For the gateway address, I think of leaving it like that at the moment, because I'm not sure how I feel about creating a file for a single constant.
For the port, I've made it so that it reuses the constant defined in the auto-generated header file.
___
*[`ios/PacketTunnelCore/Actor/ConfigurationBuilder.swift` line 30 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWvxM-1XOj57U37UEP:-NxllIlbEC45URVpM3Gd:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/PacketTunnelCore/Actor/ConfigurationBuilder.swift#L30)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Fair enough
</blockquote></details>

Done.
___
*[`talpid-routing/src/unix/mod.rs` line 21 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNK7hA0dZf_NImb95a:-Nxq-BOT2ipC6Fcs0ELH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-routing/src/unix/mod.rs#L21)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`any()` is redundant.
</blockquote></details>

Done.
___
*[`talpid-tunnel-config-client/src/lib.rs` line 129 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNZeIH7r5NAVjSHRbj:-Nxq-V3R2Omao0aaafKc:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/lib.rs#L129)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This can be split this into two functions. One that takes a `client` and no `service_address`, and another one (the original) that takes `service_address` and only creates a client then calls the new function. It probably doesn't have to be conditional on iOS.
</blockquote></details>

Done
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNbLy06Z89d7jOGoD0:-Nxq-XzM26p8LlFF3bhr:b-shje5g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L25)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Calling `Arc::increment_strong_count(self.context)` at the start of the function (before `from_raw`) is probably a bit nicer.
</blockquote></details>

This was discussed offline. We decided to leave it like this. 


<!-- Sent from Reviewable.io -->

2024-05-14 09:41 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 44 of 52 files reviewed, 13 unresolved discussions (waiting on @acb-mv, @mojganii, @pinkisemils, and @rablador)

___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 20 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxWYNo54A64cJfyrMtP:-NxqTVRh4EqtWjHEjaSh:bj7kwk9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/941b32f2e2f969a0f15693cccb431b10e4fa0641/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L20)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

It appears to be a Rust object of type `UnboundedSender`. @buggmagnet : any thoughts?
</blockquote></details>

It was very not descriptive indeed. I added some documentation to clarify how and when these functions are used.


<!-- Sent from Reviewable.io -->

2024-05-14 09:48 UTC, pinkisemils requested changes
> Reviewed 2 of 3 files at r17.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 46 of 52 files reviewed, 10 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 66 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqVA9I-xgED0dIWAIC:-NxqVA9I-xgED0dIWAID:b-6c0q45) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L66)):*
> ```Swift
> ) {
>     guard let rawConnection, let rawReadAcknowledgement else {
>         handle_recv(Data().map { $0 }, 0, rawReadAcknowledgement)
> ```

What's the point of `Data().map { $0 }` ?


<!-- Sent from Reviewable.io -->

2024-05-14 09:52 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 46 of 52 files reviewed, 11 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqVzEx5-W7oUdtA5Kw:-NxqVzEx5-W7oUdtA5Kx:b-d52x2o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
> ```XML
>     }
>     if let Some(read_tx) = weak_tx.upgrade() {
>         _ = read_tx.send(bytes.into_boxed_slice());
> ```

Should we be sending an empty slice in case the `data` pointer is null?


<!-- Sent from Reviewable.io -->

2024-05-14 09:54 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 46 of 52 files reviewed, 11 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 66 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqVA9I-xgED0dIWAIC:-NxqW_XX--_nyRxbrmWI:b-sjy4ar) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L66)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

What's the point of `Data().map { $0 }` ?
</blockquote></details>

Why isn't it just a `nil` pointer?
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqVzEx5-W7oUdtA5Kw:-NxqW6c96NcyEAx0VYq8:b-hxkr96) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Should we be sending an empty slice in case the `data` pointer is null?
</blockquote></details>

It's not empty in the sense that it's a slice with a size of 0. Instead, it is a slice with the size 


<!-- Sent from Reviewable.io -->

2024-05-14 10:59 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 46 of 52 files reviewed, 11 unresolved discussions (waiting on @buggmagnet, @mojganii, and @rablador)

___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 109 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqkJhQ2k8ULcy3i8Oe:-NxqkJhQ2k8ULcy3i8Of:bgphw3n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L109)):*
> ```XML
> ) -> i32 {
>     INIT_LOGGING.call_once(|| {
>         let _ = oslog::OsLogger::new("net.mullvad.MullvadVPN.TTCC")
> ```

This may panic if the logger is initialized elsewhere.


<!-- Sent from Reviewable.io -->

2024-05-14 11:22 UTC, dlon requested changes
> Reviewed 3 of 4 files at r16, 1 of 3 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 50 of 52 files reviewed, 16 unresolved discussions (waiting on @buggmagnet, @mojganii, @pinkisemils, and @rablador)

___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 34 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqnSET02OeHrL8ReGk:-NxqnSET02OeHrL8ReGl:bwnjyq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L34)):*
> ```Swift
> ) {
>     guard let rawConnection, let rawWriteAcknowledgement else {
>         handle_sent(0, rawWriteAcknowledgement)
> ```

This should never be called when `rawWriteAcknowledgement` is nil, only when `rawConnection` is nil. So either add a null check to `handle_sent` or just return in that case.
___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 66 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqoXXk11oWHq4igG9Z:-NxqoXXk11oWHq4igG9_:b-24ftfj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L66)):*
> ```Swift
> ) {
>     guard let rawConnection, let rawReadAcknowledgement else {
>         handle_recv(Data().map { $0 }, 0, rawReadAcknowledgement)
> ```

This should never be called when `rawReadAcknowledgement` is nil, only when `rawConnection` is nil. So either add a null check to `handle_recv` or just return in that case.
___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 73 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-Nxqol855EJ2sdEjH5-l:-Nxqol855EJ2sdEjH5-m:b-3h6zym) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L73)):*
> ```Swift
>         if let data {
>             if maybeError != nil {
>                 handle_recv(Data().map { $0 }, 0, rawReadAcknowledgement)
> ```

Same as above. You could just pass a `nil` pointer.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs` line 88 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqjyUvDMCHgtq1-XcV:-NxqjyUvDMCHgtq1-XcW:b5zd744) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs#L88)):*
> ```XML
>     }
> 
>     pub async fn ios_tcp_client(
> ```

This shouldn't be public, right? I also think it's `unsafe`, since it's unsafe to call this with an already-used `SwiftContext`.
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqVzEx5-W7oUdtA5Kw:-NxqlAkf5pBWYsMKjmpl:b-kvpzne) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It's not empty in the sense that it's a slice with a size of 0. Instead, it is a slice with the size
</blockquote></details>

When the (non-weak) sender is dropped, the receiver will cause `poll_recv` to return an error anyway, right? But it wouldn't hurt, I guess.
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 124 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqlZej0AiQW5ucrq99:-NxqlZej0AiQW5ucrq9A:b-xz7j4w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L124)):*
> ```XML
>             0
>         }
>         Err(err) => err,
> ```

Nit: The conversion from `Result`s to numeric return statuses should probably consistently occur here, not in different places depending on whether the function failed or not. But this isn't a big deal.


<!-- Sent from Reviewable.io -->

2024-05-14 12:30 UTC, rablador requested changes
> Reviewed 4 of 4 files at r16, 3 of 3 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 13 unresolved discussions (waiting on @buggmagnet, @dlon, @mojganii, and @pinkisemils)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift` line 57 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-Nxr3BuTAGDuqSdDW6Jj:-Nxr3BuTAGDuqSdDW6Jk:b7sc0zx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BPostQuantum.swift#L57)):*
> ```Swift
>             logger.error("Could not create connection state in PostQuantumConnect")
> 
>             let nextRelay: NextRelay = (state.connectionData?.selectedRelay).map { .preSelected($0) } ?? .current
> ```

Reconnecting here simply retries the PQ process with a (possibly) different relay?


<!-- Sent from Reviewable.io -->

2024-05-14 16:08 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 48 of 52 files reviewed, 12 unresolved discussions (waiting on @buggmagnet, @dlon, @mojganii, and @rablador)

___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqVzEx5-W7oUdtA5Kw:-Nxrr-xZ84S1CBWnwbke:bhoh5m5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

When the (non-weak) sender is dropped, the receiver will cause `poll_recv` to return an error anyway, right? But it wouldn't hurt, I guess.
</blockquote></details>

No, what I mean is that when the data pointer is null, we still send an empty array to the reader. Is that by design?
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 124 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqlZej0AiQW5ucrq99:-NxrrBAn8_18MhFLzEA3:buvzhjg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L124)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: The conversion from `Result`s to numeric return statuses should probably consistently occur here, not in different places depending on whether the function failed or not. But this isn't a big deal.
</blockquote></details>

Ideally, there would be an `enum Error` that has a `Into<i32>` or something like that.


<!-- Sent from Reviewable.io -->

2024-05-14 17:35 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 48 of 52 files reviewed, 12 unresolved discussions (waiting on @buggmagnet, @dlon, @mojganii, @pinkisemils, and @rablador)

___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 66 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqVA9I-xgED0dIWAIC:-Nxs9y673fq4UmE5u6f3:bem7vp8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L66)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Why isn't it just a `nil` pointer?
</blockquote></details>

Good catch; fixed.


<!-- Sent from Reviewable.io -->

2024-05-14 20:27 UTC, dlon reviewed
> Reviewed 2 of 4 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 50 of 52 files reviewed, 11 unresolved discussions (waiting on @buggmagnet, @mojganii, @pinkisemils, and @rablador)

___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqVzEx5-W7oUdtA5Kw:-NxsdTRTDDHDio8ZhHls:bj58y8p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

No, what I mean is that when the data pointer is null, we still send an empty array to the reader. Is that by design?
</blockquote></details>

Yes, it is by design in the case where `data_len == 0 && data == null`. `data_len > 0` implies that `data` must not be null, though.


<!-- Sent from Reviewable.io -->

2024-05-15 07:00 UTC, rablador reviewed
> Reviewed 4 of 4 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 11 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pinkisemils)



<!-- Sent from Reviewable.io -->

2024-05-15 10:54 UTC, rablador reviewed
> Reviewed 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 8 unresolved discussions (waiting on @dlon, @mojganii, and @pinkisemils)



<!-- Sent from Reviewable.io -->

2024-05-15 12:36 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 8 unresolved discussions (waiting on @dlon, @mojganii, and @pinkisemils)

___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 66 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqoXXk11oWHq4igG9Z:-NxvOEvw-venQzFl5dHQ:bxplirk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L66)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This should never be called when `rawReadAcknowledgement` is nil, only when `rawConnection` is nil. So either add a null check to `handle_recv` or just return in that case.
</blockquote></details>

This was discussed offline.
___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 73 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-Nxqol855EJ2sdEjH5-l:-NxvOKqj-WXYYHcLy7jV:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L73)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Same as above. You could just pass a `nil` pointer.
</blockquote></details>

Done
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNh56R7tiVK2nNOO7i:-NxwD5sj00jiGRJ5YXg8:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is this correct? I think they must be 32-byte arrays.
</blockquote></details>

Done.
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 94 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-Nxm9rK2841F94o3vQaD:-NxwD7Pr7o8bSSyOmJz3:btpeo01) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3525f8e759980dfc34a96c36a6125cfe6deb4ea2/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L94)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This has nothing to do with this function. The function doesn't invalidate the arrays. It does copy them so that the caller doesn't have to worry about keeping them around, but I'm not sure that's worth mentioning.
</blockquote></details>

I think it's important to mention for future readers tempted to let things linger on the stack a bit too long. 
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqVzEx5-W7oUdtA5Kw:-NxwD4LlEkMo-gZgtrWX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Yes, it is by design in the case where `data_len == 0 && data == null`. `data_len > 0` implies that `data` must not be null, though.
</blockquote></details>

Done.
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 109 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqkJhQ2k8ULcy3i8Oe:-NxwEWGJC4MjutadUOw1:bw9j2ky) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L109)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This may panic if the logger is initialized elsewhere.
</blockquote></details>

Can you clarify what you mean by "elsewhere" ?
AFAICT this will be ran only once per instance of the packet tunnel, and it should be safe do to so. 


<!-- Sent from Reviewable.io -->

2024-05-15 13:01 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 48 of 52 files reviewed, 8 unresolved discussions (waiting on @dlon, @mojganii, @pinkisemils, and @rablador)

___
*[`ios/MullvadPostQuantum/MullvadPostQuantum.h` line 12 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNBDFV8phKyXkLGl6q:-NxwKwM29wUDRnYb0GE5:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/ios/MullvadPostQuantum/MullvadPostQuantum.h#L12)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Xcode applies your app's version number to all included frameworks which means this can be removed.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-05-15 13:03 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 48 of 52 files reviewed, 7 unresolved discussions (waiting on @dlon, @mojganii, @pinkisemils, and @rablador)

___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 34 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqnSET02OeHrL8ReGk:-NxwKyWa-XoOsFFxXZFq:b-7korjq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L34)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This should never be called when `rawWriteAcknowledgement` is nil, only when `rawConnection` is nil. So either add a null check to `handle_sent` or just return in that case.
</blockquote></details>

This was discussed offline, `rawWriteAcknowledgement` cannot be nil here.
___
*[`ios/MullvadPostQuantum/PacketTunnelProvider+TCPConnection.swift` line 66 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqVA9I-xgED0dIWAIC:-NxwL4LW3fiYimLmdo72:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/ios/MullvadPostQuantum/PacketTunnelProvider%2BTCPConnection.swift#L66)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Good catch; fixed.
</blockquote></details>

Done.
___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNfwO3-uAbx37jBdB3:-NxwLALwEmkIavgDUoBb:bgvgoku) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L88)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should this wake the read/write task?
</blockquote></details>

That's a question for @pinkisemils 
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 124 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqlZej0AiQW5ucrq99:-NxwLH0G5Zw-qFqefert:b-m8ayut) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L124)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Ideally, there would be an `enum Error` that has a `Into<i32>` or something like that.
</blockquote></details>

I've made it return a new kind of error, which eventually gets translated into `-1` for the FFI.
If we can not create the iOS runtime, I don't think the VPN process will survive that long to be honest. 


<!-- Sent from Reviewable.io -->

2024-05-15 13:44 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r20, 4 of 4 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 6 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pinkisemils)

___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNh56R7tiVK2nNOO7i:-NxwTtpU4g9N6ig8Eg1t:b-xcz75z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks the same?


<!-- Sent from Reviewable.io -->

2024-05-15 13:54 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 6 unresolved discussions (waiting on @dlon, @mojganii, and @pinkisemils)

___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNh56R7tiVK2nNOO7i:-NxwWRCY0HdlBPLSPQSt:b-x15sxl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Looks the same?
</blockquote></details>

`PublicKey` is defined as a 32 bytes array [down the line](https://github.com/dalek-cryptography/curve25519-dalek/blob/main/curve25519-dalek/src/montgomery.rs#L75)

The same goes for [`PrivateKey`](https://github.com/dalek-cryptography/curve25519-dalek/blob/main/x25519-dalek/src/x25519.rs#L198)


<!-- Sent from Reviewable.io -->

2024-05-15 13:58 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 6 unresolved discussions (waiting on @dlon, @mojganii, @pinkisemils, and @rablador)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift` line 57 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-Nxr3BuTAGDuqSdDW6Jj:-NxwXQZsAEtV3zqSzva-:bd1zrmn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BPostQuantum.swift#L57)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Reconnecting here simply retries the PQ process with a (possibly) different relay?
</blockquote></details>

Do you mean it's what it should do ?


<!-- Sent from Reviewable.io -->

2024-05-15 14:04 UTC, rablador approved these changes
> Reviewed 4 of 4 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pinkisemils)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift` line 57 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-Nxr3BuTAGDuqSdDW6Jj:-NxwZ-taE9eIbzX8MzNF:b2e3cm8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BPostQuantum.swift#L57)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Do you mean it's what it should do ?
</blockquote></details>

Sorry, it was intended purely as a question to understand the logic. :)


<!-- Sent from Reviewable.io -->

2024-05-15 14:40 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNfwO3-uAbx37jBdB3:-Nxwd4yMEENwSq9xjzuw:b-p5wgec) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L88)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

That's a question for @pinkisemils
</blockquote></details>

Yes, it should.
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqVzEx5-W7oUdtA5Kw:-NxvNgC7BMcAvj1IVBqq:b-1kzzyd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What specifically here is done? 
I think that instead of sending vectors and have the empty vector have some special meaning that isn't actually defined anywhere in our code (we just pass on the empty vector to the reader for the TCP stream further down).

I think we should at least document that we send an empty array back to the underlying TCP reader if an error occured on the Swift side and that we expect this will cause it to treat it like an EOF.
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 109 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqkJhQ2k8ULcy3i8Oe:-NxwdAkg66zeT-Vz3Oje:bwocyax) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L109)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Can you clarify what you mean by "elsewhere" ?
AFAICT this will be ran only once per instance of the packet tunnel, and it should be safe do to so.
</blockquote></details>

Do we not call this from shadowsocks? 


<!-- Sent from Reviewable.io -->

2024-05-15 14:44 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2024-05-15 15:13 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqVzEx5-W7oUdtA5Kw:-NxwnraP8VB7SaGo5DgQ:borbcoi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

What specifically here is done? 
I think that instead of sending vectors and have the empty vector have some special meaning that isn't actually defined anywhere in our code (we just pass on the empty vector to the reader for the TCP stream further down).

I think we should at least document that we send an empty array back to the underlying TCP reader if an error occured on the Swift side and that we expect this will cause it to treat it like an EOF.
</blockquote></details>

In fact, I think if the `data` pointer is null, then we should default to creating an empty vector too. Otherwise, the tcp reader on the other end of this will just be confused and continue to wait for more data.


<!-- Sent from Reviewable.io -->

2024-05-15 20:22 UTC, dlon approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pinkisemils)

___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqVzEx5-W7oUdtA5Kw:-NxxnjRJ0TdvLSxti-QY:b-majd9l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
> I think we should at least document that we send an empty array back to the underlying TCP reader if an error occured on the Swift side and that we expect this will cause it to treat it like an EOF.

Yes, that makes sense. I think that that should be added as a doc comment for the function:

> /// If `data` is `null` or empty, this indicates that the connection was closed or that an error occurred.  An empty buffer is sent to the underlying reader to signal EOF.

`handle_sent` deserves a similar comment: a `bytes_sent` of 0 indicates that an error occurred.


<!-- Sent from Reviewable.io -->

2024-05-16 07:19 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pinkisemils)



<!-- Sent from Reviewable.io -->

2024-05-16 11:35 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii and @pinkisemils)

___
*[`talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxNfwO3-uAbx37jBdB3:-Ny07RqA6yYcZJLSZEOb:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/77879b44e4540ad74d2a6b6b93381ff11118eb7a/talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs#L88)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Yes, it should.
</blockquote></details>

Done
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 88 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqVzEx5-W7oUdtA5Kw:-Ny0A_uo6xUN5xUflYQj:b14bbhu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L88)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

> I think we should at least document that we send an empty array back to the underlying TCP reader if an error occured on the Swift side and that we expect this will cause it to treat it like an EOF.

Yes, that makes sense. I think that that should be added as a doc comment for the function:

> /// If `data` is `null` or empty, this indicates that the connection was closed or that an error occurred.  An empty buffer is sent to the underlying reader to signal EOF.

`handle_sent` deserves a similar comment: a `bytes_sent` of 0 indicates that an error occurred.
</blockquote></details>

I've added the extra bit of documentation for both `handle_sent` and `handle_recv`
___
*[`talpid-tunnel-config-client/src/ios_ffi/mod.rs` line 109 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-NxqkJhQ2k8ULcy3i8Oe:-Ny-_EQBAITrxXH3KCtI:b-c1yi1u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/afa6b196e5638a084fe005e2256eeb52ab47e16d/talpid-tunnel-config-client/src/ios_ffi/mod.rs#L109)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Do we not call this from shadowsocks?
</blockquote></details>

This has been discussed offlne, and I have tested that more than one instances of `OSLogger` can co-exist in the VPN process.


<!-- Sent from Reviewable.io -->

2024-05-16 11:39 UTC, rablador requested changes
> Reviewed 4 of 4 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet, @mojganii, and @pinkisemils)

___
*[`ios/PacketTunnel/PostQuantumKeyExchangeActor.swift` line 78 at r22](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-Ny0Ba1MEZ_TJIOP2A31:-Ny0Ba1MEZ_TJIOP2A32:bj9vpej) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f30bdab0777120f029dac6ecc89a58d7ddf70d63/ios/PacketTunnel/PostQuantumKeyExchangeActor.swift#L78)):*
> ```Swift
>             ) {
>                 self.negotiation = nil
>                 self.timer?.cancel()
> ```

Timer is already cancelled when we get here.


<!-- Sent from Reviewable.io -->

2024-05-16 12:16 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 4 unresolved discussions (waiting on @mojganii, @pinkisemils, and @rablador)

___
*[`ios/PacketTunnel/PostQuantumKeyExchangeActor.swift` line 78 at r22](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-Ny0Ba1MEZ_TJIOP2A31:-Ny0K4Xs8QlI-NE5Ki7e:bkfbjru) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f30bdab0777120f029dac6ecc89a58d7ddf70d63/ios/PacketTunnel/PostQuantumKeyExchangeActor.swift#L78)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Timer is already cancelled when we get here.
</blockquote></details>

Oops, you're right, good catch ! Fixed.


<!-- Sent from Reviewable.io -->

2024-05-16 13:05 UTC, dlon reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: 51 of 52 files reviewed, 4 unresolved discussions (waiting on @mojganii, @pinkisemils, and @rablador)



<!-- Sent from Reviewable.io -->

2024-05-16 13:09 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii and @pinkisemils)



<!-- Sent from Reviewable.io -->

2024-05-16 13:36 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii and @pinkisemils)



<!-- Sent from Reviewable.io -->

2024-05-16 15:30 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232#-:-Ny10gJ23RLy1bakO8W9:bnfp4nl)* status: 47 of 52 files reviewed, all discussions resolved (waiting on @dlon and @rablador)



<!-- Sent from Reviewable.io -->

2024-05-20 11:18 UTC, rablador approved these changes
> Reviewed 5 of 5 files at r25, 1 of 1 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-21 11:01 UTC, pinkisemils approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-21 14:21 UTC, pinkisemils approved these changes
> Reviewed 2 of 2 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6232)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-21 15:04 UTC, merged