Fix problem report logs being duplicated
mullvad/mullvadvpn-app pull request #6235
Opened 2024-05-08 15:54 UTC by rablador

Some problem reports get duplicated when displaying logs in the problem report view.

2024-05-10 08:23 UTC, buggmagnet requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6235)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/Shared/ApplicationConfiguration.swift` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6235#-NxW_EBc0XYkse2yQgyj:-NxW_EBc0XYkse2yQgyk:b-4zqq0l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6442eb6507a3f4bf01ba6628bdc31510b3462cfa/ios/Shared/ApplicationConfiguration.swift#L41)):*
> ```Swift
>             let pathIsLog = path.split(separator: ".").last == "log"
>             // Pattern should be either "net.mullvad.MullvadVPN:PacketTunnel_" or "net.mullvad.MullvadVPN_".
>             let pathBelongsToTarget = path.contains("\(target.bundleIdentifier)_")
> ```

I think we should write a test for that. 
Also there's a small typo, it should be `net.mullvad.MullvadVPN.PacketTunnel_` (dot instead of colon)


<!-- Sent from Reviewable.io -->

2024-05-10 14:01 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6235)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/Shared/ApplicationConfiguration.swift` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6235#-NxW_EBc0XYkse2yQgyj:-NxXnZe88hPr96rLo2z6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6442eb6507a3f4bf01ba6628bdc31510b3462cfa/ios/Shared/ApplicationConfiguration.swift#L41)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I think we should write a test for that. 
Also there's a small typo, it should be `net.mullvad.MullvadVPN.PacketTunnel_` (dot instead of colon)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-13 07:45 UTC, buggmagnet requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6235)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPNTests/MullvadLogging/LoggingTests.swift` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6235#-Nxku-Oa5ypH3CWk2qMG:-Nxku-Ob5kZFulrvbJHh:b-t8umzb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df6111454fc28974714d0ac7a2f88e89463c5f4a/ios/MullvadVPNTests/MullvadLogging/LoggingTests.swift#L18)):*
> ```Swift
> 
>     override func setUpWithError() throws {
>         try? fileManager.createDirectory(
> ```

We shouldn't `try?`, if the test directory cannot be created, the tests should fail.


<!-- Sent from Reviewable.io -->

2024-05-13 07:57 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6235)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPNTests/MullvadLogging/LoggingTests.swift` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6235#-Nxku-Oa5ypH3CWk2qMG:-NxkxH8r94tVMIa1eZJD:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/df6111454fc28974714d0ac7a2f88e89463c5f4a/ios/MullvadVPNTests/MullvadLogging/LoggingTests.swift#L18)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We shouldn't `try?`, if the test directory cannot be created, the tests should fail.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-13 08:15 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6235#-:-Nxl0Mmn6zwR3x8MBv1b:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-13 08:19 UTC, merged