Migrate end to end tests to staging and fix related issues
mullvad/mullvadvpn-app pull request #6278
Opened 2024-05-24 11:14 UTC by niklasberglund

In this branch the tests are running against staging production instead of production. The following Linear tickets have been addressed:
* Create client for partner API and use partner API for adding time to temporary accounts(https://linear.app/mullvad/issue/IOS-611/create-a-client-for-partner-api)
* Store test artifacts on GitHub to ease debugging(https://linear.app/mullvad/issue/IOS-614/store-test-artifacts-on-github)
* Store logs from debug builds as artifacts(https://linear.app/mullvad/issue/IOS-623/store-logs-from-debug-builds)
* Generate new temporary accounts for tests instead of using persistent accounts which might expire or have too many devices(https://linear.app/mullvad/issue/IOS-613/add-ability-to-generate-an-account-per-test)
* Run end to end tests in staging environment(https://linear.app/mullvad/issue/IOS-612/run-end-to-end-tests-in-staging-environment)
* Retry login when failing(https://linear.app/mullvad/issue/IOS-622/attempt-login-three-times-before-failing-test)

Emils also fixed an issue with the API client did not work with staging.

When running tests against staging instead of production there was some unexpected issues which has been addressed too, such as timing issues caused by staging responding faster than production and differences in number location and relay availability.

Regressions in `main` has also been adressed in this PR, and an input parameter was added for when the workflow is manually triggered. You can now optionally specify a test case/suite to run. The format must be `MullvadVPNUITests/test-suite-name/test-case-name` for example `MullvadVPNUITests/RelayTests/testAppConnection` to run `testAppConnection` or `MullvadVPNUITests/RelayTests` to run all test cases under the suite `RelayTests`.
![image](https://github.com/mullvad/mullvadvpn-app/assets/331986/aa720ff5-d3de-40bb-9db2-4a7326c41e41)

To try out the changes in this PR you might want to run all end to end tests. Do so either by triggering the workflow and specifying branch `create-a-client-for-partner-api-ios-611` https://github.com/mullvad/mullvadvpn-app/actions/workflows/ios-end-to-end-tests.yml or by running them all locally from Xcode. 

If running the tests locally you must first make sure your `UITests.xcconfig` has the two new configuration properties introduced:
```
// URL for Mullvad provided JSON data with information about the connection. https://am.i.mullvad.net/json for production, https://am.i.stagemole.eu/json for staging.
AM_I_JSON_URL = https:/${}/am.i.stagemole.eu/json

// Specify whether app logs should be extracted and attached to test report for failing tests
ATTACH_APP_LOGS_ON_FAILURE = 0
```

⚠️ Note that there's a backend bug causing connecting to relay to sometimes fail when doing so immediately after creating an account and adding time to it using partner API. `testAppConnection` and maybe also `testCustomDNS` are expected to sometimes fail with `XCTAssertTrue failed - Failed to verify that the Internet can be acccessed` ⚠️

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)

2024-05-27 14:29 UTC, rablador requested changes
> Reviewed 5 of 6 files at r1, 55 of 55 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: all files reviewed, 12 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPN/Views/StatusImageView.swift` line 44 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NytejltB7bFpvLuPiji:-NytejltB7bFpvLuPijj:b-z6agww) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPN/Views/StatusImageView.swift#L44)):*
> ```Swift
>         // swiftlint:disable:next unused_setter_value
>         set {
>             print("This accessibilityValue property is get only")
> ```

I think we can go with a `fatalError()` here instead since it would be a programmer error to use the setter.
___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuBegeDU-mEC5ODGHj:-NyuBegeDU-mEC5ODGHk:by4u4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/RelayTests.swift#L168)):*
> ```Swift
>         removeFirewallRulesInTearDown = true
> 
>         addTeardownBlock {
> ```

Maybe put the contents in this teardown to a shared function istead?
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuDATtE2-_GUa9sDWb:-NyuDATtE2-_GUa9sDWc:bbnrsu5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L41)):*
> ```Swift
> 
>     /// Throttle what's in the callback. This is used for throttling requests to the app API. All requests should be throttled or else we might be rate limited. 5 requests per second allowed.
>     private func throttle(callback: @escaping () -> Void) {
> ```

Combine lib has a throttle function: `throttle(for:scheduler:latest:)`. You can find an example of it in `PacketTunnelPathObserver`.
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 98 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuDdh_2GTTkoC2Mnor:-NyuDdh_2GTTkoC2Mnos:b-gmjzb9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L98)):*
> ```Swift
>                 requestError = MullvadAPIError.requestError
>                 requestCompletedExpectation.fulfill()
>             }
> ```

`requestCompletedExpectation.fulfill()` is same for both try and catch and can be moved outside.
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 118 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuE-_H3B7kNxYKBJdh:-NyuE-_H3B7kNxYKBJdi:b-gmjzb9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L118)):*
> ```Swift
>             requestError = MullvadAPIError.requestError
>             requestCompletedExpectation.fulfill()
>         }
> ```

`requestCompletedExpectation.fulfill()` is same for both try and catch and can be moved outside.
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 139 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuE1WK03aKC8vxbho7:-NyuE1WK03aKC8vxbho8:b-gmjzb9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L139)):*
> ```Swift
>                 addDeviceError = MullvadAPIError.requestError
>                 requestCompletedExpectation.fulfill()
>             }
> ```

`requestCompletedExpectation.fulfill()` is same for both try and catch and can be moved outside.
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuE8fH4QqhYKKhd3dO:-NyuE8fH4QqhYKKhd3dP:b-gmjzb9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L168)):*
> ```Swift
>                 requestError = MullvadAPIError.requestError
>                 requestCompletedExpectation.fulfill()
>             }
> ```

`requestCompletedExpectation.fulfill()` is same for both try and catch and can be moved outside.
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 190 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuEB0x7hCLollVDVD8:-NyuEB0x7hCLollVDVD9:b-gmjzb9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L190)):*
> ```Swift
>                 requestError = MullvadAPIError.requestError
>                 requestCompletedExpectation.fulfill()
>             }
> ```

`requestCompletedExpectation.fulfill()` is same for both try and catch and can be moved outside.
___
*[`ios/MullvadVPNUITests/Networking/PartnerAPIClient.swift` line 89 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuIJlQDZDhX6u7tIUN:-NyuIJlQDZDhX6u7tIUO:btu5ip3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Networking/PartnerAPIClient.swift#L89)):*
> ```Swift
>                   error == nil else {
>                 XCTFail("Error: \(error?.localizedDescription ?? "Unknown error")")
>                 return
> ```

We should probably fulfull the expectation here as well to be consistent with the rest of the function.
___
*[`ios/MullvadVPNUITests/Pages/LoginPage.swift` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuP3Ed1ELok9MMCw7u:-NyuP3Ed1ELok9MMCw7v:b6uqf9q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Pages/LoginPage.swift#L42)):*
> ```Swift
>     }
> 
>     @discardableResult public func verifySuccessIconShown() -> Self {
> ```

I see why this works now, but is it reliable long-term? Hard check at 0.2 secs seems prone to timing issues depending on devide and/or platform in the future.
___
*[`ios/MullvadVPNUITests/Pages/LoginPage.swift` line 72 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuPVgTAgAg7FgCVa0A:-NyuPVgTAgAg7FgCVa0B:b-e0b4jc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Pages/LoginPage.swift#L72)):*
> ```Swift
> 
>     /// Wait for success icon to be shown. Returns true if shown, false if timing out without the icon being shown
>     func waitForSuccessIcon() throws -> Self {
> ```

This function is not used anywhere.
___
*[`ios/MullvadVPNUITests/Pages/SelectLocationPage.swift` line 74 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuQAar8Q7oDIBsZnhn:-NyuQAar8Q7oDIBsZnho:b8lsxop) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Pages/SelectLocationPage.swift#L74)):*
> ```Swift
>             .matching(identifier: AccessibilityIdentifier.openCustomListsMenuButton.rawValue).allElementsBoundByIndex
> 
>         for ellipsisButton in customListEllipsisButtons where ellipsisButton.isHittable {
> ```

This is a workaround for the weird behavior of the select location view headers. Would be good to have a comment on why we do this.


<!-- Sent from Reviewable.io -->

2024-05-30 08:02 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: 4 of 60 files reviewed, 11 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Views/StatusImageView.swift` line 44 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NytejltB7bFpvLuPiji:-Nz2W83w8r5T9RCBhfHZ:b-khhn0l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPN/Views/StatusImageView.swift#L44)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I think we can go with a `fatalError()` here instead since it would be a programmer error to use the setter.
</blockquote></details>

Good point, sounds like good use of `fatalError()`
___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuBegeDU-mEC5ODGHj:-Nz2WnKd78-aeV6R-Oi-:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/RelayTests.swift#L168)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Maybe put the contents in this teardown to a shared function istead?
</blockquote></details>

Done
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuDATtE2-_GUa9sDWb:-Nz7VnppDEjGgwIvHAE0:bm87le8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L41)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Combine lib has a throttle function: `throttle(for:scheduler:latest:)`. You can find an example of it in `PacketTunnelPathObserver`.
</blockquote></details>

We had an AFK talk about not using Combine framework's throttle because it's more oriented towards publishing data changes
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 98 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuDdh_2GTTkoC2Mnor:-Nz2YgNq5QvG32J0vAZ2:bhx777w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L98)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

`requestCompletedExpectation.fulfill()` is same for both try and catch and can be moved outside.
</blockquote></details>

Ah yes. Moved it outside.
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 118 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuE-_H3B7kNxYKBJdh:-Nz2YvxX9oh2kjtdjNY-:b-84847m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L118)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

`requestCompletedExpectation.fulfill()` is same for both try and catch and can be moved outside.
</blockquote></details>

Moved
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 139 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuE1WK03aKC8vxbho7:-Nz2ZAju04-Cd48lPSkV:b-84847m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L139)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

`requestCompletedExpectation.fulfill()` is same for both try and catch and can be moved outside.
</blockquote></details>

Moved
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 168 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuE8fH4QqhYKKhd3dO:-Nz2ZBU---FpwW_j4aqc:b-84847m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L168)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

`requestCompletedExpectation.fulfill()` is same for both try and catch and can be moved outside.
</blockquote></details>

Moved
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 190 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuEB0x7hCLollVDVD8:-Nz2ZLxr6D5gHvLseBeE:b-84847m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L190)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

`requestCompletedExpectation.fulfill()` is same for both try and catch and can be moved outside.
</blockquote></details>

Moved
___
*[`ios/MullvadVPNUITests/Networking/PartnerAPIClient.swift` line 89 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuIJlQDZDhX6u7tIUN:-Nz3vkp432o0o1RbcYJv:b-d6ej7w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Networking/PartnerAPIClient.swift#L89)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

We should probably fulfull the expectation here as well to be consistent with the rest of the function.
</blockquote></details>

I like it. Fulfilling the expectation now, and asserting that there is no error.
___
*[`ios/MullvadVPNUITests/Pages/LoginPage.swift` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuP3Ed1ELok9MMCw7u:-NyyF3gQDN4ylNpOYo4P:bx9jsym) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Pages/LoginPage.swift#L42)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I see why this works now, but is it reliable long-term? Hard check at 0.2 secs seems prone to timing issues depending on devide and/or platform in the future.
</blockquote></details>

`waitForElement` is unreliable because the polling is slower. So polling every 0.2 seconds is an improvement, but it's not bullet proof for any future changes. It might work fine with a shorter polling interval too, but if the success icon is shown for less than 0.2 seconds it might start feeling like flickering.

I can't think of a more reliable way to do it, I think it's inevitable that if the app allows the icon to show for a very short time then the polling interval must be adjusted. How do you think?
___
*[`ios/MullvadVPNUITests/Pages/LoginPage.swift` line 72 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuPVgTAgAg7FgCVa0A:-Nz3lb3m5jv9vCsCN-N8:ba3dfob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Pages/LoginPage.swift#L72)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This function is not used anywhere.
</blockquote></details>

Removed
___
*[`ios/MullvadVPNUITests/Pages/SelectLocationPage.swift` line 74 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuQAar8Q7oDIBsZnhn:-Nz3q_EN7eqKrF2a2duM:b-ajwuso) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Pages/SelectLocationPage.swift#L74)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This is a workaround for the weird behavior of the select location view headers. Would be good to have a comment on why we do this.
</blockquote></details>

Good idea. Added comment


<!-- Sent from Reviewable.io -->

2024-05-30 09:20 UTC, rablador requested changes
> Reviewed 52 of 55 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 41 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuDATtE2-_GUa9sDWb:-Nz7mK6H8YQfjhAq9szG:b-1buhpe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L41)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

We had an AFK talk about not using Combine framework's throttle because it's more oriented towards publishing data changes
</blockquote></details>

Yeah, let's drop this one.
___
*[`ios/MullvadVPNUITests/Pages/LoginPage.swift` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NyuP3Ed1ELok9MMCw7u:-Nz7mv_m2j9JL0L0TNYb:b-6aouk7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6f75334b9b2d88d08e443ccef8524cd093f3617f/ios/MullvadVPNUITests/Pages/LoginPage.swift#L42)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

`waitForElement` is unreliable because the polling is slower. So polling every 0.2 seconds is an improvement, but it's not bullet proof for any future changes. It might work fine with a shorter polling interval too, but if the success icon is shown for less than 0.2 seconds it might start feeling like flickering.

I can't think of a more reliable way to do it, I think it's inevitable that if the app allows the icon to show for a very short time then the polling interval must be adjusted. How do you think?
</blockquote></details>

Let's keep it this way.
___
*[`dist-assets/binaries` line 1 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-Nz7nFux-poiygz2F0nm:-Nz7nFux-poiygz2F0nn:b3kz93o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb3130a5abc86c3175b32cc7b2719796580be3c8/dist-assets/binaries#L1)):*
> ```
> Subproject commit 0d9d7c09e14a3b661575d536c2af6f27977d8e45
> ```

Why is this changed?


<!-- Sent from Reviewable.io -->

2024-05-30 11:31 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`dist-assets/binaries` line 1 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-Nz7nFux-poiygz2F0nm:-Nz8Fuuw7v3UQXt7JGut:b-kzgltr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cb3130a5abc86c3175b32cc7b2719796580be3c8/dist-assets/binaries#L1)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Why is this changed?
</blockquote></details>

This branch has a commit from @pinkisemils which included changes to `dist-assets` under a submodule and it created merge conflicts. I'm not sure about the details but Emils asked me to modify the commit and drop those changes.


<!-- Sent from Reviewable.io -->

2024-05-30 12:47 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-05-30 14:12 UTC, rablador approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 247 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-Nz8psBI1zm-aFH1eYZT:-Nz8psBI1zm-aFH1eYZU:benrpp3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9e74b303a70034e24910ce328fae27c57fdf70a/ios/MullvadVPNUITests/RelayTests.swift#L247)):*
> ```Swift
>     }
> 
>     /// Connect to a realy in the default country and city, get name and IP address of the relay the app successfully connects to. Assumes user is logged on and at tunnel control page.
> ```

Nit: relay


<!-- Sent from Reviewable.io -->

2024-06-03 06:34 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)



<!-- Sent from Reviewable.io -->

2024-06-04 11:21 UTC, rablador approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: all files reviewed, 6 unresolved discussions (waiting on @niklasberglund)



<!-- Sent from Reviewable.io -->

2024-06-04 14:35 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: 57 of 60 files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPNUITests/RelayTests.swift` line 247 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-Nz8psBI1zm-aFH1eYZT:-NzYetJj4LsO7syLtuzf:b-1dcph8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a9e74b303a70034e24910ce328fae27c57fdf70a/ios/MullvadVPNUITests/RelayTests.swift#L247)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: relay
</blockquote></details>

Corrected
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 41 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NzTEQ0Z8-iRY2pfLxNS:-NzY9NDoDUdnSZQN10AC:b9hbeo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e1078648f343005d35ce49c7c212fc916facfec/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L41)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This is only making sure each request is done at least .25 seconds after the previous one, it's not making sure only 5 requests per seconds are allowed.
If we want to make that happen, we should either use a token bucket, or have a custom rate limiter.
</blockquote></details>

5 requests per second is the maximum allowed by the API, the throttling makes sure we are well within this limit. I think it is a feature that we're not near the 5 times per second limit? 😊 Clarified the comment a bit
___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 112 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NzTHdxQ9AAzkgMBugUn:-NzY9ggS8Zp7mJFxpXJV:b-qgjuk3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e1078648f343005d35ce49c7c212fc916facfec/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L112)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Shouldn't we throttle this too ?
</blockquote></details>

Added throttling to this too 👍
___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 58 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NzTASJU6tOh4SV_guDH:-NzYAAph9PnI6zm9ddoO:blivmil) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e1078648f343005d35ce49c7c212fc916facfec/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L58)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

From that function name alone, I definitely did not expect the account to be deleted. 
Why not call it `deleteAccountWithTime` instead ?
</blockquote></details>

It's a good point. I think the issue might be in the documentation. The account is "borrowed" - if a partner API token has been configured it is a temporary account which will be deleted here. If it is a reused account(`HAS_TIME_ACCOUNT_NUMBER`) nothing will be done.

See improved documentation for `returnAccountWithTime()` and `getAccountWithTime()`. How do you think?


<!-- Sent from Reviewable.io -->

2024-06-04 14:37 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: 57 of 60 files reviewed, 6 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPNUITests/Test base classes/LoggedInWithTimeUITestCase.swift` line 45 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NzTJX3-4RoYSdTp4BXD:-NzYfQBqArBJV5P6t2fh:bhz48qh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e1078648f343005d35ce49c7c212fc916facfec/ios/MullvadVPNUITests/Test%20base%20classes/LoggedInWithTimeUITestCase.swift#L45)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Why would terminating the app ensure there is internet connectivity ?
</blockquote></details>

Beats me! 😄 This line didn't make much sense - neither code nor comment.  It is not needed since the app is not launched in this teardown, and terminating the app wouldn't cause a disconnect. I removed the entire line.


<!-- Sent from Reviewable.io -->

2024-06-07 08:06 UTC, buggmagnet reviewed
> Reviewed 1 of 2 files at r8, 2 of 3 files at r9, 2 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: 59 of 60 files reviewed, 4 unresolved discussions (waiting on @niklasberglund and @rablador)



<!-- Sent from Reviewable.io -->

2024-06-07 09:15 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: 58 of 60 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift` line 41 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NzTEQ0Z8-iRY2pfLxNS:-NzlymLl1rzymeyqo9ai:beaweuw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e1078648f343005d35ce49c7c212fc916facfec/ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift#L41)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

5 requests per second is the maximum allowed by the API, the throttling makes sure we are well within this limit. I think it is a feature that we're not near the 5 times per second limit? 😊 Clarified the comment a bit
</blockquote></details>

@buggmagnet see comment added below regarding "throttle" implementation ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift:54


<!-- Sent from Reviewable.io -->

2024-06-07 11:51 UTC, rablador approved these changes
> Reviewed 1 of 3 files at r9, 3 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @niklasberglund)

___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 58 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NzTASJU6tOh4SV_guDH:-NzmXGDJE3ioibt7ENR7:b-4y6h6q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e1078648f343005d35ce49c7c212fc916facfec/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L58)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

It's a good point. I think the issue might be in the documentation. The account is "borrowed" - if a partner API token has been configured it is a temporary account which will be deleted here. If it is a reused account(`HAS_TIME_ACCOUNT_NUMBER`) nothing will be done.

See improved documentation for `returnAccountWithTime()` and `getAccountWithTime()`. How do you think?
</blockquote></details>

I think the wording is the problem, with "return" meaning the return of a borrowed account rather than return as in "get".


<!-- Sent from Reviewable.io -->

2024-06-07 14:18 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-:-Nzn3GsPEPIq3gNducI8:b-qcfkkb)* status: 59 of 60 files reviewed, 1 unresolved discussion (waiting on @niklasberglund and @rablador)



<!-- Sent from Reviewable.io -->

2024-06-10 06:11 UTC, buggmagnet requested changes
> Reviewed 1 of 10 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: 53 of 63 files reviewed, 1 unresolved discussion (waiting on @niklasberglund and @rablador)



<!-- Sent from Reviewable.io -->

2024-06-10 06:14 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: 53 of 63 files reviewed, 2 unresolved discussions (waiting on @niklasberglund and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 0 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-O--m48x1IH6_IJCV2Gw:-O--m48x1IH6_IJCV2Gx:b-2pfa04) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bce1ebd9e36449331c0fb068be2dd8ce011989e4/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L0)):*
Let's undelete this


<!-- Sent from Reviewable.io -->

2024-06-10 07:34 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: 49 of 63 files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line  at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-O--m48x1IH6_IJCV2Gw:-O-01O-hEez0S3Oc-jMX:b1jzsuz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bce1ebd9e36449331c0fb068be2dd8ce011989e4/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's undelete this
</blockquote></details>

Undeleted
___
*[`ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift` line 58 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-NzTASJU6tOh4SV_guDH:-O-03HqE52Jcx6rdaPOl:b-8d2e2b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7e1078648f343005d35ce49c7c212fc916facfec/ios/MullvadVPNUITests/Test%20base%20classes/BaseUITestCase.swift#L58)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I think the wording is the problem, with "return" meaning the return of a borrowed account rather than return as in "get".
</blockquote></details>

See suggested rename `returnAccountWithTime` => `deleteTemporaryAccountWithTime`(and same for accoun without time)


<!-- Sent from Reviewable.io -->

2024-06-10 11:12 UTC, buggmagnet approved these changes
> Reviewed 1 of 1 files at r12, 7 of 10 files at r13, 6 of 6 files at r14, 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/Base/BaseUITestCase.swift` line 60 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6278#-O-0mBiM6ss1kjcoeHD2:-O-0mBiM6ss1kjcoeHD3:bbfyilp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f660c518220de7683e7a3ecb307b10ebe95588a3/ios/MullvadVPNUITests/Base/BaseUITestCase.swift#L60)):*
> ```Swift
> 
>     /// Delete temporary account with time if a temporary account was used
>     func deleteTemporaryAccountWithTime(accountNumber: String) {
> ```

Pairing up with Niklas, we are deciding to rename this `deleteAccount(accountNumber: String)` .

We want to create a strucutre for both accounts, and accounts created by the partner API, both using an `Account` protocol, that the `BaseUITestCase` will know whether to call the partner API to delete or not. 

This will come in a future PR.


<!-- Sent from Reviewable.io -->

2024-06-10 11:13 UTC, merged