Fix conncheck to work on staging environment
mullvad/mullvadvpn-app pull request #6302
Opened 2024-05-30 08:57 UTC by buggmagnet

This PR removes hard coded mentions of `mullvad.net` to replace them by a hostname defined in `Api.xcconfig` instead.
This enables conncheck (`am.i.mullvad.net`) working on both debug and staging environments.

@niklasberglund : I've tagged you because I explicitly didn't touch the `mullvad.net` mentions in the UITests (`Networking.swift`). 
Let's discuss this to see if we want to make changes there as well.

2024-05-30 09:06 UTC, niklasberglund requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6302)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6302#-Nz7iciIBJB4wsq2vN-k:-Nz7iciIBJB4wsq2vN-l:by7q78k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/883ed090b4fb343d5f4922f3a1c7f0f853e98ff7/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L24)):*
> ```Swift
> 
>         var host: String {
>             "\(rawValue).am.i.\(ApplicationConfiguration.hostName)"
> ```

Nice, but what if the am I hostname was configurable in `API.xcconfig` as well? It is used by tests too, currently its in `UITests.xcconfig` but could be removed from there then 

```
// URL for Mullvad provided JSON data with information about the connection. https://am.i.mullvad.net/json for production, https://am.i.stagemole.eu/json for staging.
AM_I_JSON_URL = https:/${}/am.i.stagemole.eu/json
```
___
*[`ios/Shared/ApplicationConfiguration.swift` line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6302#-Nz7jVIS4DL15_ELkUic:-Nz7jVIS4DL15_ELkUid:bj4o107) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/883ed090b4fb343d5f4922f3a1c7f0f853e98ff7/ios/Shared/ApplicationConfiguration.swift#L78)):*
> ```Swift
> }
> 
> // swiftlint:enable force_cast
> ```

I think the re-enabling of `force_cast` could be much higher up? Looks like there's only two force casts and both are shortly after the `disable`.


<!-- Sent from Reviewable.io -->

2024-05-31 11:30 UTC, niklasberglund requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6302)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPNTests/MullvadVPN/GeneralAPIs/OutgoingConnectionProxyTests.swift` line 14 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6302#-NzDPcPSEKjKiYcu-pHe:-NzDPcPTDRZS-_16oOoL:b-n4kjwu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58cc4b4d1f7df3ff92c4ff22e2a3eaac7d1729c2/ios/MullvadVPNTests/MullvadVPN/GeneralAPIs/OutgoingConnectionProxyTests.swift#L14)):*
> ```Swift
>     private var mockIPV6ConnectionData: Data!
>     private var mockIPV4ConnectionData: Data!
>     private let hostname = "mullvad.net"
> ```

Should this still be hard coded?


<!-- Sent from Reviewable.io -->

2024-06-03 12:30 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6302)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @niklasberglund)

___
*[`ios/MullvadVPNTests/MullvadVPN/GeneralAPIs/OutgoingConnectionProxyTests.swift` line 14 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6302#-NzDPcPSEKjKiYcu-pHe:-NzT2YmJBBVvyp_ZUZLd:b-pljj9d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58cc4b4d1f7df3ff92c4ff22e2a3eaac7d1729c2/ios/MullvadVPNTests/MullvadVPN/GeneralAPIs/OutgoingConnectionProxyTests.swift#L14)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Should this still be hard coded?
</blockquote></details>

if we are going to use these URLs cross test targets then I think we need to pack them in `ApplicationConfiguration` or a another object keeps all URLs.
___
*[`ios/Shared/ApplicationConfiguration.swift` line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6302#-Nz7jVIS4DL15_ELkUic:-NzT3hDi6i6RaZ2meKLL:b-q9li94) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/883ed090b4fb343d5f4922f3a1c7f0f853e98ff7/ios/Shared/ApplicationConfiguration.swift#L78)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

I think the re-enabling of `force_cast` could be much higher up? Looks like there's only two force casts and both are shortly after the `disable`.
</blockquote></details>

nit: disabling and enabling can be taken place for these two properties


<!-- Sent from Reviewable.io -->

2024-06-03 13:44 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6302)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6302#-Nz7iciIBJB4wsq2vN-k:-NzTKjtmDlP2Druj51PN:b-6r17of) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/883ed090b4fb343d5f4922f3a1c7f0f853e98ff7/ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift#L24)):*
Yes, I would rather keep this PR small and make changes in `Networking.swift` in a separate PR. 

> but what if the am I hostname was configurable in `API.xcconfig` as well?
That is the case currently. 
___
*[`ios/MullvadVPNTests/MullvadVPN/GeneralAPIs/OutgoingConnectionProxyTests.swift` line 14 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6302#-NzDPcPSEKjKiYcu-pHe:-NzTK81X7CnuUBpKQu-K:b-2u60vf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/58cc4b4d1f7df3ff92c4ff22e2a3eaac7d1729c2/ios/MullvadVPNTests/MullvadVPN/GeneralAPIs/OutgoingConnectionProxyTests.swift#L14)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

if we are going to use these URLs cross test targets then I think we need to pack them in `ApplicationConfiguration` or a another object keeps all URLs.
</blockquote></details>

It's only for a unit test, it doesn't any networking at all, so it doesn't matter.
___
*[`ios/Shared/ApplicationConfiguration.swift` line 78 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6302#-Nz7jVIS4DL15_ELkUic:-NzTKWvJB7T28K9gqDNk:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/883ed090b4fb343d5f4922f3a1c7f0f853e98ff7/ios/Shared/ApplicationConfiguration.swift#L78)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit: disabling and enabling can be taken place for these two properties
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-05 15:36 UTC, niklasberglund approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6302#-:-Nzd1ioK4Rc_-kZqvlW9:bnfp4nl)* status: 0 of 7 files reviewed, 3 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-06-10 06:17 UTC, merged