Android api access method
mullvad/mullvadvpn-app pull request #6319
Opened 2024-06-04 15:19 UTC by Pururun

Currently not finished:

- Missing colors and margins from design
- Copy needs to be updated
- No tests
- Form validation can be improved, a lot.

2024-06-04 19:32 UTC, Rawa reviewed
> Reviewed 30 of 54 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 30 of 54 files reviewed, 21 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/TestMethodButton.kt` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZVtm449koURpY7kYv:-NzZVtm449koURpY7kYw:b9y6ymk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/TestMethodButton.kt#L41)):*
> ```Kotlin
>             testMethodState?.let {
>                 {
>                     when (testMethodState) {
> ```

Unnecessary let break out this to a separate function
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/SaveApiAccessMethodDialog.kt` line 94 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZWhY5DsTR6HrEsjNS:-NzZWhY5DsTR6HrEsjNT:bkira0w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/SaveApiAccessMethodDialog.kt#L94)):*
> ```Kotlin
>                     stringResource(
>                         id =
>                             when (state) {
> ```

Break out at separate function
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/ApiAccessMethodDetailsUiStatePreviewParameterProvider.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZWq_I6XLLEojWDXfd:-NzZWq_I6XLLEojWDXfe:b2me46j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/ApiAccessMethodDetailsUiStatePreviewParameterProvider.kt#L10)):*
> ```Kotlin
>     override val values: Sequence<ApiAccessMethodDetailsUiState> =
>         sequenceOf(
>             ApiAccessMethodDetailsUiState.Loading(shadowsocks.id),
> ```

Nice, it is too bad there is no easy way to inject dummy data from other PreviewParameterProviders. :cry: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt` line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZXDwP7H7abfz8fHCl:-NzZXDwP7H7abfz8fHCm:b-77za3m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt#L70)):*
> ```Kotlin
>             navigator.navigate(ApiAccessMethodInfoDialogDestination) { launchSingleTop = true }
>         },
>         onBackClick = { navigator.navigateUp() }
> ```

navigator::navigateUp
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt` line 94 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZXPVSEe_nH-bcZI-q:-NzZXPVSEe_nH-bcZI-r:b-i2h1yn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt#L94)):*
> ```Kotlin
>             Spacer(modifier = Modifier.height(Dimens.verticalSpace))
>             state.apiAccessMethods.forEachIndexed { index, apiAccessMethod ->
>                 if (index != 0) {
> ```

I usually find it a bit more clear to skip the last diver instead, so content of `ApiAccessMethodItem` gets more focus.

```
                if(index != state.apiAccessMethods.lastIndex) {
                    HorizontalDivider()
                }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt` line 135 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZYZ6E07aQ20p6Krkk:-NzZYZ6E07aQ20p6Krkl:bkhghwk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt#L135)):*
> ```Kotlin
>             Modifier.padding(
>                 start = Dimens.sideMargin,
>                 end = Dimens.sideMargin,
> ```

= `horizontal`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt` line 148 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZZ9Dk1-WgQBMFkycg:-NzZZ9Dl7UHCfrIUrh2z:bcv502w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt#L148)):*
> ```Kotlin
>     ) { modifier: Modifier ->
>         Column(modifier = modifier) {
>             when (state) {
> ```

Nice :+1: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt` line 173 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZZJMW7u-FVGG3OO6m:-NzZZJMW7u-FVGG3OO6n:b-8c4f4n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt#L173)):*
> ```Kotlin
>     onUseMethodClicked: () -> Unit
> ) {
>     if (state.canBeEdited) {
> ```

editable
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt` line 142 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZ_67G3Dcb85SbZJiF:-NzZ_67G3Dcb85SbZJiG:b-a2ki8a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt#L142)):*
> ```Kotlin
> 
> @Composable
> fun EditApiAccessMethodScreen(
> ```

Considering how complex this function is I think it looks really nice. :star: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt` line 172 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZ_GzLAlMj8-JwTyIc:-NzZ_GzLAlMj8-JwTyId:b297xb4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt#L172)):*
> ```Kotlin
>             when (state) {
>                 is EditApiAccessMethodUiState.Loading -> Loading()
>                 is EditApiAccessMethodUiState.Content -> {
> ```

Maybe breakout to a content method, but then we have to pass all these parameters again.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt` line 310 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZ_edK51FY46yzP0az:-NzZ_edK51FY46yzP0b-:b-9flav4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt#L310)):*
> ```Kotlin
>     Spacer(modifier = Modifier.height(Dimens.verticalSpacer))
>     RemotePortInput(portFormData = formData.remotePort, onPortChanged = onPortChanged)
>     Spacer(modifier = Modifier.height(Dimens.verticalSpacer))
> ```

We use a lot of these `Spacer` probably this is a symptom of a unclear/misinterpreted design, but the padding should most likely be built into the fields so we don't have to have all these verticalSpacers everywhere. E.g if verticalSpacer is 16dp, ServerIpInput has vertical padding of 8dp so together with the other field they end up being 16dp. 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt` line 351 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZaKGe-fh5pTz2exqG:-NzZaKGe-fh5pTz2exqH:b-9t6hzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/ko [...]

2024-06-05 05:00 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 30 of 54 files reviewed, 21 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 190 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZiwSb3CFc-8FUPFGd:-NzajwkqApZc5e6HGQM-:b-iubh04) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L190)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Here we want to use zip from arrow, it makes everything more simple:
https://arrow-kt.io/learn/quickstart/migration/#zip-1

If we have a flat structure of FormData, we can simply assign each and every error directly to state.
</blockquote></details>

Realized as I slept on this, with zipOrAccumulate we have to have the same type of error. So we need to introduce a FormValidationError that then returns custom error for every field. It would look something like this:
```
sealed interface FormError

// This type would wrap domain error or introduce custom error
data object PortValidationError : FormError

data object FormError1 : FormError
data object FormError2 : FormError

fun validatePort(value: String): Either<PortValidationError, Port> =
    Port.fromString(value)
        .mapLeft { PortValidationError }

fun e2(): Either<FormError1, String> = TODO()

fun e3(): Either<FormError2, String> = TODO()

data class Socks5(val a: Port, val b: String, val c: String)

fun validate(port: String, b: String, c: String): Either<NonEmptyList<FormError>, Socks5> =
    zipOrAccumulate(
        validatePort(port),
        e2(),
        e3()
    ) { a: Port, b: String, c: String ->
        Socks5(a, b, c)
    }
```


<!-- Sent from Reviewable.io -->

2024-06-05 05:37 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 30 of 54 files reviewed, 25 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 190 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZiwSb3CFc-8FUPFGd:-Nzalhuh2Ajq_G-yccaC:b4h8zr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L190)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Realized as I slept on this, with zipOrAccumulate we have to have the same type of error. So we need to introduce a FormValidationError that then returns custom error for every field. It would look something like this:
```
sealed interface FormError

// This type would wrap domain error or introduce custom error
data object PortValidationError : FormError

data object FormError1 : FormError
data object FormError2 : FormError

fun validatePort(value: String): Either<PortValidationError, Port> =
    Port.fromString(value)
        .mapLeft { PortValidationError }

fun e2(): Either<FormError1, String> = TODO()

fun e3(): Either<FormError2, String> = TODO()

data class Socks5(val a: Port, val b: String, val c: String)

fun validate(port: String, b: String, c: String): Either<NonEmptyList<FormError>, Socks5> =
    zipOrAccumulate(
        validatePort(port),
        e2(),
        e3()
    ) { a: Port, b: String, c: String ->
        Socks5(a, b, c)
    }
```
</blockquote></details>

Then we would have to choose if we want a list of errors in the UiState, or retrieve them before we return. I was also playing around with other methods of solving this.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 281 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZjDLo6-G3MY-oCWYR:-Nzaq0a-Die6M0YnmXqA:by1x71z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L281)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I believe this should be part of `Port` (and maybe is?)
</blockquote></details>

Seems like we need to rebase to get access to it.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SaveApiAccessMethodViewModel.kt` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzasdFVEQjhQUfwNjnJ:-NzasdFVEQjhQUfwNjnK:bvx78ra) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SaveApiAccessMethodViewModel.kt#L33)):*
> ```Kotlin
>             viewModelScope.launch {
>                 val customProxy =
>                     newAccessMethod.apiAccessMethodType as? ApiAccessMethodType.CustomProxy
> ```

Could we receive a CustomProxy right away from Navigation?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SaveApiAccessMethodViewModel.kt` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzaqItf0LzPbXXyggF9:-NzaqItf0LzPbXXyggFA:bhrde4c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SaveApiAccessMethodViewModel.kt#L44)):*
> ```Kotlin
>     }
> 
>     fun save(afterSuccessful: Boolean = false) {
> ```

I believe this could possibly be easier if we just represent the UiState better.

Maybe something like this?
```
sealed TestingState {
    data object InProgress: TestingState
    sealed interface Result: TestingState {
        data object Success: Result
        data object Error: Result
    }
}

data class UiState(
     val testing: TestingState // (InProgress, Success, Error
     val isSaving: Boolean
)
```
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/ApiAccessMethod.kt` line 2 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-Nzat6fV4O6banjuimY7:-Nzat6fV4O6banjuimY8:b-ra3bk5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/ApiAccessMethod.kt#L2)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.lib.model
> ```

Nice :100: 
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/Cipher.kt` line 8 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-Nzat_Iw5pJ-0f56eh3f:-Nzat_Iw5pJ-0f56eh3g:bxuocoa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/Cipher.kt#L8)):*
> ```Kotlin
> @Parcelize
> @JvmInline
> value class Cipher private constructor(val value: String) : Parcelable {
> ```

Feels a bit duplicate to have both of these? Wouldn't the `enum class` be enough?


<!-- Sent from Reviewable.io -->

2024-06-05 07:13 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 30 of 54 files reviewed, 21 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/TestMethodButton.kt` line 41 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZVtm449koURpY7kYv:-Nzb1ryDEj6_Oyue3Wef:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/TestMethodButton.kt#L41)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Unnecessary let break out this to a separate function
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/SaveApiAccessMethodDialog.kt` line 94 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZWhY5DsTR6HrEsjNS:-Nzb2mjg6VTTi14W_1Cq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/SaveApiAccessMethodDialog.kt#L94)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Break out at separate function
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/ApiAccessMethodDetailsUiStatePreviewParameterProvider.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZWq_I6XLLEojWDXfd:-Nzb2nfk3XsZfNdUmWyb:b-ls1dfg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/ApiAccessMethodDetailsUiStatePreviewParameterProvider.kt#L10)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Nice, it is too bad there is no easy way to inject dummy data from other PreviewParameterProviders. :cry:
</blockquote></details>

Yeah it is quite annoying.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt` line 70 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZXDwP7H7abfz8fHCl:-Nzb34yc3irR1UnWtIfl:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt#L70)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

navigator::navigateUp
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt` line 94 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZXPVSEe_nH-bcZI-q:-Nzb3Ux-A8lumLLaxVc-:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt#L94)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I usually find it a bit more clear to skip the last diver instead, so content of `ApiAccessMethodItem` gets more focus.

```
                if(index != state.apiAccessMethods.lastIndex) {
                    HorizontalDivider()
                }
```
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt` line 135 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZYZ6E07aQ20p6Krkk:-Nzb3b3yBOcTUyg5Ymjw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt#L135)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

= `horizontal`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/ApiAccessMethodDetailsUiState.kt` line 16 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZc12M7bpv6jvvxiyI:-Nzb4hn5CXy_DVq_6bp_:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/ApiAccessMethodDetailsUiState.kt#L16)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`isEditable`
`isDisableable` (It looks terrible but it is a word :sweat_smile:)
`isCurrentMethod` or `isActive`
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/ApiAccessRepository.kt` line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZf_871mo9doLt8R6h:-Nzb5QQi31_tMKR_UnKM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/ApiAccessRepository.kt#L59)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

avoid prefixing with `flow`, it is better to be explicit with return type instead.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/TestApiAccessMethodUseCase.kt` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZh0mQ4k0V8WaKkRds:-Nzb5St53dxNDvHD_ZOU:bkmwfcs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/TestApiAccessMethodUseCase.kt#L30)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Is this to clear the result after some time? Feel like maybe this usecase should just of been a suspend, but maybe it is reused in other places as well?
</blockquote></details>

Yeah it is to clear the result. It is used in both `EditApiAccess` and `ApiAccessDetails`.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/TestApiAccessMethodUseCase.kt` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZfnhz-ZRDZEHqGGXD:-Nzb5nfL2LracNU0QJ0j:b5g0mb5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/TestApiAccessMethodUseCase.kt#L33)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Personally I like to use duration when we can, we should agree internally on this.

```
private const val TEST_METHOD_RESULT_TIME_MS = 1000L * 5
delay(TEST_METHOD_RESULT_TIME_MS)
```
vs
```
private const val TEST_METHOD_RESULT_DURATION = 5.seconds
delay(TEST_METHOD_RESULT_DURATION)
```
</blockquote></details>

I think partially it is because a duration is not a primitive, but yeah I agree that using durations are nicer.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ApiAccessMethodDetailsViewModel.kt` line 68 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZhnB6DW0by1ybQPrx:-Nzb6BfY7SZBPNcDlc8p:bg47qn4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ApiAccessMethodDetailsViewModel.kt#L68)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Can we cancel the test? Clear it? I can imagine if we call this usecase twice we will emit the `null` in the end again and possibly clear other reply to early?
</blockquote></details>

Yes we should probably have a way to clear the test, I guess it depends on what the expected behaviour of the button.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 281 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZjDLo6-G3MY-oCWYR:-Nzb6wUE30nlCy47yQJq [...]

2024-06-05 07:19 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 15 of 55 files reviewed, 20 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt` line 173 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZZJMW7u-FVGG3OO6m:-NzbF5YI2ynpnwSVL7vq:b-tta2ts) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt#L173)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

editable
</blockquote></details>

Was changed to `isEditable` as per as a later comment.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt` line 172 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZ_GzLAlMj8-JwTyIc:-NzbFCpv6Zgfs_-9081S:b-rza3o3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt#L172)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Maybe breakout to a content method, but then we have to pass all these parameters again.
</blockquote></details>

I think that would be just a bunch of code with not much use.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt` line 310 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZ_edK51FY46yzP0az:-NzbFK1y3HQBwKqgnFzf:b-uzu2om) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt#L310)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We use a lot of these `Spacer` probably this is a symptom of a unclear/misinterpreted design, but the padding should most likely be built into the fields so we don't have to have all these verticalSpacers everywhere. E.g if verticalSpacer is 16dp, ServerIpInput has vertical padding of 8dp so together with the other field they end up being 16dp.
</blockquote></details>

Agree, will improve it when I add the actual margins.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 160 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZidPL1Va73CuMMZPH:-NzbFtoz7lF5UaiseHmB:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L160)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Weird use of with, it didn't make it more clear i feel. Let's assign it first and then use maybe?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-05 11:43 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 13 of 56 files reviewed, 20 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/EditApiAccessMethodUiState.kt` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZdWVwDYIiWeBolekU:-NzcCMtEBXAlX2hjn6Wj:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/EditApiAccessMethodUiState.kt#L30)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Not sure I like this, it feels a bit weird a bit too complex and it feels like we will do tones of update when it is not really necessary. Maybe it is better with a complete flat structure, skipping `FormInputField` type.
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/EditApiAccessMethodUiState.kt` line 47 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZfDNY4iMwTaj1WhEh:-NzcCNvW2bwmvCK6iKnr:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/EditApiAccessMethodUiState.kt#L47)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Looks really weird to be, we will copy the entire object multiple times but it should not really be needed I think.
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 190 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZiwSb3CFc-8FUPFGd:-NzcCP4dB7eJCt2vTlwK:b-a0jjd9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L190)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Then we would have to choose if we want a list of errors in the UiState, or retrieve them before we return. I was also playing around with other methods of solving this.
</blockquote></details>

Updated after pair programming. 


<!-- Sent from Reviewable.io -->

2024-06-10 06:28 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 12 of 61 files reviewed, 20 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt` line 148 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZZ9Dk1-WgQBMFkycg:-O--pBuN9t4oT4DWHEZx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt#L148)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Nice :+1:
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt` line 310 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZ_edK51FY46yzP0az:-O--p-P56DXGB-n-lYj0:b-hsvuk4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt#L310)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Agree, will improve it when I add the actual margins.
</blockquote></details>

Replaced most spacers with padding.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt` line 351 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZaKGe-fh5pTz2exqG:-O--p5ns4SbD4ShH7Ino:b-68c25u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt#L351)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

There is an isError on InputTextField and I know the CustomTextField (which I also hate :sweat:). Not sure if we have a specific design here, but it would be nice if we make use of that if we don't have good reasoning for it. Maybe then we don't have to set this color as well?
</blockquote></details>

Added a generic textfield for api access method.


<!-- Sent from Reviewable.io -->

2024-06-10 09:05 UTC, Rawa reviewed
> Reviewed 4 of 21 files at r2, 6 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 21 of 61 files reviewed, 6 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/TestApiAccessMethodUseCase.kt` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZh0mQ4k0V8WaKkRds:-O-0H2DGDlKyuOX4Vnme:bgur8s3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/TestApiAccessMethodUseCase.kt#L30)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Yeah it is to clear the result. It is used in both `EditApiAccess` and `ApiAccessDetails`.
</blockquote></details>

I understand why it is a `flow` since it is convenient. But it would feel more correct if it was just a `suspend` function right away, and then the ViewModel does the wrapping for setting and emitting it's internal state. I could be worth spending some time seeing if it would make sense.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/TestApiAccessMethodUseCase.kt` line 12 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0I8-e-VejpHTLJlQU:-O-0I8-e-VejpHTLJlQV:bpp4df5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/TestApiAccessMethodUseCase.kt#L12)):*
> ```Kotlin
> 
> class TestApiAccessMethodUseCase(private val apiAccessRepository: ApiAccessRepository) {
>     suspend fun testApiAccessMethod(input: TestApiAccessMethodInput) = flow {
> ```

Depending on out come from issue below signature should be:

```
fun testApiAccessMethod(input: TestApiAccessMethodInput): Flow<TestApiAccessMethodState> or implicit return
```
or
```
suspend fun testApiAccessMethod(input: TestApiAccessMethodInput): Either<TestApiAccessMethodError, TestApiAccessMethodSuccess>
```
Not `suspend` and return `Flow`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 69 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0K-FD6_4wZcWe12te:-O-0K-FD6_4wZcWe12tf:bo5hek9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L69)):*
> ```Kotlin
>     init {
>         // If we are editing the api access method, fetch initial data
>         viewModelScope.launch {
> ```

This whole launch feels a bit weird, along with the `var` it requires, I know we talked about it but maybe we should take another stab at it to see if we can come up with a better way of doing it.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 156 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0Jl9k9YfUYzojnxMF:-O-0Jl9k9YfUYzojnxMG:bludrdp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L156)):*
> ```Kotlin
>         // Check if we have any unsaved changes
>         viewModelScope.launch {
>             if (initialData?.equals(formData.value) == true) {
> ```

== true
same as
`initialData == formData.value`?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NavigateButton.kt` line 33 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0KuDj1LXdsoU7rQFs:-O-0KuDk0fukstzPVvq0:b-xys55v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NavigateButton.kt#L33)):*
> ```Kotlin
>     IconButton(onClick = onNavigateClose) {
>         Icon(
>             modifier = Modifier.rotate(-90f),
> ```

Why do we have to rotate this one?


<!-- Sent from Reviewable.io -->

2024-06-10 09:11 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 21 of 61 files reviewed, 9 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt` line 115 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0OOnv4fR-6eSGjT12:-O-0OOnv4fR-6eSGjT13:boq3wda) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt#L115)):*
> ```Kotlin
>                     )
>                     .fillMaxWidth()
>                     .wrapContentHeight()
> ```

wrapContentHeight, is it needed? isn't that default behavior?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt` line 208 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0Oe4I7H0h5JikKi37:-O-0Oe4I7H0h5JikKi38:bl8a3uy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt#L208)):*
> ```Kotlin
>     )
>     if (state.isCurrentMethod) {
>         AlreadyCurrentText()
> ```

Nice and clean :star2: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt` line 235 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0OjoT10SV5ZhdBXsK:-O-0OjoT10SV5ZhdBXsL:bly3my6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt#L235)):*
> ```Kotlin
>         maxCharLength = ApiAccessMethodName.MAX_LENGTH,
>         errorText = nameError?.let { textResource(id = R.string.this_field_is_required) },
>         onSubmit = { focusManager.moveFocus(FocusDirection.Down) }
> ```

Do we really have to use FocusManger to do all this ourselves? Is something wrong with the default behavior? Shouldn't we use KeyboardOptions?
```
    TextField(
        ...
        keyboardOptions =
            KeyboardOptions(
                imeAction = ImeAction.Next,
                ...
            ),
         ...
    )
``` 


<!-- Sent from Reviewable.io -->

2024-06-10 09:32 UTC, Rawa reviewed
> Reviewed 1 of 21 files at r2, 2 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 20 of 65 files reviewed, 14 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 88 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0SdXZ1uT86hNml9tU:-O-0SdXZ1uT86hNml9tV:ba07uq5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L88)):*
> ```Kotlin
>     }
> 
>     fun updateName(name: String) {
> ```

personally I more like these functions as `onNameChanged`, but I'm not sure if we have any praxis for it. Maybe we should? 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 171 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0TAZl9scAHuRl-5eX:-O-0TAZl9scAHuRl-5eY:b-6qtuql) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L171)):*
> ```Kotlin
> 
>     private fun setUpInitialData(accessMethod: ApiAccessMethod) {
>         val initialFormData =
> ```

Maybe EditApiAccessFormData should have a companion to create it from a `CustomProxy`? Then we can just check if the apiAccessMethodType is CustomProxy, and if not throw the error.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 203 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0TbiTEcIz3bLBVdG4:-O-0TbiTEcIz3bLBVdG5:b5y7qdw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L203)):*
> ```Kotlin
> 
>     private fun EditApiAccessFormData.parseFormData(
>         skipNameValidation: Boolean
> ```

Is this to be able to test the access method w/o a name?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 307 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0UDKwCjykoQzIVL6k:-O-0UDKwCjykoQzIVL6l:blln7du) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L307)):*
> ```Kotlin
>     private fun parseName(
>         input: String,
>         noError: Boolean
> ```

I don't think noError should be part of `parseName` if we don't want any errors we shouldn't call the parseName to begin with.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 310 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0Ty1CA6A0R8Er2nNI:-O-0Ty1CA6A0R8Er2nNJ:bczqd86) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L310)):*
> ```Kotlin
>     ): EitherNel<InvalidDataError.NameError, ApiAccessMethodName> =
>         if (input.isBlank() && !noError) {
>             nonEmptyListOf(InvalidDataError.NameError.Required).left()
> ```

I believe there is an extension function called `nel()`

```InvalidDataError.NameError.Required.nel().left()```


<!-- Sent from Reviewable.io -->

2024-06-10 09:32 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 20 of 65 files reviewed, 14 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 310 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0Ty1CA6A0R8Er2nNI:-O-0UUZ7CDjg_t6qmNPy:b-6uaa5f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L310)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I believe there is an extension function called `nel()`

```InvalidDataError.NameError.Required.nel().left()```
</blockquote></details>

Edit: There is also `leftNel()`


<!-- Sent from Reviewable.io -->

2024-06-10 10:08 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 19 of 65 files reviewed, 13 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt` line 208 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0Oe4I7H0h5JikKi37:-O-0ZpxD7oogY0LVJDxg:b32vhw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt#L208)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Nice and clean :star2:
</blockquote></details>

:)
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 88 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0SdXZ1uT86hNml9tU:-O-0_RcD7IGGQ3TUzOr6:b-y21m6v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L88)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

personally I more like these functions as `onNameChanged`, but I'm not sure if we have any praxis for it. Maybe we should?
</blockquote></details>

I think it makes more sense with onXChanged, since that is what it does. Will change.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 156 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0Jl9k9YfUYzojnxMF:-O-0_gHd4uXrCsyQPqAW:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L156)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

== true
same as
`initialData == formData.value`?
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 171 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0TAZl9scAHuRl-5eX:-O-0_r9iBFNm-CFMWw9f:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L171)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Maybe EditApiAccessFormData should have a companion to create it from a `CustomProxy`? Then we can just check if the apiAccessMethodType is CustomProxy, and if not throw the error.
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 203 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0TbiTEcIz3bLBVdG4:-O-0bIFOA4nxFrDpFkDU:b2nhswy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L203)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Is this to be able to test the access method w/o a name?
</blockquote></details>

Yes
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 310 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0Ty1CA6A0R8Er2nNI:-O-0bXI02en1TcCAppN7:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L310)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Edit: There is also `leftNel()`
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NavigateButton.kt` line 33 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0KuDj1LXdsoU7rQFs:-O-0ZiSG6GgikLysq4AR:b-hs67k9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NavigateButton.kt#L33)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Why do we have to rotate this one?
</blockquote></details>

Copy paste error, removed.


<!-- Sent from Reviewable.io -->

2024-06-10 11:03 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 18 of 67 files reviewed, 13 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt` line 115 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0OOnv4fR-6eSGjT12:-O-0cLKe2Eu-AswKPDrE:b-gfenvq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt#L115)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

wrapContentHeight, is it needed? isn't that default behavior?
</blockquote></details>

I think that is some copy paste left over. Removed.


<!-- Sent from Reviewable.io -->

2024-06-10 13:05 UTC, Rawa reviewed
> Reviewed 6 of 54 files at r1, 2 of 21 files at r2, 1 of 12 files at r4, 2 of 18 files at r5, 3 of 13 files at r6.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 52 of 67 files reviewed, 11 unresolved discussions (waiting on @Pururun)

___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/NewAccessMethod.kt` line 12 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-1Ewoq46II5HwwQiIH:-O-1Ewoq46II5HwwQiII:b-38jet3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33b911d898bf33086e1982f9622c6f40c43b42ba/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/NewAccessMethod.kt#L12)):*
> ```Kotlin
>     val apiAccessMethodType: ApiAccessMethodType
> ) : Parcelable {
>     fun customProxy() = apiAccessMethodType as ApiAccessMethodType.CustomProxy
> ```

Shouldn't `val apiAccessMethodType: ApiAccessMethodType` be of this type to begin with?


<!-- Sent from Reviewable.io -->

2024-06-10 13:15 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 52 of 67 files reviewed, 12 unresolved discussions (waiting on @Pururun)

___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/ApiAccessMethodType.kt` line 6 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-1GYnPCxfa5dnCIP5W:-O-1FiQ60CZSNMQisMGl:b15dwu3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33b911d898bf33086e1982f9622c6f40c43b42ba/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/ApiAccessMethodType.kt#L6)):*
> ```Kotlin
> import kotlinx.parcelize.Parcelize
> 
> sealed interface ApiAccessMethodType : Parcelable {
> ```

Naming feels a bit weird here. I would expect type only to be the top level items here. But it actually contains the full connection details. 

I looked into the proto, there they call this level `AccessMethod` which sounds more correct. What we call ApiAccessMethod they call `AccessMethodSetting`


<!-- Sent from Reviewable.io -->

2024-06-10 13:16 UTC, Rawa reviewed
> Reviewed 9 of 54 files at r1, 1 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 62 of 67 files reviewed, 12 unresolved discussions (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2024-06-10 13:56 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 50 of 68 files reviewed, 9 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/SaveApiAccessMethodDialog.kt` line 41 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-19ouND6slfiVN6m_S:-O-1Pa5t0wXLAjn2Z2Bz:b-j1we20) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33b911d898bf33086e1982f9622c6f40c43b42ba/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/SaveApiAccessMethodDialog.kt#L41)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

:eyes: Konsist :heart: :sweat_smile:
</blockquote></details>

:raised_hands: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt` line 140 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-1AUIy0MsPSx9EK8CY:-O-1Pe6Y4ctibbhPkNCg:b32vhw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33b911d898bf33086e1982f9622c6f40c43b42ba/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt#L140)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This looks nice :star_struck:
</blockquote></details>

:)
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/EditApiAccessMethodUiState.kt` line 51 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-1Ak2UBNB4q5w9kIeE:-O-1PgA64pnofW0H5ly5:b32vhw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33b911d898bf33086e1982f9622c6f40c43b42ba/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/EditApiAccessMethodUiState.kt#L51)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Nice :star2:
</blockquote></details>

:)
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 307 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0UDKwCjykoQzIVL6k:-O-1PpUi5IVeojKC37pM:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L307)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I don't think noError should be part of `parseName` if we don't want any errors we shouldn't call the parseName to begin with.
</blockquote></details>

Done
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/NewAccessMethod.kt` line 12 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-1Ewoq46II5HwwQiIH:-O-1QoDQ4iROZwICVLMe:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33b911d898bf33086e1982f9622c6f40c43b42ba/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/NewAccessMethod.kt#L12)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Shouldn't `val apiAccessMethodType: ApiAccessMethodType` be of this type to begin with?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-10 14:18 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 47 of 68 files reviewed, 9 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt` line 235 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0OjoT10SV5ZhdBXsK:-O-1Vxqm7FasbBf2Hihf:b-grfh0b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditApiAccessMethodScreen.kt#L235)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Do we really have to use FocusManger to do all this ourselves? Is something wrong with the default behavior? Shouldn't we use KeyboardOptions?
```
    TextField(
        ...
        keyboardOptions =
            KeyboardOptions(
                imeAction = ImeAction.Next,
                ...
            ),
         ...
    )
```
</blockquote></details>

Added `ImeAction.Next` 


<!-- Sent from Reviewable.io -->

2024-06-10 21:28 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 47 of 68 files reviewed, 9 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 274 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-1BPMj8c8ZQOBRl15G:-O-2x2jc894DbG3__A71:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33b911d898bf33086e1982f9622c6f40c43b42ba/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L274)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should change these to be the eitherEffect syntax:

```
    private fun parseUsername(input: String): Either<InvalidDataError.UserNameError, String> = either {
        ensure(input.isNotBlank()) { InvalidDataError.UserNameError.Required }
        input
    }
```

Benefits are:
We don't have to explicitly say `left`, `right` on results.
Readability and more consice
Extensible if we want to extend the error set.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SaveApiAccessMethodViewModel.kt` line 81 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-1D9Cj7lfwbwKEQ61x:-O-328P53XCys1c_lsBM:bbvqmt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33b911d898bf33086e1982f9622c6f40c43b42ba/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SaveApiAccessMethodViewModel.kt#L81)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

If we navigate up, we leave the composable scope of the ViewModel, and it should be destroyed. Since the job was launched in ViewModelScope it should be cancelled automatically I believe?
</blockquote></details>

Yes that is true. Fixed.


<!-- Sent from Reviewable.io -->

2024-06-10 22:11 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 47 of 68 files reviewed, 9 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/TestApiAccessMethodUseCase.kt` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZh0mQ4k0V8WaKkRds:-O-3C8mgEMKN6mAjwl_y:bdycarn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/TestApiAccessMethodUseCase.kt#L30)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I understand why it is a `flow` since it is convenient. But it would feel more correct if it was just a `suspend` function right away, and then the ViewModel does the wrapping for setting and emitting it's internal state. I could be worth spending some time seeing if it would make sense.
</blockquote></details>

Removed the usecase
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/TestApiAccessMethodUseCase.kt` line 12 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-0I8-e-VejpHTLJlQU:-O-3CBly9nwDVkCrnPBC:b5d3n8d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b69466115f8e939ee947b1225cc5ebd0271a417/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/TestApiAccessMethodUseCase.kt#L12)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Depending on out come from issue below signature should be:

```
fun testApiAccessMethod(input: TestApiAccessMethodInput): Flow<TestApiAccessMethodState> or implicit return
```
or
```
suspend fun testApiAccessMethod(input: TestApiAccessMethodInput): Either<TestApiAccessMethodError, TestApiAccessMethodSuccess>
```
Not `suspend` and return `Flow`
</blockquote></details>

Removed the use case


<!-- Sent from Reviewable.io -->

2024-06-11 07:06 UTC, Rawa reviewed
> Reviewed 1 of 54 files at r1, 8 of 13 files at r9, 3 of 5 files at r10, 8 of 8 files at r12.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 66 of 69 files reviewed, 5 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/SaveApiAccessMethodDialog.kt` line 73 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-56HNW9JAxdEPslmCs:-O-56HNW9JAxdEPslmCt:b-o6g5u5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/290d8b54ae475e6ef11a5a570c818ef7ed822bd6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/SaveApiAccessMethodDialog.kt#L73)):*
> ```Kotlin
>     SaveApiAccessMethodDialog(
>         state = state,
>         onCancel = { backNavigator.navigateBack() },
> ```

`backNavigator::navigateBack`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/ApiAccessMethodTextField.kt` line 41 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-55zFO2u5Glyjj0KA_:-O-55zFO2u5Glyjj0KAa:b-okzehk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/290d8b54ae475e6ef11a5a570c818ef7ed822bd6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/ApiAccessMethodTextField.kt#L41)):*
> ```Kotlin
>         onValueChanged = onValueChanged,
>         onSubmit = {
>             if (imeAction == ImeAction.Done) {
> ```

Wouldn't this be done automatically? Can we add a comment why we have to do this?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ApiAccessMethodDetailsViewModel.kt` line 68 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-NzZhnB6DW0by1ybQPrx:-O-55YbK1fP90QAfvy1l:b9j59pn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/70dc9e17fe61c6ca0280ef8d0d110c88c59db516/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ApiAccessMethodDetailsViewModel.kt#L68)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Yes we should probably have a way to clear the test, I guess it depends on what the expected behaviour of the button.
</blockquote></details>

Depends on you discussions from with UX, but if we want to offer a cancel, we just need to save this job and then call cancel on it in the cancel method along with restoring the `testApiAccessMethodState` to null
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 196 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-54xXb1vKELORp--SU:-O-54xXb1vKELORp--SV:bku74g9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/290d8b54ae475e6ef11a5a570c818ef7ed822bd6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L196)):*
> ```Kotlin
>         }
> 
>     private fun parseIpAddress(input: String): Either<InvalidDataError.ServerIpError, String> =
> ```

This parsing turned out pretty darn nice :star2: 


<!-- Sent from Reviewable.io -->

2024-06-11 07:16 UTC, Rawa reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 66 of 69 files reviewed, 6 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 187 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-58WZBAgKSiNl7l_9c:-O-58WZBAgKSiNl7l_9d:bfbtura) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33b911d898bf33086e1982f9622c6f40c43b42ba/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L187)):*
> ```Kotlin
>     private fun EditApiAccessFormData.parseFormData(
>         skipNameValidation: Boolean
>     ): Either<
> ```

We can avoid using `NonEmptyList` by using `EitherNel` it is a bit more readable.
```
EitherNel<InvalidDataError, xxx>
```


<!-- Sent from Reviewable.io -->

2024-06-11 07:19 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 66 of 69 files reviewed, 7 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 189 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-58rOS5ABSyiO2SgHq:-O-58rOS5ABSyiO2SgHr:b-z1wi18) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33b911d898bf33086e1982f9622c6f40c43b42ba/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L189)):*
> ```Kotlin
>     ): Either<
>         NonEmptyList<InvalidDataError>,
>         Pair<ApiAccessMethodName, ApiAccessMethodType.CustomProxy>
> ```

Can we improve on this return type? :grimacing: Or maybe we should split the parsing even more to avoid it?

We could have:


```
parseFormData(): EitherNel<InvalidDataError, ApiAccessMethod> {
     // This would use the parseConnectionFormData to get the CustomProxy and parse the name
}

parseConnectionFormData(): EitherNel<InvalidDataError, ApiAccessMethodType.CustomProxy>
```

In this way we can get rid of the `skipNameValidation`, and just do different validation depending on what we need. We also get rid of the Pair.


<!-- Sent from Reviewable.io -->

2024-06-11 07:51 UTC, mullmat commented
Starting to look really nice! 🙌 A few comments so far:
* In the smallest phone, the "Add method" (& "Edit method I assume) isn't scrollable.
* The list-items methods (Direct, Bridges, custom) are 72pt, in the design they are 56pt - Is this a conscious choice?
* The "Current" text is very large, 22pt while in the design it's 18pt.
* The dropdowns, the chosen option is not highlighted or indicated with a checkmark.
* The dropdowns, the options are wrong color 😮 
* On larger screens, the dropdowns are not full width but get cut off - is this by choice?
* When a textfield is in focus it becomes larger in height, is this by choice? From 56pt -> 64pt 🤔 
* When using the keyboard to go to the next textfield, the screen doesn't follow along visually.
* The "Use now" button doesn't test but shows the method as directly in use.

2024-06-11 08:43 UTC, Pururun commented
> 
>     * In the smallest phone, the "Add method" (& "Edit method I assume) isn't scrollable.
Fixed
>     * The list-items methods (Direct, Bridges, custom) are 72pt, in the design they are 56pt - Is this a conscious choice?
It is the same as other two row list items in the app. (Custom lists)
>     * The "Current" text is very large, 22pt while in the design it's 18pt.
Will fix.
>     * The dropdowns, the chosen option is not highlighted or indicated with a checkmark.
Fixed.
>     * The dropdowns, the options are wrong color 😮
Will fix
>     * On larger screens, the dropdowns are not full width but get cut off - is this by choice?
This is a bug that is fixed on newer versions of compose that are not yet stable. Will check for workaround. 
>     * When a textfield is in focus it becomes larger in height, is this by choice? From 56pt -> 64pt 🤔
Not by choice, will fix. 
>     * When using the keyboard to go to the next textfield, the screen doesn't follow along visually.
Will fix.
>     * The "Use now" button doesn't test but shows the method as directly in use.
Will fix.

2024-06-11 13:12 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 42 of 72 files reviewed, 6 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/SaveApiAccessMethodDialog.kt` line 73 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-56HNW9JAxdEPslmCs:-O-6Nfm86QqPx1kxAb6V:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/290d8b54ae475e6ef11a5a570c818ef7ed822bd6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/SaveApiAccessMethodDialog.kt#L73)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`backNavigator::navigateBack`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 187 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-58WZBAgKSiNl7l_9c:-O-6O7xsAsGb4M2Fa4On:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33b911d898bf33086e1982f9622c6f40c43b42ba/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L187)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We can avoid using `NonEmptyList` by using `EitherNel` it is a bit more readable.
```
EitherNel<InvalidDataError, xxx>
```
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 196 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-54xXb1vKELORp--SU:-O-6OEDV4TBTtNXnZbet:b-j1we20) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/290d8b54ae475e6ef11a5a570c818ef7ed822bd6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L196)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This parsing turned out pretty darn nice :star2:
</blockquote></details>

:raised_hands: 


<!-- Sent from Reviewable.io -->

2024-06-11 13:15 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 42 of 72 files reviewed, 6 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 189 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-58rOS5ABSyiO2SgHq:-O-6QPgp8C8gBBalH5eW:b-46jlgi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33b911d898bf33086e1982f9622c6f40c43b42ba/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L189)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Can we improve on this return type? :grimacing: Or maybe we should split the parsing even more to avoid it?

We could have:


```
parseFormData(): EitherNel<InvalidDataError, ApiAccessMethod> {
     // This would use the parseConnectionFormData to get the CustomProxy and parse the name
}

parseConnectionFormData(): EitherNel<InvalidDataError, ApiAccessMethodType.CustomProxy>
```

In this way we can get rid of the `skipNameValidation`, and just do different validation depending on what we need. We also get rid of the Pair.
</blockquote></details>

I made `parseConnectionFormData` it's own function, but I'm not sure about changing the return type since it is describing very clearly what information it is returning. The other option is to use class that has more information than we are actually returning or creating a return type just for this function.


<!-- Sent from Reviewable.io -->

2024-06-11 13:36 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 42 of 72 files reviewed, 6 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/ApiAccessMethodTextField.kt` line 41 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-55zFO2u5Glyjj0KA_:-O-6VnTp2rUOAVOlLNsQ:b7zafp2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/290d8b54ae475e6ef11a5a570c818ef7ed822bd6/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/ApiAccessMethodTextField.kt#L41)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Wouldn't this be done automatically? Can we add a comment why we have to do this?
</blockquote></details>

Because we are overriding that behavior in `CustomTextField`


<!-- Sent from Reviewable.io -->

2024-06-12 13:26 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 40 of 80 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 189 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-58rOS5ABSyiO2SgHq:-O-Bc5xwAQnVPvmShVJk:bck2qq9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33b911d898bf33086e1982f9622c6f40c43b42ba/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L189)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I made `parseConnectionFormData` it's own function, but I'm not sure about changing the return type since it is describing very clearly what information it is returning. The other option is to use class that has more information than we are actually returning or creating a return type just for this function.
</blockquote></details>

I looked into, and I tend to agree. We possibly could encapsulate both these values in a new class but I'm not sure if it adds much value.


<!-- Sent from Reviewable.io -->

2024-06-12 13:37 UTC, Rawa reviewed
> Reviewed 1 of 11 files at r13, 8 of 24 files at r14, 6 of 19 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 55 of 80 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SaveApiAccessMethodUiState.kt` line 16 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-BeMfu9E5n5dpN9hku:-O-BeMfu9E5n5dpN9hkv:b-7x6ebd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b784c8e1bb18ecfc06a60c88f5e4d36ab0462ce1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SaveApiAccessMethodUiState.kt#L16)):*
> ```Kotlin
>         data object Failure : Result
> 
>         fun isSuccessful() = this is Successful
> ```

I think this is unnecessary? Shouldn't we use `is Successful` maybe directly?


<!-- Sent from Reviewable.io -->

2024-06-13 07:17 UTC, Rawa reviewed
> Reviewed 1 of 19 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 56 of 80 files reviewed, 2 unresolved discussions (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2024-06-13 07:27 UTC, Rawa reviewed
> Reviewed 1 of 24 files at r14, 4 of 19 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 77 of 80 files reviewed, 3 unresolved discussions (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2024-06-13 07:39 UTC, Rawa requested changes
> Reviewed 3 of 19 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SaveApiAccessMethodViewModelTest.kt` line 173 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-FWo0R43dwd2HsU21e:-O-FWo0R43dwd2HsU21f:b-t4kv9p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b784c8e1bb18ecfc06a60c88f5e4d36ab0462ce1/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SaveApiAccessMethodViewModelTest.kt#L173)):*
> ```Kotlin
>         // Act, Assert
>         saveApiAccessMethodViewModel.uiSideEffect.test {
>             // Check for successful creation
> ```

This comment does not add up with effect.


<!-- Sent from Reviewable.io -->

2024-06-13 08:27 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 78 of 81 files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SaveApiAccessMethodUiState.kt` line 16 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-BeMfu9E5n5dpN9hku:-O-FfY_C1gYYG1lPuRYH:bctptxb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b784c8e1bb18ecfc06a60c88f5e4d36ab0462ce1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SaveApiAccessMethodUiState.kt#L16)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I think this is unnecessary? Shouldn't we use `is Successful` maybe directly?
</blockquote></details>

It was mostly useful for making the code a bit shorter, removed it.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt` line 107 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-FTu640MP0rGn3Hm-W:-O-FgnGaCUD9P3hL__tp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b784c8e1bb18ecfc06a60c88f5e4d36ab0462ce1/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt#L107)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I think the fold is unnecessary. Something like this should be enough:
```
val result = apiAccessRepository.testCustomApiAccessMethod(customProxy)
_uiSideEffect.send(
    EditApiAccessSideEffect.TestApiAccessMethodResult(successful = result.isRight())
)```
```

</blockquote></details>

Done.
___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SaveApiAccessMethodViewModelTest.kt` line 173 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-FWo0R43dwd2HsU21e:-O-Fh16TAeiuC-053xI0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b784c8e1bb18ecfc06a60c88f5e4d36ab0462ce1/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SaveApiAccessMethodViewModelTest.kt#L173)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This comment does not add up with effect.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-13 09:53 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 54 of 83 files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/ApiAccessMethodType.kt` line 6 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-1GYnPCxfa5dnCIP5W:-O-G-xFJ52dmb5I57pAt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/33b911d898bf33086e1982f9622c6f40c43b42ba/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/ApiAccessMethodType.kt#L6)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Naming feels a bit weird here. I would expect type only to be the top level items here. But it actually contains the full connection details. 

I looked into the proto, there they call this level `AccessMethod` which sounds more correct. What we call ApiAccessMethod they call `AccessMethodSetting`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-13 10:39 UTC, Rawa requested changes
> Reviewed 24 of 28 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 78 of 83 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SaveApiAccessMethodViewModelTest.kt` line 173 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-FWo0R43dwd2HsU21e:-O-G9iwS2qhUf-RIRXEh:b-pafdln) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b784c8e1bb18ecfc06a60c88f5e4d36ab0462ce1/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SaveApiAccessMethodViewModelTest.kt#L173)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Latest push does not reflect change? Did you remove the wrong line?
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/NewAccessMethod.kt` line 7 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-GAQ85EzL3v0hLmunL:-O-GAQ85EzL3v0hLmunM:bihqct) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12e95bcb2ed8ae43ce875aa521b9b5a02847f749/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/NewAccessMethod.kt#L7)):*
> ```Kotlin
> 
> @Parcelize
> data class NewAccessMethod(
> ```

Should this be NewAccessMethodSetting ?


<!-- Sent from Reviewable.io -->

2024-06-13 10:40 UTC, Rawa reviewed
> Reviewed 4 of 28 files at r18.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 82 of 83 files reviewed, 2 unresolved discussions (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2024-06-13 10:55 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 76 of 83 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SaveApiAccessMethodViewModelTest.kt` line 173 at r16](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-FWo0R43dwd2HsU21e:-O-GDcpwBodbE1RCcO7f:b-7tj1yz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b784c8e1bb18ecfc06a60c88f5e4d36ab0462ce1/android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SaveApiAccessMethodViewModelTest.kt#L173)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Latest push does not reflect change? Did you remove the wrong line?
</blockquote></details>

Hmm not sure, it is gone now.
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/NewAccessMethod.kt` line 7 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-GAQ85EzL3v0hLmunL:-O-GE8X04Zeo5YTtK-8l:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/12e95bcb2ed8ae43ce875aa521b9b5a02847f749/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/NewAccessMethod.kt#L7)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should this be NewAccessMethodSetting ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-13 11:12 UTC, Rawa approved these changes
> Reviewed 7 of 7 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-13 15:05 UTC, Rawa requested changes
> Reviewed 30 of 30 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: all files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ApiAccessMethodDetailsViewModel.kt` line 61 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-H58gn324N0LgkRYRZ:-O-H58gn324N0LgkRYR_:b-abm4fi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/727850db9378a1f5dcbf3e5ea782d651bfdfb006/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ApiAccessMethodDetailsViewModel.kt#L61)):*
> ```Kotlin
>             viewModelScope.launch {
>                 testMethodById()
>                     .fold(
> ```

This looks a bit messy, not sure if we can make this easier? Something like:

```
val result = either {
    testMethodById().onLeft { _uiSideEffect.send(...) }.bind()
    apiAccessRepository.setCurrentApiAccess(apiAccessMethodId).onLeft{ _uiSideEffect.send(...)}.bind()
}
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ApiAccessMethodDetailsViewModel.kt` line 85 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-H6p0mAnLvSPLTdGj-:-O-H6p0nBK3QYLwttRwK:bfq2e05) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/727850db9378a1f5dcbf3e5ea782d651bfdfb006/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ApiAccessMethodDetailsViewModel.kt#L85)):*
> ```Kotlin
>         testingJob =
>             viewModelScope.launch {
>                 testMethodById()
> ```

Same as before
```
val result = testMethodById()
_uiSideEffect.send(ApiAccessMethodDetailsSideEffect.TestApiAccessMethodResult(result.isRight()))
```
                      
___
*[`gui/locales/messages.pot` line 2436 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-H7FIkAUZ8PlPZI6Q2:-O-H7FIkAUZ8PlPZI6Q3:b-3ddelc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/727850db9378a1f5dcbf3e5ea782d651bfdfb006/gui/locales/messages.pot#L2436)):*
> ```pot
> msgstr ""
> 
> msgid "Shadowsocks"
> ```

Should these be in non_translatable? Or do we set that in crowdin?


<!-- Sent from Reviewable.io -->

2024-06-14 11:23 UTC, Rawa reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 80 of 105 files reviewed, 3 unresolved discussions (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2024-06-14 11:23 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 80 of 105 files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ApiAccessMethodDetailsViewModel.kt` line 61 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-H58gn324N0LgkRYRZ:-O-LUHeB654zENJeWN95:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/727850db9378a1f5dcbf3e5ea782d651bfdfb006/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ApiAccessMethodDetailsViewModel.kt#L61)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This looks a bit messy, not sure if we can make this easier? Something like:

```
val result = either {
    testMethodById().onLeft { _uiSideEffect.send(...) }.bind()
    apiAccessRepository.setCurrentApiAccess(apiAccessMethodId).onLeft{ _uiSideEffect.send(...)}.bind()
}
```
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ApiAccessMethodDetailsViewModel.kt` line 85 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-H6p0mAnLvSPLTdGj-:-O-KhIvZE2SUKakJuqdA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/727850db9378a1f5dcbf3e5ea782d651bfdfb006/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ApiAccessMethodDetailsViewModel.kt#L85)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Same as before
```
val result = testMethodById()
_uiSideEffect.send(ApiAccessMethodDetailsSideEffect.TestApiAccessMethodResult(result.isRight()))
```
</blockquote></details>

Done.
___
*[`gui/locales/messages.pot` line 2436 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319#-O-H7FIkAUZ8PlPZI6Q2:-O-LUIHI6D6Ndbqp7h9I:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/727850db9378a1f5dcbf3e5ea782d651bfdfb006/gui/locales/messages.pot#L2436)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should these be in non_translatable? Or do we set that in crowdin?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-14 11:24 UTC, Rawa reviewed
> Reviewed 25 of 25 files at r21.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: 103 of 105 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-14 11:25 UTC, Rawa reviewed
> Reviewed 2 of 2 files at r22.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-14 11:25 UTC, Rawa approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-14 13:04 UTC, Rawa approved these changes
> Reviewed 2 of 3 files at r23, 1 of 1 files at r24, 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6319)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-14 13:14 UTC, merged