Add auto-start on launch to devices without always-on setting
mullvad/mullvadvpn-app pull request #6371
Opened 2024-06-18 13:34 UTC by Pururun

This replaces the "auto-connect" feature on TV and other devices without vpn settings.

Not currently in scope, will be added in a later pr to the `android-auto-start-migration`:
- Removing the old auto-connect feature completely for phone users .    
- Remove the auto-connect feature from daemon.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)

2024-06-19 07:56 UTC, albin-mullvad reviewed
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O-jSXpv8cmOU8uUEAit:-O-jSXpv8cmOU8uUEAiu:b-fxfsrb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73becde7f71d81fce910b561e9cb707398f36127/android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt#L12)):*
> ```Kotlin
> class BootCompletedReceiver : BroadcastReceiver() {
>     override fun onReceive(context: Context?, intent: Intent?) {
>         if (intent?.action == "android.intent.action.BOOT_COMPLETED") {
> ```

Use `Intent.ACTION_BOOT_COMPLETED`



_Code quote:_
```Kotlin
"android.intent.action.BOOT_COMPLETED"
```
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 388 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O-jRnEi6AQrB1h0hYo1:-O-jRnEi6AQrB1h0hYo2:by0blot) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73becde7f71d81fce910b561e9cb707398f36127/android/lib/resource/src/main/res/values/strings.xml#L388)):*
> ```XML
>     <string name="failed_to_set_current_test_error">Failed to set to current - API not reachable</string>
>     <string name="failed_to_set_current_unknown_error">Failed to set to current - Unknown reason</string>
>     <string name="connect_on_start">Connect on start</string>
> ```

Reminder that we should align this string



_Code quote:_
```XML
Connect on start
```
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 389 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O-jRdiY7UoDU_ILYvC3:-O-jRdiY7UoDU_ILYvC4:b-7mr3zo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73becde7f71d81fce910b561e9cb707398f36127/android/lib/resource/src/main/res/values/strings.xml#L389)):*
> ```XML
>     <string name="failed_to_set_current_unknown_error">Failed to set to current - Unknown reason</string>
>     <string name="connect_on_start">Connect on start</string>
>     <string name="connect_on_start_footer">Automatically connect on device start-up</string>
> ```

Should we somehow clarify in this text that it only works if the permission has been approved? Or do we have some other idea on how to handle missing permission? :thinking: 

(this comment is also related to the `VpnService.prepare(context)` check)



_Code quote:_
```XML
Automatically connect on device start-up
```


<!-- Sent from Reviewable.io -->

2024-06-19 08:54 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt` line 12 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O-jSXpv8cmOU8uUEAit:-O-jh-uGCad-2xT6dYYH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73becde7f71d81fce910b561e9cb707398f36127/android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt#L12)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Use `Intent.ACTION_BOOT_COMPLETED`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-19 12:49 UTC, albin-mullvad reviewed
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt` line 19 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O-kWnt94QoZfYO-EDgN:-O-kWnt94QoZfYO-EDgO:b-ghjwr1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b5625e8a9f65e14977b937ff77a6a15a5d06640e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt#L19)):*
> ```Kotlin
>     private fun startAndConnectTunnel(context: Context) {
>         // Check for vpn permission
>         if (VpnService.prepare(context) == null) {
> ```

nit: I suggest a small helper function `hasVpnPermission` or `val` over the need for this comment



_Code quote:_
```Kotlin
        // Check for vpn permission
        if (VpnService.prepare(context) == null) {
```


<!-- Sent from Reviewable.io -->

2024-06-24 21:56 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)* status: 4 of 12 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt` line 19 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O-kWnt94QoZfYO-EDgN:-O0BEyon5iP_1ZXSGoOd:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b5625e8a9f65e14977b937ff77a6a15a5d06640e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt#L19)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: I suggest a small helper function `hasVpnPermission` or `val` over the need for this comment
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-06-25 07:29 UTC, albin-mullvad reviewed
> Reviewed 1 of 9 files at r1, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)* status: 7 of 12 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt` line 19 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O-kWnt94QoZfYO-EDgN:-O0DGIZo0CeVMuCiaUGJ:b9sa157) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b5625e8a9f65e14977b937ff77a6a15a5d06640e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt#L19)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Looks good! :thumbsup: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/ConnectOnStartRepository.kt` line 15 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O0DGwUY4u0XXB7IGBhE:-O0DGwUY4u0XXB7IGBhF:b-bvp8tx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd6202aa14661bdc8efe1110d89c1656d62df434/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/ConnectOnStartRepository.kt#L15)):*
> ```Kotlin
>     private val bootCompletedComponentName: ComponentName
> ) {
>     val connectOnStart = MutableStateFlow(isConnectOnStart())
> ```

I think we should be a bit more clear and verbose in how we name/refer to this setting. Imo something like `autoStartAndConnectOnBoot` better describe what it does. One example where the current naming can be confusing is "start" as in "ConnectOnStartRepository" which could mean either on app, service or device start.

This comment applies to the whole PR.



_Code quote:_
```Kotlin
connectOnStart
```


<!-- Sent from Reviewable.io -->

2024-06-26 08:00 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)* status: 3 of 12 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/ConnectOnStartRepository.kt` line 15 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O0DGwUY4u0XXB7IGBhE:-O0IY_mVCJO2K4KsCTLc:bq3c4fk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bd6202aa14661bdc8efe1110d89c1656d62df434/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/ConnectOnStartRepository.kt#L15)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I think we should be a bit more clear and verbose in how we name/refer to this setting. Imo something like `autoStartAndConnectOnBoot` better describe what it does. One example where the current naming can be confusing is "start" as in "ConnectOnStartRepository" which could mean either on app, service or device start.

This comment applies to the whole PR.
</blockquote></details>

Changed it to what was suggested. I guess we can change it again if the text is changed to something wildly different.


<!-- Sent from Reviewable.io -->

2024-07-18 13:41 UTC, Rawa requested changes
> Reviewed 4 of 9 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)* status: all files reviewed, 6 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/AndroidManifest.xml` line 111 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O24zye92xwxPIDLUPP3:-O24zye92xwxPIDLUPP4:b-ze1fub) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/AndroidManifest.xml#L111)):*
> ```XML
>         <receiver android:name="net.mullvad.mullvadvpn.receiver.BootCompletedReceiver"
>                           android:enabled="false"
>                           android:exported="true">
> ```

Does it have to be `exported`?  It means others' can invoke our receiver is it needed for when the system calls as well? Or does the intent filter protect us?
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 388 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O-jRnEi6AQrB1h0hYo1:-O253iFc1sbETS75QbUA:b7af46i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73becde7f71d81fce910b561e9cb707398f36127/android/lib/resource/src/main/res/values/strings.xml#L388)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Reminder that we should align this string
</blockquote></details>

Should these strings be updated according to what @albin-mullvad said?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 15 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O2538448ZmK06TpmJ1N:-O2538448ZmK06TpmJ1O:b-tircxa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L15)):*
> ```Kotlin
>     private val bootCompletedComponentName: ComponentName
> ) {
>     val autoStartAndConnectOnBoot = MutableStateFlow(isAutoStartAndConnectOnBoot())
> ```

Do we know that this property, from anyone else than us? E.g adb or something like that.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 36 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O252hFy-R5ME6H4VdWb:-O252hFy-R5ME6H4VdWc:b2pncxo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L36)):*
> ```Kotlin
>             COMPONENT_ENABLED_STATE_ENABLED -> true
>             COMPONENT_ENABLED_STATE_DISABLED -> false
>             else -> error("Unknown component enabled setting")
> ```

Let's add all states instead of using `else`, if Google decides to add another one in a later stage:
```
        PackageManager.COMPONENT_ENABLED_STATE_ENABLED
        PackageManager.COMPONENT_ENABLED_STATE_DEFAULT
        PackageManager.COMPONENT_ENABLED_STATE_DISABLED
        PackageManager.COMPONENT_ENABLED_STATE_DISABLED_UNTIL_USED // Can this happen? When would it happen?
        PackageManager.COMPONENT_ENABLED_STATE_DISABLED_USER // Is there a case were we should care about this one?
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 40 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O251QfN3XZb-kEKFujn:-O251QfN3XZb-kEKFujo:bxvneme) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L40)):*
> ```Kotlin
> 
>     companion object {
>         private const val BOOT_COMPLETED_DEFAULT_STATE = false
> ```

Annoying that we have to define this, it should be implicit from the manifest. Not sure if it is possible to grab some how?


<!-- Sent from Reviewable.io -->

2024-07-18 14:14 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)* status: all files reviewed, 6 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @Rawa)

___
*[`android/app/src/main/AndroidManifest.xml` line 111 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O24zye92xwxPIDLUPP3:-O25AOXtD-q_NThVvmR-:b-6mvkid) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/AndroidManifest.xml#L111)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Does it have to be `exported`?  It means others' can invoke our receiver is it needed for when the system calls as well? Or does the intent filter protect us?
</blockquote></details>

I assumed it is because of the system sending the broadcast, but I can test without it.
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 388 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O-jRnEi6AQrB1h0hYo1:-O25Aku44ESs-Eq6HnHR:bvwpm1o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73becde7f71d81fce910b561e9cb707398f36127/android/lib/resource/src/main/res/values/strings.xml#L388)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should these strings be updated according to what @albin-mullvad said?
</blockquote></details>

The strings have been aligned with Matilda, do we need to align it with someone else?
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 389 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O-jRdiY7UoDU_ILYvC3:-O25AugX77025CVyWhB-:bn227ul) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73becde7f71d81fce910b561e9cb707398f36127/android/lib/resource/src/main/res/values/strings.xml#L389)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should we somehow clarify in this text that it only works if the permission has been approved? Or do we have some other idea on how to handle missing permission? :thinking: 

(this comment is also related to the `VpnService.prepare(context)` check)
</blockquote></details>

String updated.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 15 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O2538448ZmK06TpmJ1N:-O25BJcp7PdVUhhjhtRc:bourqcl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L15)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Do we know that this property, from anyone else than us? E.g adb or something like that.
</blockquote></details>

Not sure I follow, are you asking if this could be spoofed somehow?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 36 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O252hFy-R5ME6H4VdWb:-O25BTQPCABxjUZ08Jqn:bhy9ot6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L36)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Let's add all states instead of using `else`, if Google decides to add another one in a later stage:
```
        PackageManager.COMPONENT_ENABLED_STATE_ENABLED
        PackageManager.COMPONENT_ENABLED_STATE_DEFAULT
        PackageManager.COMPONENT_ENABLED_STATE_DISABLED
        PackageManager.COMPONENT_ENABLED_STATE_DISABLED_UNTIL_USED // Can this happen? When would it happen?
        PackageManager.COMPONENT_ENABLED_STATE_DISABLED_USER // Is there a case were we should care about this one?
```
</blockquote></details>

Will do.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 40 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O251QfN3XZb-kEKFujn:-O25Ax6jCySDz5Z1tSSo:b7t3zch) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L40)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Annoying that we have to define this, it should be implicit from the manifest. Not sure if it is possible to grab some how?
</blockquote></details>

As far as I could tell no, but I can look into to it further.


<!-- Sent from Reviewable.io -->

2024-07-18 14:28 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)* status: 13 of 14 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 36 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O252hFy-R5ME6H4VdWb:-O25ByONCsv9RYEtUWHd:b-syzwjj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L36)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Added all possible cases, still kept else since we are checking an int.
Note that `PackageManager.COMPONENT_ENABLED_STATE_DISABLED_UNTIL_USED` and `PackageManager.COMPONENT_ENABLED_STATE_DISABLED_USER` are only valid for applications and not components (even though name implies that they are..) but I guess it is useful if the behaviour of android changes.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 40 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O251QfN3XZb-kEKFujn:-O25Dq28DVdDJT8tqeMI:b-8ml04a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L40)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

As far as I could tell no, but I can look into to it further.
</blockquote></details>

So the setting works that it checks what was last set by `setComponentEnabledSetting`. If this has never been called, it will return "default" (sort of like null if a shared pref has never been set). So the only way I can think of is to refer to a common resource in the repository and in the manifest. Not sure how useful that is.


<!-- Sent from Reviewable.io -->

2024-07-19 09:16 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)* status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 36 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O252hFy-R5ME6H4VdWb:-O29GnUu78gYVOhdiJgj:b1mysay) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L36)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Added all possible cases, still kept else since we are checking an int.
Note that `PackageManager.COMPONENT_ENABLED_STATE_DISABLED_UNTIL_USED` and `PackageManager.COMPONENT_ENABLED_STATE_DISABLED_USER` are only valid for applications and not components (even though name implies that they are..) but I guess it is useful if the behaviour of android changes.
</blockquote></details>

Discussed, should work with when.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 40 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O251QfN3XZb-kEKFujn:-O29GlNk672mFmr3yfZF:b-pkgs1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L40)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

So the setting works that it checks what was last set by `setComponentEnabledSetting`. If this has never been called, it will return "default" (sort of like null if a shared pref has never been set). So the only way I can think of is to refer to a common resource in the repository and in the manifest. Not sure how useful that is.
</blockquote></details>

Sounds good to me


<!-- Sent from Reviewable.io -->

2024-07-19 11:18 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`android/lib/resource/src/main/res/values/strings.xml` line 389 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O-jRdiY7UoDU_ILYvC3:-O29h_9h7Go_0pNo4_sd:b-j0rhbu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/73becde7f71d81fce910b561e9cb707398f36127/android/lib/resource/src/main/res/values/strings.xml#L389)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

String updated.
</blockquote></details>

Text alignment issue added:
https://linear.app/mullvad/issue/DROID-1200/align-on-text-for-connect-on-boot-setting-on-tv
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 15 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O2538448ZmK06TpmJ1N:-O29TeAK5e53sjfAOY-N:b482fbk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L15)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Not sure I follow, are you asking if this could be spoofed somehow?
</blockquote></details>

So it is possible to change this state via adb, will add a linear issue.
https://linear.app/mullvad/issue/DROID-1201/handle-external-enabledisable-of-broadcast-receiver
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 36 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O252hFy-R5ME6H4VdWb:-O29hXNq1ICMe59j_SZW:baxshay) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L36)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Discussed, should work with when.
</blockquote></details>

Does not work with when :(


<!-- Sent from Reviewable.io -->

2024-07-19 11:25 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)* status: 12 of 14 files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/AndroidManifest.xml` line 111 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O24zye92xwxPIDLUPP3:-O29ia2UC6Qwor0uwM4S:bed57we) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/AndroidManifest.xml#L111)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I assumed it is because of the system sending the broadcast, but I can test without it.
</blockquote></details>

Seems to work fine even though it is not exported.


<!-- Sent from Reviewable.io -->

2024-07-19 11:27 UTC, Rawa approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/app/src/main/AndroidManifest.xml` line 111 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O24zye92xwxPIDLUPP3:-O29jQs11jjQ_iBTGgAQ:b-80yxc7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/AndroidManifest.xml#L111)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Seems to work fine even though it is not exported.
</blockquote></details>

I believe we can remove exported="false" it should be default, https://developer.android.com/guide/topics/manifest/receiver-element#exported
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 15 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O2538448ZmK06TpmJ1N:-O29ji8b-Gc2uVeSLHia:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L15)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

So it is possible to change this state via adb, will add a linear issue.
https://linear.app/mullvad/issue/DROID-1201/handle-external-enabledisable-of-broadcast-receiver
</blockquote></details>

:+1: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 36 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371#-O252hFy-R5ME6H4VdWb:-O29jnQC0NaUwG3foOlX:b-fqssiv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/52062962ba4fe2158054f9e693c2a580c992b24a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L36)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Does not work with when :(
</blockquote></details>

My bad :)


<!-- Sent from Reviewable.io -->

2024-07-19 11:53 UTC, Rawa approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-19 12:37 UTC, merged