Re-enable screenshots for iPad
mullvad/mullvadvpn-app pull request #6403
Opened 2024-06-25 09:00 UTC by niklasberglund

Re-enable screenshots for iPad, since the iPad specific UI is now gone and screenshot tests should work on iPad again. The changes can be tested by running the iOS create screenshots workflow, but it is currently broken https://github.com/mullvad/mullvadvpn-app/actions/workflows/ios-screenshots-creation.yml

2024-06-26 08:00 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6403)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-26 15:18 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6403)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-27 06:21 UTC, buggmagnet reviewed
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6403)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/Pages/Page.swift` line 53 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6403#-O0NLpLN4Fb8MLScjOO9:-O0NLpLN4Fb8MLScjOOA:bgfpx5h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/92a1a22388f3d7915fde83d5119c41e3c34506ae/ios/MullvadVPNUITests/Pages/Page.swift#L53)):*
> ```Swift
> 
>     @discardableResult func tapWhereStatusBarShouldBeToScrollToTopMostPosition() -> Self {
>         app.coordinate(withNormalizedOffset: CGVector(dx: 0.75, dy: 0)).tap()
> ```

Was there a specific reason for this change ?


<!-- Sent from Reviewable.io -->

2024-06-27 09:13 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6403)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPNUITests/Pages/Page.swift` line 53 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6403#-O0NLpLN4Fb8MLScjOO9:-O0Ns7KM9Xyc5cHvssQa:bnl6n2q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/92a1a22388f3d7915fde83d5119c41e3c34506ae/ios/MullvadVPNUITests/Pages/Page.swift#L53)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Was there a specific reason for this change ?
</blockquote></details>

On iPad there's a button in the middle of the nav bar to handle split screen and such. Touching that area on a phone makes the current scroll view scroll to top, but touching the same area results in a click in the button instead. Which fails the test as it cannot proceed. Offsetting the touch a little "misses" the button and yields the result we want. It can probably be considered a hack, but if so the original implementation is as well.


<!-- Sent from Reviewable.io -->

2024-06-27 11:21 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6403)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPNUITests/Pages/Page.swift` line 53 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6403#-O0NLpLN4Fb8MLScjOO9:-O0OQNqTE8JDvr6DHQqn:bjms449) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/92a1a22388f3d7915fde83d5119c41e3c34506ae/ios/MullvadVPNUITests/Pages/Page.swift#L53)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

On iPad there's a button in the middle of the nav bar to handle split screen and such. Touching that area on a phone makes the current scroll view scroll to top, but touching the same area results in a click in the button instead. Which fails the test as it cannot proceed. Offsetting the touch a little "misses" the button and yields the result we want. It can probably be considered a hack, but if so the original implementation is as well.
</blockquote></details>

That's totally fine, we should document it though, to make sure our future selves do not forget, because it looks like a magic value from an ignorant observer's point of view.


<!-- Sent from Reviewable.io -->

2024-06-27 11:41 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6403#-:-O0OUwid5HQrrsCVKHxK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-27 11:42 UTC, merged