Move ICMP packet creation and parsing out of Pinger implementation
mullvad/mullvadvpn-app pull request #6438
Opened 2024-07-03 13:13 UTC by acb-mv

This moves `createICMPPacket` and `parseICMPResponse` out of the `Pinger` implementation to their own namespace (an instance-free struct named ICMP). This will be useful for reusing them in a new Pinger implementation that uses the IAN tunnel rather than `CFSocket`.

2024-07-03 19:16 UTC, pinkisemils requested changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6438)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @acb-mv)

___
*[`ios/PacketTunnelCore/Pinger/ICMP.swift` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6438#-O0u0NS5D6gy42eyd06v:-O0u0NS5D6gy42eyd06w:b-d0ia2w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aaf6f0292650b061fb38c71f63852d52248d6d5/ios/PacketTunnelCore/Pinger/ICMP.swift#L26)):*
> ```Swift
>         case ipv4PacketTooSmall
>         case icmpHeaderTooSmall
>         case invalidIPVersion
> ```

We should log, thus also capture, the unexpected value. This more or less applies to most other error types about unexpected values.
___
*[`ios/PacketTunnelCore/Pinger/ICMP.swift` line 86 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6438#-O0u0Fk65MBQJ7ULCshw:-O0u0Fk65MBQJ7ULCshx:b-zhen3j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aaf6f0292650b061fb38c71f63852d52248d6d5/ios/PacketTunnelCore/Pinger/ICMP.swift#L86)):*
> ```Swift
>             // Verify ICMP type.
>             guard icmpHeaderPointer.pointee.type == ICMP_ECHOREPLY else {
>                 throw Error.malformedResponse(.invalidEchoReplyType)
> ```

It might be reasonable to receive an ICMP message from our host about something else, other than an ICMP response, so I don' t think this should error out.


<!-- Sent from Reviewable.io -->

2024-07-04 08:29 UTC, rablador reviewed
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6438)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv)



<!-- Sent from Reviewable.io -->

2024-07-04 08:33 UTC, buggmagnet reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6438)* status: all files reviewed, 3 unresolved discussions (waiting on @acb-mv)

___
*[`ios/PacketTunnelCore/Pinger/ICMP.swift` line 126 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6438#-O0wgmpO8yPSGo-aMD8X:-O0wgmpO8yPSGo-aMD8Y:b7d71ev) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aaf6f0292650b061fb38c71f63852d52248d6d5/ios/PacketTunnelCore/Pinger/ICMP.swift#L126)):*
> ```Swift
>     }
> 
>     // swiftlint:disable:next file_length
> ```

:warning:  `Superfluous Disable Command Violation: SwiftLint rule 'file_length' did not trigger a violation in the disabled region; remove the disable command (superfluous_disable_command)`


<!-- Sent from Reviewable.io -->

2024-07-04 09:51 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6438)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @pinkisemils and @rablador)

___
*[`ios/PacketTunnelCore/Pinger/ICMP.swift` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6438#-O0u0NS5D6gy42eyd06v:-O0x6Nk1-CXi9kReirm6:b-n14x3c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aaf6f0292650b061fb38c71f63852d52248d6d5/ios/PacketTunnelCore/Pinger/ICMP.swift#L26)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

We should log, thus also capture, the unexpected value. This more or less applies to most other error types about unexpected values.
</blockquote></details>

I'll add it to the echo reply type. The "too small" values are probably not worth bothering with, as meaningful diagnostic data would be the entire malformed packet (which would add overhead, and be better obtained with a debugger). As for IP version, if that mismatches then we either have an IPv6 header that somehow snuck through or a malformed structure altogether, so I'm not sure if there's much point logging the IP version value in the error structure.
___
*[`ios/PacketTunnelCore/Pinger/ICMP.swift` line 86 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6438#-O0u0Fk65MBQJ7ULCshw:-O0x6weG1imoXvE6JGRg:bity068) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aaf6f0292650b061fb38c71f63852d52248d6d5/ios/PacketTunnelCore/Pinger/ICMP.swift#L86)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It might be reasonable to receive an ICMP message from our host about something else, other than an ICMP response, so I don' t think this should error out.
</blockquote></details>

I have moved this check to the caller.


<!-- Sent from Reviewable.io -->

2024-07-04 12:54 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6438)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @buggmagnet, @pinkisemils, and @rablador)

___
*[`ios/PacketTunnelCore/Pinger/ICMP.swift` line 126 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6438#-O0wgmpO8yPSGo-aMD8X:-O0xnpC32e1MQOLP3zFX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aaf6f0292650b061fb38c71f63852d52248d6d5/ios/PacketTunnelCore/Pinger/ICMP.swift#L126)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

:warning:  `Superfluous Disable Command Violation: SwiftLint rule 'file_length' did not trigger a violation in the disabled region; remove the disable command (superfluous_disable_command)`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-08 08:44 UTC, pinkisemils approved these changes
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6438)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-07-08 09:35 UTC, merged