Add negative leak test for iOS
mullvad/mullvadvpn-app pull request #6449
Opened 2024-07-05 16:06 UTC by niklasberglund

Add a negative leak test. This is a draft PR. The implementation should almost be there, but the main issue with the test right now seems to be that `getConnectedThroughRelayDateInterval` is returning a longer date interval for the relay connection than expected. I believe its a bug in the test code but it could also be that the dummy data is incorrect. Had to work with dummy data because of the ongoing move. 

To try it out run `testNegativeLeaks` under `LeakTests`. The test device must be connected to the `app-team-ios-tests` WiFi to be able to reach the packet capture API and firewall API.

2024-07-05 16:14 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ios/MullvadVPNUITests/Networking/StreamCollection.swift` line 160 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-O12f0R7EZMd28E7vQxD:-O12f0R7EZMd28E7vQxE:b-ynov4k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc5544701738ad3fab4738bc9314ef95e8d6731e/ios/MullvadVPNUITests/Networking/StreamCollection.swift#L160)):*
> ```Swift
>         }
> 
>         return DateInterval(start: startDate!, end: endDate!)
> ```

Left some illegal force unwrapping in this function which should probably be fixed :police_officer: 


<!-- Sent from Reviewable.io -->

2024-08-28 11:34 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @pinkisemils)

___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 0 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-O5NkxTdBmsV0rZeai_E:-O5NkxTe3wkzzKV55KBc:b-daebqa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dc5544701738ad3fab4738bc9314ef95e8d6731e/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L0)):*
Restore 😄


<!-- Sent from Reviewable.io -->

2024-12-18 08:36 UTC, pinkisemils reviewed
> Reviewed 3 of 13 files at r1, 7 of 11 files at r2, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449)* status: 11 of 15 files reviewed, 5 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/LeakTests.swift` line 87 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OENs-xk2_5WednDAaaA:-OENs-xk2_5WednDAaaB:bthdqtb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/811e8f4cc710fa88737aa4326b74cd89baba6fc0/ios/MullvadVPNUITests/LeakTests.swift#L87)):*
> ```Swift
> 
>         let capturedStreams = stopPacketCapture()
>         LeakCheck.assertNoLeaks(streams: capturedStreams, rules: [NoTrafficToHostLeakRule(host: targetIPAddress)])
> ```

`assertNoLeaks` implies that it shouldn't leak, no? Or am I reading this wrong? :) 
___
*[`ios/MullvadVPNUITests/Base/BaseUITestCase.swift` line 225 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OENsunuBSAYUXvM9jfp:-OENsuoAAqpHnR1oaY0f:b3kry) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/811e8f4cc710fa88737aa4326b74cd89baba6fc0/ios/MullvadVPNUITests/Base/BaseUITestCase.swift#L225)):*
> ```Swift
> 
>             // If there's a an active session due to cancelled/failed test run make sure to end it
>             if packetCaptureSessionIsActive {
> ```

S


<!-- Sent from Reviewable.io -->

2024-12-18 08:51 UTC, pinkisemils reviewed
> Reviewed 1 of 13 files at r1, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @niklasberglund)

___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 32 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OENv-z3D2ISoul9gJL_:-OENv-z3D2ISoul9gJLa:b-47xmky) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/811e8f4cc710fa88737aa4326b74cd89baba6fc0/ios/MullvadVPNUITests/Networking/Networking.swift#L32)):*
> ```Swift
> class Networking {
>     static func getIPAddress() throws -> String {
>         var ipAddress: String
> ```

We actually have an API now to get the correct IP address here, there are devices in the office where `en0` is not the WiFi interface. A simple GET on `/own-ip` will return the IP of the device.


<!-- Sent from Reviewable.io -->

2025-02-04 09:34 UTC, rablador requested changes
> Reviewed 1 of 11 files at r2, 3 of 11 files at r4, 2 of 7 files at r5, 4 of 8 files at r7, 2 of 4 files at r8, 2 of 5 files at r9, 3 of 3 files at r10, 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449)* status: 0 of 18 files reviewed, 12 unresolved discussions (waiting on @buggmagnet, @niklasberglund, @pinkisemils, and @rablador)

___
*[`ios/MullvadVPNUITests/Networking/TrafficGenerator.swift` line 43 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OIFHakR-4doIbQpj9mm:-OIFHakR-4doIbQpj9mn:b-fdgje4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1d35da37c14540d8cabe11b8e9a768190fad172b/ios/MullvadVPNUITests/Networking/TrafficGenerator.swift#L43)):*
> ```Swift
>     }
> 
>     func recreateConnection() -> NWConnection {
> ```

Rename to `createConnection` and use in `init` too?
___
*[`ios/MullvadVPNUITests/Networking/TrafficGenerator.swift` line 152 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OIFIhE6Emgez9ThCooG:-OIFIhE6Emgez9ThCooH:b-8ttla7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1d35da37c14540d8cabe11b8e9a768190fad172b/ios/MullvadVPNUITests/Networking/TrafficGenerator.swift#L152)):*
> ```Swift
> 
> extension NWEndpoint {
>     var customDebugDescription: String {
> ```

Make the two custom debug descriptions conform to `CustomDebugStringConvertible` instead?
___
*[`ios/MullvadVPNUITests/LeakTests.swift` line 17 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OHrLPXB6I0ku2o1rX28:-OHrLPXB6I0ku2o1rX29:b-t5el8g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59945289cdd41b46c06122dcb25f1b91b13a4560/ios/MullvadVPNUITests/LeakTests.swift#L17)):*
> ```Swift
>     }
> 
>     /// Send UDP traffic to a host, connect to relay and make sure while connected to relay no traffic  leaked went directly to the host
> ```

Nit: Hard to read
___
*[`ios/MullvadVPNUITests/LeakTests.swift` line 33 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OHrLm761MwgTQKBRpdA:-OHrLm761MwgTQKBRpdB:bbb8i09) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59945289cdd41b46c06122dcb25f1b91b13a4560/ios/MullvadVPNUITests/LeakTests.swift#L33)):*
> ```Swift
> 
>         // Keep the tunnel connection for a while
>         RunLoop.current.run(until: .now + 30)
> ```

Can we make this faster..?
___
*[`ios/MullvadVPNUITests/LeakTests.swift` line 42 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OHrM4th67PAkFVXmgwt:-OHrM4th67PAkFVXmgwu:b-2yf6ex) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59945289cdd41b46c06122dcb25f1b91b13a4560/ios/MullvadVPNUITests/LeakTests.swift#L42)):*
> ```Swift
>         var capturedStreams = stopPacketCapture()
>         // For now cut the beginning and and end of the stream to trim out the part where the tunnel connection was not up
>         capturedStreams = PacketCaptureClient.trimPackets(streams: capturedStreams, secondsStart: 8, secondsEnd: 3)
> ```

8 and 3 are very magical numbers.
___
*[`ios/MullvadVPNUITests/LeakTests.swift` line 75 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OHrMOOK26c7fF0mctaC:-OHrMOOK26c7fF0mctaD:bj8hxw1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59945289cdd41b46c06122dcb25f1b91b13a4560/ios/MullvadVPNUITests/LeakTests.swift#L75)):*
> ```Swift
>         RunLoop.current.run(until: .now + 5)
> 
>         app.launch()
> ```

Why do we need to luanch the app here?
___
*[`ios/MullvadVPNUITests/Networking/PacketCapture.swift` line 181 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OIFEwTA4Piv5_i64OJG:-OIFEwTA4Piv5_i64OJH:bejvu0g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1d35da37c14540d8cabe11b8e9a768190fad172b/ios/MullvadVPNUITests/Networking/PacketCapture.swift#L181)):*
> ```Swift
>         }
> 
>         let cutStartDate = collectionStartDate!.addingTimeInterval(secondsStart)
> ```

This will crash if `streams` in empty.
___
*[`ios/MullvadVPNUITests/Networking/TestRouterAPIClient.swift` line 13 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OIFGcqzAyCp_OL2oy07:-OIFGcr-Ep4QhKpwi9kR:b-ozgbn7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1d35da37c14540d8cabe11b8e9a768190fad172b/ios/MullvadVPNUITests/Networking/TestRouterAPIClient.swift#L13)):*
> ```Swift
> class TestRouterAPIClient {
>     // swiftlint:disable force_cast
>     static let baseURL = URL(
> ```

 // `swiftlint:disable:next`makes disable+enabel unnecessary.
___
*[`ios/MullvadVPNUITests/Networking/TestRouterAPIClient.swift` line 32 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OIFH2dN2Zyd2iRAd57Z:-OIFH2dN2Zyd2iRAd57_:b-11im5z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1d35da37c14540d8cabe11b8e9a768190fad172b/ios/MullvadVPNUITests/Networking/TestRouterAPIClient.swift#L32)):*
> ```Swift
>             defer { completionHandlerInvokedExpectation.fulfill() }
>             guard let data else {
>                 requestError = NetworkingError.internalError(reason: "Could not get device IP")
> ```

Why not throw here instead?
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 4276 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OHrL6Pf7Bz9SqKX48AO:-OHrL6Pf7Bz9SqKX48AP:bpsqz44) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59945289cdd41b46c06122dcb25f1b91b13a4560/ios/MullvadVPN.xcodeproj/project.pbxproj#L4276)):*
> ```
> 			isa = PBXGroup;
> 			children = (
> 				85607C882D131CCD00037E34 /* TestRouterAPIClient.swift */,
> ```

Nit: File order


<!-- Sent from Reviewable.io -->

2025-02-05 07:45 UTC, rablador requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449)* status: 0 of 18 files reviewed, 12 unresolved discussions (waiting on @buggmagnet, @niklasberglund, @pinkisemils, and @rablador)

___
*[`ios/MullvadVPNUITests/Networking/TrafficGenerator.swift` line 43 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OIFHakR-4doIbQpj9mm:-OIK3Hg25weQb-FE89c8:b-t9webh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1d35da37c14540d8cabe11b8e9a768190fad172b/ios/MullvadVPNUITests/Networking/TrafficGenerator.swift#L43)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Rename to `createConnection` and use in `init` too?
</blockquote></details>

Nevermind, as discussed IRL the init will complain about self being called too early.


<!-- Sent from Reviewable.io -->

2025-02-05 07:49 UTC, buggmagnet reviewed
> Reviewed 1 of 11 files at r2, 3 of 11 files at r4, 1 of 7 files at r5, 3 of 8 files at r7, 2 of 4 files at r8, 1 of 5 files at r9, 2 of 3 files at r10, 4 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449)* status: 16 of 18 files reviewed, 11 unresolved discussions (waiting on @niklasberglund, @pinkisemils, and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 4276 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OHrL6Pf7Bz9SqKX48AO:-OIJvPve0N8i55g89n02:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59945289cdd41b46c06122dcb25f1b91b13a4560/ios/MullvadVPN.xcodeproj/project.pbxproj#L4276)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: File order
</blockquote></details>

Done
___
*[`ios/MullvadVPNUITests/LeakTests.swift` line 17 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OHrLPXB6I0ku2o1rX28:-OIJv_8I-yor_Ul0w35G:b-bdqul4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59945289cdd41b46c06122dcb25f1b91b13a4560/ios/MullvadVPNUITests/LeakTests.swift#L17)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Hard to read
</blockquote></details>

Could you expand a bit more on what is hard to read ?
___
*[`ios/MullvadVPNUITests/LeakTests.swift` line 33 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OHrLm761MwgTQKBRpdA:-OIJwMKn78_WFNopLcTW:b-mthxnn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59945289cdd41b46c06122dcb25f1b91b13a4560/ios/MullvadVPNUITests/LeakTests.swift#L33)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Can we make this faster..?
</blockquote></details>

Considering we are trimming at least 11 seconds of packet capture at the end of this test,
yes we can wait a bit less, but not by much. 
Also  we need to make sure enough traffic is generated so guarantee that the test does what it says on the tin. 

I'll see if I can have Safari generate some traffic. 
___
*[`ios/MullvadVPNUITests/LeakTests.swift` line 42 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OHrM4th67PAkFVXmgwt:-OIJxO1f5R22pHrlrC0l:bphxxjb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59945289cdd41b46c06122dcb25f1b91b13a4560/ios/MullvadVPNUITests/LeakTests.swift#L42)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

8 and 3 are very magical numbers.
</blockquote></details>

Indeed, replacing those with constants. 
___
*[`ios/MullvadVPNUITests/LeakTests.swift` line 75 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OHrMOOK26c7fF0mctaC:-OIJxjz41fAXY73Gamgh:bcar569) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59945289cdd41b46c06122dcb25f1b91b13a4560/ios/MullvadVPNUITests/LeakTests.swift#L75)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Why do we need to luanch the app here?
</blockquote></details>

I'm not sure, that's how the test was originally written, I'm guessing the original implementer encountered a bug. 
It shouldn't be a problem to remove it.
___
*[`ios/MullvadVPNUITests/Networking/PacketCapture.swift` line 181 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OIFEwTA4Piv5_i64OJG:-OIJyJqU1ebGzORk24sW:bffawf3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1d35da37c14540d8cabe11b8e9a768190fad172b/ios/MullvadVPNUITests/Networking/PacketCapture.swift#L181)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This will crash if `streams` in empty.
</blockquote></details>

The function that gives us the stream object `getParsedCaptureObjects` will `XCTFail` if it cannot deserialize data.
At the very worst, `streams` will be an empty array. 

I'll add an `XCTAssertTrue(streams.count >= 1) before iterating the streams to validate that assertion.
___
*[`ios/MullvadVPNUITests/Networking/TestRouterAPIClient.swift` line 32 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OIFH2dN2Zyd2iRAd57Z:-OIK1Z8sB6n0gfh_TExc:bln8nxm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1d35da37c14540d8cabe11b8e9a768190fad172b/ios/MullvadVPNUITests/Networking/TestRouterAPIClient.swift#L32)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Why not throw here instead?
</blockquote></details>

Because the completion handler passed to `dataTask` isn't marked `throws`
___
*[`ios/MullvadVPNUITests/Networking/TrafficGenerator.swift` line 152 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OIFIhE6Emgez9ThCooG:-OIK4IfeBt2q7HYMwX0V:b-e4rgmd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1d35da37c14540d8cabe11b8e9a768190fad172b/ios/MullvadVPNUITests/Networking/TrafficGenerator.swift#L152)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Make the two custom debug descriptions conform to `CustomDebugStringConvertible` instead?
</blockquote></details>

They already do, but the original description isn't great.


<!-- Sent from Reviewable.io -->

2025-02-06 14:18 UTC, rablador submitted a review, later dismissed
> Reviewed 11 of 11 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449)* status: 7 of 18 files reviewed, 3 unresolved discussions (waiting on @buggmagnet, @pinkisemils, and @rablador)

___
*[`ios/MullvadVPNUITests/LeakTests.swift` line 17 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OHrLPXB6I0ku2o1rX28:-OIQbJDP4b4xV4P8lqaB:b-5mutle) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59945289cdd41b46c06122dcb25f1b91b13a4560/ios/MullvadVPNUITests/LeakTests.swift#L17)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Could you expand a bit more on what is hard to read ?
</blockquote></details>

"Send UDP traffic to a host, connect to relay and make sure - while connected to relay - that no leaked traffic went directly to the host"
___
*[`ios/MullvadVPNUITests/Networking/TestRouterAPIClient.swift` line 32 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OIFH2dN2Zyd2iRAd57Z:-OIQbtWJ8CFagW6cRouz:b2ni98j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1d35da37c14540d8cabe11b8e9a768190fad172b/ios/MullvadVPNUITests/Networking/TestRouterAPIClient.swift#L32)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Because the completion handler passed to `dataTask` isn't marked `throws`
</blockquote></details>

oh!


<!-- Sent from Reviewable.io -->

2025-02-06 14:49 UTC, buggmagnet reviewed
> Reviewed 1 of 11 files at r12.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449)* status: 5 of 18 files reviewed, 2 unresolved discussions (waiting on @pinkisemils and @rablador)

___
*[`ios/MullvadVPNUITests/LeakTests.swift` line 17 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449#-OHrLPXB6I0ku2o1rX28:-OIQj1Pd6GR8agFsCNbj:b-prjgmw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/59945289cdd41b46c06122dcb25f1b91b13a4560/ios/MullvadVPNUITests/LeakTests.swift#L17)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

"Send UDP traffic to a host, connect to relay and make sure - while connected to relay - that no leaked traffic went directly to the host"
</blockquote></details>

Yes indeed !

Done.


<!-- Sent from Reviewable.io -->

2025-02-06 14:50 UTC, rablador approved these changes
> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6449)* status: 5 of 18 files reviewed, 2 unresolved discussions (waiting on @pinkisemils and @rablador)



<!-- Sent from Reviewable.io -->

2025-02-06 14:50 UTC, merged