Test manager fixes
mullvad/mullvadvpn-app pull request #6493
Opened 2024-07-23 12:20 UTC by Serock3

Fixes DES-1092

2024-07-25 10:58 UTC, dlon requested changes
> Reviewed 10 of 20 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)* status: 9 of 21 files reviewed, 4 unresolved discussions (waiting on @Serock3)

___
*[`test/README.md` line 148 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2dVeQ61GzJT8HMuuJy:-O2dVeQ61GzJT8HMuuJz:b-uq2q22) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/README.md#L148)):*
> ```Markdown
> ```
> 
> ## Note on `ci-runtests.sh`
> ```

Should this be changed to `scripts/ci-runtests.sh`?
___
*[`test/scripts/build-runner-image.sh` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2_Jb-l-XUwtUNqG7NI:-O2_Jb-l-XUwtUNqG7NJ:bo8zq4a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/build-runner-image.sh#L37)):*
> ```Shell
>             "${SCRIPT_DIR}/../target/$TARGET/release/test-runner.exe" \
>             "${SCRIPT_DIR}/../target/$TARGET/release/connection-checker.exe" \
>             "${PACKAGE_FOLDER}/"*.exe \
> ```

What's the reason for renaming this from `_DIR`? Isn't that less consistent with how we name variables in general?
___
*[`test/scripts/ssh-setup.sh` line 116 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2_JpKV5a5WZt44nifa:-O2_JpKV5a5WZt44nifb:b-idcdon) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/ssh-setup.sh#L116)):*
> ```Shell
> # Install required packages
> if which apt &>/dev/null; then
>     echo "not doing install_packages_apt"
> ```

Should this be reverted?
___
*[`test/scripts/test-utils.sh` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2dWBOl7jvE07Kupd5W:-O2dWBOl7jvE07Kupd5X:b-rwxu9d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/test-utils.sh#L6)):*
> ```Shell
> 
> CALLER_DIR=$(pwd)
> SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
> ```

`source test-utils.sh` will overwrite variables in the calling script, for example `$SCRIPT_DIR` will refer to the directory of `test-utils.sh` after you've sourced it.

I kind of think we should either hide these "private" variables somehow, or turn this script into a "program". That is, execute the script rather than `source` it, and parse the first argument to the script as a command.


<!-- Sent from Reviewable.io -->

2024-07-25 11:14 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)* status: 9 of 21 files reviewed, 5 unresolved discussions (waiting on @Serock3)

___
*[`test/scripts/build-runner-image.sh` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2_Jb-l-XUwtUNqG7NI:-O2d_k1VCy_DIRNDmz8E:bp399ie) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/build-runner-image.sh#L37)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

What's the reason for renaming this from `_DIR`? Isn't that less consistent with how we name variables in general?
</blockquote></details>

Ah, because of its name in `test-manager`. Should we do the opposite and rename the argument to `packages-dir`? :)
___
*[`test/scripts/test-utils.sh` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2d_0Xu5rRWLZZpgOi6:-O2d_0Xu5rRWLZZpgOi7:bi4xs6g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/test-utils.sh#L29)):*
> ```Shell
> 
> if [[ ("$(uname -s)" == "Darwin") ]]; then
>     export CACHE_FOLDER=$HOME/Library/Caches/mullvad-test/packages
> ```

Could we instead export `PACKAGES_DIR`/`PACKAGE_FOLDER` and not define it anywhere except in this script?


<!-- Sent from Reviewable.io -->

2024-07-25 11:18 UTC, dlon reviewed
> Reviewed 1 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)* status: 10 of 21 files reviewed, 8 unresolved discussions (waiting on @Serock3)

___
*[`test/test-manager/src/main.rs` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2daeCO3gfUrKCyrW8h:-O2daeCO3gfUrKCyrW8i:b5j96zx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/test-manager/src/main.rs#L32)):*
> ```XML
>     Set {
>         /// Name of the config
>         name: String,
> ```

I think we should rename `name` to `vm` for consistency.
___
*[`test/test-manager/src/main.rs` line 42 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2daaVX8NUqldhb2Nlv:-O2daaVX8NUqldhb2Nlw:b5j96zx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/test-manager/src/main.rs#L42)):*
> ```XML
>     Remove {
>         /// Name of the config
>         name: String,
> ```

I think we should rename `name` to `vm` for consistency.
___
*[`test/test-manager/src/main.rs` line 138 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2daokn7f3JwH6cQko9:-O2daokn7f3JwH6cQkoA:b5j96zx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/test-manager/src/main.rs#L138)):*
> ```XML
>     Update {
>         /// Name of the VM config
>         name: String,
> ```

I think we should rename `name` to `vm` for consistency.


<!-- Sent from Reviewable.io -->

2024-07-25 11:36 UTC, Serock3 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)* status: 6 of 22 files reviewed, 5 unresolved discussions (waiting on @dlon)

___
*[`test/README.md` line 148 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2dVeQ61GzJT8HMuuJy:-O2dYkZaCwbqLOYtGs6P:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/README.md#L148)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should this be changed to `scripts/ci-runtests.sh`?
</blockquote></details>

Done
___
*[`test/scripts/build-runner-image.sh` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2_Jb-l-XUwtUNqG7NI:-O2dYnOC0juj4WltNJJG:bo10frh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/build-runner-image.sh#L37)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Ah, because of its name in `test-manager`. Should we do the opposite and rename the argument to `packages-dir`? :)
</blockquote></details>

We could to that, if you really prefer `dir` over `package`, yes
___
*[`test/scripts/test-utils.sh` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2d_0Xu5rRWLZZpgOi6:-O2dbE5R9rks9UCH6N6V:b-9fm5mp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/test-utils.sh#L29)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could we instead export `PACKAGES_DIR`/`PACKAGE_FOLDER` and not define it anywhere except in this script?
</blockquote></details>

In `test-by-version.sh`, you are expected to provide `PACKAGE_FOLDER` yourself, `ci-runtests.sh` just sets it to the cache folder
___
*[`test/test-manager/src/main.rs` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2daeCO3gfUrKCyrW8h:-O2dbVJq8VFvZSGdIvDs:b-bhxbfp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/test-manager/src/main.rs#L32)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think we should rename `name` to `vm` for consistency.
</blockquote></details>

Alright, I though  just `vm` seemed a bit weird in the context. But I agree that it is more consistent
___
*[`test/scripts/ssh-setup.sh` line 116 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2_JpKV5a5WZt44nifa:-O2dZAI09JfVeCTaG61F:bwaradi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/ssh-setup.sh#L116)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should this be reverted?
</blockquote></details>

Oh, woops. That wasn't intended to be committed. Good catch.


<!-- Sent from Reviewable.io -->

2024-07-25 12:33 UTC, Serock3 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)* status: 6 of 22 files reviewed, 5 unresolved discussions (waiting on @dlon)

___
*[`test/scripts/test-utils.sh` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2dWBOl7jvE07Kupd5W:-O2ds9eUDA0S-NGrXPHG:b-ra3ovb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/test-utils.sh#L6)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`source test-utils.sh` will overwrite variables in the calling script, for example `$SCRIPT_DIR` will refer to the directory of `test-utils.sh` after you've sourced it.

I kind of think we should either hide these "private" variables somehow, or turn this script into a "program". That is, execute the script rather than `source` it, and parse the first argument to the script as a command.
</blockquote></details>

There seems to be no way to prevent global variables from being sourced (in functions you can write `local`, but not outside functions). I refactored the globals to be functions instead, and called them where necessary
___
*[`test/scripts/test-utils.sh` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2d_0Xu5rRWLZZpgOi6:-O2dq4Vy5m27wm16VHQ_:b-ht7emf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/test-utils.sh#L29)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

In `test-by-version.sh`, you are expected to provide `PACKAGE_FOLDER` yourself, `ci-runtests.sh` just sets it to the cache folder
</blockquote></details>

That wasn't the case when I wrote the comment, men but it is now


<!-- Sent from Reviewable.io -->

2024-07-25 13:26 UTC, Serock3 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)* status: 5 of 22 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`test/test-manager/src/main.rs` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2daeCO3gfUrKCyrW8h:-O2e3aQ_BWD-fK30GAHP:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/test-manager/src/main.rs#L32)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Alright, I though  just `vm` seemed a bit weird in the context. But I agree that it is more consistent
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-07-25 13:37 UTC, dlon reviewed
> Reviewed 6 of 20 files at r1, 5 of 7 files at r4, 2 of 3 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`test/scripts/test-utils.sh` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2dWBOl7jvE07Kupd5W:-O2e0JT3A8g-ltgZRthd:b-a103s1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/test-utils.sh#L6)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

There seems to be no way to prevent global variables from being sourced (in functions you can write `local`, but not outside functions). I refactored the globals to be functions instead, and called them where necessary
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Nit: Maybe `get_script_dir` should be renamed to `get_utils_dir`or similar because it's public.
___
*[`test/scripts/test-utils.sh` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2d_0Xu5rRWLZZpgOi6:-O2e4Fu99_2adNzU35Pg:b-1smht5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/test-utils.sh#L29)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

That wasn't the case when I wrote the comment, men but it is now
</blockquote></details>

Ah. It might be fine for all scripts to have `PACKAGE_DIR` be overrideable. Then this could all be handled in the utils script.
___
*[`test/test-manager/src/tests/install.rs` line 290 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2e2u026DPc-4eWaDjd:-O2e2u026DPc-4eWaDje:b-unngjn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc6ec920fd75dadcb451c1ec796e159630852c52/test/test-manager/src/tests/install.rs#L290)):*
> ```XML
> 
>     // Re-install the app to ensure that the next test can run
>     test_install_new_app(_ctx, rpc).await?;
> ```

If something fails earlier in this test, then daemon will not be reinstalled, so all remaining tests will also fail.


<!-- Sent from Reviewable.io -->

2024-07-29 09:35 UTC, Serock3 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)* status: 18 of 27 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`test/scripts/test-utils.sh` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2d_0Xu5rRWLZZpgOi6:-O2xVAasCrmvrdGD33Jn:bobnor8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/test-utils.sh#L29)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Ah. It might be fine for all scripts to have `PACKAGE_DIR` be overrideable. Then this could all be handled in the utils script.
</blockquote></details>

I though that it was a nice design to export `CACHE_FOLDER` regardless, since it could be useful for someone writing their own script. If you prefer, I could define a function, like



_Code snippet:_
```Shell
function get_package_dir {
    local package_dir
    if [[ -z "${PACKAGE_DIR+x}" ]]; then
        package_dir="$CACHE_FOLDER"
    else
        package_dir="$PACKAGE_DIR"
    fi
    create_package_dir "$package_dir"
    echo "$package_dir"
}

And call it inside `test-utils.sh` instead of using `PACKAGE_DIR` directly, so that the defaulting behaviour is moved to `test-utils.sh`
```
___
*[`test/test-manager/src/tests/install.rs` line 290 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2e2u026DPc-4eWaDjd:-O2xpwtGABGcA1KqYr7v:b-4feyo6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc6ec920fd75dadcb451c1ec796e159630852c52/test/test-manager/src/tests/install.rs#L290)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

If something fails earlier in this test, then daemon will not be reinstalled, so all remaining tests will also fail.
</blockquote></details>

Should be fixed with the new cleanup logic


<!-- Sent from Reviewable.io -->

2024-07-29 12:51 UTC, dlon reviewed
> Reviewed 9 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)* status: all files reviewed, 3 unresolved discussions (waiting on @Serock3)

___
*[`test/scripts/test-utils.sh` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2d_0Xu5rRWLZZpgOi6:-O2yIlAF5-peOsDUwHy9:b3chqjl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/test-utils.sh#L29)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

I though that it was a nice design to export `CACHE_FOLDER` regardless, since it could be useful for someone writing their own script. If you prefer, I could define a function, like
</blockquote></details>

I like it. :) How do you feel about getting rid of `CACHE_DIR` completely with your function?

```bash
function get_package_dir {
    if [[ -n "${PACKAGE_DIR+x}" ]]; then
        echo "$PACKAGE_DIR"
        return 0
    fi
    if [[ ("$(uname -s)" == "Darwin") ]]; then
        echo "$HOME/Library/Caches/mullvad-test/packages"
    elif [[ ("$(uname -s)" == "Linux") ]]; then
        echo "$HOME/.cache/mullvad-test/packages"
    else
        echo "Unsupported OS" 1>&2
        exit 1
    fi
}
```
___
*[`test/test-manager/src/tests/install.rs` line 172 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2yMiSJ9mheu7Lwo9cG:-O2yMiSJ9mheu7Lwo9cH:b4vkn9m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/179e8b7d5f27c7dc69a2f718e9340d331563a4f9/test/test-manager/src/tests/install.rs#L172)):*
> ```XML
>     // verify that daemon is not already running
>     if rpc.mullvad_daemon_get_status().await? != ServiceStatus::NotRunning {
>         rpc.stop_mullvad_daemon().await.unwrap();
> ```

It would be more correct to uninstall the app here rather than stop it, since we're intending to test an install from a "clean" (uninstalled) state.

Arguably, though, we should just scrap the test. If it is now the responsibility of `test-manager` to ensure that the latest app is installed before a test runs, then this test is mostly confusing, IMO.
___
*[`test/test-manager/src/tests/mod.rs` line 217 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2yNKImCUa1L9k-_P3h:-O2yNKImCUa1L9k-_P3i:bjplygn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/179e8b7d5f27c7dc69a2f718e9340d331563a4f9/test/test-manager/src/tests/mod.rs#L217)):*
> ```XML
>             log::info!("Failed to reach daemon after test, re-installing app");
>             // Re-install the app to ensure that the next test can run
>             install_app(rpc, &TEST_CONFIG.app_package_filename)
> ```

If it's `test-manager`'s responsibility (not the responsibility of the tests themselves) to install the latest app, it should probably ensure that the app is installed *before* each test, and also that the correct version is installed.

Otherwise, it will unexpectedly not be installed before the *first* test, and not properly clean up the mess potentially made by other tests (such as installing an older version).

Maybe we could check this only in the case that a test has a Mullvad daemon client parameter. That would prevent pointless installs for the upgrade tests, etc. What do you think?
___
*[`test/test-manager/src/tests/mod.rs` line 217 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2yS9UE-HzAKwhrpvoZ:-O2yS9UE-HzAKwhrpvo_:b7q91lk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/179e8b7d5f27c7dc69a2f718e9340d331563a4f9/test/test-manager/src/tests/mod.rs#L217)):*
> ```XML
>             log::info!("Failed to reach daemon after test, re-installing app");
>             // Re-install the app to ensure that the next test can run
>             install_app(rpc, &TEST_CONFIG.app_package_filename)
> ```

Can we split this into two functions? One for handling (re)installs, one for restarting/updating the environment. These seem like different things.


<!-- Sent from Reviewable.io -->

2024-07-29 12:52 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)* status: all files reviewed, 3 unresolved discussions (waiting on @Serock3)

___
*[`test/scripts/test-utils.sh` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2d_0Xu5rRWLZZpgOi6:-O2yXySsAswISBomUVOu:bp7okhj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/test-utils.sh#L29)):*
> `CACHE_DIR`

(I meant `CACHE_FOLDER`.)


<!-- Sent from Reviewable.io -->

2024-07-31 13:37 UTC, Serock3 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)* status: 11 of 37 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`test/scripts/test-utils.sh` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2d_0Xu5rRWLZZpgOi6:-O2yeREC1FLCjItnUCsj:bo59izy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/test-utils.sh#L29)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

> `CACHE_DIR`

(I meant `CACHE_FOLDER`.)
</blockquote></details>

Alright, take a look at the new implementation, refactored the script a bit
___
*[`test/test-manager/src/tests/install.rs` line 172 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2yMiSJ9mheu7Lwo9cG:-O38-D5S5EQY4vGTHNdX:bxhg5cd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/179e8b7d5f27c7dc69a2f718e9340d331563a4f9/test/test-manager/src/tests/install.rs#L172)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It would be more correct to uninstall the app here rather than stop it, since we're intending to test an install from a "clean" (uninstalled) state.

Arguably, though, we should just scrap the test. If it is now the responsibility of `test-manager` to ensure that the latest app is installed before a test runs, then this test is mostly confusing, IMO.
</blockquote></details>

I make reinstalling the app (and logging in) a part of the new `prepare_daemon` step that replaces the post test cleanup
___
*[`test/test-manager/src/tests/mod.rs` line 217 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2yNKImCUa1L9k-_P3h:-O38-Y_q-Scb4vRWm6uG:b-34vmyd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/179e8b7d5f27c7dc69a2f718e9340d331563a4f9/test/test-manager/src/tests/mod.rs#L217)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

If it's `test-manager`'s responsibility (not the responsibility of the tests themselves) to install the latest app, it should probably ensure that the app is installed *before* each test, and also that the correct version is installed.

Otherwise, it will unexpectedly not be installed before the *first* test, and not properly clean up the mess potentially made by other tests (such as installing an older version).

Maybe we could check this only in the case that a test has a Mullvad daemon client parameter. That would prevent pointless installs for the upgrade tests, etc. What do you think?
</blockquote></details>

See above


<!-- Sent from Reviewable.io -->

2024-08-01 06:59 UTC, dlon requested changes
> Reviewed 4 of 6 files at r10, 23 of 23 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)* status: all files reviewed, 5 unresolved discussions (waiting on @Serock3)

___
*[`test/scripts/test-utils.sh` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2d_0Xu5rRWLZZpgOi6:-O384xeu6wg3kCGe0v93:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4ce77471ed7c00db7feca39e3a4fc2462d070e8d/test/scripts/test-utils.sh#L29)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

Alright, take a look at the new implementation, refactored the script a bit
</blockquote></details>

:+1: 
___
*[`test/scripts/test-utils.sh` line 54 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O382JWg6RAa32fak4AT:-O382JWg6RAa32fak4AU:b-jzu6p3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1539760d4cf9ab085c5bad1b30dc687f3fd55665/test/scripts/test-utils.sh#L54)):*
> ```Shell
>         # Resolve the package dir to an absolute path since cargo must be invoked from the test directory
>         pushd "$PACKAGE_DIR"
>             package_dir=$(pwd)
> ```

Nit: I think you can replace this with `package_dir=$(cd "$PACKAGE_DIR" && pwd)` and remove `pushd/popd`
___
*[`test/scripts/test-utils.sh` line 276 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O383PCh5aVCUdVFp0nK:-O383PCh5aVCUdVFp0nL:b-hii01o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1539760d4cf9ab085c5bad1b30dc687f3fd55665/test/scripts/test-utils.sh#L276)):*
> ```Shell
>     local gui_test_filename
>     gui_test_filename=$(get_e2e_filename "$CURRENT_VERSION" "$TEST_OS")
>     GUI_TEST_BIN="$package_dir"/"$gui_test_filename"
> ```

Casing looks inconsistent now. Why is this uppercase if `app_package` is lowercase?
___
*[`test/test-manager/src/run_tests.rs` line 155 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O386g5lEZT25wG-ndHD:-O386g5lEZT25wG-ndHE:b-8dvrga) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1539760d4cf9ab085c5bad1b30dc687f3fd55665/test/test-manager/src/run_tests.rs#L155)):*
> hej
___
*[`test/test-manager/src/tests/install.rs` line 172 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O2yMiSJ9mheu7Lwo9cG:-O388k99ArCn8Epw5h23:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/179e8b7d5f27c7dc69a2f718e9340d331563a4f9/test/test-manager/src/tests/install.rs#L172)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

I make reinstalling the app (and logging in) a part of the new `prepare_daemon` step that replaces the post test cleanup
</blockquote></details>

:+1: 
___
*[`test/test-manager/src/tests/install.rs` line 162 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O388pBU7vkWT87Y1uhL:-O388pBU7vkWT87Y1uhM:b-dbiap6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1539760d4cf9ab085c5bad1b30dc687f3fd55665/test/test-manager/src/tests/install.rs#L162)):*
> ```XML
>     mut mullvad_client: MullvadProxyClient,
> ) -> anyhow::Result<()> {
>     if rpc.mullvad_daemon_get_status().await? != ServiceStatus::Running {
> ```

Nit: I guess we don't really need this now. The preparation stuff should verify this, right?
___
*[`test/test-manager/src/tests/install.rs` line 177 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O3890usELEM0PZCylNz:-O3890usELEM0PZCylO-:bf2e32r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1539760d4cf9ab085c5bad1b30dc687f3fd55665/test/test-manager/src/tests/install.rs#L177)):*
> ```XML
>     // TODO: Remove once we can login before upgrade above
>     mullvad_client
>         .login_account(TEST_CONFIG.account_number.clone())
> ```

`ensure_logged_in` handles this for us now, right?


<!-- Sent from Reviewable.io -->

2024-08-05 09:34 UTC, Serock3 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`test/scripts/test-utils.sh` line 54 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O382JWg6RAa32fak4AT:-O3Wk-PB5Y95FJ1lZpGK:b-896fjx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1539760d4cf9ab085c5bad1b30dc687f3fd55665/test/scripts/test-utils.sh#L54)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: I think you can replace this with `package_dir=$(cd "$PACKAGE_DIR" && pwd)` and remove `pushd/popd`
</blockquote></details>

Done
___
*[`test/scripts/test-utils.sh` line 276 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O383PCh5aVCUdVFp0nK:-O3WpvKI5kePDAfrLT1X:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1539760d4cf9ab085c5bad1b30dc687f3fd55665/test/scripts/test-utils.sh#L276)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Casing looks inconsistent now. Why is this uppercase if `app_package` is lowercase?
</blockquote></details>

Fixed
___
*[`test/scripts/test-utils.sh` line 200 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O3DUPDD1J9RuiMNZH8H:-O3WkBYdBW8oQ6anHcC7:b-1w3e1s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e0752af79d1d6b8c5e14ede7f04cc926b243dda7/test/scripts/test-utils.sh#L200)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is logged if curl fails for any reason. This log might be a lie.
</blockquote></details>

It's nice to give a hint that the URL may be wrong though, since it's the most likely cause of failure. What could be a better log? :thinking: Maybe `echo "Failed to download package from $url (hint: build may not exist, check the url) 1>&2`?
___
*[`test/test-manager/src/run_tests.rs` line 155 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O386g5lEZT25wG-ndHD:-O3Wlo366c_cKVYyqdO0:b925brb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1539760d4cf9ab085c5bad1b30dc687f3fd55665/test/test-manager/src/run_tests.rs#L155)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

> hej
</blockquote></details>

Whoops, fixed
___
*[`test/test-manager/src/run_tests.rs` line 172 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O3DUuz6C9OlOkKQj1ua:-O3WqMiEBl_ekRWD7C_O:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e0752af79d1d6b8c5e14ede7f04cc926b243dda7/test/test-manager/src/run_tests.rs#L172)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Shouldn't `store_records(false)` be called before `run_test`?

```
        if print_failed_tests_only {
            // Stop live record
            logger.store_records(true);
        }
```
</blockquote></details>

Done
___
*[`test/test-manager/src/tests/install.rs` line 162 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O388pBU7vkWT87Y1uhL:-O3Wrfsf5CRb9zFFVFG3:bb74x83) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1539760d4cf9ab085c5bad1b30dc687f3fd55665/test/test-manager/src/tests/install.rs#L162)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: I guess we don't really need this now. The preparation stuff should verify this, right?
</blockquote></details>

True


<!-- Sent from Reviewable.io -->

2024-08-05 13:06 UTC, dlon reviewed
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`test/scripts/test-utils.sh` line 200 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O3DUPDD1J9RuiMNZH8H:-O3Xcq3wEbawbi7JXnox:bp3j3h8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e0752af79d1d6b8c5e14ede7f04cc926b243dda7/test/scripts/test-utils.sh#L200)):*
<details><summary><i>Previously, Serock3 (Sebastian Holmin) wrote…</i></summary><blockquote>

It's nice to give a hint that the URL may be wrong though, since it's the most likely cause of failure. What could be a better log? :thinking: Maybe `echo "Failed to download package from $url (hint: build may not exist, check the url) 1>&2`?
</blockquote></details>

That will do! It's still unchanged here.


<!-- Sent from Reviewable.io -->

2024-08-15 18:24 UTC, dlon requested changes
> Reviewed 3 of 4 files at r14, 3 of 3 files at r15, 17 of 20 files at r17, 7 of 10 files at r18, 10 of 10 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)* status: all files reviewed, 5 unresolved discussions (waiting on @Serock3)

___
*[`test/test-manager/src/tests/account.rs` line 86 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O4MFd117NAvrAFun1mN:-O4MFd117NAvrAFun1mO:b3vdcsd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/864c9ddd8c3725c2ad6a8d9a507993a25d37d30f/test/test-manager/src/tests/account.rs#L86)):*
> ```XML
>     );
> 
>     mullvad_client.logout_account().await?;
> ```

Nit: This and the following line are not required (app isn't logged in).
___
*[`test/test-manager/src/tests/mod.rs` line 152 at r15](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O3cpFa_2GEJC0Ib2aez:-O3cpFaa7Bzk9AioxdvT:bak05ql) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/dacbd65d137ffba124d081ad75587cf82b6724f2/test/test-manager/src/tests/mod.rs#L152)):*
> ```XML
> /// Reset the daemons environment.
> ///
> /// Will and restart or reinstall it if necessary.
> ```

Nit: Outdated comment.
___
*[`test/test-manager/src/tests/mod.rs` line 83 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O4MCk1I16vqetw-SLT8:-O4MCk1I16vqetw-SLT9:b-1owqyz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/864c9ddd8c3725c2ad6a8d9a507993a25d37d30f/test/test-manager/src/tests/mod.rs#L83)):*
> ```XML
> pub fn get_filtered_tests(specified_tests: &[String]) -> Result<Vec<&TestMetadata>, anyhow::Error> {
>     let mut tests = get_tests();
>     tests.retain(|test| test.should_run_on_os(TEST_CONFIG.os));
> ```

Nit, but this might belong in `get_tests`?
___
*[`test/test-manager/src/tests/ui.rs` line 282 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O4MDArE96xlXgDvnVQ0:-O4MDArF1K2Ecs18CeCO:bwvlr96) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/864c9ddd8c3725c2ad6a8d9a507993a25d37d30f/test/test-manager/src/tests/ui.rs#L282)):*
> ```XML
>     mut mullvad_client: MullvadProxyClient,
> ) -> Result<(), Error> {
>     mullvad_client.connect_tunnel().await?;
> ```

Are you sure `settings-import` requires being connected? If so, use `helpers::connect_and_wait` to ensure it will actually wait for the connected state.
___
*[`test/scripts/test-utils.sh` line 53 at r17](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-O4ME7RIDvH2A75HOX6P:-O4ME7RIDvH2A75HOX6Q:b-36xz5t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3fb727f2f656d74e203077bec9c38095122d9815/test/scripts/test-utils.sh#L53)):*
> ```Shell
>     if [[ -n "${PACKAGE_DIR+x}" ]]; then
>         # Resolve the package dir to an absolute path since cargo must be invoked from the test directory
>         package_dir=$(cd "$PACKAGE_DIR" > /dev/null && pwd)
> ```

Will this not fail if the dir doesn't exist? Though maybe that's fine as long as stderr receives anything useful.


<!-- Sent from Reviewable.io -->

2024-08-16 08:16 UTC, dlon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493#-:-O4PFeOp4-ZNm7LR0RZr:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Serock3)



<!-- Sent from Reviewable.io -->

2024-08-16 09:44 UTC, merged