Fix getting stuck after blocked state
mullvad/mullvadvpn-app pull request #6552
Opened 2024-07-31 12:33 UTC by mojganii

The app gets stuck in a blocked state after these transitions:

- The packet tunnel is Connected, then Airplane mode is toggled.

- The packet tunnel is Connected, then no relay constraints are satisfied.

This problem might also occur due to other reasons that result in a blocked state. To solve this issue, we need to refresh the tunnel status after reconnecting tunnel when the block state occurs. This pull request (PR) addresses the issue.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552)

2024-07-31 12:38 UTC, pinkisemils commented
If this is the right solution and it ends up getitng merged, don't forget to mark the other issue as _Done_ too :)

2024-08-08 14:35 UTC, buggmagnet requested changes
> Reviewed 18 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552)* status: 18 of 23 files reviewed, 7 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadMockData/MullvadREST/RelaySelectorStub.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3mLMex7SrZmWz1pdxZ:-O3mLMex7SrZmWz1pdx_:budtgtt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/968f7a547ef193584170fd2ae5839101829bbbab/ios/MullvadMockData/MullvadREST/RelaySelectorStub.swift#L15)):*
> ```Swift
> /// Relay selector stub that accepts a block that can be used to provide custom implementation.
> public final class RelaySelectorStub: RelaySelectorProtocol {
>     var block: (RelayConstraints, UInt) throws -> SelectedRelays
> ```

How about we rename this `selectRelaysResult` 
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3mKWj51c6ILvhFgXyP:-O3mKWj51c6ILvhFgXyQ:bbvrkdr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/968f7a547ef193584170fd2ae5839101829bbbab/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L29)):*
> ```Swift
> //        switch self {
> //            object.build(for theCase)
> //        }
> ```

Let's remove these comments
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 100 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3mKZGYEbWcd74f-WTm:-O3mKZGYEbWcd74f-WTn:bykr4j2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/968f7a547ef193584170fd2ae5839101829bbbab/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L100)):*
> ```Swift
> //    #else
> //    internal var MappingOperation = MapConnectionStatusOperation.self
> //    #endif
> ```

These too 
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 940 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3mK__708W_pg54XxZ0:-O3mK__708W_pg54XxZ1:b-xkngz3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/968f7a547ef193584170fd2ae5839101829bbbab/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L940)):*
> ```Swift
> //            queue: internalQueue,
> //            interactor: TunnelInteractorProxy(self),
> //            connectionStatus: connectionStatus,
> ```

And these as well
___
*[`ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift` line 122 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3mMezX77SKwyMl2DoJ:-O3mMezX77SKwyMl2DoK:btr2hej) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/968f7a547ef193584170fd2ae5839101829bbbab/ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift#L122)):*
> ```Swift
>     }
> 
>     func testExitBlockedStateAfterSatisfyingConstraints() async throws {
> ```

We can add a comment describing what the test does since the setup is quite complicated.
We could say something along the lines of 
___
*[`ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift` line 181 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3mKfW32HsssMc35gbA:-O3mKfW32HsssMc35gbB:bqk2byt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/968f7a547ef193584170fd2ae5839101829bbbab/ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift#L181)):*
> ```Swift
>         await fulfillment(
>             of: [blockedExpectation, connectedExpectation],
>             timeout: .UnitTest.timeout
> ```

We want to make sure that the expectations are met in order here.
```swift
        await fulfillment(
            of: [blockedExpectation, connectedExpectation],
            timeout: .UnitTest.timeout,
            enforceOrder: true
        )
```
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 287 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3mNXQ2EHMoHedgNsAm:-O3mNXQ2EHMoHedgNsAn:bww5x9t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/968f7a547ef193584170fd2ae5839101829bbbab/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L287)):*
> ```Swift
>         reason: ActorReconnectReason
>     ) async throws {
>         defer {
> ```

We should leave this after the call to `stopDefaultPathObserver` 
Otherwise, this will be ran here even if `obfuscateConnection` throws an error (For example, invalid constraints in the relay selector) which is not a desired behaviour.


<!-- Sent from Reviewable.io -->

2024-08-09 12:16 UTC, rablador requested changes
> Reviewed 16 of 23 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552)* status: all files reviewed, 12 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadRESTTests/TransportStrategyTests.swift` line 9 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3quc-SEOhdAuOsruuD:-O3quc-SEOhdAuOsruuE:b6xny7g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/599eb5cc16d32e057812a1f14b2039790ab73529/ios/MullvadRESTTests/TransportStrategyTests.swift#L9)):*
> ```Swift
> //
> 
> @testable import MullvadMockData
> ```

Intentional import?
___
*[`ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3qumln2zml4l-pfpI-:-O3qumln2zml4l-pfpI0:b-5xk1ht) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/599eb5cc16d32e057812a1f14b2039790ab73529/ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift#L25)):*
> ```Swift
>     private let logger = Logger(label: "TunnelManager.MapConnectionStatusOperation")
> 
>     required init(
> ```

Is this change necessary?
___
*[`ios/MullvadVPN/TunnelManager/SendTunnelProviderMessageOperation.swift` line 63 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3qutkdAFVMbaqf44gn:-O3qutkdAFVMbaqf44go:b-dirdrx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/599eb5cc16d32e057812a1f14b2039790ab73529/ios/MullvadVPN/TunnelManager/SendTunnelProviderMessageOperation.swift#L63)):*
> ```Swift
>         addObserver(
>             BackgroundObserver(
>                 application: backgroundTaskProvider,
> ```

"application" should probably be renamed to "backgroundTaskProvider".
___
*[`ios/MullvadVPN/TunnelManager/TunnelInteractor.swift` line 19 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3qwS4U80FOyNEmBLp7:-O3qwS4U80FOyNEmBLp8:b838a69) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/599eb5cc16d32e057812a1f14b2039790ab73529/ios/MullvadVPN/TunnelManager/TunnelInteractor.swift#L19)):*
> ```Swift
> 
>     var tunnel: (any TunnelProtocol)? { get }
>     var application: any BackgroundTaskProvider { get }
> ```

There is this and other places in the code where "application" hasn't been renamed to the match the new type.
___
*[`ios/MullvadMockData/MullvadREST/AccessMethodRepository+Stub.swift` line 12 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3r3CUXCh2cN0GUe8BM:-O3r3CUXCh2cN0GUe8BN:bmnd1mt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aad94894e0a73da7c45f61f10d9bab1f033ea1ea/ios/MullvadMockData/MullvadREST/AccessMethodRepository%2BStub.swift#L12)):*
> ```Swift
> import MullvadSettings
> 
> public struct AccessMethodRepositoryStub: AccessMethodRepositoryDataSource {
> ```

Do we need to make all these public?


<!-- Sent from Reviewable.io -->

2024-08-10 10:10 UTC, acb-mv approved these changes
> Reviewed 5 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552)* status: all files reviewed, 12 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-08-12 11:29 UTC, buggmagnet approved these changes
> Reviewed 4 of 23 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552)* status: all files reviewed, 5 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-08-12 16:16 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552)* status: 18 of 27 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadMockData/MullvadREST/RelaySelectorStub.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3mLMex7SrZmWz1pdxZ:-O3mPq6-41Pi65958Sro:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/968f7a547ef193584170fd2ae5839101829bbbab/ios/MullvadMockData/MullvadREST/RelaySelectorStub.swift#L15)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

How about we rename this `selectRelaysResult`
</blockquote></details>

Done.
___
*[`ios/MullvadRESTTests/TransportStrategyTests.swift` line 9 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3quc-SEOhdAuOsruuD:-O46JQNU46Q5ioA1ulxq:bbolfs0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/599eb5cc16d32e057812a1f14b2039790ab73529/ios/MullvadRESTTests/TransportStrategyTests.swift#L9)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Intentional import?
</blockquote></details>

`AccessMethodRepositoryStub` was moved to `MullvadMockData` .
___
*[`ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift` line 25 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3qumln2zml4l-pfpI-:-O46JsmY3FQeXnU4KBku:brpf2xp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/599eb5cc16d32e057812a1f14b2039790ab73529/ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift#L25)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Is this change necessary?
</blockquote></details>

Which one is drawing your attention?  I didn't get the difference. 
___
*[`ios/MullvadVPN/TunnelManager/SendTunnelProviderMessageOperation.swift` line 63 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3qutkdAFVMbaqf44gn:-O46KX192hDAteR4PW1p:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/599eb5cc16d32e057812a1f14b2039790ab73529/ios/MullvadVPN/TunnelManager/SendTunnelProviderMessageOperation.swift#L63)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

"application" should probably be renamed to "backgroundTaskProvider".
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/TunnelManager/TunnelInteractor.swift` line 19 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3qwS4U80FOyNEmBLp7:-O46KroJ5jjE6uUN2FVJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/599eb5cc16d32e057812a1f14b2039790ab73529/ios/MullvadVPN/TunnelManager/TunnelInteractor.swift#L19)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

There is this and other places in the code where "application" hasn't been renamed to the match the new type.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3mKWj51c6ILvhFgXyP:-O3mPs-sDu3A2Crc_SfD:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/968f7a547ef193584170fd2ae5839101829bbbab/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L29)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's remove these comments
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 100 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3mKZGYEbWcd74f-WTm:-O3mPxy0BwcsTXOoWYsX:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/968f7a547ef193584170fd2ae5839101829bbbab/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L100)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

These too
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/TunnelManager/TunnelManager.swift` line 940 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3mK__708W_pg54XxZ0:-O3mPyX52zrMaQWZNEXN:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/968f7a547ef193584170fd2ae5839101829bbbab/ios/MullvadVPN/TunnelManager/TunnelManager.swift#L940)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

And these as well
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift` line 122 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3mMezX77SKwyMl2DoJ:-O3mQ-5p7vqZbhxL8rZH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/968f7a547ef193584170fd2ae5839101829bbbab/ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift#L122)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We can add a comment describing what the test does since the setup is quite complicated.
We could say something along the lines of
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift` line 181 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3mKfW32HsssMc35gbA:-O3mQbvh6ZVwQIdQDcPM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/968f7a547ef193584170fd2ae5839101829bbbab/ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift#L181)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We want to make sure that the expectations are met in order here.
```swift
        await fulfillment(
            of: [blockedExpectation, connectedExpectation],
            timeout: .UnitTest.timeout,
            enforceOrder: true
        )
```
</blockquote></details>

Done.
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor.swift` line 287 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3mNXQ2EHMoHedgNsAm:-O3mQpKs1dDVNBnutxGL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/968f7a547ef193584170fd2ae5839101829bbbab/ios/PacketTunnelCore/Actor/PacketTunnelActor.swift#L287)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We should leave this after the call to `stopDefaultPathObserver` 
Otherwise, this will be ran here even if `obfuscateConnection` throws an error (For example, invalid constraints in the relay selector) which is not a desired behaviour.
</blockquote></details>

Done.
___
*[`ios/MullvadMockData/MullvadREST/AccessMethodRepository+Stub.swift` line 12 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552#-O3r3CUXCh2cN0GUe8BM:-O46IV5-1hweYbiQEztD:b-jevrmm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aad94894e0a73da7c45f61f10d9bab1f033ea1ea/ios/MullvadMockData/MullvadREST/AccessMethodRepository%2BStub.swift#L12)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Do we need to make all these public?
</blockquote></details>

Yes, wea re using that in `TunnelManagerTests`.


<!-- Sent from Reviewable.io -->

2024-08-13 09:23 UTC, buggmagnet approved these changes
> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552)* status: all files reviewed, 5 unresolved discussions (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2024-08-13 09:56 UTC, merged