Bump dates for all osv scanner ignored vulns and added reasons
mullvad/mullvadvpn-app pull request #6565
Opened 2024-08-05 10:02 UTC by Pururun

Added a shorter deadline for `jose4j` since that one is hopefully fixed by upgrading the AGP plugin.

See this google issue:
https://issuetracker.google.com/issues/299134781

2024-08-05 14:47 UTC, albin-mullvad reviewed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/gradle/osv-scanner.toml` line 4 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565#-O3XwDCI1GFxCX6_RzNQ:-O3XwDCI1GFxCX6_RzNR:bp3ezc6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7af6b25fcbfc95b59e9680317c410cf0b22a928b/android/gradle/osv-scanner.toml#L4)):*
> ```TOML
> #
> # Temporarily ignoring all reported android vulnerabilites with a one month deadline
> # since we plan to examine the vulnerabilites and bootstrap this file with proper
> ```

I suggest rephrasing to:

```
# The OWASP Dependency-Check tool is also used for vulnerability scanning.
```



_Code quote:_
```TOML
# Also worth mentioning that we're already using the OWASP Dependency-Check tool
# for the android code base as of before.
```
___
*[`android/gradle/osv-scanner.toml` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565#-O3XxMkCCXZ89aStNIUs:-O3XxMkD7gXpmaUJC96c:b-zphq9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9f16b96e1a9ef893e08a3d548e8d38e9dd68d8b/android/gradle/osv-scanner.toml#L24)):*
> ```TOML
> id = "CVE-2023-44487" # GHSA-xpw8-rcwv-8f8p
> ignoreUntil = 2024-11-02
> reason = "No impact on this app since it uses UDS rather than HTTP2."
> ```

nit: use or skip `.` consistently throughout these `reason`s



_Code quote:_
```TOML
.
```
___
*[`android/gradle/osv-scanner.toml` line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565#-O3XybATB9-vKI9Pn7-x:-O3XybATB9-vKI9Pn7-y:brqfw2h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9f16b96e1a9ef893e08a3d548e8d38e9dd68d8b/android/gradle/osv-scanner.toml#L59)):*
> ```TOML
> id = "GHSA-jgvc-jfgh-rjvv"
> ignoreUntil = 2024-09-02
> reason = "Used by gradle bundler, will be fixed by upgrading the android gradle plugin"
> ```

nit: change to `Used by the`? Applies to other `reason`s as well



_Code quote:_
```TOML
Used by
```
___
*[`android/gradle/osv-scanner.toml` line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565#-O3XzvMJ-vXq8gsEVDg-:-O3XzvMK55zCDBWzPU1r:b-c2ii6f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7af6b25fcbfc95b59e9680317c410cf0b22a928b/android/gradle/osv-scanner.toml#L66)):*
> ```TOML
> 
> [[IgnoredVulns]]
> id = "CVE-2022-24329" # GHSA-2qp4-g3q3-f92w
> ```

We might want to split these into `IgnoredVulns`, but we can wait with that until we've discussed it internally. Here's a newly created issue to track that.



_Code quote:_
```TOML
[[PackageOverrides]]
```
___
*[`android/gradle/osv-scanner.toml` line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565#-O3Xwb_D5beFWKJEo14s:-O3Xwb_D5beFWKJEo14t:bqx1k4p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9f16b96e1a9ef893e08a3d548e8d38e9dd68d8b/android/gradle/osv-scanner.toml#L85)):*
> ```TOML
> ignore = true
> effectiveUntil = 2024-11-02
> reason = "Used by lint and the dependency gradle plugin and not the app directly"
> ```

typo:  change to something like `dependency-check tool` or `Dependency-Check tool`

Would be nice to also consistently refer to it the same way throughout this file. 



_Code quote:_
```TOML
dependency gradle plugin
```


<!-- Sent from Reviewable.io -->

2024-08-05 16:32 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565)* status: all files reviewed, 5 unresolved discussions (waiting on @Pururun)

___
*[`android/gradle/osv-scanner.toml` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565#-O3YMm2f3AxvX-35SViO:-O3YMm2f3AxvX-35SViP:b-vm25jc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9f16b96e1a9ef893e08a3d548e8d38e9dd68d8b/android/gradle/osv-scanner.toml#L53)):*
> ```TOML
> [[IgnoredVulns]]
> id = "CVE-2023-31582" # GHSA-7g24-qg88-p43q
> ignoreUntil = 2024-09-02
> ```

Is there a reason why this and the one below expired `2024-09-02` when everything else expires `2024-11-02`?


<!-- Sent from Reviewable.io -->

2024-08-06 07:59 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565)* status: all files reviewed, 5 unresolved discussions (waiting on @Rawa)

___
*[`android/gradle/osv-scanner.toml` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565#-O3YMm2f3AxvX-35SViO:-O3ag8Hg9sENm65Rn19I:bv98xhp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9f16b96e1a9ef893e08a3d548e8d38e9dd68d8b/android/gradle/osv-scanner.toml#L53)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Is there a reason why this and the one below expired `2024-09-02` when everything else expires `2024-11-02`?
</blockquote></details>

Yes, because those are hopefully fixed by updating the gradle plugin which is ongoing work. I think we should also check for other ignores that can be removed while updating the gradle plugin, but if we forget about it this could serve as a reminder.


<!-- Sent from Reviewable.io -->

2024-08-06 08:37 UTC, Rawa approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)

___
*[`android/gradle/osv-scanner.toml` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565#-O3YMm2f3AxvX-35SViO:-O3apPk77B7aZeZVLeO9:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9f16b96e1a9ef893e08a3d548e8d38e9dd68d8b/android/gradle/osv-scanner.toml#L53)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Yes, because those are hopefully fixed by updating the gradle plugin which is ongoing work. I think we should also check for other ignores that can be removed while updating the gradle plugin, but if we forget about it this could serve as a reminder.
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2024-08-06 08:37 UTC, Rawa approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)



<!-- Sent from Reviewable.io -->

2024-08-06 10:59 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565#-:-O3bKyStEdYxabIBn50H:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/gradle/osv-scanner.toml` line 59 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565#-O3XybATB9-vKI9Pn7-x:-O3bKsNlD7TOp0MaPrNc:b-gr3m3v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9f16b96e1a9ef893e08a3d548e8d38e9dd68d8b/android/gradle/osv-scanner.toml#L59)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done Did not change to "the lint" because that sounded weird, but maybe that should be changed as well?
</blockquote></details>

Great! No need to change the lint one
___
*[`android/gradle/osv-scanner.toml` line 66 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565#-O3XzvMJ-vXq8gsEVDg-:-O3bKp-KDVegeA7v2Zd4:b4c9lyr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7af6b25fcbfc95b59e9680317c410cf0b22a928b/android/gradle/osv-scanner.toml#L66)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Yeah I think it is fine to postpone it a little bit, I also have a small hope that it might be solved by updating the android gradle plugin.
</blockquote></details>

:thumbsup: 
___
*[`android/gradle/osv-scanner.toml` line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565#-O3Xwb_D5beFWKJEo14s:-O3bKi8N9xfFjmm3lnDb:b2modi2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b9f16b96e1a9ef893e08a3d548e8d38e9dd68d8b/android/gradle/osv-scanner.toml#L85)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done changed it to `dependency-check tool`
</blockquote></details>

nice :thumbsup: 


<!-- Sent from Reviewable.io -->

2024-08-06 14:27 UTC, merged