Allow relay selector to filter daita enabled relays ios 772
mullvad/mullvadvpn-app pull request #6590
Opened 2024-08-09 09:49 UTC by rablador

When DAITA is enabled, the relay selector should only match DAITA enabled relays for the entry location when using multihop. If no DAITA relays can be matched, the packet tunnel should enter the blocked state - ideally with an error message displayed to the user that makes it obvious that no relays were matched due to none of the eligible ones allowing DAITA.

When using single-hop and DAITA is enabled only DAITA enabled relays should be considered first - the best suitable DAITA relay should be picked if at all possible. Otherwise, if the exit constraints do not match any DAITA enabled relay, the relay selector should use multihop to select a valid DAITA relay for the entry.

2024-08-15 12:39 UTC, acb-mv requested changes
> Reviewed 1 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590)* status: 1 of 26 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadREST/ApiHandlers/ServerRelaysResponse.swift` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590#-O4L1_QM06OUA4DvN5BK:-O4L1_QM06OUA4DvN5BL:bcrij93) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4c4cbe159a728071dee89c7e46ddaa825fd188d/ios/MullvadREST/ApiHandlers/ServerRelaysResponse.swift#L37)):*
> ```Swift
>         public let weight: UInt64
>         public let includeInCountry: Bool
>         public var daita: Bool?
> ```

Wouldn't a statement such as `hasDAITA` be a clearer name?
___
*[`ios/MullvadREST/Relay/AnyRelay.swift` line 20 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590#-O4L1p590Rdo4yuOOn73:-O4L1p590Rdo4yuOOn74:bcrij93) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4c4cbe159a728071dee89c7e46ddaa825fd188d/ios/MullvadREST/Relay/AnyRelay.swift#L20)):*
> ```Swift
>     var active: Bool { get }
>     var includeInCountry: Bool { get }
>     var daita: Bool? { get }
> ```

Wouldn't a statement such as `hasDAITA` be a clearer name?


<!-- Sent from Reviewable.io -->

2024-08-15 13:05 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590)* status: 1 of 26 files reviewed, 2 unresolved discussions (waiting on @acb-mv)

___
*[`ios/MullvadREST/ApiHandlers/ServerRelaysResponse.swift` line 37 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590#-O4L1_QM06OUA4DvN5BK:-O4L6YVh5al1KvBvDaQ4:b1zt0n5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4c4cbe159a728071dee89c7e46ddaa825fd188d/ios/MullvadREST/ApiHandlers/ServerRelaysResponse.swift#L37)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Wouldn't a statement such as `hasDAITA` be a clearer name?
</blockquote></details>

I agree, but that's the name we get from the servers. We could have custom coding keys, but it feels like more work than it's worth.


<!-- Sent from Reviewable.io -->

2024-08-16 08:25 UTC, acb-mv approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590#-:-O4PHZ0Y6PjPvN7A7VaJ:bnfp4nl)* status: 1 of 26 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-19 08:23 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590)* status: all files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadREST/Relay/NoRelaysSatisfyingConstraintsError.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590#-O4dergx30vbs1Jn-mBw:-O4dergx30vbs1Jn-mBx:b-atdd5v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4c4cbe159a728071dee89c7e46ddaa825fd188d/ios/MullvadREST/Relay/NoRelaysSatisfyingConstraintsError.swift#L14)):*
> ```Swift
>     case filterConstraintNotMatching
>     case invalidPort
>     case multihopEntryEqualsExit
> ```

I suggest to eliminate `multihop` keyword, what do you think about `relaysAreEqual`.
___
*[`ios/MullvadVPNTests/MullvadREST/Relay/RelayPickingTests.swift` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590#-O4dg_E14ScmVVSq4zAU:-O4dg_E14ScmVVSq4zAV:b-hk7xgp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4c4cbe159a728071dee89c7e46ddaa825fd188d/ios/MullvadVPNTests/MullvadREST/Relay/RelayPickingTests.swift#L27)):*
> ```Swift
>         let picker = SinglehopPicker(
>             constraints: constraints,
>             daitaSettings: DAITASettings(state: .off),
> ```

let's call them with the default value when the test isn't around `DaitaSettings`. if we set default value to `on` in the future, we will need to update these tests either.



_Code snippet:_
```Swift
 daitaSettings: DAITASettings()
```
___
*[`ios/MullvadVPNTests/MullvadREST/Relay/RelayPickingTests.swift` line 76 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590#-O4QFtgK-Co5qkTJM5OT:-O4dimNd9QQZ828Cqngd:b32v57) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4c4cbe159a728071dee89c7e46ddaa825fd188d/ios/MullvadVPNTests/MullvadREST/Relay/RelayPickingTests.swift#L76)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Shouldn't we have a test for the `noDaitaRelaysFound` single picker case ?
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2024-08-19 09:24 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590)* status: 20 of 26 files reviewed, 7 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadREST/Relay/NoRelaysSatisfyingConstraintsError.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590#-O4dergx30vbs1Jn-mBw:-O4djfQ70lJcVZ3PwinE:b-7n52uc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4c4cbe159a728071dee89c7e46ddaa825fd188d/ios/MullvadREST/Relay/NoRelaysSatisfyingConstraintsError.swift#L14)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I suggest to eliminate `multihop` keyword, what do you think about `relaysAreEqual`.
</blockquote></details>

Opting to keep entry and exit in the wording to more clearly convey what's going on.
___
*[`ios/MullvadREST/Relay/NoRelaysSatisfyingConstraintsError.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590#-O4PDAfx5uFaZi5vsjag:-O4deapv7wCyhApp5UJe:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4c4cbe159a728071dee89c7e46ddaa825fd188d/ios/MullvadREST/Relay/NoRelaysSatisfyingConstraintsError.swift#L15)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Can we find a better name for this ? Maybe `multihopInvalidFlow` ?
</blockquote></details>

Done.
___
*[`ios/MullvadREST/Relay/NoRelaysSatisfyingConstraintsError.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590#-O4PDej8Bb5oaTexFRl3:-O4duP45BXVN5R-HpN20:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4c4cbe159a728071dee89c7e46ddaa825fd188d/ios/MullvadREST/Relay/NoRelaysSatisfyingConstraintsError.swift#L25)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Since we log this, it would be interesting to improve this error message and see why we threw the error.

```swift
    public var errorDescription: String? {
        switch reason {
        case .filterConstraintNotMatching:
            "No relays satisfying constraints."
        case .invalidPort:
            "Invalid port selected by RelaySelector"
        case .multihopEntryEqualsExit:
            "Entry hop and Exit hop are the same"
        case .multihopOther:
            "Invalid multihop decision flow"
        case .noActiveRelaysFound:
            "No active relays found"
        case .noDaitaRelaysFound:
            "No Daita relays found"
        case .relayConstraintNotMatching:
            "Invalid constraint created to pick a relay"
        }
    }
```
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift` line 242 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590#-O4QE_63069xCTSW6G1S:-O4dewq69rtPhs3rZRMg:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4c4cbe159a728071dee89c7e46ddaa825fd188d/ios/MullvadVPN/Notifications/Notification%20Providers/TunnelStatusNotificationProvider.swift#L242)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

The entry and exit server*s* cannot be the same.
</blockquote></details>

Done.
___
*[`ios/MullvadVPNTests/MullvadREST/Relay/RelayPickingTests.swift` line 27 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590#-O4dg_E14ScmVVSq4zAU:-O4dueEY33gkJTLb8Vh6:b-yf0tib) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4c4cbe159a728071dee89c7e46ddaa825fd188d/ios/MullvadVPNTests/MullvadREST/Relay/RelayPickingTests.swift#L27)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

let's call them with the default value when the test isn't around `DaitaSettings`. if we set default value to `on` in the future, we will need to update these tests either.
</blockquote></details>

With the current test setup (and sample relays) we will get a `.noDaitaRelaysFound` error instead. I specifically want DAITA to be off here so that we test only entry and exit error and don't involve DAITA at all, even if it's default in the app or not.
___
*[`ios/MullvadVPNTests/MullvadREST/Relay/RelayPickingTests.swift` line 76 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590#-O4QFtgK-Co5qkTJM5OT:-O4diuRZCIDmwX_dJumt:bofx99e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4c4cbe159a728071dee89c7e46ddaa825fd188d/ios/MullvadVPNTests/MullvadREST/Relay/RelayPickingTests.swift#L76)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

+1
</blockquote></details>

`RelayPicking` protocol is concerned with multihop and makes sure the picking of one-one, one-many, many-many relationsships work correctly. A DAITA specific test already exists in `RelaySelectorTests.testRelayWithDaita`.
___
*[`ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderManager.swift` line 175 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590#-O4QF2X117vfLomwxLRJ:-O4desAP1SK1zvb_mgwS:b-pkzycw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a4c4cbe159a728071dee89c7e46ddaa825fd188d/ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderManager.swift#L175)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Did you accidentally rename this ?
</blockquote></details>

Yes, fixed.


<!-- Sent from Reviewable.io -->

2024-08-19 14:02 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590#-:-O4ewdNzC2WJVmZLOYBR:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-08-20 08:06 UTC, mojganii approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6590)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-08-21 09:37 UTC, merged