Disable ATS entirely
mullvad/mullvadvpn-app pull request #6642
Opened 2024-08-19 13:43 UTC by buggmagnet

This PR disables ATS entirely from our application. 
This requires justifying to apple why we do this, and we feel we have a good explanation in hand : 

- We do not trust DNS systems
- We do SSL pinning so we cannot do insecure connections to our API (we already validate the TLS connection ourselves)

2024-08-20 07:10 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6642)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-20 10:49 UTC, mojganii requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6642)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Supporting Files/Info.plist` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6642#-O4jO4BUAzCe14EGxPZq:-O4jO4BVEjKh1YaX1EdI:b-k9gjcb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2585294dee8c6f86f76e03d6aff221955b65749c/ios/MullvadVPN/Supporting%20Files/Info.plist#L65)):*
> ```
> 			</dict>
> 		</dict>
> 		<key>NSPinnedDomains</key>
> ```

we haven't set `SSLPinningURLSessionDelegate` for the url session of `OutgoingConnectionProxy`.if we are gonna removing pining here then we have to add `SSLPinningURLSessionDelegate` into `OutgoingConnectionProxy`.



_Code snippet:_
```
    outgoingConnectionProxy: OutgoingConnectionProxy(
                    urlSession: REST.makeURLSession(),
                    hostname: ApplicationConfiguration.hostName
                )
```


<!-- Sent from Reviewable.io -->

2024-08-21 14:18 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6642)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/Supporting Files/Info.plist` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6642#-O4jO4BUAzCe14EGxPZq:-O4pIHHyDb414UGWFYzn:b-4hfsgh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6b0bb523b82578b80f111f66681eb87517340530/ios/MullvadVPN/Supporting%20Files/Info.plist#L65)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

we haven't set `SSLPinningURLSessionDelegate` for the url session of `OutgoingConnectionProxy`.if we are gonna removing pining here then we have to add `SSLPinningURLSessionDelegate` into `OutgoingConnectionProxy`.
</blockquote></details>

Good catch ! I've fixed `SSLPinningURLSessionDelegate` to work with conn-check too.


<!-- Sent from Reviewable.io -->

2024-08-22 11:15 UTC, rablador approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6642)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-08-23 13:05 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6642#-:-O4zKmbU78nG3_cWAOgO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-26 11:34 UTC, rablador approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6642)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-27 07:50 UTC, merged