Packet tunnel stuck in blocked state after flightmode ios 707
mullvad/mullvadvpn-app pull request #6647
Opened 2024-08-20 12:06 UTC by mojganii

When the reason for the blocked state is a tunnel adapter error, we need to automatically recover the connection to attempt reconnection to the current relay, keeping the tunnel up to date. This PR introduces that functionality.

2024-08-21 14:28 UTC, buggmagnet requested changes
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift` line 155 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647#-O4pKUENBXNQmDMYVvnS:-O4pKUENBXNQmDMYVvnT:b5yhpwj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/004ae25cba813f877921bd6d5329dfc8441821e1/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BErrorState.swift#L155)):*
> ```Swift
> 
>                 // Schedule task to reconnect.
>                 eventChannel.send(.reconnect(.current))
> ```

Won't that mean that if we're blocked because the current relay we're trying to connect to is offline, we will stay in the blocked state until the user actually selects a different relay ?
___
*[`ios/PacketTunnelCore/Actor/State+Extensions.swift` line 191 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647#-O4pJjG16i2Xh_M7ckZR:-O4pJjG16i2Xh_M7ckZS:b442lsm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/004ae25cba813f877921bd6d5329dfc8441821e1/ios/PacketTunnelCore/Actor/State%2BExtensions.swift#L191)):*
> ```Swift
>      - App update that requires settings schema migration. Packet tunnel will be automatically restarted after update but it would not be able to read settings until
>        user opens the app which performs migration.
>      - Packet tunnel will be automatically restarted when there is tunnel adapter error.
> ```

nit
when there is *a* tunnel adapter error


<!-- Sent from Reviewable.io -->

2024-08-22 09:26 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift` line 155 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647#-O4pKUENBXNQmDMYVvnS:-O4tOFzG3qLDCmo3syMu:b-anivvh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/004ae25cba813f877921bd6d5329dfc8441821e1/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BErrorState.swift#L155)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it means whenever `WireGuardAdapterError` happens then let's retry to connect the current one after a time interval . do you think if there us any cases in `WireGuardAdapterError` that wether it happens we need to consider reconnecting to the new one?
</blockquote></details>

Let's say the user has specifically selected `gothenburg` and was connected to `se-got-wg-001`, but it went offline due to maintenance.
Now we are going to try to connect to `se-got-wg-001` despite it being offline, and the user will be in the blocked state despite having relays available.

My question is : Do we need to reconnect to the current relay to fix the problem ? Or can we fix the solution by selecting a random relay (within constraints) ?


<!-- Sent from Reviewable.io -->

2024-08-22 09:58 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift` line 155 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647#-O4pKUENBXNQmDMYVvnS:-O4tUf4H2td_oD4ZL-Rx:bf71c22) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/004ae25cba813f877921bd6d5329dfc8441821e1/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BErrorState.swift#L155)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's say the user has specifically selected `gothenburg` and was connected to `se-got-wg-001`, but it went offline due to maintenance.
Now we are going to try to connect to `se-got-wg-001` despite it being offline, and the user will be in the blocked state despite having relays available.

My question is : Do we need to reconnect to the current relay to fix the problem ? Or can we fix the solution by selecting a random relay (within constraints) ?
</blockquote></details>

I see what you mean, when the current relay is out of order, with reconnecting to the current one we are captivating user while the rest relays are available but when user has no internet connection I believe it has to retry to connect to the current one,I think we have to have 2 different  approaches:
1- user is offline due to bad or connection, then we have to connect to the current one for recovery
2- if internet is reachable but the relay doesn't respond try to go for the new one.

the current approach doesn't support both scenarios.


<!-- Sent from Reviewable.io -->

2024-08-22 11:14 UTC, rablador reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift` line 155 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647#-O4pKUENBXNQmDMYVvnS:-O4tjsYt66xbwuraMb0l:b-syrpql) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/004ae25cba813f877921bd6d5329dfc8441821e1/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BErrorState.swift#L155)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I see what you mean, when the current relay is out of order, with reconnecting to the current one we are captivating user while the rest relays are available but when user has no internet connection I believe it has to retry to connect to the current one,I think we have to have 2 different  approaches:
1- user is offline due to bad or connection, then we have to connect to the current one for recovery
2- if internet is reachable but the relay doesn't respond try to go for the new one.

the current approach doesn't support both scenarios.
</blockquote></details>

Until we make a complete solution that supports both scenarios I think we should try to connect to a new relay to make sure we cover scenario 2. It's a little unnecessary to change relay when the connection is bad, but it doesn't matter too much.


<!-- Sent from Reviewable.io -->

2024-08-22 11:45 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift` line 155 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647#-O4pKUENBXNQmDMYVvnS:-O4ttD7u2HNKfI9NlR-K:b-cdimpb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/004ae25cba813f877921bd6d5329dfc8441821e1/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BErrorState.swift#L155)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Until we make a complete solution that supports both scenarios I think we should try to connect to a new relay to make sure we cover scenario 2. It's a little unnecessary to change relay when the connection is bad, but it doesn't matter too much.
</blockquote></details>

I agree. regardless if user's connection went bad or relay is unavailable, let app try to connect to the new one. @buggmagnet what do you think if we do reconnecting tor the new one for every scenarios?


<!-- Sent from Reviewable.io -->

2024-08-22 13:06 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift` line 155 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647#-O4pKUENBXNQmDMYVvnS:-O4uBVfzBJR6ev8bNehg:b3wm5lr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/004ae25cba813f877921bd6d5329dfc8441821e1/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BErrorState.swift#L155)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I agree. regardless if user's connection went bad or relay is unavailable, let app try to connect to the new one. @buggmagnet what do you think if we do reconnecting tor the new one for every scenarios?
</blockquote></details>

I think this is the least likely to break other scenarios. So we put it back to `.random` right ?


<!-- Sent from Reviewable.io -->

2024-08-23 13:06 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift` line 155 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647#-O4pKUENBXNQmDMYVvnS:-O4zL0PbA6K9OTOmlxRT:bb7sa0c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/004ae25cba813f877921bd6d5329dfc8441821e1/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BErrorState.swift#L155)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I think this is the least likely to break other scenarios. So we put it back to `.random` right ?
</blockquote></details>

yes.


<!-- Sent from Reviewable.io -->

2024-08-23 13:15 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/PacketTunnelCore/Actor/State+Extensions.swift` line 191 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647#-O4pJjG16i2Xh_M7ckZR:-O4zN3HZ1CPC--uWg1iQ:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/004ae25cba813f877921bd6d5329dfc8441821e1/ios/PacketTunnelCore/Actor/State%2BExtensions.swift#L191)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
when there is *a* tunnel adapter error
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-08-26 11:34 UTC, rablador approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-08-27 08:19 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647#-:-O5Husrz7IlDJ8BzYl33:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-27 08:22 UTC, merged