Remove split tunnel interface if split tunneling is disabled
mullvad/mullvadvpn-app pull request #6666
Opened 2024-08-23 08:39 UTC by MarkusPettersson98

In the current split tunnel design, the split tunnel interface is never destroyed once it has been created. This PR removes the split tunnel interface when split tunneling is disabled, since any potential issues with split tunneling should not affect anyone who disables the feature.

2024-08-23 13:23 UTC, dlon requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6666)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`talpid-core/src/split_tunnel/macos/mod.rs` line 435 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6666#-O4zN0h68iul_x6LJJww:-O4zN0h68iul_x6LJJwx:b-di41y4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56afeb4126b81aa673d3e6f043cef873edfa7c80/talpid-core/src/split_tunnel/macos/mod.rs#L435)):*
> ```XML
>                 vpn_interface,
>             } if paths.is_empty() => {
>                 drop(tun_handle);
> ```

We should shut these down gracefully rather than just drop them. See `Self::shutdown()`. That could probably be called here.
___
*[`talpid-core/src/split_tunnel/macos/mod.rs` line 512 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6666#-O4zO6nk0caHDAA7AR4G:-O4zO6nk0caHDAA7AR4H:bukik1o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56afeb4126b81aa673d3e6f043cef873edfa7c80/talpid-core/src/split_tunnel/macos/mod.rs#L512)):*
> ```XML
> 
>                 match tun_handle
>                     .set_interfaces(default_interface, Some(vpn_interface.clone()))
> ```

`vpn_interface` is shadowed by the old/existing value here.


<!-- Sent from Reviewable.io -->

2024-08-23 14:02 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6666)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`talpid-core/src/split_tunnel/macos/mod.rs` line 435 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6666#-O4zN0h68iul_x6LJJww:-O4zXwdrEGlVQFatd0dy:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56afeb4126b81aa673d3e6f043cef873edfa7c80/talpid-core/src/split_tunnel/macos/mod.rs#L435)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We should shut these down gracefully rather than just drop them. See `Self::shutdown()`. That could probably be called here.
</blockquote></details>

Done
___
*[`talpid-core/src/split_tunnel/macos/mod.rs` line 512 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6666#-O4zO6nk0caHDAA7AR4G:-O4zY-2gCnutAXpS2xGA:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/56afeb4126b81aa673d3e6f043cef873edfa7c80/talpid-core/src/split_tunnel/macos/mod.rs#L512)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`vpn_interface` is shadowed by the old/existing value here.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-08-26 13:33 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6666)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-26 20:44 UTC, dlon requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6666)* status: all files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`talpid-core/src/split_tunnel/macos/mod.rs` line 505 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6666#-O5FPeCh9QH0db0Sw4QU:-O5FPeCh9QH0db0Sw4QV:btol8i4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b5a8776c6452b34c2e62f2bda168e3be9b08022/talpid-core/src/split_tunnel/macos/mod.rs#L505)):*
> ```XML
>                                 process,
>                                 tun_handle,
>                                 vpn_interface,
> ```

Previously, the state wasn't altered when failing, but now it seems to receive the new VPN interface. It could probably become out of sync with `tun`, so might be best to keep the old behavior.


<!-- Sent from Reviewable.io -->

2024-08-27 06:30 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6666)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-core/src/split_tunnel/macos/mod.rs` line 505 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6666#-O5FPeCh9QH0db0Sw4QU:-O5HWagG1_VdfTvlJDfv:bj4k01s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/998ca2f5b5ee674942e0085be6cb9ab0ae3befdb/talpid-core/src/split_tunnel/macos/mod.rs#L505)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Previously, the state wasn't altered when failing, but now it seems to receive the new VPN interface. It could probably become out of sync with `tun`, so might be best to keep the old behavior.
</blockquote></details>

Ah yes, that's a fair point. Reverted that change, so now the old VPN interface is kept upon failure.


<!-- Sent from Reviewable.io -->

2024-08-27 07:24 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6666)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-27 09:11 UTC, merged