Fix out-of-time notifications
mullvad/mullvadvpn-app pull request #6679
Opened 2024-08-26 11:23 UTC by rablador

Currently the iOS app sends but a single notification about running out of time. 

We should schedule 4 in-app notifications, with improved copy:

- "You have 3 days left on this account."
- “You have 2 days left on this account.”
- “You have 1 day left on this account.”
- "You have less than a day left on this account. Please add more time to continue using the VPN.”

We should also schedule 3 system notifications, with improved copy:

- "You have 3 days left on this account. Please add more time to continue using the VPN.."
- “You have one day left on this account. Please add more time to continue using the VPN.”
- "Blocking internet: Your time on this account has expired. To continue using the internet, please add more time or disconnect the VPN.”

2024-08-26 11:26 UTC, rablador reviewed
Can be tested by invoking eg. the snippet below (please modify as needed) somewhere in `initTunnelManagerOperation` (`AppDelegate`), after tunnel manager is fully initialized. Account expired system notification cannot be tested this way due to it working in a different manner.

Task {
            try await delay(seconds: 5)

            print("Simulate close to expiry, 3 days")
            self.tunnelManager.simulateAccountExpiration(option: .closeToExpiry(days: 3))
            try await delay(seconds: 5)

            print("Simulate close to expiry, 2 days")
            self.tunnelManager.simulateAccountExpiration(option: .closeToExpiry(days: 2))
            try await delay(seconds: 5)

            print("Simulate close to expiry, 1 day")
            self.tunnelManager.simulateAccountExpiration(option: .closeToExpiry(days: 1))
            try await delay(seconds: 5)

            print("Simulate close to expiry, 0 days")
            self.tunnelManager.simulateAccountExpiration(option: .closeToExpiry(days: 0))
            try await delay(seconds: 5)

            print("Simulate expired account")
            self.tunnelManager.simulateAccountExpiration(option: .expired)
            try await delay(seconds: 5)

            print("Simulate active account")
            self.tunnelManager.simulateAccountExpiration(option: .active)
        }

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679#-:-O5DQLZo6MrjAkUS3USO:bmw04mt)* status: 0 of 8 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-28 08:59 UTC, buggmagnet requested changes
It looks like you forgot to provide the implementation for `delay`, `Task.sleep` did the trick however.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679#-:-O5N1iXsBDE4vLhb6FVc:bhdua1n)* status: all files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpiry.swift` line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679#-O5N3DH03vYDKnzY5d4E:-O5N3DH03vYDKnzY5d4F:b-4brnio) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce3712a341f670aff548445fa610bd3fec76e270/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpiry.swift#L85)):*
> ```Swift
>     // Used to compare dates with a precision of a minimum of seconds.
>     var secondsPrecision: Date {
>         Date(timeIntervalSince1970: TimeInterval(Int(timeIntervalSince1970)))
> ```

I have to say, it feels really convoluted to do this. I think we could have done entirely the same thing just using a single point in time, and calendar operations. 

But it seems to work pretty well, so I'll leave it at that.
___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpirySystemNotificationProvider.swift` line 100 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679#-O5N4ep284hcI7Zfmn9B:-O5N4ep284hcI7Zfmn9C:bn6s1i5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce3712a341f670aff548445fa610bd3fec76e270/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpirySystemNotificationProvider.swift#L100)):*
> ```Swift
>         let dateComponents = Calendar.current.dateComponents(
>             [.second, .minute, .hour, .day, .month, .year],
>             from: Date().addingTimeInterval(1) // Giving some leeway.
> ```

Can we clarify what "giving some leeway" means here ?


<!-- Sent from Reviewable.io -->

2024-09-02 09:33 UTC, rablador reviewed
Ah, right!

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679#-:-O5l_veS5vyf2B6DsE_Q:bcn3o5h)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpiry.swift` line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679#-O5N3DH03vYDKnzY5d4E:-O5m2p561wu0lRnUH0_L:b-9if036) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce3712a341f670aff548445fa610bd3fec76e270/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpiry.swift#L85)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I have to say, it feels really convoluted to do this. I think we could have done entirely the same thing just using a single point in time, and calendar operations. 

But it seems to work pretty well, so I'll leave it at that.
</blockquote></details>

Indeed, done.
___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpirySystemNotificationProvider.swift` line 100 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679#-O5N4ep284hcI7Zfmn9B:-O5loqhA3OC8YYSD8v1K:b-9f087b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ce3712a341f670aff548445fa610bd3fec76e270/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpirySystemNotificationProvider.swift#L100)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Can we clarify what "giving some leeway" means here ?
</blockquote></details>

Yep, done.


<!-- Sent from Reviewable.io -->

2024-09-16 08:24 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpirySystemNotificationProvider.swift` line 117 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679#-O6trpgh06vCV1Ve9WBr:-O6trpgh06vCV1Ve9WBs:b-q7v7ig) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57ed7726499af977b042c34c934609503aea7b31/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpirySystemNotificationProvider.swift#L117)):*
> ```Swift
>         }
> 
>         let accountHasExpired = deviceState.accountData?.isExpired == true
> ```

nit : we can remove the equity expression. an use the variable for the next line 
___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpirySystemNotificationProvider.swift` line 120 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679#-O6tsRUhDfqalNXJwHwt:-O6tsRUhDfqalNXJwHwu:b-3gxlt4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57ed7726499af977b042c34c934609503aea7b31/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpirySystemNotificationProvider.swift#L120)):*
> ```Swift
>         let accountHasRecentlyExpired = deviceState.accountData?.isExpired != previousDeviceState.accountData?.isExpired
> 
>         self.accountHasRecentlyExpired = blockedStateByExpiredAccount && accountHasExpired && accountHasRecentlyExpired
> ```

isn't enough to compare the previous one state with the new one to realise if the account has been expired recently or not? must we evaluate the tunnel state for blocking state with the reason to be sure it's blocked? I feel we are over-evaluating to figure out  if it's expired recently or not.
___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpirySystemNotificationProvider.swift` line 146 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679#-O6tuUvMAsccHmlZh4Xi:-O6tuUvMAsccHmlZh4Xj:befoa70) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57ed7726499af977b042c34c934609503aea7b31/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpirySystemNotificationProvider.swift#L146)):*
> ```Swift
>     }
> 
>     private var formattedRemainingDurationBody: String? {
> ```

nit : I think we can make it better  :



_Code snippet:_
```Swift
     private var formattedRemainingDurationBody: String? {
        guard !accountHasRecentlyExpired, let daysRemaining = accountExpiry.daysRemaining(for: .system)?.day else {
            return expiredText
        }
        return daysRemaining == 1 ? singleDayText : multipleDaysText
    }
```


<!-- Sent from Reviewable.io -->

2024-09-17 11:30 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpirySystemNotificationProvider.swift` line 120 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679#-O6tsRUhDfqalNXJwHwt:-O6zeU0p8LJVsb9s1FpX:b-y3an3v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57ed7726499af977b042c34c934609503aea7b31/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpirySystemNotificationProvider.swift#L120)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

isn't enough to compare the previous one state with the new one to realise if the account has been expired recently or not? must we evaluate the tunnel state for blocking state with the reason to be sure it's blocked? I feel we are over-evaluating to figure out  if it's expired recently or not.
</blockquote></details>

I'm adding extra security here to make sure we don't accidentally spam users with notifications. Basically making sure that:

1. Blocked state is because of account expiry, so that we don't trigger for any kind of blocked state.
2. Current state is blocked state.
3. Previous expiry state is not the same as current expiry state. This last check alone can't decide if we went from expired -> not expired, or the other way around. That's why I combine 2) and 3).


<!-- Sent from Reviewable.io -->

2024-09-17 14:08 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpirySystemNotificationProvider.swift` line 117 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679#-O6trpgh06vCV1Ve9WBr:-O6zlOHc886tCB4tm5hH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57ed7726499af977b042c34c934609503aea7b31/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpirySystemNotificationProvider.swift#L117)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit : we can remove the equity expression. an use the variable for the next line
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Notifications/Notification Providers/AccountExpirySystemNotificationProvider.swift` line 146 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679#-O6tuUvMAsccHmlZh4Xi:-O6zln_w7xsicCC9Cq9Q:b-sp8hj9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/57ed7726499af977b042c34c934609503aea7b31/ios/MullvadVPN/Notifications/Notification%20Providers/AccountExpirySystemNotificationProvider.swift#L146)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit : I think we can make it better  :
</blockquote></details>

This doesn't work since no `.day` should return `nil` rather than `expiredText`. This will in turn make `notificationRequest` return nil, which will prevent a notification being sent. `accountHasRecentlyExpired` will check that account expiry was recent, but for all other cases (account expired sometime in the past and no longer relevant) there should be no notification date to trigger.


<!-- Sent from Reviewable.io -->

2024-09-18 11:47 UTC, rablador reviewed
Did some updates to fix the last system notification on account expiry. Code got less convoluted as well.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679#-:-O73xDP20bWD97-HCRFa:b-oo2huz)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2024-09-23 13:56 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679#-:-O7U9rEw2F0-R1guCjzg:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-09-23 14:05 UTC, mojganii approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6679)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-09-24 06:18 UTC, merged