Add negative leak test for Android
mullvad/mullvadvpn-app pull request #6691
Opened 2024-08-28 11:19 UTC by niklasberglund

2024-08-29 09:04 UTC, Rawa reviewed
> Reviewed 4 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 3 of 11 files reviewed, 25 unresolved discussions (waiting on @niklasberglund)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt` line 90 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SFK2-ADQmKwkwBryu:-O5SFK2-ADQmKwkwBryv:brdnr9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt#L90)):*
> ```Kotlin
>     }
> 
>     fun extractOutIpAddress(): String {
> ```

Out is implicit from `extract`
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt` line 100 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SFP_u8AcyLS4Rthp8:-O5SFP_u8AcyLS4Rthp9:b-lwbzfh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt#L100)):*
> ```Kotlin
>                 .text
> 
>         val extractedIpAddress = outString.split(" ")[1].split(" ")[0]
> ```

Why do we have two split twice here? I believe the second split is unnecessary. Also you already have a `extractOutIpAddress()` that can be reused.
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt` line 144 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SFztsCzugbV3b8bJs:-O5SFztsCzugbV3b8bJt:bxlm2dt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt#L144)):*
> ```Kotlin
> 
>     private fun String.extractOutIpAddress(): String {
>         return split(" ")[1].split(" ")[0]
> ```

Same here, `.split(" ")[0]` should be removable.
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt` line 147 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SGWfi-rMSfRmaUZfV:-O5SGWfi-rMSfRmaUZfW:b-xhspsc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt#L147)):*
> ```Kotlin
>     }
> 
>     private fun String.separateInIpAddress(): String {
> ```

:+1: Good that this is private, since String is a commonly used type so we don't want to pollute the scope of `String.`
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SH88h5RNRLAgruNir:-O5SH88h5RNRLAgruNis:b4b1kgs) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L33)):*
> ```Kotlin
>             val trafficGenerator = TrafficGenerator(targetIpAddress, 80)
> 
>             val session = packetCapture.startCapture()
> ```

Maybe the api of a capture can be more intuitive. Right now the user must `startCapture` and `stopCapture`, another alternative would be something like a scope. Without going into to much code could probably look like something like this:

```
packetCapture.createSession {
    // Create session starts with running startCapture()

    // Do stuff where we want to capture the packages

    // Once this lambda is complete stop the capture session and return the result.
}
```
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SH0jm4GPN0A68RBTw:-O5SH0jm4GPN0A68RBTx:b-xm5zvg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L35)):*
> ```Kotlin
>             val session = packetCapture.startCapture()
>             packetCaptureClient.sendStartCaptureRequest(session)
>             trafficGenerator.startGeneratingUDPTraffic(100)
> ```

Reminder to use [Duration](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-duration/)
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SIC_63wmEr4DOzpuS:-O5SIC_63wmEr4DOzpuT:b-5eihbg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L49)):*
> ```Kotlin
> 
>             device.findObjectWithTimeout(By.text("Disconnect")).click()
>             Thread.sleep(2000)
> ```

Feels a bit blunt to do Thread.sleep, we should be able to use `delay()` instead
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SI6fUDiuheRmUEiyp:-O5SI6fVB1Xu3pDmvIxf:buaqhr2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L53)):*
> ```Kotlin
>             trafficGenerator.stopGeneratingUDPTraffic()
>             packetCaptureClient.sendStopCaptureRequest(session)
>             val streamCollection = packetCapture.stopCapture(session)
> ```

It feels a bit redundant where we have to stop twice, doesn't really feel necessary.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SI_zV1XCZVM8M6suq:-O5SI_zV1XCZVM8M6sur:b-ek4b1r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L55)):*
> ```Kotlin
>             val streamCollection = packetCapture.stopCapture(session)
>             val connectedThroughRelayStartEndDatePair =
>                 streamCollection.getConnectedThroughRelayStartEndDate(relayIpAddress)
> ```

This variable and function looks like something taken out of ObjectiveC :sweat_smile: Try and create a more consice and readable function and variable name.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SInL5Eeh0ix_UAcFb:-O5SInL5Eeh0ix_UAcFc:b3seoje) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt#L10)):*
> ```Kotlin
>     companion object {
>         fun getIPAddress(): String {
>             NetworkInterface.getNetworkInterfaces()?.toList()?.map { networkInterface ->
> ```

As mentioned before, it could probably be worth using `!!` if there is something we don't expect to fail, or that is completely fatal. It should also fail the test.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SIzPw6egfJSgoxxXH:-O5SIzPw6egfJSgoxxXI:bf1ik53) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt#L14)):*
> ```Kotlin
>                     ?.toList()
>                     ?.find { !it.isLoopbackAddress && it is Inet4Address }
>                     ?.let {
> ```

A bit over use of let, assign to `val`
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 22 at r1](https://reviewable.io/r [...]

2024-09-03 08:25 UTC, Pururun reviewed
> Reviewed 2 of 11 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: all files reviewed, 26 unresolved discussions (waiting on @niklasberglund)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/StreamCollection.kt` line 88 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5qytor6DczaBpqBoU2:-O5qytor6DczaBpqBoU3:bdvma1r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c8fe6a0c1c15f3906b1a320e5cacc18074300b7/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/StreamCollection.kt#L88)):*
> ```Kotlin
> 
>     fun dontAllowTrafficFromTestDevice(toHost: String) {
>         streams.forEach { stream ->
> ```

Since we get all packages from all streams in a bunch of places, maybe it could be useful to have some kind of `allPackages()` helper function?


<!-- Sent from Reviewable.io -->

2024-09-09 08:42 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 1 of 19 files reviewed, 26 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt` line 100 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SFP_u8AcyLS4Rthp8:-O66ehhsEudEFx-3jpwg:ba3dfob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt#L100)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Why do we have two split twice here? I believe the second split is unnecessary. Also you already have a `extractOutIpAddress()` that can be reused.
</blockquote></details>

Removed
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt` line 144 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SFztsCzugbV3b8bJs:-O66ee72Bzk6IxhtvNti:ba3dfob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt#L144)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Same here, `.split(" ")[0]` should be removable.
</blockquote></details>

Removed
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SH88h5RNRLAgruNir:-O61kX3f57ZlDxgByWSs:by0vf36) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L33)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Maybe the api of a capture can be more intuitive. Right now the user must `startCapture` and `stopCapture`, another alternative would be something like a scope. Without going into to much code could probably look like something like this:

```
packetCapture.createSession {
    // Create session starts with running startCapture()

    // Do stuff where we want to capture the packages

    // Once this lambda is complete stop the capture session and return the result.
}
```
</blockquote></details>

Packet capture session and traffic generation session are now scope based
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SH0jm4GPN0A68RBTw:-O61l5PlAOQ1M4oUH1MP:b8niu8h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L35)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Reminder to use [Duration](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-duration/)
</blockquote></details>

Switched to Duration
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SIC_63wmEr4DOzpuS:-O65JM-31T3n6DvOaIv5:b-jy2s4t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L49)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Feels a bit blunt to do Thread.sleep, we should be able to use `delay()` instead
</blockquote></details>

Changed to using delay
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 53 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SI6fUDiuheRmUEiyp:-O61lB7x9--q-dI3RkZP:buhi7qa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L53)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

It feels a bit redundant where we have to stop twice, doesn't really feel necessary.
</blockquote></details>

The capture code was a bit messy before, have been tidied up and using a scoped function instead now
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SI_zV1XCZVM8M6suq:-O61lKIQ01TiKfym5zzU:b-s6dojb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L55)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This variable and function looks like something taken out of ObjectiveC :sweat_smile: Try and create a more consice and readable function and variable name.
</blockquote></details>

This function is no longer needed so it has been removed, but I have probably introduced some other long names 😅
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SJ4Go08jLA8CmC_L3:-O65be8R4Kvq9f9lqop0:b-ynnwy4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L22)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Not sure of the data structures of things here but this sounds more like a SessionId with its current content. Also if it is a UUID, let it be a UUID. Also if it is just an identifier we should consider using a `value class` instead
</blockquote></details>

It is now a `UUID`
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SJZH32UWoCJhw6d8k:-O65bh_X1sp2bWH3GV0f:bxz8q6g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L33)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Do we care if this fail? Can we really always guarantee that we will return a `StreamCollection`?
</blockquote></details>

Have added error handling - failing test if there's an error response
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 57 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SKIda8Ef7f1IGcocQ:-O66_MOS2ASGpclD-VQJ:b-p9t582) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L57)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should be able to create a data structure representing this message and just serializing that. E.g

```
data class StartCaptureRequest(
    val label: PacketCaptureSession
)
```
and then just serialize it as JSON. Then you don't have to have a hard-coded label in the function.
</blockquote></details>

Ah yes. Hmm now `PacketCaptureSession` has been removed, using `UUID` directly instead.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 61 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SKhDM3QE8eHnWEYsG:-O66_WjU2sOPwAykuKS2:b-d9g34v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/ [...]

2024-09-09 11:18 UTC, Pururun approved these changes
> Reviewed 2 of 13 files at r3, 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: all files reviewed, 25 unresolved discussions (waiting on @niklasberglund and @Rawa)



<!-- Sent from Reviewable.io -->

2024-09-10 07:28 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 18 of 19 files reviewed, 25 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SInL5Eeh0ix_UAcFb:-O6Pp2cGCTM0lnnd6UeM:bzeuum5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt#L10)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

As mentioned before, it could probably be worth using `!!` if there is something we don't expect to fail, or that is completely fatal. It should also fail the test.
</blockquote></details>

Turned out these weren't nullable 😯
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SIzPw6egfJSgoxxXH:-O6Pp-Xj3VcJPL0CBBMJ:b499q7j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt#L14)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

A bit over use of let, assign to `val`
</blockquote></details>

Changed


<!-- Sent from Reviewable.io -->

2024-09-10 14:32 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 18 of 19 files reviewed, 27 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SIC_63wmEr4DOzpuS:-O6RFV0h8UUuTb0YLPcO:b-a402qy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L49)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Changed to using delay
</blockquote></details>

There is still `Thread.sleep` here
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 78 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RF6rYDc22vqehSf0s:-O6RF6rYDc22vqehSf0t:bk9cr44) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L78)):*
> ```Kotlin
>             lateinit var captureResult: PacketCaptureResult
>             val connectTime = DateTime.now()
>             TrafficGenerator(targetIpAddress, targetPort).generateTraffic(10.milliseconds) {
> ```

Shouldn't this be the other way around? Now we would start generating traffic and then start capturing, thus we might miss some packets until the capture has started. Also then we don't have to do:
```
lateinit var captureResult: PacketCaptureResult
```
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 93 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RGM2b-4D160-TiFfZ:-O6RGM2b-4D160-TiFf_:b-17f4jk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L93)):*
> ```Kotlin
> 
>             val capturedStreams = captureResult.streams
>             val capturedPcap = captureResult.pcap
> ```

This is not used by anything right now, should it be removed?
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 95 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RGIMC6kToCq8sLzIi:-O6RGIMC6kToCq8sLzIj:b-wdlbq4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L95)):*
> ```Kotlin
>             val capturedPcap = captureResult.pcap
> 
>             // Attachment.saveAttachment("capture.pcap", "should-leak", capturedPcap)
> ```

Should this still be here?
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 152 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RGswy11IvmdxKibRx:-O6RGswy11IvmdxKibRy:ba3dfna) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L152)):*
> ```Kotlin
> 
>             // val pcapContent = packetCapture.getPcap()
>             // Attachment.saveAttachment("capture.pcap", "should-leak", pcapContent.toByteArray())
> ```

Remove?
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SInL5Eeh0ix_UAcFb:-O6RGz8I4m6CuL760DrQ:b-7r2hvw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt#L10)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Turned out these weren't nullable 😯
</blockquote></details>

They can be null, `Enumeration<NetworkInterface>!`. The `!` notifies you can Kotlin can determine nullability since it invokes java code.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt` line 7 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RHkpt66tTeftwGZiK:-O6RHkpt66tTeftwGZiL:bj3jxnx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt#L7)):*
> ```Kotlin
> import org.junit.Assert.fail
> 
> class Networking {
> ```

Do we have a usage for this class? Otherwise `getIpAddress` can just be a function straight away
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SJ4Go08jLA8CmC_L3:-O6RHwI8C3PTyZTe8POo:b-eg32ji) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L22)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

It is now a `UUID`
</blockquote></details>

Not sure if you missed to push latest, but It is still a `String` here.

Edit: Saw that you said further down that you've removed this class, I think it shouldn't be removed, we should use a `value class` containing a UUID, it is more clean and less error prone.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 55 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RIXsEEC6FM3G54xgb:-O6RIXsEEC6FM3G54xgc:b-pa7njd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L55)):*
> ```Kotlin
>     }
> 
>     suspend fun capturePackets(block: suspend () -> Unit): PacketCaptureResult = runBlocking {
> ```

Is it intented to use `runBlocking` here? To wait in the test case?
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 60 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RIpigDZIHUr-zqFhC:-O6RIpigDZIHUr-zqFhD:b-37cmgn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L60)):*
> ```Kotlin
>         stopCapture()
>         val parsedCapture = getParsedCapture()
>         val pcapString = getPcap()
> ```

Maybe there should be a `private finishCapture(): PackertCaptureResult` that does all these 3 things?
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 137 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RJgK7BhpOhh7_Uq-W:-O6RJgK7BhpOhh7_Uq-X:b-c95841) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L137)):*
> ```Kotlin
> data class Host(val ipAddress: String, val port: Int)
> 
> object PacketSerializer : KSerializer<List<Packet>> {
> ```

Is this really needed? Feels like you should be able to let serializationx do this for you? Or was it the boolean thing causing this to be the case?
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 182 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RKMuOApLAZP6cNrn-:-O6RKMuOApLAZP6cNrn0:b-ar1uof) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L182)):*
> ```Kotlin
>             destinationAddressAndPort.split(":").first(),
>             destinationAddressAndPort.split(":").last().toIn [...]

2024-09-10 14:33 UTC, Rawa reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: all files reviewed, 27 unresolved discussions (waiting on @niklasberglund)



<!-- Sent from Reviewable.io -->

2024-09-16 13:44 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 15 of 19 files reviewed, 26 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt` line 90 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SFK2-ADQmKwkwBryu:-O6v3782Dz7HLDVIDvqv:bylcf5v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt#L90)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Out is implicit from `extract`
</blockquote></details>

"Out" refers to the out IP address
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SIC_63wmEr4DOzpuS:-O6uBbofDEHmmOng6ZtB:b-2y2vfw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L49)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

There is still `Thread.sleep` here
</blockquote></details>

Replaced with delay
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 78 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RF6rYDc22vqehSf0s:-O6uBROrEROLu3Ck1qo5:b-8k61ie) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L78)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Shouldn't this be the other way around? Now we would start generating traffic and then start capturing, thus we might miss some packets until the capture has started. Also then we don't have to do:
```
lateinit var captureResult: PacketCaptureResult
```
</blockquote></details>

Doing it the other way around now
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 93 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RGM2b-4D160-TiFfZ:-O6v2HZTB4GgqMe49QRZ:bdmbtul) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L93)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This is not used by anything right now, should it be removed?
</blockquote></details>

See answer below https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RGIMC6kToCq8sLzIi
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 95 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RGIMC6kToCq8sLzIi:-O6v1tRI43TfrSadyTho:b-64feou) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L95)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should this still be here?
</blockquote></details>

Indecisive. There's a separate Linear issue for storing PCAP files, but most of that ticket has actually been implemented in this PR already. https://linear.app/mullvad/issue/DROID-1315/store-pcap-files-from-packet-captures-on-device

I'm leaning towards implementing this issue as well in this PR. How do you think?
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt` line 7 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RHkpt66tTeftwGZiK:-O6uEgwBAZJZ7gNt71Zj:b9l3grr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt#L7)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Do we have a usage for this class? Otherwise `getIpAddress` can just be a function straight away
</blockquote></details>

Good point, but I'm anticipating that this class will grow. For iOS end to end tests there's a "Networking" class which is quite big https://github.com/mullvad/mullvadvpn-app/blob/dc5544701738ad3fab4738bc9314ef95e8d6731e/ios/MullvadVPNUITests/Networking/Networking.swift
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SJ4Go08jLA8CmC_L3:-O6uGjzR8JDsDMo1vsR4:bo9xxfe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L22)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Not sure if you missed to push latest, but It is still a `String` here.

Edit: Saw that you said further down that you've removed this class, I think it shouldn't be removed, we should use a `value class` containing a UUID, it is more clean and less error prone.
</blockquote></details>

Turned this into a `UUID` and passing around `PacketCatpureSession` data class objects instead of `UUID`
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SJgc0-GxRDCDHsWVL:-O6uW-1n7mCydqYKjS1W:b-pb87tm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L43)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Hard-coded string, if we want to store this it should probably be a `const val` and if it is supposed to be with this class it should be in a `companion object` otherwise it would create one string for each instance of the class.
</blockquote></details>

Moved to companion object
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SJvaE60QIyhjIgZkI:-O6uWc3B0_gl2uJPvZN_:bvemyw6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L44)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Preferable we want to inject as much dependencies through the constructor as possible. Not sure of the requirements in this case, `e.g isLenient` and `prettyPrint` but we should consider providing this client through the constructor.
</blockquote></details>

It looks like they cannot be set through the constructor in this case unless I'm missing something, but it's good to know. I'll keep this in mind.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 57 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SKIda8Ef7f1IGcocQ:-O6uqcVs8tlDjznOqTeA:bms6rx1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L57)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Still, present, we should avoid using `buildJsonObject` and instead use serialize from kotlinx.serialization.
</blockquote></details>

Replaced with a serializable data class
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 73 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691# [...]

2024-09-20 08:05 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 13 of 19 files reviewed, 26 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SInL5Eeh0ix_UAcFb:-O78iXCu44KcXw7Pjku_:b698mqz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt#L10)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

They can be null, `Enumeration<NetworkInterface>!`. The `!` notifies you can Kotlin can determine nullability since it invokes java code.
</blockquote></details>

Not-null asserting `getNetworkInterfaces()`
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 53 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RQXet3n7usoOBd-Fb:-O78jDng9xQ6SnhJ0u5S:b-y6ykyf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L53)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Consider
```
private suspend fun getPcap() = client.sendGetPcapFileRequest(sessionUUID).pcapContent.body<String>().also {
        Logger.v("PCAP content: $it")
    }
```
```
private suspend fun getPcap(): String {
    return client.sendGetPcapFileRequest(sessionUUID)
                          .pcapContent.body<String>()
                          .also {
                                Logger.v("PCAP content: $it")
                           }
    }
```
</blockquote></details>

Nice suggestion 👍 Actually the the PCAP content was just debug logging which should've been removed, so I removed it now.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 55 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RIXsEEC6FM3G54xgb:-O78jfRMEpFVPOyk2fo0:bxc8skn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L55)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Is it intented to use `runBlocking` here? To wait in the test case?
</blockquote></details>

It is intended, I believe it is required because `suspend` functions are invoked? Or is there some other better way?
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 60 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RIpigDZIHUr-zqFhC:-O78k3Bu2V-65LuJ5Hww:b4t2dr0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L60)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Maybe there should be a `private finishCapture(): PackertCaptureResult` that does all these 3 things?
</blockquote></details>

This is already in the relatively low level class `PacketCapture` so I think adding an abstraction layer might make it difficult to follow. The `capturePackets` block function is already an abstraction.


<!-- Sent from Reviewable.io -->

2024-09-25 07:12 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 13 of 19 files reviewed, 20 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt` line 11 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O7byLxe7CymY0Z4Suf0:-O7byLxe7CymY0Z4Suf1:bom5cv4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60358b7db8c81e5f73c49af5fc6a4620991aff2d/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt#L11)):*
> ```Kotlin
> 
> class Attachment {
>     companion object {
> ```

No companion object needed, `object Attachment`
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt` line 37 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O7by_PB8lnnMqk0Pv8d:-O7by_PB8lnnMqk0Pv8e:bsys5i7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60358b7db8c81e5f73c49af5fc6a4620991aff2d/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt#L37)):*
> ```Kotlin
>         }
> 
>         private fun testAttachmentsDirectory(): File {
> ```

Does this really need to be a function? or can we not just assign it to a val? 
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SIC_63wmEr4DOzpuS:-O7bzEQk7JYW-PRZ6jhu:bvr31l4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L49)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Replaced with delay
</blockquote></details>

Why do we need the delay? Is it really needed? If so we should document why.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 95 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RGIMC6kToCq8sLzIi:-O7bzRnn3wTrAopi8aXZ:b-oajx2t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L95)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Indecisive. There's a separate Linear issue for storing PCAP files, but most of that ticket has actually been implemented in this PR already. https://linear.app/mullvad/issue/DROID-1315/store-pcap-files-from-packet-captures-on-device

I'm leaning towards implementing this issue as well in this PR. How do you think?
</blockquote></details>

I'm open to either way. 
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 124 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O7c-6097yajbQqCGT6U:-O7c-60AA-2S_qYPlNK1:b-uhqqku) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60358b7db8c81e5f73c49af5fc6a4620991aff2d/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L124)):*
> ```Kotlin
>                 captureResult =
>                     PacketCapture().capturePackets {
>                         relayIpAddress = app.extractInIpAddress()
> ```

Can't we move this to under "SECURE CONNECTION" find Object? We should be connected and also have a `InIpAddress`, right? Then we get rid of the `lateinit var`
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 146 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O7bzlj94uEf_LE_Qwgf:-O7bzlj94uEf_LE_Qwgg:bjfewxg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60358b7db8c81e5f73c49af5fc6a4620991aff2d/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L146)):*
> ```Kotlin
>             val capturedPcap = captureResult.pcap
> 
>             // val pcapContent = packetCapture.getPcap()
> ```

Old code?
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt` line 7 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RHkpt66tTeftwGZiK:-O7c-rVo6wY0v73b8nqr:b-wynd0a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt#L7)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Good point, but I'm anticipating that this class will grow. For iOS end to end tests there's a "Networking" class which is quite big https://github.com/mullvad/mullvadvpn-app/blob/dc5544701738ad3fab4738bc9314ef95e8d6731e/ios/MullvadVPNUITests/Networking/Networking.swift
</blockquote></details>

But there is only static methods in that one is iOS as well, we should either have `Networking` as a `object` or as functions/extension functions straight off.

E.g `Networking.getIpAddress()` might as well be `NetworkInterface.getDefaultIpAddress()`, then we don't hide away that we really are using the NetworkInterface.


<!-- Sent from Reviewable.io -->

2024-09-25 07:26 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 13 of 19 files reviewed, 10 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SJ4Go08jLA8CmC_L3:-O7c1BVU8hE2W6io-wx-:b-z10x8g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L22)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Turned this into a `UUID` and passing around `PacketCatpureSession` data class objects instead of `UUID`
</blockquote></details>

Don't forget to make it a `value class`.

`value class PacketCaptureSession(val value: UUID = UUID.randomUUID())`
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SJvaE60QIyhjIgZkI:-O7c1ba9Dxs2WoP-Jbuv:b-sggxe3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L44)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

It looks like they cannot be set through the constructor in this case unless I'm missing something, but it's good to know. I'll keep this in mind.
</blockquote></details>

To clarify, we should inject these into the constructor of the `PacketCaptureClient`.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 57 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SKIda8Ef7f1IGcocQ:-O7c2dHq8ymHy9KccEFS:bszy640) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L57)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Replaced with a serializable data class
</blockquote></details>

It is still using a String under the hood, we should be able to make it have a `PacketCaptureSession` type, looks this for an example:
https://stackoverflow.com/questions/65398284/kotlin-serialization-serializer-has-not-been-found-for-type-uuid
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 55 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RIXsEEC6FM3G54xgb:-O7c1Lfe-XBHHqhayeoI:bip4eko) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L55)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

It is intended, I believe it is required because `suspend` functions are invoked? Or is there some other better way?
</blockquote></details>

Since you are a suspending function the runBlocking shouldn't be needed.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 137 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RJgK7BhpOhh7_Uq-W:-O7c3Szp4kMXBTXFL-4a:b-mwqezn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L137)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Myea, I'm not 100% sure but from what I have read the polymorphism offered out of the box is to separate between classes with `@SerialName("expected-type-value-here")` which maps based on the value of a `type` attribute. We could request a `type` attribute to be added, but maybe that would be something that can be improved later?
</blockquote></details>

I'm fine with that.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 182 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RKMuOApLAZP6cNrn-:-O7c3b6tBlCjORKE16xX:bod08rb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L182)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Yes that's much better. Using this approach now. Is `fromString` the common convention for naming a factory method or should it have some other name?
</blockquote></details>

Name sounds good to me :) 
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 30 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O7c28omBZTK4pg_dE61:-O7c28omBZTK4pg_dE62:brshoff) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60358b7db8c81e5f73c49af5fc6a4620991aff2d/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L30)):*
> ```Kotlin
> 
> data class PacketCaptureSession(val identifier: UUID = UUID.randomUUID()) {
>     override fun toString(): String {
> ```

This function should not be needed.


<!-- Sent from Reviewable.io -->

2024-09-26 14:22 UTC, albin-mullvad reviewed
> Reviewed 1 of 6 files at r2, 1 of 13 files at r3, 9 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 13 of 19 files reviewed, 10 unresolved discussions (waiting on @niklasberglund, @Pururun, and @Rawa)

___
*[`wireguard-go-rs/libwg/wireguard-go` line 1 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O7igzG9DSzEQUTZ0dw0:-O7igzGA41h2qjGvOO6-:b-1iatt3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60358b7db8c81e5f73c49af5fc6a4620991aff2d/wireguard-go-rs/libwg/wireguard-go#L1)):*
> ```
> Subproject commit de174ac6de2934dc82d9b8301c17de87cbd575f3
> ```

FYI  looks like you need to update this submodule


<!-- Sent from Reviewable.io -->

2024-09-26 16:01 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 4 of 19 files reviewed, 10 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @Rawa)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt` line 11 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O7byLxe7CymY0Z4Suf0:-O7dghitDdlXQhnQI47j:bdie647) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60358b7db8c81e5f73c49af5fc6a4620991aff2d/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt#L11)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

No companion object needed, `object Attachment`
</blockquote></details>

Is now an object
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt` line 37 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O7by_PB8lnnMqk0Pv8d:-O7dgo7yCDSl8Vm4NiID:b-14kvp2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60358b7db8c81e5f73c49af5fc6a4620991aff2d/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt#L37)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Does this really need to be a function? or can we not just assign it to a val?
</blockquote></details>

That's very true. Converted to `val`
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 49 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SIC_63wmEr4DOzpuS:-O7dhU0i5hkjb-D9pYva:bem80e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L49)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Why do we need the delay? Is it really needed? If so we should document why.
</blockquote></details>

This is an old one which should've been removed. Now it's been removed.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 95 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RGIMC6kToCq8sLzIi:-O7hFwqF-7tBmkDa2z6c:bymsgek) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L95)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I'm open to either way.
</blockquote></details>

Implemented in this PR
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 152 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RGswy11IvmdxKibRx:-O7hG2HiAOGGLv8x-Goc:bg1l1e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L152)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Implemented in this PR now
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 124 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O7c-6097yajbQqCGT6U:-O7hGpte--PExFivwN1M:bceabwh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60358b7db8c81e5f73c49af5fc6a4620991aff2d/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L124)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Can't we move this to under "SECURE CONNECTION" find Object? We should be connected and also have a `InIpAddress`, right? Then we get rid of the `lateinit var`
</blockquote></details>

Good idea, but removed it even, `relayIpAddress` is actually not used by these tests
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 146 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O7bzlj94uEf_LE_Qwgf:-O7hG-ly5wORvQYvgfu1:bg1l1e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60358b7db8c81e5f73c49af5fc6a4620991aff2d/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L146)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Old code?
</blockquote></details>

Implemented in this PR now
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SJ4Go08jLA8CmC_L3:-O7hHZBRExxy_PHLiKe3:bf5n416) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L22)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Don't forget to make it a `value class`.

`value class PacketCaptureSession(val value: UUID = UUID.randomUUID())`
</blockquote></details>

It's now a `value class`
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 44 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SJvaE60QIyhjIgZkI:-O7hiuLuDBOkeED33vCM:b-1a4q5c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L44)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

To clarify, we should inject these into the constructor of the `PacketCaptureClient`.
</blockquote></details>

Injected in constructor now
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 57 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O5SKIda8Ef7f1IGcocQ:-O7hj7Gc6eT38oqhDgah:b-n63mq1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8eac059e695456d13ce53547124b0d91130e049f/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L57)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

It is still using a String under the hood, we should be able to make it have a `PacketCaptureSession` type, looks this for an example:
https://stackoverflow.com/questions/65398284/kotlin-serialization-serializer-has-not-been-found-for-type-uuid
</blockquote></details>

Don't know why I wrote it was serializable, it wasn't! It is now though.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 55 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RIXsEEC6FM3G54xgb:-O7ia6qt-1OFYuPtfktw:bu0g20s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L55)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Since you are a suspending function the runBlocking shouldn't be needed.
</blockquote></details>

You are absolutely right. Removed `runBlocking`
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 30 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O7c28omBZTK4pg_dE61:-O7hHgBMCOPw4hBV0I5D:ba3dfob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60358b7db8c81e5f73c49af5fc6a4620991aff2d/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L30)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This function should not be needed.
</blockquote></details>

Removed


<!-- Sent from Reviewable.io -->

2024-09-26 16:31 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 4 of 19 files reviewed, 10 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @Rawa)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt` line 7 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RHkpt66tTeftwGZiK:-O7j6ZuwB3J0BmlUUVfc:b-9batru) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt#L7)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

But there is only static methods in that one is iOS as well, we should either have `Networking` as a `object` or as functions/extension functions straight off.

E.g `Networking.getIpAddress()` might as well be `NetworkInterface.getDefaultIpAddress()`, then we don't hide away that we really are using the NetworkInterface.
</blockquote></details>

That would be neat. I looked into extending `NetworkInterface` but there's no support for extension functions on the companion object right? 


<!-- Sent from Reviewable.io -->

2024-09-27 07:33 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 3 of 19 files reviewed, 10 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @Rawa)

___
*[`wireguard-go-rs/libwg/wireguard-go` line 1 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O7igzG9DSzEQUTZ0dw0:-O7mOKbJ6Kws5pueAdFU:bbnjbut) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/60358b7db8c81e5f73c49af5fc6a4620991aff2d/wireguard-go-rs/libwg/wireguard-go#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

FYI  looks like you need to update this submodule
</blockquote></details>

Oops, must have commited this by mistake. Updated to `b1cf09a982bba6f6c63fadc956d88e8c2326d05e`


<!-- Sent from Reviewable.io -->

2024-10-01 09:10 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 2 of 20 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad, @niklasberglund, and @Pururun)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt` line 7 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RHkpt66tTeftwGZiK:-O86KmlvCUs9napH1E9I:bcruv2v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt#L7)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

That would be neat. I looked into extending `NetworkInterface` but there's no support for extension functions on the companion object right?
</blockquote></details>

NetworkInterface is just a Java class right?

```
fun NetworkInterface.defaultIpAddress(): InetAddress {
    NetworkInterface.getNetworkInterfaces()!!.toList().map { networkInterface ->
        val address =
            networkInterface.inetAddresses.toList().find {
                !it.isLoopbackAddress && it is Inet4Address
            }

        if (address != null && address.hostAddress != null) {
            return address
        }
    }

    fail("Failed to get test device IP address")
    throw RuntimeException("Fatal")
}
```


<!-- Sent from Reviewable.io -->

2024-10-01 09:13 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 2 of 20 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @Rawa)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt` line 7 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RHkpt66tTeftwGZiK:-O86Lhkp3kuWv0-kFFeg:b2nhswy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt#L7)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

NetworkInterface is just a Java class right?

```
fun NetworkInterface.defaultIpAddress(): InetAddress {
    NetworkInterface.getNetworkInterfaces()!!.toList().map { networkInterface ->
        val address =
            networkInterface.inetAddresses.toList().find {
                !it.isLoopbackAddress && it is Inet4Address
            }

        if (address != null && address.hostAddress != null) {
            return address
        }
    }

    fail("Failed to get test device IP address")
    throw RuntimeException("Fatal")
}
```
</blockquote></details>

Yes


<!-- Sent from Reviewable.io -->

2024-10-01 14:22 UTC, Rawa requested changes
> Reviewed 1 of 4 files at r6, 10 of 13 files at r10, 1 of 1 files at r11, 3 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 17 of 20 files reviewed, 9 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt` line 11 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O86LgWI60IyPlXUzxKP:-O86LgWI60IyPlXUzxKQ:b-sksr8y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt#L11)):*
> ```Kotlin
> object Attachment {
>     private const val DIRECTORY_NAME = "test-attachments"
>     public val testAttachmentsDirectory =
> ```

Remove `public`
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt` line 14 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O873AWJCfWwOhm7DSvC:-O873AWJCfWwOhm7DSvD:b1oelun) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt#L14)):*
> ```Kotlin
>         File(
>             Environment.getExternalStorageDirectory(),
>             Environment.DIRECTORY_DOWNLOADS + "/$DIRECTORY_NAME",
> ```

A bit more clear:
"${Environment.DIRECTORY_DOWNLOADS}/$DIRECTORY_NAME",
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt` line 18 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O873EVrAgfcHJouh7SO:-O873EVrAgfcHJouh7SP:bhpaca1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt#L18)):*
> ```Kotlin
> 
>     fun saveAttachment(fileName: String, data: ByteArray) {
>         if (testAttachmentsDirectory.exists().not()) {
> ```

Personally I don't like the `.not()` I think `!testAttachmentsDirectory.exists()` is more clear.
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt` line 20 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O877Q1t5yR7x9Bwbcqg:-O877Q1t5yR7x9Bwbcqh:b71t4qk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt#L20)):*
> ```Kotlin
>         if (testAttachmentsDirectory.exists().not()) {
>             if (testAttachmentsDirectory.mkdirs().not()) {
>                 fail("Failed to create directory ${testAttachmentsDirectory.absolutePath}")
> ```

Shouldn't it be if either of these fail you should fail the test? not only if both fails? Also should combine to one if statement.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 46 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87ElcmDn0fykKJhePO:-O87ElcmDn0fykKJhePP:b8xswl5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L46)):*
> ```Kotlin
>             localNetworkSharingCell.findObjectWithTimeout(By.res(SWITCH_TEST_TAG))
> 
>         if (localNetworkSharingSwitch.isChecked.not()) {
> ```

Do not each test start on a clean slate? or why do we have to check is the toggle isChecked?

nit: Avoid `not()`.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 116 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87FBn_6Awecp_Xnitf:-O87FBn_6Awecp_Xnitg:b-tvrv7t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L116)):*
> ```Kotlin
>             val connectTime = DateTime.now()
> 
>             TrafficGenerator(targetIpAddress, targetPort).generateTraffic(10.milliseconds) {
> ```

Normally we start sending traffic inside the capture, why are we doing it differently in this case?
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/LeakCheck.kt` line 12 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87FRp84VCC7Yxs-gjJ:-O87FRp84VCC7Yxs-gjK:b-vq1jf2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/LeakCheck.kt#L12)):*
> ```Kotlin
>         rules: List<LeakRule>,
>         start: DateTime,
>         end: DateTime,
> ```

Is `start` and `end` really needed? Normally they should be confined to our capture right? Is there a usecase I'm missing?
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt` line 7 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O6RHkpt66tTeftwGZiK:-O87G-Vu7PjVHckNGt5s:bahzx95) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b489e3e57ecf126975f67d6c3ef13f3191a8a2a/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/Networking.kt#L7)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Discussed offline :heavy_check_mark: 
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 43 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87GE83B4aBObY2zu07:-O87GE83B4aBObY2zu08:bmi8ppe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L43)):*
> ```Kotlin
> value class PacketCaptureSession(val value: UUID = UUID.randomUUID())
> 
> object PacketCaptureSessionAsStringSerializer : KSerializer<PacketCaptureSession> {
> ```

:100: 
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 122 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87GXvj-8u_iRFg8CIJ:-O87GXvj-8u_iRFg8CIK:b5dna49) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L122)):*
> ```Kotlin
> 
>         val response =
>             httpClient.post("$BASE_URL/capture") {
> ```

There should be possible to insert a defaultUrl I believe. https://ktor.io/docs/client-default-request.html#configure
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 169 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87Gmky1gNjRXN6vKlm:-O87Gmky1gNjRXN6vKln:b7wnir6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L169)):*
> ```Kotlin
>         fun fromString(connectionInfo: String): Host {
>             val ipAddress = connectionInfo.split(":").first()
>             val port = connectionInfo.split(":").last().toInt()
> ```

Unnecessary double split.
```
connectionInfo.split(":").let {
            val ipAddress = it.first()
            val port = it.last().toInt()
            Host(ipAddress, port)
}
```
or start with
```
val connectionInfoParts = connectionInfo.split(":")
```


<!-- Sent from Reviewable.io -->

2024-10-01 14:27 UTC, Rawa requested changes
> Reviewed 1 of 6 files at r12.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 18 of 20 files reviewed, 10 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/LeakCheck.kt` line 33 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87TMVx06z0--0oE16f:-O87TMVx06z0--0oE16g:b-23ditm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/LeakCheck.kt#L33)):*
> ```Kotlin
>     override fun isViolated(streams: List<Stream>, start: DateTime, end: DateTime): Boolean {
>         return streams
>             .filter { it.startDate.isAfter(start) && it.endDate.isBefore(end) }
> ```

Seems a bit dangerous, if one of the packages are outside start/end we dismiss the entire stream. Isn't there a risk that it still may contain a leak?


<!-- Sent from Reviewable.io -->

2024-10-01 14:45 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 18 of 20 files reviewed, 11 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 243 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87XXdP1Bs9UHgIVziA:-O87XXdP1Bs9UHgIVziB:b-mi7sc0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L243)):*
> ```Kotlin
> @SerialName("TxPacket")
> data class TxPacket(
>     @SerialName("timestamp") override val timestamp: String,
> ```

Check that this really is a `String`, also maybe timestamp is a bit to broad if it is `nanos`

Also create customSerializer directly.


<!-- Sent from Reviewable.io -->

2024-10-04 09:31 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 16 of 21 files reviewed, 12 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt` line 11 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O86LgWI60IyPlXUzxKP:-O8GdlDMBj9Vqz1R8Q_f:ba3dfob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt#L11)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Remove `public`
</blockquote></details>

Removed
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt` line 14 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O873AWJCfWwOhm7DSvC:-O8Gdq0qDnKku7zOnuE5:b-e4w9id) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt#L14)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

A bit more clear:
"${Environment.DIRECTORY_DOWNLOADS}/$DIRECTORY_NAME",
</blockquote></details>

Agree. Changed
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt` line 18 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O873EVrAgfcHJouh7SO:-O8GdtBj30Dabrs7_U0H:b-36tktj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt#L18)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Personally I don't like the `.not()` I think `!testAttachmentsDirectory.exists()` is more clear.
</blockquote></details>

My personal preference is something more verbose like `== false` or `.not()` over `!` because it's an easy mistake to miss the `!`. But the groups preference is more important and there are very few `.not()` in the codebase. Changed to using `!`.
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt` line 20 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O877Q1t5yR7x9Bwbcqg:-O8Ge_BN5X5IHYp72o9o:bwove05) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt#L20)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Shouldn't it be if either of these fail you should fail the test? not only if both fails? Also should combine to one if statement.
</blockquote></details>

The first `if` condition is just for checking if the directory don't exist, the second one for whether the directory failed to be created. If the first one fails and the second one succeeds all is good. The directory did not exist but was successfully created. Combined them into one condition.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 46 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87ElcmDn0fykKJhePO:-O8GnDqW8Qhtl8wzyOQ6:bgdst6v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L46)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Do not each test start on a clean slate? or why do we have to check is the toggle isChecked?

nit: Avoid `not()`.
</blockquote></details>

I also don't know why this check would be needed, it shouldn't be. Removed check
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt` line 116 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87FBn_6Awecp_Xnitf:-O8GnxqEEhxGgbraqWif:bdygpv7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt#L116)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Normally we start sending traffic inside the capture, why are we doing it differently in this case?
</blockquote></details>

I forgot to update it here as well when I updated the other test function. It has been updated to start generating inside the capture now.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/LeakCheck.kt` line 12 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87FRp84VCC7Yxs-gjJ:-O8HwYJW8KNZpw1aDrZE:bo19u50) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/LeakCheck.kt#L12)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Is `start` and `end` really needed? Normally they should be confined to our capture right? Is there a usecase I'm missing?
</blockquote></details>

We talked about this offline. The `List<Stream>` is instead cut up before hand.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/LeakCheck.kt` line 33 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87TMVx06z0--0oE16f:-O8Hluf70z08KotIS8QF:b-4dtq4s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/LeakCheck.kt#L33)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Seems a bit dangerous, if one of the packages are outside start/end we dismiss the entire stream. Isn't there a risk that it still may contain a leak?
</blockquote></details>

We talked a bit about this offline. The list of streams is now cut in the test case using a new utility function `splitStreamList`. Also added an assert for non-empty stream list in `assertNoLeaks` to avoid the case of asserting that an empty list of streams do not contain leaks. Because it never will.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 122 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87GXvj-8u_iRFg8CIJ:-O8Hwf6-8U6AJ44cC9Ig:b-uc6xl5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L122)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

There should be possible to insert a defaultUrl I believe. https://ktor.io/docs/client-default-request.html#configure
</blockquote></details>

Thanks. Setting a default URL instead now 👍
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 169 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87Gmky1gNjRXN6vKlm:-O8HrYY21ma_FegV_zqK:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L169)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Unnecessary double split.
```
connectionInfo.split(":").let {
            val ipAddress = it.first()
            val port = it.last().toInt()
            Host(ipAddress, port)
}
```
or start with
```
val connectionInfoParts = connectionInfo.split(":")
```
</blockquote></details>

Fixed
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 243 at r13](https://reviewable.io/reviews/mullvad/mullva [...]

2024-10-04 10:04 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 18 of 21 files reviewed, 10 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 243 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87XXdP1Bs9UHgIVziA:-O8LzAxR255Ap9GQqZ35:bhswrco) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L243)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Not sure about the best way to do this serialization. `PacketSerializer` above serializes `List<Packet>` and `Packet` is serialized as either `TxPacket` or `RxPacket`. Adding serializers for both `TxPacket` and `RxPacket` would be so verbose, in a way the current implementation might be prettier then. How do you think?
</blockquote></details>

See comment about serializer


<!-- Sent from Reviewable.io -->

2024-10-08 15:57 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 12 of 26 files reviewed, 14 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @Rawa)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 243 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O87XXdP1Bs9UHgIVziA:-O8gq8wcA0jeYRsHJHsj:boyvbli) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8931d5b0ef0a606c0661619a01e928adff63b67e/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L243)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

See comment about serializer
</blockquote></details>

Created serializer for `Long` to `DateTime`


<!-- Sent from Reviewable.io -->

2024-10-08 16:03 UTC, albin-mullvad reviewed
> Reviewed 8 of 12 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 19 of 26 files reviewed, 10 unresolved discussions (waiting on @Pururun and @Rawa)



<!-- Sent from Reviewable.io -->

2024-10-09 07:01 UTC, Pururun submitted a review, later dismissed
> Reviewed 1 of 4 files at r6, 2 of 4 files at r9, 1 of 5 files at r14, 1 of 3 files at r15, 4 of 12 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: all files reviewed, 10 unresolved discussions (waiting on @Rawa)



<!-- Sent from Reviewable.io -->

2024-10-09 16:22 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 17 of 33 files reviewed, 11 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @Rawa)

___
*[`android/test/e2e/e2e.properties` line 3 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8m4BaB1qhk4KlHxQ9a:-O8m4BaB1qhk4KlHxQ9b:b-8qpydi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/158f77006b13405146ea67e821d73ae5dac75fe3/android/test/e2e/e2e.properties#L3)):*
> ```INI
> API_VERSION=v1
> ENABLE_HIGHLY_RATE_LIMITED_TESTS=false
> ENABLE_ACCESS_TO_LOCAL_API_TESTS=true
> ```

Is `true` a good default value? For Mullvad Android developers I think it makes sense because usually tests are ran from the office. But for third party developers it won't be a good default value.


<!-- Sent from Reviewable.io -->

2024-10-09 16:28 UTC, albin-mullvad reviewed
> Reviewed 4 of 16 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 21 of 33 files reviewed, 11 unresolved discussions (waiting on @niklasberglund, @Pururun, and @Rawa)

___
*[`android/test/e2e/e2e.properties` line 3 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8m4BaB1qhk4KlHxQ9a:-O8m5QZq6csJWGTHfPwp:b-w2uru1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/158f77006b13405146ea67e821d73ae5dac75fe3/android/test/e2e/e2e.properties#L3)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Is `true` a good default value? For Mullvad Android developers I think it makes sense because usually tests are ran from the office. But for third party developers it won't be a good default value.
</blockquote></details>

I believe `false` is a better default tbh, but I'm fine with either in this PR


<!-- Sent from Reviewable.io -->

2024-10-09 16:47 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 20 of 34 files reviewed, 11 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @Rawa)

___
*[`android/test/e2e/e2e.properties` line 3 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8m4BaB1qhk4KlHxQ9a:-O8mAGwz0AFoK2eFi1Wx:bh6lxz5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/158f77006b13405146ea67e821d73ae5dac75fe3/android/test/e2e/e2e.properties#L3)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe `false` is a better default tbh, but I'm fine with either in this PR
</blockquote></details>

Agree, it's better to have defaults that will run everywhere. Anyways the most important thing is that we make sure they run in CI when they're supposed to. Set to `false` and documented it in `README.md` for e2e tests.


<!-- Sent from Reviewable.io -->

2024-10-09 16:57 UTC, albin-mullvad reviewed
> Reviewed 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 22 of 34 files reviewed, 11 unresolved discussions (waiting on @niklasberglund, @Pururun, and @Rawa)

___
*[`android/test/e2e/README.md` line 31 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8mCEXs5YSj-JGT2Fw-:-O8mCEXs5YSj-JGT2Fw0:b1qgw8v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8acef76bab43180d5c2818943ded4f763dcf6175/android/test/e2e/README.md#L31)):*
nit: I suggest changing to:

> set `ENABLE_ACCESS_TO_LOCAL_API_TESTS=true`



_Code quote:_
```Markdown
set `ENABLE_ACCESS_TO_LOCAL_API_TESTS` to true 
```


<!-- Sent from Reviewable.io -->

2024-10-10 07:23 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 21 of 34 files reviewed, 10 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @Rawa)

___
*[`android/test/e2e/README.md` line 31 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8mCEXs5YSj-JGT2Fw-:-O8pImiX-sevNbrBX-wv:b-bu91xm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8acef76bab43180d5c2818943ded4f763dcf6175/android/test/e2e/README.md#L31)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: I suggest changing to:

> set `ENABLE_ACCESS_TO_LOCAL_API_TESTS=true`
</blockquote></details>

Updated


<!-- Sent from Reviewable.io -->

2024-10-10 14:42 UTC, Rawa requested changes
> Reviewed 6 of 16 files at r18, 2 of 3 files at r21.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 29 of 34 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad, @niklasberglund, and @Pururun)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/model/Packet.kt` line 18 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qqxRY-MLtPZDMHYWP:-O8qqxRY-MLtPZDMHYWQ:buaavds) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb4b22cbe288eab528d72b330502b4eda1d1183/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/model/Packet.kt#L18)):*
> ```Kotlin
> data class RxPacket(
>     @SerialName("timestamp") @Contextual override val date: DateTime,
>     @SerialName("from_peer") override val fromPeer: Boolean,
> ```

Should be hard-coded true/false for RxPacket/TxPacket.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/serializer/PacketSerializer.kt` line 14 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qrzA988GatB9zXgiN:-O8qrzA988GatB9zXgiO:bdeavht) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb4b22cbe288eab528d72b330502b4eda1d1183/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/serializer/PacketSerializer.kt#L14)):*
> ```Kotlin
> 
> object PacketSerializer : JsonContentPolymorphicSerializer<Packet>(Packet::class) {
>     override fun selectDeserializer(element: JsonElement): KSerializer<out Packet> {
> ```

:fire: 
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/util/SplitStreamList.kt` line 6 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qs26T4K-1T1gdqJqn:-O8qs26T4K-1T1gdqJqo:b-3833ka) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb4b22cbe288eab528d72b330502b4eda1d1183/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/util/SplitStreamList.kt#L6)):*
> ```Kotlin
> import org.joda.time.Interval
> 
> fun splitStreamList(streamList: List<Stream>, interval: Interval): List<Stream> {
> ```

Should be extension function.

```
fun List<Stream>.split() = filter { interval.contains(it.interval) }
```


<!-- Sent from Reviewable.io -->

2024-10-10 14:44 UTC, Rawa reviewed
> Reviewed 2 of 16 files at r18, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 32 of 34 files reviewed, 3 unresolved discussions (waiting on @niklasberglund and @Pururun)



<!-- Sent from Reviewable.io -->

2024-10-10 14:46 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 32 of 34 files reviewed, 3 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/util/SplitStreamList.kt` line 6 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qs26T4K-1T1gdqJqn:-O8qszh3BJ_5sfujfCX9:b-wvgrp5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb4b22cbe288eab528d72b330502b4eda1d1183/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/util/SplitStreamList.kt#L6)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should be extension function.

```
fun List<Stream>.split() = filter { interval.contains(it.interval) }
```
</blockquote></details>

Also, do you actually split the stream? Looks like we only remove stream outside.


<!-- Sent from Reviewable.io -->

2024-10-10 14:47 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 32 of 34 files reviewed, 4 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/LeakCheck.kt` line 9 at r21](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qtNuVAchDOBnRjujr:-O8qtNuVAchDOBnRjujs:b-2omoc4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729d8baef23bfbcad9e54f90a7a569ebb2d1f932/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/LeakCheck.kt#L9)):*
> ```Kotlin
> object LeakCheck {
>     fun assertNoLeaks(streams: List<Stream>, rules: List<LeakRule>) {
>         // Assert that there are streams to be analyzed
> ```

Maybe add a clarification that a Stream that has no packets can't be created.


<!-- Sent from Reviewable.io -->

2024-10-10 14:50 UTC, Rawa requested changes
> Reviewed 1 of 16 files at r18.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 33 of 34 files reviewed, 7 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 49 at r21](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qtYSKDo7OOgSy977V:-O8qtYSKDo7OOgSy977W:b-d34xqo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729d8baef23bfbcad9e54f90a7a569ebb2d1f932/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L49)):*
> ```Kotlin
>     private suspend fun getParsedCapture(): List<Stream> {
>         val parsedPacketsResponse = client.sendGetCapturedPacketsRequest(session)
>         val capturedStreams = parsedPacketsResponse.body<List<Stream>>()
> ```

To avoid unnecessary assignment:
```
return parsedPacketsResponse.body<List<Stream>>().also {
    Logger.v("Captured streams: $it")
}
```
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 64 at r21](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qtmip9ufWyF1RdkaS:-O8qtmip9ufWyF1RdkaT:bkaz908) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729d8baef23bfbcad9e54f90a7a569ebb2d1f932/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L64)):*
> ```Kotlin
>         val parsedCapture = getParsedCapture()
>         val pcap = getPcap()
>         return PacketCaptureResult(parsedCapture, pcap)
> ```

Join last 3 rows into one statement.
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 106 at r21](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qtxnV4xsW4kstQjH-:-O8qtxnV4xsW4kstQjH0:ba4lln8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729d8baef23bfbcad9e54f90a7a569ebb2d1f932/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L106)):*
> ```Kotlin
>         Logger.v("Sending start capture request with body: ${Json.encodeToString(jsonObject)}")
> 
>         val response =
> ```

Response never used?


<!-- Sent from Reviewable.io -->

2024-10-10 14:51 UTC, Rawa reviewed
> Reviewed 1 of 3 files at r21.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: all files reviewed, 7 unresolved discussions (waiting on @niklasberglund)



<!-- Sent from Reviewable.io -->

2024-10-10 15:04 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 29 of 34 files reviewed, 7 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/LeakCheck.kt` line 9 at r21](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qtNuVAchDOBnRjujr:-O8qujUv1PjhkjQ5tnMh:b-6nn6e9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729d8baef23bfbcad9e54f90a7a569ebb2d1f932/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/LeakCheck.kt#L9)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Maybe add a clarification that a Stream that has no packets can't be created.
</blockquote></details>

Added clarification
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 43 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8LyHZA5Au87mCYXb0Z:-O8qunhU0Y9-xO3Rb_Im:ba48tx6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ad332964f622658f3e85d834e2db6e32d56e5b99/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L43)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Ping, still here
</blockquote></details>

Removed for real
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 49 at r21](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qtYSKDo7OOgSy977V:-O8qv3NXCNM29ivnlYJJ:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729d8baef23bfbcad9e54f90a7a569ebb2d1f932/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L49)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

To avoid unnecessary assignment:
```
return parsedPacketsResponse.body<List<Stream>>().also {
    Logger.v("Captured streams: $it")
}
```
</blockquote></details>

Done
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 64 at r21](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qtmip9ufWyF1RdkaS:-O8qv8u29wngxBy1t4-G:bv23m3y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729d8baef23bfbcad9e54f90a7a569ebb2d1f932/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L64)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Join last 3 rows into one statement.
</blockquote></details>

Joined
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt` line 106 at r21](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qtxnV4xsW4kstQjH-:-O8qvW0HCANG6iksTxUQ:bhofyfb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/729d8baef23bfbcad9e54f90a7a569ebb2d1f932/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/PacketCapture.kt#L106)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Response never used?
</blockquote></details>

Not assigning to variable any more
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/model/Packet.kt` line 18 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qqxRY-MLtPZDMHYWP:-O8qvZ_qBsr3qmkerIO6:b-4hnt3v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb4b22cbe288eab528d72b330502b4eda1d1183/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/model/Packet.kt#L18)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should be hard-coded true/false for RxPacket/TxPacket.
</blockquote></details>

Hard coded true/false 
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/util/SplitStreamList.kt` line 6 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qs26T4K-1T1gdqJqn:-O8qvd-VCuECgh77Tnwo:b-4kwld5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb4b22cbe288eab528d72b330502b4eda1d1183/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/util/SplitStreamList.kt#L6)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Also, do you actually split the stream? Looks like we only remove stream outside.
</blockquote></details>

Removed this function and file because its no longer used


<!-- Sent from Reviewable.io -->

2024-10-10 15:59 UTC, Rawa commented
Fresh of the boat: https://github.com/ktorio/ktor/releases/tag/3.0.0

2024-10-11 14:24 UTC, Rawa requested changes
> Reviewed 3 of 5 files at r22, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: 33 of 34 files reviewed, 2 unresolved discussions (waiting on @niklasberglund)

___
*[`android/test/e2e/e2e.properties` line 4 at r23](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8vxiJK4QcY83jVMnYO:-O8vxiJK4QcY83jVMnYP:b25stq8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29382e89f291b6087579994967364e7689a7014b/android/test/e2e/e2e.properties#L4)):*
> ```INI
> ENABLE_HIGHLY_RATE_LIMITED_TESTS=false
> ENABLE_ACCESS_TO_LOCAL_API_TESTS=false
> TRAFFIC_GENERATION_IP_ADDRESS=45.83.223.209
> ```

Should these values really be checked in?
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/model/Packet.kt` line 18 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qqxRY-MLtPZDMHYWP:-O8vxGYO9heOS87WOkmo:bq91ecv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb4b22cbe288eab528d72b330502b4eda1d1183/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/model/Packet.kt#L18)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Hard coded true/false
</blockquote></details>

You set the default constructor value to be true/false, this allows for it to be changed. It should be like this:
```
data class RxPacket(
    @SerialName("timestamp") @Contextual override val date: DateTime,
) : Packet
    @SerialName("from_peer") override val fromPeer = false,
```
Like this a creator of RxPacket cannot change the `fromPeer` value.


<!-- Sent from Reviewable.io -->

2024-10-11 14:24 UTC, Rawa reviewed
> Reviewed 1 of 5 files at r22.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund)



<!-- Sent from Reviewable.io -->

2024-10-11 14:25 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/model/Packet.kt` line 18 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qqxRY-MLtPZDMHYWP:-O8vxx3597H9sXiSlSWR:brx4zwm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb4b22cbe288eab528d72b330502b4eda1d1183/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/model/Packet.kt#L18)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

You set the default constructor value to be true/false, this allows for it to be changed. It should be like this:
```
data class RxPacket(
    @SerialName("timestamp") @Contextual override val date: DateTime,
) : Packet
    @SerialName("from_peer") override val fromPeer = false,
```
Like this a creator of RxPacket cannot change the `fromPeer` value.
</blockquote></details>

Edit, missed the brackets: 
```
data class RxPacket(
    @SerialName("timestamp") @Contextual override val date: DateTime,
) : Packet {
    @SerialName("from_peer") override val fromPeer = false
}
```


<!-- Sent from Reviewable.io -->

2024-10-14 09:51 UTC, niklasberglund reviewed
Updated to ktor 3.0.0

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-:-O99Qwsj8ph3jk9lhb9K:b-3ffn7m)* status: 30 of 34 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @Rawa)



<!-- Sent from Reviewable.io -->

2024-10-14 10:59 UTC, Rawa reviewed
> Reviewed 4 of 4 files at r24, 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)



<!-- Sent from Reviewable.io -->

2024-10-14 11:47 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/test/e2e/e2e.properties` line 4 at r23](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8vxiJK4QcY83jVMnYO:-O99fz_K5rE_7lzbLztg:b-1g3vb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29382e89f291b6087579994967364e7689a7014b/android/test/e2e/e2e.properties#L4)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should these values really be checked in?
</blockquote></details>

It's a good question. I think the answer is yes, but there is no optimal solution for overriding these locally on a developers computer today. It should be as easy as specifying your preferred value i `local.properties` but today doing so won't override these values. So today the way to change is either by running tests from CLI and specify these properties as arguments, or by locally editing `e2e.properties`. Created an issue for improving this https://linear.app/mullvad/issue/DROID-1430/localproperties-values-should-override-e2eproperties-values
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/model/Packet.kt` line 18 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8qqxRY-MLtPZDMHYWP:-O99RT8G4D6-7WrMlIZT:b5mkugm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ebb4b22cbe288eab528d72b330502b4eda1d1183/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/model/Packet.kt#L18)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Edit, missed the brackets: 
```
data class RxPacket(
    @SerialName("timestamp") @Contextual override val date: DateTime,
) : Packet {
    @SerialName("from_peer") override val fromPeer = false
}
```
</blockquote></details>

Ahhh yes. Updated


<!-- Sent from Reviewable.io -->

2024-10-15 12:18 UTC, Rawa approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/test/e2e/e2e.properties` line 4 at r23](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-O8vxiJK4QcY83jVMnYO:-O9F6Pp38gOskR1uO3kt:bdvlh6m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/29382e89f291b6087579994967364e7689a7014b/android/test/e2e/e2e.properties#L4)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

It's a good question. I think the answer is yes, but there is no optimal solution for overriding these locally on a developers computer today. It should be as easy as specifying your preferred value i `local.properties` but today doing so won't override these values. So today the way to change is either by running tests from CLI and specify these properties as arguments, or by locally editing `e2e.properties`. Created an issue for improving this https://linear.app/mullvad/issue/DROID-1430/localproperties-values-should-override-e2eproperties-values
</blockquote></details>

Discussed offline, we'll fix this in the other issue


<!-- Sent from Reviewable.io -->

2024-10-15 12:19 UTC, Rawa approved these changes
> Reviewed 1 of 13 files at r3, 1 of 16 files at r4, 1 of 3 files at r15, 7 of 12 files at r16, 3 of 16 files at r18.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-15 12:44 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6691#-:-O9FCIXlDR_Wwz9l_acE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-15 13:26 UTC, merged