Inject tunnel settings in RelaySelectorWrapper
mullvad/mullvadvpn-app pull request #6721
Opened 2024-09-02 14:15 UTC by buggmagnet

This PR changes `RelaySelectorWrapper` to not create tunnel settings instances by itself anymore.
Instead, we now pass tunnel settings when we need to select a relay to always rely upon settings that were read from cache.

This fixes a bug where saved user settings would otherwise not be respected when upgrading the app to a new version.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6721)

2024-09-03 13:18 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6721#-:-O5s1Nx994-TUatcEbRS:bnfp4nl)* status: 0 of 11 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-04 06:48 UTC, rablador requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6721)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorWrapperTests.swift` line 90 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6721#-O5vlk1p6ujzXDQJEa3K:-O5vlk1p6ujzXDQJEa3L:b-9zcmkw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4055668fd7da0bc6925c65bee441c528c6692fc/ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorWrapperTests.swift#L90)):*
> ```Swift
>     }
> 
>     func testCanSelectRelayWithMultihopOffAndDaitaOn() throws {
> ```

This test seem to indirectly test the same thing as before, but using `multihopWithoutDaitaConstraints` for a test that explicitly states `MultihopOffAndDaitaOn` is a little confusing.


<!-- Sent from Reviewable.io -->

2024-09-04 07:45 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6721)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-09-04 07:48 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6721)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorWrapperTests.swift` line 90 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6721#-O5vlk1p6ujzXDQJEa3K:-O5vtZcmE9ysD_PTeFkR:bqvcgdp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b4055668fd7da0bc6925c65bee441c528c6692fc/ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorWrapperTests.swift#L90)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This test seem to indirectly test the same thing as before, but using `multihopWithoutDaitaConstraints` for a test that explicitly states `MultihopOffAndDaitaOn` is a little confusing.
</blockquote></details>

You're right, the test was completely bogus, I fixed it, thanks for catching that !


<!-- Sent from Reviewable.io -->

2024-09-04 08:10 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6721)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-04 11:06 UTC, rablador approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6721)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-05 11:55 UTC, merged