Add autostart on TV and remove auto connect feature on android
mullvad/mullvadvpn-app pull request #6761
Opened 2024-09-09 06:58 UTC by Pururun

This PR does three things:

1. Add a connect on boot feature for devices that does not vpn settings (mostly TV)
2. Disables the auo-connect feauture for all devices.
3. Remove the auto-connect feature from the ui for all devices.

2024-09-25 09:27 UTC, kl requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-O7cV15D1nr0hJv2rH8T:-O7cV15D1nr0hJv2rH8U:b-rdbp9g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb03e3673ff6df8229cc2a075844ebcfa5375573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L17)):*
> ```Kotlin
>     private val bootCompletedComponentName: ComponentName,
> ) {
>     val autoStartAndConnectOnBoot = MutableStateFlow(isAutoStartAndConnectOnBoot())
> ```

The public type could be a StateFlow here instead of a MutableStateFlow


<!-- Sent from Reviewable.io -->

2024-09-25 09:28 UTC, albin-mullvad requested changes
Mostly looks ready, I just have a few minor comments and I also believe we need another quick round of copy discussion

> Reviewed 19 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-:-O7cV78_6UJ903nRZYGd:b-5ot91y)* status: 19 of 21 files reviewed, 8 unresolved discussions (waiting on @Pururun)

___
*[`android/CHANGELOG.md` line 30 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-O7cRf7P9EMdVNeZ3Bp2:-O7cRf7P9EMdVNeZ3Bp3:byaf3ph) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb03e3673ff6df8229cc2a075844ebcfa5375573/android/CHANGELOG.md#L30)):*
> ```Markdown
> - Add WireGuard over Shadowsocks.
> - Add feature indicators to the main view along with redesigning the connection details.
> - Add auto connect and start setting for devices without system vpn settings.
> ```

I suggest rephrasing a bit:

Add new "Auto-connect on boot" setting for devices without system VPN settings.



_Code quote:_
```Markdown
Add auto connect and start setting for devices without system vpn settings.
```
___
*[`android/CHANGELOG.md` line 33 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-O7cRL2gB6iXnefLdDtG:-O7cRL2gB6iXnefLdDtH:b8515uu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb03e3673ff6df8229cc2a075844ebcfa5375573/android/CHANGELOG.md#L33)):*
> ```Markdown
> 
> ### Removed
> - Legacy auto connect feature.
> ```

nit: auto-connect



_Code quote:_
```Markdown
auto connect
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-O7cUF1-BM_Po3zt5qLJ:-O7cUF1-BM_Po3zt5qLK:b-1t9p4f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb03e3673ff6df8229cc2a075844ebcfa5375573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt#L19)):*
> ```Kotlin
>     private fun startAndConnectTunnel(context: Context) {
>         val hasVpnPermission = VpnService.prepare(context) == null
>         if (hasVpnPermission) {
> ```

Maybe we should add a info log here? Could be useful if users report that it doesn't work
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-O7cU_Es7d9LaA6UdsiZ:-O7cU_Es7d9LaA6Udsi_:b-px00gc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb03e3673ff6df8229cc2a075844ebcfa5375573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L19)):*
> ```Kotlin
>     val autoStartAndConnectOnBoot = MutableStateFlow(isAutoStartAndConnectOnBoot())
> 
>     fun setAutoStartAndConnectOnBoot(connect: Boolean) {
> ```

nit: change to something like `enabled`?



_Code quote:_
```Kotlin
connect
```
___
*[`gui/locales/messages.pot` line 2291 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-O7cSiwl7nyLVskpe53I:-O7cSiwl7nyLVskpe53J:b-ko3ffe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb03e3673ff6df8229cc2a075844ebcfa5375573/gui/locales/messages.pot#L2291)):*
> ```pot
> msgstr ""
> 
> msgid "Automatically connect on device start up. Please make sure the app has VPN permission."
> ```

I believe this is usually written as "startup" or "start-up"



_Code quote:_
```pot
start up
```
___
*[`gui/locales/messages.pot` line 2291 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-O7cT1jq-1Sqkgc0UUUX:-O7cT1jq-1Sqkgc0UUUY:b-6u55kc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb03e3673ff6df8229cc2a075844ebcfa5375573/gui/locales/messages.pot#L2291)):*
I believe this is better phrased as:

> Only works if the system VPN permission has been granted. 



_Code quote:_
```pot
Please make sure the app has VPN permission.
```
___
*[`gui/locales/messages.pot` line 2303 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-O7cS7mI05ps1ZgSeplk:-O7cS7mI05ps1ZgSepll:bu7ci8z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb03e3673ff6df8229cc2a075844ebcfa5375573/gui/locales/messages.pot#L2303)):*
"boot" sounds very technical. Something like the following makes more sense IMO: 

> Connect on device start-up



_Code quote:_
```pot
boot
```


<!-- Sent from Reviewable.io -->

2024-09-25 09:29 UTC, kl reviewed
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761)* status: all files reviewed, 8 unresolved discussions (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2024-09-25 13:08 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761)* status: 20 of 21 files reviewed, 6 unresolved discussions (waiting on @albin-mullvad and @kl)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-O7cUF1-BM_Po3zt5qLJ:-O7dG_LzAKe4yRIvJ4Ja:b1couhj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb03e3673ff6df8229cc2a075844ebcfa5375573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt#L19)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Maybe we should add a info log here? Could be useful if users report that it doesn't work
</blockquote></details>

Added info log
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 17 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-O7cV15D1nr0hJv2rH8T:-O7dH8i88e7DhAF7Cwzl:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb03e3673ff6df8229cc2a075844ebcfa5375573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L17)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

The public type could be a StateFlow here instead of a MutableStateFlow
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-O7cU_Es7d9LaA6UdsiZ:-O7dH9Lz7alMS0PHmoBl:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb03e3673ff6df8229cc2a075844ebcfa5375573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt#L19)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: change to something like `enabled`?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-09-25 13:59 UTC, albin-mullvad reviewed
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-O7cUF1-BM_Po3zt5qLJ:-O7dTMn64LIAtWnatm4l:b-i855ft) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb03e3673ff6df8229cc2a075844ebcfa5375573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt#L19)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Added info log
</blockquote></details>

Is it clear enough that it's a automatic start on boot? :thinking: 


<!-- Sent from Reviewable.io -->

2024-09-26 07:39 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-:-O7hGPKGDBBAMRD5iuUx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)



<!-- Sent from Reviewable.io -->

2024-09-26 08:40 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761)* status: 19 of 21 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @kl)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-O7cUF1-BM_Po3zt5qLJ:-O7hUHT_9bgY8yUoYVRB:bhuu6lo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/eb03e3673ff6df8229cc2a075844ebcfa5375573/android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt#L19)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is it clear enough that it's a automatic start on boot? :thinking:
</blockquote></details>

Clarified


<!-- Sent from Reviewable.io -->

2024-09-26 08:47 UTC, kl approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761#-:-O7hVoCYD3wJfSO6yNlP:bnfp4nl)* status: 19 of 21 files reviewed, all discussions resolved (waiting on @albin-mullvad)



<!-- Sent from Reviewable.io -->

2024-09-26 08:56 UTC, albin-mullvad approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-26 09:41 UTC, merged