Store the raw JSON payload from the getRelays API call
mullvad/mullvadvpn-app pull request #6767
Opened 2024-09-09 12:14 UTC by rablador

Instead of storing the parsed relays to disk we should store the raw json response. This will help us avoid old structure being read when doing migration to new object properties in our relay related data.

2024-09-09 13:17 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadREST/Relay/StoredRelays.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767#-O6LvX01BPgYsjLcyiUk:-O6LvX01BPgYsjLcyiUl:biw3rof) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7017e92c716a228f48e32e152dbae1211ed96ffd/ios/MullvadREST/Relay/StoredRelays.swift#L25)):*
> ```Swift
>     public var relays: REST.ServerRelaysResponse {
>         get throws {
>             try REST.Coding.makeJSONDecoder().decode(REST.ServerRelaysResponse.self, from: rawData)
> ```

How often do we _get_ it? Could we make this lazy as to not decode the whole relay list all of the time?


<!-- Sent from Reviewable.io -->

2024-09-10 07:02 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift` line 122 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767#-O6Pj5nJ-h9mCi2DT_1R:-O6Pj5nJ-h9mCi2DT_1S:bufolv3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7017e92c716a228f48e32e152dbae1211ed96ffd/ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift#L122)):*
> ```Swift
>         )
> 
>         let now = Date()
> ```

As per the discussion earlier, I do not believe `updatedAt` should be changed to the current timestamp. Instead, we shouldn't change it at all or change it such that it forces a relay list update.

The reason we have the hotfix is because there will be cases where people cannot reliably reach our API - but we should do our best to fetch a new relay list if  we know that the data on disk is incomplete.


<!-- Sent from Reviewable.io -->

2024-09-10 07:05 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadREST/Relay/StoredRelays.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767#-O6LvX01BPgYsjLcyiUk:-O6PjgOM5IaeRLTZWOnS:b-sewl67) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7017e92c716a228f48e32e152dbae1211ed96ffd/ios/MullvadREST/Relay/StoredRelays.swift#L25)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

How often do we _get_ it? Could we make this lazy as to not decode the whole relay list all of the time?
</blockquote></details>

Also, could we not store the `REST.ServerRelaysResponse` as is here? The fact that this is a fallible getter gets on my nerves and inflates the diff size here.  


<!-- Sent from Reviewable.io -->

2024-09-10 07:07 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadREST/Relay/StoredRelays.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767#-O6LvX01BPgYsjLcyiUk:-O6PkLyP8IJkbmktLhl-:b-ruvnp8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7017e92c716a228f48e32e152dbae1211ed96ffd/ios/MullvadREST/Relay/StoredRelays.swift#L25)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Also, could we not store the `REST.ServerRelaysResponse` as is here? The fact that this is a fallible getter gets on my nerves and inflates the diff size here.
</blockquote></details>

The above could be achieved by deserializing the relay list from the raw data and never serializing it to disk in the first place.


<!-- Sent from Reviewable.io -->

2024-09-10 09:15 UTC, buggmagnet requested changes
> Reviewed 3 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767)* status: 3 of 13 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadREST/Relay/RelayCache.swift` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767#-O6QAXZZ1O9Iu1WY_Ddr:-O6QAXZZ1O9Iu1WY_Dds:bq58bhk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7017e92c716a228f48e32e152dbae1211ed96ffd/ios/MullvadREST/Relay/RelayCache.swift#L43)):*
> ```Swift
>     public func read() throws -> StoredRelays {
>         do {
>             return try fileCache.read()
> ```

The first time we launch the app with this patch, reading from the cache will fail because a `CachedRelays` type was stored, but we're trying to decode a `StoredRelays` type.

In this case, we want to be able to create a `StoredRelays` directly from a `CachedRelays`.
We probably want something along those lines

```swift
    public init(cachedRelays: CachedRelays) throws {
        self.etag = cachedRelays.etag
        self.rawData = try JSONEncoder().encode(cachedRelays.relays)
        self.updatedAt = cachedRelays.updatedAt
    }
```


<!-- Sent from Reviewable.io -->

2024-09-10 09:43 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767)* status: 3 of 13 files reviewed, 3 unresolved discussions (waiting on @pinkisemils)

___
*[`ios/MullvadREST/Relay/RelayCache.swift` line 43 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767#-O6QAXZZ1O9Iu1WY_Ddr:-O6QJ9fl8pgC_BDN-LX5:b-d6h3at) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7017e92c716a228f48e32e152dbae1211ed96ffd/ios/MullvadREST/Relay/RelayCache.swift#L43)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

The first time we launch the app with this patch, reading from the cache will fail because a `CachedRelays` type was stored, but we're trying to decode a `StoredRelays` type.

In this case, we want to be able to create a `StoredRelays` directly from a `CachedRelays`.
We probably want something along those lines

```swift
    public init(cachedRelays: CachedRelays) throws {
        self.etag = cachedRelays.etag
        self.rawData = try JSONEncoder().encode(cachedRelays.relays)
        self.updatedAt = cachedRelays.updatedAt
    }
```
</blockquote></details>

Yes, with fallback on the bundled relays. As also discussed with @pinkisemils, we should do something like the above.
___
*[`ios/MullvadREST/Relay/StoredRelays.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767#-O6LvX01BPgYsjLcyiUk:-O6QIBA28XqLFmyldCII:b-a722) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7017e92c716a228f48e32e152dbae1211ed96ffd/ios/MullvadREST/Relay/StoredRelays.swift#L25)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The above could be achieved by deserializing the relay list from the raw data and never serializing it to disk in the first place.
</blockquote></details>

I'm not sure I follow. So we shouldn't store the raw data after all...?
___
*[`ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift` line 122 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767#-O6Pj5nJ-h9mCi2DT_1R:-O6QIa3sAOVir4-7qKJB:b-o980dz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7017e92c716a228f48e32e152dbae1211ed96ffd/ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift#L122)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

As per the discussion earlier, I do not believe `updatedAt` should be changed to the current timestamp. Instead, we shouldn't change it at all or change it such that it forces a relay list update.

The reason we have the hotfix is because there will be cases where people cannot reliably reach our API - but we should do our best to fetch a new relay list if  we know that the data on disk is incomplete.
</blockquote></details>

If we force a new fetch here there would be no need for the hotfix either, since the idea behind the fix is to graft some new properties into old structure without the need for network calls. I think leaving it makes more sense.


<!-- Sent from Reviewable.io -->

2024-09-10 10:03 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767)* status: 3 of 13 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadREST/Relay/StoredRelays.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767#-O6LvX01BPgYsjLcyiUk:-O6QMrXCEX6S30JzQb2N:beh42ei) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7017e92c716a228f48e32e152dbae1211ed96ffd/ios/MullvadREST/Relay/StoredRelays.swift#L25)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I'm not sure I follow. So we shouldn't store the raw data after all...?
</blockquote></details>

We should store `rawData`, but fail the deserialization if we cannot deserialize `rawData` into `ServerRelyResponse` during deserializaiton. We can chat about this in person.
___
*[`ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift` line 122 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767#-O6Pj5nJ-h9mCi2DT_1R:-O6QNfPq0Hl4XdMJcFai:bxpfybi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7017e92c716a228f48e32e152dbae1211ed96ffd/ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift#L122)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

If we force a new fetch here there would be no need for the hotfix either, since the idea behind the fix is to graft some new properties into old structure without the need for network calls. I think leaving it makes more sense.
</blockquote></details>

We can force the fetch, but we can never rely on the fetch working. Even if we don't force a new fetch, we shouldn't update the timestamp every time the grafting takes place.


<!-- Sent from Reviewable.io -->

2024-09-10 14:26 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767)* status: 9 of 13 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

___
*[`ios/MullvadREST/Relay/StoredRelays.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767#-O6LvX01BPgYsjLcyiUk:-O6RK1nf5Lgocjr8k93J:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7017e92c716a228f48e32e152dbae1211ed96ffd/ios/MullvadREST/Relay/StoredRelays.swift#L25)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We discussed this offline, and came to the conclusion taht we can make the `init` failable, create this as a `let` property and do the JSON parsing once when we instantiate this to avoid decoding from raw JSON every time.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-10 19:58 UTC, pinkisemils approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767#-:-O6SW1PSA_A17XojQTQp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-09-10 20:11 UTC, pinkisemils approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-09-10 20:11 UTC, pinkisemils approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-09-10 20:39 UTC, merged