Add signature verification to gradle dependencies
mullvad/mullvadvpn-app pull request #6771
Opened 2024-09-09 13:58 UTC by Pururun

2024-09-23 05:51 UTC, Pururun commented
Setting this as reviewable.

See description for more information.

2024-09-25 09:36 UTC, Rawa requested changes
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`.github/workflows/android-audit.yml` line 96 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O7cXQjuBnevWGG-LJLA:-O7cXQjuBnevWGG-LJLB:bmk5whj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e0cc8f24ef1da28f7b048312b1d37b4f881091f/.github/workflows/android-audit.yml#L96)):*
> ```YAML
> 
>       - name: Re-generate lockfile keys
>         run: android/scripts/update-lockfile-keys.sh   
> ```

How well does these scripts play together? Should we have one script to update both at the same time?
___
*[`android/scripts/update-lockfile-keys.sh` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O7cVvdI08uYkuGHdWUS:-O7cVvdI08uYkuGHdWUT:bpbpci8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e0cc8f24ef1da28f7b048312b1d37b4f881091f/android/scripts/update-lockfile-keys.sh#L32)):*
> ```Shell
> function cleanup {
>     echo "Cleaning up temp dirs..."
>     rm -rf -- "$TEMP_GRADLE_PROJECT_CACHE_DIR" ../gradle/verification-metadata.dryrun.xml ../gradle/verification-keyring.dryrun.keys ../gradle/verification-keyring.dryrun.gpg
> ```

Since we use `mktemp` wouldn't it create a new unique temp folder? Do we need to remove it?

Always a bit scary to do `rm -rf` especially when passing in an argument.
___
*[`android/scripts/update-lockfile-keys.sh` line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O7cX2qs3B59k_it9qN_:-O7cX2qs3B59k_it9qNa:b-4ggor4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e0cc8f24ef1da28f7b048312b1d37b4f881091f/android/scripts/update-lockfile-keys.sh#L50)):*
> ```Shell
> # Move keys from dry run file to existing file (This part is taken from: https://gitlab.com/fdroid/fdroidclient/-/blob/master/gradle/update-verification-metadata.sh)
> # extract the middle of the new file, https://github.com/gradle/gradle/issues/18569
> grep -B 10000 "<trusted-keys>" ../gradle/verification-metadata.dryrun.xml > "$TEMP_GRADLE_PROJECT_CACHE_DIR/new.head"
> ```

Feels like this should be doable in a much cleaner way with a third party dependency, but it has some benefits of doing it in the same was as fdroid I suppose. How do you guys feel? It is something we should consider reworking?


<!-- Sent from Reviewable.io -->

2024-09-25 13:56 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`.github/workflows/android-audit.yml` line 96 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O7cXQjuBnevWGG-LJLA:-O7co_3u-agk-s_MrQy9:b-7rvhov) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e0cc8f24ef1da28f7b048312b1d37b4f881091f/.github/workflows/android-audit.yml#L96)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

How well does these scripts play together? Should we have one script to update both at the same time?
</blockquote></details>

I was thinking of running it in the same script, but I ran into caching issues, but I could test it again now that I am not longer generating the keys from scratch and it is not as unstable.
___
*[`android/scripts/update-lockfile-keys.sh` line 32 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O7cVvdI08uYkuGHdWUS:-O7dSjqk159fvGfhRMjC:b-ldoijw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e0cc8f24ef1da28f7b048312b1d37b4f881091f/android/scripts/update-lockfile-keys.sh#L32)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Since we use `mktemp` wouldn't it create a new unique temp folder? Do we need to remove it?

Always a bit scary to do `rm -rf` especially when passing in an argument.
</blockquote></details>

Not sure if I follow, the temp directory code is the same as the other script.
___
*[`android/scripts/update-lockfile-keys.sh` line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O7cX2qs3B59k_it9qN_:-O7cpVfC0vbc097Gpbsn:b-6uferw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e0cc8f24ef1da28f7b048312b1d37b4f881091f/android/scripts/update-lockfile-keys.sh#L50)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Feels like this should be doable in a much cleaner way with a third party dependency, but it has some benefits of doing it in the same was as fdroid I suppose. How do you guys feel? It is something we should consider reworking?
</blockquote></details>

For me it is fine to change it. I just copied because it is confirmed to work.


<!-- Sent from Reviewable.io -->

2024-09-26 11:52 UTC, albin-mullvad reviewed
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771)* status: all files reviewed, 5 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/gradle/verification-metadata.xml` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O7i8rRq5XrdnK0gSNYs:-O7i8rRq5XrdnK0gSNYt:b-wsnh18) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e0cc8f24ef1da28f7b048312b1d37b4f881091f/android/gradle/verification-metadata.xml#L29)):*
> ```XML
>          <trust file=".*[.]pom" regex="true"/>
>       </trusted-artifacts>
>       <ignored-keys>
> ```

Should this be kept even though `key-servers enabled="false"`?
___
*[`android/gradle/verification-metadata.xml` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O7i99-uEtJiLgqOtEHw:-O7i99-uEtJiLgqOtEHx:b3yg2ju) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e0cc8f24ef1da28f7b048312b1d37b4f881091f/android/gradle/verification-metadata.xml#L35)):*
> ```XML
>          <ignored-key id="8E3A02905A1AE67E7B0F9ACD3967D4EDA591B991" reason="Key couldn't be downloaded from any key server"/>
>       </ignored-keys>
>       <trusted-keys>
> ```

It looks like we cover a lot of dependencies. Any idea of how many are signed and verified against keys as-of this PR?
___
*[`android/scripts/update-lockfile-keys.sh` line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O7cX2qs3B59k_it9qN_:-O7i9rR5-0TMatITnd2i:b-lsufnn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e0cc8f24ef1da28f7b048312b1d37b4f881091f/android/scripts/update-lockfile-keys.sh#L50)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

For me it is fine to change it. I just copied because it is confirmed to work.
</blockquote></details>

@Rawa what third party dependency are you thinking of?

As you say though, there's a lot of value keeping this similar as the F-Droid version IMO. I suggest keeping as-is for now. 


<!-- Sent from Reviewable.io -->

2024-09-26 11:54 UTC, albin-mullvad reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771)* status: all files reviewed, 5 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`.github/workflows/android-audit.yml` line 96 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O7cXQjuBnevWGG-LJLA:-O7iANzL4dMR7B0Qg0ve:b-jp94d9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e0cc8f24ef1da28f7b048312b1d37b4f881091f/.github/workflows/android-audit.yml#L96)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I was thinking of running it in the same script, but I ran into caching issues, but I could test it again now that I am not longer generating the keys from scratch and it is not as unstable.
</blockquote></details>

If we'll always or almost always run both, it could be nice to combine the scripts :thinking: 


<!-- Sent from Reviewable.io -->

2024-10-02 06:17 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`.github/workflows/android-audit.yml` line 96 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O7cXQjuBnevWGG-LJLA:-O88j6flAnXNfkYbHIY6:bi2gum8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e0cc8f24ef1da28f7b048312b1d37b4f881091f/.github/workflows/android-audit.yml#L96)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

If we'll always or almost always run both, it could be nice to combine the scripts :thinking:
</blockquote></details>

I guess in theory you would not need to update the keys if you only update the version of a dependency.
But I think we should try to combine them.
___
*[`android/gradle/verification-metadata.xml` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O7i8rRq5XrdnK0gSNYs:-O8AriJv9oJtXOFh_RA-:b-dqbehe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e0cc8f24ef1da28f7b048312b1d37b4f881091f/android/gradle/verification-metadata.xml#L29)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should this be kept even though `key-servers enabled="false"`?
</blockquote></details>

That is true, removed them.
___
*[`android/gradle/verification-metadata.xml` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O7i99-uEtJiLgqOtEHw:-O88kydu7DrO1jw9KOFx:bkeg1dl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e0cc8f24ef1da28f7b048312b1d37b4f881091f/android/gradle/verification-metadata.xml#L35)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

It looks like we cover a lot of dependencies. Any idea of how many are signed and verified against keys as-of this PR?
</blockquote></details>

I checked and if we remove all dependencies that are signed from the file we remove 5000 lines. Since every dependency is 3-5 lines that would mean ~1000 dependencies and ~300 dependencies that are not.

It is quite massive change and it would perhaps been better to manually add keys in steps, but I could not find a good way to do this.


<!-- Sent from Reviewable.io -->

2024-10-02 09:37 UTC, albin-mullvad reviewed
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771)* status: all files reviewed, 3 unresolved discussions (waiting on @Pururun and @Rawa)



<!-- Sent from Reviewable.io -->

2024-10-03 12:37 UTC, Rawa reviewed
> Reviewed 1 of 4 files at r1, 3 of 4 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771)* status: 5 of 6 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-03 12:38 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/scripts/update-lockfile.sh` line 30 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8HNmg_292dcvSPLh09:-O8HNmg_292dcvSPLh0A:b-soplvc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bc35be6a7ae72f7b4d5778d592ebf73b5f1b1824/android/scripts/update-lockfile.sh#L30)):*
> ```Shell
> export GRADLE_USER_HOME
> 
> function cleanup {
> ```

Check what happens if a key has been rotated/replaced and this script is ran again. 


<!-- Sent from Reviewable.io -->

2024-10-03 13:33 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/scripts/update-lockfile.sh` line 30 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8HNmg_292dcvSPLh09:-O8H_LJW5fOXdDtnl3Zz:bt36334) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/bc35be6a7ae72f7b4d5778d592ebf73b5f1b1824/android/scripts/update-lockfile.sh#L30)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Check what happens if a key has been rotated/replaced and this script is ran again.
</blockquote></details>

Script seems to run fine and key is replaced with the correct one.


<!-- Sent from Reviewable.io -->

2024-10-03 13:35 UTC, Rawa approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-:-O8H_nl6EYlCGBr26aI_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-04 10:03 UTC, albin-mullvad reviewed
Looks good, I mostly have some nitpicking on some of the code comments and prints in order to keep things consistent.

> Reviewed 3 of 4 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-:-O8LyNtiA_jT1rOhOMAP:b-v87ss4)* status: all files reviewed, 13 unresolved discussions (waiting on @Pururun)

___
*[`android/scripts/update-lockfile.sh` line 37 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LvER23YrM98oIQ08g:-O8LvER23YrM98oIQ08h:b-rqrfmv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6fc454386103141bba33d28013bd97f2aba07fa/android/scripts/update-lockfile.sh#L37)):*
> ```Shell
> trap cleanup EXIT
> 
> echo "### Updating dependency lockfile ###"
> ```

nit: change to `Updating checksums`



_Code quote:_
```Shell
Updating dependency lockfile
```
___
*[`android/scripts/update-lockfile.sh` line 40 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LvUKkEKTYNfU2-J1O:-O8LvUKkEKTYNfU2-J1P:b-hycovv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6fc454386103141bba33d28013bd97f2aba07fa/android/scripts/update-lockfile.sh#L40)):*
> ```Shell
> echo "Gradle home: $GRADLE_USER_HOME"
> echo "Gradle cache: $TEMP_GRADLE_PROJECT_CACHE_DIR"
> echo ""
> ```

nit: move to after `trap cleanup EXIT` since these are shared for both the "checksum" and "key" sections. Maybe also prefix with a print saying something like:

```
echo "### Configuration ###"
```



_Code quote:_
```Shell
echo "Gradle home: $GRADLE_USER_HOME"
echo "Gradle cache: $TEMP_GRADLE_PROJECT_CACHE_DIR"
echo ""
```
___
*[`android/scripts/update-lockfile.sh` line 54 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8Luvqq20jU0-20wtVM:-O8Luvqq20jU0-20wtVN:b15cqo3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L54)):*
> ```Shell
> done
> 
> echo "### Updating dependency lockfile verification keys ###"
> ```

nit: change to `Updating keys`



_Code quote:_
```Shell
Updating dependency lockfile verification keys
```
___
*[`android/scripts/update-lockfile.sh` line 57 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LvnAs1sV5ufO_mIkW:-O8LvnAs1sV5ufO_mIkX:b-9n1eyh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L57)):*
> ```Shell
> echo ""
> 
> echo "Set key servers true temporarily"
> ```

nit `Temporarily enabling key servers...`



_Code quote:_
```Shell
Set key servers true temporarily
```
___
*[`android/scripts/update-lockfile.sh` line 60 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LvwgxAbE51JAdFk8l:-O8LvwgxAbE51JAdFk8m:b-pul9pd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L60)):*
> ```Shell
> sed -Ei 's,key-servers enabled="[^"]+",key-servers enabled="true",' ../gradle/verification-metadata.xml
> 
> # Generate keys
> ```

nit: remove this comment
___
*[`android/scripts/update-lockfile.sh` line 65 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8Ly1qt3zKFXyErBb-7:-O8Ly1qt3zKFXyErBb-8:boyeko6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L65)):*
> ```Shell
> ../gradlew -q -p .. --project-cache-dir "$TEMP_GRADLE_PROJECT_CACHE_DIR" -M pgp,sha256 "${GRADLE_TASKS[@]}" --export-keys --dry-run "${EXCLUDED_GRADLE_TASKS[@]}"
> 
> # Move keys from dry run file to existing file (This part is taken from: https://gitlab.com/fdroid/fdroidclient/-/blob/master/gradle/update-verification-metadata.sh)
> ```

nit: change to 

```
Move keys from dry run file to existing file.
This part is taken from: https://gitlab.com/fdroid/fdroidclient/-/blob/master/gradle/update-verification-metadata.sh
```



_Code quote:_
```Shell
Move keys from dry run file to existing file (This part is taken from: https://gitlab.com/fdroid/fdroidclient/-/blob/master/gradle/update-verification-metadata.sh)
```
___
*[`android/scripts/update-lockfile.sh` line 66 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LxOC_CThkuIzRrb38:-O8LxOCa4Aff8HStB9bu:b-1y5iqe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L66)):*
> ```Shell
> 
> # Move keys from dry run file to existing file (This part is taken from: https://gitlab.com/fdroid/fdroidclient/-/blob/master/gradle/update-verification-metadata.sh)
> # extract the middle of the new file, https://github.com/gradle/gradle/issues/18569
> ```

nit: `Extract the middle of the new file due to: https://github.com/gradle/gradle/issues/18569`



_Code quote:_
```Shell
extract
```
___
*[`android/scripts/update-lockfile.sh` line 74 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LxFLK9FTiTzpw-rpi:-O8LxFLK9FTiTzpw-rpj:b-7qsxqd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L74)):*
> ```Shell
> numLines="$(< ../gradle/verification-metadata.dryrun.xml wc -l)"
> numMiddleLines="$((numLines - numTopLines - numBottomLines))"
> # also remove 'version=' lines, https://github.com/gradle/gradle/issues/20192
> ```

nit: `Remove 'version=' due to: https://github.com/gradle/gradle/issues/20192`



_Code quote:_
```Shell
also remove 'version=' lines, https://github.com/gradle/gradle/issues/20192
```
___
*[`android/scripts/update-lockfile.sh` line 77 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LwWlFCqYQS5JA7gGc:-O8LwWlFCqYQS5JA7gGd:b-tmq3q3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L77)):*
> ```Shell
> < ../gradle/verification-metadata.dryrun.xml tail -n "+$numTopLinesPlus1" | head -n "$numMiddleLines" | sed 's/ version="[^"]*"//' > "$TEMP_GRADLE_PROJECT_CACHE_DIR/new.middle"
> 
> # extract the top and bottom of the old file
> ```

nit: `Extract`



_Code quote:_
```Shell
extract
```
___
*[`android/scripts/update-lockfile.sh` line 81 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LwUWdEHF4deZ0GeBN:-O8LwUWdEHF4deZ0GeBO:b-8g7lin) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L81)):*
> ```Shell
> grep -A 10000 "</trusted-keys>" ../gradle/verification-metadata.xml > "$TEMP_GRADLE_PROJECT_CACHE_DIR/old.tail"
> 
> # update verification metadata file
> ```

nit: `Update`



_Code quote:_
```Shell
update
```
___
*[`android/scripts/update-lockfile.sh` line 84 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LwldX15T4jIDgEdIE:-O8LwldX15T4jIDgEdIF:bf45er) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L84)):*
> ```Shell
> cat "$TEMP_GRADLE_PROJECT_CACHE_DIR/old.head" "$TEMP_GRADLE_PROJECT_CACHE_DIR/new.middle" "$TEMP_GRADLE_PROJECT_CACHE_DIR/old.tail" > ../gradle/verification-metadata.xml
> 
> echo "sorting keyring and removing duplicates"
> ```

nit: `Sorting keyring and removing duplicates...` 



_Code quote:_
```Shell
sorting
```
___
*[`android/scripts/update-lockfile.sh` line 85 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LwieJ2qWgyGxrmm8O:-O8LwieJ2qWgyGxrmm8P:b-83gn6s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L85)):*
> ```Shell
> 
> echo "sorting keyring and removing duplicates"
>   # sort and unique the keyring
> ```

nit: `Sort`



_Code quote:_
```Shell
sort
```
___
*[`android/scripts/update-lockfile.sh` line 103 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8Lw9fY70-frseSU [...]

2024-10-04 10:23 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/scripts/update-lockfile.sh` line 37 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LvER23YrM98oIQ08g:-O8M1sDF4PpCcbhfc66X:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6fc454386103141bba33d28013bd97f2aba07fa/android/scripts/update-lockfile.sh#L37)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: change to `Updating checksums`
</blockquote></details>

Done
___
*[`android/scripts/update-lockfile.sh` line 40 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LvUKkEKTYNfU2-J1O:-O8M1t4k56quRCgbY6uZ:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d6fc454386103141bba33d28013bd97f2aba07fa/android/scripts/update-lockfile.sh#L40)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: move to after `trap cleanup EXIT` since these are shared for both the "checksum" and "key" sections. Maybe also prefix with a print saying something like:

```
echo "### Configuration ###"
```
</blockquote></details>

Done
___
*[`android/scripts/update-lockfile.sh` line 54 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8Luvqq20jU0-20wtVM:-O8M1tqK9wsC0fRQ4rJA:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L54)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: change to `Updating keys`
</blockquote></details>

Done
___
*[`android/scripts/update-lockfile.sh` line 57 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LvnAs1sV5ufO_mIkW:-O8M1unD6_SYD_zVau-Q:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L57)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit `Temporarily enabling key servers...`
</blockquote></details>

Done
___
*[`android/scripts/update-lockfile.sh` line 60 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LvwgxAbE51JAdFk8l:-O8M1vgv-m5HVp5YfNuS:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L60)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: remove this comment
</blockquote></details>

Done
___
*[`android/scripts/update-lockfile.sh` line 65 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8Ly1qt3zKFXyErBb-7:-O8M22b7EcGYlKkTT12r:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L65)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: change to 

```
Move keys from dry run file to existing file.
This part is taken from: https://gitlab.com/fdroid/fdroidclient/-/blob/master/gradle/update-verification-metadata.sh
```
</blockquote></details>

Done
___
*[`android/scripts/update-lockfile.sh` line 66 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LxOC_CThkuIzRrb38:-O8M28lw4pPFUFX9KgpL:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L66)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: `Extract the middle of the new file due to: https://github.com/gradle/gradle/issues/18569`
</blockquote></details>

Done
___
*[`android/scripts/update-lockfile.sh` line 74 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LxFLK9FTiTzpw-rpi:-O8M2CWO0-0wsHGuysd3:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L74)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: `Remove 'version=' due to: https://github.com/gradle/gradle/issues/20192`
</blockquote></details>

Done
___
*[`android/scripts/update-lockfile.sh` line 77 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LwWlFCqYQS5JA7gGc:-O8M2GC82QQ3yQH06Rly:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L77)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: `Extract`
</blockquote></details>

Done
___
*[`android/scripts/update-lockfile.sh` line 81 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LwUWdEHF4deZ0GeBN:-O8M2IhP1xwoqgzuvNUj:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L81)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: `Update`
</blockquote></details>

Done
___
*[`android/scripts/update-lockfile.sh` line 84 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LwldX15T4jIDgEdIE:-O8M2Ltt8J_suMwSpe0c:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L84)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: `Sorting keyring and removing duplicates...`
</blockquote></details>

Done
___
*[`android/scripts/update-lockfile.sh` line 85 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LwieJ2qWgyGxrmm8O:-O8M2OBO7Ksa-67oj-tB:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L85)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: `Sort`
</blockquote></details>

Done
___
*[`android/scripts/update-lockfile.sh` line 103 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8Lw9fY70-frseSUAIE:-O8M2R9p2PHPnaCOv1ZG:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L103)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: `Disabling key servers...`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-10-04 10:32 UTC, albin-mullvad reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/scripts/update-lockfile.sh` line 84 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LwldX15T4jIDgEdIE:-O8M4KDh5v8SPqcKf_z2:bwwtjdc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L84)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done
</blockquote></details>

nit: please also add the `...` to the end to keep it consistent with the other prints


<!-- Sent from Reviewable.io -->

2024-10-04 12:27 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/scripts/update-lockfile.sh` line 84 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-O8LwldX15T4jIDgEdIE:-O8MUmrZ-W3iLk1aiJ-i:b-cl3fgz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1674fbc0d715d63f5e40af59fce98188518a93cc/android/scripts/update-lockfile.sh#L84)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: please also add the `...` to the end to keep it consistent with the other prints
</blockquote></details>

Missed `...` part. Fixed.


<!-- Sent from Reviewable.io -->

2024-10-04 13:03 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6771#-:-O8Mc8BfCrbZGjoS78UF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-04 13:25 UTC, merged