Add counter and 'all' switch to DNS content blockers
mullvad/mullvadvpn-app pull request #6800
Opened 2024-09-17 09:28 UTC by rablador

Currently there is no way to know that you have content blockers enabled unless you expand the tree.

This first iteration would have an "All" switch that activates all toggles - and the number of activated toggles would be shown at the top level. 

Toggling "All" would activate all the other toggles. But if the user then deactivates a toggle, "All" would have to be deactivated as well since all of them are not activated. Only by actively deactivating "All" does the user deactivate all the other toggles.

2024-09-17 14:09 UTC, rablador reviewed
The requirement stated that the custom DNS view should be rewritten in SwiftUI, but I opted to not do this. The PR is easily implemented in UIKit and mostly consists of data juggling.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6800#-:-O7-J55b6WLuAp_3GHV_:bevm3j0)* status: 0 of 6 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-18 09:34 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6800#-:-O73Tz1989rrgoJq6Jva:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-18 09:36 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6800)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewModel.swift` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6800#-O73S88s5YV1OvIDYJUG:-O73S88s5YV1OvIDYJUH:b-qimcsj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f55508039e6f78daee22cfb233429685b3b52328/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewModel.swift#L107)):*
> ```Swift
> 
>     static let defaultWireGuardPorts: [UInt16] = [51820, 53]
> ```

we can map the content blockers which we have in `DataSource` into the model through a dictionary: and having access to the values through `setter` and `getter`. in this way if we add another options into content blockers the only thing we need to add into model is a variable which is reading and writing the dictionary. what do you think?



_Code snippet:_
```Swift
struct VPNSettingsViewModel: Equatable {
    private(set) var blockAll : Bool {
        get {
            contentBlockers[.blockAll] ?? false
        } set {
            contentBlockers[.blockAll] = newValue
        }
    }

    private(set) var blockAdvertising: Bool {
        get {
            contentBlockers[.blockAdvertising] ?? false
        } set {
            contentBlockers[.blockAdvertising] = newValue
        }
    }

    private(set) var blockTracking: Bool {
        get {
            contentBlockers[.blockTracking] ?? false
        } set {
            contentBlockers[.blockTracking] = newValue
        }
    }

    private(set) var blockMalware: Bool {
        get {
            contentBlockers[.blockMalware] ?? false
        } set {
            contentBlockers[.blockMalware] = newValue
        }
    }

    private(set) var blockAdultContent: Bool {
        get {
            contentBlockers[.blockAdultContent] ?? false
        } set {
            contentBlockers[.blockAdultContent] = newValue
        }
    }

    private(set) var blockGambling: Bool {
        get {
            contentBlockers[.blockGambling] ?? false
        } set {
            contentBlockers[.blockGambling] = newValue
        }
    }

    private(set) var blockSocialMedia: Bool {
        get {
            contentBlockers[.blockSocialMedia] ?? false
        } set {
            contentBlockers[.blockSocialMedia] = newValue
        }
    }

    private(set) var enableCustomDNS: Bool
    private(set) var wireGuardPort: UInt16?
    var customDNSDomains: [DNSServerEntry]
    var availableWireGuardPortRanges: [[UInt16]] = []

    private(set) var obfuscationState: WireGuardObfuscationState
    private(set) var obfuscationPort: WireGuardObfuscationPort

    private(set) var quantumResistance: TunnelQuantumResistance
    private(set) var multihopState: MultihopState
    private(set) var daitaSettings: DAITASettings

    static let defaultWireGuardPorts: [UInt16] = [51820, 53]

    private var contentBlockers: [CustomDNSDataSource.Item: Bool]

    var enabledBlockersCount: Int {
        contentBlockers.count(where: { $0.key != .blockAll && $0.value })
    }

    var allBlockersEnabled: Bool {
        contentBlockers.allSatisfy({$0.key != .blockAll && $0.value})
    }

    mutating func setBlockAll(_ newValue: Bool) {
        blockAll = newValue
        self.contentBlockers = CustomDNSDataSource.Item.contentBlockers
            .reduce(into: [CustomDNSDataSource.Item: Bool]()) {
                $0[$1] = newValue
            }
        enableCustomDNS = false
    }

    mutating func setBlockAdvertising(_ newValue: Bool) {
        blockAdvertising = newValue
        blockAll = allBlockersEnabled
        enableCustomDNS = false
    }

    mutating func setBlockTracking(_ newValue: Bool) {
        blockTracking = newValue
        blockAll = allBlockersEnabled
        enableCustomDNS = false
    }

    mutating func setBlockMalware(_ newValue: Bool) {
        blockMalware = newValue
        blockAll = allBlockersEnabled
        enableCustomDNS = false
    }

    mutating func setBlockAdultContent(_ newValue: Bool) {
        blockAdultContent = newValue
        blockAll = allBlockersEnabled
        enableCustomDNS = false
    }

    mutating func setBlockGambling(_ newValue: Bool) {
        blockGambling = newValue
        blockAll = allBlockersEnabled
        enableCustomDNS = false
    }

    mutating func setBlockSocialMedia(_ newValue: Bool) {
        blockSocialMedia = newValue
        blockAll = allBlockersEnabled
        enableCustomDNS = false
    }

    mutating func setEnableCustomDNS(_ newValue: Bool) {
        enableCustomDNS = newValue
    }

    mutating func setWireGuardPort(_ newValue: UInt16?) {
        wireGuardPort = newValue
    }

    mutating func setWireGuardObfuscationState(_ newState: WireGuardObfuscationState) {
        obfuscationState = newState
    }

    mutating func setWireGuardObfuscationPort(_ newPort: WireGuardObfuscationPort) {
        obfuscationPort = newPort
    }

    mutating func setQuantumResistance(_ newState: TunnelQuantumResistance) {
        quantumResistance = newState
    }

    mutating func setMultihop(_ newState: MultihopState) {
        multihopState = newState
    }

    mutating func setDAITASettings(_ newSettings: DAITASettings) {
        daitaSettings = newSettings
    }

    /// Precondition for enabling Custom DNS.
    var customDNSPrecondition: CustomDNSPrecondition {
        if blockAdvertising || blockTracking || blockMalware ||
            blockAdultContent || blockGambling || blockSocialMedia {
            return .conflictsWithOtherSettings
        } else {
            let hasValidDNSDomains = customDNSDomains.contains { entry in
                AnyIPAddress(entry.address) != nil
            }

            if hasValidDNSDomains {
                return .satisfied
            } else {
                return .emptyDNSDomains
            }
        }
    }

    /// Effective state of the custom DNS setting.
    var effectiveEnableCustomDNS: Bool {
        customDNSPrecondition == .satisfied && enableCustomDNS
    }

    var customWireGuardPort: UInt16? {
        wireGuardPort.flatMap { port in
            Self.defaultWireGuardPorts.contains(port) ? nil : port
        }
    }

    init(from tunnelSettings: LatestTunnelSettings = LatestTunnelSettings()) {
        let dnsSettings = tunnelSettings.dnsSettings
        self.contentBlockers = CustomDNSDataSource.Item.contentBlockers
            .reduce(into: [CustomDNSDataSource.Item: Bool]()) {
                $0[$1] = false
            }

        enableCustomDNS = dnsSettings.enableCustomDNS
        customDNSDomains = dnsSettings.customDNSDomains.map { ipAddress in
            DNSServerEntry(identifier: UUID(), address: "\(ipAddress)")
        }
        wireGuardPort = tunnelSettings.relayConstraints.port.value

        obfuscationState = tunnelSettings.wireGuardObfuscation.state
        obfuscationPort = tunnelSettings.wireGuardObfuscation.port

        quantumResistance = tunnelSettings.tunnelQuantumResistance
        multihopState = tunnelSettings.tunnelMultihopState
        daitaSettings = tunnelSettings.daita

        blockAdvertising = dnsSettings.blockingOptions.contains(.blockAdvertising)
        blockTracking = dnsSettings.blockingOptions.contains(.blockTracking)
        blockMalware = dnsSettings.blockingOptions.contains(.blockMalware)
        blockAdultContent = dnsSettings.blockingOptions.contains(.blockAdultContent)
        blockGambling = dnsSettings.blockingOptions.contains(.blockGambling)
        blockSocialMedia = dnsSettings.blockingOptions.contains(.blockSocialMedia)
        blockAll = contentBlockers.allSatisfy { $0.value }
    }

    /// Produce merged view model keeping entry `identifier` for matching DNS entries.
    func merged(_ other: VPNSettingsViewModel) -> VPNSettingsViewModel {
        var mergedViewModel = other
        mergedViewModel.customDNSDomains = merge(customDNSDomains, w [...]

2024-09-18 12:25 UTC, buggmagnet approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6800)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewModel.swift` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6800#-O73S88s5YV1OvIDYJUG:-O744j7t8hdMCLFCo0OU:bhcdqnr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f55508039e6f78daee22cfb233429685b3b52328/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewModel.swift#L107)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

we can map the content blockers which we have in `DataSource` into the model through a dictionary: and having access to the values through `setter` and `getter`. in this way if we add another options into content blockers the only thing we need to add into model is a variable which is reading and writing the dictionary. what do you think?
</blockquote></details>

We don't need a dictionary approach for this. The DNS proxy that would be used is a bit set in the first place (see `DNSBlockingOptions`)  so this would be overkill IMHO


<!-- Sent from Reviewable.io -->

2024-09-18 13:38 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6800)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewModel.swift` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6800#-O73S88s5YV1OvIDYJUG:-O74L5sQ81XXUCcnD3bE:bq03s30) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f55508039e6f78daee22cfb233429685b3b52328/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewModel.swift#L107)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We don't need a dictionary approach for this. The DNS proxy that would be used is a bit set in the first place (see `DNSBlockingOptions`)  so this would be overkill IMHO
</blockquote></details>

I think following the code for how and what conditions are meeting to take proper action is a bit hard.we are hiding the complexity behind the another object.


<!-- Sent from Reviewable.io -->

2024-09-20 11:25 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6800)* status: all files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewModel.swift` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6800#-O73S88s5YV1OvIDYJUG:-O7EAGUr-8KrruOv5ZL3:bqnuhh8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f55508039e6f78daee22cfb233429685b3b52328/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewModel.swift#L107)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I think following the code for how and what conditions are meeting to take proper action is a bit hard.we are hiding the complexity behind the another object.
</blockquote></details>

I like the idea of now having to make updates to multiple places in case of future changes, but as @buggmagnet points out it's not really necessary. Can we come to concensus on this?


<!-- Sent from Reviewable.io -->

2024-09-20 11:39 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6800)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewModel.swift` line 107 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6800#-O73S88s5YV1OvIDYJUG:-O7EDTN2Ei_L5jG_Q8pk:b-h212vh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f55508039e6f78daee22cfb233429685b3b52328/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewModel.swift#L107)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I like the idea of now having to make updates to multiple places in case of future changes, but as @buggmagnet points out it's not really necessary. Can we come to concensus on this?
</blockquote></details>

If you both agreed, it's over-engineering then let's go with the current one.


<!-- Sent from Reviewable.io -->

2024-09-20 13:08 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6800#-:-O7EY1Ia8fVga0U2fOE1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @rablador)



<!-- Sent from Reviewable.io -->

2024-09-20 13:14 UTC, merged