Lower MTU during ephemeral peer negotiation
mullvad/mullvadvpn-app pull request #6836
Opened 2024-09-23 08:24 UTC by dlon

`IP_USER_MTU` doesn't work like MSS, which can cause PQ negotiation to fail on Windows when the MTU is incorrectly configured (see https://github.com/mullvad/mullvadvpn-app/actions/runs/10975572685/job/30475498014).

This PR fixes this by lowering the tunnel interface MTU during ephemeral peer negotiation.

Fix DES-1257.

2024-09-23 15:09 UTC, hulthe requested changes
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6836)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`talpid-tunnel-config-client/src/socket.rs` line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6836#-O7UEhou1X_YWHpKuj11:-O7UEhou1X_YWHpKuj12:b-r48qyx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfd2319e12460817512cf6e6bfb341ca3cf080d0/talpid-tunnel-config-client/src/socket.rs#L21)):*
> ```XML
>     /// will likely occur after the PQ handshake, so we cannot assume that the MTU is already
>     /// correctly configured.
>     const CONFIG_CLIENT_MTU: u16 = 576;
> ```

why this specific value?
___
*[`talpid-tunnel-config-client/src/socket.rs` line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6836#-O7UFhmNCIu9yAQ7y9v1:-O7UFhmNCIu9yAQ7y9v2:b-5y4c9m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfd2319e12460817512cf6e6bfb341ca3cf080d0/talpid-tunnel-config-client/src/socket.rs#L50)):*
> ```XML
>                 &mss as *const _ as _,
>                 socklen_t::try_from(std::mem::size_of_val(&mss)).unwrap(),
>             )
> ```

Unsafe... Maybe we should have a manpage reference here or something that tells us we're using the sockopt correctly.

Or maybe we can use [set_mss](https://docs.rs/socket2/latest/socket2/struct.Socket.html#method.set_mss) from socket2?


<!-- Sent from Reviewable.io -->

2024-09-23 15:36 UTC, hulthe reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6836)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`talpid-tunnel-config-client/src/socket.rs` line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6836#-O7UEhou1X_YWHpKuj11:-O7UUYf8EwZdhc_IDxbB:bv2mr3g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfd2319e12460817512cf6e6bfb341ca3cf080d0/talpid-tunnel-config-client/src/socket.rs#L21)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

why this specific value?
</blockquote></details>

can we use the const from talpid-wireguard?


<!-- Sent from Reviewable.io -->

2024-09-24 07:38 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6836)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @hulthe)

___
*[`talpid-tunnel-config-client/src/socket.rs` line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6836#-O7UFhmNCIu9yAQ7y9v1:-O7XxZ7NAwTWjfRuY2N5:bha2bo4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfd2319e12460817512cf6e6bfb341ca3cf080d0/talpid-tunnel-config-client/src/socket.rs#L50)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Good idea. Done.
</blockquote></details>

I had to revert this, because it was a bit flaky for some reason (connecting occasionally failed).

Anyway, this is unrelated to my changes, so I don't think it should be done here.


<!-- Sent from Reviewable.io -->

2024-09-24 09:14 UTC, hulthe approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6836#-:-O7YIqYO3bGD7i5Ksok1:bnfp4nl)* status: 2 of 6 files reviewed, all discussions resolved

___
*[`talpid-tunnel-config-client/src/socket.rs` line 21 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6836#-O7UEhou1X_YWHpKuj11:-O7YILJ79L5dqnSwi_3W:b-fyysb8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfd2319e12460817512cf6e6bfb341ca3cf080d0/talpid-tunnel-config-client/src/socket.rs#L21)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I didn't want to couple this to `talpid-wireguard`, so I added a comment instead.
</blockquote></details>

Aight :+1: 
___
*[`talpid-tunnel-config-client/src/socket.rs` line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6836#-O7UFhmNCIu9yAQ7y9v1:-O7YIbUzB7h7-vSQDn4Q:b-70e83m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cfd2319e12460817512cf6e6bfb341ca3cf080d0/talpid-tunnel-config-client/src/socket.rs#L50)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I had to revert this, because it was a bit flaky for some reason (connecting ocassionally failed).

Anyway, this is unrelated to my changes, so I don't think it should be done here.
</blockquote></details>

Aight, sad but we'll leave it like this then :+1: 


<!-- Sent from Reviewable.io -->

2024-09-24 13:59 UTC, merged