Fix IPv6 parsing in API access methods and custom DNS
mullvad/mullvadvpn-app pull request #6852
Opened 2024-09-24 08:06 UTC by rablador

Acceptance criteria:

- Adding IPv6 addresses should work, whilst the app should still reject any arbitrary unsigned 32 bit integer instead of interpreting that as an IPv4 address.
- Custom DNS and API access method code should use the same validation for IP addresses.
- Using IPv6 addresses in custom API methods and custom DNS works.
- The validation code must be unit tested.
- When this is fixed, it should be mentioned in the changelog.

2024-09-25 17:03 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6852)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPNTests/MullvadTypes/AnyIPAddressTests.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6852#-O7e7f084R_WyaRLThNF:-O7e7f0967CTcc_jPMnx:b-9ryrmu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d53151a37ebeae32667402dc40ed01ed8115740/ios/MullvadVPNTests/MullvadTypes/AnyIPAddressTests.swift#L25)):*
> ```Swift
>         XCTAssertNotNil(AnyIPAddress("2a03:1b20:1:f011::bb09"))
>         XCTAssertNotNil(AnyIPAddress("FE80:0000:0000:0000:0202:B3FF:FE1E:8329"))
>     }
> ```

I suggest to add more IPs to be tested out:



_Code snippet:_
```Swift
        XCTAssertNotNil(AnyIPAddress("2001:0db8:0000:0042:0000:8a2e:0370:7334"))
        XCTAssertNotNil(AnyIPAddress("2001:db8::42:0:8a2e:370:7334"))
        XCTAssertNotNil(AnyIPAddress("::1"))
        XCTAssertNotNil(AnyIPAddress("::"))
        XCTAssertNotNil(AnyIPAddress("::ffff:192.168.1.1"))
        XCTAssertNotNil(AnyIPAddress("fe80::1ff:fe23:4567:890a"))
        XCTAssertNotNil(AnyIPAddress("ff02::1"))
        XCTAssertNotNil(AnyIPAddress("2001:0db8:85a3::8a2e:0370:7334"))
        XCTAssertNotNil(AnyIPAddress("fc00::1234:5678:abcd"))
```


<!-- Sent from Reviewable.io -->

2024-09-25 17:19 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6852#-:-O7eBQBy8JBpL-YTZYj6:bnfp4nl)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2024-09-26 08:04 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6852)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @mojganii)

___
*[`ios/MullvadVPNTests/MullvadTypes/AnyIPAddressTests.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6852#-O7e7f084R_WyaRLThNF:-O7hLw2u4RLFp2a__mIq:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7d53151a37ebeae32667402dc40ed01ed8115740/ios/MullvadVPNTests/MullvadTypes/AnyIPAddressTests.swift#L25)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I suggest to add more IPs to be tested out:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-26 11:00 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6852#-:-O7hzI8ZBTsZojCToVj8:bnfp4nl)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-09-30 11:12 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6852#-:-O81cSmE6Gx_GNhT2vxh:bnfp4nl)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-09-30 11:25 UTC, merged