Duplicate windows x86 installer to have one without architecture suffix
mullvad/mullvadvpn-app pull request #6885
Opened 2024-09-30 08:29 UTC by raksooo

Until we have the universal Windows installer we want to upload the x64 installer but without the architecture suffix. This is to avoid making changes to other parts of the release process in the meanwhile.

2024-09-30 09:15 UTC, dlon reviewed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885)* status: all files reviewed, 1 unresolved discussion (waiting on @raksooo)

___
*[`ci/buildserver-build.sh` line 232 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885#-O81CKdCAXh7wVdH-MPb:-O81CKdCAXh7wVdH-MPc:b-ji0njt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a300dff7a1113687d9762ccd089fbfdf204d47bc/ci/buildserver-build.sh#L232)):*
> ```Shell
>         pushd "$artifact_dir"
>         for original_file in MullvadVPN-*-dev-*{.deb,.rpm,.exe,.pkg}; do
>             new_file=$(echo "$original_file" | sed -nE "s/^(MullvadVPN-.*-dev-.*)(_amd64\.deb|_x86_64\.rpm|_arm64\.deb|_aarch64\.rpm|_x64\.exe|_arm64\.exe|\.pkg)$/\1$version_suffix\2/p")
> ```

Do we need to rename the `.exe` without a suffix here?


<!-- Sent from Reviewable.io -->

2024-09-30 11:31 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885)* status: all files reviewed, 1 unresolved discussion

___
*[`ci/buildserver-build.sh` line 232 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885#-O81CKdCAXh7wVdH-MPb:-O81fsw77O9-UjGRM_T5:ba4s7rv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2ff7f11fa9acefe24cc0c29279feb8b3b2172189/ci/buildserver-build.sh#L232)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Do we need to rename the `.exe` without a suffix here?
</blockquote></details>

Yes, I wonder how that will work together with the suffixed ones. I'll try it out!


<!-- Sent from Reviewable.io -->

2024-09-30 13:49 UTC, raksooo reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dlon)

___
*[`ci/buildserver-build.sh` line 232 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885#-O81CKdCAXh7wVdH-MPb:-O82BD7V6WOiQ8ouz7hy:b-9kiyyt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2ff7f11fa9acefe24cc0c29279feb8b3b2172189/ci/buildserver-build.sh#L232)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Yes, I wonder how that will work together with the suffixed ones. I'll try it out!
</blockquote></details>

Fixed! I had to switch from `sed` to `perl` due to sed not supporting non-greedy matching.


<!-- Sent from Reviewable.io -->

2024-09-30 17:58 UTC, dlon reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`ci/buildserver-build.sh` line 232 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885#-O81CKdCAXh7wVdH-MPb:-O834A9_C7Qnqn2L7Aeq:b1bzz6y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2ff7f11fa9acefe24cc0c29279feb8b3b2172189/ci/buildserver-build.sh#L232)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

Fixed! I had to switch from `sed` to `perl` due to sed not supporting non-greedy matching.
</blockquote></details>

Surely `test-test` isn't correct?


<!-- Sent from Reviewable.io -->

2024-10-01 08:06 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885)* status: all files reviewed, 2 unresolved discussions (waiting on @raksooo)

___
*[`ci/buildserver-build.sh` line 209 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885#-O866QaABmoWceoecuri:-O866QaABmoWceoecurj:b-e9g56o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc1c61350444d81ca3fadeeb8d069b8c713cee6f/ci/buildserver-build.sh#L209)):*
> ```Shell
>             echo "Copying _x64.exe file to .exe for backwards and forwards compatibility"
>             find "$artifact_dir" -type f -name 'MullvadVPN*_x64.exe' \
>                 -exec bash -c 'cp "$0" "${0%_x64.exe}.exe"' {} \;
> ```

Is there no way to instead make electron builder produce the correct artifact name out of the box, instead of having to copy it? We don't need nor will ever need the `_x64` file name.
___
*[`ci/buildserver-build.sh` line 232 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885#-O866FZ148_lmFjS1o-y:-O866FZ28oNEPcpPr5ll:b-foqm6u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/cc1c61350444d81ca3fadeeb8d069b8c713cee6f/ci/buildserver-build.sh#L232)):*
> ```Shell
>         pushd "$artifact_dir"
>         for original_file in MullvadVPN-*-dev-*{.deb,.rpm,.exe,.pkg}; do
>             new_file=$(echo "$original_file" | perl -pe "s/^(MullvadVPN-.*?)(_arm64|_aarch64|_amd64|_x86_64|_x64)?(\.deb|\.rpm|\.exe|\.pkg)$/\1+test-test\2\3/p")
> ```

Looks like leftover testing.

Why change to perl? The command does not look noticeably shorter or clearer? Sed seems to have worked fine for us for a long time.


<!-- Sent from Reviewable.io -->

2024-10-01 08:54 UTC, faern submitted a review, later dismissed
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-01 15:57 UTC, raksooo reviewed
I've now tested this on the biuldserver and it works as expected :+1:

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885#-:-O87lijpCbtnjMzoYyDB:brik4oy)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-01 20:05 UTC, dlon approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-02 07:37 UTC, dlon approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-02 09:06 UTC, faern approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-02 10:05 UTC, merged