Rename account "token" to account "number"
mullvad/mullvadvpn-app pull request #6888
Opened 2024-09-30 13:14 UTC by hulthe

2024-09-30 20:59 UTC, MrChocolatine commented
This PR reminds me of #6333 .

What is more, that other PR also says this:
> It also includes a test to ensure this convention is followed.

but apparently `setAccountToken` and `accountToken` are still currently used [`4c925ef` (#6888)](https://github.com/mullvad/mullvadvpn-app/pull/6888/commits/4c925efc890b9abe6a911a60da89cda697238cd0).

2024-10-01 08:22 UTC, hulthe commented
> This PR reminds me of https://github.com/mullvad/mullvadvpn-app/pull/6333 .

Haha yeah, the Android team beat us to it :)

I get why they didn't change setAccountToken though, it's part of the IPC and changing it would affect more than just the Android codebase.

2024-10-01 09:40 UTC, MarkusPettersson98 requested changes
Nice! Did some grepping of my own and found some instances where we probably want to rename some variables :)

> Reviewed 68 of 69 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-:-O86RqJj90dst1xP2h7C:bir6xlb)* status: all files reviewed, 37 unresolved discussions (waiting on @hulthe)

___
*[`gui/src/main/account.ts` line 73 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86GjKPDz_UMJCiqFc2:-O86GjKPDz_UMJCiqFc3:b-kb1zzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/gui/src/main/account.ts#L73)):*
> ```XML
>     IpcMainEventChannel.account.handleCreate(() => this.createNewAccount());
>     IpcMainEventChannel.account.handleLogin(
>       async (token: AccountNumber) => (await this.login(token)) ?? undefined,
> ```

This variable is still called `token`



_Code quote:_
```XML
async (token: AccountNumber) => (await this.login(token)) ?? undefined,
```
___
*[`gui/src/main/account-data-cache.ts` line 36 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86GtYB3zdocsyJfm9s:-O86GtYB3zdocsyJfm9t:b-kb1zzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/gui/src/main/account-data-cache.ts#L36)):*
> ```XML
> 
>   constructor(
>     private fetchHandler: (token: AccountNumber) => Promise<AccountDataResponse>,
> ```

This variable is still called `token`



_Code quote:_
```XML
private fetchHandler: (token: AccountNumber) => Promise<AccountDataResponse>,
```
___
*[`gui/src/renderer/components/Login.tsx` line 388 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86R63N2_G_45OBv-TK:-O86R63N2_G_45OBv-TL:b-kb1zzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/gui/src/renderer/components/Login.tsx#L388)):*
> ```XML
>     />
>   );
> }
> ```

This variable is still called `token`



_Code quote:_
```XML
function AccountDropdown(props: IAccountDropdownProps) {
  const token = props.item;
  if (!token) {
    return null;
  }
  const label = formatAccountNumber(token);
  return (
    <AccountDropdownItem
      value={token}
      label={label}
      onSelect={props.onSelect}
      onRemove={props.onRemove}
    />
  );
}
```
___
*[`gui/test/unit/account-data-cache.spec.ts` line 26 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86MxALDNpUjYH8YcgI:-O86MxALDNpUjYH8YcgJ:b-kb1zzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/gui/test/unit/account-data-cache.spec.ts#L26)):*
> ```XML
>   it('should notify when fetch succeeds on the first attempt', async () => {
>     const cache = new AccountDataCache(
>       (_token) => Promise.resolve(dummyAccountData),
> ```

This variable is still called `token`



_Code quote:_
```XML
(_token) => Promise.resolve(dummyAccountData),
```
___
*[`gui/test/unit/account-data-cache.spec.ts` line 42 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86N1p82QN9p1VWGazh:-O86N1p82QN9p1VWGazi:b-kb1zzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/gui/test/unit/account-data-cache.spec.ts#L42)):*
> ```XML
>   it('should notify when fetch fails on the first attempt', async () => {
>     const cache = new AccountDataCache(
>       (_token) => Promise.resolve({ type: 'error', error: 'invalid-account' }),
> ```

This variable is still called `token`



_Code quote:_
```XML
(_token) => Promise.resolve({ type: 'error', error: 'invalid-account' }),
```
___
*[`gui/test/unit/account-data-cache.spec.ts` line 103 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86N6_Q3Y9h4JOFRu0M:-O86N6_Q3Y9h4JOFRu0N:b-kb1zzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/gui/test/unit/account-data-cache.spec.ts#L103)):*
> ```XML
>     const update = new Promise<IAccountData | void>((resolve, reject) => {
>       let firstAttempt = true;
>       const fetch = (_token: string) => {
> ```

This variable is still called `token`



_Code quote:_
```XML
const fetch = (_token: string) => {
```
___
*[`mullvad-cli/src/cmds/account.rs` line 148 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86NVJGADrGb3ouj5GY:-O86NVJGADrGb3ouj5GZ:b-kb1zzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-cli/src/cmds/account.rs#L148)):*
> ```XML
>     ) -> Result<()> {
>         let token = account_else_current(rpc, account).await?;
>         let mut device_list = rpc.list_devices(token).await?;
> ```

This variable is still called `token`



_Code quote:_
```XML
        let token = account_else_current(rpc, account).await?;
        let mut device_list = rpc.list_devices(token).await?;
```
___
*[`mullvad-cli/src/cmds/account.rs` line 177 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86NXrSB5V5cgOtqjB-:-O86NXrSB5V5cgOtqjB0:b-kb1zzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-cli/src/cmds/account.rs#L177)):*
> ```XML
>         let token = account_else_current(rpc, account).await?;
> 
>         let device_list = rpc.list_devices(token.clone()).await?;
> ```

This variable is still called `token`



_Code quote:_
```XML
        let token = account_else_current(rpc, account).await?;

        let device_list = rpc.list_devices(token.clone()).await?;
```
___
*[`mullvad-cli/src/cmds/account.rs` line 186 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86NcmO1sK6TcBAK3q_:-O86NcmO1sK6TcBAK3qa:b-kb1zzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-cli/src/cmds/account.rs#L186)):*
> ```XML
>             .ok_or(mullvad_management_interface::Error::DeviceNotFound)?;
> 
>         rpc.remove_device(token, device_id).await?;
> ```

This variable is still called `token`



_Code quote:_
```XML
      rpc.remove_device(token, device_id).await?;
```
___
*[`mullvad-cli/src/cmds/account.rs` line 211 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86NiD79UBWtSajUano:-O86NiD79UBWtSajUanp:b-kb1zzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-cli/src/cmds/account.rs#L211)):*
> ```XML
>     token: Option<String>,
> ) -> Result<String> {
>     match token {
> ```

This variable is still called `token`



_Code quote:_
```XML
async fn account_else_current(
    rpc: &mut MullvadProxyClient,
    token: Option<String>,
) -> Result<String> {
    match token {
```
___
*[`mullvad-daemon/src/account_history.rs` line 32 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86OMaB8UPfMF__KbMQ:-O86OMaB8UPfMF__KbMR:b-kb1zzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-daemon/src/account_history.rs#L32)):*
> ```XML
>     file: io::BufWriter<fs::File>,
>     token: Option<AccountNumber>,
> }
> ```

This variable is still called `token`



_Code quote:_
```XML
pub struct AccountHistory {
    file: io::BufWriter<fs::File>,
    token: Option<AccountNumber>,
}
```
___
*[`mullvad-daemon/src/account_history.rs` line 39 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86OOwZEH4TbvkB4Iqe:-O86OOwZEH4TbvkB4Iqf:b-kb1zzp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-daemon/src/account_history.rs#L39)):*
> ```XML
>     pub async fn new(
>         settings_dir: &Path,
>         current_token: Option<AccountNumber>,
> ```

This variable is still called `token`



_Code quote:_
```XML
        current_token: Option<AccountNumber>,
```
___
*[`mullvad-daemon/src/account_history.rs` line 75 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86OSny5WURRaPCnG0D:-O86OSny5WUR [...]

2024-10-01 13:15 UTC, hulthe reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`gui/src/main/account.ts` line 73 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86GjKPDz_UMJCiqFc2:-O8794j31DTQSrZU4xBw:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/gui/src/main/account.ts#L73)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`gui/src/main/account-data-cache.ts` line 36 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86GtYB3zdocsyJfm9s:-O8795ZO4aN2y_rtgnq0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/gui/src/main/account-data-cache.ts#L36)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`gui/src/renderer/components/Login.tsx` line 388 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86R63N2_G_45OBv-TK:-O8797FAD2grmWDbiaws:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/gui/src/renderer/components/Login.tsx#L388)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`gui/test/unit/account-data-cache.spec.ts` line 26 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86MxALDNpUjYH8YcgI:-O8798BU1TKdExN_Si-0:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/gui/test/unit/account-data-cache.spec.ts#L26)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`gui/test/unit/account-data-cache.spec.ts` line 42 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86N1p82QN9p1VWGazh:-O8798jREC7k4B0rPeFC:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/gui/test/unit/account-data-cache.spec.ts#L42)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`gui/test/unit/account-data-cache.spec.ts` line 103 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86N6_Q3Y9h4JOFRu0M:-O8799K995KZNO6O_mZa:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/gui/test/unit/account-data-cache.spec.ts#L103)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/account.rs` line 148 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86NVJGADrGb3ouj5GY:-O879BFO7aIgmcp_xuCa:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-cli/src/cmds/account.rs#L148)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/account.rs` line 177 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86NXrSB5V5cgOtqjB-:-O879COu5sHWTv1O3bmE:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-cli/src/cmds/account.rs#L177)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/account.rs` line 186 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86NcmO1sK6TcBAK3q_:-O879D6tDYbVsrp5S-Ec:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-cli/src/cmds/account.rs#L186)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`mullvad-cli/src/cmds/account.rs` line 211 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86NiD79UBWtSajUano:-O879Dmi51ni2l9jXcK2:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-cli/src/cmds/account.rs#L211)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`mullvad-daemon/src/account_history.rs` line 32 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86OMaB8UPfMF__KbMQ:-O879EW80CKk-TwptouM:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-daemon/src/account_history.rs#L32)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`mullvad-daemon/src/account_history.rs` line 39 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86OOwZEH4TbvkB4Iqe:-O879FB37roJ5HDhEiu7:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-daemon/src/account_history.rs#L39)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`mullvad-daemon/src/account_history.rs` line 75 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86OSny5WURRaPCnG0D:-O879Gv_BCvOHBekW8Hj:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-daemon/src/account_history.rs#L75)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`mullvad-daemon/src/account_history.rs` line 90 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86OURVEwUR3NrlGqii:-O879Hlw-ynZPUD7VGxL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-daemon/src/account_history.rs#L90)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`mullvad-daemon/src/account_history.rs` line 96 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86OVrr3qp5-IqKKF8q:-O879ILJ-D5ojiMpVdTJ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-daemon/src/account_history.rs#L96)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`mullvad-daemon/src/account_history.rs` line 102 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86OXPxB35Q0SRlKKyq:-O879Ivd3GZDySsRbSA4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-daemon/src/account_history.rs#L102)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This variable is still called `token`
</blockquote></details>

Done.
___
*[`mullvad- [...]

2024-10-01 13:44 UTC, MarkusPettersson98 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-:-O87JnlGEoV6EcIqf7AO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`mullvad-daemon/src/migrations/v5.rs` line 124 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-O86Q1wN3HsxKR-dRtmt:-O87JkDwD0lYiM_J6mKx:bqy67xj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db495246990c7930e25c9a48b63aaeb51836528e/mullvad-daemon/src/migrations/v5.rs#L124)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

A bit hesitant on digging around in old migration code, considering that the migrated field is still called `account_token` here.
</blockquote></details>

Fair enough


<!-- Sent from Reviewable.io -->

2024-10-01 14:02 UTC, raksooo approved these changes
Looks good. The changes to the `messges.po` files will require us to upload them manually next time we do translations after this, which likely is in preperation of the 2024.7 release.

> Reviewed 35 of 69 files at r1, 5 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888#-:-O87NiGJEsCP5lZf4vMD:b-s9wc51)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-01 14:02 UTC, Rawa approved these changes
> Reviewed 54 of 69 files at r1, 1 of 1 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6888)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-01 14:27 UTC, merged