Show create account confirm when user has account
mullvad/mullvadvpn-app pull request #6951
Opened 2024-10-09 11:25 UTC by kl

Now showing a confirmation dialog when creating an account when the user has already logged in on another account on the device. The text is a placeholder and needs to be decided on.

2024-10-11 08:48 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6951)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/AccountRepository.kt` line 71 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6951#-O8uUAYEB0l8fg94nQBf:-O8ukrQI1gma8oGJBCFZ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1eed10eaea3e372358f41f6a174ba02b12cd13/android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/AccountRepository.kt#L71)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

For both this and the one above we should do `onRight`. Otherwise might reset it incorrectly.
```
.onRight()
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-11 10:10 UTC, Pururun submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6951#-:-O8v2nE4B6pUwP6-CzYo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)



<!-- Sent from Reviewable.io -->

2024-10-11 11:48 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6951)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

___
*[`android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/AccountRepository.kt` line 71 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6951#-O8uUAYEB0l8fg94nQBf:-O8vP7Aj683b1W1ixu9-:b-hff248) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1eed10eaea3e372358f41f6a174ba02b12cd13/android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/AccountRepository.kt#L71)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@kl Forgot to push? the code is still the same.


<!-- Sent from Reviewable.io -->

2024-10-12 10:36 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6951)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/AccountRepository.kt` line 71 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6951#-O8uUAYEB0l8fg94nQBf:-O9-HsxW3eYwEwx8N_4y:bsa5h7i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8e1eed10eaea3e372358f41f6a174ba02b12cd13/android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/AccountRepository.kt#L71)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

@kl Forgot to push? the code is still the same.
</blockquote></details>

Oops :smile: fixed now


<!-- Sent from Reviewable.io -->

2024-10-15 12:16 UTC, Pururun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6951#-:-O9F61dy9dEwfWQUxzoi:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)



<!-- Sent from Reviewable.io -->

2024-10-15 12:37 UTC, Rawa approved these changes
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6951)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-15 12:41 UTC, merged