Fix parsing of build tags
mullvad/mullvadvpn-app pull request #6993
Opened 2024-10-16 14:10 UTC by Serock3

2024-10-21 09:07 UTC, dlon submitted a review, later dismissed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6993)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`test/scripts/test-utils.sh` line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6993#-O9i61241voBuNScjs5u:-O9i61241voBuNScjs5v:b-2nb3cr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ba141694f3fba2555bf110bebaf48d3b39622f81/test/scripts/test-utils.sh#L50)):*
> ```Shell
> if [[ -n "$TAG" && ${CURRENT_VERSION} =~ -dev- ]]; then
>     # Remove disallowed version characters from the tag
>     CURRENT_VERSION+="+${TAG//[^0-9a-z_-]/}"
> ```

Should this really strip uppercase letters? But I guess that's already the case in `buildserver-build.sh` as well, so being consistent makes sense. :shrug: 


<!-- Sent from Reviewable.io -->

2024-10-21 09:18 UTC, Serock3 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6993)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`test/scripts/test-utils.sh` line 50 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6993#-O9i61241voBuNScjs5u:-O9iMIVK2D7doLbmi8ex:bgdp7ch) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ba141694f3fba2555bf110bebaf48d3b39622f81/test/scripts/test-utils.sh#L50)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should this really strip uppercase letters? But I guess that's already the case in `buildserver-build.sh` as well, so being consistent makes sense. :shrug:
</blockquote></details>

Really weird, but if we don't match the behavior we don't get the correct URLs :shrug: I guess we could change it in both places if you think it would be an improvement.


<!-- Sent from Reviewable.io -->

2024-10-21 12:08 UTC, raksooo requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6993)* status: all files reviewed, 1 unresolved discussion (waiting on @Serock3)

___
*[`test/scripts/test-utils.sh` line 99 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6993#-O9ixtwSD14NiX8rupIA:-O9ixtwT0VDv2EtikEjr:b-etdg8h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/46167b45c080da7787f9e1159598c50fc4bdbf66/test/scripts/test-utils.sh#L99)):*
> ```Shell
> # - COMMIT_HASH: The commit hash part of the build string (e.g., "abcdef").
> # - TAG: The tag part of the build string (e.g., "+tag").
> function parse_build_version {
> ```

I find it a bit confusing that this function doesn't return the values but set them as global variables. If my memory isn't failing me it's not possible to return multiple values in a simple way though. I would suggest splitting this function into three different functions that each return one of build version, commit hash and tag.


<!-- Sent from Reviewable.io -->

2024-10-22 11:57 UTC, raksooo submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6993)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-22 12:41 UTC, Serock3 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6993)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @dlon and @raksooo)

___
*[`test/scripts/test-utils.sh` line 99 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6993#-O9ixtwSD14NiX8rupIA:-O9oEauw-8H0TLmoBJyY:bc3v2aw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/46167b45c080da7787f9e1159598c50fc4bdbf66/test/scripts/test-utils.sh#L99)):*
<details><summary><i>Previously, raksooo (Oskar Nyberg) wrote…</i></summary><blockquote>

I find it a bit confusing that this function doesn't return the values but set them as global variables. If my memory isn't failing me it's not possible to return multiple values in a simple way though. I would suggest splitting this function into three different functions that each return one of build version, commit hash and tag.
</blockquote></details>

As per our discussion, I will keep the current implementation


<!-- Sent from Reviewable.io -->

2024-10-22 12:49 UTC, raksooo approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6993)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-22 12:52 UTC, merged