POC of using page object pattern
mullvad/mullvadvpn-app pull request #7017
Opened 2024-10-18 13:52 UTC by niklasberglund

POC of using page object pattern for the login tests. Basically moving UI automator interactions to page classes with abstract functions representing user actions in test cases. Automated tests read like manual test cases and code is reused more.

In this POC PR I have not updated the detekt config but if we go with something like this we probably would like to set up some rules for `Page` subclasses?

2024-10-21 09:19 UTC, Pururun requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/LoginPage.kt` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017#-O9iM0fw-Oax_7pZpLfz:-O9iM0fw-Oax_7pZpLg-:b3oo508) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c66460763523b35c5a21d362ddcf7157c80811da/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/LoginPage.kt#L19)):*
> ```Kotlin
>     fun tapLoginButton(): LoginPage {
>         val accountTextField = device.findObjectWithTimeout(By.clazz("android.widget.EditText"))
>         val loginButton = accountTextField.parent.findObject(By.clazz(Button::class.java))
> ```

I don't really understand this, should this not find all buttons in the login screen? Is it possible to do both type and text?
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LoginTest.kt` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017#-O9iMlTE3zNe4lWxuJgz:-O9iMlTE3zNe4lWxuJh-:bjpn40d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c66460763523b35c5a21d362ddcf7157c80811da/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LoginTest.kt#L26)):*
> ```Kotlin
> 
>         LoginPage(device)
>             .enterAccountNumber(validTestAccountNumber)
> ```

:star: 


<!-- Sent from Reviewable.io -->

2024-10-21 09:46 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/LoginPage.kt` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017#-O9iM0fw-Oax_7pZpLfz:-O9iQDES9V5JnGAvgDXc:be0vjri) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c66460763523b35c5a21d362ddcf7157c80811da/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/LoginPage.kt#L19)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I don't really understand this, should this not find all buttons in the login screen? Is it possible to do both type and text?
</blockquote></details>

For this POC I just moved the existing code to this page function. The identification of this button could definitely be improved, but I kept down the scope of this PR. 


<!-- Sent from Reviewable.io -->

2024-10-21 10:45 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/LoginPage.kt` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017#-O9iM0fw-Oax_7pZpLfz:-O9iU-TWDSNnaqqqu7Pt:b-1jdw8f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c66460763523b35c5a21d362ddcf7157c80811da/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/LoginPage.kt#L19)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

For this POC I just moved the existing code to this page function. The identification of this button could definitely be improved, but I kept down the scope of this PR.
</blockquote></details>

Could also do this maybe?



_Code snippet:_
```Kotlin
    fun tapLoginButton(): LoginPage {
        val loginButton = device.findObject(By.clazz(Button::class.java).text("Login"))
        loginButton.wait(Until.enabled(true), DEFAULT_TIMEOUT)
        loginButton.click()
        return this
    }
```


<!-- Sent from Reviewable.io -->

2024-10-21 13:29 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/LoginPage.kt` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017#-O9iM0fw-Oax_7pZpLfz:-O9jFh5gEVXFVY2GOj-2:b-i5siaf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c66460763523b35c5a21d362ddcf7157c80811da/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/LoginPage.kt#L19)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

Could also do this maybe?
</blockquote></details>

IMHO test tags are more robust because text labels and class types can change, but that's another discussion and refactoring maybe 😊 Anyways if it breaks now it would only need to be updated in one place


<!-- Sent from Reviewable.io -->

2024-10-21 21:52 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/LoginPage.kt` line 19 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017#-O9iM0fw-Oax_7pZpLfz:-O9l36BY9TuKFJBJsU4y:bd6bjr4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c66460763523b35c5a21d362ddcf7157c80811da/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/LoginPage.kt#L19)):*
> For this POC I just moved the existing code to this page function. The identification of this button could definitely be improved, but I kept down the scope of this PR.

Right, than just ignore what I said. :)


<!-- Sent from Reviewable.io -->

2024-12-02 08:07 UTC, Rawa requested changes
> Reviewed 1 of 6 files at r2, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @niklasberglund)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/PrivacyPage.kt` line 11 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017#-OD5PDB85eTaT9YRaz3z:-OD5PDB85eTaT9YRaz4-:b4kfnyl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/381f294af3a3c7dac3fe402225e7205e486928cd/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/PrivacyPage.kt#L11)):*
> ```Kotlin
> class PrivacyPage internal constructor() : Page() {
>     override fun assertIsDisplayed() {
>         // uiDevice.findObjectWithTimeout(By.res("connect_card_header_test_tag"))
> ```

Should fix


<!-- Sent from Reviewable.io -->

2024-12-02 08:07 UTC, Rawa reviewed
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @niklasberglund)



<!-- Sent from Reviewable.io -->

2024-12-02 10:07 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 6 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017#-:-OD5pnJh1dUaOssr8gqO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)



<!-- Sent from Reviewable.io -->

2024-12-02 10:12 UTC, Pururun approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)



<!-- Sent from Reviewable.io -->

2024-12-02 13:27 UTC, Rawa submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-02 13:33 UTC, niklasberglund reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017#-:-OD6ZkU7CI4CxJ0T-cOo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/PrivacyPage.kt` line 11 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017#-OD5PDB85eTaT9YRaz3z:-OD6Z_tn1C4jnnY1dLI9:bh5plb7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/381f294af3a3c7dac3fe402225e7205e486928cd/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/PrivacyPage.kt#L11)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should fix
</blockquote></details>

Looks good to me since there is no test tag in privacy screen and we don't have any strict rule on only using test tags


<!-- Sent from Reviewable.io -->

2024-12-02 15:10 UTC, Pururun submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-02 15:27 UTC, Pururun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r5, 1 of 1 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7017#-:-OD6yqY08Rq5S2ckjzgq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-02 19:11 UTC, closed without merging