Update cell layout and behavior for obfuscation methods
mullvad/mullvadvpn-app pull request #7020
Opened 2024-10-18 14:28 UTC by rablador

For each cell that needs it (udp2tcp, shadowsocks):

- the cell should display the current port setting
- the cell should have an action button that will eventually navigate to a new view
- there should be a divider
- It should use the correct background color when selected/unselected

2024-10-24 11:36 UTC, acb-mv approved these changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-24 13:22 UTC, pinkisemils reviewed
Tested it out in mock release, and it is fine - no changes. Debug build looks to spec. Have not checked the code itself.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-:-O9yeOUv4lelpP3Eyp6z:b-glilx0)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-24 13:28 UTC, rablador reviewed
Updated color of separator.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-:-O9yhN965dvwABjtt86r:b-bz1vmd)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @acb-mv)



<!-- Sent from Reviewable.io -->

2024-10-28 10:33 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @acb-mv and @rablador)

___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 96 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAHTGaC5uCGm0fHnCnf:-OAHTGaC5uCGm0fHnCng:bljfxa5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50d9a7b84a8b2e6f8b91e42a7491acf327eeaa07/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L96)):*
> ```Swift
>         static let apiAccessSwitchCellTrailingMargin: CGFloat = apiAccessInsetLayoutMargins.trailing - 4
>         static let apiAccessPickerListContentInsetTop: CGFloat = 16
>         static let buttonSeparatorHeight: CGFloat = 22
> ```

nit : `VerticalDeviderHeight`can be a better candidate. `Divider` color is not clear for unselected options but it's discussed just I put that here to give feedback.

<!DOCTYPE html>
<html lang="en">
<body>

<table style="width: 100%; height: 100vh; border-collapse: collapse; text-align: center;">
    <tr>
        <td style="border: 1px solid #000;">
            <img src="https://files.reviewableusercontent.io/images/reviewable/129863230/tA9AoqUKX0Ehrs52OEB2Sqyx/Simulator%20Screenshot%20-%20iPhone%2015%20Pro%20-%202024-10-28%20at%2010.38.14.png" style="width: 100px; height: auto;">
        </td>
    </tr>
</table>

</body>
</html>
___
*[`ios/MullvadVPN/View controllers/Settings/SelectableSettingsDetailsCell.swift` line 20 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAHY4PO8t3QDd27dWTO:-OAHY4PO8t3QDd27dWTP:b-hsym00) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50d9a7b84a8b2e6f8b91e42a7491acf327eeaa07/ios/MullvadVPN/View%20controllers/Settings/SelectableSettingsDetailsCell.swift#L20)):*
> ```Swift
> 
>         let actionButton = IncreasedHitButton(type: .system)
>         actionButton.setImage(UIImage(systemName: "ellipsis"), for: .normal)
> ```

let's use `UIButton.Configuration` for button styling.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift` line 174 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAHatPwAGf3pCKsDVAx:-OAHatPwAGf3pCKsDVAy:bs9l1tc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50d9a7b84a8b2e6f8b91e42a7491acf327eeaa07/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsCellFactory.swift#L174)):*
> ```Swift
>             #if DEBUG
>             cell.detailTitleLabel.text = String(format: NSLocalizedString(
>                 "WIRE_GUARD_OBFUSCATION_SHADOWSOCKS_PORT",
> ```

Wireguard is a name then  texts should be started with `Wireguard_`
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDetailsButtonItem.swift` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAHev5P99Icy_6QFj8x:-OAHev5P99Icy_6QFj8y:b-74zif7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50d9a7b84a8b2e6f8b91e42a7491acf327eeaa07/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDetailsButtonItem.swift#L10)):*
> ```Swift
> 
> enum VPNSettingsDetailsButtonItem {
>     case udpTcp
> ```

I recommend avoid `abbreviation` as much as possible , `udpOverTcp` and `wireguardOverShadowsocks`


<!-- Sent from Reviewable.io -->

2024-10-28 10:39 UTC, mojganii reviewed
there are some codes in `UITest` that is looking `wireGuardObfuscationOn` which is no longer available, they need to attention to be resolved 

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-:-OAHh8W75K0x-ycT5IwT:b-h8g0fj)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @acb-mv and @rablador)



<!-- Sent from Reviewable.io -->

2024-10-28 15:02 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @acb-mv and @mojganii)

___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 96 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAHTGaC5uCGm0fHnCnf:-OAIYOnrEEK40OqFRFY5:b7el2wg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50d9a7b84a8b2e6f8b91e42a7491acf327eeaa07/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L96)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit : `VerticalDeviderHeight`can be a better candidate. `Divider` color is not clear for unselected options but it's discussed just I put that here to give feedback.

<!DOCTYPE html>
<html lang="en">
<body>

<table style="width: 100%; height: 100vh; border-collapse: collapse; text-align: center;">
    <tr>
        <td style="border: 1px solid #000;">
            <img src="https://files.reviewableusercontent.io/images/reviewable/129863230/tA9AoqUKX0Ehrs52OEB2Sqyx/Simulator%20Screenshot%20-%20iPhone%2015%20Pro%20-%202024-10-28%20at%2010.38.14.png" style="width: 100px; height: auto;">
        </td>
    </tr>
</table>

</body>
</html>
</blockquote></details>

Feedback noted, but I think you should add it as a comment on the designs instead so that it reaches the right person.
___
*[`ios/MullvadVPN/View controllers/Settings/SelectableSettingsDetailsCell.swift` line 20 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAHY4PO8t3QDd27dWTO:-OAIcsdpE7rlHsq0xlug:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50d9a7b84a8b2e6f8b91e42a7491acf327eeaa07/ios/MullvadVPN/View%20controllers/Settings/SelectableSettingsDetailsCell.swift#L20)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

let's use `UIButton.Configuration` for button styling.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift` line 174 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAHatPwAGf3pCKsDVAx:-OAId1rV6rxGQ_RYyKSx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50d9a7b84a8b2e6f8b91e42a7491acf327eeaa07/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsCellFactory.swift#L174)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Wireguard is a name then  texts should be started with `Wireguard_`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDetailsButtonItem.swift` line 10 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAHev5P99Icy_6QFj8x:-OAIdNAiBYmWjcVFLf-c:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50d9a7b84a8b2e6f8b91e42a7491acf327eeaa07/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDetailsButtonItem.swift#L10)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I recommend avoid `abbreviation` as much as possible , `udpOverTcp` and `wireguardOverShadowsocks`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-28 16:36 UTC, buggmagnet requested changes
Not sure what happened here, but the offset that used to be to the right of the version string seems to be missing now. 
I have checked on main, and the offset looks good there. 
![IMG\_4BE28F3A035A-1.jpeg](https://files.reviewableusercontent.io/images/reviewable/129761703/DfdWyrUGw0kcgwEC6xZLX8h0/IMG_4BE28F3A035A-1.jpeg)

> Reviewed 4 of 12 files at r1, 7 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-:-OAIlL1j7d_-6IG-AJJH:b-vklub7)* status: 13 of 14 files reviewed, 8 unresolved discussions (waiting on @mojganii and @rablador)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAIn1dy9O6JV9cEYUnV:-OAIn1dy9O6JV9cEYUnW:bhynevi) (no related file):*
I can trigger two obfuscation settings being enabled at the same time. I'm guessing it's because we don't save anything just yet when we select some obfuscation ?
[RPReplay\_Final1730130143.mov](https://files.reviewableusercontent.io/images/reviewable/129761703/KLtmYduxwXSRUJ8FJ9mOKIWh/RPReplay_Final1730130143.mov)

___
___
*[`ios/MullvadVPN/View controllers/Settings/SelectableSettingsCell.swift` line 47 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAInGaZA3n5BwHsves6:-OAInGaZA3n5BwHsves7:b91p22i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e0c1b9f09f062a2dcc194d067b82edc76e1d5db/ios/MullvadVPN/View%20controllers/Settings/SelectableSettingsCell.swift#L47)):*
> ```Swift
>                 tickImageView.pinEdgesToSuperview(PinnableEdges([
>                     .leading(0),
>                     .trailing(UIMetrics.SettingsCell.selectableSettingsCellLeftViewSpacing),
> ```

nit
can't we just set the `,trailing` one leaving the others by default to 0 ?
___
*[`ios/MullvadVPN/View controllers/Settings/SelectableSettingsDetailsCell.swift` line 14 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAIq5km0i1DlEUXmgMD:-OAIq5km0i1DlEUXmgME:b-soac1a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e0c1b9f09f062a2dcc194d067b82edc76e1d5db/ios/MullvadVPN/View%20controllers/Settings/SelectableSettingsDetailsCell.swift#L14)):*
> ```Swift
>     let viewContainer = UIView()
> 
>     var action: (() -> Void)?
> ```

I'm surprised the compiler doesn't warn here.
[`action` is actually a function defined in `CALayerDelegate`](https://developer.apple.com/documentation/quartzcore/calayer/1410844-action) which all `UIView` subclasses adopt (so does `UITableViewCell`)

I'm assuming that it doesn't complain because this is technically a valid function overload, but I really think we should rename this to something more explicit like `ellipsisAction` to avoid future confusion. 

We should do the same in `SettingsAddDNSEntryCell`
___
*[`ios/MullvadVPN/View controllers/Settings/SelectableSettingsDetailsCell.swift` line 29 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAIyCO64AtJmiaZ0uSF:-OAIyCO64AtJmiaZ0uSG:bd5hh9x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e0c1b9f09f062a2dcc194d067b82edc76e1d5db/ios/MullvadVPN/View%20controllers/Settings/SelectableSettingsDetailsCell.swift#L29)):*
> ```Swift
>             self,
>             action: #selector(didPressActionButton),
>             for: .valueChanged
> ```

This won't work unless you use `.touchUpInside` 


<!-- Sent from Reviewable.io -->

2024-10-29 08:58 UTC, rablador reviewed
Fixed.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-:-OAMUtCE4WD0IYmrdtG3:bt2vr1b)* status: 13 of 14 files reviewed, 8 unresolved discussions (waiting on @buggmagnet and @mojganii)

*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAIn1dy9O6JV9cEYUnV:-OAM990B8uyHgmFORve-:bhbkjj5) (no related file):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I can trigger two obfuscation settings being enabled at the same time. I'm guessing it's because we don't save anything just yet when we select some obfuscation ?
[RPReplay\_Final1730130143.mov](https://files.reviewableusercontent.io/images/reviewable/129761703/KLtmYduxwXSRUJ8FJ9mOKIWh/RPReplay_Final1730130143.mov)
</blockquote></details>

Both udpTcp and shadowsocks point to `.on`, so that's why.

___
___
*[`ios/MullvadVPN/View controllers/Settings/SelectableSettingsCell.swift` line 47 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAInGaZA3n5BwHsves6:-OAMAMygBLWoxySQfVM-:bt63pz0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e0c1b9f09f062a2dcc194d067b82edc76e1d5db/ios/MullvadVPN/View%20controllers/Settings/SelectableSettingsCell.swift#L47)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
can't we just set the `,trailing` one leaving the others by default to 0 ?
</blockquote></details>

It can (sort of) be done, but it'll look like there's something special going on, given that the assignments have been split up. I've provided a more compact solution in the meantime.



_Code snippet:_
```Swift
tickImageView.pinEdgesToSuperview(.all().excluding(.trailing))
tickImageView.pinEdgesToSuperview(PinnableEdges([.trailing(UIMetrics.SettingsCell.selectableSettingsCellLeftViewSpacing)]))
```
___
*[`ios/MullvadVPN/View controllers/Settings/SelectableSettingsDetailsCell.swift` line 14 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAIq5km0i1DlEUXmgMD:-OAMBJIGDrVwynZD8FLS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e0c1b9f09f062a2dcc194d067b82edc76e1d5db/ios/MullvadVPN/View%20controllers/Settings/SelectableSettingsDetailsCell.swift#L14)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I'm surprised the compiler doesn't warn here.
[`action` is actually a function defined in `CALayerDelegate`](https://developer.apple.com/documentation/quartzcore/calayer/1410844-action) which all `UIView` subclasses adopt (so does `UITableViewCell`)

I'm assuming that it doesn't complain because this is technically a valid function overload, but I really think we should rename this to something more explicit like `ellipsisAction` to avoid future confusion. 

We should do the same in `SettingsAddDNSEntryCell`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Settings/SelectableSettingsDetailsCell.swift` line 29 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAIyCO64AtJmiaZ0uSF:-OAMCwV2CvfRMqX2HXC7:b-ok8s6g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e0c1b9f09f062a2dcc194d067b82edc76e1d5db/ios/MullvadVPN/View%20controllers/Settings/SelectableSettingsDetailsCell.swift#L29)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This won't work unless you use `.touchUpInside`
</blockquote></details>

Late copy/paste... 😕


<!-- Sent from Reviewable.io -->

2024-10-29 13:04 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 12 files at r1, 1 of 8 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-:-OANN5XGDSVEGTEkMYsn:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 469 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OANN-r6A9PnZSJVA1wn:-OANN-r6A9PnZSJVA1wo:bgc8s0r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c00c25cdfe777cd5d9d5671c5a3630fa260ad82f/ios/MullvadVPN.xcodeproj/project.pbxproj#L469)):*
> ```
> 		7A27E3CB2CAE861D0088BCFF /* SettingsViewModel.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7A27E3CA2CAE86170088BCFF /* SettingsViewModel.swift */; };
> 		7A27E3CD2CB814EF0088BCFF /* DAITAInfoView.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7A27E3CC2CB814EA0088BCFF /* DAITAInfoView.swift */; };
> 		7A27E3CF2CBD4A8C0088BCFF /* SelectableSettingsDetailsCell.swift in Sources */ = {isa = PBXBuildFile; fileRef = 7A27E3CE2CBD4A830088BCFF /* SelectableSettingsDetailsCell.swift */; };
> ```

Nit
The `Settings` folder is not ordered by name anymore.


<!-- Sent from Reviewable.io -->

2024-10-29 13:14 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 469 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OANN-r6A9PnZSJVA1wn:-OANPXyl4gnkx7gqzug_:bt2vr0y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c00c25cdfe777cd5d9d5671c5a3630fa260ad82f/ios/MullvadVPN.xcodeproj/project.pbxproj#L469)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Nit
The `Settings` folder is not ordered by name anymore.
</blockquote></details>

Fixed!


<!-- Sent from Reviewable.io -->

2024-10-29 14:20 UTC, mojganii approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020)* status: 15 of 16 files reviewed, 5 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @rablador)

___
*[`ios/MullvadVPN/UI appearance/UIMetrics.swift` line 96 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020#-OAHTGaC5uCGm0fHnCnf:-OANaM2S7qjs0KhvNSsY:bb74ce2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/50d9a7b84a8b2e6f8b91e42a7491acf327eeaa07/ios/MullvadVPN/UI%20appearance/UIMetrics.swift#L96)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Feedback noted, but I think you should add it as a comment on the designs instead so that it reaches the right person.
</blockquote></details>

Sure


<!-- Sent from Reviewable.io -->

2024-10-30 08:47 UTC, merged