Implement multihop UI
mullvad/mullvadvpn-app pull request #7036
Opened 2024-10-21 22:02 UTC by Pururun

Draft PR for multihop. This is based on non-complete implementation of multihop so tunnel is potentially broken and combination with other settings might also not work.

SelectLocation is split into two screens:
`SelectLocation`
`SearchLocation`

`SelectLocation` has two different lists, entry and exit. Both lists have their own viewModel to mostly keep track of expansions and selections. Entry lists is only available if multihop is enabled.

`SearchLocation` uses a sort of fake `SearchBar` from material 3. The input is the same, but the lists is displayed in a normal `LazyColumn`

Not working 100%:
- Animations.

Missing:
- Unit tests
- Ui tests

2024-10-23 13:09 UTC, kl reviewed
> Reviewed 42 of 63 files at r1, 2 of 3 files at r2, 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: 49 of 64 files reviewed, 3 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MultihopScreen.kt` line 66 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9nNffN1LB5HlRg157x:-O9nNffOE_3NaE8mLLRh:b-gxnhrk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd612c684024bd1d042dad657b0089e2bbbec7ef/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MultihopScreen.kt#L66)):*
> ```Kotlin
>                 contentScale = ContentScale.FillWidth,
>                 modifier =
>                     Modifier.widthIn(min = Dp.Infinity, max = Dimens.settingsDetailsImageMaxWidth)
> ```

Should this not be min = Dp.Unspecified (the default value of min) instead of min = Dp.Infinity?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationList.kt` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9tOvu_1InBqpaKqQys:-O9tOvuaAukMHa-g4o_I:bs1xhz3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationList.kt#L88)):*
> ```Kotlin
> }
> 
> private fun SelectLocationListUiState.indexOfSelectedRelayItem(): Int =
> ```

What about returning Int? here instead of -1? Also the false cases can be collapsed like this:



_Code snippet:_
```Kotlin
private fun SelectLocationListUiState.indexOfSelectedRelayItem(): Int? =
    if (this is SelectLocationListUiState.Content) {
        relayListItems.indexOfFirst {
            when (it) {
                is RelayListItem.CustomListItem -> it.isSelected
                is RelayListItem.GeoLocationItem -> it.isSelected
                is RelayListItem.CustomListEntryItem,
                is RelayListItem.CustomListFooter,
                RelayListItem.CustomListHeader,
                RelayListItem.LocationHeader,
                is RelayListItem.LocationsEmptyText -> false
            }
        }
    } else {
        null
    }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationScreen.kt` line 159 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9tQSQv2PIxC1vaoxLM:-O9tQSQv2PIxC1vaoxLN:bkytl48) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationScreen.kt#L159)):*
> ```Kotlin
>         onSelectRelay = vm::selectRelay,
>         onSearchClick = { navigator.navigate(SearchLocationDestination(it)) },
>         onBackClick = dropUnlessResumed { backNavigator.navigateBack() },
> ```

Do we need to wrap all these in dropUnlessResumed? If this callback is invoked when the user clicks a button the app has to be in the resumed state so dropUnlessResumed will never do anything.


<!-- Sent from Reviewable.io -->

2024-10-24 09:19 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: 49 of 64 files reviewed, 3 unresolved discussions (waiting on @kl)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationList.kt` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9tOvu_1InBqpaKqQys:-O9xoMsm6nkh6eTg8zQ9:brxp9sd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationList.kt#L88)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

What about returning Int? here instead of -1? Also the false cases can be collapsed like this:
</blockquote></details>

Sounds good!
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationScreen.kt` line 159 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9tQSQv2PIxC1vaoxLM:-O9xoOE_60su38VDdQlj:b-hk2ja4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationScreen.kt#L159)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

Do we need to wrap all these in dropUnlessResumed? If this callback is invoked when the user clicks a button the app has to be in the resumed state so dropUnlessResumed will never do anything.
</blockquote></details>

It is mostly to protect against the user clicking the button multiple times.


<!-- Sent from Reviewable.io -->

2024-10-24 14:47 UTC, Rawa reviewed
> Reviewed 11 of 63 files at r1, 1 of 3 files at r2, 4 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: 49 of 64 files reviewed, 10 unresolved discussions (waiting on @kl and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadSegmentedButton.kt` line 57 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9t5JSsClGSHm1QFod0:-O9t5JSsClGSHm1QFod1:bo8r7j9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadSegmentedButton.kt#L57)):*
> ```Kotlin
> }
> 
> sealed interface SegmentedButtonPosition {
> ```

Feels a bit unnecessary since it is only 3 options and it directly maps to one value. We could provide 3 different functions e.g
MullvadSegmentedStartButton, MullvadSegmentedMiddle, MullvadSegmentedEndButton, and have one where 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/FilterRow.kt` line 49 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9y9TaE4WRsiZzcgSwV:-O9y9TaE4WRsiZzcgSwW:b9zeb61) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/FilterRow.kt#L49)):*
> ```Kotlin
>                 .fillMaxWidth()
>                 .horizontalScroll(scrollState),
>         horizontalArrangement = Arrangement.spacedBy(Dimens.chipSpace, alignment = Alignment.Start),
> ```

Isn't `Alignment.Start` default?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 68 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9yvpNJ-HfYJ94MDdAl:-O9yvpNJ-HfYJ94MDdAm:bmc9ztf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L68)):*
> ```Kotlin
> fun StatusRelayItemCell(
>     item: RelayItem,
>     name: String,
> ```

Isn't name the name off the `RelayItem`? Why do we need it on the side? If this is the case we maybe should consider making a RelayItem agnostic component on the side?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 124 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9yw-mGAOT7epG44yyB:-O9yw-mGAOT7epG44yyC:b-so8vwt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L124)):*
> ```Kotlin
>     name: String,
>     hasChildren: Boolean,
>     isEnabled: Boolean,
> ```

Why did we replace `RelayItem`? `isEnabled` is different from before?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/LocationsEmptyText.kt` line 17 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9ywLo8BQkXSpDbN-wg:-O9ywLo8BQkXSpDbN-wh:b-m6wivp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/LocationsEmptyText.kt#L17)):*
> ```Kotlin
> @Composable
> fun LocationsEmptyText(searchTerm: String) {
>     if (searchTerm.length >= MIN_SEARCH_LENGTH) {
> ```

Nice clean up :star: :broom: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MultihopScreen.kt` line 66 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9nNffN1LB5HlRg157x:-O9ywiQB2q4iyQClPaGS:b1vnrqe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd612c684024bd1d042dad657b0089e2bbbec7ef/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MultihopScreen.kt#L66)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

Should this not be min = Dp.Unspecified (the default value of min) instead of min = Dp.Infinity?
</blockquote></details>

Is `min` an optional parameter?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt` line 155 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9ywxQjDqrJ_vbMe9Mv:-O9ywxQjDqrJ_vbMe9Mw:b-v5r521) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt#L155)):*
> ```Kotlin
>         onClick = onMultihopClick,
>         bodyView =
>             @Composable {
> ```

`@Composable` shouldn't be necessary right?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/LocationBottomSheet.kt` line 49 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9yxG7V6SasuHMV2fRV:-O9yxG7V6SasuHMV2fRW:b-pzq89y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/LocationBottomSheet.kt#L49)):*
> ```Kotlin
> @OptIn(ExperimentalMaterial3Api::class)
> @Composable
> internal fun LocationBottomSheets(
> ```

Nice compromise, too bad BottomSheet destinations doesn't exist in Material3 yet :cry: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/RelayListContent.kt` line 101 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9yxnJK1uNlXGCgU10T:-O9yxnJK1uNlXGCgU10U:b-imdf2v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/RelayListContent.kt#L101)):*
> ```Kotlin
>                             { onSelectRelay(listItem.item) },
>                             {
>                                 // Only direct children can be removed
> ```

Not introduced by you, but shouldn't this comment be few lines up? 

```
           if (listItem.depth == 1) {
                                {
                                    onUpdateBottomSheetState(
                                        ShowCustomListsEntryBottomSheet(
                                            listItem.parentId,
                                            listItem.parentName,
                                            listItem.item,
                                        )
                                    )
                                }
```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SearchLocationScreen.kt` line 123 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9yyZ303-bv-ICdUsLD:-O9yyZ303-bv-ICdUsLE:b-616tp5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SearchLocationScreen.kt#L123)):*
> ```Kotlin
>                     snackbarHostState.showSnackbarImmediately(
>                         message = context.getString(R.string.error_occurred),
>                         duration = SnackbarDuration.Short,
> ```

This should already be default right?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationList.kt` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9tOvu_1InBqpaKqQys:-O9yzePcCrpNS-vf-1Hl:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationList.kt#L88)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Sounds good!
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2024-10-24 14:49 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: 49 of 64 files reviewed, 10 unresolved discussions (waiting on @kl and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationScreen.kt` line 159 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9tQSQv2PIxC1vaoxLM:-O9z-4bb0FVIt0Kse9Vx:b-plzzkd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationScreen.kt#L159)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

It is mostly to protect against the user clicking the button multiple times.
</blockquote></details>

Unfortunately a button can be clicked in a not resumed state, so you can actually get multiple clicks while animating the view away.


<!-- Sent from Reviewable.io -->

2024-10-24 14:50 UTC, Rawa reviewed
> Reviewed 7 of 63 files at r1, 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: 52 of 64 files reviewed, 10 unresolved discussions (waiting on @kl and @Pururun)



<!-- Sent from Reviewable.io -->

2024-10-25 09:13 UTC, Rawa reviewed
> Reviewed 32 of 63 files at r1, 2 of 3 files at r2, 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: all files reviewed, 20 unresolved discussions (waiting on @kl and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/RelayListItem.kt` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1WUbtCc5RtAR-X3d7:-OA1WUbtCc5RtAR-X3d8:b-pmfknp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/RelayListItem.kt#L65)):*
> ```Kotlin
> 
>     data object LocationHeader : RelayListItem {
>         override val key: Any = "location_header"
> ```

We should be able to remove `: Any` from the subtypes. Top level should still be `Any`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SearchSelectLocationUiState.kt` line 20 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1XVAeAaAufoo1g80x:-OA1XVAeAaAufoo1g80y:buuew5x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SearchSelectLocationUiState.kt#L20)):*
> ```Kotlin
>         val relayListItems: List<RelayListItem>,
>         val customLists: List<RelayItem.CustomList>,
>         val relayListSelection: RelayListSelection,
> ```

I think the name of this type can be a bit more clear, was confused to it's purpose and had to go into the type so find out.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SettingsUiState.kt` line 8 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1YVMuDvTIJ8zFSPec:-OA1YVMuDvTIJ8zFSPed:b-55dqi5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SettingsUiState.kt#L8)):*
> ```Kotlin
>     val isSupportedVersion: Boolean,
>     val isPlayBuild: Boolean,
>     val useMultihop: Boolean,
> ```

nit: `multihopEnabled` or `isMultihopEnabled` would be more clear.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt` line 13 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1_ujN3poGHGysiKYv:-OA1_ujN3poGHGysiKYw:b7mhor4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt#L13)):*
> ```Kotlin
> 
> // Creates a relay list to be displayed by RelayListContent
> // Search input as null is defined as not searching
> ```

Is empty string searching?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt` line 255 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1abqy6VdxUziYxkNQ:-OA1abqzDCzgxdRPxGSe:b-dpd9mp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt#L255)):*
> ```Kotlin
> // city it is fine to have same entry and exit
> // For custom lists we will block if the custom lists only contains one relay and
> // nothing else
> ```

Could this cause problems if I add 2 items to the custom lists, use multihop and them remove the item that was not selected as my entry?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/SearchLocationViewModel.kt` line 146 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1bVhdAZo9WkXyInuV:-OA1bVhdAZo9WkXyInuW:bmhq7nj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/SearchLocationViewModel.kt#L146)):*
> ```Kotlin
>             filterChips.toMutableList().apply {
>                 // Do not show entry and exit filter chips if multihop is disabled
>                 if (multihopEnabled()) {
> ```

This is a bit dangerous, since if multihop gets disabled/enabled, we don't get a new list of filterChips. We should user combine inorder to always emit the correct value.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/SelectLocationListViewModel.kt` line 68 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1bju_EJG5Lyyaq14F:-OA1bju_EJG5Lyyaq14G:b9q6lsy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/SelectLocationListViewModel.kt#L68)):*
> ```Kotlin
>         when (item) {
>             is GeoLocationId.City -> {
>                 Logger.d("GC item: $item")
> ```

Reminder to remove these logs.
___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt` line 96 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1TxhBER-KI-Z8FPvD:-OA1TxhBER-KI-Z8FPvE:bgnamc4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt#L96)):*
> ```Kotlin
>                         } else null
>                     },
>                 featureIndicators = emptyList(),
> ```

What happened here? :upside_down_face: 
___
*[`android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt` line 109 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1TynT7Q9Xm0kM4BaQ:-OA1TynT7Q9Xm0kM4BaR:b-yq3bu8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt#L109)):*
> ```Kotlin
>                         }
>                     },
>                 featureIndicators = emptyList(),
> ```

and here.
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/SelectedLocation.kt` line 3 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1U7evDq2hix_VkPPh:-OA1U7evDq2hix_VkPPi:b4x7wmx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/SelectedLocation.kt#L3)):*
> ```Kotlin
> package net.mullvad.mullvadvpn.lib.model
> 
> sealed interface SelectedLocation {
> ```

I think we should try and come up with a better name. `SelectedLocation` sounds like there is only one location you select. Let's discuss within the team, some quick proposals:

`RelayItemSelection`
`TunnelPathSelection`
`HopConfiguration`
___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/SelectedLocation.kt` line 11 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1V0dO-6R7ToLyeIX7:-OA1V0dO-6R7ToLyeIX8:bjotqw5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/SelectedLocation.kt#L11)):*
> ```Kotlin
>         val entryLocation: Constraint<RelayItemId>,
>         override val exitLocation: Constraint<RelayItemId>,
>     ) : SelectedLocation
> ```

The structure of the type looks good :100: 


<!-- Sent from Reviewable.io -->

2024-10-25 10:55 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: all files reviewed, 20 unresolved discussions (waiting on @kl and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadSegmentedButton.kt` line 57 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9t5JSsClGSHm1QFod0:-OA27fkz1x9Vb0-DMTpG:bs7wtrb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadSegmentedButton.kt#L57)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Feels a bit unnecessary since it is only 3 options and it directly maps to one value. We could provide 3 different functions e.g
MullvadSegmentedStartButton, MullvadSegmentedMiddle, MullvadSegmentedEndButton, and have one where
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-10-28 08:00 UTC, Rawa reviewed
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: 62 of 64 files reviewed, 19 unresolved discussions (waiting on @kl and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadSegmentedButton.kt` line 57 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9t5JSsClGSHm1QFod0:-OAH7v8GA7PRvIbuNlgz:b-w1ctpo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadSegmentedButton.kt#L57)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Nice :star: 


<!-- Sent from Reviewable.io -->

2024-10-28 08:02 UTC, Rawa reviewed
> Reviewed 5 of 63 files at r1, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: all files reviewed, 19 unresolved discussions (waiting on @kl and @Pururun)



<!-- Sent from Reviewable.io -->

2024-10-28 08:29 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: all files reviewed, 17 unresolved discussions (waiting on @kl and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/FilterRow.kt` line 49 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9y9TaE4WRsiZzcgSwV:-OAH7rFgB47zlOWPCaqm:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/FilterRow.kt#L49)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Isn't `Alignment.Start` default?
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 68 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9yvpNJ-HfYJ94MDdAl:-OAH7vTODtBC5oGu97zt:b-upv20i) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L68)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Isn't name the name off the `RelayItem`? Why do we need it on the side? If this is the case we maybe should consider making a RelayItem agnostic component on the side?
</blockquote></details>

It is used for blocked text, but maybe we should move that to the viewModel, let's discuss this.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 124 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9yw-mGAOT7epG44yyB:-OAH8DxMDWfMu-1vYUlz:b-34vmyd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L124)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Why did we replace `RelayItem`? `isEnabled` is different from before?
</blockquote></details>

See above
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/LocationsEmptyText.kt` line 17 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9ywLo8BQkXSpDbN-wg:-OAH8H6jAzcCUYDxiW5D:b32vhw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/LocationsEmptyText.kt#L17)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Nice clean up :star: :broom:
</blockquote></details>

:)
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MultihopScreen.kt` line 66 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9nNffN1LB5HlRg157x:-OAH8uq5CxuZTL2L2qOV:bb45h9c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd612c684024bd1d042dad657b0089e2bbbec7ef/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MultihopScreen.kt#L66)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Is `min` an optional parameter?
</blockquote></details>

The idea is that the image should scale up to fill the width of the screen until a certain width. Setting min to `Dp.Unspecified` makes the image not scale up and setting `fillMaxWidth` makes it ignore the max width. If there is a better way to do this I am all ears.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt` line 155 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9ywxQjDqrJ_vbMe9Mv:-OAH9XHp7qaGbuy9IlfM:b-lyri8b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt#L155)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`@Composable` shouldn't be necessary right?
</blockquote></details>

Seems to have been a copy-paste artifact from the other cells in this screen, removed all of then.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/LocationBottomSheet.kt` line 49 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9yxG7V6SasuHMV2fRV:-OAH9uDm1Ky5RruCKDqe:bnay2mz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/LocationBottomSheet.kt#L49)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Nice compromise, too bad BottomSheet destinations doesn't exist in Material3 yet :cry:
</blockquote></details>

:cry: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/RelayListContent.kt` line 101 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9yxnJK1uNlXGCgU10T:-OAHAPpt-FhBcRHg4jBA:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/RelayListContent.kt#L101)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Not introduced by you, but shouldn't this comment be few lines up? 

```
           if (listItem.depth == 1) {
                                {
                                    onUpdateBottomSheetState(
                                        ShowCustomListsEntryBottomSheet(
                                            listItem.parentId,
                                            listItem.parentName,
                                            listItem.item,
                                        )
                                    )
                                }
```
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SearchLocationScreen.kt` line 123 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9yyZ303-bv-ICdUsLD:-OAHAa8MCTJ9h59gPIKQ:b6q2evn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SearchLocationScreen.kt#L123)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This should already be default right?
</blockquote></details>

That is true, removed here and in select location
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationList.kt` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9tOvu_1InBqpaKqQys:-OAHB29C-4bubfmt5rkE:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationList.kt#L88)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/RelayListItem.kt` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1WUbtCc5RtAR-X3d7:-OAHBDjAEzSiZ4DoLAGh:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/RelayListItem.kt#L65)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should be able to remove `: Any` from the subtypes. Top level should still be `Any`
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SettingsUiState.kt` line 8 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1YVMuDvTIJ8zFSPec:-OAHBOWl4JlajZEIBv_K:bb6un1j) ([raw file](https://github [...]

2024-10-28 10:05 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: 50 of 64 files reviewed, 17 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationScreen.kt` line 159 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9tQSQv2PIxC1vaoxLM:-OAH_5ieEAbCbQxWxsYK:b-8r0l7r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationScreen.kt#L159)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Unfortunately a button can be clicked in a not resumed state, so you can actually get multiple clicks while animating the view away.
</blockquote></details>

I wasn't aware of that. Seems like a bug in Android for a button to be clicked in a state other than Resumed.


<!-- Sent from Reviewable.io -->

2024-10-28 15:51 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: 35 of 66 files reviewed, 17 unresolved discussions (waiting on @kl and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 68 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9yvpNJ-HfYJ94MDdAl:-OAInLKnAPLwKPHgJ3r4:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L68)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

It is used for blocked text, but maybe we should move that to the viewModel, let's discuss this.
</blockquote></details>

Fixed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 124 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9yw-mGAOT7epG44yyB:-OAInN5AEmZHmUOcE4vj:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L124)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MultihopScreen.kt` line 66 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9nNffN1LB5HlRg157x:-OAIoJBgCkp_uPleh6QT:b4ae87n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd612c684024bd1d042dad657b0089e2bbbec7ef/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MultihopScreen.kt#L66)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

The idea is that the image should scale up to fill the width of the screen until a certain width. Setting min to `Dp.Unspecified` makes the image not scale up and setting `fillMaxWidth` makes it ignore the max width. If there is a better way to do this I am all ears.
</blockquote></details>

Fixed by setting `fillMaxWidth()` after `widthIn`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SearchSelectLocationUiState.kt` line 20 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1XVAeAaAufoo1g80x:-OAIoY0T7Cqo0CGSCYUQ:bl5hh1f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SearchSelectLocationUiState.kt#L20)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I think the name of this type can be a bit more clear, was confused to it's purpose and had to go into the type so find out.
</blockquote></details>

Changed to `RelayListType`


<!-- Sent from Reviewable.io -->

2024-10-28 15:55 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: 35 of 66 files reviewed, 17 unresolved discussions (waiting on @kl and @Rawa)

___
*[`android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/SelectedLocation.kt` line 3 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1U7evDq2hix_VkPPh:-OAIoh1y8pjEzjF27slp:b-qd0v2a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/SelectedLocation.kt#L3)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I think we should try and come up with a better name. `SelectedLocation` sounds like there is only one location you select. Let's discuss within the team, some quick proposals:

`RelayItemSelection`
`TunnelPathSelection`
`HopConfiguration`
</blockquote></details>

Renamed to `RelayItemSelection`


<!-- Sent from Reviewable.io -->

2024-10-29 10:14 UTC, Rawa reviewed
> Reviewed 3 of 14 files at r5, 27 of 28 files at r6, 23 of 23 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: all files reviewed, 13 unresolved discussions (waiting on @kl and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 213 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OAMg6k3371CY75rSLNx:-OAMg6k3371CY75rSLNy:bnbjkx2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/834275f74002c2f788f2807793904282f15cbb70/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L213)):*
> ```Kotlin
> private fun Name(modifier: Modifier = Modifier, name: String, state: RelayListItemState?) {
>     Text(
>         text = name.appendName(state),
> ```

Nit: I think it is better to be explicit.

```
text = if(state == null) {
    name
} else {
    name.appendName(state)
}
```
Then we can avoid handling null in `appendName`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 264 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OAMgvbU8UF1sRxDazWe:-OAMgvbU8UF1sRxDazWf:b-ahfrho) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/834275f74002c2f788f2807793904282f15cbb70/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L264)):*
> ```Kotlin
> 
> @Composable
> private fun String.appendName(state: RelayListItemState?) =
> ```

Function name does not really match what it does, `appendName` sounds like we are appending a name. Maybe `withSuffix(state)`?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MultihopScreen.kt` line 66 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9nNffN1LB5HlRg157x:-OAMhIkT-ksNu4ecIlLN:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/fd612c684024bd1d042dad657b0089e2bbbec7ef/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MultihopScreen.kt#L66)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Fixed by setting `fillMaxWidth()` after `widthIn`
</blockquote></details>

:+1: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt` line 155 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9ywxQjDqrJ_vbMe9Mv:-OAMhMRe-7PHKEf3ukaz:bjpn40d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt#L155)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Seems to have been a copy-paste artifact from the other cells in this screen, removed all of then.
</blockquote></details>

:star: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt` line 225 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OAMhSXiBKryOUTGAuNP:-OAMhSXiBKryOUTGAuNQ:bk7n0ju) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/834275f74002c2f788f2807793904282f15cbb70/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt#L225)):*
> ```Kotlin
> 
> @Composable
> private fun Multihop(isMultihopEnabled: Boolean, onMultihopClick: () -> Unit) {
> ```

This is a very generic name. Should be something more specific. `MultihopCell` or `MultihopRow`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/RelayListContent.kt` line 101 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9yxnJK1uNlXGCgU10T:-OAMhcxY6mFngm6tpxJW:b-dtm9lm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/RelayListContent.kt#L101)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done
</blockquote></details>

:superhero: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationList.kt` line 88 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9tOvu_1InBqpaKqQys:-OAMhkqt5SwufH05Mw3h:bas2et2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationList.kt#L88)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Nice improvement.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationScreen.kt` line 159 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-O9tQSQv2PIxC1vaoxLM:-OAMiWl70PGediIfN0HQ:b-cuydig) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationScreen.kt#L159)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

I wasn't aware of that. Seems like a bug in Android for a button to be clicked in a state other than Resumed.
</blockquote></details>

Yeah, there is nothing protecting against a user clicking on a UI element while a screen is in "CREATED" state, thus causing multiple navigations up. @kl Please mark if you are happy with solution.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/RelayListItem.kt` line 18 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OAMivMz1e_xsAmd0Mhw:-OAMivMz1e_xsAmd0Mhx:b-c5e6ue) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/834275f74002c2f788f2807793904282f15cbb70/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/RelayListItem.kt#L18)):*
> ```Kotlin
> 
> enum class RelayListItemState {
>     BLOCKED_BY_ENTRY,
> ```

`BLOCKED_BY_ENTRY` or would `USED_AS_ENTRY` be more correct?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt` line 255 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1abqy6VdxUziYxkNQ:-OAMkHfUA7ZXlgOAVKA4:b-8goiwf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt#L255)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

I am not sure I follow, but it should not matter since the list should update?
</blockquote></details>

But it would then force the daemon to use the same Entry and Exit? Would we enter blocking? 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt` line 21 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OAMjcp90FAZIxaBVwez:-OAMjcpA6YrDW7koGmO7:b-873b0u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/834275f74002c2f788f2807793904282f15cbb70/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt#L21)):*
> ```Kotlin
>     customLists: List<RelayItem.CustomList>,
>     selectedItem: RelayItemId?,
>     disabledItem: RelayItemId?,
> ```

If I understand it correctly this is either a Entry or a Exit RelayItemId and thus can't be used and should be disabled? Can we make this clear with a better name?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt` line 117 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OAMjqZI3znqCmo2uP7G:-OAMjqZI3znqCmo2uP7H:blv8sqt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/834275f74002c2f788f2807793904282f15cbb70/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt#L117)):*
> ```Kotlin
>                         if (
>                             disabledItem  [...]

2024-10-29 15:31 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: 74 of 88 files reviewed, 11 unresolved discussions (waiting on @kl and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 213 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OAMg6k3371CY75rSLNx:-OANXZoV5VxHfx5bLR9s:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/834275f74002c2f788f2807793904282f15cbb70/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L213)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Nit: I think it is better to be explicit.

```
text = if(state == null) {
    name
} else {
    name.appendName(state)
}
```
Then we can avoid handling null in `appendName`
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt` line 264 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OAMgvbU8UF1sRxDazWe:-OANXa7Y5r3QWIhkUraE:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/834275f74002c2f788f2807793904282f15cbb70/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt#L264)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Function name does not really match what it does, `appendName` sounds like we are appending a name. Maybe `withSuffix(state)`?
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt` line 225 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OAMhSXiBKryOUTGAuNP:-OAN_S_hDzIi9FUZQ9Z7:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/834275f74002c2f788f2807793904282f15cbb70/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt#L225)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This is a very generic name. Should be something more specific. `MultihopCell` or `MultihopRow`
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/RelayListItem.kt` line 18 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OAMivMz1e_xsAmd0Mhw:-OAN_gFM2V6xR8mMXWXT:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/834275f74002c2f788f2807793904282f15cbb70/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/RelayListItem.kt#L18)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`BLOCKED_BY_ENTRY` or would `USED_AS_ENTRY` be more correct?
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt` line 255 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1abqy6VdxUziYxkNQ:-OANoy4i4fihxRAG-3NB:bs4e4de) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt#L255)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

But it would then force the daemon to use the same Entry and Exit? Would we enter blocking?
</blockquote></details>

Yes we would. :)
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt` line 21 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OAMjcp90FAZIxaBVwez:-OANp04J93BBvmyumaF4:bz40ugb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/834275f74002c2f788f2807793904282f15cbb70/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt#L21)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

If I understand it correctly this is either a Entry or a Exit RelayItemId and thus can't be used and should be disabled? Can we make this clear with a better name?
</blockquote></details>

Changed to `selectedByThisEntryExitList` and `selectedByOtherEntryExitList`
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt` line 117 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OAMjqZI3znqCmo2uP7G:-OANp-X-06Z8G37ZmXB8:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/834275f74002c2f788f2807793904282f15cbb70/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt#L117)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should break out this logic to another function.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt` line 188 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OAMk4eW15UZrSEk6e7M:-OANp-itCYKNYl3teZvt:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/834275f74002c2f788f2807793904282f15cbb70/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt#L188)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Break out as function as we implement this code twice.
</blockquote></details>

Done.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/SearchLocationViewModel.kt` line 144 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OAMkZfIEg6A1x2zFxJa:-OANgpfPEs3BoQUdr7qd:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/834275f74002c2f788f2807793904282f15cbb70/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/SearchLocationViewModel.kt#L144)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`useMultihop` should probably be renamed to `isMultihopEnabled`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-30 08:57 UTC, Rawa reviewed
> Reviewed 14 of 14 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SlideInFromBottomTransition.kt` line 77 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OARcyctB9a_EiSLq6qL:-OARcyctB9a_EiSLq6qM:b-k5q82w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6af69a609aa27c93d577b6b3c2b1485578eda936/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/SlideInFromBottomTransition.kt#L77)):*
> ```Kotlin
>             when (initialState.destination()) {
>                 NoDaemonDestination -> fadeIn(snap(0))
>                 SearchLocationDestination -> fadeIn()
> ```

:sparkles: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt` line 255 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OA1abqy6VdxUziYxkNQ:-OARd8mK32UhHkLQDApF:bmi8ppe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/180acb61c03bafdda7f77d19a106c2b2f31f9107/android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt#L255)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Yes we would. :)
</blockquote></details>

:100: 


<!-- Sent from Reviewable.io -->

2024-11-26 11:43 UTC, Rawa requested changes
> Reviewed 12 of 13 files at r10, 29 of 43 files at r11, 26 of 32 files at r12, 41 of 41 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: all files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/Daita.kt` line 5 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OBfA-Fy2-K_TDe3vtbZ:-OBfA-Fy2-K_TDe3vtb_:by49ktk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c6b227064c8f0e9168fa68de5bfddac9ccc5dc0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/Daita.kt#L5)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.compose.state.RelayListType
> 
> fun showOnlyRelaysWithDaita(
> ```

We should change this function name. Sounds like we are setting some property rather get deciding if we should show / filter on Daita relays.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/customlists/FilterCustomListsRelayItemUseCase.kt` line 34 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OBf9dpwB-CXCGVho5gn:-OBf9dpwB-CXCGVho5go:bpihxf8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c6b227064c8f0e9168fa68de5bfddac9ccc5dc0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/customlists/FilterCustomListsRelayItemUseCase.kt#L34)):*
> ```Kotlin
>                 ownership = selectedOwnership,
>                 providers = selectedProviders,
>                 shouldFilterByDaita =
> ```

We should improve on argument name.

`shouldFilterByDaita` is a parameter into filter. So the addition of `FilterByDaita` makes it confusing.


<!-- Sent from Reviewable.io -->

2024-11-26 11:45 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 414 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OCcHdY63XhBzC7eX-EE:-OCcHdY63XhBzC7eX-EF:bs30nzn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ba4ecfae48d0c05369e16f53381f106b80e180c9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L414)):*
> ```Kotlin
> 
>         val hostname =
>             when {
> ```

nit: Refactor into to another composable
___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt` line 59 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OCcHYw827SgQHP16sIG:-OCcHYw827SgQHP16sIH:bn1rofy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ba4ecfae48d0c05369e16f53381f106b80e180c9/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt#L59)):*
> ```Kotlin
>     val screenVerticalMargin: Dp = 22.dp,
>     val searchFieldHeight: Dp = 42.dp,
>     val searchFieldHeightExpanded: Dp = 85.dp,
> ```

This is a really odd height? Why exactly `85.dp`?


<!-- Sent from Reviewable.io -->

2024-11-26 14:02 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: all files reviewed, 3 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt` line 414 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OCcHdY63XhBzC7eX-EE:-OCcKtV-D8KvMYLfxmcE:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ba4ecfae48d0c05369e16f53381f106b80e180c9/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt#L414)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

nit: Refactor into to another composable
</blockquote></details>

Done
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/customlists/FilterCustomListsRelayItemUseCase.kt` line 34 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OBf9dpwB-CXCGVho5gn:-OCcgZNr5HqKmoF_-opG:b-atjstj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c6b227064c8f0e9168fa68de5bfddac9ccc5dc0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/customlists/FilterCustomListsRelayItemUseCase.kt#L34)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should improve on argument name.

`shouldFilterByDaita` is a parameter into filter. So the addition of `FilterByDaita` makes it confusing.
</blockquote></details>

Changed to `daita` after discussion
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/Daita.kt` line 5 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OBfA-Fy2-K_TDe3vtbZ:-OCcgc69140zqfkbBes1:bsmdyyf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9c6b227064c8f0e9168fa68de5bfddac9ccc5dc0/android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/Daita.kt#L5)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should change this function name. Sounds like we are setting some property rather get deciding if we should show / filter on Daita relays.
</blockquote></details>

Changed to `shouldFilterByDaita` after discussion
___
*[`android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt` line 59 at r14](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036#-OCcHYw827SgQHP16sIG:-OCckXOz9CuCaT6rPV9y:b-amfrbc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ba4ecfae48d0c05369e16f53381f106b80e180c9/android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt#L59)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This is a really odd height? Why exactly `85.dp`?
</blockquote></details>

Changed it to what it says in the material design guidelines


<!-- Sent from Reviewable.io -->

2024-11-26 14:17 UTC, Rawa reviewed
> Reviewed 21 of 22 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: 116 of 117 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-26 14:45 UTC, Rawa reviewed
> Reviewed 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-26 14:46 UTC, Rawa approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7036)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-27 07:58 UTC, merged