Avoid deadlocking the Packet Tunnel after a reboot
mullvad/mullvadvpn-app pull request #7089
Opened 2024-10-28 15:24 UTC by buggmagnet

This PR fixes a deadlock that was triggered by rebooting the phone when the VPN was connected.

2024-10-29 09:43 UTC, rablador reviewed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 176 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089#-OAMe-TU5ZIVmyWzTt9X:-OAMe-TU5ZIVmyWzTt9Y:b7hk4ad) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ee8b38e09f7e5c5ae795ea91d178dde5d9532aa2/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L176)):*
> ```Swift
>     }
> 
>     private func performSettingsMigration() {
> ```

Although we won't deadlock here, the code could potentially repeat forever. That's still by design then?


<!-- Sent from Reviewable.io -->

2024-10-29 09:57 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 177 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089#-OAMg2AW0sxS-_PbNVP7:-OAMg2AW0sxS-_PbNVP8:beq1i4r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ee8b38e09f7e5c5ae795ea91d178dde5d9532aa2/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L177)):*
> ```Swift
> 
>     private func performSettingsMigration() {
>         var hasNotMigratead = true
> ```

typo : `hasNotMigrated`
___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 178 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089#-OAMgf1L8iEua5UnhWaz:-OAMgf1L8iEua5UnhWb-:b-g8ze0q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ee8b38e09f7e5c5ae795ea91d178dde5d9532aa2/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L178)):*
> ```Swift
>     private func performSettingsMigration() {
>         var hasNotMigratead = true
>         repeat {
> ```

this loop tries until the migration is done, is it the thing? Can't return default value when it fails after last retry?


<!-- Sent from Reviewable.io -->

2024-10-29 10:04 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 179 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089#-OAMioRQ743mZLP8dKY9:-OAMioRQ743mZLP8dKYA:b-nkijcf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ee8b38e09f7e5c5ae795ea91d178dde5d9532aa2/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L179)):*
> ```Swift
>         var hasNotMigratead = true
>         repeat {
>             migrationManager.migrateSettings(
> ```

this code can be shorten like this : 



_Code snippet:_
```Swift
      while true {
            migrationManager.migrateSettings(
                store: SettingsManager.store,
                migrationCompleted: { [unowned self] migrationResult in
                    switch migrationResult {
                    case .success:
                        providerLogger.debug("Successful migration from PacketTunnel")
                        break
                    case .nothing:
                        providerLogger.debug("Attempted migration from PacketTunnel, but found nothing to do")
                        break
                    case let .failure(error):
                        providerLogger
                            .error(
                                "Failed migration from PacketTunnel: \(error)"
                            )
                        // `next` returns an Optional value, but this iterator is guaranteed to always have a next value
                        if let delay = migrationFailureIterator.next() {
                            providerLogger.error("Retrying migration in \(delay.timeInterval) seconds")
                            // Block the launch of the Packet Tunnel for as long as the settings migration fail.
                            // The process watchdog introduced by iOS 17 will kill this process after 60 seconds.
                            Thread.sleep(forTimeInterval: delay.timeInterval)
                        } else {
                            break
                        }
                    }
                }
            )
        }
```


<!-- Sent from Reviewable.io -->

2024-10-29 10:20 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 176 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089#-OAMe-TU5ZIVmyWzTt9X:-OAMmcY77BXwEFayPDtN:b2nhswy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ee8b38e09f7e5c5ae795ea91d178dde5d9532aa2/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L176)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Although we won't deadlock here, the code could potentially repeat forever. That's still by design then?
</blockquote></details>

Yes
___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 178 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089#-OAMgf1L8iEua5UnhWaz:-OAMmQl02KFRtHP7VcsZ:b-3dleg5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ee8b38e09f7e5c5ae795ea91d178dde5d9532aa2/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L178)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

this loop tries until the migration is done, is it the thing? Can't return default value when it fails after last retry?
</blockquote></details>

This is the intention, the PacketTunnel either succeeds the migration, or gets killed after 1 minute because of the new watchdog timer introduced in iOS 17
___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 179 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089#-OAMioRQ743mZLP8dKY9:-OAMmBK_0OBhQmI3ecCc:bq69feh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ee8b38e09f7e5c5ae795ea91d178dde5d9532aa2/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L179)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

this code can be shorten like this :
</blockquote></details>

This suggestion is problematic because it forces the PacketTunnelProvider to sleep in the callback from the `MigrationManager` effectively blocking the UI Process to perform migration while the sleep is happening. 


<!-- Sent from Reviewable.io -->

2024-10-29 10:38 UTC, mojganii requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift` line 179 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089#-OAMioRQ743mZLP8dKY9:-OAMqdlCC8356qdLG8MD:b-x4n4ru) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ee8b38e09f7e5c5ae795ea91d178dde5d9532aa2/ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift#L179)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This suggestion is problematic because it forces the PacketTunnelProvider to sleep in the callback from the `MigrationManager` effectively blocking the UI Process to perform migration while the sleep is happening.
</blockquote></details>

My mistake, that's true.


<!-- Sent from Reviewable.io -->

2024-10-29 10:42 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2024-10-29 18:44 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadREST/RetryStrategy/RetryStrategy.swift` line 86 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089#-OAO_qLN6joqO258L5fD:-OAO_qLO42M5f7olB6qv:bmewynb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f3d29750e0da52ce1c179f9a8499be307d106d8/ios/MullvadREST/RetryStrategy/RetryStrategy.swift#L86)):*
> ```Swift
>             delay: .exponentialBackoff(
>                 initial: .seconds(5),
>                 multiplier: UInt64(2),
> ```

As discussed on the day, I think there is no tangible difference between attempting to migrate 4 times a minute vs 12 - so we might as well go for the option that has a lower likelihood of getting killed and leave the multiplier at `1`.


<!-- Sent from Reviewable.io -->

2024-10-30 09:19 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadREST/RetryStrategy/RetryStrategy.swift` line 87 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089#-OARiC8u4Fitmf5yLB8m:-OARiC8u4Fitmf5yLB8n:bmewynb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f3d29750e0da52ce1c179f9a8499be307d106d8/ios/MullvadREST/RetryStrategy/RetryStrategy.swift#L87)):*
> ```Swift
>                 initial: .seconds(5),
>                 multiplier: UInt64(2),
>                 maxDelay: .minutes(1)
> ```

As discussed on the day, I think there is no tangible difference between attempting to migrate 4 times a minute vs 12 - so we might as well go for the option that has a lower likelihood of getting killed and leave the multiplier at `1`.


<!-- Sent from Reviewable.io -->

2024-10-30 09:25 UTC, mojganii submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089#-:-OARjZyl6k6uOz7IsG05:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-10-30 09:44 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadREST/RetryStrategy/RetryStrategy.swift` line 86 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089#-OAO_qLN6joqO258L5fD:-OARnzTa70suyV1ZTLnk:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f3d29750e0da52ce1c179f9a8499be307d106d8/ios/MullvadREST/RetryStrategy/RetryStrategy.swift#L86)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

As discussed on the day, I think there is no tangible difference between attempting to migrate 4 times a minute vs 12 - so we might as well go for the option that has a lower likelihood of getting killed and leave the multiplier at `1`.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-10-30 09:58 UTC, rablador reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089#-:-OARrGv-2mEVkAG7-nJQ:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2024-10-30 10:13 UTC, pinkisemils approved these changes
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @mojganii)



<!-- Sent from Reviewable.io -->

2024-10-30 10:17 UTC, merged