Add commit_hash to end to end test
mullvad/mullvadvpn-app pull request #7093
Opened 2024-10-29 09:32 UTC by mojganii

This PR enables iOS end-to-end tests to receive a commit_hash as an input, allowing the workflow to check out that specific commit. This input is optional, and if no value is provided, the workflow will use the latest commit from the branch that triggered it. The primary reason for this change is that iOS settings migration tests require an older commit version. By reusing iOS end-to-end tests for these cases and consolidating workflows and jobs in one place, it becomes necessary to fetch the repository at a specific reference.

2024-10-29 09:50 UTC, rablador requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7093)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`.github/workflows/ios-end-to-end-tests.yml` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7093#-OAMeTSJET9Bm-6bTJxA:-OAMeTSJET9Bm-6bTJxB:b80vfdm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f26182e9433642e8eb5756c19704cdcb5bd5dd/.github/workflows/ios-end-to-end-tests.yml#L18)):*
> ```YAML
>         type: string
>         required: false
>         
> ```

Remove extra spaces.
___
*[`.github/workflows/ios-end-to-end-tests.yml` line 85 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7093#-OAMfD-L62jm8e9m5Mn5:-OAMfD-L62jm8e9m5Mn6:b-xs0jmp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f26182e9433642e8eb5756c19704cdcb5bd5dd/.github/workflows/ios-end-to-end-tests.yml#L85)):*
> ```YAML
>         id: set-commit-hash
>         run: |
>           if [ -z "${{ inputs.commit_hash }}" ]; then
> ```

I think it makes more sense to check for the existence of something rather than the opposite. Ie:
`if [ -n "${{ inputs.commit_hash }}" ]; then`
___
*[`.github/workflows/ios-end-to-end-tests.yml` line 91 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7093#-OAMeYF54EJUEPW8bnbW:-OAMeYF54EJUEPW8bnbX:b80vfdm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f26182e9433642e8eb5756c19704cdcb5bd5dd/.github/workflows/ios-end-to-end-tests.yml#L91)):*
> ```YAML
>           fi
>         shell: bash
>         
> ```

Remove extra spaces.


<!-- Sent from Reviewable.io -->

2024-10-29 09:50 UTC, rablador reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7093)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)



<!-- Sent from Reviewable.io -->

2024-10-30 07:32 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7093)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @rablador)

___
*[`.github/workflows/ios-end-to-end-tests.yml` line 18 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7093#-OAMeTSJET9Bm-6bTJxA:-OARK_sA5CZt0rrXZIuA:bss4a1y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f26182e9433642e8eb5756c19704cdcb5bd5dd/.github/workflows/ios-end-to-end-tests.yml#L18)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

that is intentional
</blockquote></details>

Removed!
___
*[`.github/workflows/ios-end-to-end-tests.yml` line 91 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7093#-OAMeYF54EJUEPW8bnbW:-OARKgYY3XiO3mftUnM9:bss4a1y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/07f26182e9433642e8eb5756c19704cdcb5bd5dd/.github/workflows/ios-end-to-end-tests.yml#L91)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

that is intentional
</blockquote></details>

Removed!


<!-- Sent from Reviewable.io -->

2024-10-30 09:08 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7093#-:-OARfiHwDwaUOJYGk4xa:bnfp4nl)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2024-10-30 09:21 UTC, rablador reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7093#-:-OARify22jWEfdpy35l1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-30 10:02 UTC, merged