Add udp shadowsocks proxy support to mullvad ios
mullvad/mullvadvpn-app pull request #7132
Opened 2024-11-05 16:07 UTC by buggmagnet

This PR adds Shadowsocks obfuscation capabilities to the Packet Tunnel.
It cannot be used as of yet, but there is a test called `testRunningShadowsocksObfuscatorProxy` that makes use of the newly introduced obfuscation protocol.

2024-11-05 16:10 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132)* status: 0 of 12 files reviewed, 2 unresolved discussions

___
*[`mullvad-ios/src/tunnel_obfuscator_proxy/ffi.rs` line 10 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132#-OAx4fgo96WdPUd7Hm80:-OAx4fgo96WdPUd7Hm81:b-x1jyd9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82d5634bdd1553883765b7108aa82f886b121b0c/mullvad-ios/src/tunnel_obfuscator_proxy/ffi.rs#L10)):*
> ```XML
> static INIT_LOGGING: Once = Once::new();
> 
> #[allow(dead_code)]
> ```

note to self : this shouldn't be necessary, investigate 
___
*[`ios/MullvadRustRuntimeTests/UnsafeListener.swift` line 11 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132#-OAx4aEn5quFxTuXkPp3:-OAx4aEn5quFxTuXkPp4:bdhvxx6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82d5634bdd1553883765b7108aa82f886b121b0c/ios/MullvadRustRuntimeTests/UnsafeListener.swift#L11)):*
> ```Swift
> import Network
> 
> class UnsafeListener<T: Connection> {
> ```

note to self: Re add warning comment to not use this in production


<!-- Sent from Reviewable.io -->

2024-11-05 19:50 UTC, dlon reviewed
> Reviewed 4 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132)* status: 4 of 12 files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

___
*[`mullvad-ios/src/tunnel_obfuscator_proxy/mod.rs` line 23 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132#-OAxkLKJDt95RQzJMz8g:-OAxkLKJDt95RQzJMz8h:b-xmim2o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82d5634bdd1553883765b7108aa82f886b121b0c/mullvad-ios/src/tunnel_obfuscator_proxy/mod.rs#L23)):*
> ```XML
>         peer: SocketAddr,
>         obfuscation_protocol: TunnelObfuscatorProtocol,
>     ) -> io::Result<Self> {
> ```

Nit: Method could be infallible (just return `Self { .. }`).


<!-- Sent from Reviewable.io -->

2024-11-06 07:56 UTC, rablador requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132)* status: all files reviewed, 6 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadRustRuntimeTests/UDPConnection.swift` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132#-OB-S2dv1fSwxJJvsDTB:-OB-S2dv1fSwxJJvsDTC:b-5rt72u) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82d5634bdd1553883765b7108aa82f886b121b0c/ios/MullvadRustRuntimeTests/UDPConnection.swift#L75)):*
> ```Swift
>         return try await withCheckedThrowingContinuation { continuation in
>             nwConnection.receiveMessage { data, _, _, error in
>                 guard let data else {
> ```

Can there be data and error at the same time? Also, wouldn't checking for error first be more interesting since it could give us a hint of what's going on. As it is now we might never get to it if data is empty.
___
*[`ios/MullvadRustRuntime/TunnelObfuscator.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132#-OB-StwaAk5KTxt1lBQ_:-OB-StwaAk5KTxt1lBQa:b-jsiz26) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82d5634bdd1553883765b7108aa82f886b121b0c/ios/MullvadRustRuntime/TunnelObfuscator.swift#L14)):*
> ```Swift
> import Network
> 
> public enum TunnelObfuscationProtocol {
> ```

Not sure there's a good alternative for a name here, but it's somewhat confusing with both `TunnelObfuscationProtocol` and `TunnelObfuscatorProtocol`.
___
*[`ios/MullvadRustRuntime/TunnelObfuscator.swift` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132#-OB-TCoM2OufFvodyf0a:-OB-TCoM2OufFvodyf0b:b-e7g22a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82d5634bdd1553883765b7108aa82f886b121b0c/ios/MullvadRustRuntime/TunnelObfuscator.swift#L75)):*
> ```Swift
> 
>             let obfuscationProtocol = switch obfuscationProtocol {
>             case .udpOverTcp: TunnelObfuscatorProtocol(0)
> ```

This int param means very little on the Swift side. Can we use an enum with raw value or something else instead?


<!-- Sent from Reviewable.io -->

2024-11-06 14:49 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132)* status: all files reviewed, 6 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadRustRuntimeTests/UDPConnection.swift` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132#-OB-S2dv1fSwxJJvsDTB:-OB0w1OC78Htkq7E9ZjD:b-4tpi2j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82d5634bdd1553883765b7108aa82f886b121b0c/ios/MullvadRustRuntimeTests/UDPConnection.swift#L75)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Can there be data and error at the same time? Also, wouldn't checking for error first be more interesting since it could give us a hint of what's going on. As it is now we might never get to it if data is empty.
</blockquote></details>

Whilst it's technically valid to read a UDP datagram of size 0, in our case it's not a desired behaviour.
We can make sure to check for errors before `data` (or the lack thereof) though
___
*[`ios/MullvadRustRuntime/TunnelObfuscator.swift` line 14 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132#-OB-StwaAk5KTxt1lBQ_:-OB0wo4x0c5HiKMdgpp8:b-fluiin) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82d5634bdd1553883765b7108aa82f886b121b0c/ios/MullvadRustRuntime/TunnelObfuscator.swift#L14)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Not sure there's a good alternative for a name here, but it's somewhat confusing with both `TunnelObfuscationProtocol` and `TunnelObfuscatorProtocol`.
</blockquote></details>

Yes it's not great I agree, I'll think of something better.
___
*[`ios/MullvadRustRuntime/TunnelObfuscator.swift` line 75 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132#-OB-TCoM2OufFvodyf0a:-OB0trWD6aN9nGfMGCR_:bug23ow) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/82d5634bdd1553883765b7108aa82f886b121b0c/ios/MullvadRustRuntime/TunnelObfuscator.swift#L75)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This int param means very little on the Swift side. Can we use an enum with raw value or something else instead?
</blockquote></details>

Unfortunately, due to how [C enums are imported in Swift](https://github.com/swiftlang/swift/blob/main/docs/HowSwiftImportsCAPIs.md#enums) it's not straightforward to do so.

The other complication comes from the fact that the header file for FFI functions is automatically generated.
[We have ways around this](https://developer.apple.com/documentation/swift/grouping-related-objective-c-constants) but that would require further customisation of the automatically imported FFI header, which is a lot of work.

I would like to do that, but that would probably be a better candidate for a hack day.
For now, I think this is an acceptable tradeoff. 


<!-- Sent from Reviewable.io -->

2024-11-07 08:09 UTC, rablador reviewed
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-11-11 15:29 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-14 07:01 UTC, rablador approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-14 08:25 UTC, merged