Fix connectivity tests ios 873
mullvad/mullvadvpn-app pull request #7140
Opened 2024-11-07 08:57 UTC by buggmagnet

This PR fixes 3 tests that were constantly failing on the CI runner
- `testAPIConnectionViaBridges`
- `testAPIReachableWhenBlocked`
- `testAppStillFunctioningWhenAPIDown`

# How was it fixed ?

`testAPIConnectionViaBridges` Is skipped at the moment, the only shadowsocks bridge provided by the staging environment is declared as inactive, hence the app cannot use shadowsocks bridges to connect to the API.

`testAPIReachableWhenBlocked` This was a bug, we never updated the `TransportMonitor` to let API calls go through the packet tunnel when entering the blocked state. 

`testAppStillFunctioningWhenAPIDown` was failing because an accessibility element was put on the wrong item in API access methods. 

On top of that, since we added encrypted DNS proxy methods, we never added an encrypted DNS resolver for staging environments. This is now fixed.

2024-11-07 11:00 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140)* status: 0 of 15 files reviewed, 1 unresolved discussion

___
*[`mullvad-encrypted-dns-proxy/src/config_resolver.rs` line 65 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-OB5GyGjB0RtczzFgvrv:-OB5GyGjB0RtczzFgvrw:b-mkwr5y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9f47e5ce152775f26e7d60f3dbfa0a9b8163824b/mullvad-encrypted-dns-proxy/src/config_resolver.rs#L65)):*
> ```XML
> 
> pub async fn resolve_default_config(domain: &str) -> Result<Vec<config::ProxyConfig>, Error> {
>     // TODO: We should remove the default value here and just force the callers to provide a domain instead
> ```

Note to self: Remove this TODO


<!-- Sent from Reviewable.io -->

2024-11-07 13:00 UTC, MarkusPettersson98 requested changes
> Reviewed 4 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140)* status: 4 of 15 files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`mullvad-encrypted-dns-proxy/src/config_resolver.rs` line 64 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-OB5g57vDRrk1ZaB4NIn:-OB5g57vDRrk1ZaB4NIo:b-hz57o5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9f47e5ce152775f26e7d60f3dbfa0a9b8163824b/mullvad-encrypted-dns-proxy/src/config_resolver.rs#L64)):*
> ```XML
> }
> 
> pub async fn resolve_default_config(domain: &str) -> Result<Vec<config::ProxyConfig>, Error> {
> ```

It would be appreciated with a comment on what this function actually does. I know it wasn't there before, but imo it is even more important now when the function accepts arguments :pray: 



_Code quote:_
```XML
pub async fn resolve_default_config(domain: &str) -> Result<Vec<config::ProxyConfig>, Error> {
```
___
*[`mullvad-encrypted-dns-proxy/src/state.rs` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-OB5gN885HAAJjGaH5HY:-OB5gN885HAAJjGaH5HZ:b-gwfm70) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9f47e5ce152775f26e7d60f3dbfa0a9b8163824b/mullvad-encrypted-dns-proxy/src/state.rs#L62)):*
> ```XML
> 
>     /// Fetch a config, but error out only when no existing configuration was there.
>     pub async fn fetch_configs(&mut self, domain: &str) -> Result<(), FetchConfigError> {
> ```

:pick:
```rust
/// Fetch a config from [domain], but error out only when no existing configuration was there.
pub async fn fetch_configs(&mut self, domain: &str) -> Result<(), Fetc
```



_Code quote:_
```XML
    /// Fetch a config, but error out only when no existing configuration was there.
    pub async fn fetch_configs(&mut self, domain: &str) -> Result<(), FetchConfigError> {
```
___
*[`mullvad-ios/src/encrypted_dns_proxy.rs` line 92 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-OB5afOV8x7v0GSaIW8Z:-OB5afOV8x7v0GSaIW8_:b-tmuecp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9f47e5ce152775f26e7d60f3dbfa0a9b8163824b/mullvad-ios/src/encrypted_dns_proxy.rs#L92)):*
> ```XML
>         let c_str = CStr::from_ptr(domain_name);
>         String::from_utf8_lossy(c_str.to_bytes())
>     };
> ```

The scope of the `unsafe` block could be narrowed here. Consider changing this to
```rust
let domain = {
    let c_str = unsafe { CStr::from_ptr(domain_name) };
    String::from_utf8_lossy(c_str.to_bytes())
};
```
And while doing so, it would be good practice to provide a `SAFETY` comment when using `unsafe`. Consider adding a comment on what guarantees the caller needs to uphold in order for `encrypted_dns_proxy_init` to be safe!
```rust
/// Initializes a valid pointer to an instance of `EncryptedDnsProxyState`.
///
/// # Safety
///
/// * [domain_name] must not be non-null.
///
/// * [domain_name] pointer must be [valid](core::ptr#safety)
///
/// * The caller must ensure that the pointer to the [domain_name] string contains a nul terminator
/// at the end of the string.
#[no_mangle]
pub unsafe extern "C" fn encrypted_dns_proxy_init(
    domain_name: *const c_char,
) -> *mut EncryptedDnsProxyState {
    let domain = {
        // SAFETY: domain_name points to a valid region of memory and contains a nul terminator.
        let c_str = unsafe { CStr::from_ptr(domain_name) };
        String::from_utf8_lossy(c_str.to_bytes())
    };
  ..
}
```



_Suggestion:_
```XML
    let domain = {
        let c_str = unsafe { CStr::from_ptr(domain_name) };
        String::from_utf8_lossy(c_str.to_bytes())
    };
```


<!-- Sent from Reviewable.io -->

2024-11-11 09:06 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140)* status: 4 of 15 files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-encrypted-dns-proxy/src/config_resolver.rs` line 64 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-OB5g57vDRrk1ZaB4NIn:-OBPQaPG4n3XX1sPjZv4:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9f47e5ce152775f26e7d60f3dbfa0a9b8163824b/mullvad-encrypted-dns-proxy/src/config_resolver.rs#L64)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

It would be appreciated with a comment on what this function actually does. I know it wasn't there before, but imo it is even more important now when the function accepts arguments :pray:
</blockquote></details>

Done.
___
*[`mullvad-encrypted-dns-proxy/src/state.rs` line 62 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-OB5gN885HAAJjGaH5HY:-OBPRF92B-9oRDnE87yp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9f47e5ce152775f26e7d60f3dbfa0a9b8163824b/mullvad-encrypted-dns-proxy/src/state.rs#L62)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

:pick:
```rust
/// Fetch a config from [domain], but error out only when no existing configuration was there.
pub async fn fetch_configs(&mut self, domain: &str) -> Result<(), Fetc
```
</blockquote></details>

Done.
___
*[`mullvad-ios/src/encrypted_dns_proxy.rs` line 92 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-OB5afOV8x7v0GSaIW8Z:-OBPSJJX7utBhtjKQOVp:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9f47e5ce152775f26e7d60f3dbfa0a9b8163824b/mullvad-ios/src/encrypted_dns_proxy.rs#L92)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

The scope of the `unsafe` block could be narrowed here. Consider changing this to
```rust
let domain = {
    let c_str = unsafe { CStr::from_ptr(domain_name) };
    String::from_utf8_lossy(c_str.to_bytes())
};
```
And while doing so, it would be good practice to provide a `SAFETY` comment when using `unsafe`. Consider adding a comment on what guarantees the caller needs to uphold in order for `encrypted_dns_proxy_init` to be safe!
```rust
/// Initializes a valid pointer to an instance of `EncryptedDnsProxyState`.
///
/// # Safety
///
/// * [domain_name] must not be non-null.
///
/// * [domain_name] pointer must be [valid](core::ptr#safety)
///
/// * The caller must ensure that the pointer to the [domain_name] string contains a nul terminator
/// at the end of the string.
#[no_mangle]
pub unsafe extern "C" fn encrypted_dns_proxy_init(
    domain_name: *const c_char,
) -> *mut EncryptedDnsProxyState {
    let domain = {
        // SAFETY: domain_name points to a valid region of memory and contains a nul terminator.
        let c_str = unsafe { CStr::from_ptr(domain_name) };
        String::from_utf8_lossy(c_str.to_bytes())
    };
  ..
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-11 09:25 UTC, MarkusPettersson98 requested changes
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140)* status: 4 of 15 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`mullvad-ios/src/encrypted_dns_proxy.rs` line 92 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-OB5afOV8x7v0GSaIW8Z:-OBPX_hODo0Elyb9rp8S:b3lhjlb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9f47e5ce152775f26e7d60f3dbfa0a9b8163824b/mullvad-ios/src/encrypted_dns_proxy.rs#L92)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please add a `SAFETY` comment next to the `unsafe` block. See my original comment for some inspiration :wink:


<!-- Sent from Reviewable.io -->

2024-11-11 09:48 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140)* status: 1 of 15 files reviewed, 1 unresolved discussion (waiting on @MarkusPettersson98)

___
*[`mullvad-ios/src/encrypted_dns_proxy.rs` line 92 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-OB5afOV8x7v0GSaIW8Z:-OBPbVbiEmVhhnPepTB2:b-lp913w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9f47e5ce152775f26e7d60f3dbfa0a9b8163824b/mullvad-ios/src/encrypted_dns_proxy.rs#L92)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Please add a `SAFETY` comment next to the `unsafe` block. See my original comment for some inspiration :wink:
</blockquote></details>

Sorry, I misread your suggestion. It should be fixed now. 


<!-- Sent from Reviewable.io -->

2024-11-11 11:57 UTC, MarkusPettersson98 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-:-OBQ4X8h0ixAAXmCgXBf:bnfp4nl)* status: 4 of 15 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-15 07:56 UTC, MarkusPettersson98 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140)* status: 4 of 15 files reviewed, all discussions resolved

___
*[`mullvad-ios/src/encrypted_dns_proxy.rs` line 100 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-OBioImyEBKyLaRxpidM:-OBioImyEBKyLaRxpidN:by0sl1r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edffb4f94400a418e7abe60609ab68504c5c8d19/mullvad-ios/src/encrypted_dns_proxy.rs#L100)):*
> ```XML
>     // SAFETY: domain_name points to a valid region of memory and contains a nul terminator.
>     let domain = {
>         let c_str = unsafe { CStr::from_ptr(domain_name) };
> ```

:pick: The `SAFETY` comment could be adjacent to the `unsafe` block, i.e. move it to the next line :angel: 



_Code quote:_
```XML
    // SAFETY: domain_name points to a valid region of memory and contains a nul terminator.
    let domain = {
        let c_str = unsafe { CStr::from_ptr(domain_name) };
```


<!-- Sent from Reviewable.io -->

2024-11-15 08:03 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140)* status: 3 of 15 files reviewed, all discussions resolved (waiting on @MarkusPettersson98)

___
*[`mullvad-ios/src/encrypted_dns_proxy.rs` line 100 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-OBioImyEBKyLaRxpidM:-OBiqKFH6i-ldkHFPVpy:b-kw3mx1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edffb4f94400a418e7abe60609ab68504c5c8d19/mullvad-ios/src/encrypted_dns_proxy.rs#L100)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

:pick: The `SAFETY` comment could be adjacent to the `unsafe` block, i.e. move it to the next line :angel:
</blockquote></details>

Done ! :saluting_face: 


<!-- Sent from Reviewable.io -->

2024-11-15 08:21 UTC, MarkusPettersson98 reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140)* status: 4 of 15 files reviewed, all discussions resolved

___
*[`mullvad-ios/src/encrypted_dns_proxy.rs` line 100 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-OBioImyEBKyLaRxpidM:-OBiuRS27EQy7v0xfWxs:b-j1we20) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/edffb4f94400a418e7abe60609ab68504c5c8d19/mullvad-ios/src/encrypted_dns_proxy.rs#L100)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Done ! :saluting_face:
</blockquote></details>

:raised_hands: 


<!-- Sent from Reviewable.io -->

2024-11-18 13:11 UTC, acb-mv reviewed
> Reviewed 8 of 15 files at r1, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140)* status: 14 of 15 files reviewed, all discussions resolved

___
*[`ios/MullvadVPN/TransportMonitor/TransportMonitor.swift` line 47 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-OBzOMecDaGbAsNC6_JG:-OBzOMecDaGbAsNC6_JH:burj9vr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/7f8bc00cfd7e303173e341bc8a7c4350a3aa96d7/ios/MullvadVPN/TransportMonitor/TransportMonitor.swift#L47)):*
> ```Swift
>     }
> 
>     private func shouldByPassVPN(tunnel: any TunnelProtocol) -> Bool {
> ```

This isn't related to the work in this PR, but why is "ByPass" bicapitalised (as opposed to "Bypass")?


<!-- Sent from Reviewable.io -->

2024-11-19 09:29 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140)* status: 14 of 15 files reviewed, all discussions resolved

___
*[`ios/MullvadVPN/TransportMonitor/TransportMonitor.swift` line 47 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-OBzOMecDaGbAsNC6_JG:-OC2kDmgEhDqSBxyBl2l:b-9gs87z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/05e159d79e7e2e7c7d03edf8afabbff4982d1b2b/ios/MullvadVPN/TransportMonitor/TransportMonitor.swift#L47)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

This isn't related to the work in this PR, but why is "ByPass" bicapitalised (as opposed to "Bypass")?
</blockquote></details>

The person who wrote this wasn't a native english speaker. I'll issue a :ninja: fix for it, nice catch !


<!-- Sent from Reviewable.io -->

2024-11-26 10:04 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7140#-:-OCbvZ0136gG6e0dwCNs:bnfp4nl)* status: 14 of 15 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-26 10:14 UTC, merged