IOS-880 SwiftUI settings page for UDP/TCP obfuscation port
mullvad/mullvadvpn-app pull request #7143
Opened 2024-11-07 14:14 UTC by acb-mv

This implements a SwiftUI-based settings page for selecting the port for UDP->TCP WireGuard obfuscation. The page's ViewModel couples its state directly into the TunnelManager's Settings, bypassing the UIKit-based structure of ViewModel/DataSource objects. Additionally, there is an abstraction for a styled choice list and a a helper class for stateful previews.

2024-11-11 08:11 UTC, buggmagnet requested changes
![IMG\_BD4FC3AB6C2C-1.jpeg](https://files.reviewableusercontent.io/images/reviewable/129761703/3wO6zw6m9k-1qkWoNawrakIf/IMG_BD4FC3AB6C2C-1.jpeg)
We should find a way to remove this gap

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-:-OBP6R8O68wDM2RpkMF1:blvh34j)* status: 0 of 12 files reviewed, 11 unresolved discussions (waiting on @acb-mv)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBP237a74-Wjk05M315:-OBP237a74-Wjk05M316:bm1arvf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L25)):*
> ```Swift
>         case wireGuardObfuscation
>         case wireGuardObfuscationOption
>         case udpTcpObfuscationSettings
> ```

For the sake of consistency, let's keep the "udpOverTcp" name for definitions as well
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 323 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPGNPnE2YJkNeHs-gF:-OBPGNPnE2YJkNeHs-gG:byvxyks) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L323)):*
> ```Swift
>         case .udpTcpObfuscationSettings:
>             tableView.deselectRow(at: indexPath, animated: false)
>             delegate?.showUDPTCPObfuscationSettings()
> ```

This should be instead called in the WireGuard obfuscation cell's ellipsis action handler
___
*[`ios/MullvadVPN/View controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsViewModel.swift` line 34 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPF_1n4sK-LSvLQyWG:-OBPF_1n4sK-LSvLQyWH:bk698k5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsViewModel.swift#L34)):*
> ```Swift
>             tunnelManager: tunnelManager,
>             keyPath: \.udpOverTcpPort,
>             .automatic
> ```

This shouldn't have default values, but instead they should be consumed from the `TunnelSettings`
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPBg0S0Y0L5p5V5UQz:-OBPBg0S0Y0L5p5V5UR-:b-1k8b18) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L21)):*
> ```Swift
>     var value: Binding<T>
> 
>     func row(_ v: T) -> some View {
> ```

Let's avoid single letter names unless it's an index in a for loop. 
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPBwPlEjsRMaitexNj:-OBPBwPlEjsRMaitexNk:bs4nnw2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L25)):*
> ```Swift
>         return HStack {
>             Image("IconTick").opacity(isSelected ? 1.0 : 0.0)
>             Text(verbatim: "\(v)")
> ```

Should this be displayed without localization ?
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 39 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPG1ZS4--FBBdvF3Ro:-OBPG1ZS4--FBBdvF3Rp:b-au8pkb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L39)):*
> ```Swift
>         VStack(spacing: 0) {
>             HStack {
>                 Text(title)
> ```

The title should be bold according to Figma designs
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPBAHR0Zw2FNRYsVUl:-OBPBAHR0Zw2FNRYsVUm:b-1nrts5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L42)):*
> ```Swift
>                 Spacer()
>             }
>             .padding(16)
> ```

nit
Let's make sure we reuse constants we define in `UIMetrics` instead of using magic numbers as much as we can. 
We had a discussion in the past about how often did we want to have constants in lieu, and we came to the conclusion that if it's used once, it can be left as is, otherwise we should reuse paddings and offsets.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift` line 75 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBP1poo3L8HABUG6fAM:-OBP1poo3L8HABUG6fAN:b-4hmxgn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsCellFactory.swift#L75)):*
> ```Swift
>                 "UDP_TCP_OBFUSCATION_CELL_LABEL",
>                 tableName: "VPNSettings",
>                 value: "UDP/TCP Obfuscation",
> ```

The title should be "UDP-over-TCP", why was it changed ?
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift` line 133 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPGgeVCfGEftoiYvNR:-OBPGgeVCfGEftoiYvNS:b-64hx5k) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewController.swift#L133)):*
> ```Swift
>         let view = UDPTCPObfuscationSettingsView(viewModel: viewModel)
>         let vc = UIHostingController(rootView: view)
>         vc.title = "UDP TCP Obfuscation"
> ```

Let's make sure to reuse the "UDP-over-TCP" localized title here
___
*[`ios/MullvadVPN/View controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift` line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPFxmd8K0t4Zy8r1kD:-OBPFxmd8K0t4Zy8r1kE:b-20suh0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift#L17)):*
> ```Swift
>     var body: some View {
>         SingleChoiceList(
>             title: "Port",
> ```

Shouldn't that be a localised string ?
___
*[`ios/MullvadVPN/View controllers/Settings/Obfuscation/TunnelObfuscationSettingsWatchingObservableObject.swift` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBP7sO70xy_BhmfctoE:-OBP7sO70xy_BhmfctoF:basjqd3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/Obfuscation/TunnelObfuscationSettingsWatchingObservableObject.swift#L42)):*
> ```Swift
> 
>     private func updateValueFromSettings(_ settings: WireGuardObfuscationSettings) {
>         let newValue = settings
> ```

It looks like this function doesn't do anything, is it leftover code, or did we plan to add something later here ?


<!-- Sent from Reviewable.io -->

2024-11-11 09:18 UTC, rablador reviewed
The list content should be aligned left, so that title, section header and checkmarks all match. In the designs the title is too much on the left side though (we should keep Apple's default margins there, as we do in all other views).

![Simulator Screenshot - iPhone 16 Pro - 2024-11-11 at 09.37.07.png](https://files.reviewableusercontent.io/images/reviewable/1230209/6PHEvwAikmYEi6pqQi1lVphE/Simulator%20Screenshot%20-%20iPhone%2016%20Pro%20-%202024-11-11%20at%2009.37.07.png)

> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-:-OBPVd4z-48Hv238V7RS:bo7t26l)* status: 1 of 12 files reviewed, 11 unresolved discussions (waiting on @acb-mv)



<!-- Sent from Reviewable.io -->

2024-11-11 15:02 UTC, rablador requested changes
I just realised that we should not fix the gap, but rather there shouldn't be a new section for this feature. If you unfold `Wireguard Obfuscation` there are already rows with ellipsis buttons prepared for navigating to port selection.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-:-OBQjHKpDUXiTn8-sc-e:b-u7pa2t)* status: 1 of 12 files reviewed, 15 unresolved discussions (waiting on @acb-mv)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift` line 115 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQiIww24ow8do-nojJ:-OBQiIwx1vd8YC6akuzn:b-al021y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewController.swift#L115)):*
> ```Swift
>     }
> 
>     func showDetails(for: VPNSettingsDetailsButtonItem) {
> ```

We should remove this if it's not going to be used.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 331 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQabHFEzvttPFROwdT:-OBQabHGBOfhLDLcqQU_:b-v95juh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L331)):*
> ```Swift
>             selectObfuscationState(.udpOverTcp)
>             delegate?.didUpdateTunnelSettings(TunnelSettingsUpdate.obfuscation(obfuscationSettings))
>         // TODO: When ready, add implementation for selected obfuscation (navigate to new view etc).
> ```

Not sure When selecting 
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQcAqR2XoiJIWr6t77:-OBQcAqR2XoiJIWr6t78:b-jo5aub) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L21)):*
> ```Swift
>     var value: Binding<T>
> 
>     func row(_ v: T) -> some View {
> ```

I think this function should instead be a view that we can reuse.
___
*[`ios/MullvadVPN.xcodeproj/project.pbxproj` line 2597 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQhJyP0N7m809aneuk:-OBQhJyP0N7m809aneul:b-87dfjp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN.xcodeproj/project.pbxproj#L2597)):*
> ```
> 			isa = PBXGroup;
> 			children = (
> 				4422C0702CCFF6790001A385 /* UDPTCPObfuscationSettingsView.swift */,
> ```

Files should be ordered by name.


<!-- Sent from Reviewable.io -->

2024-11-11 15:27 UTC, rablador requested changes
> Reviewed 10 of 12 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: all files reviewed, 19 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 323 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPGNPnE2YJkNeHs-gF:-OBQnKv20Tj-LvE-y6iS:b-1yfla8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L323)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This should be instead called in the WireGuard obfuscation cell's ellipsis action handler
</blockquote></details>

Yes, see comment here: https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQiIww24ow8do-nojJ
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 331 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQabHFEzvttPFROwdT:-OBQkeLA352MioOLRcog:b7p0wk7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L331)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Not sure When selecting
</blockquote></details>

Sorry, nevermind this, I accidentally left an unfinished comment here!
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift` line 115 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQiIww24ow8do-nojJ:-OBQjxVqAJ4iyXKzMcGK:bsneb8x) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsViewController.swift#L115)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

We should remove this if it's not going to be used.
</blockquote></details>

My bad, we already have code that calls this function when the ellipsis buttons are clicked in the `Wireguard Obfuscation` cells. The code in `showUDPTCPObfuscationSettings() ` below should be moved up here.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSourceDelegate.swift` line 23 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQkKptETDvmY2WriBO:-OBQkKptETDvmY2WriBP:b-iaxc2v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSourceDelegate.swift#L23)):*
> ```Swift
>     func showDNSSettings()
>     func showIPOverrides()
>     func showUDPTCPObfuscationSettings()
> ```

Not necessary, `func showDetails(for: VPNSettingsDetailsButtonItem)` already handles this.
___
*[`ios/MullvadVPN/View controllers/Settings/Obfuscation/TunnelObfuscationSettingsWatchingObservableObject.swift` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQm6Zp2YSlMWA61GEv:-OBQm6Zp2YSlMWA61GEw:bhce3le) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/Obfuscation/TunnelObfuscationSettingsWatchingObservableObject.swift#L26)):*
> ```Swift
>             objectWillChange.send()
>             var obfuscationSettings = tunnelManager.settings.wireGuardObfuscation
>             obfuscationSettings[keyPath: keyPath] = newValue
> ```

When port is changed the tunnel should reconnect. Will this trigger a reconnection?
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 372 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQndzjBovhDJWiYI0_:-OBQndzjBovhDJWiYI0a:b7cipmy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e914beb13e7099162ece01cd534bd7e4c89e91d5/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L372)):*
> ```Swift
>             configureObfuscationHeader(view)
>             return view
>         case .wireGuardObfuscationPort:
> ```

This is the header of the foldable obfuscation section and should not be removed.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQmeVVDInLImND7O1f:-OBQmeVVDInLImND7O1g:b-v531ac) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L25)):*
> ```Swift
>         case wireGuardObfuscation
>         case wireGuardObfuscationOption
>         case udpTcpObfuscationSettings
> ```

No new identifier should be added here. `case wireGuardObfuscationOption` already handles this.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 71 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQl6PS0SgU5_MoGBw4:-OBQl6PS0SgU5_MoGBw5:b-pn18wm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L71)):*
> ```Swift
>         case wireGuardPorts
>         case wireGuardObfuscation
>         case udpTcpObfuscationSettings
> ```

No new section should be added here. `case wireGuardObfuscation` already handles this. However, the gaps need to be adjusted below that section.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 81 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQmsF23CtjuhsjZNsB:-OBQmsF23CtjuhsjZNsC:b-9uumjp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L81)):*
> ```Swift
>         case wireGuardPort(_ port: UInt16?)
>         case wireGuardCustomPort
>         case udpTcpObfuscationSettings
> ```

No new item should be added here. `case wireGuardObfuscation` already handles this.


<!-- Sent from Reviewable.io -->

2024-11-12 23:11 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: 2 of 12 files reviewed, 18 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/Settings/Obfuscation/TunnelObfuscationSettingsWatchingObservableObject.swift` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBP7sO70xy_BhmfctoE:-OBR0BzyDcHKMZhCXE4J:b-fpyadu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/Obfuscation/TunnelObfuscationSettingsWatchingObservableObject.swift#L42)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It looks like this function doesn't do anything, is it leftover code, or did we plan to add something later here ?
</blockquote></details>

Good catch. The logic had been implemented in the non-generalised version of the view model, though somehow didn't end up being copied over.
___
*[`ios/MullvadVPN/View controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift` line 17 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPFxmd8K0t4Zy8r1kD:-OBVqczS2l2Dps3VQqJ-:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift#L17)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Shouldn't that be a localised string ?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsViewModel.swift` line 34 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPF_1n4sK-LSvLQyWG:-OBVqf-UC81lgWVjFHDL:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsViewModel.swift#L34)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This shouldn't have default values, but instead they should be consumed from the `TunnelSettings`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQcAqR2XoiJIWr6t77:-OBR2m6YBcMgyOJiHkUu:b-3dulo5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L21)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I think this function should instead be a view that we can reuse.
</blockquote></details>

I will generalise this when I've written the Shadowsocks options (which require a more bespoke kind of list, having custom port options)
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPBg0S0Y0L5p5V5UQz:-OBVqgBl5fTqlXoskEe9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L21)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's avoid single letter names unless it's an index in a for loop.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPBwPlEjsRMaitexNj:-OBVqpnj0u0cfZ62p90K:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L25)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Should this be displayed without localization ?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 39 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPG1ZS4--FBBdvF3Ro:-OBVnt6S82QJN0F4fDCS:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L39)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

The title should be bold according to Figma designs
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift` line 75 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBP1poo3L8HABUG6fAM:-OBVnv587fS7CUsaVlGf:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsCellFactory.swift#L75)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

The title should be "UDP-over-TCP", why was it changed ?
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBP237a74-Wjk05M315:-OBVnw054O0KH9694dSW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L25)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

For the sake of consistency, let's keep the "udpOverTcp" name for definitions as well
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQmeVVDInLImND7O1f:-OBXaxbN3rnVL2bEXAE2:b-cf4eza) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L25)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

No new identifier should be added here. `case wireGuardObfuscationOption` already handles this.
</blockquote></details>

The WireGuard Obfuscation menu is still used for selecting the obfuscation method, with the new view being just settings for the UDP->TCP method, so we can't recycle the old item just yet.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 71 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQl6PS0SgU5_MoGBw4:-OBXbM3u99CI1uU-AfN5:b-fqo5op) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L71)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

No new section should be added here. `case wireGuardObfuscation` already handles this. However, the gaps need to be adjusted below that section.
</blockquote></details>

The wireGuardObfuscation section is still used for selecting the obfuscation method.
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 81 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQmsF23CtjuhsjZNsB:-OBXb_CHE9YdoS1qYl02:bvoego0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L81)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

No new item should be added here. `case wireGuardObfuscation` already handles this.
</blockquote></details>

The WireGuard Obfuscation menu is still used for selecting the obfuscation method, with the n [...]

2024-11-13 11:01 UTC, acb-mv commented
*[`ios/MullvadVPN/View controllers/Settings/Obfuscation/TunnelObfuscationSettingsWatchingObservableObject.swift` line 26 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQm6Zp2YSlMWA61GEv:-OB_AvH-4rraInkGvT0J:bd0chwb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/Obfuscation/TunnelObfuscationSettingsWatchingObservableObject.swift#L26)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

When port is changed the tunnel should reconnect. Will this trigger a reconnection?
</blockquote></details>

It does now...


<!-- Sent from Reviewable.io -->

2024-11-13 12:32 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: 2 of 12 files reviewed, 18 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 372 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQndzjBovhDJWiYI0_:-OB_Vbp5DSKXLfW1mHmv:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e914beb13e7099162ece01cd534bd7e4c89e91d5/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L372)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This is the header of the foldable obfuscation section and should not be removed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-13 13:52 UTC, rablador requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: 2 of 12 files reviewed, 18 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQmeVVDInLImND7O1f:-OB_lYsO4aI8YYm9dN1M:bwx6kc8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L25)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

The WireGuard Obfuscation menu is still used for selecting the obfuscation method, with the new view being just settings for the UDP->TCP method, so we can't recycle the old item just yet.
</blockquote></details>

The new items in the old menu have new ellipsis buttons that navigate to port settings.

![Simulator Screenshot - iPhone 16 Pro - 2024-11-13 at 14.46.20.png](https://files.reviewableusercontent.io/images/reviewable/1230209/z8_FkKxmwjPywBBA4-k6C1HH/Simulator%20Screenshot%20-%20iPhone%2016%20Pro%20-%202024-11-13%20at%2014.46.20.png)


<!-- Sent from Reviewable.io -->

2024-11-13 13:55 UTC, rablador requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: 2 of 12 files reviewed, 18 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift` line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBQmeVVDInLImND7O1f:-OB_nNDG9t5_A1q6HPyv:bgvnpdj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsDataSource.swift#L25)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

The new items in the old menu have new ellipsis buttons that navigate to port settings.

![Simulator Screenshot - iPhone 16 Pro - 2024-11-13 at 14.46.20.png](https://files.reviewableusercontent.io/images/reviewable/1230209/z8_FkKxmwjPywBBA4-k6C1HH/Simulator%20Screenshot%20-%20iPhone%2016%20Pro%20-%202024-11-13%20at%2014.46.20.png)
</blockquote></details>

The "UDP-over-TCP" port above will be removed once this feature is done (it's only there for legacy purposes of being able to select a port until your work with the new views is done).


<!-- Sent from Reviewable.io -->

2024-11-14 08:24 UTC, rablador reviewed
> Reviewed 8 of 10 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: all files reviewed, 13 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPBwPlEjsRMaitexNj:-OBdkOWi6MCGhptrs-KH:b2bkygm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L25)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nit: We should use the tablename params and such like in other places with localizations.
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 39 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPG1ZS4--FBBdvF3Ro:-OBdkbXR7RMG-RiZGUsn:b-86dle3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L39)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's should be semi-bold 🙂


<!-- Sent from Reviewable.io -->

2024-11-14 10:44 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: all files reviewed, 13 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPBwPlEjsRMaitexNj:-OBeGZeL-fPrn7kNkSnF:bf9021z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L25)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: We should use the tablename params and such like in other places with localizations.
</blockquote></details>

Which tablename should be used?
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 39 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPG1ZS4--FBBdvF3Ro:-OBeGUXp03MdsN1PGcB8:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L39)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It's should be semi-bold 🙂
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-14 11:07 UTC, rablador reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: all files reviewed, 13 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPBwPlEjsRMaitexNj:-OBeLHij1S3zIK71Lm-j:b-wx500t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L25)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Which tablename should be used?
</blockquote></details>

Something like this?



_Code snippet:_
```Swift
NSLocalizedString(
    "SINGLE_CHOICE_LIST_TITLE",
    tableName: "SingleChoiceList",
    value: "Text",
    comment: ""
)
```


<!-- Sent from Reviewable.io -->

2024-11-14 13:35 UTC, acb-mv commented
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPBwPlEjsRMaitexNj:-OBesAU3AX734Gp63zXW:bu9u7cj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L25)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Something like this?
</blockquote></details>

Though SingleChoiceList is not a screen in the app but a component which is composed into screens. It having a table of its own in localisation data doesn't make a lot of sense to me. In this case, shouldn't we move localisation upstream to the view that uses it?


<!-- Sent from Reviewable.io -->

2024-11-14 13:39 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: all files reviewed, 13 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPBwPlEjsRMaitexNj:-OBetVYG8MFHB6Zta2qp:bi0674w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L25)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Though SingleChoiceList is not a screen in the app but a component which is composed into screens. It having a table of its own in localisation data doesn't make a lot of sense to me. In this case, shouldn't we move localisation upstream to the view that uses it?
</blockquote></details>

Yeah, perhaps that's a better idea.


<!-- Sent from Reviewable.io -->

2024-11-14 14:26 UTC, acb-mv commented
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 25 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPBwPlEjsRMaitexNj:-OBf3IC16NedZdRSHKEr:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L25)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Yeah, perhaps that's a better idea.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-14 14:30 UTC, rablador reviewed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: all files reviewed, 13 unresolved discussions (waiting on @acb-mv and @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-11-15 08:57 UTC, rablador reviewed
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: all files reviewed, 11 unresolved discussions (waiting on @acb-mv and @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-11-15 11:32 UTC, rablador requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: all files reviewed, 15 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPBg0S0Y0L5p5V5UQz:-OBjSQEh5_hI_vtkJbaA:b-gfmxdb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L21)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's still abbreviated.
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 32 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBjSEY92TRwURxP_ixF:-OBjSEY92TRwURxP_ixG:b-v4k8le) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19c2b8ffaa2b9c457e966f0e8388a67ba2b6ef99/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L32)):*
> ```Swift
>         let isSelected = value.wrappedValue == v
>         return HStack {
>             Image("IconTick").opacity(isSelected ? 1.0 : 0.0)
> ```

We should use the `.iconTick` image resource here instead.
Also, there should be some spacing between tick and text, defined in `UIMetrics.SettingsCell.selectableSettingsCellLeftViewSpacing`.
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 36 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBjSee12jIAi-f0uKEs:-OBjSee12jIAi-f0uKEt:b-tta3pl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19c2b8ffaa2b9c457e966f0e8388a67ba2b6ef99/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L36)):*
> ```Swift
>             Spacer()
>         }
>         .padding(16)
> ```

Default padding is specified in `UIMetrics.SettingsCell.layoutMargins`.
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 37 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBj_SUQ1wQ6SIFVpX73:-OBj_SUQ1wQ6SIFVpX74:b142oze) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19c2b8ffaa2b9c457e966f0e8388a67ba2b6ef99/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L37)):*
> ```Swift
>         }
>         .padding(16)
>         .background(isSelected ? Color(UIColor.Cell.Background.selected) : Color(UIColor.Cell.Background.normal))
> ```

Unselected color should be `UIColor.Cell.Background.indentationLevelOne`.
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 45 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBjRVN6DHZ9HkkoHdHe:-OBjRVN6DHZ9HkkoHdHf:benqswb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19c2b8ffaa2b9c457e966f0e8388a67ba2b6ef99/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L45)):*
> ```Swift
> 
>     var body: some View {
>         VStack(spacing: 0) {
> ```

There should be a separator between each row. It's defined in `UIMetrics.TableView.separatorHeight`.
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 46 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBjVgOy4XSpJzt6bXjt:-OBjVgOy4XSpJzt6bXju:b-7eho7j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19c2b8ffaa2b9c457e966f0e8388a67ba2b6ef99/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L46)):*
> ```Swift
>     var body: some View {
>         VStack(spacing: 0) {
>             HStack {
> ```

This header should have bg color `UIColor.Cell.Background.normal`.


<!-- Sent from Reviewable.io -->

2024-11-15 11:35 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: all files reviewed, 16 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift` line 22 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBjahpk9W9KRXdcwmgM:-OBjahpk9W9KRXdcwmgN:bv555bx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19c2b8ffaa2b9c457e966f0e8388a67ba2b6ef99/ios/MullvadVPN/View%20controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift#L22)):*
> ```Swift
>             comment: ""
>         )
>         SingleChoiceList(
> ```

Nit: Should we wrap this whole view into a scrollview to make it general for future use cases too?


<!-- Sent from Reviewable.io -->

2024-11-15 12:25 UTC, buggmagnet reviewed
It looks like the selection in the subview isn't being honored in the UI.
Is there a way for the `VPNSettingsViewController` to be informed that it needs to reload its data source when things change under the hood ? Or should we just make it reload its data source on re-appears ?
[RPReplay\_Final1731673220.mov](https://files.reviewableusercontent.io/images/reviewable/129761703/-j8ChLVuOhOd-NLQRP2Klbe7/RPReplay_Final1731673220.mov)

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-:-OBjlUqTCa38kRAUs5gi:bolvw7w)* status: all files reviewed, 15 unresolved discussions (waiting on @acb-mv)



<!-- Sent from Reviewable.io -->

2024-11-15 12:29 UTC, rablador reviewed
There are two things going on with the cells not updating text:

1.  The tunnel observer was never added to tunnel manager, so no updates were coming through. It's been like that forever... 🙈
2.  The data source should not be rebuilt on every settings update, since it would mean losing eg. expanded state. Instead we can just reload the contents.

I have made the changes in a branch from your branch to make it easy to see the changes: `IOS-880-obfuscation-settings-page-jon`

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-:-OBjn7Br0iUmB8TGovdO:b81ix77)* status: all files reviewed, 15 unresolved discussions (waiting on @acb-mv and @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-11-15 13:51 UTC, acb-mv commented
Merged into this branch; thanks





<!-- Sent from Reviewable.io -->

2024-11-15 14:04 UTC, rablador reviewed
👍

> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-:-OBk7seA8wDLPItysHD9:b44tpx)* status: all files reviewed, 15 unresolved discussions (waiting on @acb-mv and @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-11-15 14:27 UTC, acb-mv reviewed
> Dismissed @buggmagnet from a discussion.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: all files reviewed, 14 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift` line 22 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBjahpk9W9KRXdcwmgM:-OBk4u7CCTmUXnmZVzo2:btycwgl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19c2b8ffaa2b9c457e966f0e8388a67ba2b6ef99/ios/MullvadVPN/View%20controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift#L22)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Nit: Should we wrap this whole view into a scrollview to make it general for future use cases too?
</blockquote></details>

Depends on how many items we're expecting. I don't think this use case needs it, and we could do so on the calling side to keep concerns separated.
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPBg0S0Y0L5p5V5UQz:-OBk5HHd3tAJebT6aDEp:b9dpdo1) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L21)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

It's still abbreviated.
</blockquote></details>

Not in the most recent version in the branch (where this line is also at line 29)
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 36 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBjSee12jIAi-f0uKEs:-OBkAcrL4nmbDJriE9-6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19c2b8ffaa2b9c457e966f0e8388a67ba2b6ef99/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L36)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Default padding is specified in `UIMetrics.SettingsCell.layoutMargins`.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 37 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBj_SUQ1wQ6SIFVpX73:-OBkAlbg0B14p7FmBpun:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19c2b8ffaa2b9c457e966f0e8388a67ba2b6ef99/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L37)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Unselected color should be `UIColor.Cell.Background.indentationLevelOne`.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 45 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBjRVN6DHZ9HkkoHdHe:-OBkAu6r7xr-qLd4N033:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19c2b8ffaa2b9c457e966f0e8388a67ba2b6ef99/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L45)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

There should be a separator between each row. It's defined in `UIMetrics.TableView.separatorHeight`.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 46 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBjVgOy4XSpJzt6bXjt:-OBkB3r66eGz7y_eFCao:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19c2b8ffaa2b9c457e966f0e8388a67ba2b6ef99/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L46)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This header should have bg color `UIColor.Cell.Background.normal`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-15 14:27 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: 12 of 13 files reviewed, 14 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 32 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBjSEY92TRwURxP_ixF:-OBkDF5K0FGQVcKG0GjF:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/19c2b8ffaa2b9c457e966f0e8388a67ba2b6ef99/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L32)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

We should use the `.iconTick` image resource here instead.
Also, there should be some spacing between tick and text, defined in `UIMetrics.SettingsCell.selectableSettingsCellLeftViewSpacing`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-18 10:05 UTC, rablador requested changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: all files reviewed, 10 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPBg0S0Y0L5p5V5UQz:-OByaWSe9NP_TPICO_xr:bv0nd64) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L21)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Not in the most recent version in the branch (where this line is also at line 29)
</blockquote></details>

I checked out the branch, but I still only see `v`. 🤷‍♂️
___
*[`ios/MullvadVPN/View controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift` line 22 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OByiq5PAVnhXSZ_rgJ2:-OByiq5PAVnhXSZ_rgJ3:b-gc3wej) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3b33c1dc123b5450b401f0173192137abce37ff4/ios/MullvadVPN/View%20controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift#L22)):*
> ```Swift
>             comment: ""
>         )
>         SingleChoiceList(
> ```

This whole view should have a padding of 24 to the large page title so that the content is consistent with other pages/views with large titles.
___
*[`ios/MullvadVPN/View controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift` line 37 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OByhAmF-TAdtqqfZH_w:-OByhAmF-TAdtqqfZH_x:b3o5oam) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3b33c1dc123b5450b401f0173192137abce37ff4/ios/MullvadVPN/View%20controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift#L37)):*
> ```Swift
> 
> #Preview {
>     var model = MockUDPTCPObfuscationSettingsViewModel(udpTcpPort: .port5001)
> ```

Should be `let`.


<!-- Sent from Reviewable.io -->

2024-11-18 10:06 UTC, rablador reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: all files reviewed, 10 unresolved discussions (waiting on @acb-mv and @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-11-18 10:17 UTC, pinkisemils commented
This needs a rebase on top of the latest `main`.

2024-11-18 10:26 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: all files reviewed, 10 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift` line 22 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OByiq5PAVnhXSZ_rgJ2:-OBynhQYCjD33Rd0UHwH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3b33c1dc123b5450b401f0173192137abce37ff4/ios/MullvadVPN/View%20controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift#L22)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This whole view should have a padding of 24 to the large page title so that the content is consistent with other pages/views with large titles.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift` line 37 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OByhAmF-TAdtqqfZH_w:-OBykMhJ3En12DjYR6Ea:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3b33c1dc123b5450b401f0173192137abce37ff4/ios/MullvadVPN/View%20controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift#L37)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Should be `let`.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143#-OBPBg0S0Y0L5p5V5UQz:-OBykT_p29wI5zpaS3YC:b-cunspw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e5a82130278bdb1ac29cd2ad87b0f4987fd2d2d7/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L21)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I checked out the branch, but I still only see `v`. 🤷‍♂️
</blockquote></details>

Oh, you mean the variable name,  not the type name? Fixed.


<!-- Sent from Reviewable.io -->

2024-11-18 10:42 UTC, rablador approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: all files reviewed, 8 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-11-18 10:49 UTC, rablador approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)* status: all files reviewed, 8 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-11-18 10:50 UTC, merged