Implement multihop support for Android in daemon
mullvad/mullvadvpn-app pull request #7168
Opened 2024-11-12 14:27 UTC by kl

This PR adds multihop support to the daemon for Android.

2024-11-13 09:02 UTC, dlon requested changes
> Reviewed 5 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: 5 of 13 files reviewed, 4 unresolved discussions (waiting on @kl)

___
*[`wireguard-go-rs/src/lib.rs` line 108 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBW6bJi6Cc8UBjuobQ1:-OBW6bJi6Cc8UBjuobQ2:bb7462z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/wireguard-go-rs/src/lib.rs#L108)):*
> ```XML
>     }
> 
>     /// TODO: Document
> ```

TODO
___
*[`wireguard-go-rs/libwg/libwg_android.go` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBW7YUf-IaQhAA_7McR:-OBW7YUf-IaQhAA_7McS:bb7462z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/wireguard-go-rs/libwg/libwg_android.go#L35)):*
> ```Go
> type LogContext = C.uint64_t
> 
> // TODO: Document
> ```

TODO
___
*[`talpid-wireguard/src/ephemeral.rs` line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBW6035DkechgjPgWLv:-OBW6035DkechgjPgWLw:bwip1v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/ephemeral.rs#L101)):*
> ```XML
>     let close_obfs_sender = close_obfs_sender.clone();
> 
>     // NOTE: this might be the entry?
> ```

This is only true when the exit is also the entry, so we can remove `?`
___
*[`talpid-wireguard/src/ephemeral.rs` line 165 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBW5v9Y6yvh3Lw-AH3e:-OBW5v9Y6yvh3Lw-AH3f:b-8dl4aj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/ephemeral.rs#L165)):*
> ```XML
>     .await?;
> 
>     log::info!("Config: {config:#?}");
> ```

Was this used for debugging?


<!-- Sent from Reviewable.io -->

2024-11-13 09:44 UTC, Pururun requested changes
> Reviewed 8 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: all files reviewed, 12 unresolved discussions (waiting on @kl)

___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 139 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBZu5zg8ebriXZqY9rp:-OBZu5zg8ebriXZqY9rq:b-imzyxa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/wireguard_go/mod.rs#L139)):*
> ```XML
> }
> 
> // TODO: Does this need to be pub?
> ```

Does it?
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 146 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBZrhGHDVd5Ky0daCiX:-OBZrhGHDVd5Ky0daCiY:b-878eyv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/wireguard_go/mod.rs#L146)):*
> ```XML
>     // live long enough and get closed when the tunnel is stopped
>     _tunnel_device: Tun,
>     // HACK: Don't use this. Only sometimes. ;-)
> ```

Hack?
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 195 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBZrm7j0SRpLSq3l6t1:-OBZrm7j0SRpLSq3l6t2:b-epxhox) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/wireguard_go/mod.rs#L195)):*
> ```XML
> }
> 
> // TODO: move into impl of Config
> ```

Should we do this now or later?
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 203 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBZrp6k9mMhq1xmtjQg:-OBZrp6k9mMhq1xmtjQh:b-epxhox) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/wireguard_go/mod.rs#L203)):*
> ```XML
> }
> 
> // TODO: move into impl of Config
> ```

Should we do this now or later?
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 211 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBZrpac7OskGH_jd3uR:-OBZrpac7OskGH_jd3uS:b-epxhox) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/wireguard_go/mod.rs#L211)):*
> ```XML
> }
> 
> // TODO: move into impl of Config
> ```

Should we do this now or later?
___
*[`talpid-wireguard/src/lib.rs` line 57 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBZrJUw6BpSyOoI3w4y:-OBZrJUw6BpSyOoI3w4z:btq3uza) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/lib.rs#L57)):*
> ```XML
> use self::wireguard_go::WgGoTunnel;
> 
> // TODO: Document why we have a type alias !
> ```

Fix TODO
___
*[`talpid-wireguard/src/lib.rs` line 970 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBZrXoC394T9MiVtXEd:-OBZrXoDAqr4G64chkxP:bxxzg0f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/lib.rs#L970)):*
> ```XML
>     }
> 
>     // TODO: Remove?
> ```

Decide on if it should be removed?
___
*[`talpid-wireguard/src/ephemeral.rs` line 67 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBZr4Pf1jdc0vO07sG6:-OBZr4Pf1jdc0vO07sG7:b-i75tzz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c83883562ca44b88c08fcf675c2058ea71c7f199/talpid-wireguard/src/ephemeral.rs#L67)):*
> ```XML
> }
> 
> #[cfg(not(windows))]
> ```

Should this really be removed?


<!-- Sent from Reviewable.io -->

2024-11-13 10:00 UTC, Pururun reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: all files reviewed, 9 unresolved discussions (waiting on @dlon and @kl)

___
*[`talpid-wireguard/src/ephemeral.rs` line 101 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBW6035DkechgjPgWLv:-OBZwJCY4lbNTXmiDdpG:ba3dfob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/ephemeral.rs#L101)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is only true when the exit is also the entry, so we can remove `?`
</blockquote></details>

Removed
___
*[`talpid-wireguard/src/ephemeral.rs` line 165 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBW5v9Y6yvh3Lw-AH3e:-OBZwOpj5aJINKSXIUI3:ba3dfob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/ephemeral.rs#L165)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Was this used for debugging?
</blockquote></details>

Removed
___
*[`wireguard-go-rs/libwg/libwg_android.go` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBW7YUf-IaQhAA_7McR:-OBZwx7C-nganHfI2hUX:ba3dfob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/wireguard-go-rs/libwg/libwg_android.go#L35)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

Removed
___
*[`wireguard-go-rs/src/lib.rs` line 108 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBW6bJi6Cc8UBjuobQ1:-OBZxcTcBT0C24lBFZ5x:b-bu91xm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/wireguard-go-rs/src/lib.rs#L108)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

Updated


<!-- Sent from Reviewable.io -->

2024-11-13 10:23 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: 10 of 13 files reviewed, 4 unresolved discussions (waiting on @dlon and @kl)

___
*[`talpid-wireguard/src/lib.rs` line 57 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBZrJUw6BpSyOoI3w4y:-OBZyASC9PVU_ZJoyeh7:b-bu91xm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/lib.rs#L57)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Fix TODO
</blockquote></details>

Updated
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 139 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBZu5zg8ebriXZqY9rp:-OB_-3zK5h9QcXqFOlfO:b-epuorh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/wireguard_go/mod.rs#L139)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Does it?
</blockquote></details>

Changed to `pub(crate)`
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 195 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBZrm7j0SRpLSq3l6t1:-OB_216K3GLTh1hfHliy:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/wireguard_go/mod.rs#L195)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should we do this now or later?
</blockquote></details>

Done
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 203 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBZrp6k9mMhq1xmtjQg:-OB_220D5tTo6Vulk2eb:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/wireguard_go/mod.rs#L203)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should we do this now or later?
</blockquote></details>

Done
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 211 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBZrpac7OskGH_jd3uR:-OB_22mpDG2tiv1bmRav:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/wireguard_go/mod.rs#L211)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Should we do this now or later?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-11-13 10:28 UTC, Pururun requested changes
> Reviewed 1 of 3 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: 9 of 13 files reviewed, 5 unresolved discussions (waiting on @dlon and @kl)

___
*[`talpid-wireguard/src/lib.rs` line 593 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OB_3BXq92wcxrBgvbtZ:-OB_3BXq92wcxrBgvbt_:b-44ajp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4cc23e5c471fceb91d59e8d767f7c0289e4289c8/talpid-wireguard/src/lib.rs#L593)):*
> ```XML
>     /// Used to block traffic to other destinations while connecting on Android.
>     ///
>     /// TODO: This might need some patchin' now when multihop is a thing.
> ```

Check this


<!-- Sent from Reviewable.io -->

2024-11-13 14:41 UTC, Pururun reviewed
> Reviewed 2 of 3 files at r3, 1 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon and @kl)



<!-- Sent from Reviewable.io -->

2024-11-13 15:02 UTC, dlon reviewed
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: all files reviewed, 2 unresolved discussions (waiting on @kl)

___
*[`wireguard-go-rs/libwg/tunnelcontainer/tunnelcontainer.go` line 21 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBa1UYC-aPechxJXXI3:-OBa1UYC-aPechxJXXI4:bmo3nbv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/wireguard-go-rs/libwg/tunnelcontainer/tunnelcontainer.go#L21)):*
> ```Go
> 	Uapi   net.Listener
> 	Logger *device.Logger
> 	EntryDevice *device.Device
> ```

Does this need to be used in `libwg_daita.go`? Since DAITA should only be enabled between the client and entry peer.


<!-- Sent from Reviewable.io -->

2024-11-13 16:26 UTC, dlon requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: all files reviewed, 9 unresolved discussions (waiting on @kl)

___
*[`talpid-wireguard/src/config.rs` line 201 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaD-rm8ML9zwGClwSI:-OBaD-rm8ML9zwGClwSJ:bsxjpv8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/config.rs#L201)):*
> ```XML
>     pub(crate) fn exit_config(&self) -> Option<Config> {
>         let mut exit_config = self.clone();
>         exit_config.entry_peer = self.exit_peer.clone()?;
> ```

There are probably cleaner ways to do this. The current `to_userspace_format` method uses the exit peer if it is set, or else the entry config.

Could we maybe add something like a `entry_to_userspace_format` method?

Alternatively, a new struct that contains a single peer config (which will be set to either entry or exit, plus the private key) and a `to_userspace_format` method.
___
*[`talpid-wireguard/src/config.rs` line 211 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBa7Mzi2Brem1Kb3wrv:-OBa7Mzi2Brem1Kb3wrw:b9du907) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/config.rs#L211)):*
> ```XML
>     }
> 
>     pub(crate) fn private_ip(&self) -> CString {
> ```

`first_ipv4_tun_addr`? Though I kind of think we should just do this directly at the callsite, since it is so specific.
___
*[`talpid-wireguard/src/config.rs` line 215 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaAPhECdN40fWwOuUk:-OBaAPhECdN40fWwOuUl:b-k7306a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/config.rs#L215)):*
> ```XML
>             CString::new(ip.to_string()).unwrap()
>         } else {
>             CString::default()
> ```

This should probably return `None` or an `Err` rather than default to an empty string.
___
*[`talpid-wireguard/src/ephemeral.rs` line 207 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaIFfyCDs34yxTKGY5:-OBaIFfyCDs34yxTKGY6:boutvng) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/ephemeral.rs#L207)):*
> ```XML
>     let tunnel = lock.take().expect("tunnel was None");
> 
>     let new_tunnel = tunnel.better_set_config(&config).unwrap();
> ```

Is it wise to unwrap here? It doesn't seem like wg-go is guaranteed to not fail.
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 139 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBa2ZVu3b1KrLHsUSNz:-OBa2ZVu3b1KrLHsUSO-:b-bkvkvq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/wireguard_go/mod.rs#L139)):*
> ```XML
> }
> 
> // TODO: Does this need to be pub?
> ```

I don't think it needs to be pub. But you could remove it and check if it compiles.
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 148 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaIp3qDHSc07BGawEe:-OBaIp3qDHSc07BGawEf:b956iod) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/wireguard_go/mod.rs#L148)):*
> ```XML
>     // HACK: Don't use this. Only sometimes. ;-)
>     #[cfg(target_os = "android")]
>     _log_path: Option<PathBuf>,
> ```

This should not be prepended with `_`, I think? Since it is actually used
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 340 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaJlxr953wwTx2pK3d:-OBaJlxr953wwTx2pK3e:bi89st6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/wireguard_go/mod.rs#L340)):*
> ```XML
> 
>         // multihop
>         let exit_config = exit_config.unwrap();
> ```

I think it might be better to return an error here, unless we can make it impossible to call the function without an exit peer config.


<!-- Sent from Reviewable.io -->

2024-11-13 16:30 UTC, dlon requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: all files reviewed, 12 unresolved discussions (waiting on @kl)

___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 103 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaLvvCBx4D5ZjgWdbM:-OBaLvvCBx4D5ZjgWdbN:bty0j5h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/wireguard_go/mod.rs#L103)):*
> ```XML
>         match self {
>             WgGoTunnel::Multihop(state) if !config.is_multihop() => {
>                 // Important!
> ```

Could the comment at least explain why it's important?
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 104 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaLQBq8k1iC8OGZOOF:-OBaLQBq8k1iC8OGZOOG:bts57xz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/wireguard_go/mod.rs#L104)):*
> ```XML
>             WgGoTunnel::Multihop(state) if !config.is_multihop() => {
>                 // Important!
>                 state.stop().unwrap();
> ```

Should we just return (`?`) rather than unwrap here?
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 114 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaLUfr4wJIKm6bDuKv:-OBaLUfr4wJIKm6bDuKw:bts57xz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/wireguard_go/mod.rs#L114)):*
> ```XML
>             }
>             WgGoTunnel::Singlehop(state) if config.is_multihop() => {
>                 state.stop().unwrap();
> ```

Should we just return (`?`) rather than unwrap here?


<!-- Sent from Reviewable.io -->

2024-11-14 12:01 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: 10 of 13 files reviewed, 8 unresolved discussions (waiting on @dlon and @Pururun)

___
*[`talpid-wireguard/src/config.rs` line 211 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBa7Mzi2Brem1Kb3wrv:-OBeKpj7C4aGrksVDGlo:b-84jhwq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/config.rs#L211)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

`first_ipv4_tun_addr`? Though I kind of think we should just do this directly at the callsite, since it is so specific.
</blockquote></details>

Moved to call site
___
*[`talpid-wireguard/src/config.rs` line 215 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaAPhECdN40fWwOuUk:-OBeL-HI5uif6lF7AcO_:b-jxjphv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/config.rs#L215)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This should probably return `None` or an `Err` rather than default to an empty string.
</blockquote></details>

Fixed at call site
___
*[`talpid-wireguard/src/ephemeral.rs` line 207 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaIFfyCDs34yxTKGY5:-OBe5sml0XrUnmiFf4xA:bees0qt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/ephemeral.rs#L207)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Is it wise to unwrap here? It doesn't seem like wg-go is guaranteed to not fail.
</blockquote></details>

Change to returning result instead of unwrapping
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 103 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaLvvCBx4D5ZjgWdbM:-OBe6TfL-_M5_goiAAcC:ba3dfob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/wireguard_go/mod.rs#L103)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Could the comment at least explain why it's important?
</blockquote></details>

Removed
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 104 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaLQBq8k1iC8OGZOOF:-OBe6dtGE76TApMe6SEm:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/wireguard_go/mod.rs#L104)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should we just return (`?`) rather than unwrap here?
</blockquote></details>

Done
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 114 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaLUfr4wJIKm6bDuKv:-OBe6g_79oKRSkj_QtvT:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/wireguard_go/mod.rs#L114)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should we just return (`?`) rather than unwrap here?
</blockquote></details>

Done
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 340 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaJlxr953wwTx2pK3d:-OBeKQsx9YuhBeL43wHT:b-r7qen2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/wireguard_go/mod.rs#L340)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I think it might be better to return an error here, unless we can make it impossible to call the function without an exit peer config.
</blockquote></details>

Made exit peer config required argument


<!-- Sent from Reviewable.io -->

2024-11-14 12:04 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: 10 of 13 files reviewed, 8 unresolved discussions (waiting on @dlon and @Pururun)

___
*[`talpid-wireguard/src/config.rs` line 201 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaD-rm8ML9zwGClwSI:-OBeYKNMEiOWnEhGB6hV:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/config.rs#L201)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

There are probably cleaner ways to do this. The current `to_userspace_format` method uses the exit peer if it is set, or else the entry config.

Could we maybe add something like a `entry_to_userspace_format` method?

Alternatively, a new struct that contains a single peer config (which will be set to either entry or exit, plus the private key) and a `to_userspace_format` method.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-14 12:26 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: 10 of 14 files reviewed, 8 unresolved discussions (waiting on @dlon, @kl, and @Pururun)

___
*[`wireguard-go-rs/libwg/tunnelcontainer/tunnelcontainer.go` line 21 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBectN-0UZox2H1MysI:-OBectN05pAKQflzg9_f:b9cwhy4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/989e4b51ff05371c6d3746b6df10623382746743/wireguard-go-rs/libwg/tunnelcontainer/tunnelcontainer.go#L21)):*
> ```Go
> 	Uapi   net.Listener
> 	Logger *device.Logger
> 	EntryDevice *device.Device
> ```

:pick: Please group `Device` and `EntryDevice`, thanks :angel: 



_Code quote:_
```Go
	Device *device.Device
	Uapi   net.Listener
	Logger *device.Logger
	EntryDevice *device.Device
```


<!-- Sent from Reviewable.io -->

2024-11-14 13:13 UTC, dlon requested changes
> Reviewed 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: all files reviewed, 6 unresolved discussions (waiting on @kl)

___
*[`talpid-wireguard/src/ephemeral.rs` line 207 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaIFfyCDs34yxTKGY5:-OBekjWo73gIKOPEYCc5:bqv2a33) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/ephemeral.rs#L207)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

Change to returning result instead of unwrapping
</blockquote></details>

It's still unwrapping here.
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 139 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBa2ZVu3b1KrLHsUSNz:-OBemp7539D2K9DQOfBS:b-gkip73) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/wireguard_go/mod.rs#L139)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

We changed it from pub to (pub)crate but forgot to remove the TODO.
</blockquote></details>

Does it need to be `pub` anything?
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 429 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBel7I-BYTbolUGdBID:-OBel7I06HzjJxwQpsYc:bwi9n4a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/989e4b51ff05371c6d3746b6df10623382746743/talpid-wireguard/src/wireguard_go/mod.rs#L429)):*
> ```XML
>         let config = &self.as_state().config;
> 
>         let peer_public_key = match config.exit_peer.as_ref() {
> ```

This is incorrect. This should use the entry peer, always.
___
*[`talpid-wireguard/src/lib.rs` line 784 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBemGkICwtYZXvBfteq:-OBemGkICwtYZXvBfter:bsjkz4o) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/989e4b51ff05371c6d3746b6df10623382746743/talpid-wireguard/src/lib.rs#L784)):*
> ```XML
>                 #[allow(clippy::needless_borrow)]
>                 &config,
>                 config.exit_peer.clone().unwrap(),
> ```

We could do something like this instead of relying on `is_multihop` to determine that `exit_peer` is set:

```
let tunnel = if let Some(exit_peer) = &config.exit_peer = {

    ...
    &config,
    exit_peer,
```


<!-- Sent from Reviewable.io -->

2024-11-15 07:32 UTC, Pururun reviewed
> Reviewed 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @dlon and @kl)

___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 139 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBa2ZVu3b1KrLHsUSNz:-OBiiYwE0YeGLH0ce8bH:b-68yhhm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/wireguard_go/mod.rs#L139)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Does it need to be `pub` anything?
</blockquote></details>

Yes, because otherwise you get a warning about different visibility
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 148 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaIp3qDHSc07BGawEe:-OBiif4S99oKf5QlhTa3:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/wireguard_go/mod.rs#L148)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This should not be prepended with `_`, I think? Since it is actually used
</blockquote></details>

Done
___
*[`talpid-wireguard/src/wireguard_go/mod.rs` line 429 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBel7I-BYTbolUGdBID:-OBiihELDRlPQTV6-nhk:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/989e4b51ff05371c6d3746b6df10623382746743/talpid-wireguard/src/wireguard_go/mod.rs#L429)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is incorrect. This should use the entry peer, always.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-11-15 08:18 UTC, Pururun reviewed
> Reviewed 2 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon and @kl)



<!-- Sent from Reviewable.io -->

2024-11-15 08:28 UTC, dlon requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: all files reviewed, 3 unresolved discussions (waiting on @kl)

___
*[`talpid-wireguard/src/config.rs` line 201 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaD-rm8ML9zwGClwSI:-OBiu9RqDNUiVpSeLgIB:biojefx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/config.rs#L201)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This would be more readable if instead of taking in both `entry_peer` and `exit_peer`, `userspace_format` only received a single `&PeerConfig`. You could then move this part to `Config::to_userspace_format`:

```
exit_peer
        .as_ref()
        .into_iter()
        .chain(std::iter::once(&entry_peer))
```


<!-- Sent from Reviewable.io -->

2024-11-15 08:32 UTC, dlon requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: all files reviewed, 3 unresolved discussions (waiting on @kl)

___
*[`talpid-wireguard/src/config.rs` line 201 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaD-rm8ML9zwGClwSI:-OBiwAR19ENOnESJYGOk:b4ei63s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/config.rs#L201)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This would be more readable if instead of taking in both `entry_peer` and `exit_peer`, `userspace_format` only received a single `&PeerConfig`. You could then move this part to `Config::to_userspace_format`:

```
exit_peer
        .as_ref()
        .into_iter()
        .chain(std::iter::once(&entry_peer))
```
</blockquote></details>

Ah, no, because it's an iterator. This is okay as is, but you could probably take `peers: impl Iterator<Item = &wireguard::PeerConfig>`. In `Config`, simply pass `self.peers()`. In the other place, `std::iter::once(&entry_peer)` and `std::iter::once(&exit_peer)` or something like that.


<!-- Sent from Reviewable.io -->

2024-11-15 08:43 UTC, Pururun reviewed
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @kl)

___
*[`talpid-wireguard/src/ephemeral.rs` line 207 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaIFfyCDs34yxTKGY5:-OBitrrV6aaYRihVIMYE:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/ephemeral.rs#L207)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It's still unwrapping here.
</blockquote></details>

Done
___
*[`talpid-wireguard/src/lib.rs` line 784 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBemGkICwtYZXvBfteq:-OBiub1K-F4jAU6Shpdn:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/989e4b51ff05371c6d3746b6df10623382746743/talpid-wireguard/src/lib.rs#L784)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

We could do something like this instead of relying on `is_multihop` to determine that `exit_peer` is set:

```
let tunnel = if let Some(exit_peer) = &config.exit_peer = {

    ...
    &config,
    exit_peer,
```
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-11-15 09:15 UTC, dlon reviewed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

___
*[`talpid-wireguard/src/lib.rs` line 782 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBj5DMT1ETGB5mnRnav:-OBj5DMT1ETGB5mnRnaw:bg13geb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f00c1a99096e1a1c17fb572bd9c62215346e4ca/talpid-wireguard/src/lib.rs#L782)):*
> ```XML
>         let tunnel = if let Some(exit_peer) = &config.exit_peer {
>             WgGoTunnel::start_multihop_tunnel(
>                 #[allow(clippy::needless_borrow)]
> ```

Nit: I'm pretty sure you can remove `#[allow(...)]` and just pass in `config`.
___
*[`talpid-wireguard/src/lib.rs` line 784 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBj5Sdv3Av51N3uP7gL:-OBj5Sdv3Av51N3uP7gM:b-dend9d) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f00c1a99096e1a1c17fb572bd9c62215346e4ca/talpid-wireguard/src/lib.rs#L784)):*
> ```XML
>                 #[allow(clippy::needless_borrow)]
>                 &config,
>                 exit_peer.clone(),
> ```

Nit: I believe you could pass this in by reference rather than cloning (requires changing the params, of course).


<!-- Sent from Reviewable.io -->

2024-11-15 09:58 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @dlon and @Pururun)

___
*[`talpid-wireguard/src/config.rs` line 201 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBaD-rm8ML9zwGClwSI:-OBjFa7Z2OTdApXRp2D_:b-75m0a4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2a7cd3c10ad14adc9cea785c952d993fb816e825/talpid-wireguard/src/config.rs#L201)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Ah, no, because it's an iterator. This is okay as is, but you could probably take `peers: impl Iterator<Item = &wireguard::PeerConfig>`. In `Config`, simply pass `self.peers()`. In the other place, `std::iter::once(&entry_peer)` and `std::iter::once(&exit_peer)` or something like that.
</blockquote></details>

We refactored the code again, please have a look. 


<!-- Sent from Reviewable.io -->

2024-11-15 10:20 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: 10 of 14 files reviewed, 1 unresolved discussion (waiting on @dlon)

___
*[`talpid-wireguard/src/lib.rs` line 782 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBj5DMT1ETGB5mnRnav:-OBjA1v4CUG2BdgFqas8:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f00c1a99096e1a1c17fb572bd9c62215346e4ca/talpid-wireguard/src/lib.rs#L782)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: I'm pretty sure you can remove `#[allow(...)]` and just pass in `config`.
</blockquote></details>

Done
___
*[`talpid-wireguard/src/lib.rs` line 784 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OBj5Sdv3Av51N3uP7gL:-OBjA13B0Npgc_EdTRE0:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/0f00c1a99096e1a1c17fb572bd9c62215346e4ca/talpid-wireguard/src/lib.rs#L784)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: I believe you could pass this in by reference rather than cloning (requires changing the params, of course).
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-11-15 12:27 UTC, dlon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> (if you've made sure that PQ works)

> Reviewed 2 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-:-OBjmXrmCueBLXlgHJqA:bc29eto)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-19 12:19 UTC, Pururun approved these changes
> Reviewed 13 of 13 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

___
*[`talpid-wireguard/src/lib.rs` line 1076 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OC3M9U42qACiCZEP5wE:-OC3M9U42qACiCZEP5wF:b-4qrjmu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3385e297cbdc61c0343f54e6ec4be437fc0c2021/talpid-wireguard/src/lib.rs#L1076)):*
> ```XML
>     #[cfg(target_os = "android")]
>     #[error("Tunnel seemingly does not serve any traffic")]
>     TunnelUp,
> ```

Nit: To me at least it would more sense to call this `TunnelUpError`


<!-- Sent from Reviewable.io -->

2024-11-19 14:15 UTC, Pururun submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

___
*[`talpid-wireguard/src/lib.rs` line 1076 at r18](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OC3M9U42qACiCZEP5wE:-OC3lbM20FjV6tH8UWK3:b-q39v81) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3385e297cbdc61c0343f54e6ec4be437fc0c2021/talpid-wireguard/src/lib.rs#L1076)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

It is _kind of_ an anti-pattern to suffix error variants with `Error`, even though we do not enforce it: https://rust-lang.github.io/rust-clippy/master/index.html#enum_variant_names

Just FYI
</blockquote></details>

The more you know, thanks :)


<!-- Sent from Reviewable.io -->

2024-11-20 13:01 UTC, dlon approved these changes
> Reviewed 3 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

___
*[`talpid-wireguard/src/lib.rs` line 1089 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168#-OC8dk5xArijaW527ws6:-OC8dk5xArijaW527ws7:b3sju7l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffa2f87e2dde462c0935e57084a667a80ded9e0a/talpid-wireguard/src/lib.rs#L1089)):*
> ```XML
>     DaitaNotSupported,
> 
>     /// [connecitivity] error.
> ```

Nit: connectivity


<!-- Sent from Reviewable.io -->

2024-11-20 17:29 UTC, dlon submitted a review, later dismissed
> Reviewed 3 of 3 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-22 11:58 UTC, dlon approved these changes
> Reviewed 4 of 4 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7168)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-22 16:56 UTC, merged