Support Android app's new version code format
mullvad/mullvadvpn-app pull request #7206
Opened 2024-11-20 10:22 UTC by kl

2024-11-20 10:38 UTC, Pururun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-:-OC88jlp063aI5RFnVhP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-20 16:27 UTC, albin-mullvad requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

___
*[`mullvad-version/src/lib.rs` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OC9NvIEDEXxaFtEbDKi:-OC9NvIEDEXxaFtEbDKj:bhji1jt) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa51155bb2687a167d0ff76ca9c3922c25e15fc3/mullvad-version/src/lib.rs#L22)):*
> ```XML
>     Beta(String),
>     Dev(String),
>     Release,
> ```

I suggest we call this one `Stable` rather than `Release` since we for example often refer to betas by saying "beta release".



_Code quote:_
```XML
Release
```


<!-- Sent from Reviewable.io -->

2024-11-21 07:13 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Pururun)

___
*[`mullvad-version/src/lib.rs` line 22 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OC9NvIEDEXxaFtEbDKi:-OCCZLga8gffI0gE8U14:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/aa51155bb2687a167d0ff76ca9c3922c25e15fc3/mullvad-version/src/lib.rs#L22)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest we call this one `Stable` rather than `Release` since we for example often refer to betas by saying "beta release".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-21 08:50 UTC, Pururun submitted a review, later dismissed
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: all files reviewed, 1 unresolved discussion (waiting on @albin-mullvad)



<!-- Sent from Reviewable.io -->

2024-11-21 12:32 UTC, albin-mullvad submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-:-OCCwJsd6v1KnWCHZ36f:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-21 12:53 UTC, faern requested changes
> Reviewed 2 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: all files reviewed, 3 unresolved discussions (waiting on @kl)

___
*[`mullvad-version/src/lib.rs` line 82 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCDkGF3564FGrGiglvG:-OCDkGF3564FGrGiglvH:b-w1nvlf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/144112aedba3a0b2b7993e103aa7d09b2daa2464/mullvad-version/src/lib.rs#L82)):*
> ```XML
>         static VERSION_REGEX: LazyLock<Regex> = LazyLock::new(|| {
>             Regex::new(
>                 r"(?x)
> ```

You overally improve the readability of the regex here a lot! I love it! If we also just add a comment to this line saying that `(?x)` enables the free spacing mode that would be awesome
___
*[`mullvad-version/src/lib.rs` line 122 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCDlj5vBvpH7PYIMrHc:-OCDlj5vBvpH7PYIMrHd:b-irj9um) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/144112aedba3a0b2b7993e103aa7d09b2daa2464/mullvad-version/src/lib.rs#L122)):*
> ```XML
>             (Some(v), _, _) => VersionType::Alpha(v.to_owned()),
>             (_, Some(v), _) => VersionType::Beta(v.to_owned()),
>             (_, _, Some(v)) => VersionType::Dev(v.to_owned()),
> ```

A suggestion could be to replace the `_` patterns with `None` and then add a last catch-all branch for `(..)` and throw an error? This makes us fail loudly in case the regex/version string is messed up at some point.
___
*[`mullvad-version/src/lib.rs` line 134 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCDm-l9E9mlzsxABVzu:-OCDm-l9E9mlzsxABVzv:bgc7vqv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/144112aedba3a0b2b7993e103aa7d09b2daa2464/mullvad-version/src/lib.rs#L134)):*
> ```XML
> }
> 
> #[cfg(test)]
> ```

:heart: 
___
*[`mullvad-version/Cargo.toml` line 20 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCDgkED3SYgkyQLtZyz:-OCDgkED3SYgkyQLtZz-:b-ylu5j5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/144112aedba3a0b2b7993e103aa7d09b2daa2464/mullvad-version/Cargo.toml#L20)):*
> ```TOML
> 
> [dependencies]
> regex = "1.11.1"
> ```

Was there any newly introduced feature we needed? Upgrading is not bad in any way, I'm just curious why it's needed :)


<!-- Sent from Reviewable.io -->

2024-11-21 16:18 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad, @faern, and @Pururun)

___
*[`mullvad-version/Cargo.toml` line 20 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCDgkED3SYgkyQLtZyz:-OCEVGyp5neak2dqcf89:b-rrzq7b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/144112aedba3a0b2b7993e103aa7d09b2daa2464/mullvad-version/Cargo.toml#L20)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Was there any newly introduced feature we needed? Upgrading is not bad in any way, I'm just curious why it's needed :)
</blockquote></details>

No real reason, I just saw there was a more recent version. Could also revert back to the old version? 
___
*[`mullvad-version/src/lib.rs` line 82 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCDkGF3564FGrGiglvG:-OCEVlWB0HbU7vprmsI8:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/144112aedba3a0b2b7993e103aa7d09b2daa2464/mullvad-version/src/lib.rs#L82)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

You overally improve the readability of the regex here a lot! I love it! If we also just add a comment to this line saying that `(?x)` enables the free spacing mode that would be awesome
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-22 08:18 UTC, faern approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-11-22 08:20 UTC, faern submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

___
*[`mullvad-version/Cargo.toml` line 20 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCDgkED3SYgkyQLtZyz:-OCHxC7i0hQ3b67jMHfr:b-xwkq4a) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/144112aedba3a0b2b7993e103aa7d09b2daa2464/mullvad-version/Cargo.toml#L20)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

No real reason, I just saw there was a more recent version. Could also revert back to the old version?
</blockquote></details>

They are semver compatible, so you don't need to update `Cargo.toml`. If you want/need a newer regex version then just `cargo update -p regex` is enough. Bumping version requirements is for when you *need* to up the lower limit or make a semver incompatible upgrade.


<!-- Sent from Reviewable.io -->

2024-11-22 15:02 UTC, faern approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`mullvad-version/Cargo.toml` line 20 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCDgkED3SYgkyQLtZyz:-OCJNTwX4FGeDQUmk-X8:b-70gbhg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/144112aedba3a0b2b7993e103aa7d09b2daa2464/mullvad-version/Cargo.toml#L20)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

They are semver compatible, so you don't need to update `Cargo.toml`. If you want/need a newer regex version then just `cargo update -p regex` is enough. Bumping version requirements is for when you *need* to up the lower limit or make a semver incompatible upgrade.
</blockquote></details>

Great :+1: The upgrade still happens due to the changes to `Cargo.lock` still being there. But that's fine, let's keep it. Just want to point it out, that it might not be recommended unless there is a specific reason.


<!-- Sent from Reviewable.io -->

2024-11-25 14:32 UTC, faern submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-25 15:42 UTC, MarkusPettersson98 requested changes
> Reviewed 2 of 5 files at r1, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: all files reviewed, 2 unresolved discussions (waiting on @kl)

___
*[`mullvad-version/src/lib.rs` line 134 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCDm-l9E9mlzsxABVzu:-OCYzJ6H7UiI4AfyL5UU:b-j1we20) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/144112aedba3a0b2b7993e103aa7d09b2daa2464/mullvad-version/src/lib.rs#L134)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

:heart:
</blockquote></details>

:raised_hands: 
___
*[`mullvad-version/src/lib.rs` line 23 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCYwzy28apEd5GeQej8:-OCYwzy28apEd5GeQej9:bgntcg5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a151fdd7154fbf55ae998d2fae8f1fb82afcd11a/mullvad-version/src/lib.rs#L23)):*
> ```XML
>     Dev(String),
>     Stable,
> }
> ```

This is out of scope, but wouldn't it be cool to distinguish between the version string that `Alpha` and `Beta` variants accept vs the `Dev` variant. The former accept just random version numbers whereas the latter only accept commit-hashes.



_Code quote (i):_
```XML
pub enum VersionType {
    Alpha(String),
    Beta(String),
    Dev(String),
    Stable,
}
```



_Code snippet (ii):_
```XML
pub enum VersionType {
    Alpha(VersionCode),
    Beta(VersionCode),
    Dev(CommitHash),
    Stable,
}

// Optimally, these would be there own proper types with their own proper parsing logic.
// For that little extra bit of rustiness.
type VersionCode = String; // XX e.g. 01, 02, ..
type CommitHash = String;  // xxyyzz e.g. abc012, 210cba, ..
```
___
*[`mullvad-version/src/lib.rs` line 117 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCYyZYn3ymk2K-xJ2u9:-OCYyZYo8grVx4McZgRQ:b-htidi3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a151fdd7154fbf55ae998d2fae8f1fb82afcd11a/mullvad-version/src/lib.rs#L117)):*
> ```XML
>             .name("dev")
>             .map(|m| m.as_str())
>             .or(captures.name("no_ver_dev").map(|_| ""));
> ```

This feels a bit iffy, why do we event bother extracting `no_ver_dev` and pass along an empty string instead of returning an error? Maybe there's a good use case, but I feel like that warrants a document by the `Dev` variant declaration at least.



_Code quote:_
```XML
            .or(captures.name("no_ver_dev").map(|_| ""));
```
___
*[`mullvad-version/src/main.rs` line 82 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCYusyI9gHDmgPgdD-X:-OCYusyJ5hpi2EExNaz9:bl4g3rl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a151fdd7154fbf55ae998d2fae8f1fb82afcd11a/mullvad-version/src/main.rs#L82)):*
> ```XML
>     if !is_valid_windows_version(&version_type) {
>         panic!("Invalid Windows version type: {version_type:?}");
>     }
> ```

:pick: I think this might be a _teeny tiny bit_ clearer if expressed as an `assert`



_Code quote (i):_
```XML
    if !is_valid_windows_version(&version_type) {
        panic!("Invalid Windows version type: {version_type:?}");
    }
```



_Code snippet (ii):_
```XML
assert!(is_valid_windows_version(&version_type), "Invalid Windows version type: {version_type:?}");
```
___
*[`mullvad-version/src/main.rs` line 97 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCYvSga3L96CqpnyXTP:-OCYvSga3L96CqpnyXTQ:b-bthvoh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a151fdd7154fbf55ae998d2fae8f1fb82afcd11a/mullvad-version/src/main.rs#L97)):*
> ```XML
>         VersionType::Beta(_) | VersionType::Dev(_) | VersionType::Stable
>     )
> }
> ```

It would be cool with a comment stating which Windows version types that are considered legal. It seems like `Stable`, `Beta` and `Dev` are considered valid, while `Alpha` is not. You did such a might fine job explaining the version format in `to_android_version_code`, and I want more of it :blush:



_Code quote:_
```XML
fn is_valid_windows_version(version_type: &VersionType) -> bool {
    matches!(
        version_type,
        VersionType::Beta(_) | VersionType::Dev(_) | VersionType::Stable
    )
}
```


<!-- Sent from Reviewable.io -->

2024-11-26 14:16 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @MarkusPettersson98)

___
*[`mullvad-version/src/lib.rs` line 23 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCYwzy28apEd5GeQej8:-OCciVLV2z2JD-UUJSWt:bqs3d9m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a151fdd7154fbf55ae998d2fae8f1fb82afcd11a/mullvad-version/src/lib.rs#L23)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This is out of scope, but wouldn't it be cool to distinguish between the version string that `Alpha` and `Beta` variants accept vs the `Dev` variant. The former accept just random version numbers whereas the latter only accept commit-hashes.
</blockquote></details>

Agreed, this would be nice to do if we add more logic to this code in the future.
___
*[`mullvad-version/src/lib.rs` line 117 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCYyZYn3ymk2K-xJ2u9:-OCcp4Yz-rsza-PFkrxc:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a151fdd7154fbf55ae998d2fae8f1fb82afcd11a/mullvad-version/src/lib.rs#L117)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This feels a bit iffy, why do we event bother extracting `no_ver_dev` and pass along an empty string instead of returning an error? Maybe there's a good use case, but I feel like that warrants a document by the `Dev` variant declaration at least.
</blockquote></details>

Fixed
___
*[`mullvad-version/src/main.rs` line 82 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCYusyI9gHDmgPgdD-X:-OCci80F0MwvN5vuzL24:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a151fdd7154fbf55ae998d2fae8f1fb82afcd11a/mullvad-version/src/main.rs#L82)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

:pick: I think this might be a _teeny tiny bit_ clearer if expressed as an `assert`
</blockquote></details>

Fixed
___
*[`mullvad-version/src/main.rs` line 97 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCYvSga3L96CqpnyXTP:-OCciDp54Ip0Pp2etFJR:bwchkgx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a151fdd7154fbf55ae998d2fae8f1fb82afcd11a/mullvad-version/src/main.rs#L97)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

It would be cool with a comment stating which Windows version types that are considered legal. It seems like `Stable`, `Beta` and `Dev` are considered valid, while `Alpha` is not. You did such a might fine job explaining the version format in `to_android_version_code`, and I want more of it :blush:
</blockquote></details>

All credit goes to @albin-mullvad  for the nice format description :wink: 


<!-- Sent from Reviewable.io -->

2024-11-26 15:08 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-:-OCd-g3B6eH8LTrLwZzq:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`mullvad-version/src/main.rs` line 97 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCYvSga3L96CqpnyXTP:-OCd-H805vcEjmjIvLkg:b1q6etj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a151fdd7154fbf55ae998d2fae8f1fb82afcd11a/mullvad-version/src/main.rs#L97)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

All credit goes to @albin-mullvad  for the nice format description :wink:
</blockquote></details>

Thanks! :blush:


<!-- Sent from Reviewable.io -->

2024-11-26 15:17 UTC, MarkusPettersson98 submitted a review, later dismissed
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-26 15:40 UTC, faern submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-27 08:53 UTC, albin-mullvad submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-:-OCgokqh9hBQ_Kq4P14u:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

___
*[`mullvad-version/src/lib.rs` line 72 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCgoFZ-96_BIPEAWpFc:-OCgoFZ-96_BIPEAWpFd:b-oto6rk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8003e6137715b5c363270585a694788227d7b184/mullvad-version/src/lib.rs#L72)):*
> ```XML
>             Alpha(version) => write!(f, "-alpha{version}"),
>             Beta(version) => write!(f, "-beta{version}"),
>             BetaDev { beta, dev } => write!(f, "-beta{beta}-dev-{dev}"),
> ```

nit: I suggest we rename this one to `commit_hash` in order to keep it consistent with the `Dev` version type 



_Code quote:_
```XML
dev
```


<!-- Sent from Reviewable.io -->

2024-11-27 12:56 UTC, albin-mullvad submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-:-OChgWfYD5sZ0T_IxDhr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-27 13:47 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[`mullvad-version/src/lib.rs` line 72 at r9](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCgoFZ-96_BIPEAWpFc:-OChrwafBA0Z4ZChlEag:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8003e6137715b5c363270585a694788227d7b184/mullvad-version/src/lib.rs#L72)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: I suggest we rename this one to `commit_hash` in order to keep it consistent with the `Dev` version type
</blockquote></details>

Fixed
___
*[`mullvad-version/src/lib.rs` line 4 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OChlq5J5sxsX2aUinuZ:-OChrxF2EkNTtEiZgZ1T:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/68131b27d2066bd1fe1d3fc4772cc92364f4a04c/mullvad-version/src/lib.rs#L4)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nitpick. But please avoid wildcard imports https://github.com/mullvad/coding-guidelines/blob/main/rust.md#imports-and-modules
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2024-11-27 13:54 UTC, faern approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: all files reviewed, 2 unresolved discussions (waiting on @kl)

___
*[`mullvad-version/src/lib.rs` line 15 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OChtSXnDRrYMjm0rdoW:-OChtSXnDRrYMjm0rdoX:ba2iini) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/daef200515da13a30ee5c1d2c3be4908817619a6/mullvad-version/src/lib.rs#L15)):*
> ```XML
>     pub year: String,
>     pub incremental: String,
>     pub version_type: Option<VersionType>,
> ```

Not a blocker, but I think it would be beneficial with rustdocs on this field explaining what it means. Kind of like what you added for `dev` below.
___
*[`mullvad-version/src/lib.rs` line 68 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OChsvZ910Hh8lTNuk5F:-OChsvZ910Hh8lTNuk5G:bmjc6gi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/daef200515da13a30ee5c1d2c3be4908817619a6/mullvad-version/src/lib.rs#L68)):*
> ```XML
>         };
> 
>         if let Some(dev) = dev {
> ```

Maybe name this variable `commit_hash` for clarity?


<!-- Sent from Reviewable.io -->

2024-11-27 14:02 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[`mullvad-version/src/lib.rs` line 15 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OChtSXnDRrYMjm0rdoW:-OChvUK2AgPX9hwG2QOy:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/daef200515da13a30ee5c1d2c3be4908817619a6/mullvad-version/src/lib.rs#L15)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Not a blocker, but I think it would be beneficial with rustdocs on this field explaining what it means. Kind of like what you added for `dev` below.
</blockquote></details>

Fixed
___
*[`mullvad-version/src/lib.rs` line 68 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OChsvZ910Hh8lTNuk5F:-OChvWDM6Pqz9N26n9mm:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/daef200515da13a30ee5c1d2c3be4908817619a6/mullvad-version/src/lib.rs#L68)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Maybe name this variable `commit_hash` for clarity?
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2024-11-27 14:56 UTC, faern submitted a review, later dismissed
NOICE

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-:-OCi6zdy0kUdzOw-96w4:b-849pej)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-27 15:15 UTC, albin-mullvad reviewed
> Reviewed 1 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: all files reviewed, 2 unresolved discussions (waiting on @kl)

___
*[`mullvad-version/src/lib.rs` line 23 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCi8ms73h_LlLDVhvHi:-OCi8ms73h_LlLDVhvHj:b-8o568g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c3cce1311dfc7d011720b8e8bc9328a8f95c20e/mullvad-version/src/lib.rs#L23)):*
> ```XML
> 
> #[derive(Debug, Clone, PartialEq)]
> pub enum VersionType {
> ```

nit: due to the `VersionType` no longer representing the `Stable` type (after other PR feedback) I suggest we rename it to something more suitable, such as `PreReleaseType`.
___
*[`mullvad-version/src/main.rs` line 101 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCi9QKW9ENlJkoPQZa4:-OCi9QKW9ENlJkoPQZa5:bzgepyp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c3cce1311dfc7d011720b8e8bc9328a8f95c20e/mullvad-version/src/main.rs#L101)):*
> ```XML
> 
> fn is_valid_windows_version(version_type: &Option<VersionType>) -> bool {
>     matches!(version_type, None | Some(VersionType::Beta(_)))
> ```

nit: it seems a bit strange to check whether the optional `version_type` is `None` part of this function where it's the only argument. IMO it would make more sense to change this so that either:
* This function checks whether a `Version` is valid, by check its `version_type`.
* Revert to how it looked before (`(version_type: &VersionType)`) and let the caller handle the `None` check.



_Code quote:_
```XML
None 
```


<!-- Sent from Reviewable.io -->

2024-11-27 15:19 UTC, albin-mullvad reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: all files reviewed, 2 unresolved discussions (waiting on @kl)

___
*[`mullvad-version/src/lib.rs` line 23 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCi8ms73h_LlLDVhvHi:-OCiBZgr5qUA0_ZfMzku:bn79vih) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c3cce1311dfc7d011720b8e8bc9328a8f95c20e/mullvad-version/src/lib.rs#L23)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: due to the `VersionType` no longer representing the `Stable` type (after other PR feedback) I suggest we rename it to something more suitable, such as `PreReleaseType`.
</blockquote></details>

I realize `PreReleaseType` might not be optimal even though it's quite common to use to refer to alphas and betas. Perhaps `PreStableType` is more in line with our other related naming.


<!-- Sent from Reviewable.io -->

2024-11-27 16:47 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad and @faern)

___
*[`mullvad-version/src/lib.rs` line 23 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCi8ms73h_LlLDVhvHi:-OCiJ_7IEjPV_F6069p5:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c3cce1311dfc7d011720b8e8bc9328a8f95c20e/mullvad-version/src/lib.rs#L23)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I realize `PreReleaseType` might not be optimal even though it's quite common to use to refer to alphas and betas. Perhaps `PreStableType` is more in line with our other related naming.
</blockquote></details>

Fixed
___
*[`mullvad-version/src/main.rs` line 101 at r12](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OCi9QKW9ENlJkoPQZa4:-OCiWBBy0PPz7ZsPtUft:b1n1qmk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/1c3cce1311dfc7d011720b8e8bc9328a8f95c20e/mullvad-version/src/main.rs#L101)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: it seems a bit strange to check whether the optional `version_type` is `None` part of this function where it's the only argument. IMO it would make more sense to change this so that either:
* This function checks whether a `Version` is valid, by check its `version_type`.
* Revert to how it looked before (`(version_type: &VersionType)`) and let the caller handle the `None` check.
</blockquote></details>

Changed function to taking Version instead


<!-- Sent from Reviewable.io -->

2024-11-28 08:26 UTC, albin-mullvad reviewed
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: all files reviewed, 1 unresolved discussion (waiting on @kl)

___
*[`mullvad-version/src/lib.rs` line 129 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OClrawiE56KMkjdO4yy:-OClrawiE56KMkjdO4yz:bt1yph2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeb7e4499f2427059c0b817c187f4bbcde941bc/mullvad-version/src/lib.rs#L129)):*
> ```XML
>             year,
>             incremental,
>             pre_stable: version_type,
> ```

Is this correct? :thinking: 



_Code quote:_
```XML
pre_stable: version_type,
```


<!-- Sent from Reviewable.io -->

2024-11-28 11:43 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad, @faern, @MarkusPettersson98, and @Pururun)

___
*[`mullvad-version/src/lib.rs` line 129 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-OClrawiE56KMkjdO4yy:-OCm_5zZDlkH-7-XPyam:b6xw7um) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ffeb7e4499f2427059c0b817c187f4bbcde941bc/mullvad-version/src/lib.rs#L129)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is this correct? :thinking:
</blockquote></details>

Fixed variable name


<!-- Sent from Reviewable.io -->

2024-11-28 11:58 UTC, albin-mullvad approved these changes
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-28 14:46 UTC, faern approved these changes
> Reviewed 1 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-28 14:53 UTC, Pururun approved these changes
Tested with `prepare-release.sh` and `build-apk.sh` and seems to work fine. :+1: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7206#-:-OCnFZRw4yau4Hz6rP1X:b5tolkl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-28 15:13 UTC, merged