Fix broken retry strategy tests ios 938
mullvad/mullvadvpn-app pull request #7213
Opened 2024-11-21 07:38 UTC by buggmagnet

This PR does the following things:

- Amend the documentation about the algorithm governing the automatic port selection
  - In particular, it adds an iOS specific section as it's quite different from other platforms
- Changes how local IP discovery is done in UITests (it used to be based on the interface name, which is not a reliable method on iOS)
- Adds a UITest for Shadowsocks obfuscation
- Updates the automatic reconnection algorithm for iOS based on the [official documentation](https://github.com/mullvad/mullvadvpn-app/blob/main/docs/relay-selector.md#default-constraints-for-tunnel-endpoints)

2024-11-21 07:50 UTC, pinkisemils requested changes
> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadREST/Relay/ObfuscatorPortSelector.swift` line 96 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-OCCgYLQDxygYAHnWBz1:-OCCgYLQDxygYAHnWBz2:b1ijsvd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d118592d20215ce631b62b787c4721b5f108e722/ios/MullvadREST/Relay/ObfuscatorPortSelector.swift#L96)):*
> ```Swift
>         switch tunnelSettings.wireGuardObfuscation.udpOverTcpPort {
>         case .automatic:
>             return (connectionAttemptCount % 2 == 0) ? .only(80) : .only(5001)
> ```

Would this have ever worked? Or was the connection attempt count specific to each obfuscation method?
___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-OCCgpKl4G1_MjWhFen4:-OCCgpKmCHiQzifoIZPC:bhkk75m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8cfa2dad08cb80734f5e45afd205f05ddb5d3181/ios/MullvadVPNUITests/Networking/Networking.swift#L59)):*
> ```Swift
>                 ) == 0 {
>                     ipAddress = String(cString: hostname)
>                     if ipAddress.starts(with: "192.168") {
> ```

This is wrong.


<!-- Sent from Reviewable.io -->

2024-11-21 07:50 UTC, pinkisemils requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-OCCgpKl4G1_MjWhFen4:-OCCgslb9rUP8CBVCXRk:b-uq6vvp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8cfa2dad08cb80734f5e45afd205f05ddb5d3181/ios/MullvadVPNUITests/Networking/Networking.swift#L59)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This is wrong.
</blockquote></details>

We can never know which local subnet will be used in tests.


<!-- Sent from Reviewable.io -->

2024-11-21 07:52 UTC, MarkusPettersson98 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`docs/relay-selector.md` line 77 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-OCCgoCnDEKSW68uSuXW:-OCCgoCnDEKSW68uSuXX:b-uwnpgb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8cfa2dad08cb80734f5e45afd205f05ddb5d3181/docs/relay-selector.md#L77)):*
> ```Markdown
> 
> - The UDP2TCP random port is **either** 80 **or** 5001
> - The Shadowsocks port is random within a certain range of ports defined by the relays configuration
> ```

:pick: relay's configuration* (?)



_Code quote:_
```Markdown
relays configuration
```
___
*[`docs/relay-selector.md` line 135 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-OCCfZ9oDLbUQt1ByHnb:-OCCfZ9oDLbUQt1ByHnc:b-tzalrc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8cfa2dad08cb80734f5e45afd205f05ddb5d3181/docs/relay-selector.md#L135)):*
> ```Markdown
> 
> There are two type of obfuscators - _udp2tcp_, and _shadowsocks_.
> They are used if the obfuscation mode is set to _On_ or _Auto_ and the user has selected WireGuard to be the only tunnel protocol to be used.
> ```

I think this is a bit outdated, the `On` option has not existed for a while. In this case, I think it is fine to just mention the `Auto` option :blush:



_Code quote:_
```Markdown
There are two type of obfuscators - _udp2tcp_, and _shadowsocks_.
They are used if the obfuscation mode is set to _On_ or _Auto_ and the user has selected WireGuard to be the only tunnel protocol to be used.
```


<!-- Sent from Reviewable.io -->

2024-11-21 07:53 UTC, pinkisemils reviewed
> Reviewed 1 of 9 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadVPNUITests/Pages/TunnelControlPage.swift` line 135 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-OCCh3WT3QL1fDFfIKbi:-OCCh3WT3QL1fDFfIKbj:bt5hkdd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8cfa2dad08cb80734f5e45afd205f05ddb5d3181/ios/MullvadVPNUITests/Pages/TunnelControlPage.swift#L135)):*
> ```Swift
>         if connectionAttempts.count == 4 { // Expected retries flow
>             for (attemptIndex, attempt) in connectionAttempts.enumerated() {
>                 if attemptIndex == 0 || attemptIndex == 1 || attemptIndex == 2 {
> ```

Would `attemptIndex < 3` not be more legible?

Or a set operation, like `attemptIndex in { 0, 1, 2 }`.


<!-- Sent from Reviewable.io -->

2024-11-21 09:12 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, and @pinkisemils)

___
*[`docs/relay-selector.md` line 77 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-OCCgoCnDEKSW68uSuXW:-OCCzU-t8r2eJxnb4IMO:b-meffe8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8cfa2dad08cb80734f5e45afd205f05ddb5d3181/docs/relay-selector.md#L77)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

There's 2 sets of ports, the ones that all relays support and, for relays with an `shadowsocks_extra_addr_in`, these addresses support all ports.
</blockquote></details>

I think we should call it "relay list". Since that's what we refer to the content of this API endpoint as everywhere else(?). I interpret "relay configuration" as an internal config we have generated for talking to a relay. While the "relay list" is the response from the API, which do contain the valid port ranges.


<!-- Sent from Reviewable.io -->

2024-11-21 09:23 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @buggmagnet, @MarkusPettersson98, and @pinkisemils)

___
*[`docs/relay-selector.md` line 65 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-OCD-rW5C4pplaWX4aQT:-OCD-rW5C4pplaWX4aQU:byn9m3t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/75265ad3efb42ae34b42f26079d90d442679efad/docs/relay-selector.md#L65)):*
> ```Markdown
>   - The eighth attempt will connect to an OpenVPN relay over a bridge on a random port
> 
> ### Default constraints for tunnel endpoints on iOS
> ```

We'll see what happens in ~a month when we remove OpenVPN from the automatic retry order. But great that you want to update the docs so they are better for your team/platform. Let's do this.


<!-- Sent from Reviewable.io -->

2024-11-21 10:40 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98 and @pinkisemils)

___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-OCCgpKl4G1_MjWhFen4:-OCDFb8v8sHnO9f8mRNg:bg0u9iw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8cfa2dad08cb80734f5e45afd205f05ddb5d3181/ios/MullvadVPNUITests/Networking/Networking.swift#L59)):*
> Has this ever failed us?

Literally the first device I took in the office didn't have an `en0` interface, so yes, which led me to make this change.

> If I was to run my test suite at home, with these new changes, it'd be broken.

The tests would likely fail anyway because they rely on the firewall API that is in the office.

> The better solution would....

We should not try to deduct the correct IP address to use from the tests, it will be broken in subtle ways that we might not expect. 
I thought about adding the IP address of the device running the tests in the `xcconfig` file but that is also error prone as you'd have to change it for every different device you use. 

Realistically, 99% of networks will use an IP in the 192.168.x.x/16 range for local IP addresses, and this is the least path of resistance. 

I made this change mostly with the automated tests running on the device attached to the local runner in the office.
But also this way, everyone can just run those tests without any issue, or needing to edit their configuration files. 


<!-- Sent from Reviewable.io -->

2024-11-21 12:14 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @buggmagnet, @faern, and @pinkisemils)

___
*[`docs/relay-selector.md` line 77 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-OCCgoCnDEKSW68uSuXW:-OCDdAAO1PhqovvCU4YZ:bo01rk9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8cfa2dad08cb80734f5e45afd205f05ddb5d3181/docs/relay-selector.md#L77)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

>  The Shadowsocks port is random within a certain range of ports defined by the relay list

Does that sound acceptable ?
</blockquote></details>

Sounds good to me :+1:


<!-- Sent from Reviewable.io -->

2024-11-21 13:15 UTC, pinkisemils requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`docs/relay-selector.md` line 77 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-OCCgoCnDEKSW68uSuXW:-OCDqIlrCh0IRa6GNYu6:bg7igkv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8cfa2dad08cb80734f5e45afd205f05ddb5d3181/docs/relay-selector.md#L77)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Sounds good to me :+1:
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 
___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-OCCgpKl4G1_MjWhFen4:-OCDqWAgBJ8Vw0XUjx9h:bsf5lnh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8cfa2dad08cb80734f5e45afd205f05ddb5d3181/ios/MullvadVPNUITests/Networking/Networking.swift#L59)):*
> Realistically, 99% of networks will use an IP in the 192.168.x.x/16 range for local IP addresses, and this is the least path of resistance.

99% of networks will not use an IP in `192.168/16`. 

> We should not try to deduct the correct IP address to use from the tests, it will be broken in subtle ways that we might not expect.  
I thought about adding the IP address of the device running the tests in the `xcconfig` file but that is also error prone as you'd have to change it for every different device you use.

I am not talking about specifying the IP address of the device - I am talking about specifying the subnet which to match with.
You can never know what IP address will your mobile provider give to you, it could also be a 192.168/16 address, as per Eskimo's post.

Also, may I ask, which device did not have the correct interface on `en0`?


<!-- Sent from Reviewable.io -->

2024-11-25 07:45 UTC, rablador reviewed
> Reviewed 7 of 9 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-11-25 14:31 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-OCCgpKl4G1_MjWhFen4:-OCYioBZ4uPL8RIDQzF_:b-op86wu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8cfa2dad08cb80734f5e45afd205f05ddb5d3181/ios/MullvadVPNUITests/Networking/Networking.swift#L59)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

> Realistically, 99% of networks will use an IP in the 192.168.x.x/16 range for local IP addresses, and this is the least path of resistance.

99% of networks will not use an IP in `192.168/16`. 

> We should not try to deduct the correct IP address to use from the tests, it will be broken in subtle ways that we might not expect.  
I thought about adding the IP address of the device running the tests in the `xcconfig` file but that is also error prone as you'd have to change it for every different device you use.

I am not talking about specifying the IP address of the device - I am talking about specifying the subnet which to match with.
You can never know what IP address will your mobile provider give to you, it could also be a 192.168/16 address, as per Eskimo's post.

Also, may I ask, which device did not have the correct interface on `en0`?
</blockquote></details>

We discussed this offline with the conclusion that we will add an API on the endpoint where the firewall resides
that will tell us which IP address the phone has, so we don't have to do local discovery of our own IP address.


<!-- Sent from Reviewable.io -->

2024-11-25 14:51 UTC, rablador submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2024-11-25 15:36 UTC, pinkisemils submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-OCCgpKl4G1_MjWhFen4:-OCYxoIt3shibMzTbT1S:bpypysm) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8cfa2dad08cb80734f5e45afd205f05ddb5d3181/ios/MullvadVPNUITests/Networking/Networking.swift#L59)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We discussed this offline with the conclusion that we will add an API on the endpoint where the firewall resides
that will tell us which IP address the phone has, so we don't have to do local discovery of our own IP address.
</blockquote></details>

The router API will now return the IP address as a string (be it IPv4 or IPv6) on route `/own-ip`. 


<!-- Sent from Reviewable.io -->

2024-11-26 08:16 UTC, rablador submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-11-26 10:01 UTC, rablador reviewed
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-11-26 12:00 UTC, rablador approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-11-26 13:13 UTC, buggmagnet reviewed
> Dismissed @pinkisemils from a discussion.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`ios/MullvadVPNUITests/Networking/Networking.swift` line 59 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-OCCgpKl4G1_MjWhFen4:-OCcaa4D2ghdq9ku46XW:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8cfa2dad08cb80734f5e45afd205f05ddb5d3181/ios/MullvadVPNUITests/Networking/Networking.swift#L59)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The router API will now return the IP address as a string (be it IPv4 or IPv6) on route `/own-ip`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-26 14:00 UTC, MarkusPettersson98 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213#-:-OCclRsC1iwumG3MuauW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-26 14:38 UTC, rablador approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-11-27 11:04 UTC, merged