Fix log redaction loading issue
mullvad/mullvadvpn-app pull request #7233
Opened 2024-11-25 14:44 UTC by mojganii

this PR take log redaction out of main thread which caused blocking UI when working around it.

2024-11-26 09:58 UTC, rablador requested changes
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/View controllers/ProblemReport/ProblemReportInteractor.swift` line 29 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCbqvxbDxnvIGeeEWDF:-OCbqvxbDxnvIGeeEWDG:b-7thij7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e625845ef602cace1c43ed0ed9b20932eb1065d/ios/MullvadVPN/View%20controllers/ProblemReport/ProblemReportInteractor.swift#L29)):*
> ```Swift
> 
>     func loadLogFiles(completion: @escaping () -> Void) {
>         DispatchQueue
> ```

Is this queueu necessary when `consolidatedLog.addLogFiles` already runs in a concurrent queue? Same for the calls to `consolidatedLog.string` below.
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCbnGRG6RRNZnj5gzbw:-OCbnGRG6RRNZnj5gzbx:b-fqfgd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e625845ef602cace1c43ed0ed9b20932eb1065d/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L55)):*
> ```Swift
> 
>     func addLogFiles(fileURLs: [URL], completion: @escaping () -> Void = {}) {
>         logQueue.async(flags: .barrier) {
> ```

Why do we use .barrier?
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCbod2s5et2cP3l0PqR:-OCbod2s5et2cP3l0PqS:b-prol3p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e625845ef602cace1c43ed0ed9b20932eb1065d/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L113)):*
> ```Swift
>         let redactedPath = redact(string: path)
> 
>         if let lossyString = readFileLossy(path: path, maxBytes: bufferSize) {
> ```

Why getting rid of the gobal var? `.logMaximumFileSize` ensures all log related activities use the same size.


<!-- Sent from Reviewable.io -->

2024-11-26 14:51 UTC, buggmagnet requested changes
> Reviewed 2 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)* status: all files reviewed, 8 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCcfKPT3ccYLfFgXZmP:-OCcfKPT3ccYLfFgXZmQ:bfzsx5w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b97d84a542913cd2007395a17eaa9e2ca4aa39c/ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift#L28)):*
> ```Swift
> 
>     override func tearDownWithError() throws {
>         super.tearDown()
> ```

We should call the correct `super` function, `tearDownWithError` here 
___
*[`ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift` line 39 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCcg1WG6_-FV-_9X97K:-OCcg1WG6_-FV-_9X97L:b-ql9ntg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b97d84a542913cd2007395a17eaa9e2ca4aa39c/ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift#L39)):*
> ```Swift
>     func testAddLogFiles() {
>         var string = ""
>         let expectation = self.expectation(description: "Log files added")
> ```

nit
no need for `self` here and below
___
*[`ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift` line 80 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCcwlS09I2CgmucIzY9:-OCcwlS09I2CgmucIzYA:bko9nxw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b97d84a542913cd2007395a17eaa9e2ca4aa39c/ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift#L80)):*
> ```Swift
>     }
> 
>     func testAddLogFilesRaceCondition() {
> ```

We discussed this offline, and decided to remove this test and `testReportedStringRaceCondition` as it doesn't really test against race conditions.
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 133 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCc64zi2DTaU8RNkFbY:-OCc64zj3vXtZeqGQ5mo:b-l7m0e3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/795ce077aa11fbaaa8b9e05e553e42820750df42/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L133)):*
> ```Swift
>             String(decoding: data, as: UTF8.self)
>                 .drop { ch in
>                     // Drop leading replacement characters produced when decoding data
> ```

That comment was useful, we should leave it
___
*[`ios/MullvadVPN/View controllers/ProblemReport/ProblemReportInteractor.swift` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCccF9G-6gxZEU0ncTu:-OCccF9HBW1bVjZjUHEK:b-rp1pcl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b97d84a542913cd2007395a17eaa9e2ca4aa39c/ios/MullvadVPN/View%20controllers/ProblemReport/ProblemReportInteractor.swift#L30)):*
> ```Swift
>     func loadLogFiles(completion: @escaping () -> Void) {
>         DispatchQueue
>             .global()
> ```

We don't need to dispatch on the `global` queue here since we're already doing this in a private concurrent queue.
The same applies to all uses of `global` in this file. 

If we absolutely need to dispatch off the UI thread here, the `ProblemReportInteractor` class can use a private dispatch queue. 


<!-- Sent from Reviewable.io -->

2024-11-27 11:45 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)* status: 2 of 7 files reviewed, 11 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCbnGRG6RRNZnj5gzbw:-OCd8JnD3nsaYnXjLEm1:b-p5f5t8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e625845ef602cace1c43ed0ed9b20932eb1065d/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L55)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Why do we use .barrier?
</blockquote></details>

Since the queue in concurrent, we need to be sure manipulation is executing in thread safe manner.
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 113 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCbod2s5et2cP3l0PqR:-OCd8UlXBR9wJ-SAxg-g:b6j52ig) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5e625845ef602cace1c43ed0ed9b20932eb1065d/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L113)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Why getting rid of the gobal var? `.logMaximumFileSize` ensures all log related activities use the same size.
</blockquote></details>

I'll add it through dependency injection.
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 133 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCc64zi2DTaU8RNkFbY:-OCd8pbh7_tM6ITQmyjL:b-jpuc3t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/795ce077aa11fbaaa8b9e05e553e42820750df42/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L133)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

That comment was useful, we should leave it
</blockquote></details>

It was unintentional.
___
*[`ios/MullvadVPN/View controllers/ProblemReport/ProblemReportInteractor.swift` line 30 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCccF9G-6gxZEU0ncTu:-OCd8yHi6_BHHhFaaX5F:bkajrg6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b97d84a542913cd2007395a17eaa9e2ca4aa39c/ios/MullvadVPN/View%20controllers/ProblemReport/ProblemReportInteractor.swift#L30)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We don't need to dispatch on the `global` queue here since we're already doing this in a private concurrent queue.
The same applies to all uses of `global` in this file. 

If we absolutely need to dispatch off the UI thread here, the `ProblemReportInteractor` class can use a private dispatch queue.
</blockquote></details>

We don't need that here. I made mistake.
___
*[`ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift` line 28 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCcfKPT3ccYLfFgXZmP:-OCd96hK7876smmGLqAW:b-kl8g3z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b97d84a542913cd2007395a17eaa9e2ca4aa39c/ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift#L28)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We should call the correct `super` function, `tearDownWithError` here
</blockquote></details>

good catch.
___
*[`ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift` line 39 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCcg1WG6_-FV-_9X97K:-OCd9Cqj4iPaP6Xc1wWJ:b-83sjo4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b97d84a542913cd2007395a17eaa9e2ca4aa39c/ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift#L39)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

nit
no need for `self` here and below
</blockquote></details>

Nice.
___
*[`ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift` line 80 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCcwlS09I2CgmucIzY9:-OCdAEzr8mXbHnMrop7U:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8b97d84a542913cd2007395a17eaa9e2ca4aa39c/ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift#L80)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We discussed this offline, and decided to remove this test and `testReportedStringRaceCondition` as it doesn't really test against race conditions.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 36 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OChQF2P2ThvqVm2ahcJ:-OChQF2P2ThvqVm2ahcK:bct5kdo) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/243b6b4c9ac9b9991077d3b29e23c0f85f43ba92/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L36)):*
> ```Swift
>     private let logQueue = DispatchQueue(
>         label: "com.mullvad.consolidation.logs.queue",
>         attributes: .concurrent
> ```

since there is I/O Operations and they can sometimes cause heavy process, I rather to user serial queue instead of concurrent one.
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 68 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OChQzvj83hnRNIPZK--:-OChQzvj83hnRNIPZK-0:b9hdkmp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13c8ebcaddd8bfd2d4c36bc99cc25c518a18e8d6/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L68)):*
> ```Swift
>         logQueue.async(flags: .barrier) {
>             self.logs.append(LogAttachment(label: message, content: redactedError))
>             DispatchQueue.main.async {
> ```

switch to main for calling the completion, since `ConsolidatedApplicationLog` belongs and interacts with the main app.
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 76 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OChQYYXEdf0yB7bSruU:-OChQYYXEdf0yB7bSruV:bh6635w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13c8ebcaddd8bfd2d4c36bc99cc25c518a18e8d6/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L76)):*
> ```Swift
>     var string: String {
>         var result = ""
>         logQueue.sync {
> ```

Since It's a serial queue anymore then for avoiding deadlock, I removed invoking `write`  function an the sync process.


<!-- Sent from Reviewable.io -->

2024-11-27 12:01 UTC, rablador reviewed
> Reviewed 5 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)* status: all files reviewed, 9 unresolved discussions (waiting on @buggmagnet and @mojganii)

___
*[`ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift` line 23 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OChUVqW8y3OeFj-s2Su:-OChUVqX73pzAuL-Te03:b7o4nc0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/243b6b4c9ac9b9991077d3b29e23c0f85f43ba92/ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift#L23)):*
> ```Swift
>             redactCustomStrings: mockRedactStrings,
>             redactContainerPathsForSecurityGroupIdentifiers: mockSecurityGroupIdentifiers,
>             bufferSize: 65_536
> ```

How come we use a different buffer size than the default in prod code?


<!-- Sent from Reviewable.io -->

2024-11-27 15:02 UTC, rablador submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)* status: all files reviewed, 5 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-11-28 12:29 UTC, buggmagnet requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 157 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCmQaow9-SK7hDNFz3s:-OCmQaow9-SK7hDNFz3t:buyqbl9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13c8ebcaddd8bfd2d4c36bc99cc25c518a18e8d6/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L157)):*
> ```Swift
>         }
> 
>         let data = fileHandle.readData(ofLength: Int(bufferSize))
> ```

This method seems deprecated, we should use its replacement
```swift
public func read(upToCount count: Int) throws -> Data?
```
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 160 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCmQ53uDD56yLelTvyR:-OCmQ53uDD56yLelTvyS:b-n8kzrz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13c8ebcaddd8bfd2d4c36bc99cc25c518a18e8d6/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L160)):*
> ```Swift
>         let replacementCharacter = Character(UTF8.decode(UTF8.encodedReplacementCharacter))
>         let lossyString = String(
>             String(decoding: data, as: UTF8.self)
> ```

:policewoman: :warning: `Optional Data -> String Conversion Violation: Prefer failable `String(data:encoding:)` initializer when converting `Data` to `String` (optional_data_string_conversion)`
___
*[`ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift` line 38 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCmjvf_44QQ8fQbMngF:-OCmjvf_44QQ8fQbMngG:br92zbe) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13c8ebcaddd8bfd2d4c36bc99cc25c518a18e8d6/ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift#L38)):*
> ```Swift
>     }
> 
>     func testAddLogFiles() {
> ```

Somehow, this test is broken now


<!-- Sent from Reviewable.io -->

2024-11-28 21:06 UTC, rablador requested changes
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)* status: all files reviewed, 4 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 77 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCo_KSE7Yn3Pn8S5ysA:-OCo_KSE7Yn3Pn8S5ysB:bvxr5zk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1defbf28b825966f06412a5768bc393f89caa84/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L77)):*
> ```Swift
>         var result = ""
>         logQueue.sync {
>             if !logs.isEmpty {
> ```

This seems to be almost identical to `write()` below. Can we create a new function for the constructiom of `result`/`localOutput`?


<!-- Sent from Reviewable.io -->

2024-12-02 08:43 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 157 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCmQaow9-SK7hDNFz3s:-OCn1D5u-G_L4QO4hoz9:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13c8ebcaddd8bfd2d4c36bc99cc25c518a18e8d6/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L157)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This method seems deprecated, we should use its replacement
```swift
public func read(upToCount count: Int) throws -> Data?
```
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 160 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCmQ53uDD56yLelTvyR:-OCn1EIR84gX3JXEX3GA:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13c8ebcaddd8bfd2d4c36bc99cc25c518a18e8d6/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L160)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

:policewoman: :warning: `Optional Data -> String Conversion Violation: Prefer failable `String(data:encoding:)` initializer when converting `Data` to `String` (optional_data_string_conversion)`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 77 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCo_KSE7Yn3Pn8S5ysA:-OD5XHzF7wuJmaMvSonD:b1fumv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1defbf28b825966f06412a5768bc393f89caa84/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L77)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

This seems to be almost identical to `write()` below. Can we create a new function for the constructiom of `result`/`localOutput`?
</blockquote></details>

No, that can cause `deadlock`.
___
*[`ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift` line 38 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCmjvf_44QQ8fQbMngF:-OCnDatLEY1vjBSv3LZM:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/13c8ebcaddd8bfd2d4c36bc99cc25c518a18e8d6/ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift#L38)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Somehow, this test is broken now
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2024-12-02 09:07 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)* status: all files reviewed, 3 unresolved discussions (waiting on @mojganii and @rablador)

___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 77 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCo_KSE7Yn3Pn8S5ysA:-OD5aRSE7bIjqfTgrmmJ:b2osp97) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9759cb30da613ee838dcff4d30e6564b1eb0b5c4/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L77)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

No, that can cause `deadlock`.
</blockquote></details>

I agree with @rablador, we can create such a function

Note that you can also use `dispatchPrecondition(condition: .onQueue(logQueue))` (or the `.notOnQueue` variant) to make assertions about deadlocks and whatnot.

```swift
    func formatHeader() -> String {
        var result = ""
        result += "System information:\n"
        for (key, value) in metadata {
            result += "\(key.rawValue): \(value)\n"
        }
        result += "\n"
        for attachment in logs {
            result += "\(kLogDelimiter)\n"
            result += "\(attachment.label)\n"
            result += "\(kLogDelimiter)\n"
            result += "\(attachment.content)\n\n"
        }

        return result
    }

    var string: String {
        var result = ""
        logQueue.sync {
            if !logs.isEmpty {
                result = formatHeader()
            }
        }
        return result
    }

    func write(to stream: inout some TextOutputStream) {
        logQueue.sync {
            var localOutput = ""
            if !logs.isEmpty {
                localOutput = formatHeader()
                stream.write(localOutput)
            }
        }
    }
```
___
*[`ios/MullvadSettings/SettingsManager.swift` line 50 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OD5MQR05II5kYh5VNdG:-OD5MQR16_9rj4Npnvmz:bbfq156) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9759cb30da613ee838dcff4d30e6564b1eb0b5c4/ios/MullvadSettings/SettingsManager.swift#L50)):*
> ```Swift
>     public static func getLastUsedAccount() throws -> String {
>         let data = try store.read(key: .lastUsedAccount)
>         return String(bytes: data, encoding: .utf8) ?? ""
> ```

We should throw a `StringDecodingError` instead of silently failing and returning an empty string here.
___
*[`ios/MullvadVPN/View controllers/ProblemReport/ProblemReportInteractor.swift` line 24 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OD5UdM57_rJI_k7GChP:-OD5UdM57_rJI_k7GChQ:br1azt2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9759cb30da613ee838dcff4d30e6564b1eb0b5c4/ios/MullvadVPN/View%20controllers/ProblemReport/ProblemReportInteractor.swift#L24)):*
> ```Swift
>         self.tunnelManager = tunnelManager
>         self.consolidatedLog = ConsolidatedApplicationLog(
>             redactCustomStrings: [tunnelManager.deviceState.accountData?.number].compactMap { $0 },
> ```

I realize that this `redactCustomStrings` is not a good design. 
It only does something if the user is logged in when sending logs, otherwise this will be empty (because no `accountData.number` when logged out) and won't redact anything.

Thankfully, we have a `redactAccountNumber` function that uses a regex to redact account numbers, otherwise we'd have a pretty major problem. 

We should delete this false sense of privacy, and make sure the regex we use (for now) is solid instead.


<!-- Sent from Reviewable.io -->

2024-12-02 10:50 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadSettings/SettingsManager.swift` line 50 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OD5MQR05II5kYh5VNdG:-OD5jSvt9n-AA_Cgj6Vp:b5q5tp6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9759cb30da613ee838dcff4d30e6564b1eb0b5c4/ios/MullvadSettings/SettingsManager.swift#L50)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

We should throw a `StringDecodingError` instead of silently failing and returning an empty string here.
</blockquote></details>

but the function `String(bytes: data, encoding: .utf8)`  doesn't throw any thing and the new one is  the same as what they were.
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 77 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCo_KSE7Yn3Pn8S5ysA:-OD5i2aL0v0v02AO9rSd:baakb38) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9759cb30da613ee838dcff4d30e6564b1eb0b5c4/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L77)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I agree with @rablador, we can create such a function

Note that you can also use `dispatchPrecondition(condition: .onQueue(logQueue))` (or the `.notOnQueue` variant) to make assertions about deadlocks and whatnot.

```swift
    func formatHeader() -> String {
        var result = ""
        result += "System information:\n"
        for (key, value) in metadata {
            result += "\(key.rawValue): \(value)\n"
        }
        result += "\n"
        for attachment in logs {
            result += "\(kLogDelimiter)\n"
            result += "\(attachment.label)\n"
            result += "\(kLogDelimiter)\n"
            result += "\(attachment.content)\n\n"
        }

        return result
    }

    var string: String {
        var result = ""
        logQueue.sync {
            if !logs.isEmpty {
                result = formatHeader()
            }
        }
        return result
    }

    func write(to stream: inout some TextOutputStream) {
        logQueue.sync {
            var localOutput = ""
            if !logs.isEmpty {
                localOutput = formatHeader()
                stream.write(localOutput)
            }
        }
    }
```
</blockquote></details>

`dispatchPrecondition(condition: .onQueue(logQueue))` can't prevent from probably deadlock, it's just for checking, I found another way to do that.
___
*[`ios/MullvadVPN/View controllers/ProblemReport/ProblemReportInteractor.swift` line 24 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OD5UdM57_rJI_k7GChP:-OD5k9siERORCtzOQ2-m:buwhpf9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9759cb30da613ee838dcff4d30e6564b1eb0b5c4/ios/MullvadVPN/View%20controllers/ProblemReport/ProblemReportInteractor.swift#L24)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I realize that this `redactCustomStrings` is not a good design. 
It only does something if the user is logged in when sending logs, otherwise this will be empty (because no `accountData.number` when logged out) and won't redact anything.

Thankfully, we have a `redactAccountNumber` function that uses a regex to redact account numbers, otherwise we'd have a pretty major problem. 

We should delete this false sense of privacy, and make sure the regex we use (for now) is solid instead.
</blockquote></details>

I know it's good to improve code when there is room to do that but It's beyond the current issue I opened PR for. since it's adding through DI then I changed that to accept nil and mange that in `ConsolidatedApplicationLog`  


<!-- Sent from Reviewable.io -->

2024-12-02 11:20 UTC, rablador reviewed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-12-02 11:50 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/MullvadSettings/SettingsManager.swift` line 50 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OD5MQR05II5kYh5VNdG:-OD6BMjL8QlgUK-K6n77:bi23v4z) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9759cb30da613ee838dcff4d30e6564b1eb0b5c4/ios/MullvadSettings/SettingsManager.swift#L50)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

but the function `String(bytes: data, encoding: .utf8)`  doesn't throw any thing and the new one is  the same as what they were.
</blockquote></details>

That `init` can return a `nil` value, and this API is already declared as `throws` so the call site expects to handle errors.
In general, it's bad practice to hide errors like this, because it makes it significantly harder to debug  when things go wrong.
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 77 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCo_KSE7Yn3Pn8S5ysA:-OD6Bj-4Df38I6mevqi6:b-5vfik3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9759cb30da613ee838dcff4d30e6564b1eb0b5c4/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L77)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

`dispatchPrecondition(condition: .onQueue(logQueue))` can't prevent from probably deadlock, it's just for checking, I found another way to do that.
</blockquote></details>

You're right that `dispatchPrecondition` does not prevent deadlocks, but that isn't the point of using that API.
The point is that whenever you cannot guarantee that a call happens on a specific dispatch queue, this will blow up and give you a stack trace, which will lead to the root cause.


<!-- Sent from Reviewable.io -->

2024-12-02 14:51 UTC, mojganii reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadSettings/SettingsManager.swift` line 50 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OD5MQR05II5kYh5VNdG:-OD6jQxC32MgfqLfsmEX:b-ilyshw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9759cb30da613ee838dcff4d30e6564b1eb0b5c4/ios/MullvadSettings/SettingsManager.swift#L50)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

That `init` can return a `nil` value, and this API is already declared as `throws` so the call site expects to handle errors.
In general, it's bad practice to hide errors like this, because it makes it significantly harder to debug  when things go wrong.
</blockquote></details>

I agree to throw exception when it's not able to cast data to intended encoding but I'm just telling it was the thing we had before :)
___
*[`ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift` line 77 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-OCo_KSE7Yn3Pn8S5ysA:-OD6jE-N20OcH2on4gb6:b-8ron0n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9759cb30da613ee838dcff4d30e6564b1eb0b5c4/ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift#L77)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

You're right that `dispatchPrecondition` does not prevent deadlocks, but that isn't the point of using that API.
The point is that whenever you cannot guarantee that a call happens on a specific dispatch queue, this will blow up and give you a stack trace, which will lead to the root cause.
</blockquote></details>

I agree but with the current implementation I suppose we don't need that anymore.


<!-- Sent from Reviewable.io -->

2024-12-02 15:04 UTC, rablador approved these changes
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-12-03 10:06 UTC, buggmagnet requested changes
> Reviewed 1 of 5 files at r3, 1 of 3 files at r4, 1 of 5 files at r5, 1 of 2 files at r6, 3 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)* status: all files reviewed, 2 unresolved discussions (waiting on @mojganii)

___
*[`ios/Shared/LaunchArguments.swift` line 51 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-ODAz2bO-nPiDxwWdz_4:-ODAz2bO-nPiDxwWdz_5:bevppsn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e7379c3b51cd0801629e0ac2c4267babd5a54d7c/ios/Shared/LaunchArguments.swift#L51)):*
> ```Swift
>         let data = try encoder.encode(self)
>         guard let result = String(bytes: data, encoding: .utf8) else {
>             throw StringDecodingError(data: data)
> ```

That should be a `StringEncodingError` here


<!-- Sent from Reviewable.io -->

2024-12-03 10:35 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233#-:-ODB4aq13-VCxUQnKW0N:bnfp4nl)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-12-03 10:37 UTC, merged