Make shadowsocks obfuscation ready for production ios 879
mullvad/mullvadvpn-app pull request #7257
Opened 2024-11-28 13:40 UTC by buggmagnet

This PR adds WireGuard over Shadowsocks obfuscation in `Release` and `MockRelease` builds.
It also amends the Changelog to mention said change.

2024-11-28 13:46 UTC, acb-mv requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7257)* status: all files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/CHANGELOG.md` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7257#-OCn09twDLxZ59WY5DhW:-OCn09twDLxZ59WY5DhX:b84wqpc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/408e15e1c07e8f48e7b16a2f6527511941b4237b/ios/CHANGELOG.md#L26)):*
> ```Markdown
> ## Unreleased
> ### Added
> - Add WireGuard over Shadowsocks obfuscation. It can be enabled in "VPN settings". This will
> ```

Grammatical error. Perhaps "...and will also be used automatically"?


<!-- Sent from Reviewable.io -->

2024-11-28 14:19 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7257)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv)

___
*[`ios/CHANGELOG.md` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7257#-OCn09twDLxZ59WY5DhW:-OCn7dHH1ctXcEGSqAwj:b4igzqx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/408e15e1c07e8f48e7b16a2f6527511941b4237b/ios/CHANGELOG.md#L26)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Grammatical error. Perhaps "...and will also be used automatically"?
</blockquote></details>

I'm not sure I see it, there's a dot `.` after the second sentence, so both this, and the third one are valid (I copy pasted this from the desktop release notes to be honest) 

Did you mean that there should be a comma `,` instead of a dot  `.` ?


<!-- Sent from Reviewable.io -->

2024-11-28 15:33 UTC, acb-mv commented
*[`ios/CHANGELOG.md` line 26 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7257#-OCn09twDLxZ59WY5DhW:-OCnOWLF3suOeemO6lKj:b-viva64) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/408e15e1c07e8f48e7b16a2f6527511941b4237b/ios/CHANGELOG.md#L26)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

I'm not sure I see it, there's a dot `.` after the second sentence, so both this, and the third one are valid (I copy pasted this from the desktop release notes to be honest) 

Did you mean that there should be a comma `,` instead of a dot  `.` ?
</blockquote></details>

Sorry, I missed the "Th" at the start of "This will", and the browser helpfully showed "is will" at the start of the next line, which I assumed was meant to be an "it will". Carry on.


<!-- Sent from Reviewable.io -->

2024-11-28 20:58 UTC, rablador approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7257)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-02 12:39 UTC, acb-mv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7257)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-02 14:04 UTC, merged