Add accessibility identifiers to SingleChoiceList rows and text fields
mullvad/mullvadvpn-app pull request #7273
Opened 2024-12-03 09:01 UTC by acb-mv

This adds the ability to add `accessibilityIdentifier`s to tappable rows and custom entry controls in a `SingleChoiceList`, preparing it for UI tests.

2024-12-03 09:46 UTC, rablador approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7273)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-03 15:28 UTC, buggmagnet requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7273)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv)

___
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 223 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7273#-ODC7FCUDgMiIZX2JkhW:-ODC7FCUDgMiIZX2JkhX:b-4lq5vg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ca7ed9bf0e2d34600aee7cc89ad4dc13c76aab04/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L223)):*
> ```Swift
>             customValueInput = ""
>         }
>         .accessibilityIdentifier(itemAccessibilityIdentifier(item))
> ```

Have we actually tested this ?
Since we have our own custom override of `UIAccessibilityIdentification` which will try to case the value to the `AccessibilityIdentifier` enum, if that string is not present in the `raw` representation, it will just crash at runtime. 

Or is SwiftUI using a different protocol for accessibility ?


<!-- Sent from Reviewable.io -->

2024-12-03 16:00 UTC, acb-mv commented
*[`ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift` line 223 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7273#-ODC7FCUDgMiIZX2JkhW:-ODCELVNDRhJpr0dkfMh:b9xzn2j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ca7ed9bf0e2d34600aee7cc89ad4dc13c76aab04/ios/MullvadVPN/View%20controllers/Settings/SwiftUI%20components/SingleChoiceList.swift#L223)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Have we actually tested this ?
Since we have our own custom override of `UIAccessibilityIdentification` which will try to case the value to the `AccessibilityIdentifier` enum, if that string is not present in the `raw` representation, it will just crash at runtime. 

Or is SwiftUI using a different protocol for accessibility ?
</blockquote></details>

SwiftUI has a modifier which accepts a `String` as the identifier. 
https://developer.apple.com/documentation/swiftui/view/accessibilityidentifier(_:)


<!-- Sent from Reviewable.io -->

2024-12-04 06:34 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7273#-:-ODFN2BsBfCIbJOsCWXh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-12-04 06:36 UTC, merged