Migrate ConnectionTest e2e tests to use POP
mullvad/mullvadvpn-app pull request #7283
Opened 2024-12-04 16:36 UTC by niklasberglund

Migrated the e2e test cases in `ConnectionTest` to follow Page Object Pattern, similar to how we implemented it in `LoginTests`. The changes can be tested by running all test cases under `ConnectionTest`.

Also implemented Wireguard obfuscation set to automatic with UDP traffic to relay blocked connection test(`testWireGuardObfuscationAutomatic`).

Fixes DROID-1600, DROID-1622

2024-12-05 09:15 UTC, Rawa requested changes
> Reviewed 4 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7283)* status: 4 of 12 files reviewed, 2 unresolved discussions (waiting on @niklasberglund)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt` line 176 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7283#-ODL4y-S16eMTWLAHGX0:-ODL4y-S16eMTWLAHGX1:ble8sfw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ed0f4ce1182e68b1a392b3eb92ac01ae32bff72/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt#L176)):*
> ```Kotlin
>             on<SystemVpnConfigurationAlert> { clickOk() }
> 
>             var relayIpAddress: String? = null
> ```

Ping me and we can talk about this, I would like to avoid the var's
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt` line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7283#-ODL4qVn6FVfS6LiHJaf:-ODL4qVn6FVfS6LiHJag:b-s701td) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ed0f4ce1182e68b1a392b3eb92ac01ae32bff72/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt#L215)):*
> ```Kotlin
>             clickLocalNetworkSharingSwitch()
>             pressBack()
>             pressBack()
> ```

A bit misleading because this pressBack is probably on SettingsPage rather than VpnSettingsPage.


<!-- Sent from Reviewable.io -->

2024-12-05 09:43 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7283)* status: 4 of 12 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt` line 176 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7283#-ODL4y-S16eMTWLAHGX0:-ODLBprx4DjzaNZNxRYW:b-riiija) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ed0f4ce1182e68b1a392b3eb92ac01ae32bff72/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt#L176)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Ping me and we can talk about this, I would like to avoid the var's
</blockquote></details>

Perfect. Me too 👍
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt` line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7283#-ODL4qVn6FVfS6LiHJaf:-ODLA_azDgFLdjSko8vu:b-q3531s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ed0f4ce1182e68b1a392b3eb92ac01ae32bff72/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt#L215)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

A bit misleading because this pressBack is probably on SettingsPage rather than VpnSettingsPage.
</blockquote></details>

True! Actually the `pressBack()` function in `Page` is maybe a bit misleading, because it uses the Android back functionality, it doesn't press the back arrow in the settings view. I'm torn. On one hand it's nice to shorten the syntax, on the other hand it's misleading and maybe more descriptive to do `uiDevice.pressBack()`, on the third hand maybe the tests should actually press the back button instead of using the Android back functionality.


<!-- Sent from Reviewable.io -->

2024-12-05 10:07 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7283)* status: 4 of 12 files reviewed, 1 unresolved discussion

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt` line 176 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7283#-ODL4y-S16eMTWLAHGX0:-ODLHJGA9liYRAe4reLe:bwvb3r2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ed0f4ce1182e68b1a392b3eb92ac01ae32bff72/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt#L176)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Perfect. Me too 👍
</blockquote></details>

Seems like we are a bit limited by the type system. :cry: 


<!-- Sent from Reviewable.io -->

2024-12-06 08:38 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7283)* status: 4 of 14 files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt` line 215 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7283#-ODL4qVn6FVfS6LiHJaf:-ODQ6P_O5RMJ2l6Bngr2:b-bqttaz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6ed0f4ce1182e68b1a392b3eb92ac01ae32bff72/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt#L215)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

True! Actually the `pressBack()` function in `Page` is maybe a bit misleading, because it uses the Android back functionality, it doesn't press the back arrow in the settings view. I'm torn. On one hand it's nice to shorten the syntax, on the other hand it's misleading and maybe more descriptive to do `uiDevice.pressBack()`, on the third hand maybe the tests should actually press the back button instead of using the Android back functionality.
</blockquote></details>

We talked about this over a Slack huddle. Have removed `pressBack()` from `Page` and using `device.pressBack()` instead, and also moved them out of the page scopes.


<!-- Sent from Reviewable.io -->

2024-12-06 10:25 UTC, Rawa approved these changes
> Reviewed 2 of 12 files at r1, 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7283)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-06 12:55 UTC, merged