Make AccessibilityIdentifier no longer a String enum
mullvad/mullvadvpn-app pull request #7293
Opened 2024-12-05 16:50 UTC by acb-mv

This removes the backing String value type from `AccessibilityIdentifier`. As of this change,

- `AccessibilityIdentifier` no longer has a `.rawValue`. For producing the string-based identifier, there is a `.asString` value which does the same thing
- `UIAccessibilityIdentification` no longer has an `accessibilityIdentifier` variable typed to `AccessibilityIdentifier`, but in turn has a `setAccessibilityIdentifier` method. The handful of use cases that involved matching a string to an `AccessibilityIdentifier` value are done by comparing the resulting strings.

Why have we done this, you may be wondering? The main thing this unblocks is more sophisticated `AccessibilityIdentifier` types and less boilerplate.  Whereas until now, each value that had its own cell/button would have had its own `AccessibilityIdentifier` value, with a case statement to convert the underlying values to them, with this change it will be possible to have tagged values of `AccessibilityIdentifier`, with all options having the same underlying value and each differing only in the data value it encapsulates.

2024-12-09 07:08 UTC, rablador requested changes
> Reviewed 66 of 68 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293)* status: all files reviewed, 3 unresolved discussions (waiting on @acb-mv)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift` line 83 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-ODeD6r989R6UDBPcllo:-ODeD6r989R6UDBPcllp:b-fu0p67) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aa969bfc4088eaab3917b8d5051712ffcb0f8f2/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsCellFactory.swift#L83)):*
> ```Swift
> 
>             cell.titleLabel.text = portString
>             // TODO: replace this with a tagged AccessibilityIdentifier
> ```

Is this planned work in an upcoming pr? Otherwise we should either do it here or remove the todo.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift` line 330 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-ODeCXG40WFHXlENv5sY:-ODeCXG40WFHXlENv5sZ:b1olfp6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aa969bfc4088eaab3917b8d5051712ffcb0f8f2/ios/MullvadVPN/View%20controllers/SelectLocation/LocationCell.swift#L330)):*
> ```Swift
>             // location here is fine.
>             if let location = item.node.locations.first {
>                 // we can probably replace this with a tagged AccessibilityIdentifier and cut this case statement
> ```

If you have an idea, go for it :)
___
*[`ios/MullvadVPNUITests/Base/BaseUITestCase.swift` line 251 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-ODeDdaS0TywnwyWMsIq:-ODeDdaS0TywnwyWMsIr:b4yhce2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aa969bfc4088eaab3917b8d5051712ffcb0f8f2/ios/MullvadVPNUITests/Base/BaseUITestCase.swift#L251)):*
> ```Swift
>         // Ensure changelog is no longer shown
>         _ = app
>             .otherElements[AccessibilityIdentifier.changeLogAlert.asString]
> ```

Thanks to the subscript function in `XCUIElementQuery` we can simplify this with `.otherElements[.changeLogAlert]`. This apply to all similar cases below.


<!-- Sent from Reviewable.io -->

2024-12-09 08:24 UTC, buggmagnet requested changes
Please make sure to also run the UITests on the CI to guarantee we don't break anything (or at least not make it worse given its recent issues)

> Reviewed 66 of 68 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-:-ODeW7KC-qVyEjN3FgU3:b-mcdphd)* status: all files reviewed, 5 unresolved discussions (waiting on @acb-mv)

___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeContentView.swift` line 254 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-ODeVa9I7rPV2D4vp7t0:-ODeVa9I7rPV2D4vp7t1:b-b3us3y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aa969bfc4088eaab3917b8d5051712ffcb0f8f2/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeContentView.swift#L254)):*
> ```Swift
>     @objc private func tapped(button: AppButton) {
>         switch button.accessibilityIdentifier {
>         case AccessibilityIdentifier.purchaseButton.asString:
> ```

Do we need to specify the whole type name here ? It feels like a downgrade in readability
___
*[`ios/MullvadVPN/Classes/AccessbilityIdentifier.swift` line 218 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-ODeR89W0HPE7kGGy_FC:-ODeR89W0HPE7kGGy_FD:b-xqxwfa) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aa969bfc4088eaab3917b8d5051712ffcb0f8f2/ios/MullvadVPN/Classes/AccessbilityIdentifier.swift#L218)):*
> ```Swift
> 
> extension AccessibilityIdentifier {
>     public var asString: String {
> ```

Let's just make it compliant to `CustomStringConvertible` instead of doing this, we don't need to reinvent the wheel


<!-- Sent from Reviewable.io -->

2024-12-09 10:48 UTC, acb-mv commented
*[`ios/MullvadVPNUITests/Base/BaseUITestCase.swift` line 251 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-ODeDdaS0TywnwyWMsIq:-ODf0tmI-uUgfhMOzCxe:br2fbj8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aa969bfc4088eaab3917b8d5051712ffcb0f8f2/ios/MullvadVPNUITests/Base/BaseUITestCase.swift#L251)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Thanks to the subscript function in `XCUIElementQuery` we can simplify this with `.otherElements[.changeLogAlert]`. This apply to all similar cases below.
</blockquote></details>

Do we need to configure it to handle our custom `AccessibilityIdentifier` type?


<!-- Sent from Reviewable.io -->

2024-12-09 10:48 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293)* status: 66 of 69 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/Classes/AccessbilityIdentifier.swift` line 218 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-ODeR89W0HPE7kGGy_FC:-ODefbfS0pwS2P-1hi6V:bv76278) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aa969bfc4088eaab3917b8d5051712ffcb0f8f2/ios/MullvadVPN/Classes/AccessbilityIdentifier.swift#L218)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Let's just make it compliant to `CustomStringConvertible` instead of doing this, we don't need to reinvent the wheel
</blockquote></details>

That's what I did initially. The problem is, if you do that, you enter a loop, with `"\(self)"` calling the newly available `self.description` method until the stack overflows.  There does not appear to be a user-accessible tagged-enum-formatting mechanism lower level than string interpolation (which calls `description`).

For what it's worth, the string we're getting is more specific than a catch-all description: it is a unique value generated from the enum and used for comparison, so it is not inappropriate for it to have a different computed variable.
___
*[`ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeContentView.swift` line 254 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-ODeVa9I7rPV2D4vp7t0:-ODeho0B-o3rrOHlNVkn:b-zea4fj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aa969bfc4088eaab3917b8d5051712ffcb0f8f2/ios/MullvadVPN/View%20controllers/CreationAccount/Welcome/WelcomeContentView.swift#L254)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Do we need to specify the whole type name here ? It feels like a downgrade in readability
</blockquote></details>

Unfortunately, we do, as we're doing string comparisons. Unless we somehow hack storage onto arbitrary UIKit objects to store our structured `AccessibilityIdentifier` type, or else implement a parser to convert arbitrary strings from UIKit to whatever they plausibly came from, we're working in the string domain. Though there isn't a huge amount of this code, and perhaps a future solution could be a Swift macro to hide the boilerplate.
___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift` line 330 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-ODeCXG40WFHXlENv5sY:-ODejlZeAwiTHSuKgODR:b-fgymck) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aa969bfc4088eaab3917b8d5051712ffcb0f8f2/ios/MullvadVPN/View%20controllers/SelectLocation/LocationCell.swift#L330)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

If you have an idea, go for it :)
</blockquote></details>

I tried replacing that one with a `AccessibilityIdentifier.locationCell(RelayLocation)`, though bringing `MullvadTypes` into the dependencies caused building UI tests to fail with `Missing required module "WireGuardKitC"`. Is there an easy fix for this?
___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift` line 83 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-ODeD6r989R6UDBPcllo:-ODemQiL1AiupZ0zBbQh:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aa969bfc4088eaab3917b8d5051712ffcb0f8f2/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsCellFactory.swift#L83)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Is this planned work in an upcoming pr? Otherwise we should either do it here or remove the todo.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-09 12:45 UTC, rablador requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293)* status: all files reviewed, 4 unresolved discussions (waiting on @acb-mv and @buggmagnet)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift` line 330 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-ODeCXG40WFHXlENv5sY:-ODfRRqK4h8cMypCtnmf:bhhf9nq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aa969bfc4088eaab3917b8d5051712ffcb0f8f2/ios/MullvadVPN/View%20controllers/SelectLocation/LocationCell.swift#L330)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

I tried replacing that one with a `AccessibilityIdentifier.locationCell(RelayLocation)`, though bringing `MullvadTypes` into the dependencies caused building UI tests to fail with `Missing required module "WireGuardKitC"`. Is there an easy fix for this?
</blockquote></details>

I don't think so, although I'm not terribly confident in evaluating the dependency problems we have sometimes.
___
*[`ios/MullvadVPNUITests/Base/BaseUITestCase.swift` line 251 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-ODeDdaS0TywnwyWMsIq:-ODfRcFmD4RXatSw5SmY:b1fhh5r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aa969bfc4088eaab3917b8d5051712ffcb0f8f2/ios/MullvadVPNUITests/Base/BaseUITestCase.swift#L251)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Do we need to configure it to handle our custom `AccessibilityIdentifier` type?
</blockquote></details>

Not sure I understand what you mean. We don't need any extra handling for most (all?) of them, right? And if we do, perhaps we could just have make and exception for outliers.


<!-- Sent from Reviewable.io -->

2024-12-09 13:09 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293)* status: all files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPNUITests/Base/BaseUITestCase.swift` line 251 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-ODeDdaS0TywnwyWMsIq:-ODfVjjY5ThYjS6mfR7A:b-rv6tjv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aa969bfc4088eaab3917b8d5051712ffcb0f8f2/ios/MullvadVPNUITests/Base/BaseUITestCase.swift#L251)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Not sure I understand what you mean. We don't need any extra handling for most (all?) of them, right? And if we do, perhaps we could just have make and exception for outliers.
</blockquote></details>

Ah yes, I see. Done.


<!-- Sent from Reviewable.io -->

2024-12-09 13:10 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293)* status: 67 of 69 files reviewed, 4 unresolved discussions (waiting on @buggmagnet and @rablador)

___
*[`ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift` line 330 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-ODeCXG40WFHXlENv5sY:-ODfXUxnBUdBNGvzs8OQ:b-d4rr9y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/9aa969bfc4088eaab3917b8d5051712ffcb0f8f2/ios/MullvadVPN/View%20controllers/SelectLocation/LocationCell.swift#L330)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I don't think so, although I'm not terribly confident in evaluating the dependency problems we have sometimes.
</blockquote></details>

Fair enough. I'll consign this particular case statement to the too-hard basket for now, removing this comment, and stick to attaching types that don't come from dependency hell.


<!-- Sent from Reviewable.io -->

2024-12-09 15:36 UTC, acb-mv commented
Done. Nothing new appears to be broken.





<!-- Sent from Reviewable.io -->

2024-12-10 07:50 UTC, rablador approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293)* status: all files reviewed, 2 unresolved discussions (waiting on @buggmagnet)



<!-- Sent from Reviewable.io -->

2024-12-10 08:16 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7293#-:-ODjcxD41HBeGW9WZASN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-12-10 08:23 UTC, merged