Enable compilation with Swift 6 for most targets
mullvad/mullvadvpn-app pull request #7311
Opened 2024-12-10 13:05 UTC by buggmagnet

This PR enables us to compile most targets with Swift 6.0 except for all the targets that consume NetworkExtensions (duplicated symbols galore and other compilation issues that I want to solve later)

It mostly declares a lot of types as `Sendable` or disables strict concurrency checks in order to compile.
We will revisit the app piece by piece over time to remove all those `@unchecked Sendable` since most of the code is already working (as proven by shipping it, and not seeing crashes)

⚠️ We should not merge this PR before we move the CI to Xcode 16 because Xcode 15.0 does not support building with Swift 6.0 ⚠️

2024-12-11 08:40 UTC, mojganii requested changes
> Reviewed 5 of 294 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311)* status: 5 of 294 files reviewed, 1 unresolved discussion (waiting on @buggmagnet)

___
*[`ios/PacketTunnel/DeviceCheck/DeviceCheckOperation.swift` line 137 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311#-ODorrtg0eUot0A0ylzU:-ODorrtg0eUot0A0ylzV:blopw5g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db519d8059aee1d2f788e4c8ac335f2375f54ea2/ios/PacketTunnel/DeviceCheck/DeviceCheckOperation.swift#L137)):*
> ```Swift
>         dispatchGroup.enter()
>         let accountTask = remoteService.getAccountData(accountNumber: accountNumber) { result in
>             accountResult = result
> ```

I got this waring which is referring to the concurrency checking:
![Screenshot 2024-12-11 at 09.32.52.png](https://files.reviewableusercontent.io/images/reviewable/129863230/zjP87MHqubjNR52hLFWZzcwb/Screenshot%202024-12-11%20at%2009.32.52.png)


<!-- Sent from Reviewable.io -->

2024-12-11 10:20 UTC, acb-mv reviewed
> Reviewed 115 of 294 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311)* status: 115 of 294 files reviewed, 2 unresolved discussions (waiting on @buggmagnet)

___
*[`ios/MullvadREST/ApiHandlers/RESTTaskIdentifier.swift` line 13 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311#-ODlQZW53G2arTIt7c_B:-ODlQZW53G2arTIt7c_C:b1l0h95) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/db519d8059aee1d2f788e4c8ac335f2375f54ea2/ios/MullvadREST/ApiHandlers/RESTTaskIdentifier.swift#L13)):*
> ```Swift
> extension REST {
>     private static let nslock = NSLock()
>     nonisolated(unsafe) private static var taskCount: UInt32 = 0
> ```

Would it make sense to encapsulate this state into an Actor?


<!-- Sent from Reviewable.io -->

2025-01-08 14:18 UTC, rablador requested changes
> Reviewed 280 of 294 files at r1, 1 of 2 files at r2, 5 of 5 files at r3, 3 of 4 files at r4, 11 of 11 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311)* status: all files reviewed, 8 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @mojganii)

___
*[`ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` line 2 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311#-OG5GDHj9z_AZfmdNHBJ:-OG5GDHj9z_AZfmdNHBK:b-y691e6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d28dea623377ba1e979b8161645304fa73e2652f/ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L2)):*
> ```
> {
>   "originHash" : "c15149b2d59d9e9c72375f65339c04f41a19943e1117e682df27fc9f943fdc56",
> ```

Did this need to be updated or is it unintentional?
___
*[`ios/MullvadRESTTests/Mocks/AnyTransport.swift` line 9 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311#-OG5BAPQ55-4ujgOiRez:-OG5BAPQ55-4ujgOiRf-:bojzr4j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d28dea623377ba1e979b8161645304fa73e2652f/ios/MullvadRESTTests/Mocks/AnyTransport.swift#L9)):*
> ```Swift
> //
> 
> @preconcurrency import Foundation
> ```

Why do we need to add preconcurrency here?
___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksSectionHandler.swift` line 12 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311#-OG5D35nCXgm1txackb4:-OG5D35nCXgm1txackb5:bbq3ou6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d28dea623377ba1e979b8161645304fa73e2652f/ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksSectionHandler.swift#L12)):*
> ```Swift
> import UIKit
> 
> /// Type responsible for handling cells in socks table view section.
> ```

Why not turn the whole thing into an actor instead?
___
*[`ios/MullvadVPN/TunnelManager/SetAccountOperation.swift` line 111 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311#-OG5EBVV1vgR1d_jo3hJ:-OG5EBVV1vgR1d_jo3hK:bdalvnn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d28dea623377ba1e979b8161645304fa73e2652f/ios/MullvadVPN/TunnelManager/SetAccountOperation.swift#L111)):*
> ```Swift
>      Does nothing if device is already logged out.
>      */
>     private func startLogoutFlow(completion: @escaping @Sendable () -> Void) {
> ```

Are the sendable attribute on funcs necessary when the class is sendable?
___
*[`ios/PacketTunnelCore/Actor/PacketTunnelActor+Extensions.swift` line 9 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311#-OG5GiRL-ZSXjdHqqHc4:-OG5GiRL-ZSXjdHqqHc5:bddy03j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d28dea623377ba1e979b8161645304fa73e2652f/ios/PacketTunnelCore/Actor/PacketTunnelActor%2BExtensions.swift#L9)):*
> ```Swift
> //
> 
> @preconcurrency import Combine
> ```

Is combine not ready for concurrency?
___
*[`ios/MullvadVPN/Coordinators/Settings/SettingsCoordinator.swift` line 50 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311#-OG5ChnD6GyISbTAL7Tp:-OG5ChnD6GyISbTAL7Tq:b-b2xcdr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d28dea623377ba1e979b8161645304fa73e2652f/ios/MullvadVPN/Coordinators/Settings/SettingsCoordinator.swift#L50)):*
> ```Swift
>     private let interactorFactory: SettingsInteractorFactory
>     private var viewControllerFactory: SettingsViewControllerFactory?
>     private let accessMethodRepository: AccessMethodRepositoryProtocol
> ```

Why do we need these three as instance vars now?


<!-- Sent from Reviewable.io -->

2025-01-09 11:43 UTC, rablador requested changes
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311)* status: all files reviewed, 3 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @mojganii)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksSectionHandler.swift` line 12 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311#-OG5D35nCXgm1txackb4:-OG9rw065nG2aqR3Y2i2:b-ci7vc4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d28dea623377ba1e979b8161645304fa73e2652f/ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksSectionHandler.swift#L12)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

It doesn't need to ?

Declaring something to run on the main actor with `@MainActor` is not the same thing as turning a struct into an `actor`.
We have to be careful to not conflate two different concepts here.

In Swift 6.0 mode, everything that runs on the UI thread, or uses any API that is expected to run on the UI Thread is declared `@MainActor` and as such, should be declared to run on it.

This struct doesn't need any form of synchronisation, as it's only ever used on UI Thread.
</blockquote></details>

Sorry, I meant to declare it `@MainActor`.


<!-- Sent from Reviewable.io -->

2025-01-09 15:07 UTC, mojganii approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311#-:-OGAaozF9RrkovVR9_-m:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @acb-mv and @buggmagnet)



<!-- Sent from Reviewable.io -->

2025-01-10 13:41 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311)* status: 301 of 302 files reviewed, 3 unresolved discussions (waiting on @acb-mv, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksSectionHandler.swift` line 12 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311#-OG5D35nCXgm1txackb4:-OGFRal54AUZiEtt6bGa:b-m85e3q) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d28dea623377ba1e979b8161645304fa73e2652f/ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksSectionHandler.swift#L12)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Sorry, I meant to declare it `@MainActor`.
</blockquote></details>

Ah yes indeed !
Done !


<!-- Sent from Reviewable.io -->

2025-01-10 14:18 UTC, rablador requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311)* status: all files reviewed, 3 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @mojganii)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksSectionHandler.swift` line 12 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311#-OG5D35nCXgm1txackb4:-OGF_2gPBypZTEwHn9U9:brzyv0h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d28dea623377ba1e979b8161645304fa73e2652f/ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksSectionHandler.swift#L12)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Ah yes indeed !
Done !
</blockquote></details>

I believe there are more instances where this is true, so we could update all of them if you're up to it 🙃


<!-- Sent from Reviewable.io -->

2025-01-13 09:45 UTC, buggmagnet reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311)* status: all files reviewed, 3 unresolved discussions (waiting on @acb-mv, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksSectionHandler.swift` line 12 at r6](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311#-OG5D35nCXgm1txackb4:-OGU2OscABJFTM9Civvb:b-ymkb5l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/d28dea623377ba1e979b8161645304fa73e2652f/ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksSectionHandler.swift#L12)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I believe there are more instances where this is true, so we could update all of them if you're up to it 🙃
</blockquote></details>

I'd like to get it out of PR limbo but since I have to solve conflicts anyway, might as well add some more.... 🫠


<!-- Sent from Reviewable.io -->

2025-01-13 11:10 UTC, rablador approved these changes
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv and @mojganii)



<!-- Sent from Reviewable.io -->

2025-01-13 14:09 UTC, rablador approved these changes
> Reviewed 11 of 11 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv and @mojganii)



<!-- Sent from Reviewable.io -->

2025-01-14 10:10 UTC, rablador approved these changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7311)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv and @mojganii)



<!-- Sent from Reviewable.io -->

2025-01-14 10:49 UTC, merged