Implement gradle rust plugin
mullvad/mullvadvpn-app pull request #7319
Opened 2024-12-10 22:20 UTC by Pururun

Draft PR, very rough, mostly to spot any issues with CI, but feel free to review. :)

Things left to be decided:
- Can we use a symlink for the maybenot_machines? Will it work on windows?
- How do we handle the difference between debug/release? Currently we check if the starting task contains "release". This will break if we build debug and release at the same time. However I don't think we do this, so maybe it is an ok solution for now?
- Currently we only generate a new relays.json file if none exists or if it is a release build (see above for how we determine that). We could add further checks for maybe the age of the file or add a flag to force it to always build.
- How do we handle flags and local properties. We should avoid using the `local.properties` file, but what should we use instead?

2024-12-11 07:20 UTC, MarkusPettersson98 commented
> Things left to be decided:
> 
>     * Can we use a symlink for the maybenot_machines? Will it work on windows?
[This should no longer be needed](https://github.com/mullvad/mullvadvpn-app/pull/7158/files#diff-852897104c5cf350a945bb63cd9836c04ab5209a74900a1e8938092f6b9d68fb) if https://github.com/mullvad/mullvadvpn-app/pull/7158 is merged :blush:

2024-12-11 07:25 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/.gitignore` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-ODoaQgn6t2cxlxfRSAS:-ODoaQgn6t2cxlxfRSAT:bjdam9e) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceabdc7107bcd5da9e025ae778a85f0151f52b6b/android/.gitignore#L6)):*
> ```ignore
> local.properties
> # We want to generate relays.json not store it
> app/src/main/assets/relays.json
> ```

This seems applicable to all platforms! Should we move the ignore to the root `.gitignore`? :blush:



_Code quote:_
```ignore
# We want to generate relays.json not store it
app/src/main/assets/relays.json
```


<!-- Sent from Reviewable.io -->

2024-12-11 07:35 UTC, MarkusPettersson98 reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: 0 of 16 files reviewed, 5 unresolved discussions (waiting on @Pururun)

___
*[`wireguard-go-rs/build.rs` line 236 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-ODobmmDEat6ylFxLEgl:-ODobmmDEat6ylFxLEgm:b-1bz16w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceabdc7107bcd5da9e025ae778a85f0151f52b6b/wireguard-go-rs/build.rs#L236)):*
> ```XML
>     let mut move_command = Command::new("cp");
>     move_command
>         .arg("-p")
> ```

:pick: `move_command` should probably be renamed now that `cp` is used instead of `mv` :wink: 

Also, could we document why the `-p` flag is important? :pray:



_Code quote:_
```XML
    let mut move_command = Command::new("cp");
    move_command
        .arg("-p")
```
___
*[`android/build-apk.sh` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-ODobKOZ-S3tIxr7VuX0:-ODobKO_AyBi3v9luC-J:bx3i2gg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceabdc7107bcd5da9e025ae778a85f0151f52b6b/android/build-apk.sh#L21)):*
> ```Shell
> RUN_PLAY_PUBLISH_TASKS="no"
> PLAY_PUBLISH_TASKS=()
> SKIP_STRIPPING=${SKIP_STRIPPING:-"no"}
> ```

:pick: This seems to be unused (:tada:)



_Code quote:_
```Shell
SKIP_STRIPPING=${SKIP_STRIPPING:-"no"}
```
___
*[`android/build-apk.sh` line 56 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-ODocgUYDM6TtFudhWwD:-ODocgUYDM6TtFudhWwE:b7j9um0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceabdc7107bcd5da9e025ae778a85f0151f52b6b/android/build-apk.sh#L56)):*
> ```Shell
>     elif [[ "$PRODUCT_VERSION" == *"-alpha"* ]]; then
>         echo "Removing old Rust build artifacts"
>         cargo clean
> ```

Is the intention to get rid of all explicit invocations of `cargo` in this script? Is `cargo clean` run when invoking `gradlew clean`? :blush:



_Code quote:_
```Shell
        echo "Removing old Rust build artifacts"
        cargo clean
```
___
*[`android/build-apk.sh` line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-ODoct0T1EKUIWWPgHgt:-ODoct0T1EKUIWWPgHgu:bb7eybp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceabdc7107bcd5da9e025ae778a85f0151f52b6b/android/build-apk.sh#L61)):*
> ```Shell
>         PLAY_PUBLISH_TASKS=(publishPlayStagemoleReleaseBundle)
>     else
>         cargo clean
> ```

dito



_Code quote:_
```Shell
cargo clean
```


<!-- Sent from Reviewable.io -->

2024-12-11 08:02 UTC, Pururun reviewed
That is great. :)

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-:-ODohJEd9icnts6ee1Aa:barr9l8)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`wireguard-go-rs/build.rs` line 236 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-ODobmmDEat6ylFxLEgl:-ODoghB31UFoWc6eV31e:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceabdc7107bcd5da9e025ae778a85f0151f52b6b/wireguard-go-rs/build.rs#L236)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

:pick: `move_command` should probably be renamed now that `cp` is used instead of `mv` :wink: 

Also, could we document why the `-p` flag is important? :pray:
</blockquote></details>

Done
___
*[`android/build-apk.sh` line 21 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-ODobKOZ-S3tIxr7VuX0:-ODofulV9vvV4XGGfXcV:b8bi1j8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceabdc7107bcd5da9e025ae778a85f0151f52b6b/android/build-apk.sh#L21)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

:pick: This seems to be unused (:tada:)
</blockquote></details>

Nice catch!. Removed.
___
*[`android/build-apk.sh` line 56 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-ODocgUYDM6TtFudhWwD:-ODofyg55_XpLKtOburc:b91wkwh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceabdc7107bcd5da9e025ae778a85f0151f52b6b/android/build-apk.sh#L56)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

Is the intention to get rid of all explicit invocations of `cargo` in this script? Is `cargo clean` run when invoking `gradlew clean`? :blush:
</blockquote></details>

`Cargo clean` is not invoked when running `gradle clean`. Maybe we want to do it, I'll add it to the list.


<!-- Sent from Reviewable.io -->

2024-12-11 18:56 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: 0 of 17 files reviewed, 3 unresolved discussions (waiting on @MarkusPettersson98)

___
*[`android/.gitignore` line 6 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-ODoaQgn6t2cxlxfRSAS:-ODr3DfXAOUa29g30Vhp:bv71mjz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceabdc7107bcd5da9e025ae778a85f0151f52b6b/android/.gitignore#L6)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

This seems applicable to all platforms! Should we move the ignore to the root `.gitignore`? :blush:
</blockquote></details>

We decided to move the file back into build so it will be ignored.


<!-- Sent from Reviewable.io -->

2024-12-18 18:37 UTC, Rawa requested changes
> Reviewed 7 of 16 files at r1, 2 of 4 files at r3, 2 of 4 files at r7, 2 of 5 files at r8, 2 of 5 files at r9, 2 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: all files reviewed, 12 unresolved discussions (waiting on @MarkusPettersson98 and @Pururun)

___
*[`android/app/build.gradle.kts` line 298 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ1Wt43hQguCZnVhzB:-OEQ1Wt43hQguCZnVhzC:b9hotq3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/app/build.gradle.kts#L298)):*
> ```Kotlin
>         }
>     }
>     exec = { spec, _ -> println(spec.commandLine) }
> ```

Should maybe remove?
___
*[`android/app/build.gradle.kts` line 315 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ252c9FgEzpFJNICc:-OEQ252c9FgEzpFJNICd:b-dhrncz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/app/build.gradle.kts#L315)):*
> ```Kotlin
>         val output = standardOutput as ByteArrayOutputStream
>         // Create file if needed
>         File("$extraAssetsDirectory").mkdirs()
> ```

Should we reference parent of `relayListPath` maybe?
___
*[`android/app/build.gradle.kts` line 317 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ1rqy-bNGP8zyAeQQ:-OEQ1rqz4QUS8XscViZO:b-4ijidg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/app/build.gradle.kts#L317)):*
> ```Kotlin
>         File("$extraAssetsDirectory").mkdirs()
>         File("$extraAssetsDirectory/relays.json").createNewFile()
>         FileOutputStream("$extraAssetsDirectory/relays.json").use { it.write(output.toByteArray()) }
> ```

We should reuse the `relayListPath` here, right now we seem to construct it multiple times.
___
*[`android/app/build.gradle.kts` line 320 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ2GZo5qYV-FFss-1g:-OEQ2GZo5qYV-FFss-1h:be9z4ji) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/app/build.gradle.kts#L320)):*
> ```Kotlin
> 
>         // Old ensure exists tasks
>         if (!relayListPath.exists()) {
> ```

Does this serve any purpose? Shouldn't it exist if the thing above successfully ran?
___
*[`android/app/build.gradle.kts` line 327 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ2NygEg7FbXHkmA6N:-OEQ2NygEg7FbXHkmA6O:buey4jc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/app/build.gradle.kts#L327)):*
> ```Kotlin
> 
> fun isReleaseBuild() =
>     gradle.startParameter.getTaskNames().any { it.contains("release", ignoreCase = true) }
> ```

We probably should add a comment and DROID-X issue link to something in our backlog to address this at some point, or what do you think?
___
*[`android/build.gradle.kts` line 21 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ159p0x7fYTibns3f:-OEQ159p0x7fYTibns3g:b-vh8h7l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/build.gradle.kts#L21)):*
> ```Kotlin
>     alias(libs.plugins.detekt) apply true
>     alias(libs.plugins.dependency.versions) apply true
> ```

Nit: remove whitespace
___
*[`android/build.gradle.kts` line 74 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ1Cbr5WTpIMURM45p:-OEQ1Cbr5WTpIMURM45q:b-wxqijn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/build.gradle.kts#L74)):*
> ```Kotlin
>         classpath("$prebuilt:macos-x86_64@tar.gz")
> 
>         classpath("org.mozilla.rust-android-gradle:plugin:${libs.versions.rust.android.gradle}")
> ```

Should this also be extracted to some toml file??
___
*[`wireguard-go-rs/build.rs` line 174 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ2gsfD22m23RFcitL:-OEQ2gsfD22m23RFcitM:bgmbgqw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/wireguard-go-rs/build.rs#L174)):*
> ```XML
>     // or if the libwg.so file has been changed. The latter is required since the
>     // libwg.so file could be deleted. It however means that this build will need
>     // to run two times before it is properly cached.
> ```

We should probably add some issue to track this post merging this. Unless we have any idea on how we can make this work for real.
___
*[`.github/workflows/android-app.yml` line 171 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ-vkS4WyRQh52PYf1:-OEQ-vkS4WyRQh52PYf2:bz39t70) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/.github/workflows/android-app.yml#L171)):*
> ```YAML
>           - arch: "armv7"
>             abi: "armeabi-v7a"
>             taskVariant: "Arm"
> ```

Generally we seem to name the keys with dashes instead of camelCase, should we change?


<!-- Sent from Reviewable.io -->

2024-12-18 18:46 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: all files reviewed, 14 unresolved discussions (waiting on @MarkusPettersson98 and @Pururun)

___
*[`android/build-apk.sh` line 64 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ4j2y3MKKQU_PtU0F:-OEQ4j2y3MKKQU_PtU0G:b-ddb2rn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/build-apk.sh#L64)):*
> ```Shell
> fi
> 
> pushd "$SCRIPT_DIR"
> ```

We should already be in the correct folder I believe so we should be able to remove this `pushd` & `popd` below,
___
*[`android/app/build.gradle.kts` line 332 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ4AqB6BKTpbBs5EWQ:-OEQ4AqB6BKTpbBs5EWR:b-ogswdv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/app/build.gradle.kts#L332)):*
> ```Kotlin
>     val localProperties = gradleLocalProperties(rootProject.projectDir, providers)
>     val versionName = generateVersionName(localProperties)
>     return versionName.contains("dev", ignoreCase = true) ||
> ```

Does it make sense to ignore case? Or would it better to safeg


<!-- Sent from Reviewable.io -->

2024-12-19 08:36 UTC, MarkusPettersson98 reviewed
> Reviewed 3 of 16 files at r1, 1 of 4 files at r3, 1 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: all files reviewed, 11 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[`wireguard-go-rs/build.rs` line 236 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-ODobmmDEat6ylFxLEgl:-OET1xE6DTtbpXYD2uE2:b-94pq6n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceabdc7107bcd5da9e025ae778a85f0151f52b6b/wireguard-go-rs/build.rs#L236)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done
</blockquote></details>

:pick: It should say `-p`, not `P`. `p` and `P` are different flags in `cp`

Also, it would be nice if the comment would mention that we use `cp -p` because we want to preserve ownership & timestamp to not re-trigger `cargo` accidentally :)
___
*[`wireguard-go-rs/build.rs` line 174 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ2gsfD22m23RFcitL:-OET1_O04ff5kQGr3h-h:b-h0ofsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/wireguard-go-rs/build.rs#L174)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should probably add some issue to track this post merging this. Unless we have any idea on how we can make this work for real.
</blockquote></details>

I agree. Also, I think this deserves to be prefixed with "FIXME" to stand out more / increase grep-ability.


<!-- Sent from Reviewable.io -->

2024-12-19 10:59 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: 17 of 18 files reviewed, 10 unresolved discussions (waiting on @Rawa)

___
*[`.github/workflows/android-app.yml` line 171 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ-vkS4WyRQh52PYf1:-OETUsvDAsrUq6wbpUvB:b8gj3mz) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/.github/workflows/android-app.yml#L171)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Generally we seem to name the keys with dashes instead of camelCase, should we change?
</blockquote></details>

Good catch, fixed.
___
*[`android/app/build.gradle.kts` line 298 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ1Wt43hQguCZnVhzB:-OETWH6P3XwJMWC7nko7:b1k18wk) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/app/build.gradle.kts#L298)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should maybe remove?
</blockquote></details>

Indeed, we could add it again if we need for testing purposes
___
*[`android/app/build.gradle.kts` line 317 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ1rqy-bNGP8zyAeQQ:-OETWcoK-cZVrDWtR6um:b569x0r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/app/build.gradle.kts#L317)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should reuse the `relayListPath` here, right now we seem to construct it multiple times.
</blockquote></details>

Yes fixed!
___
*[`android/app/build.gradle.kts` line 320 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ2GZo5qYV-FFss-1g:-OETWe-l9VmqatR5lLDk:b-mu9na7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/app/build.gradle.kts#L320)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Does this serve any purpose? Shouldn't it exist if the thing above successfully ran?
</blockquote></details>

Yeah I'll remove it.
___
*[`android/app/build.gradle.kts` line 327 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ2NygEg7FbXHkmA6N:-OETWxtw6ClNIOKNp-3h:b-n1hznw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/app/build.gradle.kts#L327)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We probably should add a comment and DROID-X issue link to something in our backlog to address this at some point, or what do you think?
</blockquote></details>

Yes will create an issue.
___
*[`android/app/build.gradle.kts` line 332 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ4AqB6BKTpbBs5EWQ:-OETYIaG5Jw-U7aIH3Fr:b-58m0r2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/app/build.gradle.kts#L332)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Does it make sense to ignore case? Or would it better to safeg
</blockquote></details>

Was a copy paste from the releaes build check, will remove the ignore case.
___
*[`wireguard-go-rs/build.rs` line 236 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-ODobmmDEat6ylFxLEgl:-OETZUd68RhBnyZtA3mo:b-2zp6hi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceabdc7107bcd5da9e025ae778a85f0151f52b6b/wireguard-go-rs/build.rs#L236)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

:pick: It should say `-p`, not `P`. `p` and `P` are different flags in `cp`

Also, it would be nice if the comment would mention that we use `cp -p` because we want to preserve ownership & timestamp to not re-trigger `cargo` accidentally :)
</blockquote></details>

Updated text!
___
*[`wireguard-go-rs/build.rs` line 174 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ2gsfD22m23RFcitL:-OETY_gG9ER04l2kSfSM:b-cmyqia) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/wireguard-go-rs/build.rs#L174)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

I agree. Also, I think this deserves to be prefixed with "FIXME" to stand out more / increase grep-ability.
</blockquote></details>

Created issue and added FIXME.
___
*[`android/build-apk.sh` line 61 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-ODoct0T1EKUIWWPgHgt:-OETVd072BBeNjJP7YRg:b9azmrh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/ceabdc7107bcd5da9e025ae778a85f0151f52b6b/android/build-apk.sh#L61)):*
<details><summary><i>Previously, MarkusPettersson98 (Markus Pettersson) wrote…</i></summary><blockquote>

dito
</blockquote></details>

Removed! It will now always clean cargo.
___
*[`android/build-apk.sh` line 64 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ4j2y3MKKQU_PtU0F:-OETVph1BRUpFgju_Nyz:bss4a1y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/build-apk.sh#L64)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should already be in the correct folder I believe so we should be able to remove this `pushd` & `popd` below,
</blockquote></details>

Removed!


<!-- Sent from Reviewable.io -->

2024-12-19 11:13 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: 13 of 18 files reviewed, 10 unresolved discussions (waiting on @MarkusPettersson98 and @Rawa)

___
*[`android/build.gradle.kts` line 74 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ1Cbr5WTpIMURM45p:-OETb3zdCB7nQqhDnHwJ:btzifna) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/build.gradle.kts#L74)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should this also be extracted to some toml file??
</blockquote></details>

Probably, could not really find a good way to do this?
___
*[`android/app/build.gradle.kts` line 315 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ252c9FgEzpFJNICc:-OETZgZM9gAOal5pLplj:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/app/build.gradle.kts#L315)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Should we reference parent of `relayListPath` maybe?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-12-19 11:49 UTC, Rawa requested changes
> Reviewed 3 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: 17 of 18 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/build.gradle.kts` line 315 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEQ252c9FgEzpFJNICc:-OETjh3I6InY74FdPfoN:b6514kf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/5c4a2cba0f034a37ad4ac9d58da5f1685942429a/android/app/build.gradle.kts#L315)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Seems like we set it to`extraAssetsDirectory` not `relayListPath.parent()`. This has the implicit dependency of relayListPath being a direct child of `extraAssetsDirectory`.
___
*[`android/app/build.gradle.kts` line 322 at r13](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OETk6Ea9gYwuM1E9aG8:-OETk6Ea9gYwuM1E9aG9:b-s746r3) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69a277af3d6f04eef1c22e90a99137c55e96c70c/android/app/build.gradle.kts#L322)):*
> ```Kotlin
> tasks.register<Exec>("cargoClean") {
>     workingDir = File(repoRootPath)
>     commandLine("cargo", "clean")
> ```

:star2: 


<!-- Sent from Reviewable.io -->

2024-12-19 11:55 UTC, albin-mullvad reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @Pururun and @Rawa)

___
*[a discussion](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OETlKIh9nBlSjUf8Iyk:-OETlKIi-V-2D6kAi62n:b81pm1c) (no related file):*
Can we rename `android/build-apk.sh` to `android/build.sh`?


<!-- Sent from Reviewable.io -->

2024-12-19 13:37 UTC, albin-mullvad reviewed
> Reviewed 3 of 16 files at r1, 2 of 4 files at r7, 1 of 5 files at r8, 3 of 7 files at r14, 3 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: 14 of 19 files reviewed, 3 unresolved discussions (waiting on @Pururun and @Rawa)



<!-- Sent from Reviewable.io -->

2024-12-19 13:47 UTC, Rawa submitted a review, later dismissed
> Reviewed 2 of 5 files at r13, 3 of 7 files at r14, 5 of 5 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2024-12-20 08:26 UTC, Rawa submitted a review, later dismissed
> Reviewed 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2024-12-20 12:18 UTC, albin-mullvad requested changes
> Reviewed 1 of 3 files at r10, 2 of 5 files at r13, 1 of 7 files at r14, 1 of 5 files at r15, 1 of 1 files at r16, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: all files reviewed, 4 unresolved discussions (waiting on @Pururun)

___
*[`wireguard-go-rs/build.rs` line 235 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEYx2B8C403z8glWDNU:-OEYx2B8C403z8glWDNV:bj329v) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e04ac290e231d5039e78e7e09aa7949e618dc8c/wireguard-go-rs/build.rs#L235)):*
> ```XML
>     std::fs::create_dir_all(parent_of_output)?;
> 
>     let mut copy_command = Command::new("cp");
> ```

Is there any way we could avoid the copy? Asking since a copy is usually much more experience.
___
*[`wireguard-go-rs/build.rs` line 237 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEYwr_k2KI5xqtgk7TH:-OEYwr_k2KI5xqtgk7TI:b-61cleg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e04ac290e231d5039e78e7e09aa7949e618dc8c/wireguard-go-rs/build.rs#L237)):*
> ```XML
>     let mut copy_command = Command::new("cp");
>     // -p command is required to preserve ownership and timestamp of the file to prevent a
>     // rebuild of this module everytime.
> ```

nit: `every time`



_Code quote:_
```XML
everytime
```
___
*[`.github/workflows/android-app.yml` line 132 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEUXxdP8D1pYVy2Bl6v:-OEUXxdP8D1pYVy2Bl6w:b-94l42h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/99f37a3ffd1cad8487d0da037bc6576d03603d5f/.github/workflows/android-app.yml#L132)):*
> ```YAML
>       - name: Generate
>         if: steps.cache-relay-list.outputs.cache-hit != 'true'
>         uses: burrunan/gradle-cache-action@v1
> ```

I suggest we skip using the cache action here unless we see a lot of value in keeping it. The relay list will be cached on a daily basis (see `cache-relay-list`) so this should only run once a day unless the caching mechnaism is broken.
___
*[`.github/workflows/android-app.yml` line 158 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEUXZB2EUOxkddpWTrR:-OEUXZB2EUOxkddpWTrS:bchlq05) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/99f37a3ffd1cad8487d0da037bc6576d03603d5f/.github/workflows/android-app.yml#L158)):*
> ```YAML
>       image: "${{ needs.prepare.outputs.container_image }}"
>     strategy:
>       matrix:
> ```

Can this matrix be simplified a bit or are all values needed?


<!-- Sent from Reviewable.io -->

2024-12-20 12:47 UTC, albin-mullvad reviewed
> Reviewed 1 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: all files reviewed, 6 unresolved discussions (waiting on @Pururun)

___
*[`android/app/build.gradle.kts` line 270 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEZ5XFA-67yxMjiEs0r:-OEZ5XFA-67yxMjiEs0s:bffudbb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e04ac290e231d5039e78e7e09aa7949e618dc8c/android/app/build.gradle.kts#L270)):*
> ```Kotlin
>     // https://github.com/mozilla/rust-android-gradle/tree/master?tab=readme-ov-file#targets
>     targets =
>         gradleLocalProperties(rootProject.projectDir, providers)
> ```

I believe we want to avoid `local.properties`: https://linear.app/mullvad/issue/DROID-1430/rework-localproperties-and-e2eproperties

I guess it's fine to not address now if too much work
___
*[`android/app/build.gradle.kts` line 300 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEZ4cPe2VUvKPHBwUoN:-OEZ4cPe2VUvKPHBwUoO:b-nj8y53) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e04ac290e231d5039e78e7e09aa7949e618dc8c/android/app/build.gradle.kts#L300)):*
> ```Kotlin
> 
>     // Set this if you get a cargo not found error
>     // environment =
> ```

Can we elaborate a bit here? What would we set it to and are there any relevant internal or external issues we can link to?



_Code quote:_
```Kotlin
    // Set this if you get a cargo not found error
    // environment =
```


<!-- Sent from Reviewable.io -->

2024-12-20 14:47 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)

___
*[`.github/workflows/android-app.yml` line 158 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEUXZB2EUOxkddpWTrR:-OEZVvYiChHQU_DDJaKo:b-w34tyh) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/99f37a3ffd1cad8487d0da037bc6576d03603d5f/.github/workflows/android-app.yml#L158)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can this matrix be simplified a bit or are all values needed?
</blockquote></details>

Removed arch as it is no longer needed.
___
*[`android/app/build.gradle.kts` line 270 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEZ5XFA-67yxMjiEs0r:-OEZWfIL6aQLutUSwtxW:bjrgyho) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e04ac290e231d5039e78e7e09aa7949e618dc8c/android/app/build.gradle.kts#L270)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe we want to avoid `local.properties`: https://linear.app/mullvad/issue/DROID-1430/rework-localproperties-and-e2eproperties

I guess it's fine to not address now if too much work
</blockquote></details>

We decided to keep using `local.properties` as the plugin is still using it and it would make more sense to have them at the same place. We should probably have some kind issue for moving them in the future though.
___
*[`android/app/build.gradle.kts` line 300 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEZ4cPe2VUvKPHBwUoN:-OEZWzB0AnwStTRvUahZ:bx6ixgy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e04ac290e231d5039e78e7e09aa7949e618dc8c/android/app/build.gradle.kts#L300)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can we elaborate a bit here? What would we set it to and are there any relevant internal or external issues we can link to?
</blockquote></details>

There is a potential issue with Android Studio and environment variables, but that should not be documented here. Removed.
___
*[`wireguard-go-rs/build.rs` line 237 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEYwr_k2KI5xqtgk7TH:-OEZXJYN9sEdV8KSE-2H:bb6un1j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e04ac290e231d5039e78e7e09aa7949e618dc8c/wireguard-go-rs/build.rs#L237)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: `every time`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2025-01-07 13:17 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: 16 of 19 files reviewed, 2 unresolved discussions (waiting on @albin-mullvad, @MarkusPettersson98, and @Rawa)

___
*[`.github/workflows/android-app.yml` line 132 at r19](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEUXxdP8D1pYVy2Bl6v:-OG-uO-470svrD6YMYtb:b5q6fo6) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/99f37a3ffd1cad8487d0da037bc6576d03603d5f/.github/workflows/android-app.yml#L132)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I suggest we skip using the cache action here unless we see a lot of value in keeping it. The relay list will be cached on a daily basis (see `cache-relay-list`) so this should only run once a day unless the caching mechnaism is broken.
</blockquote></details>

Replaced with normal grade task.
___
*[`wireguard-go-rs/build.rs` line 235 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEYx2B8C403z8glWDNU:-OG-Otjs1Eq-LVSyXDYw:b-48uuqd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e04ac290e231d5039e78e7e09aa7949e618dc8c/wireguard-go-rs/build.rs#L235)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Is there any way we could avoid the copy? Asking since a copy is usually much more experience.
</blockquote></details>

As far as we could tell not, since if we don't use copy it will always rebuild.


<!-- Sent from Reviewable.io -->

2025-01-07 14:19 UTC, Rawa submitted a review, later dismissed
> Reviewed 2 of 3 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)



<!-- Sent from Reviewable.io -->

2025-01-07 20:38 UTC, albin-mullvad submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-:-OG1UFEL6r-dl8CWQf90:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/app/build.gradle.kts` line 270 at r20](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OEZ5XFA-67yxMjiEs0r:-OG0O63EDmGeYSnq2O_p:b-pbcoz7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/4e04ac290e231d5039e78e7e09aa7949e618dc8c/android/app/build.gradle.kts#L270)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

We decided to keep using `local.properties` as the plugin is still using it and it would make more sense to have them at the same place. We should probably have some kind issue for moving them in the future though.
</blockquote></details>

Alright! :thumbsup: 


<!-- Sent from Reviewable.io -->

2025-01-08 09:25 UTC, Rawa submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-:-OG4DoqqA5Py0p6wWTGl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-08 09:34 UTC, albin-mullvad requested changes
> Reviewed 4 of 4 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`building/android-container-image.txt` line 1 at r23](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OG4Fp-02kbFNRQveLXn:-OG4Fp-02kbFNRQveLXo:b-2ysomj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c7873384ae6f10adfca5cdbdb51612aff87763a6/building/android-container-image.txt#L1)):*
> ```help
> ghcr.io/mullvad/mullvadvpn-app-build-android:3ac5745b0
> ```

Bad EOF according to reviewable


<!-- Sent from Reviewable.io -->

2025-01-08 09:54 UTC, Pururun reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @albin-mullvad and @Rawa)

___
*[`building/android-container-image.txt` line 1 at r23](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-OG4Fp-02kbFNRQveLXn:-OG4KRer8dzwYa35ylVL:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c7873384ae6f10adfca5cdbdb51612aff87763a6/building/android-container-image.txt#L1)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Bad EOF according to reviewable
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2025-01-08 09:59 UTC, albin-mullvad approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7319#-:-OG4L_qH9od7cVgcQlU4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-08 10:03 UTC, merged

2025-01-08 10:53 UTC, Crazy-9669 commented
В

ср, 8 янв. 2025 г., 13:04 Jonatan Rhodin ***@***.***>:

> Merged #7319 <https://github.com/mullvad/mullvadvpn-app/pull/7319> into
> main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mullvad/mullvadvpn-app/pull/7319#event-15851238564>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BE55V3WSI7QUZBAB542ZI3T2JTZ2RAVCNFSM6AAAAABTMFEV7KVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJVHA2TCMRTHA2TMNA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>