Migrate remaining e2e tests to POP
mullvad/mullvadvpn-app pull request #7332
Opened 2024-12-12 08:41 UTC by niklasberglund

`LoginTest` and `ConnectionTest` was migrated since before. This PR migrates remaining end to end tests to use Page Object Pattern.

2024-12-12 09:42 UTC, Pururun requested changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/WireGuardCustomPortModal.kt` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332#-ODuEIXFB8-O_P4uSXHh:-ODuEIXFB8-O_P4uSXHi:b1a0azr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69604c257a49f824ea382e7294f06d4822be386e/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/WireGuardCustomPortModal.kt#L6)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.test.common.extension.findObjectWithTimeout
> 
> class WireGuardCustomPortModal internal constructor() : Page() {
> ```

Modal feels very iOS, but maybe it is something commonly used when using POC? Otherwise I think dialog is fine.


<!-- Sent from Reviewable.io -->

2024-12-12 10:06 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @Pururun)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/WireGuardCustomPortModal.kt` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332#-ODuEIXFB8-O_P4uSXHh:-ODuK-D97PJnF01FnFH2:b6c5rvg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69604c257a49f824ea382e7294f06d4822be386e/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/WireGuardCustomPortModal.kt#L6)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Modal feels very iOS, but maybe it is something commonly used when using POC? Otherwise I think dialog is fine.
</blockquote></details>

Right, it is also called `CustomPortDialog` in the app code so that's a better name. Renamed to `WireGuardCustomPortDialog`.


<!-- Sent from Reviewable.io -->

2024-12-12 10:21 UTC, Pururun submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332#-:-ODuNhoCC8BiH_rYN2P9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/WireGuardCustomPortModal.kt` line 6 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332#-ODuEIXFB8-O_P4uSXHh:-ODuNdWGByiVE90H7TTC:b-8fx2u7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/69604c257a49f824ea382e7294f06d4822be386e/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/WireGuardCustomPortModal.kt#L6)):*
<details><summary><i>Previously, niklasberglund (Niklas Berglund) wrote…</i></summary><blockquote>

Right, it is also called `CustomPortDialog` in the app code so that's a better name. Renamed to `WireGuardCustomPortDialog`.
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2024-12-12 14:01 UTC, Rawa requested changes
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/WebLinkTest.kt` line 20 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332#-ODvAA8j8dcMpQlHq-1Y:-ODvAA8kDWIskeYS1tj5:b-tj2c3h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/830fb47462adb998928e5432bee39e17402f2436/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/WebLinkTest.kt#L20)):*
> ```Kotlin
>         on<SettingsPage> { clickFaqAndGuides() }
> 
>         on<MullvadWebsite> {}
> ```

Same here `on<MullvadWebsite>()`
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LogoutTest.kt` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332#-ODvA0ot1agT2ZZO_fsP:-ODvA0ot1agT2ZZO_fsQ:b-5gdrj9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/830fb47462adb998928e5432bee39e17402f2436/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LogoutTest.kt#L24)):*
> ```Kotlin
>         on<AccountPage> { clickLogOut() }
> 
>         on<LoginPage> {}
> ```

nit: I believe we could just write `on<LoginPage>()`


<!-- Sent from Reviewable.io -->

2024-12-13 08:41 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @Pururun and @Rawa)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LogoutTest.kt` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332#-ODvA0ot1agT2ZZO_fsP:-ODzAQhe6DHNnn_Dd0gp:b-tt00xv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/830fb47462adb998928e5432bee39e17402f2436/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LogoutTest.kt#L24)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

nit: I believe we could just write `on<LoginPage>()`
</blockquote></details>

Removed `{}` 
___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/WebLinkTest.kt` line 20 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332#-ODvAA8j8dcMpQlHq-1Y:-ODzAUfBBRX9YtWefzG3:b-tt00xv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/830fb47462adb998928e5432bee39e17402f2436/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/WebLinkTest.kt#L20)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Same here `on<MullvadWebsite>()`
</blockquote></details>

Removed `{}` 


<!-- Sent from Reviewable.io -->

2024-12-13 10:19 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332)* status: all files reviewed, 1 unresolved discussion (waiting on @Rawa)

___
*[`android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LogoutTest.kt` line 24 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332#-ODvA0ot1agT2ZZO_fsP:-ODzN3Py-rMvcU_aP6ME:b-1z0gm4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/830fb47462adb998928e5432bee39e17402f2436/android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LogoutTest.kt#L24)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I believe this won't compile, you need the `()`
</blockquote></details>

You are absolutely right, now the build and tests are passing 👍


<!-- Sent from Reviewable.io -->

2024-12-13 10:30 UTC, Rawa approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-13 14:41 UTC, merged