Use stagemole with e2e tests
mullvad/mullvadvpn-app pull request #7343
Opened 2024-12-13 12:23 UTC by niklasberglund

Using stagemole for e2e tests by default. Can optionally specify to use prod. Artefacts will be uploaded if testing with stagemole.

Also added very basic error handling for 429 rate limited error responses(very basic since we probably will migrate to ktor) and moved pulling of outputs from `run-instrumented-tests.sh` to the workflow, so that artefacts are uploaded even if the run is cancelled or tests step time out. Fixes DROID-1635

2024-12-13 14:51 UTC, Pururun submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-:-OE-V6283xhLsfCWMA_t:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-17 14:47 UTC, albin-mullvad requested changes
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: all files reviewed, 7 unresolved discussions (waiting on @niklasberglund)

___
*[`android/scripts/run-instrumented-tests.sh` line 112 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEK2H2_-WWI_YdM7Kr0:-OEK2H2_-WWI_YdM7Kr1:bkijqyl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/15fc4f927f9a05ca88563f8d7ead79f9f7c7e807/android/scripts/run-instrumented-tests.sh#L112)):*
> ```Shell
>         echo "Error: The 'e2e' test type with billing flavor 'play' require infra flavor 'stagemole'."
>         exit 1
>     elif [[ $BILLING_FLAVOR == "oss" && $INFRA_FLAVOR != "prod" ]]; then
> ```

Should this block really be removed? Didn't we say to keep using the play build? :thinking: 
___
*[`.github/workflows/android-app.yml` line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEK-IufCQ9UgRNuJ5kC:-OEK-IufCQ9UgRNuJ5kD:bfwy2do) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b067b083b2a1ac419e2cf3bc894cb6e17ecb6435/.github/workflows/android-app.yml#L51)):*
> ```YAML
>       e2e_tests_infra_flavor:
>         description: >
>           Infra environment to run e2e tests on(prod/stagemole).
> ```

nit: add space `on (prod/stagemole)`



_Code quote:_
```YAML
on(prod/stagemole).
```
___
*[`.github/workflows/android-app.yml` line 351 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEK-ZZID9jIyGgemorW:-OEK-ZZID9jIyGgemorX:bc2uum2) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b067b083b2a1ac419e2cf3bc894cb6e17ecb6435/.github/workflows/android-app.yml#L351)):*
> ```YAML
>       - name: Build stagemole app
>         uses: burrunan/gradle-cache-action@v1
>         if: github.event.inputs.e2e_test_repeat != '0'
> ```

Can we check `e2e_tests_infra_flavor` instead?



_Code quote:_
```YAML
github.event.inputs.e2e_test_repeat != '0'
```
___
*[`.github/workflows/android-app.yml` line 494 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEK3pB-30f_SePPoYNG:-OEK3pB-30f_SePPoYNH:bpnv3qw) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b067b083b2a1ac419e2cf3bc894cb6e17ecb6435/.github/workflows/android-app.yml#L494)):*
> ```YAML
>       - name: Upload instrumentation report (${{ matrix.test-type }})
>         uses: actions/upload-artifact@v4
>         if: always() && matrix.test-repeat != 0 && github.event.inputs.e2e_tests_infra_flavor == 'stagemole'
> ```

Do we need this check? These tests doesn't include anything sensitive since it's only used for isolated tests atm (unless we decide to merge `instrumented-tests` & `instrumented-e2e-tests`



_Code quote:_
```YAML
 && github.event.inputs.e2e_tests_infra_flavor == 'stagemole'
```
___
*[`.github/workflows/android-app.yml` line 501 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEK2vL_-82bYVobE22R:-OEK2vLa91fYNG887s6Y:bug75ze) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b067b083b2a1ac419e2cf3bc894cb6e17ecb6435/.github/workflows/android-app.yml#L501)):*
> ```YAML
>           retention-days: 7
> 
>   instrumented-e2e-tests:
> ```

Could it make sense to merge this one with `instrumented-tests` now that the difference between the two is less than before? I believe the main thing to consider is that we would only want to set some of the `env` variables for the e2e tests (such as `PARTNER_AUTH`).



_Code quote:_
```YAML
instrumented-e2e-tests
```
___
*[`android/scripts/pull-test-output.sh` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEK1Hn5BhQ1-qg_sGNf:-OEK1Hn5BhQ1-qg_sGNg:b-ukjezy) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b067b083b2a1ac419e2cf3bc894cb6e17ecb6435/android/scripts/pull-test-output.sh#L35)):*
> ```Shell
> LOCAL_LOGCAT_FILE_PATH="$REPORT_DIR/logcat.txt"
> LOCAL_SCREENSHOT_PATH="$REPORT_DIR/screenshots"
> LOCAL_TEST_ARRACHMENTS_PATH="$REPORT_DIR/test-attachments"
> ```

Would be really nice if we could just have a single on-device path for all this content such as `/sdcard/test-report` that we just pull recursively into `$REPORT_DIR` instead of a bunch of paths that we now have to keep track of in two different scripts. But probably a bit out-of-scope for this PR...



_Code quote:_
```Shell
DEVICE_SCREENSHOT_PATH="/sdcard/Pictures/mullvad-$TEST_TYPE"
DEVICE_TEST_ATTACHMENTS_PATH="/sdcard/Download/test-attachments"
LOCAL_LOGCAT_FILE_PATH="$REPORT_DIR/logcat.txt"
LOCAL_SCREENSHOT_PATH="$REPORT_DIR/screenshots"
LOCAL_TEST_ARRACHMENTS_PATH="$REPORT_DIR/test-attachments"
```
___
*[`android/scripts/pull-test-output.sh` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEK0_HCDL5AECM_DTyp:-OEK0_HCDL5AECM_DTyq:bs5dff0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b067b083b2a1ac419e2cf3bc894cb6e17ecb6435/android/scripts/pull-test-output.sh#L38)):*
> ```Shell
> 
> echo "Collecting report and produced test attachments..."
> adb logcat -d > "$LOCAL_LOGCAT_FILE_PATH"
> ```

The other script that runs the tests should probably be responsible for dumping the logcat content into a file on the device. This script can then be responsible for downloading that file.



_Code quote:_
```Shell
adb logcat -d > "$LOCAL_LOGCAT_FILE_PATH"
```


<!-- Sent from Reviewable.io -->

2024-12-18 16:15 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: 1 of 8 files reviewed, 7 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`.github/workflows/android-app.yml` line 51 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEK-IufCQ9UgRNuJ5kC:-OEKKOW9-Bk2s19-ty2L:beadxp5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b067b083b2a1ac419e2cf3bc894cb6e17ecb6435/.github/workflows/android-app.yml#L51)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: add space `on (prod/stagemole)`
</blockquote></details>

Added space. Also added to `mockapi_test_repeat` and `e2e_test_repeat` descriptions
___
*[`.github/workflows/android-app.yml` line 351 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEK-ZZID9jIyGgemorW:-OEKBzh1DL1-cNomy3pk:b6wzxw8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b067b083b2a1ac419e2cf3bc894cb6e17ecb6435/.github/workflows/android-app.yml#L351)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can we check `e2e_tests_infra_flavor` instead?
</blockquote></details>

Now checking `e2e_test_repeat`, `run_firebase_tests` and `e2e_tests_infra_flavor`
___
*[`.github/workflows/android-app.yml` line 494 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEK3pB-30f_SePPoYNG:-OEO4_M3EPUVy3o_4pKL:b-9vpo1f) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b067b083b2a1ac419e2cf3bc894cb6e17ecb6435/.github/workflows/android-app.yml#L494)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Do we need this check? These tests doesn't include anything sensitive since it's only used for isolated tests atm (unless we decide to merge `instrumented-tests` & `instrumented-e2e-tests`
</blockquote></details>

Removed the stagemole check
___
*[`.github/workflows/android-app.yml` line 501 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEK2vL_-82bYVobE22R:-OEO4awhBZGWn4PWZZ_s:bhzgsuf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b067b083b2a1ac419e2cf3bc894cb6e17ecb6435/.github/workflows/android-app.yml#L501)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Could it make sense to merge this one with `instrumented-tests` now that the difference between the two is less than before? I believe the main thing to consider is that we would only want to set some of the `env` variables for the e2e tests (such as `PARTNER_AUTH`).
</blockquote></details>

Created triage issue for this. We had an offline talk about keeping it outside of this PR.
___
*[`android/scripts/pull-test-output.sh` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEK1Hn5BhQ1-qg_sGNf:-OEPY7YM3_WyBInC4SVb:b-ejc7rj) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b067b083b2a1ac419e2cf3bc894cb6e17ecb6435/android/scripts/pull-test-output.sh#L35)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Would be really nice if we could just have a single on-device path for all this content such as `/sdcard/test-report` that we just pull recursively into `$REPORT_DIR` instead of a bunch of paths that we now have to keep track of in two different scripts. But probably a bit out-of-scope for this PR...
</blockquote></details>

Now all files are under `/sdcard/Downloads/test-outputs`
___
*[`android/scripts/pull-test-output.sh` line 38 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEK0_HCDL5AECM_DTyp:-OEPYCoX4QiKYCo5PBUQ:b-k1opup) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/b067b083b2a1ac419e2cf3bc894cb6e17ecb6435/android/scripts/pull-test-output.sh#L38)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

The other script that runs the tests should probably be responsible for dumping the logcat content into a file on the device. This script can then be responsible for downloading that file.
</blockquote></details>

Dumping the content in the other file now
___
*[`android/scripts/run-instrumented-tests.sh` line 112 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEK2H2_-WWI_YdM7Kr0:-OEKK8re8S9plkCu-78w:bdfvl6p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/15fc4f927f9a05ca88563f8d7ead79f9f7c7e807/android/scripts/run-instrumented-tests.sh#L112)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should this block really be removed? Didn't we say to keep using the play build? :thinking:
</blockquote></details>

Brought this back


<!-- Sent from Reviewable.io -->

2024-12-19 09:42 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: 1 of 8 files reviewed, 8 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`.github/workflows/android-app.yml` line 560 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OETHjU83dnJtEgqsMv1:-OETHjU83dnJtEgqsMv2:b32z403) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e2adfa40580690a6b4710fa6a08bfd6e78574e90/.github/workflows/android-app.yml#L560)):*
> ```YAML
>           INFRA_FLAVOR: ${{ github.event.inputs.e2e_tests_infra_flavor }}
>           PARTNER_AUTH: ${{ github.event.inputs.e2e_tests_infra_flavor == 'stagemole' && secrets.STAGEMOLE_PARTNER_AUTH || '' }}
>           VALID_TEST_ACCOUNT_NUMBER: ${{ github.event.inputs.e2e_tests_infra_flavor == 'prod' && secrets.ANDROID_PROD_TEST_ACCOUNT || '' }}
> ```

The two lines above are too long and should be split into multiple lines, working on splitting them without breaking the code


<!-- Sent from Reviewable.io -->

2024-12-19 09:43 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: 1 of 8 files reviewed, 9 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/rule/CaptureScreenshotOnFailedTestRule.kt` line 20 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OETI5Oh2ozwmYRoBmUq:-OETI5Oh2ozwmYRoBmUr:b-egk29c) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e2adfa40580690a6b4710fa6a08bfd6e78574e90/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/rule/CaptureScreenshotOnFailedTestRule.kt#L20)):*
> ```Kotlin
> import java.time.OffsetDateTime
> import java.time.temporal.ChronoUnit
> import net.mullvad.mullvadvpn.test.common.misc.Attachment
> ```

Only using `Attachment` for the outputs path right now. Should probably also use it for storing screenshots though?


<!-- Sent from Reviewable.io -->

2025-01-09 13:58 UTC, albin-mullvad submitted a review, later dismissed
> Reviewed 4 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: 4 of 8 files reviewed, 6 unresolved discussions (waiting on @niklasberglund and @Pururun)

___
*[`android/scripts/pull-test-output.sh` line 5 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEZRGLeCimrpu_HtP3Y:-OEZRGLeCimrpu_HtP3Z:bazps7s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1b570cfeb6d96603117724f34097fdc9a216ae0/android/scripts/pull-test-output.sh#L5)):*
> ```Shell
> set -eu
> 
> TEST_DEVICE_OUTPUTS_DIR="${TEST_DEVICE_OUTPUTS_DIR:-/sdcard/Download/test-outputs/attachments}" # Must match the path where e2e tests output their attachments
> ```

Should we not skip `/attachments` here?



_Code quote:_
```Shell
/attachments
```
___
*[`android/scripts/pull-test-output.sh` line 5 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEZRLmQ5fCq8DL2Pk3w:-OEZRLmQ5fCq8DL2Pk3x:b-9pgjht) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1b570cfeb6d96603117724f34097fdc9a216ae0/android/scripts/pull-test-output.sh#L5)):*
> ```Shell
> set -eu
> 
> TEST_DEVICE_OUTPUTS_DIR="${TEST_DEVICE_OUTPUTS_DIR:-/sdcard/Download/test-outputs/attachments}" # Must match the path where e2e tests output their attachments
> ```

nit: move comment to the line above



_Code quote:_
```Shell
# Must match the path where e2e tests output their attachments
```
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt` line 10 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEZQfrw7zuGTnyLLQnb:-OEZQfrw7zuGTnyLLQnc:b-aetx51) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1b570cfeb6d96603117724f34097fdc9a216ae0/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt#L10)):*
> ```Kotlin
> 
> object Attachment {
>     val DIRECTORY_PATH = "${Environment.DIRECTORY_DOWNLOADS}/test-outputs/attachments"
> ```

Can we define this `test-output` path in a single place?



_Code quote:_
```Kotlin
${Environment.DIRECTORY_DOWNLOADS}/test-outputs
```
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt` line 58 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEZQqGJ02DyucXJr5pA:-OEZQqGJ02DyucXJr5pB:b-aetx51) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1b570cfeb6d96603117724f34097fdc9a216ae0/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt#L58)):*
> ```Kotlin
>     companion object {
>         val OUTPUT_DIRECTORY =
>             "${Environment.getExternalStorageDirectory().path}/Download/test-outputs/attachments/video"
> ```

Can we define this `test-output` path in a single place?



_Code quote:_
```Kotlin
${Environment.getExternalStorageDirectory().path}/Download/test-outputs/
```


<!-- Sent from Reviewable.io -->

2025-01-09 14:10 UTC, Rawa requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: 6 of 8 files reviewed, 8 unresolved discussions (waiting on @albin-mullvad, @niklasberglund, and @Pururun)

___
*[`.github/workflows/android-app.yml` line 491 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OGALHc5Ep3E4AgeYG3M:-OGALHc5Ep3E4AgeYG3N:b-kml6no) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8691d01a67a7c3a0165e62c1988243aca2664d49/.github/workflows/android-app.yml#L491)):*
> ```YAML
> 
>       - name: Pull test report
>         if: always() && matrix.test-repeat != 0 && github.event.inputs.e2e_tests_infra_flavor == 'stagemole'
> ```

Is there a reason for not uploading test report if flavor was `prod`? We don't have test reports if it is prod?
___
*[`.github/workflows/android-app.yml` line 494 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OGALW_Y2CDAb3IfLbCy:-OGALW_Y2CDAb3IfLbCz:bch23yf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8691d01a67a7c3a0165e62c1988243aca2664d49/.github/workflows/android-app.yml#L494)):*
> ```YAML
>         shell: bash -ieo pipefail {0}
>         env:
>           TEST_DEVICE_OUTPUTS_DIR: '/sdcard/Download/test-outputs'
> ```

```        TEST_DEVICE_OUTPUTS_DIR: '/sdcard/Download/test-outputs'```
We define the same variable in 4 places, can we set it in one common place so we don't repeat?


<!-- Sent from Reviewable.io -->

2025-01-09 14:11 UTC, Rawa reviewed
> Reviewed 1 of 4 files at r1, 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: 7 of 8 files reviewed, 8 unresolved discussions (waiting on @niklasberglund)



<!-- Sent from Reviewable.io -->

2025-01-09 14:11 UTC, Rawa reviewed
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: all files reviewed, 8 unresolved discussions (waiting on @niklasberglund)



<!-- Sent from Reviewable.io -->

2025-01-10 15:47 UTC, niklasberglund reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @Rawa)

___
*[`.github/workflows/android-app.yml` line 491 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OGALHc5Ep3E4AgeYG3M:-OGAV4zYCfarAyNuFf6w:bz5e99t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8691d01a67a7c3a0165e62c1988243aca2664d49/.github/workflows/android-app.yml#L491)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Is there a reason for not uploading test report if flavor was `prod`? We don't have test reports if it is prod?
</blockquote></details>

Yes correct, before we didn't upload any test reports ever but now we will upload when tests run against staging environment since then account number etc is OK to "leak".
___
*[`.github/workflows/android-app.yml` line 494 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OGALW_Y2CDAb3IfLbCy:-OGAWDGl1h2fgTavlshn:b-25qt1s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8691d01a67a7c3a0165e62c1988243aca2664d49/.github/workflows/android-app.yml#L494)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

```        TEST_DEVICE_OUTPUTS_DIR: '/sdcard/Download/test-outputs'```
We define the same variable in 4 places, can we set it in one common place so we don't repeat?
</blockquote></details>

Good point. Now setting it in `TEST_OUTPUTS_PATH` on workflow-level which is passed to steps `env`'s `TEST_DEVICE_OUTPUTS_DIR`. I'm not sure but maybe it is possible to set `TEST_OUTPUTS_PATH` on workflow level directly and not set it per step but I'm thinking it would make the code harder to follow.
___
*[`android/scripts/pull-test-output.sh` line 5 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEZRGLeCimrpu_HtP3Y:-OGAX3b9AlUMWyfaOMLO:b-bzcv10) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1b570cfeb6d96603117724f34097fdc9a216ae0/android/scripts/pull-test-output.sh#L5)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Should we not skip `/attachments` here?
</blockquote></details>

Yes. Removed
___
*[`android/scripts/pull-test-output.sh` line 5 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEZRLmQ5fCq8DL2Pk3w:-OGAh8TqD3p8afT7eUpc:b-84847m) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1b570cfeb6d96603117724f34097fdc9a216ae0/android/scripts/pull-test-output.sh#L5)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

nit: move comment to the line above
</blockquote></details>

Moved
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt` line 10 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEZQfrw7zuGTnyLLQnb:-OGAgjpz-RxwMgom-pkZ:bgij00l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1b570cfeb6d96603117724f34097fdc9a216ae0/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/Attachment.kt#L10)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can we define this `test-output` path in a single place?
</blockquote></details>

Defined in `Attachment` now under `DIRECTORY_NAME`.
___
*[`android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt` line 58 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OEZQqGJ02DyucXJr5pA:-OGAgohU9CZjPphylKi2:bgij00l) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/e1b570cfeb6d96603117724f34097fdc9a216ae0/android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt#L58)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

Can we define this `test-output` path in a single place?
</blockquote></details>

Defined in `Attachment` now under `DIRECTORY_NAME`.
___
*[`android/scripts/run-instrumented-tests.sh` line 239 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OGFtMV3EqTGkt92tTCQ:-OGFtMV3EqTGkt92tTCR:b68hsr7) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6e38560ddf6203d58080aa486333f42f3485699b/android/scripts/run-instrumented-tests.sh#L239)):*
> ```Shell
>     -e runnerBuilder de.mannodermaus.junit5.AndroidJUnit5Builder \
>     ${OPTIONAL_TEST_ARGUMENTS:-""} \
>     androidx.test.orchestrator/androidx.test.orchestrator.AndroidTestOrchestrator"
> ```

CI runs are currently failing because of invalid syntax here I believe. Haven't found the cause, but maybe `$INSTRUMENTATION_COMMAND` or `$GRADLE_ENVIRONMENT_VARIABLES` is misformatted?


<!-- Sent from Reviewable.io -->

2025-01-13 08:05 UTC, Rawa reviewed
> Reviewed 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad)



<!-- Sent from Reviewable.io -->

2025-01-20 14:29 UTC, albin-mullvad reviewed
> Reviewed 1 of 7 files at r2, 3 of 5 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @Rawa)



<!-- Sent from Reviewable.io -->

2025-01-20 15:03 UTC, albin-mullvad reviewed
> Reviewed 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: all files reviewed, 1 unresolved discussion (waiting on @niklasberglund)

___
*[`.github/workflows/android-app.yml` line 489 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OH3DJR81Bw8CTdLX-lk:-OH3DJR90IPA8fRumFN4:b-lf4apd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/308e9c11ba4e24f1c518f74eeb5a59be1b1db0ef/.github/workflows/android-app.yml#L489)):*
> ```YAML
>           BILLING_FLAVOR: oss
>           INFRA_FLAVOR: prod
>           TEST_DEVICE_OUTPUTS_DIR: ${{ env.TEST_OUTPUTS_PATH }}
> ```

Would be nice to keep the naming consistent



_Code quote:_
```YAML
TEST_DEVICE_OUTPUTS_DIR: ${{ env.TEST_OUTPUTS_PATH }}
```


<!-- Sent from Reviewable.io -->

2025-01-23 08:36 UTC, Pururun approved these changes
> Reviewed 4 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: all files reviewed, 2 unresolved discussions (waiting on @niklasberglund)

___
*[`android/scripts/run-instrumented-tests.sh` line 242 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OHHINjNBTY99K-2SswB:-OHHINjNBTY99K-2SswC:bn1uhyc) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/308e9c11ba4e24f1c518f74eeb5a59be1b1db0ef/android/scripts/run-instrumented-tests.sh#L242)):*
> ```Shell
>     androidx.test.orchestrator/androidx.test.orchestrator.AndroidTestOrchestrator"
> 
>     echo "Command: $INSTRUMENTATION_COMMAND"
> ```

Debug log, should we keep it?


<!-- Sent from Reviewable.io -->

2025-01-23 22:20 UTC, albin-mullvad reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: 1 of 8 files reviewed, all discussions resolved (waiting on @Pururun and @Rawa)

___
*[`android/scripts/run-instrumented-tests.sh` line 242 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-OHHINjNBTY99K-2SswB:-OHKF-jfEM6fxnGo8RmS:bss4a1y) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/308e9c11ba4e24f1c518f74eeb5a59be1b1db0ef/android/scripts/run-instrumented-tests.sh#L242)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Debug log, should we keep it?
</blockquote></details>

Removed!


<!-- Sent from Reviewable.io -->

2025-01-24 07:55 UTC, Rawa approved these changes
> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: 1 of 8 files reviewed, all discussions resolved (waiting on @Rawa)



<!-- Sent from Reviewable.io -->

2025-01-24 07:58 UTC, Pururun approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343#-:-OHMJS-a9VnpHSZhi8JP:bnfp4nl)* status: 1 of 8 files reviewed, all discussions resolved (waiting on @albin-mullvad and @Rawa)



<!-- Sent from Reviewable.io -->

2025-01-27 08:08 UTC, Pururun approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @albin-mullvad, @Pururun, and @Rawa)



<!-- Sent from Reviewable.io -->

2025-01-27 13:50 UTC, Pururun approved these changes
> Reviewed 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7343)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @albin-mullvad, @Pururun, and @Rawa)



<!-- Sent from Reviewable.io -->

2025-01-27 15:00 UTC, merged