Update UI tests for the new WG Obfuscation views
mullvad/mullvadvpn-app pull request #7371
Opened 2024-12-18 15:53 UTC by acb-mv

This updates the UI test covering WireGuard Obfuscation settings (`SettingsMigrationTests.testChangeVPNSettings`) to work with the new SwiftUI-based pages, traversing both the UDP/TCP and Shadowsocks settings pages, and in turn implements UI test support for `SingleChoiceList`-based pages. This does not implement any new tests.

2024-12-19 16:27 UTC, niklasberglund requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7371)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @acb-mv)

___
*[`ios/MullvadVPNUITests/SettingsMigrationTests.swift` line 142 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7371#-OEUjGVO5IvP3YnDgHdo:-OEUjGVO5IvP3YnDgHdp:b-12i8k5) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2470e1e2f1a0154ed48dcf4a7d015c7a222849b9/ios/MullvadVPNUITests/SettingsMigrationTests.swift#L142)):*
> ```Swift
>         UDPOverTCPObfuscationSettingsPage(app)
>             .tapPortCell(2)
>             .tapPortCell(1)
> ```

IMO when using indices like this in page methods it's difficult for a reader to understand what the tests do and also the tests are more prone to becoming outdated when the UI is updated. Suggest separate functions and names like `tapPort80Cell` etc. Even if the separate functions for now maybe would use indices to identify elements they could in the future be improved.
___
*[`ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift` line 183 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7371#-OEUi6qV1ri1A6v1oJpd:-OEUi6qV1ri1A6v1oJpe:b-v0e1dv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/2470e1e2f1a0154ed48dcf4a7d015c7a222849b9/ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift#L183)):*
> ```Swift
>     @discardableResult func verifyUDPOverTCPPort80Selected() -> Self {
>         let detailLabel = app.staticTexts[AccessibilityIdentifier.wireGuardObfuscationUdpOverTcpPort]
>         XCTAssertTrue(detailLabel.label.hasSuffix("80"))
> ```

nit: this could also match other ports ending with "80" if there were any, but there isn't so probably no need to change. Or maybe it could match suffix " 80" with a leading space to avoid potential clash in the future.


<!-- Sent from Reviewable.io -->

2024-12-19 16:51 UTC, niklasberglund approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7371#-:-OEUpCInB0NsTEwowyLf:bnfp4nl)* status: 0 of 10 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-20 10:59 UTC, rablador reviewed
> Reviewed 3 of 9 files at r1, 2 of 5 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7371)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift` line 157 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7371#-OEYhzE41vRkAlmonZ6x:-OEYhzE41vRkAlmonZ6y:b-i4e5d8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/830cffef8806cc260ea65a4ff70be28d399081f0/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsCellFactory.swift#L157)):*
> ```Swift
>             ), viewModel.obfuscationUpdOverTcpPort.description)
> 
>             cell.setAccessibilityIdentifier(item.accessibilityIdentifier)
> ```

Do we need both a11y id:s here?


<!-- Sent from Reviewable.io -->

2024-12-20 17:44 UTC, acb-mv reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7371)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift` line 157 at r4](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7371#-OEYhzE41vRkAlmonZ6x:-OE_9tnpBPzlV7f9hN7j:b8xhf5p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/830cffef8806cc260ea65a4ff70be28d399081f0/ios/MullvadVPN/View%20controllers/VPNSettings/VPNSettingsCellFactory.swift#L157)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

Do we need both a11y id:s here?
</blockquote></details>

Yes. To check that the cell is selected, and to check that the detail label mentions the correct value (as in "Port: 80")


<!-- Sent from Reviewable.io -->

2024-12-30 10:42 UTC, pinkisemils approved these changes
> Reviewed 3 of 9 files at r1, 2 of 5 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7371)* status: all files reviewed, 1 unresolved discussion (waiting on @rablador)



<!-- Sent from Reviewable.io -->

2025-01-02 09:28 UTC, merged