Remove global API endpoint
mullvad/mullvadvpn-app pull request #7373
Opened 2024-12-18 17:25 UTC by pinkisemils

This particular changeset started off with adding a unit test to see why the iOS end-to-end API client is failing. I fixed it and added a test to ensure it doesn't get broken again. Adding a test implied removing some _global state_, namely the global `ApiEndpoint`.  The test itself is using `httpmock` and exercising the FFI that the Swift test client is using.  I have tested these changes with various Android builds, will try out the app with stagemole later too. I am not entirely certain if removing the global state has made the code any more readable or better, but it certainly has improved the testability. 

This then bubbled over into refactoring the daemon parameters just one slight bit - I am not certain it is a change we need, and thus can drop the last commit.

2024-12-18 19:50 UTC, Rawa requested changes
> Reviewed 1 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373)* status: 1 of 24 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 228 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373#-OEQ7u5s1zFh7H5swTvX:-OEQ7u5s1zFh7H5swTvY:b-50f9hq) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7808d2a9edf9a13988c1f7ed12d9e34545e5c57/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L228)):*
> ```Kotlin
>     viewModel { VpnSettingsViewModel(get(), get(), get(), get(), get()) }
>     viewModel { WelcomeViewModel(get(), get(), get(), get(), isPlayBuild = IS_PLAY_BUILD) }
>     viewModel { ReportProblemViewModel(get(), get(), get<DaemonConfig>().apiEndpointOverride) }
> ```

We should inject it directly to the ProblemReporter instead of the ViewModel, it should not have to worry about the apiEndpointOverrides. Or maybe just migrate the problem reporter for the usecase of android? (Could be a separate issue.)
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 228 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373#-OEQJTj81VYDeqaZIUMd:-OEQJTj81VYDeqaZIUMe:bgx117s) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7808d2a9edf9a13988c1f7ed12d9e34545e5c57/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L228)):*
> ```Kotlin
>     viewModel { VpnSettingsViewModel(get(), get(), get(), get(), get()) }
>     viewModel { WelcomeViewModel(get(), get(), get(), get(), isPlayBuild = IS_PLAY_BUILD) }
>     viewModel { ReportProblemViewModel(get(), get(), get<DaemonConfig>().apiEndpointOverride) }
> ```

Right now this override does not take into account the `ApiEndpointFromIntentHolder` overrides. Lets discuss how we can make it a bit more unified.


<!-- Sent from Reviewable.io -->

2024-12-19 10:57 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373)* status: 1 of 24 files reviewed, 2 unresolved discussions (waiting on @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 228 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373#-OEQ7u5s1zFh7H5swTvX:-OETKjif7OfuYYHBzoAk:b-sccy2w) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7808d2a9edf9a13988c1f7ed12d9e34545e5c57/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L228)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

We should inject it directly to the ProblemReporter instead of the ViewModel, it should not have to worry about the apiEndpointOverrides. Or maybe just migrate the problem reporter for the usecase of android? (Could be a separate issue.)
</blockquote></details>

Definitely not migrating the problem report to grpc here. 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 228 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373#-OEQJTj81VYDeqaZIUMd:-OETKfOU3Zu8vG6TB0Ov:b4aa4bu) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7808d2a9edf9a13988c1f7ed12d9e34545e5c57/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L228)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Right now this override does not take into account the `ApiEndpointFromIntentHolder` overrides. Lets discuss how we can make it a bit more unified.
</blockquote></details>

Should it? Do you test problem reports in e2e tests? I'm happy to have a better solution here - I did not author the kotlin parts here. I can hack on it a bit, but this soup of `getgetgetgetget` is most certainly just rune gibberish to me - that is to say that I welcome any and all help.


<!-- Sent from Reviewable.io -->

2024-12-19 12:05 UTC, dlon requested changes
> Reviewed 14 of 23 files at r1, 4 of 4 files at r3, 2 of 3 files at r4, 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373)* status: 20 of 26 files reviewed, 3 unresolved discussions (waiting on @pinkisemils and @Rawa)

___
*[`mullvad-api/src/rest.rs` line 455 at r3](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373#-OET7ehe6_XURPZaeBIW:-OET7ehe6_XURPZaeBIX:bkwwcqb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/89e1b457d7d9d4ad02133495b26e8e6cf40c55ae/mullvad-api/src/rest.rs#L455)):*
> ```XML
>         }
> 
>         println!("rest - {:?}", self.request.uri());
> ```

This should be removed


<!-- Sent from Reviewable.io -->

2024-12-19 12:58 UTC, Rawa requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373)* status: 20 of 26 files reviewed, 3 unresolved discussions (waiting on @dlon and @pinkisemils)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 228 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373#-OEQ7u5s1zFh7H5swTvX:-OETyzkY6klET_ubXqSe:b-35fn3b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7808d2a9edf9a13988c1f7ed12d9e34545e5c57/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L228)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Definitely not migrating the problem report to grpc here.
</blockquote></details>

I'm all fine with postponing migration to gRPC to another issue, but we should move it to the problem reporter component.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 228 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373#-OEQJTj81VYDeqaZIUMd:-OETzDuSDd7PG0ULZEdj:bezbtpr) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7808d2a9edf9a13988c1f7ed12d9e34545e5c57/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L228)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Should it? Do you test problem reports in e2e tests? I'm happy to have a better solution here - I did not author the kotlin parts here. I can hack on it a bit, but this soup of `getgetgetgetget` is most certainly just rune gibberish to me - that is to say that I welcome any and all help.
</blockquote></details>

This would be for mockApi tests. No right now we don't the problem reports specifically but if we want to test it later it would be weird that the daemon uses two different API endpoints at the same time. I can help out and make it happen.


<!-- Sent from Reviewable.io -->

2024-12-20 07:00 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373)* status: 18 of 26 files reviewed, 1 unresolved discussion (waiting on @dlon and @pinkisemils)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 228 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373#-OEQ7u5s1zFh7H5swTvX:-OEXrXiZ8DQck3mDpuMt:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7808d2a9edf9a13988c1f7ed12d9e34545e5c57/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L228)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

I'm all fine with postponing migration to gRPC to another issue, but we should move it to the problem reporter component.
</blockquote></details>

Fixed.
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt` line 228 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373#-OEQJTj81VYDeqaZIUMd:-OEXrYqkDUn4nDzyU4PD:bt2vr1b) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/a7808d2a9edf9a13988c1f7ed12d9e34545e5c57/android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt#L228)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

This would be for mockApi tests. No right now we don't the problem reports specifically but if we want to test it later it would be weird that the daemon uses two different API endpoints at the same time. I can help out and make it happen.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2024-12-20 09:56 UTC, Rawa approved these changes
:star: Kotlin parts <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 14 of 23 files at r1, 2 of 4 files at r3, 1 of 3 files at r4, 4 of 4 files at r5, 1 of 3 files at r6, 1 of 2 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373#-:-OEYUp3502xtTBQZDFAI:bfoo80y)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)



<!-- Sent from Reviewable.io -->

2024-12-20 11:49 UTC, dlon submitted a review, later dismissed
Might be more readable if we get rid of some conditional compilation that's all over the place right now. I kind of think that `api-override` really only needs to affect the behavior of `ApiEndpoint::from_env_vars()` (which should probably be replaced by `ApiEndpoint::default()`).

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373#-:-OEYqiGQ2IdC5j9jjiDI:blkyeja)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-20 12:24 UTC, Pururun requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/MullvadProblemReport.kt` line 60 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373#-OEZ0Sw-0FtVQOz444Az:-OEZ0Sw-0FtVQOz444B-:bbg4q9j) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/09a642fe43062128e974052da4c335db2dd9a7f2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/MullvadProblemReport.kt#L60)):*
> ```Kotlin
>                 val apiOverride =
>                     if (BuildConfig.DEBUG) {
>                         apiEndpointFromIntentHolder.apiEndpointOverride ?: apiEndpointOverride
> ```

This will break stagemole and devmole builds. It should be possible to override api on release builds.


<!-- Sent from Reviewable.io -->

2024-12-20 12:28 UTC, Pururun requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/MullvadProblemReport.kt` line 60 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373#-OEZ0Sw-0FtVQOz444Az:-OEZ1DXZCyg0NBOztvpD:b-jfrus4) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/09a642fe43062128e974052da4c335db2dd9a7f2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/MullvadProblemReport.kt#L60)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This will break stagemole and devmole builds. It should be possible to override api on release builds.
</blockquote></details>

It should be something like this:
```
intentApiOverride = apiEndpointFromIntentHolder.apiEndpointOverride
if (BuildConfig.DEBUG && intentApiOverride != null) {
                intentApiOverride
            } else {
                apiEndpointOverride
            }
```


<!-- Sent from Reviewable.io -->

2024-12-20 15:08 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373)* status: 24 of 27 files reviewed, 1 unresolved discussion (waiting on @Pururun and @Rawa)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/MullvadProblemReport.kt` line 60 at r8](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373#-OEZ0Sw-0FtVQOz444Az:-OEZbCRV1nbT_aOI0WtM:b-cbjew9) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/09a642fe43062128e974052da4c335db2dd9a7f2/android/app/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/MullvadProblemReport.kt#L60)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

It should be something like this:
```
intentApiOverride = apiEndpointFromIntentHolder.apiEndpointOverride
if (BuildConfig.DEBUG && intentApiOverride != null) {
                intentApiOverride
            } else {
                apiEndpointOverride
            }
```
</blockquote></details>

Seems to work as expected now :) 


<!-- Sent from Reviewable.io -->

2024-12-20 17:11 UTC, pinkisemils reviewed
Whilst that is a worthwhile change, let's get @faern's approval once he's back.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373#-:-OE_2BzJ9Ue1obU0j4Ni:b-skl7eq)* status: 22 of 27 files reviewed, 1 unresolved discussion (waiting on @dlon, @Pururun, and @Rawa)



<!-- Sent from Reviewable.io -->

2024-12-23 12:44 UTC, Rawa approved these changes
> Reviewed 3 of 3 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2024-12-23 12:45 UTC, Rawa submitted a review, later dismissed

2024-12-27 16:01 UTC, dlon approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2024-12-27 16:02 UTC, dlon approved these changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7373)* status: all files reviewed, 1 unresolved discussion (waiting on @Pururun)



<!-- Sent from Reviewable.io -->

2025-01-02 10:04 UTC, merged