Add connection detail toggle to connection view
mullvad/mullvadvpn-app pull request #7388
Opened 2024-12-20 09:00 UTC by rablador

The connection details should be shown/hidden depending on if the view is expanded or collapsed, via the tappable chevron.

This PR also includes https://linear.app/mullvad/issue/IOS-932/add-feature-indicator-pills-to-connection-details.

2024-12-20 10:30 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388)* status: 0 of 32 files reviewed, 2 unresolved discussions

___
*[`ios/MullvadRustRuntimeTests/MullvadPostQuantum+Stubs.swift` line 15 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OEYZuUj1PIvgRn0fswQ:-OEYZuUj1PIvgRn0fswR:b-ka9ny0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44afa376093c3c62f57a6518eb467cd488de02ac/ios/MullvadRustRuntimeTests/MullvadPostQuantum%2BStubs.swift#L15)):*
> ```Swift
> @testable import WireGuardKitTypes
> 
> // swiftlint:disable function_parameter_count
> ```

Everything in this file is to make the unit tests work (currently failing when looking for `MullvadTypes.WgFuncPointers`).
___
*[`ios/convert-assets.rb` line 35 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OEYZkQv2ko3kAdejkOr:-OEYZkQv2ko3kAdejkOs:b-gf1umd) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/44afa376093c3c62f57a6518eb467cd488de02ac/ios/convert-assets.rb#L35)):*
> ```Ruby
>   "icon-fail.svg",
>   "icon-info.svg",
>   "icon-reload.svg",
> ```

Added as a pure SVG in project assets instead of being converted here.


<!-- Sent from Reviewable.io -->

2024-12-20 10:35 UTC, acb-mv reviewed
> Reviewed 31 of 32 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388)* status: 29 of 32 files reviewed, 5 unresolved discussions (waiting on @rablador)

___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift` line 25 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OEYc2WVCw9-Ci-Pj3lK:-OEYc2WW0_bGHdhwkJTi:b2pevob) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f9a3da36ecefd4f8853c80daa76f29596e4f0d27/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift#L25)):*
> ```Swift
>         for (index, chip) in chips.enumerated() {
>             let textWidth = chip.name.width(using: .preferredFont(forTextStyle: .subheadline))
>             let chipWidth = textWidth + 16 /* inside horisontal padding */ + 8 /* outside trailing padding */
> ```

typo: should be "horizontal"
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ChipFeature.swift` line 24 at r1](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OEYbZYb0T1qk2iyilvx:-OEYbZYb0T1qk2iyilvy:b-3x5ywl) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/f9a3da36ecefd4f8853c80daa76f29596e4f0d27/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ChipFeature.swift#L24)):*
> ```Swift
> 
>     var name: String {
>         String("DAITA")
> ```

Is the `String("
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ChipView/ChipFeature.swift` line 85 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OEYbgGJ6-bdPMYvIUBL:-OEYbgGJ6-bdPMYvIUBM:b-ci1otf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/3e1c133cdfedc8985e49be9ed3449df334b682db/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ChipView/ChipFeature.swift#L85)):*
> ```Swift
> 
>     var name: String {
>         String("Server IP override")
> ```

Is the `String("...")` wrapper necessary? IIRC,`"Server IP override"` would return a `String`


<!-- Sent from Reviewable.io -->

2025-01-08 16:01 UTC, mojganii requested changes
When we change the tunnel settings , the connection view is expanded which it's not correct.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-:-OG59Apw8rEZdYRXXZXL:b-7r29op)* status: 17 of 43 files reviewed, 15 unresolved discussions (waiting on @acb-mv and @rablador)

___
*[`ios/MullvadVPN/Extensions/View+TapAreaSize.swift` line 31 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG4q8IC2AmoCY2xOl7_:-OG4q8IC2AmoCY2xOl7a:bb8flsv) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c32c22f2066f2ffa153b7b3dd63ed85f98c6a1c9/ios/MullvadVPN/Extensions/View%2BTapAreaSize.swift#L31)):*
> ```Swift
>             )
>             .contentShape(Rectangle())
>             .frame(width: actualViewSize.width, height: actualViewSize.height)
> ```

we are setting frame size twice which isn't necessary, we can remove the second frame property. in addition, since the it's view modifier to prevent form setting size less than minimum then putting `.contentShape(Rectangle())` should be done in the component which is using this modifier. 
as we discussed offline, if there is a behind reason for that or it has some side effects on the code, let comment it out here:



_Code snippet:_
```Swift
private struct TappablePadding: ViewModifier {
    @State private var actualViewSize: CGSize = .zero
    private let tappableViewSize = UIMetrics.Button.minimumTappableAreaSize

    func body(content: Content) -> some View {
        content
            .sizeOfView { actualViewSize = $0 }
            .frame(
                width: max(actualViewSize.width, tappableViewSize.width),
                height: max(actualViewSize.height, tappableViewSize.height)
            )
//            .contentShape(Rectangle())
//            .frame(width: actualViewSize.width, height: actualViewSize.height)
    }
}


struct CustomToggleStyle: ToggleStyle {
    private let width: CGFloat = 48
    private let height: CGFloat = 30
    private let circleRadius: CGFloat = 23

    var disabled = false
    let accessibilityId: AccessibilityIdentifier?
    var infoButtonAction: (() -> Void)?

    func makeBody(configuration: Configuration) -> some View {
        HStack {
            configuration.label
                .opacity(disabled ? 0.2 : 1)

            if let infoButtonAction {
                Button(action: infoButtonAction) {
                    Image(.iconInfo)
                }
                .adjustingTapAreaSize()
                .contentShape(Rectangle())
                .tint(.white)
            }

            Spacer()

            ZStack(alignment: configuration.isOn ? .trailing : .leading) {
                Capsule(style: .circular)
                    .frame(width: width, height: height)
                    .foregroundColor(.clear)
                    .overlay(
                        RoundedRectangle(cornerRadius: circleRadius)
                            .stroke(
                                Color(.white.withAlphaComponent(0.8)),
                                lineWidth: 2
                            )
                    )
                    .opacity(disabled ? 0.2 : 1)

                Circle()
                    .frame(width: circleRadius, height: circleRadius)
                    .padding(3)
                    .foregroundColor(
                        configuration.isOn
                            ? Color(uiColor: UIColor.Switch.onThumbColor)
                            : Color(uiColor: UIColor.Switch.offThumbColor)
                    )
                    .opacity(disabled ? 0.4 : 1)
            }
            .accessibilityIdentifier(accessibilityId?.asString ?? "")
            .onTapGesture {
                toggle(configuration)
            }
            .adjustingTapAreaSize()
        }
    }

    private func toggle(_ configuration: Configuration) {
        withAnimation(.easeInOut(duration: 0.25)) {
            configuration.isOn.toggle()
        }
    }
}
```
___
*[`ios/MullvadVPN/Views/MainButtonStyle.swift` line 13 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5dDhU6J9RNQXInjnz:-OG5dDhU6J9RNQXInjo-:bpywh9n) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/Views/MainButtonStyle.swift#L13)):*
> ```Swift
> struct MainButtonStyle: ButtonStyle {
>     var style: Style
>     var disabled: Bool
> ```

we can remove `disabled` property from here and cunstructor.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView/ButtonPanel.swift` line 70 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5EIse6RctkXIVyGzd:-OG5EIse6RctkXIVyGze:b-2a9fby) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView/ButtonPanel.swift#L70)):*
> ```Swift
>                     text: LocalizedStringKey(
>                         viewModel.tunnelStatus.state == .waitingForConnectivity(.noConnection)
>                             ? "Disconnect"
> ```

texts should be localized.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift` line 16 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG4ycQH4m6AKNrHUJ2W:-OG4ycQH4m6AKNrHUJ2X:b-tn3y0g) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift#L16)):*
> ```Swift
> 
> extension ChipViewModelProtocol {
>     func chipsToAdd(forContainerWidth containerWidth: CGFloat) -> (chips: [ChipModel], chipsWillOverflow: Bool) {
> ```

nit: `isOverflowing`
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift` line 20 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5AhCR9EYlTBIBHXfY:-OG5AhCR9EYlTBIBHXfZ:bx7ikyb) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift#L20)):*
> ```Swift
>         var chipsWillOverflow = false
> 
>         let moreTextWidth = "\(chips.count) more..."
> ```

it should be localized.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift` line 36 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG58a_G27kjtdK0z_8E:-OG58a_G27kjtdK0z_8F:b-6xpc9h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift#L36)):*
> ```Swift
>             let chipWillFit = totalChipsWidth <= containerWidth
> 
>             if chipWillFitWithMoreText {
> ```

can we make it more simplifier :



_Code snippet:_
```Swift
            guard (chipWillFit && isLastChip) || chipWillFitWithMoreText else {
                chipsWillOverflow = true
                break
            }
            chipsToAdd.append(chip)
```
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView/HeaderView.swift` line 48 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5PcNRA-d9HS7xge75:-OG5PcNRA-d9HS7xge76:b-njih6h) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView/HeaderView.swift#L48)):*
> ```Swift
>                         .foregroundStyle(.white)
>                         .accessibilityIdentifier(AccessibilityIdentifier.relayStatusCollapseButton.asString)
>                         .transaction { transaction in
> ```

Since we don't have any specific animation for the chevron based on desktop app, then we can remove that.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView/DetailsContainer.swift` line [...]

2025-01-09 09:51 UTC, rablador reviewed
Fixed.

> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-:-OG9T0GA6uXXTIQ6D9dJ:bt2vr1b)* status: 17 of 43 files reviewed, 13 unresolved discussions (waiting on @acb-mv and @mojganii)

___
*[`ios/MullvadVPN/Extensions/View+TapAreaSize.swift` line 31 at r7](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG4q8IC2AmoCY2xOl7_:-OG9OvFe8TvdNdsejr8_:bqps8oi) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/c32c22f2066f2ffa153b7b3dd63ed85f98c6a1c9/ios/MullvadVPN/Extensions/View%2BTapAreaSize.swift#L31)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

we are setting frame size twice which isn't necessary, we can remove the second frame property. in addition, since the it's view modifier to prevent form setting size less than minimum then putting `.contentShape(Rectangle())` should be done in the component which is using this modifier. 
as we discussed offline, if there is a behind reason for that or it has some side effects on the code, let comment it out here:
</blockquote></details>

Done. The `.contentShape()` needs to stay though, as it's necessary for the increased frame area to be tappable.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ChipView/ChipView.swift` line 14 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG53PVYAfnLiDOCVUIb:-OG9KcR90uxaCjSUHzUR:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ChipView/ChipView.swift#L14)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Since we are already using the localized value here, then we need to use the simple format of the text :
`Text(item.name)`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift` line 16 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG4ycQH4m6AKNrHUJ2W:-OG9LekyB-7jOCiN08lQ:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift#L16)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

nit: `isOverflowing`
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift` line 20 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5AhCR9EYlTBIBHXfY:-OG9LfV07gGidp97Cl5M:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift#L20)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

it should be localized.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift` line 36 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG58a_G27kjtdK0z_8E:-OG9LwXr134CD7Z7W5LH:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift#L36)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

can we make it more simplifier :
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView/ButtonPanel.swift` line 70 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5EIse6RctkXIVyGzd:-OG9M12E0t7x7sGoc5vJ:b9047hg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView/ButtonPanel.swift#L70)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

texts should be localized.
</blockquote></details>

I have thought about this some more. I think it's fine to keep the `LocalizedStringKey` that we have in the swiftUI code right now. Perhaps it could be a good way of testing it out. If you feel strongly about it I can "revert" to NSLocalizedString.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView/DetailsContainer.swift` line 28 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5Loiq10z8Sbd1SMkw:-OG9MkkT1PRDqVCsbfbx:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView/DetailsContainer.swift#L28)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Since the we are calculating the size of content in bottom then I believe we can remove this from here
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView/DetailsContainer.swift` line 38 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5Q-B7-Q-_8tWJjSTp:-OG9MzAj7nTjBm_uRE5y:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView/DetailsContainer.swift#L38)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

there is another issue for animation implementation, it can be removed.
main
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView/HeaderView.swift` line 48 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5PcNRA-d9HS7xge75:-OG9NFJrBLdUKyMRwU2B:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView/HeaderView.swift#L48)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

Since we don't have any specific animation for the chevron based on desktop app, then we can remove that.
</blockquote></details>

Done.
___
*[`ios/MullvadVPN/Views/MainButtonStyle.swift` line 13 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5dDhU6J9RNQXInjnz:-OG9NWHP3sb2J_laEMVl:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/Views/MainButtonStyle.swift#L13)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

we can remove `disabled` property from here and cunstructor.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-09 10:02 UTC, Crazy-9669 commented
ср, 8 янв. 2025 г., 19:01 mojganii ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> When we change the tunnel settings , the connection view is expanded which
> it's not correct.
>
> *Reviewable
> <https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-:-OG59Apw8rEZdYRXXZXL:b-7r29op>*
> status: 17 of 43 files reviewed, 15 unresolved discussions (waiting on
> @acb-mv <https://github.com/acb-mv> and @rablador
> <https://github.com/rablador>)
>
> ------------------------------
>
> *ios/MullvadVPN/Extensions/View+TapAreaSize.swift line 31 at r7
> <https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG4q8IC2AmoCY2xOl7_:-OG4q8IC2AmoCY2xOl7a:bb8flsv>
> (raw file
> <https://github.com/mullvad/mullvadvpn-app/blob/c32c22f2066f2ffa153b7b3dd63ed85f98c6a1c9/ios/MullvadVPN/Extensions/View%2BTapAreaSize.swift#L31>):*
>
>             )
>             .contentShape(Rectangle())
>             .frame(width: actualViewSize.width, height: actualViewSize.height)
>
> we are setting frame size twice which isn't necessary, we can remove the
> second frame property. in addition, since the it's view modifier to prevent
> form setting size less than minimum then putting
> .contentShape(Rectangle()) should be done in the component which is using
> this modifier.
> as we discussed offline, if there is a behind reason for that or it has
> some side effects on the code, let comment it out here:
>
> *Code snippet:*
>
> private struct TappablePadding: ViewModifier {
>     @State private var actualViewSize: CGSize = .zero
>     private let tappableViewSize = UIMetrics.Button.minimumTappableAreaSize
>
>     func body(content: Content) -> some View {
>         content
>             .sizeOfView { actualViewSize = $0 }
>             .frame(
>                 width: max(actualViewSize.width, tappableViewSize.width),
>                 height: max(actualViewSize.height, tappableViewSize.height)
>             )
> //            .contentShape(Rectangle())
> //            .frame(width: actualViewSize.width, height: actualViewSize.height)
>     }}
>
> struct CustomToggleStyle: ToggleStyle {
>     private let width: CGFloat = 48
>     private let height: CGFloat = 30
>     private let circleRadius: CGFloat = 23
>
>     var disabled = false
>     let accessibilityId: AccessibilityIdentifier?
>     var infoButtonAction: (() -> Void)?
>
>     func makeBody(configuration: Configuration) -> some View {
>         HStack {
>             configuration.label
>                 .opacity(disabled ? 0.2 : 1)
>
>             if let infoButtonAction {
>                 Button(action: infoButtonAction) {
>                     Image(.iconInfo)
>                 }
>                 .adjustingTapAreaSize()
>                 .contentShape(Rectangle())
>                 .tint(.white)
>             }
>
>             Spacer()
>
>             ZStack(alignment: configuration.isOn ? .trailing : .leading) {
>                 Capsule(style: .circular)
>                     .frame(width: width, height: height)
>                     .foregroundColor(.clear)
>                     .overlay(
>                         RoundedRectangle(cornerRadius: circleRadius)
>                             .stroke(
>                                 Color(.white.withAlphaComponent(0.8)),
>                                 lineWidth: 2
>                             )
>                     )
>                     .opacity(disabled ? 0.2 : 1)
>
>                 Circle()
>                     .frame(width: circleRadius, height: circleRadius)
>                     .padding(3)
>                     .foregroundColor(
>                         configuration.isOn
>                             ? Color(uiColor: UIColor.Switch.onThumbColor)
>                             : Color(uiColor: UIColor.Switch.offThumbColor)
>                     )
>                     .opacity(disabled ? 0.4 : 1)
>             }
>             .accessibilityIdentifier(accessibilityId?.asString ?? "")
>             .onTapGesture {
>                 toggle(configuration)
>             }
>             .adjustingTapAreaSize()
>         }
>     }
>
>     private func toggle(_ configuration: Configuration) {
>         withAnimation(.easeInOut(duration: 0.25)) {
>             configuration.isOn.toggle()
>         }
>     }}
>
> ------------------------------
>
> *ios/MullvadVPN/Views/MainButtonStyle.swift line 13 at r10
> <https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5dDhU6J9RNQXInjnz:-OG5dDhU6J9RNQXInjo-:bpywh9n>
> (raw file
> <https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/Views/MainButtonStyle.swift#L13>):*
>
> struct MainButtonStyle: ButtonStyle {
>     var style: Style
>     var disabled: Bool
>
> we can remove disabled property from here and cunstructor.
> ------------------------------
>
> *ios/MullvadVPN/View
> controllers/Tunnel/FeatureIndicators/ConnectionView/ButtonPanel.swift line
> 70 at r10
> <https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5EIse6RctkXIVyGzd:-OG5EIse6RctkXIVyGze:b-2a9fby>
> (raw file
> <https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView/ButtonPanel.swift#L70>):*
>
>                     text: LocalizedStringKey(
>                         viewModel.tunnelStatus.state == .waitingForConnectivity(.noConnection)
>                             ? "Disconnect"
>
> texts should be localized.
> ------------------------------
>
> *ios/MullvadVPN/View
> controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift
> line 16 at r10
> <https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG4ycQH4m6AKNrHUJ2W:-OG4ycQH4m6AKNrHUJ2X:b-tn3y0g>
> (raw file
> <https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift#L16>):*
>
> extension ChipViewModelProtocol {
>     func chipsToAdd(forContainerWidth containerWidth: CGFloat) -> (chips: [ChipModel], chipsWillOverflow: Bool) {
>
> nit: isOverflowing
> ------------------------------
>
> *ios/MullvadVPN/View
> controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift
> line 20 at r10
> <https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5AhCR9EYlTBIBHXfY:-OG5AhCR9EYlTBIBHXfZ:bx7ikyb>
> (raw file
> <https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift#L20>):*
>
>         var chipsWillOverflow = false
>
>         let moreTextWidth = "\(chips.count) more..."
>
> it should be localized.
> ------------------------------
>
> *ios/MullvadVPN/View
> controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift
> line 36 at r10
> <https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG58a_G27kjtdK0z_8E:-OG58a_G27kjtdK0z_8F:b-6xpc9h>
> (raw file
> <https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ChipView/ChipViewModelProtocol.swift#L36>):*
>
>             let chipWillFit = totalChipsWidth <= containerWidth
>
>             if chipWillFitWithMoreText {
>
> can we make it more simplifier :
>
> *Code snippet:*
>
>             guard (chipWillFit && isLastChip) || chipWillFitWithMoreText else {
>                 chipsWillOverflow = true
>                 break
>             }
>             chipsToAdd.append(chip)
>
> ------------------------------
>
> *ios/MullvadVPN/View
> controllers/Tunnel/FeatureIndicators/ConnectionView/HeaderView.swift line
> 48 at r10
> <https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5PcNRA-d9HS7xge75:-OG5PcNRA-d9HS7xge76:b-njih6h>
> (raw file
> <https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/Fe [...]

2025-01-09 10:12 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388)* status: 16 of 43 files reviewed, 13 unresolved discussions (waiting on @acb-mv and @mojganii)

___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ChipView/ChipFeature.swift` line 13 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG59YEGBytPOf2yp0ff:-OG9UbUr-zt4v5PIc8O6:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ChipView/ChipFeature.swift#L13)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

I suggest you to add comment here which describes the reason behind using `NSLocalizedString` instead of `LocalizedStringKey`.

as we discussed the reason why we are calculating the text size for chips then it matters to have localized value to compute the correct text width.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-09 10:56 UTC, mojganii approved these changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388)* status: 16 of 43 files reviewed, 7 unresolved discussions (waiting on @acb-mv and @rablador)

___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView/ButtonPanel.swift` line 70 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5EIse6RctkXIVyGzd:-OG9ch5E63VUupR3XsqO:bxl6q0t) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView/ButtonPanel.swift#L70)):*
<details><summary><i>Previously, rablador (Jon Petersson) wrote…</i></summary><blockquote>

I have thought about this some more. I think it's fine to keep the `LocalizedStringKey` that we have in the swiftUI code right now. Perhaps it could be a good way of testing it out. If you feel strongly about it I can "revert" to NSLocalizedString.
</blockquote></details>

No that's fine, after carful consideration I came to the conclusion it's better to take advantage of  new APIs as much as we can.


<!-- Sent from Reviewable.io -->

2025-01-09 11:02 UTC, rablador reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388)* status: 16 of 43 files reviewed, 7 unresolved discussions (waiting on @acb-mv and @mojganii)

___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView/ButtonPanel.swift` line 70 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG5EIse6RctkXIVyGzd:-OG9igyACMPYA2aeVWju:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/497bcd4a4f566885c87b401b4849b0cd610d2cf9/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/ConnectionView/ButtonPanel.swift#L70)):*
<details><summary><i>Previously, mojganii wrote…</i></summary><blockquote>

No that's fine, after carful consideration I came to the conclusion it's better to take advantage of  new APIs as much as we can.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-09 15:24 UTC, buggmagnet reviewed
It seems that the "X more ...." function does not work on iOS 16.7.0

> Reviewed 12 of 32 files at r1, 1 of 4 files at r2, 3 of 10 files at r6, 1 of 11 files at r7, 1 of 9 files at r8, 2 of 11 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-:-OGAecZy8-GMC4edtIUW:b-srsb1r)* status: 21 of 43 files reviewed, 8 unresolved discussions (waiting on @acb-mv, @mojganii, and @rablador)

___
*[`ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/FI_TunnelViewController.swift` line 94 at r11](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-OG9u89E42tqwb312Q7R:-OG9u89FAcjPPfF0eQHD:bqngwyp) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8f0b8126db6a27fa4b7559a8b0810aeb59204b47/ios/MullvadVPN/View%20controllers/Tunnel/FeatureIndicators/FI_TunnelViewController.swift#L94)):*
> ```Swift
>         }
> 
>         interactor.didGetOutGoingAddress = { [weak self] connectionInfo in
> ```

nit
`outgoing` is a single word, it should be `didGetOutgoingAddress`


<!-- Sent from Reviewable.io -->

2025-01-13 08:40 UTC, buggmagnet approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 32 files at r1, 1 of 4 files at r2, 1 of 5 files at r5, 1 of 11 files at r11, 15 of 19 files at r15, 1 of 1 files at r16, 6 of 6 files at r17.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7388#-:-OGToKOb76QXC5DBkZ-U:bnfp4nl)* status: 43 of 44 files reviewed, 7 unresolved discussions (waiting on @acb-mv and @mojganii)



<!-- Sent from Reviewable.io -->

2025-01-13 08:45 UTC, merged