Update changelog presentation
mullvad/mullvadvpn-app pull request #7394
Opened 2024-12-20 12:44 UTC by kl

2024-12-20 12:57 UTC, Pururun requested changes
> Reviewed 20 of 20 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394)* status: 19 of 21 files reviewed, 2 unresolved discussions (waiting on @kl)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationData.kt` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OEZ7sBl8yIbZjmYrOtZ:-OEZ7sBl8yIbZjmYrOt_:b5u5o5p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8750c27aba71902e2524b063b682ecb2fa914a7e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationData.kt#L42)):*
> ```Kotlin
>     ) : this(
>         AnnotatedString(title),
>         message?.let { NotificationMessage.Text(AnnotatedString(it)) },
> ```

This is just a general comment about clickable text, but any reason we did use an icon as for external links instead of the clickable text?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/NewChangelogNotificationUseCase.kt` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OEZ7L8385dv_bb6nrvE:-OEZ7L8385dv_bb6nrvF:b-7ibswn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8750c27aba71902e2524b063b682ecb2fa914a7e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/NewChangelogNotificationUseCase.kt#L18)):*
> ```Kotlin
>     operator fun invoke() =
>         combine(
>                 userPreferencesRepository.preferencesFlow,
> ```

Do we need to consider `ALWAYS\_SHOW\_CHANGELOG` or do we already do that in the repository? Maybe that property is not longer relevant?


<!-- Sent from Reviewable.io -->

2024-12-20 12:59 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394)* status: 19 of 21 files reviewed, 2 unresolved discussions (waiting on @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationData.kt` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OEZ7sBl8yIbZjmYrOtZ:-OEZ8Nig96GwYbx4C2Sp:bvxvdn) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8750c27aba71902e2524b063b682ecb2fa914a7e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationData.kt#L42)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This is just a general comment about clickable text, but any reason we did use an icon as for external links instead of the clickable text?
</blockquote></details>

We already have one clickable icon in that view (the X to close the notification), so maybe strange to have more?
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/NewChangelogNotificationUseCase.kt` line 18 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OEZ7L8385dv_bb6nrvE:-OEZ8c5s3GtbwLTqoO-2:bup4e65) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8750c27aba71902e2524b063b682ecb2fa914a7e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/NewChangelogNotificationUseCase.kt#L18)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

Do we need to consider `ALWAYS\_SHOW\_CHANGELOG` or do we already do that in the repository? Maybe that property is not longer relevant?
</blockquote></details>

Good question!


<!-- Sent from Reviewable.io -->

2024-12-20 14:02 UTC, albin-mullvad requested changes
> Reviewed 3 of 20 files at r1, 2 of 2 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394)* status: all files reviewed, 4 unresolved discussions (waiting on @kl and @Pururun)

___
*[`android/lib/resource/src/main/res/values/strings.xml` line 179 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OEZN0yQ0wGQRVMFVwqa:-OEZN0yQ0wGQRVMFVwqb:b-pcuu5r) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6c095d7a0fad486851eced85f03413b11dc1480d/android/lib/resource/src/main/res/values/strings.xml#L179)):*
> ```XML
>     </string>
>     <string name="new_changelog_notification_title">NEW VERSION INSTALLED</string>
>     <string name="new_changelog_notification_message">Click here to see what\'s new.</string>
> ```

See other comment regarding curly apostrophes



_Code quote:_
```XML
what\'s
```
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 392 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OEZMLFP0fibbT0LJNW2:-OEZMLFP0fibbT0LJNW3:b-ca7ef8) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6c095d7a0fad486851eced85f03413b11dc1480d/android/lib/resource/src/main/res/values/strings.xml#L392)):*
> ```XML
>     <string name="share">Share…</string>
>     <string name="app_info">App info</string>
>     <string name="changelog_title">What\'s new</string>
> ```

I believe this string is incorrect since we should only use curly apostrophes (`’`). We also shouldn't need the backslash.

For example see this previous issue: https://linear.app/mullvad/issue/DROID-1290



_Code quote:_
```XML
What\'s new
```


<!-- Sent from Reviewable.io -->

2024-12-20 14:16 UTC, Pururun requested changes
> Reviewed 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394)* status: all files reviewed, 3 unresolved discussions (waiting on @kl)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationData.kt` line 42 at r2](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OEZ7sBl8yIbZjmYrOtZ:-OEZOYFp4xFFd966T2Ft:buj6f8p) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8750c27aba71902e2524b063b682ecb2fa914a7e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationData.kt#L42)):*
<details><summary><i>Previously, kl (Kalle Lindström) wrote…</i></summary><blockquote>

We already have one clickable icon in that view (the X to close the notification), so maybe strange to have more?
</blockquote></details>

Right I did not considered the close button, in that case it is all good!
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/NewChangelogNotificationUseCase.kt` line 11 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OEZOjbF2zBZGYkBpVrQ:-OEZOjbGDvMEhL5-k-b3:bkljawf) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6c095d7a0fad486851eced85f03413b11dc1480d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/NewChangelogNotificationUseCase.kt#L11)):*
> ```Kotlin
> import net.mullvad.mullvadvpn.repository.UserPreferencesRepository
> 
> class NewChangelogNotificationUseCase(
> ```

This should considered if we actually have anything in the changelog. Should probably not notify if we have an empty changelog. 


<!-- Sent from Reviewable.io -->

2024-12-23 09:20 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394)* status: 18 of 25 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad, @kl, and @Pururun)

___
*[`android/lib/resource/src/main/res/values/strings.xml` line 179 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OEZN0yQ0wGQRVMFVwqa:-OEmoFT05e4EXJxuN4mM:b-9q1wng) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6c095d7a0fad486851eced85f03413b11dc1480d/android/lib/resource/src/main/res/values/strings.xml#L179)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

See other comment regarding curly apostrophes
</blockquote></details>

Fixed, but we need to notify desktop team since they use the wrong apostrophes on these strings.
___
*[`android/lib/resource/src/main/res/values/strings.xml` line 392 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OEZMLFP0fibbT0LJNW2:-OEmo8lo9mSaIolID0KX:b-9q1wng) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6c095d7a0fad486851eced85f03413b11dc1480d/android/lib/resource/src/main/res/values/strings.xml#L392)):*
<details><summary><i>Previously, albin-mullvad wrote…</i></summary><blockquote>

I believe this string is incorrect since we should only use curly apostrophes (`’`). We also shouldn't need the backslash.

For example see this previous issue: https://linear.app/mullvad/issue/DROID-1290
</blockquote></details>

Fixed, but we need to notify desktop team since they use the wrong apostrophes on these strings.


<!-- Sent from Reviewable.io -->

2024-12-23 09:37 UTC, Rawa reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394)* status: 18 of 25 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @Pururun)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/NewChangelogNotificationUseCase.kt` line 11 at r5](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OEZOjbF2zBZGYkBpVrQ:-OEmqxxQDOw8Bi3mFRWr:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/6c095d7a0fad486851eced85f03413b11dc1480d/android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/NewChangelogNotificationUseCase.kt#L11)):*
<details><summary><i>Previously, Pururun (Jonatan Rhodin) wrote…</i></summary><blockquote>

This should considered if we actually have anything in the changelog. Should probably not notify if we have an empty changelog.
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2025-01-08 08:27 UTC, Pururun approved these changes
> Reviewed 2 of 7 files at r6, 24 of 29 files at r8, 9 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)



<!-- Sent from Reviewable.io -->

2025-01-08 08:51 UTC, Rawa requested changes
> Reviewed 6 of 20 files at r1, 1 of 2 files at r4, 2 of 2 files at r5, 2 of 7 files at r6, 4 of 29 files at r8, 5 of 9 files at r9, 26 of 26 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394)* status: all files reviewed, 5 unresolved discussions (waiting on @albin-mullvad and @kl)

___
*[`android/app/src/main/proto/user_prefs.proto` line 8 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OG45cnkEe2XFUQe8Toy:-OG45cnkEe2XFUQe8Toz:bu4rqyg) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ef9492a3ac7ba91065f015de1e47755e2bae74e/android/app/src/main/proto/user_prefs.proto#L8)):*
> ```proto
> message UserPreferences {
>   bool is_privacy_disclosure_accepted = 1;
>   int32 version_code_for_latest_shown_changelog_notification = 2;
> ```

Maybe can be a bit simpler name
```last_shown_changelog_version_code```
or
```version_code_for_last_shown_changelog```
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AppInfoScreen.kt` line 106 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OG459z44745Z4Fq83vP:-OG459z44745Z4Fq83vQ:b-eucr47) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ef9492a3ac7ba91065f015de1e47755e2bae74e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AppInfoScreen.kt#L106)):*
> ```Kotlin
>     Column(modifier = Modifier.padding(bottom = Dimens.smallPadding).animateContentSize()) {
>         ChangelogRow(navigateToChangelog)
>         HorizontalDivider(color = Color.Transparent)
> ```

Why do we add a transparent Divider? :upside_down_face: 
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangelogScreen.kt` line 65 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OG45GqaEnZexas755_c:-OG45GqaEnZexas755_d:b-gf32s0) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ef9492a3ac7ba91065f015de1e47755e2bae74e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangelogScreen.kt#L65)):*
> ```Kotlin
>     ChangelogScreen(
>         uiState.value,
>         onBackClick = { navController.navigateUp() },
> ```

`navController::navigateUp`


<!-- Sent from Reviewable.io -->

2025-01-08 09:47 UTC, Rawa reviewed
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394)* status: all files reviewed, 3 unresolved discussions (waiting on @albin-mullvad and @kl)

___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AppInfoScreen.kt` line 106 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OG459z44745Z4Fq83vP:-OG4IrFS3etKeLc1A4jN:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ef9492a3ac7ba91065f015de1e47755e2bae74e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AppInfoScreen.kt#L106)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Why do we add a transparent Divider? :upside_down_face:
</blockquote></details>

Fixed
___
*[`android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangelogScreen.kt` line 65 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OG45GqaEnZexas755_c:-OG4J-0MDx0Q3Mm3KyCY:b-886gsx) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ef9492a3ac7ba91065f015de1e47755e2bae74e/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangelogScreen.kt#L65)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

`navController::navigateUp`
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2025-01-08 10:05 UTC, kl reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394)* status: 42 of 46 files reviewed, 3 unresolved discussions (waiting on @albin-mullvad, @Pururun, and @Rawa)

___
*[`android/app/src/main/proto/user_prefs.proto` line 8 at r10](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394#-OG45cnkEe2XFUQe8Toy:-OG4LMbW4MrnlkLzA576:b-896fix) ([raw file](https://github.com/mullvad/mullvadvpn-app/blob/8ef9492a3ac7ba91065f015de1e47755e2bae74e/android/app/src/main/proto/user_prefs.proto#L8)):*
<details><summary><i>Previously, Rawa (David Göransson) wrote…</i></summary><blockquote>

Maybe can be a bit simpler name
```last_shown_changelog_version_code```
or
```version_code_for_last_shown_changelog```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-08 14:49 UTC, Rawa submitted a review, later dismissed
> Reviewed 1 of 1 files at r12, 3 of 3 files at r13, 7 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394)* status: all files reviewed, 2 unresolved discussions (waiting on @albin-mullvad)



<!-- Sent from Reviewable.io -->

2025-01-09 08:34 UTC, olmoh approved these changes
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-09 09:27 UTC, albin-mullvad approved these changes
> Reviewed 1 of 7 files at r14, 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7394)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-09 09:56 UTC, merged